### ISSUE TITLE
Problem MACD 'Period signal' 9 not take change effect !!

### ISSUE THREAD

**Issue by bouhali00** [binary-com/binary-bot#1000]
@binary-ex-machina
Hello,
When i change de value for input MACD 'Period signal' : 9 to 5, I find the signal Histogram it is the same effect as value 9 !!

There is another parametres to add ??
![macd](https://user-images.githubusercontent.com/44878529/49114247-a5c20080-f28f-11e8-8606-c1a9a85cf8bf.jpg)

**Comment by binary-ex-machina** [comment]
when you put same effect, you mean that the block outputs a same value? i don't think it's possible. Now if you are talking about the win rate, then is not a problem of the indicator but of the strategy itself

**Comment by bouhali00** [comment]
@binary-ex-machina 
In the shart with 2 indicators MACD 12 26 9 and MACD 12 26 5 They are different : Its ok, But In the bot they are not different , they are the same value for histogram, that mean the MACD take always the value 9 , even if we change the value !!!

**Comment by binary-ex-machina** [comment]
well in this case this could be a bug

@gokula-krishna-dev, it's possible to check that?
