### ISSUE TITLE
under 4

### ISSUE THREAD

**Issue by sinung21** [binary-com/binary-bot#1010]
bot menu under: if there are digits 4 and 5 he does martiangle. if he's out of number 1/2/3/6/7/8/9 he doesn't do martiangle

**Comment by Eshhh** [comment]
[Under4 Martingale@LastDigit4or5.zip](https://github.com/binary-com/binary-bot/files/2643509/Under4.Martingale.LastDigit4or5.zip)

**Comment by sinung21** [comment]
THANKS @Eshhh
