### ISSUE TITLE
How to change the initial amount 

### ISSUE THREAD

**Issue by ziyadiok** [binary-com/binary-bot#1012]
i want if the last digit of the exit spot is = 5
the initial amount will change to  0.8

![image](https://user-images.githubusercontent.com/45568371/49404158-39f50180-f781-11e8-8df4-69bdeca99278.png)

**Comment by brklght** [comment]
![image](https://user-images.githubusercontent.com/43042301/49408305-52b7e400-f78e-11e8-8c54-6fc8aebc868a.png)

use this block
