### ISSUE TITLE
ANALYSIS LOCK POINT

### ISSUE THREAD

**Issue by sinung21** [binary-com/binary-bot#1019]
I HAVE RULE MANUAL VOL10  5TICK  IF FIRTS  POINT IS  +0.300  
IF SECOND POINT IS +0.300
IF THIRD POINT IS  +0.300 RIGHT NOW TO OPEN RISE

IF FIRST POINT IS -0.300
SECOND POINT IS -0.300
THIRD POINT IS -0.300 OPEN FALL
CAN ANYONE HELP ME TO BUILD THIS RULE?

**Comment by sinung21** [comment]
yer right like that @binary-ex-machina

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/49649178-89e8f800-fa0f-11e8-9e69-b4676fdf8f90.png)

**Comment by sinung21** [comment]
ok thanks a lot @binary-ex-machina
