### ISSUE TITLE
i have problems with my bot

### ISSUE THREAD

**Issue by romeo1911** [binary-com/binary-bot#1020]
![bho](https://user-images.githubusercontent.com/44220114/49570629-c5c98200-f969-11e8-8ed1-a9d2c20f195a.jpg)
 hi, i have some problems that i cannot fix by my self.
i use digits, inside the configuration, in the beginning set "prediction" to init and init to 0.
After make some calculations( take ~ 30 sec) , i have the variable "predic" with a number, after i set init to "predic" and after i buy. 
Even if my variable "predic" have number 8 ( for example) and init is 8, the first buy is everytime 0.
i notice that everytime he change the number he not make it directly but skip 1 turn, as in the picture, before was 8 after change to 4 , he continue with 8 for 1 turn.
any suggestion how to fix it?
p.s. what is the message in corner right down? never came out before
-- sorry for my english --

**Comment by binary-ex-machina** [comment]
post the file here, it will be better to help. If you set the prediction to 0 and then you change it without finish the actual contract (trade) it will use 0. Only in the next trade it will use the prediction you've set during the trade.

**Comment by romeo1911** [comment]
[buono oltre 10240.xml.zip](https://github.com/binary-com/binary-bot/files/2656505/buono.oltre.10240.xml.zip)
u mean that if i set to 0 and after "i change idea" and i want to buy 9 (before buy the contract), i have to buy 0 no matter what?
ps. what change between volatility 10 and 100?
thanks for your time

**Comment by binary-ex-machina** [comment]
@romeo1911 you need to set the prediction in the first block (1), after it passes this block, you can't change until the block (4), before you start the loop again. V10 and V100 are different markets, different numbers.

**Comment by romeo1911** [comment]
ok, thanks 4 explanation
