### ISSUE TITLE
Indicator Hull MA dont Cross Up !

### ISSUE THREAD

**Issue by bouhali00** [binary-com/binary-bot#1021]
@binary-ex-machina

Hello,
I have a message error for my bot "Undefined is not function''
How i can do ?

![hull ma](https://user-images.githubusercontent.com/44878529/49610014-30dc7e00-f995-11e8-92c3-d3c557df5584.jpg)

**Comment by binary-ex-machina** [comment]
You can see that you are using get on my indicador HullMA. The indicator block return a number, not a list. Using get only makes sense on lists or arrays.

**Comment by bouhali00** [comment]
@binary-ex-machina
I also try with the block: "GethullMAArray" but it crashes the pc. did i have a bad editing ?? thank you for helping.
