### ISSUE TITLE
Take part in developing the strategy tester

### ISSUE THREAD

**Issue by TheShaltys** [binary-com/binary-bot#1027]
Hi, one day I've had an idea if there is a strategy tester in MT4, why it won't be possible in blocks. I have already try to make a One Touch Tester, but it didn't work for me.
The tester means that you insert there any conditions (for trade) and from a specific part of time (n# of candles from the end) and it'll test the condition for each candle in that part of time and at the end it will tell you num of trades + results (win/lose).
Is somebody here willing to build it?

**Comment by eonuoha30** [comment]
@aaron-binary 

Was there any update on this issue?

Such feature would really be of great help

**Comment by anton-binary** [comment]
Hi @eonuoha30,

It's a part of our roadmap for new generation of Binary Bot platform. Check it out https://deriv.app/bot. Will start working on shortly.

`Deriv`(https://www.deriv.com) is new brand of Binary.com.  

Thanks,
Anton
