### ISSUE TITLE
how  to view value variable ?

### ISSUE THREAD

**Issue by adiwirak** [binary-com/binary-bot#1031]
sometimes when the bot is running, there is a bug so that there is an OpenTime value that becomes invalid (the value is fixed / Not up to date).
finally my flow program doesn't work properly.

![gmbr1](https://user-images.githubusercontent.com/45034301/49873993-d8532800-fe4f-11e8-83f7-95c13eea3716.png)

Well, when it happens, can I do console.log on the web inspection console, so I can see the variable "now"?

and why is that value stuck? Is it because the bot runs too long in the browser? or something

**Comment by aaron-binary** [comment]
Hey adiwirak, you can check the value of your variable using either the **print**-block, or the **notify**-block, we currently do not support logging to the web browser's console.

As for the value being stuck, could you upload your .xml file? I'll have a look and see what's up.

Regards,
Aaron

**Comment by adiwirak** [comment]
> Hey adiwirak, you can check the value of your variable using either the **print**-block, or the **notify**-block, we currently do not support logging to the web browser's console.
> 
>     * The **print**-block can be found under **Text** -> **print** (this will print the variable to the log panel, click on the log icon ![screenshot 2018-12-13 at 9 21 01 am](https://user-images.githubusercontent.com/44427668/49909110-7549ab80-feb8-11e8-86e9-625aad387f3d.png) to open.
> 
>     * The **notify**-block can be found under **Binary** -> **Tools** -> **Misc.** -> **notify**

i know with your mean, to make print a string/text. I think this method is less effective. because this incident happened at any time. Not logic error. There are even events, there is a transaction that does not get results, whether it be, win or loss. Strange...???

> 
> 
> As for the value being stuck, could you upload your .xml file? I'll have a look and see what's up.
> 
> Regards,
> Aaron

this, I give my code snippet.
![gambar](https://user-images.githubusercontent.com/45034301/49909837-061d8880-feb3-11e8-9dbd-9363132f1c10.png)

Please note, that the WktCdl variable, I set it at the beginning of the define contract session.
So logically, every minute, the program will once enter the "if" block.

Is it possible, this happened because I use VPS Europe with Win 7? so that sometimes the bot doesn't get a response back, finally some functions produce a stuck value.

**Comment by adiwirak** [comment]
Oh yeach, can the bot read/write the local file ?

**Comment by baruga** [comment]
@aaron-binary @adiwirak Pls????

**Comment by adiwirak** [comment]
> 
> 
> Hey adiwirak,
> 
> > Oh yeach, can the bot read/write the local file ?
> 
> We do not support reading or writing to local files at this time.
> 
> Could you share your .xml file? If you don't want to post it publicly you can send it over to [aaron@binary.com](mailto:aaron@binary.com) and I'll try to identify why the value is stuck.
> 
> Regards,
> Aaron

I have sent an email to you. Check it?

**Comment by baruga** [comment]
@adiwirak Can You sent to my email to pls ppaybiz@gmail.com tanks

**Comment by murali139** [comment]
@baruga Sir, if you don't mine, please tell a good manual strategy for us.
hear all bots are good but when it runs- trade timing missed.
Sir, please give a chance for good improvement.

**Comment by adiwirak** [comment]
@aaron-binary , @baruga , sorry for making you curious ;)

Ok. We focus first on this 
![gambar](https://user-images.githubusercontent.com/45034301/50005300-82f85180-ffdc-11e8-9675-68ca6764e537.png)
Here, we make the bot make a list of candles per 2 minutes. Is it right ?

now, focus and imagine, if the code below is run / play.
![gambar](https://user-images.githubusercontent.com/45034301/50005393-ceaafb00-ffdc-11e8-904d-5ad9b48d581e.png)
my question is, is it possible that the "TickKe" value can reach 500 and above?

if in my logic, it shouldn't happen. because in 1 minute, the number of ticks is at most 30. Is that right?
Because when there is a change in the OpenTime value, the "TickKe" variable is reset to zero (0).

Now, if  the "TickKe" value can reach 500 and above, So where is the bug?

**Comment by baruga** [comment]
@adiwirak so sorry friends, saya hanya melihate sampeyan maka saya gunakan bahasa gado gado

**Comment by adiwirak** [comment]
is there an answer to my problem? Mr. @aaron-binary , @baruga , etc
or we agree that the bug of this problem is a network problem, not from a code or logic error?

If you agree, I will close this thread.

Because this problem happened again yesterday. Yesterday, I ran this code from 8am to 21pm, and the results were OK. But when at 22pm, the bot becomes an error. Because the value of OpenTime does not increase or stuck.
