### ISSUE TITLE
www.binary.bot is not responding

### ISSUE THREAD

**Issue by arguswing** [binary-com/binary-bot#1035]
Please assist me on this.
I am newbie on your website. And your www.binary.bot is not working after long loading.

![29a0623521894123b584fd479bef8084](https://user-images.githubusercontent.com/45914600/50053000-57a26d80-0168-11e9-9018-711ee2455cdc.png)

![binary-bot-not-working](https://user-images.githubusercontent.com/45914600/50053117-2dea4600-016a-11e9-9e59-bcb58969c109.png)

Regards,
Augustine
singpeck@gmail.com

**Comment by aaron-binary** [comment]
Hey arguswing, thank you for reporting this issue. Are you still experiencing this? If so, could you let us know where you are connecting from (i.e. country)?

Regards,
Aaron

**Comment by arguswing** [comment]
Dear Aaron,

Thank you for your response.

I am still experience this issue.

And I am connecting from Singapore.

Regards,

Augustine

**Comment by romeo1911** [comment]
that is the problem, i was in singapore too and i have same problem, use vpn and try connect from usa

**Comment by romeo1911** [comment]
@aaron-binary i'm in indonesia and i use vpn, personally happends if i login, i tried with firefox chromium, tor, open vpn ( from binary) all the same story, cames an error ( sometime i can read it sometimes is just a flash) "error:not licensed for domain https://www.binary.bot/bot.html" and parts of the site cannot load. 
after i disconnect vpn from singapore and i connect to USA , the error remain but all is working.
btw i open an issie with the pics
