### ISSUE TITLE
Can the BOT hit a URL as alarm?

### ISSUE THREAD

**Issue by adiwirak** [binary-com/binary-bot#1059]
Can the BOT hit a URL as alarm?
I want make bot, when the bot reaches a critical level, it will hit a certain url. Can this be made?

**Comment by aaron-binary** [comment]
Hey adiwirak, 

We currently do not support this, but I think it's a great idea, I'll dicuss it with the team.

Regards,
Aaron

**Comment by adiwirak** [comment]
> 
> 
> Hey adiwirak,
> 
> We currently do not support this, but I think it's a great idea, I'll dicuss it with the team.
> 
> Regards,
> Aaron

Ow...means you are a person binary.com. OK let me know, if that feature exists.
