### ISSUE TITLE
ultimo digito

### ISSUE THREAD

**Issue by william7843** [binary-com/binary-bot#1077]
hola a todos!!
soy nuevo en este mundo de bots, me podrian colaborar con un bot que evalué el ultimo digito y si es 7 o 9 haga la transaccion con impar (ODD), y si pierde martin gala...
muchas gracias por su colaborador

**Comment by xremmy** [comment]
[William7843.zip](https://github.com/binary-com/binary-bot/files/2729334/William7843.zip)

**Comment by william7843** [comment]
Muchas Gracias!!

**Comment by Omar2227** [comment]
buenas tardes... alguien me podría hacer el favor de decirme como se configuran las señales en estos % en under y over... 62% amarrillo - 68% azul de forma ascendente operar al under y 60% amarillo 48% azul de forma desendente operar al over.

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: Omar2227 <notifications@github.com>
Enviado: quinta-feira, 25 de junho de 2020 17:30
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] ultimo digito (#1077)


buenas tardes... alguien me podría hacer el favor de decirme como se configuran las señales en estos % en under y over... 62% amarrillo - 68% azul de forma ascendente operar al under y 60% amarillo 48% azul de forma desendente operar al over.
