### ISSUE TITLE
digital bot . please build this to martingale. thanks

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1086]
please create this martingale system thanks
digital bot
[digital bot.zip](https://github.com/binary-com/binary-bot/files/2731603/digital.bot.zip)

**Comment by sinung21** [comment]
[digital bot 2A.zip](https://github.com/binary-com/binary-bot/files/2732517/digital.bot.2A.zip)

**Comment by dushanu** [comment]
thank you very much friend...........
