### ISSUE TITLE
Issue "Unknown contract proposal"

### ISSUE THREAD

**Issue by TonyFromMontana** [binary-com/binary-bot#1092]
Hello there! My bot is working technically, but i recieved some strange issue. I run the bot on several quotes and had 2 contracts on my strategy today. 1st contact worked correctly. At the time of 2nd one the bot showed me an error and its working status was strange. As i see, parametrs of the bots are equal. The difference is only in working quote. Could the problem be in connection/platform, or my bot is something broken? How to fix the unsure stop of my bot   (As you see, my bot "has stoped", but is shows a rectangle like it is worhing) ?
![joxi_screenshot_1546938425367](https://user-images.githubusercontent.com/46303560/50822068-d2af0c00-1341-11e9-96d2-a55ea3759817.png)

**Comment by binary-ex-machina** [comment]
i encountered this some times and is probably due to the connection with binary.com servers. They might my restarting or other similar issues.

You can let these 2 options selected on the first block to avoid that

![image](https://user-images.githubusercontent.com/34610787/50864743-21809400-138a-11e9-8878-2e48cc5c9d63.png)

**Comment by TonyFromMontana** [comment]
> i encountered this some times and is probably due to the connection with binary.com servers. They might my restarting or other similar issues.
> 
> You can let these 2 options selected on the first block to avoid that
> 
> ![image](https://user-images.githubusercontent.com/34610787/50864743-21809400-138a-11e9-8878-2e48cc5c9d63.png)



> i encountered this some times and is probably due to the connection with binary.com servers. They might my restarting or other similar issues.
> 
> You can let these 2 options selected on the first block to avoid that
> 
> ![image](https://user-images.githubusercontent.com/34610787/50864743-21809400-138a-11e9-8878-2e48cc5c9d63.png)

Ok, Thank you very much. I'll try that.
