### ISSUE TITLE
Buy contract at specific price

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [binary-com/binary-bot#1124]
How can I buy a contract automatically at a specific price (above, under or at)??

**Comment by streetyuk** [comment]
lower price set, if last tick <or= to (set number) do buy. vise versa  for a higher price set,  like if last tick >or= 3000 do buy raise or fall. last tick = current value, u will find it under tick analysis

**Comment by SatoshiNakamotoBitcoins** [comment]
@streetyuk Thank you for your reply!
