### ISSUE TITLE
About Decimal Point

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1129]
How to set decimal points with just last two digit,
Example : If after a calculation get a value with " 11796.36324582 ", so how can get value as " 11796.36 "

**Comment by baruga** [comment]
@navneetsinh  You can set with around in matematic

**Comment by navneetsinh** [comment]
@baruga thanks for reverting, but how to do this, if applying round function it rounded with 11796, and I require 11796.36 !!! so how ??? to clear it ?????

**Comment by baruga** [comment]
@navneetsinh 

Like this friend

![anunya](https://user-images.githubusercontent.com/24489532/51667783-afe84d00-1ffb-11e9-8af7-9bfc7fbc94df.jpg)

**Comment by navneetsinh** [comment]
![opera snapshot_2019-01-24_152835_bot binary com](https://user-images.githubusercontent.com/42480287/51670578-f71b1180-1fec-11e9-9bc8-29389a29b4c8.png)

here is result you can see last tick is 880.823 and anu is 880823, and I required 880.23

**Comment by baruga** [comment]
@navneetsinh  U can share to this forum or my person email??? I need your strategy and i help u what u want it

**Comment by navneetsinh** [comment]
hi @baruga ,
I got the same as your suggestion just one block not added.
thanks for helping,
![opera snapshot_2019-01-25_051724_bot binary com](https://user-images.githubusercontent.com/42480287/51715953-d7bdcc00-2060-11e9-8399-d5ca3541116e.png)

**Comment by navneetsinh** [comment]
hi, @baruga 
it's good and thanks for supporting, but your first way is better for the last, because it gives some error in numeric display,
please see, I attached images,
![opera snapshot_2019-01-25_050159_bot binary com](https://user-images.githubusercontent.com/42480287/51730093-36546b80-209c-11e9-9fa2-c309f2671053.png)
![opera snapshot_2019-01-25_122134_bot binary com](https://user-images.githubusercontent.com/42480287/51730107-40766a00-209c-11e9-977e-119c03cc900f.png)

**Comment by baruga** [comment]
@navneetsinh You set up it, you already understand.

**Comment by navneetsinh** [comment]
@baruga oh yes, thanking you....

**Comment by kjsanjeewa** [comment]
> [BOT EVEN.zip](https://github.com/binary-com/binary-bot/files/4645617/BOT.EVEN.zip)

Set the Last Digit Prediction 0 and Price Bar count the  - - - - -.0  -   then Open Purchase Digit Differs Order with the this same setting.

automatically change LDP and open trade with the  ----.0- this no. 
Ex. LDP 0   price bar ----.0-   open differ
LDP 1   price bar ----.1-  open differ
LDP 2   price bar ----.2-  open differ
LDP 3   price bar ----.3-  open differ
LDP 4   price bar ----.4-  open differ
LDP 5   price bar ----.5-  open differ
LDP 6   price bar ----.6-  open differ
LDP 7   price bar ----.7-  open differ
LDP 8   price bar ----.8-  open differ
LDP 9   price bar ----.9-  open differ

Stake 1.1
Martingle add the 11
Take Profit, Stop Loss
![Screenshot 2020-11-27 21 10 17 - Copy](https://user-images.githubusercontent.com/74783297/100886864-52b46100-34da-11eb-8637-8985fe782db8.png)

**Comment by kjsanjeewa** [comment]
> ![opera snapshot_2019-01-24_152835_bot binary com](https://user-images.githubusercontent.com/42480287/51670578-f71b1180-1fec-11e9-9bc8-29389a29b4c8.png)
> 
> here is result you can see last tick is 880.823 and anu is 880823, and I required 880.23

> [BOT EVEN.zip](https://github.com/binary-com/binary-bot/files/4645617/BOT.EVEN.zip)

Set the Last Digit Prediction 0 and Price Bar count the  - - - - -.0  -   then Open Purchase Digit Differs Order with the this same setting.

automatically change LDP and open trade with the  ----.0- this no. 
Ex. LDP 0   price bar ----.0-   open differ
LDP 1   price bar ----.1-  open differ
LDP 2   price bar ----.2-  open differ
LDP 3   price bar ----.3-  open differ
LDP 4   price bar ----.4-  open differ
LDP 5   price bar ----.5-  open differ
LDP 6   price bar ----.6-  open differ
LDP 7   price bar ----.7-  open differ
LDP 8   price bar ----.8-  open differ
LDP 9   price bar ----.9-  open differ

Stake 1.1
Martingle add the 11
Take Profit, Stop Loss
![Screenshot 2020-11-27 21 10 17 - Copy](https://user-images.githubusercontent.com/74783297/100886864-52b46100-34da-11eb-8637-8985fe782db8.png)
