### ISSUE TITLE
Prediciton in Bots, still not working?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1133]
Is Prediciton in Bots, still not working? Mine still will not load..

**Comment by aaron-binary** [comment]
Hey @buckman1974 

You are correct, the **prediction**-block (and also **barrier offset**-blocks) are still not imported properly. We're working on a couple more changes before we update Binary Bot.

We're looking to release this and some other fixes in 1-2 days from now.

Regards,
Aaron
