### ISSUE TITLE
Bug::notify box bottom left >> show wrong location show in comment 

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1134]
Bug::notify box bottom left , show wrong location show in comment. try in firefox, opera, chrom same
step to duplicate problem.
login to bot.binary.com then load any existing  block with comment and run.
[binary-bot.txt](https://github.com/binary-com/binary-bot/files/2793112/binary-bot.txt)
![image](https://user-images.githubusercontent.com/31925501/51701339-375dac80-204c-11e9-8287-988db378cab3.png)

if create new no problem

**Comment by aaron-binary** [comment]
Hey @nextnaro 

Thank you for reporting this issue, I'll look into it and will issue a fix in the future.

Regards,
Aaron

**Comment by baruga** [comment]
@nextnaro iku ora bug masbro

**Comment by nextnaro** [comment]
It just happened when pinned comment.
