### ISSUE TITLE
digitos consecutivos

### ISSUE THREAD

**Issue by william7843** [binary-com/binary-bot#1136]
Hola, si me pueden ayudar se los agradezco, necesito programar un bot que al salir el 0-7-8 en COLOR AZUL consecutivos compre RISE y salga un mensaje "DIRECCION UP", y si sale 0-7-8 en COLOR ROJO consecutivos compre FALL, Y SALGA UN MENSAJE "DIRECCION DOWN" sin martingala, con interes compuesto 3 veces.
muchisimas gracias

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/52166512-59fb5f80-26f5-11e9-9f5c-3de92bf6ee85.png)

**Comment by william7843** [comment]
Muchas gracias lo ensayaremos

**Comment by pao11901** [comment]
please xml, please!!!

**Comment by william7843** [comment]
binary-ex-machina, porfa me puedes colaborar con el archivo del bot, no he podido lograr que funcione, soy novato y esto de programar me dificulta
muchas gracias amigo

**Comment by william7843** [comment]
mira como lo hice, pero no hace la compra, cual sera mi error
porfa
muchas gracias

[bot digitos.txt](https://github.com/binary-com/binary-bot/files/2828746/bot.digitos.txt)

**Comment by davidperci** [comment]
Te lo modifique ... probalo
Renombra el archivo a .xml
[DigitosConsecutivos.txt](https://github.com/binary-com/binary-bot/files/6052840/DigitosConsecutivos.txt)
