### ISSUE TITLE
Bug: Chart not recognising market

### ISSUE THREAD

**Issue by Baselope** [binary-com/binary-bot#1138]
My bot is trading R75, yet when I click on "Open chart", I get the R100 chart.
![image](https://user-images.githubusercontent.com/36667093/51797632-b3ecb880-220f-11e9-802d-4293b5dba1f9.png)
Any ideas?

**Comment by Baselope** [comment]
It happens when loading the bot into the client - the chart view is not updated according to the market specified in the bot. Reproduced several times.
[- - bug test.zip](https://github.com/binary-com/binary-bot/files/2799828/-.-.bug.test.zip)

**Comment by aaron-binary** [comment]
Hey @Baselope 

Thank you for reporting this issue, we're aware of this and will release a fix as soon as possible. For now I recommend using TradingView's chart, which you can open by pressing the icon below:

> ![screenshot 2019-01-28 at 9 04 46 am](https://user-images.githubusercontent.com/44427668/51809423-ce8c6380-22db-11e9-8e94-b221bc16b365.png)

Regards,
Aaron

**Comment by aaron-binary** [comment]
Fixed in #1178
