### ISSUE TITLE
Bug on importing collection

### ISSUE THREAD

**Issue by binary-ex-machina** [binary-com/binary-bot#1146]
I clicked on the download option of this block and when i tried to upload, it says that the strategy is not valid. The same occur with all collections that it was working before.

Here is the file i'm trying to import. You can try to download any block and import, the same error will appear.
[report.xml.zip](https://github.com/binary-com/binary-bot/files/2807699/report.xml.zip)

**Comment by buckman1974** [comment]
@binary-ex-machina  - I can't get your bot to load at all? (if this helps?)

**Comment by binary-ex-machina** [comment]
@buckman1974 yeah, all my indicators and bots have some issues now, i'll wait for their reply.

**Comment by shonOXO** [comment]
yeah i cant import anything from ur collection ! @binary-ex-machina

**Comment by aaron-binary** [comment]
Hey @binary-ex-machina @buckman1974 @shonOXO 

I'm looking into this issue right away and will update this issue asap.

Regards,
Aaron
