### ISSUE TITLE
Help creating a good differ bot!

### ISSUE THREAD

**Issue by pieterbrandsen** [binary-com/binary-bot#1148]
Hello,

I think we can now make a super good differ bot because the new 1 tick gives us a better change to get it right!

My bot idea is:
if Number appears 3 times in a row (can be less, can be more) differ that number. so high probability, low risk and maybe now martingrale becuase it could still go wrong 2 times in a row and we dont want a x11 martingrale.

**Comment by mexarrinha** [comment]
Hey
I was using martingale on differs, but if i lost one time, then put the trade amount to 1 for 5 times, then back to 0.35 again. 
Do you know how can i get the last 25 digits? 
Thanks

**Comment by pieterbrandsen** [comment]
https://github.com/binary-com/binary-bot/issues/223

**Comment by mexarrinha** [comment]
hey @pieterbrandsen  i'm trying to do the same, but that way of setting thick one to thick two and so on, has a problem... it's never correct with the previous thicks. When you start the bot first you need to get the last 25 thicks, then assign them to the right num(num0,num1....) and only then you start shifting all thicks and it will be correct with the website.
I tried looping a few times but it broke down and lost everything xD
