### ISSUE TITLE
Close repeated candles.

### ISSUE THREAD

**Issue by janith119** [binary-com/binary-bot#115]
Hi Amin.

Thanks for your last reply.
i want to know the code blocks to do these points
 1) I want to execute trades with the open of a new candle each time.
           
![new candle](https://cloud.githubusercontent.com/assets/24697795/21561408/4a7f7112-ce92-11e6-91e6-aab0f0656e43.PNG)
    
    (as soon as the candle opens i want to make the trade)

2) If the green and red candles appear **one after another** and they continue 5 times , then i want to 
    quit the trade and ,wait for the two candles on same direction and then start from beginning with the  bot.
![wait](https://cloud.githubusercontent.com/assets/24697795/21561756/ef49f95c-ce96-11e6-8d09-13bca2721949.PNG)

**Comment by aminmarashi** [comment]
I hope [this](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/is%2520stripes%2520pattern.xml) is what you wanted.

**Comment by janith119** [comment]
Thanks for the help Amin, that's what i wanted.And please let me do a suggestion that you could do a tutorial series in YouTube or anywhere you like which help us to make powerful bots.Thanks

**Comment by aminmarashi** [comment]
Thanks for the suggestion, we're working on it 👍

**Comment by wilsonsiena** [comment]
What is the best market?
