### ISSUE TITLE
Add a strategy that has been saved before 

### ISSUE THREAD

**Issue by baruga** [binary-com/binary-bot#1153]
@aaron-binary 

Why is the help of the information now if you add a strategy that has been saved before it can't ... Is there really a limitation on binary bots at this time

![tdk bisa menambah](https://user-images.githubusercontent.com/24489532/51970264-698a6680-24b1-11e9-9aba-e3c38092b256.jpg)

**Comment by aaron-binary** [comment]
Hey @baruga,

We're aware of this issue and will release a fix soon. Please check out #1146 for more information, and how to continue trading.

Regards,
Aaron
