### ISSUE TITLE
webpage does not respond

### ISSUE THREAD

**Issue by lasaidhari** [binary-com/binary-bot#1155]
![bot](https://user-images.githubusercontent.com/34808023/51977250-8165e880-24b9-11e9-848e-9b66753e69ca.jpg)
webpage does not respond

**Comment by aaron-binary** [comment]
Hey @lasaidhari,

We're aware of the issues regarding the Binary Bot website and are working on fixing them. We apologise for the inconvenience this has caused you.

Regards,
Aaron
