### ISSUE TITLE
Account balance going down but not rising!!

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1175]
I was using the manual Webtrader yesterday, and I was using tick trades and winning trades but the account total figure wasn’t updating!

My account was being deducted with trades I was making fine, but my wins didn’t show?!!

Luckily I was on Virtual account, but please check and see if this is a bug?
Thanks

**Comment by pieterbrandsen** [comment]
Strange!

**Comment by aaron-binary** [comment]
Hey @buckman1974,

Thanks for reporting this issue, I've forwarded it to the Webtrader department. 

_Please note that this Github issues page is only for Binary Bot._

Regards,
Aaron

**Comment by buckman1974** [comment]
Thank you @aaron-binary 

Can I ask if there is another GitHub for the Webtrader issues only that I have missed?

Thanks
