### ISSUE TITLE
server time delayed increasing more and more  

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1176]
start bot on 19 Jan , page never refresh. server time delayed increasing look at captured.
![image](https://user-images.githubusercontent.com/31925501/52224412-f0d93f00-28e2-11e9-94fe-a667a12ffc70.png)

**Comment by aaron-binary** [comment]
Hey @nextnaro,
 
Thank you for reporting this issue.

I've had a quick look and it seems that we only synchronise the time with our server at the start of a session, over longer periods of time this may cause inaccuracies being displayed in the topbar. 

Rest assured that the times displayed in the summary panel are correctly displayed, as those times are returned by our servers.

We will work on synchronising the time with the server in regular intervals.

Regards,
Aaron
