### ISSUE TITLE
Fast rising/down

### ISSUE THREAD

**Issue by pieterbrandsen** [binary-com/binary-bot#1179]
Is it posible to create a bot that looks for fast rising/downs and then go with the direction?

**Comment by binary-ex-machina** [comment]
it's possible, but what you wrote is too subjective. Define specifically with number: Fast, Rising and Downs.

**Comment by pieterbrandsen** [comment]
I mean like if vol100 normally goes 1 to 2 numbers down and up per tick (down know if this real) and then sometimes goes 4 numbers up, you buy or sell (direction), so you can maybe can get the spikes!

**Comment by binary-ex-machina** [comment]
the chart works like the sparkle line below:

![image](https://user-images.githubusercontent.com/34610787/52342177-d0e96e80-29fb-11e9-9d71-0bae3f7c14d6.png)

You can't go up or down multiple times in one tick. Each tick will go in one direction.

**Comment by pieterbrandsen** [comment]
didnt meaned one tick but multiplie but figured it out!
