### ISSUE TITLE
Non-stop work "Before Purchase"

### ISSUE THREAD

**Issue by LinkSayrus** [binary-com/binary-bot#1182]
Is there a way to make the work of the module Before Purchase every tick, even if the contract is open?
This is necessary in order to launch new contracts while others are being executed.

**Comment by LinkSayrus** [comment]
I basically can not buy a multiple contracts?
In the future, this opportunity will be?

**Comment by binary-ex-machina** [comment]
its very unlikely this will be available.

**Comment by LinkSayrus** [comment]
Can I run a bot, buy a contract, write data to a variable, run a second bot, read the data from the variable of the first bot?

**Comment by binary-ex-machina** [comment]
@LinkSayrus no, you can't communicate between tabs using the bot page

**Comment by LinkSayrus** [comment]
Maybe stupid idea, but maybe:
Can I run the bot in console mode on my server?
Connect it to my account on binar.com. Send it the logic in XML format? And already inside my server to manipulate variables?

**Comment by LinkSayrus** [comment]
And for clarification. With functions, can I buy a new contract when the previous contract has not expired?

**Comment by binary-ex-machina** [comment]
@LinkSayrus you can use binary Live API to place trades, as many trades as you want. 

Using functions or not, you can't interfere in the trading flow with the blocks.

**Comment by LinkSayrus** [comment]
Ok. Thank you for answer.
