### ISSUE TITLE
some error in notification and duration

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1197]
here is some errors in duration and notification
in touch bot when load or clean up blocks always duration minutes change in ticks
and notification displays in comment section example in image
![opera snapshot_2019-02-10_125704_bot binary com](https://user-images.githubusercontent.com/42480287/52531096-255f5780-2d36-11e9-935e-7ba902accd14.png)
[touch.xml.txt](https://github.com/binary-com/binary-bot/files/2848632/touch.xml.txt)

**Comment by aaron-binary** [comment]
Hey @navneetsinh,

We're aware of the notification display issue (this was previously reported in #1134) and we're working on fixing this issue in the near future. 

As for your other issue, I've confirmed that this is happening. We'll investigate and patch it when we find the cause of this.

Regards,
Aaron
