### ISSUE TITLE
After last tick update bot stops working after some hours

### ISSUE THREAD

**Issue by daviqq** [binary-com/binary-bot#1207]
Before the update I used to leave my bot running 24/7 but after last update the bot stops after some hours running.

**Comment by aaron-binary** [comment]
Hey @daviqq,

Would you be able to share your strategy with us? This will allow us to test it and see where it might go wrong. Other reasons for the random stops might have to do with the connection between your computer and the Binary.com servers.

I look forward to hearing from you.

Regards,
Aaron
