### ISSUE TITLE
DEFINE TREADE OPTION NOW

### ISSUE THREAD

**Issue by baruga** [binary-com/binary-bot#1216]
@aaron-binary  Why define trade options now after an update cannot be made for a plus and minus barrier.
Please why???

![opera snapshot_2019-02-13_152227_binary bot](https://user-images.githubusercontent.com/24489532/52694140-b7b86300-2fa3-11e9-8212-d8bc245445b1.png)

**Comment by aaron-binary** [comment]
Hey @baruga,

We're aware of this issue and one of our developers (@cakasuma) is working on it as we speak. 

I sincerely apologise for the inconvenience this has caused.

Regards,
Aaron

**Comment by baruga** [comment]
@aaron-binary has the problem been resolved ?? information please

**Comment by cakasuma** [comment]
@baruga we have found the solution to the problem, we will release it soon
to fix it, sorry for the inconvinience this has caused

**Comment by baruga** [comment]
@cakasuma @aaron-binary Thank you, master. Your response is fast enough to respond to what I want. I salute you.

**Comment by cakasuma** [comment]
We are happy to help!, do not hesitate to contact us back if you have any
problem or issues

Regards,
Amam

**Comment by mexarrinha** [comment]
Hey, I'm also having a problem that i belive it might be a bug...
I can't acess my balance on "run once at start" 
In this case I'm trying set the stake to 3% of my balance, but it always says it needs to be a positive number..
If i had it on the "before purchasing" it works fine..

**Comment by baruga** [comment]
@mexarrinha several times I found this but I consider nothing. hopefully if that bug can be solved immediately

**Comment by aaron-binary** [comment]
Hey @mexarrinha & @baruga,

I've created a separate issue #1222, we'll add it to our list of bugs and address it as soon as we can.

Regards,
Aaron
