### ISSUE TITLE
The last digit is not the same as the end of the last tick number

### ISSUE THREAD

**Issue by baruga** [binary-com/binary-bot#1223]
@aaron-binary Is this a bug? or what about this. this can be a gap in the lack of binary. and I've read that if I get a gap from the shortcomings of binary, WHAT DO I REALLY GET THE BREAK FROM BINARY?

![digit terakhir tdk sama](https://user-images.githubusercontent.com/24489532/52836672-8ddb7980-3126-11e9-9c1c-8d8482f2a1f4.jpg)

**Comment by mexarrinha** [comment]
Do the logic insine a while loop inside the "Define trade options"...

**Comment by aaron-binary** [comment]
Hey @baruga,

It seems that when you notify the tick value, it is rounded up. I'll look into this, could you upload your strategy here or send it through to aaron@binary.com?

Regards,
Aaron

**Comment by baruga** [comment]
@aaron-binary that's right, only I want the binary to give a value number is a definite value because this if it occurs in the digit strategy can be a lot to your disadvantage.
