### ISSUE TITLE
Bug on duration type

### ISSUE THREAD

**Issue by binary-ex-machina** [binary-com/binary-bot#1225]
I have encountered a problem using 2 of the main blocks in the define trade options input.

here is an example when i build the logic first time
![image](https://user-images.githubusercontent.com/34610787/52873801-02b6af80-3137-11e9-9ee5-e5bed8cfd0bf.png)

After i move, edit, save, add or remove a block, it changes back to the ticks duration unit
![image](https://user-images.githubusercontent.com/34610787/52873832-182bd980-3137-11e9-8c17-a8e9b5d45aa4.png)

I understand that there is some function revering back to the first duration unit when something on canvas change, and this only happens if i have 2 of the configuration blocks.

**Comment by mexarrinha** [comment]
Boas @binary-ex-machina,
eu encontrei este post #889 sobre backTesting.
Neste tipo de backTesting que falas, tens de esperar dias normais ou consegues acelerar o processo?
Obrigado

**Comment by binary-ex-machina** [comment]
@mexarrinha o que o lance de backtest tem haver com o que eu postei? por favor, não misture os posts, crie um novo.

**Comment by aaron-binary** [comment]
Hey @binary-ex-machina,

Thanks for reporting this, we're working on the **Define trade options**-block at the moment, and weren't aware of this issue. I'll make sure this is fixed for the next release.

Regards,
Aaron

**Comment by Splourian** [comment]
When will be the next release? @aaron-binary

**Comment by Seapson** [comment]
@binary-ex-machina please how can i reset stake back to initial stake (1) after a second loss of 1.96 instead of a countinues stake of 1.96 1.96 1.96 using your strategety https://gist.githubusercontent.com/Fruitfella/d9747ecf6b4843c03353e67ba9cd07ba/raw/ffba998c8dc4fd656a31b8a8b05778df660f44f7/FRUITFELLA's_Compound_Management_ver.1.0.xml
