### ISSUE TITLE
Synchronization problem entered in HEDGING

### ISSUE THREAD

**Issue by bouhali00** [binary-com/binary-bot#1229]
I have a problem with hedging,
I have two problems: sometimes a part of bot is not active anymore or sometimes late!
And I use the same conditions of entry.
Are you having the same remarks ???

![problem hedge](https://user-images.githubusercontent.com/44878529/52888250-f6504800-3172-11e9-8044-afe3cb7d4425.png)

**Comment by binary-ex-machina** [comment]
the best for running 2 bots at the same time is to make them enter at the same time, or do analysis at the same time. Any block inside the IF in the blocks below, will be executed only in the 58 second of each minute.

![image](https://user-images.githubusercontent.com/34610787/53016843-5c67f400-342d-11e9-8756-7d35164f1624.png)

**Comment by bouhali00** [comment]
@binary-ex-machina 
is it this timing connected to the BOT system clock? I find a difference between clocks indicated on the BOT page !!
Here are the trade conditions with two BOTs in hedge.
![synchro hedge](https://user-images.githubusercontent.com/44878529/53023636-8503e400-3455-11e9-9b47-a9bf9f2b40cc.png)

**Comment by bouhali00** [comment]
@binary-ex-machina 
I put the block of 'remainder of seconds', I found a miss as shown in the photo, it is as if there is a problem of crash!
![reminder](https://user-images.githubusercontent.com/44878529/53200918-a9f58400-361a-11e9-830f-961c3fc83a16.png)

**Comment by binary-ex-machina** [comment]
@bouhali00 nothing will be perfectly sync. Some differences may occur and this is totally normal. It's impossible to have all the trades you make, everyday, forever, in sync.

**Comment by rubenspina** [comment]
veja o que montei ontem e deixei a noite trabalhando todos quer uma estabilidade nem se for um valor pequeno e seguro para enviar agora por email $10 sem muita conversa conta para deposito NETELLER 451425729446 o email projetos_10@hotmail.com o email para enviar comprovante de pagamento e projetos_10@hotmail.com envio o arquivo por email.
![captura de tela 2019-02-24 as 09 22 28](https://user-images.githubusercontent.com/30381449/53299191-efca6c00-3815-11e9-9133-a7b533e92b1a.png)
![captura de tela 2019-02-24 as 09 25 29](https://user-images.githubusercontent.com/30381449/53299218-36b86180-3816-11e9-9d86-e87f7dfc07da.png)

**Comment by binary-ex-machina** [comment]
@aaron-binary please ban this @rubenspina, he is spamming and selling bots all over the issues

**Comment by rubenspina** [comment]
estou ajudando o pessoal a nao perder dinheiro com estes bots mentiroso que vcs programa que nunca ganha so come o dinheiro do pessoal e vc deve ganhar comissão da binary pois esta criticando a verdade dos bot que sao alterados e mostra outra realidade.

________________________________
De: Binary Ex Machina <notifications@github.com>
Enviado: domingo, 24 de fevereiro de 2019 14:03
Para: binary-com / binary-bot
Cc: rubenspina; Mencione
Assunto: Re: [binary-com / binary-bot] Problema de sincronização inserido em HEDGING (# 1229)


@ aaron-binary<https://github.com/aaron-binary> por favor banir este @rubenspina<https://github.com/rubenspina> , ele é spam e vendendo bots em todas as questões

-
Você está recebendo isso porque você foi mencionado.

**Comment by bouhali00** [comment]
Estou aberto a todos, o bom lugar para ganhar dinheiro é FOREX, e quem ganha com sua estratégia, ele compartilha com as pessoas de graça.

I am open to all, The good place to earn money is FOREX, and who wins with his strategy, he shares with people for free.
