### ISSUE TITLE
How to change prediction number ??

### ISSUE THREAD

**Issue by mathiasmoor** [binary-com/binary-bot#1230]
Hello guys I need your help with changing prediction.

**How I can set variables for prediction digits ? 
I have manully selected digits, which I want to use for automated changing before opening every contract.** 

_**For example:** 
If last digit was 9, I need  change prediction to 9, if last digit was 8, I need change prediction to 8, if last digit was 7, I need change prediction to 7...etc._

Any solutions  ?  thanks

**this is what I need ...**

![image](https://user-images.githubusercontent.com/42667075/52900027-5d144680-31f1-11e9-9e9a-90fabf4bccff.png)

 **... but  when I run it there is opened  this notify** 
![image](https://user-images.githubusercontent.com/42667075/52900042-8c2ab800-31f1-11e9-8776-3d0b7fe32185.png)

**Comment by romeo1911** [comment]
i think u can use "last digit" in "define trade options: prediction:"
"last digit" u can find where is "last tick"

**Comment by mathiasmoor** [comment]
> i think u can use "last digit" in "define trade options: prediction:"
> "last digit" u can find where is "last tick"
