### ISSUE TITLE
bot binary erorr.

### ISSUE THREAD

**Issue by lasaidhari** [binary-com/binary-bot#1235]
webpage loading

**Comment by nextnaro** [comment]
clear cache or open private mode

**Comment by binary-ex-machina** [comment]
it was probably an update on the servers

**Comment by aaron-binary** [comment]
Hey @lasaidhari,

Let me know if you're still experiencing issues, if not, feel free to close this issue. 

Regards,
Aaron

**Comment by lasaidhari** [comment]
hey @aaron-binary I encountered web bot binary problems .. edit bot is slower every time it pushes the block and so does the block. otamatic binary bot goes out of account if it is too late to run a bot.
