### ISSUE TITLE
help for multiple strategy

### ISSUE THREAD

**Issue by abirroy1** [binary-com/binary-bot#1236]
1)suppose 1st strategy is rsi
2) 2nd strategy is cci
3) 3rd strategy is bulish and bearish

 if 1st trade is loss than start 2 strategy
if 2nd trade is loss  than start 3 strategy
if 3rd trade is loss than start 1st strategy 

please make this block

**Comment by mexarrinha** [comment]
Just create a variable x set it to 0.
Then inside the before purchase do:
If x = 0 do rsi
If x = 1 do cci
If x = 2 do bullish bearish

After purchase check the result:
If result is win set x to 0
If result is loss and if x >= 3 set x to 0 trade again;
Else change x by one.

**Comment by binary-ex-machina** [comment]
here is an example using 3 strategies. It will reset to the first strategy on a win

![image](https://user-images.githubusercontent.com/34610787/53016214-d5fee280-342b-11e9-9a03-8edf8013505a.png)

**Comment by tymu** [comment]
@binary-ex-machina xml?

**Comment by abirroy1** [comment]
Is possible make a block different timeframe 
suppose , strategy 1 is duration 5tick . strategy 2 is 1minit . startegy 3 is 3 minit @binary-ex-machina
