### ISSUE TITLE
Problem indication entry and exit spot

### ISSUE THREAD

**Issue by bouhali00** [binary-com/binary-bot#1239]
Hello,

i noticed the response time is slow, and lack of indication on entry and exit spot
![problem affichage entry exit spot](https://user-images.githubusercontent.com/44878529/53088218-049abd00-3501-11e9-967b-713b2e493b35.png)

**Comment by binarydream1** [comment]
I have the same problem .... why is this happen @aaron-binary ?make me nervous..please help!
![screenshot 2019-02-20 18 29 39](https://user-images.githubusercontent.com/47627429/53088867-91fc0280-353d-11e9-9a2f-84edeb679181.png)

**Comment by sinung21** [comment]
![ice_screenshot_20190220-201648](https://user-images.githubusercontent.com/28952744/53094454-c0350e80-354c-11e9-9188-8232bf6c874a.jpeg)
SAME TOO

**Comment by aaron-binary** [comment]
Hey @bouhali00, @binarydream1, @sinung21,

Thank you for reporting this issue, would any of you be able to send through their strategy to binarybot@binary.com? We will look into it and investigate why these values are not showing correctly.

Regards,
Aaron

**Comment by binarydream1** [comment]
Hey @aaron-binary is this problem really has something to do with the strategy?

**Comment by aaron-binary** [comment]
Hey @binarydream1,

We've identified the cause of this issue and are working on fixing it.

Regards,
Aaron

**Comment by binarydream1** [comment]
Hey @aaron-binary Thank You
