### ISSUE TITLE
Under Over , any share bot under over ?

### ISSUE THREAD

**Issue by ikwanbh** [binary-com/binary-bot#1240]
apakah ada yang mempunyai bot over under ?

![under over](https://user-images.githubusercontent.com/47769586/53090299-8dd1e400-3541-11e9-8e11-6a06fc7b39d7.png)

**Comment by binarydream1** [comment]
@ikwanbh lho itu SS nya udah bot Over/Under ?

**Comment by ikwanbh** [comment]
> 
> 
> @ikwanbh lho itu SS nya udah bot Over/Under ?

selain ini ada yang punya om ? ini main martianglenya kadang nyesek 5 x salah :D mau cobain gak om , saya share 
[digi_under_over_bot.zip](https://github.com/binary-com/binary-bot/files/2888026/digi_under_over_bot.zip)

**Comment by ikwanbh** [comment]
a

> 
> 
> @ikwanbh lho itu SS nya udah bot Over/Under ?

adakah yang punya selain ini ?

[OVER-UNDER MODAL $156.zip](https://github.com/binary-com/binary-bot/files/2888096/OVER-UNDER.MODAL.156.zip)

**Comment by binarydream1** [comment]
@ikwanbh itu sudah bagus botnya? masalahnya dimana?

**Comment by rubenspina** [comment]
veja o que montei ontem e deixei a noite trabalhando todos quer uma estabilidade nem se for um valor pequeno e seguro para enviar agora por email $10 sem muita conversa conta para deposito NETELLER 451425729446 o email projetos_10@hotmail.com o email para enviar comprovante de pagamento e projetos_10@hotmail.com envio o arquivo por email.
![captura de tela 2019-02-24 as 09 22 28](https://user-images.githubusercontent.com/30381449/53299191-efca6c00-3815-11e9-9133-a7b533e92b1a.png)
![captura de tela 2019-02-24 as 09 25 29](https://user-images.githubusercontent.com/30381449/53299218-36b86180-3816-11e9-9d86-e87f7dfc07da.png)
