### ISSUE TITLE
how to get result "change"

### ISSUE THREAD

**Issue by sinung21** [binary-com/binary-bot#1244]
![ice_screenshot_20190221-013157](https://user-images.githubusercontent.com/28952744/53115325-85e16680-3578-11e9-828e-31f11bd02345.jpeg)

**Comment by mexarrinha** [comment]
Do the 8398.587 - 8398.28 = 0,307
Subtract one thick by the other

**Comment by abirroy1** [comment]
can you make this block ? @sinung21

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/53189594-a6e0a080-35e6-11e9-9565-3e59f4edf406.png)

**Comment by drezende89** [comment]
![capturar](https://user-images.githubusercontent.com/47386079/53190236-e065db80-35e7-11e9-927a-9df9e512688e.PNG)

**Comment by sinung21** [comment]
ok thanks @binary-ex-machina  and @drezende89

**Comment by rubenspina** [comment]
veja o que montei ontem e deixei a noite trabalhando todos quer uma estabilidade nem se for um valor pequeno e seguro para enviar agora por email $10 sem muita conversa conta para deposito NETELLER 451425729446 o email projetos_10@hotmail.com o email para enviar comprovante de pagamento e projetos_10@hotmail.com envio o arquivo por email.
![captura de tela 2019-02-24 as 09 22 28](https://user-images.githubusercontent.com/30381449/53299191-efca6c00-3815-11e9-9133-a7b533e92b1a.png)
![captura de tela 2019-02-24 as 09 25 29](https://user-images.githubusercontent.com/30381449/53299218-36b86180-3816-11e9-9d86-e87f7dfc07da.png)

**Comment by rubenspina** [comment]
estou ajudando o pessoal a nao perder dinheiro com estes bots mentiroso que vcs programa que nunca ganha so come o dinheiro do pessoal e vc deve ganhar comissão da binary pois esta criticando a verdade dos bot que sao alterados e mostra outra realidade.
e tenho 100% de certeza que nao confio nos bot que vcs deixa para fazer downloads pois tenho 3 anos que investigo a capacidades deles e nenhum presta se nao alterados 

```
 
@ aaron-binary por favor banir este @rubenspina , ele é spam e vendendo bots em todas as questões](

**Comment by binary-ex-machina** [comment]
@rubenspina não o seu merda, eu não to vendendo nada aqui seu lixo. Coloca o bot gratis, seu insignificante e para de ficar cobrando $10 e colocando seu email pra vender. Nem fala do bot direito e ja coloca a conta do Neteller. Gente como você só atrapalha outras pessoas, não agrega em nada. Ta desesperado amigo? ta precisando de dinheiro? deve ser um merda que só vive de vender lixo, por isso fica fazendo spam por todos os lados. Não comprem desse bosta. Se quisesse ajudar a comunidade já teria postado o bot aqui e não colocado o endereço do Neteller dele. Lixo é sempre lixo mesmo.

**Comment by rubenspina** [comment]
nao sei quem vc e mas ficou bem incomodado logo logo o pessoal vai notar que esta sendo enganados por vcs que administra este bot que sao programados so para perder ate o ultimo centavos de quem usar

**Comment by rubenspina** [comment]
ola o que me perguntaram
http://binary.vanillacommunity.com/discussion/370/binary-com-bot-works-against-you

**Comment by binary-ex-machina** [comment]
@rubenspina lixo como você sempre vem querer vender algo. Posta o bot free aqui e para de tentar lucrar na boa fé de outras pessoas. Qualquer um aqui pode criar o bot e existem centenas de pessoas que ganham grana com opções binárias. Se você acredita que todos perdem com so bots por que alguém compraria o seu? por que o seu seria diferente? por que ao invés de postar o bot colocou sua conta do Neteller? 

Pessoas que querem vender a todo o custo o bot aqui em um lugar onde todos se ajudam, são as piores e mais irrelevantes nesse mundo. Da uma procurada no repositório o quanto já ajudei aqui antes de vir falar de mim, vendedor de merda.

**Comment by rubenspina** [comment]
porque vc esta estressado e nervoso baixando o nivel que coisa feia para um membro de grande respeito no site?

**Comment by binary-ex-machina** [comment]
por que lixo tem que ser tratado como lixo. Aqui as pessoas se ajudam. Caso você não saiba, esse lugar não á para vender bots e sim ajudar pessoas. Vc postou a propaganda de vender bots em mais de 10 posts diferentes, totalmente irrelevante com a dúvida de cada usuário. As pessoas não querem o lixo que você vende. Preciso baixar o nível pra você entender.

**Comment by rubenspina** [comment]
ja que vc diz que esta ai para ajudar qual os valor corretos e bom para iniciar este meu bot e faturar pelos menos uns $750 por dia me coloca a formula de jogadas aqui o exemplo seria este numero de jogada?
![captura de tela 2019-02-24 as 21 05 49](https://user-images.githubusercontent.com/30381449/53307566-98111c80-3878-11e9-90f7-7d9f08ed3451.png)
![captura de tela 2019-02-24 as 21 07 35](https://user-images.githubusercontent.com/30381449/53307570-9e06fd80-3878-11e9-803f-a0b301635ae3.png)

**Comment by rubenspina** [comment]
cara tudo bem eu nao estou bravo meu objetivo e so criar uma conta real com $6.000.000.000 vc acho que vou me estressar com vc

**Comment by rubenspina** [comment]
cara boa noite e obrigado de se comunicar este domingo com migo via internet vou indicar seu site para algumas depois que nao tem amigos para ficar teclando com vc blz ate.

**Comment by binary-ex-machina** [comment]
@rubenspina usando conta demo? que feio, pelo menos posta imagem de bot rodando em conta real. Vc é tão burro que não sabe que este é o repositório da binary.com do site onde você monta o robô com blocos. Acredito que você nem tem noção do que é este lugar, mas blz, a ignorância pra você ta de bom tamanho. Criou a conta só para fazer spam e tentar vender esse lixo de bot que você tem, que com certeza não vai te ajudar a fazer os 6m que você quer. 

Além de lixo você ainda não ajuda a comunidade. Qual o problema de postar seu bot aqui? por que não ajuda as pessoas? por que só quer vender bot que roda em conta demo?

Esse seu bot de touch com barreira 1.4 que quando perde você faz martingale x6 é a maior ilusão e você ainda quer que alguém compre? Não esquece que conta demo não da pra sacar tá?
