### ISSUE TITLE
Invalid duration input.

### ISSUE THREAD

**Issue by Splourian** [binary-com/binary-bot#1257]
Hello, here i'm again with the same error (i never fixed it). I try to change my browser to Firefox, Opera but nothing. So i change my operating system to Linux and nothing.
How many of you have the same problem?
Please notifiy me when the bug will be fixed or how i can fix it, thanks.

**Comment by aaron-binary** [comment]
Hey Splourian,

I'm sorry to hear that you're still experiencing these issues, we will investigate again what could be the cause of this. Our recommended setup is using the latest Chrome version on any platform, make sure to purge your temporary files, see https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en for more information.

Regards,
Aaron

**Comment by aaron-binary** [comment]
Hey @Splourian,

Could you try connecting to our website using a VPN? If that works, could you report back to me so we can investigate why you're unable to connect from your location?

Thanks in advance!

Regards,
Aaron

**Comment by Splourian** [comment]
Hello, ok i Will test it today!

Il mar 26 feb 2019, 02:09 Aaron Imming <notifications@github.com> ha
scritto:

**Comment by Splourian** [comment]
I try to connect with a VPN (NordVPN) and its doesn't work. Im frustrated
because i work hard for the strategy... Please notify me how it can be
fixed or when you will fix it.
Thanks in advanced
Best Regards

Il giorno martedì 26 febbraio 2019, D6vil isNotX <aphexcraft@gmail.com> ha
scritto:

**Comment by Splourian** [comment]
> Hey @Splourian,
> 
> Could you try connecting to our website using a VPN? If that works, could you report back to me so we can investigate why you're unable to connect from your location?
> 
> Thanks in advance!
> 
> Regards,
> Aaron

Done, but not working.

**Comment by Splourian** [comment]
![error](https://user-images.githubusercontent.com/47654573/53647228-5f3cc300-3c3d-11e9-87b3-c2b8dec77142.JPG)
Cache, Cookies deleted, VPN but nothing. I have the lastest version of Chrome and Windows 10.

**Comment by Splourian** [comment]
![error](https://user-images.githubusercontent.com/47654573/53647228-5f3cc300-3c3d-11e9-87b3-c2b8dec77142.JPG)
Cache, Cookies deleted, VPN but nothing. I have the lastest version of Chrome and Windows 10.

**Comment by Splourian** [comment]
@aaron-binary
