### ISSUE TITLE
LIMITATION OF SINGAPORE TRADING VPS

### ISSUE THREAD

**Issue by baruga** [binary-com/binary-bot#1276]
@aaron-binary Is it true that if you use the Singapore vps there is a limit to trading volume volatility???
even though I already have a Singapore vps.

![vps singapore tidak boleh](https://user-images.githubusercontent.com/24489532/53455561-eb948d80-3a65-11e9-95a0-aac283ae0950.jpg)

**Comment by thainano** [comment]
what is the VPS for? are you in area where tick trading is not available?

**Comment by aaron-binary** [comment]
Hey @baruga,

Thanks for reporting this.

We do disable access to volatility markets for clients that registered in Singapore (or logged out users that connect from a Singapore IP address), however this shouldn't affect users that have registered elsewhere and connect from a Singapore IP, so this is a bug and we'll work on fixing it.

Regards,
Aaron

**Comment by baruga** [comment]
@thainano trading for the volatility market is not available, so I asked the master admin. hopefully it will be fixed soon and we can all trade with vps smoothly.

**Comment by adiwirak** [comment]
@baruga , where do u rent your VPS ?

**Comment by baruga** [comment]
@adiwirak im rent vps hire https://portal.jayahost.com/aff.php?aff=678

**Comment by ghossan86** [comment]
Mohon bantuannya mas mas yg uda jd master.. Uda 1 mingguan buat acuan beli call 2 kali put 2 kali dg cara zizag,  jd purchasenya call-call put-put call-call put-put.. 
Screenshotnya saja.. 
Terimakasih banyak

**Comment by baruga** [comment]
@aaron-binary Is it a solution for VPS with Singapore's IP?
