### ISSUE TITLE
strategy new

### ISSUE THREAD

**Issue by lasaidhari** [binary-com/binary-bot#1283]
hey @aaron-binary you can change the strategy bot can open 2 positions in one bot ... make changes to the website page ..

**Comment by aaron-binary** [comment]
Hey @lasaidhari,

I'm not sure if I understand your message, are you asking if it's possible to open multiple contracts in a single bot instance? If so, we currently only support a single trade per bot instance, however, you can open multiple tabs and run multiple strategies.

Regards,
Aaron

**Comment by lasaidhari** [comment]
yes that's what i meant. I have also tried to open more than 2 tabs, but bots don't go as expected because of network factors ... it's easier if 1 tabs open more than one position to avoid open positions that are different when buying

**Comment by aaron-binary** [comment]
Hey @lasaidhari,

We don't currently support running multiple bots in a single instance.

Regards,
Aaron
