### ISSUE TITLE
how to create bot 10m RSI THANKS

### ISSUE THREAD

**Issue by loigaak** [binary-com/binary-bot#1284]
![image](https://user-images.githubusercontent.com/10124794/53615286-d65b6280-3c0f-11e9-8c09-772174c71fa0.png)
![image](https://user-images.githubusercontent.com/10124794/53615291-dbb8ad00-3c0f-11e9-898e-727ea9706ff2.png)

**Comment by ghossan86** [comment]
Hi guys I've proven bot over seven very profitable,  you just need balance 50USD
If you want i'll send it via email..

**Comment by loigaak** [comment]
@ghossan86 OKE SIR , PLEASE SEND GMAIL loigaak123@gmail.com thanks

**Comment by udesh99** [comment]
Pls send me too @ghossan86

**Comment by udesh99** [comment]
Udtuds@gmail.com @ghossan86

**Comment by binary-ex-machina** [comment]
Post the bot here, if not just post an image of the blocks. Come here and say that have a bot and ask for email looks like he is selling.

**Comment by ghossan86** [comment]
Just simple strategy, actually i wanna share but i don't know yet how to
share in this forum..

Pada tanggal Sel, 12 Mar 2019 18:53, Binary Ex Machina <
notifications@github.com> menulis:

**Comment by binary-ex-machina** [comment]
@ghossan86 you can put the file here zipped. You can change the file extension to .txt too.

**Comment by ghossan86** [comment]
binary-ex-machina thanks a lot.. I'll try..

**Comment by aydotaone** [comment]
Please kindly share.
aydotaone@gmail.com

Thanks

**Comment by giaupn** [comment]
phongpv67@gmail.com
Please share

**Comment by Lester157** [comment]
> Привет, ребята, я доказал, что бот в течение семи лет очень выгоден, вам просто нужно баланс 50USD. 
> Если хотите, я вышлю его по электронной почте ..

И мне можно ?
L.kastos@mail.ru
