### ISSUE TITLE
How to get previous RSI values

### ISSUE THREAD

**Issue by anggalieur** [binary-com/binary-bot#129]
Can anyone help me how to get previous rsi tick values (not current) and previous tick values

**Comment by aminmarashi** [comment]
Hi, you need to use arrays (lists) like this:
<img width="679" alt="screen shot 2017-01-12 at 1 54 51 pm" src="https://cloud.githubusercontent.com/assets/6560964/21878662/bad2047a-d8ce-11e6-857c-1681a0821cc1.png">
You can download the blocks from [here](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/5eb51942bfcc73b62fc55098dcb52345ba5959d9/Get%2520previous%2520tick%2520candle%2520or%2520RSI.xml)

**Comment by anggalieur** [comment]
Awsome, worked perfectly.
