### ISSUE TITLE
Fix the duration

### ISSUE THREAD

**Issue by Splourian** [binary-com/binary-bot#1290]
![error](https://user-images.githubusercontent.com/47654573/53647541-0faac700-3c3e-11e9-822c-3c0802630fbf.JPG)
Hello, i need to fix it. I don't know if it's problem of the algorithm or mine.

Someone has the same bug? How you fix it?

(I have the lastest version of Chrome, Windows 10)

**Comment by thainano** [comment]
they are updating the Help? session, every time update anything there will be problem

**Comment by Splourian** [comment]
Any update?

**Comment by thainano** [comment]
my issue is fixed now

**Comment by Splourian** [comment]
Really? How?

**Comment by thainano** [comment]
i think sending issue to support@binary.com will get you faster help

**Comment by Splourian** [comment]
@aaron-binary any update of the fix?

**Comment by Splourian** [comment]
i send the ticket but no one reply me.

**Comment by Splourian** [comment]
@aaron-binary pls notify me
