### ISSUE TITLE
Start the bot in New candle

### ISSUE THREAD

**Issue by ChinthakaJP** [binary-com/binary-bot#1294]
Help me to create this

Start trade the bot in new candle every time..

Thanks

**Comment by romeo1911** [comment]
[ordernewcandle.zip](https://github.com/binary-com/binary-bot/files/2922835/ordernewcandle.zip)

**Comment by ghossan86** [comment]
romeo1911  can you help me please,  if direction at first tick in new candle is rise, purchase rise in third tick and if first tick in new candle direction is fall,  purchase fall in third tick.. So its purchase in third tick.. i hope you can help me.. 
Thanks before..
