### ISSUE TITLE
Add multiple open position

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-bot#130]
Needs #134 first

**Comment by samodins** [comment]
Yes Please

How can I have multi Open positions
with same asking price for example

Sammy

**Comment by aminmarashi** [comment]
It's not supported yet.

**Comment by BatTagil** [comment]
I use the application for TileTabs
https://chrome.google.com/webstore/detail/tile-tabs-we/lbnnfjfjdijcnaakaebgcoemmlicjbnl
https://addons.mozilla.org/ru/firefox/addon/tile-tabs/
![image](https://cloud.githubusercontent.com/assets/28902514/26365643/a2f1208a-4001-11e7-811a-5a8fe4cbfedc.png)
