### ISSUE TITLE
Please Create For Me This good Strategy Bot

### ISSUE THREAD

**Issue by ashrafulcg** [binary-com/binary-bot#1308]
![photo_2019-03-08_20-20-17](https://user-images.githubusercontent.com/45341442/54036085-ec0af200-41e4-11e9-865a-5c2f6e941727.jpg)

We need 3 confirmation
candle 15 green
candle 5 green
start candle 1 minute green

take call 56 second

same like put

**Comment by romeo1911** [comment]
[3c.zip](https://github.com/binary-com/binary-bot/files/2947909/3c.zip)

**Comment by ashrafulcg** [comment]
Thank you but can you give me martingale version also plz @romeo1911

**Comment by sinung21** [comment]
[3c with martingale.zip](https://github.com/binary-com/binary-bot/files/2948333/3c.with.martingale.zip)

**Comment by syed18** [comment]
@romeo1911  can you please send me your email , i have good strategy to make bot

**Comment by ricowidiatmoko** [comment]
@romeo1911  gan cara bikin logic " setiap open candle 1 menit lebih tinggi dari highest candle sebelumnya purchase rise" caranya gimana gan? ane dah otak atik gajalan logic nya heheh mohon bantuan nya gan
