### ISSUE TITLE
Help me Strategy MACD and EMA

### ISSUE THREAD

**Issue by Rafaelwebs** [binary-com/binary-bot#1310]
If EMA 17 is higher than EMA34 and MACD is higher than SIGNAL then RISE.
If EMA 17 is lower than EMA34 and MACD is lower than SIGNAL, then FALL.

MACD(12,26,9) 1 minute

**Comment by romeo1911** [comment]
[emacd.zip](https://github.com/binary-com/binary-bot/files/2947938/emacd.zip)

**Comment by Rafaelwebs** [comment]
Thanks friend. 👍
