### ISSUE TITLE
necesito ayuda para q este bot sea mas rapido, muy buen bot

### ISSUE THREAD

**Issue by Ares31** [binary-com/binary-bot#1314]
Hola este bot es bueno pero entre contratos demora muchisimo en ejecutar, alguien puede ayudarme a que el bot lo haga mas rapido, me refiero entre un contrato y otro q no demore tanto tiempo en ejecutarlo muchas gracias
[Rise - Fall.zip](https://github.com/binary-com/binary-bot/files/2949425/Rise.-.Fall.zip)

**Comment by romeo1911** [comment]
No puede hacerlo más rápido porque depende de la lógica. puede intentar eliminar "set 4" y "set 5"...

**Comment by Ares31** [comment]
gracias lo voy a intentar
