### ISSUE TITLE
Can someone made bot from this strategy

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#1319]
Please put in the bot:

1.Martingle
2.Target profit
3.Stop loss
https://www.youtube.com/watch?v=UYXcmN1kF1E&t=223s

**Comment by binary-ex-machina** [comment]
Just replicate the blocks below

![image](https://user-images.githubusercontent.com/34610787/54197956-0b837280-44a4-11e9-86a9-c45a46d4fee3.png)

**Comment by poroinika** [comment]
> Just replicate the blocks below
> 
> ![image](https://user-images.githubusercontent.com/34610787/54197956-0b837280-44a4-11e9-86a9-c45a46d4fee3.png)

Thanks man,but can you put .XML?
I try to made it but....... :D

**Comment by sinung21** [comment]
[binary-botDIFFER.zip](https://github.com/binary-com/binary-bot/files/2958468/binary-botDIFFER.zip)

**Comment by syed18** [comment]
how can we exclude zero digits from it ?

**Comment by sinung21** [comment]
[binary-bot DIFFER V100.zip](https://github.com/binary-com/binary-bot/files/2963041/binary-bot.DIFFER.V100.zip)
