### ISSUE TITLE
Cara share bot dalam bentuk zip maupun xml

### ISSUE THREAD

**Issue by ghossan86** [binary-com/binary-bot#1321]
Dari kemarin nguteg2 Hp tetep g ketemu caranya share bot di forum ini dalam bentuk zip maupun xml, jd terpaksa lewat email.. 
Barangkali temen2 ada yg mau ngasih tau..

**Comment by thainano** [comment]
please send me thai.lehong88@gmail.com. thanks

**Comment by sinung21** [comment]
arahkan pointer di file bot nya..klik mouse kanan..selanjutnya pilih  add to archive klik.selanjutnya muncul archive name and parameters pilih archive format ZIP.UDAH baru klik OK di bawah

**Comment by ghossan86** [comment]
Sip matur nuwun mas,  kayake harus pake laptop y..

**Comment by albert2309** [comment]
Paling gampang sih pakai laptop bang. Kalau pakai hp ribet, mesti gonta ganti aplikasi.
