### ISSUE TITLE
Bot accidently stopping

### ISSUE THREAD

**Issue by bluelught** [binary-com/binary-bot#1323]
Hello everyone!
My strategy requires running few windows with bot running on them. I've noticed that after running for some time bot just accidently stopped on some of windows and on some was still running.

Then few words about how did bot stop. There were no errors or mistakes in log, even in the monitor window status was still "bot is running". But signals on buy or sell were not taken, I've noticed it only because I watched currenices graph and see places where bot had to take trade. After that I had got a feeling that something is wrong and embedded to bot a command to post a text every minute. It was made to monitor bot activity and see when does it stop to trade without any sings, as explained earlier. I saw that some windows with bot running on them work flawlessly and on other it simultaneously stopped after few minutes or hours. Can anyone help with this problem? Thx.

**Comment by aaron-binary** [comment]
Hey @bluelught,

Thanks for reporting this issue. 

Would you be able to share your strategy with us so we can investigate what's going on. You can either upload it here (as a .txt file) or send it to us directly at binarybot@binary.com. Additional information like screenshots and videos would also help a lot.

We apologise for the inconvenience this has caused to you.

Regards,
Aaron

**Comment by bluelught** [comment]
[Strategy.txt](https://github.com/binary-com/binary-bot/files/2961551/Strategy.txt)
http://www.filedropper.com/strategy1

In here I added short description of strategy and link to XML-file.
The strategy is runned at few currency pairs. If any more information is needed, I would be happy to provide.

**Comment by bluelught** [comment]
Also if there will be some problems with getting .xml file from link, I may send it directly by e-mail.
