### ISSUE TITLE
bot has stopped

### ISSUE THREAD

**Issue by romeo1911** [binary-com/binary-bot#1325]
the bot has stopped working after 11 hours no stop, but it continues to make orders, without following all the logic. 
the logic is: open trade on second candle( 1 candle trade and 1 not)
follow the macd trend ( it no longer does it from when it show "bot has stopped working")
only open put orders.
![Untitled](https://user-images.githubusercontent.com/44220114/54275392-0f56e800-45bd-11e9-91ec-1718f28c558f.png)

**Comment by aaron-binary** [comment]
Hey @romeo1911,

Thanks for reporting this issue.

We're aware that sometimes the status indicator is incorrectly showing that the bot has stopped, but rest assured that the logic will not change when this occurs. We're working on fixing the status indicator issue. 

For investigation purposes, would you be able to send through your strategy? You can either upload it here (as a .txt-file) or send it to binarybot@binary.com.

Regards,
Aaron

**Comment by romeo1911** [comment]
I just send u a mail.
let me know.
thanks

**Comment by romeo1911** [comment]
[ex4.zip](https://github.com/binary-com/binary-bot/files/2967920/ex4.zip)
similar logic, same problem, inside there is the log, after bot has stopped for 3 hours only put
