### ISSUE TITLE
Как в боте использовать фунцию "загрузить блок из..."

### ISSUE THREAD

**Issue by AlexK54** [binary-com/binary-bot#1331]
Господа мозаичники ботов! Есть работающий бот. Хочу в случае нескольких неудачных сделок автоматом перейти на другой бот автоматически. Нашел функцию "загрузить блок из...", но она не вписывается в действующую мозаику блока. Кто поможет? Как ее использовать?

**Comment by AlienFly** [comment]
В твоем случае никак =). Она для другого предназначена...

**Comment by AlexK54** [comment]
Спасибо! А для чего она?

**Comment by aaron-binary** [comment]
Hi @AlexK54,

I don't speak Russian so I'll reply in English.

If I'm correct you're looking for a way to load additional blocks or another bot based on specific conditions? I don't believe you would be able to do this currently, however, this would be an interesting feature. Could you explain more about how it would work?

Thanks in advance!
Aaron

**Comment by AlexK54** [comment]
К сожалению я не владею английским, а перевод часто не точный и не всегда мы можем понять друг друга. 
Вы правы. Хотелось бы создать бота перехоящего автоматически на другой бот в зависимости от ситуации на рынке (тренд, флэт)  или нескольких проигрышей подряд. Но сейчас это невозможно. Спасибо!

**Comment by anton-binary** [comment]
Добрый день Alex54,

Не могли бы Вы утонить, что именно означает перейти на другой бот? Изменить инструмент или изменить логику торговли? И что означает "не вписывается в действующую мозаику блока"? Возможно поняв это, мы сможем тогда посоветовать что-то или запланируем разработку новой функциональности.

Спасибо!
Антон

**Comment by AlexK54** [comment]
1. Идея такая : есть несколько ботов, работает один,. По какой то причине, например убыток, запрограммировать внутри работающего бота с помощью этой функции загрузку другого бота и дальше торговать по нему.
2. Не вписывается означает блок "загрузить из .."не имеет выступов мозаики (ни сверху, ни снизу, фома сглаженный прямоугольник) чтобы его вписать в какой либо другой блок
Как можно использовать блок "загрузить из .." ?
Спасиибо!
Александр.

**Comment by anton-binary** [comment]
Добрый день, спасибо за пояснения.
 
Если я правильно понял Вас, то Вам незачем загружать другого бота. Обратите внимание на функции. Раздел Расширенные\Функции (Advanced/Functions). Вы можете сделать две (или более) функции, каждая из которых будет реализовывать определенную Вами торговую логику. Затем Вы можете вызывать нужную функцию в зависимости от некоторых условий, которые Вы зададите.  См. пример ниже. Есть ограничение: нельзя поменять инструмент, не останавливая функцию (т.е. если задан Vol 10, то обе функции должны по нему торговать).

![image](https://user-images.githubusercontent.com/43776314/54581636-88848e00-4a48-11e9-9833-df09d45db524.png)

**Comment by AlexK54** [comment]
Спасибо! Буду разбираться и пробовать! Я еще новичок в ботах!
