### ISSUE TITLE
Как сделать паузу в торговле бота?

### ISSUE THREAD

**Issue by AlexK54** [binary-com/binary-bot#1332]
После нескольких проигрышных сделок подряд хочу сделать паузу в торговле допустим в 69 сек. Использую функцию "выполнить после 60 сек" ничего не вставляя внутрь. Она то работает, то нет. Как ее правильно использовать?

**Comment by AlienFly** [comment]
![69](https://user-images.githubusercontent.com/36364199/54462709-c00de480-4781-11e9-9248-17024cf8f881.png)

**Comment by AlexK54** [comment]
Спасибо! Нечто подобное делал, только этот блок вставлял внутрь блока ЕСЛИ и последним блоком был блок ТОРГОВАТЬ СНОВА. Правильно ли это?
В вашем случае, если предложенный вами блок будет последним, то пауза будет после каждой сделки.
