### ISSUE TITLE
Есть ли в боте операторы условного и безусловного перехода?

### ISSUE THREAD

**Issue by AlexK54** [binary-com/binary-bot#1333]
Есть ли в боте операторы условного и безусловного перехода?

**Comment by anton-binary** [comment]
Доброго времени суток AlexK54,

Безусловный переход не поддерживается.
Поддерживаемые операторы условного перехода: if-else if-else (если-иначе если-иначе). Доступны на вкладке Logic (Логика).

Антон.

**Comment by AlexK54** [comment]
Спасибо!
