### ISSUE TITLE
Linear Regression Channel

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#1335]
Can somebody create 3 values of Linear Regression Channel based on ticks look back.
@binary-ex-machina

**Comment by tymu** [comment]
I've found this https://www.prorealcode.com/prorealtime-indicators/linear-regression-channel-with-percent-upper-and-lower-lines/

**Comment by tymu** [comment]
https://www.tradingview.com/script/LpbWEcA3-Regression-Line-Formula/

**Comment by binary-ex-machina** [comment]
@tymu the main problem in creating the Linear Regression Channel is that you need to calculate the correlation between 2 SMA lists. The calculation is very complex to apply on the blocks.

**Comment by Shuckoswaldo** [comment]
Me gustaría saber como hacer fibonacci.
