### ISSUE TITLE
Как перенести копированием или перетаскиванием

### ISSUE THREAD

**Issue by odn1** [binary-com/binary-bot#1337]
Как перенести копированием или перетаскиванием части (блок с функцией) одного робота (бота /bot.binary.com/bot.html) в другой, который загружен в другом окне или вкладке?

**Comment by anton-binary** [comment]
Доброго времени суток odn1.
Вы можете сохранить блок с функцией, выбрав "Загрузить" из контекстного меню. Затем загрузить сохраненный блок в окне другого бота. Ваша функция будет добавлена к блокам на рабочем пространстве.
![image](https://user-images.githubusercontent.com/43776314/54522207-9df5ab80-49a7-11e9-9bd2-6e2a4a4a2b4c.png)

**Comment by odn1** [comment]
Спасибо. Такой способ тоже устраивает.
