### ISSUE TITLE
Run on 5th tick every new candle

### ISSUE THREAD

**Issue by hubbaloo** [binary-com/binary-bot#1338]
Ladies and gentlemen, really appreciate if  anyone could give a clue on how to create a function so bot will run on 5th tick every new candle? Thanks.

**Comment by anton-binary** [comment]
Hey @hubbaloo, check this example
[https://github.com/binary-com/binary-bot/blob/dev/examples/misc/is%20candle%20new%20package.xml](url)

You will need to add tick counter to this example to trigger your logic on every 5th tick after candle is started.

**Comment by hubbaloo** [comment]
@anton-binary Still could not open the file in bot after following your instruction above. Is it the old XML version?

**Comment by binarydream1** [comment]
@hubbaloo maksudnya seperti ini kisanak?

[Tik Ke-5.zip](https://github.com/binary-com/binary-bot/files/2986390/Tik.Ke-5.zip)

**Comment by hubbaloo** [comment]
@binarydream1 wah pendekar turun gunung...Terima kasih kisanak

mau nyoba strategi 5 tik kayanya oke juga martinem cuma maks 3x

**Comment by binarydream1** [comment]
@hubbaloo ohh ..silahken kisanak .. sy doakan kisanak dianugerahi kemenangan dlm setiap pertandingan

**Comment by hubbaloo** [comment]
@binarydream1 terima kasih doanya Ki. Saya sudah siap jalankan strategi ini di malam Jumat kliwon sambil bakar kemenyan wkwkwk

**Comment by hubbaloo** [comment]
For those of you who wants to test this strategy and create your own bot;
1. Make sure it’s a new candle
2. If tick 5 is greater than tick 1 open higher and do the opposite for lower
3. This only works better in trends. Big speculations in sideways market so you need to Avoid the sideway market by using bollinger bands as indicator
4. Martingale is about 3 level tops so you can prepare the MM wisely

Have fun.

**Comment by ZDEGLET** [comment]
hubbaloo скиньте плиз этого бота в формате txt

**Comment by ZDEGLET** [comment]
anton-binary ваш пример не запускается плиз этого бота в формате txt

**Comment by romeo1911** [comment]
@hubbaloo 
Nek misale ora kasil ngobong dupa pas jumat kliwon, Nek gelem tak kirim tuyul dinggo ngawe bot nggo koe  gratis wkwkwkwk

**Comment by anton-binary** [comment]
@ZDEGLET please note that this is not a bot, it's a collection of blocks. To use them you will have to call _binary::is new candle_ function from your bot. It returns "True" in case current tick is the first tick within the candle. Please check the attqched file.

[is new candle.txt](https://github.com/binary-com/binary-bot/files/2987253/is.new.candle.txt)

**Comment by hubbaloo** [comment]
@romeo1911 wkwkwk tuyul ne Mbah Jambrong anti loss khusus malam jumat kliwon bot 5 tick wkwkwk

**Comment by ghossan86** [comment]
anton-binary how to use this text at bot?

**Comment by ghossan86** [comment]
binarydream1 trim's bgt suhu.. 
Sudah ada pencerahan..

**Comment by anton-binary** [comment]
@ghossan86, 
> anton-binary how to use this text at bot?

Download and rename, XML, load into Binary Bot platform. As i mentioned in this thread this is not a trading bot, this is an example of how you can identify a new candle. This example is created by Binary Developers for you. You need to add blocks from this example into YOUR trading strategy and then call _binary::is new candle_ function which will return True in case if new candle is started.
