### ISSUE TITLE
PAYOUT HIGHER LOWER MANUAL DIFFERENT WITH PAYOUT BOT BINARY

### ISSUE THREAD

**Issue by baruga** [binary-com/binary-bot#1343]
@aaron-binary WHY PAYOUT HIGHER LOWER MANUAL DIFFERENT WITH PAYOUT BOT BINARY?

**Comment by romeo1911** [comment]
better if u take a pic like this
![Untitled](https://user-images.githubusercontent.com/44220114/54862929-58a0f780-4d74-11e9-94f6-e7802cd2bf92.png)
the same quantity of money to stake, at the same moment, with the same barrier
