### ISSUE TITLE
Alguien puede ayudarme a agregar algunos parametros mas a este robot - PUEDO PAGAR

### ISSUE THREAD

**Issue by DaveCortes21** [binary-com/binary-bot#1346]
Quisiera agregar:

-Take profit
-Stop loss
-Niveles de Martingala 
-Una casilla de reinicio automático después de 10, 15, 20 minutos después de haber llegado al TP o al  SL.

Saludos 

[Ticks.xml.zip](https://github.com/binary-com/binary-bot/files/2992691/Ticks.xml.zip)

**Comment by ericcovich** [comment]
cual es tu correo?

**Comment by DaveCortes21** [comment]
> cual es tu correo?

smarcky@gmail.com 
o @Dave_CR Telegram
