### ISSUE TITLE
Help me to Create During Purchase Tab

### ISSUE THREAD

**Issue by ChinthakaJP** [binary-com/binary-bot#1348]
Hello Guys...i need to create a bot for During Purchase Tab,
Example for CALL trade

![Untitled](https://user-images.githubusercontent.com/35625635/54863574-694f6e80-4d70-11e9-926c-151bb3a3068e.jpg)

Hope You understand !
Thanks

**Comment by romeo1911** [comment]
[sellatmarket.zip](https://github.com/binary-com/binary-bot/files/2999226/sellatmarket.zip)
1: open the bot that u want,
2: open this ( will load the part u need inside your bot over the block 1)
3: move the part that will be added inside the block 3
