### ISSUE TITLE
Помогите пожалуйста доработать бота.

### ISSUE THREAD

**Issue by Lester157** [binary-com/binary-bot#1351]
Хочу создать бота который открывал бы сделки в зависимости от закрытия свечи. 
Если свеча закрылась на покупку. то робот открывает следующую сделку на покупку, если свеча закрылась на продажу, робот открывает сделку на продажу. 

Не могу разобраться с тем, как это осуществить со свечами, подскажите что можно сделать!
![1](https://user-images.githubusercontent.com/48863837/54869039-3626d280-4da4-11e9-82dc-e36f0775d5ec.png)

**Comment by romeo1911** [comment]
![Untitled](https://user-images.githubusercontent.com/44220114/54874231-783e2b80-4e19-11e9-8a35-78ba455ccd7d.png)
