### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by gingaginger** [binary-com/binary-bot#1352]
Is there a "last digit" button that will enable me to purchase if the last digit is a certain number?

**Comment by Ahmedoptions** [comment]
Hello Frienda I  made this great bot with my Friends the bot work with many strategies we did the martingale woke after two steps like example if the bot loose 0.35 the bot after that will opine new order withe same stake 0.35 if got win after that will opine new stake with 4.29 we need change the  martingale and let him work after 7 steps or more like this 0.35 loose , 0.35 win , 0.35 win , 0.35 win, 0.35 win ,0.35 wine ,0.35 win , 4.29 win, can you help us please we tried many times but we got failed
[Differ-martangel v3.zip](https://github.com/binary-com/binary-bot/files/3000595/Differ-martangel.v3.zip)

**Comment by wilburforce83** [comment]
You need to build a logic function:

If: last digit = n
Do: place trade

The last digit variable is under binary > tick analysis. The "if do" is under logic.
