### ISSUE TITLE
Fix the martangel stratgies

### ISSUE THREAD

**Issue by Ahmedoptions** [binary-com/binary-bot#1355]
@chylli @raunakkathuria @MahboobehMohammadi @ashkanx @jy-binary 
Hello dear I  made this great bot with my Friends the bot work with many strategies we did the martingale woke after two steps like example if the bot loose 0.35 the bot after that will opine new order withe same stake 0.35 if got win after that will opine new stake with 4.29 we need change the  martingale and let him work after 7 steps or more like this 0.35 loose , 0.35 win , 0.35 win , 0.35 win, 0.35 win ,0.35 wine ,0.35 win , 4.29 win, can you help us please we tried many times but we got failed
[Differ-martangel v3.zip](https://github.com/binary-com/binary-bot/files/3000604/Differ-martangel.v3.zip)

**Comment by ZDEGLET** [comment]
НЕ ДОГОНЯЮ КАК ОНИ ЗАШИЛИ ПАРАМЕТРЫ МАРТИНА

**Comment by ZDEGLET** [comment]
САМИ СДЕЛАЛИ БОТ А ПАРАМЕТРЫ ПОМЕНЯТЬ НЕ МОГУТ. ПРИКОЛЬНО!!!
