### ISSUE TITLE
Help me add Martingale Bot 

### ISSUE THREAD

**Issue by Ahmedoptions** [binary-com/binary-bot#1356]
Hello dear I  made this great bot with my Friends the bot work with many strategies we did the martingale woke after two steps like example if the bot loose 0.35 the bot after that will opine new order withe same stake 0.35 if got win after that will opine new stake with 4.29 we need change the  martingale and let him work after 7 steps or more like this 0.35 loose , 0.35 win , 0.35 win , 0.35 win, 0.35 win ,0.35 wine ,0.35 win , 4.29 win, can you help us please we tried many times but we got failed
[Differ-martangel v3.zip](https://github.com/binary-com/binary-bot/files/3000604/Differ-martangel.v3.zip)

**Comment by lasaidhari** [comment]
![6l](https://user-images.githubusercontent.com/34808023/55206103-e6169880-5207-11e9-8b14-2495727d612a.jpg)
[said martinggale differ Ahmedoptions v1.zip](https://github.com/binary-com/binary-bot/files/3020888/said.martinggale.differ.Ahmedoptions.v1.zip)
Semoga dapat membantu.

**Comment by Ahmedoptions** [comment]
> ![6l](https://user-images.githubusercontent.com/34808023/55206103-e6169880-5207-11e9-8b14-2495727d612a.jpg)
> [said martinggale differ Ahmedoptions v1.zip](https://github.com/binary-com/binary-bot/files/3020888/said.martinggale.differ.Ahmedoptions.v1.zip)
> Semoga dapat membantu.

Hello bro thanks for bot but there are problem in bot can you fix it please 
![Screenshot (203)](https://user-images.githubusercontent.com/48227893/55207095-cdd75700-51d0-11e9-80f4-799d6eadcc80.png)

**Comment by lasaidhari** [comment]
[bot said differ martingale v1 v2 yes full edit -1.zip](https://github.com/binary-com/binary-bot/files/3025394/bot.said.differ.martingale.v1.v2.yes.full.edit.-1.zip)
![Ahmedoptions](https://user-images.githubusercontent.com/34808023/55275440-a55a7480-5318-11e9-865c-cc817467c5d1.gif)

semoga dapat membantu.
