### ISSUE TITLE
Notify win rate and loss rate

### ISSUE THREAD

**Issue by ghossan86** [binary-com/binary-bot#1363]
Can anyone help me please the logic how to show win rate and loss rate in every win or loss 
I try like this 
[ (win counter) × (no. Of Runs) ÷ (100) ]
[ (loss counter) × (no. Of Runs) ÷ (100) ]
but it doesn't work like expected
Thanks for response before

**Comment by binarydream1** [comment]
Seperti ini yg dicari?
[Bot WinLoss Ratio.zip](https://github.com/binary-com/binary-bot/files/3006724/Bot.WinLoss.Ratio.zip)

**Comment by ghossan86** [comment]
Terimakasih  banyak mas...
Sudah sangat membantu..
