### ISSUE TITLE
Binary Bot v20190326_0: New Features

### ISSUE THREAD

**Issue by aaron-binary** [binary-com/binary-bot#1364]
**Transaction log**
You can now reset the transaction log in the Summary window. Just click on the icon on the top right corner of the Summary window to clear the transaction list.

![clear_transactions](https://user-images.githubusercontent.com/44427668/54976642-f1827d80-4fd5-11e9-8426-46f7f2b753a5.gif)

**Only ups/downs**
We have added the Only Ups/Only Downs trade type to our Binary Bot platform. Try your automated strategies with Only Ups/Only Downs today.

Find out more about Only Ups/Only Downs. https://www.binary.com/en/get-started/binary-options.html?anchor=only-ups-only-downs#types-of-trades

**Comment by binarydream1** [comment]
@aaron-binary Thanks for your information

**Comment by wilburforce83** [comment]
Please see urgent bug report for this release [#1367](https://github.com/binary-com/binary-bot/issues/1367)
