### ISSUE TITLE
Please, Help me add martingale this file.

### ISSUE THREAD

**Issue by thawatchaii** [binary-com/binary-bot#1366]
[loop2.xml.zip](https://github.com/binary-com/binary-bot/files/3007908/loop2.xml.zip)

**Comment by ChinthakaJP** [comment]
@thawatchaii 
 
Here you Go .....>>>>

[Loop Diff BOT with Martingale.zip](https://github.com/binary-com/binary-bot/files/3008978/Loop.Diff.BOT.with.Martingale.zip)

**Comment by thawatchaii** [comment]
I am quite confused about your bot, Would you please fill out with I wish?, I want 200 profits and every loss, next turn stake will be ?*11.3, For example turn 1 stake = 0.35 then loss, Turn 2 stake = 0.35*11.3 $ then loss, Turn 3 stake = (0.35*11.3)*11.3 $ then loss, Turn 4 stake = (0.35*11.3*11.3)*11.3 $
@ChinthakaJP

**Comment by wilburforce83** [comment]
Looking at the bot @ChinthakaJP linked, the Martingale box is how many MG steps i.e. 5 would be to run martingale for 5 steps/losses in a row. 

Martingale factor is the multiplier *added* to the last stake so 1.5 would be 0.35 + (0.35*1.5) and so on.

**Comment by wilburforce83** [comment]
BTW, I would suggest adding in a delay after 2 losses, as this is an indicator that you hitting a barrier say, support of resistance of some description. in order for "not a digit" to work the returns are so low that you need to ensure you minimise the losses. I just tested this and when I got one or two out in often ran to three or four, which makes a 0.35 trade in the hundreds therefore not workable. :)

**Comment by wilburforce83** [comment]
[Loop Diff Cum Loss Martingale.zip](https://github.com/binary-com/binary-bot/files/3010031/Loop.Diff.Cum.Loss.Martingale.zip)

@thawatchaii  I have done you a slightly modified martingale. i feel it is a little safer than the traditional MG set up. It uses the cumulative loss, this is only a slight variation but significantly lowers the increases at 3 losses + I hope it helps :)

**Comment by thawatchaii** [comment]
hey @wilburforce83 thank you for your bot, I tried its but it isn't work because it's not random number so you can see in this pic >>
![Screen Shot 2019-03-27 at 12 44 51 PM](https://user-images.githubusercontent.com/48922976/55053851-1804ef00-5090-11e9-8605-2fcfe8f0aa6f.png)

It's not random like 1,2,3 and4, It's random only 1

I am looping 1 through 4 because it's just my idea.

**Comment by thawatchaii** [comment]
Again, Why the number of prediction can not change, My bot should change number in each times from 1 to 4 but it's locked by 2 like this case >>

![Screen Shot 2019-03-27 at 5 43 57 PM](https://user-images.githubusercontent.com/48922976/55070086-12bb9a80-50b8-11e9-9c85-faba2a54bb91.png)


[Loop Diff Cum Loss Martingale (1).xml.zip](https://github.com/binary-com/binary-bot/files/3012726/Loop.Diff.Cum.Loss.Martingale.1.xml.zip)

@wilburforce83 @aaron-binary

**Comment by wilburforce83** [comment]
Because you are only running that part on IF result = win

**Comment by romeo1911** [comment]
is locked at number 2 , because the block that change the numbers is inside "if result is win".
[Loop Diff Cum Loss Martingale (2).zip](https://github.com/binary-com/binary-bot/files/3013144/Loop.Diff.Cum.Loss.Martingale.2.zip)

**Comment by wilburforce83** [comment]
![here](https://user-images.githubusercontent.com/17556774/55076679-f1de4f80-508d-11e9-9e60-529ce5e518a1.JPG)

I have move it to be after the trade is closed, rather than specifying after a win.

[Loop Diff Cum Loss Martingale V2.zip](https://github.com/binary-com/binary-bot/files/3013155/Loop.Diff.Cum.Loss.Martingale.V2.zip)

**Comment by thawatchaii** [comment]
OK, Thanks a lot for both of you guys @wilburforce83 @romeo1911 !!

**Comment by ainvoot** [comment]
Its very good bot but i think change martingale that would not require a large deposit!
If loss 0.35 amount dont take after that 3.85 amount but split this amount x3 etc.

Thats my idea!

**Comment by wilburforce83** [comment]
I've done this before for someone, Its on here somewhere lol. I'll see if I can find it and link it for you

**Comment by Ares31** [comment]
Hola en ese bot se puede hacer q cuando pierda en vez de repetir la prediccion siga avanzando gracias
