### ISSUE TITLE
BUG : Trade Definition Defaulting to 1 Tick after changing Index

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1367]
Hi, 

I need to report a bug on the most recent updates (some time overnight) Changing index will change the trade definitions to 1 Tick.

### Expected Behaviour

When selecting a different index the trade definitions should return to whatever was being used on the previous index.

### Actual Behaviour

Change index, trade definition resets to a 1 Tick without warning leaving you trading on 1 tick trades until you notice its changed.

### Importance

Critical. Will cause a lot of problems for many users.

**Comment by wilburforce83** [comment]
Please see urgent bug report [#1367](https://github.com/binary-com/binary-bot/issues/1367)

**Comment by aaron-binary** [comment]
Hey @wilburforce83,

This behaviour is intentional. 

It fixes an issue where if a user changes to an instrument that doesn't support the previous set duration it would throw an error.

Regards,
Aaron
