### ISSUE TITLE
Bot binary unknown contract proposal

### ISSUE THREAD

**Issue by delano24** [binary-com/binary-bot#1368]
Before update my bot is fine. After update my bot alway get unknown contract proposal.. and always stop...

**Comment by aaron-binary** [comment]
Hey @delano24,

Could you send your strategy to binarybot@binary.com? Could you also let us know which account you're using as shown in the top right corner of the screen (e.g. VRTC12345678), this information would help us to identify what is causing this behaviour.

Regards,
Aaron

**Comment by delano24** [comment]
Okk ill sent later. Please fix up...
