### ISSUE TITLE
EVEN ODD

### ISSUE THREAD

**Issue by kobbyhigher** [binary-com/binary-bot#1371]
Hello guys i need help,

a want a feature that can switch between even and odd after a pre-determine loss. For example, purchase even, but if there are four continues loss, purchase odd.

**Comment by romeo1911** [comment]
i think in this post [https://github.com/binary-com/binary-bot/issues/1258#issuecomment-468673396_](https://github.com/binary-com/binary-bot/issues/1258#issuecomment-468673396_) there is what u r looking for
![image](https://user-images.githubusercontent.com/34610787/53642634-00615480-3c11-11e9-85cc-a08ff29dff54.png)
just change 5 with 4

**Comment by kobbyhigher** [comment]
thank you very much

**Comment by gentlevin** [comment]
@romeo1911 , pls can you add mightingale to this Even/Odd bot that is shown above for me pls? i followed the pic you attached above but do not know how to add mightingale to it.

**Comment by Osundina** [comment]
@romeo1911 I actually need something like the strategy u showed us just now, am having hard time creating this for unknown reasons can you please send to Osundinasegun@gmail.com thanks

**Comment by Osundina** [comment]
@romeo1911 pls i am still waiting for the strategy. Send to Osundinasegun@gmail.com thanks

**Comment by romeo1911** [comment]
i just see my email and this reply of u... wait a moment i will make

**Comment by romeo1911** [comment]
@gentlevin @Osundina 
i not use evenodd% because for me have a defect
i not send nothing using by mail because of spamming
it uses martingale, if u see that win are less then loss better u stop and try in other times
[evenoddzigozago.txt](https://github.com/binary-com/binary-bot/files/3100812/evenoddzigozago.txt)
