### ISSUE TITLE
Помогите пожалуйста сделать робота по цвету закрывающейся свечи.

### ISSUE THREAD

**Issue by Lester157** [binary-com/binary-bot#1373]
Помогите пожалуйста сделать робота партни! есть шаблон но он не работает так как надо.
![2](https://user-images.githubusercontent.com/48863837/55168992-fe919f00-5184-11e9-8390-ac85ea419e06.png)

Алгоритм работы:
Если свеча закрылась зелёная, то ставит вверх.
Если свеча закрылась красная, то ставит вниз.

Если сделка проиграла, то ставит следующую сумму.
Если сделка выиграла, то возвращается к первой сумме.
Если сделка возвратная, то ставит эту же сумму.

Поставить первый и последующие разы должен тогда, когда сделка завершилась(ибо важна каждая милисекунда)

**Comment by romeo1911** [comment]
Я не русский, лучше, если вы поделитесь своим ботом.
Я думаю, что сначала вы должны проверить, когда свеча новая,
после проверки, если свеча только что закрылась, зеленого или красного цвета.
"потому что важна каждая милисекунда" в этом проблема. лично я могу закрыть сделку 56 секунд, а когда 57 секунд открывается новая сделка, я получаю цену открытия в новой свече, если в интернете не слишком много задержки (если тело свечи очень мало, я могу ошибаться).
или вы можете торговать 1 минуту да и 1 минуту нет
[https://github.com/binary-com/binary-bot/blob/dev/examples/tools/is%20candle%20new.xml](url)

**Comment by Lester157** [comment]
Yes, of course, look here please.

**Comment by Lester157** [comment]
> Я не русский, лучше, если вы поделитесь своим ботом.
> Я думаю, что сначала вы должны проверить, когда свеча новая,
> после проверки, если свеча только что закрылась, зеленого или красного цвета.
> "потому что важна каждая милисекунда" в этом проблема. лично я могу закрыть сделку 56 секунд, а когда 57 секунд открывается новая сделка, я получаю цену открытия в новой свече, если в интернете не слишком много задержки (если тело свечи очень мало, я могу ошибаться).
> или вы можете торговать 1 минуту да и 1 минуту нет
> [https://github.com/binary-com/binary-bot/blob/dev/examples/tools/is%20candle%20new.xml](url)

Here, take a look please.

**Comment by Lester157** [comment]
[binary-bot1 (5).zip](https://github.com/binary-com/binary-bot/files/3019310/binary-bot1.5.zip)


> Я не русский, лучше, если вы поделитесь своим ботом.
> Я думаю, что сначала вы должны проверить, когда свеча новая,
> после проверки, если свеча только что закрылась, зеленого или красного цвета.
> "потому что важна каждая милисекунда" в этом проблема. лично я могу закрыть сделку 56 секунд, а когда 57 секунд открывается новая сделка, я получаю цену открытия в новой свече, если в интернете не слишком много задержки (если тело свечи очень мало, я могу ошибаться).
> или вы можете торговать 1 минуту да и 1 минуту нет
> [https://github.com/binary-com/binary-bot/blob/dev/examples/tools/is%20candle%20new.xml](url)

[binary-bot1 (5).zip](https://github.com/binary-com/binary-bot/files/3019315/binary-bot1.5.zip)

**Comment by romeo1911** [comment]
[binary-bot2.zip](https://github.com/binary-com/binary-bot/files/3020537/binary-bot2.zip)
[up-down.zip](https://github.com/binary-com/binary-bot/files/3020555/up-down.zip)
вот бот, который вы хотели.
второй - детектор направления, если вы хотите, вы можете открыть его после того, как откроете своего бота, и внутри меню «функция» у вас есть 2 блока для восходящего и нисходящего трендов, просто добавьте «составьте список свечей ... "и период, может быть," 9 "

**Comment by Lester157** [comment]
> [binary-bot2.zip](https://github.com/binary-com/binary-bot/files/3020537/binary-bot2.zip)
> [up-down.zip](https://github.com/binary-com/binary-bot/files/3020555/up-down.zip)
> вот бот, который вы хотели.
> второй - детектор направления, если вы хотите, вы можете открыть его после того, как откроете своего бота, и внутри меню «функция» у вас есть 2 блока для восходящего и нисходящего трендов, просто добавьте «составьте список свечей ... "и период, может быть," 9 "

Binary-bot2.zip does not start, can you fix it please ? Thanks)))
![1](https://user-images.githubusercontent.com/48863837/55217359-67722900-5210-11e9-92df-bfe75f4906bd.png)

**Comment by romeo1911** [comment]
![Untitled](https://user-images.githubusercontent.com/44220114/55232869-5f8aa700-5259-11e9-9952-c65efa70ad4a.png)
for me is working, try wait the first new candle ( max 60 seconds)

**Comment by Lester157** [comment]
> ![Untitled](https://user-images.githubusercontent.com/44220114/55232869-5f8aa700-5259-11e9-9952-c65efa70ad4a.png)
> for me is working, try wait the first new candle ( max 60 seconds)

Not understand, still does not start :c What can be done ?
![2](https://user-images.githubusercontent.com/48863837/55235783-65738e80-523f-11e9-9c5f-fdeda627a6c0.png)

**Comment by romeo1911** [comment]
maybe is because the delay  is more than 2 seconds on you.
the logic is: see if this candle is green or red and send the signal 2/3 seconds before the new candle happends then i get the value of open candle = start trade.
 try lowdown the number 57 maybe 56 or 55 or 53 and put the seconds of the trade -1 of that number.
if i put 58 i will trade 1 time on 2 candles

**Comment by romeo1911** [comment]
@Lester157 btw was happend to me too yesterday. my clock on my pc was not correct, this is why never open a trade.
