### ISSUE TITLE
Cara mengatur marti menjadi 5 bagian#differs

### ISSUE THREAD

**Issue by ghossan86** [binary-com/binary-bot#1377]
Mohon bantuannya para master dan kawan2 (barangkali ada yg bs membantu) ..
Saya coba membuat marti menjadi 5 bagian dg blok loop# mengulang 5 kali,  tp g berhasil.. 
Saya bermaksud jika dlm DD hasilnya loss maka memartinya 5×
Analoginya : misal jika stake $1 dan hasilnya loss , maka stake dirubah menjadi $2 dan diulang 5×

(mungkin bgni) 
Jika loss maka stake ditingkatkan 2kali lipat dan diulang 5×

Terimakasih sebelumnya..

**Comment by lasaidhari** [comment]
untuk DD tidak akan menghasilkan dgan 
-1 loss
-2 loss
-3 loss
-4 loss
5 win

**Comment by ghossan86** [comment]
Saya sudah punya bot yg diuji beberapa hari dan paling jauh loss hanya 2× berurutan dan itupun dlm 4000 transaksi hanya menemui loss berurutan 2× sebanyak 20×, dan jarak antara loss sekitar 10 bahkan 40 transaksi baru loss (kecuali loss berurutan) ,  jd saya perkirakan jika memartinya 5 kali maka tidak jd masalah.. 
Saya khawatir kalo meningkatkan stake 10 × lipat akan menemui loss berurutan..

**Comment by ghossan86** [comment]
lasaidhari mohon screenshotnya saja gpp,  ..
Trim's..

**Comment by lasaidhari** [comment]
sya punya versi martinggale yang dapat anda atur maximal martingale , reset martingale dan lain lain tpi munkin akan sulit dipahami cara inputnya...
[bot said differ martingale v1 v2 full-5.zip](https://github.com/binary-com/binary-bot/files/3025128/bot.said.differ.martingale.v1.v2.full-5.zip)

nanti z berikan back test mantinggale dalam bentuk excel.. saya buatkan dulu

**Comment by lasaidhari** [comment]
dalam bot akan diminta input .. silahak anda input dengan petunjuk didalam kurung ( .....) ..

**Comment by lasaidhari** [comment]
maaf sebelumya martinggale v1 eror.. 
[bot said differ martingale v1 v2 full-1-1.zip](https://github.com/binary-com/binary-bot/files/3025146/bot.said.differ.martingale.v1.v2.full-1-1.zip)

**Comment by ghossan86** [comment]
Terimakasih banyak master, akan saya pahami dulu logika rulenya sebelum running..

**Comment by ghossan86** [comment]
Mf perangkat saya sangat berat untuk membaca dan memerintah filenya,  terlalu besar ukurannya.. Nampaknya sangat lengkap analisanya.. Akan saya gunakan kalau laptop sudah upgrade sebab perangkat masih repair..

Barangkali kalau tidak keberatan cukup anda beri screenshotnya saja untuk marti diulang 5 kali.. 
Terimakasih banyak..

**Comment by lasaidhari** [comment]
leptop anda tidak masalah .. bot yang bermasalah.. saya sedang merubah martingale awal x2 dan  martinggale refres balance yang loss x11 .. karan Digit differ porofit 9.9% jdi harus ada martingale diatas 11 untuk mengembalikan modal.. sya sedang mencoba merubah martinggale v1 untuk dapat digunakan di Digit difer .. nanti saya upload screncot dan botnya

**Comment by ghossan86** [comment]
Terimaksih banyak master.. 
Ditunggu bantuannya

**Comment by lasaidhari** [comment]
![MARTINGALE SAID](https://user-images.githubusercontent.com/34808023/55274968-55c47a80-5311-11e9-845a-510d687d6b1f.jpg)
![ghossan86](https://user-images.githubusercontent.com/34808023/55274969-578e3e00-5311-11e9-92f7-702b7bee6851.gif)
 

silakan anda ikuti pentujukknya.. jika ingin merubah versi martinggale silahakan andan input pertama ( you ) terus dapat anda memilih versi martinggale ( v1 atau v2 )

**Comment by ghossan86** [comment]
OMG..terimaksih banyak.. Ini akan sangat membantu..

**Comment by lasaidhari** [comment]
ya sama .. jika butuh bantuan silahkan anda hubungi saya

**Comment by ghossan86** [comment]
Baik master,  sebenarnya bgini..kalau boleh tahu apakah bisa disederhanakan lagi logika perintahnya..
Misal jika hasilnya loss maka ubah modal dengan modal yg loss (biasanya saya pakai "mutlak detail kontrak profit") × (bla bla bla tergantung kebutuhan) 

Mf sebelumnya,  bgini ;
Jika
Trade 1st       dg stake $1 hasil loss
Trade 2nd      ubah stake mjd $2
Trade 3rd       stake $2
Trade 4th       stake $2
Trade 5th       stake $2
Trade 6th       stake $2

Tapi jika di trading 2nd atau 3rd atau 4th atau 5th atau 6th mengalami loss , maka ;
Stake diubah menjadi $4 sampai 5×
Terimakasih banyak master sebelumnya
saya bener2 newbie yg masih banyak belajar..

**Comment by lasaidhari** [comment]
semua bisa dilakukan dengan martinggale tersebut.. anda hanya perlu input sesuai martingale anda inginkan .. input you trus pilih v1 atau v2

**Comment by lasaidhari** [comment]
ikuti petunjuk selajutnya

**Comment by ghossan86** [comment]
Sip terimakasih banyak..
Baru mudeng..

Pada tanggal Sab, 30 Mar 2019 19:22, lasaidhari <notifications@github.com>
menulis:

**Comment by lasaidhari** [comment]
[bot said differ martingale v1 v2 yes full++reset++ edit .zip](https://github.com/binary-com/binary-bot/files/3025604/bot.said.differ.martingale.v1.v2.yes.full%2B%2Breset%2B%2B.edit.zip)
![ghossan86+](https://user-images.githubusercontent.com/34808023/55277797-b1552f00-5336-11e9-8dc1-721abc9cf27d.gif)


telah ditambahkan reset martinggale++

**Comment by ghossan86** [comment]
[Mfddlowb.zip](https://github.com/binary-com/binary-bot/files/3026212/Mfddlowb.zip)

**Comment by ghossan86** [comment]
Mohon bantuannya master agar ditambah rule logicnya,  jika loss maka memartinya 5× dan per marti dua kali lipat jumlah kerugian.. 
Seperti yg saya maksud di awal.. 
Saya coba bot yg master kirim,  tp belum beberapa menit hp langsung panas,  untuk memuatnya butuh waktu lama..

**Comment by ghossan86** [comment]
[UjiDD#2.zip](https://github.com/binary-com/binary-bot/files/3026214/UjiDD.2.zip)
ini hanya untuk uji coba,  saya harap bisa diberi rulenya untuk memarti 5× jika loss
Saya sudah mencobanya berbagai hal dan blok selama semingguan tp belum menemukan titik temu..
Sangat berharap bantuannya master..

**Comment by ghossan86** [comment]
Terimakasih banyak sebelumnya..

**Comment by lasaidhari** [comment]
saya akan mehubungngkan github dengan bot.binary .. agar file bisa lebih kecil .. mohon menunggu..

**Comment by ghossan86** [comment]
Terimakasih banyak,  saya berharap ada penyelesaiannya,  dan akan segera dishare ke temen2 yang lain,  sebab saya rasa logika rulenya dg membagi marti tsb sangat pas bila digabung dg bot yg saya rakit dan akan memiliki ketahanan dg modal cukup $10

**Comment by lasaidhari** [comment]
[@said mantinggale v1 v2 id Mfddlowb-2.zip](https://github.com/binary-com/binary-bot/files/3029280/%40said.mantinggale.v1.v2.id.Mfddlowb-2.zip)
![Mfddlowb](https://user-images.githubusercontent.com/34808023/55328013-9ceb7080-54b5-11e9-839e-a9ae8ffb43f1.gif)


z mengalami masalah menghubungkn dgn github. tpi anda bisa mencobanya dulu

**Comment by ghossan86** [comment]
Terimakasih banyak Suhu akan saya coba..

**Comment by lasaidhari** [comment]
apakah anda telah berhasil menjalankanya

**Comment by ghossan86** [comment]
Sangat berat saat load,  dan ketika order run bot g mau jalan,  biasannya bot yg saya pakai paling besar ukurannya tdk lebih dari 200kb, terimakasih banyak bantuannya,  jd sekarang lebih ke strategi compound saja drpd marti 5×

**Comment by lasaidhari** [comment]
ya klw pc bs jln normal..
