### ISSUE TITLE
Помогите доделать отличного бота!!!

### ISSUE THREAD

**Issue by Lester157** [binary-com/binary-bot#1379]
У меня есть робот, который работает на таймфрейме 1 мин.
Контракт покупаются при открытии новой свечи. 
Как сделать так, чтобы контракты покупались при закрытии текущей свечи или на 59 секунде? 
Дело в том, что из-за пинга создаются нежелательные паузы, а мне нужно чтобы бот открывал контракт в точности на новой свече.
Вот наработка.
[Candle bot.zip](https://github.com/binary-com/binary-bot/files/3025698/Candle.bot.zip)

**Comment by romeo1911** [comment]
3 варианта:
1: уже сделано человеком с почти идеальными результатами (но не с binary.com), снимая соседнюю квартиру с оптоволоконным подключением.

2: нанять хакера и запустить бота прямо с их сервера
3: вы физически подключаетесь к серверу
иначе невозможно быть точным

**Comment by Lester157** [comment]
> 3 варианта:
> 1: уже сделано человеком с почти идеальными результатами (но не с binary.com), снимая соседнюю квартиру с оптоволоконным подключением.
> 
> 2: нанять хакера и запустить бота прямо с их сервера
> 3: вы физически подключаетесь к серверу
> иначе невозможно быть точным

)))
