### ISSUE TITLE
Bollinger Bands rounding the values

### ISSUE THREAD

**Issue by pamorell** [binary-com/binary-bot#138]
Dears, please,could you help me?

I have a bot with Bollinger Bands, but something is nothing working as should be.

The lower band compared to MetaTrader4 graphs, should be arroud 1.4190, bur the value read from Binary Bot is 1.42 (rounded value only to 2 decimal numbers);
The price for the active was 1.4199, higher than real BB lower value (1.4190), but the is considering that it is lower, the BB returned value is 1.42.
That is why my strategy is not working.

For best understanding:

The values read from Metatrader:
Price = 1.4197 -> price value near the central BB line
BB upper = 1.4210
BB Lower = 1.4185
**
The values read from Binary Bot:
**Price 1.4197
BB upper = 1.42 (The Bollinger Band returns round value only. It is rouded down in this case)
BB lower = 1.42 (It rounded up)
The bot considered that the price was below the BB lower , what is not true.

I will really appreciate if anyone can help me.

Regards,

Paulo Rocha

**Comment by aminmarashi** [comment]
Thanks Paulo for reporting this. I'll fix this soon and let you know.

**Comment by aminmarashi** [comment]
@pamorell This problem should be fixed now.

**Comment by pamorell** [comment]
Thanks @aminmarashi . That´s great!
