### ISSUE TITLE
Can someone help with a MG idea?

### ISSUE THREAD

**Issue by ericcovich** [binary-com/binary-bot#1382]
Hi, i was thinking, about a bot that when it losses, the next entry would be the half of the 2nd Step of martingale

example

1
.50
.50

And if there are 2 or more losses in a row, the next step would be the half of total lost amount

The logic of the bot I am not sure, but this is a money management that I guess would works, because we could have more losses, with less money, well is my idea

I hope someone can help

**Comment by wilburforce83** [comment]
I don't see this working. Your win rate will be circa 50% so this will just money, slowly. You can never win back any losses, and each first loss will be more than twice the possible winning if the next trade is ITM

**Comment by ericcovich** [comment]
If we use a entry return of 50% or 40% of example, we would have more wins than losses, here is when the money mangement would work better

**Comment by binary-ex-machina** [comment]
@ericcovich and if you get 6 losses in row? Trying to divide martingale to not increase the stake so much will never be profitable on long run.
