### ISSUE TITLE
May be some error on putting barrier block

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1383]
![Opera Snapshot_2019-04-01_101335_bot binary com](https://user-images.githubusercontent.com/42480287/55304075-41929180-5467-11e9-8f7d-7261e88ca054.png)

**Comment by aaron-binary** [comment]
Hey @navneetsinh,

Thank you for reporting this issue, we've addressed the issue and will release a fix asap.

Regards,
Aaron
