### ISSUE TITLE
Which is default indicator in chart

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1384]
![Opera Snapshot_2019-04-01_104728_www binary com](https://user-images.githubusercontent.com/42480287/55305041-25ddba00-546c-11e9-8452-0af3c5124738.png)
please tell me which is rsi indicator configuration

**Comment by murali139** [comment]
oho no, why this happened

**Comment by binary-ex-machina** [comment]
@navneetsinh it's not an indicator, it's a zoom tool. If you move the block, you will see that it will show old ticks.

**Comment by navneetsinh** [comment]
ok, thanks, @binary-ex-machina
