### ISSUE TITLE
I need help with this simple strategy.

### ISSUE THREAD

**Issue by ricajoplin** [binary-com/binary-bot#1388]
I want to make a script Binary that when it has loss it try to recover 5 times in a row: example. bet 1 lost, try to recover 5 times of 0.20, if you lose in those 5 again, there try 5 times of 0.40.

I'm trying but I can not do it. NEED HELP

**Comment by ghossan86** [comment]
[ReadyDDCpound.zip](https://github.com/binary-com/binary-bot/files/3036528/ReadyDDCpound.zip)

**Comment by ghossan86** [comment]
I've same problem like you but haven't solving yet,  i hope issue you open will someone help it.. 
The bot just requires $10 balance
Recommendation : 
Without martingale
Compound level 3 to 5
Stake 7% to 25% of balance..
May be useful

**Comment by ricajoplin** [comment]
Thanks, buddy, is this your script profitable? What sets it apart from others? if I can I'll contact you.

**Comment by ghossan86** [comment]
You're welcome Yeah that bot i made by meself,  and everyday can take profit 50 to 100% of balance..
You can try it in virtual account first,  then you'll be very happy..
You can call me if there is problem of the bot.. 
I've other bot compound with martingale,  but requires at least $20 balance

**Comment by munzeer** [comment]
can you share  that bro

**Comment by ghossan86** [comment]
[ReadyMfDDCpound.zip](https://github.com/binary-com/binary-bot/files/3036731/ReadyMfDDCpound.zip)
Enjoy this life buddy.. 
"THE MORE WE SHARE THE MORE WE HAVE"

**Comment by munzeer** [comment]
it doesnt hve martingale bro

**Comment by munzeer** [comment]
thnks man

**Comment by ghossan86** [comment]
![safe marti](https://user-images.githubusercontent.com/47954272/55451232-46d51500-55fc-11e9-92e2-9bae59de750d.JPG)

**Comment by munzeer** [comment]
thank u again

**Comment by ghossan86** [comment]
You're welcome guys,  i'm glad be able to share an useful thing
