### ISSUE TITLE
Using Application API on Desktop App Development

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1399]
@aaron-binary 

Hey, I'm looking at building a native cross-platform app. I'd like to offer it for free with a small developer commission (like 0.25% - 1% or something that people will be happy to use) as offered in the Application API. Is there a way to integrate the markup without redirects? i.e. just use my appId in js and have the end users log in using their own API token?

I would like to have my appId in the code to verify to the server that my app is being used, which I am guessing marks all trades coming from that appId. Then instead of having the user login with OAuth, they just use their API token.

I can't find any details on how I could this, though I am sure it is probably fairly simple?

Thanks!!

**Comment by wilburforce83** [comment]
Could this be what I need to do? write my application and have it call for the bot script.js, which will call for input of user API token. 

Then use this to run that script with my app own app ID:

`ENDPOINT='wss://ws.binaryws.com/websockets/v3?l=en&app_id=<myappIdhere>' bot wilburforce83-magic-bot.js`

Thanks!

**Comment by aaron-binary** [comment]
Hey @wilburforce83,

> Is there a way to integrate the markup without redirects?

You are able to register an application and specify a markup percentage (between 0-5%) on the application registration page. You will then receive the set commission on all of the contracts sold through the application.

- https://developers.binary.com/applications/

You are able to ask for a user's API token and make trades on their behalf. Perhaps @binary-ex-machina can shed some light on this, as they have implemented a similar workflow.

Regards,
Aaron

**Comment by binary-ex-machina** [comment]
@wilburforce83 the way you put in the comment is the right one to use with the CLI bot.

`ENDPOINT='wss://ws.binaryws.com/websockets/v3?l=en&app_id=<myappIdhere>' bot script.js`

I think the best way to create a cross platform is to integrate with binary API library. You will have more control and more options

https://github.com/binary-com/binary-live-api

**Comment by wilburforce83** [comment]
@binary-ex-machina thanks man!! This is exactly what I was looking for!!
