### ISSUE TITLE
NECESITO AYUDA CON ESTE BOT...

### ISSUE THREAD

**Issue by Ares31** [binary-com/binary-bot#1401]
Hola este bot es de dígito diferente ej. da como predicción el numero 1 y si pierde vuelva a dar el numero 1, yo necesito q me ayuden a q de por ejemplo 1 de predicción y si pierde seleccione el 2 y si volviera a perder fuera el numero 3 y así sucesivamente... si selecciona el 5 y pierde q el próximo fuera el 6 y así iría... les agradezco si pueden ayudarme 

[Loop - Dígito Diferente (2).zip](https://github.com/binary-com/binary-bot/files/3045760/Loop.-.Digito.Diferente.2.zip)

**Comment by Ares31** [comment]
escribio cualquier cosa pero necesito q si da de prediccion el 1 el próximo sea el 2 y luego el 3 y asi sucesivamente

**Comment by romeo1911** [comment]
[Loop - Digito Diferente3.zip](https://github.com/binary-com/binary-bot/files/3045984/Loop.-.Digito.Diferente3.zip)

**Comment by Ares31** [comment]
Gracias t agradezco mucho la ayuda
