### ISSUE TITLE
 How to get graph data of the balls?

### ISSUE THREAD

**Issue by drezende89** [binary-com/binary-bot#1403]
![Capturar](https://user-images.githubusercontent.com/47386079/55628214-83cd1300-5786-11e9-8aed-ff790352a4e5.PNG)

**Comment by romeo1911** [comment]
Eu acho que eles são feitos usando o movimento "[zig zag](https://www.investopedia.com/terms/z/zig_zag_indicator.asp)". nós não temos isso. você poderia tentar usar "hma" + histograma macd

**Comment by binary-ex-machina** [comment]
te red dot is the lowest tick in latest 21 ticks. Blue dot is the highest of the last 21 ticks. You can get them with the blocks below. This graph is created using the last 21 ticks of the selected market.

![image](https://user-images.githubusercontent.com/34610787/55748862-19ca9d00-5a16-11e9-95e5-156eb390ac7f.png)

**Comment by drezende89** [comment]
> te red dot is the lowest tick in latest 21 ticks. Blue dot is the highest of the last 21 ticks. You can get them with the blocks below. This graph is created using the last 21 ticks of the selected market.
> 
> ![image](https://user-images.githubusercontent.com/34610787/55748862-19ca9d00-5a16-11e9-95e5-156eb390ac7f.png)

thank you very much @binary-ex-machina
