### ISSUE TITLE
Trading is unavailable at this time. Issue

### ISSUE THREAD

**Issue by mnaseem01** [binary-com/binary-bot#1408]
Hi All,
I notice for few weeks. In our country binary.com showing this message.? This is same for you.
![image](https://user-images.githubusercontent.com/13481811/55687057-ae32f200-5979-11e9-8d84-dae66ef48590.png)

**Comment by ZDEGLET** [comment]
Смотря какой рынок открыт для работы. Например форекс с валютными парами в данный момент не работает.

**Comment by mnaseem01** [comment]
No, It looks they stopped trading here. Could you please confirm your  side.

**Comment by aaron-binary** [comment]
Hey @mnaseem01,

From which country are you connecting?

Regards,
Aaron

**Comment by mnaseem01** [comment]
UAE

**Comment by aaron-binary** [comment]
Hey @mnaseem01,

We've closed down business in the UAE to remain compliant to applicable international laws governing online trading. Unfortunately, we can no longer offer our services to residents of the UAE.

Regards,
Aaron
