### ISSUE TITLE
How to get last digit count for last 50 ticks

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1410]
How can we get every digit count from last 50 ticks 
from last 50 ticks 
how many " 0 " as last digit count from last 50 ticks
same as other numbers. 1 to 9.

**Comment by AlienFly** [comment]
![zero](https://user-images.githubusercontent.com/36364199/55765414-4dd6aa00-5a78-11e9-84dd-27c7489f7acd.png)
