### ISSUE TITLE
Bot binary

### ISSUE THREAD

**Issue by Nguyenxuancuong0701** [binary-com/binary-bot#1412]
Please help me.
I want to pause after 3 consecutive losses. With a certain amount of pause (eg 1200 seconds). Attached files.
[binary-bot 9.zip](https://github.com/binary-com/binary-bot/files/3059010/binary-bot.9.zip)

**Comment by Dankettan** [comment]
ê ông add zalo trao đổi đi - 0343409719

**Comment by AlienFly** [comment]
@Nguyenxuancuong0701 

[#1412.zip](https://github.com/binary-com/binary-bot/files/3060149/1412.zip)

**Comment by Nguyenxuancuong0701** [comment]
Thanks very much

**Comment by Nguyenxuancuong0701** [comment]
Can you help me again?
After a pause, the start amount is $ 0.35 again
[3 loss.zip](https://github.com/binary-com/binary-bot/files/3061816/3.loss.zip)

**Comment by ZDEGLET** [comment]
ДЕРЖИ
[3-35 loss.zip](https://github.com/binary-com/binary-bot/files/3065261/3-35.loss.zip)

**Comment by ZDEGLET** [comment]
Nguyenxuancuong0701 ПОЧЕМУ 1200 СЕКУНД

**Comment by wanacharaya** [comment]
Need Help for Small Changes Binary bot Please Help Me 

i have a over under bot ( Need bolck trade this number 0 1 2 3 4 ) ( no trade )
i want to trade only this number 5 6 7 8 9 ( trade)
see this picture 
![b](https://user-images.githubusercontent.com/49775435/56414895-ac3a2e80-62a9-11e9-9fe5-42fb9b250682.JPG)


[myideabinary-bot.zip](https://github.com/binary-com/binary-bot/files/3097492/myideabinary-bot.zip)

**Comment by ReynaldoMartell** [comment]
Hello. Hope everybody are good. I wondering who can help me here? I found that on youtube video and i want to create as you can i on the screen. But it is hard. Can anyone help me?
![image](https://user-images.githubusercontent.com/53940485/62777490-00ae2780-baae-11e9-87a5-6aff5b9ffe28.png)

**Comment by anton-binary** [comment]
Hey @ReynaldoMartell,
Could you share the XML or describe what exactly you want to achieve? It's not quite obvious from the screenshot.
Thanks,
Anton

**Comment by ReynaldoMartell** [comment]
https://www.youtube.com/watch?v=KrNQhAeXP70

I just need guidance on how i create this strategy. Hope you will understand now. I have sent a video.

Config with:
Stake               0,45
martingale       2,1 
targetprofit     10
stoploss           30

Define Trade Options

Duraction        Ticks              5
Stake:              USD          Stake
