### ISSUE TITLE
End digits trigger on Vol 10/

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1417]
Does anyone know how to get the last 2 digits in Vol 10 as a trigger for Over/Under?
I did this successfully on Vol 100 as its only 2 digits after the decimal point.
But Vol 10 has 3 digits and I'd like to be able to input the numbers as a trigger where 'Z" is on Vol 10 - ie:  XXXX.X**ZZ** ?

I have a 'make list from text' so can type in any sets of 'ZZ' numbers as a trigger but think the issue maybe here : 
![block1 bot](https://user-images.githubusercontent.com/43829090/55940335-cf286b00-5c37-11e9-94ea-e360ba3f7fc5.JPG)

**Comment by AlienFly** [comment]
![lt](https://user-images.githubusercontent.com/36364199/55994992-fe80bb80-5cbb-11e9-8f14-c5fe3dde1218.png)

**Comment by buckman1974** [comment]
Thank you @AlienFly !

i will have to try this next week, so hopefully this ticket isn't closed by then!  :)

**Comment by buckman1974** [comment]
Thank you @AlienFly 

I have programmed your section into the bot and have included it here. It works as your screenshot shows, but I think I may have 'broken' another part?

Basically I was trying to build a bot that followed this strategy as depicted here with "Over 0" :
https://youtu.be/AV4LOUg56j0

My bot is here, and I think is 90% correct? I am trying to get the 'make list from text' numbers as triggers. This was working fine, but now misses the digits as they appear??

Here is my bot : 
[Over 0 - Vol 10.txt](https://github.com/binary-com/binary-bot/files/3088358/Over.0.-.Vol.10.txt)

**Comment by wanacharaya** [comment]
Need Help for Small Changes Binary bot Please Help Me 

i have a over under bot ( Need bolck trade this number 0 1 2 3 4 ) ( no trade )
i want to trade only this number 5 6 7 8 9 ( trade)
see this picture 
![b](https://user-images.githubusercontent.com/49775435/56414895-ac3a2e80-62a9-11e9-9fe5-42fb9b250682.JPG)


[myideabinary-bot.zip](https://github.com/binary-com/binary-bot/files/3097492/myideabinary-bot.zip)
