### ISSUE TITLE
Help with MACD Histogram

### ISSUE THREAD

**Issue by Rafaelwebs** [binary-com/binary-bot#1420]
I would like to compare the value of the previous histogram (position 2) with the previous value (position 3). The current value of the histogram would be position 1. If histogram value 2 is higher than 3 purchase Rise. If histogram value 2 is lower than 3 purchase Fall . Can anyone help me?

**Comment by ZDEGLET** [comment]
А где сам скрипт? Чего сравнивать корову с лошадью?

**Comment by romeo1911** [comment]
![h](https://user-images.githubusercontent.com/44220114/56006135-e6ca2700-5cfd-11e9-8fe9-fd7cbedd65a4.png)

**Comment by Rafaelwebs** [comment]
Awesome. Thanks @romeo1911
