### ISSUE TITLE
Problem in using different time intervals (Maybe robot bug)

### ISSUE THREAD

**Issue by Zaxushitso** [binary-com/binary-bot#1422]
Hi,
I'm trying to implement a strategy that verifies the price treatment near the SMA in some different time intervals. The problem is changing the SMA output to incorrect numbers after about 5 minutes!!!!
I set one SMA with 1min candle stick time interval, one 2min, one 3min and one 5min . At first it is OK but the numbers goes wrong soon. (If i stop the bot and run it again the numbers become correct!!! :)   )
When you define more than one SMA ''that their time intervals are different'' this issue happens. but there is no problem with several SMA's with  same time interval.

please help me to solve this problem
![Opera Snapshot_2019-04-12_215232_www binary bot](https://user-images.githubusercontent.com/48320076/56054921-63e0b500-5d6d-11e9-92ba-6d9ea7710413.png)

**Comment by Zaxushitso** [comment]
I test the problem with other indicators and also every simple calculations related to different time intervals and the problem exists.
I mean whenever you are using more than ONE TIME INTERVAL the calculations goes wrong after some minutes. I think this is a bug in robot. 
maybe it is because of the main time interval that is set in the FIRST BLOCK (define your trade contract)

please help to solve this problem

**Comment by aaron-binary** [comment]
Hey @Zaxushitso,

How do you determine the values are incorrect? Could you assist us and provide a video of these incorrect values being generated (e.g. with a chart on the side)?

Regards,
Aaron

**Comment by Zaxushitso** [comment]
> Hey @Zaxushitso,
> 
> How do you determine the values are incorrect? Could you assist us and provide a video of these incorrect values being generated (e.g. with a chart on the side)?
> 
> Regards,
> Aaron

Hi,
Sure. I'll take a video and send here but it was so easier to just do like what I did (the screenshot)  :)

**Comment by Zaxushitso** [comment]
> Hey @Zaxushitso,
> 
> How do you determine the values are incorrect? Could you assist us and provide a video of these incorrect values being generated (e.g. with a chart on the side)?
> 
> Regards,
> Aar

**Comment by Zaxushitso** [comment]
> Hey @Zaxushitso,
> 
> How do you determine the values are incorrect? Could you assist us and provide a video of these incorrect values being generated (e.g. with a chart on the side)?
> 
> Regards,
> Aaron

Hi, Please verify the videos (Links are attached). Thank you for your kind attention.

https://ufile.io/q9pbjp8u
https://ufile.io/3f6w9akp

**Comment by aaron-binary** [comment]
Hey @Zaxushitso,

Thanks for uploading the video, it helps a lot!

The values may differ between both Binary Bot and SmartCharts because they're using two separate WebSocket connections, one connection may retrieve data before the other so values will differ slightly. We understand this isn't the most optimal behaviour so we will investigate if we can improve this.

Regards,
Aaron

**Comment by Zaxushitso** [comment]
Thank you @aaron-binary 
You are right but I think it's more than a slight difference .
If you let the bot to go on the values will differ a lot. For example you will see 17pip value for a 0.5 pip one minute candle (Volatility100)

I appreciate your attention and hope your team can fix the problem
Best Regards
