### ISSUE TITLE
Bot freezes.

### ISSUE THREAD

**Issue by SWCotor** [binary-com/binary-bot#1423]
Hello. My bot freezes. And not only the one that I send to you now. At first, I did not notice this, only noticed that the bot did not enter into transactions for a long time, although it should. Then I complicated the bot with text blocks, and found that at some point, the bot simply stops updating the values ​​of the specified variables.
I tried to add blocks "repeat this block every second", and others. However, it does not help. Help to set it up and subsequent bots so that they do not hang, please. I tested the bot on different computers and browsers. Different pairs. Hangup happens randomly. The bot freezes over a period of time - from 1 hour to 1-2 days. **It is written,
that the bot works, but in fact it is frozen** = (.

https://yadi.sk/d/T3yoArpOxAi7HQ
https://yadi.sk/d/VYi0CmdR8sg4xw
https://yadi.sk/d/RahJJNQ7admeig

Bot works on Price Action.

**Comment by ZDEGLET** [comment]
В какой период он должен работать? мне кажется дело в неправильной установки  времени.

**Comment by romeo1911** [comment]
[v.8.1(12321).zip](https://github.com/binary-com/binary-bot/files/3077446/v.8.1.12321.zip)
я даю ему диету
btw i dunno if is correct or not, but the candle from the last 3 is opposite in comparison with the 4 and 2. i remake your logic how was.
return set correctly your market and time trading.
in my case my bot stop update the values too and continue to buy or sell without look at the logic but not in 1 hour.
try set a "take profit" because is not supposed to use the bot for 24 houres and i hope that now happends less often. do svidaniya

**Comment by SWCotor** [comment]
Можно и не ставить время, он тоже зависнет. А вот информация что бот не поддерживает работу больше 24 часов интересная информация. А смысл в нем тогда? Если его перезапускать постоянно, это уже ручная торговля, и придется перезабивать новую ставку по "мартину". Смысл бота как раз в том чтобы он работал круглосуточно хотя бы полную неделю. А вообще время я прикрутил к нему, потому что сделана идиотская остановка бота, когда вылетает ошибка: "контракты на данный период не предлагаются временем меньше 5-и часов". Если бы научить бота игнорировать данную ошибку и это ограничение по времени можно убрать.

**Comment by SWCotor** [comment]
А можно как то добавить алгоритм перезапуска бота с сохранением некоторых текущих переменных(мартингейл и так далее), чтобы он работал 24/7.

**Comment by romeo1911** [comment]
не может работать с "волатильностью или быком / медведем"? у вас не будет проблемы с контрактом. Это нормально, если вы выбираете второстепенную пару, может быть, ночью, что контракт будет длиться менее 5 часов, как если бы вы выбирали товары, так долго контракт

**Comment by SWCotor** [comment]
romeo1911. 
1) По поводу вашего бота: он завис через 5 мин после включения. Я не шучу, Могу приложить лог. Проработал он с 07:07 до 07:11(GMT +4).
2)Проблема **не в волантильности**. Проблема в том что он останавливается! И пока я сплю он не торгует, пока я не встану утром и не запущу его в ручную. Бот не умеет игнорировать эту ошибку. Вот в чем проблема.

**Comment by romeo1911** [comment]
soo strange

**Comment by AlienFly** [comment]
@SWCotor 

1. У тебя в боте слишком много лишних операций. Частично я их поправил, но на твоем месте отказался бы и от уведомлений и от времени.
2. Теперь об уведомлениях. Они по сути нужны только на этапе предварительного тестирования, для проверки отработки заложенного алгоритма. После этого они только мешают, забивая кеш браузера, что при длительных запусках бота чревато подвисаниями и различными глюками.
3. Не используй хром и другие браузеры на его основе, с некоторых пор он начал отвратительно работать с конструктором. Из собственного опыта firefox будет оптимальным для работы.

[#1423.zip](https://github.com/binary-com/binary-bot/files/3082233/1423.zip)

**Comment by SWCotor** [comment]
Проверю, потом отпишусь.

**Comment by SWCotor** [comment]
@AlienFly
Красивый алгоритм, но не правильно работает. Свечи по PA выбирает не правильно.
Вот так:
[url=https://radikal.ru][img]https://c.radikal.ru/c43/1904/08/1f16f5e28e5f.jpg[/img][/url]

А должен вот так:

[url=https://radikal.ru][img]https://b.radikal.ru/b39/1904/fa/16ab34168037.jpg[/img][/url]

**Comment by SWCotor** [comment]
И кажется бот завис. Я запустил ваш алгоритм без изменений для теста. Уже более 8 часов он не торгует. Чувствую что завис, потому что вижу подходящие ситуации для входа на графике бота по паре USDCHF. Последнее сообщение из лога 4:37(GMT +4) 18.04.19.
Binary высказали замечание, что нужен ооочень мощный комп для работы бота, может в этом причина. У меня AMD-FX-8370 Eight, 12Gb оперативы . Думаю дело не в этом.....
Браузер кстати да, тоже использую Mozila. Хром хреново работает, давно подметил.
