### ISSUE TITLE
Momentum divergence

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#1427]
Can someone build a script that identifies momentum divergence with price that ocur in interval of 300ticks.

This is formula for momentum indicator:
Momentum = (Current close price / Lagged close price) x 100

**Comment by romeo1911** [comment]
more or less have to be: momentum = lasttick / (in list "ticklist" get from the end "300") * 100

**Comment by tymu** [comment]
@romeo1911 it has do be an array list to compare indicator value with price
