### ISSUE TITLE
Binary Bot v20190416: Introducing Google Drive Support

### ISSUE THREAD

**Issue by aaron-binary** [binary-com/binary-bot#1429]
# Take your bot anywhere, with Google Drive
Trading on Binary Bot? 

We're happy to let you know that you can now save your strategies on your Google Drive. 

Your bots are within reach anywhere, anytime — on your computer, smartphone, or tablet. Plus, they're all backed up and safe for when you need them.

Here's a video on how to use your Google Drive with Binary Bot. 

- https://www.youtube.com/watch?v=mi18spqE7R4

Log in via Google to get started. 

If you have any queries, please get in touch with us

**Comment by ZDEGLET** [comment]
отлично

**Comment by hotmatrixx** [comment]
Hi, Team:
First Post! (expect more....)
Thanks for adding the GD support, it's great (and I dont have to run my backup FTP software anymore for this.)

Feedback on that in the first instance;
#1 - its great.
#2 - Could we please create a 'main' BinaryBot folder in the root of my G-Drive that everything then gets dumped into as subfolders? I got a bunch of 'new' folders in a place that I really don't want them.
#3 - I think that the 'save button should go to my PC, and the G-Drive button should save to G-Drive. Maybe add another button, with a Gx or something on it for disconnecting. I keep clicking the wrong things as they are in slightly unintuitive places.


BUT THANKS! :)


I have used the bot extensively and have quite a bit of feedback. I have just created a GitHub account so I can start with my input. Most of it is/will be feedback for QoL stuff as a 'power user'.

**Comment by buckman1974** [comment]
Thank you for this @aaron-binary but my Binary-Bot page, when i want to save, still only has "Save to Collection" and no mention of Google Drive saving?

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Thanks for the feedback, it helps a lot! 

> Could we please create a 'main' BinaryBot folder in the root of my G-Drive that everything then gets dumped into as subfolders? I got a bunch of 'new' folders in a place that I really don't want them.

Could you elaborate on this? We went for this behaviour because if a user didn't have any folders in their Google Drive, they wouldn't be able to select a save location. Are you saying that multiple folders are created on your end? I'd love to hear about your thoughts on how to improve this.

> I think that the 'save button should go to my PC, and the G-Drive button should save to G-Drive. Maybe add another button, with a Gx or something on it for disconnecting. I keep clicking the wrong things as they are in slightly unintuitive places.

Good point, I'll discuss this with the team :-)

---

@buckman1974,

This may have to do with your browser caching the files downloaded from our server. Please clean them and you should be good to go.

- **Chrome**: https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

- **Firefox**: https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

Please report back if you're still not able to use the Google Drive feature.

Regards,
Aaron

**Comment by romeo1911** [comment]
Hi @aaron-binary please can u check bot.binary.me? still not cames out the connection to google drive ( but on the beta version and .com there is)

**Comment by buckman1974** [comment]
Hi @aaron-binary , I have cleared the cache and cookies and still nothing with Google Drive as a potential save destination?

**Comment by aaron-binary** [comment]
Hey @romeo1911 & @buckman1974,

We're updating those domains as we speak. Sit tight! 😄

Regards,
Aaron

**Comment by romeo1911** [comment]
all is working, thanks

**Comment by hotmatrixx** [comment]
Thanks for the feedback, it helps a lot!

    Could we please create a 'main' BinaryBot folder in the root of my G-Drive that everything then gets dumped into as subfolders? I got a bunch of 'new' folders in a place that I really don't want them.

Could you elaborate on this? We went for this behaviour because if a user didn't have any folders in their Google Drive, they wouldn't be able to select a save location. Are you saying that multiple folders are created on your end? I'd love to hear about your thoughts on how to improve this.
---------------------------------
Sure thing! 
To try and clarify.

I have folders in my G drive main / root of G~
Cars (has folders like photos, insurance etc)
Paperwork
Historical
Computer Stuff
.... and so on.

and I'd like 1 with Binary bot. When BB was given access to my G~ it added
Binary-Stratagies
Bank Statements
model data
dropdowndata
Toast

and a bunch of others. into my root directory.
You're welcome to invade my G~ drive, but please make a root folder, first - and all of these as subfolders

If that doesn't make sense, I'll send photos, I just.. don't really want to.

**Comment by aaron-binary** [comment]
@hotmatrixx,

Thanks for getting back to me. Those folders aren't created by Binary Bot, only the **Binary Bot - Strategies** folder should have been created. 

- Are you using a language other than English?
- Would you be able to send us the screenshots via binarybot@binary.com with reference #1429?

Regards,
Aaron

**Comment by ZDEGLET** [comment]
aaron-binary а вы можете сделать чтоб в боте на рынке форекс можно было ставить время экспирации в секундах. на данный момент есть тики, минута, час и день

**Comment by aaron-binary** [comment]
Hi @ZDEGLET,

We're not planning on adding **second**-durations to our Forex markets.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
> 
> 
> @hotmatrixx,
> 
> Thanks for getting back to me. Those folders aren't created by Binary Bot, only the **Binary Bot - Strategies** folder should have been created.
> 
>     * Are you using a language other than English?
> 
>     * Would you be able to send us the screenshots via [binarybot@binary.com](mailto:binarybot@binary.com) with reference #1429?
> 
> 
> Regards,
> Aaron

I replied via email; just thought I should update this thread as well - those folders were created by another application, and are normally hidden from me, was not caused by binarybot.

good to know i have hidden files on my Gdrive, though!
