### ISSUE TITLE
notifications QoL [Feature Request]

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1431]

**Comment by hotmatrixx** [comment]
Could we have the ability to make a 'custom timeout' for notifications?
Could we have a 'clear all' for notifications?

Reason being that I'm running a bot that currently bids on every tick, it has 10 notifications per tick, and they stack all up the screen with duplicates from the previous cycle.

It's all super handy info, but it just looks really untidy if they stack up constantly, I'd like them to 'refresh' each tick/ cycle (in case I set my run to 3 minutes, for instance) - I'd like them to persist until I want them gone.

also, if they are running in a second tab, they cascade for a LONG time when you switch back to it.

**Comment by Zaxushitso** [comment]
Hi,
If refreshing the values is not much important on every tick you can put your notify commands in a   RUN AFTER  #  SECONDS  function and set the number to 2 seconds 
![Opera Snapshot_2019-04-20_184032_www binary bot](https://user-images.githubusercontent.com/48320076/56458473-42e71800-639c-11e9-9cb3-b84abc1256fd.png)

Do not set it more than 2 seconds because there is a problem with this function and it forces  the whole bot processes # seconds even if you're just using it for notify commands. I will report this problem with video document soon but already you can use it as i explained.

**Comment by hotmatrixx** [comment]
> 
> 
> Hi,
> If refreshing the values is not much important on every tick you can put your notify commands in a RUN AFTER # SECONDS function and set the number to -2- (every tick) or -4- (every other tick) seconds
> ![Opera Snapshot_2019-04-20_184032_www binary bot](https://user-images.githubusercontent.com/48320076/56458473-42e71800-639c-11e9-9cb3-b84abc1256fd.png)
> 
> Do not set it more than 2-4 seconds because there is a problem with this function and it forces the whole bot processes # seconds delay even if you're just using it for notify commands. I will report this problem with video document soon but already you can use it as i explained.

That's actually a pretty good tip,
however in my case, I use the notifications for bugtesting, and so need them every bid (the reason I am running ticks is to get more results in less time for bugtesting! I plan on using my stratagies on.... longer timed markets.)

**Comment by Zaxushitso** [comment]
Oh, Yes
So maybe this trick (In ScreenShot) can help you, else you should wait till they add the feature ...

![Opera Snapshot_2019-04-24_154055_www binary bot](https://user-images.githubusercontent.com/48320076/56655373-d2940b80-66a7-11e9-9b08-ba9eb65411ef.png)

**Comment by hotmatrixx** [comment]
Yes, I saw it, didn't really bother with it earlier, kind of forgot about it.

Made the effort.  its definitely more compact. takes a tiny bit longer to find the info I want, but probably because I'm used to the  first one.

will help with spam, for sure.
thanks!
PS: the bot always loses for the first 40 minutes or so. As this is a 'new' run with the new notifications (hours run .33 VS 15h) it hasn't started making gains yet....

![image](https://user-images.githubusercontent.com/49715381/56702863-4a227300-675a-11e9-9ee3-32729e6ba791.png)

**Comment by hotmatrixx** [comment]
:)

I see you're working on it @aaron-binary 
happyness.
