### ISSUE TITLE
Need Help for Small Changes Binary bot Please Help Me

### ISSUE THREAD

**Issue by wanacharaya** [binary-com/binary-bot#1433]
Need Help for Small Changes Binary bot Please Help Me 

i have a over under bot ( Need bolck trade this number 0 1 2 3 4 ) ( no trade )
i want to trade only this number 5 6 7 8 9 ( trade)
see this picture 
![b](https://user-images.githubusercontent.com/49775435/56414895-ac3a2e80-62a9-11e9-9fe5-42fb9b250682.JPG)

[myideabinary-bot.zip](https://github.com/binary-com/binary-bot/files/3097492/myideabinary-bot.zip)

**Comment by romeo1911** [comment]
the entry spot is the next tick after your bot send the signal to purchase, can put a logic for try to predict the last digit, but who knows the future...

**Comment by wanacharaya** [comment]
brother We will be able to do 0 1 2 3 4 for no trade i wa,nt block open trade this number

only trade 5 6 7 8 9  last digit number 

comming last digit number 5 6 7 8 9 open  trade

last digit number  0 1 2 3 4  no open trade   
sorry my bad english  i can,t manage in englsh very much

**Comment by James-Ngigi** [comment]
I have made your bot, but you have to understand that the entry spot on the binary servers is different to what the signal entry by the bot is provided. It will always be late by probably a tick or something like that
Look at the pic below, it's a trade made by your strategy based on what you have requested for.
![Annotation 2019-04-21 114313](https://user-images.githubusercontent.com/28121458/56467681-d23b0c80-642a-11e9-8a12-4d238dfa33ff.png)
You can see it get's the signal to trade when the digit is 7, but the entry spot will be on the next tick
Here is your bot

[My idea Binary-Bot.zip](https://github.com/binary-com/binary-bot/files/3101047/My.idea.Binary-Bot.zip)

**Comment by wanacharaya** [comment]
dear Brother James-Ngigi  

thank you so soooooooooooooo   ....... much  hellp me wish you all the best god bless you

**Comment by James-Ngigi** [comment]
@wanacharaya welcome.

**Comment by whitekingcrypto** [comment]
hi, can u share the updated bot I try from my end.The one Mr.Ngugi re created for 56789

**Comment by mokoenjd** [comment]
Hi guys,

Can someone please create a bot for me using these following information:

last digit: 40 50 60 70 (Rise) blue
Last Digit 31 21 11 01 (fall) Red

Volatility 100 Index
5ticks
