### ISSUE TITLE
Digit Stats 0-4 and 5-9

### ISSUE THREAD

**Issue by Brishe** [binary-com/binary-bot#1435]
Hi Guys,

Is there a way to create stats list where the digits 0-4 or digits 5-9 is counted from the last 100 ticks?

For example:
1. Digits 0-4 = 55%, Digits 5-9 = 45%
2. Digits 0-4 = 40%, Digits 5-9 = 60%

Just thinking of using it for a strategy on digits.

Thanks for your help.

**Comment by James-Ngigi** [comment]
Yes there is. Check it out here : https://youtu.be/JJX9hMUQ6GM

**Comment by Brishe** [comment]
@James-Ngigi, this is for Digit Differ strategy. I'm thinking of using Digit Over 4 Under 5 strategy. So I have to determine what's the combined number of ticks for digits 0-4, or digits 5-9 on the last 100 ticks.

![image](https://user-images.githubusercontent.com/46435102/56470652-5ae19900-647b-11e9-8e10-dda20b54665b.png)

For example:

0 - 15%
1 - 9%
2 - 9%
3 - 11%
4 - 11%
5 - 7%
6 - 8%
7 - 16%
8 - 9%
9 - 5%

Total of 0 - 4 = 55%
Total of 5 - 9 = 45%

So strategy is Digit Under 5

Can this logic be created in binary bot?

**Comment by romeo1911** [comment]
if 50% skip trade or repeat the last trade? martingale? stop at some income?

**Comment by romeo1911** [comment]
if u put martingale to 0 will not use it, 4 the rest i think is clear
i suggest to change 100 ticks with 10
![Untitled](https://user-images.githubusercontent.com/44220114/56486510-01707d00-6502-11e9-8aa7-da2bd53e2a74.png)
[ud2.txt](https://github.com/binary-com/binary-bot/files/3102440/ud2.txt)

**Comment by Brishe** [comment]
@romeo1911, thanks for this. Bot's working fine. Will test it for consistency (fingers crossed).

**Comment by Brishe** [comment]
@romeo1911, can this be used predicting 2 digits, like 4 and 5?

**Comment by romeo1911** [comment]
what u mean? if <4 purchase down or if >5 purchase up?
