### ISSUE TITLE
Need Help! Candle Pattern bot

### ISSUE THREAD

**Issue by iNuii** [binary-com/binary-bot#1442]
Hi guys,

I got a binary bot with candle pattern strategy, but the bot is freezing after last result is Win
it's not trade again, please help
[binary-bot-candle-loop.xml.zip](https://github.com/binary-com/binary-bot/files/3103452/binary-bot-candle-loop.xml.zip)

**Comment by ZDEGLET** [comment]
СКРИПТ ВООБЩЕ УБИТЫЙ. ГДЕ ИСХОДНИК?

**Comment by reggie66** [comment]
[binary-bot-candle-loop CORRECTED.xml.zip](https://github.com/binary-com/binary-bot/files/3105214/binary-bot-candle-loop.CORRECTED.xml.zip)


YOU CAN CONTACT ME FOR ANY ISSUES
gogopeters@yandex.com

**Comment by iNuii** [comment]
@reggie66 thank you very much, bot working well.
