### ISSUE TITLE
profit $330 last digit after night with split martingale prediction over 1

### ISSUE THREAD

**Issue by rednumber686868** [binary-com/binary-bot#1455]
Hi all, please see video : https://www.youtube.com/watch?v=U5g54M9CL0A
I test prediction purchase over 1 and have good profit after 1 night, so now I want to optimize probablity ( if frequency no. 0 + 1 in 4 hours > 22%, then 4 hours later the bot will purchase over 1). Please help me code, thanks

**Comment by binary-ex-machina** [comment]
You can't analyse 4 hours of digits, the maximum number of digits you can get is 1000 (which is close to 33min) If you keep inserting these digits into a list, the webpage will became unresponsive after 1 hour or so, because the calculation will be heavier each tick.

**Comment by rednumber686868** [comment]
> You can't analyse 4 hours of digits, the maximum number of digits you can get is 1000 (which is close to 33min) If you keep inserting these digits into a list, the webpage will became unresponsive after 1 hour or so, because the calculation will be heavier each tick.

Many thanks @binary-ex-machina
