### ISSUE TITLE
Need code for money management method

### ISSUE THREAD

**Issue by rednumber686868** [binary-com/binary-bot#1461]
<img width="857" alt="Screen Shot 2019-04-30 at 11 04 11 AM" src="https://user-images.githubusercontent.com/50037759/56940325-d4dae780-6b37-11e9-99e3-7ffe349909d3.png">

Hi all, please help me code as folowing:

"abl": average bet loss;

"abw": average bet win;

With probability 50:50, the bot will run after 1000 trade ( often 500 loss and 500 win);

And my target is:

abl : $5 x 500 loss trade;

abw : $5.5 x 500 win trade ( from $1 trade start);

highest stake may be from $20 to $25;

lowest balance may be from -$100 to -$200;

I don't know way to code "after 6 or 8 consecutive losing, the stake will be "abl x 1.1";
Thanks

**Comment by hotmatrixx** [comment]
Hi!
Interesting bot! it's a pity I can only see part of it, it looks similar to a strategy I am trying to make at the moment.

I have made a code snippet that will hopefully help you to do what you wanted "after six CONSECUTIVE losses, make
' stake=abl x 1.1'

I don't really understand most of what else you are trying to say, sorry.

If you need any further help, I'd probably need to see the rest of the bot. I'd be happy to help through Private Message if you don't want to share with everyone else at this time... or at all....

 if thats

a. possible
b. not against any rules here
c. ok with you.

![image](https://user-images.githubusercontent.com/49715381/56950105-c963dc80-6b88-11e9-9403-86eb29b66e23.png)

**Comment by ZDEGLET** [comment]
ПРИШЛИ СКРИПТ РОБОТА ПОЖАЛУЙСТА ПОСМОТРИМ:)

**Comment by rednumber686868** [comment]
Many thanks @hotmatrixx i will message you after a few day, the current bot is running unstable and i have to adjust some variable. Thanks
