### ISSUE TITLE
Defining Trade During Phase 2 [Feature Request]

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1462]
Hi, guys!
Another user here requested help with making a bot, that seems to have shown up a shortfall that I've actually noticed before, but not needed to pay much attention to previously.

I thought I'd bring it to your attention now that it's been brought to mine, again;
This particular chap would like to basically define the Trade (matches/differs) based on the Last Tick; so he'd like to watch until the Last Tick repeats, ### then Define the _Trade Prediction_, Then Purchase.

I'm wondering if the bot could be "changed" so that "watch and purchase your trade" (the repeating cycle) was phase 1, then "define your trade " was phase 2 - and programatically, it then purchases the trade at the bottom of that point... then have phases 3&4 as per normal.

 I "don't think" it will actually affect any already exsisting scripts that are currently written? however it will open up new strategies to become available as you'll be able to change your Trade Definitions on the tick, instead of having to wait a full cycle as we do now.

This is the other discussion, for reference. ---> https://github.com/binary-com/binary-bot/issues/1460#issue-438260637
I've kind-of made a workaround, but it's not quite what he wanted, I don't think. I made it so that it sets the prediction, then waits for a tick to match it before buying. He wants to wait until ticks match a rule, then set the Definition, and Buy on the coming Tick.

**Comment by ZDEGLET** [comment]
Я ДУМАЮ ЧТО ВСЕ ТИКОВЫЕ РОБОТЫ ЭТО КАЧЕЛИ. КУДА ТРЕНДИК  ПОЙДЕТ НЕ ИЗВЕСТНО. ВОТ НА СВЕЧАХ ЕЩЕ МОЖНО ПРЕДПОЛОЖИТЬ ПО ИНДИКАТОРАМ.

**Comment by ZDEGLET** [comment]
ТАК Я ИСПОЛЬЗУЮ РОБОТА В РУЧНУЮ. ГЛАВНОЕ ПОПАСТЬ В ТРЕНД. ПОСЛЕДНЮЮ СДЕЛКУ ОН ПРОИГРАЛ И ОСТАНОВИЛСЯ НО ПРИ ЭТОМ Я В ПЛЮСЕ.
![2019-04-30_16-50-44](https://user-images.githubusercontent.com/36106343/56966745-6bbf9800-6b68-11e9-83b7-34e17ffcf337.png)

**Comment by hotmatrixx** [comment]
@aaron-binary hey mate, 
as far as I can tell, the russian chap above is basically talking about how his bot makes consecutive wins... which has literally nothing to do with this thread.

also, he's put it all in russian, in ALL CAPS, as far as I can tell... in an obviously english-speaking thread. I have no issue with any other language or culture participating, but if the OP posts in a particular language, the participants (IMO) should be kind enough to continue in the same language.

Could you remove the unrelated comments from the thread? You may wish to check other messages from our Russian friend above, as he may have spammed??? (it seems like it to me) other threads as well.

I followed him to his Repository, trying to make sense of his comments (Google translate is garbage) where he clearly has a comprehensive grasp of the english language.

If I am out of place, feel free to let me know. It feels like he's trying to sell me on the idea of his fork/branch of his bot.

**Comment by hotmatrixx** [comment]
just found this Russian chap https://github.com/ZDEGLET on the next thread. Somone asking for help with thier script... and ZDEGLET basically is saying something like "come look at my bot instead" here: https://github.com/binary-com/binary-bot/issues/1461#issuecomment-488120510
