### ISSUE TITLE
Summary Window (QoL/Feature)

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1463]
When The Summary Opens, I can't see all of the last column by default.

Either we need to make the window slightly wider overall, or possibly pull the Reference Number in a bit?

Cheers.
![image](https://user-images.githubusercontent.com/49715381/56954648-69266800-6b93-11e9-9399-fe5445838004.png)

**Comment by ZDEGLET** [comment]
МЫШКОЙ СДЕЛАЙ СТОЛБЦЫ МЕНЬШЕ

**Comment by romeo1911** [comment]
in the first line  (timestamp/reference/etc) u can move all the column

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Thank you for your suggestion, we're in the process of revamping the way transactions are displayed. I've never come across this behaviour, what browser are you using?

Regards,
Aaron

**Comment by hotmatrixx** [comment]
> 
> 
> in the first line (timestamp/reference/etc) u can move all the column

I know that I can move it, thanks.
My point is, that I shouldn't have to. I realise that for most people they see a 'whole image', else this would have been fixed, long ago, I'm sure.

**Comment by hotmatrixx** [comment]
> 
> 
> Hey @hotmatrixx,
> 
> Thank you for your suggestion, we're in the process of revamping the way transactions are displayed. I've never come across this behaviour, what browser are you using?
> 
> Regards,
> Aaron



> 
> 
> Hey @hotmatrixx,
> 
> Thank you for your suggestion, we're in the process of revamping the way transactions are displayed. I've never come across this behaviour, what browser are you using?
> 
> Regards,
> Aaron

Firefox, V66

I think I have your email address, I'll send you the Troubleshooting/diagnostic that gives you a

I've also logged into the bot from another PC, also on FF, and it seems to do the same thing.
I've probably got the same custom setting on both machines that's messing with it.

ll my addons/settings/javascript custom code/etc. I don't feel like putting that on the WWW.
