### ISSUE TITLE
Tick Stats (Rise and Fall)

### ISSUE THREAD

**Issue by Brishe** [binary-com/binary-bot#1464]
Hi guys,

Is there a way to create stats list where directions Rise and Fall are counted from the last 100 ticks?

For example:

    Rise = 55%, Fall = 45% ===> Purchase RISE
    Rise = 45%, Fall = 55% ===> Purchase FALL

Thanks for your help.

**Comment by romeo1911** [comment]
[100.txt](https://github.com/binary-com/binary-bot/files/3135174/100.txt)
my browser with 100 ticks get frozen, if happens to you too change to a lower value (maybe 10)

**Comment by hotmatrixx** [comment]
to be honest I'm not even sure what "direction=rise" is actually measuring. Is it the overall trend? Is it a trend over a certain period of time? Is it considering the last candle only? Is it considering the last tick only?
any of those things is easy to make a bot for, however the last hundred rise and falls are not actually measured in their own database. If I knew what they were actually quantifying, I'm pretty sure it would be a trivial matter to make a bot that does the thing that you are asking.

**Comment by Brishe** [comment]
@romeo1911, mine's working well. Maybe because you're using it on forex. I'm using it on Volatility 100 Index.

**Comment by hotmatrixx** [comment]
If it helps at all, and because it 'came from here', I asked and found out that Direction=Rise/Fall is based on ticks, which I guess you probably already realise.

It was another thread I opened, here... if it helps at all.

https://github.com/binary-com/binary-bot/issues/1465#issue-439427793
