### ISSUE TITLE
what does direction = Rise actually mean? (UI/QoL)

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1465]
I'm not even sure what "direction=rise" is actually measuring. Is it the overall trend? Is it a trend over a certain period of time? Is it considering the last candle only? Is it considering the last tick only?

some kind of flavour text that explains this would be a nice little tweak, thank you

**Comment by nextnaro** [comment]
Current tick compare to previous tick price. if not mistaken.

**Comment by AlienFly** [comment]
@hotmatrixx 

You can verify this by using internal notifications

![r-f](https://user-images.githubusercontent.com/36364199/57075747-5a08fc80-6cf0-11e9-816a-49232c692b88.png)

**Comment by aaron-binary** [comment]
@hotmatrixx,

> some kind of flavour text that explains this would be a nice little tweak, thank you

Thanks for the feedback :-)

Regards,
Aaron

**Comment by hotmatrixx** [comment]
> 
> 
> @hotmatrixx,
> 
> > some kind of flavour text that explains this would be a nice little tweak, thank you
> 
> Thanks for the feedback :-)
> 
> Regards,
> Aaron

Thanks, and no problem :)

**Comment by hotmatrixx** [comment]
> 
> 
> @hotmatrixx
> 
> You can verify this by using internal notifications
> 
> ![r-f](https://user-images.githubusercontent.com/36364199/57075747-5a08fc80-6cf0-11e9-816a-49232c692b88.png)

oh and thank you for making an effort to "prove" this. Easy to do, I know, but it's nice to see.
I wasn't in the mood to do it myself, so it's nice that someone has :)
