### ISSUE TITLE
Add sell option to bot

### ISSUE THREAD

**Issue by ravihansa1** [binary-com/binary-bot#1468]
I need to add sell option to my bot. When we place a call or put Oder in volatility index (think we put 10$ call Oder) in long time(30 minute). If it exceed we expected profit (think i need 2$ profit on that trade) trade auto close and put another call or put Oder in 30 minute .i want to make this type of bot please help me.

**Comment by Tharumax** [comment]
try this 
[SELLING BOT.zip](https://github.com/binary-com/binary-bot/files/3144678/SELLING.BOT.zip)

**Comment by ravihansa1** [comment]
Thank you @Tharumax  i would check this.

**Comment by Tharumax** [comment]
> Thank you @Tharumax i would check this.

you welcome

**Comment by ravihansa1** [comment]
@Tharumax Check this bro. convert txt to xml. be careful with money.
[Digital Ladder Bot V1-0-1.txt](https://github.com/binary-com/binary-bot/files/3145415/Digital.Ladder.Bot.V1-0-1.txt)

**Comment by Tharumax** [comment]
ok thx
