### ISSUE TITLE
Balance Number/String

### ISSUE THREAD

**Issue by pamorell** [binary-com/binary-bot#147]
Dears,

I´m trying to include a limit of profir based on my balance, as example, stop to trade if the total profit is more initial balance + 50.

What is happening is that when I use the Balance(Number) + 50 calculation, it is look like that the Balance(Number) is the same as String.

For example: 
Initial Balance = 540.45
Balance(Number) +50 should be 590.45, but is 540.45**50**

Can you fix it?

Thanks,

Paulo Rocha

**Comment by aminmarashi** [comment]
Fixed. Many thanks for reporting this Paulo.

**Comment by pamorell** [comment]
Thanks for fixing it !
