### ISSUE TITLE
Digit Analyzer Issue - freezes on error

### ISSUE THREAD

**Issue by Brishe** [binary-com/binary-bot#1471]
Hi guys,

I'm using this digit analyzer which was developed by aminmarashi for EVEN/ODD contract types. Every time the analyzer shows which digit is the most frequent, it will purchase EVEN or ODD. But every time the bot notifies "You have reached the rate limit for proposal" and resumes trading after some time, the analyzer stops showing the most frequent digit. And the last contract type it purchased before the rate limit notification will remain the same (if ODD, it will continue trading ODD: if EVEN, it will continue trading EVEN), ignoring the most frequent digit in the analyzer.

I've already checked these options in Block 1, but still the error persists.

![image](https://user-images.githubusercontent.com/46435102/57163904-05b36900-6e25-11e9-8d8f-4bc7c9d87c94.png)

Can anybody explain this? Looks like the digit analyzer freezes when an error occurs.

Thanks.

**Comment by aaron-binary** [comment]
Hey @Brishe,

Could you provide a link to the strategy you're referring to, or upload it to https://gist.github.com? 

Regards,
Aaron
