### ISSUE TITLE
candal pattern bot

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1472]
need help someone

strategy
if 3 1 minute candal up (bullish / green) buy next 3 min or
if 3 1 minute candal down (bearish / red) sell next 3 min

and if lost add matingale to next
Ex
green green green then buy end time 3 min or
red red red then sell end 3 min
and lost
add 3X matingale and same staragy
please help
thanks
1 minute candal

**Comment by AlienFly** [comment]
![33](https://user-images.githubusercontent.com/36364199/57180925-38e21080-6e96-11e9-9ad4-0a34856c5f59.png)

**Comment by Tharumax** [comment]
[COLOR.zip](https://github.com/binary-com/binary-bot/files/3144672/COLOR.zip)

**Comment by dushanu** [comment]
thank you very much both of u
