### ISSUE TITLE
do we have pause logic?

### ISSUE THREAD

**Issue by streetyuk** [binary-com/binary-bot#1477]
i would like help in pausing my bot after a loss and Carrie on after 1 minute.

**Comment by aaron-binary** [comment]
Hey @streetyuk,

Below is an example of how you could implement that logic.

![Screenshot 2019-05-06 at 9 19 02 AM](https://user-images.githubusercontent.com/44427668/57203161-2ffd5600-6fe0-11e9-9006-99459ca333d2.png)

https://gist.github.com/aaron-binary/38e1856f9bbcf1cf07d209fd8be6ac8f

**Comment by streetyuk** [comment]
wow simples ty aaron, but would this continue on with a martingale increase? or is it stopping and replaying?

**Comment by aaron-binary** [comment]
Hey @streetyuk,

This will not interrupt your strategy—so your martingale increase would keep on working. 

All this block does is pause the execution for the number of seconds you specify.

Hope that helps,
Aaron

**Comment by streetyuk** [comment]
much appreciation for your time and answers ty.
