### ISSUE TITLE
Please Tel Me About This

### ISSUE THREAD

**Issue by Binaryboy707** [binary-com/binary-bot#1479]
At the same time, Bot can be opened in two Trade Can you Make it

Example  Volatility Indices 100  High Low

bot open two trade same time  High bariyar  +3
                                                   Low  Bariyar  - 3

Some Time  Lose 2 trade  Just Open Martingale  High bariyar  +3
                                                                              Low  Bariyar  - 3
                                                                               Same Time  
 ( only martingale affter 2 trade Same Time loss only)

same time one trade win & one trade loss this time no open martingale i need Next two trade  open nomaly same time

Thank You

**Comment by romeo1911** [comment]
bot cannot open 2 trades in same time

**Comment by Binaryboy707** [comment]
> bot cannot open 2 trades in same time

Than You Brother
