### ISSUE TITLE
Native Application Teaser

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1489]
Hi Guys, I said I was working on something new, here is a screenshot of the first Live account testing for a new native platform for Windows, Linux and Mac using the binary.com API. It won't be released for a few months but it'll be **free to use** with a small 1% dev fee (same as binary-ex-Machina's system). Following features:

- Data persistence; stop, pause, restart, close app (or app crashes), and you can resume your trading on app open. Never lose your martingale steps again!!!

- Auto-market select. The platform will look for cleanest Volatility index and auto switch (you can also manually switch), this automatically updates all the charts and trading parameters, never look at the wrong chart again!!

- Choice of money management, classic martingale, cumulative loss martingale, and ladder profits.

- Fully auto trading, manual trading (with built-in martingale options, take profits and stop loss), or semi-auto, where is trades using an algorithm until x number losses, where you can manually take over.

- Selection of different strategies, with advanced option to adjust the parameters of the technical indicators used to trigger trades - built you own strategy with no coding or blockly knowledge at all!

- Full virtual and Live account support; switch between the two without having to re-enter any API tokens!!

![Capture](https://user-images.githubusercontent.com/17556774/57367379-c5375080-7180-11e9-9481-47e597bee82a.JPG)

**Comment by wilburforce83** [comment]
@Ares31 I'll be releasing it in the next couple of months and adding more info soon! I'm just debugging some things and running some live tests before adding more features

**Comment by Ares31** [comment]
disculpa mi a atrevimiento pero puedes ayudarme con un bot, solo quiero una modificacion pero no se hacerlo si tienes tiempo puedes ayudarme, si no puedes lo entiendo gracias

**Comment by romeo1911** [comment]
hi @wilburforce83 it will be possible to
- launch a strategy on all the markets at the same time with different martingale for each 1?
- import from xml? (strategy or indicator)
- add forex markets? (there are ppl that cannot trade volatility)

**Comment by wilburforce83** [comment]
@romeo1911

Hi! There will be a separate version for forex. Basically, volatility indices are synthetic markets which move based on internal transaction volume, as far as I can work out. This means that their volume, therefore stability for momentum are severely limited, so successful strategies for VIX and FRX are very different and I don't want to mix them up.

- You will only be able to run one money management system at a time, I don't really see the benefit of trading Tue way you propose.

- The XML format used by blockly is incompatible. So unfortunately, no. There will however be a strategy for all major technical indicators, with advanced options to change all the settings for each indicator and trade durations. In addition there will be a custom strategy where you can choose any number technical indicators to act as trade triggers either *any one signal* or *every signal* being the trigger. So there will be a huge amount of choice.

If you want to chat more I have set up a discord server for the platform I'll add a feature request channel for people to talk about future features. I plan to actively develop both VIX and FRX versions.

**Comment by wilburforce83** [comment]
Discord invite; please, all are welcome to discuss features etc. Thanks

https://discord.gg/MFkyJ6

**Comment by wilburforce83** [comment]
alpha release available on discord https://discord.gg/xVtsakq now!

**Comment by wilburforce83** [comment]
@aaron-binary   Regarding forex, this is not available in my country, can you tell me which pairs are available for those trading in other countries? 

Is it all pairs, or just majors? My virtual account is showing all pairs, with a trade duration minimum of 3 minutes. Is that what everyone can trade if they have forex access?

Thanks!

**Comment by aaron-binary** [comment]
Hey @wilburforce83,

It all depends on the account type (e.g. VRTC, CR, MX etc.) and the jurisdiction you're under. 

- You can request the list of available pairs for you by requesting `asset_index` from the API. Please see https://developers.binary.com/api/#asset_index

Make sure to make the call after a user has `authorize`d so the API only returns symbols specific to that user.

Regards,
Aaron
