### ISSUE TITLE
Error  keeps  breaking the Bot.

### ISSUE THREAD

**Issue by Bliznez360** [binary-com/binary-bot#1492]
Hello, after any Error, such as "Unknown contract proposal" the binary bot stops making the right deals, according to the logics of strategy. 

Instead it keeps making purchases all the time. 
Please help. 
[https://github.com/Bliznez360/Test-for-Binary/blob/master/%D1%84%D0%B0%D0%B9%D0%BB_%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8.png](Screenshot)

**Comment by aaron-binary** [comment]
Hey @Bliznez360,

Could you upload your strategy to https://gist.github.com?

Regards,
Aaron

**Comment by Bliznez360** [comment]
[https://github.com/Bliznez360/Test-for-Binary/blob/master/binary-botVOT_VAM.xml](url)
That's  the strategy

**Comment by Bliznez360** [comment]
Any   suggestions?  it basically starts purchasing  randomly after the first "Unknown contract Proposal" error occurs. 0_o

**Comment by Bliznez360** [comment]
not Solved yet.
