### ISSUE TITLE
CCI binary bot based on ticks

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#1500]
Can someone create cci indicator based on 1000ticks?

**Comment by romeo1911** [comment]
cci indicator use ohcl ( candles) not ticks

**Comment by wilburforce83** [comment]
You can create a rapid oscillating CCI using 1 minute candles and a period around 6. This will work for short trades.

I have been toying with the idea of mapping my own 15s candles using the tick data in order to get better short term data
