### ISSUE TITLE
How does this Strategy Work?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1502]
I have been watcfhing these strategies for a while, and he claims its all down to the mathematical calculations on the last 4-7 digits?

https://youtu.be/0utD80JynNc

I know the trading amounts of $500-$1000 maybe risky or fake, but what about how he is actually doing this? Could it be turned into a bot?

**Comment by romeo1911** [comment]
where he claims that? put all the money is kind of crazy things i think

**Comment by buckman1974** [comment]
> where he claims that? put all the money is kind of crazy things i think

He doesn't 'claim' it... Its merely and observation. Watch the video!
Also he does 2 other separate videos exactly the same, whereby he puts everything on each trade.

I am not saying they are genuine, or its most probably a Virtual Account, but he claims its all down to the mathematical calculations on the last 4-7 digits?

**Comment by romeo1911** [comment]
ya It's merely an observation. and he wrote that will gives that money to other people because he not need money. btw i think can be real, I have also seen that other people do the same. maybe is a quality of him, or a lot of practice, or just lucky

**Comment by loigaak** [comment]
What is your method? i can create bot

**Comment by buckman1974** [comment]
> What is your method? i can create bot

That is what I am asking!
