### ISSUE TITLE
Help Me Brothers

### ISSUE THREAD

**Issue by Binaryboy707** [binary-com/binary-bot#1507]
i need two  binary bot run single Click Same time  ( Like imacros script builder for my strategy )

Exmple -========  open two page in firefox browser affter load two bot 2 page ( i have bot )

next i need single click just open two bot same time

any one help me Thank You

@hotmatrixx @James-Ngigi @romeo1911 @binary-ex-machina

**Comment by romeo1911** [comment]
post the bots pls

**Comment by ZDEGLET** [comment]
СКАЧАЙ ПРОГРАММУ ReMouse УСТАНОВИ САМУЮ МАКСИМАЛЬНУЮ СКОРОСТЬ И ПОГНАЛИ!!!

**Comment by romeo1911** [comment]
https://github.com/binary-com/binary-bot/issues/1229#issuecomment-465119789
