### ISSUE TITLE
I have tried many ways Need help

### ISSUE THREAD

**Issue by Binaryboy707** [binary-com/binary-bot#1508]
Do you have Less than five Loss Rise Fall Bot   ( Max Lose 3 Very Good )
Can you give me
I have tried many ways, but none of them is successful

Can you tell the correct method from the numbers?

Exmple -  i watch Last Digit Number comming ReD 9 just open ten tick trade Rise

What are the correct methods you are familiar with  For Rise Fall Trade

@hotmatrixx @James-Ngigi @romeo1911 @binary-ex-machina

**Comment by loigaak** [comment]
Is that method really good ??

**Comment by ZDEGLET** [comment]
Я ПОКА НЕ ВИДАЛ ТАКОГО БОТА. ЕСЛИ БЫ ОН БЫЛ ЭТО ГРААЛЬ:)

**Comment by sinung21** [comment]
[dBrengos-Rise-Fall-using-Number-9-Strategy-V1.0.zip](https://github.com/binary-com/binary-bot/files/3177991/dBrengos-Rise-Fall-using-Number-9-Strategy-V1.0.zip)
