### ISSUE TITLE
Native Application Alpha Tests

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1511]
Hi Everyone, not sure if I can post here, so @aaron-binary  please remove if I am breaking any rules, I can't see anything to say otherwise explicitly.

I have an alpha release of my platform for trading with binary.com so anyone wanting to try it out please feel free to join the discord server where the release is and I will be monitoring feedback etc.

It supports loads of features just download and have a play, it's free, and just has a small developer fee of 1% on winning trades, as with binary-ex-machinas website.

https://discord.gg/xVtsakq

or download directly here (link updated for forex + volatility version):

http://bit.ly/2WQ52BA

thanks all :)

**Comment by loigaak** [comment]
How can we install logic into it?

**Comment by romeo1911** [comment]
@loigaak no

**Comment by wilburforce83** [comment]
@loigaak you can't code your own strategies. bot.binary.com does that, so there isn't much point in duplicating it. What you can do is choose from different preset money management and strategies. In advanced options you can fine tune those strategies, changing MA periods etc. The platform is designed to give much more control over trading than you get with the vanilla binary.com offerings. I hope this helps. cheers!

**Comment by ZDEGLET** [comment]
Для англоязычных может и нормальное приложение для меня русского я ничего не понимаю что делать. А главное куда нажать где торговать?

**Comment by wilburforce83** [comment]
@ZDEGLET at the moment I am just building the platform. I will add translations be once I am at a proper release stage. I hope this helps!

**Comment by ZDEGLET** [comment]
@wilburforce83  хорошо

**Comment by sinung21** [comment]
![ice_screenshot_20190516-005432](https://user-images.githubusercontent.com/28952744/57860216-ae4acb00-781e-11e9-9a3e-ea41c8bc3d63.jpeg)

**Comment by sinung21** [comment]
![ice_screenshot_20190516-194955](https://user-images.githubusercontent.com/28952744/57860257-c28ec800-781e-11e9-9ecf-adc3dedff7ab.jpeg)

**Comment by wilburforce83** [comment]
@sinung21  Hi there! I that first image you have live account selected without a live token added :) but I see in the second screenshot you have that sorted now :) If you need any more help, please feel free to use my discord server https://discord.gg/xVtsakq to save clogging up the github pages. Thanks!!!

**Comment by wilburforce83** [comment]
Forex support is now live on the latest version:
http://bit.ly/2WQ52BA

Strategies are still limited while I add more, but the framework is now pretty much there, manual trading and price action strategy are probably the best way to use the platform at the moment. Thanks!

**Comment by loigaak** [comment]
HAS BEEN RUNNING ON A REAL ACCOUNT ??

**Comment by wilburforce83** [comment]
Yes it is now on its first stable release over at https://binarybottrading.eu with people trading live on it now

**Comment by wilburforce83** [comment]
@loigaak you can also write your own strategies for it now too. I built a whole point and click builder you can write strategy files with candle patterns and indicators as triggers
