### ISSUE TITLE
Digit Under Over 2 Digits Prediction

### ISSUE THREAD

**Issue by Brishe** [binary-com/binary-bot#1512]
Hi guys, 

Referring to issue #1435, can I use 2 digits for prediction?

Thanks.

**Comment by romeo1911** [comment]
[ud23.txt](https://github.com/binary-com/binary-bot/files/3182547/ud23.txt)
this is an example of under 4 over 5.
when u launch the bot and finds 4 or 5 u need to stop and relaunch it.

**Comment by Brishe** [comment]
@romeo1911, thanks. But I've noticed that the bot continues to trade when min4 = 5 (no. of digits below 4) and mag5 = 5 (no. of digits above 5). Is this normal? I was thinking bot will only trade when min4 > 6 or mag5 > 6.

**Comment by romeo1911** [comment]
depends how u wanted. there are a lot of configurations....
 if min4 >6 u want to buy:
 up 4
up 5
down 4
down 5
and the same things for number 5...

**Comment by Brishe** [comment]
What happened to romeo1911? Did he deactivate his.account or was deleted?
