### ISSUE TITLE
How To Do This Type Rise Fall

### ISSUE THREAD

**Issue by Binaryboy707** [binary-com/binary-bot#1520]
Some People  trade Watch Digit Number Rise Fall How To Do ?

I have tried many ways, but none of them is successful.What are the correct methods you are familiar with For Rise Fall Trade

Please Tel Me How To Get successful Signal worm line or digit number
i neeed successful methods im, lost lot of money Please help me brothers

Thank You

**Comment by romeo1911** [comment]
personally i never see 1 winning bot with digits. 
i know people do it manually and they can make good profit (but u need exercise a lot) 
4 the rest i use bot 1min candles and martingale just 4 make it faster. (my strategy is better with bot then manual)

**Comment by Binaryboy707** [comment]
Dear Brother @romeo1911 Can you describe more about your methodology?

how to do trade 1m candle Where to begin first trade  Rise Or Fall

Can I explain how to first trade and affter loss trade four steps martingale correctly?
can u make small video I have very very tried many ways. my feeling down Please help me brother sorry my bad engslish

**Comment by romeo1911** [comment]
everybody have proper methods, this means that maybe my method does not work well with u. i use Bollinger bands, hma and macd. u can ask to google, there is a lot of videos that teach u about bb plus macd strategy, how to read candles etc. after u open the chart with the indicators and u try to predict if the price go up or down... practice.
where to begin the trade, looking at the chart
4 levels of martingale, depends on how much money u have , how much u stake and what u trade. 4 levels can be 8 $ or 1100$ or more, i not get the question

**Comment by Binaryboy707** [comment]
@romeo1911 thank you very much help me  i wish you all the best god bless you my dear brother
