### ISSUE TITLE
Entry point 

### ISSUE THREAD

**Issue by CristianGrig** [binary-com/binary-bot#1535]
Hello Everyone and happy trading!
I was wondering if anyone could help me setting up a bot to enter the market at a specific point. For example, to trade on ticks but to buy a contract when digits are even ?

**Comment by CristianGrig** [comment]
Hi again,

What I failed to say is if we can apply to the martingale strategy the above settings. Martingale bot to purchase only when last digit is even.

Many thanks in advance!

**Comment by binary-ex-machina** [comment]
here an example to buy the contract when the last digit is even

![image](https://user-images.githubusercontent.com/34610787/58363641-ce613680-7e7d-11e9-8c22-b5ec0c3e4ac7.png)

**Comment by CristianGrig** [comment]
> here an example to buy the contract when the last digit is even
> 
> ![image](https://user-images.githubusercontent.com/34610787/58363641-ce613680-7e7d-11e9-8c22-b5ec0c3e4ac7.png)

**Comment by CristianGrig** [comment]
> here an example to buy the contract when the last digit is even
> 
> ![image](https://user-images.githubusercontent.com/34610787/58363641-ce613680-7e7d-11e9-8c22-b5ec0c3e4ac7.png)

Many thanks for setting this up. After trying to start the bot I was given an error. I’ve attached images. Could you please advise on what went wrong ?

![2310349B-CB98-4B71-94DC-CC0D38028B17](https://user-images.githubusercontent.com/50909333/58372121-18472c80-7f11-11e9-9c30-df4c35a068ee.jpeg)
![640D7930-12D5-4509-BB2E-02A252A47DD8](https://user-images.githubusercontent.com/50909333/58372122-18472c80-7f11-11e9-9c9e-71f93ad9dd5f.jpeg)

**Comment by aaron-binary** [comment]
Hey @CristianGrig,

In the screenshots it looks like you've created a variable called **Last Digit List**, rather than using the special **Last Digit List**-block. You may find this block in **Binary** -> **Tick Analysis** -> **Advanced**.

![last-digit-list](https://user-images.githubusercontent.com/44427668/58392098-ea75fb00-806a-11e9-9718-bb0211707cd3.gif)

Let us know if that helped.
Aaron :-)

**Comment by CristianGrig** [comment]
> Hey @CristianGrig,
> 
> In the screenshots it looks like you've created a variable called **Last Digit List**, rather than using the special **Last Digit List**-block. You may find this block in **Binary** -> **Tick Analysis** -> **Advanced**.
> 
> ![last-digit-list](https://user-images.githubusercontent.com/44427668/58392098-ea75fb00-806a-11e9-9718-bb0211707cd3.gif)
> 
> Let us know if that helped.
> Aaron :-)

Hi Aaron, 
Many thanks for your help :) 
I did as you showed me and the bot is working now, but there is one other issue, the bot is buying both even & odd regardless if it's set up on even or odd. 
Please see attached. Could you please help fixing this:)

Much appreciated,
Cristian

![image](https://user-images.githubusercontent.com/50909333/58419781-6d0ab480-8083-11e9-93f3-08dc13862c35.png)

![image](https://user-images.githubusercontent.com/50909333/58419823-8ad81980-8083-11e9-8b41-0da4fdbcc53c.png)
