### ISSUE TITLE
How to do this, need some help

### ISSUE THREAD

**Issue by droidman85** [binary-com/binary-bot#1536]
Hi, i have a simple bot that is workinga but it need's some improvement. I wanted for example if the last 3 exit_tick's were even numbers i want it to enter the market and do it's thing, only after 3 even numbers. after that it waits for 3 more even numbers and does it's thing. 
thanks in advance

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/58363633-b12c6800-7e7d-11e9-95b7-8d2a7b0c061b.png)

**Comment by droidman85** [comment]
Thank you binary-ex-machina 
i was making a count variable count +1 every time an sequence of evens showed up on run on every tick, i think that it works the same but i'm going to try this method, not sure if any of the them is more stable.

**Comment by droidman85** [comment]
i'm having a very hard time finding how to add that "AND" after the first IF

**Comment by droidman85** [comment]
i managed to add multiple "and"'s and it looks like it will work but they went on a straight line, not organized vertically like yours

**Comment by droidman85** [comment]
got it to work but only enters the market once, the bot is still running bot it does not enter the market after winning or losing. tried to add the code to the run on every tick block added a buy variable set it to 1 and still only buyes once

**Comment by droidman85** [comment]
problem solved, was missing the trade again on section 4
