### ISSUE TITLE
How to trade on specifics time in candle?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1543]
Example
I wanna trade 3 times in 1 candle on 1 to 19(1), 20 to 39(2) and 40 to 59(3) second.
How to code it? Pls share xml here.

**Comment by binary-ex-machina** [comment]
you can do like this
![image](https://user-images.githubusercontent.com/34610787/58363601-41b67880-7e7d-11e9-8798-00d8c123477d.png)
