### ISSUE TITLE
Telegram Notifications

### ISSUE THREAD

**Issue by aaron-binary** [binary-com/binary-bot#1548]
# Telegram Notifications

You can now send messages to Telegram using the newly added Telegram Notify-block. To use this block you are required to create your own Telegram bot.

### Here’s the how-to steps

1. Create a Telegram Bot and get your Telegram API token. Read more on how to create bots in Telegram here: https://core.telegram.org/bots#6-botfather
2. Start a chat with your newly created Telegram Bot and make sure to send it some messages before proceeding to the next step. (e.g. `Hello Bot!`)
3. Now let's find out the chat id using the Telegram REST API (read more: https://core.telegram.org/bots/api#getupdates)
    1. Visit the following URL, make sure to replace `<access_token>` with the Telegram API token you created in Step 1: `https://api.telegram.org/bot<access_token>/getUpdates`
    2. Find the chat id property in the response, and copy the value of the `id` property: 
![pasted image 0](https://user-images.githubusercontent.com/44427668/58398258-0edfd080-8087-11e9-845e-69b05548ae9f.png)
4. Flip over to Binary Bot and add the `Notify Telegram` block to the canvas. Paste the Telegram API token and chat id into the block fields accordingly.

You can also view a visual how-to using the following URL: https://gist.github.com/aaron-binary/e5bd33bc7c657a911499c06b50dd04e9

![Screenshot 2019-05-27 at 2 17 25 PM](https://user-images.githubusercontent.com/44427668/58399264-33897780-808a-11e9-9d3d-dd60dbaeec59.png)

We're more than happy to hear your thoughts on this block (and anything else Binary Bot), feel free to reply below. 🤖

**Comment by T3sl4** [comment]
Awesome feature, I love it. Question though, would it be possible to add the functionality to start and stop the bot via a telegram message, or perhaps add custom commands that the bot can receive via telegram message. I have not looked into telegram bots much beyond getting this block working, so I do not know how feasible it would be to send commands to the bot via telegram, but even as is, it is a nice feature, thanks you guys for adding it...

**Comment by aaron-binary** [comment]
@T3sl4,

Thank you for your feedback, we appreciate it.

We don't have this functionality at the moment but it would definitely be nice to be able to control your bot externally. I'll discuss this with the team.

Thanks again!
Aaron

**Comment by James-Ngigi** [comment]
Were you able to do it @aaron-binary ? That is control the bot externally?

**Comment by hotmatrixx** [comment]
more importantly, what the hell is Telegram?
maybe a built-in link in the bot to encourage us to investigate it when we discover thsi feature.

Googling Telegram gives me a reverence to the 1700 - pre- telephone via wire method of communication made famous in the Old West.

**Comment by T3sl4** [comment]
> more importantly, what the hell is Telegram?
> maybe a built-in link in the bot to encourage us to investigate it when we discover thsi feature.
> 
> Googling Telegram gives me a reverence to the 1700 - pre- telephone via wire method of communication made famous in the Old West.

You are trolling right?? 
https://telegram.org/

**Comment by James-Ngigi** [comment]
Telegram is a powerful messaging platform fit for business and personal relations.
You can find its app on any platform

**Comment by sohailsb** [comment]
i want to develop binary.com bot
Digit Differ Strategy
Rules:
if Tick1=0 Tick2=0 Tick3=1 then Differ=1 Duration= 1 tick
same this strategy
Tick1=0 Tick2=0 Tick3=2 thne Differ=2 Duration= 1 tick
We can say this strategy
0-0-1 Differ 1
0-0-2 Differ 2
0-0-3 Differ 3
0-0-4 Differ 4
0-0-5 Differ 5......................... up to 0-0-9 Differ 9
can you develop this strategy in bot

**Comment by muroyal** [comment]
This function  not working at present..
