### ISSUE TITLE
ПРИКОЛ РОБОТ ЗАБЫЛ ДОВЕСТИ ДЕЛО ДО КОНЦА

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#1550]
![2019-05-27_20-54-49](https://user-images.githubusercontent.com/36106343/58434434-4b7ded00-80c4-11e9-939b-533383c6b62a.png)

**Comment by loigaak** [comment]
can you share it for me @ZDEGLET

**Comment by ZDEGLET** [comment]
твоя электронная почта

**Comment by loigaak** [comment]
here sirr : hoangvanloi1166@gmail.com  @ZDEGLET

**Comment by arpan2121** [comment]
sarpanjot0@gmail.com

**Comment by Jalalahmadi** [comment]
j_ahmadi@ymail.com

**Comment by Ares31** [comment]
kamil_186@hotmail.com puedes compartirlo gracias

**Comment by tryx68** [comment]
tryx1969@gmail.com

**Comment by Jonni81** [comment]
@ZDEGLET привет. скинь мне тоже поглядеть. treid8159@yandex.ru

**Comment by ZDEGLET** [comment]
ВСЕМ ОТПРАВИЛ НА ПОЧТУ:)

**Comment by sinung21** [comment]
send to me too @ZDEGLET herypriawan78@gmail.com

**Comment by thawatchaii** [comment]
thawatchaiii333@gmail.com

**Comment by sandramanaka1** [comment]
also send to me @ZDEGLET  :  sandramanaka1@gmail.com

**Comment by ZDEGLET** [comment]
СЕГОДНЯ ПРИШЛЮ

**Comment by Baselope** [comment]
This looks awesome, please send it to me too. ericashaw484@gmail.com

**Comment by poroinika** [comment]
Can you send to me....Thanks!!!!
Stenli_777@abv.bg

**Comment by ZDEGLET** [comment]
ОТПРАВИЛ ВСЕМ. ВЧЕРА РАБОТАЛ НЕ СМОГ.

**Comment by ZDEGLET** [comment]
ПИШИТЕ ДЕЛИТЕСЬ РЕЗУЛЬТАТАМИ ИДЕЯМИ

**Comment by xremmy** [comment]
Can you please share with me aswell, Thanks
xremmy@gmail.com

**Comment by josetrafalgar** [comment]
send for me please: js.assinscreed@gmail.com

**Comment by sopranox** [comment]
send me, please mvegasina@gmail.com

**Comment by jerorios** [comment]
Hi! ZDEGLET could you please sen to me email? jero.rios@gmail.com thanks in advance!

**Comment by ashrafulcg** [comment]
ashrafulcg@gmail.com

**Comment by oliveiradue** [comment]
amazing layonom@gmail.com

**Comment by ballck** [comment]
can you share it for me @ZDEGLET
my email: juvefcfb@gmail.com

**Comment by alansilva1** [comment]
alansilva433@Gmail.com

**Comment by muroyal** [comment]
@ZDEGLET evaroyal84@gmail.com

**Comment by amendes92** [comment]
@ZDEGLET alexmendes92@gmail.com
