### ISSUE TITLE
can help me

### ISSUE THREAD

**Issue by sinung21** [binary-com/binary-bot#1551]
IF THERE ARE PRICES PROVIDING THE NEXT 2X MOVING IN RIDE / DOWN IN 1 POINTS THEN REVERSAL OPERATIONS.
example :  XXXX.9XX
                 XXXX.9XX
                 XXXX.8XX OP RISE BECAUSE 1 POINT

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/59114070-bcbb6c80-891c-11e9-9557-1fde359e9243.png)

**Comment by sinung21** [comment]
OK THANKS @binary-ex-machina
