### ISSUE TITLE
Notify the maximum martingale

### ISSUE THREAD

**Issue by andreksu** [binary-com/binary-bot#1552]
Hello, could someone help me to make the bot calculate what was the maximum martingale that happened during the whole running? 

Something like:

Maximum martingale reached: 7x equal to $700 at [timestamp]

**Comment by ZDEGLET** [comment]
ПОСМОТРИ ИСТОРИЮ ВСЕХ СДЕЛОК НА РАБОТАЮЩЕМ РОБОТЕ:)

**Comment by Hooponopono** [comment]
![Immagine](https://user-images.githubusercontent.com/50791712/58653748-986df780-8340-11e9-80ac-0f18c0804b3b.png)

**Comment by ceakuk** [comment]
I can do it within 1 hour for 5$
I see so many issues that i can do in a few minutes. However it would take me forever to help everybody. So i'll charge 5$  for my time. if the strategy is sound then 5$ is nothing compared to your potential profit.
