### ISSUE TITLE
Help open a trade right away after a loss not waiting new signal

### ISSUE THREAD

**Issue by bonbon21** [binary-com/binary-bot#1554]
Hi, Anyone can help me make a bot which it's open a trade right away with martingale after a loss, not waiting for new signal ?
Thank you

**Comment by binary-ex-machina** [comment]
I like to use the idea of straight recovering, not waiting for a new signal after loss, but trading the same direction right away.

![image](https://user-images.githubusercontent.com/34610787/59113631-c7c1cd00-891b-11e9-877c-6a1764338a9d.png)
