### ISSUE TITLE
can somebody fix the bot?

### ISSUE THREAD

**Issue by Hooponopono** [binary-com/binary-bot#1557]
I started the bot at 2.38, at 3.01 I get error messages and after the bot did not follow the part inside "on every tick" until I stop it at 10, ya is impossible I know that then u can see the log,
then how I can change my bot for not get stuck?
[bot.zip](https://github.com/binary-com/binary-bot/files/3239577/bot.zip)

**Comment by ZDEGLET** [comment]
![2019-05-31_08-22-30](https://user-images.githubusercontent.com/36106343/58683495-4dbea080-837d-11e9-98f0-683ff59e3146.png)

**Comment by Hooponopono** [comment]
Do you mean that I can use only 1 prediction?
