### ISSUE TITLE
Help Change Barrier

### ISSUE THREAD

**Issue by bonbon21** [binary-com/binary-bot#1559]
Dear Brother @aaron-binary @hotmatrixx @James-Ngigi @romeo1911 @binary-ex-machina

Please Help me, how to create bot change barrier based strategy?
Ex:  

- With stategy 1, i want change barrier to - 1, and purchase higher
- With stategy 2, i want change barrier to +1, and purchase lower
- And if strategy 1 run and purchase, then next waiting for signal of stategy 2,  if strategy 2 run and purchase, then next waiting for signal of stategy 1

Thank you

**Comment by binary-ex-machina** [comment]
@bonbon21 here is a way of getting what you want running. The strategy 1 is RSI10 above 80 and strategy 2 is RSI10 below 20. Each strategy will use a contract type, Higher/Lower. In case you want both contract types to run for each strategy, it's better to have 2 scripts running, each one with it's own strategy.

![image](https://user-images.githubusercontent.com/34610787/59113282-1e7ad700-891b-11e9-8e71-f231439fea2b.png)

**Comment by wallpersonal** [comment]
> @bonbon21 here is a way of getting what you want running. The strategy 1 is RSI10 above 80 and strategy 2 is RSI10 below 20. Each strategy will use a contract type, Higher/Lower. In case you want both contract types to run for each strategy, it's better to have 2 scripts running, each one with it's own strategy.
> 
> ![image](https://user-images.githubusercontent.com/34610787/59113282-1e7ad700-891b-11e9-8e71-f231439fea2b.png)

EU TE AMO CARA! PQP! VC EH FODA!
