### ISSUE TITLE
incorrect values RSI, between the chart and binary bot

### ISSUE THREAD

**Issue by ekozhin** [binary-com/binary-bot#156]
![rsi wrong](https://cloud.githubusercontent.com/assets/24454432/22323265/d4524fa6-e3b2-11e6-800e-151d8cb26ae7.jpg)
Hello, Amin!
RSI indicator that is used in the binary bot, gives wrong values.
If you look at the screenshot you can see that on the chart RSI level is around 20, and a binary bot RSI level is 36
and because of this error very rarely open transaction in a binary bot when RSI levels 80 and 20, although the chart RSI is above 80 and 20 is quite often
probably in the indicator RSI binary bot used the wrong formula to calculate

**Comment by aminmarashi** [comment]
Binary Bot indicators are not compatible with the binary.com and webtrader.binary.com
If you want to compare the charts you can compare tradingview.binary.com with the binary bot charts.

**Comment by ekozhin** [comment]
Why then added RSI indicator in binary bot, if shows completely different values compared to the schedule, as actually probably other indicators used in the binary bot

**Comment by aminmarashi** [comment]
The values should match the chart within the bot itself, not other apps of the binary.com company. there are different implementations for each and every indicator we have, in Binary Bot we tried to stick to the standard apps as much as possible.
So if you use the [tradingview.binary.com](https://tradingview.binary.com/) for example you shouldn't see a lot of difference between the values.

**Comment by ekozhin** [comment]
Сan somehow fix the value of the indicator RSI in the binary bot that there was no difference, because how to use it in bot silly

**Comment by aminmarashi** [comment]
Did you check in the [tradingview.binary.com](https://tradingview.binary.com/) app or our MT5 app? If you do you shouldn't see any significant difference.
RSI by nature meets the `overbought` and `oversold` lines rarely. But it all depends on your definition of those lines, which are most commonly set as 70 and 30 respectively.
If you want you can change those values for example 60 and 40 can be crossed more often.

**Comment by rockroxy** [comment]
I'm sorry that I write here, amin marashi can you please help me, https://binary.vanillacommunity.com/discussion/210/with-strict-parameters-shopping-bot#latest

**Comment by ekozhin** [comment]
I can check the values on tradingview, but there is no binary bot, meaning what, I'll check the value?

**Comment by aminmarashi** [comment]
What do you mean by there is no binary bot?

**Comment by ekozhin** [comment]
in general, you can not fix RSI indicator in binary bot, thank you. The question is closed

**Comment by aminmarashi** [comment]
Maybe you want to fine tune the values you use in your strategy with the RSI indicator. If that's the case maybe I can help you with that, but yes, definitely I can't do that.
