### ISSUE TITLE
How to get " 012 " digit instead of " 12 "

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1566]
How to get " 012 " digit instead of " 12 "

**Comment by ceakuk** [comment]
I can do it within 1 hour for 5$

**Comment by binary-ex-machina** [comment]
@navneetsinh maybe you want to get the last 3 digits of the tick right? You can do like the image below. Never pay any amount for people asking money here. This is a repository to share knowledge and help others, not a market place for desperate people.

![image](https://user-images.githubusercontent.com/34610787/59112455-6bf64480-8919-11e9-8a1e-02bd13e0315e.png)

**Comment by navneetsinh** [comment]
> @navneetsinh maybe you want to get the last 3 digits of the tick right? You can do like the image below. Never pay any amount for people asking money here. This is a repository to share knowledge and help others, not a market place for desperate people.
> 
> ![image](https://user-images.githubusercontent.com/34610787/59112455-6bf64480-8919-11e9-8a1e-02bd13e0315e.png)

@binary-ex-machina thank you very much for help and good suggestion,

**Comment by politecruise** [comment]
> @navneetsinh maybe you want to get the last 3 digits of the tick right? You can do like the image below. Never pay any amount for people asking money here. This is a repository to share knowledge and help others, not a market place for desperate people.
> 
> ![image](https://user-images.githubusercontent.com/34610787/59112455-6bf64480-8919-11e9-8a1e-02bd13e0315e.png)

assuming the last tick is 286.0**65**5
how do I set the bot to make a purchase when the last tick has **65** as the 2nd and 3rd digit from the end

or

assuming the last tick is 286.3**69**2
how do I set the bot to make a purchase when the last tick has **6** as the 3rd digit from the end

this is what I tried for both but it didnt work

 for **65**
![2and3](https://user-images.githubusercontent.com/51704885/59598111-5a6c2400-90f3-11e9-8747-3a7798ba64c2.PNG)
 
for **6**
![3rd](https://user-images.githubusercontent.com/51704885/59598112-5b04ba80-90f3-11e9-98b3-0b26457b28de.PNG)

please help a brother, thanks

**Comment by binary-ex-machina** [comment]
@politecruise here is the blocks you need

![image](https://user-images.githubusercontent.com/34610787/59614229-b08e9680-90f6-11e9-9c52-1d6cb1e6ab28.png)

**Comment by politecruise** [comment]
> @politecruise here is the blocks you need
> 
> ![image](https://user-images.githubusercontent.com/34610787/59614229-b08e9680-90f6-11e9-9c52-1d6cb1e6ab28.png)

thanks, so where do I insert purchase to get it running
