### ISSUE TITLE
I NEED TO ADD MARTINGALE TO THIS SCRIPT

### ISSUE THREAD

**Issue by unclewale** [binary-com/binary-bot#1569]
[BOT.txt](https://github.com/binary-com/binary-bot/files/3267700/BOT.txt)

**Comment by unclewale** [comment]
https://github.com/binary-com/binary-bot/issues/1569#issue-453706773
I need to add martingale strategy to the bot in the above link

**Comment by sinung21** [comment]
[BOT 2 2LOSS STOP RECOVERY.zip](https://github.com/binary-com/binary-bot/files/3268596/BOT.2.2LOSS.STOP.RECOVERY.zip)

**Comment by sinung21** [comment]
[BOT 2 2LOSS STOP RECOVERY.zip](https://github.com/binary-com/binary-bot/files/3268603/BOT.2.2LOSS.STOP.RECOVERY.zip)

**Comment by unclewale** [comment]
thanks bro, I really appreciate this gesture.

**Comment by unclewale** [comment]
Thanks for sharing your bot, I am sharing this with you too. Find the
attached file
  ALS BOT-20190424T050813Z-001.zip
<https://drive.google.com/file/d/1qA9d3GyiEhblJob7PRoaahBVxdarbYx9/view?usp=drivesdk>
Install it and add more settings for choice

**Comment by unclewale** [comment]
I HAVE SHARE THE LINK WITH YOU NOW, YOU CAN DOWNLOAD THE SOFTWARE NOW.
I EQUALLY HAVE A GOOD BOT THAT CAN MAKE YOU REASONABLE PROFIT EVERYDAY.
HERE IS MY WHATAPPS CONTACT: +2348026112241
