### ISSUE TITLE
Why RSI value in bot different in chart ???

### ISSUE THREAD

**Issue by bonbon21** [binary-com/binary-bot#1571]
Hi,
Anyone know why RSI value in bot different in chart ???
![z3](https://user-images.githubusercontent.com/51173257/59154707-22d1fc00-8aa3-11e9-961d-9ed44500ba12.PNG)

**Comment by aaron-binary** [comment]
Hey @bonbon21,

Usually, there's a slight difference as both the chart and bot use different streams. In this case, the difference is quite big, would you be able to send us your strategy? You can either upload it to https://gist.github.com or send it to us directly at binarybot@binary.com.

Regards,
Aaron

**Comment by Hooponopono** [comment]
[rsiwebtrader.zip](https://github.com/binary-com/binary-bot/files/3270563/rsiwebtrader.zip)
![Untitled](https://user-images.githubusercontent.com/50791712/59172286-6b57eb00-8b71-11e9-9af8-c4afcb82d5c1.png)
u can import this block directly in your strategy
