### ISSUE TITLE
How will notify on candle change

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1573]
how will I get notified on candle change.
example @ if default candle is for 1 minute, and it's change with new candle every new candle I've to notify.
any suggestion ?

@aaron-binary ,@binary-ex-machina ,@Hooponopono ,@hotmatrixx ,@AlienFly ,@murali139 ,@baruga ,@ghost ,

**Comment by binary-ex-machina** [comment]
you can use the @fruitfella new candle block. Click on the link below and save the page .xml. Load the block on your bot and use it like the image below 

![image](https://user-images.githubusercontent.com/34610787/59515160-d9175600-8e94-11e9-9491-fd669b40ab49.png)


[https://gist.githubusercontent.com/Fruitfella/571952f7b1e03cf0148655c8364a3214/raw/7be26e77742c8bbcd1d60bd832c808483eb5efb9/FRUITFELLA_New_Candle_v2.xml](url)

**Comment by navneetsinh** [comment]
> you can use the @Fruitfella new candle block. Click on the link below and save the page .xml. Load the block on your bot and use it like the image below
> 
> ![image](https://user-images.githubusercontent.com/34610787/59515160-d9175600-8e94-11e9-9491-fd669b40ab49.png)
> 
> [https://gist.githubusercontent.com/Fruitfella/571952f7b1e03cf0148655c8364a3214/raw/7be26e77742c8bbcd1d60bd832c808483eb5efb9/FRUITFELLA_New_Candle_v2.xml](url)

I got it thanks dear @binary-ex-machina
