### ISSUE TITLE
Help for creating some block

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1574]
if I have 3 results ( A )
A Side
Result 1
Result 2
Result 3

and 4 conditions ( B )
B Side
Condition 1
Condition 2
Condition 3
Condition 4

If  any conditions will confirm 
any of ( A ) side confirms with ( B ) side
make trade confirm
![Opera Snapshot_2019-06-09_221042_user-images githubusercontent com](https://user-images.githubusercontent.com/42480287/59161697-8b50c580-8b03-11e9-931e-3cd9b377df2f.png)

**Comment by Hooponopono** [comment]
u have 4 trade confirmations? ( r1+c1 = confirm 1 etc ?)
what kind of data are in a and b? (numbers letters true and false?)

**Comment by navneetsinh** [comment]
> u have 4 trade confirmations? ( r1+c1 = confirm 1 etc ?)
> what kind of data are in a and b? (numbers letters true and false?)

if ( A = R1 = Result 1 ) confirmation true , than check for ( B = C1 or C2 or C3 or C4 ( any one out of four ) confirmation true 
set trade confirmation true

**Comment by Hooponopono** [comment]
[ab.txt](https://github.com/binary-com/binary-bot/files/3274741/ab.txt)
like this?

**Comment by navneetsinh** [comment]
> [ab.txt](https://github.com/binary-com/binary-bot/files/3274741/ab.txt)
> like this?

oh, yes thanks dear, it's good,
I'll test it in bot.
thanks dear,
