### ISSUE TITLE
Error  in binary Bot "Unknown contract Proposal" not Solved(( 

### ISSUE THREAD

**Issue by Bliznez360** [binary-com/binary-bot#1578]
https://github.com/binary-com/binary-bot/files/3166534/binary-botVOT_VAM.zip 
Error happens "Unknown contract proposal" and the binary bot stops making the right deals, according to the logics of strategy.  (starts making  Purchase every 5 ticks or so) 
Details in Screenshot: https://github.com/Bliznez360/Test-for-Binary/blob/master/%D1%84%D0%B0%D0%B9%D0%BB_%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8.png 

(Previous  thread was closed  prematurely,  problem still persisting, please help!)

**Comment by aaron-binary** [comment]
Hi @Bliznez360,

Could you describe in detail how the bot stops making the right deals?

Let us know and we'll investigate.

Regards,
Aaron

**Comment by Bliznez360** [comment]
At some   point  the bot  just starts  making purchases every time  the contract  is over- it just opens new one straight away. 
Any way   to fix/ work around it? 
Bliznez360

**Comment by Bliznez360** [comment]
I noticed  the glitch above happens  right  after "Unknown contract proposal" error   shows up. 
Before then  it seems to work  fine. 
Any ideas?

**Comment by Bliznez360** [comment]
Hi,  any solutions?  the problem is still  persisting?! 
Bliznez360
