### ISSUE TITLE
Take trade based on entry price

### ISSUE THREAD

**Issue by Motafota** [binary-com/binary-bot#159]
Hi all,

I saw some example scripts posted on the project and had a suggestion for once since i wasn't able to find a build in function on the bot itself.

Having it take a call/put trade if a contract price is equal to the one set would be a useful script idea if im waiting for a pair to reach a certain price but can't be around long enough to monitor it!

Just an idea if you're taking requests, if not then sorry to clutter up the issues section!

**Comment by aminmarashi** [comment]
Thanks, I added the strategy to the examples.
You can find it [here](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/buy_on_desired_net_profit.xml)
