### ISSUE TITLE
Hi, can somebody help me how to make instructions in my Rise Fall bot

### ISSUE THREAD

**Issue by loigaak** [binary-com/binary-bot#1591]
Hi, can somebody help me how to make instructions in my Rise Fall bot

When candle is green and 4 ticks go down in a row (the spot is red - red - red - red ) purchase rise
When candle is red and 4 ticks go up in a row (the spot is blue - blue - blue - blue) purchase fall
I have tried to do like this:
If ... is candle black ... (bla bla bla) = false
do ... If tick1 < tick2 and tick2 < tick3 and tick3 < tick4
do ... Purchase Rise
But it doesn't work
I know nothing about making bot script just trying to modify bots free-downloaded from youtube.
Would be very happy if someone can help me solve this issue for me.
Many thanks in advance

**Comment by binary-ex-machina** [comment]
You can achieve this idea with the logic below

![image](https://user-images.githubusercontent.com/34610787/59379568-54f68e80-8d2d-11e9-9550-256b3de720c6.png)

**Comment by loigaak** [comment]
thanks @binary-ex-machina
