### ISSUE TITLE
Stable release of Bot platform

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1593]
Hey everyone,

There is now a stable of release of my trading platform:

Simple strategy builder load and save your strategy. Build using no coding at all, point and click indicators and candlestick pattern detection.

Manual and auto trading, lots of money management features, auto market selection and a growing community of traders sharing their strategy files.

Https://binarybottrading.eu

Currently windows is the only stable release. Linux coming in the next day or so, and Mac once I get a VM spun up to build the source code.

Cheers guys!!

EDIT; Linux release now on the site, same release as Windows now

**Comment by wilburforce83** [comment]
Live proof of a whole months trading during testing. Skip to the end to see all the results charted including the martingale reset on a stop loss day, plus some close shaves

https://youtu.be/tZRapylV0NY

**Comment by ZDEGLET** [comment]
я вижу на платформе рекламу всяких игр. куда нажать чтоб торговать так и не понял

**Comment by ceakuk** [comment]
The bots here are easy to build or free to get plus we can see the whole blocky to be sure nothing is fishy. are they  working ? 99.99% not
so why would we use your platform? what advantages do you offer?
What if somewhere in your code you make me loose and pick your rewards from affiliate to binary.com?
any conflict of interest?
I saw in the video you start at 0.35$ and chase the lossing trade upto 38.25$. thats a long chase similar to gambling. im sure you will soon chase from 0.35$ to risking 1000$ or more for the sake of earning cents as the martingale builds exponentially.

**Comment by Hooponopono** [comment]
do!!!  @ZDEGLET i think you have to download the application, @ceakuk is an application,100% you cannot see blockly because there is not. if you lose he not take nothing, before u talk and throw shit over the ppl is better u get information. the only conflict of interest is between your disinformation and your arrogance to know everything.

**Comment by ceakuk** [comment]
i say your video and anything that rely on martingale is bound to fail today or tomorrow. starting at 0.35$ and winning at 34$ is such a range. the next would be 70's the 150's then 300's then you blow your account chasing 0.31$
thats all i said

**Comment by wilburforce83** [comment]
Yeah that's just a choice. The platform isn't a strategy. It is a fully fledged platform like MT4 but simpler and just for binary.com. it has many money management options and even every single multiplier for each money management type is adjustable :)

**Comment by wilburforce83** [comment]
Also the problem with martingale and any negative progression is that it will always fail at a 50% win rate. The data you saw for a whole months trading was auto trading for up to three losses then manual override after that, this significantly increases you winerate making negative progression sustainable. 

In addition fixed stake would work also, if you strategy is above 55% win rate

**Comment by Ares31** [comment]
La has probado con dinero real... te ha dejado ganancias ???

**Comment by wilburforce83** [comment]
@Ares31 the YouTube video shows a whole months live trading results. Which earned about £700 off a 200 account. But that's just one strategy. The program is a whole platform that you can use to trade manually and automatically. It features full money management for manual trading which isn't available from binary.com you can also write your own strategies using tool which aren't available elsewhere such as candle pattern detection, support and resistance lines and all the normal indicators.

You try it on practice, and have a play. It's free to download and use

**Comment by Ares31** [comment]
puedes pasarme como lo programaste para q funione xq no lo entendi mucho disulpa mi ignorancia gracias

**Comment by george94mike** [comment]
@wilburforce83 can i email you

**Comment by wilburforce83** [comment]
@Ares31 Of course, I still need to do all the tutorial videos!!!

The strategy used in that month of that video is this ( you will need to unzip):


[PriceAction.zip](https://github.com/binary-com/binary-bot/files/3300126/PriceAction.zip)

1. Unzip the folder you will then have `PriceAction.strat` file
2. In bbtrader press the open icon in the top right next to your account balance
3. select PriceAction.strat
4. once loaded press play

If you need any more help or want to play with other strategies / build your own please join our Discord server https://discord.gg/ParaMDz 

Thanks!

**Comment by wilburforce83** [comment]
> @wilburforce83 can i email you

Of course, it is my GitHub username at gmail.com

**Comment by Ares31** [comment]
muchas gracias es bueno ver gente así que ayuda a los demas ... gracias otra ves

**Comment by Ares31** [comment]
Otra consulta los resultados debajo no se reinician cuando cierras secion, xq cuando lo inicio tiene los datos del dia  anterior... gracias

**Comment by wilburforce83** [comment]
@Ares31 Yes, that's intentional, so you can stop your session and carry on later. It will save your progress during a crash too. Just press the orange "reset" button to clear all the history and set the bit back to 0 and the initial stake 

Thanks

**Comment by Ares31** [comment]
Ahhh ok gracias

**Comment by ZDEGLET** [comment]
дайте ссылку самой платформы

**Comment by wilburforce83** [comment]
Hi @ZDEGLET the download link is in #releases on discord and above here 

https://binarybottrading.eu  click downloads or scroll down to them :)

**Comment by ZDEGLET** [comment]
@wilburforce83 
СПАСИБО БУДУ РАЗБИРАТЬСЯ КАК ПРИМЕНИТЬ ДЛЯ МОЕЙ СТРАТЕГИИ

**Comment by wilburforce83** [comment]
@ZDEGLET Всем привет. В течение следующих нескольких дней у меня будет учебное пособие по разработке стратегий на веб-сайте. Я был действительно занят своей дневной работой, так что еще не сделал это! Спасибо!

**Comment by simonsow19** [comment]
Hello, please I need help in setting up the bbtrader platform

**Comment by ceakuk** [comment]
@wilburforce83 
please guys watch the video. the martingale is like x3 and he looses as  high as 100$ then  trade like 300$ to recouver. if he was to lose 2 more time which is very possible then it will be 100$ to 300$ to 900$ chasing to win 0.35/2 (about 0.20$)
very bad bot. stay away. thanks for the effort though.
