### ISSUE TITLE
how to get histogram color 

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1594]
how to get histogram color ?
if previous color green and current color red make put
same as for call if previous color red and current color green
![Opera Snapshot_2019-06-14_035414_charts binary com](https://user-images.githubusercontent.com/42480287/59471241-2aedbb00-8e58-11e9-94b2-c391a89e9728.png)
CALL

PUT
![Opera Snapshot_2019-06-14_035259_charts binary com](https://user-images.githubusercontent.com/42480287/59471243-2b865180-8e58-11e9-9fcf-8f26f236b4f0.png)

@aaron-binary @binary-ex-machina @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by binary-ex-machina** [comment]
green color = if the actual value is higher then the previous
red color = if the actual value is lower then the previous

**Comment by Binaryboy707** [comment]
> green color = if the actual value is higher then the previous
> red color = if the actual value is lower then the previous

@binary-ex-machina   Brother please help me  My problem here 
https://github.com/binary-com/binary-bot/issues/1592

**Comment by navneetsinh** [comment]
> green color = if the actual value is higher then the previous
> red color = if the actual value is lower then the previous

@binary-ex-machina thanks replying, 
so it is not like candle, green or red,
just difference between current open and previous close,
if difference negative (current open " - " previous close) red color
and if difference positive (current open " - " previous close) red color

**Comment by Hooponopono** [comment]
the histogram is the difference between macd and signal,  when macd and signal are =, the histogram is at 0. if u want to have that, just make a logic that compares the value of the histogram before with now (or what u want). in your put picture u can see even the defect of macd,, macd and signal go up and the histogram go down, that is why macd have to work with other indicators

**Comment by navneetsinh** [comment]
> the histogram is the difference between macd and signal, when macd and signal are =, the histogram is at 0. if u want to have that, just make a logic that compares the value of the histogram before with now (or what u want). in your put picture u can see even the defect of macd,, macd and signal go up and the histogram go down, that is why macd have to work with other indicators

thanks to dear @Hooponopono

**Comment by binary-ex-machina** [comment]
@navneetsinh here is an example of how to check the color of histogram

![image](https://user-images.githubusercontent.com/34610787/59520532-8e034000-8ea0-11e9-9f1d-7e9fb668f2dc.png)

**Comment by navneetsinh** [comment]
> @navneetsinh here is an example of how to check the color of histogram
> 
> ![image](https://user-images.githubusercontent.com/34610787/59520532-8e034000-8ea0-11e9-9f1d-7e9fb668f2dc.png)

thanks dear @binary-ex-machina, I got the best value of response.
