### ISSUE TITLE
Create Aroon or Aroon Oscillator bot?

### ISSUE THREAD

**Issue by bonbon21** [binary-com/binary-bot#1596]
Hi,
Anyone can help me create bot for Aroon or Aroon Oscillator indicator?
Thank you

**Comment by binary-ex-machina** [comment]
Here is the arrow indicator

![image](https://user-images.githubusercontent.com/34610787/59520338-1b926000-8ea0-11e9-80d3-97ac320bb453.png)

**Comment by bonbon21** [comment]
> Here is the arrow indicator
> 
> ![image](https://user-images.githubusercontent.com/34610787/59520338-1b926000-8ea0-11e9-80d3-97ac320bb453.png)

I think it's error, can you check again? Trend is down but bot is up
![image](https://user-images.githubusercontent.com/51173257/59549986-ac943480-8f8f-11e9-9322-84ad324f8e0e.png)

**Comment by binary-ex-machina** [comment]
The indicator from this tab give different values from the one from tradingview https://tradingview.binary.com/v1.3.12/main.html

You can adjust the calculation and the blocks, i sent just an idea how to do it.
