### ISSUE TITLE
Price gap

### ISSUE THREAD

**Issue by thainano** [binary-com/binary-bot#1598]
as far as i know VOX100 is a 24/7 index. what is this?
![Untitled](https://user-images.githubusercontent.com/47125235/59546033-f2320c80-8f51-11e9-9016-652aa74ce524.png)

**Comment by Hooponopono** [comment]
maybe your internet
![Immagine](https://user-images.githubusercontent.com/50791712/59549103-e9a5fa00-8f82-11e9-83af-33197d4a1be5.png)

**Comment by binary-ex-machina** [comment]
normal here. Try to refresh the page.

![image](https://user-images.githubusercontent.com/34610787/59556981-30f0b280-8fa4-11e9-83c1-6bfb3ea21e5e.png)
