### ISSUE TITLE
how to get 3 ema

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1599]
kindly please help for getting 3 ema 10 ( 1 minute candle close )
![Opera Snapshot_2019-06-15_124231_charts binary com](https://user-images.githubusercontent.com/42480287/59548339-7e9cf900-8f6b-11e9-90ee-7d9f3d53e270.png)
@aaron-binary @binary-ex-machina @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by binary-ex-machina** [comment]
You can use my indicator Tripple EMA

https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#triple-ma

**Comment by Jalalahmadi** [comment]
I can not import on Bot !!  please help me.
Thank you , 
@binary-ex-machina

**Comment by navneetsinh** [comment]
> https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#triple-ma

oh, thank you very much @binary-ex-machina , and good thing is that I'm trying for 1 indicator and now I've lots of for analysis, thanks agin
