### ISSUE TITLE
Open an order with an especific expiration

### ISSUE THREAD

**Issue by delonbh** [binary-com/binary-bot#160]
Hello,

I'm trying to figure out how to open an position to ends at the end of the candle, out a GMT time especific.

IE.  Candle touches Bollinger, there are 2 minutes left to close. I wanna read this 2 minutes and plus 3, so, my order will expire at 3 minutes.

In the same way, I have an analises that will expire at 22gmt. Now 21 gmt.  The nice spot appeart at 21:26gmt, so how to put an order to expire at 34min (22gmt)

**Comment by aminmarashi** [comment]
Once you purchased a contract you can't extend or reduce the time it expires.
But you can still sell your open contract if available in the 3rd block like this:
<img width="272" alt="screen shot 2017-02-15 at 11 48 14 am" src="https://cloud.githubusercontent.com/assets/6560964/22959890/aa1c94c2-f374-11e6-8e60-dfd2f424f332.png">

**Comment by delonbh** [comment]
Dear Amin,

This is not exactly what I'm trying to explain.

![image](https://cloud.githubusercontent.com/assets/25711367/22971212/251e53b8-f35c-11e6-9620-3ed99f0c4b89.png)

**Comment by aminmarashi** [comment]
Maybe sth like this: <img width="455" alt="screen shot 2017-02-21 at 10 49 16 am" src="https://cloud.githubusercontent.com/assets/6560964/23148904/6ba36faa-f823-11e6-846d-840e5f311ff0.png">

**Comment by delonbh** [comment]
Interesting,  Ill try

Em seg, 20 de fev de 2017 23:49, Amin Marashi <notifications@github.com>
escreveu:

**Comment by aminmarashi** [comment]
I'll close this issue. If you still need assistant please reopen it.
