### ISSUE TITLE
Help with bot please!

### ISSUE THREAD

**Issue by m5gold** [binary-com/binary-bot#1602]
Hi guys
I´m just trying to do a simple bot, but something doesn´t work. I want to do this stuff:
- If last tick is 0 set prediction to 0
- If last tick is 1 set prediction to 1
- and so on...
I don´t know what i´m doing wrong. Here is the bot:

[binary-bot (17).zip](https://github.com/binary-com/binary-bot/files/3293234/binary-bot.17.zip)

Thanks.

**Comment by sinung21** [comment]
[dede 171.zip](https://github.com/binary-com/binary-bot/files/3293429/dede.171.zip)

**Comment by m5gold** [comment]
Ok, that what i was looking for. Thanks!!
