### ISSUE TITLE
rise/fall/draw - certain loss

### ISSUE THREAD

**Issue by thainano** [binary-com/binary-bot#1605]
for this broker. in rise/fall type
your chance of winning is 1/3 because if it is draw you still lose
other broker, if draw they will return the money
![used-margin](https://user-images.githubusercontent.com/47125235/59574941-7667c980-90e3-11e9-9d03-757043de5f4c.png)

**Comment by ZDEGLET** [comment]
ТАКИЕ УСЛОВИЯ НИЧЕГО НЕ ПОДЕЛАТЬ

**Comment by ArunGowthamm** [comment]
There is trade type called "Rise equal / Fall equal"

I dont try it before...but i saw it in the smart trade page.. give a try bro

**Comment by thainano** [comment]
for fairness, please add this option for binary bot,
or set the draw so that it will not take trader money
![Untitled](https://user-images.githubusercontent.com/47125235/59732132-45b69a00-9273-11e9-8e3a-83929f2bca0f.png)
