### ISSUE TITLE
КАК НА ФОРЕКСЕ СДЕЛАТЬ ПОКУПКУ ОПЦИОНА С КАЖДОЙ НОВОЙ СВЕЧИ НА 5 МИНУТАХ

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#1608]

**Comment by xremmy** [comment]
You will need  to set your expiry to 4 minutes if you want to play every new 5 minutes candle.

**Comment by ZDEGLET** [comment]
4 МИНУТЫ НЕ УСТРАИВАЕТ ХОТЯ БЫ 4,5 МИНУТЫ
