### ISSUE TITLE
I'm sorry, but it's currently impossible to set the prediction on a purchase. You'll need to define your prediction in the 1st block and you can't go back and change it when you want to purchase the contract.

### ISSUE THREAD

**Issue by bobnzelu** [binary-com/binary-bot#1611]
I'm sorry, but it's currently impossible to set the prediction on a purchase. You'll need to define your prediction in the 1st block and you can't go back and change it when you want to purchase the contract.
It's similar to #152. I hope we can implement that in the next version of the Bot.

_Originally posted by @aminmarashi in https://github.com/binary-com/binary-bot/issues/183#issuecomment-287669036_

Hi Amin, is there a way to capture previous "Exit Spot"?

I am trying to develop a strategy with this.

**Comment by binary-ex-machina** [comment]
Exit spot is the date the trade ended. Exit value is the tick it ended

![image](https://user-images.githubusercontent.com/34610787/59700577-f8322280-91c9-11e9-90b8-94f0c3c04606.png)

**Comment by bobnzelu** [comment]
See attached Screenshot of the values I am seeking and how to call those values for the next trade. The 5th column.



​Best regards,
​
Prodeus Technologies Nigeria Ltd, RC1201043, accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.

**Comment by binary-ex-machina** [comment]
Don't answer the email, post the image here.

**Comment by bobnzelu** [comment]
Thanks!



​Best regards,
​
Prodeus Technologies Nigeria Ltd, RC1201043, accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.

**Comment by bobnzelu** [comment]
Oh OK. Thanks. I understand it now. If you can further help, is there a way to get the numerical value of the last digit of "Exit Value"?

Thanks in advance

**Comment by binary-ex-machina** [comment]
yes, it's possible

![image](https://user-images.githubusercontent.com/34610787/59704000-7fcf5f80-91d1-11e9-98fb-4bc9b7db63f3.png)

**Comment by bobnzelu** [comment]
Thanks mate. Last question; How do I tell the Bot to wait (not to trade) till something happens?

**Comment by binary-ex-machina** [comment]
you can do this on the block 1 or 2. On block 1 you need to keep the bot on a loop, until the condition met, then you can break the loop and continue the flow.

On block 2, you just need to not purchase the contract until the conditions met. It will keep looping on it's on.

**Comment by bobnzelu** [comment]
I honestly don't get it. Sample maybe?

**Comment by bobnzelu** [comment]
I want to be able to keep purchasing quickly while I win, but if I lose, I want certain conditions to be met before I purchase a contract.

**Comment by binary-ex-machina** [comment]
in the image below you can see two examples, on the block 1 and 2.

block1
it will only go to the duration/stake block if the last tick is above the SMA5.

block2
it will only go to the block purchase rise it the last tick is above SMA5

![image](https://user-images.githubusercontent.com/34610787/59723390-e3bb4d80-91fc-11e9-9977-1261b791234d.png)

**Comment by bobnzelu** [comment]
OK. Problem now is that my indicators are from Trade results like Exit Value. 

So I want to be able to say if my Exit Value is "39", don't trade, until next Exit Value.

**Comment by binary-ex-machina** [comment]
exit value only appears after a trade. How can you wait for a exit value if you don't trade? what will exit?

you can keep looping on the block 4 until a condition is met

the image below shows a way of looping on the last block. Since the exit value is a tick, you can keep comparing the tick with the value you want. When the condition met, it will break the loop and trade again

![image](https://user-images.githubusercontent.com/34610787/59724942-27648600-9202-11e9-9fdd-220a72f79c8e.png)

**Comment by bobnzelu** [comment]
Thanks

**Comment by bobnzelu** [comment]
Tried this. THis does not work for the purpose. May I ask, is there a way to make a dud trade? Like a null purchase that does not result in either profit or loss -  The idea is just to read the patterns of the Exit value to make decisions for a future contract purchase.

**Comment by binary-ex-machina** [comment]
you can try to create "fake trades"

![image](https://user-images.githubusercontent.com/34610787/59778530-0b59f680-928d-11e9-8d1b-78ac8d40b190.png)

**Comment by bobnzelu** [comment]
Not sure I quite understand what you have done here.

**Comment by hotmatrixx** [comment]
> 
> 
> Not sure I quite understand what you have done here.

its pretty complicated, but clever. I do something similar.
basically, hes' not trading. He's saying 'If I bought Right now, what would the value be? set that to "entrytick"

once that timelimit expires, eg 1 tick or 1 minute, the  value is now set to 'exittick'.

These values give you a 'fake' trade open and close value, and you can use them to make a calculation based on the 'fake' open and close values of your 'fake' candle values.


Or, you could make real trades witht he minimum value and read the real values, then when the conditions you want are met, you can spike the value of your next trades to cover any potential losses.

**Comment by ceakuk** [comment]
if it was possible to set prediction on purchase, i believe  it would be easier to beat binary.com
they intentionally don't allow that and i don't see them ever allowing that
