### ISSUE TITLE
please add martingale like this

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1614]
please add martingale like this
1 loss 0.35
2 loss 0.35
3 loss 0.35
4 martingale 2X
5th martingale 10X
like this
thanks

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/59779541-d353b300-928e-11e9-9804-78b02d4f4082.png)

**Comment by dushanu** [comment]
brother can you send me as XML files
[lovi.martin.zip](https://github.com/binary-com/binary-bot/files/3307996/lovi.martin.zip)
appreciated your help
like this
1 loss 0.35
2 loss 0.35
3 loss 0.35
4 martingale 2X
5th martingale 10X

**Comment by dushanu** [comment]
because i want martingale start from 3rd stpep thanks bro..

**Comment by hotmatrixx** [comment]
he won't send you the bot. he, like me, wil show you how to do it, but wants you to do some of the work yourself. If you're not willing to learn by copying exactly what he's shown you, he's not going to make the effort to do it for you.

Nor would I..
