### ISSUE TITLE
Can possible for first run is as test run

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1616]
can it possible bot run is test and check all configuration of bot 
and get end of all get contract detail of profit
and display test complete now continue.....ok

in that case I want contract detail profit before start trade

is it possible ??

@aaron-binary @binary-ex-machina @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by binary-ex-machina** [comment]
Contract detail profit only has a value if you have a contract close first. If you didn't bought the contract, how you would have the profit it made?

You can get the payout amount of the actual contract parameters on block 2

![image](https://user-images.githubusercontent.com/34610787/59778046-1eb89200-928c-11e9-9054-95756199e068.png)

**Comment by navneetsinh** [comment]
> Contract detail profit only has a value if you have a contract close first. If you didn't bought the contract, how you would have the profit it made?
> 
> You can get the payout amount of the actual contract parameters on block 2
> 
> ![image](https://user-images.githubusercontent.com/34610787/59778046-1eb89200-928c-11e9-9054-95756199e068.png)

hey man thanks, @binary-ex-machina , I want it, I just tedious to finding that result, I found it from 4th section and after purchase, contract detail, but I didn't get that result before purchase, I tried to creating some type blocks too, disgusting...
end of all thanks dear,

**Comment by hotmatrixx** [comment]
I made a block that does this,  it runs once in 'setup mode'. Then it never gets used by my bot again. basically it's created as a function, and if 'setup=true" then it runs, but once it's run once, it sets 'setup' to false and the funciton never gets called  or parsed again.
