### ISSUE TITLE
Suggestion: Default Market

### ISSUE THREAD

**Issue by binary-ex-machina** [binary-com/binary-bot#1618]
I would like to suggest an alteration on the default market after the page loads. Today is AUD Index, the suggestion is to be Volatility Index 100. 

![image](https://user-images.githubusercontent.com/34610787/59779900-77d5f500-928f-11e9-9e72-34feafc7a883.png)

**Comment by navneetsinh** [comment]
> I would like to suggest an alteration on the default market after the page loads. Today is AUD Index, the suggestion is to be Volatility Index 100.
> 
> ![image](https://user-images.githubusercontent.com/34610787/59779900-77d5f500-928f-11e9-9e72-34feafc7a883.png)

I'm agree too, some times run start and get message market close or run success and contract detail get differ of mind than, oh,, change market.

**Comment by aaron-binary** [comment]
Hey @binary-ex-machina,

Will discuss it with the team. Thanks for your suggestion, we appreciate it.

Regards,
Aaron

**Comment by Diegogc11** [comment]
Hello! I need help for this issue, can somebody view it please? https://github.com/binary-com/binary-bot/issues/1446 thank you!

**Comment by binary-ex-machina** [comment]
@Diegogc11 that's not possible to get from the blocks.
