### ISSUE TITLE
How can i get change(%)

### ISSUE THREAD

**Issue by laxracorp** [binary-com/binary-bot#1619]
How can i get change(%) i want to use it on my strategy but i cant get it,help

**Comment by laxracorp** [comment]
![SEN](https://user-images.githubusercontent.com/36192147/59813591-fa9b9600-9309-11e9-8175-fa40d335cc1c.PNG)

**Comment by laxracorp** [comment]
like the the highlighted values

**Comment by navneetsinh** [comment]
check,
![Opera Snapshot_2019-06-20_131658_bot binary com](https://user-images.githubusercontent.com/42480287/59830702-cc47a600-935d-11e9-8dd4-45848770306c.png)

**Comment by ZDEGLET** [comment]
@navneetsinh 
Пришли мне этот робот zdeglet@gmail.com
спасибо

**Comment by laxracorp** [comment]
@navneetsinh Please can you upload your file,i dont know what i'm doing wrong.

**Comment by munzeer** [comment]
@laxracorp attach your file here. We can make solution easily

**Comment by laxracorp** [comment]
[binary-bot.txt](https://github.com/binary-com/binary-bot/files/3316486/binary-bot.txt)

**Comment by navneetsinh** [comment]
> [binary-bot.txt](https://github.com/binary-com/binary-bot/files/3316486/binary-bot.txt)

your blocks are ok,

just notification 

![Opera Snapshot_2019-06-22_182831_bot binary com](https://user-images.githubusercontent.com/42480287/59964232-c4356500-951b-11e9-8d68-f010da809ae4.png)

**Comment by laxracorp** [comment]
the problem is mine is not showing more than 0.01%

**Comment by navneetsinh** [comment]
you are testing in volatility 10, and it value of changes are very low, it is rounding of with 2 decimal value,
you have to test in volatility 100, and if you want in other volatility you have to set with its decimal points, it can be 0.0001% or 0.00001%.

**Comment by laxracorp** [comment]
@navneetsinh  can you explain how i can work with the decimals for each index.
if you can list the index with the corresponding decimal formula
