### ISSUE TITLE
List of markets per country

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1623]
@aaron-binary hi, where can I get a list if which markets are available in which counties?

Thanks!!

**Comment by anton-binary** [comment]
Hey @wilburforce83 ,
May we know why you need that? 

Thanks,
Anton

**Comment by anton-binary** [comment]
Basically, you can get use this call [https://developers.binary.com/api/#landing_company](https://developers.binary.com/api/#landing_company) to get the landing company for the specific loginid and then you can call this one [https://developers.binary.com/api/#asset_index](https://developers.binary.com/api/#asset_index) to get the assets list.

On this page you can find out which country sits under which landing company.
https://www.binary.com/en/regulation.html

Hope that helps.

Anton.

**Comment by wilburforce83** [comment]
That's great thanks. I have a user on my third party platform receiving a "Token is invalid" upon placing a trade, he is logged in with the token, therefore it is valid. I just wanted to check to make sure he is not trying to trade an asset which is not available to him :)

Thanks!
