### ISSUE TITLE
How to apply SMAA and EMAA indicator in charts

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1624]
![Opera Snapshot_2019-06-23_125837_bot binary com](https://user-images.githubusercontent.com/42480287/59973000-a9fc9500-95b6-11e9-9a8c-2936cd7f2fa8.png)
@aaron-binary @binary-ex-machina @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by binary-ex-machina** [comment]
EMA and SMA arrays are a list of values of the indicator. When you put in the chart, they are a line of values through time, so a list of values. there is no sense in have a list of values of the moving averages on the chart, since the chart only shows a list of values.

**Comment by hotmatrixx** [comment]
> 
> 
> ![Opera Snapshot_2019-06-23_125837_bot binary com](https://user-images.githubusercontent.com/42480287/59973000-a9fc9500-95b6-11e9-9a8c-2936cd7f2fa8.png)
> @aaron-binary @binary-ex-machina @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

you're asking a really good question though.
The "input List" needs to be something like the 'ticks' list, or the 'candle values -closed-' list, etc.
once you put those in, you can start to work with the values, by assigning a specific value in that list as a variable, or by using it as an output to make a calculation....

hard to explain, easy to do.....

for exaMPLE
![image](https://user-images.githubusercontent.com/49715381/60333755-f5b3a200-99ed-11e9-814a-6465a365d5c5.png)
this reads the SMA and compares it to the last closed candle value.
There is basically no difference that I can see between the SMA and the SMAA unless the SMAA charts values that I don't know how to access.

**Comment by navneetsinh** [comment]
> EMA and SMA arrays are a list of values of the indicator. When you put in the chart, they are a line of values through time, so a list of values. there is no sense in have a list of values of the moving averages on the chart, since the chart only shows a list of values.

ok, I understand, there is sma = sma array get from last 1

**Comment by navneetsinh** [comment]
> > ![Opera Snapshot_2019-06-23_125837_bot binary com](https://user-images.githubusercontent.com/42480287/59973000-a9fc9500-95b6-11e9-9a8c-2936cd7f2fa8.png)
> > @aaron-binary @binary-ex-machina @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost
> 
> you're asking a really good question though.
> The "input List" needs to be something like the 'ticks' list, or the 'candle values -closed-' list, etc.
> once you put those in, you can start to work with the values, by assigning a specific value in that list as a variable, or by using it as an output to make a calculation....
> 
> hard to explain, easy to do.....
> 
> for exaMPLE
> ![image](https://user-images.githubusercontent.com/49715381/60333755-f5b3a200-99ed-11e9-814a-6465a365d5c5.png)
> this reads the SMA and compares it to the last closed candle value.
> There is basically no difference that I can see between the SMA and the SMAA unless the SMAA charts values that I don't know how to access.

thanks to revert me, 
here is the same thing is sma close default 14 > last tick, 
ya, ok thanks dear,
