### ISSUE TITLE
Strategy

### ISSUE THREAD

**Issue by CristianGrig** [binary-com/binary-bot#1625]
Dear All,

Could you please help in setting up a double RSI strategy. For example:
If RSI 5 > 75 and RSI 20 > 65 purchase rise.

Also, could you help adding MACD into equation?

Many thanks for all your help in advance.

**Comment by ceakuk** [comment]
@CristianGrig 
i can do it for 5 $ in 1 hour

**Comment by binary-ex-machina** [comment]
@aaron-binary i think the $5 on hour guy is spamming on all issues

@CristianGrig never pay to anyone trying to make money on a repository, where people share things for free. You didn't specified the MACD filter for the trades, below an image of how you can have multiple indicators as filters

![image](https://user-images.githubusercontent.com/34610787/60058119-8a9c5f80-96bd-11e9-8f05-3add97e76c79.png)

**Comment by CristianGrig** [comment]
@aaron-binary Hi Aaron, 
Many thanks for your help again :) the first MACD setting I was thinking of was if the MACD line crosses the signal line purchase rise.

And second setting was based on the histogram. For example something like: if at the close of candle last bar of histogram is green purchase rise.

Another request if I may, how can you set up a bot to do the following:
If last tick was up purchase rise and if down purchase fall.

And the last one I promise:) , can you please set up the following:
If in the first 5 seconds since the candle opened direction is rise or candle crossed MA purchase rise for the remaining of the minute ( in this case 55 seconds )

Thank you so much for your great help!

Cristian
