### ISSUE TITLE
How add macd indicator and move average cross?

### ISSUE THREAD

**Issue by wilsonsiena** [binary-com/binary-bot#163]
![temp macd](https://cloud.githubusercontent.com/assets/25809038/23017921/40998974-f423-11e6-947c-a3ac8654f6d3.JPG)

![images](https://cloud.githubusercontent.com/assets/25809038/23017741/a8f88ebc-f422-11e6-84a3-20b06779d79d.png)

**Comment by ekozhin** [comment]
![default](https://cloud.githubusercontent.com/assets/24454432/23039583/06b6b192-f49f-11e6-843e-8f8e7d907919.jpg)

**Comment by ekozhin** [comment]
if MACD cross SMA 21 from the bottom up  - RISE
if MACD cross SMA 21 from the top down  - FALL

**Comment by wilsonsiena** [comment]
Could you send me the xml? Please.

**Comment by wilsonsiena** [comment]
dont working

**Comment by ekozhin** [comment]
tell what strategy do you want? MACD crosses with RSI ?

**Comment by wilsonsiena** [comment]
Yes

**Comment by wilsonsiena** [comment]
Would you do it for me please? Thank you

**Comment by ekozhin** [comment]
may intersect both SMA and MACD if they are in different positions of the screen and overlap? change the settings of your strategy

**Comment by aminmarashi** [comment]
I'm going to close this issue, if you still need help please feel free to reopen it.
