### ISSUE TITLE
Running bot 24/7

### ISSUE THREAD

**Issue by TheShaltys** [binary-com/binary-bot#1635]
Hello, Is there somehow a way to run binary bot 24/7 without having your computer on? Officialy? Or not officialy (with API token)?

Thanks for reply, 
Shaltys

**Comment by binary-ex-machina** [comment]
You can run the bot on bot.binary.com without stop, as well create a system to run without stop and using the API token

**Comment by hotmatrixx** [comment]
> 
> 
> Hello, Is there somehow a way to run binary bot 24/7 without having your computer on? Officialy? Or not officialy (with API token)?
> 
> Thanks for reply,
> Shaltys

"Not Really"
Binary.com doesn't provide servers or infrastructure or hardware that will run your bot for you.
You need to find a way to do it yourself.

Although I just run a low-powered laptop to run my bot, if that's not an option for you, then possibly a very cheap VM could work for you?

A Managed Hosting Solution actually would cost me less to use than the power my laptop consumes in a month.

**Comment by James-Ngigi** [comment]
You can use an API third party program or just rent a cheap vps and open a browser with bot running. Leave the server on remotely and do something else on your workstation.
