### ISSUE TITLE
EMA price (high+low)/2

### ISSUE THREAD

**Issue by bonbon21** [binary-com/binary-bot#1641]
Hi, how to change price type of ema to (high+low)/2 in bot?
Thank you

**Comment by binary-ex-machina** [comment]
@bonbon21 you can achieve like this. You need to loop and insert the calculation on a list, then use it on the indicator as a input list
![image](https://user-images.githubusercontent.com/34610787/60523947-0b60ea00-9cc2-11e9-8ad9-66c1506c513c.png)
