### ISSUE TITLE
how to set prediction like this

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1644]
like tnis
0 buy
1 buy 
2 but
.......
9 buy
0 buy
1buy circul
like this i want it digital match 
thanks

**Comment by dushanu** [comment]
everytime change prediction in a row
0123456789

**Comment by dushanu** [comment]
not random

**Comment by dushanu** [comment]
can you help me please

**Comment by binary-ex-machina** [comment]
@dushanu you can like this

![image](https://user-images.githubusercontent.com/34610787/60525294-7d3a3300-9cc4-11e9-9ba5-a4fa69b32c85.png)

**Comment by dushanu** [comment]
thanks you very much 

> @dushanu you can like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/60525294-7d3a3300-9cc4-11e9-9ba5-a4fa69b32c85.png)

thank you very much @binary-ex-machina
