### ISSUE TITLE
I need reminder-notification when are candle green or red, help

### ISSUE THREAD

**Issue by mare69** [binary-com/binary-bot#1654]
I would be very grateful if some wone can make reminder when are candle green or red 1min chart
![Z](https://user-images.githubusercontent.com/52427410/60525228-45e07c00-9cee-11e9-9fc9-5981c262c670.PNG)

Sample:

1min graf

red candle
green candle
red candle
green candle
Now got some waring or reminder push up notifi....

Can you make this?

**Comment by binary-ex-machina** [comment]
you can get the warning like in this image below

![image](https://user-images.githubusercontent.com/34610787/60525736-503a5000-9cc5-11e9-9ccd-39563f62c8dc.png)

**Comment by mare69** [comment]
Can you make this?

Next i need that i start trade
red candle  (loose)     Martinangle and start trade (i put preset prices for all trades)  
green candle (loose)   Martinangle cahange bet and start trade agan
red candle  (loose)     Martinangle and start trade
green candle (loose)   Martinangle cahange bet and start trade agan
red candle  (loose)     Martinangle and start trade
green candle (winnnnnnnnnn)  
Start looking:
red candle
green candle
red candle
green candle
and trade from begining

pls help and tnx ex-machina for helping...you can sen me email marjanb008@gmail.com

**Comment by mare69** [comment]
I would be very happy to get xml at least the first solution....

**Comment by mare69** [comment]
Please i will wait..

**Comment by binary-ex-machina** [comment]
@mare69 i don't post .xml bots here, just the image of the blocks. I'm sure you can use the mouse and replicate the same thing i sent. It will be good for you to learn how to click and drag and about the mechanic of the site, as well you will be able to improve the strategy

**Comment by mare69** [comment]
i cant see wher i get ,,and,, end in candle list 
get#from end....

**Comment by mare69** [comment]
i have worksheet but i cant find your ,,and,, end ,,candle list
get#from end...,,
![worksheet](https://user-images.githubusercontent.com/52427410/60529773-9c9e8380-9cf7-11e9-9488-5b13e09c8faa.PNG)

**Comment by mare69** [comment]
wher i can find good tutorials?

**Comment by binary-ex-machina** [comment]
You can start paying attention to what you have

![image](https://user-images.githubusercontent.com/34610787/60529890-f8ecad80-9ccd-11e9-8b88-ff891fca002f.png)

**Comment by mare69** [comment]
yes but a cant find ,,and,, how you get this? so you need only 10min or less and i loking 3 days
i need to try this strategy:

so i wont trade 1min chart when condision of market are like that (pattern):
red candle
green candle
red candle
green candle
i get notification and start trade down next 1min candle  ( before I turn on the bot, I set my prices)
1. down if i lose  start trade up  next 1min candle
2. up   if i lose start trade down  next 1min candle 
3. down .........
4. up      ........
5. down ........ 
6. up  ......i win  STOP trading and start looking pattern:
red candle
green candle
red candle
green candle
i get notification and start trade down next 1min candle .....reapit

p.s: binary-ex-machina i will need have of year to making this :(

**Comment by binary-ex-machina** [comment]
You will invest in learning to make your idea. I already gave you the basis to start, just try to build. There is a menu of the blocks on the left side, explore them. It will take 2min to read all the blocks.

**Comment by mare69** [comment]
tnx

**Comment by mare69** [comment]
pls help

How you get this? 
![how you get this](https://user-images.githubusercontent.com/52427410/60746106-78ec6f00-9f7d-11e9-87a7-a71812fa1942.PNG)

some tutorial plase...

**Comment by navneetsinh** [comment]
> pls help
> 
> How you get this?
> ![how you get this](https://user-images.githubusercontent.com/52427410/60746106-78ec6f00-9f7d-11e9-87a7-a71812fa1942.PNG)
> 
> some tutorial plase...

![Opera Snapshot_2019-07-06_080943_bot binary com](https://user-images.githubusercontent.com/42480287/60750420-ab21bf00-9fc5-11e9-808c-b000126789c9.png)
![Opera Snapshot_2019-07-06_081040_bot binary com](https://user-images.githubusercontent.com/42480287/60750421-abba5580-9fc5-11e9-80fd-95ab2ad2f433.png)

**Comment by AFPEMI** [comment]
Here is how you do it
![image](https://user-images.githubusercontent.com/52548202/61560689-59f0e100-aa43-11e9-9680-925025a3f4d6.png)

![image](https://user-images.githubusercontent.com/52548202/61560807-ac320200-aa43-11e9-8d4f-257e4aca91d5.png)

![image](https://user-images.githubusercontent.com/52548202/61560870-e13e5480-aa43-11e9-84a8-4f3381d7351a.png)

And finally you will have

![image](https://user-images.githubusercontent.com/52548202/61561030-498d3600-aa44-11e9-8e95-4c3f0226b2c4.png)

**Comment by Sonal-sl** [comment]
hey I am from Sri Lanka please send me a bot digit differ green candle to my email 
sonalnimsara229@gmail.com
