### ISSUE TITLE
Heikin Ashi strategy

### ISSUE THREAD

**Issue by Diegogc11** [binary-com/binary-bot#1657]
Hello! I've been using IQ Option for a while and I've seen that heikin ashi candles help a lot in detecting price action patterns, I've noticed that Binary bot charts have this candles too. I'm new in making bots so I want to know if somebody can help me to do hekin ashi candles to use it with indicators, here's an issue in which somebody has the formula to do it https://github.com/binary-com/binary-bot/issues/1446  I don't know how make the same but in the format of a candle list. thanks a lot!!

**Comment by binary-ex-machina** [comment]
@Diegogc11 you can't replicate the Heikin ashi analysis on the bot binary blocks. The calculation will not be precise and there will be a lot of errors.

**Comment by Diegogc11** [comment]
Ok I understand! thank you!
