### ISSUE TITLE
Robot based on the sequence of candles

### ISSUE THREAD

**Issue by wilsonsiena** [binary-com/binary-bot#166]
I need a robot, Thank you.

![candles](https://cloud.githubusercontent.com/assets/25809038/23097021/2eabbd4a-f608-11e6-8ffa-66ed14e26799.jpg)

**Comment by delonbh** [comment]
Maybe: https://gist.github.com/aminmarashi/094961982556d36639b9055a1d40ec06

**Comment by wilsonsiena** [comment]
Dont working. No entry. Help me please.

**Comment by aminmarashi** [comment]
The original three line strike needs trend detection, therefore it buys when more confident. But I implemented [this](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/simple_three_line_strike.xml) according to your strategy.

**Comment by aminmarashi** [comment]
The original three line strike needs trend detection, therefore it buys when more confident. But I implemented [this](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/simple_three_line_strike.xml) according to your strategy.

**Comment by wilsonsiena** [comment]
Thank you Amin

**Comment by izy123** [comment]
please help me i also need that  no entry

**Comment by wilsonsiena** [comment]
Here https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/simple_three_line_strike.xml

**Comment by izy123** [comment]
hello thank you for the script but it's only for call how can i make it do put option.thank you.

**Comment by aminmarashi** [comment]
It's for both `CALL` (`Rise`) and `PUT` (`Fall`)
