### ISSUE TITLE
Help create the conditions !!

### ISSUE THREAD

**Issue by Batekmax** [binary-com/binary-bot#1660]
Hello! Help please, I can not figure out how to do it right. In general, let's say we have a list of rates, I need to make sure that when I lose Suppose -0.35 of total profit bot increased the bid from the list until it is + 0.35 to total profit and starts the cycle all over again.`
[Qwerty.zip](https://github.com/binary-com/binary-bot/files/3353212/Qwerty.zip)

**Comment by binary-ex-machina** [comment]
You can do a stake list cycling like this image below. It will use the first item of the list as stake when a win occur. In case you don't want to reset the stake, remove the logic form block 4.

![image](https://user-images.githubusercontent.com/34610787/60603188-a1ad1280-9d8b-11e9-881d-11b63dc18684.png)

**Comment by Batekmax** [comment]
it's easy to do everything yourself, but how to make it possible to say: rate 0.35 (profit), then again 0.35 (profit) then 0.35 (loss), 0.37 (loss) 0.39 (loss) total -0.41 cent, then 0.44, (profit), 0.47 (profit) is a total of approximately +0.40 cents and now the rate has been reset to 0.35 and so on in a circle before a loss.

**Comment by binary-ex-machina** [comment]
@Batekmax whats the logic on raising the stake like that? how much will be the rate of change ? You don't need a circular stake, you need to compare how much is the actual profit to reset the stake and increase the stake until you reach that level

**Comment by Batekmax** [comment]
http://www.youtube.com/watch?v=7AR1peB1atk&list=PLeGM-_PONFzeN0pw4fTF6Hcwj5vVeFkcf

This shows what I cannot do.

**Comment by binary-ex-machina** [comment]
i see what you want to do. You can change the 1.125 to other number to decrease the rate of stake. IF the profit is above 0.3, it will reset the stake and the profit. Otherwise, it will increase the stake until recover.

![image](https://user-images.githubusercontent.com/34610787/60616778-a3d19a00-9da8-11e9-8ecd-2830a6faf7c2.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina Where is this tool?

![ssss](https://user-images.githubusercontent.com/51996252/60651297-1d808b00-9e70-11e9-9804-ce56c4ddf086.PNG)

**Comment by Herotaiko** [comment]
I found it. Thank you very much.

**Comment by Herotaiko** [comment]
My results are not good
![qqqq](https://user-images.githubusercontent.com/51996252/60652929-3f2f4180-9e73-11e9-9b5b-4ecff511feb6.PNG)
![qqq](https://user-images.githubusercontent.com/51996252/60652937-422a3200-9e73-11e9-9607-670b63f68dcd.PNG)

**Comment by Herotaiko** [comment]
OMG
![3333](https://user-images.githubusercontent.com/51996252/60666942-81b44680-9e92-11e9-879c-43c3222f7e15.PNG)

**Comment by Herotaiko** [comment]
I try to set it up like this, but when it reaches the target, it doesn't stop working.
![zzz](https://user-images.githubusercontent.com/51996252/60668296-d7d6b900-9e95-11e9-9dcc-78fe35245054.PNG)

**Comment by navneetsinh** [comment]
what's your set up in fourth block?

**Comment by Herotaiko** [comment]
I think it's a good bot, but I want to have a stop loss  and a profit target to prevent losses that come out of the account.

i want insert 
- account balance
- profit target
- stop loss

I tried to set it but not as a result.

![qq](https://user-images.githubusercontent.com/51996252/60675737-43755200-9ea7-11e9-931a-affabd4e60bd.PNG)

**Comment by Eshhh** [comment]
You have to do something like this

![image](https://user-images.githubusercontent.com/33750313/60704919-69403c80-9f23-11e9-82f3-7cb1c19c5cd7.png)

**Comment by Herotaiko** [comment]
@Eshhh Ask another question, where is this tool?
Thank You.
![ddddd](https://user-images.githubusercontent.com/51996252/60709110-deb70780-9f39-11e9-9c3f-5fdbe0f7bb95.PNG)

**Comment by Herotaiko** [comment]
Sorry i found it

**Comment by Herotaiko** [comment]
> http://www.youtube.com/watch?v=7AR1peB1atk&list=PLeGM-_PONFzeN0pw4fTF6Hcwj5vVeFkcf
> 
> This shows what I cannot do.
@Eshhh @binary-ex-machina  @Batekmax 
If the control of Mattingale is excellent
