### ISSUE TITLE
Given candle list is not valid

### ISSUE THREAD

**Issue by Dankettan** [binary-com/binary-bot#1661]
I got this error - please some know ?
![given candle](https://user-images.githubusercontent.com/49433087/60569204-f1460b00-9d98-11e9-85f5-dd8b12d2428d.png)

**Comment by binary-ex-machina** [comment]
try to define the Candle Set on the first block as Empty list.

![image](https://user-images.githubusercontent.com/34610787/60603382-08323080-9d8c-11e9-9334-70f1202ba269.png)
