### ISSUE TITLE
Digit Under buy after analysis

### ISSUE THREAD

**Issue by andreksu** [binary-com/binary-bot#1665]
The strategy is simple: analyse last 25 digits to make an entry spot. Prediction is 7. If digit is 7 or over 7 after 3x times, the bot buys the next tick.

Example:
2821.10
2821.15
2820.17
2820.19
2821.17 > set buy AFTER this exit spot is made, so if:
2820.15 > win

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/60603721-ad4d0900-9d8c-11e9-91f7-8e7b23d2b7f5.png)

**Comment by andreksu** [comment]
> you can do like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/60603721-ad4d0900-9d8c-11e9-91f7-8e7b23d2b7f5.png)

Thanks for the quick reply. I'll test this!

**Comment by andreksu** [comment]
I've tried to put a martingale but its not working as intended. Could you help me please?

<img width="715" alt="image" src="https://user-images.githubusercontent.com/45677796/60609169-6d3f5380-9d97-11e9-9dbf-bd79558264c6.png">
