### ISSUE TITLE
VPN for Binary bot

### ISSUE THREAD

**Issue by fm3711** [binary-com/binary-bot#1667]
Hello. 
I am using my own bot on binary.com
I wanted to ask how can I run it on VPN, because it is difficult to leave a computer open for the day. 
Do you have any system for it? 
I found a binary VPN on PlayMarket for Android phone, but I dod not understand how to use it. It has only one button to turn it ON or OFF. 
If you can help, please describe it details, because I am new to it. 

Thank you!

**Comment by buckman1974** [comment]
Does a VPN make any difference at all to wins or losses?

**Comment by fm3711** [comment]
Of course not. It just gives you a uninterrupted internet connection. Otherwise I have to leave computer open for the day. It is not comfortable. I have kids, and one time they stopped the bot and I had abig loss. And internet connection can be interrupted
