### ISSUE TITLE
Repeat trade, need help

### ISSUE THREAD

**Issue by thanh301** [binary-com/binary-bot#1668]
So I was using a bot running on odd/even type, when a row of 3 odd or even appear it will make a reverse purchase. The thing is I want to set it keep make a same purchase until it won then wait for a new row (with martingale). Can anyone help me a code for that action?

Sorry for my broken english

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/60683355-c1b50280-9e6d-11e9-824b-caa05ec2a1e2.png)
