### ISSUE TITLE
Morning star or evening star 

### ISSUE THREAD

**Issue by sswbsc** [binary-com/binary-bot#1671]
can any one add evening star or morning star candle system for this block code...
thanks for helping!
![Capture](https://user-images.githubusercontent.com/52449125/60679675-1f654100-9ea6-11e9-9cb2-733fe17ae80b.PNG)

**Comment by binary-ex-machina** [comment]
Here is how to calculate morning start candle pattern

![image](https://user-images.githubusercontent.com/34610787/60683802-34bf7880-9e70-11e9-8c29-dfbe71ff174c.png)

and here is how to calculate evening start candle pattern

![image](https://user-images.githubusercontent.com/34610787/60683813-4ef95680-9e70-11e9-9847-8f1b86470273.png)

**Comment by sswbsc** [comment]
thanks man....z :) :) 👍 🥇

**Comment by sswbsc** [comment]
this block code doesn't appear in my block wall...how i get this?
![Capture](https://user-images.githubusercontent.com/52449125/60701040-da79f280-9f17-11e9-8b3c-68b567c12988.PNG)

**Comment by aaron-binary** [comment]
Hi @sswbsc,

The block is indeed a bit hard to find, but you should be able to get it at **Binary** -> **Tick Analysis**. We're working on improving this. 

Regards,
Aaron

**Comment by lasaidhari** [comment]
> 
> 
> Here is how to calculate morning start candle pattern
> 
> ![image](https://user-images.githubusercontent.com/34610787/60683802-34bf7880-9e70-11e9-8c29-dfbe71ff174c.png)
> 
> and here is how to calculate evening start candle pattern
> 
> ![image](https://user-images.githubusercontent.com/34610787/60683813-4ef95680-9e70-11e9-9847-8f1b86470273.png)

the right duration for the bot

**Comment by Herotaiko** [comment]
@sswbsc 

Please provide .xml file.
