### ISSUE TITLE
Help on a Bot for binary.com

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1672]
Hello there, I'm trying to set up a Bot for Binary.com to identify a sequence of three(3) candles of the same color and to open a trade on the opposite direction after the closing of the third candle.
I came up with the script attached, but it's not reading the candles properly. Some time it reads a red candle as green, and vice-versa.
Can you please help?
Thank you
[Candles AFP GOOD 2.zip](https://github.com/binary-com/binary-bot/files/3360471/Candles.AFP.GOOD.2.zip)

**Comment by binary-ex-machina** [comment]
your script has a lot of things that i didn't find useful for the strategy you want to build

below is way to do what you want, if 3 candles green (counter = 3) place Fall or if 3 candles red (counter = -3) place Rise. It will analyse the candles at the last tick of the actual candle

![image](https://user-images.githubusercontent.com/34610787/60689167-e7073800-9e90-11e9-8115-732b0afcb166.png)

**Comment by AFPEMI** [comment]
Hi there, thanks for your fast reply.
Please excuse my lack of knowledge, but I cant find the "in candle list  get # from end  1  with interval: default" on my logic commands list.
Is there any specific way to load it?
Thanks

**Comment by AFPEMI** [comment]
Never mind, I've got it
Thanks again

**Comment by AFPEMI** [comment]
Hi there, I've changed the script as you've suggested, but its not working. It opens a put operation at start after the first candle is formed and that's it. It doesn't  do anything else
[Candles AFP GOOD Test.zip](https://github.com/binary-com/binary-bot/files/3360757/Candles.AFP.GOOD.Test.zip)

**Comment by AFPEMI** [comment]
It's counting one candle as three candles and opening the trade at the candle's closing.
