### ISSUE TITLE
Staggered Martingale Block?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1677]
Is it possible @binary-ex-machina to get a staggered Martingale block?

i have seen them before rarely in other bots, but just need to add it to mine, so for example on Digit Differs : 

ie: $10 loss
Next trade : Martingale x6 = $60 = Win = $5.93
Next trade : Martingale x6 = $60 = Win = $5.93

To recover?

instead of Digit Differs going for a 10 times amount in ONE trade?

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-07-06_015221_bot binary com](https://user-images.githubusercontent.com/42480287/60743822-cde5b080-9f90-11e9-9e1b-8f7e4be3c7d4.png)

Check this, not tested.......

**Comment by buckman1974** [comment]
Right so this block does take 2 x 5.5 martingale trades after a single losing one to recoup?
Then goes back to normal trade?
