### ISSUE TITLE
    High/low Martingale bot not running right..

### ISSUE THREAD

**Issue by Woscarr** [binary-com/binary-bot#168]
Hi I seem to having a problem with a bot script, the script says one odd then one even and when it follows this it actually provides pretty good results. For long strings of runs it adheres to the put/call sequence.  Then all of a sudden the bot runs 6 or 7, 4 or 5 puts/calls in a row on a loosing streak and wipes me out ! How can a script do something it's not programmed to do !? Error in the script possibly? Mistake I made in the build ?
I just used one of the available scripts and modified it a little. I've added a couple of pics. 1 shows the bot in the builder. 2 shows a loosing streak of 3 puts then another put that won so 4 in a row. I've seen 7 in a row although I don't have a screen shot of that.

I would like the bot just take one put and one call consecutively and never deviate from this sequence ?! Is it possible. 

Also a 4 second pause on a loss would nice too. Can it be done with the builder ?

Hope to get a answer to these questions.
Thanks Wayne.

![botscript](https://cloud.githubusercontent.com/assets/25891231/23111253/6647a578-f6f5-11e6-8996-65de5a92d45d.jpg)
![botrun](https://cloud.githubusercontent.com/assets/25891231/23111264/701a9ca4-f6f5-11e6-8a4e-f00399839268.jpg)

**Comment by aminmarashi** [comment]
Seems like our first version of our martingale. I implemented [this](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/martingale_alternate_even_odd.xml) for you, using our newest version of martingale which is easier to modify.
And yes, you can use the timeout block to delay `Trade Again` block.
You can find the modified strategy with time delay [here](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/martingale_alternate_even_odd_with_timeout.xml)
<img width="212" alt="screen shot 2017-02-21 at 10 45 51 am" src="https://cloud.githubusercontent.com/assets/6560964/23148848/f3180a3c-f822-11e6-97ec-952e9f1657e9.png">

**Comment by Woscarr** [comment]
Hi I really appreciate  you getting back to me. I'll have to admit I'm
pretty new to this and I'm not sure how to use these scripts you supplied.
I've only used the builder it's self adding blocks from the side menu. So
if you could point me in the right direction would be greatly appreciated.
Thanks again.
Wayne.

**Comment by aminmarashi** [comment]
It's really easy to do:
1. Right click on [this](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/martingale_alternate_even_odd_with_timeout.xml) and click `Save As` and save the file where you can find it easily
2. Drag and Drop the saved file into Binary Bot
3. Enjoy!

If this procedure does not work for you or if you have any other inquiries regarding how to use the bot. Please feel free to contact us: marketing@binary.com.

**Comment by Woscarr** [comment]
That did the trick.. Thanks again.
