### ISSUE TITLE
binary-ex-machina как сделать?

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#1680]
Пожалуйста!!! как сделать чтоб робот считал количество прибыльных и убыточных сделок если это возможно? Если возможно покажите пример блока)))

**Comment by binary-ex-machina** [comment]
If I understood it right, you want to calculate the number of wins and losses, right?

you can do like this

![image](https://user-images.githubusercontent.com/34610787/60774933-37c99b80-a0f2-11e9-8265-652f8472c3ec.png)

**Comment by ZDEGLET** [comment]
огромное спасибо!!!
