### ISSUE TITLE
Help me make a bot go in three rounds

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1681]
I have a bot that works well.

The maximum loss limit, maximum loss streak and expected win are also working well.

But what I need help on is this....

If the trade reaches a 'Maximum loss streak of 5' or  maximum loss amount of 100$ , I want the trade to switch over to a second level where the new 'expected win amount , first stake and maximum loss amount' will be changed to double of its initial value.

Also, if its reached, I want it to automatically enter a third level where the mentioned values will be triple its starting value.

For instance, 

if  First stake is 1$,
Expected win is 100$
Maximum loss is 200$
Maximum loss streak is 5

If the maximum loss streak or maximum loss amount is reached, I'd want it to automatically switch to a second level where the listed first stake, expected win and maximum loss would be doubled.

Also, if the second fails, I'd want it to switch to a third level where the first stake value, expected profit and maximum loss would be tripled

@hotmatrixx
@aaron-binary
@binary-ex-mechina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

**Comment by ZDEGLET** [comment]
сделай расчет рефинансирования в Excel так я думаю будет проще.
я в своей таблице вижу когда и сколько нужно вложить.
![2019-07-08_01-12-28](https://user-images.githubusercontent.com/36106343/60774515-8b9daa00-a11d-11e9-8c2b-5d82ca31bb01.png)

**Comment by binary-ex-machina** [comment]
@eonuoha30 you can your idea of multiple leves, working separately from each other like the image below. If the max losses in row reach the amount pre determined, it will double  the original value, the same with target profit and stop loss, in case they reach the value. They will work independently and will maintain this amount. The max level is a general max updating steps it will take

![image](https://user-images.githubusercontent.com/34610787/60841925-50e15380-a1a9-11e9-9d3f-c6559ce556b0.png)

**Comment by eonuoha30** [comment]
Thanks

I'd try it out
