### ISSUE TITLE
New winning Digit DIFFER STRATEGY

### ISSUE THREAD

**Issue by nobleb2007** [binary-com/binary-bot#1682]
Please, I have been using this simple strategy manually for some days now.

The strategy is as follow
Add the  last digit numbers 5times together and divide by 5.  Pick the result as your next digit differ.

Eg
1st -1341.23  LAST DIGIT is 3
2nd - 1234.34 LAST DIGIT is 4
3rd - 23.09 LAST DIGIT is 9
4th - 234.10  LAST DIGIT is 0
5th - 234.06 LAST DIGIT is 6
Therefore 3+4+9+0+6 = 21/5 = 4.2
Pick digit differ 4.
After winning, it should start Over again

@hotmatrixx
@aaron-binary 
@binary-ex-mechina
@gokula-krishna-dev 
@eshhh
@batekmax
@lasaidhari

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-07-08_002750_bot binary com](https://user-images.githubusercontent.com/42480287/60772660-437b8900-a117-11e9-8f8e-437f7d8a69a0.png)

**Comment by nobleb2007** [comment]
Thanks for your prompt solution. After assembled it according to the pictures. I noticed that is just predict only one digit. 

I want it to predict and reanalysis the number again before make second prediction.

**Comment by binary-ex-machina** [comment]
@nobleb2007 it uses the same digit after losing?

**Comment by nobleb2007** [comment]
Yes, it is picking same digit even after lossing. I want it to calculate
the digit again before picking next trade. So grateful for you prompt
response

**Comment by Herotaiko** [comment]
@nobleb2007  Please request .xml file.

**Comment by nobleb2007** [comment]
[5_5 l.txt](https://github.com/binary-com/binary-bot/files/3369186/5_5.l.txt)

This is the bot. Kindly help out.

**Comment by Herotaiko** [comment]
I have tried to adjust slightly and are testing.
![aaaaaaaaa](https://user-images.githubusercontent.com/51996252/60830802-38d9f600-a1e2-11e9-8ebc-73578f741113.PNG)

**Comment by nobleb2007** [comment]
Thanks, can you send the XML file please

**Comment by nobleb2007** [comment]
With this picture sir, this will only predict digit 0 only.

What I actually want is to analyse 5 digit and divide by 5 and pick the
result as the next digit.

Do it again, and pick the new digit.

I hope you understand it now.
I have the strategy up.
Thanks

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-07-08_233511_user-images githubusercontent com](https://user-images.githubusercontent.com/42480287/60832296-29a27a80-a1d9-11e9-997f-65b7dc5a97a3.png)
check prediction box again

**Comment by nobleb2007** [comment]
This is just predicting 0. 

I don't understand what you meant by that arror

**Comment by nobleb2007** [comment]
This is just predicting 0. 

I don't understand what you meant by that arrow

**Comment by nobleb2007** [comment]
The strategy is as follow
Add the last digit numbers 5times together and divide by 5. Pick the result as your next digit differ.

Eg
1st -1341.23 LAST DIGIT is 3
2nd - 1234.34 LAST DIGIT is 4
3rd - 23.09 LAST DIGIT is 9
4th - 234.10 LAST DIGIT is 0
5th - 234.06 LAST DIGIT is 6
Therefore 3+4+9+0+6 = 21/5 = 4.2
Pick digit differ 4.
After winning, it should analyse the digit and start Over again

**Comment by navneetsinh** [comment]
> This is just predicting 0.
> 
> I don't understand what you meant by that arrow

check my uploaded image of bot and correct your bot,
you are selected 0 for prediction so obviously it should be 0,
input prediction block

**Comment by nobleb2007** [comment]
![Screenshot_20190708-211503](https://user-images.githubusercontent.com/26756670/60840398-52ba0f80-a1c7-11e9-8a5a-4cc2a1a63f2a.png)

This is my own. If I don't put it right you can tell me but it is not still working according to my strategy.
Thanks for your prompt response. I hope you can still help me out.

**Comment by navneetsinh** [comment]
kindly check what I sent and what you set?

**Comment by Herotaiko** [comment]
@navneetsinh @nobleb2007

Bot :https://drive.google.com/file/d/1VrJ9ZHyehLUSUPoDmJ4GRiz7rDVRGrXu/view?usp=sharing

**Comment by nobleb2007** [comment]
Thanks @herotaiko @navneetsinh
I am so grateful but still remain changes of the digit after adding and divide. Am expecting the digit to Change not to CONSTANT.

@hotmatrixx
@aaron-binary
@binary-ex-mechina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

Please kindly help with the final peace.

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-07-09_115209_bot binary com](https://user-images.githubusercontent.com/42480287/60864087-2e4e4980-a240-11e9-9019-ed2b91f9a9d2.png)

**Comment by Eshhh** [comment]
[5_5 edited.zip](https://github.com/binary-com/binary-bot/files/3371778/5_5.edited.zip)
 
here..

**Comment by hotmatrixx** [comment]
That looks messy.
try coding it with a loop?

[5 by 5 for NobleB.zip](https://github.com/binary-com/binary-bot/files/3372383/5.by.5.for.NobleB.zip)


![image](https://user-images.githubusercontent.com/49715381/60878309-98dca500-a293-11e9-908a-70ca37e9ae7d.png)

**Comment by hotmatrixx** [comment]
oh I must ask.
how did you develop this strategy? I've tried running it for a little while Linda seems to be quite successful. It's not something that I would have thought of doing. I'm wondering why you thought of averaging the last digit of the trades?

**Comment by Eshhh** [comment]
![image](https://user-images.githubusercontent.com/33750313/60881100-9e6dc700-a262-11e9-8a0c-838fc7e0fbf1.png)

Still risky..

**Comment by Herotaiko** [comment]
> ![image](https://user-images.githubusercontent.com/33750313/60881100-9e6dc700-a262-11e9-8a0c-838fc7e0fbf1.png)
> 
> Still risky..

Is a problem that I encountered as well.

**Comment by nobleb2007** [comment]
I have been testing on manual for some times now and it is working well on
demo. The problem am having with the bot is that after 1 trade.

The both should wait and RECALCULATE  another average of 5 number before
making the 2nd trade.

Am sure this is the piece missing from the bot.

Can someone implement that please.

**Comment by binary-ex-machina** [comment]
@nobleb2007 the image below shows the same idea already posted here, but without any other filter to calculate the prediction

![image](https://user-images.githubusercontent.com/34610787/60927207-70e34680-a27f-11e9-98c0-5c266d60fc96.png)

**Comment by nobleb2007** [comment]
@herotaiko
@hotmatrixx
@binary-ex-mechina
@Eshhh
@Batekmax
@lasaidhari

Thanks for your effort so far really grateful for your input.

The reason while the bot is lossing 3 in a row is the the strategy has not been fully implemented.

If the bot make the first trade. It should wait and calculate another average of 5 numbers before make the second trade.

If this can be implemented in the bot. Am telling is going to come good.

**Comment by binary-ex-machina** [comment]
@nobleb2007 I have sent how to do it, look at the image on my post above. Your idea will not have any different result then a strategy using digit differ without any analysis. Any number can come next, so you do any analysis and try to improve the win rate or avoid losing streaks will have always 10% chance of fail and 90% of winning.

I let the bot i sent the image running for 3 min, it got 3 losses in row, so it's the same as any other differ bot

**Comment by hotmatrixx** [comment]
I'll be able to do it once I get home Ina couple of hours. Easy money.

**Comment by ceakuk** [comment]
@ nobleb2007 
people would want to believe they can predict random numbers. in that case you would win a nobel price in mathematics. you can only  develope a good money management trategy.
by default you  will win 900 out 1000 trades even if you close your eyes and guess.

if your strategy consistently win 990 out of 1000 then we can say you have succeeded in predicting the random numbers.

winning money with  just 900 wins out of 1000 trades with martingale is pure luck as a result of just the martingale and prediction has no role in your win which is very risky and one of these days it will bite you so painfully

**Comment by ceakuk** [comment]
@Herotaiko 
loosing 228 trades, we expect by guess work you would win 228*9 =2052 trades
but you win only 2030 trades
so the 136.72$ you won is prely out of luck that martingale did not explode but it will happen sooner than later. the strategy added nothing 
![Unbenannt](https://user-images.githubusercontent.com/43122491/60955796-d9730780-a301-11e9-8826-a8fdb3d5dad6.PNG)

**Comment by ceakuk** [comment]
@nobleb2007 
just out of curiosity, you are trading tick and you manage to manually sum up the last 5 ticks, get the average, place a trade before new ticks form. 
for ordinary people, 10 ticks would have passed and if the strategy works on manuall then we should average the last 5 tick but say tick number 15 to number 10 or about there.
i just dont see the logic

**Comment by nobleb2007** [comment]
Maybe from your own view. You maynot understand but I will keep to my strategy. Am sure no signal or strategy is 100%. If you don't have anything to add. Don't discourage other please.

Am grateful for you advice anyway. Thanks to all that has taken time to attempt and give solution. So grateful.

**Comment by ramonrly** [comment]
Just trade again after 12 sec.

**Comment by navneetsinh** [comment]
> Just trade again after 12 sec.

@ramonrly 
![Opera Snapshot_2019-10-31_161217_bot binary com](https://user-images.githubusercontent.com/42480287/67940234-4a179a00-fbf9-11e9-9f7e-261da88c1345.png)

**Comment by jay37-binary** [comment]
Hello,

How can we rectify last digit before purchase 

Please do help.

**Comment by Sonal-sl** [comment]
hello I am from Sri lanka 
Who can tell me how to create 0 loss bot because I saw it Youtube 
please mail my email 
sonalnimsara229@gmail.com

**Comment by binary-ex-machina** [comment]
@Sonal-sl 0 loss videos are just fake, luring people to believe they are possible. When you buy the bot, it loses and breaks your account, then the person that sold the bot to you disappears. You got scammed. Congrats.

Stop believing in perfect bots, they don't exist and will never exist in this universe.

**Comment by Sonal-sl** [comment]
Thank you very much  can you send me a bot minimum loss to  my email  Sent from Mail for Windows 10 From: Binary Ex MachinaSent: Thursday, July 8, 2021 6:04 AMTo: binary-com/binary-botCc: Sonal-sl; MentionSubject: Re: [binary-com/binary-bot] New winning Digit DIFFER STRATEGY (#1682) @Sonal-sl 0 loss videos are just fake, luring people to believe they are possible. When you buy the bot, it loses and breaks your account, then the person that sold the bot to you disappears. You got scammed. Congrats.Stop believing in perfect bots, they don't exist and will never exist in this universe.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by binary-ex-machina** [comment]
@Sonal-sl, there is no bot with a minimum loss. All bots can go to 15-20 losses in a row. So you can use bots with digit differ trade types, which will give you a 10% payout and require big martingale to recover. Any rise fall bot will have a 50% win rate, and they will give 8 losses in a row or more. Have balance to recover that, and you can use any strategy/bot.

**Comment by Sonal-sl** [comment]
Thank you very musch where are you? Sent from Mail for Windows 10 From: Binary Ex MachinaSent: Thursday, July 8, 2021 8:54 AMTo: binary-com/binary-botCc: Sonal-sl; MentionSubject: Re: [binary-com/binary-bot] New winning Digit DIFFER STRATEGY (#1682) @Sonal-sl, there is no bot with a minimum loss. All bots can go to 15-20 losses in a row. So you can use bots with digit differ trade types, which will give you a 10% payout and require big martingale to recover. Any rise fall bot will have a 50% win rate, and they will give 8 losses in a row or more. Have balance to recover that, and you can use any strategy/bot.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bobmeg** [comment]
Hello...i have a digits bot ive been testing for almost a month now...recently its been freezing in the middle of the tests...yet on the bot it still shows that the bot is running..every time it does this i have to stop the bot and press play again..its so frustrating especially when there has been a loss...ive tried to clear my browser history but nothing has changed...can anyone help out here
