### ISSUE TITLE
2 touch barrier

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1683]
how to set 2 touch barrier please help me

like this
+1
-1
strategy is only touch
but different barrier some signal

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/60774924-e0c3c680-a0f1-11e9-8609-7d854877c4f3.png)

**Comment by dushanu** [comment]
thank you very much @binary-ex-machina
