### ISSUE TITLE
@Binário Ex Machina

### ISSUE THREAD

**Issue by kikopqfgdffg** [binary-com/binary-bot#1684]
@Binário Ex Machina

qero fazer um bot scalper 
hig/low 
exemplo ele abrir uma ordem de 1 usd e fechar e quando ele tiver no lucro fechar a ordem tipo entro com 1 usd e fechar a ordem com 0.4 usd

**Comment by binary-ex-machina** [comment]
@kikopqfgdffg você pode fazer como na imagem abaixo

![image](https://user-images.githubusercontent.com/34610787/60819129-6a68a800-a175-11e9-8a53-97acb9e9cbd0.png)

**Comment by kikopqfgdffg** [comment]
obrigado me ajudou bastante

**Comment by bin** [comment]
@kikopqfgdffg Please stop @ mentioning me.  I also don't speak Portuguese.
