### ISSUE TITLE
Need a VPS/VPN for binary bot

### ISSUE THREAD

**Issue by fm3711** [binary-com/binary-bot#1686]
Hello.
I am using my own bot on binary.com
I wanted to ask how can I run it on VPN, because it is difficult to leave a computer open for the day.
Do you have any system for it?
I found a binary VPN on PlayMarket for Android phone, but I dod not understand how to use it. It has only one button to turn it ON or OFF.
If you can help, please describe it details, because I am new to it.

Thank you!

**Comment by binary-ex-machina** [comment]
look for google cloud compute engine, you can run a windows machine in there for free (you receive $300 as bonus and can configure how much processor, ram memory and HD you want). In there you can have the chrome browser running and run as many bots you want without stop.

**Comment by fm3711** [comment]
Thank you so much!

**Comment by binarybotbrazil** [comment]
@binary-ex-machina Is it possible to run a bot in the cloud (in background), through a python, js or PHP script? When I say "in the cloud" I mean to run on the server side, instead of the user having to have a graphical interface active at the time of execution.

Thanks!

**Comment by binary-ex-machina** [comment]
@binarybotbrazil  yes, you can rent a VPS and run on the cloud in any language. Using bot on the cloud will require that you use their API to build everything to trade using your Deriv account
