### ISSUE TITLE
Great Martingale Bot

### ISSUE THREAD

**Issue by interpan** [binary-com/binary-bot#169]
Good day,

I would like to see the great martingale version of the martingale bot. I thought I could just make some adjustments to the martingale bot, but I was not able to do so.

In the great martingale strategy, the sequence after each loss is 1, 3, 7, 15, 31, 63 and so on (double previous bet plus one basic bet) rather than the martingale sequence of 1, 2, 4, 8, 16, 32, 64 (double previous bet).

**Comment by aminmarashi** [comment]
You can download the [original martingale implementation](https://gist.githubusercontent.com/aminmarashi/0feb52b5802519cd4157b612d9bd3471/raw/martingale.xml) and then expand the core function:
<img width="384" alt="screen shot 2017-03-08 at 1 38 30 pm" src="https://cloud.githubusercontent.com/assets/6560964/23691633/a4369c4c-0404-11e7-927a-d9f57e9cdfb4.png">
and then modify it
<img width="511" alt="screen shot 2017-03-08 at 1 38 57 pm" src="https://cloud.githubusercontent.com/assets/6560964/23691640/b30b91aa-0404-11e7-9542-8e67be690c3b.png">
Collapse it again
<img width="553" alt="screen shot 2017-03-08 at 1 40 23 pm" src="https://cloud.githubusercontent.com/assets/6560964/23691666/dee7dcde-0404-11e7-9478-644aea8ba50e.png">
And save it as a collection for future use.
<img width="314" alt="screen shot 2017-03-08 at 1 40 40 pm" src="https://cloud.githubusercontent.com/assets/6560964/23691678/f5012a70-0404-11e7-997a-6b8e5927105e.png">
You can find the result in [here](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/Greate%2520Martingale.xml)

**Comment by interpan** [comment]
Thank you aminmarashi. It would be nice if you could tell us how to merge the saved "Great Martingale" block with the martingale binary bot, or better still create the "Great Martingale" binary bot.

**Comment by aminmarashi** [comment]
Our final `martingale` strategy is nothing but some file like the above uploaded somewhere and then loaded using its address to save some space.
You can build your own version of martingale without uploading the blocks like this:
1. Start with the default blocks (save your changes beforehand)
2. Load the great martingale file
3. Replace the default amount with Martingale Trade Amount
<img width="627" alt="screen shot 2017-03-09 at 9 44 54 am" src="https://cloud.githubusercontent.com/assets/6560964/23732305/4d528c66-04ad-11e7-890f-89fabe5750a2.png">
4. Replace the `Trade Again` block with Martingale Trade Again... 
<img width="492" alt="screen shot 2017-03-09 at 9 45 57 am" src="https://cloud.githubusercontent.com/assets/6560964/23732308/5121e292-04ad-11e7-8136-3493006af823.png">
And that's it, you have your own version of martingale.
You can find the end result [here](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/Great%2520Martingale.xml)

**Comment by interpan** [comment]
Thank you very much aminmarashi. Previously, I didn't start with the default blocks. Now, I have adhered to your advice, and it worked perfectly.
