### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1691]
I have a bot that works well.

The maximum loss limit, maximum loss streak and expected win are also working well.

But what I need help on is this....

If the trade reaches a 'Maximum loss streak of 5' or  maximum loss amount of 100$ , I want the trade to switch over to a second level where the new 'expected win amount , first stake and maximum loss amount' will be changed to double of its initial value.

Also, if its reached, I want it to automatically enter a third level where the mentioned values will be triple its starting value.

For instance, 

if  First stake is 1$,
Expected win is 100$
Maximum loss is 200$
Maximum loss streak is 5

If the maximum loss streak or maximum loss amount is reached, I'd want it to automatically switch to a second level where the listed first stake, expected win and maximum loss would be doubled.

Also, if the second fails, I'd want it to switch to a third level where the first stake value, expected profit and maximum loss would be tripled

@hotmatrixx
@aaron-binary
@binary-ex-mechina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

**Comment by ZDEGLET** [comment]
пришли робота zdeglet@gmail.com
