### ISSUE TITLE
[bug?]  Activity Log doesn't reset

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1696]
not sure whether this is intended behaviour,but when you reset the summary, the activity log remains.

Although I admit it can be handy to go back through all of the logs historically, I've found that it can fill up with thousands of log entries in trying to navigate in a log with for example 10,000 entries (when I've actually only run one bot 1000 times with 10 runs) the log will lock up my entire browser for quite a few seconds.

I'm wondering if the log should be reset when the bot is reset using the "rubbish bin" icon in the summary.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

The rubbish bin does not reset the log, but we may add a similar feature to the log in the future.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
Working As intended?
ok, no worries. Thanks for letting me know. Feel free to close this thread.
