### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1697]
@hotmatrixx
@aaron-binary
@binary-ex-mechina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

First, I'd say thanks to @binary ex machina and others for the last support they rendered.

But I still need a little more help on a bot.

Its on overs/unders. 

I want the first predict to be on Over5 and the first stake = first stake ( 1$ ).

If it loses, second Predict will be Under8 and second stake= first stake * 5.35

If it loses, third Predict will be Over1 and third stake= first stake * 28.57

If it loses, fourth Predict will be Under9 and fourth stake= first stake * 422.86

If any trade WINS, the cycle should automatically go back to the first predict/stake.
If it loses, it goes to the next stake.
But if all the four loses, the trade should automatically stop.

For instance, if trade 1 wins, it will trade again. But if it loses, it goes to trade 2.

If trade 2 loses, it goes to trade 3 then finally , trade 4.
But if it wins, it starts all over from trade 1

Thanks

**Comment by lasaidhari** [comment]
[eonuoha30 overunder 5819.zip](https://github.com/binary-com/binary-bot/files/3376493/eonuoha30.overunder.5819.zip)

Please try

**Comment by ceakuk** [comment]
@eonuoha30 
under9 does not exist. its under8
which is same as over1
which is the same as your 3rd prediction but larger amount.
im certain it won't work bairing in mind you are betting  stake= first stake * 422.86
of course it has a high probability of working in short term since you are taking smaller profit but in the long run, your acount will be wiped clean

**Comment by hotmatrixx** [comment]
> 
> 
> @eonuoha30
> under9 does not exist. its under8
> which is same as over1
> which is the same as your 3rd prediction but larger amount.
> im certain it won't work bairing in mind you are betting stake= first stake * 422.86
> of course it has a high probability of working in short term since you are taking smaller profit but in the long run, your acount will be wiped clean

Under 9 does exsist. its' any digit except 9.

**Comment by lasaidhari** [comment]
I tried to make the bot and the result was digit under 9 won with the last digit 8. this is an experimental image. column marked red
![under9](https://user-images.githubusercontent.com/34808023/60960272-a29cf180-a301-11e9-8766-21920ecc5cf9.jpg)

**Comment by ceakuk** [comment]
@eonuoha30 
you are right. however i dont think that's what he is looking for. remember he increased stake from 42$ to over 422$ for the sake of such a large variation. remember  he only has 1/10 chance to win if his under9  picks 1. here is a table i compiled
he wont risk all that amount for  a random guess between 1  and 8.

under1/ over8  has 1/10=10% win rate    ;  risk 1$ to make 0.89     (8.09*1/9 =0.89)
under2/over7 has 2/10=20% win rate    ;  risk 1$ to make 0.92      (3.7*2/8 =0.92)
under3/over6  has 3/10=30% win rate    ;  risk 1$ to make 0.95      (2.22*3/7 =0.95)
under4/over5  has 4/10=40% win rate    ;  risk 1$ to make 0.96      (1.44*4/6 =0.96)
under5/over4  has 5/10=50% win rate    ;  risk 1$ to make0.94      (0.94*5/5 =0.94)
under6/over3  has 6/10=60% win rate    ;  risk 1$ to make 0.9       (0.6*6/4 =0.9)
under7/over2  has 7/10=70% win rate    ;  risk 1$ to make 0.93     (0.4*7/3 =0.93)
under8/over1  has 8/10=80% win rate    ;  risk 1$ to make 0.88     (0.22*8/2 =0.88)
under9/over0  has 9/10=90% win rate    ;  risk 1$ to make 0.81     (0.09*9/1 =0.81)

![Unbenannt](https://user-images.githubusercontent.com/43122491/60960414-3d013300-a30a-11e9-9f33-0b07f27df3b1.PNG)

**Comment by ceakuk** [comment]
@lasaidhari 
its not winning which will keep you in the game longer but the risk management.
risking 422$ to make 42$, of course you are most likely to win.
that might even happen 5 consecutive times to make you 42*5 = 210$ but when you loose just once all the 422$ will be gone.

binary.com is a big company. of course they hire mathematics professors  to work out the math and the idea that if you loose 4 times, you are more likely to win the 5th is  so untrue. theoretically you can even loose consecutively 100 times using even over0 which should be winning 90% of trades
its just not common but its possible and befor you know it, you will be wipped out.

in mathematics we say random numbers only converge to the expected probabilities  with highest surerity after very many numbers say 10,000 times or even more.  sometimes after few but with no guarantee

**Comment by eonuoha30** [comment]
PLEASE, I've NOT GOTTEN ANY WORKING REPLY ON THIS.

my request is simple.

I need a bot that runs on 4 trades.

First trade is over5
Second is under8
Third is over1
Fourth is under9

If the first wins, it continues. But if it fails, it goes to the second trade, third trade or fourth until a win is secured.

Once a win is secured, it automatically returns back to the first trade and stake. Then restarts the cycle again.

Also, assuming I decide to use 1$ as stake,

 the first STAKE on Over5 will be = 1unit * 1$  
The second STAKE on Under8 will be = 5.35unit * 1$ 
 the third STAKE on Over1 will be = 28.57unit * 1$
 the fouth STAKE on Over9 will be = 422.86unit * 1$
