### ISSUE TITLE
how set the martingale level and martingale start after ?

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1698]
Like this, Please show me blogs.

![ssssss](https://user-images.githubusercontent.com/51996252/60907476-dd703c80-a2a3-11e9-9751-7db76484ffc8.PNG)

**Comment by ghienhoi** [comment]
Hi !
Please try this
![1](https://user-images.githubusercontent.com/52727412/60937122-89904280-a2f9-11e9-9d99-c6f0c3ab0cad.jpg)

**Comment by ghienhoi** [comment]
Please try !
You can delete 1 row: "set Begin to 0.35" because i  forgot delete it
![1](https://user-images.githubusercontent.com/52727412/60937271-fa375f00-a2f9-11e9-881c-31f1ed912895.jpg)

**Comment by Herotaiko** [comment]
I'm not sure if it's set correctly.

![123](https://user-images.githubusercontent.com/51996252/60970913-2a5c1d80-a34d-11e9-9ef8-af4f10ffe505.PNG)

**Comment by binary-ex-machina** [comment]
@Herotaiko try like this
![image](https://user-images.githubusercontent.com/34610787/61010487-d2bdb200-a34c-11e9-9ad1-b3f96ee10d7c.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina @ghienhoi 
I will try to create it. If I can't do it, I'm bothering again. For settings

**Comment by ghienhoi** [comment]
MISTAKE ! I fixed it.
Please try again .
![3](https://user-images.githubusercontent.com/52727412/61261015-8d650e80-a7aa-11e9-9361-3e6a7e076915.jpg)

**Comment by Herotaiko** [comment]
@ghienhoi @binary-ex-machina 
I want to reach them max martingale and start back as the first stake price.

**Comment by ghienhoi** [comment]
@Herotaiko .
Is this like this ?
![2](https://user-images.githubusercontent.com/52727412/62260304-b5f03800-b43b-11e9-8edc-79c38d27cc09.jpg)

**Comment by Herotaiko** [comment]
@ghienhoi  try like this .
![sssss](https://user-images.githubusercontent.com/51996252/62415877-36d94a80-b65b-11e9-8d17-266cd6a5d15b.PNG)
