### ISSUE TITLE
Martingale Only After 2 or 3 times loss

### ISSUE THREAD

**Issue by dadankm4** [binary-com/binary-bot#170]
Hi Amin,
Can you help me make a code, begin martingale only start after 2 or 3 times loss. Because in the worst trade, win make after step 9 or 10 and maybe 11 or 12 step. if we run robot for 24 h. 
Thank you for your kind

**Comment by aminmarashi** [comment]
Please check [this file](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/start%2520martingale%2520after%25202%2520loss.xml) to see if it serves your purpose.
