### ISSUE TITLE
How to track percentage of win/loss

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1700]
Good morning,
I'm trying to setup an script to open four(4) different operations when they become available:
1) If a sequence of two(2) candles of the same color is formed, open an operation on the third candle on the same direction as the two candles (If two candles Green, open a Call on the third one, and vise versa if the candle is Red)

2) If a sequence of three(3) candles of the same color is formed, open an operation reversing the pattern on the fourth candle. (If a sequence of three(3) green candles, open a Put on the fourth candle, and vise versa if it is a sequence of red candles)

3) If a sequence of three(4) candles of the same color is formed, open an operation reversing the pattern on the fourth candle. (If a sequence of three(4) green candles, open a Put on the fourth candle, and vise versa if it is a sequence of red candles)

4) If a sequence of three(7) candles of the same color is formed, open an operation reversing the pattern on the fourth candle. (If a sequence of three(7) green candles, open a Put on the fourth candle, and vise versa if it is a sequence of red candles)

However I'd like to open the operations only if a preset percentage of wins is confirmed for each possibility.

How can I determine and catalog when a win or a loss came from which one of the above patterns?
I have the variables set as:
**Total 2 x 1, Total 3 x 1, Total 4 x 1, Total 7 x 1** = the amount of opportunities each of this patterns presented themselves.

And:
**% 2 x 1, % 3 x 1, % 4 x 1, % 7 x 1** = As the win percentage for each case.

I'm having trouble identifying when a win/loss came from each pattern.

Thank you.

**Comment by binary-ex-machina** [comment]
A better approach would be divide the script in four and open 4 windows, using each script and tracking each one. Check the blocks below.


This one will be common on each script (you can add martingale, stop loss, target profit and so on)
![image](https://user-images.githubusercontent.com/34610787/60980379-bf89f280-a30a-11e9-9e42-750cdaa106f3.png)

Pattern 1:
![image](https://user-images.githubusercontent.com/34610787/60980453-e0524800-a30a-11e9-98cd-77f60fabe186.png)

Pattern 2: 
![image](https://user-images.githubusercontent.com/34610787/60980501-f7913580-a30a-11e9-8273-4ae36f205828.png)

Pattern 3:
![image](https://user-images.githubusercontent.com/34610787/60980548-0ed02300-a30b-11e9-9d7a-5c9f693180bb.png)

Pattern 4:
![image](https://user-images.githubusercontent.com/34610787/60980600-27403d80-a30b-11e9-93d0-846878416fbc.png)
