### ISSUE TITLE
Worm Tick

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1702]
How to get 
after 20 second condition check
if worm head blue = confirmation true
than worm head green 2 time 
trade for put

vise versa for call

ex:
after 20 sec  blue green green - put
after 20 sec  red green green - call

**Comment by binary-ex-machina** [comment]
after 20 seconds starting from what? 20 seconds of a 1min candle?

**Comment by navneetsinh** [comment]
@binary-ex-machina 
Yes, here 1 minute candle,
First 20 second not ready for any confirmation,
 20 to 35 second is for confirmation period,
And after 35 second again wait for next 1 minute candle 20 second to 35 second for confirmation
Any trade start in 1 minute candle between 20 to 35 second

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/61139950-de21f200-a4a0-11e9-970e-fd25f78a5a5d.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina
@navneetsinh

I have tried this strategy and it works well. Thank you.

If the candle is 5 minutes, how should it be set?

**Comment by binary-ex-machina** [comment]
@Herotaiko change the numbers 60 for 300

**Comment by Herotaiko** [comment]
@binary-ex-machina 
20 and 36 do not need to change?

**Comment by navneetsinh** [comment]
> you can do like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/61139950-de21f200-a4a0-11e9-970e-fd25f78a5a5d.png)

thanks @binary-ex-machina for support, most I tried for these seconds blocks but didn't succeed, but not  it's good, thanks again

**Comment by buckman1974** [comment]
> @binary-ex-machina
> @navneetsinh
> 
> I have tried this strategy and it works well. Thank you.

@Herotaiko do you have an XML bot of this strategy at all?

**Comment by Herotaiko** [comment]
@navneetsinh @binary-ex-machina
Please allow both of them too

@buckman1974
I have tried and tested it. If you take it further, it will be very good.
BOT: https://drive.google.com/file/d/1ampUtCCGXeOMOTNbtvP6t7niYHaaFKzd/view?usp=sharing

**Comment by buckman1974** [comment]
Thanks @Herotaiko so this now takes a trade in opposite direction once it hits the top (blue) and bottom (red)?
