### ISSUE TITLE
Doji

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1703]
How to make for doji candle blocks:
Doji
Dragonfly Doji
Gravestone Doji

**Comment by binary-ex-machina** [comment]
here is how to detect these 3 patterns

![image](https://user-images.githubusercontent.com/34610787/61074601-73b07980-a3ee-11e9-9c64-fa5ddae5d950.png)

**Comment by navneetsinh** [comment]
@binary-ex-machina thank you very much,
One another thing,
How can get last doji/dragonfly/gravestone.

**Comment by binary-ex-machina** [comment]
@navneetsinh what i have sent is to get the most recent formation (it will use the actual candle

**Comment by navneetsinh** [comment]
@binary-ex-machina ok done, thanking you

**Comment by kikopqfgdffg** [comment]
quando ele encontrar os padrões como colocar rise e call nessa estratégia de doji

**Comment by dulajkulathunga** [comment]
> here is how to detect these 3 patterns
> 
> ![image](https://user-images.githubusercontent.com/34610787/61074601-73b07980-a3ee-11e9-9c64-fa5ddae5d950.png)

Hi Dear 

Can you please send me this three pattern block   dulajfree@gmail.com

**Comment by dulajkulathunga** [comment]
> here is how to detect these 3 patterns
> 
> ![image](https://user-images.githubusercontent.com/34610787/61074601-73b07980-a3ee-11e9-9c64-fa5ddae5d950.png)

 Dear  @binary-ex-machina 

Can you please send me this three pattern block dulajfree@gmail.com
