### ISSUE TITLE
bot differ

### ISSUE THREAD

**Issue by luckman1988** [binary-com/binary-bot#1704]
![Capture](https://user-images.githubusercontent.com/34752686/61101954-34287280-a46c-11e9-80ab-26fc87b069b0.PNG)

hie help to creat a reduce martingale on bot differ like if my martingale is 5 ie from 0.35 to 2.1
l want my mart run 3 times at the vale of 2.1 nad it goes back to 0.35

**Comment by ZDEGLET** [comment]
ПРИМЕРНО ТАК?
![2019-07-12_14-55-45](https://user-images.githubusercontent.com/36106343/61126479-3662ef00-a4b5-11e9-8ca0-18ab65c99d4b.png)

**Comment by luckman1988** [comment]
yes can u help with the snap short of the set up of thatv martingale l dont know how to creat it

**Comment by ZDEGLET** [comment]
ОТСЫЛАЙ РОБОТА НА ПОЧТУ zdeglet@gmail.com я привяжу к нему
