### ISSUE TITLE
@binary exmachina 

### ISSUE THREAD

**Issue by kikopqfgdffg** [binary-com/binary-bot#1707]
![20190712_111037](https://user-images.githubusercontent.com/33980574/61134344-d14bd100-a495-11e9-946e-82deabca7e65.jpg)
 tem como fazer essa estratégia se os dois últimos foram verde ele entra com call se ele der loss ele dar só 1 martingale com call de novo a mesma serve pra put

**Comment by binary-ex-machina** [comment]
você pode fazer desta forma

![image](https://user-images.githubusercontent.com/34610787/61141220-75884480-a4a3-11e9-8fc0-063ba9e005b2.png)

**Comment by kikopqfgdffg** [comment]
@binary ex machine ele não tá dando call

**Comment by binary-ex-machina** [comment]
@kikopqfgdffg se você seguiu corretamente a imagem, ele vai usar call e put. Manda uma imagem dos blocos que você colocou

**Comment by kikopqfgdffg** [comment]
já arrumei obrigado
