### ISSUE TITLE
IF/AND Command

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1709]
Good morning
I'm trying to setup two indicators to monitor the candle's movements 
For example: If the candle crosses the bottom line on the Bollinger Band, and if at the same time the it also crosses the lower setting on the RSI, open a Call operation.
Where can I find the "IF-AND" command?
Thank you

**Comment by AFPEMI** [comment]
![image](https://user-images.githubusercontent.com/52548202/61174355-46da9e80-a575-11e9-834d-28fbd6b71411.png)

**Comment by anton-binary** [comment]
Hi @AFPEMI,
The 'IF' and the 'AND' are two different blocks. Both can be found under logic section.
You need to add both blocks to the canvas and then to connect them.
![image](https://user-images.githubusercontent.com/43776314/61191509-06e2fb00-a6de-11e9-8953-ea37adc600c4.png)

Like so..
![image](https://user-images.githubusercontent.com/43776314/61191522-40b40180-a6de-11e9-8b51-18e7e387c1c3.png)

Additionally you can change the way the 'AND' block looks. By selecting "External inputs' from the context menu.
![image](https://user-images.githubusercontent.com/43776314/61191548-807ae900-a6de-11e9-8bbc-8ceafa7bdad7.png)

So finally you will have the following.
![image](https://user-images.githubusercontent.com/43776314/61191558-98526d00-a6de-11e9-8a1e-d5b4cded33a6.png)

**Comment by AFPEMI** [comment]
Thank you!
