### ISSUE TITLE
tick up down

### ISSUE THREAD

**Issue by mare69** [binary-com/binary-bot#1710]
hey, 
how can i make bot wich purche trade if was tick down or up
exsample: tick down, tick up, tick down, tick up,   - purche trade up

it will be nice to see notefy when is tick up or down?

**Comment by binary-ex-machina** [comment]
you can do like this below to follow the pattern you sent

![image](https://user-images.githubusercontent.com/34610787/61231369-63f0a800-a702-11e9-8e04-26886981f2f5.png)
