### ISSUE TITLE
how to buy or sell specific time

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1712]
like i want start buy or sell and martingale
12.00pm
12.01pm
12.02pm
12.03pm'
thanks

**Comment by binary-ex-machina** [comment]
You can do like this image below. You need to adjust the UTC from your country

![image](https://user-images.githubusercontent.com/34610787/61231193-fe042080-a701-11e9-98d5-47749c51e900.png)

**Comment by dushanu** [comment]
thank you very much @binary-ex-machina
