### ISSUE TITLE
donchian channel help

### ISSUE THREAD

**Issue by mare69** [binary-com/binary-bot#1716]
Hey, help please
i work on https://github.com/binary-com/binary-bot/issues/631
how to set to trade only when tick tuch DonchianChannel Lower = LL (n)
trade fall?

idea?
![61186099-8bdbff00-a661-11e9-80ef-7f8bc86053d1](https://user-images.githubusercontent.com/52427410/61225994-f5bbdd80-a721-11e9-9b80-bfe7a38d969f.jpg)

pls, help

**Comment by binary-ex-machina** [comment]
@mare69 follow the first image you post, it will do what it's showing. Donchain Channels will produce a lot of false signals, since it can break the band multiple times and don't stop trending.

**Comment by mare69** [comment]
I won't use this width bb and sma 
Bb break up and go down...
Sma 20 crose 10 sma (10sma is under 20)
DonchianChannel touch Lower = LL (n)
And then I trade 5 tick down

How to make this?

**Comment by mare69** [comment]
And I look bb on 1min chart

**Comment by binary-ex-machina** [comment]
@mare69 here is an example. You didn't specified the donchian period, so I put with 5

![image](https://user-images.githubusercontent.com/34610787/61240735-47f80100-a718-11e9-8236-56ed579bec65.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina 
I'm not sure what went wrong or right?

![z](https://user-images.githubusercontent.com/51996252/61308287-21ba8a00-a81a-11e9-94f7-4bbb55d7a91c.PNG)

**Comment by binary-ex-machina** [comment]
try this

![image](https://user-images.githubusercontent.com/34610787/61308912-a16b3900-a7c7-11e9-862c-2d273884e3e4.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina 
I tried to follow you But still found the same problem
![Capturess](https://user-images.githubusercontent.com/51996252/61310011-97742500-a81d-11e9-9267-2ca4c96928a7.PNG)

**Comment by binary-ex-machina** [comment]
@Herotaiko you copied wrong. Bollinger Bands indicator uses array

**Comment by Herotaiko** [comment]
@binary-ex-machina 
I can make it work by using ฺฺBB and SMA an array, Looks like it will take quite a long time to trade. If you get results, I will update it again.
