### ISSUE TITLE
Help with bot

### ISSUE THREAD

**Issue by laxracorp** [binary-com/binary-bot#1718]
is it possible to build this type of bot?
@1.  close is above upper bb
@2. close is greater than close in point 1 but close is less  than upper bb
i have thought of every possible way i can think of but nothing.
![1](https://user-images.githubusercontent.com/36192147/61258056-9da9c900-a76b-11e9-9494-77fed1fdc514.PNG)

**Comment by laxracorp** [comment]
is it possible to make a bot for the m-top in the circle?

**Comment by ZDEGLET** [comment]
если очень постараться то думаю можно. какие значения ВВ
