### ISSUE TITLE
Binary bot martingale

### ISSUE THREAD

**Issue by izy123** [binary-com/binary-bot#172]
Hello admin please i seriously need help. I downloaded some xml and ran it . It actually did well, but I encountered significant amount of loss in the long run especially if there is a change in trend. I'd like you to help me write a script if there's three consecutive loss it should stop and wait for 3 minute before it can continue by that time the trend has change.

**Comment by okovalov** [comment]
@izy123 here is an example of "Pause trade before starting again" https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/pause%252010s%2520after%25203%2520runs.xml
