### ISSUE TITLE
How to make a Stop Loss based in cumulative losses

### ISSUE THREAD

**Issue by Diegogc11** [binary-com/binary-bot#1722]
Hello! I'd like to test a stop loss not based in total profit but in cumulative loss balance, so when the cumulative loss is reached the bot will stop even if the balance is positive. Please help me do it =)

**Comment by binary-ex-machina** [comment]
this is an example on how to count all profits when a loss occur. The value will be negative, so you can compare with the stop loss

![image](https://user-images.githubusercontent.com/34610787/61309400-8816bc80-a7c8-11e9-882d-7ea8d54688cb.png)

**Comment by Diegogc11** [comment]
Thank's a lot!!
