### ISSUE TITLE
every win change strategy? 

### ISSUE THREAD

**Issue by dushn** [binary-com/binary-bot#1724]
hello
i wannt to know this
every win change strategy automatically
like this
1 run oscar after win 1 usd
change like anotyher after 2 run new strategy 
like this
1st strategy
1 lost
2 lost
4 win 
cnahge strategy
1 lost
2 win
change strategy 3
1 lost
2 lost
4 lost
8 lost
16 win
change strategy 1st

with martingale

**Comment by dushanu** [comment]
??????????????

**Comment by dushanu** [comment]
Please help me... I want run two boys.. every win after change another bot. Please help me ... I want script or somtingg .. thanks

**Comment by dushanu** [comment]
need answer

**Comment by navneetsinh** [comment]
@dushanu Check this one.
![Opera Snapshot_2019-07-22_193059_bot binary com](https://user-images.githubusercontent.com/42480287/61638609-654c4280-acb7-11e9-9051-0b68da524ebb.png)
