### ISSUE TITLE
nao consigo colocar bloco com martingale

### ISSUE THREAD

**Issue by rgsk8** [binary-com/binary-bot#1725]
tenho este bot porem quero bloco com martingale alguém pode me ajudar

<xml xmlns="http://www.w3.org/1999/xhtml" collection="false">
  <variables>
    <variable type="" id="n]qs~bBJST_*f$/_Minz">Prediction</variable>
    <variable type="" id="#A2-5aYp^edd~V/77@FS">Buymode</variable>
    <variable type="" id="+9PWYTI)36/H^baq7(xl">PreviousLastDigit</variable>
  </variables>
  <block type="trade" id="xgH69|xFn9=70w.*3Vo@" x="0" y="0">
    <field name="MARKET_LIST">volidx</field>
    <field name="SUBMARKET_LIST">random_daily</field>
    <field name="SYMBOL_LIST">RDBEAR</field>
    <field name="TRADETYPECAT_LIST">digits</field>
    <field name="TRADETYPE_LIST">matchesdiffers</field>
    <field name="TYPE_LIST">both</field>
    <field name="CANDLEINTERVAL_LIST">60</field>
    <field name="TIME_MACHINE_ENABLED">FALSE</field>
    <field name="RESTARTONERROR">TRUE</field>
    <statement name="INITIALIZATION">
      <block type="variables_set" id="iYciGANj1+39+rfw$nRg">
        <field name="VAR" id="n]qs~bBJST_*f$/_Minz" variabletype="">Prediction</field>
        <value name="VALUE">
          <block type="math_random_int" id="%DI=Ci#L@D[)uM+Ey]qN">
            <value name="FROM">
              <shadow type="math_number" id="#v_d~cQ9!@#zvT|tCjQn">
                <field name="NUM">0</field>
              </shadow>
            </value>
            <value name="TO">
              <shadow type="math_number" id="GOnD.Z_,N0XPj`^*5nt/">
                <field name="NUM">9</field>
              </shadow>
            </value>
          </block>
        </value>
        <next>
          <block type="variables_set" id="k2/B5*N[@HRCDoZ5vpW,">
            <field name="VAR" id="+9PWYTI)36/H^baq7(xl" variabletype="">PreviousLastDigit</field>
            <value name="VALUE">
              <block type="math_random_int" id=".@6.dyX|MQAJng_aMwkV">
                <value name="FROM">
                  <shadow type="math_number" id="5@S:$C1]h:`.G1~U+zRX">
                    <field name="NUM">0</field>
                  </shadow>
                </value>
                <value name="TO">
                  <shadow type="math_number" id="LuobVUhBu`vlMu2Tc!fS">
                    <field name="NUM">9</field>
                  </shadow>
                </value>
              </block>
            </value>
            <next>
              <block type="variables_set" id="eG8ri9QZaWNA!Uu_FL36">
                <field name="VAR" id="#A2-5aYp^edd~V/77@FS" variabletype="">Buymode</field>
                <value name="VALUE">
                  <block type="logic_boolean" id="=@tL.%Cc3psE0,d^n-Rx">
                    <field name="BOOL">FALSE</field>
                  </block>
                </value>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
    <statement name="SUBMARKET">
      <block type="tradeOptions" id="x=V33~4Lb|(sLv`J[:Eb">
        <field name="DURATIONTYPE_LIST">t</field>
        <field name="CURRENCY_LIST">USD</field>
        <field name="BARRIEROFFSETTYPE_LIST">+</field>
        <field name="SECONDBARRIEROFFSETTYPE_LIST">-</field>
        <value name="DURATION">
          <shadow type="math_number" id="UR1:j-^zs-8LnfrJ0nQ]">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="AMOUNT">
          <shadow type="math_number" id="ml)25~7^q}3I9}vjf:%K">
            <field name="NUM">0.35</field>
          </shadow>
        </value>
        <value name="PREDICTION">
          <shadow type="math_number" id=",^:o@5TaGV[v%_SWNf+3">
            <field name="NUM">2</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>
  <block type="tick_analysis" id="u?e[_DRz+8CjO5B^}0O2" x="680" y="6">
    <statement name="TICKANALYSIS_STACK">
      <block type="notify" id="XY-}gjM937;W=c28Yo21">
        <field name="NOTIFICATION_TYPE">success</field>
        <field name="NOTIFICATION_SOUND">silent</field>
        <value name="MESSAGE">
          <shadow type="text" id="lO9xC+l+9wS#b!p6H{Aw">
            <field name="TEXT">abc</field>
          </shadow>
          <block type="text_join" id="1y8bYIzk/Bo,C^1Z8Psm">
            <mutation items="5"></mutation>
            <value name="ADD0">
              <block type="text" id="f86%GrYI:(j+X=1^djjN">
                <field name="TEXT">Prev:</field>
              </block>
            </value>
            <value name="ADD1">
              <block type="variables_get" id="AO)[~%L@rOG::BhOP=R^">
                <field name="VAR" id="+9PWYTI)36/H^baq7(xl" variabletype="">PreviousLastDigit</field>
              </block>
            </value>
            <value name="ADD2">
              <block type="text" id="]bYb(MrYaG6Ue)j1}c~5">
                <field name="TEXT"> | </field>
              </block>
            </value>
            <value name="ADD3">
              <block type="text" id=")el^;[V=|Hos*xCA5u(U">
                <field name="TEXT">Last:</field>
              </block>
            </value>
            <value name="ADD4">
              <block type="last_digit" id="AWYpJ$USXj%``xcwHH3*"></block>
            </value>
          </block>
        </value>
        <next>
          <block type="controls_if" id="|=6*A0:DeVi;1eo?m{`~">
            <value name="IF0">
              <block type="logic_compare" id="$:3)TM)6h`::i$Q_.)Iw">
                <field name="OP">EQ</field>
                <value name="A">
                  <block type="variables_get" id="XI=~:yO!Vx+O#OB9S3^R">
                    <field name="VAR" id="+9PWYTI)36/H^baq7(xl" variabletype="">PreviousLastDigit</field>
                  </block>
                </value>
                <value name="B">
                  <block type="last_digit" id="UrkM[`?g#OM{zdlQ,Bn1"></block>
                </value>
              </block>
            </value>
            <statement name="DO0">
              <block type="variables_set" id="{-*$b50}r9{$Oa]2)TKK">
                <field name="VAR" id="n]qs~bBJST_*f$/_Minz" variabletype="">Prediction</field>
                <value name="VALUE">
                  <block type="variables_get" id="dPCI%!-s-.$-.Fq$J#cp">
                    <field name="VAR" id="+9PWYTI)36/H^baq7(xl" variabletype="">PreviousLastDigit</field>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="~SGJ%:D^6.qITv4M{QL#">
                    <field name="VAR" id="#A2-5aYp^edd~V/77@FS" variabletype="">Buymode</field>
                    <value name="VALUE">
                      <block type="logic_boolean" id="kcF_2C`BKvmqsHctc%!.">
                        <field name="BOOL">TRUE</field>
                      </block>
                    </value>
                  </block>
                </next>
              </block>
            </statement>
            <next>
              <block type="variables_set" id="HsxOGdB6eM`?L3wF;:6,">
                <field name="VAR" id="+9PWYTI)36/H^baq7(xl" variabletype="">PreviousLastDigit</field>
                <value name="VALUE">
                  <block type="last_digit" id="c/|NI8K-xV}{PO3)4J[I"></block>
                </value>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="before_purchase" id="i-CIx.(Onm4?ihxzA}Y]" x="3" y="572">
    <statement name="BEFOREPURCHASE_STACK">
      <block type="controls_if" id=")yHy}%-aVRimq~~k:G{E">
        <value name="IF0">
          <block type="variables_get" id="]RVz*rO?^xI.06//yClt">
            <field name="VAR" id="#A2-5aYp^edd~V/77@FS" variabletype="">Buymode</field>
          </block>
        </value>
        <statement name="DO0">
          <block type="purchase" id="W6q#Z-I3q3d[d3-`S[dS">
            <field name="PURCHASE_LIST">DIGITMATCH</field>
          </block>
        </statement>
      </block>
    </statement>
  </block>
  <block type="after_purchase" id="D^Jz1^n=2vtZku1vBN@;" x="401" y="586">
    <statement name="AFTERPURCHASE_STACK">
      <block type="variables_set" id="g!=E#T-1NlK/TTA4*c#e">
        <field name="VAR" id="#A2-5aYp^edd~V/77@FS" variabletype="">Buymode</field>
        <value name="VALUE">
          <block type="logic_boolean" id="|oBEP:bDLmVy!%(cf/5G">
            <field name="BOOL">FALSE</field>
          </block>
        </value>
        <next>
          <block type="trade_again" id="c)S|KjoQdXc8l#J@5z3P"></block>
        </next>
      </block>
    </statement>
  </block>
</xml>

**Comment by binary-ex-machina** [comment]
você pode colocar martingale deste jeito
![image](https://user-images.githubusercontent.com/34610787/61487953-76c2e100-a97d-11e9-8161-3cfbf06a4fd6.png)

**Comment by rgsk8** [comment]
boa tarde muito obrigado por me ajudar porem não deu certo

![image](https://user-images.githubusercontent.com/52988962/61494390-6d8d4080-a98c-11e9-97d5-1fb22e644afd.png)

**Comment by rgsk8** [comment]
Boa tarde, muito obrigado por me ajudar ...
porem não deu certo a solução que sugeriu 

![martingale please](https://user-images.githubusercontent.com/52988962/61494627-0d4ace80-a98d-11e9-8f7f-f60ff3b3d702.jpg)

**Comment by rgsk8** [comment]
se possível poderia me mandar o xml
