### ISSUE TITLE
"Sell at Market" on Bots?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1726]
Does this feature exist on Bots?

I am just thinking of starting a trade at whatever signal (like previous bots) say for 30 mins, so a longer time frame. But can you add a 'sell at market' for a certain point or price hit, within the 30 mins so that it stops the trade?

Either a price "sell at Market" or a % 'sell at market'' (like on the contract chart within Binary.com)

So either like a SL on a certain point or price and a TP on a certain point or price, like Forex but on longer Binary trades of 30 mins+ ?

**Comment by Hooponopono** [comment]
exist, is the block 3, is the voice "during purchase".

**Comment by buckman1974** [comment]
So the 'during purchase' block? can i put a stop loss and take profit on this then?

**Comment by thanh301** [comment]
![sell market](https://user-images.githubusercontent.com/52536345/61423952-f8921a80-a93b-11e9-928a-e729ea6683fb.png)
You can do it like this

**Comment by buckman1974** [comment]
OK thanks, can I ask the relevance of >1 and <1 

What exactly is the 1 unit?

**Comment by buckman1974** [comment]
I actually think this is incorrect.

I have added this sell at market strategy, over 2 hour trades on a bot with EMA's.

But it takes a trade and 1 tick later closes it, all Losses!

**Comment by thanh301** [comment]
The number is the profit the bot will sell the trade at the market. At my picture the bot will auto sell the trade if it got 1$ profit or 1$ loss

**Comment by thanh301** [comment]
![image](https://user-images.githubusercontent.com/52536345/61460896-e1821580-a999-11e9-820c-3d3dcb0d5583.png)
It work fine for me, I set the duration at 5 minute

**Comment by buckman1974** [comment]
Ok great thank you!

So the top part which is  ' > ' is the profit?

And the lower part with the ' < ' is the stop loss?

**Comment by buckman1974** [comment]
Ok input exactly as you did, and put a timeframe of 1 hour on Vol100

Put a profit of $50 and a SL of $75 

However this still takes a trade and immediatley stops with it in the red and loss?

I am doing something wrong?

**Comment by rgsk8** [comment]
> ![imagem](https://user-images.githubusercontent.com/52536345/61460896-e1821580-a999-11e9-820c-3d3dcb0d5583.png)
> Funciona bem para mim, eu defino a duração em 5 minutos

como posso colocar valores em % para esta mesma função?

**Comment by thanh301** [comment]
@buckman1974 Can you up a screen shot of your set up?

**Comment by buckman1974** [comment]
@thanh301 @rgsk8 Here is my set up : 
I don't think the number of trades works and is ignored, also the take profit seems to be ignored too?

![botp1](https://user-images.githubusercontent.com/43829090/61518089-baaafa00-aa00-11e9-84a4-835825dc8fdf.JPG)
![botp2](https://user-images.githubusercontent.com/43829090/61518090-baaafa00-aa00-11e9-84d5-88d05f96dcc1.JPG)
