### ISSUE TITLE
TradingView Implementation

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1727]
With regards TradingView, and Binary.com implementation, can we use the original TradingView to pull up the Volatility Indexes?

I know they are available through Binary.com, on Tradingview - but can we pull them up on the stand-alone TradingView, so that we can use the TV custom indicators and templates on the Volatility Indexes?

**Comment by binary-ex-machina** [comment]
No, you can't use the main site of tradingview with  volatility indexes.

**Comment by buckman1974** [comment]
OK thank you @binary-ex-machina but do you know if you used the Binary.com/Trading View charts, whether you can 'save' more than one chart set-up/indicators? so that you can re-load different strategies or indicators? 

I can't seem to see saved presets to load back up on the Binary.com/Trading View charts?

**Comment by binary-ex-machina** [comment]
The TradingView charts on binary.com are limited, you can't save, multiple charts at the same screen, custom indicators, pine editor and so on.
