### ISSUE TITLE
Time purchase

### ISSUE THREAD

**Issue by thanh301** [binary-com/binary-bot#1728]
Is it possible to set the bot to purchase at a specific time with condition meet. For example, if the condition meet and it at second 30 to second 40 every minute, it will purchase. Even the condition meet but it is not at the time zone, the bot will do nothing.

**Comment by binary-ex-machina** [comment]
You can do like this below. Put your filters inside the if with the remainder 

![image](https://user-images.githubusercontent.com/34610787/61488154-e769fd80-a97d-11e9-905d-f6bba6ec7164.png)

**Comment by thanh301** [comment]
@binary-ex-machina Thank man you're the best
