### ISSUE TITLE
How to run trend downtrend and three line strike strategy.

### ISSUE THREAD

**Issue by izy123** [binary-com/binary-bot#173]
How can i run the uptrend, downtrend and three line strike into volatility market. please help me.thank

**Comment by okovalov** [comment]
https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/simple_three_line_strike.xml

**Comment by izy123** [comment]
thank you very much but can i get that one of down trend and uptrend?

**Comment by okovalov** [comment]
@izy123 depends how you define the trend.

**Comment by aminmarashi** [comment]
I'm going to close this issue, if you still need help please feel free to reopen it.

**Comment by rq8019** [comment]
What is the best bot who give consistent profit ,... any one if have plz share for binary.com
