### ISSUE TITLE
Two very simple things needed!

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1730]
Ok maybe 3 things!

I have built a longer time frame bot, that i am just testing, but i need the basic simple 101 lesson on adding a : 

1. Simple Martingale, so every loss is x2

2. Stop loss and take profit, so stop the bot if the losses exceed $100? and take a profit and STOP bot if profit is $50 ?

3. Maximum number of trades? so type in a number like 90, so after 90 trades, it stops regardless?

I know these are really simple, but i have tried and they seem to be ignored so i am doing something stupid!!

**Comment by Eshhh** [comment]
![image](https://user-images.githubusercontent.com/33750313/61451059-209e6f80-a976-11e9-9c9b-5daf8be866cc.png)

**Comment by politecruise** [comment]
either use this 

![bot](https://user-images.githubusercontent.com/51704885/61457201-b11d8580-a95f-11e9-9634-3ff787191e29.PNG)
![bott](https://user-images.githubusercontent.com/51704885/61457202-b11d8580-a95f-11e9-8f6c-4b65489eb2ab.PNG)
[bot.zip](https://github.com/binary-com/binary-bot/files/3406473/bot.zip)

**Comment by politecruise** [comment]
or this 

![bott1](https://user-images.githubusercontent.com/51704885/61457437-36089f00-a960-11e9-8125-672185eda3b9.PNG)
![bot1](https://user-images.githubusercontent.com/51704885/61457439-36a13580-a960-11e9-90a5-edbe064c3b8c.PNG)
[bot (1).zip](https://github.com/binary-com/binary-bot/files/3406477/bot.1.zip)

**Comment by politecruise** [comment]
the difference is the type of loss, maximum stake or maximum loss

**Comment by martinrf79** [comment]
Does someone tell me how to place this thread where appropriate or someone directly respond to my mail?  https://github.com/martinrf79/digits-diff-bot/issues/1

**Comment by hotmatrixx** [comment]
> 
> 
> Does someone tell me how to place this thread where appropriate or someone directly respond to my mail? [martinrf79/digits-diff-bot#1](https://github.com/martinrf79/digits-diff-bot/issues/1)

you should start a new thread uner issues here, not under your own forum.
I answered your question, not realizing it was on your private one.
also, please don't hijack other threads.
https://github.com/martinrf79/digits-diff-bot/issues/1#issuecomment-513430186

**Comment by politecruise** [comment]
has this issue been resolved yet? do you still my assisstance??
