### ISSUE TITLE
Can someone make bot from this strategy?

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#1732]
Add martingle,profit and stop loss!!!

https://www.youtube.com/watch?v=gFdRdCHxSTk

Thanks!!!

**Comment by binary-ex-machina** [comment]
here it is

![image](https://user-images.githubusercontent.com/34610787/61489646-8d6b3700-a981-11e9-93e2-052ee00aea1a.png)

**Comment by eonuoha30** [comment]
I'm having difficulty fixing this up.

Pls, can you drop the XML or zip file?

**Comment by poroinika** [comment]
And is for me is hard to build it like on the picture,can someone post .xml?

**Comment by Herotaiko** [comment]
@binary-ex-machina 
Do I miss something?

![eee](https://user-images.githubusercontent.com/51996252/61524249-4d1ebe00-aa40-11e9-97a2-e648fcac827b.PNG)

**Comment by binary-ex-machina** [comment]
@Herotaiko here is working normally

![image](https://user-images.githubusercontent.com/34610787/61545654-5303a780-aa1e-11e9-9f08-1b5ec85e23eb.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina 

I can use it now but did not see the difference with other differ strategy

Thank you for your help.

**Comment by Arionfox** [comment]
mine doesn't even start working, just saying "Bot is Starting", and never going to "Bot is Running!" What Did I Do Wrong?

![why](https://user-images.githubusercontent.com/53241830/61756315-cba59380-ad91-11e9-9bfa-b833d1715800.png)

![Why2](https://user-images.githubusercontent.com/53241830/61756327-d5c79200-ad91-11e9-9960-4447e67290a9.png)

**Comment by rgsk8** [comment]
alguem podemandar xml por gentilesa

**Comment by Larras** [comment]
Hello...

Thank you for sharing this strategy.
I have a question, I can't find this block, can you please tell me where it is.

![image](https://user-images.githubusercontent.com/53036952/62288538-9ef51a00-b42a-11e9-970b-94a1495e9f24.png)

@binary-ex-machina 

Thank you

**Comment by binary-ex-machina** [comment]
@Larras look at the image i post, there is a block with the function. You have to create the function and access it from the Function menu.

@Arionfox if you copied the image exactly like the one I posted, it should work as mine did.
