### ISSUE TITLE
Bot Bollinger Bands

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#1735]
How to create a bot that buys when the price exceeds the lower band and sells when the price exceeds the upper band, with martingale option common in the beginning. Then you have to add input parameters.

**Comment by hotmatrixx** [comment]
you don't ask for much, do you.
can you write a simple bot yourself?
can you at least write a simple martingale bot?

this is a shortened version of the block you need to do the sell part.
![image](https://user-images.githubusercontent.com/49715381/61573667-9e918080-ab06-11e9-8566-bf4c26cf6282.png)


if you can do some of the basic bot work, you should be able to figure out how to generate a buy signal based on this, in block 2.

a martingale could be added in block 4 based on teh win/loss based on something like this:
![image](https://user-images.githubusercontent.com/49715381/61573655-6b4ef180-ab06-11e9-9204-18fe3c57a970.png)

**Comment by martinrf79** [comment]
Thank you very much for your answers, according to my experience the price moves in trend and range, although more times it moves in range, according to this statement what I want to achieve is a bot through bollinger bands overcomes the lower band buy and if it crosses the band top band
To that we would have to add a special martingale for the bot to make an operation after the fourth loss, or when the price has moved in a trend 4 times in a row.
