### ISSUE TITLE
Best Moving Average for 5 min strategy?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1737]
This maybe more of a general trading question, but wanted to incorporate into a bot.

Does anyone recommend the Best Moving Average for 5 min strategy on Volatility Indexes?

And whether EMA is better than SMA for 5 mins? I see everything from 5MA (or SMA / EMA) to 50MA ?

The smaller the number the more volatile and following of the trend(s) i guess? but its just knowing which would be better for say 5 mins? and maybe 5 ticks (ultra fast?)

Thanks!

**Comment by Herotaiko** [comment]
I agree with this topic because I am also skeptical. I would like to have a more practical answer than saying that because every type has risks.
