### ISSUE TITLE
MT5 intergration with Binary.com

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1738]
I am also just looking into MT5 that Binary.com supports.

It looks like this is Binary.com's own 'web-based' version of MT5 which is good when you have an internet connection (and looks like it will run on a Mac)

However is it best for better response/speed to use the Web-based MT5 that Binary.com gives us here, or use a downloaded program version (on Windows)?

Is there a speed increase with using a downloaded program, as opposed to the web 'streaming' version?

**Comment by Hooponopono** [comment]
u can download the general mt5 from them site.
mt5 give the possibility to the various company of brokerage to customize a proper version for them clients.
mt5 give to all brokers the ''web based'' version.
no speed difference because all start from u and your connection.
