### ISSUE TITLE
Before you start trading on the live account, you need to know this

### ISSUE THREAD

**Issue by mare69** [binary-com/binary-bot#1739]
1. citizen of the European Union - they can not trade binary options
With the aim of protecting small investors, the European Securities and Markets Authority (ESMA) has temporarily banned the marketing, trading and selling of binary options.
 
So i got email from binary.com:
> Kindly be informed that we no longer offer Binary options to clients residing in the E.U countries, only professional clients can trade.
> As an alternative we offer CFD, Volatility and Forex trading on MT5 for more information, please check the following link
> Best regards,
> Denis Kuznetsov 
> Customer Support Executive | Binary.com 

2. If you use Bot you have time limit of reality check 60min...
![Reality Check](https://user-images.githubusercontent.com/52427410/61576760-21eaac00-aade-11e9-9e6d-45862426dd6b.PNG)

Conclusion:
I can not trade on this platform because I am a citizen of the EU and, as second, my bot is useless because Reality Check.

**Comment by mare69** [comment]
I really want someone to tell me this before I worked on a demo account for a month:(

**Comment by nextnaro** [comment]
some broker have "PROFESSIONAL ACCOUNT FOR EUROPEAN TRADERS".

**Comment by mare69** [comment]
Yes binary.com have professional account..but must have 50k 

I won't trade only small amounts...0.35, 1...

**Comment by buckman1974** [comment]
Also the difference between Virtual and Real accounts, is that there is a delay. This could be crucial for some tick strategies.

I was told by another user that this was a delay of 1 tick between Real & Virtual accounts.

I just played them side by side, and the Real account definitely has a delay from when you hit the trade which can make all the difference.

**Comment by buckman1974** [comment]
You need to try your strategies on Real Account instead of Virtual, because the delay is quite big.

I just used the same bot on Virtual and Real account, and the real account was VERY laggy, and slow, delayed, and I have a good internet connection. 
When I went back to Virtual, the speed came back... disappointing
