### ISSUE TITLE
cannot read property slice of undefine

### ISSUE THREAD

**Issue by izy123** [binary-com/binary-bot#174]
I expand the TLS and inserted it inside watch and purchase your contract but it read slice of undefind please help me

**Comment by okovalov** [comment]
@izy123 where is your xml?

**Comment by izy123** [comment]
sorry trying to uploadf it but couldn't.i got it from admin the TLS I ecpanded it and put it inside the second step and ran it but it wrote cannot read property slice of undefine

**Comment by aminmarashi** [comment]
You can send it to marketing@binary.com, set `cannot read property slice of undefine #174` as your email subject.
