### ISSUE TITLE
New blocks added: Use a specific date and time in your strategies

### ISSUE THREAD

**Issue by anton-binary** [binary-com/binary-bot#1744]
You can now use a specific date and time in your strategies with the addition of these two new blocks, available in Binary > Tools > Time: 

- This is the `To Timestamp` block. It converts the date and time to the number of seconds since the Unix Epoch (1970-01-01 00:00:00).

<img width="368" alt="totimestamp" src="https://user-images.githubusercontent.com/43776314/61607153-f6072c00-ac7f-11e9-9423-4060bd3fae5d.png">

**Example:**
<img width="707" alt="totimestamp_example1" src="https://user-images.githubusercontent.com/43776314/61623496-5494d000-aca9-11e9-9430-be3bdcd9594a.png">

Here, we’re telling our bot to purchase a Rise contract at midnight on 1st August 2019.

- This is the `To Date/Time` block. It converts the number of seconds since the Unix Epoch to a date and time format such as 2019-08-01 00:00:00.

<img width="195" alt="todatetime" src="https://user-images.githubusercontent.com/43776314/61607151-f6072c00-ac7f-11e9-8cce-9620c434f896.png">

**Example:**
<img width="566" alt="todatetime_example" src="https://user-images.githubusercontent.com/43776314/61607277-8e9dac00-ac80-11e9-950b-732246310624.png">

In this example, our bot will display the date and time in green.
Try these new blocks and don’t forget to give us your feedback!

**Comment by Herotaiko** [comment]
It can be controlled to run the bot. According to the time we can set?

**Comment by anton-binary** [comment]
Hi @Herotaiko,
These blocks convert time in seconds into human readable date/time format and vice versa. It's not possible to run the bot at a specified time. However, you specify the time when you want to purchase (as shown in the example above) and then run your strategy. If all set correctly, your bot won't purchase before the specified time.

Anton

**Comment by hamels16** [comment]
hi @aaron-binary 

how to make bot always purchase in first tick each 5 min ? can i use this block to do this ?

thanks

**Comment by anton-binary** [comment]
Hi @hamels16 ,
You could store the time value in seconds in a variable and then check it on every tick. But the easier way would be to use 5 min duration i guess.

Thanks,
Anton.
