### ISSUE TITLE
Real Account delay different from Virtual?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1747]
I was told by another user that this was a delay of 1 tick between Real & Virtual accounts.

I just played them side by side, and the Real account definitely has a delay from when you hit the trade which can make all the difference.  This could be crucial for some tick strategies.

Can anyone at Binary.com confirm this? @aaron-binary ?

**Comment by anton-binary** [comment]
Hey @buckman1974 , 
Binary virtual and real feeds are equal, meaning it's the same code being run server side to price contracts for virtual and real accounts. There's no extra delay intentionally added to real accounts. Binary can't control users' internet connection though.

However, we'd appreciate if you can share video or screenshot demonstrating the delay. We can check what was going on at that particular time on our side.

Thanks,
Anton
