### ISSUE TITLE
Problemas ao abrir o xml

### ISSUE THREAD

**Issue by leoassencio** [binary-com/binary-bot#1748]
Bom dia, estou com problemas na abertura do bot xml, ele estava funcionando perfeitamente ate quinta passada (18/07/2019), agora quando tento abrir para operar ele da que o xml não é suportado.
Houve alguma atualização na plataforma?
O que posso fazer para resolver?
![Sem título](https://user-images.githubusercontent.com/53182940/61638434-c8b28200-ac6f-11e9-9b6b-0342b3f045e7.png)

**Comment by kikopqfgdffg** [comment]
chare
