### ISSUE TITLE
BB %B indicator

### ISSUE THREAD

**Issue by thainano** [binary-com/binary-bot#1749]
can you make the BB B% indicator? thanks very much

**Comment by binary-ex-machina** [comment]
you can get the value of the indicator like this below
![image](https://user-images.githubusercontent.com/34610787/61717224-0fb77a80-ad37-11e9-8b31-e00446bc21df.png)

**Comment by thainano** [comment]
> you can get the value of the indicator like this below
> ![image](https://user-images.githubusercontent.com/34610787/61717224-0fb77a80-ad37-11e9-8b31-e00446bc21df.png)

thankyou for the bot
