### ISSUE TITLE
three consecutive lost

### ISSUE THREAD

**Issue by izy123** [binary-com/binary-bot#175]
Hello please i'd like you to help, I want to add something into my strategy that after three consecutive loss it should wait for like three minute then continue.is it possible?

**Comment by aminmarashi** [comment]
Please find your requested blocks [here](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/pause%252010s%2520after%25203%2520runs.xml)

**Comment by izy123** [comment]
Amin am very grateful for your help.But please i want it to pause and wait if for example I have three consecutive losing run then afterward the can continue. is it possible? why i say this is because of trend. If am calling and then have three losing run consecutively, then i know the trend has change I just have to wait.please help me thanks.
