### ISSUE TITLE
new Project

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#1752]
I am in a project that has a lot of time of analysis in candles of 1 minutes but it has to work with tiks since the price behavior is fractal.

Assuming that the tiks up R and the tiks down F. The operations won W and the lost L . This would be the configuration.

F = W or L next prediction F
F = W next prediction F
F = L (2) next prediction R

R = W or L next prediction R
R = W next prediction R
R = L (2) next prediction F

F = W or L next prediction F
F = W next prediction F
F = L (2) next prediction R

R = W or L next prediction R
R = W next prediction R
R = L (2) next prediction F

and so on. To this we would have to add a function so that the bot operates only after the fourth loss has been recorded, in this way we cover the 10 progressions at the most that I have registered in several price tests.

Best regards

Martin

**Comment by binary-ex-machina** [comment]
It's a bit confused your analogy. What will be the pattern? For what i read in your post when a tick is lower then the past tick (F), if it's Win or loss, you assume it will go down once again. Then below you put the same idea, but if it wins it will go down again, it repeats the same rule as the first prediction.

**Comment by martinrf79** [comment]
As they are, the strategy is very simple although I can not make myself understood I think that by the language. In a summary way, starting trades up or down is indistinct. For example, we start with put operations until it loses 2 times, when there are 2 losses in a row, switch to call operations, and when there are 2 losses in a row, switch to put operations. and so on. To this we would have to add a martingale of x 2.2 or similar, the duration of the trade can be 1 tick onwards.

  Ideally, the bot will only operate when there are at least 4 loss operations, for example if the price moves 2 intervals of x ticks up and 2 intervals of x ticks down just there the bot is executed until the win is achieved. contract. Then wait for the next pattern (to name it) of 2 moves up and 2 moves down.
