### ISSUE TITLE
I need help with this strategy

### ISSUE THREAD

**Issue by Arionfox** [binary-com/binary-bot#1757]
I want my bot to work with MA crossover, but I want it to open the operation only on MA crossover

Explaining Better:

When the MA's cross, it will open a single trade and nothing else, it will only open another operation if the MA's cross again, crossing down operating fall, crossing up operating rise!

Can anyone help me?

**Comment by lasaidhari** [comment]
![SMA CRROSOVER](https://user-images.githubusercontent.com/34808023/61831605-31fbe600-ae66-11e9-8b52-5da7047a3a25.gif)
example. please create the MA option for the period and duration and add your martinggale settings
[Arionfox.zip](https://github.com/binary-com/binary-bot/files/3428900/Arionfox.zip)

**Comment by Hooponopono** [comment]
> ![SMA CRROSOVER](https://user-images.githubusercontent.com/34808023/61831605-31fbe600-ae66-11e9-8b52-5da7047a3a25.gif)
> example. please create the MA option for the period and duration and add your martinggale settings
> [Arionfox.zip](https://github.com/binary-com/binary-bot/files/3428900/Arionfox.zip)

you forget ''# from the end"

**Comment by lasaidhari** [comment]
> 
> 
> > ![SMA CRROSOVER](https://user-images.githubusercontent.com/34808023/61831605-31fbe600-ae66-11e9-8b52-5da7047a3a25.gif)
> > example. please create the MA option for the period and duration and add your martinggale settings
> > [Arionfox.zip](https://github.com/binary-com/binary-bot/files/3428900/Arionfox.zip)
> 
> you forget ''# from the end"

![Hooponopono](https://user-images.githubusercontent.com/34808023/61846134-dea58a00-ae9d-11e9-9d8c-eb09b57f0169.gif)

**Comment by Arionfox** [comment]
Thank you, helped me a lot!
