### ISSUE TITLE
Copy trading on binary.com

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1758]
Please, is it possible to copytrade on binary.com? 

What I mean is to link the trading account of different persons to mine.

Then, when I place trades on mine, exactly same trade will be simultaneously placed on their accounts also.

Please, how can I do this?

**Comment by anton-binary** [comment]
Hey @eonuoha30,

Binary offer copy trading. There's actually 2 options available:
1. Users (Copiers) can link their accounts to another user's account (a Trader), so any deal made by a Trader will be mirrored on Copiers accounts. Trader can use any of Binary platforms including Bot. To set this up you can open https://webtrader.binary.com/, log in and set up the link between Copier's and Trader's account.
 
![image](https://user-images.githubusercontent.com/43776314/62018281-a7f8a800-b1ec-11e9-85fe-037783b3d311.png)

2. Users can trade on behalf of other users via API. https://developers.binary.com/copytrading/

Best regards,
Anton

**Comment by emtecetr** [comment]
Where can i see list of traders tokens to copy.

**Comment by oShaDav** [comment]
> 

Hii. Did you find out how to set copy trading. I also want to know how to let other traders to copy my trades on binary.com. If you know please help me. Thank you.
