### ISSUE TITLE
Need Tick bot like this @binaryexmachina  @lasaidhari

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1762]
please help me
if 5 ticks continuously upword 5 ticks buy
if 5 ticks continuously down sell 5 ticks sale
like this
20 21 22 23 24 25 signal buy
20 19 18 17 15 12 sale
its ticks analyze bot
please help me
thanks
and martingale too and stop loss or matringale step

**Comment by dushanu** [comment]
please help me ... hml or text..

**Comment by lasaidhari** [comment]
![dushanu 5 TICK RRRRR FFFFF](https://user-images.githubusercontent.com/34808023/61922846-bed39c00-af59-11e9-96d8-675ccbdbf3ef.gif)

may be useful
[5 TICK RRRRR FFFFF.zip](https://github.com/binary-com/binary-bot/files/3434024/5.TICK.RRRRR.FFFFF.zip)

**Comment by dushanu** [comment]
thank you very much @lasaidhari .. god bless u

**Comment by dushanu** [comment]
thanks again
