### ISSUE TITLE
"Amount must be a positive number."

### ISSUE THREAD

**Issue by XCelestialX** [binary-com/binary-bot#1763]
I dont know whats happening with the bot, im not sure what im doing, but basically i was trying to combine 2 bots, i want the final bot to operate like one but manage the loss like the other so im not sure whats happening.

I was trying to combine these bots:

Use this to Watch and purchase the contract: 
[2-3-sma.zip](https://github.com/binary-com/binary-bot/files/3433384/2-3-sma.zip)

This one to Get my trade result and trade again: 
[recover-bot.zip](https://github.com/binary-com/binary-bot/files/3433385/recover-bot.zip)

This is my attempt to do it(im noob): 
[NewBot.zip](https://github.com/binary-com/binary-bot/files/3433400/NewBot.zip)

**Comment by lasaidhari** [comment]
![2-3ma recoverbot](https://user-images.githubusercontent.com/34808023/61924264-ed07aa80-af5e-11e9-99af-14061240438a.gif)

is it like that? may be useful
[2-3ma recoverbot.zip](https://github.com/binary-com/binary-bot/files/3434060/2-3ma.recoverbot.zip)

**Comment by XCelestialX** [comment]
Wow, thank you so much for your help but im afraid that it isnt what i wanted my friend, is there a way we can talk private so i can explain to you more in detail? Email?

**Comment by lasaidhari** [comment]
saidforex26@gmail.com

**Comment by XCelestialX** [comment]
Hello my friend, what i was trying to do is to use the strategy that the
2-3ma bot uses to buy the contracts, but using the recover-bot money
management strategy if you know what i mean.

**Comment by XCelestialX** [comment]
What i have seen is that the 2-3ma bot stats are better than the
recover-bot one, the wins and loses are more balanced(50/50), but the
recover-bot has a better way to manage the loses, you can test them so you
can undestand, the 2-3ma uses the martingale system, but the recover-bot
has a strategy that is less risky.

**Comment by lasaidhari** [comment]
do you mean using money
management from recover bot and 2-ma to buy contracts

**Comment by XCelestialX** [comment]
Yes

**Comment by lasaidhari** [comment]
![2-3ma part2](https://user-images.githubusercontent.com/34808023/61926886-74a6e680-af6a-11e9-986a-cbf2b19f857a.gif)
Please try..
[2-3sma Part2.zip](https://github.com/binary-com/binary-bot/files/3434241/2-3sma.Part2.zip)

**Comment by XCelestialX** [comment]
> ![2-3ma part2](https://user-images.githubusercontent.com/34808023/61926886-74a6e680-af6a-11e9-986a-cbf2b19f857a.gif)
> Please try..
> [2-3sma Part2.zip](https://github.com/binary-com/binary-bot/files/3434241/2-3sma.Part2.zip)

Haha, i did my best but i kinda forgot the blocks down there xD, im new in this.

Thank you so much! Thanks for your help, very useful.

Im gonna keep testing it to see how it goes. I will share the results soon.

**Comment by Herotaiko** [comment]
Thanks for the lab to change the information.
