### ISSUE TITLE
can anyone make a bot of this strategy

### ISSUE THREAD

**Issue by Arionfox** [binary-com/binary-bot#1764]
https://www.youtube.com/watch?v=pBG-c34eRcs&t=

Thank you so much!!!

**Comment by lasaidhari** [comment]
Maybe like this
![Change](https://user-images.githubusercontent.com/34808023/61988558-ac6d6700-b01a-11e9-9dd0-cec99b72b8c4.gif)

**Comment by kikopqfgdffg** [comment]
send me bot  obrigado

**Comment by kikopqfgdffg** [comment]
danipq12@gmail.com

**Comment by lasaidhari** [comment]
Tested again in a virtual account first
[Change index 25 under 7 (0.01%) (2).zip](https://github.com/binary-com/binary-bot/files/3438182/Change.index.25.under.7.0.01.2.zip)
