### ISSUE TITLE
Moving Average Higher/Lower

### ISSUE THREAD

**Issue by LCavanholi** [binary-com/binary-bot#1766]
The strategy is as follows:
If the candlestick closes above the moving average (higher / period 2) it is put put with an expiration time of 3min.
If the candlestick closes below the moving average (lower / period 2) it is call with a 3 minute expiration time.
Standard candle 3 minutes.
It is possible?

**Comment by binary-ex-machina** [comment]
you can do like this
![image](https://user-images.githubusercontent.com/34610787/62133024-8105a900-b2b4-11e9-9240-eac996ea96d5.png)
