### ISSUE TITLE
I have a problem with my bot,Can someone help me?

### ISSUE THREAD

**Issue by Arionfox** [binary-com/binary-bot#1768]
My bot simply does not want to run, it is only in "Bot is Starting", never goes to "Bot is Running", regardless of the tab, or the browser that I open it, is giving this error!

Does anyone know how to resolve this error?

![61756327-d5c79200-ad91-11e9-9960-4447e67290a9](https://user-images.githubusercontent.com/53241830/61956300-3245cf80-af93-11e9-9e55-ac422f65ae83.png)

**Comment by anton-binary** [comment]
Hi @Arionfox,

Perhaps the `Repeat` loop in `Define trade options` in infinite? So, your bot never goes to the `Watch and purchase your contract`, thus stays on `Starting` forever.

Best regards,
Anton
