### ISSUE TITLE
can i change if trade lost different market? 

### ISSUE THREAD

**Issue by dushn** [binary-com/binary-bot#1770]
if i trade votalitity index 10 1 usd i called odd if lost change 2nd trade with volatiluty index 25 i called 2 doller odd if lost next votalitity index 50 4 usd if win chage first stratagy of if lost go volatality index 75
liki this?

**Comment by dushanu** [comment]
i mean change strategy if lost every time in same bot.. go to other market?

**Comment by lasaidhari** [comment]
Bot.binary.com Cannot do index changes in one bot ... you have to open 5 tabs and do an analysis ... following Money Management Examples Who can find out every option that loses on other bot tabs
![money managemen](https://user-images.githubusercontent.com/34808023/62000313-f4989200-b0cb-11e9-9bbf-7cff9c26ecc5.gif)

**Comment by dushanu** [comment]
can you please upload this... @lasaidhari

**Comment by lasaidhari** [comment]
money management is not free.
