### ISSUE TITLE
can anyone make bot for touch/no touch 

### ISSUE THREAD

**Issue by hamels16** [binary-com/binary-bot#1771]
hi my friend

can anyone can help me to create bot for touch/no touch strategy ? 
if the previous candle is green then touch 
if the previous candle is red then no touch 

i need to define barrier as well

thanks for your help

**Comment by lasaidhari** [comment]
May be useful
![TOUCH](https://user-images.githubusercontent.com/34808023/62004263-b4143500-b11a-11e9-90c2-47846a6a861e.gif)

**Comment by hamels16** [comment]
hi @lasaidhari 

good work many thanks.. but i want to have different offset for touch and no touch... how to do ?

**Comment by hamels16** [comment]
hi master

anyone can help me to make bot starting every first minute of the candle ??

**Comment by lasaidhari** [comment]
[Color Candle With Time Candle (2).zip](https://github.com/binary-com/binary-bot/files/3454754/Color.Candle.With.Time.Candle.2.zip)

This is how to make a bot with cadle colors and candle opening time .. please learn how it works and add martingale that suits your finances. hopefully useful
https://drive.google.com/open?id=1g8Gm2gIvymxlwmTKRqe-DNe8bZLdl9W0
