### ISSUE TITLE
How to add 2 blocks for higher / lower +-

### ISSUE THREAD

**Issue by Batekmax** [binary-com/binary-bot#1773]
![Безымянный](https://user-images.githubusercontent.com/52479036/62004991-16cef600-b146-11e9-9b44-5876d83b878d.jpg)

**Comment by navneetsinh** [comment]
@Batekmax 
![Opera Snapshot_2019-07-29_184920_bot binary com](https://user-images.githubusercontent.com/42480287/62051761-a30a1780-b231-11e9-996b-8c79131111fe.png)
