### ISSUE TITLE
Need Help: How can I add my account to the robot.

### ISSUE THREAD

**Issue by sakiakanda** [binary-com/binary-bot#1776]
Hi There,

I have attached the bot which I cannot run.
I need to add my virtual account and real account to this robot.
Can you please test and give me a solution to how I can add my account.

Thanks in advance

[BinaryRobot.zip](https://github.com/binary-com/binary-bot/files/3441735/BinaryRobot.zip)

**Comment by Hooponopono** [comment]
not have a solution because miss parts in the program,

**Comment by sakiakanda** [comment]
Oh.. 
This robot is only working on internet explorer 11 browsers.
