### ISSUE TITLE
How  set up when reaching the max Martingale and start again at the first steak price

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1777]
I want to reach them max martingale and start back as the first stake price.
Ex. I wont start stake 0.35 again

![sssss](https://user-images.githubusercontent.com/51996252/62058776-27699400-b24c-11e9-892f-e7652c9531b1.PNG)

**Comment by binary-ex-machina** [comment]
Do like this
![image](https://user-images.githubusercontent.com/34610787/62132794-15bbd700-b2b4-11e9-9f83-209e9ba768fd.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina Thank you for helping, but after that, Bots did not martingale.
![Capture](https://user-images.githubusercontent.com/51996252/62146962-ad570f00-b320-11e9-851a-1fbe48dd4b30.PNG)

**Comment by Herotaiko** [comment]
@binary-ex-machina I am wrong, some settings are now available. Thank you for helping.
