### ISSUE TITLE
add a new candle to run

### ISSUE THREAD

**Issue by felixhuy** [binary-com/binary-bot#178]
Hi Amin,

Pease help me. I added new candle in the bot to run when begin new candle during 53s, but it not working

![capture](https://cloud.githubusercontent.com/assets/26194420/23762214/ec1a730c-0527-11e7-879c-3649b715b45f.PNG)

**Comment by aminmarashi** [comment]
Could you please upload your blocks somewhere and share the link with us? Or you can send it to marketing@binary.com set `add a new candle to run #178` as your email subject.

**Comment by felixhuy** [comment]
Please help me, i want add method but it is not run

If Put win next trade Put, Call win next trade Call
If Put lose next trade Call - Call - Call, Call lose next trade Put - Put -
Put.

2017-03-10 14:34 GMT+07:00 Amin Marashi <notifications@github.com>:

**Comment by aminmarashi** [comment]
Please find it [here](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/alternate%2520call%2520put%2520on%2520loss.xml)

**Comment by felixhuy** [comment]
Thank you so much!

2017-03-10 15:16 GMT+07:00 Amin Marashi <notifications@github.com>:

**Comment by felixhuy** [comment]
Hi Amin!

Can you help me to add the block to bot. I can't understand where can i add
?

2017-03-10 15:20 GMT+07:00 Huy Nguyễn <nghuy2410@gmail.com>:

**Comment by aminmarashi** [comment]
Just drag-and-drop it to Binary Bot window.

**Comment by felixhuy** [comment]
Hi Amin,

Have you skype ? or Facebook or another ? can i chat with you ?

2017-03-10 15:40 GMT+07:00 Amin Marashi <notifications@github.com>:

**Comment by aminmarashi** [comment]
You can contact marketing@binary.com for further assistance.
