### ISSUE TITLE
help with the analysis of the color of the candle

### ISSUE THREAD

**Issue by Batekmax** [binary-com/binary-bot#1781]
I need the bot to determine the color of the candle (green) at intervals of 15 minutes. and insert it in block 2 to trade only on it. If anyone has something skinte please in xml. Thank you very much!

**Comment by binary-ex-machina** [comment]
the strategy you send is very vague. If the candle on 15min time frame is green, it trades what? rise / fall?

**Comment by hotmatrixx** [comment]
do yo umean you want the 15 minute candles to be green (ie 4 candles per hour)
or do you mean that every 15 minutes you check to see if the current 1 minute candle was green?
