### ISSUE TITLE
[BUG ]Contract Proposal Undefined

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1782]
So I'm running a bot ATM, and if i use it on volitility indices (ie fake stocks) it's perfect. the moment I use it on a commodity or Forex, it does about 10-15 trades, the trend swaps direction, 2x, and the 3rd time it pops 'contract proposal undefined'.

it's a bug. I'm sure of that as it works on some markets, but not others.
today, instead of popping 'contract poroposal undefined' it popped this instead, which I thin may be the same or similar thing, but it may also help you to find out what's causing theis unresolved issue;
![image](https://user-images.githubusercontent.com/49715381/62174220-27bd7880-b38d-11e9-9937-5c1aca55e99a.png)

**Comment by anton-binary** [comment]
Hey @hotmatrixx,
Thanks for reporting, we'll investigate and let you know.

Anton

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Thanks for reporting this issue. Would you be able to share your strategy with us? This will allow us to investigate what's happening here. You may send this to binarybot@binary.com or upload it on gist.github.com and share it here.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
Just an update, Aaron.
I've just revisitied my strategy. It's prety complicated, and I'm a little protective over it ATM.
I have looked at it though, and it seems that I may have been recursively dividing by the Stake on a loss, causing the stake to eventually be calculated as a negative number. Maybe. I've adjusted it, but it's quite a slow moving strategy, so it might be a few hours or days before I can confirm.

If it's STILL doing it after this, I will let you have it.

Those REM's would make explaining it (and therefore bug finding) much more efficient. :)

**Comment by aaron-binary** [comment]
> [...]

Hi @hotmatrixx,

Alrighty, keep us posted.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
It happened again, but I think i fixed it,

my Stake was calculated based on previous events. I added a rounding function to the stake round (x100 /100) to make it round to 2 decimal places. previously it could calculate out to about 0.00000000001 places. (i was using a notification that let me know)

I wonder if that causes the mini freakout?

I just quicly wrote a script up to test this.
nope it seems your softare rounds down internally (cheeky) and disallows a negative number.

**Comment by hotmatrixx** [comment]
I just wrote a bot for someone else, and it's doing 'contract undefined' as well.
[HERE IS YOUR DOWNLOAD](https://github.com/binary-com/binary-bot/files/3471487/eon.zip)
