### ISSUE TITLE
RSI Higher/Lower Touch And Return Back

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1783]
Indicators: RSI (14) with levels at 70 and 30.

Buy Entry : Buy when RSI has crossed below 30, formed a bottom, and then crossed back up through 30.
Sell Entry : Sell when RSI has crossed above 70, formed a peak, and then crossed back down through 70.

@binary-ex-machina
@lasaidhari
@aaron-binary
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

**Comment by binary-ex-machina** [comment]
You can get the cross part like this below
![image](https://user-images.githubusercontent.com/34610787/62218210-626de380-b382-11e9-8582-f25bb8e14383.png)

**Comment by RozeBlack** [comment]
> You can get the first cross part like this below
> 
> ![image](https://user-images.githubusercontent.com/34610787/62218210-626de380-b382-11e9-8582-f25bb8e14383.png)
> 
> 

For some reason when I put this in. I get undefined is not a function error
