### ISSUE TITLE
EMA breakthrough

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1785]
50 EMA
**Time Frame :** 5M

Watching for a candle to pierce 50 EMA and finally close above (to enter Long) or below (to go Short). Enter with the second candle after it makes 5 pips higher than the previous one.

@binary-ex-machina
@lasaidhari
@aaron-binary
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

**Comment by binary-ex-machina** [comment]
@navneetsinh another copy/paste, repeating questions from other posts. Try to search first #1786
