### ISSUE TITLE
50 EMA

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1787]
**Time frames :** Minute 15 `( Suggest If any good time frame with this condition )`

**Buying :**
1. Wait for price to break the 50 EMA to the upside
2. The candlestick that breaks the 50 EMA either upwards and closes above it is your entry candlestick.
3. Place your buy stop order 2-5 pips above the high of this candlestick. You are anticipating a breakout of this candlestick which will trigger your buy stop order.
4. Place you stop loss 5-10 pips below the low of the entry candlestick.
5. Exit when an opposite signal is given or lock in profits by using trailing stop loss and placing it a few pips behind lower swing highs that form as the price continues to move downward until you get stopped out with a profit.

**Selling :**
1. Wait for price to break the 50 EMA to the downside.
2. The candlestick that breaks the 50 EMA either downwards and closes below it is your entry candlestick.
3. Place your sell stop order 2-5 pips below the low of this candlestick. You are anticipating a breakout of this candlestick which will trigger your sell stop order
4. Place you stop loss 5-10 pips above the high of the entry candlestick.
5. Exit when an opposite signal is given or lock in profits by using trailing stop loss and placing it a few pips behind higher swing lows that form as the price continues to move until until you get stopped out with a profit.
`**If any good suggestion in this given conditions please give as required.**`

@binary-ex-machina @lasaidhari @aaron-binary @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by hotmatrixx** [comment]
why are yo uposting these, mate?
have you made these indicators? Are you offereing them to the community?
are you asking us to build them for you?
these are pretty much copy and pasted instructions on how they should work as a stop loss setup. I don't really understand why you've posted this here.

**Comment by binary-ex-machina** [comment]
@navneetsinh again, another forex strategy. Please pay attention of what you post here, since this is for binary options. Like hotmatrixx posted, looks like you just found a website with a lot of strategies, didn't read any of them and just posted here. This repository is for you to learn, not to get anything you want build.
