### ISSUE TITLE
200 EMA With Awesome Oscillator

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1788]
**Indicators :** 200 EMA, Awesome Oscillator (default settings)

**Time frames :** 30 Minute ( **Suggest If any good time frame with this condition** )

**Buying :**
1. Price must be (a) travelling above the 200 ema and head back down to touch the 200 ema or (b) crossed up from below the 200 ema and there’s a bullish candlestick closed above the 200 ema.
2. The Awesome Oscillator must (a) have a green bar or (b) must be above the 0.00 level.
3. The buy signal must be a bullish candlestick that forms after touching the 200 ema and bounced up or crossed from below the 200 ema and closed above the 200 ema line.
4. Place a buy stop order 2 pips above the high of that bullish candlestick (if spread is huge, increase this to between 3-5 pipes).
5. Place your stop loss 2 pips below the low of the nearest swing low, which ideally should be the bottom of the candlestick that touched the 200 ema and bounced back up from or 2 pips below the low of that bullish candlestick where you placed the pending buy stop order if that stop loss is not too close to get you stopped our prematurely.
6. For take profit target price level, aim for the previous swing high point or you can use a risk:reward of 1:2 or more.

**Selling :**
1. Price must be (a) travelling below the 200 ema and head up to touch the 200 ema or (b) crossed down from above the 200 ema line and there’s a bearish candlestick closing above the 200 ema.
2. The Awesome Oscillator must (a) have a red bar or (b) must be below the 0.00 level.
3. The sell signal must be a bearish candlestick (a) that forms after touching the 200 ema and bouncing back down or (b) crossed from above the 200 ema and closed below the 200 ema line.
4. Place a sell stop order 2 pips above the high of that bearish candlestick (if the spread is huge, increase this to between 3-5 pips).
5. Place your stop loss 2 pips above the high of the nearest swing high, which ideally should be the top of the candlestick that touched the 200 ema where it bounced back down from or 2 pips above the low of that bearish candlestick where you place the pending sell stop order if that stop loss is not too close to get you stopped our prematurely.
6. For take profit target price level, aim for the previous swing low point or you can use a risk:reward of 1:2 or more.

**If any good suggestion in this given conditions please give as required.**

@binary-ex-machina @lasaidhari @aaron-binary @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by binary-ex-machina** [comment]
@navneetsinh this is all for forex, did n't read it before posting? nothing to do with binary options here
