### ISSUE TITLE
Linear Weighted Moving Average ( LWMA )

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1789]
**Linear Weighted Moving Average ( LWMA )** **= ?**

@binary-ex-machina @lasaidhari @aaron-binary @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

**Comment by binary-ex-machina** [comment]
LWMA is the same as WMA, but it shows color when one value is above the past value (green) or below (red) 

You can get the WMA indicator on my repository
https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#wma

**Comment by ricothenfx** [comment]
@binary-ex-machina 
![Opera Snapshot_2019-09-15_174120_www binary me](https://user-images.githubusercontent.com/42637217/64920293-1666e900-d7e0-11e9-8e04-5a7fd3608a77.png)
try open chart on SMART TRADER binary.com
there are WEIGHTED MOVING AVERAGE & LINEARLY WEIGHTED MOVING AVERAGE also.
confused.

**Comment by binary-ex-machina** [comment]
@ricothenfx 

https://www.investopedia.com/terms/l/linearlyweightedmovingaverage.asp

https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/wma

try to find the differences

**Comment by ricothenfx** [comment]
Only at binary.com smart trader there are WMA & LWMA. I checked at another web, theres only WMA or theres only LWMA. At metatrader 5, also theres only LWMA.

**Comment by binary-ex-machina** [comment]
@ricothenfx so what's your point? it really makes difference in the filters? i don't see major differences in the calculation. Original is only WMA, both sites i sent shows that the calculation is almost the same.
