### ISSUE TITLE
3 lose and reply

### ISSUE THREAD

**Issue by felixhuy** [binary-com/binary-bot#179]
Hi Amin,

Can you help me about this ?
I want to change something
Ex: 
Normal it will run 
Put lose- Call lose- Put lose- Call lose.....until to win. But it lose over 10 times.
I think i want lose 3 times, then change method
Like this:
1. get Put lose
2. get Call lose
3. get Put lose
but 4. get Put... (this is need change)
............
1 get Call lose
2 get Put lose
3 get Call lose
and 4. get Call... (this is need change)

I think i want lose 3 times and change method, it will be safe for my balance. Please help me, Thanks you.
![capture](https://cloud.githubusercontent.com/assets/26194420/23807055/d1ee3412-05f6-11e7-9c67-1a1cfc4c97aa.PNG)

**Comment by aminmarashi** [comment]
I hope [this](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/alternate%25203%2520times%2520then%2520change%2520order%2520(1).xml) is what you're looking for.

**Comment by felixhuy** [comment]
Thank you so much, it is awesome :D

2017-03-13 8:50 GMT+07:00 Amin Marashi <notifications@github.com>:

**Comment by felixhuy** [comment]
Hi Amin,

Have you sell bot for binary, I try make a good bot w lose 4 times or less
in one trade, but i cant it always lose over 4 times in one trade, Please
help me if you have a something idle. Thank you.

2017-03-13 9:23 GMT+07:00 Amin Marashi <notifications@github.com>:
