### ISSUE TITLE
Unfair!!!

### ISSUE THREAD

**Issue by thainano** [binary-com/binary-bot#1790]
![pre-school-fx-ladder](https://user-images.githubusercontent.com/47125235/62208089-06c24b00-b3c0-11e9-8fc4-06b103300a01.png)

if the broker win, he gets 100%
if trader win he only gets 88%
if no one win, the broker still gets 100%
what the hell is this?
what more do you want? you have more weight than me plus I fight a boxing match with you with one of my hand tied?

**Comment by hotmatrixx** [comment]
that's actually how it's supposed to work, yes.
it's exactly the same as betting on horses or boxing matches.

If Player A wins, I pay $1.10
If Player B wins, I pay $.80c

Then, I make sure that I only take as many people betting on A as B.
I don't care who wins, I keep $.10c on every dollar.

however is it fair?
sure it is. there are not many places where you can make 80% of your money back in one minute.

Also, I have been working on Stock Markets for 3 years, studying them. I make nearly a full time living at it now. I can beat the market quite regularly.

This is on my real money account.
![image](https://user-images.githubusercontent.com/49715381/62212106-31c69200-b3f4-11e9-86cd-c8bc0ae38d30.png)

**Comment by kikopqfgdffg** [comment]
@hotmatrixx tem como me enviar esse robo da imagem acima agradesco!!
