### ISSUE TITLE
Can someone help me with this strategy

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#1796]
![screen-08 14 22 01 08 2019 `1](https://user-images.githubusercontent.com/36769713/62267437-c7821180-b434-11e9-868e-c1247b5a03e9.png)

I whant bot wich open when he see that on the picture:

Open if ''Change"' is >0.70 and direction is UP.....to open FALL

Please add Martingle and Take Profit and Stop loss

Thanks!!!

**Comment by lasaidhari** [comment]
[Change _0.7 .zip](https://github.com/binary-com/binary-bot/files/3455094/Change._0.7.zip)
please select one of the fall or rise options and try it first in the virtual account ... hope it can help
![change 0 7](https://user-images.githubusercontent.com/34808023/62270495-08c2f300-b42e-11e9-9348-1d62db858298.gif)

**Comment by poroinika** [comment]
yes man,thats it what I whant.

Thanks!!!
