### ISSUE TITLE
is it possible to do that?

### ISSUE THREAD

**Issue by Arionfox** [binary-com/binary-bot#1798]
Is it possible to have a bot open a fall trade when the penultimate price digit is "7"?

![Opera Instantâneo_2019-08-01_085354_www binary com](https://user-images.githubusercontent.com/53241830/62291620-c48a1f80-b43a-11e9-87bd-699883aa076b.png)

Thank You!

**Comment by lasaidhari** [comment]
it is very possible but the use of digits for rise fall is less effective because each time the digit will change

**Comment by Arionfox** [comment]
@lasaidhari 

Yeah, I'll fit this into a more complete strategy, I just really don't know how to do this, can you help me?

**Comment by lasaidhari** [comment]
[oke Letter # from End.zip](https://githubit is one of the functions of selecting digits. there are many other ways ... please develop and learn ... hopefully it can help.com/binary-com/binary-bot/files/3459328/oke.Letter.from.End.zip)

![okey select Letter # from End](https://user-images.githubusercontent.com/34808023/62338825-c4892e80-b4d1-11e9-81e5-d7c6df7e7e41.gif)

**Comment by junioryum** [comment]
Amigo é possível fazer a troca da previsão do dígito exemplo determinar dois dígitos de previsão e alternar entre eles

**Comment by junioryum** [comment]
Friend is it possible to make a forecast digit change example determine two digits of the forecast and switch between them can send me an email junioryum1985@gmail.com
