### ISSUE TITLE
how to get Payout percentage ?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1806]
how to get Payout percentage ?
return as % , 90% 94% ?
any block available or new feature?

**Comment by lasaidhari** [comment]
[percentage.zip](https://github.com/binary-com/binary-bot/files/3459777/percentage.zip)
hopefully can help
![percentage](https://user-images.githubusercontent.com/34808023/62347804-d9c28500-b4f2-11e9-83b6-73038e50a53a.gif)
