### ISSUE TITLE
Please Help Me Crate This Fractal Parabolic Bot

### ISSUE THREAD

**Issue by Binaryboy707** [binary-com/binary-bot#1809]
Dear Brother How Are You

I need Crate this type bot With martingale  to Next signal
( after lost trade Next signal to trade martingale )
please help me 
 see this picture  
displaying one candle to fractal and parabolic  dot  just open  call  or put ( See this picture )
Example  ( candle up side to coming fractal and parabolic dot open put trade )
                ( candle to under side coming to fractal and parabolic open call trade

coming to signal fractal and parabolic dot in one candle  just open trade 1 minute Expire next candle
![0000](https://user-images.githubusercontent.com/49775435/62395052-c4019e00-b58c-11e9-8da3-607cf44c7222.JPG)
![2](https://user-images.githubusercontent.com/49775435/62395094-daa7f500-b58c-11e9-95ea-68d18a9fe16b.JPG)

@hotmatrixx @James-Ngigi @ghost @binary-ex-machina @T3sl4 @sinung21 @lasaidhari

**Comment by hotmatrixx** [comment]
I've actually just created a Parabolic SAR bot. it only took me like 2 weeks to get it running smoothly. 

Parabolic SAR is not natively supported by this software, you have to write it 'manually'. it's a fair bit of coding, TBH.

Most importantly, you can't bid on Forex in 1minute increments on this trading platform.
also, IQ Option will take your money. their  software is really reliable on the demo account, but once you put real money into it, it completely does its' own thing, and can be.... quite different to the 'LIVE' markets. they class it as 'spread'.  I lost $3k on their platform. it's what led me to discover this one.
