### ISSUE TITLE
strategy change every 10 usd win? @binaryexmachina @lasaidhari

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1810]
[5.TICK.RRRRR.FFFFF.zip](https://github.com/binary-com/binary-bot/files/3463140/5.TICK.RRRRR.FFFFF.zip)
i need change this to every win change strategy

like this
1 st 10 usd win trade as 1 usd RRRRR only after win  10USD change it FFFFF to next and after win 10 usd change to RRRRR and win 10 usd chage it FFFFF to next 
can you help me
thanks

**Comment by dushanu** [comment]
![EEEEE](https://user-images.githubusercontent.com/46428076/62403705-d7246600-b5ac-11e9-9cef-a8884ea39669.JPG)
like this

**Comment by lasaidhari** [comment]
[CHANGE RRRRR TO FFFFF.zip](https://github.com/binary-com/binary-bot/files/3463212/CHANGE.RRRRR.TO.FFFFF.zip)
![RRRRR FFFF USD10 CHANGE](https://user-images.githubusercontent.com/34808023/62404933-87d03c80-b590-11e9-9b52-410567223839.gif)

**Comment by dushanu** [comment]
thanks you very much ... you re soo helping me... thanks again god bless u.. if you can tell me how to set 4 strategey  like rrrff ffrrr like... 

- can

**Comment by dushanu** [comment]
and bot changed evety time win i mean every 10 doller not single trade . strategy target is 10 usd
like 1 1 1 1 1 1 1 profit 10 usd after change

**Comment by dushanu** [comment]
sorry for disterbing for you...i dont know how to create bot...

**Comment by lasaidhari** [comment]
RRRFF TO FALL AND FFFRR to rise 
or
RRRFF TO rise AND FFFRR to fall

**Comment by dushanu** [comment]
RRRFF to rise
FFFRR fall

**Comment by dushanu** [comment]
please check every win change bot i want target profit change like 10 usd

**Comment by dushanu** [comment]
![Capture x](https://user-images.githubusercontent.com/46428076/62405487-3be6bd00-b5bb-11e9-8d6b-2e1495d182fd.JPG)

**Comment by dushanu** [comment]
i want it stay same strategy after complete 10 usd and change another

**Comment by dushanu** [comment]
add this strategy//// thanks you very much

**Comment by dushanu** [comment]
i deleted some comment ... i wrong... please add 
RRRFF to rise
FFFRR fall stragegy

**Comment by dushanu** [comment]
it mean 4 stratefy

**Comment by lasaidhari** [comment]
[PART1 PART2.zip](https://github.com/binary-com/binary-bot/files/3463248/PART1.PART2.zip)
Please make and develop it. try to create it with your thoughts .. the logic of the programmer is the same as human logic, it only needs to be creative and diligent in learning so you can make other bots in the future ... bots that currently have 2 parts ... learn and develop the bot with your ability to make it more fine again
![PART1 PART2](https://user-images.githubusercontent.com/34808023/62405618-88b89c80-b597-11e9-98a1-9c58fdb96c25.gif)

**Comment by dushanu** [comment]
thank you soo much ... god bless you

**Comment by lasaidhari** [comment]
You are welcome
