### ISSUE TITLE
How can I create a tick list?

### ISSUE THREAD

**Issue by Rafaelwebs** [binary-com/binary-bot#1819]
How can I create this tick list? If tick 3 direction is rise and tick 2 direction fall and last tick 1 direction fall then fall

**Comment by streetyuk** [comment]
[block evry tick x8.zip](https://github.com/binary-com/binary-bot/files/3542312/block.evry.tick.x8.zip)

**Comment by shedriko** [comment]
pls how do i create tick analysis to differ last digit  in a set of 20 ticks
