### ISSUE TITLE
Block MACD

### ISSUE THREAD

**Issue by felixhuy** [binary-com/binary-bot#182]
Can you help me make a example block MACD ?

**Comment by okovalov** [comment]
@felixhuy here is an example of using another indicator "Use RSI indicator to choose the purchase option" - https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/rsi%2520call%2520put.xml

**Comment by felixhuy** [comment]
ok close this issue
