### ISSUE TITLE
How to open a trade in an exact moment?

### ISSUE THREAD

**Issue by XCelestialX** [binary-com/binary-bot#1823]
Lets say i want the bot to open a trade each minute, but have to be exactly 60 seconds, if possible, can it be done using real time?

**Comment by hotmatrixx** [comment]
Yes. Kind of.
 remember, however that if you wanted to trade exactly every 60s, you'll have an issue, let me explain:

Either you could use these 
![image](https://user-images.githubusercontent.com/49715381/62515000-1f75a980-b875-11e9-90bb-15b988f98b34.png)

or you could set up a loop that does something like this;
![image](https://user-images.githubusercontent.com/49715381/62515033-31574c80-b875-11e9-94d8-7584d19c45e9.png)


however, remember that 
1. if you are trading on Forex, they tend to liek m3 or 5 minute trades as a minimum.
2. you can only place one trade at a time, and the last trade must complete before the bot wills tart calculating or watching for the next trade
3. if you set it to buy 'on' the minute, and the trade is 60s or 120s or 180 s.... then remember that it starts looking after the other trade complets, so if you took a 3 minute trade, it would actually wait 59 secoonds after the last one closed before purchasing the next trade....

so not really, I'm guessing.
