### ISSUE TITLE
Std Dev Multiplier in BB Indicator

### ISSUE THREAD

**Issue by kan-il** [binary-com/binary-bot#1824]
Can anyone please explain what the Std Dev Multiplier in the BB indicator means and the value to be entered. Thanks

**Comment by hotmatrixx** [comment]
Standard Deviations are a 'parabolic' style of calculation, basically, you're multiplying the speed of the trend by the SD.

I THINK I might be wrong, but i THINK the upper and lower are calculated by taking the middle band, then adding/subtracting the difference in size from previous trades to the power of the std dev, so if your std dev is 2, then your next value is something like {[current candle value]- [previous candle]} to the power of 2.

I've seen a guyuse it with amazing sucess. he used 1.25 I think it then represents around 65% of all trade volume for that period.

**Comment by kan-il** [comment]
> Standard Deviations are a 'parabolic' style of calculation, basically, you're multiplying the speed of the trend by the SD.
> 
> I THINK I might be wrong, but i THINK the upper and lower are calculated by taking the middle band, then adding/subtracting the difference in size from previous trades to the power of the std dev, so if your std dev is 2, then your next value is something like {[current candle value]- [previous candle]} to the power of 2.
> 
> I've seen a guyuse it with amazing sucess. he used 1.25 I think it then represents around 65% of all trade volume for that period.
> 
> think of it as a bell curve that moves dynamically with your trend line, the standard deviation tells it how aggressively to move.
> ![image](https://user-images.githubusercontent.com/49715381/62525989-7b97f800-b88c-11e9-846d-17c8fb36e26d.png)
> 
> so 13.6 + 34.1 = 47.7
> 47.7 x2 = 95.4
> 
> so basically a BB with deviation 2 should capture 95.4% of all trade volume

Thank you, this helped me a lot
