### ISSUE TITLE
Bot showcase Real account.

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1826]
https://www.youtube.com/channel/UCHuFagPAEDTRZOF04e5RgBQ/live

**Comment by Batekmax** [comment]
Does he sell it or what?

**Comment by hotmatrixx** [comment]
> 
> 
> Does he sell it or what?

he's planning to. if you open up that link , then upen up the 'read more' on the YT channel you can see him trying to sell you his bot 'once it releases'
