### ISSUE TITLE
Problem to create list

### ISSUE THREAD

**Issue by rasjohse** [binary-com/binary-bot#1829]
hello mr, I need help to create a list of an individual value, I managed to create that list, but it does not save the previous ones but it repeats the same input data in the whole list, I would be grateful if you can direct me on how to create the list, thanks 

@binary-ex-machina @lasaidhari @aaron-binary @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost

![REPEAT-IN-LIST](https://user-images.githubusercontent.com/33709714/62636503-a83d2580-b907-11e9-978e-d85427d9b61a.png)

**Comment by lasaidhari** [comment]
send file xml

**Comment by hotmatrixx** [comment]
it's not really possible to see what's going wrong, as you have too many variables in your list set up, and importantly, they are included in calculations. if any of them are incorrect, the whole thing will go bad.

lists are limited to 1000 entries, so bear that in mind.

I'm wondering if the in list 
LISTEYE "insert at" "first"
should be 
LISTEYE "insert at" "_S"

**Comment by gabriellanzer** [comment]
As far as I know the ranges are from 1 to N, not 0 to N-1 (as in C++)... This might be the issue.
