### ISSUE TITLE
Need help with binary bot "Open Position when the second is 58"

### ISSUE THREAD

**Issue by BinaryBiksu** [binary-com/binary-bot#1832]
Please help with my problem
I want to create binary bot with logic
When the second is exactly 58, the bot open position
I can't find the right function for this. I've used SecondApoch ÷ 58, but it didn't work
Thx for the help

**Comment by lasaidhari** [comment]
![seconds](https://user-images.githubusercontent.com/34808023/62758875-8e225500-ba77-11e9-8dbc-8a9127b1db89.gif)

**Comment by BinaryBiksu** [comment]
Thx for the answer, i'll try

**Comment by BinaryBiksu** [comment]
Thx for the answer, its work....
