### ISSUE TITLE
help add a third block for sale in the bot and improve the bot

### ISSUE THREAD

**Issue by Batekmax** [binary-com/binary-bot#1835]
[Rsi + boll 2.zip](https://github.com/binary-com/binary-bot/files/3490169/Rsi.%2B.boll.2.zip)
help add a third block to sell the contract in case the loss is 50% of the bid amount. For example, the bid amount is $ 1 if the forecast goes the other way and the future loss is 50% -0.50 $ to sell the contract! Further down the martin x2, that is, $ 2 and the same as with the previous bid, only change the duration of the contract instead of 10 ticks for 40 seconds. Help create please, maybe there will be more ideas for improvement.

**Comment by Batekmax** [comment]
after $ 1, then go up Martin x2. mixed up in the text

**Comment by hotmatrixx** [comment]
interesting, thanks for sharing! I'm trying to figure out how it all works, but I'm too tired. :(

would this do it? it's what I 'think' you wanted?

![image](https://user-images.githubusercontent.com/49715381/63094559-e815a400-bfbc-11e9-8051-e0bd7c13bfc5.png)

**Comment by Batekmax** [comment]
it seems yes, thanks for the help
