### ISSUE TITLE
Binary Bot for sale

### ISSUE THREAD

**Issue by dushn** [binary-com/binary-bot#1838]
https://www.youtube.com/watch?v=RZ2HJFro5OU
https://www.youtube.com/watch?v=9jJOsCS6C3k&t=25s
need idea about price?
i think this is more valuable.. just need  1 company .. or 1 person ...

**Comment by eonuoha30** [comment]
Bot sales isn't allowed

If you don't wanna share, keep it to yourself

**Comment by eonuoha30** [comment]
...moreover, there's nothing special about the bot.

OVER 3 will always have a 60% win rate on the long run and that's exactly what u had in d video.

All your stakes where on 'Overs'.

and a stake plan that still had up to 4 straight loss.

On the Long run, you'll experience longer lose streaks such as 5, 6 or 7

**Comment by dushn** [comment]
Thanks for comment
