### ISSUE TITLE
Smart martingale

### ISSUE THREAD

**Issue by syed18** [binary-com/binary-bot#1839]
Can anyone send me the block of smart martingale like this 0.35, 0.40, 0.81, 1.67, 3.32, 6.60..........

**Comment by ceakuk** [comment]
i charge 5$

**Comment by hotmatrixx** [comment]
> 
> 
> i charge 5$

oh.

**Comment by hotmatrixx** [comment]
> 
> 
> Can anyone send me the block of smart martingale like this 0.35, 0.40, 0.81, 1.67, 3.32, 6.60..........

BinaryExMachina made one that does soemthing quite like this, using a sequential list not so long ago.

maybe have a hunt through his previous posts and you'll find it?

it was really beatifully coded.

**Comment by sinung21** [comment]
i can do it

**Comment by syed18** [comment]
@sinung21 please send me your email , i have a bot and i want to add this martingale system.

**Comment by navneetsinh** [comment]
@syed18 try this
![Opera Snapshot_2019-08-16_130937_bot binary com](https://user-images.githubusercontent.com/42480287/63151526-53945b80-c027-11e9-858e-94e88ed42103.png)

**Comment by syed18** [comment]
Hey thanks... Can i have your email? I want to add this on my bot, i don't know how to do

**Comment by navneetsinh** [comment]
> Hey thanks... Can i have your email? I want to add this on my bot, i don't know how to do

navneetsinhsb@gmail.com

**Comment by syed18** [comment]
@navneetsinh check your email

**Comment by navneetsinh** [comment]
> @navneetsinh check your email

updated file sent to your mail,

**Comment by binary-ex-machina** [comment]
@syed18 i'm seeing you post here asking for people build the bots for you (i did several times), then you ask for .xml. Looks like you get bots anywhere, want to modify them but don't want to learn how to do it. I advise you to learn at least how to use the mouse to copy what you can find here in this repository. Lazy people always stay behind.

**Comment by T3LL3Z** [comment]
Can anyone send me the block of smart martingale like this 0.35, 0.40, 0.81, 1.67, 3.32, 6.60 help me please
