### ISSUE TITLE
Martingale %

### ISSUE THREAD

**Issue by jonathancosta746** [binary-com/binary-bot#184]
how can i change the % of martingale trades? The bot automatically change the next trade to 100% (1<2<4...). I want change for exemple to (1<2.3<5.7...)

**Comment by felixhuy** [comment]
you only expand Martingale Core Functionality and change number you want
![capture](https://cloud.githubusercontent.com/assets/26194420/24086550/dbbece94-0d43-11e7-89a1-1f154be12bb8.PNG)

**Comment by jonathancosta746** [comment]
I finally got to adjust the value of the martingale when the robot loses. But now the problem is that the robot does martingale too when he wins. How can I do it when the robot wins it back to the value of the initial bets?

**Comment by felixhuy** [comment]
Add if result loss -> marti.
![1](https://cloud.githubusercontent.com/assets/26194420/24130651/77b231fa-0e1c-11e7-8d0a-2c8f5d070856.PNG)

**Comment by okovalov** [comment]
@jonathancosta746 you need to use extra variables which would store martingale trades count and you also would need to add an extra if condition which would rely on that variable (s)

**Comment by jonathancosta746** [comment]
Thanks for the suport guys, the bot is functional

**Comment by jonathancosta746** [comment]
![bot](https://cloud.githubusercontent.com/assets/26524921/24219346/32338322-0f25-11e7-8eb9-c942cbf03c10.png)

If anyone needs...
