### ISSUE TITLE
please, assist me on this

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1840]
![IMG_20190814_135928](https://user-images.githubusercontent.com/52554096/63023914-a211f080-be95-11e9-82a0-fe5f6c076e2e.jpg)

I explained how the bot  works on the picture above.

I've been working on making the bot for some weeks but couldn't get it done (I'm still a learner).

Please, i want to start live trading with something similar to that as soon as possible.

Please, help me make the bot

**Comment by ceakuk** [comment]
@eonuoha30 
I have done these strategies and confirmed what I already knew that  they can't work in the long run.
every over/under has a probability of occuring and unfortunatly the reward is   always lower than the probability of occurance.

example  with MATCHDIFF you win 90 trades and loose 10 you get 0.09*90 =8$ but loose 10$ , net =-2$

unless you have some smart wy to increase your stake its doomed to fail.
also just increasing a fixed a mount every time you loose will fail

**Comment by ceakuk** [comment]
law of random numbers is that they are radom. theoretically, there is nothing to stop the last digit to be 0 or any other number 100 consecutive times

**Comment by eonuoha30** [comment]
just help me out on the bot.
I can deal with the rest

**Comment by ceakuk** [comment]
ok. ill do it. in 1 hour when i get home

**Comment by eonuoha30** [comment]
...OK, Thanks a lot.

Also, if I want to learn how to make bots, where will I get the tutorials?

I already know the basics 

and I also visit this website up to 20 times a day.

But once I see what u guys are doing, I just feel like you guys are gurus from another planet.

I wish to learn

**Comment by ceakuk** [comment]
bot is done. let  me see it trade for 30 minutes then i send it.
creating any strategy  with blocky is very esay. making it  profitable is the pandora's box.
binary.com bot is nothing new. its just using google blocky.
Take a look at a few blocky examples to help you build the logic and everything will fall in place
[https://developers.google.com/blockly/]
if you win some $$$$$$$ please  share with me

**Comment by ceakuk** [comment]
google blocky is here
https://developers.google.com/blockly/

**Comment by ceakuk** [comment]
the 1st flaw in the strategy: it takes just 3 steps to hit dead end. that is:
step A: loose over 3,
step B: loose over 4 and
step C:  loose over1
maybe you shoul go to next step if you loose 1 out of the 3 in that stage but not one loss goes to next stage
![strategy](https://user-images.githubusercontent.com/43122491/63047500-dce74900-bed4-11e9-8169-66434fa88500.PNG)

**Comment by ceakuk** [comment]
here is the code
i made the logics longer for you to understand better. you can just compress them if you want the codes to be lighter for the browser
[binary-bot strategy.zip](https://github.com/binary-com/binary-bot/files/3502835/binary-bot.strategy.zip)

**Comment by eonuoha30** [comment]
Thanks for your comments and quick aid.

Actually, what I sent you is not in anyway, the strategy I was working on.

The stakes are also false.

I only needed those lines so that from there, I can build what's on my mind.

I usually get this constant weird feeling that binary guys are here and can alter stuffs if you upload a method that finally works.

Anyway, thanks. I still hv a lot to do on that file.

**Comment by ceakuk** [comment]
@eonuoha30 
that doesn't sound nice. my time is valuable so if i help you, better give me the full strategy. 
I once  said i charge 5$ to help but @binary-ex-machina  talked bad at me for charging. now i see why i don't want to help for free.

and so what if other people know your strategy. if it works, you both win money and if it doesn't then you  either help each other fix it or abandon it.

anyway have a nice day with your master strategy

**Comment by binary-ex-machina** [comment]
@ceakuk you are not helping if you charge, you are working for money, which is totally fine in my opinion, depending where you offer your job. I think here is a place for people to learn about creating the strategies, not a "get your strategy for free" thing. Give a start to learn, a maybe just a few blocks can help the player develop his strategy, but make complex things over and over again to the same people is not fair, you can't waste time for lazy people.

**Comment by ceakuk** [comment]
@binary-ex-machina 
i just helped this guy @eonuoha30  only for him to tell me  he was wasting my time

**Comment by binary-ex-machina** [comment]
@ceakuk i found several like this here over the last years, but think that other person can find this helpful in some way.

**Comment by eonuoha30** [comment]
...honestly, I appreciate your effort.

Sharing the file to you isn't a problem either.

So, generally , there's no problem sir.

**Comment by hotmatrixx** [comment]
@ceakuk he didn't say he was wasting your time.
he said that he wanted to basic structure of how to write the bot, so that he could use it as a skeleton to create his 'true' strategy.

you were helpful to him.

I must give you credit for NOT asking for money this time. Just remember, if you don't want to be helpful, you don't actually have to participate in these forums.

however, I think you did great. Keep it up, @ceakuk !!!
