### ISSUE TITLE
Pls help...need worm bot

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#1842]
Worm will be blue doth(high position),affter that move  2 ticks down and affter that 1 tick up....so open FALL 

Put martingle and Take Profit

Thats it!!!
Thanks!!!

**Comment by hotmatrixx** [comment]
that makes exactly not any sense whatsoever.
sorry. I'm sure it sounds easy to make, but I don't really understand.

**Comment by poroinika** [comment]
Worm is blue,make one tick down....second tick down agine and 3-rd tick is UP......so open FALL. 

OR:

Worm is blue go down for next 2-3-4-5.....ticks(no metter how),but when it comes tick UP....open FALL

**Comment by poroinika** [comment]
That is the strategy:

https://m.youtube.com/watch?feature=youtu.be&v=H1AUK2JyUTg

**Comment by poroinika** [comment]
@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by binary-ex-machina** [comment]
@poroinika you can do like this below. This is another "Worm Pattern" myth, there is a thousand variations. In case you want to save time testing and building this, change the strategy.

![image](https://user-images.githubusercontent.com/34610787/63193158-1f2e9880-c043-11e9-98c3-eeacb91a4173.png)

**Comment by poroinika** [comment]
can anyone send .xml with martingle?

**Comment by abelojo11** [comment]
@binary-ex-machina please i need help with my robot, it is not respecting the acceptable loss command. can you help me please? want it to stop ones it gets to acceptable loss

**Comment by abelojo11** [comment]
please i need help with my robot, it is not respecting the acceptable loss command. can someone help me please? want it to stop one it gets to acceptable loss
