### ISSUE TITLE
Need Your Help ASAP

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#1844]
Hi, I found this good bot that runs very great
but the bot need only to be run when it's uptrending.
I want the bot to analyze the market itself without me having to check every time when it should be running or when it's not.
Pls, Help Me. I don't really know how to code.

Here's the bot, Change .txt to .xml
[Binary-bot.txt](https://github.com/binary-com/binary-bot/files/3506478/Binary-bot.txt)

**Comment by lasaidhari** [comment]
what indicators do you usually use to determine a rising trendwhat indicators do you usually use to determine a rising trend

**Comment by Adammodex** [comment]
I use the EMA indicator.
EMA 5 & EMA 12
But If There's Something Better than that that you can advice me with, Please Don't hesitate to Use It.

**Comment by Adammodex** [comment]
@lasaidhari 
I use the EMA indicator.
EMA 5 & EMA 12
But If There's Something Better than that that you can advice me with, Please Don't hesitate to Use It.

**Comment by Adammodex** [comment]
@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by binary-ex-machina** [comment]
@Adammodex you can't avoid trading in other market moments besides Uptrend. Imagine if that was possible? trend with strategies that are good in uptrend, exclusively on uptrend. 

Also your bot is very far from "very great" as you put. It's a completely mess on the blocks and a lot of useless processing, making it very slow. It has a big problem that is changing the strategy based on number of losses, this will go bad at some point, really bad. Try to clean this script, the analysis and the strategy as a whole.

Also you are using 10min duration, using the indicators with ticks input? so you analyze micro movements and take 10min durations? it's like cleaning kitchen, expecting that all house will be cleaned as well. Change to candles analyzing 1min or more and remove the loss verification on the filter. A bot without target profit and stop loss will always explode accounts, no doubt on that.

**Comment by Adammodex** [comment]
@binary-ex-machina 
Okay sir, Thank You Very Much
