### ISSUE TITLE
Tell me some bot for a deposit of $ 1000,1500

### ISSUE THREAD

**Issue by Batekmax** [binary-com/binary-bot#1845]

**Comment by Nimlemon** [comment]
https://www.youtube.com/channel/UCWtzMx6h3atVHQt-GRtBTDw
ลองอันนี้

**Comment by iqbinary** [comment]
https://www.youtube.com/c/iqbinary

**Comment by Nimlemon** [comment]
> https://www.youtube.com/c/iqbinary

IQBINARY YOUR JUST FAKE YOUTUBER.. RECORD RECORD RECORD AGAIN PUT IN TO YOUTUBE>>>
YOUR JUST SCREEN RECORDER>>>

**Comment by nextnaro** [comment]
Waiting my bot?

**Comment by dushn** [comment]
i am planing sale my bot to 500 usd per person.... if anyone interest me please contact.

**Comment by Eshhh** [comment]
@dushn that's funny dude, people in their right minds would never buy any bot for $500, including yours.
