### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by freedonone** [binary-com/binary-bot#1846]
Please I need help with a block(s) or bot that can get the 2nd to the lowest frequent digit and 2nd to the highest frequent digit.

for example in the image below I set it to **V10** and **25ticks**,
2nd to lowest frequent digit is **7** and 
2nd to highest frequent digit which is **8** 

while the lowest frequent is **3** and
highest frequent is **4**

![Capture1](https://user-images.githubusercontent.com/54136867/63165971-e8498a00-c024-11e9-8955-2ae5dbce285c.PNG)

thanks.

**Comment by lasaidhari** [comment]
https://github.com/Fruitfella/ROBOT-binary

**Comment by freedonone** [comment]
> https://github.com/Fruitfella/ROBOT-binary

I already know about the bot in that link, but the bot only gets the least and most frequent, I want the one that can get the 2nd, 3rd, 4th, etc to the lowest (least) frequent and 2nd, 3rd, 4th, etc to the highest (most) frequent.
thanks

**Comment by waltergrant** [comment]
check it, plz
[bot-min-max-listDigits.txt](https://github.com/binary-com/binary-bot/files/3551761/bot-min-max-listDigits.txt)
