### ISSUE TITLE
Need Help Writing this code.

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#1849]
Hi,
Can You Please Write this code For me:
> If The Trend Is Above 20 Moving Average, And EMA 5 Crossed EMA 12 For More Than 5 Min
    - Then Buy Rise (1-30 min candles)
> If The Trend Is Above 50 Moving Average, And EMA 5 Crossed EMA 12 For More Than 5 Min
    - Then Buy Rise (1-30 min candles)
> If The Trend Is Above 200 Moving Average, And EMA 5 Crossed EMA 12 For More Than 
1 Hour
    - Then Buy Rise (1 hour to 1-day candles)

Assets: Whatever assets You Would Try This Code On.

Now Please When Writing the Code, Each Code Have to be in a separated File.
  Thanks !!! 👍💯 

Platform: binary.bot
Indicator Used: Moving Average (MA) - EMA 

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

Thank You Guys, For Your Precious Time.

**Comment by binary-ex-machina** [comment]
@Adammodex you can do like this image below. Just change the duration and the SMA period for each idea you have.

![image](https://user-images.githubusercontent.com/34610787/63213568-4d17e980-c0e4-11e9-877a-650332c072a1.png)

**Comment by Adammodex** [comment]
Alright, Thank You Sir. 
Let Me Figure This Out! 
And I'll Be Back If I Have Any Problems.

**Comment by Adammodex** [comment]
Here Sir, I Copied Your Proposition. and It's Really Good Except That The Bot never Buys Any Contract !

Here You can See My Copy:
![image](https://user-images.githubusercontent.com/54149729/63215437-4017ec00-c11e-11e9-8633-ad836b6867d6.png)

And Here You Can See That The Trend Is above 20 SMA and 5 EMA have Crossed 12 EMA. But The Bot Still Didn't make Any Contract.

![image](https://user-images.githubusercontent.com/54149729/63215485-07c4dd80-c11f-11e9-9c21-51a7e0d7796a.png)
![image](https://user-images.githubusercontent.com/54149729/63215498-3a6ed600-c11f-11e9-97be-cd2862738f87.png)

Can You Please Help Me.

**Comment by binary-ex-machina** [comment]
@Adammodex why did you use SMA array? In the image i sent i used normal SMA

**Comment by Adammodex** [comment]
I fixed It, Let Me See If There's going to be a difference.
![image](https://user-images.githubusercontent.com/54149729/63215799-bec35800-c123-11e9-8e7f-c6169ba0ab9c.png)

**Comment by Adammodex** [comment]
Still Nothing Sir (@binary-ex-machina)

![image](https://user-images.githubusercontent.com/54149729/63217409-0951ce00-c13e-11e9-9f3b-3fe96837f3e7.png)

The Bot Was Runing For A very Long Period Of Time, But Still Nothing. 
Please Help Me So  I can Fix This.

**Comment by binary-ex-machina** [comment]
Here is working normally on 1min time frame

![image](https://user-images.githubusercontent.com/34610787/63218101-b241fe00-c129-11e9-89d8-8d79f21e7d35.png)

**Comment by Adammodex** [comment]
Okay, I'm Gonna Try to reduce the time frame and see what's going to happen.

**Comment by Adammodex** [comment]
Hi, 
After Editing The Bot And doing Some Retouch. It Works Fine.
But Here's A list Of things That I don't Want To Happen:

Text and Lines Marked In red are what I'm Talking About.

![pp](https://user-images.githubusercontent.com/54149729/63225609-84ac9180-c1c9-11e9-8d62-3fb55c7a30bb.jpg)

In Conclusion, I Only Want the bot to trade one time after all of the indicators match with The Configuration.
If Result Is Win, Then Wait For The Next Trend To Show Up
If Result Is Loss, Trade Again Until Result Is Win

Thank's.

@binary-ex-machina

**Comment by binary-ex-machina** [comment]
@Adammodex here is an example of how you can implement a kind of recovery logic. When a loss occur, it will trade again without any filter. When a win occur, will trade only if the filter conditions met

![image](https://user-images.githubusercontent.com/34610787/63225830-35efff00-c1ab-11e9-980a-9cb31994f29d.png)

**Comment by Adammodex** [comment]
Not Sure How To Implement it here Sir,

![image](https://user-images.githubusercontent.com/54149729/63226787-8597f000-c1d6-11e9-987c-fee038567083.png)

May You Help Me?
