### ISSUE TITLE
Please Help Me create a HMA bot.

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1851]
Can binary bots be created?
HMA 12

![Capture](https://user-images.githubusercontent.com/51996252/63221313-7ce8ef00-c1c1-11e9-842e-8d4b2552f6a3.PNG)

**Comment by binary-ex-machina** [comment]
i have created the HMA indicator for binary bot, you can check here https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#hull-ma

**Comment by Herotaiko** [comment]
@binary-ex-machina 
Is it possible for the bot to run both call and put, As shown in the picture?

**Comment by Herotaiko** [comment]
@binary-ex-machina 
Sorry, I can't download from your link.

**Comment by binary-ex-machina** [comment]
you can download the indicator here https://raw.githubusercontent.com/binary-ex-machina/binary.com-bot/master/indicators/hull_moving_average/hullma.xml

as well you can make comparison like this below

![image](https://user-images.githubusercontent.com/34610787/63615604-23ffc900-c5bc-11e9-8a19-1085eb4b0252.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina 


 Sorry to bother you but I can't download Indicator. If not bothering, is there any other way to download it?
![ss](https://user-images.githubusercontent.com/51996252/63631723-8658d800-c655-11e9-9deb-b28c3f1ce45f.PNG)


Thank you for your help

**Comment by binary-ex-machina** [comment]
try to save the page when you open, like ctrl + s (cmd + s) it will popup a window and you will see that it will download a .xml

**Comment by Herotaiko** [comment]
@binary-ex-machina I really want to thank you for your help.
