### ISSUE TITLE
digital differ bot help

### ISSUE THREAD

**Issue by Nimlemon** [binary-com/binary-bot#1854]
its digital differ bot . 
if i build watch and perches block some strategy it going to 1 st block 
If watch and purchased indicate 3 in differ trade and same should indicate in predictions 3
If watch and purchased indicate 1 in differ trade and same should indicate in predictions 1
how to create that

**Comment by Nimlemon** [comment]
![343](https://user-images.githubusercontent.com/54200960/63275762-b869e300-c2bf-11e9-8948-5d7176bfbf21.jpg)
like this

**Comment by Nimlemon** [comment]
anyone??

**Comment by lasaidhari** [comment]
What do you mean.

**Comment by Nimlemon** [comment]
2nd block signal prect trade .

**Comment by freedonone** [comment]
> 2nd block signal predict trade .
> if 2n block result most number 1 then 1 predict
> prediction was taken watch and purches result

must it be square root, because square root of any number is fixed, so the bot will not work

or do you mean average of sum these numbers circled below

![saved](https://user-images.githubusercontent.com/54136867/63346846-c6fedb80-c34d-11e9-9bd5-574be9610239.jpg)

**Comment by Nimlemon** [comment]
no this is example... if watch and purches logic is 4 predictin is 4 different
id watchand purches logic is 7 prediction is 7 differ
like 
this is example... i want to know how to set this

**Comment by Nimlemon** [comment]
yes....

**Comment by Nimlemon** [comment]
watch and purches multiple logic and random nmbers .. thats why i asked it

**Comment by Nimlemon** [comment]
signal is 4 trade4 differ
signal is 7 trade 7 differ
signal is 3 trade 3 differ

**Comment by freedonone** [comment]
the issue I have been having with such bot is that it gets confused most times and picks randomly from the prediction numbers, so what I do is I set a bot for a particular outcome at a time, so it will ignore signal 4 an signal 7 and consider signal 3 and trade 3, after which it will ignore signal 4 and signal 3 and consider signal 7 and trade 7, etc

I will also appreciate anyone to clear this issue for me......

but here is the one you demanded for, like I said expect some confusing outcomes.....

![work](https://user-images.githubusercontent.com/54136867/63352034-40033080-c358-11e9-948e-56cad5f927ce.PNG)
[work.txt](https://github.com/binary-com/binary-bot/files/3520890/work.txt)



rename .txt to .xml

**Comment by Nimlemon** [comment]
thank you very much... ill try this... and i let u know

**Comment by Nimlemon** [comment]
thank you very much... @freedonone ... its working... thank you

**Comment by lasaidhari** [comment]
using Block 2 to change peridiction will not work. because changes will occur after win or lose.
![work](https://user-images.githubusercontent.com/34808023/63384964-eae70f00-c397-11e9-91a4-4f96b149eefe.jpg)

**Comment by ricothenfx** [comment]
Yap you cannot set the prediction on block 2. You must set the prediction on block 1 and 4. You can use combination of looping and "run after (seconds):
