### ISSUE TITLE
[bug] unable to stop showing buy successed and contract never close

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1856]
![Screenshot_2019-08-21-13-02-27](https://user-images.githubusercontent.com/31925501/63405186-815b1500-c418-11e9-829f-862a67d2c640.jpeg)

**Comment by aaron-binary** [comment]
Hey @nextnaro,

Could you describe what's happening in the screenshot?

Regards,
Aaron

**Comment by nextnaro** [comment]
@aaron-binary 

Time on GMT Wed, Aug 21, 2019 5:02 am as captured 
My VPS time zone is -7  22:02
Bot try to buy contract More than 1 hour  @ 20:58 ~  GMT 03:58  in the  capture
![image](https://user-images.githubusercontent.com/31925501/63493277-d3ba3580-c4ed-11e9-851d-29a7a1b0051b.png)

showing by success on ID *380888 But contract never expire and unable to stop BOT show "stoping". it wont stop need to refresh page.

**Comment by nextnaro** [comment]
Again pending....... contract not close.
![Screenshot_2019-08-22-21-58-55](https://user-images.githubusercontent.com/31925501/63521349-d9813c80-c528-11e9-9ad3-817255572848.jpeg)
When try to stop. Stoping............but not stop.
![Screenshot_2019-08-22-21-59-37](https://user-images.githubusercontent.com/31925501/63521352-d9813c80-c528-11e9-8e90-12b724adf726.jpeg)

**Comment by hotmatrixx** [comment]
yep I've had that happen occasionally. not for a while, though.
