### ISSUE TITLE
about hacking basics

### ISSUE THREAD

**Issue by annireddy777** [binary-com/binary-bot#1859]

**Comment by annireddy777** [comment]
i want to learn hacking from basics plz help me

**Comment by binary-ex-machina** [comment]
Hacking? are you serious? admin didn't even read the title?

**Comment by hotmatrixx** [comment]
hey, buddy.
[Read A Book](https://www.amazon.com/Learn-Ethical-Hacking-Scratch-penetration/dp/1788622057/ref=sr_1_2?keywords=ethical+hacking&qid=1566545752&s=gateway&sr=8-2)
