### ISSUE TITLE
Change when result lose

### ISSUE THREAD

**Issue by felixhuy** [binary-com/binary-bot#186]
Hi Amin,

Can you help me ?
I want if lose 1 times it wont marti, and lose >= 2 times it will marti. i tried but it's not run, Can you fix for me, please ?
![capture](https://cloud.githubusercontent.com/assets/26194420/24179567/74ca9d80-0ee2-11e7-9282-4e4cb43d4975.PNG)

**Comment by aminmarashi** [comment]
I guess it's the same as #170

**Comment by felixhuy** [comment]
but it's not right

2017-03-23 9:11 GMT+07:00 Amin Marashi <notifications@github.com>:

**Comment by felixhuy** [comment]
@aminmarashi But it's not right
![1](https://cloud.githubusercontent.com/assets/26194420/24242895/d5510176-0feb-11e7-82fd-69012ea340f6.PNG)

**Comment by delonbh** [comment]
IF RESULT = WIN
SET NUM OF LOSS =0
set this at the beggining of (4) Block.

You need to clear the counter when you win the trade ou it will mart every loss.

**Comment by felixhuy** [comment]
@delonbh ok thank you! Done
