### ISSUE TITLE
Statistics and bot testing

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#1860]
Hello how are you, I would like to know if it is possible to do back testing of strategies of any bot of binary.com. I would like to know if you can do something similar to test a forex ea or something similar. I need a statistic of many operations no matter if they are 10, 11, 12 etc. consecutive martingale of losses, from there I found the way to operate only when the conditions exist but to be effective I need a solid statistics of loss martingale. Best regards

**Comment by binary-ex-machina** [comment]
You can use the cli command to get the ticks/candles and apply your strategy. It needs programming knowledge https://github.com/binary-com/binary-bot#running-the-cli-command

**Comment by martinrf79** [comment]
Thanks for your reply. Unfortunately I know very little about programming, by chance there is some video or tutorial on how to do it. or where can I get more information on this subject.
