### ISSUE TITLE
Please help me improve the 4th block.

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1861]
I want to give when losing at a price that exceeds 7 or more, To trade at a new starting price from this block

![Capturey](https://user-images.githubusercontent.com/51996252/63491569-bbdcb480-c4e1-11e9-80b3-9aec9d3a6437.PNG)

**Comment by ricothenfx** [comment]
Can you try explain clearly ? What do you want to make ?

**Comment by Herotaiko** [comment]
When trading, losing more than or equal to 7, trading at 0.35 again.

Ps. Sorry that my English is bad

**Comment by ricothenfx** [comment]
You can use code something like this :
IF [CONTRACT DETAIL PROFIT] <= -7
SET STAKE TO 0.35
...

**Comment by Herotaiko** [comment]
Please show me how to create a blog.

**Comment by hotmatrixx** [comment]
this line is wrong. on a losing trade, the number 'contract detail:profit' is zero.
so you're chainging your amount lost by negative zero.

that should be 'change amountlost by negative <stake>

![image](https://user-images.githubusercontent.com/49715381/63576705-dd709580-c5e0-11e9-9bfe-45006c804a9c.png)

**Comment by Herotaiko** [comment]
@hotmatrixx 
If I understand correctly, should I do this?
![s](https://user-images.githubusercontent.com/51996252/63577087-d1241280-c5b7-11e9-8e4f-0e0a8bf515a7.PNG)

**Comment by Herotaiko** [comment]
> I want to give when losing at a price that exceeds 7 or more, To trade at a new starting price from this block
> 
> ![Capturey](https://user-images.githubusercontent.com/51996252/63491569-bbdcb480-c4e1-11e9-80b3-9aec9d3a6437.PNG)

When trading, losing more than or equal to 7, trading at 0.35 again.

**Comment by hotmatrixx** [comment]
I think i have a bot that does something similar, but works a little differently.
here, I have added a screenshot of how mine works, i think its a bit simpler to follow than yours, and hopefully you can see a way that it might help you out.
i change my stake based on my inital stake, plus amount lost. so if i set my amount lost to zero, then my stake would reset to its initial.

you might want to make that line reset your stake to your initial as well as reset your amount lost
![image](https://user-images.githubusercontent.com/49715381/63630192-4bae6a00-c66c-11e9-879e-90868d4693bf.png)

**Comment by Herotaiko** [comment]
> I think i have a bot that does something similar, but works a little differently.
> here, I have added a screenshot of how mine works, i think its a bit simpler to follow than yours, and hopefully you can see a way that it might help you out.
> i change my stake based on my inital stake, plus amount lost. so if i set my amount lost to zero, then my stake would reset to its initial.
> 
> you might want to make that line reset your stake to your initial as well as reset your amount lost
> ![image](https://user-images.githubusercontent.com/49715381/63630192-4bae6a00-c66c-11e9-879e-90868d4693bf.png)

@hotmatrixx Thanks for the advice, I'll try to do it.
