### ISSUE TITLE
Need help pls..

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#1865]
![Screenshot_20190823-095023_Samsung Internet](https://user-images.githubusercontent.com/36769713/63573172-51814e00-c58d-11e9-89c4-7ffde69f3c5e.jpg)
Whant bot open if the last 3 numbers are from 0-100 like on the picture is x.xxx.024

Thats all!!!
Thanks!!!

**Comment by hotmatrixx** [comment]
that makes...
no sense at all.

**Comment by poroinika** [comment]
Can you do that or not?

**Comment by lasaidhari** [comment]
this is for rise fall or digits. The following details

**Comment by poroinika** [comment]
Rise/Fall

**Comment by lasaidhari** [comment]
please add / change according to your wishes
[get get  3 from end.zip](https://github.com/binary-com/binary-bot/files/3533908/get.get.3.from.end.zip)

**Comment by poroinika** [comment]
@lasaidhari yes man thats it what i whant but can you put and martingle and stop loss and Take profit?

**Comment by lasaidhari** [comment]
I see that you have been using this forum for a long time ... you should be able to make martingale.

**Comment by poroinika** [comment]
But I cant......

**Comment by hotmatrixx** [comment]
> 
> 
> But I cant......

can you even write a basic bot?

**Comment by poroinika** [comment]
> > But I cant......
> 
> can you even write a basic bot?

what is your problem?
