### ISSUE TITLE
[Feature Request] <Constrain> QoL improvement

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1866]
Hi, team!

regarding the Constrain blocky chain, I'd like to suggest that it works really well in some cases but there are some outlying cases where it needs a second 'container' I'll 'photoshop' up with Paint :)

basically, It works fine for "Set" a variable, bot not for "Change" a variable

1. works well here.
2. this is fine if I only want to constrain my results, but not if I want to constrain my original variable, I'm forced to add a second line
3. my 'photoshop skillz' version of a new constrain blaock

after doing this I catually see the issue with this, what I'm currently doing (2) is almost as long as my proposed solution. Hmmm. More thinking required.

![image](https://user-images.githubusercontent.com/49715381/63574539-15290e80-c5dc-11e9-9a17-549fea66c784.png)

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Hmm, could you explain why constrain wouldn't work with the `Change x by`-block? The value returned from the `Change x by`-block will add onto `x`'s value, so in order to `constrain` the value of `x` you would first calculate the outcome of `x` + your added value, and then use the `Set x to`-block in combination with the `constrain`-block to set `x`'s value.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
> 
> 
> Hey @hotmatrixx,
> 
> Hmm, could you explain why constrain wouldn't work with the `Change x by`-block? The value returned from the `Change x by`-block will add onto `x`'s value, so in order to `constrain` the value of `x` you would first calculate the outcome of `x` + your added value, and then use the `Set x to`-block in combination with the `constrain`-block to set `x`'s value.
> 
> Regards,
> Aaron

Yes, that achieves the same outcome - although I think i do it the other way around - but in all honesty, I'm just being lazy and I feel it should be an all-in-one solution. There are much bigger and more important things that you could be working on (like colour-coded REMarks :) ) So in hindsight I'll close this one for now.

Thanks for replying!
