### ISSUE TITLE
[Feature Request] Telegram

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1867]
I haven't used Telegram yet, however with my latest bot being... near complete I've realised it has a weakness.... a bug. sadly I do not wish to share my current iteration, however I may break it down into a simpler version that still replicates the bug later.

however, it's helped me realize an important weakness with Telegram, one that I think would be a really useful feature to add; the ability to notify me on a serious error.

I've set the bot to stop on error, for now, but if I am away from it, I have no idea if it's stopped due to an error. Telegram could fill this role, but I cannot see a method to notify myself on a bot 'failure'.

specifically I'm referring to these lines:
![image](https://user-images.githubusercontent.com/49715381/63574945-098a1780-c5dd-11e9-90f5-52b5ea450227.png)

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

This is a good idea and we've discussed something similar like this internally. We won't add in the very near future, but later along the line, this would be a nice feature to have.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
Thanks at least we know what's up.
I'll close this for now, but it would be nice if you can remember to add the feature to the roadmap (is there even a roadmap that we can access?)
