### ISSUE TITLE
last digit not same

### ISSUE THREAD

**Issue by baintalu** [binary-com/binary-bot#1871]
![Screenshot_28](https://user-images.githubusercontent.com/16547446/63659241-f9438980-c7e2-11e9-99ee-757b6fdc7504.png)

**Comment by aaron-binary** [comment]
Hey @baintalu,

We tried to replicate this issue, however, the values seem to be correct on our end. Could you share with us your strategy? You may upload it to https://gist.github.com.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
I've seen the bot do wierd things if you don't refresh the page for a few days. Don't use the in-bot refresh, but the Browser's Page Refresh. Make sure to remember to save your strategy first !!!

It might have frozen or bugged out or locked out a value somewhere.
it's working fine for me.

![image](https://user-images.githubusercontent.com/49715381/63723716-4b9bad80-c8aa-11e9-92c0-738d0d823382.png)
