### ISSUE TITLE
installing Bot

### ISSUE THREAD

**Issue by phutannguyen** [binary-com/binary-bot#1872]
Hell, Good day.
I want to install a bin bin to run. But I am a new trader who does not understand much about installing Bot. Please help with detailed instructions so that I can install the correct location (folder) Help me to control in binanary. com.
Best regard
Thank You.
Tinh Nguyen.  Mail : tinh.tanphu1954@gmail.com

**Comment by nextnaro** [comment]
install nodejs and npm then run the CLI command
#npm i -g binary-bot

**Comment by hotmatrixx** [comment]
you could always just run the pre built browser based version here:
https://bot.binary.com/bot.html
