### ISSUE TITLE
Suggestion ?!!

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#1876]
I wonder If Someone Knows some indicators or a trick that a bot can use to determine bad markets conditions?!
If You do Please Let Me Know.

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by hotmatrixx** [comment]
hi. there are plenty of tricks to determine types of markets. although this is more of a forum for discussing the software and it's programming, srategies discussions are welcomed by the devs, so I'm happy to accomodate you.

there are some important things to learn and understand. for instance, there is no such thing as a bad market. there are markets that are bad for your strategy. a different strategy in the same market might have excellent success.

I'm guessing that you are at 'beginner' level with Binary Options, and possibly with Stock Trading in general? That's OK, we all start at the beginning. All I can truely reccomend is that you take advantage of the unlimted refills on the demo account here and practice. It took me 3 years to become profitable.


BO are quite unique and there is not a lot of documentation on them. unless you understand their idiosyncracies really well, you are honestly just gambling at a roulette table. They are still a relatively new entry into stocks and shares, and many who do not understand themintimately, and some who do, don't consider them to be 'true' trading and they are super heavily regulated and banned all over the world.

Don't let that scare you off. Just be aware of what you're getting into.

_I can promise you one thing though_
Do not buy one of those advertized Auto trading bot for binary options, EVER. They don't explain their strategy, you have no idea why their bot makes/passes on trades, they always succeed on demo accounts and always fail when you put real money into one. and NO ONE ever made money off one. 
they are just a hole in the wall to put your money into.

you have come here to learn how to code your very own strategy, and that's admirable. I recommend having a strategy first, then beginning to learn how to code for that.

Today you're asking about strategies. actually, indicators, which suggests you know very little. I highly reccomend that you go and learn some basics. I recommend this:
that you get the MetaTrader 5 app,
Learn how to set it to forex
Learn how to set the trade window to display candles
 and learn how to add and adjust indicators in that app. 

once you have done these very simple things, start playing with indicators to see what ones work for YOU and what ones you like. MT5 has a LOT of indicators. I'd suggest going through each one 1 by 1 and finding a tutorial video on how each indicator works. DON"T buy whatever that tutorial is probably selling. Learn the indicators, learn to look for pattersn using your own system. then you will be set up for life.

Trading is a race, but it's won over a lifetime, not over a week, a month, or a year. successful traders get rich at around year 5. but they lose money until about year 3.

97% of traders lose their money. I know they numbers are claimed to be around 70- to 90% but believe me, it's much higher than that. 70 percent lose everything in year one. 85% in year 2. 90% in year 3. but the stats don't include those facts. It takes persistence and grit. and my strategy probably won't work for you. nor will anyone else's. Time, patience, risk tolerance, initial investment, ongoing overheads, human error, all factor in. human error is the cause of most losses on the stocks. misinformed, using strategies without understanding why, or panicing when things look like they are going badly and stopping too soon, or too late.

you need to get in the game, and stay there long enough that you can resist the urge to interfere with a strategy. that takes years.

here is one to get you started.
I promise you, you need to run it wtih 10k in the bank or it will suck you dry.
It's not a real solid strategy, but its a good start for you to begin to understand indicators.

please learn and get familiar with the stock market. if trading is exciting, your doing it wrong. you need to be so well practiced, and so confident in your system, that it's BORING.  That's whn you know you're doing it right.

https://github.com/binary-com/binary-bot/issues/1862#issuecomment-524198484

**Comment by Adammodex** [comment]
@hotmatrixx Hi Sir, 
Thank You For Your Reply and I do understand what you've said.

99% Of What You Said Here is true, the 1% is Wrong and true at the same time, I might be a beginner to coding, but not a beginner in binary options and forex trading, I Spent more than 2 years Trading on Practice accounts and with different brokers Such as Iq Option, Binary.com, Metatrader5 (Forex Trading).

Thank You Sir Very Much I do like your question and i will take it more in consideration.

I do have a strategy and i did build a bot for it (not build but just assembled different bots).
My bot is fairly good but it loses some trades when the market is bad so that's why asked if There's someway or a trick to implement The Bad Market Conditions in the bot so that he can avoid trading in them.

If you do know any way Please Let Me Know, If Not then that's no problem at all.

And For the Third Time, Thank You Very Much For Your Past Reply.

**Comment by ceakuk** [comment]
@Adammodex 
bad market condition only happen in real markets where buy and sell determines where the market is goin. that is stocks and forex (ECN) which are not under manipulation of market makers.

volatility index has no known drivers other than random numbers generators. you cant predict favourable times. but you can use say bollinger bands to avoid  specific areas of volatility so that you work only in a given  standard deviation range

**Comment by Adammodex** [comment]
Okay, @ceakuk I'll try to Use The Bb Indicators. Thank You very much.

**Comment by hotmatrixx** [comment]
You have to define bad. What you're of market is causing you issues
