### ISSUE TITLE
[Bug] orphaning certain blocks doesn't work (QoL)

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1878]
If I 'orphan' a block to disable it - say by pulling it out of the loop and leaving it stranded outside any logic loop, the bot will 'usually' automatically disable it, issue a little yellow warning, and carry on.

if however you orphan a (without disabling it) block that requires inputs, such as a MACD array, the bot will give an "INPUT cannot be empty" and hard failure. it stops the bot.

Not a major, but it took a little bit of investigation to figure out why it wouldnt start when i was certain my 'active' blocks were all initialized and variables filled correctly.

Mostly a QoL thing, I think.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Thanks for reporting this issue. I wasn't able to reproduce this issue, could you explain the steps that cause this behaviour?

Thanks once again for your feedback, we appreciate it. 👍 

Regards,
Aaron
