### ISSUE TITLE
Need help please 

### ISSUE THREAD

**Issue by nobleb2007** [binary-com/binary-bot#1879]
Good morning, 
Please kindly help me check this strategy out and build it into bot

Strategy: If the last 2digit is between 30-40 and red colour. It should buy LOWER with BARRIER 0.8 volatility 10.
Else if the last 2digit is between 30-40 and blue colour. It should buy HIGHER with BARRIER -0.8.

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

Thanks and God bless you all.

**Comment by hotmatrixx** [comment]
Considering how long you've been here, and the help you've asked for in the past, are you actually able to code this yourself? its' really really simple to do. 

Do you understand how to put these bots together, or do you just ask us to do it for you?

**Comment by nobleb2007** [comment]
Yes, if I see the picture of it I can code it myself. Just that am finding
it difficult to put the logic together.

Hope you help out

**Comment by nobleb2007** [comment]
Please kindly help me out with this one. Am finding it difficult to get the
strategy right myself.

You can help with pictures of it, I can assemble it myself.

Thanks. Please

**Comment by lasaidhari** [comment]
![hing lower loop (-1)](https://user-images.githubusercontent.com/34808023/63898740-19956300-c9f2-11e9-9cd1-4db4468a5f7c.gif)
[hinglower loop lockdigits .zip](https://github.com/binary-com/binary-bot/files/3553210/hinglower.loop.lockdigits.zip)
please add martingale ...

**Comment by nobleb2007** [comment]
Thanks am grateful. I even like the tutorial step of it. God bless you.

**Comment by lasaidhari** [comment]
You are welcome. I tested the bot and lost a maximum of 1x.

**Comment by nobleb2007** [comment]
I have added MARTINGALE to it. It really killing it softly. Thanks alot

**Comment by nobleb2007** [comment]
[need correction.txt](https://github.com/binary-com/binary-bot/files/3576054/need.correction.txt)
Kindly help me fix this, I put recovery stake in the bot. Just wanted to modify it little.

But I don't know what I don't put right after lossing it will trade the same amount, and after winning once.

The next trade should be MARTINGALE and if it wins it should return to initial stake.

But it is not returning and it kept trading with MARTINGALE. 

Please help my check it. God bless you all.

**Comment by nobleb2007** [comment]
@lasaidhari  please help me. It is the same boy abeg. Thanks

**Comment by nobleb2007** [comment]
@lasaidhari
Please am still counting on you on this final piece. Please, please help me out. Thanks

**Comment by Eshhh** [comment]
[need.correction - corrected.zip](https://github.com/binary-com/binary-bot/files/3584627/need.correction.-.corrected.zip)

this should work

**Comment by nobleb2007** [comment]
Thanks sir
@eshhh


This is what I intended to achieve
If the first trade loss, trade same amount until win. Then next trade MARTINGALE. If this win go back to initial stake.if loss it should follow the same first step.

I hope you understand. Kindly help out. God bless you

**Comment by saidforex26** [comment]
![amountlos](https://user-images.githubusercontent.com/54820719/64466569-c8c8ed00-d10a-11e9-9dd1-4ecb5a25a88f.gif)
