### ISSUE TITLE
Dummy Ticks Trades (DTT)

### ISSUE THREAD

**Issue by waal9** [binary-com/binary-bot#188]
Could the attached bot be made to trade after losing 3 trades?

<script src="https://gist.github.com/waal9/3ef66c4ecb1d945e688d4697054f3c53.js"></script>

**Comment by aminmarashi** [comment]
You can't attach your blocks in here. I suggest you use https://gist.github.com/ to create a list and put the link into your comment.
An alternative is sending your block to marketing@binary.com
