### ISSUE TITLE
Giving away no martingale profitable bot for free trials

### ISSUE THREAD

**Issue by ceakuk** [binary-com/binary-bot#1882]
Hallo everyone,
I would like to give out my bot for free trials but thats only possible if I can hide the codes otherwise nobody will   later buy it if they can just keep the trial version or even copy it. Is there a way to hide the codes.
Thanks

**Comment by nobleb2007** [comment]
Yes, can you send it to me nobleb2007@gmail.com

**Comment by ceakuk** [comment]
@nobleb2007 
please read the explanation. i can't send it until I know how to mask the codes

**Comment by ceakuk** [comment]
I'm not selling here, just asking for technical help.
anybody with idea @binary-ex-machina

**Comment by binary-ex-machina** [comment]
@ceakuk you can't hide the codes, not even from external loaded files.

**Comment by lasaidhari** [comment]
to hide the code is not available, using the load block function will also display the code. You might use this function to create a trial timeout. Its weaknesses will be easily dismantled if someone understands how it works ...
![bata expired](https://user-images.githubusercontent.com/34808023/63895421-0335da00-c9e7-11e9-9b16-9bb2dbc32645.jpg)

**Comment by ceakuk** [comment]
Thank you @binary-ex-machina  and @lasaidhari 
So someone can just take my 12 months of work either for free or for a small amount and sell it as his own.
binary.com need to do something about that

**Comment by ceakuk** [comment]
the code would be  easy to create by just limiting decompressing compressed codes

**Comment by Glexmoney** [comment]
@ceakuk I am ready to buy and use it privately only show results performances

**Comment by Craziestar36** [comment]
How much are you charging it for.
I will buy it.And if i attract any customers i will redirect them back to you!!!I am a man of my words.

**Comment by Glexmoney** [comment]
@ceakuk I want to buy the trial
