### ISSUE TITLE
how to install binary bot locally?

### ISSUE THREAD

**Issue by sl777** [binary-com/binary-bot#1883]
how to install binary bot locally?

**Comment by sl777** [comment]
any videos .. please help me

**Comment by nextnaro** [comment]
Install nodejs , npm then follow https://github.com/binary-com/binary-bot/wiki

**Comment by sl777** [comment]
not start

**Comment by sl777** [comment]
not starting please someone help me

**Comment by nextnaro** [comment]
@sl777  u should be give more info error ur evn etc nobody know like this.
