### ISSUE TITLE
Pls help building bot with my strategy

### ISSUE THREAD

**Issue by emtecetr** [binary-com/binary-bot#1884]
Hello all. I have tried manual trade my idea and it worked but I hope someone will help me make bot with it , couse i can not do it. So I am waiting to see last digit is 0 or 1 for two consecutive ticks then i put digit over 1 for next tick if win continue with min bet else martingale factor 5.5 . For now i get maximum 2 loses. And i make 11$per hour.

**Comment by lasaidhari** [comment]
what index and how many ticks

**Comment by emtecetr** [comment]
Nevermind index, i hope . But only tried it on index10 .I am watching only last two ticks , last number to be lower then 1 then put next to be over 1.

**Comment by lasaidhari** [comment]
[lock2digist _2.zip](https://github.com/binary-com/binary-bot/files/3555369/lock2digist._2.zip)
hopefully can help

**Comment by freedonone** [comment]
https://github.com/binary-com/binary-bot/files/3549863/xx.xax.xaax.today.V1.txt

@lasaidhari  could you help me look into the bot above

it is having alot of errors

**Comment by emtecetr** [comment]
Thank you it is exactly the same.

**Comment by lasaidhari** [comment]
@freedonone I see no errors but how the bot works does not meet your expectations. maybe you can tell us what bot you want so I can make it

**Comment by lasaidhari** [comment]
@emtecetr you are welcome ... hopefully useful

**Comment by freedonone** [comment]
> @freedonone I see no errors but how the bot works does not meet your expectations. maybe you can tell us what bot you want so I can make it

I expect it to switch to the next condition after a loss

the conditions are in these forms

for instance, if any of these number formations occurs in this particular order not necessarily in a consecutive order in a last digit list (where **x** is a particular number e.g 5); 

**x,x**  and **x,d,x**   and last digit **x**, purchase digit differ "**x**"   after 3 ticks

if loss, then it will consider this next condition

**x,x**  and **x,d,x**  and **x,d,f,x**  and last digit **x**, purchase digit differ "**x**"   after 4 ticks

if loss, then it will consider this next condition

**x,x**  and **x,d,x**  and **x,d,f,x**  and **x,c,f,r,x** and last digit **x**, purchase digit differ "**x**"   after 5 ticks

if loss, then it will consider this next condition

**x,x**  and **x,d,x**  and **x,d,f,x**  and **x,c,f,r,x**  and **x,c,f,r,b,x**  and last digit **x**, purchase digit differ "**x**"   after 6 ticks

if win at any condition it will return to condition one.

thanks

**Comment by lasaidhari** [comment]
do you mean x is the same number ...
example. 6,7,6 then buy differs 6 after 3 tick

**Comment by freedonone** [comment]
> do you mean x is the same number ...
> example. 6,7,6 then buy differs 6 after 3 tick

yes, in that case
 
the conditions will be;

6,6 and 6,3,6 and last digit 6, purchase digit differ "6" after 3 ticks

if loss, then it will consider this next condition

6,6 and 6,3,6 and 6,3,7,6 and last digit 6, purchase digit differ "6" after 4 ticks

if loss, then it will consider this next condition

6,6 and 6,3,6 and 6,3,7,6 and 6,8,7,1,6 and last digit 6, purchase digit differ "6" after 5 ticks

if loss, then it will consider this next condition

6,6 and 6,3,6 and 6,3,7,6 and 6,8,7,1,6 and 6,8,7,1,9,6 and last digit 6, purchase digit differ "6" after 6 ticks

if win at any condition it will return to condition one.

thanks

**Comment by lasaidhari** [comment]
You must use logic (or) not logic (and)

**Comment by lasaidhari** [comment]
try this
[2same digits (1).zip](https://github.com/binary-com/binary-bot/files/3559913/2same.digits.1.zip)

**Comment by freedonone** [comment]
![Cap](https://user-images.githubusercontent.com/54136867/64022601-7d24ab00-cb2e-11e9-966c-7dccb7892bad.PNG)
 
something like this

**Comment by lasaidhari** [comment]
please try what I have shared ... develop

**Comment by martinrf79** [comment]
Hi, how are you lasaidhari, could you code the photo bot. Entry occurs once, in the change from red to green candle or from green to red.
If after the change the last candle is green, we look at the graph the immediate previous green candles, if there is a previous green candle put prediction, if there are 2 previous candles call prediction.

If after the change we have a red candle we look at the immediate previous red candles, if there is a red candle prediction call and if there are 2 previous candles prediction put.
The next entry will be when another candle change occurs.
![Candle comb](https://user-images.githubusercontent.com/52263754/64029412-e1d60a80-cb1a-11e9-942c-94c5866c08cc.png)

**Comment by lasaidhari** [comment]
[2colorcandle (1).zip](https://github.com/binary-com/binary-bot/files/3561940/2colorcandle.1.zip)
@martinrf79  hopefully can help . please go to the market you want to compare and add a martingale and develop a bot according to your expectations

**Comment by martinrf79** [comment]
Hi, how are you, thank you very much for the bot. Thanks to this advanced coding that you used I can try several strategies.
If it is not too much trouble and you have time I want to ask you about bots of different digits, attached I send you 2 bots what they do is the following: in the sequence of digits 6 6 4 6 in both bot the prediction number 6 but one takes the 4 as result and the other takes 6. What I want to achieve is that the bot last digit my version volat 10 results in the number 6 and not the number 4, if you don't have to open 10 bots, one for each digit

Thanks again, best regards.
[last digit my version limpio volat 10.txt](https://github.com/binary-com/binary-bot/files/3564075/last.digit.my.version.limpio.volat.10.txt)
[2 ticks iguales 66.txt](https://github.com/binary-com/binary-bot/files/3564076/2.ticks.iguales.66.txt)

**Comment by abelojo11** [comment]
please i need help with my robot, it is not respecting the acceptable loss command. can someone help me please? want it to stop one it gets to acceptable loss

**Comment by saidforex26** [comment]
> 
> 
> Hi, how are you, thank you very much for the bot. Thanks to this advanced coding that you used I can try several strategies.
> If it is not too much trouble and you have time I want to ask you about bots of different digits, attached I send you 2 bots what they do is the following: in the sequence of digits 6 6 4 6 in both bot the prediction number 6 but one takes the 4 as result and the other takes 6. What I want to achieve is that the bot last digit my version volat 10 results in the number 6 and not the number 4, if you don't have to open 10 bots, one for each digit
> 
> Thanks again, best regards.
> [last digit my version limpio volat 10.txt](https://github.com/binary-com/binary-bot/files/3564075/last.digit.my.version.limpio.volat.10.txt)
> [2 ticks iguales 66.txt](https://github.com/binary-com/binary-bot/files/3564076/2.ticks.iguales.66.txt)

[66.zip](https://github.com/binary-com/binary-bot/files/3577449/66.zip)

**Comment by saidforex26** [comment]
> 
> 
> ![Capte](https://user-images.githubusercontent.com/54136867/64022764-cd037200-cb2e-11e9-89d1-836831c54891.PNG)
> 
> something like this

[condition 1to6.zip](https://github.com/binary-com/binary-bot/files/3577564/condition.1to6.zip)

**Comment by Pastranatecks** [comment]
alguien podria ayudarme con esto  analizando 4 digitos  en azul
variables:

Digito1

Digito2

Digito3

Digito4

par

impar

Paso par1 “paso par creciendo” “ejemplo 4 8”

Paso par2 “paso par decreciendo” “ejemplo 6 2”

Paso impar1 “paso impar creciendo” “ejemplo 1 5”

Paso impar2 “paso impar decreciendo” “ejemplo 7 3”

Si digito1 es par y digito2 es par mayor a digito1,  entonces

Paso par1= Digito1 y digito2

Si digito1 es par y digito2 es par menor a digito1,  entonces

Paso par2= Digito1 y digito2

Si digito1 es impar y digito2 es impar mayor a digito1,  entonces

Paso impar1= Digito1 y digito2

Si digito1 es impar y digito2 es impar menor a digito1,  entonces

Paso impar2= Digito1 y digito2

si se cumple : paso par1 y paso impar1 entonces apostar arriba

si se cumple : paso par2 y paso impar2 entonces apostar abajo

fin

**Comment by I-Marwa** [comment]
Hi, how do I build a bot that purchases rise after two consecutive rising ticks?
