### ISSUE TITLE
help ne this... ZIG - ZAG rise/fall bot

### ISSUE THREAD

**Issue by sl777** [binary-com/binary-bot#1885]
can you do this... ZIG - ZAG rise/fall bot with martingale
trade rise 
if lost fall
 if lost rise 
if lost rise
like this .. zig - zag with martingale
please help me

**Comment by lasaidhari** [comment]
very easy..

**Comment by waltergrant** [comment]
![image](https://user-images.githubusercontent.com/9876451/64080129-22e04180-cd0a-11e9-9498-8fe6e6a45b99.png)
