### ISSUE TITLE
Bot binary - 5 candles count - Help me

### ISSUE THREAD

**Issue by Eulerhp** [binary-com/binary-bot#1886]
I have a strategy that assembles a bot that makes entries like this.
I want him when I play he will wait for 5 candles and check the color the last candle(5) and make the entry in the opening of the next candle so that the same color of the previous candle in case number 5
This example.

1º Candle = Green
2º Candle = Red
3º Candle = Red
4º Candle = Green
5º Candle = Red

The robot will put put for the next candle to be red

Help me.

**Comment by lasaidhari** [comment]
![colorcandle](https://user-images.githubusercontent.com/34808023/63985619-5a5fab80-cac8-11e9-96e1-4c9fc645f51b.gif)
[green,red,red,green,red.zip](https://github.com/binary-com/binary-bot/files/3557807/green.red.red.green.red.zip)

**Comment by Eulerhp** [comment]
Thank you very much it was very good.
Want to know how I do it regardless of the color of the candles, (1,2,3,4,5) how do I get him to count 5 candles and always enter the sixth candle saying it will be the same color as the 5 candle?

**Comment by Eulerhp** [comment]
It will count 5, but will only take candle color 5 into consideration, and go in to make candle 6 the same color as candle 5! I think now I could explain better.

**Comment by lasaidhari** [comment]
I did not understand

**Comment by Eulerhp** [comment]
[](https://github.com/Eulerhp/robo_trader/blob/master/IQOPTION.jpg)
https://github.com/Eulerhp/robo_trader/blob/master/IQOPTION.jpg
Sorry I'm not very good at explaining I'll post a picture here to try to explain the strategy better, lost me for the bad english.

**Comment by Eulerhp** [comment]
> I did not understand

Please help me

**Comment by Eulerhp** [comment]
> ![colorcandle](https://user-images.githubusercontent.com/34808023/63985619-5a5fab80-cac8-11e9-96e1-4c9fc645f51b.gif)
> [green,red,red,green,red.zip](https://github.com/binary-com/binary-bot/files/3557807/green.red.red.green.red.zip)

I made some modifications but it is coming in before the 3rd candle closes, how can I get this right, can you help me?
[](https://github.com/Eulerhp/bot_trader/blob/master/binary-bot-v5.xml)

**Comment by Eulerhp** [comment]
> > ![colorcandle](https://user-images.githubusercontent.com/34808023/63985619-5a5fab80-cac8-11e9-96e1-4c9fc645f51b.gif)
> > [green,red,red,green,red.zip](https://github.com/binary-com/binary-bot/files/3557807/green.red.red.green.red.zip)
> 
> I made some modifications but it is coming in before the 3rd candle closes, how can I get this right, can you help me?



> ![colorcandle](https://user-images.githubusercontent.com/34808023/63985619-5a5fab80-cac8-11e9-96e1-4c9fc645f51b.gif)
> [green,red,red,green,red.zip](https://github.com/binary-com/binary-bot/files/3557807/green.red.red.green.red.zip)
[binary-bot-v5.xml](https://github.com/Eulerhp/bot_trader/blob/master/binary-bot-v5.xml)

**Comment by Eulerhp** [comment]
I made some modifications but it is coming in before the 3rd candle closes, how can I get this right, can you help me?

**Comment by saidforex26** [comment]
> 
> 
> 
> https://github.com/Eulerhp/robo_trader/blob/master/IQOPTION.jpg
> Sorry I'm not very good at explaining I'll post a picture here to try to explain the strategy better, lost me for the bad english.

[5candle.zip](https://github.com/binary-com/binary-bot/files/3577405/5candle.zip)

**Comment by Eulerhp** [comment]
> > https://github.com/Eulerhp/robo_trader/blob/master/IQOPTION.jpg
> > Sorry I'm not very good at explaining I'll post a picture here to try to explain the strategy better, lost me for the bad english.
> 
> [5candle.zip](https://github.com/binary-com/binary-bot/files/3577405/5candle.zip)

Thank you! Without your help I would not succeed. I use this strategy in the iq option it gives me great results, but it is so consistent if i use 3 levels of martingales, for example if the fourth candle is green i will get the next candle to be the same color as the fourth one, and If not, I enter again so that the next Fifth candle is the same color as the Fourth, and if not, I enter again saying that the Sixth candle will still be the same color as the Fourth candle, can you understand?

How do I make these 3 levels of martingales if the result of the first negative operation?

**Comment by saidforex26** [comment]
try this
[v3Xcandle4 (1).zip](https://github.com/binary-com/binary-bot/files/3581391/v3Xcandle4.1.zip)

**Comment by Eulerhp** [comment]
> try this
> [v3Xcandle4 (1).zip](https://github.com/binary-com/binary-bot/files/3581391/v3Xcandle4.1.zip)

Hi said how are you?
This robot is fantastic, thanks to you it is running and its first test was amazing, test it also always in these conditions.
1 hour a day.
start 09:00 to 10:00 and post here the result please. If you have any suggestions for improvement you can also talk.
[bot_bnx1.jpg](https://github.com/Eulerhp/bot_trader/blob/master/bot_bnx1.jpg)

**Comment by saidforex26** [comment]
You run it on volatility indices or forex. which country time it is

**Comment by Eulerhp** [comment]
> You run it on volatility indices or forex. which country time it is

I am using the volatile indices, starting the tests from 09:00 to 10:00 am in Brazil, have a converter for your parents with this time difference

**Comment by Eulerhp** [comment]
> You run it on volatility indices or forex. which country time it is

add my whatsapp +5531994360905

**Comment by Eulerhp** [comment]
> try this
> [v3Xcandle4 (1).zip](https://github.com/binary-com/binary-bot/files/3581391/v3Xcandle4.1.zip)

Said, how are you?
There is a way to define the amount and daily operations of the robot. for example 100 no of runs?

**Comment by saidforex26** [comment]
yes there are many ways

**Comment by FlavianoFlavio** [comment]
TEria como fazer esse bot para essa estratégia;

Se o bot contar 5 Velas Verdes ele deverá abrir uma operação dizendo que a próxima vela (6° vela) sera Vermelha, e se o bot contar 5 velas vermelhas ele abrirá operação dizendo que a peóxima vela (6º vela) será Verde... Teria como ?

**Comment by saidforex26** [comment]
download file and develop

**Comment by FlavianoFlavio** [comment]
Eu não consegui fazer isso, já tentei várias vezes....

**Comment by junioryum** [comment]
Can a friend determine the length of the candles?

**Comment by Eulerhp** [comment]
> Teria como fazer esse bot para essa estratégia;
> 
> Se o bot contar 5 Velas Verdes ele deverá abrir uma operação dizendo que a próxima vela (6° vela) sera Vermelha, e se o bot contar 5 velas vermelhas ele abrirá operação dizendo que a peóxima vela (6º vela) será Verde... Teria como ?

Tem como sim. 
Trabalho com desenvolvimento de bots binary se precisar posso te enviar um orçamento.

**Comment by Eulerhp** [comment]
> yes there are many ways

Example this code?

**Comment by Eulerhp** [comment]
> download file and develop

how do i stop limiting my bot to only make 30 entries a day. limit number of runs? Help me

**Comment by linhvb** [comment]
You could define the condition at Block 4
Num of runs value = 30

How about your strategy?

**Comment by RSALINASGA** [comment]
Hola buenas tardes, es posible hacer un bot que despues de la tercera vela del mismo color y si es mas grande que las anteriores haga una operacion de revercion? y si es posible identificar que este en una zona de soporte y resistecia y en un retroceso mucho mejor. muchas gracias
![ejemplo entradas bot](https://user-images.githubusercontent.com/53910956/107585437-3d3f6f80-6bcc-11eb-9577-9ae51981cee3.png)
