### ISSUE TITLE
how to set target profit

### ISSUE THREAD

**Issue by sl777** [binary-com/binary-bot#1888]
please tell me hot to set profit target
like 500 usd daily profit limit
![git](https://user-images.githubusercontent.com/54656820/64016029-88ce9c80-cb43-11e9-97b8-6d0286ce8699.jpg)
how to set target profit

**Comment by sinung21** [comment]
send your bot?

**Comment by sl777** [comment]
tell me how to set that.. i perches that.please tell me

**Comment by sl777** [comment]
help me

**Comment by lasaidhari** [comment]
![profit target](https://user-images.githubusercontent.com/34808023/64063424-0e0d8c00-cbec-11e9-872a-1083f01babbe.gif)

**Comment by sl777** [comment]
thank you very much sir..
