### ISSUE TITLE
2 bot at the same time?

### ISSUE THREAD

**Issue by thanh301** [binary-com/binary-bot#1889]
Is it possible to set 2 bot running at same time, make trade at same time and only do martingale when both bot loss a trade?

**Comment by lasaidhari** [comment]
Before I add the analysis function of 2 bots that are running, I have to see how your bot works. send your bot I can help you

**Comment by thanh301** [comment]
Well I run one with barrier +0.1 and another with barrier -0.1, the one with barrier + 1 make higher trade and the other lower trade.

[higher lower x2.txt](https://github.com/binary-com/binary-bot/files/3565958/higher.lower.x2.txt)

**Comment by ceakuk** [comment]
unless you are not doing it by web, no its  not possible.
they know hedging is profitable when done right so they  don't allow it
