### ISSUE TITLE
Error Install Local NPM Binary.com

### ISSUE THREAD

**Issue by arturodiazlora** [binary-com/binary-bot#189]
<a href="http://www.uploadhouse.com/viewfile.php?id=23807418&showlnk=0" target="_blank"><img src="http://img8.uploadhouse.com/fileuploads/23807/23807418-holder-cb1a54e529ad5f36bb24beb2cb549f07.jpg" alt="Image Hosted by UploadHouse.com" border="0" /></a>
<br>
help me!! please!!!

**Comment by aminmarashi** [comment]
Binary Bot package is not meant to be used like this. It's a CLI package, which means you can install and use it to run any code specially written for Binary Bot.
And please be advised that the package is experimental and is generated from this #181 
You can find a usage example [here](https://www.npmjs.com/package/binary-bot#running-the-cli-command)

**Comment by aminmarashi** [comment]
If you meant to start the Binary Bot web project locally, I updated instructions in the [README](https://github.com/binary-com/binary-bot#development)
