### ISSUE TITLE
Dummy open price

### ISSUE THREAD

**Issue by john1052** [binary-com/binary-bot#1890]
Hai guys. Could someone help me? How to program dummy bot? Now I trade use 2 bot. Virtual bot & real bot on same progr. I will start open price on real bot waiting 2 or 3 losses on virtual bot and start running on real bot to minimize lose.
But I need bot can do both bot.
Can you help me, pls.

Thank's

**Comment by lasaidhari** [comment]
to send a signal from a virtual account to a real account it can't .. there are actually 2 ways to minimize Kurigian ..
1. carry out future analysis with the technique of waiting for results to be true / win.
2. deactivate the martinggale on the staple booth and start the star again from the beginning of the stake and after the win returns the balance of the stall.

**Comment by john1052** [comment]
Ok. Thank you for your suggest. ..

**Comment by john1052** [comment]
Ok. Thank you for your suggest. ..
