### ISSUE TITLE
Same Bot in 2 different tabs but different results

### ISSUE THREAD

**Issue by syed18** [binary-com/binary-bot#1892]
Hello, i have started same bot in 2 tabs but why the results are different , i just add martingale in 1 bot please see the screenshot 
![Screenshot_2](https://user-images.githubusercontent.com/44053138/64065688-d7eefd00-cc29-11e9-985d-600f16cacd13.png)
![Screenshot_5](https://user-images.githubusercontent.com/44053138/64065689-d8879380-cc29-11e9-8bcc-4ee52ff3009b.png)

**Comment by nextnaro** [comment]
Y 1 put 1 call?

**Comment by Eshhh** [comment]
you need to make sure that the 2 bots have same the entry spot
