### ISSUE TITLE
ALGUIEN ME AYUDA 

### ISSUE THREAD

**Issue by Ares31** [binary-com/binary-bot#1895]
Este bot se detiene un poco despues de funcionar y no se por que... alguien puede revisarlo muchas gracias amigos

[Binary Bot S.L..zip](https://github.com/binary-com/binary-bot/files/3563721/Binary.Bot.S.L.zip)

**Comment by waltergrant** [comment]
hi. check it, plz. rename from .txt to .xml
[0-5-bot.txt](https://github.com/binary-com/binary-bot/files/3563747/0-5-bot.txt)

**Comment by Ares31** [comment]
Gracias Amigo
