### ISSUE TITLE
After 5 consecutive odd purchase even

### ISSUE THREAD

**Issue by guif413** [binary-com/binary-bot#1896]
Hi, I would like to ask if you can help me with an even-odd bot. I want to start after 5 consecutive even or odd.

eg.  

odd
odd
odd
odd
odd

purchase even and run martingale until it reaches an even.

**Comment by ceakuk** [comment]
you can send what you have and i modify it for you. if you have none then write to me and ill make you one tomorrow

**Comment by guif413** [comment]
[EVEN ODD.zip.zip](https://github.com/binary-com/binary-bot/files/3567132/EVEN.ODD.zip.zip)

If you can help me to configure martingale. I need to when there is a loss, run martingale immediately until reaches an even/odd.

**Comment by binary-ex-machina** [comment]
@guif413 you can do like this one below
![image](https://user-images.githubusercontent.com/34610787/64182955-72745980-ce3f-11e9-9f26-1a157b049fad.png)

**Comment by guif413** [comment]
I configured like this one, but when the bot purchase odd, it changes to even when there is a martingale.

**Comment by guif413** [comment]
Thank you very much. It is working normally now.

**Comment by creativi77** [comment]
This what you may be looking for.
[EVEN ODD for Forum.zip](https://github.com/binary-com/binary-bot/files/3571727/EVEN.ODD.for.Forum.zip)

**Comment by guif413** [comment]
Thank you creativi77
