### ISSUE TITLE
Please help me how to use rsi in binary bot, how to put a weighted close in input list on rsi

### ISSUE THREAD

**Issue by Charlescpe** [binary-com/binary-bot#1897]
I'm just a beginner in binary bot programming can you help me about rsi, what is the meaning of error like this "cannot read property "length" of undefined" ?

**Comment by binary-ex-machina** [comment]
post an image of the blocks you have used and got this error

**Comment by Charlescpe** [comment]
![rsi](https://user-images.githubusercontent.com/54802854/64229775-5f37bb80-cf1d-11e9-8f0d-0db4925bc46e.png)


i figured it out, my problem is if it possible to purchase a rise contract even if the price is changing and the candle is not yet closed if my condition is met.
