### ISSUE TITLE
@aaron-binary 

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#1898]
hi @aaron-binary can you share the AROON & AROON OSCILATOR indicators ... please

**Comment by aaron-binary** [comment]
Hey @saidforex26,

We don't currently offer these indicators as part of bot, perhaps @binary-ex-machina can help out. 😄 

Regards,
Aaron

**Comment by binary-ex-machina** [comment]
you can get the values of the Aroon Indicator like this below. 

![image](https://user-images.githubusercontent.com/34610787/64182033-eb72b180-ce3d-11e9-9684-1886ae111a67.png)

**Comment by saidforex26** [comment]
thanks @binary-ex-machina 
![aroon up dow](https://user-images.githubusercontent.com/54820719/64308799-64831d80-cf92-11e9-8240-8dbf6f0661f8.jpg)

**Comment by cmaurelio1785** [comment]
Please post the script of aroon indicator please thanks

**Comment by saidforex26** [comment]
[@lasaidhari aroon indikator.zip](https://github.com/binary-com/binary-bot/files/3673550/%40lasaidhari.aroon.indikator.zip)

**Comment by cmaurelio1785** [comment]
How to use this Aroon indicator?

**Comment by saidforex26** [comment]
[AROON EXAMPLE.zip](https://github.com/binary-com/binary-bot/files/3674243/AROON.EXAMPLE.zip)
![AROON EXAMPLE](https://user-images.githubusercontent.com/54820719/65931907-68745500-e403-11e9-9561-d63b764a7d5d.gif)

**Comment by cmaurelio1785** [comment]
Do you have digit differ using Aroon indicator?
