### ISSUE TITLE
Prediction Add

### ISSUE THREAD

**Issue by servervender** [binary-com/binary-bot#190]
Can I 2 or more Prediction in one Bot

**Comment by aminmarashi** [comment]
Same as #152 ?

**Comment by okovalov** [comment]
I think so. it only works in CLI

**Comment by aminmarashi** [comment]
We also have it in the [experimental version](https://aminmarashi.github.io/binary-bot/bot.html). [an example](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/two%2520predictions.xml)
