### ISSUE TITLE
Info about diff digits.

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#1900]
Hello, as they are all, I would like to know if anyone has access to digit statistics since I am trying a different digit strategy, and today the number 9 was repeated 5 times in a row, (if you listen well 5 times in a row) maybe there is someone Have more time on this and can tell me if these repetitions usually occur often.

Assuming that a digit is repeated every 3 or 5 days 5 times in a row I will continue testing the strategy but otherwise I will have to disclose the subject.

Or maybe there are some scripts that show us statistics in digit history.

As always grateful for your answers and contributions. Best regards.

**Comment by binary-ex-machina** [comment]
try the Fruitfella digit analyzer

https://github.com/Fruitfella/ROBOT-binary/issues/35

![image](https://user-images.githubusercontent.com/34610787/64177774-91bab900-ce36-11e9-91b9-c36f6cafbad4.png)

**Comment by freedonone** [comment]
is it possible to exclude a certain number in  the analysis??

> try the Fruitfella digit analyzer
> 
> [Fruitfella/ROBOT-binary#35](https://github.com/Fruitfella/ROBOT-binary/issues/35)
> 
> ![image](https://user-images.githubusercontent.com/34610787/64177774-91bab900-ce36-11e9-91b9-c36f6cafbad4.png)

**Comment by martinrf79** [comment]
How are you binary-ex-machina the coding of the bot you sent # 1899 is great and from there I get a query.

In the sequence of digits 0 0 3 5 the first bot I send attached (machina 00) takes 5 as the exit spot, and the second bot I send (tick 1 tick 2 prediction 0) takes 3 as the exit spot.

My question is if there is any way that the bot machina00 or some similar take as exit spot the number 3, instead of the number 5. since the other bot (tick 1 tick 2 prediction 0) only takes as a prediction one digit in this case the 0.

A cordial greeting.


[machina 00. txt](https://github.com/binary-com/binary-bot/files/3572395/machina.00.txt)
[tick 1 y tick 2 predicc 0.txt](https://github.com/binary-com/binary-bot/files/3572397/tick.1.y.tick.2.predicc.0.txt)

**Comment by martinrf79** [comment]
Hello how are you, unfortunately there is some part of the translation of the explanation that I do not understand so I could not operate the digits statistics bot. Best regards
