### ISSUE TITLE
Can someone turn "Last digit stats" into Bot Logic?

### ISSUE THREAD

**Issue by Radiorusack** [binary-com/binary-bot#1901]
![image](https://user-images.githubusercontent.com/53004644/64143099-d5162700-ce38-11e9-8d57-4ccca3108848.png)

Can someone turn this digit stats into bot logic? only staking in some trigger.

example:
+dont trade if percentage of digit 0 is above 10%, or something..

thank

**Comment by binary-ex-machina** [comment]
you can follow #1900

**Comment by sl777** [comment]
yes iwanted too.. high stat bot... please someone help

**Comment by Radiorusack** [comment]
Oke, Thanks @binary-ex-machina....i found it there
