### ISSUE TITLE
Need your help on this.

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#1902]
Hi Guys, 
as you know, Profits in touch/no-touch are not stable. and that's affecting my bot (martingale).

Let's see how it is affecting it 

I use factor 1.875 on my martingale.

for Example, if the profit percentage is 115%:

Loss 1 : -0.35
Loss 2 : -0.66
Loss 3 : -1.23
Loss 4 : -2.31
Loss 5 : -4.33
Win 1 : +9.32

and the profit is 0.44$

For Example, if the profit percentage is 95%

Loss 1 : -0.35
Loss 2 : -0.66
Loss 3 : -1.23
Loss 4 : -2.31
Loss 5 : -4.33
Win 1 : +7.7

and the profit is -1.18$

and that's how I lose money

Now my issue is I want to make the bot run but only if the percentage of the profit is equal or higher than 115%

can some please help me figure this out.
thank you

Best regards.

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by binary-ex-machina** [comment]
you can do something like this to get the profit percentage compared to the stake
![image](https://user-images.githubusercontent.com/34610787/64177618-47d1d300-ce36-11e9-86d9-c95555365dd0.png)

**Comment by Adammodex** [comment]
Thank You very much @binary-ex-machina, I'll try to implement it and see how it goes.
