### ISSUE TITLE
i wanted high stat bot @lasaidhari

### ISSUE THREAD

**Issue by sl777** [binary-com/binary-bot#1905]
i have minstat bot.. but i want high stat bot 
like fruitella
please help me someone

**Comment by sl777** [comment]
please help

**Comment by sl777** [comment]
need help

**Comment by saidforex26** [comment]
@sl777 as what you want

**Comment by dushn** [comment]
I want highstat bot. Frutella.. like 25 tick analyze maxstat 
If 25 tick max stay is 6 match or differ 6

**Comment by dushn** [comment]
Max stat bot. Frutella Max stat.

**Comment by sl777** [comment]
yes its fruitell maxstat.. i have minstat. i want max stat bot

**Comment by saidforex26** [comment]
it was shared too

**Comment by sl777** [comment]
can you please share it again... pls.

**Comment by saidforex26** [comment]
Try sending the fruitella file that you use for minstat ...

**Comment by sl777** [comment]
[MinStats.With.MArti.txt](https://github.com/binary-com/binary-bot/files/3592812/MinStats.With.MArti.txt)

**Comment by saidforex26** [comment]
minstat and maxstat are available in the file

**Comment by sl777** [comment]
not working
canyou please make a bot please
