### ISSUE TITLE
I need  help asap

### ISSUE THREAD

**Issue by freedonone** [binary-com/binary-bot#1908]
please house, 

is there any way I can tweak fruitfella's  digit analyzer bot to fetch me the frequency of a few numbers like 0,1,2,3,4,5,6 only.......... excluding 7,8,9.

the 100 percent will be based on the 7 numbers only

**Comment by waltergrant** [comment]
![image](https://user-images.githubusercontent.com/9876451/64358033-2253ed80-d01f-11e9-8c08-2229585ac10c.png)

**Comment by freedonone** [comment]
thanks for your effort but this is just the sum of the digit 0-7 frequency, not really what I want
