### ISSUE TITLE
Difference between "Open" and "Open time" in candle list block

### ISSUE THREAD

**Issue by kan-il** [binary-com/binary-bot#1910]
![4](https://user-images.githubusercontent.com/53809756/64346199-532c2680-d00f-11e9-8c98-b533d57e4c8f.JPG)
![5](https://user-images.githubusercontent.com/53809756/64346210-57f0da80-d00f-11e9-86bf-7a18bec2806b.JPG)

Can anyone please tell me the difference between "open" and "open time" in candle list block

**Comment by nextnaro** [comment]
Open is price.
Open time is ephoc time.
when open new candle.

**Comment by kan-il** [comment]
@nextnaro  sorry I didn't quite understand your explanation on "open time"

**Comment by nextnaro** [comment]
"open time" return [Epoch Timestamp](https://www.epochconverter.com/) when start new candle.

**Comment by kan-il** [comment]
> "open time" return [Epoch Timestamp](https://www.epochconverter.com/) when start new candle.

Thank you @nextnaro
