### ISSUE TITLE
Need Help For Stake/Money Management!

### ISSUE THREAD

**Issue by Radiorusack** [binary-com/binary-bot#1912]
Hello, 
Do anyone can make my simple staking stake strategy in to block?

would be like this:
Stake 1 : 1
Stake 2 : 0.5
Stake 3 : 0.5
Stake 4 : 1

Also add for Target Profit and SL

For the stake can add manually and changeable... 

Thanks for help

**Comment by waltergrant** [comment]
check, plz. rename from .txt to .xml
[manually-stakes-bot.txt](https://github.com/binary-com/binary-bot/files/3584354/manually-stakes-bot.txt)

**Comment by Radiorusack** [comment]
Awesome dude.. Work perfectly.. Thanks loot dude...
