### ISSUE TITLE
Need Simple Help > Adding delay after Lost

### ISSUE THREAD

**Issue by Radiorusack** [binary-com/binary-bot#1913]
This is what i want to do.. but for sure this is not working..

Can somebody help me to make it better?
thanks

![image](https://user-images.githubusercontent.com/53004644/64430394-6b20aa80-d0e2-11e9-82db-d036e91f1eda.png)

**Comment by waltergrant** [comment]
try it 
![image](https://user-images.githubusercontent.com/9876451/64433888-c9e12680-d0d8-11e9-95bd-f78527f258eb.png)

**Comment by Radiorusack** [comment]
Oke i will try it.. Btw thanks dude

**Comment by nobleb2007** [comment]
[need correction.txt](https://github.com/binary-com/binary-bot/files/3585515/need.correction.txt)
@waltergrant 

This is what I intended to achieve
If the first trade loss, trade same amount until win. Then next trade MARTINGALE. If this win go back to initial stake and vice versa.I hope you understand.

Please kindly help me fix it. God bless you.

**Comment by waltergrant** [comment]
@nobleb2007 
I hope understood correctly
[lower-bot.txt](https://github.com/binary-com/binary-bot/files/3586377/lower-bot.txt)

**Comment by nobleb2007** [comment]
Thanks
