### ISSUE TITLE
Please Help for custom Martingale strategy (Martingale after 4 trades)

### ISSUE THREAD

**Issue by Radiorusack** [binary-com/binary-bot#1914]
Hello,

Can anyone make this martingale strategy?

it would martingale after 4 trades.

![image](https://user-images.githubusercontent.com/53004644/64431932-a670a880-d0e5-11e9-8ce5-a00a28bad917.png)

And if during trade 2nd lost again, the rule martingale is same for the first ( after 4 trades from lost)

thanks

**Comment by waltergrant** [comment]
yo, check it
[starting-after-bot.txt](https://github.com/binary-com/binary-bot/files/3586255/starting-after-bot.txt)

**Comment by Radiorusack** [comment]
Work great brooo..thanks

![image](https://user-images.githubusercontent.com/53004644/64470000-05760200-d166-11e9-9923-87450d4333d6.png)

**Comment by waltergrant** [comment]
oh, sorry, forgot to add)
![image](https://user-images.githubusercontent.com/9876451/64471043-a2846b00-d165-11e9-933c-c9d7ad051a5b.png)

**Comment by nobleb2007** [comment]
@waltergrant
[Stressful (2).txt](https://github.com/binary-com/binary-bot/files/3587219/Stressful.2.txt)

please i tried to combine this starting after bot with my strategy to higher lower bot. I couldn't get it right cos the bot is not buying anything. Kindly help me fix it. Please God bless you.

**Comment by nobleb2007** [comment]
Please kindly help me fix it

**Comment by waltergrant** [comment]
@nobleb2007 
plz, next time create new issue
[binary-bot-edited.txt](https://github.com/binary-com/binary-bot/files/3614793/binary-bot-edited.txt)
