### ISSUE TITLE
Finding the martingale block

### ISSUE THREAD

**Issue by ysewellam** [binary-com/binary-bot#1916]
Hello, I'm new here and having a hard time to find the block for martingale in that bot. Any help will be appreciated to show me how to remove it or set the martingale to 1.

[Rise.Fall.Bot.txt](https://github.com/binary-com/binary-bot/files/3586496/Rise.Fall.Bot.txt)

**Comment by ysewellam** [comment]
And also please how can I make the trade open only if a blue head appears and after 1 tick it sells and only if red head appears and after 1 tick it buys. As in those blocks it's not functioning like that it is just opening trades randomly after the blue or red head appears. Thanks

![blocks](https://user-images.githubusercontent.com/54754989/64474213-c1412c80-d17a-11e9-8eaa-adbdcbd69159.png)

**Comment by ysewellam** [comment]
No hope guys?

**Comment by prathuishpraad123** [comment]
could any one pls help me to modify my bot with martingale function
