### ISSUE TITLE
strategy change help??

### ISSUE THREAD

**Issue by sl777** [binary-com/binary-bot#1917]
i use 3 strategy same market
how to set in one bot
1 st strategy win after change 2nd 
how to put 3 strategy watch and perches part 
and change after win strategy
thakns

**Comment by saidforex26** [comment]
it's very easy .. give your bot strategy and I complete the new logistics

**Comment by sl777** [comment]
nmbers analyze tick analyze ?
how to create like this
please create 3 logics?
