### ISSUE TITLE
Can someone explain this strategy to me?

### ISSUE THREAD

**Issue by Arionfox** [binary-com/binary-bot#1918]
https://www.youtube.com/watch?v=b5gk8LZoGes

Thank You!

**Comment by eonuoha30** [comment]
Life is easy. Don't make it seem complicated.

if you don't  understand it, why not leave it?

There are thousands more on the internet

**Comment by saidforex26** [comment]
I made the bot and agreed. But the results are not satisfactory ... the strategy is not good
