### ISSUE TITLE
[Help] Zero Line Cross (Awesome Oscillator)

### ISSUE THREAD

**Issue by hlesht** [binary-com/binary-bot#1922]
Hi,
Need some help...
Could someone help me create a call option when AO indicator cross line 0?
Ty

**Comment by creativi77** [comment]
Try this



[AweSome for Forum.zip](https://github.com/binary-com/binary-bot/files/3599358/AweSome.for.Forum.zip)

**Comment by creativi77** [comment]
this is with recovery option
bellow

[AweSome recovery for Forum.zip](https://github.com/binary-com/binary-bot/files/3599719/AweSome.recovery.for.Forum.zip)

**Comment by hlesht** [comment]
TY so much.
Works!!!
ure the best
