### ISSUE TITLE
Simple Bot Range Break

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#1924]
Hello everyone, I would like to know if you can modify the attached bot so that it only does operations when the price does not exceed the +2 or -2 barrier for 3 minutes for example. a cordial greeting.
[Barrera fuera 2 mas menos.txt](https://github.com/binary-com/binary-bot/files/3598040/Barrera.fuera.2.mas.menos.txt)

**Comment by xremmy** [comment]
Try this
[Barrera fuera 2 mas menos editt.txt](https://github.com/binary-com/binary-bot/files/3599503/Barrera.fuera.2.mas.menos.editt.txt)
