### ISSUE TITLE
Candle High/Low [Bug]

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#1925]
I have a bot that depends on the High and Low values of a candle to make it's predictions.  (specifically when the high/low reaches the outer bounds of the previous BB Divergence, but that doesn't matter)

It keeps 'not' picking trades that I'd expect it to, and upon bug testing, it appears that these:

![image](https://user-images.githubusercontent.com/49715381/64668583-3b8eeb00-d4b2-11e9-8c3e-275d7421fb97.png)

Are seemingly setting my Variables (High, and Low) to the Open and Close values of the candles.

**Comment by ceakuk** [comment]
i got that problem yesterday.
the solution is to use the already completed candle stick which is index 2 from ethe end. you are using index 1 which changes with every tick

**Comment by ceakuk** [comment]
set time to old candlestick time and only new time is greater then new candle stick time is updated. everything in that if loop
![Unbenannt](https://user-images.githubusercontent.com/43122491/64689652-0a50f380-d48f-11e9-8c33-5bd89a526a87.PNG)
