### ISSUE TITLE
how to copy from binary.com blocky files?

### ISSUE THREAD

**Issue by ceakuk** [binary-com/binary-bot#1926]
Hi,
I would like to copy some of my codes/blocky from different .xml files into my working file. is it possibly by any means?

Its such a duplication of effort to keep re-writing old codes/blocky into new strategies.
Thanks in advance for any suggestions

**Comment by nextnaro** [comment]
Save as collection tick on ✓or right click on main block > download. Open master file > open again collection file all block from collection file will include to screen.

**Comment by hotmatrixx** [comment]
it will only transfer inot the new block if both blocks are saved with the tick, and there are no duplicate variables between the two blocks
