### ISSUE TITLE
How to divide martingale into 3 parts

### ISSUE THREAD

**Issue by Goodluckwal** [binary-com/binary-bot#1929]
Hello friends and guys....
I have a problem regarding money management : how to divide the Martingale factor into 3 parts. for detail please see image below:
![image](https://user-images.githubusercontent.com/55231514/64836982-8cb7ef80-d616-11e9-823a-19f936f9fa74.png)
Would you please help me . Thankyou ....

**Comment by byomartin** [comment]
new variable "countlossmartingale"
if loss then change "countlossmartingale" by 1
if "countlossmartingale"=1 then stake = 0.35x5
if "countlossmartingale"=2 then stake = 0.35x3
...
if win reset to 0
is that what you want?

**Comment by Goodluckwal** [comment]
No , I mean If loss -0.35..then buy price 3.5 divided by 3 
stake 1 = 1.5
stake 2 = 1
stake 3 = 1
