### ISSUE TITLE
Cross

### ISSUE THREAD

**Issue by LoboFJP** [binary-com/binary-bot#193]
Hi everyone

I would like to know if someone can tell me how to program any type crossing, for example when 2 moving averages intersect each other?

Or how to compare the value of 2 moving averages a minute before and a minute later?

Thank you and sorry for my bad english

**Comment by okovalov** [comment]
@LoboFJP I wish I knew where the average (and therefore price) price would be two minutes later from now :)

**Comment by okovalov** [comment]
I dont even need to know exact value.. just - higher or lower :)

**Comment by aminmarashi** [comment]
@LoboFJP take a look at #70 .
