### ISSUE TITLE
Candle identification

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1931]
Can any one tell me how the candles are identified? Like, how does the system knows when the candle is red or when it's green?

**Comment by navneetsinh** [comment]
> Can any one tell me how the candles are identified? Like, how does the system knows when the candle is red or when it's green?

![Opera Snapshot_2019-09-13_183116_bot binary com](https://user-images.githubusercontent.com/42480287/64864437-b859ca80-d654-11e9-90d6-657b660f0bfe.png)

**Comment by saidforex26** [comment]
[@lasaidhari Block Candles Color Indicator (BCCI).zip](https://github.com/binary-com/binary-bot/files/3610125/%40lasaidhari.Block.Candles.Color.Indicator.BCCI.zip)

**Comment by AFPEMI** [comment]
Thank you guys, but that's not what I'm looking for.
I'd like to know how the bot knows the candles' colors.
Like when you enter the block "is candle black?", how does it know if it's black or not?

**Comment by nextnaro** [comment]
Current price > open green and Current price < open red

**Comment by saidforex26** [comment]
what I reported @navneetsinh  is correct. . You can also use the indicators that I provide ... it will display the number of colors of the candle according to what we are going to analyze

**Comment by saidforex26** [comment]
example
![AFPEMI colorcandle](https://user-images.githubusercontent.com/54820719/64868424-3d35eb80-d637-11e9-8b9d-1668fb70d691.gif)

**Comment by AFPEMI** [comment]
@saidforex26 Thanks for your reply.
What I'm trying to do is to catalog all candles for, lets say, the past two hours
Use the data to identify how many times I had a sequence of 3 green candles and the fourth candle was red and vise-versa.
On top of that I'll build a probability logic to open operations both ways CALL/PUT
I have a script written (attached) but is running too slow and it's not opening the operations at the very beginning of the next candle. It's opening at different times and sometimes doesn't even open at all.
[120 Candles Catalog rev(1).zip](https://github.com/binary-com/binary-bot/files/3611796/120.Candles.Catalog.rev.1.zip)
