### ISSUE TITLE
How to get a functional STOPLOSS

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1932]
please guys, how can I get a functional stop loss that will actually 'stop' the whole trading process once it is reached?

The stoploss has to work this way....

If there's a loss , it changes until the stop loss is reached.  So, it doesn't really has to wait till the whole profit balance equals the stoploss value

What I was able to build only 'notifies or prompts' that stop loss has been reached but will never stop the trade. After the notification, it continues trading.

**Comment by navneetsinh** [comment]
> please guys, how can I get a functional stop loss that will actually 'stop' the whole trading process once it is reached?
> 
> The stoploss has to work this way....
> 
> If there's a loss , it changes until the stop loss is reached. So, it doesn't really has to wait till the whole profit balance equals the stoploss value
> 
> What I was able to build only 'notifies or prompts' that stop loss has been reached but will never stop the trade. After the notification, it continues trading.

![Opera Snapshot_2019-09-14_030740_bot binary com](https://user-images.githubusercontent.com/42480287/64896280-dba86800-d69c-11e9-9402-06a8375f019a.png)

**Comment by eonuoha30** [comment]
Thanks for the aid.

But from my little knowledge, I think this code will only prompt for a YES / NO text.

If yes, it continues trading.
If no, it will only send a prompt message.

And after the PROMPT message, It is likely to continue the trade

**Comment by eonuoha30** [comment]
I can't find the logic that changes the loss if the trade is lost.

Also, I just want the trade to totally STOP once the stop loss value is reached.


As for the stop loss, I want it to change only when there is a loss until total lost equals stoploss ( and not necessarily when profit equals stop loss)

So, at stop loss , total profit can be negative or positive

**Comment by navneetsinh** [comment]
@eonuoha30 these blocks works for 
once lost amount >= to stop loss 
ask message for want to continue trading or not 
if answer is Y it trade continue with regular martingale stake
if n trade stops
+++
this is another thing can do with that
Stop trading at  (stake + lost amount)  >= stop loss
as result trade will not continue 
if total lost amount + next stake value is >= stop loss
in that case bot will never taking trade >= stop loss
---
or Is there any other condition that I didn't understand?

**Comment by byomartin** [comment]
I'm stuck here too. The bot has no STOP function so I don't know how to really stop the bot. Admin you can add STOP function to After trade please?
Or someone can share your STOP when Profit or Loss reached bot?
Thank you.

**Comment by navneetsinh** [comment]
> I'm stuck here too. The bot has no STOP function so I don't know how to really stop the bot. Admin you can add STOP function to After trade please?
> Or someone can share your STOP when Profit or Loss reached bot?
> Thank you.

![Opera Snapshot_2019-09-17_212947_bot binary com](https://user-images.githubusercontent.com/42480287/65058734-5b328180-d992-11e9-9b50-efcf32b35b9f.png)

**Comment by byomartin** [comment]
> > I'm stuck here too. The bot has no STOP function so I don't know how to really stop the bot. Admin you can add STOP function to After trade please?
> > Or someone can share your STOP when Profit or Loss reached bot?
> > Thank you.
> 
> ![Opera Snapshot_2019-09-17_212947_bot binary com](https://user-images.githubusercontent.com/42480287/65058734-5b328180-d992-11e9-9b50-efcf32b35b9f.png)

I did that but not working. It still makes trade after reaching profit/loss, because I set other function to trade again.
For example if the trade is win then reset martingale and trade again.
Is there any way to really stop the bot, I mean the bot from "running" to "stopped"

**Comment by navneetsinh** [comment]
> > > I'm stuck here too. The bot has no STOP function so I don't know how to really stop the bot. Admin you can add STOP function to After trade please?
> > > Or someone can share your STOP when Profit or Loss reached bot?
> > > Thank you.
> > 
> > 
> > ![Opera Snapshot_2019-09-17_212947_bot binary com](https://user-images.githubusercontent.com/42480287/65058734-5b328180-d992-11e9-9b50-efcf32b35b9f.png)
> 
> I did that but not working. It still makes trade after reaching profit/loss, because I set other function to trade again.
> For example if the trade is win then reset martingale and trade again.
> Is there any way to really stop the bot, I mean the bot from "running" to "stopped"

How can I tell how you have set up?

**Comment by byomartin** [comment]
https://i.gyazo.com/25e7eab379a8de722b5dc8117584d4d1.png
Here is the example. When the total profit reachs profit it will notify but it keeps making new trade.

**Comment by navneetsinh** [comment]
> https://i.gyazo.com/25e7eab379a8de722b5dc8117584d4d1.png
> Here is the example. When the total profit reachs profit it will notify but it keeps making new trade.

your set up for take profit is ok,
what you added value as stop on take profit,,
can you share your full bot image.???

**Comment by byomartin** [comment]
> > https://i.gyazo.com/25e7eab379a8de722b5dc8117584d4d1.png
> > Here is the example. When the total profit reachs profit it will notify but it keeps making new trade.
> 
> your set up for take profit is ok,
> what you added value as stop on take profit,,
> can you share your full bot image.???

the value has no affection. I added them because the bot doesn't stop making new trade.
stk=rst=$0.35 because I use martingale, if I don't add this when the bot makes new trade it will start with the last martingale.
countlosses=0 is to reset the number of loss to 0.
I want to find the way to completely STOP the bot, not PRINT and NOTIFY, like you press Stop button.

**Comment by IQBinary** [comment]
> 
> 
> > > https://i.gyazo.com/25e7eab379a8de722b5dc8117584d4d1.png
> > > Here is the example. When the total profit reachs profit it will notify but it keeps making new trade.
> > 
> > 
> > your set up for take profit is ok,
> > what you added value as stop on take profit,,
> > can you share your full bot image.???
> 
> the value has no affection. I added them because the bot doesn't stop making new trade.
> stk=rst=$0.35 because I use martingale, if I don't add this when the bot makes new trade it will start with the last martingale.
> countlosses=0 is to reset the number of loss to 0.
> I want to find the way to completely STOP the bot, not PRINT and NOTIFY, like you press Stop button.

@byomartin 
![How to get a functional STOPLOSS #1932 01](https://user-images.githubusercontent.com/54183297/65139226-e3b03100-da29-11e9-8c0f-eb278befd0f7.png)

**Comment by byomartin** [comment]
> > > > https://i.gyazo.com/25e7eab379a8de722b5dc8117584d4d1.png
> > > > Here is the example. When the total profit reachs profit it will notify but it keeps making new trade.
> > > 
> > > 
> > > your set up for take profit is ok,
> > > what you added value as stop on take profit,,
> > > can you share your full bot image.???
> > 
> > 
> > the value has no affection. I added them because the bot doesn't stop making new trade.
> > stk=rst=$0.35 because I use martingale, if I don't add this when the bot makes new trade it will start with the last martingale.
> > countlosses=0 is to reset the number of loss to 0.
> > I want to find the way to completely STOP the bot, not PRINT and NOTIFY, like you press Stop button.
> 
> @byomartin
> ![How to get a functional STOPLOSS #1932 01](https://user-images.githubusercontent.com/54183297/65139226-e3b03100-da29-11e9-8c0f-eb278befd0f7.png)
> Get XML : https://github.com/IQBinary/BinaryBot/blob/e00c8edda59cab5eacf664e4bb58698186d61f87/Stop%20Trading%20On%20Getting%20Expected%20Profit%20(Without%20Notification)

thank you. It works. I'm stupid. I have many other condition with trade again so it keeps making new trade. 
Just remove "trade again" and it works fine.

**Comment by drumsmasher** [comment]
I was able to do it like this:
![image](https://user-images.githubusercontent.com/86668666/141196936-baf61103-6ac8-4128-9fcf-130438bf2749.png)

It worked for me.
