### ISSUE TITLE
Help For Learn Loop Blocks

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1935]
Hello everyone,
Please help me to learn `Loop` Blocks,
How does this block work?
And where can this block be used?
If possible give a example.
![Opera Snapshot_2019-09-14_104803_bot binary com](https://user-images.githubusercontent.com/42480287/64903840-30200780-d6de-11e9-8f9d-d4e6e0a5ff09.png)

**Comment by ceakuk** [comment]
![Unbenannt](https://user-images.githubusercontent.com/43122491/64911713-94b28500-d725-11e9-927d-e9acda1f357b.PNG)

**Comment by ceakuk** [comment]
![Unbenannt1](https://user-images.githubusercontent.com/43122491/64911749-f377fe80-d725-11e9-876e-a6b07792dfa4.PNG)

**Comment by ceakuk** [comment]
ist image:
say you want to loop through the last 10  entries in the lastgigit list and if  8 is missing then you  make a prediction that the next match will be 8. you can use them with matchdiff, with overunder or with anything

2nd: image you can also loop through an last digitlist , tickslist, candle sticks  and do the same thing. in this case you get the actual values directly and not the index.

i can give a one one one lesson on a small fee or send me your strategies and i code for you if coding is not your thing

**Comment by navneetsinh** [comment]
> ist image:
> say you want to loop through the last 10 entries in the lastgigit list and if 8 is missing then you make a prediction that the next match will be 8. you can use them with matchdiff, with overunder or with anything
> 
> 2nd: image you can also loop through an last digitlist , tickslist, candle sticks and do the same thing. in this case you get the actual values directly and not the index.
> 
> i can give a one one one lesson on a small fee or send me your strategies and i code for you if coding is not your thing

@ceakuk thanks for response,
I'll check how it maintain, but I think I need more to know about it,
and thanks also for coding for me, and also that coding is not my thing, but I'll learn about creating blocks and how to manage it, that's why I asked for help, if you've more suggestion you can share it at here, But I want to know how these two blocks work.

**Comment by ceakuk** [comment]
here is a good guide. binary.com blockly codes are just using the google blockly 

https://developers.google.com/blockly/

**Comment by navneetsinh** [comment]
> here is a good guide. binary.com blockly codes are just using the google blockly
> 
> https://developers.google.com/blockly/

@ceakuk I already checked it, but it can't fulfill some required parts.

**Comment by navneetsinh** [comment]
@binary-ex-machina
@lasaidhari
@saifforex
Can you help me for this????
