### ISSUE TITLE
(FREE bots) Newest versions of bbTrader up on the site

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1937]
Auto and manual trading platforms have been updated and improved, [here](https://binarybottrading.eu).

All versions feature a fully packed feature list:

-  A full spectrum of money management systems which can be used for manual trading and auto trading.

- Lite and Mobile have pre-built strategies which can be used right away.

- Pro (pro as in technical level. It is still FREE!) has fully-fledged strategy builder able to use machine learning pattern detection for all major candlestick patterns, as well as S&R triggers and technical indicators, and other price action triggers. These can be saved and loaded and shared between users. All triggers can be mixed together and require all or any signal to trade giving an unlimited amount of strategies easily built without blockly or code :)

- Full high-quality charting built into all platforms.

- Manual overrides so you can take over the auto-trading and intervene at any point.

- Full online support from me via the discord server or email.

Check out all the versions here: [https://binarybottrading.eu](https://binarybottrading.eu)

**Comment by ceakuk** [comment]
shouldn't you make a video explaining what is this platform?
how is it related to binary.com or is it alternative?
if related then how do you make money or through conflict of interest?
do i deposit money with binary.com or i have to trust you with my hard earned cash?
too many unanswered questions

**Comment by ceakuk** [comment]
we also need to see how your real account is doing trading with this so called improved platform. make a video

**Comment by wilburforce83** [comment]
@ceakuk, you're always bashing my stuff and asking the same stupid questions which others, not even me, have answered previously. I'm not really sure what your problem is? You seem perpetually suspicious yet unwilling to educate yourself with simple due diligence. 

To answer your sensible question; Yes, I am putting up some tutorial videos soon, the platforms have been in alpha and early beta testing for a while, any help can be got from our discord server, there is a getting started tutorial on the website too for bbPro.

To answer the others;

It uses binary.com, hence why it is here. I use the [binary-live-api](https://github.com/binary-com/binary-live-api) javascript library, as with all javascript you can see the source code under the dev tab of any browser, feel free to analyze and determine for yourself whether I am trustworthy.

I make a 1% commission on **winning trades only** via the developers.binary.com application registration system. As you can see, it is not in my interest at all to produce something that makes you lose money, as I wouldn't make anything either.

I'm not sure how you think binary.com works, but the trades are placed through a secure websocket, the same API call is used for virtual and live accounts- I can't manipulate anything without the code showing it - and trust me, enough people know javascript for anything fishy to be picked up upon very rapidly, this can be independently verified by anyone willing to make the effort, if you are still suspicious. Anyhow, just use a virtual account token and try it out, you're not risking anything:

https://www.binary.com/en/user/security/api_tokenws.html (select read and trade only).

**Comment by Kosta92** [comment]
Can you add 'maximum stake', 'maximum Martingale level' and 'maximum cumulative losses' info to the bottom status bar? Something like permanent "MG STEP" and "CUM. LOSSES" for the entire duration of the session. I need to know how much money was at stake when I check the trading status after some hours of auto trading.

**Comment by wilburforce83** [comment]
Yeah definitely. The data is already being stored for pretty much all statistics so I just need to add to the bottom bar. Which version are you using? Mobile, lite or Pro? Cheers

**Comment by Kosta92** [comment]
I'm using the Lite version, but it should be available for all versions.

One more thing you can add. There should be an option for a custom progression style, something like a list of stakes that we can type for the bot to use.

**Comment by chumui91** [comment]
![image](https://user-images.githubusercontent.com/41452501/65656414-f9d17900-e049-11e9-9d63-e47d86b4d3eb.png)
error???

**Comment by wilburforce83** [comment]
It looks like you arent logged in due to your token being invalid. In the top right it should be showing your account details? If not you haven't entered a correct code. Thanks :)

**Comment by anton-binary** [comment]
Hi wilburforce83,

We love the open sharing of knowledge, but we don't encourage advertising and selling your applications here. This repository is used to help others, report issues, request new features, etc. 

We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: [https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today](https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today). 

You can also contact marketing@binary.com to learn more about partnership options.

Best regards,
Anton
