### ISSUE TITLE
please help make bot

### ISSUE THREAD

**Issue by lupus-00** [binary-com/binary-bot#1940]
hi guys,,
pls help me make a bot with a rule just open on a new candle, if the previous candle is up so it buy  RISE and if the previous candle is down it buy PUT..
thanks...

**Comment by eonuoha30** [comment]
You won't achieve much with that.

More of 50% win rate. 

I've seen results from many similar bots here.

....always 50% win . same thing you'd get even without analysis

**Comment by lupus-00** [comment]
can u help me with my request bot??
