### ISSUE TITLE
How to make a bot if the current price met the condition?

### ISSUE THREAD

**Issue by Charlescpe** [binary-com/binary-bot#1944]
![giitthub](https://user-images.githubusercontent.com/54802854/65005660-2ba05c80-d933-11e9-8b27-02cfc88df985.png)

Can anyone please help me?
Im just a beginner building a bot

**Comment by saidforex26** [comment]
![rsi100 5](https://user-images.githubusercontent.com/54820719/65012101-e289e180-d90d-11e9-90e0-73deead25ecc.jpg)

**Comment by Charlescpe** [comment]
![erorrrrrr](https://user-images.githubusercontent.com/54802854/65012690-dec88000-d94a-11e9-95d7-8762a943ff34.png)

@saidforex26 this is my strategy sir if rsi100 value +  rsi 5 value = is less than or equal to 48, purchase rise even if the current price is moving , im having problem with the input list of rsi how can i implement my strategy not depending on the candle

**Comment by saidforex26** [comment]
![rsi100 5](https://user-images.githubusercontent.com/54820719/65017255-300e4a80-d91e-11e9-8ef5-fa98c8b579fe.jpg)

**Comment by Charlescpe** [comment]
![65017255-300e4a80-d91e-11e9-8ef5-fa98c8b579fe](https://user-images.githubusercontent.com/54802854/65021623-12fb6b00-d962-11e9-9902-4e0b565f3ec2.jpg)

@saidforex26  sir what is the use of this can you explain to me? thank you sir for responding

**Comment by saidforex26** [comment]
it is detecting time. 300 is taken from a period of 1 minute equal to 60 seconds so 60x5 = 300. then every 297 seconds the bot will open a position every 5 minutes for a new candle
