### ISSUE TITLE
Minimum stake of 0.35 and maximum payout of 100.00. Current payout is 125.04.  new limitation?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1945]
New limitation?

**Comment by Hooponopono** [comment]
yesterday give to me same error, today no

**Comment by navneetsinh** [comment]
Minimum stake of 0.35 and maximum payout of 100.00. Current payout is 125.04. new limitation?

this is the same error what I got in rise-fall bot, and bot couldn't run.
At the same time a differs bot is playing normally.

**Comment by Hooponopono** [comment]
yesterday i got it on smarttrader
