### ISSUE TITLE
Binary.com BOT

### ISSUE THREAD

**Issue by Ashlep95** [binary-com/binary-bot#1948]
Hi there, I am requesting a very screenshot of a very simple BOT I am trying to create.

The Bot to place a trade in the direction of the previous candle.

E.g. on the 5 min chart, 5 Min candle closes bullish, a CALL trade is placed for 5 mins continuously placing trades in the direction of the ptevious candle Until turned off. 
Very simple but for some reason can not have an easy explanation / screenshot of how to do this, can anyone please help? It is quite urgent. 

Possible Martingale also... 

Cheers in advance

**Comment by Craziestar36** [comment]
I understand why are you asking for this, because even i too have observed  
that most of the time candles occurs in pairs(almost like 75-80% of the time 
so that our win percentage would be nearly 70%).

I'm trying to work on it and i prefer less volatile pairs so as to decrease the possibility of market turning against us.

**Comment by Ashlep95** [comment]
Exactly... 

Human interaction would be needed for filtered pairs (not ranging / sideways) but that's easy enough.

Just need the Bot to place the trades. Surely that's easy enough?

**Comment by hotmatrixx** [comment]
@OP
I think you meant that in a bullish candle it would PUT, not Call?

anyway. 
![image](https://user-images.githubusercontent.com/49715381/65366619-91b21a00-dc7a-11e9-918d-03bba79b4465.png)

**Comment by hotmatrixx** [comment]
[ashlep95 simple put call martingale(1).zip](https://github.com/binary-com/binary-bot/files/3638315/ashlep95.simple.put.call.martingale.1.zip)

**Comment by Ashlep95** [comment]
oh wow mate, thank you very much for that did not expedct someone to actually comment exactly what I was looking for, that is extremely hard to find these days.

thanks so much mate,

That 'Strategy' file isnt working though as I can only access major and minor FOREX pairs here in Asutralia

Ill try those inputs and see how I go, thanks alot again mate, really do appreciate it

**Comment by Ashlep95** [comment]
Can someone open that file and change it from the indexes to a forex pair? I can't open it otherwise :(

Thanks!

**Comment by Ashlep95** [comment]
> [ashlep95 simple put call martingale(1).zip](https://github.com/binary-com/binary-bot/files/3638315/ashlep95.simple.put.call.martingale.1.zip)
> 
> I ran it like this for about 20 minutes, it risked about $200 and made about $170.
> You could tweak the Martingale down to around 1.8, I think but over time I"m pretty sure that somewhere you will have a bad run, and a bad day.
> still.
> 
> was fun

Hi mate, please see my reply, I can not open file due to INDEXES are not available here in Australia. Would there be a change you could change it to a FOREX paid and then send back again? 

Also does it open at the close of the current candle / open of the next? As I have trialled those blocks in that sequence you have and it enters at all random points, based on ticks not on the candle at all?


thanks mate

**Comment by Craziestar36** [comment]
Hello hotmatrixx.
  Actually the bot that you posted here,I tested it everyday between 11:00 am to 02:00pm(3 hours-INDIAN TIME) and it consistently makes $600-$800 risking about $200( 3 times minimum each run) and never gave a badrun/loss.
The requirement is that you need a minimum of $1000 account to make profits everyday.

If you are the designer of the bot,is there anyway you could reduce the risk it takes and can manage to run on a minimum $100-$200 account.
If yes please notify with an update of the bot!!!  Thankyou.

**Comment by Fidzl** [comment]
> Can someone open that file and change it from the indexes to a forex pair? I can't open it otherwise :(
> 
> Thanks!

Hi there please send me your gmail address so that i can send you the amended file
