### ISSUE TITLE
How to update a list

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1949]
if we crate a list, it becomes coma " , " separated.
if we want to use them with other sign instead of coma " , " separated.
current get in list
a,b,c,d,
but if want 
a*b*c*d*
so how can get it??

**Comment by pauloceia** [comment]
Why sometimes appears message "data longer then data time" ???

**Comment by saidforex26** [comment]
@navneetsinh  
![navneetsinh  ](https://user-images.githubusercontent.com/54820719/65364608-d0a88700-dc0a-11e9-82ce-79ca9fbb2c76.gif)
example

**Comment by hotmatrixx** [comment]
> 
> 
> Why sometimes appears message "data longer then data time" ???

becuase lists are not allowed to be more than 1000 entries long

**Comment by hotmatrixx** [comment]
> 
> 
> if we crate a list, it becomes coma " , " separated.
> if we want to use them with other sign instead of coma " , " separated.
> current get in list
> a,b,c,d,
> but if want
> a_b_c_d_
> so how can get it??

do you want a numbers or letters list?
oh you want to use Underscore for your delimiter? the formatting treats that oddly in github so I couldnt see you used them as a delimiter.

here.
![image](https://user-images.githubusercontent.com/49715381/65366517-1bf97e80-dc79-11e9-87e0-13e21a666e15.png)

**Comment by navneetsinh** [comment]
hello, @saidforex26 and @hotmatrixx ,
thanks for reverting, and both of your idea's are good, checked done,
I've another one query,
I've a list for confirmation
with list of (u,v,w,x,y,z,uw,vx,wy,xz,yu,zv,uxu,vyv,wzw,xux,yvy,zwz)
if any of one confirmation gets from list(u,v,w,x,y,z,uw,vx,wy,xz,yu,zv,uxu,vyv,wzw,xux,yvy,zwz),
make confirmation true
so in that case from given list if 
notification shows for "w", confirmation true
notification shows for "yu", confirmation true
notification shows for "wzw", confirmation true
this type of
not only for this 3 given example but all for given list.
@saidforex26 , @hotmatrixx , 
try to help for that,
if you won't create block not to worry, but please teach me how to do that, I'll try to create it.thanks,

**Comment by saidforex26** [comment]
try sending the bot you are making. I will add an example

**Comment by navneetsinh** [comment]
> try sending the bot you are making. I will add an example

thanks for reply @saidforex26 ,
here is attached a file,
in file upper confirmation setup is correct, but it's lots of blocks with " or ",
I want it in short form getting from a given list.

[want to set list configuration.txt](https://github.com/binary-com/binary-bot/files/3639927/want.to.set.list.configuration.txt)

**Comment by saidforex26** [comment]
what you made is wrong. indeed making a list is correct but taking one of the same lists is not like that logically.

**Comment by navneetsinh** [comment]
no, I don't want to take from the same list,
here setup in 2nd block is actual, but it is taking lots of blocks,
I want all the 2nd block setup is in list format, and take output from list

in ignored block wants correction, 
I created a list, but I don't know how to use this list as

confirmation spot = any of value from list
trade true

like that

**Comment by saidforex26** [comment]
Please develop
[navneetsinh  martinggale steps.zip](https://github.com/binary-com/binary-bot/files/3640176/navneetsinh.martinggale.steps.zip)
![martingale steps](https://user-images.githubusercontent.com/54820719/65394461-70d6eb00-dd86-11e9-8858-4f777f2c1f6c.gif)

**Comment by navneetsinh** [comment]
> Please develop
> [navneetsinh martinggale steps.zip](https://github.com/binary-com/binary-bot/files/3640176/navneetsinh.martinggale.steps.zip)
> ![martingale steps](https://user-images.githubusercontent.com/54820719/65394461-70d6eb00-dd86-11e9-8858-4f777f2c1f6c.gif)

Ok, dear one, thanks for giving your valuable time, 
But currently my need is not met yet.
Now I try to explain with your given bot.
In your given bot if result is loss martingale change by step + 1, so it's next one,
But I don't want next one.
Here is confirmation is fixed with " Result is loss' than go for martingale list step + 1
But I've confirmation is not fixed 
it comes from any of value,
I don't know
But if any value comes from the list given, then the confirmation is true.
If can possible please check
![Untitled](https://user-images.githubusercontent.com/42480287/65395154-9c70ca00-ddb4-11e9-8280-134b4acc5585.png)

**Comment by saidforex26** [comment]
sorry, I do not understand what you mean

**Comment by navneetsinh** [comment]
> sorry, I do not understand what you mean

hmm, let me try some other way,
![Opera Snapshot_2019-09-23_041650_bot binary com](https://user-images.githubusercontent.com/42480287/65395538-c4aef780-ddb9-11e9-9abb-489131c6d8b9.png)
[gngfdnn.txt](https://github.com/binary-com/binary-bot/files/3640256/gngfdnn.txt)

**Comment by navneetsinh** [comment]
I got something near,
![Opera Snapshot_2019-09-23_044201_bot binary com](https://user-images.githubusercontent.com/42480287/65395738-9ed72200-ddbc-11e9-862d-4d3445b84c36.png)
[binary-bot (8).zip](https://github.com/binary-com/binary-bot/files/3640266/binary-bot.8.zip)
Here is getting confirmations, but it selecting random value from list, 
if one chosen randomly from list
it doesn't take confirmation for another value from list once clear,
then after it choose another 1 randomly from list

**Comment by saidforex26** [comment]
I understand that. but actually what you want to make. money management or others

**Comment by navneetsinh** [comment]
NO, not for money management, for purchase contract confirmation,
last tick digit comes from given list value 
make confirmation true
not for taking trade, but as per choice of selection confirmation, 
take trade true

**Comment by saidforex26** [comment]
try to learn this
[same digit.zip](https://github.com/binary-com/binary-bot/files/3640319/same.digit.zip)
![same digit](https://user-images.githubusercontent.com/54820719/65396518-dd5de400-dd9e-11e9-8cb5-ec1ef1317a87.gif)

**Comment by navneetsinh** [comment]
> try to learn this
> [same digit.zip](https://github.com/binary-com/binary-bot/files/3640319/same.digit.zip)
> ![same digit](https://user-images.githubusercontent.com/54820719/65396518-dd5de400-dd9e-11e9-8cb5-ec1ef1317a87.gif)

@saidforex26 thanks for supporting, 
I did not get what I wanted but now I am close to it, thanks again.
