### ISSUE TITLE
creating a macdbot

### ISSUE THREAD

**Issue by sudsmax** [binary-com/binary-bot#1955]
hi i am new to blocks and xml programming, so it may be a simple task for many but i am a learner.

I want to create a simple bot that uses macd.
macd main switches side/ macd and signal crossover (we could be able to switch any one parameter or both)
with martingle upto level we can choose the maximum level. please guide how can i program this Thanks

**Comment by saidforex26** [comment]
create macd
![membuat macd](https://user-images.githubusercontent.com/54820719/65393898-125a3e80-dd7f-11e9-807a-a882355a5fd5.gif)

**Comment by saidforex26** [comment]
create martingale. please develop more 
![membuat macd martingale](https://user-images.githubusercontent.com/54820719/65394119-7bdb4c80-dd81-11e9-935a-6c068836769c.gif)

[macd bot.zip](https://github.com/binary-com/binary-bot/files/3640146/macd.bot.zip)
