### ISSUE TITLE
Prediction Sequence

### ISSUE THREAD

**Issue by VeritasEx** [binary-com/binary-bot#1963]
Good afternoon, guys

I'm struggling to make a sequence block,

i want to have a sequence of numbers that i create,

Ex.: 1, 3, 5, 4, 8, 0, repeat

but i'm not finding a way to do it.

anybody knows how to do it?

thanks in advance!

**Comment by ceakuk** [comment]
your explanation is not very clear. if this is not what you mean then  please make another  explanation. you can also make the list using  for loop and even populate it randomly

[binary-bot - 2019-09-24T030523.965.xml.zip](https://github.com/binary-com/binary-bot/files/3645713/binary-bot.-.2019-09-24T030523.965.xml.zip)
