### ISSUE TITLE
How BOT to recognise CLOSE of Candle

### ISSUE THREAD

**Issue by Ashlep95** [binary-com/binary-bot#1965]
Some reason my bot is not recognising the close of each previous candle, anyone else have same issues?

**Comment by ceakuk** [comment]
by default it recorgnizes the close of  candle number 1 from end   every tick.
if you use candle number 2 from end then you will get the close every say 1,2,5,10 minute  etc  depending on your wish. thats the best way. then  on trade again you can delay  next trade by xxx seconds  corresponding to  the minutes you want. alternatively use  if statement on open time from the candles to only proceeed if time of opening  2nd new candle is greater than that of the old second candle

**Comment by ceakuk** [comment]
try and if you cant then send your bot and ill put it for you

**Comment by Ashlep95** [comment]
Ok thanks alot mate I will send once I'm home

All I'm chasing is to open CALL if close of previous candle was bullish. Or open PUT if close of previous candle was bearish. Etc.. and just let it run. 

On AUDUSD

**Comment by Ashlep95** [comment]
For expiration of ONE CANDLE

E.g. on the 5 min chart. 5 min candle closes bullish, and the close of that / open of next a 5 min CALL trade gets placed.. and then repeat etc.

**Comment by Ashlep95** [comment]
> try and if you cant then send your bot and ill put it for you

Hi mate please see above replies. I can not send the file for some reason... Ill try again..

**Comment by Ashlep95** [comment]
[ashlep95.simple.put.call.martingale.1.zip](https://github.com/binary-com/binary-bot/files/3647156/ashlep95.simple.put.call.martingale.1.zip)


Try this one... If you could potetnially assist with the candle close that would be a huge help and I would be very very appreciative. Also is there a chance you could change it to AUDUSD like I asked above? That way I can open the file and check

thanks so much mate

**Comment by ceakuk** [comment]
Did you want something like this?
you can shorten the codes but i thought declearing bullish =false and  bearish = false is better if you want to add other strategies befor call/put

[binary-bot - 2019-09-24T150315.111.xml.zip](https://github.com/binary-com/binary-bot/files/3648964/binary-bot.-.2019-09-24T150315.111.xml.zip)

**Comment by Ashlep95** [comment]
Wow man thanks so much for that!!

That is almost bang on, however the only last issue is I turn it on and it still places a trade immediately and does not wait for candle to close? 

Any assistance with this? 

Thank you very much

**Comment by Ashlep95** [comment]
Oh wait!! No I think we are good now! Just isnt quite lining up but still pretry much perfect I think :)

Much appreciated!

**Comment by ceakuk** [comment]
yes it should not wait but to make it wait, i can help with that one line of code. give me a minute

**Comment by ceakuk** [comment]
now it waits tile the time  you set which is in this case 5 minutes candle to close before starting.
it reads the open time in the candles. good luck
[binary-bot - 2019-09-25T053536.673.xml.zip](https://github.com/binary-com/binary-bot/files/3651738/binary-bot.-.2019-09-25T053536.673.xml.zip)

**Comment by Ashlep95** [comment]
Mate you are an absolute legend. perfect! thank you!!
