### ISSUE TITLE
Massive library of UNSORTED XML files 450+ files

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1968]
Hi everyone!

Since moving over to Node, and building the bbTrader platforms, I have not really been using the XML system. These are a total mess regarding filing, but there are a lot of good strategies floating around in them.

In total there are over 450 XML scripts here. Knock yourselves out, guys!!

[Archive.zip](https://github.com/binary-com/binary-bot/files/3648354/Archive.zip)

**Comment by freedonone** [comment]
`well done chief`

**Comment by Kosta92** [comment]
Holy Mother of God! This is pure gold, right here! And it's FREE! I can't believe it!

Thank you so, so much for this.

**Comment by nobleb2007** [comment]
Thanks for the free gift. How can I use your bb trader platform or send the download page here

**Comment by wilburforce83** [comment]
Hey @nobleb2007 I have mobile, web and desktop app at https://binarybottrading.eu they are also all free to use too :)

**Comment by wilburforce83** [comment]
@Kosta92 hahaha no worries man!

**Comment by Ares31** [comment]
Muchas gracias amigo...
