### ISSUE TITLE
Digit Reading for Matches/Differs

### ISSUE THREAD

**Issue by VeritasEx** [binary-com/binary-bot#1973]
Hi Everyone!

I saw some issues in this forum, some guys here have really good skills in using the platform and I have a doubt, is it possible for the bot, to read the tick and based on sequences of last digits, to take a trade?

Ex.:

Tick 1 = 1962.6**4**
Tick 2 = 1962.7**4**
Tick 3 = 1962.8**4**

Then, take a trade on "Differs 4"?

Thanks guys!

**Comment by poroinika** [comment]
[Differ 4.txt](https://github.com/binary-com/binary-bot/files/3653518/Differ.4.txt)

**Comment by Glexmoney** [comment]
> [Differ 4.txt](https://github.com/binary-com/binary-bot/files/3653518/Differ.4.txt)

great work but pls can code the version that can trade any last digits that have that kind of 3sequence on differ and not just limited to just 4, any of the digits that give the signals?

**Comment by VeritasEx** [comment]
Perfect example, @poroinika, thank you very much!

exactly what i needed.

:D

**Comment by saidforex26** [comment]
easy tutorial

if you use digit analysis 0,1,2,3,4,5,6,7,8,9 then you can use the last digit

if only digit 4 then you can input 4

if it's not just 4 but other digits too, for example 2,4,5 and others
 okay
donation: paypal.me/lasaidhari
![VeritasEx differss same](https://user-images.githubusercontent.com/54820719/65643998-ffe43d00-dfea-11e9-8eb6-318b4ef8fcc6.gif)
[differs same digit.zip](https://github.com/binary-com/binary-bot/files/3655066/differs.same.digit.zip)
