### ISSUE TITLE
There is definitely a few in my download pack #1968

### ISSUE THREAD

**Issue by sudsmax** [binary-com/binary-bot#1977]
There is definitely a few in my download pack #1968

_Originally posted by @wilburforce83 in https://github.com/binary-com/binary-bot/issues/1975#issuecomment-535429448_

It's a huge collection but i am afraid i can't find a ema crossover with martingle in that collecction. Still searrching

**Comment by waltergrant** [comment]
next time better search closed issues
https://github.com/binary-com/binary-bot/issues/1784
and martingale can find in:
https://github.com/Fruitfella/ROBOT-binary
