### ISSUE TITLE
HELP - TIME OF CLOSE CANDLE

### ISSUE THREAD

**Issue by GeorgeTelles** [binary-com/binary-bot#198]
I'm trying to make a robot that opens the order exactly the moment the candle closes.

Basically I want the following strategy:

1. If the spark plug is low -> CALL
If you win -> CALL
To get lost -> PUT

2. If the candle is high -> PUT
If you win -> PUT
Is lost -> CALL

Can someone help me ? My biggest difficulty is to take the time at the end of the candle.

**Comment by aminmarashi** [comment]
I guess there's no significant difference between the moment a candle closes and another candle opens.
You can use [is candle new](https://gist.githubusercontent.com/aminmarashi/7cd7be9f3ce9004de767f4d4f6a6c5a0/raw/is%2520candle%2520new.xml) block.
You can find the strategy [here](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/alternate%2520call%2520put%2520on%2520loss.xml).
And more similar strategies [here](https://gist.github.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb#alternate-callput-on-loss)

You can find your desired strategy which is a combination of the above blocks [here](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/alternate%2520call%2520put%2520on%2520new%2520candle.xml)
