### ISSUE TITLE
Please Help! binary bot Profitable strategy 

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#1981]
Dear friends ,

At the beginning and so far I have completed two years in trading and I regret to tell you that I lost all my money,

On the professional level I have two baccalaureate degrees and many international courses, and so far I have not found any work in my certificates,

I have a family and two children, I need as much money as anyone in the world, especially those who face every day a problem with money,

We all know that even if you have the most profitable strategies in the world, you will not be able to raise all the money in the world, and that in the end we are human and have a love for help and humanity,
So please my friends, help me to be able to spend on my family as a man. I would be grateful to you all the time.

binaty option strategy
 Best regards
ahmadhusam112@gmail.com

**Comment by wilburforce83** [comment]
@ahmadhus hi there, may I ask, what sort of trading were you doing before when you lost your money?

**Comment by ahmadhus** [comment]
@ wilberforce 83 hi my friend, first of all thank you for your respond,
i tried many type of trade, in forex, in binary option, digital, trading in companies,
Platform iَQ option, Q8 trades

i lost all of my money , but what to do ?!

You can say I tried several times, but unfortunately, always loses  , 

best wishes ,
ahmadhusam112@gmail.com

**Comment by Tebu1429** [comment]
Hello Guys , 

I really need help on binary.com 
I've been loosing my money day in day out. I can even make just $10 a day .

Please help with any strategy guys .

Thank you!

**Comment by ahmadhus** [comment]
@Tebu1429 

all respect . 

so am i ..

i hope that some one will help us .

**Comment by Tebu1429** [comment]
@ahmadhus, 

I can't anymore . can't afford to loose everytime.
