### ISSUE TITLE
 blocks needed .! help

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#1984]
Dear all ,
in last digit match ,
if i want the expected last digit to be the last digit in the point that i opened the trade ,
example :
311.7830 is this point that i will open a trade on it so the bot will open the trade with except last digit match to be zero because whenthe bot was opened the trade was the last digit  311.7830 (end with zero ) the last expected digit 0 

example 2 
if  311.7521 the bot will open the trade with expectation last digit match to be 1 

please help me with the blocks needed .

**Comment by ahmadhus** [comment]
Dear @Fruitfella can you help me please

**Comment by windjenn** [comment]
> Dear all ,
> in last digit match ,
> if i want the expected last digit to be the last digit in the point that i opened the trade ,
> example :
> 311.7830 is this point that i will open a trade on it so the bot will open the trade with except last digit match to be zero because whenthe bot was opened the trade was the last digit 311.7830 (end with zero ) the last expected digit 0
> 
> example 2
> if 311.7521 the bot will open the trade with expectation last digit match to be 1
> 
> please help me with the blocks needed .

[DIFFER  2019txt.txt](https://github.com/binary-com/binary-bot/files/3668692/DIFFER.2019txt.txt)
here is a bot made for digit differ , it trigger trade on ur selected digit , means if u want bot to take trade on 0 it will trigger whenwhever there wld zero come at last , 
but im willing to know how u will use it for digit match ? any wrking strategy , well digit trades are quite random

**Comment by ceakuk** [comment]
just not just create a list everytime you send a trade  you insert the last digit
