### ISSUE TITLE
binary-live-api support please

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1987]
@aaron-binary 
@aminmarashi-binary 

The binary-live-api issues page doesn't appear to be at all active. Please, can a Dev from here help me with the below issue:

https://github.com/binary-com/binary-live-api/issues/137

Thanks

Will

**Comment by aaron-binary** [comment]
Hi @wilburforce83,

Please post this on https://binary.vanillacommunity.com/ and someone should be able to help you out there. We don't maintain `binary-live-api` as we're working on a new API library.

Regards,
Aaron

**Comment by wilburforce83** [comment]
Thanks, sorted now.
