### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#1988]
Hello.
I found a bot on the web that is password protected.
can anyone help me by coding this field

[Files.zip](https://github.com/binary-com/binary-bot/files/3678271/Files.zip)

**Comment by sinung21** [comment]
YOUR BOT PASSWORD IS '' boss''

**Comment by saarsalu** [comment]
> YOUR BOT PASSWORD IS '' boss''

Tanx
