### ISSUE TITLE
UI Refactor

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-bot#199]
- [x] Use [jQuery UI](https://jqueryui.com/) for all panels
- [ ] Integrate `Summary` into the header
- [x] Separate `Chart`, `Trade Info` and `Log` windows
- [x] Create `Log` window
- [x] Convert `Trade Info` to react #196
- [x] Make `Log` and `Trade Info` infinitely scrollable
- [x] Save/Load `Log` and `Trade Info` data offline

**Comment by nextnaro** [comment]
Make Log and Trade Info infinitely scrollable already done?

Possible put auto scroll ? or put latest on top? sort by latest first like that.
