### ISSUE TITLE
Candles

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1991]
How can I count how many green candles, or red candles, in a period of 24 hours?
One minute candles.
Thanks.

**Comment by ceakuk** [comment]
Unfortunately you can only access 1000 candles which is like 1000/60 = 16.7 hours.

![Unbenannt](https://user-images.githubusercontent.com/43122491/66233364-74099980-e6eb-11e9-9083-4324d047fcdd.PNG)

if that is enough data points for you, in my can I would just use a for loop like below. I hope it helps.
as you can see sum of green+red is sometimes less that the total in cases where the open=close
[binary-bot - 2019-10-04T152711.596.xml.zip](https://github.com/binary-com/binary-bot/files/3692002/binary-bot.-.2019-10-04T152711.596.xml.zip)
