### ISSUE TITLE
Bot freez

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#1994]
Hello.
I can't use the robot because the page stays loading.

if I don't log in, the page will load.

if i log in i will not reload the page.

this joke lasts for 3 days.

today I called Binary.com
and they said my net was slow.
the same concern with the phone net as with the computer.

net is not at all slow.
![Screenshot_20191003-113355_Chrome](https://user-images.githubusercontent.com/30391002/66133180-e81a4380-e5fe-11e9-8f8d-4a895a2c5914.jpg)
![Screenshot_20191003-122813_Chrome](https://user-images.githubusercontent.com/30391002/66133181-e81a4380-e5fe-11e9-87f8-d3d16b4b5d8d.jpg)
![Screenshot_20191003-165600_Speedtest](https://user-images.githubusercontent.com/30391002/66133182-e8b2da00-e5fe-11e9-8dcb-92fbdab0932f.jpg)

**Comment by saarsalu** [comment]
[
![Kuvatõmmis (1)](https://user-images.githubusercontent.com/30391002/66152487-3a209080-e622-11e9-8478-85d8d9a4d2de.png)
![Kuvatõmmis (2)](https://user-images.githubusercontent.com/30391002/66152488-3ab92700-e622-11e9-9acc-478a57bd8ee4.png)

](url)

**Comment by anton-binary** [comment]
Hi @saarsalu,
We're working on the fix right now. Should be done soon.
Thanks,
Anton
