### ISSUE TITLE
Running BOT on VPS and logging into the binary account using my personal computer

### ISSUE THREAD

**Issue by kan-il** [binary-com/binary-bot#1995]
I'm running my bot on a VPS in Lithuania and I'm located in Sri Lanka. So the bot will be logged into my binary account from a Lithuania IP address while I will be using my local personal computer to monitor the trades. Will it be a problem since there are two logins at the same time with two different locations?

**Comment by Craziestar36** [comment]
Probably no!!

**Comment by ceakuk** [comment]
@kan-il 
Please let me know when you get the answer.  better  send a ticket. I'm also waiting to hear from them about  this
