### ISSUE TITLE
there is a BUG on bot.binary.com

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#2002]
there is a BUG on bot.binary.com

![there is a BUG on bot binary com](https://user-images.githubusercontent.com/54820719/66208444-fa52bb00-e6ac-11e9-908a-0700e0ff5f83.gif)

**Comment by poroinika** [comment]
Yes same problem....

**Comment by ceakuk** [comment]
@saidforex26 
finaly someone  also experiencing this problem. it has driven me crazy the whole day plus  long gone are the days binary.com would assist you instantly on chat

**Comment by ceakuk** [comment]
@saidforex26 
How do you create the video of gif

**Comment by danishbeg** [comment]
You can use the <WIN> + G to open up the Gaming Console in Windows 10. Then you can record video of screenshot.

**Comment by saidforex26** [comment]
@ceakuk You can download it at https://www.screentogif.com/

**Comment by saidforex26** [comment]
#2002

**Comment by Goodluckwal** [comment]
> there is a BUG on bot.binary.com
> 
> ![there is a BUG on bot binary com](https://user-images.githubusercontent.com/54820719/66208444-fa52bb00-e6ac-11e9-908a-0700e0ff5f83.gif)

Yes, same problem.....

**Comment by sandramanaka1** [comment]
@saidforex26,  
yes same problem

**Comment by aaron-binary** [comment]
This should be resolved now, please let us know if this issue persists.
