### ISSUE TITLE
What the hell is wrong  with volatility index?

### ISSUE THREAD

**Issue by ceakuk** [binary-com/binary-bot#2005]
Somehow  since this morning, I can not work onvolatility index. all the orthers like forex, smartfx, commodities work but if i  go to volatility index, it  changes instantly to smartfx.

Is anyone experiencing the same problems?
My servers are in US because its more reliable there. I wonder if since today,  binary.com could have  put a restriction  on that or is it just some crazy bug in their  system

**Comment by danishbeg** [comment]
There is a bug. I'm facing the same problem from UK, and also from Pakistan.

**Comment by saidforex26** [comment]
this happens only on bot.binary.com. some functions have been added but some coding is having problems. #2002

**Comment by saidforex26** [comment]
@aaron-binary @anton-binary @aminmarashi-binary @arun-binary @sam-binary @tom-binary @b

**Comment by aaron-binary** [comment]
This should be resolved now, please let us know if this issue persists.

**Comment by ceakuk** [comment]
@aaron-binary 
thank you
