### ISSUE TITLE
"The Under market have moved to much" but it kill the martingale bot step....

### ISSUE THREAD

**Issue by crypto-maniac** [binary-com/binary-bot#201]
Hello i  have setup a simple martingale bot 
https://bot.binary.com/bot.html
but sometime this give error :"The Under market have moved to much ........"

the problem is its happend sometime when the martingale is at step 3/4/5/6/7 

![image](https://cloud.githubusercontent.com/assets/8384676/25112273/7929ff4c-23f0-11e7-8ce4-4a094c039ed8.png)

also its stoped at -127 dollars i could not recover them 
71	27750855568	PUT	956.010	956.018	127.52	0.00	-127.52

its demo account so that ok , but could you fix that part please ?
the error should not stop the martingale step , because its not enough stable ..

thanx you

**Comment by crypto-maniac** [comment]
its happend again at a big martingale step...

![image](https://cloud.githubusercontent.com/assets/8384676/25112562/6259abb2-23f2-11e7-99cd-db53ac9bf7c5.png)

**Comment by aminmarashi** [comment]
same as #158. Will be fixed in the next major release.

**Comment by frxncisjoseph** [comment]
Don't use if you don't know anything about the martingale method or programming. 

You'll lose money as you just have.

**Comment by crypto-maniac** [comment]
yeah well we didn't wait for ya ffxncisjoseph ...
