### ISSUE TITLE
I Need to salve a problem in my BOT. CAN YOU HELP ?!

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2011]
Dear All . 

with regards .

i need to apply the strategy and if i loss the trade ,the recovery will be in the next 3 trades , 

Run Diff .zip](https://github.com/binary-com/binary-bot/files/3694844/Run.Diff.zip)

can any one help me ? 

wish you luck .

**Comment by ceakuk** [comment]
i must say  such a simple bot is just too bulky with to many an necessary codes. would you like a simple one doing the same thing.
As a caution though,  it won't be profitable.
waiting for 2, 3,4, 100000 similar last digit does not add to the odds of you winnning. it just means  fewer trades so in stead of loosing everything in 1 hour, you loose it in a day or longer

**Comment by ahmadhus** [comment]
dear @ceakuk 
your point of view seems to be right ,
but the main question for you is what should we do ?

how we can generate a strategy that will give us higher profitable percantage ? 

in my case , i filtered more than 600 bot ,

and i did not find any bot that can work in low balance of money .
so if you have strategy that is profitable . please share it with me , and i will be thankful until the death ,

and same to me if i have ,i will share it with all members here , because if i will trade from today until the death i will never collect all the money ,

so i will share the strategy with all member to make not just my life better , but make all of them life's better ,

regards .

**Comment by saidforex26** [comment]
to get a bot with a small capital is not possible to run for hours. even though your strategy is correct but with a tick duration and every tick has a random number in the volume there will be loses many times. if you use martingale, you will need large capital.

**Comment by ahmadhus** [comment]
@saidforex26
that is right , so what should i do , which strategy should i ues  ?

all respect

**Comment by saidforex26** [comment]
get one bot and a virtual test. analysis of the right time to use a bot with a small capital. if you get the right time to run the bot with the capital you need, use that time to use the bot and set your target profit

**Comment by ahmadhus** [comment]
how can i know which time is the perfect time ?
do you have any idea about the perfect time in general ,

**Comment by saidforex26** [comment]
all depends on the bot used. Every strategy in the bot has a different time. therefore, use 1 bot and analyze the correct time by looking at the tranding history

**Comment by ahmadhus** [comment]
@saidforex26 

digit differs or match .. no need for aspecific  time . 

but i think all the other types need specific time to trade .

okay brother , do you have a good strategy ? 

best wishes

**Comment by saidforex26** [comment]
sorry i can't give my strategy. because maybe my strategy actually harms you going forward ... I hope you can find your own strategy because the financial risk is in your own hands.

**Comment by ahmadhus** [comment]
@saidforex26 

be sure that i respect you and your opinion ,
but anyway , even if you give me a strategy i will test it many time , and no matter what happens it is on my hands

thanks alote

**Comment by olireggae** [comment]
Dear all,  
I have come across a strategy called the bmat strategy to trade volatilities. It seems profitable can this be converted to a bot for the benefit for all in the house??
N.B ( I have videos of the strategy, I can share it here. kindly let me know. Thanks!

**Comment by saidforex26** [comment]
please share the video. I see

**Comment by olireggae** [comment]
@saidforex26 

Here is a link to the first 2 part of video. Try it and let me know if it is possible to create a bot for this. Thanks
https://drive.google.com/file/d/1bAU5ioXnpU4MrKbXkUpc9gda4wzvgJ5D/view?usp=sharing

**Comment by ahmadhus** [comment]
@olireggae 

it is soo good my friend , 

we need some one to make it bot .

regards

**Comment by olireggae** [comment]
> @olireggae
> 
> it is soo good my friend ,
> 
> we need some one to make it bot .
> 
> regards

Good to hear, I have others who work greatly as well. But let's get started with this to develop into a BOT. I will share the remaining parts as well.

**Comment by ahmadhus** [comment]
perfect , i will try to share it , 

to see if we find someone . 

Plz if you find , share is with me . and same to me ,

all regards

**Comment by Eshhh** [comment]
As told by @binary-ex-machina its impossible to make ADX indicator with blocks.

**Comment by ahmadhus** [comment]
@olireggae 

hope find you well ,

any update ?
