### ISSUE TITLE
bot purchase every minutes

### ISSUE THREAD

**Issue by lupus-00** [binary-com/binary-bot#2012]
hello master
it's possible to make bots that make purchases every minute??
ex :
bot purchase on 12:01:00 for 5 tick then purchase again on 12:02:00 for 5 tick

**Comment by ceakuk** [comment]
click on step 1 (binary), step 2 (tools), step 3(time), then drag the blocky to the trade again and set the number of seconds you want.

unless you want it to be specifically the  first 5 ticks a new candle is formed then we can do it differently
![Unbenannt](https://user-images.githubusercontent.com/43122491/66326123-bec42500-e928-11e9-82b5-8582eece249a.PNG)

**Comment by lupus-00** [comment]
yes that was i mean..
first 5 tick in new candle..
