### ISSUE TITLE
Money Management - try to recover loss after 2 consecutive wins

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2014]
Hi.

Can anyone help me set up money management strategy that compounds lost stakes and only places a combined stake when there are two consecutive wins, hoping that the third winning stake, if it happens, recover the previous loss? The strategy should also come with a simple math in order to cover for the loss due to lower % of the return (which is ~94% for the Rise/Fall stakes starting with $1).

Example:

$1 - LOST
$1 - LOST
$1 - WON
$1 - LOST
$1 - WON
$1 - WON
$3.21** - LOST
$1 - LOST
$1 - LOST
$1 - WON
$1 - WON
$8.78*** - WON

** $3.21 is a combined loss of the three previous lost stakes + 7% (1+1+1=3 +7% (0.21) =$3.21)
*** $3.29 is a combined loss of the six previous lost stakes + 7% (1+1+1+3.21+1+1=8.21 +7% (0.57) =$8.78)

I really hope you guys can understand all of this.

Thank you.

**Comment by ceakuk** [comment]
@Kosta92 
I could help you with that. though I'm sure it wont work.  I did that before, recouvering all lossing in 1 go is a terrible idea. maybe recover  it in 3 steps or something

**Comment by Kosta92** [comment]
@ceakuk 
Can you help me with this?

**Comment by thommmaz** [comment]
This is exactly I'm looking for too. Can someone help?

**Comment by overwatch873** [comment]
Its good money management....but you need to implement a block that calculates the  total amount of loss you have made....so that after a streak of winning trades the bot will try to recover the loss you made based on the previous trades... Thereby keeping your stake size small

**Comment by Linda-maxw** [comment]
Revenant cyber hacker has earned a well-deserved reputation within the Bitcoin community. Their commitment to excellence, combined with their customer-centric approach, has garnered the recognition and trust of both individuals and businesses. Revenant cyber hacker's positive reputation is a testament to their dedication to restoring faith in Bitcoin by providing reliable and effective recovery services. Revenant cyber hacker services have played a crucial role in rebuilding trust in the Bitcoin ecosystem. By successfully recovering lost or inaccessible Bitcoin, they have demonstrated that there is help available when things go wrong. Their expertise has shown individuals and businesses that they don't have to lose hope in the face of seemingly irretrievable digital assets. Revenant cyber hacker has proven that faith can be restored, even in the volatile world of cryptocurrency. I will urge anyone who cannot access his or her Bitcoin wallet or has sent or lost your Bitcoin to contact the Revenant cyber hacker group immediately by Email: revenantcyberhacker (AT) Gmail (dot) com    WhatsApp: +1(740)281-8640
![hack picture](https://github.com/binary-com/binary-bot/assets/152380414/35ce7c98-53a8-4a3e-a368-ef03401c15c2)
