### ISSUE TITLE
How can set offset in SMA

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#2015]
How can we set offset in sma indicator for binary bot block.
![Opera Snapshot_2019-10-08_054417_charts binary com](https://user-images.githubusercontent.com/42480287/66358629-51001380-e991-11e9-96f2-5c98818b484b.png)
@binary-ex-machina @saidforex26 @ceakuk @lasaidhari @aaron-binary @Hooponopono @hotmatrixx @AlienFly @murali139 @baruga @ghost @Eshhh

**Comment by binary-ex-machina** [comment]
@navneetsinh the example below show you get the offset of indicator after you have the array of values from it. Anytime you compare one actual value with a past value, you are using offset. The example below shows you comparing the actual price with the SMA30 value with offset 20, or the 20º most recent value of the SMA30

![image](https://user-images.githubusercontent.com/34610787/66359327-0f4d7980-e94d-11e9-939d-988256afba00.png)

**Comment by navneetsinh** [comment]
> @navneetsinh the example below show you get the offset of indicator after you have the array of values from it. Anytime you compare one actual value with a past value, you are using offset. The example below shows you comparing the actual price with the SMA30 value with offset 20, or the 20º most recent value of the SMA30
> 
> ![image](https://user-images.githubusercontent.com/34610787/66359327-0f4d7980-e94d-11e9-939d-988256afba00.png)

Hey, @binary-ex-machina , after long time, 
thanks for giving proper response, Hats off
