### ISSUE TITLE
Profitable binary trading strategy development into a Bot

### ISSUE THREAD

**Issue by olireggae** [binary-com/binary-bot#2016]
Dear all,
I have come across a strategy called the bmat strategy to trade volatilities on binary.com. It seems to be profitable can this be converted to a bot ?
N.B ( I have videos of the strategy, I can share it here. kindly let me know. Thanks!

**Comment by poroinika** [comment]
Why you not share it here,becouse sombody made it for free and you gona sell it....?

**Comment by olireggae** [comment]
Here is the link to the strategy, if you have any idea to create into a bot that will be great. I have more strategies that we can all benefit from:
https://drive.google.com/file/d/1bAU5ioXnpU4MrKbXkUpc9gda4wzvgJ5D/view?usp=sharing

**Comment by windjenn** [comment]
> Here is the link to the strategy, if you have any idea to create into a bot that will be great. I have more strategies that we can all benefit from:
> https://drive.google.com/file/d/1bAU5ioXnpU4MrKbXkUpc9gda4wzvgJ5D/view?usp=sharing

NO clear strategy found in video , whatever he talking in the video better we take rise n fall on it

**Comment by Fidzl** [comment]
> Here is the link to the strategy, if you have any idea to create into a bot that will be great. I have more strategies that we can all benefit from:
> https://drive.google.com/file/d/1bAU5ioXnpU4MrKbXkUpc9gda4wzvgJ5D/view?usp=sharing

Hello ... What other strategies do you have ?
