### ISSUE TITLE
ICHIMOKU bot needed!

### ISSUE THREAD

**Issue by mahmudayaz** [binary-com/binary-bot#2017]
Hello experts,

can someone has ichimoku bot, i need it kindly share. 

Regards,

Mahmud Ayaz

**Comment by saidforex26** [comment]
https://github.com/binary-ex-machina/binary.com-bot

**Comment by mahmudayaz** [comment]
Okay thanks, let me check. but this isn't the bot, i have tried so many times to configure the indicator but i am failed. can you please help me out to configure the Ichimoku indicator?

**Comment by saidforex26** [comment]
[create ichimoku.zip](https://github.com/binary-com/binary-bot/files/3709460/create.ichimoku.zip)
please develop
![ichimoku](https://user-images.githubusercontent.com/54820719/66521516-3a69d180-eae3-11e9-9353-c21224cfc5ae.gif)

**Comment by mahmudayaz** [comment]
I have attached the RSI logic but it doesn't work, its only working with green / red cloud logic
