### ISSUE TITLE
3 tick down or up to start bot

### ISSUE THREAD

**Issue by wallpersonal** [binary-com/binary-bot#2018]
Tried to make a bot that starts betting after 3 ticks down or that starts betting after 3 ticks up. Bet on the next tick contrary to the 3 ticks before the start. (call and put)

Already tried to do but fried the brain, and could not.

**Comment by saidforex26** [comment]
please develop 
![3tick rise fall](https://user-images.githubusercontent.com/54820719/66435967-ddf0ae80-ea1d-11e9-8c58-1d7b869218e0.gif)
[3tick rise fall.zip](https://github.com/binary-com/binary-bot/files/3704660/3tick.rise.fall.zip)
