### ISSUE TITLE
desktop installation of bot 

### ISSUE THREAD

**Issue by pawel27** [binary-com/binary-bot#202]
Hi I encountered difficulties in installing bot on desktop. I followed this instruction:

git clone https://github.com/binary-com/binary-bot.git
cd binary-bot
npm install
npm start

however once I type npm in the terminal I get:

npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I would appreciate your help. Thank you.

**Comment by aminmarashi** [comment]
You need to install [`npm`](https://nodejs.org/en/)

**Comment by pawel27** [comment]
Thank you I went one step forward but now encountered another problem when
typing 'npm start':


############### these are few lines at the end of the previous step (npm
install)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.1.1: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN binary-bot@2.3.2 No repository field.
##############


~\binary-bot [master ≡]> npm start

> binary-bot@2.3.2 start C:\Users\Administrator\binary-bot
> gulp watch

[06:08:59] Requiring external module babel-register
module.js:471
    throw err;
    ^

Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(C:\Users\Administrator\binary-bot\node_modules\binary-common-utils\lib\observer.js:10:18)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js]
(C:\Users\Administrator\binary-bot\node_modules\babel-reg
ister\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! binary-bot@2.3.2 start: `gulp watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binary-bot@2.3.2 start script 'gulp watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the binary-bot
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs binary-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls binary-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\binary-bot\npm-debug.log
~\binary-bot [master ≡]>


*I tried to install babel-register but got (I got the same message when
installing immutable as well):*

binary-bot@2.3.2 C:\Users\Administrator\binary-bot
`-- babel-register@6.24.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.1.1: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN binary-bot@2.3.2 No repository field.


2017-04-25 4:31 GMT+00:00 Amin Marashi <notifications@github.com>:

**Comment by aminmarashi** [comment]
Did you forget `npm install` first?

**Comment by pawel27** [comment]
I believe that was an issue. Thank you. What would be next step ? - I
opened bot.html as you can see in the attached picture 1 but the site is
loading all the time and nothing is loaded eventually (picture 2).

2017-04-25 7:06 GMT+00:00 Amin Marashi <notifications@github.com>:

**Comment by aminmarashi** [comment]
If it loads forever, there should be an error, check the console, also please put the contents here.

**Comment by pawel27** [comment]
Screenshot attached

2017-04-26 1:25 GMT+00:00 Amin Marashi <notifications@github.com>:

**Comment by aminmarashi** [comment]
Please upload the image in the [issue](https://github.com/binary-com/binary-bot/issues/202) itself. github ignores email attachments.

**Comment by pawel27** [comment]
![image](https://cloud.githubusercontent.com/assets/11303647/25420372/632633ac-2a47-11e7-9dc3-6463c44f611f.png)

**Comment by aminmarashi** [comment]
try this url: [localhost:8080/bot.html](http://localhost:8080/bot.html)

**Comment by pawel27** [comment]
I am not sure what to do with that lin. After I click it I get: This site can’t be reached

localhost refused to connect.
Search Google for localhost 8080 bot
ERR_CONNECTION_REFUSED

**Comment by aminmarashi** [comment]
First you need to make sure that `npm start` works correctly. If it does you get sth like this:
<img width="452" alt="screen shot 2017-04-26 at 2 21 27 pm" src="https://cloud.githubusercontent.com/assets/6560964/25420659/b0c08f88-2a8b-11e7-8c05-062e5cfa3922.png">

**Comment by aminmarashi** [comment]
I think I fixed it. Give it a try:
```
git pull
npm i
npm start
```

**Comment by pawel27** [comment]
Thank you it worked. I typed npm start and http://localhost:8080/bot.html poped up, and the website loaded.

**Comment by aminmarashi** [comment]
Cool, and thanks for reporting.
