### ISSUE TITLE
O Bot não esta alterando a previsão da forma correta

### ISSUE THREAD

**Issue by FlavianoFlavio** [binary-com/binary-bot#2020]
Estou desenvolvendo um Bot na plataforma e a mesma apresenta um erro como eu relato abaixo:

O bot eu programei para:

Toda vez que o "Ultimo Dígito" for 5 "Alterar Previsão" para o número 5 e Acionar o botão "Difere"
Toda vez que o "Ultimo Dígito" for 3 "Alterar Previsão" para o número 3 e Acionar o botão "Difere"
Toda vez que o "Ultimo Dígito" for 9 "Alterar Previsão" para o número 9 e Acionar o botão "Difere"

Porém o Bot esta colocando números aleatórios na Previsão, e não esta colocando o numero que eu coloquei na configuração, esta como se estivesse sorteando entre os números 5,3 e 9 e colocando de forma aleatória.

Alguém pode me ajudar ?

![Print Bot](https://user-images.githubusercontent.com/56320282/66433695-411b1a80-e9f7-11e9-84e0-d1c3819f247f.jpg)

![Print Bot2](https://user-images.githubusercontent.com/56320282/66433742-627c0680-e9f7-11e9-944d-4baa3964e596.jpg)

[Projeto bot 1.zip](https://github.com/binary-com/binary-bot/files/3704542/Projeto.bot.1.zip)

**Comment by saidforex26** [comment]
por favor desenvolva
[differs 539.zip](https://github.com/binary-com/binary-bot/files/3704707/differs.539.zip)
![differs 359](https://user-images.githubusercontent.com/54820719/66437134-e5658700-ea20-11e9-9f4a-ca89ee2b8819.gif)

**Comment by FlavianoFlavio** [comment]
Muito obrigado por sua ajuda amigo, tenho visto você sempre ajudando os iniciantes aqui varias vezes, parabéns pela sua atitude de ajudar todos sempre. 

Seria possível fazer este bot para quando qualquer número de 0 ao 9 sair 3 vezes seguidas o bot abrir uma ordem com este numero que se repetiu 3 vezes seguidas no ultimo digito ?

**Comment by saidforex26** [comment]
Eu só ajudei com as idéias deles. por favor desenvolva
[difers 3 digit same.zip](https://github.com/binary-com/binary-bot/files/3705275/difers.3.digit.same.zip)
![differs 3 digit same](https://user-images.githubusercontent.com/54820719/66446554-f32c0400-ea42-11e9-871c-56cbaca40813.gif)
