### ISSUE TITLE
Por favor me ajudem a criar Bot com essa estratégia 

### ISSUE THREAD

**Issue by gustavolima2019** [binary-com/binary-bot#2021]
A estratégia é a seguinte;

Qualquer numero 0, 1, 2, 3, 4, 5, 6, 7, 8 ,9 que sair 3 vezes em sequência o bot irá abrir uma ordem na modalidade digito diferente colocando na previsão o dígito que sair 3 vezes seguidas.

Seria interessante deixar um campo, onde eu pudesse alterar a quantidade de vezes seguidas que os números devem sair, onde  eu escolheria quantas vezes  o número deve sair em sequência para abrir a ordem. Também seria interessante um campo onde eu pudesse adicionar ou eliminar algum numero da estratégia, exemplo; se o dígito 3 tiver dando muito erro eu eliminar o dígito 3 da estratégia, e no dia seguinte eu adicionar o numero 3 novamente a estratégia....

Agradeço a ajuda de todos....

**Comment by gustavolima2019** [comment]
@saidforex26
@raunakkathuria 
@gustavolima2019 
@gustavolima2019 ashkanx

**Comment by saidforex26** [comment]
![differs 3 digit same](https://user-images.githubusercontent.com/54820719/66708007-bbbe9f80-ed41-11e9-8547-67ecd25c65c6.gif)
please develop

**Comment by gustavolima2019** [comment]
Muito obrigado amigo. mas como faço para excluir um número da estratégia, exemplo se o número 0 estiver dando muitos erros, como posso fazer a estratégia desconsiderar este número em determinado dia, e no outro eu adicioná-lo a estratégia novamente ?  Falo isso pois em alguns dias o mesmo número se repete várias vezes em sequência, e por isso podem ocorrem muitos erros seguidos....
