### ISSUE TITLE
Please help me to create a bot

### ISSUE THREAD

**Issue by immwhyd14** [binary-com/binary-bot#2023]
Please help me to create a bot for this strategy. (touch option)
Indicator RSI 14 and BB 20,2,2 TF 1 minutes
Rules : When RSI level above 50 and price touch BB higher band from below, open touch plus barrier (only one open). and when RSI level below 50 and price touch BB lower band from above, open touch minus barrier (only one open)
Thankyouuuu

**Comment by Tebu1429** [comment]
Did you managed to create the bot?
