### ISSUE TITLE
Strategia

### ISSUE THREAD

**Issue by alansilva1** [binary-com/binary-bot#2024]
I would like to make the following strategy: When you give 5 green candles on Friday, she goes down. When she gives 5 red candles on Friday, she goes up.

**Comment by FlavianoFlavio** [comment]
Muito boa essa estratégia, verifiquei no gráfico na IQ options operando manualmente realmente a taxa de acertos é muito alta. Espero que apareça algum programador para ajudar a fazer este bot.

**Comment by saidforex26** [comment]
1. For what market
2. what is the candle interval
3. duration

**Comment by alansilva1** [comment]
> 1. Para que mercado
> 2. qual é o intervalo da vela
> 3. duração

MARKET COUPLE OF COINS. 1 MINUTES INTERVAL AND 1 MINUTES EXPIRATION

**Comment by Tebu1429** [comment]
I need help on building a bit.

Please help

**Comment by FlavianoFlavio** [comment]
?

**Comment by saidforex26** [comment]
[5color candle R_100.zip](https://github.com/binary-com/binary-bot/files/3765981/5color.candle.R_100.zip)
