### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by freedonone** [binary-com/binary-bot#2027]
i always have this error when trying to run my bot, "Cannot read property 'currency' of undefined".
what could be the cause.

**Comment by ghossan86** [comment]
It coused of block slice not on the place.. 
I have had some experiences about that

**Comment by aaron-binary** [comment]
Hey @freedonone,

Could you create a screenshot of your strategy, or supply us with the XML file? You may upload it to https://gist.github.com.

Regards,
Aaron

**Comment by saarsalu** [comment]
> Hey @freedonone,
> 
> Could you create a screenshot of your strategy, or supply us with the XML file? You may upload it to https://gist.github.com.
> 
> Regards,
> Aaron

@aaron-binary 
i am ceting same error

Cannot read property 'currency' of undefined

**Comment by parvezcs16** [comment]
> Hey @freedonone,
> 
> Could you create a screenshot of your strategy, or supply us with the XML file? You may upload it to https://gist.github.com.
> 
> Regards,
> Aaron

Hi there, I have the same error "my binary bot show error cannot read proprety"jquery" of undefined in xml file"
here is XML code
<xml xmlns="http://www.w3.org/1999/xhtml" collection="false">
  <variables>
    <variable type="" id="8fJmh^O(;kz`u0ImvoQJ">last digit</variable>
    <variable type="" id="H4*ZvkKN@A|ry]?)/N%u">digits</variable>
    <variable type="" id="(8_5vzCMX6{)JP=a(F8D">if result is loss here =&gt;</variable>
    <variable type="" id="Z+wJm83m!XK3LB~|TP@$">martingale (on / off)</variable>
    <variable type="" id="*1i]0z8AfAj}CE`G!0IU">ticks</variable>
    <variable type="" id="riy(z@GoXvxy!RfJa#vn">stake</variable>
    <variable type="" id="(hZrCC^?ob$49F$mp?9g">profit at :</variable>
    <variable type="" id="R^^T^d?^c!.TT|0l.x%F">i</variable>
    <variable type="" id="h)$N3{}[P(!mZ:hw5sVo">%&lt;4</variable>
    <variable type="" id="|vUc7=ckQkOJ@o8P$3Lu">martin</variable>
    <variable type="" id="ikf??ChG/xI^`EUcJ9%4">totprof</variable>
    <variable type="" id="GAl!7H(56+{o0sm4/-I)">mrt</variable>
    <variable type="" id="~bt}KTB[/LeMa.EN*h_d">stk</variable>
    <variable type="" id="nQ?;BggAXDSrBm8b_G^}">tik</variable>
    <variable type="" id="r-@[^-kKvx;/75wI;ed%">min4</variable>
    <variable type="" id="[,?Hg$dDo=K_S:d#pjMZ">mag5</variable>
    <variable type="" id="pVVMdJ+;P/r$gL|oIqmK">%&gt;5</variable>
    <variable type="" id="2dg]L,j_y4:E@tJ{WG8y">rst stk</variable>
    <variable type="" id="^FhEQ)Z@JKr:W8Y+6;$@">profit</variable>
  </variables>
  <block type="procedures_defreturn" id="sbN}z#iG^H5(|spJ5UYp" collapsed="true" x="0" y="0">
    <mutation>
      <arg name="last digit" varid="8fJmh^O(;kz`u0ImvoQJ"></arg>
      <arg name="digits" varid="H4*ZvkKN@A|ry]?)/N%u"></arg>
    </mutation>
    <field name="NAME">check%</field>
    <comment pinned="false" h="80" w="160">Describe this function...</comment>
    <statement name="STACK">
      <block type="controls_for" id="-.5i9Pa!}(^0NJ~uA|_8">
        <field name="VAR" id="R^^T^d?^c!.TT|0l.x%F" variabletype="">i</field>
        <value name="FROM">
          <block type="variables_get" id="dM;X0j2`-pKm~OjpC(a!">
            <field name="VAR" id="H4*ZvkKN@A|ry]?)/N%u" variabletype="">digits</field>
          </block>
        </value>
        <value name="TO">
          <block type="math_number" id="cYveM)?r4Buwa:h2cT*?">
            <field name="NUM">1</field>
          </block>
        </value>
        <value name="BY">
          <block type="math_number" id="9~#4AXPkVRYNa|.,x*fo">
            <field name="NUM">1</field>
          </block>
        </value>
        <statement name="DO">
          <block type="controls_if" id="/wkaea7huXFbdQQ-AAqQ">
            <mutation else="1"></mutation>
            <value name="IF0">
              <block type="logic_compare" id="5#@.^]|LXI^%SrY;UB9W">
                <field name="OP">LTE</field>
                <value name="A">
                  <block type="lists_getIndex" id="*U7;gG~|kk:KKT.9b(^_">
                    <mutation statement="false" at="true"></mutation>
                    <field name="MODE">GET</field>
                    <field name="WHERE">FROM_END</field>
                    <value name="VALUE">
                      <block type="variables_get" id="quoSr0}R4cLv!A^utHz6">
                        <field name="VAR" id="8fJmh^O(;kz`u0ImvoQJ" variabletype="">last digit</field>
                      </block>
                    </value>
                    <value name="AT">
                      <block type="variables_get" id="~=$},J@KArvq5mZ{-,X(">
                        <field name="VAR" id="R^^T^d?^c!.TT|0l.x%F" variabletype="">i</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="B">
                  <block type="math_number" id="|wJ[p8djRX1.qL//m/Vd">
                    <field name="NUM">4</field>
                  </block>
                </value>
              </block>
            </value>
            <statement name="DO0">
              <block type="math_change" id="qv:_TT/J.9^/42_WXV(_">
                <field name="VAR" id="r-@[^-kKvx;/75wI;ed%" variabletype="">min4</field>
                <value name="DELTA">
                  <shadow type="math_number" id="T|JpU~A(xKwC_!78#.=R">
                    <field name="NUM">1</field>
                  </shadow>
                </value>
              </block>
            </statement>
            <statement name="ELSE">
              <block type="math_change" id="/c=K-XBm7w;`d-L+HQk}">
                <field name="VAR" id="[,?Hg$dDo=K_S:d#pjMZ" variabletype="">mag5</field>
                <value name="DELTA">
                  <shadow type="math_number" id="GMNyN0WtyDn7)7][-.$4">
                    <field name="NUM">1</field>
                  </shadow>
                </value>
              </block>
            </statement>
          </block>
        </statement>
        <next>
          <block type="variables_set" id="rVK35apq:Vd}k6R8+[j-">
            <field name="VAR" id="h)$N3{}[P(!mZ:hw5sVo" variabletype="">%&lt;4</field>
            <value name="VALUE">
              <block type="math_arithmetic" id=".4i0JjznabH6{tUJsN)w">
                <field name="OP">MINUS</field>
                <value name="A">
                  <shadow type="math_number" id="^n_Mx8wmI)Pu$}e;q]-.">
                    <field name="NUM">100</field>
                  </shadow>
                  <block type="math_arithmetic" id="vgwN(vNXpx|!;dpS4^;1">
                    <field name="OP">ADD</field>
                    <value name="A">
                      <shadow type="math_number" id="4]J#Qy9xLPn+D~,M1GYL">
                        <field name="NUM">1</field>
                      </shadow>
                      <block type="variables_get" id="0%s#0{fN3-rdMMpqQw`_">
                        <field name="VAR" id="r-@[^-kKvx;/75wI;ed%" variabletype="">min4</field>
                      </block>
                    </value>
                    <value name="B">
                      <shadow type="math_number" id="}3wJz+]~I5g)W]l7r$T_">
                        <field name="NUM">1</field>
                      </shadow>
                      <block type="variables_get" id="l~h|0TRAEXF3PO]uO1oq">
                        <field name="VAR" id="[,?Hg$dDo=K_S:d#pjMZ" variabletype="">mag5</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="B">
                  <shadow type="math_number" id="^R[uiJ4A0!tkDAhK]=;+">
                    <field name="NUM">1</field>
                  </shadow>
                  <block type="variables_get" id="Tc-3S32]V##HazWrY^Xd">
                    <field name="VAR" id="[,?Hg$dDo=K_S:d#pjMZ" variabletype="">mag5</field>
                  </block>
                </value>
              </block>
            </value>
            <next>
              <block type="variables_set" id="/-/.Xms1_Iw2uh`/;pGf">
                <field name="VAR" id="pVVMdJ+;P/r$gL|oIqmK" variabletype="">%&gt;5</field>
                <value name="VALUE">
                  <block type="math_arithmetic" id="y:.qXDhMXb!ntnATJ=js">
                    <field name="OP">MINUS</field>
                    <value name="A">
                      <shadow type="math_number" id=")!ODSOY.uvx-XOPvC^|P">
                        <field name="NUM">100</field>
                      </shadow>
                      <block type="math_arithmetic" id="o2IcA}5x7$5@YaDEzX`S">
                        <field name="OP">ADD</field>
                        <value name="A">
                          <shadow type="math_number" id="4]J#Qy9xLPn+D~,M1GYL">
                            <field name="NUM">1</field>
                          </shadow>
                          <block type="variables_get" id="TWe_g-wJlQ!Uje_?a+/D">
                            <field name="VAR" id="r-@[^-kKvx;/75wI;ed%" variabletype="">min4</field>
                          </block>
                        </value>
                        <value name="B">
                          <shadow type="math_number" id="}3wJz+]~I5g)W]l7r$T_">
                            <field name="NUM">1</field>
                          </shadow>
                          <block type="variables_get" id=":g8;T@Kjc,HN6^y(qfiw">
                            <field name="VAR" id="[,?Hg$dDo=K_S:d#pjMZ" variabletype="">mag5</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <value name="B">
                      <shadow type="math_number" id="^R[uiJ4A0!tkDAhK]=;+">
                        <field name="NUM">1</field>
                      </shadow>
                      <block type="variables_get" id="9`FR0{i$k_KI$a,Gc:;~">
                        <field name="VAR" id="r-@[^-kKvx;/75wI;ed%" variabletype="">min4</field>
                      </block>
                    </value>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="^Qw_V%OW?_NjOk-yf7@@">
                    <field name="VAR" id="[,?Hg$dDo=K_S:d#pjMZ" variabletype="">mag5</field>
                    <value name="VALUE">
                      <block type="math_number" id="P:%L|yjiR53$Qz}uays{">
                        <field name="NUM">0</field>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="~T~7_TG9}W1nW#x;?ZYO">
                        <field name="VAR" id="r-@[^-kKvx;/75wI;ed%" variabletype="">min4</field>
                        <value name="VALUE">
                          <block type="math_number" id="154j)_]8F6`wSkSjCoI1">
                            <field name="NUM">0</field>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
    <value name="RETURN">
      <block type="logic_ternary" id="i:p~NBAjG9wgzKwIE+Xs">
        <value name="IF">
          <block type="logic_compare" id=".+2[?R:!1QDO[B,,oGcR">
            <field name="OP">GT</field>
            <value name="A">
              <block type="variables_get" id="/5Uml/OLYD@Alf}IgzU~">
                <field name="VAR" id="pVVMdJ+;P/r$gL|oIqmK" variabletype="">%&gt;5</field>
              </block>
            </value>
            <value name="B">
              <block type="variables_get" id="5qnIy6Rb.Lo]@w`R#s/.">
                <field name="VAR" id="h)$N3{}[P(!mZ:hw5sVo" variabletype="">%&lt;4</field>
              </block>
            </value>
          </block>
        </value>
        <value name="THEN">
          <block type="logic_boolean" id="[%1A)rRaw~?rNC][lQ4e">
            <field name="BOOL">TRUE</field>
          </block>
        </value>
        <value name="ELSE">
          <block type="logic_boolean" id="{pW4[D1G![@X%9=17goZ">
            <field name="BOOL">FALSE</field>
          </block>
        </value>
      </block>
    </value>
  </block>
  <block type="procedures_defnoreturn" id=",+p8(j=xzJ49ouOJB=@;" collapsed="true" x="0" y="53">
    <mutation>
      <arg name="if result is loss here =&gt;" varid="(8_5vzCMX6{)JP=a(F8D"></arg>
    </mutation>
    <field name="NAME">4</field>
    <comment pinned="false" h="80" w="160">Describe this function...</comment>
    <statement name="STACK">
      <block type="controls_if" id="aiT-o-[L*Lnne/)R3)NX">
        <value name="IF0">
          <block type="variables_get" id="6)h7Rd8#+f{ZN7|r3;6h">
            <field name="VAR" id="|vUc7=ckQkOJ@o8P$3Lu" variabletype="">martin</field>
          </block>
        </value>
        <statement name="DO0">
          <block type="controls_if" id="(JQ|a!JflV7(8Z9rWzdX">
            <mutation else="1"></mutation>
            <value name="IF0">
              <block type="variables_get" id="rW,yLcdOwgIcDMdG*Dx4">
                <field name="VAR" id="(8_5vzCMX6{)JP=a(F8D" variabletype="">if result is loss here =&gt;</field>
              </block>
            </value>
            <statement name="DO0">
              <block type="variables_set" id="o6Z;)KQFeu#,KzjAIxbq">
                <field name="VAR" id="~bt}KTB[/LeMa.EN*h_d" variabletype="">stk</field>
                <value name="VALUE">
                  <block type="math_arithmetic" id="@]#*=%_y`}|_*2yn-?Lf">
                    <field name="OP">MULTIPLY</field>
                    <value name="A">
                      <shadow type="math_number" id="6tmyx8A-ET!Xs6/iNeJS">
                        <field name="NUM">1.5</field>
                      </shadow>
                      <block type="variables_get" id="m?`JqUk.w(TcYODK]V4@">
                        <field name="VAR" id="GAl!7H(56+{o0sm4/-I)" variabletype="">mrt</field>
                      </block>
                    </value>
                    <value name="B">
                      <shadow type="math_number" id="GtfEAdz=qCMUs^4dhH46">
                        <field name="NUM">1</field>
                      </shadow>
                      <block type="variables_get" id="v=hiWvFs_xV4{K%+0do@">
                        <field name="VAR" id="~bt}KTB[/LeMa.EN*h_d" variabletype="">stk</field>
                      </block>
                    </value>
                  </block>
                </value>
              </block>
            </statement>
            <statement name="ELSE">
              <block type="variables_set" id="_{8GfW6P.(/8qsxM7;h*">
                <field name="VAR" id="~bt}KTB[/LeMa.EN*h_d" variabletype="">stk</field>
                <value name="VALUE">
                  <block type="variables_get" id="WvM|cW7=;eGaS57Ua.lN">
                    <field name="VAR" id="2dg]L,j_y4:E@tJ{WG8y" variabletype="">rst stk</field>
                  </block>
                </value>
              </block>
            </statement>
          </block>
        </statement>
        <next>
          <block type="variables_set" id="4n*Y:yX`9fsNxwto0e]I">
            <field name="VAR" id="ikf??ChG/xI^`EUcJ9%4" variabletype="">totprof</field>
            <value name="VALUE">
              <block type="logic_ternary" id="8qRZWSR!~6bltF3(@Bcd">
                <value name="IF">
                  <block type="logic_compare" id="29)|RX.Ki9*X#P,[(%RW">
                    <field name="OP">LT</field>
                    <value name="A">
                      <block type="total_profit" id="eLV`OOt#fJD|NK$N/W?,"></block>
                    </value>
                    <value name="B">
                      <block type="variables_get" id="kZB%etN]lb2iab!72lO@">
                        <field name="VAR" id="^FhEQ)Z@JKr:W8Y+6;$@" variabletype="">profit</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="THEN">
                  <block type="logic_boolean" id="@|{1@zyULlP[|Y$|-`(i">
                    <field name="BOOL">TRUE</field>
                  </block>
                </value>
                <value name="ELSE">
                  <block type="logic_boolean" id="Lg{%`67aK(UF]IL}o6`Q">
                    <field name="BOOL">FALSE</field>
                  </block>
                </value>
              </block>
            </value>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="procedures_defnoreturn" id="f4k;?VD3AfVPauxrxDmL" collapsed="true" x="0" y="106">
    <mutation>
      <arg name="martingale (on / off)" varid="Z+wJm83m!XK3LB~|TP@$"></arg>
      <arg name="ticks" varid="*1i]0z8AfAj}CE`G!0IU"></arg>
      <arg name="stake" varid="riy(z@GoXvxy!RfJa#vn"></arg>
      <arg name="profit at :" varid="(hZrCC^?ob$49F$mp?9g"></arg>
    </mutation>
    <field name="NAME">money managment</field>
    <comment pinned="false" h="80" w="160">Describe this function...</comment>
    <statement name="STACK">
      <block type="controls_if" id="TPNx3b90BzH`O,(~#0}}">
        <mutation else="1"></mutation>
        <value name="IF0">
          <block type="logic_compare" id="^k!;EJ#/5m#8A-aj+qM^">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="variables_get" id="~8EG4a`Rk?Tj%bh_3PJ^">
                <field name="VAR" id="Z+wJm83m!XK3LB~|TP@$" variabletype="">martingale (on / off)</field>
              </block>
            </value>
            <value name="B">
              <block type="math_number" id="PpQ8V|-@dT6MIh@=/|r*">
                <field name="NUM">0</field>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO0">
          <block type="variables_set" id="zHqH/U{j7#4gkr4,U~C7">
            <field name="VAR" id="|vUc7=ckQkOJ@o8P$3Lu" variabletype="">martin</field>
            <value name="VALUE">
              <block type="logic_boolean" id="xrIevW8H1tUVCfTv)iYz">
                <field name="BOOL">FALSE</field>
              </block>
            </value>
          </block>
        </statement>
        <statement name="ELSE">
          <block type="variables_set" id="Zb(OR|ywwK!mIja=Q)pI">
            <field name="VAR" id="GAl!7H(56+{o0sm4/-I)" variabletype="">mrt</field>
            <value name="VALUE">
              <block type="variables_get" id="CX?,vgGK[d^T/,ufUCRa">
                <field name="VAR" id="Z+wJm83m!XK3LB~|TP@$" variabletype="">martingale (on / off)</field>
              </block>
            </value>
            <next>
              <block type="variables_set" id="TQQdPzU`l_|Q8%DKwV)X">
                <field name="VAR" id="|vUc7=ckQkOJ@o8P$3Lu" variabletype="">martin</field>
                <value name="VALUE">
                  <block type="logic_boolean" id=";2##NcBILy7nO_n7WS7Z">
                    <field name="BOOL">TRUE</field>
                  </block>
                </value>
              </block>
            </next>
          </block>
        </statement>
        <next>
          <block type="variables_set" id="=ByK[(M:urqnvUp-i-f%">
            <field name="VAR" id="~bt}KTB[/LeMa.EN*h_d" variabletype="">stk</field>
            <value name="VALUE">
              <block type="variables_get" id="0F/iT1RVSjl}G$waYb]r">
                <field name="VAR" id="riy(z@GoXvxy!RfJa#vn" variabletype="">stake</field>
              </block>
            </value>
            <next>
              <block type="variables_set" id="(LavI/5V;r.{*{z=:mF-">
                <field name="VAR" id="nQ?;BggAXDSrBm8b_G^}" variabletype="">tik</field>
                <value name="VALUE">
                  <block type="variables_get" id="REEUe~zXYz|^{;NBiW3L">
                    <field name="VAR" id="*1i]0z8AfAj}CE`G!0IU" variabletype="">ticks</field>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="#!73[2;!a91vx!URtPF|">
                    <field name="VAR" id="^FhEQ)Z@JKr:W8Y+6;$@" variabletype="">profit</field>
                    <value name="VALUE">
                      <block type="variables_get" id="f_Mirc+j:ztbLj8+6~75">
                        <field name="VAR" id="(hZrCC^?ob$49F$mp?9g" variabletype="">profit at :</field>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="ELFKUk#t{Hl^P%-_SU^}">
                        <field name="VAR" id="2dg]L,j_y4:E@tJ{WG8y" variabletype="">rst stk</field>
                        <value name="VALUE">
                          <block type="variables_get" id="_;LAjvC:gIgBx{9L}1VC">
                            <field name="VAR" id="~bt}KTB[/LeMa.EN*h_d" variabletype="">stk</field>
                          </block>
                        </value>
                        <next>
                          <block type="variables_set" id="{o;b,p82NTCTEgIzp7,X">
                            <field name="VAR" id="ikf??ChG/xI^`EUcJ9%4" variabletype="">totprof</field>
                            <value name="VALUE">
                              <block type="logic_boolean" id="NwyR3L)D~73eLa!1HeXW">
                                <field name="BOOL">TRUE</field>
                              </block>
                            </value>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="trade" id="xgH69|xFn9=70w.*3Vo@" x="0" y="159">
    <field name="MARKET_LIST">volidx</field>
    <field name="SUBMARKET_LIST">random_index</field>
    <field name="SYMBOL_LIST">R_10</field>
    <field name="TRADETYPECAT_LIST">digits</field>
    <field name="TRADETYPE_LIST">overunder</field>
    <field name="TYPE_LIST">both</field>
    <field name="CANDLEINTERVAL_LIST">60</field>
    <field name="TIME_MACHINE_ENABLED">FALSE</field>
    <field name="RESTARTONERROR">TRUE</field>
    <statement name="INITIALIZATION">
      <block type="procedures_callnoreturn" id="@%o!OsCA.n-wO*IT|rsQ">
        <mutation name="money managment">
          <arg name="martingale (on / off)"></arg>
          <arg name="ticks"></arg>
          <arg name="stake"></arg>
          <arg name="profit at :"></arg>
        </mutation>
        <value name="ARG0">
          <block type="math_number" id="tM_e~[,59xkQPc%TH[aS">
            <field name="NUM">2.2</field>
          </block>
        </value>
        <value name="ARG1">
          <block type="math_number" id="xwx(fNTcawqrGZ)blrRu">
            <field name="NUM">5</field>
          </block>
        </value>
        <value name="ARG2">
          <block type="math_number" id="/!!u$Nz1evz:,wfloY}7">
            <field name="NUM">1</field>
          </block>
        </value>
        <value name="ARG3">
          <block type="math_number" id="O)=PBIkh_Ucl!vt4HI[Y">
            <field name="NUM">10</field>
          </block>
        </value>
      </block>
    </statement>
    <statement name="SUBMARKET">
      <block type="tradeOptions" id="x=V33~4Lb|(sLv`J[:Eb">
        <field name="DURATIONTYPE_LIST">t</field>
        <field name="CURRENCY_LIST">USD</field>
        <value name="DURATION">
          <shadow type="math_number" id="h,tkI1GevUPDDgMLBgv_">
            <field name="NUM">1</field>
          </shadow>
          <block type="variables_get" id="PQyZgiV^I=f#ZqLlipu_">
            <field name="VAR" id="nQ?;BggAXDSrBm8b_G^}" variabletype="">tik</field>
          </block>
        </value>
        <value name="AMOUNT">
          <shadow type="math_number" id="ml)25~7^q}3I9}vjf:%K">
            <field name="NUM">1</field>
          </shadow>
          <block type="variables_get" id="_WCAd7-l}($|6v[~7-d6">
            <field name="VAR" id="~bt}KTB[/LeMa.EN*h_d" variabletype="">stk</field>
          </block>
        </value>
        <value name="PREDICTION">
          <shadow type="math_number" id="^[8/-`}dN;gHD4{Vfj[X">
            <field name="NUM">5</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>
  <block type="before_purchase" id="i-CIx.(Onm4?ihxzA}Y]" x="0" y="714">
    <statement name="BEFOREPURCHASE_STACK">
      <block type="notify" id="$pJ*.0U~skj,UIh?I@NB">
        <field name="NOTIFICATION_TYPE">success</field>
        <field name="NOTIFICATION_SOUND">silent</field>
        <value name="MESSAGE">
          <shadow type="text" id="s=N;vT^OQ||e{hRKavKS">
            <field name="TEXT">abc</field>
          </shadow>
          <block type="variables_get" id="JxjZ?90-[N1XP[tu6sJt">
            <field name="VAR" id="h)$N3{}[P(!mZ:hw5sVo" variabletype="">%&lt;4</field>
          </block>
        </value>
        <next>
          <block type="notify" id="kZu|!FZxBtoNncHK4D?d">
            <field name="NOTIFICATION_TYPE">error</field>
            <field name="NOTIFICATION_SOUND">silent</field>
            <value name="MESSAGE">
              <shadow type="text" id=";|+.uxnW9#~FZNA^Q+-}">
                <field name="TEXT">abc</field>
              </shadow>
              <block type="variables_get" id="6jAp#pKdA?EY`29i3^uL">
                <field name="VAR" id="pVVMdJ+;P/r$gL|oIqmK" variabletype="">%&gt;5</field>
              </block>
            </value>
            <next>
              <block type="controls_if" id="SSh?K(cegJh?ZG,)_x%^">
                <mutation else="1"></mutation>
                <value name="IF0">
                  <block type="variables_get" id="X9?(TF^.AJsPqDqHeI*p">
                    <field name="VAR" id="ikf??ChG/xI^`EUcJ9%4" variabletype="">totprof</field>
                  </block>
                </value>
                <statement name="DO0">
                  <block type="controls_if" id="6cE1xiC0rI0!o=e:VS{}">
                    <mutation else="1"></mutation>
                    <value name="IF0">
                      <block type="procedures_callreturn" id="[79+$ophfShbhsZ34PDM">
                        <mutation name="check%">
                          <arg name="last digit"></arg>
                          <arg name="digits"></arg>
                        </mutation>
                        <value name="ARG0">
                          <block type="lastDigitList" id=";_osT@0uK-Ba%{:OA_Q_"></block>
                        </value>
                        <value name="ARG1">
                          <block type="math_number" id="+PI{|!O9pAOc*dpr[O.2">
                            <field name="NUM">100</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <statement name="DO0">
                      <block type="purchase" id="Qr|@~;1ro^|T~z!ofbbk">
                        <field name="PURCHASE_LIST">DIGITUNDER</field>
                      </block>
                    </statement>
                    <statement name="ELSE">
                      <block type="notify" id="[*_9tSZ#;hPsBl4!~:tf">
                        <field name="NOTIFICATION_TYPE">success</field>
                        <field name="NOTIFICATION_SOUND">silent</field>
                        <value name="MESSAGE">
                          <shadow type="text" id="0gKpm2?KoUL2A|(%K%]s">
                            <field name="TEXT">oh no...</field>
                          </shadow>
                        </value>
                      </block>
                    </statement>
                  </block>
                </statement>
                <statement name="ELSE">
                  <block type="notify" id="VKIkaP_ih`AAI`nR21)z">
                    <field name="NOTIFICATION_TYPE">success</field>
                    <field name="NOTIFICATION_SOUND">silent</field>
                    <value name="MESSAGE">
                      <shadow type="text" id="8ATcYXWro:~%PR7/zIAR">
                        <field name="TEXT">finished....</field>
                      </shadow>
                    </value>
                  </block>
                </statement>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="after_purchase" id="D^Jz1^n=2vtZku1vBN@;" x="0" y="1136">
    <statement name="AFTERPURCHASE_STACK">
      <block type="procedures_callnoreturn" id="6-p/zwfXZAv9if]yzCVY">
        <mutation name="4">
          <arg name="if result is loss here =&gt;"></arg>
        </mutation>
        <value name="ARG0">
          <block type="contract_check_result" id="5^RS3xD^IpH_z)c%-N5`">
            <field name="CHECK_RESULT">loss</field>
          </block>
        </value>
        <next>
          <block type="timeout" id="Hu@~yqN6-UXqx:z1J1HH">
            <statement name="TIMEOUTSTACK">
              <block type="trade_again" id="c)S|KjoQdXc8l#J@5z3P"></block>
            </statement>
            <value name="SECONDS">
              <shadow type="math_number" id="mLC)js@p}Y=;(eyQcDCS">
                <field name="NUM">20</field>
              </shadow>
            </value>
          </block>
        </next>
      </block>
    </statement>
  </block>
</xml>
