### ISSUE TITLE
OP trade at the open of new candle

### ISSUE THREAD

**Issue by thanh301** [binary-com/binary-bot#2031]
Hi, can you guys help me to code the bot to open the trade exactly when the new candle open?

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-10-16_023044_bot binary com](https://user-images.githubusercontent.com/42480287/66869437-0a2ba280-efbd-11e9-8042-4138361134e8.png)

**Comment by jose895** [comment]
Si la vela fuera verde mejor
