### ISSUE TITLE
I need help making this martingale setup.

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#2036]
The first loss, martingale multiplied by 1.125 and the next time multiplied by 2.2

![Capture](https://user-images.githubusercontent.com/51996252/67024795-323b1300-f12f-11e9-88fe-7cda03cf155b.JPG)

If adding more from the picture is very good

**Comment by navneetsinh** [comment]
> The first loss, martingale multiplied by 1.125 and the next time multiplied by 2.2
> 
> ![Capture](https://user-images.githubusercontent.com/51996252/67024795-323b1300-f12f-11e9-88fe-7cda03cf155b.JPG)
> 
> If adding more from the picture is very good

try to add some required blocks in your bot

![Opera Snapshot_2019-10-18_165135_bot binary com](https://user-images.githubusercontent.com/42480287/67090418-ad500800-f1c7-11e9-89e8-e9c20c8ea57c.png)

**Comment by Herotaiko** [comment]
@navneetsinh Thank you brother.
