### ISSUE TITLE
Someone help me please

### ISSUE THREAD

**Issue by alansilva1** [binary-com/binary-bot#2037]
@Someone help me please. I would like a robot with the following strategy: 5 green candles in a row and the sixth candle goes down buying. If you win, continue with a new candle analysis; If you lose, keep going until you win. Sorry about my English.

**Comment by navneetsinh** [comment]
> @Someone help me please. I would like a robot with the following strategy: 5 green candles in a row and the sixth candle goes down buying. If you win, continue with a new candle analysis; If you lose, keep going until you win. Sorry about my English.

@alansilva1 
![Opera Snapshot_2019-10-18_163030_bot binary com](https://user-images.githubusercontent.com/42480287/67089243-cefbc000-f1c4-11e9-9cfd-a9617bd05574.png)

**Comment by alansilva1** [comment]
> > @Someone help me please. I would like a robot with the following strategy: 5 green candles in a row and the sixth candle goes down buying. If you win, continue with a new candle analysis; If you lose, keep going until you win. Sorry about my English.
> 
> @alansilva1
> ![Opera Snapshot_2019-10-18_163030_bot binary com](https://user-images.githubusercontent.com/42480287/67089243-cefbc000-f1c4-11e9-9cfd-a9617bd05574.png)

Thank you very much. How does martigale ??

**Comment by navneetsinh** [comment]
> > > @Someone help me please. I would like a robot with the following strategy: 5 green candles in a row and the sixth candle goes down buying. If you win, continue with a new candle analysis; If you lose, keep going until you win. Sorry about my English.
> > 
> > 
> > @alansilva1
> > ![Opera Snapshot_2019-10-18_163030_bot binary com](https://user-images.githubusercontent.com/42480287/67089243-cefbc000-f1c4-11e9-9cfd-a9617bd05574.png)
> 
> Thank you very much. How does martigale ??

@alansilva1 ,

![Opera Snapshot_2019-10-19_004830_bot binary com](https://user-images.githubusercontent.com/42480287/67121918-40aa2d00-f20a-11e9-9bc7-e7d0a3dc817e.png)

**Comment by alansilva1** [comment]
Friend thank you very much.

**Comment by ahmadhus** [comment]
@alansilva1 

Dear can you send me the final bot ?

**Comment by alansilva1** [comment]
> > > > @ Alguém me ajude por favor. Eu gostaria de um robô com a seguinte estratégia: 5 velas verdes seguidas e a sexta vela cai na compra. Se você vencer, continue com uma nova análise de velas; Se você perder, continue até ganhar. Desculpe meu ingles.
> > > 
> > > 
> > > @ alansilva1
> > > ![Opera Snapshot_2019-10-18_163030_bot binário com](https://user-images.githubusercontent.com/42480287/67089243-cefbc000-f1c4-11e9-9cfd-a9617bd05574.png)
> > 
> > 
> > Muito obrigado. Como martigale ??
> 
> @ alansilva1 ,
> 
> ![Opera Snapshot_2019-10-19_004830_bot binário com](https://user-images.githubusercontent.com/42480287/67121918-40aa2d00-f20a-11e9-9bc7-e7d0a3dc817e.png)

Friend thank you so much for your help. But can you tell me how do I check in both sides ?? Up and down ???

**Comment by navneetsinh** [comment]
> > > > > @ Alguém me ajude por favor. Eu gostaria de um robô com a seguinte estratégia: 5 velas verdes seguidas e a sexta vela cai na compra. Se você vencer, continue com uma nova análise de velas; Se você perder, continue até ganhar. Desculpe meu ingles.
> > > > 
> > > > 
> > > > @ alansilva1
> > > > ![Opera Snapshot_2019-10-18_163030_bot binário com](https://user-images.githubusercontent.com/42480287/67089243-cefbc000-f1c4-11e9-9cfd-a9617bd05574.png)
> > > 
> > > 
> > > Muito obrigado. Como martigale ??
> > 
> > 
> > @ alansilva1 ,
> > ![Opera Snapshot_2019-10-19_004830_bot binário com](https://user-images.githubusercontent.com/42480287/67121918-40aa2d00-f20a-11e9-9bc7-e7d0a3dc817e.png)
> 
> Friend, thank you so much for your help. But can you tell me how I check in on both sides? For Rise and Put

@alansilva1 
here is the setup for fall contract

![Opera Snapshot_2019-10-19_111315_bot binary com](https://user-images.githubusercontent.com/42480287/67138498-a8d82d80-f261-11e9-82eb-05e7dbbcdbe4.png)

**Comment by navneetsinh** [comment]
@alansilva1 

you can set this as

![Opera Snapshot_2019-10-19_113124_bot binary com](https://user-images.githubusercontent.com/42480287/67138632-2a30bf80-f264-11e9-975e-7661907b02d5.png)

**Comment by alexssadro** [comment]
> @alansilva1
> 
> you can set this as
> 
> ![Opera Snapshot_2019-10-19_113124_bot binary com](https://user-images.githubusercontent.com/42480287/67138632-2a30bf80-f264-11e9-975e-7661907b02d5.png)

Thank you very much friend .... This is my Email friend .... Pass your contact OK. I would like to take a doubt    alansilva433@Gmail.com

**Comment by navneetsinh** [comment]
navneetsinhsb@gmail.com

**Comment by navneetsinh** [comment]
@alansilva1 
Check this post #2038 or 
[Digito entrada no zero% (EDITED).zip](https://github.com/binary-com/binary-bot/files/3747844/Digito.entrada.no.zero.EDITED.zip)

**Comment by alansilva1** [comment]
> > @ alansilva1
> > você pode definir isso como
> > ![Opera Snapshot_2019-10-19_113124_bot binário com](https://user-images.githubusercontent.com/42480287/67138632-2a30bf80-f264-11e9-975e-7661907b02d5.png)
> 
> Muito obrigado amigo .... Este é o meu amigo Email .... Passe seu contato OK. Gostaria de tirar uma duvida [alansilva433@Gmail.com](mailto:alansilva433@Gmail.com)

Thanks for the help friend. Sera if I did something wrong ???? But the robot he is entering at other times. I wanted him to appear one after another until he won.
![ERROR](https://user-images.githubusercontent.com/36489138/67160307-e2726c80-f325-11e9-905d-b3bfd87006dd.PNG)
![ERROR22](https://user-images.githubusercontent.com/36489138/67160308-e2726c80-f325-11e9-961d-c6a55e1d2971.PNG)

**Comment by navneetsinh** [comment]
@alansilva1 your block setup is not completed as I sent

**Comment by alansilva1** [comment]
> @ alansilva1 a configuração do seu bloco não foi concluída como enviei

I'll check friend

**Comment by alansilva1** [comment]
> @ alansilva1 a configuração do seu bloco não foi concluída como enviei

Thank you so much friend ... Robo runs very well. God bless

**Comment by ahmadhus** [comment]
@alansilva1

Dear friend , 

can you send me the final robot file as zip 

best regard

**Comment by Gasha0** [comment]
@alansilva1 i want that bot too best regard

**Comment by Gasha0** [comment]
@alansilva1 

Com licença, na última imagem que você enviou, o que seu bot deixou de funcionar? Porque eu estava tentando muitas coisas e não consigo fazê-lo realizar operações com frequência quando ele perde

![67160308-e2726c80-f325-11e9-961d-c6a55e1d2971](https://user-images.githubusercontent.com/56451198/68095709-87468b00-fe8a-11e9-9f38-d2d9107b44b3.png)

**Comment by navneetsinh** [comment]
@Gasha0 
![Opera Snapshot_2019-11-04_140942_bot binary com](https://user-images.githubusercontent.com/42480287/68108154-05e40c80-ff0d-11e9-81ad-345693726e4c.png)
