### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Gasha0** [binary-com/binary-bot#2040]
I need to program a bot that when I have 6 green candles often throw a downward signal at 7, if you have 6 red candles often that throw a high signal at 7, if you lose keep pulling until you win and if you win keep analyzing

**Comment by navneetsinh** [comment]
@Gasha0 
you can check this and can edit with some blocks #2037

**Comment by Gasha0** [comment]
Oh thank you

**Comment by Gasha0** [comment]
But i dont know how to do it, do you have the xml file?

**Comment by Gasha0** [comment]
[binary-bot.zip](https://github.com/binary-com/binary-bot/files/3748584/binary-bot.zip)

Until there, I don't know how to do the rest

**Comment by Gasha0** [comment]
![67089243-cefbc000-f1c4-11e9-9cfd-a9617bd05574](https://user-images.githubusercontent.com/56451198/67168967-c9e27080-f37e-11e9-9335-dd519669317a.png)

That block I don't know how to do it or put it

**Comment by Gasha0** [comment]
@navneetsinh Hi, sorry to bother you, I was able to build the bot but it doesn't work as I expected, I don't know how to configure blocks (1) and (4)

There is an different (4)
![67138632-2a30bf80-f264-11e9-975e-7661907b02d5](https://user-images.githubusercontent.com/56451198/68095188-2321c800-fe86-11e9-8abb-742f7fdae619.png)

And here is another (4)
![67121918-40aa2d00-f20a-11e9-9bc7-e7d0a3dc817e](https://user-images.githubusercontent.com/56451198/68095198-35036b00-fe86-11e9-8a6b-f33a5b017037.png)

idk how to make it work, there is my xml file
[binary-bot (1).zip](https://github.com/binary-com/binary-bot/files/3802427/binary-bot.1.zip)

**Comment by navneetsinh** [comment]
@Gasha0 ,
here is some pending blocks in (4)
![Opera Snapshot_2019-11-04_140942_bot binary com](https://user-images.githubusercontent.com/42480287/68108118-e2b95d00-ff0c-11e9-977e-7145aacbdcd0.png)
