### ISSUE TITLE
DigitDiff

### ISSUE THREAD

**Issue by basquetemfhx** [binary-com/binary-bot#2041]
Como faço para fazer o bot DigitDiff comprar differs depois que os dois ultimos digitos for dois 0 seguidos?
desse jeito:

11280.34
11280.31
11282.73
11279.20
11283.00 <- Compra Differs 0

11289.57
11287.91
11285.46
11286.80
11284.30<- Compra Differs 0

Eu quero que o bot verifique o último dgit = 0, próximo último dgit = 0 e compre. Como faço isso?
Poderiam me Ajudar?

**Comment by ghossan86** [comment]
English please.. So that more understandable..

**Comment by navneetsinh** [comment]
> Como faço para fazer o bot DigitDiff comprar differs depois que os dois ultimos digitos for dois 0 seguidos?
> desse jeito:
> 
> 11280.34
> 11280.31
> 11282.73
> 11279.20
> 11283.00 <- Compra Differs 0
> 
> 11289.57
> 11287.91
> 11285.46
> 11286.80
> 11284.30<- Compra Differs 0
> 
> Eu quero que o bot verifique o último dgit = 0, próximo último dgit = 0 e compre. Como faço isso?
> Poderiam me Ajudar?

At #2042, @windjenn replied
