### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by Tebu1429** [binary-com/binary-bot#2043]
Good day Guy , 
Can anybody send a bot that has a timestamp or create one for me .

You don't have to put your strategy , I just need a bot that has a timestamp and just test it before if it works. Please , not all of us are good in programming so bare with us if we kinda need help .
Please and thank you .

Just a simple bot that has a timestamp can put end time if necessary. But ain't important at all.

**Comment by navneetsinh** [comment]
> Good day Guy ,
> Can anybody send a bot that has a timestamp or create one for me .
> 
> You don't have to put your strategy , I just need a bot that has a timestamp and just test it before if it works. Please , not all of us are good in programming so bare with us if we kinda need help .
> Please and thank you .
> 
> Just a simple bot that has a timestamp can put end time if necessary. But ain't important at all.

#2026
