### ISSUE TITLE
Backtesting Regards

### ISSUE THREAD

**Issue by ArunGowthamm** [binary-com/binary-bot#2049]
Is it possible to backtesting a bot ..

If it possible it could save more time for testing new bot

**Comment by ArunGowthamm** [comment]
If possible anyone teach me how to do that

Thanks

**Comment by ceakuk** [comment]
no but  you can let it run on demo for different indtruments like volatility100,75,50,25,10 etc. if you use ticks then you need multiple accounts to not run into problems
