### ISSUE TITLE
How to read current default candle interval

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#2054]
Hi, 
I've an odd question,
but can it possible that bot can read default candle interval before purchase contract
it's for taking trade calculation of candles
**example:**
if 'Strategy A' true on 1 minute candle
take trade for 1 * 3 minute duration
@aaron-binary 
@binary-ex-machina

currently I'm doing it manually
![Opera Snapshot_2019-10-24_141956_bot binary com](https://user-images.githubusercontent.com/42480287/67469303-9eef6980-f669-11e9-8fc3-22d774e680bc.png)
![Opera Snapshot_2019-10-24_142020_bot binary com](https://user-images.githubusercontent.com/42480287/67469304-9eef6980-f669-11e9-8b08-78b8ec18c11b.png)

**Comment by binary-ex-machina** [comment]
default candle interval is define once at start, and it's possible to change only manually. You can set the candle interval on each input list you get

![image](https://user-images.githubusercontent.com/34610787/67507399-31d9d500-f665-11e9-9692-b09d40270665.png)

**Comment by navneetsinh** [comment]
Oh, yes @binary-ex-machina.
thanks for responding.
I'm currently using these blocks. I was trying to do it this way but there is no corresponding block. It may be that the block will be found in future. Like Payout block. 
Ok, Thanks.
