### ISSUE TITLE
how to create over 5 under 4 ?

### ISSUE THREAD

**Issue by sl777** [binary-com/binary-bot#2059]
first part? difine trade option part?

**Comment by sl777** [comment]
if some singnal trade over 5
if some signal Under 4.....
i created that but it run over 5 and under 5 first time....  if time under 4 work frist time run under 5... please help this...

**Comment by sl777** [comment]
please help

**Comment by ceakuk** [comment]
@sl777 
its not easy understanding what you are  saying

**Comment by sl777** [comment]
if some signal under 4 if some signal over 5 ...

**Comment by sl777** [comment]
![image](https://user-images.githubusercontent.com/54656820/67855084-c77ad600-fb37-11e9-82ca-a709fa973a5f.png)
wanted add strategy to this part not second

**Comment by sl777** [comment]
![image](https://user-images.githubusercontent.com/54656820/67855213-fee98280-fb37-11e9-922c-119181db058c.png)
like this

**Comment by sl777** [comment]
please help

**Comment by sl777** [comment]
no one help/
