### ISSUE TITLE
Need Profitable Bot 

### ISSUE THREAD

**Issue by aakanksha2000** [binary-com/binary-bot#2061]
Hello guys i'm new here.i have $100 in my binary account. i need to increase the amount using bot.
anyone have profitable bot please send me to my email. laghariaakanksha@yahoo.com
Thanks

**Comment by ceakuk** [comment]
@aakanksha2000 
all those bots y working with long capital like yours  can never succeed in the long run. that  capital is too little. dont bthrow it away here

**Comment by aakanksha2000** [comment]
@ceakuk how much do you prefer to as a capital amount ?
