### ISSUE TITLE
I need To Create An Indicator!

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#2062]
Hi,
Can Someone Please Create the Maximum and Minimum Indicators For Bot Use?
thank you!
best regards

@binary-ex-machina
 @saidforex26

**Comment by Adammodex** [comment]
Please Guys ?! Help !

**Comment by binary-ex-machina** [comment]
Max indicator will the return maximum values on certain period. There is a built-in block on the bot build that will get return the max value of the giving series of values. You can create a sublist of the values, to limit the number of elements that the block will analyse

Example below will get the max value of the last 20 ticks
![image](https://user-images.githubusercontent.com/34610787/68057995-7ead5380-fcd6-11e9-8978-f702208b85e8.png)


example below will return the max value of the last 20 high values of the last 20 candles
![image](https://user-images.githubusercontent.com/34610787/68058031-97b60480-fcd6-11e9-8591-5d9b60363897.png)


Minimum is on the same block and works the same way
![image](https://user-images.githubusercontent.com/34610787/68058050-a3a1c680-fcd6-11e9-85b1-b5fe1733d8f0.png)

**Comment by Adammodex** [comment]
Thank You Very Much, Sir!
Glad, You Helped Me :)
