### ISSUE TITLE
Duration for end of current candle ?

### ISSUE THREAD

**Issue by carlsec** [binary-com/binary-bot#2063]
Hi

I am creating a bot with bollinger bands, when the candle touches the band, the bot does the operation, but I would like him to do that end of that same candle.

Example.
https://www.tradingview.com/x/Q2P0Oyss

**Comment by FlavianoFlavio** [comment]
manda aqui...

**Comment by ceakuk** [comment]
@carlsec 
in the photo we can see that even though the candles close did not cross the BB, the high and low did.
however we can not tell exactly if trades are tacken after 
1) the close of candle and high/low  crosses the BB (use candle index 2 from end)
2) the trades are taken imediately the BB is crosed (use candle index 1 from end)

**Comment by navneetsinh** [comment]
> Hi
> 
> I am creating a bot with bollinger bands, when the candle touches the band, the bot does the operation, but I would like him to do that end of that same candle.
> 
> Example.
> https://www.tradingview.com/x/Q2P0Oyss

@carlsec 
you didn't provided enough data,
check this if you set it up

![Screenshot (2)](https://user-images.githubusercontent.com/42480287/68739334-94901200-060e-11ea-9f22-f291fedac9d7.png)
