### ISSUE TITLE
Bot MACD MA doesn't work (please help)

### ISSUE THREAD

**Issue by Goodluckwal** [binary-com/binary-bot#2064]
Hello Guys
I have bot MACD MA, If the MACD histogram is positive and the candle is above MA 9, it will open a position.
But it doesn't work, there's no trading at all.
Please help friends.
I will attach my bot, but I don't know how to do it.....
Thank you
![Pict2](https://user-images.githubusercontent.com/55231514/67742905-de45fd80-fa4f-11e9-8107-eea394d448b5.png)
![Pict1](https://user-images.githubusercontent.com/55231514/67742908-e4d47500-fa4f-11e9-9aaa-4e2e5e86235f.png)

**Comment by ceakuk** [comment]
@Goodluckwal 
zip/rar the file  then drag and drop in the comments section or  whichever method you used with the images. it works once zipped

**Comment by Goodluckwal** [comment]
Ok ..This is the bot 

[Bot_FallRise_MACD_MA.zip](https://github.com/binary-com/binary-bot/files/3786869/Bot_FallRise_MACD_MA.zip)
