### ISSUE TITLE
PLEASE HOW TO I STOP A BOT AFTER TEN RUNS

### ISSUE THREAD

**Issue by esperanda01** [binary-com/binary-bot#2065]
I HAVE A BOT AND I NEED IT TO STOP IMMEDIATELY IT GETS TO TEN RUNS. I HAVE SEEN THE FUNCTION THAT LOOKS AT  NUMBER OF RUNS BUT I CANT FIND THE FUNCTION THAT STOPS THE BOT. PLEASE ANYONE CAN HELP ???

**Comment by creativi77** [comment]
![image](https://user-images.githubusercontent.com/28829793/67756274-eb82ce00-f9f6-11e9-8c4f-48c12f59c1b0.png)

**Comment by ceakuk** [comment]
@creativi77 
even though no trade will be sent after 10 trades, the bot will continue running and testing that condition. better do it with "trade again"
![Unbenannt](https://user-images.githubusercontent.com/43122491/67826173-fa878000-facb-11e9-8067-ea6af14ecb0b.PNG)
[binary-bot.zip](https://github.com/binary-com/binary-bot/files/3786770/binary-bot.zip)

**Comment by ceakuk** [comment]
or go with in built tool (count runs)
the problem with that that approach is that after the 10 runs, if you want another 10 runs, then you have to clear the popup summery ( like history/data)

![Unbenannt](https://user-images.githubusercontent.com/43122491/67826683-a2ea1400-facd-11e9-9816-634d4f6ca43b.PNG)
[binary-bot(19).zip](https://github.com/binary-com/binary-bot/files/3786795/binary-bot.19.zip)
