### ISSUE TITLE
Help setting up a bot

### ISSUE THREAD

**Issue by jose895** [binary-com/binary-bot#2069]
I want to program a bot that sells the gains at + 80% and the losses at -30%, please help

**Comment by jose895** [comment]
.

**Comment by ceakuk** [comment]
@jose895 
you are dreaming

**Comment by binary-ex-machina** [comment]
@jose895 you can add the logic for sell at the market like the image below. It will sell the contract at 80% or at -30% loss

![image](https://user-images.githubusercontent.com/34610787/68075875-a828b680-fd8c-11e9-89ab-0e9a84a5f92b.png)

**Comment by jose895** [comment]
Thank you very much I will try it
