### ISSUE TITLE
Two candle different time frame

### ISSUE THREAD

**Issue by ubanemas** [binary-com/binary-bot#207]
can you help me please,
if candle in time frame 5 minutes is black
and candle in time frame 1 minutes is black 
do, purchase fall (put) 5 tick
else purchase rise
it is possible in binary bot?

**Comment by Fruitfella** [comment]
bisa kalo pake trik sedikit. cuma agak ribet.
gini caranya :
1. di block Trade Definition (T1) ubah Candle interval -> 5 minute
2. di block Before Purchase (P2) buat begini logikanya: 
-setiap muncul lilin baru dan setiap 60 detik kemudian simpan harga saat itu sebagai harga open utk lilin 1 menit, kamu bisa membanding harga tsb dengan last tick utk menentuka apakah lilin 1 menit itu naik atau turun.
-utk menentukan arah lilin 5 menit kamu bisa pakai block candle is black.
nah, udah bisa kebayang kan harus gimana selanjutnya?

**Comment by ubanemas** [comment]
Wah mantab ne mastah, boleh dikirim kan ke email, btw aku Dari Malang, lha mas nya asal?

**Comment by Fruitfella** [comment]
anak medan neh hahaha.
alamat imel nya?

**Comment by ubanemas** [comment]
ubanemas@gmail.com trims

**Comment by Fruitfella** [comment]
udah aq kirim bro @ubanemas .
btw kalo mau coba2 robot strategy pake multi Time Frame, tunggu aja om amin selesaiin #91, pake itu kita gak perlu lagi ribet2 and njelimet.

**Comment by aminmarashi** [comment]
I assume this is resolved, if not please feel free to reopen the issue.
