### ISSUE TITLE
Need assistance for creating PROFITABLE strategies 

### ISSUE THREAD

**Issue by DzeeQeer** [binary-com/binary-bot#2072]
Hai, I've got a strategy in Digit Differ, but it's hard for me to compile it to bot binary, is there anyone that could help me, please?

Here's the rule or strategy :

1. Analyze on V10 and Open Position on V100.

2. Analyze LDP on every close candle 3 minute.

3. Open Position on second 58 before close candle 3 Minute (ex: MM:SS, 02:58, 05:58, 08:58, 11:58, 14:58, etc).

4. Menu Digit Differs.

5. LDP obtained from the last digit of multiplication between last 2 digit behind the coma (decimal number) as primary number and the last digit from behind the coma (decimal number also, it's the third digit from the coma) as multiplier.

Example there is a price 7,280.123 so we multiply 12 and 3 = 36 and it's LDP is 6.

Another example there is a price 7,299.435 so we multiply 43 and 5 = 215 and it's LDP is 5.

6. We perform obtaining LDP only if there's a closed candle 3 minutes.

7. We don't perform the calculation of LDP if there is 3 or 6 right behind the coma decimal. Example price X,XXX.3YY dan X,XXX.6YY.

Thank you,

Best Regards!

**Comment by windjenn** [comment]
for digit differ u want to calculate so hefty formula? its all random numbers i think its not worth it

**Comment by DzeeQeer** [comment]
> for digit differ u want to calculate so hefty formula? its all random numbers i think its not worth it

For manual trading, it's quite profitable. I got 40 winstreak a day. Just imagine if you compound the result quite promising. I've just got tired to trading manual

**Comment by eonuoha30** [comment]
Its also possible to get 100 win streak in digit differs

The TRUTH remains that , even without all these ur kenghty formula, a normal digit differ can yield same or even better result

**Comment by sinung21** [comment]
how many tick for open position?

**Comment by binary-ex-machina** [comment]
@DzeeQeer on real account? how many weeks doing that? I believe you are running this for some weeks at least to consider "promising", right? just 1-3 days is doesn't count as statistics for any idea of consistent strategy, specially for digits

**Comment by DzeeQeer** [comment]
> @DzeeQeer on real account? how many weeks doing that? I believe you are running this for some weeks at least to consider "promising", right? just 1-3 days is doesn't count as statistics for any idea of consistent strategy, specially for digits

Yes it is a real account.
It's just around 1 month +- 2 or 3 weeks I used this strategy. Yeah you're right it's not a perfect strategy that never get any losses, but it's quite profitable in my opinion especially if we used martingale. In my own experience never got 2 loss streak using this strategy. Trading this strategy just spending our time so much. Currently I can't get that much time for manual trading, so I like to find any alternative to trade on bot.

**Comment by DzeeQeer** [comment]
> how many tick for open position?

1 tick sir

**Comment by sinung21** [comment]
@DzeeQeer JADI INI op y nunggu candle 3 menit berakhir dan nunggu lagi  candle 3 mnit berikut tetapi op di detik 58 sebelum candle 3 mnt berakhir yah?

**Comment by DzeeQeer** [comment]
> @DzeeQeer JADI INI op y nunggu candle 3 menit berakhir dan nunggu lagi candle 3 mnit berikut tetapi op di detik 58 sebelum candle 3 mnt berakhir yah?

You could trading on every 3 minutes. No need to wait 3 minutes candle ended.
Step:
1. Look at price previous candle 3 minutes
2. Trading at almost closed candle 3 minutes next to point 1

**Comment by DzeeQeer** [comment]
@windjenn 
@binary-ex-machina

**Comment by binary-ex-machina** [comment]
You really think that there is a logic behind placing differ trades based on the tick multiplied by 12 at the last tick of a 3min candle? why not on 4min candle? why not on the first tick? sorry this is non sense. Like @windjenn posted, it's all random, you can do any sort of complex analysis on digits, on 1000 trades, the result will be always close to 90% win rate and 10% loss on differs. 

People need to understand that digits are random and stop believing in myths about prediction, it's impossible

**Comment by windjenn** [comment]
> @windjenn
> @binary-ex-machina

Bro in my opinion if invest ur time in rise and fall , it will be more profitable . 
i traded a lot on digits , i kept earning for 2 months bt one day all my profit + capital gone in just one day.coz i became over confident on the strategy i was using . 
Reality is there is no real strategy for digits , its a pure random game.
Many people selling strategies , saying never loss , 90 percent win even 100 percent win. 
All are lies , if there is any such strategy they dont need to sell those, they can make money by their strategy n enjoy their life. But they try to find desperate people to sell their creepy formula.

IF they wanna do something good for other people they could do something like @binary-ex-machina does. 
earn commission when people are winning

**Comment by alanvito1** [comment]
Look my stuff and feel inspirated.

https://github.com/alanvito1/superfree-binary-bot
