### ISSUE TITLE
Help me build a stoploss

### ISSUE THREAD

**Issue by bas22boy** [binary-com/binary-bot#2073]
Hello, im not good at building bots so that why im asking for help.
I have a idea for a stop loss it goes like this. You would with 0.35 cents if you make profit 2x in a row it will go to 0.70 cents and if u would win 2x again it would be 1.40 etc etc. But if you would lose for example at the 1.40 round you would go back a round to 0.70 cents.

**Example**

+1.40=_Profit_
+0.70=_Profit_
+0.70=_Profit_
-1.40=_Loss_
+1.40=_Profit_
+0.70=_Profit_
+0.70=_Profit_
+0.35=_Profit_
+0.35=_Profit_

**Comment by binary-ex-machina** [comment]
maybe is not stop loss, but stake you are referring. Stop loss exist to make the bot stop the losses and save the account from blowing up. In case is the stake, you can follow the image below

![image](https://user-images.githubusercontent.com/34610787/68058539-28d9ab00-fcd8-11e9-96a2-8394cea35b4a.png)
