### ISSUE TITLE
 What functions should I use? 

### ISSUE THREAD

**Issue by BlackenedDoom** [binary-com/binary-bot#2074]
I am recently starting to study the guidelines for creating a bot in Binary, and I would like to ask for advice on the following question, if I would like to create a bot that runs Rise/Fall only at specific times.

For example open trade Rise at 01:15:00, and then a second Rise at 01:18:00

What functions to use and how?

Thank you in advance for the advice you can give me :)

**Comment by binary-ex-machina** [comment]
to make such filter tom start the trades, you need to get the hour, minute and second of the actual timestamp, compare and get from the list of "dates" you want to make trades

Below an example of how can you build such logic, the trades will happen at 01:15:00 and at 01:18:00 (GMT)

![image](https://user-images.githubusercontent.com/34610787/68058251-46f2db80-fcd7-11e9-9eed-37620bd2efb9.png)

**Comment by Tebu1429** [comment]
Can you create a bot exactly like that one on the image with timestamp ,I
need a bot that has a timestamp ,but when I put timestamp n seconds the bot
does not run at a specific time I wanted it to run.

**Comment by binary-ex-machina** [comment]
@Tebu1429 there is no sense in playing at some seconds. You need to put as I put in the image

1:15(what you have to put on the list) = 01:15:00 (the time the trade will start) = One hour and fifteen minutes and zero seconds

**Comment by BlackenedDoom** [comment]
@binary-ex-machina Thank you for the detailed answer :) what programming language do you recommend me to learn? to better understand the development of bot in binary

**Comment by binary-ex-machina** [comment]
To build bots on the blocks site, just get a lot of the bots (and images i provided in a lot of issues here in the repository) and try to recreate them and understand how they work. If you have 100 strategies and try to implement 1 per day and learn about, in 3 months you will be building everything and will not depend on anyone to test your ideas.
