### ISSUE TITLE
MACD bot

### ISSUE THREAD

**Issue by Rover1953** [binary-com/binary-bot#2075]
Привет коллеги трейдеры! Подскажите как создать MACD bot, чтобы вход в сделку происходил при следующих условиях: сделка PUT если линия MACD пересекает сигнальную линию сверху вниз выше нулевого уровня, а гистограмма переходит под нулевой уровень. И наоборот: сделка СALL если линия MACD пересекает сигнальную линию снизу вверх ниже нулевого уровня, а гистограмма появляется соответственно над нулевым уровнем. Вобщем обычные сигналы по MACD. Надо чтобы бот смог поймать это пересечение линии MACD и сигнальной линии. Заранее огромное спасибо.

**Comment by binary-ex-machina** [comment]
maybe in english more people can help you

**Comment by Rover1953** [comment]
Hello fellow traders! Tell me how to create a MACD bot so that the entry into the transaction occurs under the following conditions: PUT trade if the MACD line crosses the signal line from top to bottom above the zero level, and the histogram appears below the zero level.  And vice versa: a CALL trade if the MACD line crosses the signal line from bottom to top below the zero level, and the histogram appears respectively above the zero level. These are ordinary signals received from MACD. It is necessary for the bot to catch this intersection of the MACD line and the signal line. Thank you very much in advance.

**Comment by binary-ex-machina** [comment]
The crossing logic you can do like the image below. Every time the MACD crosses over the Signal, the histogram will be above 0, no matter where the cross happen. The inverse will result in a Histogram below 0, no matter the the place this happens (above/below 0). You can change the input list for ticks, in case you are going to go for fast trading.

![image](https://user-images.githubusercontent.com/34610787/68075609-c5f41c80-fd88-11e9-9dff-65357e05fe08.png)

**Comment by Rover1953** [comment]
Please send it in XML format. Thank You.


сб, 2 нояб. 2019 г. в 20:54, Binary Ex Machina <notifications@github.com>:

**Comment by Rover1953** [comment]
I'm not able to find the highlighted blocks, therefore i ask You to send
the bot in HML format and together with martingale option.
Thank You.

сб, 2 нояб. 2019 г. в 20:54, Binary Ex Machina <notifications@github.com>:

**Comment by Rover1953** [comment]
Many thanks for Your help, I have found the missing blocks and now will
check how the bot works!
Have a nice day!


сб, 2 нояб. 2019 г. в 21:38, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by Rover1953** [comment]
Unfortunately bot doesn't work, an ad appears in the bottom right
"undefined is not a function".
I assembled the bot exactly according to your scheme.
Please see the attached pictures and bot HML file.

вс, 3 нояб. 2019 г. в 20:25, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by binary-ex-machina** [comment]
@Rover1953 my mistake change the second to signal instead of macd

![image](https://user-images.githubusercontent.com/34610787/68090450-a6292b00-fe52-11e9-86bc-376f9873f850.png)

**Comment by Rover1953** [comment]
OK, done, now works without error, waiting for results.
Thank You!

вс, 3 нояб. 2019 г. в 20:57, Binary Ex Machina <notifications@github.com>:
