### ISSUE TITLE
It would be great if there are...

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#208]
![002](https://cloud.githubusercontent.com/assets/26277327/25691114/1a5b4168-30c2-11e7-8882-e4794c97fa1d.PNG)

1-4, with these some strategies that use candles in 2 or more Time Frames (#207) can be easily applied. since binary option mostly traded on small TF, dropdown menu with 1Minute, 5Minutes,10,15,30 and 1hour is good enough.

5-6, with these we can continue martingale strategy even after restart. maybe some strategies can also use these.

7, if there is a sound when something happen (open purchase, close purchase, error) that will help bot testing and maybe wake me up when i fall asleep (lol kidding).

**Comment by aminmarashi** [comment]
1-4 it's been planned for a long time: #91 delayed because of more important tasks.

**Comment by Fruitfella** [comment]
too bad for 5-6. if it can be made, it would solve martingale problem cause by error like #158.
ill wait for #91 and #209.
if only i know programming, i would definitely help mysel.. *cough**cough* help you make those 1-4.

**Comment by aminmarashi** [comment]
Once we finish #191 martingale does not have to worry about restarting. We keep the state of everything and restore the state after restart automatically.
