### ISSUE TITLE
Help in modifying A Bot

### ISSUE THREAD

**Issue by windjenn** [binary-com/binary-bot#2080]
Hi , frnds 

i tried to modify a bot with 3 RSI strategy as follows:- 
For rise 
RSI (Period 50) above LEVEL 53
RSI (Period 24) above LEVEL 50
  THE TRIGGER POINT When RSI (Period 2) goes above LEVEL 80 

FOR PUT trade
RSI (Period 50) below LEVEL 47
RSI (Period 24) below LEVEL 50
  THE TRIGGER POINT When RSI (Period 2) goes below LEVEL 20

I am attaching the bot which i tried to modify but it taking trades on RSI PERIOD 2 only , not considering other 2 RSI i added.
IF anyone can modify it 
[RSI RISE FALL WIND.zip](https://github.com/binary-com/binary-bot/files/3800467/RSI.RISE.FALL.WIND.zip)

**Comment by binary-ex-machina** [comment]
change the block 2 to this one

![image](https://user-images.githubusercontent.com/34610787/68075772-32701b00-fd8b-11e9-8c1a-14b6b29f57ad.png)

**Comment by windjenn** [comment]
> change the block 2 to this one
> 
> ![image](https://user-images.githubusercontent.com/34610787/68075772-32701b00-fd8b-11e9-8c1a-14b6b29f57ad.png)

Thanks bro , its working now
