### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Gasha0** [binary-com/binary-bot#2081]
Could someone build a block that recognizes for example a value of -5.40 and makes an alert in the form of a popup? better if the popup can make noise, also if I would be kind enough to send the block to be downloaded, I have no idea how to do it by myself, I'm sorry

**Comment by Gasha0** [comment]
I need the block not to interrupt the bot from throwing operations, just alert

**Comment by binary-ex-machina** [comment]
@Gasha0 you can use the block Print, it will create an alert without stopping the operations

![image](https://user-images.githubusercontent.com/34610787/68075741-b83f9680-fd8a-11e9-9fbb-02e776265ada.png)

you can use the Notify block as well to just create a popup (can have a sound) 

![image](https://user-images.githubusercontent.com/34610787/68075748-d0171a80-fd8a-11e9-8216-4e368bf33dab.png)

**Comment by Gasha0** [comment]
Sure, but I need you to let me know if an operation is in -X amount, not if the total profit is -X, I don't know if it's possible to do that

**Comment by binary-ex-machina** [comment]
you want to know how much profit the actual operation is? use this block below

![image](https://user-images.githubusercontent.com/34610787/68076718-4b7ec900-fd97-11e9-8e87-1263f7d10ab8.png)

**Comment by Gasha0** [comment]
Or if not, somehow notify me with a popup / sound when you lose X martingale level

**Comment by Gasha0** [comment]
Oh thank you i will try it

**Comment by Gasha0** [comment]
I placed them but it makes sound every time you throw an operation and not when you lose it in -X amount as I want

**Comment by Gasha0** [comment]
For example, there are 5 martingale, I need you to let me know when you lose the 5th,
-1.00
-2.00
-4.00
-8.00
-16.00
-32.00 <---- Alert on this

**Comment by binary-ex-machina** [comment]
you need to specify better what you want to do. Look at your main question and how it's very far from what you really want. You want the notification to come if the bot hit 5 losses in row.

![image](https://user-images.githubusercontent.com/34610787/68076881-723dff00-fd99-11e9-8e01-44c941e1a7ea.png)

**Comment by Gasha0** [comment]
Sorry, I don't speak English, I'm using the translator :(

**Comment by Gasha0** [comment]
Thank you very much

**Comment by Gasha0** [comment]
and sorry again

**Comment by Gasha0** [comment]
@binary-ex-machina Thank you so muchhhhhhhh <3
