### ISSUE TITLE
Any genius?

### ISSUE THREAD

**Issue by wallpersonal** [binary-com/binary-bot#2082]
...

**Comment by binary-ex-machina** [comment]
@wallpersonal to understand your question is a genius job. You want to calculate the number of losses since the last win? the total number of losses since you started the bot? 

for calculating the number of losses in row (since last win)
![image](https://user-images.githubusercontent.com/34610787/68123890-d91ffd00-feec-11e9-8ead-816bf7ab845b.png)

**Comment by ceakuk** [comment]
@wallpersonal 
do as @ says or create an empty list and populate it with +1(win) and -1(loss)
thatway you have a whole pictures since you started trading and you can do whatever you wish with more advanced analysis  with the number of wins/losses

**Comment by alanvito1** [comment]
Look this stuff @wallpersonal :
https://github.com/alanvito1/superfree-binary-bot

**Comment by wallpersonal** [comment]
> @wallpersonal to understand your question is a genius job. You want to calculate the number of losses since the last win? the total number of losses since you started the bot?
> 
> for calculating the number of losses in row (since last win)
> ![image](https://user-images.githubusercontent.com/34610787/68123890-d91ffd00-feec-11e9-8ead-816bf7ab845b.png)

Bom dia meu amigo! A muito te admiro! Melhora ainda eh saber que eh brazuca! :D

Entao, estou com um projeto de um bot que tem barreira no call e no put. Eu consegui fazer o bot numa boa, mas preciso ficar "chamando"  aposta call ou put qdo da LOSS e quando da play.

Existe alguma maneira de ele pegar a analise do bot, caso esteja bom call usa call, e caso bom put, usar put???

Em miudos, gostaria de usa sempre a analise do bot e nao ter que ficar chamando apos vitoria ou derrota, ele escolher se vai ou nao call e put... com barreiras opostas ficou dificil visto que preciso diferencia-los na segunda parte do bloco 1.

**Comment by wallpersonal** [comment]
> Look this stuff @wallpersonal :
> https://github.com/alanvito1/superfree-binary-bot

Acho que vc eh Brazuca... obrigado pela dica.
