### ISSUE TITLE
Help Change Barrier Offset

### ISSUE THREAD

**Issue by viberjet** [binary-com/binary-bot#2083]
Dear  @aaron-binary @hotmatrixx @James-Ngigi @romeo1911 @binary-ex-machina

Please Help me, how to create bot change barrier based strategy?
Ex:

With stategy 1, i want change barrier to - 1, and purchase higher
With stategy 2, i want change barrier to +1, and purchase lower

if possible please send me the xml file , because I am beginner

Thanks a lot

**Comment by viberjet** [comment]
Dear @binary-ex-machina
some time age yo have answered to similar issue  at here : https://github.com/binary-com/binary-bot/issues/1559
please send me the xml file
Yhanks again

**Comment by binary-ex-machina** [comment]
@viberjet i'll not send anything besides the image. In case you don't know how to use the mouse and follow a picture to build the bot, keep trying. I'm sure one day you will be able to have the same bot as i sent on the image

**Comment by viberjet** [comment]
> @viberjet i'll not send anything besides the image. In case you don't know how to use the mouse and follow a picture to build the bot, keep trying. I'm sure one day you will be able to have the same bot as i sent on the image

Thanks for quick answer
You are right
i will try

**Comment by viberjet** [comment]
> @viberjet i'll not send anything besides the image. In case you don't know how to use the mouse and follow a picture to build the bot, keep trying. I'm sure one day you will be able to have the same bot as i sent on the image

Hi again @binary-ex-machina

i can not find the : " length of " 

![length of](https://user-images.githubusercontent.com/46893330/68085040-4aaa6d80-fe51-11e9-863f-1d34367d6d4d.jpg)

Please help me
Thanks

**Comment by binary-ex-machina** [comment]
@viberjet click on every menu item in the left menu, read all blocks with caution. You will find it

**Comment by viberjet** [comment]
> @viberjet click on every menu item in the left menu, read all blocks with caution. You will find it
@binary-ex-machina
Thanks Bro
You are Prefect
God Bless You

**Comment by Herotaiko** [comment]
@binary-ex-machina 
If I want to use HMA I do not know how my mistakes where bots are not running.


![q3](https://user-images.githubusercontent.com/51996252/68138735-95181100-ff5b-11e9-93d6-45c44d6fb8da.JPG)

**Comment by binary-ex-machina** [comment]
@Herotaiko what is the initial value of this variable 
![image](https://user-images.githubusercontent.com/34610787/68139570-15f9ed00-ff09-11e9-9a69-f658d7a544b1.png) ?

**Comment by Herotaiko** [comment]
@binary-ex-machina 
zero
![q4](https://user-images.githubusercontent.com/51996252/68139879-7dda2300-ff5d-11e9-974e-f9728baeb77a.JPG)

**Comment by binary-ex-machina** [comment]
on block 2 use HMAstrategy variable

**Comment by Herotaiko** [comment]
@binary-ex-machina It works. Thank you, brother.

**Comment by viberjet** [comment]
> @binary-ex-machina It works. Thank you, brother.

Hi  @Herotaiko 

Please send me final xml file

I could not build it , Thanks

**Comment by alanvito1** [comment]
Hello guys!

Look for inspiration here all free:

https://github.com/alanvito1/superfree-binary-bot
