### ISSUE TITLE
Help to build bot with indicator : Choppiness index

### ISSUE THREAD

**Issue by viberjet** [binary-com/binary-bot#2084]
Dear @binary-ex-machina

is it possible to create a bot with Choppiness index indicator with this strategy :

when the chop indicator's Line Break with high Angle , then bot will trade call or put , 

please see the below image : 

![Choppiness Index](https://user-images.githubusercontent.com/46893330/68079828-33459300-fe05-11e9-8911-6e7bc734acc6.jpg)

Thanks a lot

**Comment by ahmadhus** [comment]
.

**Comment by ceakuk** [comment]
its possible.
say you are using a period of =x ticks;
if average true range is say (y), then rise fall  for a 45° angle =x.y
compare that with your actual   ticks rise  
its even possible to use fancy COS(theta), SIN(theta), TAN(theta) to make your threshold on the choppiness indicator.

i just wanted to give you a hint but im not motivated to use more effort than that.  first try  by manual visualization and it it gives good results then i'll create for you a bot. Good luck

**Comment by viberjet** [comment]
> its possible.
> say you are using a period of =x ticks;
> if average true range is say (y), then rise fall for a 45° angle =x.y
> compare that with your actual ticks rise
> its even possible to use fancy COS(theta), SIN(theta), TAN(theta) to make your threshold on the choppiness indicator.
> 
> i just wanted to give you a hint but im not motivated to use more effort than that. first try by manual visualization and it it gives good results then i'll create for you a bot. Good luck

Thanks a lot @ceakuk 

But I don't understand completely what you mean
please explain more for me because i am beginner

Thanks for your help

**Comment by windjenn** [comment]
> > its possible.
> > say you are using a period of =x ticks;
> > if average true range is say (y), then rise fall for a 45° angle =x.y
> > compare that with your actual ticks rise
> > its even possible to use fancy COS(theta), SIN(theta), TAN(theta) to make your threshold on the choppiness indicator.
> > i just wanted to give you a hint but im not motivated to use more effort than that. first try by manual visualization and it it gives good results then i'll create for you a bot. Good luck
> 
> Thanks a lot @ceakuk
> 
> I am using 5 Ticks ,
> But I don't understand completely what you mean
> please explain more for me because i am beginner
> 
> Thanks for your help

i think @ceakuk meant to say , try ur strategy in manually first and if it can give good results and if u can show results and explain ur strategy then he can create a bot for u.
