### ISSUE TITLE
Binary bot help with a strategy

### ISSUE THREAD

**Issue by binary-dice** [binary-com/binary-bot#2088]
Hello guys i would like to know if it is possible for someone to help me set a bot that will play on  digit over/under with the purchase condition of having each one of the last digit of the last 4 ticks > to 6 and the prediction set at 7 and going under

**Comment by navneetsinh** [comment]
@binary-dice 
![Opera Snapshot_2019-11-04_181813_bot binary com](https://user-images.githubusercontent.com/42480287/68122091-916e9500-ff2f-11e9-8ecb-70bee1ef3055.png)

**Comment by binary-dice** [comment]
Thank you 🙏 that was of a big help

**Comment by binary-dice** [comment]
@navneetsinh could you send it to me in .xml file

**Comment by sinung21** [comment]
@binary-dice what volatility u used?

**Comment by binary-dice** [comment]
@sinung21 volatility 10

**Comment by sinung21** [comment]
[U-7 diatas 6 v10.zip](https://github.com/binary-com/binary-bot/files/3820919/U-7.diatas.6.v10.zip)

**Comment by alanvito1** [comment]
Look for Demon Digits.

https://github.com/alanvito1/superfree-binary-bot
