### ISSUE TITLE
Help me in my bot

### ISSUE THREAD

**Issue by zsssss20** [binary-com/binary-bot#2089]
Hello Guys! 
I'm creating my bot like that. 
Rise-Rise-Rise...etc and adding martingale ×2 but for the winning

**Comment by navneetsinh** [comment]
@zsssss20 
I just created some blocks,
check it,

![Opera Snapshot_2019-11-04_181022_bot binary com](https://user-images.githubusercontent.com/42480287/68121719-78191900-ff2e-11e9-9ee1-51671793b9e3.png)

**Comment by zsssss20** [comment]
@navneetsinh Thanks!! But I have question please, does the lost amount means only the first lost trade or all the loss trades amount? Beacuse I want to multiply the first loss trade only that comes after winning trades 
Like the 16×2 and then reset

**Comment by navneetsinh** [comment]
@zsssss20 
you can create that blocks and test it,
by the way in that configuration,
lost amount will added untill it covers on win

**Comment by zsssss20** [comment]
@navneetsinh I will. Do you have an idea how to keep it working even after covering on wins?

**Comment by alanvito1** [comment]
Hello guys!
I'm here to share some startegies.

https://github.com/alanvito1/superfree-binary-bot

**Comment by zsssss20** [comment]
@navneetsinh bro how can I make 5 rise 3 fall and keep repeating bot?

**Comment by navneetsinh** [comment]
> @navneetsinh bro how can I make 5 rise 3 fall and keep repeating bot?

@zsssss20 
Check this ,

![Screenshot (1)](https://user-images.githubusercontent.com/42480287/68671831-4b8c7f00-0576-11ea-9378-db727785308a.png)

**Comment by zsssss20** [comment]
@navneetsinh thanks bro!! You're amazing! Sorry I asked a lot but do you have an idea how to create a bot that starts after 3 same ticks? Like this: if 3 ticks were fall then purchase rise or if 3 ticks were rise then purchase fall 
I mean only trade after 3 ticks are the same ?

**Comment by navneetsinh** [comment]
> @navneetsinh thanks bro!! You're amazing! Sorry I asked a lot but do you have an idea how to create a bot that starts after 3 same ticks? Like this: if 3 ticks were fall then purchase rise or if 3 ticks were rise then purchase fall
> I mean only trade after 3 ticks are the same ?

@zsssss20 

![Screenshot (2)](https://user-images.githubusercontent.com/42480287/68673750-77116880-057a-11ea-96f5-ce223c33b4f2.png)

**Comment by zsssss20** [comment]
@navneetsinh bro. Couldn't find some blocks that you used. Can you add a xml file?

**Comment by navneetsinh** [comment]
@zsssss20 
all blocks available in left panel

**Comment by zsssss20** [comment]
@navneetsinh I know bro but I couldn't find the (and) block. I found one and it has 1 empty box from each side

**Comment by navneetsinh** [comment]
@zsssss20 
it is the same block for and
right click on " and " block external inputs
![Screenshot (2)](https://user-images.githubusercontent.com/42480287/68681069-b6df4c80-0588-11ea-89d8-40183d90dc01.png)

**Comment by zsssss20** [comment]
@navneetsinh bro. How can I change it to seconds? Like if last 2- 15 seconds which equals 30 seconds were rise purchase 15 seconds fall?

**Comment by navneetsinh** [comment]
@zsssss20 exactly, I don't understand what you want to configure??

**Comment by zsssss20** [comment]
@navneetsinh now the bot works if 3 ticks were rise then purchase fall or of 3 ticks were fall then purchase rise. I want to make it if the 15 seconds were rise 2 times which means 30 seconds then purchase 15 seconds fall and if they were fall then purchase rise . Hope you understood me

**Comment by zsssss20** [comment]
@navneetsinh bro can you check the last issue i added?

**Comment by navneetsinh** [comment]
@zsssss20 ,
here is we can set seconds for some kind of calculations,15 seconds is approximately between 7 to 8 ticks, so you can set up it with 7 or 8 ticks calculation
here is block setup for 8 ticks

![Screenshot (3)](https://user-images.githubusercontent.com/42480287/69173175-4060c280-0b25-11ea-828a-46266c09b72c.png)

**Comment by zsssss20** [comment]
@navneetsinh bro you are great 
last question bro. i want to make my martingale works after 2 losses like that: if i lost for 2 times in a row then multiply the stake by 2 but i tried a lot and couldn't find any way to do it :( can you help me please

**Comment by navneetsinh** [comment]
> @navneetsinh bro you are great
> last question bro. i want to make my martingale works after 2 losses like that: if i lost for 2 times in a row then multiply the stake by 2 but i tried a lot and couldn't find any way to do it :( can you help me please

@zsssss20 ,
Check on #2141 
Kindly don't post same issues in other issues
Dear, It's better to open new issue for looking around
