### ISSUE TITLE
Why are the graphs displayed on the website and MT5 not matching?

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#2091]
I would like to know if the graph is shown on the website and MT5 match or not, The prices and the graphs are different and when the trading bots do not match. Not a delay.

![111](https://user-images.githubusercontent.com/51996252/68131356-7e6bbd00-ff4f-11e9-91f9-127f3d0bf379.JPG)

![22](https://user-images.githubusercontent.com/51996252/68131113-0dc4a080-ff4f-11e9-836e-2db1f018a6a7.JPG)

 I want to know if someone is like me?

**Comment by windjenn** [comment]
the chart in ur bot page is not of v100

**Comment by anton-binary** [comment]
Hi @Herotaiko, what was the date/time for the MT5 chart, it's not clear from your screenshot.
