### ISSUE TITLE
Anyone always profitable

### ISSUE THREAD

**Issue by mbarneskar** [binary-com/binary-bot#2092]
I have tried many years to become profitable at trading. Some times it gets very good, then it booom, lose so much.

Anyone that is profitable, and can really rely on your system?

Is it binary.com that makes it impossible to win in the long term?

**Comment by Ares31** [comment]
No creo q alguien viva de esto... si alguien lo hiciera ya habrian compartido la estrategia o puesto en venta... pero es mi opinion

**Comment by alanvito1** [comment]
You win, you loss, but you have to know be profitable.

Try some tools.

https://github.com/alanvito1/superfree-binary-bot
