### ISSUE TITLE
alguém consegue criar um bot com estas estratégias ? 

### ISSUE THREAD

**Issue by GoncalvesF253** [binary-com/binary-bot#2096]
[Passaword= bull.pdf](https://github.com/binary-com/binary-bot/files/3811804/Passaword.bull.pdf)
[DIGITS MATCHES Trsdingsignalbinary.com.pdf](https://github.com/binary-com/binary-bot/files/3811805/DIGITS.MATCHES.Trsdingsignalbinary.com.pdf)
[TRADER VOLINDEX VOL 10_ENGLISH.pdf](https://github.com/binary-com/binary-bot/files/3811807/TRADER.VOLINDEX.VOL.10_ENGLISH.pdf)

**Comment by windjenn** [comment]
> [Passaword= bull.pdf](https://github.com/binary-com/binary-bot/files/3811804/Passaword.bull.pdf)
> [DIGITS MATCHES Trsdingsignalbinary.com.pdf](https://github.com/binary-com/binary-bot/files/3811805/DIGITS.MATCHES.Trsdingsignalbinary.com.pdf)
> [TRADER VOLINDEX VOL 10_ENGLISH.pdf](https://github.com/binary-com/binary-bot/files/3811807/TRADER.VOLINDEX.VOL.10_ENGLISH.pdf)

files password protected
the password u provided not working

**Comment by FlavianoFlavio** [comment]
Password for volindex 10 is = profitable. 
Password Bull it is = bull

**Comment by ceakuk** [comment]
@FlavianoFlavio 
is it only me who dont get what the hell you are talking about.
anyway i'll give you 1000$ if you can prrove in a real account that you can win 111 out of 1000 trades.
can we make a deal. I'll pay you by paypal

**Comment by FlavianoFlavio** [comment]
@ceakuk My question was if anyone could make a bos with the above strategies, if you don't know how to bot, your opinion is unnecessary.

**Comment by alanvito1** [comment]
Look that:
https://github.com/alanvito1/superfree-binary-bot/blob/master/BOT0017%20-%20Professor%20Inv.xml
