### ISSUE TITLE
DIGIT DIFFER WITH CHANGE LAST DIGIT PREDICTION

### ISSUE THREAD

**Issue by Agentsbu** [binary-com/binary-bot#210]
HI AMIN, CAN YOU PLEASE UPLOAD A DIGIT DIFFER BOT THAT CAN CHANGE LAST DIGIT PREDICTION. lets say it trade :  last digit is not 1 after 5 ticks, next trade must say is not 2 after 5 ticks and so on.....

**Comment by Fruitfella** [comment]
im not amin, but i can give u a sample if u want

**Comment by Fruitfella** [comment]
lol, kidding. here..
![contohprediksi](https://cloud.githubusercontent.com/assets/26277327/25781725/5e8fa2dc-3367-11e7-9854-ae08a9f11545.jpeg)

**Comment by Agentsbu** [comment]
OH!!!! MY MAN, IT WORKS GOT IT MAN, THANKS A MILLION. HALA @FRUITFELLA!!!!

**Comment by sunny199112** [comment]
bro...always change the prediction after 100 trade it gives yoU 100% sUre i am bro..
