### ISSUE TITLE
hello anybody have a profitable bot?

### ISSUE THREAD

**Issue by yakturkt** [binary-com/binary-bot#2101]
hello anybody have a snowy bot?

**Comment by binary-ex-machina** [comment]
how is that? it's like some decoration on the blocks? a new theme?

**Comment by yakturkt** [comment]
I meant profitable

**Comment by binary-ex-machina** [comment]
Yeah, any bot that can make martingale. Select a good entry point, make 1% a day and stop

**Comment by alanvito1** [comment]
Hello,

Here we are:
https://github.com/alanvito1/superfree-binary-bot

**Comment by Ares31** [comment]
1% del capital invertido ???

**Comment by ZDEGLET** [comment]
@alanvito1 как запустить ваших ботов
