### ISSUE TITLE
can you make a bot like this video?

### ISSUE THREAD

**Issue by yakturkt** [binary-com/binary-bot#2103]
https://www.youtube.com/watch?v=EzYdBJjun1Q&t=1158s

**Comment by viberjet** [comment]
what is the strategy ?
please send the strategy in English , Then i will create Bot for you

**Comment by yakturkt** [comment]
strateji:over under   Last Digit Prediction:2  When any one of the numbers 0,1,2 arrives, can you make the bot to open an over?

**Comment by yakturkt** [comment]
> @yakturkt
> what is the strategy ?
> please send the strategy in English , Then i will create Bot for you

strateji:over under Last Digit Prediction:2 When any one of the numbers 0,1,2 arrives, can you make the bot to open an over?

**Comment by viberjet** [comment]
> @yakturkt

Here is your Bot , Please share your results here
[Last Digit 0-1-2.zip](https://github.com/binary-com/binary-bot/files/3827564/Last.Digit.0-1-2.zip)

**Comment by yakturkt** [comment]
> > @yakturkt
> 
> Here is your Bot , Please share your results here
> [Last Digit 0-1-2.zip](https://github.com/binary-com/binary-bot/files/3827564/Last.Digit.0-1-2.zip)


Thank you bro

**Comment by viberjet** [comment]
> > > @yakturkt
> > 
> > 
> > Here is your Bot , Please share your results here
> > [Last Digit 0-1-2.zip](https://github.com/binary-com/binary-bot/files/3827564/Last.Digit.0-1-2.zip)
> 
> Thank you bro

Your Welcome

**Comment by yakturkt** [comment]
> > > > @yakturkt
> > > 
> > > 
> > > Here is your Bot , Please share your results here
> > > [Last Digit 0-1-2.zip](https://github.com/binary-com/binary-bot/files/3827564/Last.Digit.0-1-2.zip)
> > 
> > 
> > Thank you bro
> 
> Your Welcome

I have one more strategy.        strateji:over under Last Digit Can you get the bot to over open a transaction when any of the numbers 0,1,2 comes 3 times?

**Comment by yakturkt** [comment]
> > > > > @yakturkt
> > > > 
> > > > 
> > > > Here is your Bot , Please share your results here
> > > > [Last Digit 0-1-2.zip](https://github.com/binary-com/binary-bot/files/3827564/Last.Digit.0-1-2.zip)
> > > 
> > > 
> > > Thank you bro
> > 
> > 
> > Your Welcome
> 
> I have one more strategy. strateji:over under  you get the bot to over open a transaction when any of the numbers 0,1,2 comes 3 times?

**Comment by viberjet** [comment]
> > > > > > @yakturkt
> > > > > 
> > > > > 
> > > > > Here is your Bot , Please share your results here
> > > > > [Last Digit 0-1-2.zip](https://github.com/binary-com/binary-bot/files/3827564/Last.Digit.0-1-2.zip)
> > > > 
> > > > 
> > > > Thank you bro
> > > 
> > > 
> > > Your Welcome
> > 
> > 
> > I have one more strategy. strateji:over under  you get the bot to over open a transaction when any of the numbers 0,1,2 comes 3 times?

After Now , Please Send your strategy to my email : viberjet@gmail.com

**Comment by alanvito1** [comment]
Here you have more strategyes, just play.

Try it!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!

**Comment by viberjet** [comment]
Thanks Bro
