### ISSUE TITLE
Does Anyone want to help me?..

### ISSUE THREAD

**Issue by ghossan86** [binary-com/binary-bot#2105]
The 
![Screenshot_20191108_163300](https://user-images.githubusercontent.com/47954272/68466295-ae180f00-0246-11ea-9afe-9b7d58f9dbb3.jpg)
strategy like this if the price goes up by 5 points then buy fall if the price drops by 5 points, buy a rise I have been trying for a month but keep failing

**Comment by ceakuk** [comment]
i think the ticks list is like 1000 or 200 ticks in length. you are subtraction  tick number 1000/2000 from tick number 1 for your information. is that what you want?
volatility 100
tick1 =1722.71
tick2 =1722.69
difference is like 0.02. you are waiting for 5 is such a big number. maybe you have to wait forever.

**Comment by ceakuk** [comment]
for a market like volatility 100, you cant get 5. why dont you use data instead of a fixed number. you could use  average true range for example
ATR = Mean(Max(H-L,H-Cp,L-Cp))
[binary-bot(31).zip](https://github.com/binary-com/binary-bot/files/3828002/binary-bot.31.zip)

**Comment by ghossan86** [comment]
Okay thanks for zip.. i'll try..and i'll try your recommendation too
![Screenshot_20191110_101938](https://user-images.githubusercontent.com/47954272/68538283-9bb3e780-03a4-11ea-9abd-8da702b05088.jpg)

**Comment by ghossan86** [comment]
Okay..thank You so much guys for the zip, that works..GBYW

**Comment by alanvito1** [comment]
Try it guys!

Some strategys, just play.

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!

**Comment by ZDEGLET** [comment]
как сделать чтоб они работали. видеть вижу а как запустить?

**Comment by creativi77** [comment]
i believe this is what you are looking for

![image](https://user-images.githubusercontent.com/28829793/68998972-80237200-08b9-11ea-9e8e-2974622e3737.png)

**Comment by ghossan86** [comment]
creativi77 I've try that but isn't work like expected..
