### ISSUE TITLE
Help with setting a bot

### ISSUE THREAD

**Issue by binary-dice** [binary-com/binary-bot#2107]
Hello guys i would like to know if it is possible to make a bot where it waits for 4 ticks going down to play a call, and also if it is possible to make a bot that plays under 5 if we get a number above 5 and followed by a number of which the last digit is 0 (i want it to play on the 0 not the following tick).

**Comment by ceakuk** [comment]
its possible. use while loop with like 2 minites pauses to avoid while loop overloding

**Comment by binary-dice** [comment]
Can you send a picture or the .xml file

**Comment by alanvito1** [comment]
xml files here:

Try it guys!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!
