### ISSUE TITLE
Open candle / Closed candle(s) question

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2108]
I want to know what is the difference between these candle lists. What each one of them actually do? Which one of them gets the value of the current open candle and which one gets the value of the past closed candle(s)?

![candles](https://user-images.githubusercontent.com/11698414/68529381-4b824a00-02fe-11ea-92f4-5155e6fb2321.png)

**Comment by binary-ex-machina** [comment]
1. Just read the text on the block
A. In candles list (this is obvious)
B. read Open # (# means position, open means open value of the candle)
C. from end 1 (means the last item on the list or the most recent)
D. with interval default (default interval is set on the block 1)
End: It will read the open value of the most recent candle with the default interval

2. Just read the text on the block
A. In candle list
B. get # from end  1(# means position)
C. with interval default (default can be set on block 1)
End: In the candle list, it will get the most recent candle with default interval

3. Just read the text on the block
A. Make a list (obvious)
B. of Open values in candle list (open is the open value of the candle, it will make a list of the open values of the candles)
C. with interval default (default is set on block 1)
End: Make a list with the open values of the candles with default interval

**Comment by Kosta92** [comment]
Thank you for your answer. It seems to me that 1 and 2 are somewhat the same when it comes to reading the current (open) candle. I still can't understand what is the difference between "read Open #1 from end" and "get #1 from end". Aren't those values the same?

What I want to achieve is to get this value of the current candle, to check whether it is higher or lower than the last value of the closed candle:
![candle](https://user-images.githubusercontent.com/11698414/68718370-4f85c480-05a9-11ea-8e0e-666bc3595660.png)

**Comment by binary-ex-machina** [comment]
@Kosta92 wrong, 1 gets the Open value, 2 gets the candle OHLC (open, high, close and low values)

get open from end, means you will get the open value

get from end, means you will get the all candle values (open, high, close and low values)

When you say the the current candle, it means you want the OHLC. What you need to get is the actual close value (or last tick) and compare to the Close value of the past closed candle

![image](https://user-images.githubusercontent.com/34610787/68719078-d9259a00-0589-11ea-9570-8af55a754eec.png)

**Comment by Kosta92** [comment]
Thank you so much. I've got it all clear now.
