### ISSUE TITLE
Good Strategy (Is it possible to create bot on it)

### ISSUE THREAD

**Issue by windjenn** [binary-com/binary-bot#2109]
hi guys 
m trading with a manual strategy 5M TF 1 candle expiry. it gives good result but formation take times.
here the strategy 
rsi period 2 overbought - 55, oversold - 45 
call option - when at the end of 5m candle , rsi line finish between level 55 & 45 from the above to below { means the rsi line shld come above the the 55 level and end between 55 & 45 level} 
we place up trade for 5 minute immediately

put option - when at the end of 5m candle , rsi line finish between level 55 & 45 from the below to above { means the rsi line shld come below the the 45 level and end between 55 & 45 level} 
we place down trade for 5 minute immediately

IS IT POSSIBLE TO CREATE A BOT ON IT?

**Comment by ceakuk** [comment]
i can do it for you. how many trades have you done with it and  how many wins/losses.
hopefully not just a handful of trades. that would be luck

**Comment by windjenn** [comment]
> i can do it for you. how many trades have you done with it and how many wins/losses.
> hopefully not just a handful of trades. that would be luck

i got 70 to 80 percent results via manual trading , but there are few more conditions too which i think not possible to add in a bot,

like when trend is going up i just look for call options only and when trend is down i look for only put trades. 
And when i look for call option i look for a good and clean GReen candle and if  after that a doji or small red candle forms , and rsi finished like i said above i take a call trade for next 5 min candle
FOR put option i do the same opposite way means look for a clean good red candle - and if a smaal green or doji candle , i trade for down for next five min candle

**Comment by alanvito1** [comment]
Well, i have some strategyes, try it!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!

**Comment by binary-ex-machina** [comment]
@windjenn you can do like this. It will make the analysis at the last tick of the actual 5min candle. 

![image](https://user-images.githubusercontent.com/34610787/68707209-11b87a00-0570-11ea-9422-13819e5c3531.png)

**Comment by windjenn** [comment]
> @windjenn you can do like this. It will make the analysis at the last tick of the actual 5min candle.
> 
> ![image](https://user-images.githubusercontent.com/34610787/68707209-11b87a00-0570-11ea-9422-13819e5c3531.png)

thanks bro

**Comment by saarsalu** [comment]
> > @windjenn you can do like this. It will make the analysis at the last tick of the actual 5min candle.
> > ![image](https://user-images.githubusercontent.com/34610787/68707209-11b87a00-0570-11ea-9422-13819e5c3531.png)
> 
> thanks bro

hei can you share r bot
