### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Juniorpalmer83** [binary-com/binary-bot#2110]
Hola. Quiero hacer un bot de la siguiente manera. Si la vela cierra alcista, abrir operación hacia la alza por 5 ticks en la opción Rise/Fall. TF 1 min. Y viceversa, si la vela cierra bajista, abrir operación hacia la baja por 5 ticks. Eso que se repita cada vez que abra una vela. Gracias

**Comment by viberjet** [comment]
This is for you :

[Fall and Rise  New Candle.zip](https://github.com/binary-com/binary-bot/files/3827475/Fall.and.Rise.New.Candle.zip)

**Comment by alanvito1** [comment]
Try it guys!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!
