### ISSUE TITLE
HELP WITH COMPOUND INTEREST

### ISSUE THREAD

**Issue by Richard610** [binary-com/binary-bot#2111]
GOOD AFTERNOON FRIENDS. I WANT YOU TO HELP ME. I HAVE THIS BOOT BUT I WOULD LIKE TO PLACE COMPOUND INTEREST AT 5 OR 6 LEVELS BETTER IF YOU COULD PLACE IT AT LEVELS
EXAMPLE
FIRST OPERATION = 1
WIN
NEXT OPERATION = 1.23
AND SO ON. THANK YOU BASTANETE FOR YOUR SUPPORT.

**Comment by Richard610** [comment]
[AYUDA.zip](https://github.com/binary-com/binary-bot/files/3827638/AYUDA.zip)

**Comment by alanvito1** [comment]
Try it guys!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!

**Comment by binary-ex-machina** [comment]
@Richard610 you can do like this. It will compound 30% of the profit you make on every winning trade. On a loss, it will reset to the initial stake. this is a very bad idea of money management, you will never be profitable on long run with this

![image](https://user-images.githubusercontent.com/34610787/68706707-1597cc80-056f-11ea-84fd-b91db83ca5d0.png)
