### ISSUE TITLE
Can Anyone  help me to make a bot he take only even digits (0,2,4,6,8) take trade 

### ISSUE THREAD

**Issue by fawadkhan007** [binary-com/binary-bot#2113]
[EVEN_ODD2,4,6,8binary-bot.zip](https://github.com/binary-com/binary-bot/files/3828126/EVEN_ODD2.4.6.8binary-bot.zip)
Can Anyone  help me to make a bot he take onlyLast  even digits (0,2,4,6,8) take trade. I mean Last digit even and he purchase .
Exemple: 

1 - 1028.44
2 - 1022.96
3 - 1026.30
4 - Purchase Even **

**Comment by binary-ex-machina** [comment]
same #2114
