### ISSUE TITLE
Can Anyone  help me to make a bot he take onlyLast  even digits (0,2,4,6,8) take trade

### ISSUE THREAD

**Issue by fawadkhan007** [binary-com/binary-bot#2114]
Can Anyone  help me to make a bot he take onlyLast  even digits (0,2,4,6,8) take trade. I mean Last digit even and he purchase .
Exemple: 

1 - 1028.44
2 - 1022.96
3 - 1026.30
4 - Purchase Even **
[EVEN_ODD2,4,6,8binary-bot.zip](https://github.com/binary-com/binary-bot/files/3828125/EVEN_ODD2.4.6.8binary-bot.zip)

**Comment by alanvito1** [comment]
Try it guy!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!

**Comment by binary-ex-machina** [comment]
you didn't specified how many evens before it purchases, so i consider after any even digit

![image](https://user-images.githubusercontent.com/34610787/68706128-12501100-056e-11ea-84cb-19953073d0aa.png)
