### ISSUE TITLE
Google drive?!?!?!

### ISSUE THREAD

**Issue by Batekmax** [binary-com/binary-bot#2115]
Where did Google Drive from Binary.bot go ?! more than 2 weeks no longer.

**Comment by aaron-binary** [comment]
> Where did Google Drive from Binary.bot go ?! more than 2 weeks no longer.

Hi @Batekmax, through which domain are you accessing the Binary website? I've double checked and it seems to be down for https://binary.bot, although it does seem to work for https://bot.binary.me and https://bot.binary.com, we'll look into why https://binary.bot isn't cooperating.

Regards,
Aaron

**Comment by Batekmax** [comment]
I use binary.bot, I tried the listed sites, it says that the application has not passed the test yet, so I can’t open it through Google.

**Comment by alanvito1** [comment]
Isn't normal, send an e-mail.

**Comment by aaron-binary** [comment]
> I use binary.bot, I tried the listed sites, it says that the application has not passed the test yet, so I can’t open it through Google.

Sorry to hear that, could you post a screenshot of what you're seeing? This will help us identify what's going on.

Regards,
Aaron
