### ISSUE TITLE
Profits stop loss

### ISSUE THREAD

**Issue by Juniorpalmer83** [binary-com/binary-bot#2116]
Hola. En algunos bots que he probado, tengo la opción de colocar al inicio de correr el bot, el monto de la operación, el profit esperado y las perdidas permitidas. Ahora no sé como colocar eso en otro bot. Alguien sabe cómo se hace? Gracias

**Comment by alanvito1** [comment]
Olá irmão, veja aqui algumas estratégias.

https://github.com/alanvito1/superfree-binary-bot

**Comment by binary-ex-machina** [comment]
@Juniorpalmer83 try to copy the same blocks to the bot you want. Analyze the blocks that do make the analysis on the stake, stop loss and target
