### ISSUE TITLE
Alguém me Ajuda a fazer um bot com essa estratégia ? 

### ISSUE THREAD

**Issue by GoncalvesF253** [binary-com/binary-bot#2117]
Se os 4 último dígitos forem 2,1,3,4 o bot deve alterar a previsão para 2 e comprar difere como no exemplo abaixo:

2536.5**2**
2895.6**1**
2891.9**3**
2595.8**4**

Por favor não questionem a eficiência da estratégia, vou usa-la para um caso em específico ...

**Comment by FlavianoFlavio** [comment]
Fiz dessa forma mas não funcionou 
[Bot binary.zip](https://github.com/binary-com/binary-bot/files/3829522/Bot.binary.zip)

**Comment by alanvito1** [comment]
Tenho algumas estratégias parecidas, veja o que acha.

https://github.com/alanvito1/superfree-binary-bot

**Comment by binary-ex-machina** [comment]
@FlavianoFlavio você pode fazer assim

![image](https://user-images.githubusercontent.com/34610787/68705800-7aeabe00-056d-11ea-9324-d478f500e996.png)
