### ISSUE TITLE
Quero que quando os números 2,1,3,4 saia em sequencia o bot abra ordem difere, esta correto dessa forma ? 

### ISSUE THREAD

**Issue by gustavolima2019** [binary-com/binary-bot#2119]
![image](https://user-images.githubusercontent.com/56326689/68560445-d60e9a80-041f-11ea-868b-f3fc37405c20.png)

**Comment by gustavolima2019** [comment]
Quero que quando os números 2,1,3,4 saia em sequencia o bot abra ordem difere, esta correto dessa forma ?

**Comment by saidforex26** [comment]
[differ 2,1,3,4 ldp 2.zip](https://github.com/binary-com/binary-bot/files/3830066/differ.2.1.3.4.ldp.2.zip)

**Comment by alanvito1** [comment]
Tenho algumas estratégias aqui, se quiser testar e incrementar no seu robot, fica a vontade!

https://github.com/alanvito1/superfree-binary-bot
