### ISSUE TITLE
Confirm profit Split martingale strategy 

### ISSUE THREAD

**Issue by ABDULAHI24HRS** [binary-com/binary-bot#2123]
Who can apply this split martingale to digit differ as in the image below 
![IMG_20191111_080537_538](https://user-images.githubusercontent.com/54444449/68581847-8e1c6180-0479-11ea-9135-7b89a1dadc11.jpg)

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/68705274-85588800-056c-11ea-83b5-f9b04e0210c8.png)
