### ISSUE TITLE
Help me in bot guys!

### ISSUE THREAD

**Issue by zsssss20** [binary-com/binary-bot#2124]
Hello Guys I need help! How can I make a 5 rise 3 fall strategy bot?? And keep repeating it?

**Comment by alanvito1** [comment]
Try it, https://github.com/alanvito1/superfree-binary-bot

**Comment by alanvito1** [comment]
Best Regards and blesses!

**Comment by zsssss20** [comment]
@alanvito1 Thanks bro. But I opened link and haven't got anything! Redirected to binary.com website

**Comment by binary-ex-machina** [comment]
same #2125
