### ISSUE TITLE
How to make 5 rise 3 fall bot? Keep repeating it? 

### ISSUE THREAD

**Issue by zsssss20** [binary-com/binary-bot#2125]
Guys how can I make 5 rise 3 fall bot? And keep repeating it?

**Comment by ceakuk** [comment]
initialize:
count =0

after every trade
count+=1;

if(count%8)<5):
rise

else
put

**Comment by zsssss20** [comment]
@ceakuk can you add a picture for the bot? Please

**Comment by binary-ex-machina** [comment]
@zsssss20 another way to do it, is having a variable as a list, where you can use any pattern you want. Below an image of the pattern you wanted, repeating.

![image](https://user-images.githubusercontent.com/34610787/68703702-e468cd80-0569-11ea-88ee-d3269be53aeb.png)

**Comment by zsssss20** [comment]
@binary-ex-machina Thanks bro! I need your help. How can I make a bot that works like that: W means Won, L means Lost and numbers beside them means the stake
If my trades were 
W1,W2,L4,L1,L1,W1,W1
As you can see I used martingale for the winning trades not lost. So I want to make a bot that change the W1 that inside [] : W1,W2,L4,L1,L1,W1,[W1] to First Loss amount ×2 which will equal 8
I will try to make it easier 
W1,W2,L4,L1,L1,W1,(W1×L4×2=8)---- or any other number instead of 4 (L4) and keep continuing until win. Then reset 
Hope you understood me

**Comment by ceakuk** [comment]
it looks promising. i used x1.5 martingale. good luck
![Unbenannt1](https://user-images.githubusercontent.com/43122491/68709830-be0d5700-0596-11ea-9761-d988327b822e.PNG)
[binary-bot(34).zip](https://github.com/binary-com/binary-bot/files/3838180/binary-bot.34.zip)

**Comment by ceakuk** [comment]
looks promising even with fewer wins. but only when wins follow wins and  losses follow losses
 ![Unbenannt](https://user-images.githubusercontent.com/43122491/68709911-e2693380-0596-11ea-8835-6c031ceaa4ba.PNG)

**Comment by ceakuk** [comment]
in the print out you will see the largest trade ever takrn (amount-largest)
highest profit gained (profit: max-gained)
and  largest draw down in your account ( profit : max-loss)

**Comment by zsssss20** [comment]
@ceakuk thanks bro! Have you used the strategy I said about?

**Comment by ceakuk** [comment]
in the notify print-out you will see the largest trade ever taken (amount-largest)
highest profit gained (profit: max-gained)
and  largest draw down in your account (profit : max-lost)

**Comment by ceakuk** [comment]
@zsssss20 
i used it with martingale x1.25 but that sometimes  ended in problems  by losing  just  one step to recovering loss. martingale x2 to me is too high in case you encounter those bad moments. try and optimize the best martingale and maybe post your results here for us to cross check. good luck

**Comment by ceakuk** [comment]
this could just be luck so let it run for 24 hours
![Unbenannt](https://user-images.githubusercontent.com/43122491/68716333-421a0b80-05a4-11ea-82e8-f8c217856127.PNG)

**Comment by ceakuk** [comment]
@zsssss20 
DATA analysis using python  jupyter notebook.
even though results here look nice, when i take the data from different strategies and run against martingale while winnning or martingale while loosing, here is my conclusion
martingale while loosing must be x1.5 and above while martingale while loosing can be as low as x1.15.
also on profit, you get more with martingale while increasing but the risk is also  higher (better low risk)

it also fails in   some cases while other strategies sta lean on amount hence this method is not my choice

**Comment by zsssss20** [comment]
@ceakuk sure bro I will, but I have small problem with the bot you added. 
i want to multiply the first loss amount after winnings, the bot keeps multiplying until it recover all short term losses, how can I do it? for only the first lost trade amount x2

**Comment by zsssss20** [comment]
@ceakuk @binary-ex-machina BRO's can you check the last isuue i added and help me with it?
