### ISSUE TITLE
3 ticks were fall then purchase rise or if 3 ticks were rise then purchase fall

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#2126]
@navneetsinh thanks bro!! You're amazing! Sorry I asked a lot but do you have an idea how to create a bot that starts after 3 same ticks? Like this: if 3 ticks were fall then purchase rise or if 3 ticks were rise then purchase fall 
I mean only trade after 3 ticks are the same ?

_Originally posted by @zsssss20 in https://github.com/binary-com/binary-bot/issues/2089#issuecomment-552878484_

**Comment by navneetsinh** [comment]
@zsssss20,

![Screenshot (2)](https://user-images.githubusercontent.com/42480287/68673639-39acdb00-057a-11ea-8e68-38ada434eeb2.png)

**Comment by kadinwhite** [comment]
@navneetsinh I was able to build this portion of the bot. But when i run it its not taking any trades. Please Help I have the normal define trade set at 1 tick and 1 usd what else am i missing i have trade again in #4 also
