### ISSUE TITLE
REVERSA

### ISSUE THREAD

**Issue by pao11901** [binary-com/binary-bot#2127]
Hello friend, the strategy  it named REVERSAL, in manual it works very well, but you have to wait a lot... so in a robot it would be profitable, the strategy for the robot  is the following, I analyze the last digit of volatility 100, I analyze the last 5 nummbers ticks, and the following must be fulfilled.

1. The worm's head must be green.
![image](https://user-images.githubusercontent.com/46610874/68675834-af875700-0526-11ea-8f75-c42fbbf5b206.png)

2. The first 2 digits of analysis must be, even / odd or odd / even.
3. The last digit (the fifth tick) has to be a zero.
4. there must be numbers of both colors, red and blue
5. There should not be a 9 of any color in the 5 ticks that are analyzed.
6. The bet will be DOWN if the last digit, zero, is blue.
7. The bet will be UP if the last digit, the zero is red.
Example :

5 6 6 2 0= DOWN  The first 2 digits of analysis must be, even / odd or odd / even.

5 8 2 2 0 =DOWN  The last digit (the fifth tick) has to be a zero.
5 1 6 8 0 = UP  There should not be a 9 of any color in the 5 ticks that are analyzed.

4 1 4 2 0 = UP The bet will be UP if the last digit, the zero is red.

![image](https://user-images.githubusercontent.com/46610874/68675807-a0a0a480-0526-11ea-984f-98a64b6b8ea5.png)

thank you very much!!!

**Comment by binary-ex-machina** [comment]
You said it works very well, like in how much trades ? if is less then 1000 trades, you can't say "it works very well", because your data for analysis is too low. Also there is 0 correlation of the last digit show the direction.

I'm 100% sure that in 1000 trades, the win rate will not be higher then 55%. If you play again more 1000 trades, it will be close to 50% win rate (with 7-10 losses in row, like any other rise/fall strategy will get over time)

**Comment by ceakuk** [comment]
@pao11901 
use  for loop for the period you are interested in like this
period =10;
ticksList=ticks list given[10: 1 from end]
lowerlow = ticksList[1]
higherhigh = ticksList[1]

for(int i =1<length(ticksList); i++)
{
 if(ticksList[i]>higherhigh)
 higherhigh = ticksList[i]
 if(ticksList[i]<lowerlow)
lowerlow = ticksList[i]
}
now you have the highest(higher high) and the lowest(lowerlow

if the 1st 3 ticks are among the lowest and the current last tick is between high and low ( you can even give say between 40-60% then your condition is met
