### ISSUE TITLE
Stop email notification

### ISSUE THREAD

**Issue by Tebu1429** [binary-com/binary-bot#2129]
Hi
How do you stop email notification from github

**Comment by aaron-binary** [comment]
Hey @Tebu1429,

This page may help: https://help.github.com/en/github/receiving-notifications-about-activity-on-github/choosing-the-delivery-method-for-your-notifications

Regards,
Aaron

**Comment by Tebu1429** [comment]
Cannot find any setting on my profile. That leads me to notification. No option of even edit my profile ,

**Comment by navneetsinh** [comment]
> Cannot find any setting on my profile. That leads me to notification. No option of even edit my profile ,

@Tebu1429 
https://github.com/settings/notifications
