### ISSUE TITLE
Martingale Is not working on my wait after loss

### ISSUE THREAD

**Issue by Agentsbu** [binary-com/binary-bot#213]
Hi guys please help me with martingale on my Digit Differ Bot, it was working until I tried to set Number of loss. heres the picture below. 
![bot](https://cloud.githubusercontent.com/assets/26632197/25865702/089ce3e2-34f4-11e7-874a-1dedf18fff24.png)

**Comment by Fruitfella** [comment]
@Agentsbu walah bro, salah tuh nempatin block nya
![num of loss](https://cloud.githubusercontent.com/assets/26277327/25867959/7716bbf0-3525-11e7-9a12-4f3f710543f1.png)

**Comment by Agentsbu** [comment]
FANTASTIC BRO, SO EASY. LOL I TOOK DAYS TRYING TO FIGURE OUT.

**Comment by luckman1988** [comment]
![bb](https://user-images.githubusercontent.com/34752686/61102221-45be4a00-a46d-11e9-8d80-592cd91944ac.PNG)
