### ISSUE TITLE
taking trades on candle closing basis

### ISSUE THREAD

**Issue by josward1** [binary-com/binary-bot#2130]
Hi, 

I'm having trouble getting the correct block arrangement for my bot to take trades only when the previous candle has closed. i have tried the following block arrangement however this does not work.

Thanks
![Screen Shot 2019-11-12 at 21 50 54](https://user-images.githubusercontent.com/37579005/68713920-cc5b7300-0596-11ea-80ca-370c9d0e0624.png)

**Comment by navneetsinh** [comment]
@josward1 use this blocks
![Screenshot (2)](https://user-images.githubusercontent.com/42480287/68743175-de312a80-0617-11ea-8897-e62d57ac98ef.png)

**Comment by josward1** [comment]
Thank you for your response

I have tried this block arrangement in the "watch and purchase your contract" block and the bot doesn't seem to be executing correctly. where is the correct place to have the block set up? say if i was using a simple break of a moving average strategy.

thanks

**Comment by josward1** [comment]
![image](https://user-images.githubusercontent.com/37579005/68812022-e74ae780-0669-11ea-9c5b-3f48e1fe520c.png)

i am looking for the bot to take a trade when the 3 period bollinger band crosses the 13 but waits until the candle has closed out before it takes the trade. If the moving averages uncross before the candle has closed the bot does not take the trade. This is my set up if you could help me out i would very much appreciate it. 

Thanks

**Comment by navneetsinh** [comment]
@josward1 
![Screenshot (3)](https://user-images.githubusercontent.com/42480287/68837854-82cc6e80-06e3-11ea-8aca-7290d742d095.png)

**Comment by josward1** [comment]
Again, thank you so much for your reply. I have applied the block arrangement as i can see it however on the candle close the bot does not trade and i receive the signal "undefined is not a function"

**Comment by navneetsinh** [comment]
Share here what you created

**Comment by josward1** [comment]
I have developed my strategy so that the bot takes a confirmation from the RSI indicator. When the 3 SMA crosses  down the 13 SMA I want a confirmation of the RSI crossing down through the 80 level. And when the 3 SMA crosses up through the 13 a confirmation of the RSI crossing up through the 20 all on candle closing basis. Thank you for your help and I look forward to hearing back from you.
Thanks
