### ISSUE TITLE
Alguém consegue colocar barreira nesse bot ? Eu fiz dessa forma da foto mas não funcionou...

### ISSUE THREAD

**Issue by GoncalvesF253** [binary-com/binary-bot#2131]
![como colocar barreira](https://user-images.githubusercontent.com/56320282/68720575-7682cd00-058e-11ea-812d-d6597563a5df.jpg)

**Comment by navneetsinh** [comment]
@FlavianoFlavio 
you have to change some setups for getting barrier offset value
![Screenshot (2)](https://user-images.githubusercontent.com/42480287/68738688-f51e4f80-060c-11ea-8e57-1c84dae7e592.png)

**Comment by FlavianoFlavio** [comment]
[Bot Barreira.zip](https://github.com/binary-com/binary-bot/files/3841199/Bot.Barreira.zip)
Fiz da forma que você falou mas não funcionou, veja o bot em anexo....
