### ISSUE TITLE
Why people can keep selling/spamming things here?

### ISSUE THREAD

**Issue by binary-ex-machina** [binary-com/binary-bot#2132]
It's not the first time and probably will not be the last, but why admins just let these guys come here and sell things? People posting links to other stores, promo codes, sharing links from users playing with demo accounts and changing the name to real accounts, offering services, to mention a few... At least deleting the issues/comments or blocking these fake accounts would help future users of the bot.binary.com

More and more people create github profiles every day to come here and spam links of fake things,  selling products, fake videos... soon this will became a marketplace and not a repository to solve issues and help others

this is the lastest clown in town #2106

**Comment by Eshhh** [comment]
The admins probably want the people to get scammed and lose money to binary.com

**Comment by anton-binary** [comment]
Hi @binary-ex-machina, 
Thanks for pointing this out. We typically close such issues, this one was indeed missed by us.
Anton

**Comment by binary-ex-machina** [comment]
@anton-binary thank you for the answer Anton. In case i see other suspicious posts, I'll mark you or Aaron
