### ISSUE TITLE
Can we have any variable in binary bot to get the expired time contract?

### ISSUE THREAD

**Issue by tnhminh** [binary-com/binary-bot#2133]
Hi all,

As my title,

I want to get this variable for further investigation

Thanks

**Comment by ceakuk** [comment]
explain but i think if i get you right then yes. but try to explain first

**Comment by anton-binary** [comment]
Hi @tnhminh,
You could use `Contract detail` block. It returns only GMT time string, e.g. 01:10:30. So, you might want to do something like this. You can also convert the result to timestamp.
![image](https://user-images.githubusercontent.com/43776314/68910022-46544d80-078b-11ea-8f7e-246cc990a484.png)
