### ISSUE TITLE
[strategy] Ai seus BR, vamos criar alguma coisa eficiente juntos, pq ta fod@!

### ISSUE THREAD

**Issue by alanvito1** [binary-com/binary-bot#2136]
Não sei se pode criar em portugues, tem lugar que tem frescura que só pode iniciar os post em inglês, mas enfim bora lá

Estou há algum tempo já rodando nesse mundo dos robts e até agora só vi nego vendendo robô, fiz algumas tentativas fracassadas de operações 24hrs, pois este é o objetivo e só obtive aprendizados das funcções da plataforma, ganhar dinheiro que é bom... nada, não sei se sou burro ou ingenuo, se alguem quiser citar ...uma palavra kkk... em acreditar que isso possa dar certo, mas é assim quer surgem grandes ideias, assim como a Google, só perguntar pra ela como ela foi criada (google assistant).

É basicamente isso galera, um recrutamento ai pra criar um robo open souce, se pá podemos até desenvolver algo com estruturas blockchain, as linhas vão até onde você as consegue/sabe digitar.

Os robos que eu estudei estão nos meus repositórios do github, fiquem a vontade para utilizar os robos ali, **pelamordedeus** conhece o robo antes e faça muitos testes em **conta virtual**, pra depois não vir chorando que quebrou a banca... kkk

Eu sou uma pessoa que conversa rindo, isso me deixa puto as vezes ajsiajsasaajksija

FLW!

Forte abraço!

🗡

**Comment by FlavianoFlavio** [comment]
E ai Jovem, pela minha experiência com bots binary, não é possível rodar nenhum um bot 24 horas por melhor que ele seja, o negócio é bater meta de 1% a no máximo 2% e sair fora do mercado, e jamais operar por mais de 40 minutos. Se tentar a sorte na binary o azar é certo.

**Comment by ZDEGLET** [comment]
@alanvito1
Как воспользоваться работой ваших ботов при переходе по ссылке. Напишите последовательно что я должен сделать.

**Comment by binary-ex-machina** [comment]
@alanvito1 aqui no github tem muita gente que ajuda, não só vende. Já encontrei diversas pessoas ajudando em grupos de whatsapp e teelgram, então discordo com você na parte de que só tem gente vendendo bot. Vi que você fez um spam em varios posts aqui sobre o seu repositório, os bots e tudo mais. Não acho valido ficar respondendo qualquer issue com isso, por que você não ajuda a resolver o problema que o post se trata, só faz spam e na minha opinião perde credibilidade.

Se juntar para criar algo eficiente é um belo sonho, mas o que você traz para a união? qual conhecimento você tem que vai fazer a diferença? O repositório aqui é sobre os bots em .xml para a binary.com, você falou em blockchain, talvez fosse melhor ir em um forum de desenvolvedores para o blockchain e ver la.

Se o seu objetivo é criar estratégias que possam rodar 24 horas e serem lucrativas, você esta com o objetivo quase impossível de ser alcançado (não conheço nenhuma estrategia que seja lucrativa assim)
