### ISSUE TITLE
How can I split a martingale into 4 portions?

### ISSUE THREAD

**Issue by pgfbr** [binary-com/binary-bot#2138]
Can anyone help me, I would like to know how to split the martingale into 4 installments ... Since the first installment is only after a win after the loss example:

First Order: Win
Second Order: Loss
Third Order: Win (not martingale)
Fourth Order: Martingale to Recover Second Order

**Comment by binary-ex-machina** [comment]
you didn't specified with multiple losses occur, so I assumed that it will be reset to the initial stake. the same applies to the win, I assumed that after the martingale is applied after the win, and it wins, it will return to the initial stake as well

![image](https://user-images.githubusercontent.com/34610787/69401748-a6d81300-0cd4-11ea-9ccd-f288c3dfbfd3.png)

**Comment by GoncalvesF253** [comment]
@binary-ex-machina Muito Obrigado pela ajuda, como eu poderia parcelar o martingale em 4 vezes ? Exemplo: O bot fez uma entrada de 5usd e perdeu, eu gostaria que ele fizesse  O martingale parcelado em 3 entradas, isso é possível ?
