### ISSUE TITLE
helpppp in bot

### ISSUE THREAD

**Issue by zsssss20** [binary-com/binary-bot#2141]
Hello guys I need help 
I want to set my trade duration to 15 seconds
if 15 seconds were lower than entry spot for 2 times then purchase rise
and if 15 seconds were higher than entry spot for 2 times then purchase fall

**Comment by navneetsinh** [comment]
Duplicate of #2089

**Comment by zsssss20** [comment]
@navneetsinh bro i want to make martingale like this
if i get 2 losses in a row then multiply stake by 2 
tried a lot but couldn't find a way

**Comment by navneetsinh** [comment]
@zsssss20 ,

check this

![Screenshot (3)](https://user-images.githubusercontent.com/42480287/69180553-7f961000-0b33-11ea-83e1-8d337720ac18.png)
