### ISSUE TITLE
hi can you make the strategy in the video bot

### ISSUE THREAD

**Issue by yakturkt** [binary-com/binary-bot#2142]
https://youtu.be/QsM4I7L2od0                      
Hello
when the seconds of digital clock are between 30 and 36 !!!

ıt must be appear blue colorHello
when the seconds of binary clock are between 30 and 36 !!!

ıt must be appear blue color

**Comment by eonuoha30** [comment]
Theres no logical backup in this conditions that can make it qualify to be called a STRATEGY.

If it wins, count it as pure LUCK.

but on the long run, it'd yield a success/failure ratio synonymous to a bot that has ZERO STRATEGY or ANALYSIS attached to it.

**Comment by navneetsinh** [comment]
@yakturkt 
here is required block setup, you can check it ,

![Screenshot (3)](https://user-images.githubusercontent.com/42480287/69173998-f8429f80-0b26-11ea-835b-d1d6808816b0.png)

**Comment by yakturkt** [comment]
Can you turn this strategy into a boat? in xml

**Comment by yakturkt** [comment]
> Can you turn this strategy into a bot? in xml

**Comment by navneetsinh** [comment]
@yakturkt ,
all required blocks are available in left panel,

**Comment by yakturkt** [comment]
I do not know how to create a bot

**Comment by GoncalvesF253** [comment]
[Bot 30.36seg.zip](https://github.com/binary-com/binary-bot/files/3870967/Bot.30.36seg.zip)

**Comment by yakturkt** [comment]
> [Bot 30.36seg.zip](https://github.com/binary-com/binary-bot/files/3870967/Bot.30.36seg.zip)

Thank you bro

**Comment by GoncalvesF253** [comment]
Fiz graças a ajuda de @navneetsinh
