### ISSUE TITLE
Previsão não funciona

### ISSUE THREAD

**Issue by jaksondc** [binary-com/binary-bot#2143]
Desenvolvi um bot para comprar dígito diferente a cada vez que um número der uma quantidade de repetições seguidas, mas o bot está comprando algumas vezes sem a repetição e não está respeitando o número da previsão. Compra sem o número repetir e quando repete compra com outro número.
[xml e cvs.zip](https://github.com/binary-com/binary-bot/files/3870781/xml.e.cvs.zip)

Alguém pode me ajudar?

**Comment by binary-ex-machina** [comment]
Pelo que entendi da estratégia, ele começa com o prediction 7, espera aparecer duas vezes o digito igual ao prediction, então o bot compra executa a ordem de compra do contato. Depois que é definido o prediction no bloco 1, mesmo mudando ele em outros blocos, terá validade apenas no próximo contrato comprado.

Para que a sua logica funcionasse para qualquer digito, servindo de prediction para a trade e sendo executada, a logica precisa ser feita antes de definir as opções do contrato. Sempre leve em consideração que existe um delay de 1 tick entre o bot definir a trade e ela ser executada. Se você quiser que o bot faça a compra logo em seguida que os digitos repetidos aparecem, você precisará usar o prediction fixo

Vc pode fazer desta forma abaixo para prediction dinamico (conforme aparecerem os digitos repetidos, o bot define um novo prediction) 

![image](https://user-images.githubusercontent.com/34610787/69401105-e998eb80-0cd2-11ea-9f87-a22f6c80f4d7.png)

**Comment by jaksondc** [comment]
> Pelo que entendi da estratégia, ele começa com o prediction 7, espera aparecer duas vezes o digito igual ao prediction, então o bot compra executa a ordem de compra do contato. Depois que é definido o prediction no bloco 1, mesmo mudando ele em outros blocos, terá validade apenas no próximo contrato comprado.
> 
> Para que a sua logica funcionasse para qualquer digito, servindo de prediction para a trade e sendo executada, a logica precisa ser feita antes de definir as opções do contrato. Sempre leve em consideração que existe um delay de 1 tick entre o bot definir a trade e ela ser executada. Se você quiser que o bot faça a compra logo em seguida que os digitos repetidos aparecem, você precisará usar o prediction fixo
> 
> Vc pode fazer desta forma abaixo para prediction dinamico (conforme aparecerem os digitos repetidos, o bot define um novo prediction)
> 
> ![image](https://user-images.githubusercontent.com/34610787/69401105-e998eb80-0cd2-11ea-9f87-a22f6c80f4d7.png)

Quero agradecer imensamente @binary-ex-machina pela atenção e ajuda. Obrigado.

**Comment by GoncalvesF253** [comment]
eu vi um bot no Brasil que faz esta função veja no link : https://www.youtube.com/watch?v=cB6dF3MoWXE&t=330s

**Comment by jaksondc** [comment]
> eu vi um bot no Brasil que faz esta função veja no link : https://www.youtube.com/watch?v=cB6dF3MoWXE&t=330s

Na verdade não é igual. O meu pode monitorar todos os números de 0 a 9 ou pode monitorar um único número quando coloco "Monitorar todos" para "false" e não faz soros. O problema é que da forma como o binary-ex-machina colocou, não está fazendo a compra do contrato e não estou conseguindo corrigir.

**Comment by binary-ex-machina** [comment]
@jaksondc aqui está rodando normal

![image](https://user-images.githubusercontent.com/34610787/69505715-03704380-0f0a-11ea-9dff-0aa63eb59668.png)

**Comment by jaksondc** [comment]
Obrigado a todos que ajudaram. Eu havia cometido um erro na verificação entre o último dígito e o dígito anterior. Com a ajuda de vocês, está funcionando perfeitamente e muito lucrativo. Recebam minha gratidão

**Comment by alex199686** [comment]
olá podem compartilhar o robô que foi corrigido  @jaksondc

**Comment by alex199686** [comment]
podem compartilhar o  robô  @jaksondc @binary-ex-machina

**Comment by hieber17** [comment]
podem compartilhar o robô @jaksondc @binary-ex-machina ???

**Comment by oespiao** [comment]
Ola, estava desenvolvendo o mesmo robo, mas encontrei um problema com o ultimo digito 0, em "Last Digit List" ele nao pega o 0...

**Comment by adilsonalpino** [comment]
Por favor, poderiam me enviar o bot em questão?

**Comment by adilsonalpino** [comment]
Gastei muito deste debate.

**Comment by adilsonalpino** [comment]
Por gentileza,  poderiam colocar este bot aqui para download, ou enviar para o e-mail adilsonalpino@gmail.com

**Comment by adilsonalpino** [comment]
> @jaksondcaqui esta rodando normal
> 
> ![imagem](https://user-images.githubusercontent.com/34610787/69505715-03704380-0f0a-11ea-9dff-0aa63eb59668.png)

Não consegui montar este script.
Poderia enviar este arquivo .xml para meu e-mail?
Grato
adilsonalpino@gmail.com
