### ISSUE TITLE
DBot beta is now available

### ISSUE THREAD

**Issue by anton-binary** [binary-com/binary-bot#2146]
We’re pleased to announce the beta release of **DBot** –– a revamped version of **Binary Bot** for our new Deriv trading service. You can check it out now at [https:/deriv.app/bot](https://deriv.app/bot?utm_source=github&utm_medium=social&utm_campaign=ww-d-deriv-dbot-ghannouncement1119-en) (just log in with your existing Binary.com account).

![image](https://user-images.githubusercontent.com/43776314/69316457-d7d42b80-0c73-11ea-83e5-d6de52671330.png)

**What you can expect with DBot**
With DBot, we’ve reimagined our popular bot creation tool from the ground up. Here are some of the new features you can expect:
* **Quick strategy setup**
Create your Martingale, D’Alembert, or Oscar’s Grind strategies easily without having to drag blocks around.
* **Integrated help content**
View tutorials, guides, and other useful references right in your workspace as you’re building your strategy.
* **Search for blocks**
Easily find the blocks you need by typing in the name of the block and selecting it from the search results.

We plan to add more new features to DBot in the coming weeks, so stay tuned for updates!

**What will happen to Binary Bot?**
We plan to keep supporting Binary Bot going forward. Everything in Binary Bot will stay the same, working like it always has.

If you want to give DBot a try, it even supports strategies built with Binary Bot so you don’t have to recreate your existing strategies. All you need to do is upload your XML files to DBot.

If you’ve tried DBot and you want to tell us what you think, please leave your feedback here in this thread. We’d love to hear from you!

**Comment by GoncalvesF253** [comment]
Se tiver no idioma português do brasil seria ótimo !

**Comment by binary-ex-machina** [comment]
The interface is very nice, cleaner and with some very useful tools. The quick strategy is a very nice approach for the money management. My suggestions would be on the blocks design. The actual bot builder is very subtle on the connections between the blocks, the beta version is too large in my opinion

![image](https://user-images.githubusercontent.com/34610787/69399772-26161880-0cce-11ea-8ad7-e940fd24f415.png)

![image](https://user-images.githubusercontent.com/34610787/69399787-2e6e5380-0cce-11ea-9c03-3c4adea5fae5.png)

The idea of multi colours is nice, it will help to distinguish between the blocks types, but making the base block (1, 2, 3 and 4 base blocks) almost the same color as the background i don't think it's good. for bright monitors this could cause some problems. Maybe some border or these blocks being very dark and the other coloured blocks being semi tone, would represent the hierarchy the bot have (block 2 darker color, contains an IF blue block, less coloured and more bright, that contains some variable even brighter and so on). From darker (highest hierarchy) to brighter (lowest  hierarchy)

Maybe something like this

![image](https://user-images.githubusercontent.com/34610787/69400200-9d987780-0ccf-11ea-94ff-8079823549a7.png)

the idea of the help content is good, but i think for experienced bot creators, would be nice to be able to hide that. It will make the interface cleaner and the menu smaller with the information we need to see, the block name.

A dark theme version would be very nice too. 

Overall the platform feels very fast and not consuming too much RAM memory with heavy bots. I have other ideas for the possible changes and new blocks that can be added, but I will wait for more updates. 

Very nice update and project!

**Comment by anton-binary** [comment]
Hi @binary-ex-machina ,

Many thanks for your feedback.

> the idea of the help content is good, but i think for experienced bot creators, would be nice to be able to hide that.

Did you try "Search"? The idea was that experienced users would like to type block name/description to search for the block they need.

**Comment by anton-binary** [comment]
hi @GoncalvesF253 , translations will follow soon, including Portuguese.

**Comment by ceakuk** [comment]
@anton-binary 
the best customer of a product is the designer. can you please show us how the tool has helped you make successful trades

**Comment by ZDEGLET** [comment]
Если его привяжите к МТ4 это будет круто!!!

**Comment by anton-binary** [comment]
Добрый день @ZDEGLET 
Спасибо за обратную связь.
К сожалению, мы этого не можем сделать, поскольку протокол взаимодействия MT4/5 клиента и сервера закрытый, и пытаться его использовать это прямое нарушение соглашения Binary.com с MetaQuotes.

Антон

**Comment by darito21** [comment]
Hey, DBot is cool but since it´s not ready for real money if you code/edit a bot with DBot mostly of the timeswheni you load it into Binary app it keeps saying "XML File Contains Unsupported Elements..."
I tried everything, ignoring all content and deleting all main blocks... saving as collection... it just doesnt work.
Any suggestion? I dont want to recode the whole bot again with the old version.
Thanks

**Comment by anton-binary** [comment]
Hi @darito21 ,

Indeed, XML created in DBot are not supported in Binary Bot. However, you can easily run Binary Bot XMLs in DBot. 

BTW, **Real accounts trading is enabled now.** 

Thanks,
Anton

**Comment by ZDEGLET** [comment]
русского языка не нашел:(
а так с виду вроде не плохо. начал тестировать посмотрим:)

**Comment by ZDEGLET** [comment]
ПРОСТОЙ РОБОТ А МАРТИН НЕ РАБОТАЕТ
![2019-12-14_00-33-05](https://user-images.githubusercontent.com/36106343/70833693-7d109880-1e09-11ea-9992-2466e7d5360b.png)

**Comment by ZDEGLET** [comment]
РАЗОБРАЛСЯ ВСЕ ОКЕЙ. ПЛОХО ЧТО НЕТ РУССКОГО:)

**Comment by ZDEGLET** [comment]
МАРТИНГЕЙЛ НЕ ЗНАЮ КАК СДЕЛАТЬ:(

**Comment by anton-binary** [comment]
@ZDEGLET Русский язык (и другие) будет скоро.
Что именно не получается?

Если нажмете "Quick strategy", то появится диалог, где можно задать параметры для мартина. Если потом нажать "Create", то блоки появятся на рабочем пространстве.

**Comment by ZDEGLET** [comment]
спасибо!!!

**Comment by muroyal** [comment]
@anton-binary 

I am not getting error in binary bot but while executing same bot in Bet getting error continuously.

By the way the new beta version is good for trace the bot.. But the images size should be bit smaller.. 

Kindly have a look into it.. it seems this error will affect bot performance.. 

![image](https://user-images.githubusercontent.com/32416314/71775646-35190780-2faa-11ea-919f-19194bc88b2d.png)

**Comment by alanvito1** [comment]
ótima ferramenta, se precisarem de robôs tenho alguns aqui!

Visite minha página para download de novos bots gratuitos.
Visit my librarie for new free bots.

https://github.com/alanvito1/superfree-binary-bot

**Comment by hotmatrixx** [comment]
@anton-binary 
Hey, friend.
Sorry I can't find much info on DBOT - maybe I've missed a thread somewhere?

Can you confirm; is this the "new" version of Binary bot?
Does this mean Support is ending for Binary Bot? 

Should I move over to D-Bot? does it include all fucntionality of BB?

What are the advantages you me in DB?
What are your advantages as a Dev/ company rep in DB

Disadvantages?

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

This will indeed be the new version of Binary Bot. We're still supporting Binary Bot until we deem DBot to be stable, after which we'll slowly phase out Binary Bot in favour of DBot. We're working on making DBot fully backward compatible with Binary Bot strategies and the functionality should be similar.

Regards,
Aaron

**Comment by brunsan** [comment]
Can someone share with me a link to a bot interpreter? Basically I want to build an app that parses XML and calls the binary API. Like Deriv.app and Binary.com does.

Sorry to ask here...

**Comment by hotmatrixx** [comment]
> 
> 
> Can someone share with me a link to a bot interpreter? Basically I want to build an app that parses XML and calls the binary API. Like Deriv.app and Binary.com does.
> 
> Sorry to ask here...

No worries! Yeah you could have started a new thread for it I guess, but.. meh.
If you navigate to the binary.com's home on github, there is a branch called deriv.api
I haven't gotten as far as calling the API's myself, but this might possibly help you?

https://github.com/binary-com/deriv-api

**Comment by hotmatrixx** [comment]
@anton-binary 
@aaron-binary 

So I came across a mild issue today...
I decided to try out deriv. I found bugs.  There is nowhere to post issues for Deriv, except in the API project.

**Comment by harshalkharose** [comment]
Hello Harshal kharose here,
Please solve this
In MACD Indicator How to set fast moving average line cross slow moving average line then buy and wait for the same for next same move.
Please help thank you & regards

**Comment by bangvanthuat** [comment]
my opinion.  The new version is very confusing, complicated layout.  The floor should maintain the same look as the old version.  Look more intuitive and overall when testing the bot.
I think the floor should add more indicators to optimize the bot setup.  The current number of indicators is too small.

**Comment by anton-binary** [comment]
Hi @bangvanthuat, thanks for your feedback, really appreciate it.
May I ask you for a bit more details? What exactly is confusing? Blocks menu, blocks colors and/or size, or the way summary table now looks like? What do you mean by "the floor"?

Thanks,
Anton

**Comment by bangvanthuat** [comment]
Hello
"Sàn" in his words is binary.com
As for the complicated setup of the library layout, it makes me feel
difficult to use and search for the necessary blocks so that if I don't
know the block name and its function.
The second problem is the length of the logical block k for line breaks.
Once a long logical block arises it will be difficult to observe it in the
most detailed manner.
The next problem was that the color of the block was so flashy that it made
users like me uncomfortable.
The next is that the bot part is difficult to visually observe the bot
running and the notification displays.
in my personal opinion.  Perhaps you should keep the same settings and
layout as the old version and add more indicators.
Thanks!

Vào 08:07 T.6, 10 Th4 2020 anton-binary <notifications@github.com> đã viết:

**Comment by thommmaz** [comment]
DBot does not show total profit/loss ? I need manually calculate it?

**Comment by Rampage1000** [comment]
Good Anton I’m having a problem there is a strategy that turns it into bot, works well in Binary but not in Dbot. You would do me the favor of making that the file is compatible without modifying the strategy nor the established values... I am very new I would appreciate it

**Comment by Rampage1000** [comment]
You have a telegram or something in case you decide to help me? In order to send you the file...

**Comment by anton-binary** [comment]
Hi @Rampage1000 , please send your strategy to binarybot@binary.com we'll look it.
Thanks.

**Comment by trident2005** [comment]
Please add the option to use "inline inputs" and "external imputs" as we have in bianry.bot,

and allow editing within the blocks of "CUSTON FUNTIONS", you cannot manage the fields created to use the function, since if I delete them directly from the variable list, the entire function is deleted and it must be created again from the beginning

**Comment by buckman1974** [comment]
I am gradually switching to the Dbot with some of my bots, but they don't seem to run?

Run Fine on Binary.com Bot and all set up correctly, but on Dbot they load fine and play/run but when the criteria is met (digits or RSI etc) the Dbot does nothing

**Comment by mkaranja** [comment]
Is there detailed documentation on how to create DBot?

**Comment by aaron-binary** [comment]
> @trident2005: Please add the option to use "inline inputs" and "external imputs" as we have in bianry.bot,
Thanks for your feedback, we'll look into whether this is something we could do.

> @trident2005: and allow editing within the blocks of "CUSTON FUNTIONS", you cannot manage the fields created to use the function, since if I delete them directly from the variable list, the entire function is deleted and it must be created again from the beginning

I'm interested to learn how you'd like to see the function block to behave. Do you mean the arguments should be editable? I'd love to hear your thoughts.

> @buckman1974: I am gradually switching to the Dbot with some of my bots, but they don't seem to run?

Could you share some of these strategies with us? You can email them to binarybot@binary.com, we'll look into them and add some modifications to our conversion logic. There may have been some edge cases that we missed.

> Is there detailed documentation on how to create DBot?

We currently don't have a detailed overview on how to create bots on DBot, however the idea is the same as in the old Binary Bot. You could find some tutorials online on how to build a Binary Bot, or check out the DBot help centre here: https://deriv.com/help-centre/dbot#what-is-dbot

**Comment by trident2005** [comment]
@aaron-binary 

I really did not expect an ironic response to my suggestion, maybe I did not know how to explain correctly, or somehow I offended the programmers.

I hope I can explain myself better in the following image, and I apologize if it is something that is present and I do not know how to do it.

And something else that I wanted to add, the distribution of the blocks is extremely uncomfortable to work since EVERYTHING takes up more space on the screen with respect to what it looks like in binary.bot

![dbot](https://user-images.githubusercontent.com/56892552/84723713-3a648000-af54-11ea-8a1b-02bd4a0a22fd.png)

**Comment by aaron-binary** [comment]
Hey @trident2005,

> I really did not expect an ironic response to my suggestion, maybe I did not know how to explain correctly, or somehow I offended the programmers.

My response wasn't meant ironic, sorry if I made it sound that way. 👌  

To provide some more details, we're aware that we don't have inline and external inputs in DBot, the technical reason for this is that we're using Scratch Blocks under the hood, and they got rid of this. Because of this we converted a lot of multiline blocks to multiple blocks (e.g. the trade definition block). Perhaps we'll move back to 100% Blockly in the future, as their support for different renderers will provide us with the same features we require for DBot.

Gotcha on the function arguments. I think it's a good idea and will discuss this internally. 👍

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: mkaranja <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 16:11
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] DBot beta is now available (#2146)


Is there detailed documentation on how to create DBot?

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: buckman1974 <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 11:03
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] DBot beta is now available (#2146)


I am gradually switching to the Dbot with some of my bots, but they don't seem to run?

Run Fine on Binary.com Bot and all set up correctly, but on Dbot they load fine and play/run but when the criteria is met (digits or RSI etc) the Dbot does nothing

**Comment by shfx0096** [comment]
Trading view binary chart is not available now for rebranding issue.When it'll be available for deriv?

**Comment by vipclubsi** [comment]
Hello Friends! How are you?
I would like to know how I can insert a robot (xml) externally, through Developer Tools?
Is there a ready-made function that I can use just to replace the current code blocks with another one, easily?
Thanks!!
