### ISSUE TITLE
Random75 Digit 10% Win

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2147]
Hi.

Can sombody make bot with this strategy?

Step 1: Select Random 75
Step 2: Select 5 tick duration
Step 3: Last Digit Prediction is 0
Step 4: Stake amount: $10 to $1000
Step 5: Watch spot tick last digit is always on 9
Step 6: On 9 last digit click Differs

money calculation could be.

each new deal that the robot opens is the amount of the previous win

so when i do 10 usd transaction i get back to 10.99

the next transaction will open at 10.99usd
and so on

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh
@waltergrant

**Comment by navneetsinh** [comment]
@saarsalu ,
![Opera Snapshot_2019-11-21_171325_bot binary com](https://user-images.githubusercontent.com/42480287/69335163-4e782580-0c82-11ea-8aae-b7341105d68b.png)

**Comment by saarsalu** [comment]
> @saarsalu ,
> ![Opera Snapshot_2019-11-21_171325_bot binary com](https://user-images.githubusercontent.com/42480287/69335163-4e782580-0c82-11ea-8aae-b7341105d68b.png)

hei.

i didnt mean random stake.
money calculation could be.

each new deal that the robot opens is the amount of the previous win

so when i do 10 usd transaction i get back to 10.99

the next transaction will open at 10.99usd
and so on.


and the bot wount trade

**Comment by binary-ex-machina** [comment]
@saarsalu you can do like this

![image](https://user-images.githubusercontent.com/34610787/69399359-a2a7f780-0ccc-11ea-9bd4-c5b934a9905f.png)

**Comment by saarsalu** [comment]
> @saarsalu you can do like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/69399359-a2a7f780-0ccc-11ea-9bd4-c5b934a9905f.png)

hei, tanx but the bot will not trade any trade.

like he dont see digits

**Comment by binary-ex-machina** [comment]
I tried here and it's placing trades normally. It will take some time. At least 1 per minute it will make

![image](https://user-images.githubusercontent.com/34610787/69401298-78a60380-0cd3-11ea-87cd-09f3384f56f0.png)

**Comment by saarsalu** [comment]
> I tried here and it's placing trades normally. It will take some time. At least 1 per minute it will make
> 
> ![image](https://user-images.githubusercontent.com/34610787/69401298-78a60380-0cd3-11ea-87cd-09f3384f56f0.png)

![Kuvatõmmis (30)](https://user-images.githubusercontent.com/30391002/69402185-be78c100-0cff-11ea-814d-724c3463799c.png)


intresting

**Comment by binary-ex-machina** [comment]
@saarsalu why you created a variable called Last Digit? There is a built-in block for that. That's why it's not working for you

![image](https://user-images.githubusercontent.com/34610787/69402922-01bf3980-0cd8-11ea-8fb6-022e0276754e.png)

**Comment by saarsalu** [comment]
> @saarsalu why you created a variable called Last Digit? There is a built-in block for that. That's why it's not working for you
> 
> ![image](https://user-images.githubusercontent.com/34610787/69402922-01bf3980-0cd8-11ea-8fb6-022e0276754e.png)

heheh.

my mistake tanx

**Comment by saarsalu** [comment]
> @saarsalu you can do like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/69399359-a2a7f780-0ccc-11ea-9bd4-c5b934a9905f.png)

how can I make a robot open only 4 transactions for example (10. 10.99. 12.08. 13.27) when they are done the robot will start again from 10. 10.99. 12.08. 13.27

if one of the bets loses he opens the next deal to martingale and if he wins he goes back to the beginning

**Comment by saarsalu** [comment]
sofare good.

50 runs winners 0 loosers
![Kuvatõmmis (31)](https://user-images.githubusercontent.com/30391002/69405924-8fffe380-0d09-11ea-8e88-8bf3ed8b5fda.png)

**Comment by ceakuk** [comment]
@saarsalu 
don't celebrate yet. random numbers are  very good at  deceiving people. in theory, you can even win 1000 consecutively. doesnt  mean the method will work.
statistically you must loose 10% of the trades. you can't ague with math.

@binary-ex-machina 
i see you  always increase stake when you win and go back to initial stack when you loose. you need to have a max when you win to go back to initial amount. or else a loss will always come that brings wipes away all your wins. 100% guaranteed

**Comment by saarsalu** [comment]
> @saarsalu
> don't celebrate yet. random numbers are very good at deceiving people. in theory, you can even win 1000 consecutively. doesnt mean the method will work.
> statistically you must loose 10% of the trades. you can't ague with math.
> 
> @binary-ex-machina
> i see you always increase stake when you win and go back to initial stack when you loose. you need to have a max when you win to go back to initial amount. or else a loss will always come that brings wipes away all your wins. 100% guaranteed

how can I make a robot open only 4 transactions for example (10. 10.99. 12.08. 13.27) when they are done the robot will start again from 10. 10.99. 12.08. 13.27

if one of the bets loses he opens the next deal to martingale and if he wins he goes back to the beginning.

or maby bot will take profit and starts ower again

**Comment by binary-ex-machina** [comment]
@ceakuk i don't use this feature for my trades. Put profit on the next trade will sure end on loss. Specially with digits. The best way to recover on binary options is martingale. The other money managements will never work on long run

**Comment by navneetsinh** [comment]
@saarsalu 
You can check this step martingale setup
And you can set it as per requirements 

![Studio_20191122_232857](https://user-images.githubusercontent.com/42480287/69452181-17d80300-0d87-11ea-947f-e30ee44b83a7.jpg)

**Comment by ceakuk** [comment]
@binary-ex-machina 
i meant the solution you suggested should have a maximum at which you stop increasing like  say when you target profit is  reached

**Comment by binary-ex-machina** [comment]
@ceakuk yes, it can be used with all risk/money managements the user wants.

**Comment by saarsalu** [comment]
> @saarsalu
> You can check this step martingale setup
> And you can set it as per requirements
> 
> ![Studio_20191122_232857](https://user-images.githubusercontent.com/42480287/69452181-17d80300-0d87-11ea-947f-e30ee44b83a7.jpg)

hei.

i cet error  (Amount must be a positive number)
![Kuvatõmmis (36)](https://user-images.githubusercontent.com/30391002/69458371-d12edc80-0d77-11ea-9ac9-ecf82ebcef2e.png)

**Comment by saarsalu** [comment]
[step bot 0.35,0.40,0.81,1.67,3.32,6.60.zip](https://github.com/binary-com/binary-bot/files/3881312/step.bot.0.35.0.40.0.81.1.67.3.32.6.60.zip)

**Comment by saarsalu** [comment]
I dont see wath the bot will open a martingale after losing trade.

how i can ade this.

Maby we can ade take profit.

The bot will take profit and starts ower:)

![Kuvatõmmis (37)](https://user-images.githubusercontent.com/30391002/69461659-bd877400-0d7f-11ea-8775-3d683c13d82b.png)

**Comment by saarsalu** [comment]
> @saarsalu
> You can check this step martingale setup
> And you can set it as per requirements
> 
> ![Studio_20191122_232857](https://user-images.githubusercontent.com/42480287/69452181-17d80300-0d87-11ea-947f-e30ee44b83a7.jpg)

tanx working like sharm.

can we ade hor this time like if the bot traded here 4 trades
10.00,10.99,12.08,13.27

after thes trades the bot will wait 30 min before he starts ower with thes trades

**Comment by saarsalu** [comment]
Hei.

R sombody hawe a good plan how code this?
