### ISSUE TITLE
Given candle is not valid. Triple indicators RSI + Stoch + CCI

### ISSUE THREAD

**Issue by TrinhKhuong1997DHKienTruc** [binary-com/binary-bot#2149]
Hi @binary-ex-machina, hi guys.
I used binary-ex-machina's CCI and Stochastic indicator functions. But when I run both I get the message that "Given candle is not valid. Please help me fix. Hope you understand :)
![Untitled](https://user-images.githubusercontent.com/50324383/69379177-844cf680-0ce2-11ea-9c87-ed1098030a31.png)

[RSI + Stoch + CCI.txt](https://github.com/binary-com/binary-bot/files/3876933/RSI.%2B.Stoch.%2B.CCI.txt)

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-11-22_042441_github com](https://user-images.githubusercontent.com/42480287/69383682-549cef00-0ce0-11ea-9abd-a211cbeb3502.png)

**Comment by binary-ex-machina** [comment]
@navneetsinh needs to be candles, not ticks

**Comment by navneetsinh** [comment]
yes, @binary-ex-machina, I just highlighted him with arrows on his given image, for use candle list instead of tick list,
it's my mistake that I didn't explained.
But thanks to you for noticing to me.

**Comment by TrinhKhuong1997DHKienTruc** [comment]
Hi guys. Please help me convert these lines of code from Binary.com to MT5 software.

[Differ Analyze 160 TEST CHỈ %.txt](https://github.com/binary-com/binary-bot/files/3896213/Differ.Analyze.160.TEST.CH.txt)
[RSI + Stoch + CCI TEST COMEBACK.txt](https://github.com/binary-com/binary-bot/files/3896214/RSI.%2B.Stoch.%2B.CCI.TEST.COMEBACK.txt)
