### ISSUE TITLE
Bot Feature

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#2150]
Please, how can I make a bot stop after a particular time?

For instance, if I input '30' ,

It means that I want the bot to automatically stop  after trading for 30minutes.

Thanks for your quick response

**Comment by gayya** [comment]
you can do it like this
<img width="960" alt="2019-11-22 (2)" src="https://user-images.githubusercontent.com/57481410/69436059-ad16cf80-0d66-11ea-88c5-b0020c4b7a25.png">

**Comment by eonuoha30** [comment]
Thanks man
