### ISSUE TITLE
Purchase each 15 seconds 00.15 and 00.30 and 00.45.... etc

### ISSUE THREAD

**Issue by zsssss20** [binary-com/binary-bot#2152]
Hello 
I want to set exact time for bot to start. At 00.00.00
00.00.15
00.00.30
00.00.45 
To make purchase at each 15 seconds
Hope you understood me

**Comment by navneetsinh** [comment]
@zsssss20 

Here is you can't trade on exact 15 seconds interval, it takes 1 or 2 seconds differences 
You can check this blocks

![Screenshot_2019-11-23-00-05-30~2](https://user-images.githubusercontent.com/42480287/69451535-a055a400-0d85-11ea-9fb9-87564de0390b.png)

**Comment by zsssss20** [comment]
Thanks bro. I know it takes 2 seconds but will these blocks make purchase each new 15 seconds? I mean at 00.15 and .30, .45 ...etc?

**Comment by navneetsinh** [comment]
@zsssss20 

It can't take trade at exact 0.15, 0.30, 0.45 for every time
If you set for that exact intervals 
Some trades will skip

_Sent from my Galaxy TabS 10.5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zsssss20** [comment]
Yes bro. What I mean to say is: there is any way to make the bot purchase the order once the time is .15 or .30..etc? Like once the time is 00.00.15 purchase 1 tick, once time is 00.00.30 purchase 1 tick and keep doing it? Even if the server took 2 or 3 seconds to start the bot .
