### ISSUE TITLE
Smart martingale please help me

### ISSUE THREAD

**Issue by T3LL3Z** [binary-com/binary-bot#2153]
Can anyone send me the block of smart martingale like this 0.35, 0.40, 0.81, 1.67, 3.32, 6.60 .. etc

**Comment by navneetsinh** [comment]
> Can anyone send me the block of smart martingale like this 0.35, 0.40, 0.81, 1.67, 3.32, 6.60 .. etc

@T3LL3Z 
Check this one
![Studio_20191122_232857](https://user-images.githubusercontent.com/42480287/69449376-d47a9600-0d80-11ea-866b-08f9d7e96813.jpg)

**Comment by T3LL3Z** [comment]
I wrote to your email friend, I only create the blocks as well as your image?  And I adapt it to my bot?

**Comment by zsssss20** [comment]
@navneetsinh can you check my issue too bro

**Comment by navneetsinh** [comment]
@zsssss20 I shared something for you in your created issue.

_Sent from my Galaxy TabS 10.5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by navneetsinh** [comment]
@T3LL3Z 
I didn't get any email 
You can set this given blocks in your bot as per your requirements. 
Also check to use that martingale? 
For win martingale or loss martingale?!!!!!!

_Sent from my Galaxy TabS 10.5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by T3LL3Z** [comment]
> @T3LL3Z
> I didn't get any email
> You can set this given blocks in your bot as per your requirements.
> Also check to use that martingale?
> For win martingale or loss martingale?!!!!!!

bro thanks for answering, but I can't find those parameters of "Run once at the beginning" and Define commercial option "I'm a new apology, maybe you have the blocks to download them bro please?

**Comment by T3LL3Z** [comment]
> @T3LL3Z
> I didn't get any email
> You can set this given blocks in your bot as per your requirements.
> Also check to use that martingale?
> For win martingale or loss martingale?!!!!!!

what I want is to have that kind of smart martingale so that we can double the losses of each entry

**Comment by navneetsinh** [comment]
> bro thanks for answering, check in spam, my email is [solverteck@gmail.com](mailto:solverteck@gmail.com)

Dear everyone has that block
![Screenshot_2019-11-23-00-45-31~2](https://user-images.githubusercontent.com/42480287/69453954-0f81c700-0d8b-11ea-9612-4a2eead58437.png)

**Comment by T3LL3Z** [comment]
yes bro i found it thanks

**Comment by navneetsinh** [comment]
> > @T3LL3Z
> > I didn't get any email
> > You can set this given blocks in your bot as per your requirements.
> > Also check to use that martingale?
> > For win martingale or loss martingale?!!!!!!
> 
> what I want is to have that kind of smart martingale so that we can double the losses of each entry

![Screenshot_2019-11-23-00-53-39](https://user-images.githubusercontent.com/42480287/69454290-d8f87c00-0d8b-11ea-9146-1aa98b2d9eb5.png)

**Comment by T3LL3Z** [comment]
sorry I meant "not to double the losses per ticket"

**Comment by navneetsinh** [comment]
Explain

**Comment by T3LL3Z** [comment]
In the first image that you sent me, I just did it, the problem is that when I win it does not return to the initial amount but it follows the martingale list that I made, as I do so that once I win the martingale I return to the initial amount

**Comment by navneetsinh** [comment]
@T3LL3Z 
![Screenshot_2019-11-23-01-14-40](https://user-images.githubusercontent.com/42480287/69455634-d51a2900-0d8e-11ea-816e-cb992424dcce.png)

**Comment by T3LL3Z** [comment]
![asd](https://user-images.githubusercontent.com/58082543/69456151-f996e680-0d37-11ea-9bf6-264ab60cb8ac.png)
Is this block of the image that I show you the same "or" block that you send me in your image? because I don't know where to find that block of your image .. I found the one that sent you in my image that is similar but I don't know if it is the same

**Comment by T3LL3Z** [comment]
![asdada](https://user-images.githubusercontent.com/58082543/69456545-e6384b00-0d38-11ea-9961-d85932989a47.png)
look bro I have it that way and it doesn't work, keep going with the martingale list numbers even when you win the martingale
![mg](https://user-images.githubusercontent.com/58082543/69456673-38796c00-0d39-11ea-9bd8-4a21c34b2af0.png)

**Comment by navneetsinh** [comment]
It's the same

**Comment by T3LL3Z** [comment]
what can i do then bro? :( because he continues with the martingale list even after winning

**Comment by zsssss20** [comment]
Try this bro

**Comment by zsssss20** [comment]
@T3LL3Z 
Put ( if ) block from the Logic and add (Result is win) block for the first input. You can find it in the Binary-After Purchase 
Second input add: create variable (Stake) you can create it from: Advanced- List. and add : ( Set Stake to) then add number 1 and get the number block from the Math section
I wish I could upload a picture to let you see but I'm trying and it's not happening . I will try again 
![20191122_232501](https://user-images.githubusercontent.com/56763178/69458390-3f779d00-0d80-11ea-8b92-fb537aae67c7.jpg)

**Comment by T3LL3Z** [comment]
Thanks bro :)

**Comment by ZDEGLET** [comment]
ПРИШЛИ МНЕ НА ПОЧТУ СВОЕГО РОБОТА Я ПРИКРЕПЛЮ МАРТИНА И ОТПРАВЛЮ ГОТОВЫЙ РОБОТ.
zdeglet@gmail.com
