### ISSUE TITLE
need smart martingle on this realy good bot

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#2155]
just change martingle to 0.35,0.39,0.81..........

test bot 50 hours and rich 7 step martingle ($22) 
[good RSI bot.txt](https://github.com/binary-com/binary-bot/files/3882299/good.RSI.bot.txt)

THANKS!!!!

@hotmatrixx
@aaron-binary
@binary-ex-mechina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

**Comment by muroyal** [comment]
@poroinika 

I have added martingle and added some stuff in your BOT.. Please share me your email .. I will send you the BOT..
