### ISSUE TITLE
XML/Bot Security

### ISSUE THREAD

**Issue by Gasha0** [binary-com/binary-bot#2157]
Is it possible to put an XML password when it is loaded in binary? Or some way that only one person can use that bot

**Comment by navneetsinh** [comment]
You can add password for any bot. And it can use for starting of bot.
But it's not possible for lock one user for use.
Anybody who knows bot editing can remove installed password from bot.
Adding password in bot it's just westing time.

**Comment by ZDEGLET** [comment]
Такой вопрос уже был но его никто не решил;(

**Comment by Gasha0** [comment]
@navneetsinh So, its possible to hide the blocks then?

**Comment by navneetsinh** [comment]
@Gasha0 No, you can't hide blocks, you just can collapse blocks or set good/complex arrangements, but if anyone has enough knowledge of blocking,  they can easily cracke your blocks 

_Sent from my Galaxy TabS 10.5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gayya** [comment]
You can add some variables with other local language will make it more difficult.but again it can change if anyone familiar with bots

**Comment by navneetsinh** [comment]
Yes, it can,
It's open for who knows bot coding

**Comment by aaron-binary** [comment]
Hi @Gasha0,

I missed this issue. Someone asked a similar question recently and this was my response.

> Hey @ceakuk,
>
> Let's keep it civil please. 😄 
>
>This is an interesting question. Technically I don't believe it's possible to create closed-source strategies, the only thing we could do from our side is preventing the user from exporting the strategy or implement some kind of authentication system for strategies. A thing to note is that all of our frontend apps are open-source, a technical user could easily reverse engineer our logic.
>
>An alternative solution would be to create your own application which implements the logic of your strategy on the server-side using our API. You would ask for a user's API token which would allow your app to make trades on their behalf, as well as charging a markup between 0-5%. You may read more here:
>
>- https://developers.binary.com/ 
>- https://developers.binary.com/applications/
>
>The best place to get support for third-party apps is on our forums: 
>- https://binary.vanillacommunity.com/
>
>Hope that helps,
>Aaron

**Comment by Gasha0** [comment]
@aaron-binary Thanks aaron

**Comment by navneetsinh** [comment]
Thanks @aaron-binary, I don't know about that.
