### ISSUE TITLE
Alguem Por favor..

### ISSUE THREAD

**Issue by wallpersonal** [binary-com/binary-bot#2158]
Sei que aki eh cheio de Brazuca, inclusive o grande ExMachida... por favor, alguem me de uma soluçao.. kero um bot com barreira call e put(ambas direçoes). Consegui faze-lo mas chamando ou call ou put, MAS QUERIA Q O BOT ANALISASSE SOZINHO E CHAMASSE CALL OU PUT DEPENDENDO DA ANALISE, mas nao consigo, como disse precisop chamar antecipadamente call ou putt eu mesmo com uma variavel....

Alguem sabe como proceder? Obrigado galera!
![Área de Transferência02](https://user-images.githubusercontent.com/47636304/69487781-9e9be700-0e3e-11ea-9f6a-ac135aa99003.jpg)

**Comment by GoncalvesF253** [comment]
![image](https://user-images.githubusercontent.com/56320282/69505045-63fd8180-0f06-11ea-95ef-02f04ad256e4.png)
Não sei se você vai conseguir entender, mas fiz esse bloco com uma estratégia bem simples só para exemplificar, onde se o ultimo dígito for Igual ou menor que 4 comprar PUT, e Se for Igual ou menor que 5 Comprar CALL (Desconsidere a estratégia foi só um exemplo). Da forma que esta ai o bot vai fazer a primeira entrada de acordo com o sinal da estratégia, creio que era essa sua dúvida...

**Comment by GoncalvesF253** [comment]
Ah esqueci de outra coisa você tem que colocar tudo dentro de um loop "Repetir enquanto -> verdadeiro'

**Comment by GoncalvesF253** [comment]
E ai Jovem você vai fazer dessa forma que esta na foto, vou tentar explicar. No Bot Acima Coloquei uma estratégia bem simples só para exemplificar, a estratégia é: Se o ultimo dígito for menor ou igual a 2 Comprar PUT, e o ultimo dígito for Maior ou igual a 3 comprar CALL, (Desconsidere a estratégia foi só para exemplificar), então você substituindo minha estratégia pela sua creio que dará certo... Boa Sorte !

**Comment by wallpersonal** [comment]
> E ai Jovem você vai fazer dessa forma que esta na foto, vou tentar explicar. No Bot Acima Coloquei uma estratégia bem simples só para exemplificar, a estratégia é: Se o ultimo dígito for 0 ,1 ou 2 Comprar PUT, e Se o ultimo dígito for 7, 8 ou 9 comprar CALL, (Desconsidere a estratégia foi só para exemplificar), então você substituindo minha estratégia pela sua creio que dará certo... Boa Sorte !
> ![image](https://user-images.githubusercontent.com/56320282/69509168-c494ba80-0f16-11ea-956c-9f59256f4553.png)

**Comment by wallpersonal** [comment]
> > E ai Jovem você vai fazer dessa forma que esta na foto, vou tentar explicar. No Bot Acima Coloquei uma estratégia bem simples só para exemplificar, a estratégia é: Se o ultimo dígito for 0 ,1 ou 2 Comprar PUT, e Se o ultimo dígito for 7, 8 ou 9 comprar CALL, (Desconsidere a estratégia foi só para exemplificar), então você substituindo minha estratégia pela sua creio que dará certo... Boa Sorte !
> > ![image](https://user-images.githubusercontent.com/56320282/69509168-c494ba80-0f16-11ea-956c-9f59256f4553.png)

Vou tentar aki e retorno meu amigo. Desde ja, mto obrigado!
