### ISSUE TITLE
Bandas de Bollinger com valores errados, podem me ajudar?

### ISSUE THREAD

**Issue by jaksondc** [binary-com/binary-bot#2162]
Estou desenvolvendo um bot onde quero vender se o preço tocar ou superar a banda superior e comprar se o preço tocar ou superar a banda inferior. A estratégia ainda contará com uma SMA de 100, mas essa está com os valores corretos, apenas a Banda de bollinger está trazendo os valores errados. Vejam na imagem que ela retorna o valor correto da banda superior (1330.68), mas retorna o valor errado da banda inferior (1328.99) quando no gráfico mostra próximo de (1330.00).
Alguém pode me auxiliar a pegar os valores corretos? Obrigado
![Bandas Bollinger](https://user-images.githubusercontent.com/19330069/69586108-4bea3880-0fc0-11ea-9375-270a8e48b109.jpg)

**Comment by anton-binary** [comment]
Hi @jaksondc,
Try using smartcharts.
![image](https://user-images.githubusercontent.com/43776314/69591668-5b07cf80-102e-11ea-8e6b-0f1b35372c2e.png)
Or https://charts.binary.com/

**Comment by jaksondc** [comment]
> Hi @jaksondc,
> Try using smartcharts.
> ![image](https://user-images.githubusercontent.com/43776314/69591668-5b07cf80-102e-11ea-8e6b-0f1b35372c2e.png)
> Or https://charts.binary.com/

Solicito ajuda e me vem um atormentado com uma solução de porco...

**Comment by jaksondc** [comment]
Ninguém consegue???

**Comment by binary-ex-machina** [comment]
@jaksondc o cálculo feito no gráfico do smart charts é diferente do que é feito no bot.binary. Não tem como você pegar aquele valor sem recriar o indicador

**Comment by jaksondc** [comment]
> @jaksondc o cálculo feito no gráfico do smart charts é diferente do que é feito no bot.binary. Não tem como você pegar aquele valor sem recriar o indicador

E como eu recrio o indicador? Pode me ajudar por gentileza?

**Comment by binary-ex-machina** [comment]
@jaksondc da uma olhada na formula https://traderhq.com/ultimate-guide-to-bollinger-bands/

**Comment by jaksondc** [comment]
> @jaksondc da uma olhada na formula https://traderhq.com/ultimate-guide-to-bollinger-bands/

Valeu, obrigado, vou estudar
