### ISSUE TITLE
How to change txt to xml and upload it to binary bot

### ISSUE THREAD

**Issue by zsssss20** [binary-com/binary-bot#2164]
Hey guys how to change txt  file to xml so I can upload it to binarybot? 
Plus how can I set my trades to start at the beginning of each minute? I mean like that
Start: 22.00.00
Second 22.01.00 ...etc?

**Comment by ceakuk** [comment]
instal text editors like sublime (current version is 3 i guess) or notepad plus.
i use sublime. open the txt and save it as blablabla.xml

**Comment by zsssss20** [comment]
@ceakuk thanks bro and how can I make the trade duration? Tried a lot but couldn't find a way
I want the trase to start at each new 1 minute and another one for each 30 seconds?

**Comment by ceakuk** [comment]
actually i have just tried using normal text editors like notepad or wordpad. just open your file but save as blablabla.xml by typing ".xml" instead of  ".txt"

**Comment by ceakuk** [comment]
what do you want as your trade duration?
fixed number of variable that you can change?

**Comment by zsssss20** [comment]
@ceakuk  I want a fixed number like 30 seconds. Once the time has a 30 seconds like 23.00.30 or 21.00.00 or 21.00.30 
I want it to open order immediately for 30 or 25 seconds
I mean to open 2 orders per minute
And if I want, easy to change it to 15 seconds or 20
Can you do it bro?

**Comment by zsssss20** [comment]
@ceakuk bro
I want the trade bot to open new trade each 15 seconds for 6 ticks bear market
Which equals 12 seconds but I want bot to start 
Like that : 00.00.15
00.00.30
.... and complete like that

**Comment by daredude26** [comment]
> what do you want as your trade duration?
> fixed number of variable that you can change?
@ceakuk,i need a help to modify my bot ,could you please  provide your email

**Comment by binary-ex-machina** [comment]
@daredude26 it's impossible to open a trade on an odd number. You can try to open every 16 seconds (8 ticks) but the best is to trade every 20 seconds

just change to the number you need
![image](https://user-images.githubusercontent.com/34610787/70766241-e9bd6180-1d3b-11ea-9eaf-9b6ea3d3c3b4.png)

**Comment by amanroxx** [comment]
how can i enter raw code in my binary bot?

**Comment by amanroxx** [comment]
and how can i set 3 indicators in my bot at once?
