### ISSUE TITLE
Periods longer than data length!!!

### ISSUE THREAD

**Issue by wallpersonal** [binary-com/binary-bot#2165]
"Periods longer than data length". Alguem sabe pq esta merda ocorre!?

Does anyone know why this shit occurs !?

I lost money because of this!

**Comment by anton-binary** [comment]
Hi @wallpersonal,

I had to edit the title of your message to remove swearing. Please note that we don't encourage such language here. 

Please specify the issue, post blocks that didn't work. 
In case if you want to dispute trades, please kindly raise a ticket on binary.com.

Thanks,
Anton.

**Comment by ceakuk** [comment]
do you have a dynamically changing period?
what about data? which data is that? ticks list etc?
