### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by ngeorg-veritas** [binary-com/binary-bot#2166]
Hey guys, anybody knows how to make an "executable python file" to trade via websocket?

i want to implement in a django website for making personal management via third site.

but i want to know how to make websocket working.

idk how to do it.

**Comment by anton-binary** [comment]
Hi @ngeorg-veritas,

There's a API forum https://binary.vanillacommunity.com/. You could ask there.
Also, there's https://developers.binary.com/demos/ where you can find examples in Python.

Regards,
Anton

**Comment by nextnaro** [comment]
@ngeorg-veritas me too need that, starting to study python.
