### ISSUE TITLE
[ need help ] how to make bot trade after x even or odds.

### ISSUE THREAD

**Issue by ngeorg-veritas** [binary-com/binary-bot#2167]
Hey guys,

my strategy is based on the bot playing even or odd after x consecutive even or odd sequence.

how to make it work in the platform?

i'm having no success (all the codes i tried, no success)

**Comment by GoncalvesF253** [comment]
Qual a estratégia ?

**Comment by binary-ex-machina** [comment]
@ngeorg-veritas you can do like this. It will wait for digits even/odd, count them and will place following what appear 3 times

![image](https://user-images.githubusercontent.com/34610787/70766484-9bf52900-1d3c-11ea-8cfd-2af83ea7bc8f.png)
