### ISSUE TITLE
Money Management required

### ISSUE THREAD

**Issue by Gasha0** [binary-com/binary-bot#2168]
Hello, I need a money management that evaluates accumulated losses and multiplies in function of winning waiting for the next ITM, so it does not open such high lots in case of finding a strong wave of OTM

**Comment by Gasha0** [comment]
I mean MG is like you calculate your earnings and losses and more losses that are having consecutive and that makes you Martingale

**Comment by Gasha0** [comment]
Sorry for my english!

**Comment by ZDEGLET** [comment]
кидай бота на почту приделаю
zdeglet@gmail.com

**Comment by Gasha0** [comment]
@ZDEGLET Как вы собираетесь прикрепить его? Вы хотите, чтобы я отправил вам сообщение на это письмо?

**Comment by ZDEGLET** [comment]
у тебя сам бот есть к чему прикреплять? или у тебя только стратегия?

**Comment by Gasha0** [comment]
@ZDEGLET Нет, я ищу, извините, но я думаю, что вы поняли

**Comment by ZDEGLET** [comment]
ты разбираешься в блоках как смонтировать робота? Что ты ищешь прибыльную стратегию или робота? я не понял что ты хочешь.

**Comment by Gasha0** [comment]
Я ищу некоторые блоки, которые делают управление капиталом в мартингейле для моей стратегии

**Comment by ZDEGLET** [comment]
понятно. закидывай на почту самого простого робота. я прикреплю блоки к нему. а там перетаскивай их на свою стратегию.

**Comment by Gasha0** [comment]
Ok
