### ISSUE TITLE
Help me to make an money management

### ISSUE THREAD

**Issue by Gasha0** [binary-com/binary-bot#2169]
I dont know how to build this, i need help pls
![77356363_576908589781157_2110364174100987904_n](https://user-images.githubusercontent.com/56451198/69690931-1d498c00-10ac-11ea-9154-aa2c5b8b0b87.png)

**Comment by Gasha0** [comment]
It is a money management that evaluates accumulated losses and multiplies in function of winning waiting for the nearby WINS, so it does not open such high lots in case of finding a strong wave of LOSES

**Comment by binary-ex-machina** [comment]
there is a lack of information about a lot of things in this money management. Waiting for nearby wins is very subjective and doesn't depend only on money management. You will need minimum trades win.loss to start applying the factor, as well when it will stop applying the factor.

Also there is other problems that we can't figure out just by looking for the image you sent
• safeLevel ???
• Profit???

other then this you can achieve the idea i presented (based on the image you sent, lacking more of the logic behind the analysis)

![image](https://user-images.githubusercontent.com/34610787/70766962-44f05380-1d3e-11ea-9d5c-02872e1b008a.png)

At the end, is not better then martingale and it will just add complexity to the bot
