### ISSUE TITLE
Please help me convert Bot from Binary.com to MT5 software.

### ISSUE THREAD

**Issue by TrinhKhuong1997DHKienTruc** [binary-com/binary-bot#2170]
Hi guys. Please help me convert these lines of code from Binary.com to MT5 software.

[RSI + Stoch + CCI TEST COMEBACK.txt](https://github.com/binary-com/binary-bot/files/3896174/RSI.%2B.Stoch.%2B.CCI.TEST.COMEBACK.txt)
[Differ Analyze 160 TEST CHỈ %.txt](https://github.com/binary-com/binary-bot/files/3896175/Differ.Analyze.160.TEST.CH.txt)

**Comment by ZDEGLET** [comment]
У меня есть программа бесплатная для MT4. Для ручной торговли все работает отлично. Не могу программу поставить на автоматическую торговлю. Инструкция в программе есть. Помогите как сделать автоматическую торговлю. Программу прилагаю.
[BotBinaryV10.3_upd_11.07.2019.zip](https://github.com/binary-com/binary-bot/files/3900339/BotBinaryV10.3_upd_11.07.2019.zip)

Моя почта zdeglet@gmail.com.

**Comment by anton-binary** [comment]
Hi @TrinhKhuong1997DHKienTruc , @ZDEGLET ,
I have to close this thread as it's not related to Binary Bot/DBot. 

Anton.
