### ISSUE TITLE
trade on previous candle close and current price. 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2171]
Hello Team,

I need one help on CCI and SMA combination trade. the Bot is given very good results i would like to twice little more.

The trade is happening on previous candle open close but the trade will go on next candle. because the bot is using EPOCH 57

I would like your help to modify the bot withe while placing order need to compare withe current price and previous candle close.

If the current price is more than previous candle close then withe condition it should go for CALL.
2)If the previous candle close is less than current price then got for put withe CCI and SMA condition.

In attached BOT there is no 15 seconds and 30 seconds candle is it possible to add in to , please help me.

Kindly check that the CCI coding is well set in the bot ?

Capture

**Comment by muroyal** [comment]
@ @raunakkathuria @ashkanx @jy-binary @Mahboobeh-binary

**Comment by willyzkibe** [comment]
hellow send the bot here wilymu@gmail.com

**Comment by muroyal** [comment]
Bot has sent to you @willyzkibe  Please add ATR indicator in my successfully BOT for high probability results. 

![image](https://user-images.githubusercontent.com/32416314/70305818-3dd8bb00-17fd-11ea-808b-742029596dba.png)

**Comment by willyzkibe** [comment]
hellow sir thanks for your email kindly send me your contacts detail for
easy communication or telegram

**Comment by muroyal** [comment]
https://t.me/royal089 telegram  me


Thanks

WhatsApp 919964402456

**Comment by muroyal** [comment]
Are you developer.. ?

If you are trader the bot which shared  need to give some instructions..

**Comment by willyzkibe** [comment]
hellow am not a trader  am practising coding unfortunately ave not been
able to check your bot since i something was off with binary website bot
section i may be able to check it and add the parameters you said but her
is what  i require detailed instructions on how you wand the bot to  be
coded

**Comment by muroyal** [comment]
Hello willyzkibe,

As per attached BOT Need below modification


1)   The order is placing on the candle 2nd candle end and  trade start
from 4th candle.  the price comparison is doing last 2nd candle open
closed. I would need to change withe current price and previous candle
close.

I need to get the current price value in a variable and compare with
previous candle close.

If the Previous candle close is lower then* current price* then the order
(CALL) will be place withe CCI and SMA condition.

If the Previous candle close is higher then *current price t*hen the order
(PUT) will be place withe CCI and SMA condition.


[image: image.png]

*2) I need ATR (14) OR ADX  indicator in **exciting** BOT.  I would like to
place the order only on trend either PUT or CALL. *
*This ATR indicator will filter trend and sideways.  *

*If you add ATR indicator with sample settings  will change **according** to
my *requirement*.*

*ex: Please order PUT or call based on  above 12.000 above from below
chart. (ATR+CCI+SMA4+SMA1) *

[image: image.png]

The above all requirement is for 1 minute candle.


3) *The second requirement is after changing all setting please convert
into candle based to ticks wise trade for example 5 ticks CCI and 14 ticks
ATR instead of candled. *

Finally I need orders on current price comparing previous candle close and
ATR indicator  and same BOT convert into tic based CCI and ATR BOT as well.

I am glad to work withe you .. Thanks for your help in advance. Please
reply back if you need any more details.


Thanks
Murali Pujari

Whatsapp +919964402456

Telegram @royal089

**Comment by muroyal** [comment]
Hello willyzkibe,

If you feel it is complex kindly add ATR indicator in to my Bot withe any
sample value above place or order CALL or PUT*. *

*I have tried to add ATR indicator from *
https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#average-true-range


But don't know how to add into watch and purchase your contract module.
Kindly help me on this request.

Thank’s,
Murali Pujari
SQL Server DBA
Datavail  - Global Delivery Centre
Direct Dial: 2122350373
Global Support No: 303.926.4851 – (Option 2)
Murali.pujari@datavail.com  | www.datavail.com

**Comment by muroyal** [comment]
Hello Sir,

How are you?

I have added indicator and tested it is not worth.. Can you please add
stochastic indicator in place of ATR ?

Thanks

Murali
