### ISSUE TITLE
Price after 7 ticks

### ISSUE THREAD

**Issue by BinaryBiksu** [binary-com/binary-bot#2172]
Dear

Does anyone know how to get price before and after 7 ticks
For example, if at first tick higher than last tick, purchase Rise

Thx

**Comment by ghossan86** [comment]
https://github.com/Fruitfella/ROBOT-binary/issues/26

**Comment by BinaryBiksu** [comment]
Suwun yo leekkk

**Comment by ghossan86** [comment]
Njjieeh ndook..cah ayuu..

**Comment by BinaryBiksu** [comment]
Wkwkwk
Aq lanang leeek

**Comment by BinaryBiksu** [comment]
Tiwas boso inggerisan, tibake wong jowo

**Comment by ghossan86** [comment]
Hwahahaaa...
