### ISSUE TITLE
New Algo Project

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#2173]
Hi Guys, 

I have been playing about with a "quant"/"algo"/blackbox" application for binary.com. Basically, totally automated, it runs ongoing backtests on all markets, and only when the best market meets my predetermined thresholds for quality does it place trades.

It was intended to be nodejs only, but I've decided to put a front end on it to make it more user-friendly.

It doesn't require any trading knowledge, technical analysis or anything, just put in your risk tolerances, API token, and let it trade.

I am still tweaking and testing but will be looking to release soon.

As always, it is will be totally free to download and use :)

![BlackBox](https://user-images.githubusercontent.com/17556774/69733141-c207b000-1124-11ea-9dfd-d22d6214115e.JPG)
![BlackBox2](https://user-images.githubusercontent.com/17556774/69733156-c6cc6400-1124-11ea-9e22-c45cac6f7fc2.JPG)

**Comment by anncoin** [comment]
Hi.
How do i get it?

**Comment by wilburforce83** [comment]
@anncoin it's not released yet, but I'll put a link up once I've finished my live testing l.

Thanks!!

**Comment by anncoin** [comment]
I am using the one you have on your page and I get a server error every time I try to open any operation ... how long will it take to launch it and be able to use it?

**Comment by ceakuk** [comment]
> 
> 
> Hi Guys,
> 
> I have been playing about with a "quant"/"algo"/blackbox" application for binary.com. Basically, totally automated, it runs ongoing backtests on all markets, and only when the best market meets my predetermined thresholds for quality does it place trades.
> 
> It was intended to be nodejs only, but I've decided to put a front end on it to make it more user-friendly.
> 
> It doesn't require any trading knowledge, technical analysis or anything, just put in your risk tolerances, API token, and let it trade.
> 
> I am still tweaking and testing but will be looking to release soon.
> 
> As always, it is will be totally free to download and use :)
> 
> ![BlackBox](https://user-images.githubusercontent.com/17556774/69733141-c207b000-1124-11ea-9dfd-d22d6214115e.JPG)
> ![BlackBox2](https://user-images.githubusercontent.com/17556774/69733156-c6cc6400-1124-11ea-9e22-c45cac6f7fc2.JPG)

it would be  interesting to know  winrate for say 1000 trades. 
is the return on investment 0.94 like in rise/fall ?

**Comment by GoncalvesF253** [comment]
@wilburforce83 você é o cara !

**Comment by anton-binary** [comment]
Hi all,
I have to close this thread as it's not related to Binary Bot/DBot. Feel free to discuss that on https://binary.vanillacommunity.com/

Thanks,
Anton.
