### ISSUE TITLE
High Profit

### ISSUE THREAD

**Issue by willyzkibe** [binary-com/binary-bot#2176]
hellow i have a bot it seem to be analyzing but not taking trade can you help fix the bug how do i upload am getting an erro when itry to upload here

**Comment by ZDEGLET** [comment]
присылай посмотрим
zdeglet@gmail.com

**Comment by Max-Profit** [comment]
> hellow i have a bot it seem to be analyzing but not taking trade can you help fix the bug how do i upload am getting an erro when itry to upload here

zip the file , and then upload
