### ISSUE TITLE
candle closing basis

### ISSUE THREAD

**Issue by josward1** [binary-com/binary-bot#2179]
Hi i have a very simple crossover bot but i only want the bot to take a trade if the crossover has happened and the candle has closed? At the moment the bot takes a trade at any point during the
 candle. Can anyone help me please?

**Comment by willyzkibe** [comment]
can you she

> 
> 
> Hi i have a very simple crossover bot but i only want the bot to take a trade if the crossover has happened and the candle has closed? At the moment the bot takes a trade at any point during the
> candle. Can anyone help me please?

can you share the bot wilymu@gmail.com

**Comment by binary-ex-machina** [comment]
@josward1 you can put your logic inside the IF, like the image below
![image](https://user-images.githubusercontent.com/34610787/70377470-8c688100-18f3-11ea-9e31-79813a37c4af.png)

It will only trigger at the last tick of the actual (1min) candle, so your cross filter will be done in that moment, once

**Comment by willyzkibe** [comment]
hello joseph ave been unable to complete the task as am also practising
coding so kindly just allow me to keep trying  as i learn  i will get back
to you
