### ISSUE TITLE
Creat bot Please Help ! ^__*

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2183]
Dear All

Please can any one help me with creat bot in this idea :

If the last digit is a odd number and happend 5 times Respectively

example : the alst digit : 1 . 5 .1 .3 ,9 (5 odd digit ) 
the next trade will be for even numbers  
the bot will take a even trade .

thank you

**Comment by daredude26** [comment]
hey,i have the bot as you asked,i tried to upload here,but it failed,kindly mail me at vasudevanvelu@gmail.com,i will share with you,if it goes well share it here

**Comment by ahmadhus** [comment]
@daredude26  

Brother i sent you email >>
thank you

**Comment by daredude26** [comment]
i have replied you

**Comment by ahmadhus** [comment]
`file:///C:/Users/drana/Downloads/binary-bot%20even%20odd%20bot.xml`

**Comment by ahmadhus** [comment]
[file:///C:/Users/drana/Downloads/binary-bot%20even%20odd%20bot.xml](url)

**Comment by ahmadhus** [comment]
brother , @daredude26 daredude26

the bot is good but we need to make some changes on it , 

1) if the trade happend and the result is lose then we should make a changes in bot to take all the martingale trades Directly and sequentially without waiting until new 5 odd number coming , 

exp : the last numbers was like this 
1 ,5,5,7,9,3,7,5,2,4
(5 odd) the trade is even as let is say the result is loss becuse the last digit was 3 in the example
so the robot should take new trade on the 3 and the result is loss becuse the last digit was 7 in the example , 
again robot should take new trade on the 7 and the result is loss becuse the last digit was 5 in the example
 new trade on 5 then finaly we won becouse the last digit was 2, 

do you understand me ? 
can you make this changes ? 
[binary-bot even odd bot.zip](https://github.com/binary-com/binary-bot/files/3907523/binary-bot.even.odd.bot.zip)

**Comment by daredude26** [comment]
hi bro, good dayiam not a coder,you can post in github and ask the coder to
help,i just shared you what i got,

**Comment by drezende89** [comment]
[binary-bot even odd bot.zip](https://github.com/binary-com/binary-bot/files/3914002/binary-bot.even.odd.bot.zip)

test

**Comment by daredude26** [comment]
Hi dreezen, good day
        I tested the bot,could you please modify,like when the trade loss,
example even is loss ,the robot keeps continue to take even trades, instead
when digit even loss,set the bot to take digitodd trades immediately till
it profit,can you do that please,Thanks in  advance

**Comment by silambu8194** [comment]
How I create Trading BOT last digit is ODD / EVEN based on Entry and Exit.

![123](https://user-images.githubusercontent.com/66401379/83713113-e4830480-a644-11ea-8546-8d508f78a888.PNG)
