### ISSUE TITLE
My bot for correction. please. I need some help on the soros count block.

### ISSUE THREAD

**Issue by bkan-jp** [binary-com/binary-bot#2184]
good evening everyone.
please. I need some help on the soros count block.
ex. would get whatever the bot made only 3 contract and reset to first contract if all 3 was won.

My bot for correction ..
[Soros =3  Martingale =8.zip](https://github.com/binary-com/binary-bot/files/3906575/Soros.3.Martingale.8.zip)

**Comment by binary-ex-machina** [comment]
try like this
![image](https://user-images.githubusercontent.com/34610787/70377410-f6345b00-18f2-11ea-900a-4c0945677d33.png)

**Comment by bkan-jp** [comment]
@binary-ex-machina 
Thanks a lot for the help
