### ISSUE TITLE
Percentage Price Binary Bot for 10$

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#2185]
https://www.youtube.com/watch?v=6QHlkEfI5zk
no martingale

**Comment by eonuoha30** [comment]
Useless bot

**Comment by tymu** [comment]
> Useless bot
https://www.youtube.com/watch?v=rvPIJSoTpJw

**Comment by eonuoha30** [comment]
...so, I checked again.

Its SCRAP.

...still a USELESS BOT

**Comment by ZDEGLET** [comment]
ШЛЯПА!!!
