### ISSUE TITLE
t5 Strategy with EMA 10

### ISSUE THREAD

**Issue by traderjnunes** [binary-com/binary-bot#2187]
Dear Srs
Could you help me to create a bot with the rules below:
1.	The previous candle should be open over the EMA with period 10 and close above EMA 10 period
2.	Actual candle should be open above the EMA with period 10 and close over EMA 10 period
3.	If we have conditions 1 and 2 or vice-versa signal is true
4.	Next candle green or red will define the direction of the trade, if close green trade put, if close red trade call.
5.	If steep four is loss, trade again with the same direction, with martingale factor configurable in two times.
Regards

**Comment by binary-ex-machina** [comment]
you can do like this. It will do the analysis on the last tick of each candle, only once. If the conditions met, it will place the trade. In case of a loss, it will apply martingale and activate the recover mode, where it will ignore the filter and place the same direction of the previous trade.

![image](https://user-images.githubusercontent.com/34610787/70377335-32b38700-18f2-11ea-9a2e-69c8e1233398.png)

**Comment by traderjnunes** [comment]
Tanks for your reply. I will test. Regards
