### ISSUE TITLE
How to add ATR indicator

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2188]
Hello Team,

Can you please help me how to add ATR indicator in to our BOT. Please provide code or how to add indicator. 

![Capture](https://user-images.githubusercontent.com/32416314/69927782-39d13400-14b1-11ea-8a3d-3b23d7ec0a55.PNG)

Thanks

**Comment by muroyal** [comment]
@eonuoha30 @jy-binary

**Comment by muroyal** [comment]
https://www.investopedia.com/terms/a/atr.asp

**Comment by binary-ex-machina** [comment]
I have created ATR indicator, you can check and download it here
https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#average-true-range

![image](https://user-images.githubusercontent.com/34610787/70377184-1d3d5d80-18f0-11ea-93dd-fed361669489.png)

**Comment by muroyal** [comment]
Getting array error. Kindly help me how to add variable and add ATR indicator.

**Comment by binary-ex-machina** [comment]
@muroyal post an image of the blocks you did so far

**Comment by muroyal** [comment]
Please find below block


[image: image.png]

**Comment by muroyal** [comment]
Kindly add ATR condition in highlighted area with condition ATR above only
has to purchase PUT or CALL.

[image: image.png]

Thanks & Regards

Murali Woota

**Comment by binary-ex-machina** [comment]
you can add the ATR filter like this, using the values you need together with other filters
![image](https://user-images.githubusercontent.com/34610787/70383885-78a13700-1954-11ea-8f1e-c3dd65fd0ef7.png)

**Comment by muroyal** [comment]
Getting below results.




[image: image.png]

I have change it like below


[image: image.png]

Is it correct

Thanks

Murali woota

**Comment by muroyal** [comment]
I have fixed it now withe below settings. Why ATR is showing above 400 where can i verify it is there any charts to verify in binary.com. 

![image](https://user-images.githubusercontent.com/32416314/70385462-9782e600-19b3-11ea-85fe-d1d14a5c1b5e.png)

**Comment by muroyal** [comment]
@binary-ex-machina

**Comment by muroyal** [comment]
@binary-ex-machina Got it according to the script the ATR value will change.
