### ISSUE TITLE
The Default Candle Interval must be equals to Duration 

### ISSUE THREAD

**Issue by tnhminh** [binary-com/binary-bot#2189]
![image](https://user-images.githubusercontent.com/20137683/69936648-f3a8be80-150a-11ea-8d14-6efdf9d3c5fb.png)

![image](https://user-images.githubusercontent.com/20137683/69936665-015e4400-150b-11ea-8c09-87a5b91957e6.png)

Hi admin,

I want to know about the relation of them.
Maybe, when I want to start the contract by setting up 5 min duration, the Default Candle Interval must be the same with Duration?

**Comment by binary-ex-machina** [comment]
No need to have the same candle interval as your duration. Default Candle interval will be used on the blocks that have the use default at the end

like this one
![image](https://user-images.githubusercontent.com/34610787/70377158-dd767600-18ef-11ea-9055-e3d5f756f281.png)

**Comment by tnhminh** [comment]
In case of having the getUpperTrendLine by using the default candle (value is 5 min on the pic). 
The duration definition is 1 min, something went wrong while I use 1 min to start the contract but the signal for the upper trendline is 5 min?

![image](https://user-images.githubusercontent.com/20137683/70427057-a4cccd00-1aa6-11ea-8558-651cbd53e452.png)

**Comment by tnhminh** [comment]
Please see the 2 number in the above
