### ISSUE TITLE
Hello bot  can you add smart martingale

### ISSUE THREAD

**Issue by yakturkt** [binary-com/binary-bot#2191]

**Comment by yakturkt** [comment]
Hello bot can you add smart martingale
[binary-bot 9.zip](https://github.com/binary-com/binary-bot/files/3910811/binary-bot.9.zip)

**Comment by tnhminh** [comment]
Hi guy, 

I confuse about your bot, why the win rate is alway 100%?

**Comment by ZDEGLET** [comment]
ТАК ЭТО ХОРОШО:)

**Comment by ZDEGLET** [comment]
смарт это как?

**Comment by ZDEGLET** [comment]
1,100,1000 .....

**Comment by binary-ex-machina** [comment]
@tnhminh it's not 100% win rate, run for 10min and you will see it will lose, at least 10% of the trades

A bot like this, Digit Under 9 is like Digit Differ 9. 

@yakturkt explain what your smart martingale do?
