### ISSUE TITLE
Do we have any Bot which will determine the upper/lower trend within high exact result?

### ISSUE THREAD

**Issue by tnhminh** [binary-com/binary-bot#2192]

**Comment by Kosta92** [comment]
What?

**Comment by binary-ex-machina** [comment]
@tnhminh high exact result? what that means? it's impossible to determine the trend with 100% accuracy, you will have a clue where you are now, like using Moving averages

![image](https://user-images.githubusercontent.com/34610787/70377121-6a6cff80-18ef-11ea-8df9-1df0e1efb479.png)
