### ISSUE TITLE
Bot Binary Control N. of Runs

### ISSUE THREAD

**Issue by Eulerhp** [binary-com/binary-bot#2193]
Help me.

Hello I am building a robot, and I need to put a limit on daily operations, it would be no. off runs. Can someone help me how to do this. I already searched but found nothing.

**Comment by aaron-binary** [comment]
Hey @Eulerhp,

There is no way to limit the amount of daily trades on our website, however you may check out the [self exclusion page](https://www.binary.com/en/user/security/self_exclusionws.html). On this page you can set turnover limits, maximum number of open positions, etc.

Alternatively you can add this kind of logic to your bot strategy, however this doesn't stop you from running the bot again and bypassing your own limits.

Regards,
Aaron

**Comment by Eshhh** [comment]
![image](https://user-images.githubusercontent.com/33750313/70030252-d50bfb80-15ce-11ea-815e-865ed804d39c.png)

**Comment by ceakuk** [comment]
you mean number of trades?

**Comment by Eulerhp** [comment]
> você quer dizer número de negociações?

Yes

**Comment by Eulerhp** [comment]
> Hey @Eulerhp ,
> 
> Não há como limitar a quantidade de transações diárias em nosso site, mas você pode conferir a [página de autoexclusão](https://www.binary.com/en/user/security/self_exclusionws.html) . Nesta página, você pode definir limites de rotatividade, número máximo de posições em aberto, etc.
> 
> Como alternativa, você pode adicionar esse tipo de lógica à sua estratégia de bot, no entanto, isso não impede que você execute o bot novamente e contorne seus próprios limites.
> 
> Atenciosamente,
> Aaron

Thank you

**Comment by Eulerhp** [comment]
you have example this limit position? of. num runs

**Comment by Eulerhp** [comment]
> Hey @Eulerhp,
> 
> There is no way to limit the amount of daily trades on our website, however you may check out the [self exclusion page](https://www.binary.com/en/user/security/self_exclusionws.html). On this page you can set turnover limits, maximum number of open positions, etc.
> 
> Alternatively you can add this kind of logic to your bot strategy, however this doesn't stop you from running the bot again and bypassing your own limits.
> 
> Regards,
> Aaron



> you mean number of trades?



> Hey @Eulerhp,
> 
> There is no way to limit the amount of daily trades on our website, however you may check out the [self exclusion page](https://www.binary.com/en/user/security/self_exclusionws.html). On this page you can set turnover limits, maximum number of open positions, etc.
> 
> Alternatively you can add this kind of logic to your bot strategy, however this doesn't stop you from running the bot again and bypassing your own limits.
> 
> Regards,
> Aaron

Hi, 
Hello I want to tug my robot when he makes 10 entries losing or winning when he hits 10 operations he is tucked, this is what I need.

**Comment by binary-ex-machina** [comment]
@Eulerhp the bot will not stop, but it will not make any further trade when it hits 10 trades
![image](https://user-images.githubusercontent.com/34610787/70768337-6e5fae00-1d43-11ea-923b-0e9e100c90dd.png)
