### ISSUE TITLE
BINARY BOT PREDICTION RULE

### ISSUE THREAD

**Issue by eva123456-debug** [binary-com/binary-bot#2194]
GoodDay, i need help with something, some one please help me code this

previous result entry spot : xxxx.xx4

next trade prediction should be 4    - then the entry spot result of this trade is xxxx.xx3

now the next trade prediction should be 3.

i have tried doing it on my own, however the prediction does not change accordingly
[](url)
![Opera Snapshot_2019-12-02_195235_bot binary com](https://user-images.githubusercontent.com/58440136/69982709-ce817380-153d-11ea-835d-83b5441c413f.JPEG)
   
PLEASE HELP

**Comment by eva123456-debug** [comment]
PLEASE HELP GUYS

**Comment by ceakuk** [comment]
@eva123456-debug 
maybe this is not the answer you expected but the truth is that it can't work. i have done it many times back then.

the fact that the last digit was X doesn't mean it cant repeat. it can repeat even 100 times in theory.

please read a bit about random numbers? each  number is independent of the previous numbers. so if last number is X, the new generated number gives all the next number equal probability of being generated. you can't predict them. you can only design a smart money management (martingale  etc ) but smarter than what currently exists

**Comment by eva123456-debug** [comment]
Thank you. much appreciated
