### ISSUE TITLE
permanently compress blocky or use password

### ISSUE THREAD

**Issue by ceakuk** [binary-com/binary-bot#2195]
@aaron-binary  @anton-binary
Dear binary.com,
I would like to share my bot which has taken me 2 years to build. however I  don't trust that after using free on demo, anybody will ever rent it if they can just keep it and even sell it as their own. 

my suggestion is if we can  permanently compress blocky codes or  set passwords for decompressing, then I can set expiry time within the blocky. thatway i can control how long i allow anybody to use itfor free or at a fee. thank you

NB/ any other suggestion is appreciated. but i don't want to just get commission by using the api/backend. too little returns

**Comment by Eshhh** [comment]
oh wow, its like you buy a Tesla but the controls are in Elon's hands.

**Comment by ceakuk** [comment]
@Eshhh 
you don't buy. you can't afford to buy coz i would sell it for 1 million $.
you rent it.  if you want to make 10,000$ then the bot stops working when your target is reached. you don't pay untill you reach your target.

the most expensive bot im sure is less than 100$. tell yourself, why would anybody  do all the work of trying to sell a bot for that small amount if  such a bot works? they would do better making money with it.
and once you buy it, you could just resell it as yours if it works. the truth is  those bots are fake.     

my bot will be free to use on demo account and  then only pay 10% of the total profit you make. I cant sell  something fake if im only being paid after profit is made, can I ?

**Comment by Eshhh** [comment]
That wouldn't work. The problem here is trust and accountability. Even if the bot is free or you would take your cut only when the bot reaches its target, people have to put their money into their accounts and the controls are in your hands for the particular bot. Who would trust you with their money, or even if they trust your bot, will you take accountability for any losses incurred by whoever is using your bot?

**Comment by xremmy** [comment]
@ceakuk 
How can i contact you?

**Comment by ceakuk** [comment]
@xremmy
my email address is wishpool@gmail.com

**Comment by ceakuk** [comment]
> 
> 
> That wouldn't work. The problem here is trust and accountability. Even if the bot is free or you would take your cut only when the bot reaches its target, people have to put their money into their accounts and the controls are in your hands for the particular bot. Who would trust you with their money, or even if they trust your bot, will you take accountability for any losses incurred by whoever is using your bot?

you don't understand.
I don't control the bot. i send it to you the bot but you can't see the codes and you cant modify it. i have no control of it at that stage. its just that once the target is met, the  bot is now useless.

talking of trust, i think its way more trustworthy than anything you can find online. currently, any stupid bot you have to buy without trying it for free. that's  susceptible to fraud. you should be able to try it for free limitless forever on demo account and only pay commission on your real accounts profit

**Comment by ceakuk** [comment]
> 
> 
> That wouldn't work. The problem here is trust and accountability. Even if the bot is free or you would take your cut only when the bot reaches its target, people have to put their money into their accounts and the controls are in your hands for the particular bot. Who would trust you with their money, or even if they trust your bot, will you take accountability for any losses incurred by whoever is using your bot?

what do you mean trust me with their money? im not trying to manage accounts. i live in EU so I cant trade with my bot unfortunately.
about in case of loss, isn't that why you use demo account to know how it works and you set your own targets?
out of all those hundreds of fake bots out there, have you asked them if they pay you back for  your losses or you are trying by all means to find something negative. even  with a strange question.

show me which bot  that id more transparent and works 24/7 and with stoploss less that 30% of take profit and i give you my bot free. all of it.

**Comment by Eshhh** [comment]
Your bot may be the best bot in the world, idk, but i don't like the way you are trying to sell it or rent it even. If people buy a product by paying what its worth, then they are alone accountable for how they use it, even if they bought a stupid ass bot and incurred losses, it would be the mistake of the buyer and not the seller. But in your case if you even have the slightest of control over your product that other people are using which could render the bot unusable, then that is not a democratic way of doing business. And also nobody knows if you have good intentions for others with your bot, do you wanna genuinely help others make money or you wanna just make money for yourself?

And when you say "i think its way more trustworthy than anything you can find online" i wouldn't take just your word for that. Anyways good luck buddy.

**Comment by ZDEGLET** [comment]
выставляй видео и продавай его. эта тема не раз здесь озвучивалась. Нито не сделал чтоб поставить пароль.

**Comment by ceakuk** [comment]
@ZDEGLET 
thanks for your comments. however please when commenting to a post in English, try and  even google translate it.

problem with youtube videos:
1) any bot is a winner, just do many virtual accounts videos and post as a good bot
or
2) do a few  real account videos short enough to make some money and those that loose, you will get back your money by selling the fake bot.

no, i will not sell the bot. what stops you from  re-selling it. maybe 100 people buys at30$ =3000$ . that is pocket  money for my 2 years work  and then you will make that amount in 1 day from my sweat

**Comment by ceakuk** [comment]
> 
> 
> Your bot may be the best bot in the world, idk, but i don't like the way you are trying to sell it or rent it even. If people buy a product by paying what its worth, then they are alone accountable for how they use it, even if they bought a stupid ass bot and incurred losses, it would be the mistake of the buyer and not the seller. But in your case if you even have the slightest of control over your product that other people are using which could render the bot unusable, then that is not a democratic way of doing business. And also nobody knows if you have good intentions for others with your bot, do you wanna genuinely help others make money or you wanna just make money for yourself?
> 
> And when you say "i think its way more trustworthy than anything you can find online" i wouldn't take just your word for that. Anyways good luck buddy.

i posted this to ask binary.com  how we can sell at peace. when you buy iphone or any proprietary product do you have access to the technology or just the usage?
im asking the most basic and scam free question. i have created over 1000 bots in the process, 99.99% of the never made it. i could make videos and sell the crap but im not like that. i 

either you dont understand english or you are just ignorant. try to think please and if you can't then just stay away from this thread. create yours

**Comment by ceakuk** [comment]
@Eshhh 
do you know how the random number generator for the synthetic instruments  (volatility index) works?
is it democratic?
im really pissed off by your luck of intelligence

**Comment by aaron-binary** [comment]
Hey @ceakuk,

Let's keep it civil please. 😄 

This is an interesting question. Technically I don't believe it's possible to create closed-source strategies, the only thing we could do from our side is preventing the user from exporting the strategy or implement some kind of authentication system for strategies. A thing to note is that all of our frontend apps are open-source, a technical user could easily reverse engineer our logic.

An alternative solution would be to create your own application which implements the logic of your strategy on the server-side using our API. You would ask for a user's API token which would allow your app to make trades on their behalf, as well as charging a markup between 0-5%. You may read more here:

- https://developers.binary.com/ 
- https://developers.binary.com/applications/

The best place to get support for third-party apps is on our forums: 
- https://binary.vanillacommunity.com/

Hope that helps,
Aaron

**Comment by eonuoha30** [comment]
....I fully understand and support @ceakuk  ideology.
Being able to give out a bot  without exposing the coding behind it is nice.

I once tried minimizing the blocks.
Later, I tried adding a SECRET password but a programmer such as ceakuk and binary ex machina can easily decipher it.

If truly @ceakuk  , your bot works , I'd love to have access to it. 
If possible , hide the code.

Its strictly for personal use as I have no intention of selling or renting anything.

**Comment by eonuoha30** [comment]
...I hv  a not that can run for 24 hours without exceeding 210 $.

....still working on it.

An understanding on the randomness or pseudorandomness of random numbers is VERY important if you are trading volatility index.

The second factor is an understanding of the concept of PROBABILITY

and finally, being able to relate a good STAKING PLAN to the probabilities

**Comment by eonuoha30** [comment]
@ceakuk  , you can reach me via eonuoha30@gmail.com

**Comment by Eshhh** [comment]
> 
> 
> > Your bot may be the best bot in the world, idk, but i don't like the way you are trying to sell it or rent it even. If people buy a product by paying what its worth, then they are alone accountable for how they use it, even if they bought a stupid ass bot and incurred losses, it would be the mistake of the buyer and not the seller. But in your case if you even have the slightest of control over your product that other people are using which could render the bot unusable, then that is not a democratic way of doing business. And also nobody knows if you have good intentions for others with your bot, do you wanna genuinely help others make money or you wanna just make money for yourself?
> > And when you say "i think its way more trustworthy than anything you can find online" i wouldn't take just your word for that. Anyways good luck buddy.
> 
> "democratic way of doing business"????
> is it democratic that you are using that computer but the softwares are both protected? do you know the ingredients in cocacola we consume yet the ingredients are not known to us?
> 
> i posted this to ask binary.com how we can sell at peace and not work for years then let others use/sell it. when you buy iphone or any proprietary product do you have access to the technology or just the usage?
> im asking the most basic and scam free question. i have created over 1000 bots in the process, 99.99% of the never made it. i could make videos and sell the crap but im not like that. i
> 
> either you dont understand english or you are just ignorant. try to think please and if you can't then just stay away from this thread. create yours

I know you are pissed, but that doesn't stop me from pissing you off more. lol

We do know the ingredients in coca cola we just don't know the recipe, its patented, like wise we do have access to the technologies of an iphone and the methods and tools to recreate it, but it is again patented. Just buy the patent and recreate your own cocacola or iphone. And the random number generator works the same way as its name suggests, it works "randomly". So if possible patent your bot and prove that it works, ill buy it happily, instead of trying to make money out of it in a fishy way.

Okay i accept that i lack intelligence, but Ive also been told that the people who attack other people for their lack of intelligence are the people who lack intelligence primarily. Peace

**Comment by eonuoha30** [comment]
Whichever way u see it,

Both of you guys are right.

But speaking on the interest of ceakuk, I think a feature should be added to lock the blocks code from being visible or make it collapse permanently.

Its my effort and I have the right to lock it.
Speaking of patency, binary.com can fix a little fee to this feature before anyone can 'lock' a bot.

Else, they can leave it freely.

Imagine finding your 2years of labour bot  on YouTube for sale @ 10$ without your consent and you have absolutely no one to cry to.

That's too.... BAD.

**Comment by ceakuk** [comment]
> A thing to note is that all of our frontend apps are open-source

"A thing to note is that all of our frontend apps are open-source"
that is useless. as long as your back-end is closed.  allow us also to steal your back end and to create our versions of competing binary.com platform


you would not want other people to start a new binary.com, stealing your  many years of work. for you to all these years not protect the work of developers is a shame.

We need to e able to protect our work

**Comment by ceakuk** [comment]
> 
> 
> Hey @ceakuk,
> 
> Let's keep it civil please. smile
> 
> This is an interesting question. Technically I don't believe it's possible to create closed-source strategies, the only thing we could do from our side is preventing the user from exporting the strategy or implement some kind of authentication system for strategies. A thing to note is that all of our frontend apps are open-source, a technical user could easily reverse engineer our logic.
> 
> An alternative solution would be to create your own application which implements the logic of your strategy on the server-side using our API. You would ask for a user's API token which would allow your app to make trades on their behalf, as well as charging a markup between 0-5%. You may read more here:
> 
>     * https://developers.binary.com/
> 
>     * https://developers.binary.com/applications/
> 
> 
> The best place to get support for third-party apps is on our forums:
> 
>     * https://binary.vanillacommunity.com/
> 
> 
> Hope that helps,
> Aaron

so i give you a bot which i have worked on for years and tested to be sure it has never failed and the maximum i get is 5%
if you make 1000$  i get 50$ that is the most stupid thing. even a beggar doesn't get that low

**Comment by xremmy** [comment]
@ceakuk Check your mail

**Comment by binary-ex-machina** [comment]
@aaron-binary API approach is the best for protected code. Please don't put the bot.binary with that password feature. A lot of people just want to make money selling things that probably don't work, so these passwords will just destroy the community, specially here. A lot of people will take the help here and sell, and others that will start learning will never be able to see good things that where made

Just take a look at the Expert Advisors thing that Meta Trader has, thousands and thousands of bots, all code protected, less then 0.01% work well
