### ISSUE TITLE
Reverse Martingale Bot programming?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#2196]
Does anyone know of any simple Reverse Martingale Bots, or Paroli systems, that I could try as .xml's?

I just wanted to see how they worked in terms of programming etc.

I have tried programming my own, so that a win doubles up, instead of a loss, but my loss doesn't go back to $1 stake after a loss??

Here when the $11.37 is a loss, surely it should go back to $1 to start again? Is that correct?
![Screen Shot 11](https://user-images.githubusercontent.com/43829090/70059185-3d130f80-15d8-11ea-919a-735f09d5e499.png)

**Comment by ZDEGLET** [comment]
пришли своего робота посмотрим
zdeglet@gmail.com

**Comment by binary-ex-machina** [comment]
@buckman1974 you can do like this
![image](https://user-images.githubusercontent.com/34610787/70377044-72786f80-18ee-11ea-83fe-9fd6588d7251.png)

**Comment by buckman1974** [comment]
Thank you @binary-ex-machina 

What if i wanted to reverse-martingale, only 5 wins, then start again, so that my stake doesn't go too high, incase I lose, so as its winning, it just starts over again?

Thanks!
