### ISSUE TITLE
![image](https://user-images.githubusercontent.com/33750313/70030252-d50bfb80-15ce-11ea-815e-865ed804d39c.png)

### ISSUE THREAD

**Issue by Eulerhp** [binary-com/binary-bot#2197]
![image](https://user-images.githubusercontent.com/33750313/70030252-d50bfb80-15ce-11ea-815e-865ed804d39c.png)

_Originally posted by @Eshhh in https://github.com/binary-com/binary-bot/issues/2193#issuecomment-561041863_

Hi,
Hello I want to tug my robot when he makes 10 entries losing or winning when he hits 10 operations he is tucked, this is what I need.
No, of runs = 10 =  Bot stoped

**Comment by Eshhh** [comment]
just change the no of runs to 10 instead of 1000

**Comment by Eulerhp** [comment]
> just change the no of runs to 10 instead of 1000

I did it but it is not stopping, it shows the alert, but still operating.

**Comment by Eshhh** [comment]
send me the bot

**Comment by ceakuk** [comment]
there are 2 methods. here is method 1 which i don't like. 
![Capture](https://user-images.githubusercontent.com/43122491/70099139-3e6f2700-162e-11ea-95fa-8c9421eb2b13.PNG)


problem with the method is say  you want 10 runs and the bot stops after 10 runs. if you want another 10 runs, you have to clear the  trades  like below
![Capture1](https://user-images.githubusercontent.com/43122491/70099263-a6be0880-162e-11ea-9e27-abaa22d9d2e4.PNG)

**Comment by ceakuk** [comment]
better this way. so when you stop the bot and start again, it starts counting for that session
![Capture](https://user-images.githubusercontent.com/43122491/70099836-48922500-1630-11ea-8bfc-691d07f5db02.PNG)

**Comment by Eulerhp** [comment]
Very good, Thanks . Thanks Thanks
Love U rsrsr

Em ter., 3 de dez. de 2019 às 20:53, ceakuk <notifications@github.com>
escreveu:
