### ISSUE TITLE
Help to create strategies

### ISSUE THREAD

**Issue by trident2005** [binary-com/binary-bot#2198]
@binary-ex-machina HI

Regards.

This is the first algorithm that I created of this type, apparently everything is well done and works correctly for a while and then for no apparent reason it stops without throwing any error message, will anyone know what could be happening?

I hope you can help me

[Close change MACD.zip](https://github.com/binary-com/binary-bot/files/3920053/Close.change.MACD.zip)

**Comment by binary-ex-machina** [comment]
It's a failure on the sell at market logic, inside the binary bot code. There is nothing you can do with blocks to prevent, as far as i tried and saw this error so far.

**Comment by trident2005** [comment]
Thank you very much for your response, I thought it was something that could be corrected, but if it is a platform error there is nothing that can be done about it.

**Comment by binary-ex-machina** [comment]
give a try with this on block 3. the logic is to check if it's available to sell at market first. Looks like the rest of the logic in selling the contract will go without issues after the bot check that first

![image](https://user-images.githubusercontent.com/34610787/70149557-1eb81d00-1687-11ea-9cc8-1a5debf54932.png)

**Comment by trident2005** [comment]
I will try it and give you my feedback

**Comment by trident2005** [comment]
Good way to simplify the algorithm, now I learned something new.

I was testing the structured block in the same way as you showed it to me in the capture, but the result is the same, it work well for a while but it stop working for no apparent reason.

**Comment by binary-ex-machina** [comment]
this may be a code issue inside the binary bot code. Maybe @anton-binary can check your script and see what could be the problem

**Comment by trident2005** [comment]
It seems to be a good strategy but it is necessary to constantly test it to know its weakness, but with these interruptions it is not possible to obtain that data

**Comment by Kosta92** [comment]
Gosh, I hate those freezes... They happen randomly, no matter what kind of bot you are running. They also happen when you're using a 3rd party Binary.com trading software.

**Comment by trident2005** [comment]
That error has given me a lot using that Watch and Sell block, good strategies can be developed with that block, I think binary.com should pay attention to that problem since if a Martingale strategy stops at a 5 or 6 level, that it could mean a very big problem

**Comment by trident2005** [comment]
@anton-binary regards

Do you have any response to the error raised in this thread?

**Comment by trident2005** [comment]
Regards, I have a question

How could this scrypt be improved so that the purchase signal occurs exactly at the candle close?

![capture](https://user-images.githubusercontent.com/56892552/70481112-f6318800-1ab7-11ea-9a9c-71095ee5ccfc.jpg)

**Comment by binary-ex-machina** [comment]
@trident2005 try to put all the content of the block 2 inside this block below. It will make the analysis on the last tick of the 1min candle

![image](https://user-images.githubusercontent.com/34610787/70482647-cccb2900-1ac4-11ea-9295-c5d57560c7c5.png)

**Comment by trident2005** [comment]
It seems to work excellent.

Thank you very much @binary-ex-machina
![Sin título](https://user-images.githubusercontent.com/56892552/70488780-2a18a780-1ad0-11ea-94e1-2443cf396449.png)

**Comment by trident2005** [comment]
Regards

I have been trying to create a candle analysis, I want to get the difference between entry prices closing prices, higher price and lower price, but this program does not return the data I want to get to create the strategy, I need get the differences between one point and another to establish comparisons with each other.
![Watch and purchase BLOCK](https://user-images.githubusercontent.com/56892552/70863553-d36ffb00-1f1f-11ea-819f-b71842b9914a.png)

**Comment by trident2005** [comment]
Greetings.

@binary-ex-machina 

Could you help me complete this algorithm ??, this is a digit analyzer that I configure only for OVER / UNDER (from FRUITFELLAS), I configured 2 barriers that vary according to the percentage, Exm. if the percentage from 0 to 4> 5 to 9 the barrier is = 3 and the contract is OVER otherwise the barrier is = 6 and the contract is UNDER. The bot seems to work well but sometimes, the transition between one barrier and another does not run in a clean way, that is, sometimes the contract is OVER and the barrier does not fit 3 remains at 6 and sometimes the same thing happens in opposite case.

[Example.zip](https://github.com/binary-com/binary-bot/files/4009954/Example.zip)

**Comment by binary-ex-machina** [comment]
in order to have the analysis working 100% of the time, you must put the filters before defining the prediction, in a loop. When the conditions met, you break the loop and continue the trade

![image](https://user-images.githubusercontent.com/34610787/71597314-6bc1ce80-2b21-11ea-8ad5-7f5ad1663558.png)

**Comment by trident2005** [comment]
@binary-ex-machina Thank you very much once again, I will try and give you my feedback

**Comment by trident2005** [comment]
@binary-ex-machina The scrypt works 100%, it is excellent, thanks again!!!

Speaking of the same scrypt, there is something else that I would like to try, but I don't know how to generate lists (assuming it can be done with lists), I would like to establish an entry point for the purchase defined by only the rising percentage, for example , we have the two groups, from 0 to 4 and from 5 to 9, suppose that the percentage of the first group 48% and after several ticks it becomes greater than 50% to buy UNDER and the same condition for the other group.

If it is over 50% only open orders when the percentage goes up, example 2, if it comes from 50% to 51% or higher then BUY, but if the percentage comes in backward as 60% to 58% do not buy anything, I want the entries to be made only when the percentage increases, in each group individually (0-4 percentage and 5-9 percentage).

I've tried a lot but I have no idea why I can't make it work.

**Comment by trident2005** [comment]
@binary-ex-machina regards

I was thinking about money management but I have no idea how to materialize it.

Is it possible to emulate fake operations?, I explain to you, when the strategy sends a signal, a real operation does not open but a notification is issued, for example, but that the algorithm is able to keep a count of how many of those fakes operations  would have been lost and from this count determine the entry of real operations in martingale.

Grateful for your attention.
