### ISSUE TITLE
Change Trade Type from Over/Under to Differ

### ISSUE THREAD

**Issue by war10ckoo1** [binary-com/binary-bot#2200]
As mentioned, need help with this, strategy is when loss with over under after that next trade will be for differ. No need for whole code, just need piece of code or advice to change trade type.

**Comment by ceakuk** [comment]
within web based XML, you can not change from even/odd to over/under to match/diff

**Comment by muroyal** [comment]
Kindly add ATR condition in highlighted area with condition ATR above only has to purchase PUT or CALL. 

![image](https://user-images.githubusercontent.com/32416314/70383728-d6577280-1998-11ea-952a-bf0413a58353.png)
