### ISSUE TITLE
Olá como posso fazer um bot que identifique a cor das velas ?

### ISSUE THREAD

**Issue by gustavolima2019** [binary-com/binary-bot#2201]
Gostaria de saber como montar um bot para a estratégia : 
Se houver 3 velas seguidas na cor Vermelha o bot deve comprar Acima e se houver 3 velas verdes seguidas o bot devera comprar Abaixo .

Alguém pode me ajudar ?

**Comment by drezende89** [comment]
![3candle](https://user-images.githubusercontent.com/47386079/70155425-fdf4c500-1690-11ea-9eb2-718720d454ba.PNG)
