### ISSUE TITLE
Random Fall/Rise?

### ISSUE THREAD

**Issue by Gasha0** [binary-com/binary-bot#2202]
How can i make a random fall/rise blocks?

**Comment by Kosta92** [comment]
Don't bother. This "strategy" always fails at some point, no matter how random you make it.

**Comment by binary-ex-machina** [comment]
@Gasha0 you can do like this

![image](https://user-images.githubusercontent.com/34610787/70376900-e4e85000-18ec-11ea-9456-295be96f024e.png)

**Comment by ceakuk** [comment]
@binary-ex-machina 
i think you are alternating rise and fall instead of random. also as already said, that strategy cant work. random can  take rise even 100 times in a row
![Capture](https://user-images.githubusercontent.com/43122491/70765452-2187d180-1d5b-11ea-87ff-fe4f1e4e68bb.PNG)
