### ISSUE TITLE
Need Help to add ADX or ATR indicator in my binary bot. 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2208]
Need Help to add wither ADX indicator or ATR indicator with combination of CCI BOT. 

The bot is running successfully i need to twice bit withe adding ATR or ADX indicator. 

![image](https://user-images.githubusercontent.com/32416314/70319712-dd587680-181a-11ea-829a-10c96bf37336.png)

Please any developers Kindly help

**Comment by muroyal** [comment]
I Believe My Bot will provide more probability results if we add ATR or ADX indicators. 

Please find youtube video for the bot results. [Link](https://www.youtube.com/watch?v=99rG7a1FIMU&lc=z22rxzybtlu3fvymgacdp43bgbyoqtxy5mfvf1qpgcdw03c010c)

**Comment by binary-ex-machina** [comment]
@muroyal do you own that bot? the guy of the video is charging $20 for that, probably is not profitable...

also the video doesn't show any indicator he is using, so you are guessing that he uses ADX and CCI?

i don't advise anyone buy something after seeing a video of the results on demo account. Specially if you saw these kinds of bots on github repositories

**Comment by muroyal** [comment]
@binary-ex-machina thanks for your advice...
