### ISSUE TITLE
Alguém pode me falar como fazer o bot vender contrato antecipado ?

### ISSUE THREAD

**Issue by ForexJapao** [binary-com/binary-bot#2210]
Alguém pode me falar como fazer o bot vender contrato antecipado no bloco 3 ?

**Comment by binary-ex-machina** [comment]
você pode fazer igual na imagem abaixo. O bot vai vender quando o lucro da ordem atual for maior que $0.5 

![image](https://user-images.githubusercontent.com/34610787/70376675-3216f280-18ea-11ea-9c77-fe21fdd3dfbc.png)

**Comment by ceakuk** [comment]
@binary-ex-machina 
sell/askprice = 0.5
because different ask price have different sell profit/loss

**Comment by binary-ex-machina** [comment]
@ceakuk it was an example on how to do it, provide a better one with images, it will help more

**Comment by ceakuk** [comment]
![Capture](https://user-images.githubusercontent.com/43122491/70377020-94ceb500-190f-11ea-9b40-fdf14c0ce197.PNG)

**Comment by pgfbr** [comment]
Muito Obrigado @binary-ex-machina  e @ceakuk  pela ajuda !!

**Comment by pgfbr** [comment]
Tentei fazer desta forma mas não funcionou, eu queria que quando o lucro negativo fosse Igual ou menor que metade do valor inicial o bot vendesse o contrato para não perder 100% do valor inicial. Alguém me ajuda ? 
![image](https://user-images.githubusercontent.com/56320282/70395747-a7fd8580-19e0-11ea-987f-2c148ac5583b.png)
