### ISSUE TITLE
COPYTRADING

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#2211]
Please, what's the maximum number of accounts you can link to your account via copy trading?

Secondly, while trading on demo, can you link account to yours via copy trading?

**Comment by gustavolima2019** [comment]
Qual empresa de copytrading você usa ?

**Comment by anton-binary** [comment]
Hi @eonuoha30 ,

>Please, what's the maximum number of accounts you can link to your account via copy trading?
There's no such limit. However, if you could share what you are going to do, we can be more specific about possible issues.

>Secondly, while trading on demo, can you link account to yours via copy trading?
You can link demo to demo and/or real to real. You can't link real to demo.

Thanks,
Anton

**Comment by eonuoha30** [comment]
@aaron-binary  , what I meant was the maximum number of account (different persons) i can link to my account via copy trading (real account to real account).

Secondly, if I set up telegram notifications in a binary bot, my trade notifications on the telegram bot  page won't be visible to the members.

Why is this so? And how can I fix it so that members can see the notifications?

**Comment by aaron-binary** [comment]
Hi @eonuoha30,

- If I'm not mistaken you may link an unlimited number of accounts through copytrading.
- Telegram notifications only work through bot strategies, so they will only work for the user running the bot strategy. An alternative would be to implement the webhook block which allows you to send a payload to any endpoint, you could for example implement your own push notifications with this.

![Screenshot 2019-12-10 at 09 37 30](https://user-images.githubusercontent.com/44427668/70487592-d0949500-1b30-11ea-9629-6dd0e1c82b92.png)

Hope this helps,
Aaron

**Comment by eonuoha30** [comment]
> Hi @eonuoha30,
> 
> > @aaron-binary , what I meant was the maximum number of account (different persons) i can link to my account via copy trading (real account to real account).
> 
> If I'm not mistaken you may link an unlimited number of accounts through copytrading.
> 
> > Secondly, if I set up telegram notifications in a binary bot, my trade notifications on the telegram bot page won't be visible to the members.
> 
> Telegram notifications only work through bot strategies, so they will only work for the user running the bot strategy. An alternative would be to implement the webhook block which allows you to send a payload to any endpoint, you could for example implement your own push notifications with this.
> 
> ![Screenshot 2019-12-10 at 09 37 30](https://user-images.githubusercontent.com/44427668/70487592-d0949500-1b30-11ea-9629-6dd0e1c82b92.png)
> 
> Hope this helps,
> Aaron

Yes, your response was VERY helpful.

I have a telegram notification linked to my bot. 
The notification sent includes my trades details such

**Comment by eonuoha30** [comment]
please, use BASIC terminologies in your explanation because I'm not a programmer.

I may not understand terms like webhook, endpoint, payload

**Comment by eonuoha30** [comment]
@aaron-binary 

@aminmarashi-binary

**Comment by aaron-binary** [comment]
Hi @eonuoha30,

> I normally use a 'forwarder' app to auto-transfer those messages to another telegram channel where they can view it.

That's a creative way of solving your problem. 👍

---

There is currently no way to set up Telegram to send messages to copytraders and I don't think we'll ever implement it. The webhook blocks I mentioned previously may offer a solution as it's completely up to you as to what you'll do with the data that's sent to the endpoint you specify, however you may need some technical knowledge to implement this.

A webhook could make a request to your own server e.g. `https://website.com/send_message_to_all_coptraders`. Your server would receive a payload in the form of a JSON object e.g.

```JSON
{
   "message": "Profit: $100"
}
```

Your own server could then implement its own logic to send the message to all your Telegram chats, there are no limitations on how to process the data you send from a Binary Bot instance to your own server.

Regards,
Aaron

**Comment by eonuoha30** [comment]
Can you help me with a sample of how to work on it?

Assuming...

1.  I have created a telegram bot via botfather titled  'BINARY BOT'

2. I also have a telegram channel titled 'BOT CHANNEL'

3. I intend to send notification of my trades 'TOTAL PROFIT' to the channel for all the members to see (via the telegram channel).

The message is not to be sent to individual members. Rather, I want it to be posted on the channel such that anyone that joins the channel can view it.

PLEASE,  give me a sample of how I can do the above using the 'WEBHOOK ' or the 'NOTIFY TELEGRAM' feature

**Comment by daisia6449** [comment]
Hi everyone, are you looking for a professional binary, forex and Bitcoin broker/manager who will guide and help manage your trade and help you earn meaningful profits all within 24 hours or within a week? contact Daisia Benson now for your investment plan. Daisia Benson has helped me to earn 92,300 USD just with a little investment capital and with the aid of Daisia Benson trading software system that brings forth good trading signals i was able to trade and cash out on time and am still trading with Daisia Benson, if you need assistance on how to recover your lost investment in bitcoin/binary Contact her now on whatsapp : +1 718 218 4397. or contact Daisia Benson on email address Email: tradewithdaisiabenson@gmail.com [WITH DAISIA BENSON I BELIEVE THERE ARE STILL GOOD INDIVIDUALS WHO STILL HAVE GOOD INTENTION TO OTHERS. ONCE AGAIN THANKS DAISIA.]
