### ISSUE TITLE
three buying trigger single bot worth bot $ 30

### ISSUE THREAD

**Issue by rubenspina** [binary-com/binary-bot#2213]
ver testado várias vezes muito mais difícil de quebrar a conta bot está funcionando bem, aguardando o momento da compra ativado com três alternativas de compra inteligente na perda, ele não está desesperado comprando todos os contratos em que está calmo, mesmo quando o mercado gira em segundos.
bot value $ 30 Não sei para que serve o log de bot, mas estou atualizando-o aqui.
transfere NETELLER 451425729446 email projetos_10@hotmail.com para enviar comprovante de pagamento projetos_10@hotmail.com arquivo bot.xml por email.
![foto9](https://user-images.githubusercontent.com/30381449/70470391-aba90f00-1aa9-11ea-9c85-78417a477e55.png)

**Comment by eonuoha30** [comment]
This is trash...!!!

No analysis can work as long as you are trading on 'DIGITS'

As a matter of fact, you LACK the basic understanding of how 'DIGITS over/under' works.

When I joined this forum , I was clueless like you.
I made useless bot  requests and kept on asking how to add stop loss or take profit.
But after reading several great articles, I can comfortably build better profitable BOTS with good money management.

**Comment by eonuoha30** [comment]
....without 'good' money management system (not martingale) , all your efforts are trash

Forget your crazy 'analysis'

**Comment by rubenspina** [comment]
MOSTRA O SEU MELHOR
________________________________
De: PremzY <notifications@github.com>
Enviado: segunda-feira, 9 de dezembro de 2019 21:00
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: rubenspina <projetos_10@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] three buying trigger single bot worth bot $ 30 (#2213)


....without 'good' money management system (not martingale) , all your efforts are trash

Forget your crazy 'analysis'

**Comment by rubenspina** [comment]
MANDA UNS TRES BOT BOM AI PARA MEU EMAIL
________________________________
De: PremzY <notifications@github.com>
Enviado: segunda-feira, 9 de dezembro de 2019 20:57
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: rubenspina <projetos_10@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] three buying trigger single bot worth bot $ 30 (#2213)


This is trash...!!!

No analysis can work as long as you are trading on 'DIGITS'

As a matter of fact, you LACK the basic understanding of how 'DIGITS over/under' works.

When I joined this forum , I was clueless like you.
I made useless bot requests and kept on asking how to add stop loss or take profit.
But after reading several great articles, I can comfortably build better profitable BOTS with good money management.

**Comment by nobleb2007** [comment]
Why you always condemned peoples strategy and u never make any effort to supply any help. What work for A may not work for B.

**Comment by thommmaz** [comment]
> ver testado várias vezes muito mais difícil de quebrar a conta bot está funcionando bem, aguardando o momento da compra ativado com três alternativas de compra inteligente na perda, ele não está desesperado comprando todos os contratos em que está calmo, mesmo quando o mercado gira em segundos.
> bot value $ 30 Não sei para que serve o log de bot, mas estou atualizando-o aqui.
> transfere NETELLER 451425729446 email [projetos_10@hotmail.com](mailto:projetos_10@hotmail.com) para enviar comprovante de pagamento [projetos_10@hotmail.com](mailto:projetos_10@hotmail.com) arquivo bot.xml por email.
> ![foto9](https://user-images.githubusercontent.com/30381449/70470391-aba90f00-1aa9-11ea-9c85-78417a477e55.png)

Put your bot on real account if you want to sell it. If you think its so good then why demo?

**Comment by ceakuk** [comment]
> 
> 
> ver testado várias vezes muito mais difícil de quebrar a conta bot está funcionando bem, aguardando o momento da compra ativado com três alternativas de compra inteligente na perda, ele não está desesperado comprando todos os contratos em que está calmo, mesmo quando o mercado gira em segundos.
> bot value $ 30 Não sei para que serve o log de bot, mas estou atualizando-o aqui.
> transfere NETELLER 451425729446 email [projetos_10@hotmail.com](mailto:projetos_10@hotmail.com) para enviar comprovante de pagamento [projetos_10@hotmail.com](mailto:projetos_10@hotmail.com) arquivo bot.xml por email.
> ![foto9](https://user-images.githubusercontent.com/30381449/70470391-aba90f00-1aa9-11ea-9c85-78417a477e55.png)

its true, you can never do statistics on random numbers like digits.
to build a good bot, let martingale or such systems just compliment your analysis. do the bot with fixed stake first and realize this so called analysis is just  illusion. good luck
