### ISSUE TITLE
Golden traditional strategy __ Need BOT

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2215]
Requirment:

Heikin-Ashi--- Candles.
Smart martigle
200 Moving average
20 moving average
4 or 8 moving average.
CCI indicator

Call Stratagy:

1)Previous candle open greater than close.
2)current price more than previous candle close.
3)price us more than 8 moving average and 20 moving average and 200 moving average.
4) CCI is more than 100.
5)stochastic Buy signal (for double confirmation)

Trade must open starting of candle.

Put stratagy:

previous candle close less than open.
Current price less than previous candle close.
3)Price below 8 EMA and 20 EMA and 200 EMA.
4)CCI less than -100
5)stochastic sell 
Trade must open starting of candle.

Need 1 minute or 5 minute startagy- for forex trading.

**Comment by mustdowe80** [comment]
[GOLDEN TRADITIONAL STRATEGY V3.zip](https://github.com/binary-com/binary-bot/files/3966198/GOLDEN.TRADITIONAL.STRATEGY.V3.zip)
hopefully it's useful.

**Comment by muroyal** [comment]
Thanks a lot !! It will be very use full I will test it and update @mustdowe80

**Comment by muroyal** [comment]
https://www.youtube.com/watch?v=M8fr0MYgIs4&t=374s

https://www.youtube.com/watch?v=KKWnrlD8cqU

@mustdowe80 Kindly check this stratagy i have given above based on this video..

**Comment by muroyal** [comment]
As we are trading on candle based trades hence i have changed 

SMA---200  to SMA -- 20

SMA--- 20  to  SMA -4

SMA -- 8 To SMA --1 

CCI- -50 and CCI 50 

Testing withe above configurations..

**Comment by muroyal** [comment]
@mustdowe80 Can you please add Choppiness indicator into it the trades should be executed between 
61.8 for the high threshold and 38.2 for the lower threshold to avoided side ways and High volatility.

**Comment by muroyal** [comment]
I have tried to add Choppiness indicator  but getting error.

**Comment by muroyal** [comment]
I have modified the BOT updated for Binary options. Please test it and provide your suggestions
[Chanikya_Forex_Bot_V5.zip](https://github.com/binary-com/binary-bot/files/3984235/Chanikya_Forex_Bot_V5.zip)
