### ISSUE TITLE
I have a Bot i have been trying to get working properly

### ISSUE THREAD

**Issue by josward1** [binary-com/binary-bot#2217]
I have a Bot i have been trying to get working properly for some time now.I am struggling to get it fully functioning how i want it. If there is anybody on here who can help me i can send the XML file of the bot, explain the strategy. I am a professional trader trying to get my strategy on a bot to maximise trading hours and minimise human error. The finished product would be very much of interest to anybody wanting to earn money via binary options. Any help i have had on here up to now has been not worked. I am looking to send the bot to a professional to get amended and receive back fully functioning. If anyone is interested email me on josward1@hotmail.com

**Comment by ZDEGLET** [comment]
zdeglet@gmail.com присылай бота посмотрим.

**Comment by ZDEGLET** [comment]
zdeglet@gmail.com присылай бота посмотрим.

**Comment by ceakuk** [comment]
@josward1 
Unless you are paying for the help, you want free help but still keeps your bot to yourself

**Comment by josward1** [comment]
Ok, i an happy to pay for help i am new to this site and do not fully understand how this works. i have a bot that needs amending so it works properly. Who do i need to speak to so i can arrange this? i am happy to pay i just need some help
________________________________

**Comment by ZDEGLET** [comment]
ПИШИ ЧТО НУЖНО НА ПОЧТУ. ЧТО МОЛЧИШЬ. ИЛИ ЗДЕСЬ ПИШИ. НЕ ОЧКУЙ ВСЕ ПОД КОНТРОЛЕМ.
