### ISSUE TITLE
Help with Higher Lower

### ISSUE THREAD

**Issue by dune2** [binary-com/binary-bot#222]
Hello Sir,

I am having problem with "Barrier" in Higher/Lower contracts.

What I expect to happen:
 When Call is initiated, it should open with +1 Barrier
When Put is initiated, it should open with -1 Barrier

But Instead Bot sometimes opens Call with -1 Barrier and Put with +1 Barrier and sometimes opens the way I want to as described above.

I am attaching Image,

Please Help!

Thank You.

![mabasedhigherlower](https://cloud.githubusercontent.com/assets/28773865/26188626/bf666802-3bb9-11e7-9567-f42f1e6f0b0a.jpg)

**Comment by aminmarashi** [comment]
There's no correct way of doing this in the current version. However, in the [experimental version](https://aminmarashi.github.io/binary-bot/bot.html) you can put the indicators in the first block and select the barrier sign based on that.
<img width="452" alt="screen shot 2017-05-18 at 6 14 37 pm" src="https://cloud.githubusercontent.com/assets/6560964/26197732/e30aaa5c-3bf5-11e7-95d5-185e8236c2d7.png">

**Comment by dune2** [comment]
Thank You Sir for quick reply!

**Comment by freesurf1988** [comment]
I did not understand how to do it!

**Comment by freesurf1988** [comment]
I tried to do it but I could not

**Comment by aminmarashi** [comment]
Please send me your original blocks so that I can help you do it. You need to make a zip file first to be able to upload it here.

**Comment by okovalov** [comment]
@aminmarashi it wont help. the variable "Barrier Offset 1" is defined as +1 on the contract definition step. So even though it is indeed gets changed based on sma14 value, its new value is not updating the contract in the step 2. it only happens at step 4.

**Comment by aminmarashi** [comment]
Exactly, that's why I suggested to do it in the first step!

**Comment by okovalov** [comment]
@aminmarashi when the experimental version is planned to be merged to the upstream?

**Comment by aminmarashi** [comment]
It's taking longer than expected. We tried rewriting the core in a way that's more testable and readable and therefore less error prone. But in the process, we concluded that it's necessary to use a flow architecture (using redux) to make the bits and pieces more testable.

**Comment by dune2** [comment]
[MABasedHigherLower.txt](https://github.com/binary-com/binary-bot/files/1017766/MABasedHigherLower.txt)


I have attached my bot, just rename txt to xml
It is giving the problem that i described earlier.

Would be nice if someone could fix it!

Thank You!

**Comment by aminmarashi** [comment]
I created this for you: [MABasedHigherLower-modified.xml.zip](https://github.com/binary-com/binary-bot/files/1017873/MABasedHigherLower-modified.xml.zip) and fixed a related bug in the process, so please refresh before use. (You can try it in [Beta](https://bot.binary.com/beta/bot.html)

**Comment by dune2** [comment]
WOW! Working Fine now in beta version!
Thank you so much Sir! 
You are truly Amazing!!!
