### ISSUE TITLE
Bot won't open trade at the beginning of the candle

### ISSUE THREAD

**Issue by thommmaz** [binary-com/binary-bot#2228]
Any ideas why it always open trade at 58 sec and not 00 ? It's volatility 100 index.

![epoch](https://user-images.githubusercontent.com/40931373/70692243-914a7d80-1cc3-11ea-94c4-3065536972f4.png)

**Comment by binary-ex-machina** [comment]
Try with < 3

**Comment by thommmaz** [comment]
> Try with < 3

Thanks!
