### ISSUE TITLE
COPYTRADING

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#2239]
@aaron-binary 
Can you help me with a sample of how to work on it?

Assuming...

1.  I have created a telegram bot via botfather titled  'BINARY BOT'

2. I also have a telegram channel titled 'BOT CHANNEL'

3. I intend to send notification of my trades 'TOTAL PROFIT' to the channel for all the members to see (via the telegram channel).

The message is not to be sent to individual members. Rather, I want it to be posted on the channel such that anyone that joins the channel can view it.

PLEASE,  give me a sample of how I can do the above using the 'WEBHOOK ' or the 'NOTIFY TELEGRAM' feature

**Comment by binary-ex-machina** [comment]
After you create the bot, you will receive the access token
it will look like this **123456789:AAFzLsmmPdfslfnsldnfklsndf1ip5sf4sfjosikrm54g**

to get the chat ID of your channel first add the bot to the channel and put as admin, then send a message in the channel using your account, manually

After you add the bot and send a message on the channel, go here https://api.telegram.org/bot<AccessToken>/getUpdates and substitute the AccessToken by the token you got when creating the bot

It will display in your browser something like this
![image](https://user-images.githubusercontent.com/34610787/70769248-86d1c780-1d47-11ea-8d69-16d2c37622ef.png)

the id that will appear here is what you need
![image](https://user-images.githubusercontent.com/34610787/70769262-8f2a0280-1d47-11ea-801d-33a70edc91a4.png)

then is just use the telegram block on bot.binary, the bot will send a message to the channel

![image](https://user-images.githubusercontent.com/34610787/70769328-cd272680-1d47-11ea-9adb-a5136f3c29ac.png)

**Comment by eonuoha30** [comment]
Thanks
This should be exactly what I need.

I'd try it out

**Comment by eonuoha30** [comment]
I've done exactly as you instructed but its saying 'telegram notification can't be sent'

**Comment by eonuoha30** [comment]
![Screenshot_2019-12-13-10-21-24](https://user-images.githubusercontent.com/52554096/70793304-48fe8e80-1d9b-11ea-9284-7bb517266ba8.png)

**Comment by binary-ex-machina** [comment]
you can contact me binaryexmachina@gmail.com and send your access token of the bot. I will check what can be the problem. In case you don't mind post it here, i can help you right away.

**Comment by eonuoha30** [comment]
@binary-ex-machina 

Thanks for your response

Here's the token

1035129231:AAHG_HSxUiBWZmOcLjxsO7P2beWF7N8pc5U

**Comment by binary-ex-machina** [comment]
@eonuoha30 it should be working now, i have sent some test messages, don't know if it worked, but you can add me on the channel as well, just for checking if it's working  Telegram: **@binaryexmachina**

Use the block below
Chat ID: -1001443005901

URL to check updates - https://api.telegram.org/bot1035129231:AAHG_HSxUiBWZmOcLjxsO7P2beWF7N8pc5U/getUpdates

![image](https://user-images.githubusercontent.com/34610787/70837402-50955600-1de2-11ea-8704-df8a20d115d7.png)

**Comment by eonuoha30** [comment]
Yeah, I got ur messages on the channel

Sometimes, I marvel at your skills.
Thanks alot

**Comment by eonuoha30** [comment]
Please, delete the last message you sent here

**Comment by binary-ex-machina** [comment]
@eonuoha30 only admins can delete

**Comment by eonuoha30** [comment]
....I finally discovered my error.

There's a MINUS sign before those numbers in the ' chat I.d '

Without that sign , the chat I.d is incomplete and won't work.

So, never forget to add it up
