### ISSUE TITLE
Martingale alternate-call-up-on-two-loss

### ISSUE THREAD

**Issue by Agentsbu** [binary-com/binary-bot#224]
Hi Guys, I Need to know how to put martigale on Alternate call up on two loss ? I tried it and it ddnt work
![bot](https://cloud.githubusercontent.com/assets/26632197/26218359/fa7b6c52-3c0a-11e7-81a2-5c357835590f.png)

**Comment by Fruitfella** [comment]
Hi @Agentsbu , i dont get what u mean. can u explain it more? in a more simple way.
my english is terible. itd be easier for me to understand if u use trades example, like how u want the bot make a purchase or how u want the bot put the martingale.

**Comment by Agentsbu** [comment]
![bot](https://cloud.githubusercontent.com/assets/26632197/26260479/ae85bbc2-3ccd-11e7-9dd8-aa7d2964b7ce.png)
![bot 2](https://cloud.githubusercontent.com/assets/26632197/26260492/bc5d401c-3ccd-11e7-841f-40a61e192840.png)
I want it to multiply on loss.

**Comment by Fruitfella** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26277327/26261350/0972cda4-3cfb-11e7-9f27-eec0ce819ed0.png)

**Comment by Agentsbu** [comment]
Excellent Work, Short and Sweet. Thanks Man!!!!#
