### ISSUE TITLE
Bot doesn't work continue after run several times. The reason?

### ISSUE THREAD

**Issue by tnhminh** [binary-com/binary-bot#2240]

**Comment by tnhminh** [comment]
The reasons I think about:
1/ Connection
2/ Anything else?

**Comment by binary-ex-machina** [comment]
Did you manage to reproduce the error? The chances of a connection problem are big

**Comment by ZDEGLET** [comment]
ПРИСЫЛАЙ НА ПОЧТУ ПОСМОТРИМ
zdeglet@gmail.com

**Comment by ZDEGLET** [comment]
@binary-ex-machina ОНИ ПИШУТ А РОБОТА НЕ ВЫСЫЛАЮТ КАК БУДТО У НИХ В РУКАХ ГРААЛЬ.
Я СИЖУ НА ЭТОМ ФОРУМЕ НАВЕРНО 3 ГОДА И ЕЩЕ НИ ОДНОГО НОРМАЛЬНОГО РОБОТА НЕ ВИДЕЛ.
