### ISSUE TITLE
Money management in cycles

### ISSUE THREAD

**Issue by thommmaz** [binary-com/binary-bot#2241]
How is it possible to make money management in cycles? The idea is that after loss(still same stake) we start calculating sum of next wins and losses until we get 2 wins in a row and then based on the sum of last trades we raise stake. If lose, back to initial stake and calculating should continue. Cycle should end after we get 3 wins in a row.

![cycles](https://user-images.githubusercontent.com/40931373/70786241-dbe7fa80-1d94-11ea-8c50-4c0b058dae5d.png)

**Comment by binary-ex-machina** [comment]
you can do like this
![image](https://user-images.githubusercontent.com/34610787/70816754-f202b480-1dae-11ea-91c8-8a9deb3ab58d.png)

You will face things like this below, which can lead to something very bad
![image](https://user-images.githubusercontent.com/34610787/70816788-ffb83a00-1dae-11ea-92b0-3c5f82faab08.png)

**Comment by thommmaz** [comment]
Awesome, thank you very much! I know there is a big risk there but I'm trying to implement it with splitting martingale so let see. Thank you again!
