### ISSUE TITLE
Are there any bot builders on here i can pay for technical help?

### ISSUE THREAD

**Issue by josward1** [binary-com/binary-bot#2242]
Are there any bot builders on here i can pay for technical help?

**Comment by ZDEGLET** [comment]
СМОТРЯ ЧТО НУЖНО ДЕЛАТЬ

**Comment by josward1** [comment]
i do not understand this language

________________________________

**Comment by josward1** [comment]
i do not understand this language

**Comment by ZDEGLET** [comment]
LOOKING FOR WHAT YOU NEED TO DO. WRITE.

**Comment by josward1** [comment]
I have a bot that is not functioning how I want. Needs correcting. Can you help
 I can send xml file? And explain strategy

On 13 Dec 2019, at 23:56, Zdeglet <notifications@github.com<mailto:notifications@github.com>> wrote:


LOOKING FOR WHAT YOU NEED TO DO. WRITE.

**Comment by ZDEGLET** [comment]
send the robot to the mail we will see what to do.

**Comment by josward1** [comment]
I want a put trade to be taken when the RSI crosses below 70 on candle closing, I want a call trade to be taken when the RSI crosses above 30 when the candle has closed. This is what I have so far but the bot takes trades anywhere on the RSI. The strategy is strictly crossovers at the set levels. The candle closing and taking the trades exactly in the correct place every time is key to this strategy. t. A signal is no good unless the candle has closed this is confirmation. I also need to be able to adjust the RSI settings as I change the parameters depending on how the chart is behaving.

On 14 Dec 2019, at 17:01, Zdeglet <notifications@github.com<mailto:notifications@github.com>> wrote:


send the robot to the mail we will see what to do.

**Comment by ZDEGLET** [comment]
Where did you find this robot?
send to the mail of your robot I will look.

**Comment by eonuoha30** [comment]
> i do not understand this language

Drop the bot here.

Someone would definitely help you out.

You don't have to pay anyone.
Or send private messages

**Comment by josward1** [comment]
[rsi crossover 1.xml.zip](https://github.com/binary-com/binary-bot/files/3976021/rsi.crossover.1.xml.zip)

Here is the XML file to my bot
