### ISSUE TITLE
Multiple entries with martingale (with remuneration WITH REMUNERATION)

### ISSUE THREAD

**Issue by alissonlinneker** [binary-com/binary-bot#2243]
I need a strategy to work as follows:

- Insert the list of currency pairs with their respective times and if it is M5, M10 or M15, and inform if it is PUT or CALL;
- The entry is made at the indicated time with 1% of the bank;
- In case of loss he makes the first Martingale with 2.3% of the bank;
- In case of second loss, he makes the last Martingale with 4.6% of the bank;

The list contains an average of 10 entries to be performed.

I'll pay for this. Anyone willing?

**Comment by ZDEGLET** [comment]
САМ БОТ ЕСТЬ ОТ ЧЕГО РАБОТАТЬ?
