### ISSUE TITLE
How to limit telegram notify only when signal change?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2245]
![Screenshot_2019-12-15-17-46-23](https://user-images.githubusercontent.com/31925501/70860978-169f8d80-1f63-11ea-9ed2-e04ab61cc751.jpeg) 
I try to put telegram bot to give signal on telegram. Current send on every trade on tick.
Need send only when signal change from put to call or call to put how to block this?

**Comment by eonuoha30** [comment]
....drop your bot  here.

It would then be easier to help you out.
What you seek can't take more than 5minutes to fix
