### ISSUE TITLE
Help bot Martingale

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2246]
Dear All,

i need to add Martingale levels in my bot , 

Can you please help me , 

this is My bot 
[Important Bot.zip](https://github.com/binary-com/binary-bot/files/3965126/Important.Bot.zip)

Regards

**Comment by josward1** [comment]
i can send you an xml file with martingale on if that helps?

**Comment by ahmadhus** [comment]
@josward1 josward1 

thanks for replay , 

do you mean that you will adjust my bot by add the Martingale into it and resend it to me as a XMl

that is what i need it , 

regards

**Comment by josward1** [comment]
If you send me the XML file I will load it on. I am not a programmer but I’m sure I will be able to do it
On 16 Dec 2019, at 00:00, ahmadhus <notifications@github.com<mailto:notifications@github.com>> wrote:


@josward1<https://github.com/josward1> josward1

thanks for replay ,

do you mean that you will adjust my bot by add the Martingale into it and resend it to me as a XMl

that is what i need it ,

regards

**Comment by ahmadhus** [comment]
@josward1 josward1
brother i already attached my bot as a zip
download it and will work directly ..
here we can not attached Xml files ..
adjust it and resend it here 
or send it by email ..
Ahmadhusam1996@gmail.com
