### ISSUE TITLE
Help to limit or martingale after losing 3 in a row

### ISSUE THREAD

**Issue by iblime** [binary-com/binary-bot#2247]

**Comment by iblime** [comment]
Hello, I need some help.

I would like to limit my bot's martingale when it loses 3 in a row, back to the initial stake value.

**Comment by iblime** [comment]
My bot:
[Over Under 8.zip](https://github.com/binary-com/binary-bot/files/3965853/Over.Under.8.zip)

**Comment by eonuoha30** [comment]
[Un8 3step martingale.xml.zip](https://github.com/binary-com/binary-bot/files/3967661/Un8.3step.martingale.xml.zip)


Here's your BOT.

GOODLUCK...!!!

(please, its not a zip file. Simply RENAME the file from  " Un8.3step.martingale.xml.zip " TO " Un8.3step.martingale.xml " .   )
Just remove the .zip I added at the end of the file name. that's all. You won't need any software to do this. 
Just click 'rename' on your mobile phone or laptop, then delete the part I told you.
