### ISSUE TITLE
Direction of the Indicator

### ISSUE THREAD

**Issue by HarshAchar** [binary-com/binary-bot#2248]
Hello everyone! Im trying binary bot and I am new. Though I know a few strategies which Im trying to create with blocks.

My question is to do with direction of a particular curve.

We have Direction is Rise/Fall. 

![image](https://user-images.githubusercontent.com/32027087/70879662-38653880-1f94-11ea-914a-2ddf58f892bf.png)

How to use this rise/fall block for an indicator like EMA or SMA?

 
![image](https://user-images.githubusercontent.com/32027087/70879785-aad61880-1f94-11ea-9ce1-f16346171d13.png)

In the above picture the EMA rises and the SMA falls. Is there a way I can implement it in a block?

Like say - If EMA direction is Rise and SMA direction is Fall, then do list of actions.

Any help is much appreciated.

**Comment by NetworkerTrader007** [comment]
Periodos de la SMA Y LA EMA???

**Comment by HarshAchar** [comment]
@NetworkerTrader007 hey amigo! You can take up something like 40 SMA and 10 EMA ;)

Worked out a piece of code by myself. Closing issue.
