### ISSUE TITLE
Periods is Longer than Data length???

### ISSUE THREAD

**Issue by ArunGowthamm** [binary-com/binary-bot#2249]
I know what it's mean while error occors.

But my question is how to determine the data length...what's the limits..what can i do to overcome this error.

Please advice on above

**Comment by aaron-binary** [comment]
This usually happens with indicator blocks, the period you specify cannot exceed the size of the list you plug into the indicator block.

-  **For example**: 
    - You have a list of 3 values: [100.12, 100.50, 100.32]
    - The period you specify is 4.
    - You will now get an error saying the period is longer than the data length.

To verify the length of your list you may use the block below, which you can find in **Advanced** -> **List** -> **length of**:

![Screenshot 2019-12-17 at 15 57 21](https://user-images.githubusercontent.com/44427668/70975967-efbd9480-20e5-11ea-83d0-cdd082fec983.png)

Hope that helps,
Aaron

**Comment by hotmatrixx** [comment]
it also occurs if you try to create a list of more than 999/1000 values
