### ISSUE TITLE
Orders Loss but are Win

### ISSUE THREAD

**Issue by neoricalex** [binary-com/binary-bot#225]
Hi all, sometimes happens bot making a PUT the price goes down but he counts as a loss and lose.
Others make a CALL the price goes up but he looses also.

Any thougs for the the possible causes?

**Comment by Fruitfella** [comment]
Hi @neoricalex U should check the Entry Spot and Exit Spot to know whether the trade is a win or a loss.
The chart often lagging, late about 1 thick.
lately i use notification to tell me the current price (last thick) since the chart is lagging. it help me a little.

**Comment by neoricalex** [comment]
Hi @Fruitfella thanks for youre reply. Nice hint .. Lagging. However i need learn more about notifications because for now, the only way i know is telling to the bot make a print, and that is painfull (need to click ok ok ok ....) but i will learn more about.

again a big thanks !

**Comment by Fruitfella** [comment]
![capturex](https://cloud.githubusercontent.com/assets/26277327/26258562/5e7e95d2-3cef-11e7-840d-89680696bd42.PNG)

**Comment by neoricalex** [comment]
Wow ! Thanks. I will test lets say 48 hours to see if i catch one. if i dont catch i close this topic. But for know i think that is closed.

big thank you @Fruitfella

**Comment by Fruitfella** [comment]
^-^

**Comment by Fruitfella** [comment]
this is a sample on how i use notify block to inform me the exit spot and win/lose.
![win-lose](https://cloud.githubusercontent.com/assets/26277327/26259949/8c97869e-3cf5-11e7-984c-c3d7ec01d4a4.PNG)
i hope this helpful

**Comment by neoricalex** [comment]
Mom says: The table is ready.

^.^

Give me some time to learn and spot how it helps. The idea is perfect. Now i need to learm the "Lists" feature and see what they really do for us.

i will update this post for sure when i spot the idea underline.

Thanks for youre help again @Fruitfella  . helpful for sure (y);-)

**Comment by Fruitfella** [comment]
I found that i made something stupid.
to make the bot notify us about the **Exit value** , simply by putting **Notify** _Last Tick_ in F(4) block is enough. *sigh*
![notif](https://cloud.githubusercontent.com/assets/26277327/26420195/1fc20ec2-40ec-11e7-95e6-bff80b7298aa.png)
put the **Notify** block above **Trade Again**

**Comment by Fruitfella** [comment]
I found that i made something stupid.
to make the bot notify us about the Exit value , simply by putting Notify Last Tick in F(4) block is enough. sigh
![notif](https://cloud.githubusercontent.com/assets/26277327/26420347/85cc9b38-40ec-11e7-90eb-a8a50c2c1c9c.png)

**Comment by neoricalex** [comment]
Im testing, im only comparing the big looses to see if i catch one to make a print.

**Comment by neoricalex** [comment]
Only updating ... is working ... but let me test a bit more ...

**Comment by aminmarashi** [comment]
@neoricalex Is this still happening?

**Comment by aminmarashi** [comment]
I will close this, please feel free to open it again if the issue still exists
