### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2252]
Dear All,

i need to add Martingale levels in my bot , 

Can you please help me , 

this is My bot 
[Important Bot.zip](https://github.com/binary-com/binary-bot/files/3965126/Important.Bot.zip)

Regards

**Comment by ZDEGLET** [comment]
Все работает отлично. Мартингейл загружен.

**Comment by ZDEGLET** [comment]
какие уровни?
