### ISSUE TITLE
Setting visibility of controls in tool bar

### ISSUE THREAD

**Issue by clluiz** [binary-com/binary-bot#2253]
Hi everyone, I started to work with binary-bot and have a question: it is possibile to se what controls will be visible in this tool bar?
![image](https://user-images.githubusercontent.com/1070968/71134323-89676d80-21dc-11ea-9214-3c5cbbb03e77.png)
Thanks in advance!

**Comment by aaron-binary** [comment]
Hey @clluiz, 

We don't currently have this functionality, could you provide us with an example use case of this? We're happy to your feedback. 👍 

Regards,
Aaron
