### ISSUE TITLE
Alguém pode me mostrar como programar o horário da entrada ?

### ISSUE THREAD

**Issue by ForexJapao** [binary-com/binary-bot#2254]
Preciso que o bot dê entrada no EUR/USD as 14:50 como posso fazer isso no bloco ?

**Comment by anton-binary** [comment]
Hi @pgfbr ,
You could try this.
![image](https://user-images.githubusercontent.com/43776314/71243648-c00fc600-234b-11ea-8413-26aaa9b06be3.png)
