### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by karkec** [binary-com/binary-bot#2256]
can anyone help 
me in building a bot. I have attached the bots below. Can anyone combine all these bot signals more or less equally to a single bot with continuous trading for 2.2 time when loss arises.  kindly mail me karkec@gmail.com

**Comment by karkec** [comment]
[6 bots.zip.zip](https://github.com/binary-com/binary-bot/files/3983614/6.bots.zip.zip)

**Comment by muroyal** [comment]
Even  i have three strategies in one bot but they are not working randomly.... evaroyal84@gmail.com is my email ...
