### ISSUE TITLE
Digit/matches bot

### ISSUE THREAD

**Issue by eva123456-debug** [binary-com/binary-bot#2258]
good day, please help...

if result is win , purchase differs
if result is loss , purchse matches

**Comment by gustavolima2019** [comment]
[Win Difers_ Loss Matches @Flavio.zip](https://github.com/binary-com/binary-bot/files/3991798/Win.Difers_.Loss.Matches.%40Flavio.zip)

Veja este !

**Comment by gustavolima2019** [comment]
[Win Difers_ Loss Matches @Flavio.zip](https://github.com/binary-com/binary-bot/files/3991805/Win.Difers_.Loss.Matches.%40Flavio.zip)
 Você quer dizer assim ???

**Comment by eva123456-debug** [comment]
yess, thank you very much
