### ISSUE TITLE
Digit Differ New Candle After Loss

### ISSUE THREAD

**Issue by Agentsbu** [binary-com/binary-bot#226]
Hi Guys, me Again, I want my bot to Run : If Result is Loss = Run After NEW CANDLE. NOT AFTER SECONDS, AFTER NEW CANDLE OPENS
![bot](https://cloud.githubusercontent.com/assets/26632197/26279321/aec3460c-3db0-11e7-86d7-7afebbdc2f3e.png)

**Comment by Fruitfella** [comment]
dont use **[Run After [] Second(s)]** for **[binary;;Is new candle]** , use **if** block instead.

**Comment by Agentsbu** [comment]
I DONT GET IT. EXAMPLE ?

**Comment by Fruitfella** [comment]
im testing my bot now, so i cant give u example. look at bottom left of ur picture above.
what u need to is just replace that orange(pink?) block in **(4) Get your result and trade again** with **if ... do...** block from "logic" menu.
make it like this:

_if_ **[binary;;Is new candle]
_do_ **[Trade Again]**

get it?
u dont need **[Run After [] Second(s)]** block.
@Agentsbu

**Comment by Agentsbu** [comment]
Cool Man the Issue Is sorted. As Always Thanks A Million
