### ISSUE TITLE
Need code sample for results display

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2261]
Hello Team,

can any on provide sample bot which display below results for 10 seconds on very 5 minutes . 

1) Total Profits 
2)Maximum Loss amount
3) Martingle max level reached
4) Winning percentage.

**Comment by eonuoha30** [comment]
Drop your Bot  and is help you fix those stuff in it.

Its very easy

**Comment by muroyal** [comment]
Thanks for reply please find attached bot..
[ForLowB.zip](https://github.com/binary-com/binary-bot/files/3991401/ForLowB.zip)
[King Kong Hack.zip](https://github.com/binary-com/binary-bot/files/3991403/King.Kong.Hack.zip)

**Comment by muroyal** [comment]
I have configured myself ..
