### ISSUE TITLE
Olá como posso fazer o bot para dar uma entrada Call ou Put a cada 10 velas ?

### ISSUE THREAD

**Issue by gustavolima2019** [binary-com/binary-bot#2263]
Olá, alguém pode me mostrar como fazer o bot realizar uma entrada a cada 10 velas ?

Como posso fazer este contador de velas ? Não importa a cor da vela só a quantidade...

**Comment by anton-binary** [comment]
hi @gustavolima2019 

You could try something like this.
![image](https://user-images.githubusercontent.com/43776314/71392708-0fa00b80-2644-11ea-901a-69c9b84d22b1.png)
