### ISSUE TITLE
Trade Every New Candle

### ISSUE THREAD

**Issue by davi9411** [binary-com/binary-bot#2265]
Hello Guys,

I need some help or advice, I have a bot that operates with each new candle, following the color of the previous candle.

My problem is that the Bot does not always open order in the new candle, in some candles it skips.

I am attaching the bot, can anyone take a look or guide me, if there is a way to the bot operate on every new candle?

thanks

**Comment by navneetsinh** [comment]
@davi9411 

![Opera Snapshot_2019-12-26_020331_bot binary com](https://user-images.githubusercontent.com/42480287/71450238-fef6af00-2783-11ea-8262-c3cc4115ac89.png)

Here is your trade duration is 59 seconds
and new trade on every new candle start 0 to 5 seconds, so so some time if trade taken on new candle  1 to 5 seconds + 59 seconds = you skip for next trade.

**Comment by ForexJapao** [comment]
@navneetsinh Existe alguma forma de resolver este problema ?

**Comment by davi9411** [comment]
> @davi9411
> 
> ![Opera Snapshot_2019-12-26_020331_bot binary com](https://user-images.githubusercontent.com/42480287/71450238-fef6af00-2783-11ea-8262-c3cc4115ac89.png)
> 
> Here is your trade duration is 59 seconds
> and new trade on every new candle start 0 to 5 seconds, so so some time if trade taken on new candle 1 to 5 seconds + 59 seconds = you skip for next trade.

Thank you very much, my bad, sometimes we get tired and don't even think straight.

**Comment by ForexJapao** [comment]
@navneetsinh @davi9411 I do not understand, how can it be resolved?

**Comment by navneetsinh** [comment]
@ForexJapao, Just change trade duration,
you'll get your result

**Comment by promzy4844** [comment]
> Hello Guys,
> 
> I need some help or advice, I have a bot that operates with each new candle, following the color of the previous candle.
> 
> My problem is that the Bot does not always open order in the new candle, in some candles it skips.
> 
> I am attaching the bot, can anyone take a look or guide me, if there is a way to the bot operate on every new candle?
> 
> thanks

Help me with the bot please
