### ISSUE TITLE
Erro de vendas esta retirando dinheiro de minha conta!

### ISSUE THREAD

**Issue by opstrade** [binary-com/binary-bot#2266]
![valor removido de minha conta binary](https://user-images.githubusercontent.com/56803963/71420040-af17cb00-2651-11ea-9afd-6f19202cd874.png)
https://www.youtube.com/watch?v=zQ0p1X9p-lI

Robô fez a entrada e retirou dinheiro da conta, logo da um erro quando tenta vender a entrada a mercado, e assim ele faz outra entrada retirando o mesmo valor anterior de minha conta. Assim refazendo uma nova entrada, mas não recuperando o dinheiro retirado duas vezes!
Isso pode se petir seguido mas de uma vez!

**Comment by pgfbr** [comment]
Upload the bot here so we can check and help sir...

**Comment by anton-binary** [comment]
hi @opstrade ,

Can you please also post the error message the bot did when it was trying to sell?

Thanks.

**Comment by opstrade** [comment]
Não vou postar o robô porque ele é pago, do meu canal.. Mas se você montar qualquer estratégia de vendas de contrato, vai esta descobrindo esse erro.. Se não existe mas possibilidades de revender o contrato, simplesmente é só não vender, e deixar o contrato termina. Mas o sistema refaz uma nova entrada retirando mas uma vez o mesmo valor de sua conta, alem disse a entrada do contrato muitas vezes você está ganhando, e ele refaz um nova entrada, e logo pode esta perdendo ...
Pior é saber que a binary, não quer devolver o valor retirado da conta! Queria ver se eu perdesse minha banca por causa desse erro..

**Comment by opstrade** [comment]
![valor removido de minha conta binary](https://user-images.githubusercontent.com/56803963/71446569-87813b00-2703-11ea-8b75-33fd1af6e3fe.png)

**Comment by opstrade** [comment]
![Erro de vendas da Binary](https://user-images.githubusercontent.com/56803963/71446584-b26b8f00-2703-11ea-9f67-92d44bb0cd2e.png)

**Comment by ForexJapao** [comment]
I have bots with contract sales and are working normally, have no errors. If you don't want to post the bot for us to help then solve your problem yourself.

**Comment by ForexJapao** [comment]
I have bots with the contract selling strategy and they are all working perfectly.

**Comment by anton-binary** [comment]
Hi @opstrade,

I ran your bot that you emailed me, it did 128 runs until it had reached the stop loss.
![image](https://user-images.githubusercontent.com/43776314/71451937-0a64cd00-27ba-11ea-8689-c1f029458777.png)

I couldn't replicate neither error nor the issue with missing exit price.
You can check the video
https://www.youtube.com/watch?v=VeY8iq9usgs

It could be internet connection issue and this can happen with any internet service (and with "with any broker").

**Comment by opstrade** [comment]
![opstrade bot - YouTube](https://user-images.githubusercontent.com/56803963/71452343-df02c380-2762-11ea-9958-205e5336d585.png)

Olhei o vídeo, e ele tentou vender e deu a notificação! Justamente quando acontece isso ele refaz a entrada, mas não conseguir ver isso no vídeo... Isso não é um erro de internet, me desculpa. E de qualquer forma eu estou saindo prejudicado com isso... Eu estudo Análise e desenvolvimento de sistemas, e não ia ficar aqui comentando se eu não tivesse certeza do que aconteceu.. Esta tudo gravado, e isso ta acontecendo com outras pessoas.. Vou pedir que o pessoal me manda em vídeo esses mesmos erros, e vou relatar tudo, oque vem acontecendo. Não vou ser reembolsado pela corretora Binary?

**Comment by opstrade** [comment]
![opstrade bot - YouTube](https://user-images.githubusercontent.com/56803963/71452553-d1e6d400-2764-11ea-9cc3-34321d747a32.png)

Essa imagem é do seu vídeo. Deu a notificação de erro da venda, e logo ja comprou novamente, sem terminar o tempo do contrato!

**Comment by opstrade** [comment]
![Sem título](https://user-images.githubusercontent.com/56803963/71452587-1a05f680-2765-11ea-9003-db54f352d142.png)
pode analisar a entrada!

**Comment by opstrade** [comment]
No Deriv, acontece também!

**Comment by opstrade** [comment]
![image](https://user-images.githubusercontent.com/56803963/71452880-3014b680-2767-11ea-8f34-0ba68c224e5c.png)
https://www.youtube.com/watch?v=zQ0p1X9p-lI&t=5s
tempo do vídeo onde ocorre o 1º erro 15:25       conta real

**Comment by anton-binary** [comment]
HI @opstrade ,
>Essa imagem é do seu vídeo. Deu a notificação de erro da venda, e logo ja comprou novamente, sem terminar o tempo do contrato!
Indeed, let me check that again.

**Comment by anton-binary** [comment]
@opstrade In the meantime as a workaround you could check if entry/exit spots are populated using Contract details block.

![image](https://user-images.githubusercontent.com/43776314/71455228-114a0a80-27cf-11ea-8ca1-36a5379ab996.png)

**Comment by opstrade** [comment]
Ta certo eu aguardo, e espero que consiga arrumar isso, já fiquei no prejuízo, por causa disso.. E pior que eu vendo esse robõ e acabo tendo que dar assistência para o pessoal...   😥

**Comment by Kosta92** [comment]
This have also happened to me a few times and the timing is completely random. It's not happening due to a bad bot or due to my perfectly good internet connection, but... "just because"... I really don't know why. What is also happening, again, at random, is that the bot just stops working in the middle of a purchase and can't be stopped or continued - it can only be manually restarted.

**Comment by opstrade** [comment]
Conseguiram resolver esse problema?

**Comment by opstrade** [comment]
![Binary Bot](https://user-images.githubusercontent.com/56803963/71588434-38227c80-2b00-11ea-9c9d-0e44fbb199c5.png)

Oque aconteceu, que não estão mas respondendo o suporte?

**Comment by anton-binary** [comment]
Hi all,

This is being investigated. I'll update here.
In the meantime as a workaround you could check if entry/exit spots are populated using Contract details block.

Thanks

**Comment by opstrade** [comment]
Ta bom, obrigado!

**Comment by opstrade** [comment]
![erro de vendas](https://user-images.githubusercontent.com/56803963/71643005-66d05c80-2c92-11ea-9ce8-011275ebdd1c.png)
Aparece notificação de erro de venda de contrato, (essa revenda de contrato não é oferecida) e o robô não faz mas operações... Nossa, esta complicado de trabalhar com Binary!😓

**Comment by azludium** [comment]
Same error

**Comment by azludium** [comment]
![Facebook1](https://user-images.githubusercontent.com/48847444/71771636-2fc1ab80-2f1d-11ea-8a15-78eef76c9275.jpg)

**Comment by hiltonoishi** [comment]
The error keeps on happening. 
![20200104_183245](https://user-images.githubusercontent.com/59516777/71772239-ae6f1680-2f26-11ea-84f9-c8829f750000.jpg)

**Comment by hiltonoishi** [comment]
Once again and now I lost 1.75usd
![20200104_195055](https://user-images.githubusercontent.com/59516777/71772566-eb89d780-2f2b-11ea-8c7a-d2c3615fd2ec.jpg)

**Comment by hiltonoishi** [comment]
Mais uma vez
![20200104_221023](https://user-images.githubusercontent.com/59516777/71773929-9d350280-2f44-11ea-8b62-e7b331c849ed.jpg)

**Comment by hiltonoishi** [comment]
E mais outra 
![20200104_223856](https://user-images.githubusercontent.com/59516777/71773937-c2c20c00-2f44-11ea-98e2-87fa87f5e0cb.jpg)

**Comment by opstrade** [comment]
> @opstrade Enquanto isso como uma solução alternativa você pode verificar se os pontos de entrada / saída são preenchidos usando os detalhes do contrato bloco.
> 
> ![imagem](https://user-images.githubusercontent.com/43776314/71455228-114a0a80-27cf-11ea-8ca1-36a5379ab996.png)

Isso não funcionou, para nada.

**Comment by alanvito1** [comment]
Visite minha página para download de novos bots gratuitos.
Visit my librarie for new free bots.

https://github.com/alanvito1/superfree-binary-bot

**Comment by opstrade** [comment]
> Visite minha página para baixar novos bots gratuitos.
> Visite minha biblioteca para novos bots gratuitos.
> 
> https://github.com/alanvito1/superfree-binary-bot

Oque vc agrega nesse fórum?  Estamos tentando resolver um erro, ninguém ta interessado em propaganda...

**Comment by binary-ex-machina** [comment]
@opstrade exatamente, é um spam em varios posts

experimenta usar esta logica
![image](https://user-images.githubusercontent.com/34610787/72115412-b31c3c00-3325-11ea-8b53-5e2c18215837.png)


Este erro na venda de contratos esta acontecendo fazem alguns meses. O bot simplesmente para de funcionar

**Comment by opstrade** [comment]
@binary-ex-machina ola, não minha programação está certa, esse erro é da binary... Quero ver se eu vir perde uma banca alta, se eles vão me devolver...
