### ISSUE TITLE
purchase odd and even  

### ISSUE THREAD

**Issue by karing-sidikalang** [binary-com/binary-bot#227]
someone would you please help me to develop a block, open position only last digit is 0 after 5
for instance
XXX.15
XXX.20 ----- purchase odd
XXX.33
XXX.35
XXX.90 ----- purchase even
.
.
            ------ purchase odd

i have developed but it didn't work
![1](https://cloud.githubusercontent.com/assets/28832596/26280374/124475b2-3dfb-11e7-882f-8fd6374be7bf.jpg)

**Comment by Fruitfella** [comment]
bro @karing-sidikalang , susah jelasinnya pake bhs inggris, maklum bhs inggris q jeblok, kalo mau aq jelasin pake bhs indo silahkan tulis pertanyaannya yg jelas di https://github.com/Fruitfella/ROBOT-binary/issues
trims

**Comment by jibran02** [comment]
i need your help as i am new to these bots but trying to make bot that get tick list of digit percentage then purchase the highest percentage prediction for even or odd. plz help
![tick list](https://user-images.githubusercontent.com/35220497/34669097-f3c3ae3e-f491-11e7-9655-d63171a290dd.jpg)
