### ISSUE TITLE
Please help me. with this line in the bot. weeks trying and nothing ...

### ISSUE THREAD

**Issue by bkan-jp** [binary-com/binary-bot#2272]
martingale 6.80 win 2.78 ... next bet would be 0.35 but no reset to 0.35 ..

how do i so it doesn't stay in that loop.
ex
1 - gained in martingale.
2 - it should go back to 0.35 .. but it didn't happen.
how could i for this loop. I've tried everything and nothing right.

before you think I'm just sucking on information.
I've been trying for weeks without whispering.
when martingale hit the serum bug ..
Thank you very much in advance.
![bkan4](https://user-images.githubusercontent.com/55218772/71483418-8b39be00-27e6-11ea-8d5b-5dcd1098b157.PNG)

[X 3 imferior.zip](https://github.com/binary-com/binary-bot/files/4003037/X.3.imferior.zip)

@navneetsinh
@anton-binary
@binary-ex-machina

**Comment by navneetsinh** [comment]
@bkan-jp , try to change some setups

![Opera Snapshot_2019-12-27_004342_bot binary com](https://user-images.githubusercontent.com/42480287/71487553-07152400-2842-11ea-8371-d7017f8d9bc6.png)

**Comment by bkan-jp** [comment]
@navneetsinh 

> @ bkan-jp , tente alterar algumas configurações
> 
> ![Opera Snapshot_2019-12-27_004342_bot binário com](https://user-images.githubusercontent.com/42480287/71487553-07152400-2842-11ea-8371-d7017f8d9bc6.png)

Thank you for your help.
see that your image .. wants 0.35 loss .. and martingale 1.33 gain 0.54 .. plus it continues with martingale.
Note: when you see gain in matigale it should return to 0.35 ..

see your image .. loss at 0.35 ok
ex: 0.35 -1.33 - 1.87 - 2.63 ....

right would be ... loss at 0.35 ok
ex: 0.35 -1.33 - 0.35 - 0.47 ...... ....

**Comment by bkan-jp** [comment]
@navneetsinh
![bkan5](https://user-images.githubusercontent.com/55218772/71491186-e8953580-280d-11ea-9746-e1b5274fdb18.PNG)

try here without success ..

**Comment by navneetsinh** [comment]
@bkan-jp try this one
![Opera Snapshot_2019-12-27_185953_bot binary com](https://user-images.githubusercontent.com/42480287/71518918-33c94a00-28db-11ea-872c-edcc3a6fe648.png)

**Comment by bkan-jp** [comment]
thank you so much for helping @navneetsinh.
the bot was perfect ..
I am so happy. It comes from such a headache. 
in the end solved. thank you my friend...
