### ISSUE TITLE
Como Posso fazer para identificar que a vela anterior foi fechada, para que eu possa fazer uma entrada no mesmo sentido da vela anterior?

### ISSUE THREAD

**Issue by gustavolima2019** [binary-com/binary-bot#2273]
Gostaria se saber como bot pode identificar a a vela anterior acabou de fechar verde, e entrar logo em seguida com call

**Comment by binary-ex-machina** [comment]
sim, pode fazer da forma abaixo

![image](https://user-images.githubusercontent.com/34610787/72115290-53259580-3325-11ea-8270-730b2acdaf6f.png)
