### ISSUE TITLE
Need Help on barrier error 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2274]
Hello @wilburforce83 

I am testing your bot can please let me know how is the probability of success rate. I am getting below error i am still investigating why it is getting .

 can you help me on it or please any one have look into it and help us. 

bot generating barrier error while trend is on CALL ..

[Final CCI Trending Bot v2.zip](https://github.com/binary-com/binary-bot/files/4005420/Final.CCI.Trending.Bot.v2.zip)

![image](https://user-images.githubusercontent.com/32416314/71519264-c6072900-28ae-11ea-9ef0-170e2681bce4.png)

**Comment by wilburforce83** [comment]
Hi there, this is likely an issue with the barrier being too big to have a profitable return on the market chosen.

If you go to webtrader on binary.com you can see the barrier returns and set the level to a point that is profitable. I hope that helps!!

**Comment by muroyal** [comment]
The Put operations are working fine with out error only for calls direction getting error.
