### ISSUE TITLE
Bot keeps stopping after 40min

### ISSUE THREAD

**Issue by dcbgu255** [binary-com/binary-bot#2276]
Hello I have a Digit Differs 2 XML bot file that needs help with amending the timing as the bot keeps stopping after 40min and want it to continue.

[Digit Differs 2.zip](https://github.com/binary-com/binary-bot/files/4007094/Digit.Differs.2.zip)

**Comment by hotmatrixx** [comment]
Try it (with Demo Money, not real) on Syntheitc indecies and see if it still stops?
mine always work on synthetic, but always stop at around 40mins-1hour on 'real' forex markets

**Comment by dcbgu255** [comment]
Already tried that as it was on demo version.
