### ISSUE TITLE
Binary não da suporte a erro do sistema!!!

### ISSUE THREAD

**Issue by opstrade** [binary-com/binary-bot#2282]
![image](https://user-images.githubusercontent.com/56803963/71588471-61dba380-2b00-11ea-81ca-e02041f6e8c7.png)

Quando vão resolver isso?
Porque não responderam mas os email de suporte?

**Comment by opstrade** [comment]
![Binary Bot](https://user-images.githubusercontent.com/56803963/71588509-8c2d6100-2b00-11ea-9a4a-374ec749c94c.png)

**Comment by aaron-binary** [comment]
Hey @opstrade,

We're investigating this issue at the moment, I'll get back to you asap.

Regards,
Aaron
