### ISSUE TITLE
Need 20 SMA candle close BLock

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2285]
Can anyone provide blocks for

candle open and close above 20 SMA and 20 EMA.

candle open and close below 20 SMA and 20 EMA.

Call

if Open close above 20 SMA and 20 EMA

Put

Open close Below 20  SMA and 20 EMA

I have additional conditions in including this. 

![image](https://user-images.githubusercontent.com/32416314/71645265-92246d00-2ccd-11ea-890d-9c1c5a40c867.png)

I need below calculations to calculate side ways 

every 2 minutes need to calculate below things 

Sideways=20 SMA+ 20 EMA/2 - 5 SMA value

If sideways <5 

then sideways

**Comment by Kosta92** [comment]
Is sideways:

((20+20)/2)-5
or
20+(20/2)-5
or
(20+20)/(2-5)

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/72114934-fd042280-3323-11ea-99e0-52395ec8bb1b.png)
