### ISSUE TITLE
Binary website error

### ISSUE THREAD

**Issue by ForexJapao** [binary-com/binary-bot#2287]
When I use my bot, it always does all the graphical analysis that was configured, but when it comes to the operation it just stops and this message appears:

The underlying market has fluctuated greatly since you set the contract price. The payout contract has changed in your favor from USD2.16 to USD2.12.

How to solve it?

**Comment by hotmatrixx** [comment]
BUMP
I keep running into a similar error and it stops my bot dead in it's tracks.
But I only get this issue on 'real' Forex markets, and never on synthetics!!!

**Comment by binary-ex-machina** [comment]
@ForexJapao this is happening since some days ago. Try to use durations 1min or above and check if the error persists
