### ISSUE TITLE
last 3 digit odd in sequence, maximum result differ than Zero

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2288]
dear sir, manually, strategy is successful, if last three digit are odd in sequence then 4rth digit will be differ than zero, can you create bot for me.
with best regards.

**Comment by saidforex26** [comment]
may be useful
[digit differs 3digitodd 0differ.zip](https://github.com/binary-com/binary-bot/files/4017506/digit.differs.3digitodd.0differ.zip)
![digit differs 3digitodd 0differ](https://user-images.githubusercontent.com/54820719/71696197-4bc72f00-2def-11ea-8f51-38aa4c543ba5.gif)

**Comment by sohailsb** [comment]
Weldone, and thanks, can you add one more function, prediction change on last digit
trade=odd odd odd,  then prediction=last odd

**Comment by sohailsb** [comment]
> may be useful
> [digit differs 3digitodd 0differ.zip](https://github.com/binary-com/binary-bot/files/4017506/digit.differs.3digitodd.0differ.zip)
> ![digit differs 3digitodd 0differ](https://user-images.githubusercontent.com/54820719/71696197-4bc72f00-2def-11ea-8f51-38aa4c543ba5.gif)

Weldone, and thanks, can you add one more function, prediction change on last digit
trade=odd odd odd, then prediction=last odd
and also add target and stop loss
with best regards

**Comment by saidforex26** [comment]
I have tested the strategy and can make 4x sequential losses


> 
> 
> Weldone, and thanks, can you add one more function, prediction change on last digit
> trade=odd odd odd, then prediction=last odd

I have tested the strategy and can make 4x sequential losses

**Comment by sohailsb** [comment]
> I have tested the strategy and can make 4x sequential losses
> 
> > Weldone, and thanks, can you add one more function, prediction change on last digit
> > trade=odd odd odd, then prediction=last odd
> 
> I have tested the strategy and can make 4x sequential losses

if 3 odd prediction zero in loss then next martingale trade opposite with 3 even prediction 9

**Comment by saidforex26** [comment]
> if 3 odd prediction zero in loss then next martingale trade opposite with 3 even prediction 9

[diferrs 3odd0differ & 3even9differs.zip](https://github.com/binary-com/binary-bot/files/4018427/diferrs.3odd0differ.3even9differs.zip)

**Comment by sohailsb** [comment]
thank you very much

**Comment by sohailsb** [comment]
> > if 3 odd prediction zero in loss then next martingale trade opposite with 3 even prediction 9
> 
> [diferrs 3odd0differ & 3even9differs.zip](https://github.com/binary-com/binary-bot/files/4018427/diferrs.3odd0differ.3even9differs.zip)

I got nice result, can you add function prediction= last digit of 3 odd or 3 even
with best regards.

**Comment by sohailsb** [comment]
thank you very much
