### ISSUE TITLE
Full fledged Strategy  target above 65% win Rate

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2289]
Hello Team,

I have Bot which is customise for forex. I have run the bot on one of Virtual chart got below results. 

Run time 5 hours
number of trades 19 
Win trades 14
Win rate 73%
Average hourly trades 4 to 3 

I am in process to develop new strategy with fully technical condition. 

If any one have good developing Skills please contact me evaroyal84@gmail.com 

![image](https://user-images.githubusercontent.com/32416314/71767412-22fb8280-2f32-11ea-95cb-f58ece5bc935.png)

**Comment by muroyal** [comment]
From 3 hours running below is results and win rate. 

![image](https://user-images.githubusercontent.com/32416314/71779812-dcfcf800-2fdf-11ea-9f3a-1bed26839917.png)

**Comment by alanvito1** [comment]
Man, tem que rodar em conta real pra ver se vai dar certo.

Tenho alguns bots para utilizar e estudar.

Visite minha página para download de novos bots gratuitos.
Visit my librarie for new free bots.

https://github.com/alanvito1/superfree-binary-bot

**Comment by muroyal** [comment]
Thanks
