### ISSUE TITLE
Restart Bot at ...

### ISSUE THREAD

**Issue by neoricalex** [binary-com/binary-bot#229]
Hello all ...

Is there any way to restart bot? Not the "Run again after X seconds". 

What i want to do is telling to the bot not use my balance. As you surely know the bot uses their own balance while the expected profit (or loss) is atteint.

Example:

My balance: US$100
Expected Profit: 50
Stop Loss: 20

Lets say after 100 runs we have US$149.00 and at run 101 the martingale bet is US$19.

If he looses, he looses more than US$20 ( SUM of all looses martingale bets )

So, I want to say to the bot restart each US$20.00 profit (or loss). Like that i minimize the risk.

**Comment by Fruitfella** [comment]
hi @neoricalex .
i dont really get what u mean. blame google translate for that _lol_ .

**Comment by neoricalex** [comment]
Lol

I want to do That:
![sem titulo15](https://cloud.githubusercontent.com/assets/11452141/26330799/131f08c4-3f24-11e7-95a8-2037787ab07f.jpg)

**Comment by neoricalex** [comment]
in others words ...
lets say we set 50 as expected profit. Then the bot Stop when reach 50 and we need restart manually.
i want that the bot do the restart. not me.

**Comment by Fruitfella** [comment]
ah!
then what u need is trailing stop (reset the stoploss when u reach a certain poin).
if that the case, send me ur martingale bot, ill edit ur martingale management. your martingale seems different from mine.
or why dont u change ur stoploss to stop when martingale reach a certain level?
like the bot will stop if u loss 5x in a row. so no mater how much ur profit/loss the bot will only stop when it get 5 loses in a row. then make the target profit 10k _lol_.
its basically not so different from what u want.

**Comment by neoricalex** [comment]
For now i have the standard Martingale2:
![sem titulo16](https://cloud.githubusercontent.com/assets/11452141/26334417/5488e39a-3f3b-11e7-874f-d650a987d3c8.jpg)

But lets imagine that i only have $100. 
I can only set up the expected loss to 50. If he looses the sum of martingale loss is 50 + 25 + 12,5 + 6 ...

However if he reach $20 of profit and he save to the balance, then i can rise the expected loss to 60 ( Because now i have $120 at balance )

you understand what i want to do?

Thanks for youre help :-)

**Comment by neoricalex** [comment]
Need to test more, but i think ive found what im looking for .. 

![0001](https://cloud.githubusercontent.com/assets/11452141/26359754/a7657f44-3fac-11e7-8709-ce67841f03ef.jpg)

**Comment by neoricalex** [comment]
Work like a charm ....

**Comment by komodojo123** [comment]
hello , 
      pls i need help with a digit differ bot , i have a digit differ bot that martingale.  but i want somebody that can help to make some amendment to the bot, once there is a loss  the  bot will wait for like 1-3minutes before making another purchase or there should be a column where i can change the time of purchase after a loss .

**Comment by jozzto5** [comment]
Komodojo Whatsapp me asap...  +260976690674
