### ISSUE TITLE
Can anyone create a bot that trades according to the payout percentage?

### ISSUE THREAD

**Issue by erepspinos** [binary-com/binary-bot#2290]
I want to create a bot that trades when these conditions are met:
1. Payout percentage is greater than 100% 
2. Payout Percentage is equal to 108%

**Comment by hotmatrixx** [comment]
yeah that will never happen, as the payout is NEVER that high unless it's a digit/differs bot and in that case the payout is around 800% but the loss ratio is around 1/10 (900%).

Payouts are always lower than the average expected return. That's the fundamental method of the Broker's income.

**Comment by binary-ex-machina** [comment]
@erepspinos you can get the payout percentage like this 
![image](https://user-images.githubusercontent.com/34610787/72114488-6edb6c80-3322-11ea-9825-0efe68ea3d42.png)

Like @hotmatrixx wrote above, on synthetic indexes the payout are below average return. You can get payouts above 100% only in forex pairs
