### ISSUE TITLE
Ayuda con bot de digit differ

### ISSUE THREAD

**Issue by yusnel12** [binary-com/binary-bot#2291]
Necesito ayuda para crear una función que tome de la estadísticas del ultimo dígito el de menor porciento en los últimos 50 intervalos y ese sea la predicción para numero diferente. Gracias
![Sin título](https://user-images.githubusercontent.com/59448766/71742031-6d93d680-2e2e-11ea-8fea-766ae6ec24d7.jpg)

**Comment by binary-ex-machina** [comment]
check here https://gist.githubusercontent.com/Fruitfella/ab019eedc64c2c525adfcc9900b99413/raw/abd0050418294f21e90e3993f6a1e47a316681f3/FRUITFELLA's_LD_Analyzer_ver.2.0.xml

![image](https://user-images.githubusercontent.com/34610787/72114295-d644ec80-3321-11ea-8ce3-e11b71c75df7.png)
