### ISSUE TITLE
please add martingale, stop loss and target profit

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2293]
please add martingale, stop loss and target profit
with best regards 
[project.zip](https://github.com/binary-com/binary-bot/files/4021535/project.zip)

**Comment by Malithwadu** [comment]
![Screenshot (90)_LI](https://user-images.githubusercontent.com/58516489/71760197-a17b0480-2edf-11ea-840a-a16fa8461cd4.jpg)
this is completely bad. isn't it? can you remove this gap? it may be good.

**Comment by sohailsb** [comment]
thanks
