### ISSUE TITLE
i am successful trader, i want other copy me free of cost

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2294]
i am successful trader, i want other copy me free of cost,
can any body help me, others copy my trades.
with best regards.

**Comment by sohailsb** [comment]
closed

**Comment by eonuoha30** [comment]
We don't even know if you are trading on oranges or mangoes. Yet, you want us to copy you.

Blindly risking hard earned money.

**Comment by alanvito1** [comment]
Em meio multidões eis que alguém se dispõe a ajudar, tenho alguns robôs para quem quiser aprender com engenharia reversa, só observar e aprender, esta é minha contribuição!

Visite minha página para download de novos bots gratuitos.
Visit my librarie for new free bots.

https://github.com/alanvito1/superfree-binary-bot
