### ISSUE TITLE
Digit Under

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2299]
the robot will not stop when tp is reached
[Files.zip](https://github.com/binary-com/binary-bot/files/4023055/Files.zip)

**Comment by alanvito1** [comment]
Olá, tenho alguns robôs na minha biblioteca, se quiser testar ou estudar, fique a vontade.

Visite minha página para download de novos bots gratuitos.
Visit my librarie for new free bots.

https://github.com/alanvito1/superfree-binary-bot

**Comment by saarsalu** [comment]
> Olá, tenho alguns robôs na minha biblioteca, se quiser testar ou estudar, fique a vontade.
> 
> Visite minha página para download de novos bots gratuitos.
> Visit my librarie for new free bots.
> 
> https://github.com/alanvito1/superfree-binary-bot

tanx mate i downloaded already them tanx

**Comment by ceakuk** [comment]
here it is.
however takeprofit=1 and stoploss =-60 is crazy
i added a line to make sure the stoploss is never exceeded.
usually say your loss is 59$ and stoploss is 60$ a new trade will be oppened and if your last trade was 60$ then with martingale you could open  say 120$ trade. if you loose then the total loss =59+120 =178$

so the line i added makes sure if you already lost 59$ then the next trade is 1$ max.

[binary-bot - 2020-01-05T132155.203.xml.zip](https://github.com/binary-com/binary-bot/files/4023777/binary-bot.-.2020-01-05T132155.203.xml.zip)

**Comment by saarsalu** [comment]
> here it is.
> however takeprofit=1 and stoploss =-60 is crazy
> i added a line to make sure the stoploss is never exceeded.
> usually say your loss is 59$ and stoploss is 60$ a new trade will be oppened and if your last trade was 60$ then with martingale you could open say 120$ trade. if you loose then the total loss =59+120 =178$
> 
> so the line i added makes sure if you already lost 59$ then the next trade is 1$ max.
> 
> [binary-bot - 2020-01-05T132155.203.xml.zip](https://github.com/binary-com/binary-bot/files/4023777/binary-bot.-.2020-01-05T132155.203.xml.zip)

tanx mate
