### ISSUE TITLE
How to make a list?

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#230]
Hi @aminmarashi @okovalov
could u guys help me?
i want to make a new list with items from another list, but i want skip some items.
lets say in **Thick list** 30th from end to the last, i want to take the 1st from end, 4th from end, 7th from end, 10th from end,..., 28th from end and put them into a new list.

also, is there a way to make a list of **Entry value** or **Exit value**?

_thx_

**Comment by aminmarashi** [comment]
Here you go:
<img width="614" alt="screen shot 2017-05-23 at 9 55 33 am" src="https://cloud.githubusercontent.com/assets/6560964/26335389/048f1996-3f9e-11e7-9f3f-97dbbb34d57e.png">
The blocks:
[Select elements from another list.xml.zip](https://github.com/binary-com/binary-bot/files/1020688/Select.elements.from.another.list.xml.zip)

**Comment by Fruitfella** [comment]
Thank you @aminmarashi 👍
