### ISSUE TITLE
please offer me for bot price? bid

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2303]
Happy new year trader, dreamer , gambler.
Started streaming on Jan 3, 2020
https://www.youtube.com/channel/UCHuFagPAEDTRZOF04e5RgBQ/live
If i want to sell how much u offer me?
https://youtu.be/D-YvuzDsAH0

**Comment by ZDEGLET** [comment]
сколько времени работает робот?

**Comment by saarsalu** [comment]
> Happy new year trader, dreamer , gambler.
> https://www.youtube.com/channel/UCHuFagPAEDTRZOF04e5RgBQ/live
> If i want to sell how much u offer me?

Wath r selling. First show how it will trade in real acount not demo

**Comment by hotmatrixx** [comment]
This is more a forum for discussing bugs, strategies, as well as overcoming coding issues and limitations.
This is not the place to sell your wares.

The truth is, that if it worked, you would protect it, not sell it.

**Comment by ZDEGLET** [comment]
100$

**Comment by saarsalu** [comment]
> 50$
hahaah for bot wath is trading il demo.

oo i can sell for you tons of demo bots 🗡

**Comment by binary-ex-machina** [comment]
@aaron-binary check here, maybe he is trying to sell something
