### ISSUE TITLE
can anyone here help me with ui.vision

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2306]
it's not related to the Binary Bot but maybe someone can help me?

is there a possibility that the macro is constantly watching for a place and if it sees what is needed then it will make the next moves.

now i have to start the macro myself every time.

i need the macro to work all the time. the macro starts to find the image and then does it with 4 clicks.
and then I have to keep looking for myself when I start the macro again.

i need the macro to watch for a certain place for me and if for example a number appears there the macro will do its 4 clicks again.

and so constantly 24.7
my macro is here

{
"Name": "sjdkjs",
"CreationDate": "2020-1-6",
"Commands": [
{
"Command": "visualVerify",
"Target": "vUB90b_dpi_96.png",
"Value": ""
},
{
"Command": "click",
"Target": "id=summaryStopButton",
"Value": ""
},
{
"Command": "click",
"Target": "id=summaryClearButton",
"Value": ""
},
{
"Command": "XClick",
"Target": "5fzJl4_dpi_96.png",
"Value": ""
},
{
"Command": "click",
"Target": "id=summaryRunButton",
"Value": ""
}
]
}

**Comment by hotmatrixx** [comment]
not even sure what macro you're scripting in: Autohotkey?MacroPro? etc

You're better off going to the forum of the macro, than here.

**Comment by saarsalu** [comment]
> not even sure what macro you're scripting in: Autohotkey?MacroPro? etc
> 
> You're better off going to the forum of the macro, than here.

maybe it is possible to communicate with you by whatsapp or email or telegram

**Comment by saarsalu** [comment]
> not even sure what macro you're scripting in: Autohotkey?MacroPro? etc
> 
> You're better off going to the forum of the macro, than here.

hello again if you could make me such a macro
https://www.youtube.com/watch?v=wsgLeBhHHNQ&t=40s

 then i would be very happy. and believe many others would enjoy this macro.

the only thing is that this macro needs to recognize the winning transaction in order not to move on to the next transaction.

and when the first transaction loses, the macro should move on to the next transaction and recognize again whether there was a win or a loss. as the victory moves back to the first step in the macro. if you lose then move on
