### ISSUE TITLE
100 INDEX STRATEGY 

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2308]
is it possible for the robot.
put in the time when the robot makes transactions.

It's easy to do Open Position (OP) on Index 100, the thing to note is 1.  Trading time Trading time on index 100 is 09.00 GMT until 11.00 GMT and at night is 23:00 GMT until 01.00 GMT. Watch the time of trading, because time will determine your victory. 

2.  Graph Position Carefully observe the position of the graph, the position of the rake at the beginning of your account (at 09:00 GMT or 23:00 GMT), see the position of the chart "The Lowest Valley" on the left. The lowest valley on the left graph should be aligned with the graphic at the end (See picture). If it is parallel, then you are ready to do OP. 

![Capture](https://user-images.githubusercontent.com/30391002/71892062-b0b4b900-3150-11ea-9854-8545a43c465d.PNG)

3.  If the above is fulfilled, then the next is to do OP 

OPEN POSITION TECHNIQUE 
 
To open a position, hereinafter refer to "worm chart" note the following: 
RISE: do the Rise If it happens drastically 2 times so pass through the previous valley, then up slightly. Then do RISE 
 
 
![Capture2](https://user-images.githubusercontent.com/30391002/71892155-f5405480-3150-11ea-95c0-57e677341c7a.PNG)

Notice "Video 100 Rise" 
https://drive.google.com/open?id=1ErindNq06qMJx8FnmninS7kR8SZ26Hfa

FALL: do FALL If it Happens Drastically 2 times so pass through the previous mountain, then down a bit. Then do FALL 

![Capture3](https://user-images.githubusercontent.com/30391002/71892334-55cf9180-3151-11ea-904a-bc9ebb9d8396.PNG)

Notice "Video 100 Fall" 
https://drive.google.com/open?id=1dMSJdJCdMUsjwljD4cqP1-NjTMntF2JO

**Comment by binary-ex-machina** [comment]
@saarsalu almost impossible to get that movement from the first images you sent, since the number of ticks need to be dynamic to get that formation. Based on the videos you shared, it waits 1 tick up after the last tick is the minimum in the last 21 ticks or if the 1 tick down after the last tick is the maximum in the last 21 ticks.

![image](https://user-images.githubusercontent.com/34610787/72114031-1061be80-3321-11ea-91e0-5851259e1d91.png)

**Comment by saarsalu** [comment]
> @saarsalu almost impossible to get that movement from the first images you sent, since the number of ticks need to be dynamic to get that formation. Based on the videos you shared, it waits 1 tick up after the last tick is the minimum in the last 21 ticks or if the 1 tick down after the last tick is the maximum in the last 21 ticks.
> 
> ![image](https://user-images.githubusercontent.com/34610787/72114031-1061be80-3321-11ea-91e0-5851259e1d91.png)

can you share this block wit me

**Comment by saarsalu** [comment]
@binary-ex-machina 


wath is the problem with tish
![Screenshot (35)](https://user-images.githubusercontent.com/30391002/72142856-61e76900-3374-11ea-9994-ad58a9b4baf2.png)
