### ISSUE TITLE
[Localhost] Start with my.xml

### ISSUE THREAD

**Issue by neoricalex** [binary-com/binary-bot#231]
Hi all,

When we are on localhost mode, bot start with main.xml and sidebar.xml. 
I dont want to mess with code, because if there are an update, i will loose my definitions. So, im wondering if there are ... lets say a "easy way", to start the bot on localhost directly with  a specific .xml file and not the standard main and sidebar.xml.

Anyone know?

**Comment by aminmarashi** [comment]
You can save your strategy file and replace it with main.xml.

**Comment by neoricalex** [comment]
Thanks @aminmarashi
