### ISSUE TITLE
% difference between ticks block. Help

### ISSUE THREAD

**Issue by lxxneonxxl** [binary-com/binary-bot#2310]
Dear experts .. help create the block. to calculate the percentage between tick  https://b.radikal.ru/b38/2001/10/21af5e93981e.png

**Comment by hotmatrixx** [comment]
![Capture](https://user-images.githubusercontent.com/49715381/72025651-af64c700-32dd-11ea-9b98-21ef1da68cb6.PNG)


This creates a list with the values for you.
the percentages are stored in a list and are expressed as floating point integers.
they include positive and negative values, depending on whether the tick went up or down. If you only need postiive values, then add the 'absolute' value where ponted to in the picture

Hope this helps you along in your endaevours.
(I haven' run and tested it, I hope my code is good!)

**Comment by lxxneonxxl** [comment]
> ![Захватить](https://user-images.githubusercontent.com/49715381/72025651-af64c700-32dd-11ea-9b98-21ef1da68cb6.PNG)
> 
> Это создает список со значениями для вас.
> проценты хранятся в списке и выражаются как целые числа с плавающей запятой.
> они включают в себя положительные и отрицательные значения, в зависимости от того, повысился или уменьшился тик. Если вам нужны только положительные значения, добавьте «абсолютное» значение там, где указано на рисунке.
> 
> Надеюсь, это поможет вам в ваших трудностях.
> (Я не запускал и не проверял его, я надеюсь, что мой код хорош!)

thank you brother.. to my regret, I had a mistake, but you sent me in the right direction and after some effort, I achieved the result.. thanks for the help

**Comment by lxxneonxxl** [comment]
Hotmatrixx, I had another question.. I hope you can help me or suggest the right direction.. I was able to convert the number of ticks into percentages.. now I need that for the conclusion of the contract conditions were approximately such 0.05% 0.04% 0.03% - - - on decrease and on a turn. and so on.. but to be consistent and with a step of 0.01% I hope you will help me.. I'm still new to this business.. thanks in advance

**Comment by lxxneonxxl** [comment]
Hotmatrixx,
I had another question.. I hope you can help me or suggest the right direction.. I was able to convert the number of ticks into percentages.. now I need that for the conclusion of the contract conditions were approximately such 0.05% 0.04% 0.03% - - - on decrease and as on increase. and so on.. but to be consistent and with a step of 0.01% I hope you will help me.. I'm still new to this business.. thanks in advance

**Comment by muroyal** [comment]
@hotmatrixx 

getting error while executing with this block.

![image](https://user-images.githubusercontent.com/32416314/72657804-06018d80-39cf-11ea-856a-27949141b35b.png)

**Comment by lxxneonxxl** [comment]
> 

Hi. So I had this error.. but that put me in the right direction.. I implemented it this way.. let it be noticeable, but I'm learning))))
![screencapture-www-binary-bot-bot-html-1579530720510](https://user-images.githubusercontent.com/57267933/72734492-d60ee180-3baa-11ea-9852-724935dfcc6d.png)
