### ISSUE TITLE
Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2313]
@aaron-binary
can you say were is the problem?

2020-01-09 15:52:40 GMT+0200
Rate limit reached for: buy, retrying in 1.5s
2020-01-09 15:52:42 GMT+0200
Unknown contract proposal
2020-01-09 15:52:44 GMT+0200
Reduce of empty array with no initial value
2020-01-09 15:52:45 GMT+0200
Reduce of empty array with no initial value

![Screenshot (25)](https://user-images.githubusercontent.com/30391002/72040927-bfb37c80-32b2-11ea-9ac3-c86e95b63d0a.png)

![Screenshot (29)](https://user-images.githubusercontent.com/30391002/72076674-9587ac00-32fe-11ea-9e70-5e873ef0766e.png)

**Comment by saarsalu** [comment]
@aaron-binary
can you say were is the problem?

**Comment by aaron-binary** [comment]
Hey @saarsalu,

Could you share the strategy? 

Regards,
Aaron

**Comment by saarsalu** [comment]
> Hey @saarsalu,
> 
> Could you share the strategy?
> 
> Regards,
> Aaron

i can share a robot.

but what caused this error

**Comment by saarsalu** [comment]
> Hey @saarsalu,
> 
> Could you share the strategy?
> 
> Regards,
> Aaron

and now i got error

**Comment by aaron-binary** [comment]
Hey @saarsalu,

I'm unable to reproduce the issue, but it may have to do with the `math_on_list` block, see the screenshot below.

![Screenshot 2020-01-10 at 10 49 56](https://user-images.githubusercontent.com/44427668/72121971-89036200-3397-11ea-8f37-795956319964.png)

Initialising it when first running the bot may fix the issue, see screenshot below:

![Screenshot 2020-01-10 at 10 55 30](https://user-images.githubusercontent.com/44427668/72122053-bc45f100-3397-11ea-8728-cfbff9be444d.png)

The other error `cannot read property 'childNodes' of null` seems to originate from another source, perhaps one of your Chrome addons.

Let me know if that works,
Aaron

**Comment by saarsalu** [comment]
> Hey @saarsalu,
> 
> I'm unable to reproduce the issue, but it may have to do with the `math_on_list` block, see the screenshot below.
> 
> ![Screenshot 2020-01-10 at 10 49 56](https://user-images.githubusercontent.com/44427668/72121971-89036200-3397-11ea-8f37-795956319964.png)
> 
> Initialising it when first running the bot may fix the issue, see screenshot below:
> 
> ![Screenshot 2020-01-10 at 10 55 30](https://user-images.githubusercontent.com/44427668/72122053-bc45f100-3397-11ea-8728-cfbff9be444d.png)
> 
> The other error `cannot read property 'childNodes' of null` seems to originate from another source, perhaps one of your Chrome addons.
> 
> Let me know if that works,
> Aaron

Hei bot is up and running!

I got rid of it
cannot read property 'childNodes' of null.
after all this porridge remained 2
line
![Screenshot (33)](https://user-images.githubusercontent.com/30391002/72136011-8f2d1a80-3366-11ea-9d47-bf8217ab77d3.png)

**Comment by saarsalu** [comment]
> > Hey @saarsalu,
> > I'm unable to reproduce the issue, but it may have to do with the `math_on_list` block, see the screenshot below.
> > ![Screenshot 2020-01-10 at 10 49 56](https://user-images.githubusercontent.com/44427668/72121971-89036200-3397-11ea-8f37-795956319964.png)
> > Initialising it when first running the bot may fix the issue, see screenshot below:
> > ![Screenshot 2020-01-10 at 10 55 30](https://user-images.githubusercontent.com/44427668/72122053-bc45f100-3397-11ea-8728-cfbff9be444d.png)
> > The other error `cannot read property 'childNodes' of null` seems to originate from another source, perhaps one of your Chrome addons.
> > Let me know if that works,
> > Aaron
> 
> Hei bot is up and running!
> 
> I got rid of it
> cannot read property 'childNodes' of null.
> after all this porridge remained 2
> line
> ![Screenshot (33)](https://user-images.githubusercontent.com/30391002/72136011-8f2d1a80-3366-11ea-9d47-bf8217ab77d3.png)

again shame shit 
![Screenshot (36)](https://user-images.githubusercontent.com/30391002/72144082-aa078b00-3376-11ea-92f0-945cb5bd3c5d.png)
![Screenshot (37)](https://user-images.githubusercontent.com/30391002/72144083-aa078b00-3376-11ea-8ff6-aa8e018f8766.png)

**Comment by aaron-binary** [comment]
Hey @saarsalu,

The `math_on_list` block (the block in below screenshot) uses JavaScript's reduce in the background. Reduce doesn't work on an empty array (or list) which causes this error. Perhaps you could implement a check to see if the array (or list) is empty before attempting to trade.

![Screenshot 2020-01-10 at 10 49 56](https://user-images.githubusercontent.com/44427668/72121971-89036200-3397-11ea-8f37-795956319964.png)

Regards,
Aaron
