### ISSUE TITLE
5-Minute Killer Forex Binary Options Trading Strategy

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2314]
The 5-minute killer binary options trading strategy is a classic scalping system trend-momentum. This method is applicable to indices, commodities and forex market. The timeframes used for this systems are 5 minutes or higher and the expiry time is 3-5 candles.

Indicators:
RSI 9 period, close,
Stochastic (10, 3,3,),
MACD (12, 26,9)
Heiken Ashi,
EMA-Crossover Signal (4, 8),

Call Entry:
The RSI must be above 50-level.
The stochastic must cross upward.
The MACD histogram is greater than the line more aggressive trading option or MACD > 0 more conservative.
Heiken Ashi is color white.
Put Entry:
The RSI must be below the 50-level.
The stochastic must cross downward.
The MACD histogram is less than the line more aggressive trading option or MACD < 0 more conservative.
Heiken Ashi is color red.

Please find attached 
[HKIn main.zip](https://github.com/binary-com/binary-bot/files/4040746/HKIn.main.zip)
 Heiken Ashi candle sample XML..

**Comment by muroyal** [comment]
Kany you please anyone work on it and provide bot to evaroyal84@gmail.con

**Comment by binary-ex-machina** [comment]
you can try like this below. Stochastic indicator you can find in my repository https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#stochastic

![image](https://user-images.githubusercontent.com/34610787/72113656-e2c84580-331f-11ea-8bc6-95ca57d2bd49.png)

![image](https://user-images.githubusercontent.com/34610787/72113670-ee1b7100-331f-11ea-8ade-4be159f463c8.png)

**Comment by muroyal** [comment]
I have prepared Bot can any one test it .. 
[Killer_HA V1.zip](https://github.com/binary-com/binary-bot/files/4043570/Killer_HA.V1.zip)

**Comment by amrmenam** [comment]
@muroyal @binary-ex-machina send me pls amrworld1@gmail.com Thanks

**Comment by muroyal** [comment]
I have prepared Please find attached and test and post the results. 
[Chanikya_haki_v1.0.zip](https://github.com/binary-com/binary-bot/files/4049122/Chanikya_haki_v1.0.zip)

**Comment by amrmenam** [comment]
> I have prepared Please find attached and test and post the results.
> [Chanikya_haki_v1.0.zip](https://github.com/binary-com/binary-bot/files/4049122/Chanikya_haki_v1.0.zip)

bro i have error (given candle is not vaild) . how i can fix it ?

**Comment by muroyal** [comment]
@binary-ex-machina  can you please have look into it..
