### ISSUE TITLE
Digit Differ Strategy need robot

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2316]
X mean= Any Digit
XX mean= same any two digit   and XXX mean= same three any digits,
Strat first trading with   XX Differ X
incase of loss Martingale apply second rule
XXX differ X
After profit apply again on first rule.
With best regards.

**Comment by Kosta92** [comment]
This is a bad strategy which can destroy your account balance really quick. It has been done before many times.

**Comment by sohailsb** [comment]
thanks
