### ISSUE TITLE
Schedule cut off time

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2318]
Can anyone provide me how to configure bot running cutoff time for 10 hours .. . 

The bot should run only 10 hours for the day. Daily 10$ profits need to reset.

**Comment by binary-ex-machina** [comment]
you can try with these blocks below. When you press play it will start counting the seconds. It will trade until it reaches the target profit. After reaching the target, it will wait until the cycle of 10 hours (the counter will add 1 to the variable counter as a tick, that is equal to 2 seconds). When that cycle completes (10 hours), it will reset the counter, reset the profit counter (dailyProfit) and will start trading again, repeating the cycle.

![image](https://user-images.githubusercontent.com/34610787/72231538-cbe15780-359a-11ea-9e83-30e10ecbe576.png)

**Comment by muroyal** [comment]
How to set the same block with hourly 1$ profit. i think need to replace 10 to 2  @binary-ex-machina

**Comment by muroyal** [comment]
@binary-ex-machina  i have tried but it is causing tick calculation performance of the bot and performance of the BOT is it possible to calculated on time basis instead of  every tick.

**Comment by hotmatrixx** [comment]
do you want it to run for a max of 10 hours, or for a specific time (eg between 12 and 10pm?)

**Comment by muroyal** [comment]
Trades should be turn off for 4 hours...

From 2:00 am to 6:30 am IST payouts are less and market movements less ...
Probability of failure more..

**Comment by muroyal** [comment]
11:00 pm GMT to 3:00 am

**Comment by hotmatrixx** [comment]
oh well I did this already;

![Capture](https://user-images.githubusercontent.com/49715381/73602137-b7a9dc80-45d3-11ea-87f8-f960edbae308.PNG)

**Comment by hotmatrixx** [comment]
i HAVEN'T TESTED IT:

set your time to start and number of hours to run in the Run Once At Start.

**Comment by hotmatrixx** [comment]
code uploaded to:
https://github.com/hotmatrixx/binary.com.public/tree/master/scripts

**Comment by muroyal** [comment]
Great ! Thanks You Sir !!

**Comment by muroyal** [comment]
the time is not changing.  I think the current time variable should b global. I have changed it like below please review ... ...  

![image](https://user-images.githubusercontent.com/32416314/73612764-784fb000-4614-11ea-9d6e-6a0ad989afbf.png)

**Comment by muroyal** [comment]
@hotmatrixx 

Seconds run variable showing undefined

![image](https://user-images.githubusercontent.com/32416314/73613006-2cead100-4617-11ea-8aa1-b778e1b06b39.png)
 

![image](https://user-images.githubusercontent.com/32416314/73612994-1a709780-4617-11ea-9e90-23fbc0819f4a.png)
