### ISSUE TITLE
unable martingale

### ISSUE THREAD

**Issue by karing-sidikalang** [binary-com/binary-bot#232]
i need help,

after modified my bot, it can not did martingale...and also i want the open position/purchase break for 60 seconds after loss. would someone help me please..here is my bot

![rf](https://cloud.githubusercontent.com/assets/28832596/26519617/f2456e6e-42f6-11e7-8610-322cb03f7533.jpg)

**Comment by neoricalex** [comment]
Hi @karing-sidikalang ,

Im not at home, tonight i see more in depht if i can help. however try to put youre "Run After X seconds" inside a "If do" block, outside  "If result is Win" block.

**Comment by karing-sidikalang** [comment]
@neoricalex  still didnt work.....ok, let me delete Run after X seconds... how is the martingale?

**Comment by Fruitfella** [comment]
dude @karing-sidikalang 
just dump ur martingale, the take my martingale <a href="https://gist.github.com/Fruitfella/eca0b3937c06b527e39a7e4d89ca9223">here</a>
set it just like the pict below, i made the setting according to ur bot.
![martingale-for-jos](https://cloud.githubusercontent.com/assets/26277327/26522956/ef0bd47e-4335-11e7-96cc-422c5d53f7d1.PNG)

good luck!

**Comment by karing-sidikalang** [comment]
thanks.. u r great

**Comment by neoricalex** [comment]
Hey ! You forgot the "Trade Again" inside youre "Run after" block LOL that why doesnt work ^.^

**Comment by Fruitfella** [comment]
@neoricalex @karing-sidikalang I just notice that i made mistake on that martingale bot. I really careless and made mistakes a lot _lol_.
but i already fixed it, its works great now. please <a href="https://gist.github.com/Fruitfella/eca0b3937c06b527e39a7e4d89ca9223">redownload</a>

**Comment by stockholmboy** [comment]
@karing-sidikalang can u send the .xml file? thnks
