### ISSUE TITLE
martingale

### ISSUE THREAD

**Issue by Rover1953** [binary-com/binary-bot#2320]
Please help set up the martingale so that it works immediately after a miss, but only the specified number of steps

**Comment by ZDEGLET** [comment]
где робот? я что у себя настраивать буду?

**Comment by Rover1953** [comment]
Вот робот, пожалуйста

пт, 10 янв. 2020 г. в 20:09, Zdeglet <notifications@github.com>:

**Comment by ZDEGLET** [comment]
у меня твой аккаунт не открывается.  шли на почту zdeglet@gmail.com

**Comment by ZDEGLET** [comment]
ПРИШЛИ ФАЙЛ РОБОТА НА ПОЧТУ zdeglet@gmail.com

**Comment by Kosta92** [comment]
You can get it from user FRUITFELLA. Here is the link: https://github.com/Fruitfella/ROBOT-binary

**Comment by Rover1953** [comment]
Please let me know how to download or upload the block FRUITFELLA's
CROSS-Lines.


вт, 28 янв. 2020 г. в 04:20, Aaron <notifications@github.com>:

**Comment by Rover1953** [comment]
Please let me know how to download or upload the block FRUITFELLA's  CROSS-Lines
