### ISSUE TITLE
How to set bot with license with expire time and trading limit? 

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2326]
How to set bot with license with expire time and trading limit? 
want to inject my XML file to exe.. or xml with license with expire time?
how to do that? 
thank you

**Comment by virtusasys** [comment]
please help.. singithiml@gmail.com please contact me

**Comment by ZDEGLET** [comment]
ТЫ НЕ ПЕРВЫЙ КТО ЭТО ХОЧЕТ.

**Comment by ceakuk** [comment]
im also interested in that. i have great bots but i live in Eu so I can not trade with them. 2 years of hard work daily.

**Comment by trident2005** [comment]
You can not put any passwor or licence key on .xml scrypt
