### ISSUE TITLE
Webhook block regards

### ISSUE THREAD

**Issue by ArunGowthamm** [binary-com/binary-bot#2327]
Please advice on WEBHOOK blocks..

How to use the block...which url and website does it support

Which type of data will it retrieved by payload block

**Comment by aaron-binary** [comment]
Hey @ArunGowthamm,

Unfortunately we don't have any documentation on this (yet), but it would work just like any other webhook you'll find on the web. The block allows you to send a JSON payload to any endpoint on the web, what the endpoint does with that payload is up to them.

- Please note that the receiving endpoint must have the `Access-Control-Allow-Origin` header set, and must allow requests from either the Binary domains or any domain. Please see https://stackoverflow.com/a/10636765 for more information.

Whenever the block is executed, a request is made to the URL that you supplied in the **Webhook URL** input, it will **POST** the payload in JSON format. I've uploaded an example strategy below that uses a third-party service to allow CORS requests to be made anywhere. **Please make sure you're using this on your demo account.**

-  Download the strategy here: https://gist.github.com/aaron-binary/1e99451016f86fb0a1afcac087cd7eb0

The strategy will prompt you with a message saying **Please visit https://webhook.site/ and paste the generated URL below:**, please follow those instructions. https://webhook.site/ is a website that allows you to test your webhooks. An example payload from the strategy is:

```JSON
{
  "Result: ": "Win! :-)",
  "profit": 0.96,
  "contract_type": "CALL",
  "entry_spot": "02:23:30",
  "entry_value": 1049.9801,
  "entry_value_string": "1049.9801",
  "exit_spot": "02:23:40",
  "exit_value": 1050.3781,
  "exit_value_string": "1050.3781",
  "barrier": 1049.9801,
  "payout": 1.96,
  "result": "win",
  "ask_price": 1,
  "statement": 138776934208
}
```

Please let me know if you have any other questions.

Regards,
Aaron

**Comment by ArunGowthamm** [comment]
@aaron-binary 

Thanks for your support Bro.
