### ISSUE TITLE
Help to create a new Money Management

### ISSUE THREAD

**Issue by trident2005** [binary-com/binary-bot#2328]
Regards

I was thinking about money management but I have no idea how to materialize it.

Is it possible to emulate fake operations?, I explain to you, when the strategy sends a signal, a real operation does not open but a notification is issued, for example, but that the algorithm is able to keep a count of how many of those fakes operations would have been lost and from this count determine the entry of real operations in martingale.

Grateful for your attention.

**Comment by ZDEGLET** [comment]
ВКЛЮЧИ ДЕМО СЧЕТ, СКАЧАЙ АНАЛИЗ В EXCEL И ДЕЛАЙ ВЫВОДЫ.

**Comment by trident2005** [comment]
I have executed this type of operability manually, I would like to automate it to see if it works in the long term

**Comment by lxxneonxxl** [comment]
Присоединяюсь к просьбе автора..

**Comment by lxxneonxxl** [comment]
I join the author's request..

**Comment by ZDEGLET** [comment]
Я НЕ ПОНИМАЮ, ЧТО ХОТИТЕ И ЗАЧЕМ ТАКОЙ ГЕМОРОЙ?

**Comment by trident2005** [comment]
When the strategy sends a signal, a real operation does not open but a notification is issued, for example, but that the algorithm is able to keep a count of how many of those fakes operations would have been lost and from this count determine the entry of real operations in martingale.
