### ISSUE TITLE
Candle analyse Alternate bot

### ISSUE THREAD

**Issue by Agentsbu** [binary-com/binary-bot#233]
Hi Fella
![binary bot](https://cloud.githubusercontent.com/assets/26632197/26524320/a25769dc-432f-11e7-8b41-cc6e4cf52a01.png)

1. when Candle purchase fall, after 1 loss, wait Rise purchase.
![binary bot 1](https://cloud.githubusercontent.com/assets/26632197/26524341/31dc06ee-4330-11e7-9b63-d7e5f0e8d66a.png)
What  am i doing wrong because even after it lose, it doesn't change to alternate.

**Comment by neoricalex** [comment]
Hu @Agentsbu , the contract type need to be CALL or PUT. You have the Market:

![a25769dc-432f-11e7-8b41-cc6e4cf52a01](https://cloud.githubusercontent.com/assets/11452141/26524469/54b0cc12-4309-11e7-8586-ce66b2af3f49.jpg)

**Comment by Agentsbu** [comment]
![binary bot](https://cloud.githubusercontent.com/assets/26632197/26524516/243f4d0c-4335-11e7-9905-f10bf5641c68.png)
It doesn't work, I even tried it on Even Odd

**Comment by neoricalex** [comment]
Try like that ...

IF result loss
do:
1) Martingale
2) youre wait system
3) If wait 0 and 1 do trade again

**Comment by Agentsbu** [comment]
I don't understand

**Comment by Fruitfella** [comment]
This is the problem @Agentsbu 
![error](https://cloud.githubusercontent.com/assets/26277327/26524570/46fbc81c-4361-11e7-9006-f8d2e155e654.png)

nice jacket @neoricalex 👍

**Comment by Fruitfella** [comment]
![error](https://cloud.githubusercontent.com/assets/26277327/26524584/eebe8044-4361-11e7-8c0f-0f4c0db90161.png)

**Comment by Agentsbu** [comment]
![binary bot 1](https://cloud.githubusercontent.com/assets/26632197/26524610/42234ea0-4339-11e7-8685-0750e701a914.png)
I TRIED TO FIX IT AGAIN BUT ITS STILL THE SAME

**Comment by neoricalex** [comment]
The other Trade again also. You are telling to the bot trade no matter is the wait. So, if there are a loss, if example the 0 is true, the bot will trade because 0 is different of 2. im wrong here?

**Comment by Agentsbu** [comment]
LEMME CHECK

**Comment by Fruitfella** [comment]
show me ur complete blocks, i dont understand why u attached pics of 2 different bots.

**Comment by Agentsbu** [comment]
GReat, I think its working now. I removed the trade again button, and I see some changes.

**Comment by Fruitfella** [comment]
i post that **Trade Again** problem was 20 minutes ago, and u just delete it now? oh my

**Comment by Agentsbu** [comment]
![binary bot 2](https://cloud.githubusercontent.com/assets/26632197/26524676/60a5e3c2-433b-11e7-8af6-d4ba41e89649.png)

**Comment by Agentsbu** [comment]
LOL @Fruitfella

**Comment by Agentsbu** [comment]
THANKS GUYS, ITS WORKING !!!!!!!!

**Comment by Fruitfella** [comment]
no probs ;-)

**Comment by neoricalex** [comment]
Dont forget to close this topic ... have Fun!

**Comment by okovalov** [comment]
@Agentsbu "dont forget to close the topic"
