### ISSUE TITLE
statistics of the number in red

### ISSUE THREAD

**Issue by claytonliotti** [binary-com/binary-bot#2331]
hello is it possible to get the statistics of the number in red

![image](https://user-images.githubusercontent.com/44580787/72479201-86a76a80-37d2-11ea-8307-6b9bcabd6528.png)

**Comment by ZDEGLET** [comment]
да!!! что конкретно тебе надо?

**Comment by claytonliotti** [comment]
english please

**Comment by waltergrant** [comment]
https://github.com/Fruitfella/ROBOT-binary

**Comment by hotmatrixx** [comment]
> 
> 
> да!!! что конкретно тебе надо?

You know, when someone posts a request in ENGLISH they probably expect the replies in ENGLISH, not in RUSHKI

**Comment by hotmatrixx** [comment]
hey, @claytonliotti 
My Binary Client doesn't have those stats as an option; but I"m guessing that you want them in the bot, not in the webtrader interface.

What stats are you after exactly? some of them are indeed logged by the bot, and can be found by Parsing their list - but if you let me know what figures you need exactly, I can point you in the right direction.

**Comment by claytonliotti** [comment]
thanks for the feedback
is the low red statistic from the 1000 tick list
in the graph of digits
I attached a print

![image](https://user-images.githubusercontent.com/44580787/72954457-3783ab80-3d77-11ea-922d-ce543d0b633b.png)
