### ISSUE TITLE
Please fix my higher lower

### ISSUE THREAD

**Issue by cunk888** [binary-com/binary-bot#2333]
My higher lower is not work please fix

**Comment by cunk888** [comment]
[Fix.log](https://github.com/binary-com/binary-bot/files/4070991/Fix.log)

**Comment by cunk888** [comment]
![Screenshot_2020-01-16-19-52-44-119_com android chrome](https://user-images.githubusercontent.com/59736310/72522984-cab17280-3899-11ea-83f5-786ae9c80c44.png)

**Comment by Martinez222** [comment]
Try this :
![hi-low](https://user-images.githubusercontent.com/39260368/72661853-f6427300-39e7-11ea-9497-e42649273287.jpg)

**Comment by cunk888** [comment]
Thx mennnn

**Comment by Martinez222** [comment]
No problem,men glad i can help!Next time attach xml file...
:)
