### ISSUE TITLE
how to create bot using this strategy 

### ISSUE THREAD

**Issue by amrmenam** [binary-com/binary-bot#2335]
![Capture](https://user-images.githubusercontent.com/10170656/72559381-55e83380-38ad-11ea-83fc-3f98db302070.PNG)

how to create bot do rise if ema 20 or 50 or 100 or 200 or bollinger period 20 dev 2.5 (upper) or bollinger period 20 dev 3.5 (upper) and closed candle inverted hammer green
and same idea in the picture

**Comment by Martinez222** [comment]
Here you go  ,but with that bollinger deviation you will receive very few trades..
[BB star_2.zip](https://github.com/binary-com/binary-bot/files/4078327/BB.star_2.zip)

**Comment by amrmenam** [comment]
@Martinez222 thanks bro . can you give me your email ?

**Comment by Martinez222** [comment]
U are welcome!
sexxy_martinez@yahoo.co.uk
