### ISSUE TITLE
BINARY BOT KEEPS STOPPING WHEN ATTEMPTING BUY

### ISSUE THREAD

**Issue by esperanda01** [binary-com/binary-bot#2336]
I NOTICED SOMETHING RECENTLY. I DONT KNOW WHY MY BOT KEEPS STOPPING/HANGING SOMETIMES WHEN ATTEMPTING A BUY..  
![yyyy](https://user-images.githubusercontent.com/44817486/72594150-0df5fa80-3907-11ea-9aa9-e094f8955a0f.PNG)

FROM THE SCREENSHOT ABOVE IT ATTEMPTED MAKING  PURCHASE AND HANGED THERE. I DONT KNOW WHY.

**Comment by Kosta92** [comment]
It happens a lot because the platform is not 100% stable.

**Comment by ZDEGLET** [comment]
НА ПЛАТФОРМЕ МЕНЯЕТСЯ СТАВКА!!!
