### ISSUE TITLE
Help Me please! 

### ISSUE THREAD

**Issue by Zhdennis** [binary-com/binary-bot#2338]
Hi guys. Please help me understand. There are conditions for buying and selling. After one of the conditions is met, if the forecast is justified, the same conditions remain. If the forecast is not met, you need to choose other conditions for buying and selling.

**Comment by hotmatrixx** [comment]
yes, so what is your actual question?
It sounds like you want to make a bot that has multiple conditions that need to be met before it will place a trade?
