### ISSUE TITLE
Programing issue

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2339]
if volitality 10 spot is: 7609.583
then prediction is first digit after dot, like 5  in this spot
please help me
with best regards

**Comment by hotmatrixx** [comment]
Like this?

![Capture](https://user-images.githubusercontent.com/49715381/72965087-55591b00-3e20-11ea-9132-afbdfcfd4cf4.PNG)

**Comment by sohailsb** [comment]
not working

**Comment by sohailsb** [comment]
not working
