### ISSUE TITLE
Bot with candle

### ISSUE THREAD

**Issue by apaajadehbos** [binary-com/binary-bot#234]
Hi everyone, sorry im new here, and im not a blocker

i have a problem, how to develop my bot with 4 consecutive green and purchase rise and then 4 consecutive red then purchase fall (on the timeline 1 minute)....... can somebody help me please

thanks

**Comment by aminmarashi** [comment]
It should be similar to [this](https://gist.github.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/3%2520same%2520candle%2520colors.xml)
