### ISSUE TITLE
Запрос функции

### ISSUE THREAD

**Issue by lxxneonxxl** [binary-com/binary-bot#2343]
There is a lack of a function for collecting data and exporting it to csv// for example, I want to create a list that will contain information already processed by the robot for further analysis and statistics collection

**Comment by aaron-binary** [comment]
Hey @lxxneonxxl,

You may export your transactions or log in Binary Bot by pressing the floppy icon found in each of the panels. It'll look like the icon in the screenshow below:

![Screenshot 2020-01-20 at 10 18 25](https://user-images.githubusercontent.com/44427668/72694006-4b0ff600-3b6e-11ea-8930-f6a0711ee2a6.png)

In addition, you may use webhooks to send data to an external endpoint. Webhooks allow you to receive data and process them off-site, giving you complete freedom to process that data. You may check issue #2327 for more information.

Regards,
Aaron

**Comment by lxxneonxxl** [comment]
> Привет @ lxxneonxxl ,
> 
> Вы можете экспортировать свои транзакции или войти в Binary Bot, нажав на значок дискеты на каждой из панелей. Это будет выглядеть как значок на скриншоте ниже:
> 
> ![Скриншот 2020-01-20 в 10 18 25](https://user-images.githubusercontent.com/44427668/72694006-4b0ff600-3b6e-11ea-8930-f6a0711ee2a6.png)
> 
> Кроме того, вы можете использовать веб-хуки для отправки данных на внешнюю конечную точку. Webhooks позволяют вам получать данные и обрабатывать их вне сайта, предоставляя вам полную свободу для обработки этих данных. Вы можете проверить выпуск [№ 2327](https://github.com/binary-com/binary-bot/issues/2327) для получения дополнительной информации.
> 
> С уважением,
> Аарон

thanks for the help
