### ISSUE TITLE
RF rise bot Can't Execute purchase,help me fix the logic

### ISSUE THREAD

**Issue by novasugi88** [binary-com/binary-bot#2347]
Sir ,I've tried this logic to purchase after 2nd redhead wormtick on v100,and price change after 2nd redhead wormtick is more then 0.1
help me solve this problem sir  @binary-ex-machina,and to everyone who has mastered binary bot
![IMG_20200121_020332](https://user-images.githubusercontent.com/57997979/72752040-ca93d880-3bf3-11ea-9d4c-ae675fa5d42d.jpg)

**Comment by sohailsb** [comment]
send me the file

**Comment by novasugi88** [comment]
> send me the file
ok sir with pleasure, here it is 
[TNT om jin test.zip](https://github.com/binary-com/binary-bot/files/4090159/TNT.om.jin.test.zip)

**Comment by hotmatrixx** [comment]
That's really, really cool. it looks awesome, visually, but the truth is that both the "IF=True" and the AND blocks are broken.
Your logic might be perfect, but if you have and AND statement in it, the bot will freak out and not work correctly a lot of the time.

It will also freak out if you don't add an "= true" block atthe end of an IF statement and simply imply 'true'.

In other words, you may need to break this down, by making each statement into a "If True Then..." and making that tick a variable, then later checking if  all those variables are true.
I realise your code is really compact and looks nice in it's own way (I'd ahve used a function, but hey).
But the bot doesn't like it.
You're better off to 'nest' multiple "IF" statements
here is a simple example
![Capture](https://user-images.githubusercontent.com/49715381/72965486-4b83e780-3e21-11ea-9967-18334959b16e.PNG)

**Comment by novasugi88** [comment]
Thanks sir for your answer,thats really helpful,also there are many block which I don't understand yet,how to use it,and I've no background in programming,so I can't simplify the logic to make it work efectivly and looks compact,do you have any eferences to learn binary bot block ?

**Comment by hotmatrixx** [comment]
I'm currently doing a series of youtube videos; beginning with what each block is, and I'll move onto deeper things like programming and bugfixing eventually.

I'm making the tutorials up as I go along, and I'm releasing a couple a day...
Here.

Please tell me what you do/don't like so I can improve them in the future.

https://www.youtube.com/playlist?list=PLyJwiVv5enme2TbXs3wyqlTSq5cDP7Y-G
