### ISSUE TITLE
{BUG?} Payout (Rising / Falling) function has changed

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2350]
This Block:
![Capture](https://user-images.githubusercontent.com/49715381/72843264-0cf60c00-3cff-11ea-9fb8-923ca08d1a04.PNG)

USED to give me the actual payout as a fractional representation of that ratio. IE if my stake was $5 and my potential profit was $4 this function would output "0.8"

NOW it returns my stake+potential payout ($9)

Do you realise how destructive that has been to my bots? It almost cost me a fortune.
It DID cost me 2 days in hair pulling, trying to figure out why my 'bets' were all over the place, and much, much lower than I expected them to be. (this particular bot has a LOT of functions.)

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

We haven't changed the type of value that we return (i.e. ratio vs. actual payout), it has always been **Stake + Potential Payout**. The payout itself fluctuates based on the current tick which may have resulted in the values looking off. 

If you would like to dispute a transaction, please contact our customer support team. 

Regards,
Aaron

**Comment by hotmatrixx** [comment]
I'm wondering now.
maybe when I was testing this function the first time if I did it with $1 trades, so the output would look like a ratio

**Comment by hotmatrixx** [comment]
hmmm.
that ratio is important, I thought that there was a function for it;
am I mistaken, or is it somewhere else?

It would certainly make calculating potential winnings for martingales or ladders much, much easier.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

We don't currently have a payout ratio block, but you may calculate it by dividing potential payout by stake i.e. **Ratio = Potential payout ÷ Stake**.

Regards,
Aaron.

**Comment by hotmatrixx** [comment]
![Capture](https://user-images.githubusercontent.com/49715381/72956242-dfdf5180-3e03-11ea-82f6-b9b6cfdfa078.PNG)


Hi Aaron. All respect to you, and yes that's what I'll have to do; however it mean I have to run a dummy trade before I can start using my Money Management strategies, as I can't actually check the Payout until after I've won something.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

You can only use that specific payout-block in the **Before Purchase** scope. There's another block in the **After Purchase** category which may help, which is the **Contract detail** block, this block has a **Payout** option which will yield the payout of the contract. 

You may set this to a variable and use this information in your next trade. 

Personally I don't think it would help to know the payout while a contract is running, but I'm open to your feedback on this.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
> 
> 
> Hey @hotmatrixx,
> 
> You can only use that specific payout-block in the **Before Purchase** scope. There's another block in the **After Purchase** category which may help, which is the **Contract detail** block, this block has a **Payout** option which will yield the payout of the contract. You may set this to a variable and use this information in your next trade.
> 
> Personally I don't think it would help to know the payout while a contract is running, but I'm open to your feedback on this.
> 
> Regards,
> Aaron

Yeah I know about the **Contract: Payout** option. it's really annoying, because if you lose a contract it returns a value of **Zer0**. So if you win, that's fine, but if you lose, then you're trying to find the Ratio via Dividing By Zero. Less cool.

Cheers.
