### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2353]
stratgy:
if last two digit same then prediction same
if trade in profit continue strategy
if trade close in loss
then
trip digit same and preiction last same digit
can anybody create these blocks

**Comment by hotmatrixx** [comment]
Have you learned how to put together your own bacis bots yet?
I need to make a tutorial series.

**Comment by sohailsb** [comment]
> Have you learned how to put together your own basic bots yet?
> I need to make a tutorial series.

i know basics very well, please send me the tutorial, with best regards.

**Comment by xremmy** [comment]
Here you go
[2 and 3 digits analyse Differ.zip](https://github.com/binary-com/binary-bot/files/4104520/2.and.3.digits.analyse.Differ.zip)

**Comment by sohailsb** [comment]
> Here you go
> [2 and 3 digits analyse Differ.zip](https://github.com/binary-com/binary-bot/files/4104520/2.and.3.digits.analyse.Differ.zip)

Million of thanks

**Comment by sohailsb** [comment]
Millions of thanks
