### ISSUE TITLE
Limits for Synthetic Indices

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2354]
Can anyone share here the hourly and daily limits for all Synthetic Indices (including the new 1s ones)?

**Comment by hotmatrixx** [comment]
yeah there is a new limit on them that's popped up in the last couple of days.

I'm not sure what it is, because it's new.
 there are other problems, also - using genuine forex markets locks my bot up completely. 3 minute trades are taking 10 minutes to close, then after about 5 trades my browser locks up to the point where I can't even refresh the tab, I have to close it.

**Comment by hotmatrixx** [comment]
> 
> 
> Can anyone share here the hourly and daily limits for all Synthetic Indices (including the new 1s ones)?

I can't test it, because I actually use my bot every day, but I think it's around 500 calls in a 24h period.
That's pretty much the equivelent of placing a trade every 3 minutes for 24h.

 (24*60/3=480)

**Comment by aaron-binary** [comment]
Hey @Kosta92,

You may check this page https://developers.binary.com/api/#website_status and press **Send request**. Then search for `api_call_limits` and you'll find the answer. Afaik they're not bound to any underlying, but rather global limits (i.e. apply to all underlying). Here's the output:

```JSON
"api_call_limits": {
      "max_proposal_subscription": {
        "applies_to": "subscribing to proposal concurrently",
        "max": 5
      },
      "max_requestes_general": {
        "applies_to": "rest of calls",
        "hourly": 14400,
        "minutely": 180
      },
      "max_requests_outcome": {
        "applies_to": "portfolio, statement and proposal",
        "hourly": 1500,
        "minutely": 25
      },
      "max_requests_pricing": {
        "applies_to": "proposal and proposal_open_contract",
        "hourly": 3600,
        "minutely": 80
      }
```
