### ISSUE TITLE
bot is locking up after internal build update

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2355]
using genuine forex markets locks my bot up completely. 3 minute trades are taking 10 minutes to close, then after about 5 trades my browser locks up to the point where I can't even refresh the tab, I have to close it.

The bot also locks up for around 3 minutes after a synthetic 1m market purchase, now.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

I'm not sure what you mean by internal build update, the last release was last December 12th. Please see https://github.com/binary-com/binary-bot/releases for more details. Your bot locking up may have to do with your strategy performing complex calculations.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
that's awesome except it says that all your releases have been on the 12th

oh, and I get this almost every couple of days

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

You're right, it's a bit confusing. We changed the release process around that time so it looks like all releases were done on December the 12th, for previous releases, for a more detailed overview please see https://github.com/binary-com/binary-bot/commits/gh-pages.

Those messages have to do with backend maintenance, they shouldn't affect how the bot is running. It would help if you could share your strategy so we can analyse what may be happening here. You can upload it to https://gist.github.com and post the link here.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
I appreciate that gaining the strategies is important in trying to discover what's going wrong. I'm sure you also appreciate that those of us with consistently winning Strategies are also very protective of them, so as much as I want to share the bot, I don't want to reveal my secrets.

I will try and break my bot down and see if it still has this 'fail' - and send that to you. If it then starts working, then that might help us figure out where we are going wrong, too.

Also that bot is 370KB - it's basically massive, with 27 separate conditional functions - yet it tends to fail on the actual Close - it buys, waits 3 minutes, then doesn't move to block 4 (I made a bugreport notification on block 4 to test this)

importantly, I mentioned in the other thread, that I think W10 eco /UWP funcitonali8ty may be affecting it as it happens especially when I'm running some silly little game and leaving the bot on idle in another window

Silly little game = AAA title DOOM2016 - straining my PC a little.
