### ISSUE TITLE
2 ticks up and 3 ticks down Call

### ISSUE THREAD

**Issue by ForexJapao** [binary-com/binary-bot#2358]
Hello, can someone tell me how to do this strategy: If I give two ticks up and then 3 ticks down to open the call order.

**Comment by ForexJapao** [comment]
![TICK](https://user-images.githubusercontent.com/56320282/73043083-792d5880-3e42-11ea-91f7-90b4dc22737b.jpg)

I did it this way, but it didn't work

**Comment by hotmatrixx** [comment]
I did something similar for someone else very recently; I'm going to post THAT bot in here. It's not the strategy that you wanted, but what it will do is give you a fairly straightfowrad bot to look at and dissect, hopefully showing you how to check this.

Importantly, and this may help; these blocks count the last tick's direction - which is what you're trying to do:
![Capture](https://user-images.githubusercontent.com/49715381/73043184-f3a0bb80-3ec8-11ea-8a62-e705e286577d.PNG)
[binary-bot 3 tick up or down.zip](https://github.com/binary-com/binary-bot/files/4106739/binary-bot.3.tick.up.or.down.zip)

**Comment by ForexJapao** [comment]
Thanks buddy ... So I know how to do it, but my strategy is more complicated because it has to be 2 ticks up and 3 ticks down in the sequence ...

**Comment by hotmatrixx** [comment]
I know.
I was hoping i might give you a pointer in the right direction, rather than just do it for you.

here.

[tickup2 tickdown3(1).zip](https://github.com/binary-com/binary-bot/files/4106823/tickup2.tickdown3.1.zip)

**Comment by ForexJapao** [comment]
Thank You Friend 😊😊
