### ISSUE TITLE
Ticks Change To Minutes [QoL]

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2360]
Hey, @aaron-binary 

This occurs in Block1;
One of the things that really annoys me is that if I change my **Market** (eg from AUD/JPY to GBP/USD) or whatever, the **Duration**  (under **Define Trade Options**) switches from _Minutes_ back to _Ticks_.

I understand this happening as a reset if you changed the **Trade** Type, but I feel that minutes should be the default setting, rather than ticks... if possible/practical.

**Comment by ZDEGLET** [comment]
Мне это тоже не нравится. 3 года назад этого не было.

**Comment by hotmatrixx** [comment]
> 
> 
> Мне это тоже не нравится. 3 года назад этого не было.

_I do not like it either. 3 years ago this was not._

Why do you insist on answering threads in Russian? You seem to understand English, yet I have to load up Google Translate (as does eveyone else) just for you.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Yep, we do this cause we default to the first duration when changing symbol or trade types. We're not planning on changing this at this time.

Regards,
Aaron
