### ISSUE TITLE
How I can make my bot autotrade again after "Sell at market"

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2361]
How I can make my bot autotrade again after "Sell at market"
![AAAAAAAAAAA](https://user-images.githubusercontent.com/58647652/73116201-db7e7a00-3f64-11ea-9376-46ec8dfa2c8f.PNG)

**Comment by ZDEGLET** [comment]
бери и делай как все. я на картинке и в вопросе ничего не понял что ты хочешь сделать с 4 или 3 блоком.
