### ISSUE TITLE
Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2367]
![Screenshot (130)](https://user-images.githubusercontent.com/30391002/73134469-99763680-403f-11ea-9f5e-af4f3e8f2ad1.png)

**Comment by aaron-binary** [comment]
Hey @saarsalu,

This usually occurs when you're trying to get a substring of an empty string, or when you're trying to get a sub-list of a list. If you're able to upload your strategy to https://gist.github.com I may be able to locate where the error occurs.

Regards,
Aaron

**Comment by saarsalu** [comment]
> Hey @saarsalu,
> 
> This usually occurs when you're trying to get a substring of an empty string, or when you're trying to get a sub-list of a list. If you're able to upload your strategy to https://gist.github.com I may be able to locate where the error occurs.
> 
> Regards,
> Aaron

Here it is 

https://gist.github.com/saarsalu/fa3ac6b7611445c081d1acae3acb3557

**Comment by aaron-binary** [comment]
Hey @saarsalu,

I had a quick look but couldn't get the strategy to work, my error was `Cannot read property 'currency' of undefined`. I was able to fix that error and then the strategy was running fine, you may find the updated strategy here. https://gist.github.com/aaron-binary/7616bef8c0e48053da5e18bb1acd67bb

Regards,
Aaron

**Comment by UFOvariante** [comment]
> Hey @saarsalu,
> 
> I had a quick look but couldn't get the strategy to work, my error was `Cannot read property 'currency' of undefined`. I was able to fix that error and then the strategy was running fine, you may find the updated strategy here. https://gist.github.com/aaron-binary/7616bef8c0e48053da5e18bb1acd67bb
> 
> Let me know if that helps,
> Aaron

Hi @aaimio, im having the same problem, but your link is not openning, do you have the solution yet?
