### ISSUE TITLE
Virtual Loss

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2369]
Can anyone create virtual loss strategy, if two virtual loss according to strategy then, third time enter for real trade.
with best regards

**Comment by babehdyo** [comment]
yes i can. what kind of trade you want?..

**Comment by sohailsb** [comment]
> yes i can. what kind of trade you want?..

Million of thanks, Digit Differ Strategy

**Comment by babehdyo** [comment]
Give me the logic and i will create it..

> > yes i can. what kind of trade you want?..
> 
> Million of thanks, Digit Differ Strategy

**Comment by sohailsb** [comment]
> Give me the logic and i will create it..
> 
> > > yes i can. what kind of trade you want?..
> > 
> > 
> > Million of thanks, Digit Differ Strategy
3 Digit same Differ

[XXX- Differ X.zip](https://github.com/binary-com/binary-bot/files/4114239/XXX-.Differ.X.zip)

**Comment by babehdyo** [comment]
> > Give me the logic and i will create it..
> > > > yes i can. what kind of trade you want?..
> > > 
> > > 
> > > Million of thanks, Digit Differ Strategy
> > > 3 Digit same Differ
> 
> [XXX- Differ X.zip](https://github.com/binary-com/binary-bot/files/4114239/XXX-.Differ.X.zip)

[XXX- Differ X Virtual Loss.zip](https://github.com/binary-com/binary-bot/files/4114309/XXX-.Differ.X.Virtual.Loss.zip)
Test it. if there's any trouble let me know. i haven't test it because it need a long time to open position..

**Comment by sohailsb** [comment]
OK Bro, i will inform you.

**Comment by trident2005** [comment]
Hello, greetings and grateful for the contribution @babehdyo 

I have a question; This scrypt can really emulate the Vitual Loss with the rules of the server ?, I talk about the request tick, the purchase tick and the closing tick (assuming that the duration of each contract is 1 tick), those trees ticks that are They comply for all contracts on the server.

**Comment by babehdyo** [comment]
> Hello, greetings and grateful for the contribution @babehdyo
> 
> I have a question; This scrypt can really emulate the Vitual Loss with the rules of the server ?, I talk about the request tick, the purchase tick and the closing tick (assuming that the duration of each contract is 1 tick), those trees ticks that are They comply for all contracts on the server.

Do you mean entry value and exit value?. If that' what you mean, than it can be done for virtual loss for ticks value..

**Comment by trident2005** [comment]
@babehdyo  when we are going to buy a contract, the purchase is never immediate, suppose that the duration is 1 tick, we need to go through three steps, 1 step: request, 2 step: purchase and 3 step: closing (the closing is we see them as the between spot and the exit spt)

**Comment by babehdyo** [comment]
> @babehdyo when we are going to buy a contract, the purchase is never immediate, suppose that the duration is 1 tick, we need to go through three steps, 1 step: request, 2 step: purchase and 3 step: closing (the closing is we see them as the entry spot and the exit spt)

i know what u mean. And it can be done...

**Comment by trident2005** [comment]
That would be the true way to establish virtual losses, I have tried to schedule that for a long time but I don't know where to start, to apply it to any strategy, like here 

https://www.youtube.com/watch?v=phXoZCxM_YY&t=766s

**Comment by abukoush** [comment]
> yes i can. what kind of trade you want?..


hello
can you edit this strategy if 2 or3 virtual loss according to strategy then third time enter for real trade with martingale please ?


[New folder.zip](https://github.com/binary-com/binary-bot/files/4647535/New.folder.zip)

**Comment by gustan81** [comment]
Hi Babehdyo.. can you please build me a bot binary. io? odd  bot. and even bot. that have virtualhook. thanks
