### ISSUE TITLE
Rate limit reached for: proposal_open_contract - Error meaning

### ISSUE THREAD

**Issue by okovalov** [binary-com/binary-bot#237]
@aminmarashi please take a look at [this test console bot](https://gist.github.com/okovalov/3519b1ee13bbf1c749e450058ef338bd)

when it runs for about 15-20 it starts giving an error

> 
11:34:46 AM: WARN: Rate limit reached for: proposal, retrying in 2048.5s
12:08:54 PM ====================================
12:08:55 PM: INFO: Bought: Win payout if the last digit of Volatility 10 Index is odd after 5 ticks.
12:08:55 PM: WARN: Rate limit reached for: proposal_open_contract, retrying in 1.5s
12:08:55 PM: WARN: Rate limit reached for: proposal, retrying in 1.5s
12:08:55 PM: WARN: Rate limit reached for: proposal, retrying in 1.5s
12:08:57 PM: WARN: Rate limit reached for: proposal_open_contract, retrying in 2.5s
12:08:57 PM: WARN: Rate limit reached for: proposal, retrying in 2.5s
12:08:57 PM: WARN: Rate limit reached for: proposal, retrying in 2.5s
12:08:59 PM: WARN: Rate limit reached for: proposal_open_contract, retrying in 4.5s
12:08:59 PM: WARN: Rate limit reached for: proposal, retrying in 4.5s

> 

What is the meaning of this error? what have caused it and how can I avoid it?

thank you

**Comment by okovalov** [comment]
@aminmarashi  it is quite annoying. I got another account with a different api key and in 10 minutes or so I got it again

5:10:06 PM: INFO: Bought: Win payout if the last digit of Volatility 10 Index is odd after 5 ticks.
5:10:06 PM: WARN: Rate limit reached for: proposal, retrying in 1.5s
5:10:06 PM: WARN: Rate limit reached for: proposal, retrying in 1.5s
5:10:06 PM In purchase now... 6/1/2017, 5:10:06 PM
5:10:07 PM In purchase now... 6/1/2017, 5:10:07 PM
5:10:08 PM In purchase now... 6/1/2017, 5:10:08 PM
5:10:08 PM: WARN: Rate limit reached for: proposal, retrying in 2.5s
5:10:08 PM: WARN: Rate limit reached for: proposal, retrying in 2.5s
5:10:10 PM In purchase now... 6/1/2017, 5:10:10 PM
5:10:11 PM: WARN: Rate limit reached for: proposal, retrying in 4.5s
5:10:11 PM: WARN: Rate limit reached for: proposal, retrying in 4.5s
5:10:12 PM In purchase now... 6/1/2017, 5:10:12 PM
5:10:14 PM In purchase now... 6/1/2017, 5:10:14 PM
5:10:15 PM: WARN: Rate limit reached for: proposal, retrying in 8.5s
5:10:15 PM: WARN: Rate limit reached for: proposal, retrying in 8.5s
5:10:16 PM In purchase now... 6/1/2017, 5:10:16 PM


here is logic

while (IsTradeActive) {
    console.log('In trade');

    Bot.start(TradeOptions) ;

    console.log('====================================');
    console.log('Preparing Proposals');

    var numberOfTicksToAnalyze = 1000;

    while(watch('before')) {
        console.log('====================================');

        DigitStats = GetDigitStats(
            GetChunkOfTheList(Bot.getTicks(), numberOfTicksToAnalyze), 2, RealTickLength
        );

        // console.log(DigitStats);
        DigitPercentStats = GetDigitPercentStats(DigitStats, numberOfTicksToAnalyze);

        console.log(DigitPercentStats);

        if(IsSignalToTrade(DigitPercentStats)) {
            Bot.purchase(TradeType);
        }

        // Prevent max sell alert because of trading too fast
        // console.log('1 Sleep start...');
        // sleep(1);
        // console.log('1 Sleep finished...');
    }

    while(watch('during')) {
        console.log('In purchase now...', new Date().toLocaleString());
    }

    console.log('Last Tick  After', Bot.getLastTick());
    console.log('Last Digit After', Bot.getLastDigit());
    console.log('--------------------------');
    console.log('Contract finished.');

    var tradeResult = Bot.readDetails(11);

    if (tradeResult === 'win') {
        WinsCount++;
        LossChainLength = 0;
    } else if (tradeResult === 'loss') {
        LossCount++;
        LossChainLength++;
    }

    if (LossChainLength > MaxLossChainLength) {
        MaxLossChainLength = LossChainLength;
    }

    TotalProfit = Bot.getTotalProfit();

    var tradeStatsDto = {
        'total_profit'         : TotalProfit,
        'wins_count'           : WinsCount,
        'loss_count'           : LossCount,
        'loss_chain_length'    : LossChainLength,
        'max_loss_chain_length': MaxLossChainLength
    };

    ShowTradeSessionStats(tradeStatsDto, false);

    // Prevent max sell alert because of trading too fast
    console.log('Sleep start...');
    sleep(10);
    console.log('Sleep finished...');

    IsTradeActive = ShouldTradeRemainActive(TotalProfit, ExpectedProfit, MaxAcceptableLoss);
}

please advise..
thank you

**Comment by Fruitfella** [comment]
@okovalov
I think this error is same with "the price move too much".
my bot that got this "the price move too much" error in official site,
got "rate limit" error in beta site. im using the blocky bot though,
not sure if its same with the console.
The broker denied(refused?) ur propose contract when "the price move
too much" between the start purchase to entry spot. this also happen
when i trade manually. i wonder if this is what they mean by high/low
intraday in the "terms and conditions".
i see that with the console, its still running after get that error,
while with blocky it stop and thats really a problem.

**Comment by okovalov** [comment]
@aminmarashi another example of a different threshold 

9:08:58 PM Purchased: CALL at 6/1/2017, 9:08:58 PM
9:08:58 PM: WARN: Rate limit reached for: proposal_open_contract, retrying in 1.5s
9:08:58 PM: WARN: Rate limit reached for: proposal, retrying in 1.5s
9:08:58 PM: WARN: Rate limit reached for: proposal, retrying in 1.5s

**Comment by okovalov** [comment]
@Fruitfella well, ui bot uses same engine which is used by a console one, so must be same thing there..

**Comment by aminmarashi** [comment]
@okovalov As you, all figured it out it's probably our server not being able to handle proposal requests and we try again after these time intervals. You're asking for two proposals (and you get this error for each).
For **real accounts**, you shouldn't see this error easily.
This limit is more aggressive for **virtual accounts**, therefore if you have multiple connections open it's likely that you get these errors.
The current limit is 20 requests per minute (we have hourly limit too).
Anyhow, if you have less than 4 open connections you shouldn't see this warning at all.
@Fruitfella It shouldn't be different from the command-line. What error do you see before it stops?

**Comment by okovalov** [comment]
@aminmarashi thank you. so then a few more questions:
1) how can I see a remained threshold for a number of proposals I am sending?
2) from where exactly in my script a proposal request is being sent? So I can put a sleep there or to add sort of a method to check available threshold so I can avoid meeting the limit?
3) how come I have multiple connections open if I have only one instance running? how can I limit it?
I don't know why but I see it almost immediately I run the script and it was NOT happening before (maybe couple months ago) I had like 4-5 instances running and it was always working ok..

please help 
thank you

**Comment by okovalov** [comment]
@aminmarashi 
so proposal request being sent from this block?

    while(watch('before')) {
        console.log('====================================');

        // console.log('1 Sleep start...');
        sleep(1);
        // console.log('1 Sleep finished...');

        DigitStats = GetDigitStats(
            GetChunkOfTheList(Bot.getTicks(), numberOfTicksToAnalyze), 2, RealTickLength
        );

        // console.log(DigitStats);

        DigitPercentStats = GetDigitPercentStats(DigitStats, numberOfTicksToAnalyze);

        // console.log(DigitPercentStats);

        if(IsSignalToTrade(DigitPercentStats)) {
            Bot.purchase(TradeType);
            // console.log('2a Sleep start...');
            sleep(1);
            // console.log('2a Sleep finished...');
        }
    }


or when I run ?

console.log('Starting bot...');

while (IsTradeActive) {
    console.log('In trade');

    console.log('0 Sleep start...');
    sleep(1);
    console.log('0 Sleep finished...');

    Bot.start(TradeOptions) ;

**Comment by aminmarashi** [comment]
1. Make sure `bot -V` gives you `8.0.47`. (`npm i -g binary-bot`)
2. If your startegy `sell`s at the market, you have to be extra careful about how often you sell.
3. If you're doing tick trades, It's highly unlikely to hit the limit by only one instance of `bot`, if it happens a lot, it's a bug.
4. Best place to put your sleep is before start.
Important calls:
## (1)
`init`: only done once, for configs that are unlikely to change during a bot session
`start`: request a new trade by making proposal(s) for market price
## (2 & 3)
`watch`: We have two continuous scopes (currently named `'before'` and `'during'`, we may change them to `'purchase'` and `'sell'`).
### (2)
 `'before'` is triggered by each tick and needs proposals requested by `start` to be ready.
### (3)
 `'during'` is triggered by each update on purchased contract, here's where you should decide to sell
## (4)
If the result of calling `watch('during')` returns false means contract is closed (sold or expired). and any code after that and before start is like the 4th block.

If you still can't solve it, please feel free to send your code (without the analytic parts).

**Comment by okovalov** [comment]
@aminmarashi thank you for the explanation, then it is a **bug**, since as you could see here [ - there is a one second pause ](https://gist.github.com/okovalov/3519b1ee13bbf1c749e450058ef338bd#file-test_bot-js-L580) before     Bot.start(TradeOptions) ; is called again (and therefore a new proposal being sent) - please test it.

One note about init() though -I use it upon trade is finished to change a contract. for instance to change the stake.
like this

    console.log('--------------------------');
    console.log('Contract finished.');

    var tradeResult = Bot.readDetails(11);

    if (tradeResult === 'win') {
        BetAmount = InitialAmount;
        WinsCount++;
        LossChainLength = 0;
    } else if (tradeResult === 'loss') {
        LossCount++;
        LossChainLength++;

        BetAmount += Round(BetAmount / ReturnPercent, 2);

        console.log('New BetAmount', BetAmount);
    }

    IsTradeActive = ShouldTradeRemainActive(TotalProfit, ExpectedProfit, MaxAcceptableLoss);

    BotInitOptions.amount = BetAmount;
    Bot.init(Token, BotInitOptions);

    // Prevent max sell alert because of trading too fast
    sleep(10);


I found no other way for doing that, please advise if there is another way of changing the contract 

but most important is this **bug**, which causes rate limit to be reached... it really prevents me of using it.. thank you

**Comment by aminmarashi** [comment]
I'm really excited about the way you used the undocumented CLI interface to build your bot, great job @okovalov.
I'm still unable to reproduce the bug after `Number of runs  = 100`
Are you sure about the `bot -V == 8.0.47`?
There's no need to put a sleep for tick trades.
There are two conditions that you have to be careful about our limits:
1. You have multiple open bots (running at the same time)
2. You want to sell at market (`Bot.sellAtMarket()`) too often.
Your case is neither of those.
I'll keep the bot open hoping to see the bug.

**Comment by aminmarashi** [comment]
Maybe it's the way you try to exit the running bot. How do you do that? If you want to exit properly you should hit `Ctrl+C` otherwise there's a chance that there are open bot instances somewhere in your system.
If you use Mac (or Linux) you can try this:
```
ps aux |grep bot |grep -v grep | wc -l
```
It should give you 1:
```
       1
```
If you see `2` or more, it means you have multiple instances running.

**Comment by aminmarashi** [comment]
I could actually see the
```
9:56:57 AM Trade started at 6/6/2017, 9:02:10 AM
9:56:57 AM Trade finished at 6/6/2017, 9:56:57 AM
```

**Comment by aminmarashi** [comment]
@okovalov Is it fixed?

**Comment by okovalov** [comment]
@aminmarashi sorry, I could not re-test it yet.. crazy beginning of the week. please let me try it tonight and I will let you know. and yes, the cli version is the latest of course. I think it could have been related to a token restrictions? like it is a demo unverified account and therefore it has lower threshold etc? what do you think? are there any restrictions based on token type (beside an obvious one like real and virtual in general?)

**Comment by aminmarashi** [comment]
There are no such restrictions on the token that I'm aware of. And I also tested it multiple times with my own virtual account which is unverified.
My guess is zombie bots still running in the background.

**Comment by okovalov** [comment]
@aminmarashi yes, it looks ok now.

12:28:10 In purchase now... 2017-6-11 12:28:10
12:28:10: SUCCESS: Profit amount: 0.68
12:28:10 --------------------------
12:28:10 Contract finished.
12:28:10 --------------------------
12:28:10 Number of runs  = 261
12:28:10 --------------------------
12:28:10 - net profit   = 0.68
12:28:10 - trade result = win
12:28:10 - stake size   = 0.72
12:28:10 --------------------------
12:28:10     Total Session Wins 148
12:28:10     Total Session Loss 113
12:28:10 --------------------------
12:28:10     Current Max Profit 50
12:28:10 --------------------------
12:28:10     Current Consequence Loss 0
12:28:10     Max     Consequence Loss 6
12:28:10 --------------------------
12:28:10
12:28:10     Total Profit 50
12:28:10
12:28:10 Trade started at 2017-6-11 11:33:02
12:28:10 Trade finished at 2017-6-11 12:28:10
12:28:10 { symbol: 'R_100',
  amount: 0.35,
  basis: 'stake',
  candleInterval: 60,
  contractTypes: [ 'DIGITEVEN', 'DIGITODD' ],
  currency: 'USD',
  duration: 5,
  duration_unit: 't' }


continue to test now, just wanted to run it one more time and then will close the issue. thank you!

**Comment by okovalov** [comment]
@aminmarashi yes, have it running for several hours. looks ok. thank you. closing it off

**Comment by JGihon** [comment]
Hello Guys, 
Pls I have a question related to this topic.
Aminmarashi you said:
Make sure bot -V gives you 8.0.47. (npm i -g binary-bot) 
If your startegy sells at the market, you have to be extra careful about how often you sell...

My bot would open a trade with 1 min expiry then watch the trade.
If conditions met it sells @ market (if profit/loss is reaching -70%) otherwise it checks the profit/loss after 35 sec and might sell @ market. Then it takes time to analyze and opens next trade if conditions met, so its rare that it would open trades after one another. 

So, can this reach the limit?
(Please also check what I have posted here: https://github.com/binary-com/binary-bot/issues/710
seems its a bug...)

Thanks in advance,
Gihon
