### ISSUE TITLE
HELP ME SOLVE THIS ISSUE.

### ISSUE THREAD

**Issue by esperanda01** [binary-com/binary-bot#2372]
BOT STOPS EVERYTIME BECAUSE OF THE MARKET HAS MOVED TOO MUCH
![save](https://user-images.githubusercontent.com/44817486/73194110-f2bb9400-412b-11ea-8297-2cd5df20a055.PNG)

**Comment by ZDEGLET** [comment]
СЕГОДНЯ НЕПОНЯТНАЯ СИТУАЦИЯ ТВОРИТСЯ. Я САМ НЕ ПОНИМАЮ В ЧЕМ ДЕЛО.

**Comment by hotmatrixx** [comment]
> 
> 
> BOT STOPS EVERYTIME BECAUSE OF THE MARKET HAS MOVED TOO MUCH
> ![save](https://user-images.githubusercontent.com/44817486/73194110-f2bb9400-412b-11ea-8297-2cd5df20a055.PNG)

tick this.
call me if fix

:)


![Capture](https://user-images.githubusercontent.com/49715381/73232931-c8c8a700-41e9-11ea-834a-029e20dbe612.PNG)

**Comment by esperanda01** [comment]
okay will try that 

> > BOT STOPS EVERYTIME BECAUSE OF THE MARKET HAS MOVED TOO MUCH
> > ![save](https://user-images.githubusercontent.com/44817486/73194110-f2bb9400-412b-11ea-8297-2cd5df20a055.PNG)
> 
> tick this.
> call me if fix
> 
> :)
> 
> ![Capture](https://user-images.githubusercontent.com/49715381/73232931-c8c8a700-41e9-11ea-834a-029e20dbe612.PNG)

OKAY WILL TRY THAT AND GIVE YOU FEEDBACK

**Comment by esperanda01** [comment]
> > BOT STOPS EVERYTIME BECAUSE OF THE MARKET HAS MOVED TOO MUCH
> > ![save](https://user-images.githubusercontent.com/44817486/73194110-f2bb9400-412b-11ea-8297-2cd5df20a055.PNG)
> 
> tick this.
> call me if fix
> 
> :)
> 
> ![Capture](https://user-images.githubusercontent.com/49715381/73232931-c8c8a700-41e9-11ea-834a-029e20dbe612.PNG)

Worked but made spoils the bot rules.. and makes the bot trade without checking the rules
