### ISSUE TITLE
can anybody create these blocks

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2375]
can anybody create these blocks

![72522984-cab17280-3899-11ea-83f5-786ae9c80c44](https://user-images.githubusercontent.com/43085185/73244140-08cc6180-41cb-11ea-831d-a6e1a4cc3512.png)

**Comment by ZDEGLET** [comment]
самое главное в закрытых блоках. какая у них настойка?

**Comment by hotmatrixx** [comment]
No, because the blocks "**absolute stake**", **'this block is called on every stake**' and all of **block 4** are all collapsed/hidden. only the original author could make those blocks. there is no way of knowing what's in them.
