### ISSUE TITLE
[QoL] Is Candle Black?

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2379]
Hi, @aaron-binary I have a suggestion to make this block easier to understand;
the flavour text indicates that the block returns true if the Close is lower than the Open - ie if the candle is a 'put'.

This is actually quite confusing (to me, and so probably to others) as the default candle in some other apps have black as a rising/call, with hollow blocks representing a put/fall.

It might make more sense to call it "Is Candle Red?" as that fits in better with the indicators that are natural on the binary.com site and tradingview.com - whom you use by default for your indicators.

It might also be nice to make it have the "Options" of making the Red into a selectable "Red/Green" similar to a True/False block, as adding a 'not' block is counter-intuitive.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

We stick to the definition in our help page here: https://www.binary.bot/bot.html?data-elevio-article=127. For backward compatibility we won't change the existing block, although we may update the label to be _**Is candle black/red?**_, and perhaps we could add a _**Is candle white/green**_ block too. Will discuss it internally.

Regards,
Aaron

**Comment by hotmatrixx** [comment]
Thanks,
honestly, you're awesome.

in line with your thoughts Is candle Black (Red)? is easier to understand in  'natural' english, as the "/" usually denotes opposites - ie win/loss up/down, call/put VS a statement like "Will the price go up (call), or down (put)?"

Hope that makes sense?
