### ISSUE TITLE
Helping please in coding

### ISSUE THREAD

**Issue by alsorory** [binary-com/binary-bot#2383]
Hello Programmers
I need your help in how to make this code in binary bot

if i want to sum the last two digit for example in index 75 the number is 426,934,9152
the last two digit is 5 and 2 and the sum is 7 so i need to open order based on the last digit of sum number 7
and the sum of number 9 and number 1 is 10, this number 10 is the number of tick

can you make this coding in binary bot

Thank you

**Comment by hotmatrixx** [comment]
where did the number 426,934,9152 come from?

**Comment by alsorory** [comment]
thank you for your 

> where did the number 426,934,9152 come from?
> what numbers are you using as last digits? you didn't explain that bit well. last digit of every tick, last digit of previous trades, last digit of contract numbers, last digit from RNG?

Thank you for your reply hotmatrixx
let me explain to you again

that number is a random number i bring it from index v75 to give you example
if you go yo index v75 you will see around 10 number "426,934,9152" right this is example and it is 10 number

what i care of the last 4 digit numbers 9152
we will work on 91 and then work 52

in the first part if i already set on binary bot when 9 digit and 1 digit are occurs that means the sum of 9+1 is 10, set the tick number to 10 

in case i want to set other numbers like 4 digit and 2 digit instead of 9 digit and 1 digit, so i will wait till the first 2 numbers of last 4 digits are 4 and 2 and it should show something for example xxx,xxx,42xx and in this case the sum of 4 and 2 is 6, so i want the tick number change to 6

and for the second part the last two digits of our example "426,934,9152" are 5 and 2 and the sum is 7, so in this case i want to set the last digit to match is 7 

so from first part we have after 10 ticks and second part is set number 7 as Last Digit Prediction

so the bot should make order based on these rules and we wait for the next 9 ticks to show the result of last digit prediction

if it is still not clear please let me know so i will try to explain it in more example

**Comment by hotmatrixx** [comment]
Yeah.. you still didn't answer the question. Not really. I wanted to know what numbers you added together.

I presume it's the last digit and the previous one.

I made the bot for you and uploaded it to my repository.
https://github.com/hotmatrixx/binary.com.public

**Comment by alsorory** [comment]
> Yeah.. you still didn't answer the question. Not really. I wanted to know what numbers you added together.
> 
> I presume it's the last digit and the previous one.
> 
> I made the bot for you and uploaded it to my repository.
> https://github.com/hotmatrixx/binary.com.public

![last tick](https://user-images.githubusercontent.com/20263495/73424587-4d2d3e00-4340-11ea-8bb3-2d799d3e1993.png)

i hope you get the idea from this picture

i want to make code like this, the code in picture is for explanation not real or not working

**Comment by hotmatrixx** [comment]
well I don't really understand.
I made something that checks the last digit of the last two ticks, adds them together, then uses the last digit of that operation as the next prediction.

heh.
you sure know how to confuse a guy.

I already built this for you. I posted a link to the repository. it literally has your name on it.
https://github.com/hotmatrixx/binary.com.public/tree/master/other.users

**Comment by alsorory** [comment]
> well I don't really understand.
> I made something that checks the last digit of the last two ticks, adds them together, then uses the last digit of that operation as the next prediction.
> 
> heh.
> you sure know how to confuse a guy.
> 
> I already built this for you. I posted a link to the repository. it literally has your name on it.
> https://github.com/hotmatrixx/binary.com.public/tree/master/other.users

Yes i have checked it but it was different from the idea

Thank you for your effort trying to build that logic

**Comment by hotmatrixx** [comment]
That's fine. I guess the issue is that I don't understand what you want. please don't try to explain it again.

**Comment by alsorory** [comment]
> That's fine. I guess the issue is that I don't understand what you want. please don't try to explain it again.

Hope i got another developer who already understand it and my the code

**Comment by hotmatrixx** [comment]
I re-read your description, what's confusing is that you didn't really explain what your example number was. it's the output of a tick. if you'd used an actual tick, in it's proper format, it would have made way more sense the first time.
![Capture](https://user-images.githubusercontent.com/49715381/73443815-3f1d0300-43bc-11ea-8d94-a11e9b0a222d.PNG)

**Comment by alsorory** [comment]
> I re-read your description, what's confusing is that you didn't really explain what your example number was. it's the output of a tick. if you'd used an actual tick, in it's proper format, it would have made way more sense the first time.
> ![Capture](https://user-images.githubusercontent.com/49715381/73443859-5956e100-43bc-11ea-9e59-58985c0d5b63.PNG)

oh Thank you for your response, i have just noticed now you have responded to me

yes you started get what i meant

i also just opened any topic explaining with picture and code, i had tried to make that code but it doesn't work

https://github.com/binary-com/binary-bot/issues/2400

**Comment by hotmatrixx** [comment]
so;
there is no 'natural' way to do this, ticks are considered floating point values, not strings... even the one called 'ticks string' can't be parsed as such.

So there is no easy way to do this. I can do it using a big loop or two and a rounding down function, but that will take more code than I feel like doing this morning. it's 5.30am, I'm going to bed, before I do the next rounds on my tutorial series.

Annoy me again tomorrow and I'll make it happen for you. I think. It requires more brain power than I have right now, and it can only be done, I think, using a workaround.

To Be Honest your method is quite unorthodox, and appears to me, to be based on a 'random number generator' style of trading - that's why there isn't an easy way to do it... - so I ask you how did you come up with this strategy?

**Comment by alsorory** [comment]
you are genius and very smart

yes i think it is not easy to made, i also kept two days trying to make it with my sample knowledge of coding

the way why i want number from end 4 and from end 3 to be added manually because i want to test for what numbers are working well and what numbers we don't need 

for example in your last code you make it for any two number equal to 4, so the tick is from 4

but that won't work for this strategy because maybe 2+2 is working for this strategy while 3+1 is not working, so that's why i need to put them manually to check what numbers are works

**Comment by hotmatrixx** [comment]
Yeah I understood alright. I put those numbers in 'manually' for clarification. If I was actually writing the bot, I would have used calculated variables, - but if I did that in the picure you wouldn't have been able to see what was going on.

I just wanted to make sure I understood the idea of what you wanted.
I'll have a play with it in a few hours.

**Comment by alsorory** [comment]
Great, i am waiting for your code to test it also, 

and Thanks for @aaron-binary who is label this as a strategy

**Comment by alsorory** [comment]
> Yeah I understood alright. I put those numbers in 'manually' for clarification. If I was actually writing the bot, I would have used calculated variables, - but if I did that in the picure you wouldn't have been able to see what was going on.
> 
> I just wanted to make sure I understood the idea of what you wanted.
> I'll have a play with it in a few hours.

How was the testing with you?

**Comment by jstfrancis365** [comment]
> > I re-read your description, what's confusing is that you didn't really explain what your example number was. it's the output of a tick. if you'd used an actual tick, in it's proper format, it would have made way more sense the first time.
> > ![Capture](https://user-images.githubusercontent.com/49715381/73443859-5956e100-43bc-11ea-9e59-58985c0d5b63.PNG)
> 
> oh Thank you for your response, i have just noticed now you have responded to me
> 
> yes you started get what i meant
> 
> i also just opened any topic explaining with picture and code, i had tried to make that code but it doesn't work
> 
> #2400

Hi

**Comment by itzaakay** [comment]
pld how can i download it
