### ISSUE TITLE
Inputting Chart data based on close of last candle

### ISSUE THREAD

**Issue by phoenix-pk** [binary-com/binary-bot#2384]
I have a BB strategy. I simply pulled up the sample BB strategy from the help website but what I am not able to do is that I need it to do this based on the close of last candle of duration 1 minute or 5 minute for example, not the last tick.

How do I make it so it checks if last candle closed above or below BB then trade.

![Capture](https://user-images.githubusercontent.com/60455890/73414597-1ef43200-4331-11ea-8087-c77bf1932518.PNG)

**Comment by hotmatrixx** [comment]
good on you for trying to figure it out, then asking.
so many people ask us to code the bot, without attempting to make an effort to learn first.

here is the code block you want.

notice it's candle #2 - that's bcause candle #1 is the currently open one, candle 2 is the one that closed last.

the Default Period is set in the Block 1.

**Comment by hotmatrixx** [comment]
you'll probably want this, too:
![Capture](https://user-images.githubusercontent.com/49715381/73427399-8e9f0700-439b-11ea-84d3-1e5a4ee67c72.PNG)

**Comment by hotmatrixx** [comment]
heh.
you sure know how to confuse a guy.

I already built this for you. I posted a link to the repository. it literally has your name on it.
https://github.com/hotmatrixx/binary.com.public/tree/master/other.users

**Comment by hotmatrixx** [comment]
another thing, Forex/Major Markets will only work on timeframes 3 minutes or longer.
Synthetic markets are great for using 1 minute candles for slightly quicker testing.

**Comment by phoenix-pk** [comment]
> 
> 
> another thing, Forex/Major Markets will only work on timeframes 3 minutes or longer.
> Synthetic markets are great for using 1 minute candles for slightly quicker testing.

Thanks a lot! Appreciate the quick help!

Let's see how Bot trading goes for me. I have been doing testing on a BB strategy, it goes against trend usually so its extremely risky, traded manually, ended up with good result except for Martingale, ends badly then.

BB 20 with 2.5 DEV. Any candle which ends above upper band, PUT. Anything below, CALL. One would want to enter 2-3 seconds before the candle closes to get in on the best position.

For a more safe option, forumlate to go only if candle ends b/w BB20 (2.5) and BB20 (3) < Harder to achieve when trading manually. 

5 Minutes time frame also works, gives you those few precious seconds to enter because 1 Minute, sometimes the next candle jumps way above for one to start.

**Comment by phoenix-pk** [comment]
@hotmatrixx Forgot to ask, can we run multiple instances of the bot for different pairs/indices? i.e. possible to run one in each browser tab without issues?

**Comment by phoenix-pk** [comment]
> 
> 
> yeah, no worries. just be aware that the more operations it makes while checking, the more taxed your computer will be - it's especially taxing on your PC if you have it running loops or 'on every tick' operations - but if it does a check, makes a buy, then waits most of the time you'll be fine....
> 
> as long as you have an OK PC and enough RAM. You'll know becuase your browser will start giving you 'do you want to stop our wait this operation'.
> 
> No vconflicts with bots, but there is a limit onthe number of trades you can place in Virtual accounts, somewhere around 500-1000 per day. Just keep an eye on Task manager to make sure you've PC is at under 99% utilized.

Got enough RAM and system power so not really worried about system bogging down. 

Wanted clarification from you, you said I have to enter 2 for "candles list read 'Close' # from 2" as current/open candle is 1. What happens if I select 1? Since technically, it cannot read close value of the current open candle because it is open? I just tried with 1 and it did end up buying option still and won.

**Comment by hotmatrixx** [comment]
yep, so the 'close' of candle 1 is it's current position/tick. if you ran a bot to show you the closed value on every tick you'd see it constantly changing.
