### ISSUE TITLE
continually logged out

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2385]
just having an issue right at this moment. I run 2 or 3 scripts in multiple tabs, normally. 
Except that as soon as I load one tab at the moment, it will fail after a trade or 2 (if any trades at all) and i have to log in again.

Deriv seems fine, it's local to bot.binary.com

**Comment by phoenix-pk** [comment]
I faced the same issue today while trying to have multipe tabs open. Had to refresh and re-run the bots on all previous open tabs just to be safe.

**Comment by hotmatrixx** [comment]
yep.
6 hours of sleep and a reboot seems to have helped, but my scripts won't start reliably.

**Comment by aaron-binary** [comment]
Hey @hotmatrixx and @phoenix-pk,

If these issues persist, please contact us through customer support by emailing support@binary.com.

Regards,
Aaron
