### ISSUE TITLE
I need an Explanation

### ISSUE THREAD

**Issue by genom16** [binary-com/binary-bot#2388]
Please can someone explain how the BEAR & BULL Indexes are generated in Binary.com?

**Comment by hotmatrixx** [comment]
Hi, @genom16 
The biggest clue is in the type of index it is it's listed as a "Synthetic" index. That basically means that it's made up of artificial numbers that have no basis on the real markets. it's numbers being spat out by the broker to 'simulate' a stock market.

That is the same for all Synthetic markets. They are literally 'numbers made up by the Broker'. ie, binary.com can make them be anything they want to be, at any moment in time.
