### ISSUE TITLE
Split martingale

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2390]
Anybody have split martingale code

**Comment by muroyal** [comment]
https://github.com/binary-com/binary-bot/issues/2123

**Comment by hotmatrixx** [comment]
maybe I should release my martingale code, too. I'll get it all lined up into an easy to use script and add it to my git in the next few days

**Comment by sohailsb** [comment]
> maybe I should release my martingale code, too. I'll get it all lined up into an easy to use script and add it to my git in the next few days

thanks

**Comment by sohailsb** [comment]
> maybe I should release my martingale code, too. I'll get it all lined up into an easy to use script and add it to my git in the next few days

i am waiting
