### ISSUE TITLE
[issue] - bot performance on unreliable internet

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2394]
So, I have bad internet, that's my problem, and most people would have a fairly stable connection, I recognise that. I'm mostly bringing this up, as it's something that might be overlooked altogether if you're used to having a stable connection.

My internet has micro disconnects all the time. 1/8 second drop outs, to 2 minute ones. I know there is a problem on the exchange in our area, I'm working on it. it's the short onesthat seem to be the issue. If the internet hangs, while there is a trade open, it can take  10-20+ minutes to close the trade... or hang altogether.

Just putting it out there.

**Comment by muroyal** [comment]
@hotmatrixx 

Just i would like to suggest you to use Virtual system.. Google console is free for some days you can install vertical system with high speed internet  no need to connect Laptop or system it will be online for 24/7 and run the bots. 

https://console.cloud.google.com/compute/instances?_ga=2.194220909.-1791856044.1572582965&pli=1&supportedpurview=project&project=constant-cursor-257705
 
Or

https://www.kamatera.com/express/compute/?tcampaign=35126_365085&bta=35126&nci=5344&utm_campaign=cloud

**Comment by hotmatrixx** [comment]
That's actually a good idea, I might implement that once I'm making enough to justify it.
thanks!

I hav been thinking about how to deal with my PC's limited processing power - I can run any game I want, but open 10 tabs in firefox running (my) bot.binary scripts brings it to it's knees. This could be a great solution.

**Comment by muroyal** [comment]
I have used firefox for few days it is not performing smooth comparing  with google chrome. 
Register demo virtual console in google you will get around 300$ free amount for use virtual server for 1 year --- good offer given by google.. 👍

**Comment by thommmaz** [comment]
Even if you have very good connection (in my case 100Mbps/100Mbp) and only 1 bot running, nothing can be done about this:

![rate_limit](https://user-images.githubusercontent.com/40931373/73589916-ed23cc80-44e4-11ea-90a6-46d625cad048.png)

**Comment by hotmatrixx** [comment]
> 
> 
> Even if you have very good connection (in my case 100Mbps/100Mbp) and only 1 bot running, nothing can be done about this:
> 
>

Uhh. That's a different issue @thommmaz 
That's caused by making too many API calls within a time limit.

I'm talking about the bot purchasing a trade, then just hanging - stopping - and never moving on to block 4 once the trade's close time passes.
