### ISSUE TITLE
Filter for bad market(choppy ranges)

### ISSUE THREAD

**Issue by Martinez222** [binary-com/binary-bot#2396]
Hi ,

did enyone have a pice of code so i can filter the area from the pictures attached?
I already try ex-machina chop filter and it's not what i need.
10x!
![Volo 4b](https://user-images.githubusercontent.com/39260368/73590884-a6d46a80-44f0-11ea-9d14-bf1431822485.jpg)
![volo 7a](https://user-images.githubusercontent.com/39260368/73590886-a6d46a80-44f0-11ea-83ed-604703d07397.jpg)

**Comment by muroyal** [comment]
Chop index period 25 trade only below 45..

You can use atr indicator or adx  also

**Comment by hotmatrixx** [comment]
So, interestingly the problem with trend indicators, is they take a while to flatten out when this happens, and take a while to take off again once there is a trend... catching the trend or chop in time is definitely  challengining. I have a couple of ideas around this,  here's a quick and nasty idea for you;

one thing that I'm looking at, is if the SMA(5) is between candle #2'open and close  then you're either in a flat or a trend direction change. I'd use something to confirm that.

Another thing you could use is if the values of the Bollinger bands' upper and lower limits are less than 80% of their average, then the market is experienceing less Volitility. 

Actually , I might try that one out!

**Comment by Martinez222** [comment]
Thanks for your answers.@muroyal &@hotmatrixx.
As i said i already try binary ex machina chop block many configurations  but is not helping me.My bot is trading 1 time per candle ,10 ticks(not at the begining of the candle ,as soon as condition met).I have RSI and Volatility combination and trading above or beyound fast EMA.I alreaqy try with bollinger bands hotmatrixx îs not working.Bot has very good results and If i decide to go live o whant to do it without martingale.I learn my leasson when i blow my #acc with confidence that my bot  will never have more then x steps.Martingale it's a matter of time.The ideea of SMA(5) between candle #2'open and close then ....-seems good ideea but i don't know If i can make it.I'm trying to this : If in the last  6 closed candles ,3 candles ore more are crossing Ema 6 then îs flat market and bot is not trading....i have candles crossing issue :)

**Comment by Martinez222** [comment]
P.S How has Adx?:)

**Comment by muroyal** [comment]
I have bot it have some conditions. They may usefull in your bot...

https://github.com/muroyal/Binary/blob/master/Autobot9000%20-%20epic%20conditional%20triggers.xml

**Comment by Martinez222** [comment]
10x i will look on it!

**Comment by ZDEGLET** [comment]
@muroyal 
скиньте пожалуйста в zip архиве я не знаю как его загрузить.

**Comment by muroyal** [comment]
Copy past in notepad and change extension from .txt to .xml

**Comment by muroyal** [comment]
@Martinez222 This is binary trading hence take one indicator less period and one more same indicator double period and take some condition that if the short period indicated is above long period indicator then control your trades with this ..... this is some what i would like to share with you. .you can avoid some failures.. 

And try to trade in forex market with proper technical indicators   But the main issue is the binary bots contracts are not placing properly on right period our trade will be fail or bot will get some issue   and it will stop and you will lose in high martingale place  💯

**Comment by Martinez222** [comment]
@muroyal i've looked at your bot, but i didn't find any filters, less fruitffela block for candles analyzing ..
yet it seems an interesting bot if you twist it a little .. :)
maybe I'll put in my bot too some candle analyzing...
![gix](https://user-images.githubusercontent.com/39260368/73598554-8d5c0e80-4542-11ea-9820-edc1cc126490.jpg)

**Comment by Martinez222** [comment]
The problem with all indicators is that they are not showing the future ,they are showing the past.My bot seems to work very well in some conditions.I have positive results evrey day for more than 2 monts.Beacause i already blow my account with martingale i do not want to use martingale enymore.
May be is just an illusion that bot is working well.I don't trust this syntetic markets.But if i will manage to do it as i wish i will go live without martingale.Until now i have 8 steps loss in a row.
Today just 6 in a row after  more de 8 hours of running...
![jax1](https://user-images.githubusercontent.com/39260368/73598712-643c7d80-4544-11ea-9f30-0409dae48fea.jpg)
![jax2](https://user-images.githubusercontent.com/39260368/73598713-64d51400-4544-11ea-8d4c-8e5665507687.jpg)

**Comment by muroyal** [comment]
Bot is running on live account from 24 hours.  stop loss 10$ 1 time went to 3rd martingale i am using split martingale.. As per count of wins and losses i can go without martingale.. I am testing with less bet on live account.. 

Martigl

![image](https://user-images.githubusercontent.com/32416314/73598832-fa7f9c00-4562-11ea-9ba9-c13788b93323.png)

👍

**Comment by hotmatrixx** [comment]
> 
> 
> P.S How has Adx?:)

one of the more experienced coders here manually made one.
I've made a few too, Heinken Ashi, Parabolic, Hull, etc. that interested me.
