### ISSUE TITLE
How to compile XML bot..

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2397]
[@indikator.adx (1).zip](https://github.com/binary-com/binary-bot/files/4142497/%40indikator.adx.1.zip)
The reason for asking to find errors attache adx indicator .. I am unable load it .. it have some errors .. @aaron-binary

**Comment by hotmatrixx** [comment]
You talking to @binary ex machina?
this looks like one of his scripts.

I got it to load, just fine.

Do you know how to use collapsed, multi nested funcitons correctly???

**Comment by muroyal** [comment]
I am not developer .. I am database administrator.. but I have good
knowledge on charts and indicators Fibonacci and Elliott waves .. I have
learnt from online ..

I am entry level knowledge on bot development.. and XML..

**Comment by muroyal** [comment]
I have already added ATR hence it is not uploading. I am able to upload now in plain.. Yes may be it has developed by  @binaryexmachina But why he have not uploaded in his repository ? May be it is not complete indicator may have some bugs need to test it.. :)

**Comment by hotmatrixx** [comment]
it works.
I'd say you haven't figured out how to configure the function inputs correctly.
