### ISSUE TITLE
Let's improve the bot

### ISSUE THREAD

**Issue by lxxneonxxl** [binary-com/binary-bot#2401]
![image](https://user-images.githubusercontent.com/57267933/73592218-03dc1a80-4509-11ea-8538-b7db9d395c76.png)

Hi, everybody. there is such an idea.. when the price of R100 (you can use other random numbers, but the value of the impulse is selected) is in the flat, it sometimes makes impulses in one direction or another and turns around(5 ticks).. the impulse value is selected for this market(there is an idea how to do it automatically, but there is no experience in coding( this will come)) ).. we take the momentum from the table %
https://github.com/lxxneonxxl/Binary_Bot/blob/master/impulse%20bot.xml

                                  ** What do you want to learn to implement ** 

1. To make the analyzer the loss of a percentage(of impulse), something like this analyzer latest numbers from the user 	Fruitfella ( the variable value is written) if the statistics of loss of momentum above, the bot will automatically switch to pulse which is higher..

2.the bot should only trade in the flat state

![image](https://user-images.githubusercontent.com/57267933/73593331-08f29700-4514-11ea-8534-e6ea553e34fd.png)

**Comment by hotmatrixx** [comment]
Do you realize that the R100 is a Synthetic Market, controlled by an RNG generator by the broker?
