### ISSUE TITLE
Plz help... Digit Differ Bot

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2403]
Digit Differ Bot
if 3 last digits
1,2,3 Differ 3
2,3,4 Differ 4
3,4,5 Differ 5
4,5,6 Differ 6
5,6,7 Differ 7
6,7,8 Differ 8
7,8,9 Differ 9
With best regards

**Comment by Martinez222** [comment]
I twisted a bot posted a couple days ago .. i think is what u  ask.
Diggits is just a matter of time until your balance disappear ...:)
![last 3](https://user-images.githubusercontent.com/39260368/73647694-b5538b00-4684-11ea-88fc-8a267cfd2b73.jpg)

**Comment by Martinez222** [comment]
[Differ 123.zip](https://github.com/binary-com/binary-bot/files/4147469/Differ.123.zip)
