### ISSUE TITLE
10 ticks

### ISSUE THREAD

**Issue by Juniorpalmer83** [binary-com/binary-bot#2405]
Hola. Quiero configurar un bot que haga lo siguiente. En una cuenta de 10 ticks, si hay más de 6 ticks high, que haga una compra a la alza, y viceversa. Los ticks no tienen que ser consecutivos. Gracias

**Comment by ZDEGLET** [comment]
This is the grail!

**Comment by Juniorpalmer83** [comment]
What grail? The holy grail?
