### ISSUE TITLE
strategy 

### ISSUE THREAD

**Issue by alansilva1** [binary-com/binary-bot#2407]
Would anyone know how to make this strategy on a robot ????   

https://www.youtube.com/watch?v=u8fx2MtXscw

**Comment by trident2005** [comment]
Do not waste your time with this strategy, just choose to buy the digit that has the lowest percentage of appearance, in general do not waste your time with bots of different digits

**Comment by hotmatrixx** [comment]
> 
> 
> Would anyone know how to make this strategy on a robot ????
> 
> https://www.youtube.com/watch?v=u8fx2MtXscw

I do, I've done it.
Trust me, I've run it for 10,000 trades. It doesn't work - the last digit strats are controlled by an RNG + and AI algorithm and are.... tricky to beat.

I konw there is an AI behind it, as I write AI's and know how they behave.. so I wrote a script to test for ai's.

**Comment by ZDEGLET** [comment]
Стратегия называется - БАНКРОТ:)

**Comment by thommmaz** [comment]
> 
> 
> Would anyone know how to make this strategy on a robot ????
> 
> https://www.youtube.com/watch?v=u8fx2MtXscw

People have to understand that there is NO WORKING STRATEGY for digits. These are random numbers, generated randomly, there is no logic behind these numbers. So you can never win in the game where are no rules at all! As @hotmatrixx  said, there is also some X-factor in never let you win consistently.

**Comment by hotmatrixx** [comment]
> 
> 
> > Would anyone know how to make this strategy on a robot ????
> > https://www.youtube.com/watch?v=u8fx2MtXscw
> 
> People have to understand that there is NO WORKING STRATEGY for digits. These are random numbers, generated randomly, there is no logic behind these numbers. So you can never win in the game where are no rules at all! As @hotmatrixx said, there is also some X-factor in never let you win consistently.

Yep. that X factor is simply this; because you 'bid' before the trade completes, the Broker knows what will win or lose you the most money and can put any number they want; It's a Syntheic Market, which literally meant 'whatever numbers the broker wants to make up'
