### ISSUE TITLE
PSA: Fresh install of Firefox VS Chrome

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2408]
so, if you're regular here, you'll know that I've recently been a bit more aggressive about posting bugs.
and, my PC has been hanging a lot.

I've been blaming the internet (it's been unreliable here), inrta codeing loops.. all kinda things, but...

I've had issues witn trades hanging - never closing, or taking 10 minutes to close on a 3 minute trade, etc....

I installed FF and Chrome fresh after trying a VM out that ran chrome.
same PC, same page, same script, started at the same time.

The Chrome one opened and closed trades perfectly, on the 3 minute mark every time.
The one in FF hung and never opened a trade.
Here's the difference.

![Capture](https://user-images.githubusercontent.com/49715381/73718293-f4ff9d00-4780-11ea-9763-7a243031e524.PNG)

**Comment by thommmaz** [comment]
I have exactly opposite problem - Chrome hangs all the times(mostly because of chrome helper) and then I downloaded Firefox Quantum and I have to tell I haven't seen faster/smoother browser than Quantum.

**Comment by muroyal** [comment]
I prefer chrome..
