### ISSUE TITLE
2 new issues - arrays (Aaron)

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#2413]
I'm presuming that they are bugs in my code, but I am getting 2 new errors that I have not seen before.
I have initialised the lists, and I made a loop that updates the last 5 values in them constantly, for working with averages

I get 2 errors:
![Capture](https://user-images.githubusercontent.com/49715381/73806511-8f69ea00-482e-11ea-8d38-928041cc7f58.PNG)
![Capture](https://user-images.githubusercontent.com/49715381/73806558-ab6d8b80-482e-11ea-9399-d0b22595e12f.PNG)

Thoughts?

It seems to happen on, between,  or after the 5-12th run

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

The array seems to become `undefined` or empty at one point, are you able to share your strategy? 

Regards,
Aaron

**Comment by hotmatrixx** [comment]
hey, really great to see you online, man.
I'm not a fan of sharing my... anything, but sure I'll do ti this time.

the goal of this is to find a 'channel' based on the last few values of the max[open|close] and min[open|close] of the last few candles, then use them like a vertical trendline - if the last ticks breaks the line, then a trend may be starting (it's basically just to find periods of sideways movemnt for someone else)

the 1st two lines 'define empty list' were in my Runonce; but after moving them to my Block2, before the loop, the problem seems to have resolved. 

Sideways loop count was a static variable, set to 5

the candles are +1 because if i didnt want the 'currently open' candle
![Capture](https://user-images.githubusercontent.com/49715381/73807471-76af0380-4831-11ea-8490-61f6d0ea947d.PNG)

**Comment by hotmatrixx** [comment]
after all this all i was doing wat taking their average and comparing to the previous tick, then put/call based on that info.

**Comment by hotmatrixx** [comment]
...if you can't get teh error with that I'll supply the full code.
I just didnt' want to because it's got a lot of my 'normal' stuff in there - custom notify scripts, money management, etc. all well proven.. this is the only new snippet in my base template

**Comment by hotmatrixx** [comment]
were you able to see anything in this?

**Comment by aaron-binary** [comment]
Hey @hotmatrixx,

Could you send the full strategy to my first name @binary.com?

Regards,
Aaron
