### ISSUE TITLE
Oliver velez trading. Rules for forex options ?

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2419]
Is it possible to convert into bot .. 
https://youtu.be/KKWnrlD8cqU

https://youtu.be/xQuEEB6R_k4

https://youtu.be/M8fr0MYgIs4

**Comment by hotmatrixx** [comment]
@muroyal 
without trying ot be rude;
you've been here for a while - I'd have thought you understood it well enough to code you're own by now?

**Comment by muroyal** [comment]
I have posted all this strategies to take the people mood from syntactic to Forex.. 😁

**Comment by hotmatrixx** [comment]
You 'can' program a bot that does something like this; but there is a big difference;
these strategies depend on you being able to hold for an indefinite period of time. Binary, you can't do that, so you'd need a Money Managment strategy in place.

In all honesty, I use a modified version of Oliver's teachings, and those bots are my profitable ones, so yes, it can be done.

**Comment by hotmatrixx** [comment]
> 
> 
> I have posted all this strategies to take the people mood from syntactic to Forex.. 😁

think that's a step in the right direction. I don't know if this is the right forum for that discussion, but I do think that people need to take another look at Forex Instruments; I'm not sure why so many people are so interested in Synthetic Markets; they have no validity in the real world. Maybe it's because of their shorter timeframes; allowing you to lose your money in even faster ways?

**Comment by Martinez222** [comment]
> You 'can' program a bot that does something like this; but there is a big difference;
> these strategies depend on you being able to hold for an indefinite period of time. Binary, you can't do that, so you'd need a Money Managment strategy in place, that will allow you to keep buying and surviving long enough for it to pay off.
> 
> In all honesty, I use a modified version of Oliver's teachings, and those bots are my profitable ones, so yes, it can be done.

Again ..again  & again..Why u keep telling that u have profitable bots?
if you are really honest and have no other hidden interests do not encourage the idea that there are profitable bots ...
All  my respect for the fact that u are helping others, If  u realy have profitable bots keept them!  I pray for you and I wish you to become rich ! Trading with or without robots involves a great risk, the risk of losing what you do not aford to lose.
