### ISSUE TITLE
bot stop running

### ISSUE THREAD

**Issue by apaajadehbos** [binary-com/binary-bot#242]
can someone help me please, i am new here.
this is happen always. 
i start my bot at night, and i see in the morning 5 windows of my bot always stop playing. i have checked also Restart on Errors, but it doesn't work. what should i do please?

**Comment by aminmarashi** [comment]
Does our [beta version](bot.binary.com/beta/bot.html) have the same problem for you?

**Comment by karing-sidikalang** [comment]
i will try sir. thanks

**Comment by karing-sidikalang** [comment]
can i use my real account with this website ??

![1](https://user-images.githubusercontent.com/28832596/26912386-246b4b5c-4c3e-11e7-8b97-697e8976cbbe.jpg)

**Comment by aminmarashi** [comment]
I wouldn't recommend you to do so.

**Comment by karing-sidikalang** [comment]
@aminmarashi  when would you launch the beta version, it would be more stable?? and i hope we can add sound when start purchasing...

**Comment by aminmarashi** [comment]
It's been under development for a while now. Maybe you can try with virtual money first, if your strategy works fine in the beta consistently, you can also try with real money.
We will definitely add the sound notifications in the future.

**Comment by aminmarashi** [comment]
I'm closing this because it's a dupliaction of #158
