### ISSUE TITLE
how do I get the sum of the last digits?

### ISSUE THREAD

**Issue by lxxneonxxl** [binary-com/binary-bot#2420]
![image](https://user-images.githubusercontent.com/57267933/73905122-57ef5200-48af-11ea-9afe-7023fc41bd10.png)
I was able to add up the last two decimal numbers from the two ticks, but faced the difficulty of adding a two-digit number to a Prime.: 15---- 1+5=6

![image](https://user-images.githubusercontent.com/57267933/73905486-7e61bd00-48b0-11ea-873d-647561f10a48.png)

**Comment by hotmatrixx** [comment]
you have to treat the last digit as a string, then separate them off as variables, then add them together.

**Comment by lxxneonxxl** [comment]
> Вы должны рассматривать последнюю цифру как строку, затем отделять их как переменные, а затем складывать их вместе.

thanks for the hint. I did it
