### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by mad345** [binary-com/binary-bot#2421]
I got this error when running `console.log(Bot)`
TypeError: Cannot read property 'data' of undefined
    at C:\Users\10\AppData\Roaming\npm\node_modules\binary-bot\lib\index.js:14078:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
how to fix this? i want to run cli bot

**Comment by hotmatrixx** [comment]
so you're running it local client?
that erorr usually means that you have requested a call on an unspecified variable; most commonly caused by checking a list, but **calling the 11th item in a list that's only 10 items long.**

**Comment by aaron-binary** [comment]
Hey @mad345,

Could you post the JavaScript code you're trying to execute?

Regards,
Aaron

**Comment by mad345** [comment]
Hi @hotmatrixx the bot installed globally with npm.
Hi @aaron-binary at first, I only want to check available methods, variables, etc. so I simply run this only command `console.log(Bot)` from js file referring this example on issue [#1232](https://github.com/binary-com/binary-bot/issues/1232#issuecomment-465283771). 
![logbot](https://user-images.githubusercontent.com/37037798/74117640-f4389200-4bea-11ea-82ec-b490e168341f.jpg)

**Comment by aaron-binary** [comment]
Hey @mad345,

You may check the code that's generated by the bot on the web in `blockly/index.js`, it'll be something like in the gist found here: https://gist.github.com/aaron-binary/f542f90fdd6fedb86d33ae7a47222425 Some of those blocks are required to initialise the `Bot` class, in the gist I've added the default blocks.

Regards,
Aaron
