### ISSUE TITLE
How to protect script? My strategy ? i want sale or rent my bot with protect My Code?

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2422]
How to protect script? My strategy ? i want sale or rent my bot with protect My Code?
can inject my code to exe?
or remote location my code?
help me this 
thanks

**Comment by hotmatrixx** [comment]
You can't, normally. But there is a way to partner with binary.com where they act as a reseller of your scripts. I can't remember how to get involved with that, but try looking up FAQ's on their website, it might have something there.

**Comment by virtusasys** [comment]
thank you @hotmatrixx  ill try to find

**Comment by virtusasys** [comment]
how to find reseller? i google it .. cant find yet... how can i trust them? please give me a idea... or contact by email //singithiml@gmail.com
thanks..

**Comment by trident2005** [comment]
@virtusasys You cannot place any security on your scrypt XML, if you want to protect your strategy with the intention of selling or renting, you need to create an application from a programming language like VISUAL BASIC and use the binary.com API, you need to learn how to do it. Otherwise, if your strategy is so good because you simply do not use it?

**Comment by virtusasys** [comment]
yes.. i want to learn .. its my own indicator.. thats why i protect that. just need some quck money. that y i want sale or rent that..  is it very hard to create with visual basic? i just want this indicator protect

**Comment by muroyal** [comment]
@virtusasys can you please show me real account results ?

**Comment by virtusasys** [comment]
are u programmer..please send me a mail.. @muroyal

**Comment by muroyal** [comment]
evaroyal84@gmail.com

**Comment by virtusasys** [comment]
help me this ///thanks
