### ISSUE TITLE
Can you solve this? Please help

### ISSUE THREAD

**Issue by cunk888** [binary-com/binary-bot#2425]
My bot is always stop with nothing notice.. running in higher lower. .. how to solve this?

**Comment by hotmatrixx** [comment]
where is it stopping exacty; mid trade, after trade, does it complete a trade and not run a new one....
it might be a lot easier to ehlop out if you either posted a screenshot of your code or uploaded it (you need to  save it in .zip format if you want to post it in here
)

**Comment by hotmatrixx** [comment]
does it 'stop' as in, you have to press 'play' again (in other words, you need to put a 'trade again' into block 4) or hang (caused by a nested loop, or bad internet)
