### ISSUE TITLE
blue blue blue red

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2426]
hello can anyone build a robot rise / fall

the robot will open the deal rise when the last numbers appear 3 blue and one red in a row

**Comment by hotmatrixx** [comment]
so... this?
![Capture](https://user-images.githubusercontent.com/49715381/74072890-45bb1280-4a6d-11ea-9adc-c849ea90a24f.PNG)

**Comment by hotmatrixx** [comment]
easy
https://github.com/hotmatrixx/binary.com.public/tree/master/other.users

**Comment by saarsalu** [comment]
> so... this?
> ![Capture](https://user-images.githubusercontent.com/49715381/74072890-45bb1280-4a6d-11ea-9adc-c849ea90a24f.PNG)

I Mean in dicits
![Capture](https://user-images.githubusercontent.com/30391002/74082390-0cc97080-4a62-11ea-8614-c1d474f69816.PNG)

**Comment by novasugi88** [comment]
> hello can anyone build a robot rise / fall
> 
> the robot will open the deal rise when the last numbers appear 3 blue and one red in a row

actually I've use this logic for others rf bot sir,may be it would help you a little

**Comment by saarsalu** [comment]
> > hello can anyone build a robot rise / fall
> > the robot will open the deal rise when the last numbers appear 3 blue and one red in a row
> 
> actually I've used this logic for others rf bot sir,may be it could help you some
> 
> [RF text spot 4 pattern.zip](https://github.com/binary-com/binary-bot/files/4174082/RF.text.spot.4.pattern.zip)

nice one can you ade martincale step for this?
