### ISSUE TITLE
How can I detect the "Low momentum market" for stays In trading ?

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2427]
How can I detect the "Low momentum market" for stays In trading

**Comment by hotmatrixx** [comment]
try bollinger bands, period 10, deviation 1.
if candles' open and close is inside the Deviation Limits, then you're probably in a channel.

**Comment by freedayz04** [comment]
> try bollinger bands, period between 10 - 20 , deviation 1.
> if candles' open or close is inside the Deviation Limits, then you're probably in a channel.

Thank you so , ฺBut can you show me how can I detect the candles open or close is inside the Deviation Limits
