### ISSUE TITLE
Compound profits/Loss 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2429]
Hourly Profit target 3$
Stop Loss : 6 $

IF Target achieved 

1) Run bot after 1 hour 
2)Next target=Balance +3$

IF Stop loss trigger

1) Run Bot after 1 hour
2)Next target= Balance+3$

**Comment by hotmatrixx** [comment]
come one, I'm sure you can do this.

**Comment by muroyal** [comment]
I will do it and post here.. 
@hotmatrixx  there are very less forex bots available I need you help to create some strategies..

**Comment by sohailsb** [comment]
> I will do it and post here..
> @hotmatrixx there are very less forex bots available I need you help to create some strategies..
> 
> I have checked repository and haki nashi candles xml not loading..

we are waiting
