### ISSUE TITLE
Trade again without checking margins in block 2

### ISSUE THREAD

**Issue by mwmwmwmwmw** [binary-com/binary-bot#243]
Hi everyone,

I am trying to build my binary bot example, but I have problem with one thing. 

Is it possible to have prescription: if results is loss, do trade again immediately  (or in one second) without checking block  Watch and purchase your contract? For example If I lost a trade I want to run new trade without waiting to reaching margins for RSI and SMA in 2nd block,.. (see below on picture)

I am trying with this but I have no idea what to do next.
![trade again](https://user-images.githubusercontent.com/29285264/26942037-e929c792-4c80-11e7-9da1-80c232b32a16.png)

Does anyone has any suggestion/solution?

**Comment by aminmarashi** [comment]
Please note that nothing will run after the `Trade Again` block.
You can define a variable and act upon it:
<img width="317" alt="screen shot 2017-07-03 at 5 53 28 pm" src="https://user-images.githubusercontent.com/6560964/27787765-8f5b0a9a-6018-11e7-8e3b-4bb7b5237d50.png">
