### ISSUE TITLE
Bot running 24/7 - how to avoid to stop automatically?

### ISSUE THREAD

**Issue by yorkinvest** [binary-com/binary-bot#2430]
Hi
How can I run a bot at https://bot.binary.com/, 24/7 without the bot automatically stopping out?
After a while this happens to me every time and if I user Martingale with high progression is this very dangerous.

Can please someone helps me?

Many thanks in advance!

**Comment by thommmaz** [comment]
> 
> 
> Hi
> How can I run a bot at https://bot.binary.com/, 24/7 without the bot automatically stopping out?
> After a while this happens to me every time and if I user Martingale with high progression is this very dangerous.
> 
> Can please someone helps me?
> 
> Many thanks in advance!

You can't avoid it. There are always some bugs from broker side. Connection lost, system update/upgrade, rate limit errors and more... Martingale bots are very dangerous and I would never let them run in a bot. Very common thing is that bot stops just in the moment where martingale stake is high and you can't blame nobody. Broker sees exactly what is inside your bot and how it acts.
