### ISSUE TITLE
I need help binary bot

### ISSUE THREAD

**Issue by shafikgh** [binary-com/binary-bot#2435]
Hello 
I have bot and i need to upgrade and add
* if lose 4 times in a row 
  (one after another ) pause and wait until the live candel finished
 and restart with a new one.

Could you help ?
Thanks.

**Comment by Martinez222** [comment]
Try this : 
![exem](https://user-images.githubusercontent.com/39260368/74127760-36120a00-4be4-11ea-98d9-2601ac3b7009.jpg)

**Comment by shafikgh** [comment]
> Try this :
> ![exem](https://user-images.githubusercontent.com/39260368/74127760-36120a00-4be4-11ea-98d9-2601ac3b7009.jpg)

Thank you so much 
Actually i couldn't create it 
I attached the bot 
Could u please create it

**Comment by shafikgh** [comment]
[YARAB BOT.zip](https://github.com/binary-com/binary-bot/files/4180021/YARAB.BOT.zip)

**Comment by Martinez222** [comment]
:)
Here u go :
[Yarab Bot Var.zip](https://github.com/binary-com/binary-bot/files/4180228/Yarab.Bot.Var.zip)

**Comment by shafikgh** [comment]
> :)
> Here u go :
> [Yarab Bot Var.zip](https://github.com/binary-com/binary-bot/files/4180228/Yarab.Bot.Var.zip)

Great 👍👍👍 
Amazing man 
Thank you so much

**Comment by shafikgh** [comment]
> > :)
> > Here u go :
> > [Yarab Bot Var.zip](https://github.com/binary-com/binary-bot/files/4180228/Yarab.Bot.Var.zip)
> 
> Great 
> Amazing man
> Thank you so much
