### ISSUE TITLE
Technical Tools Can we Use to Measure Momentum 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2436]
Rate of Change
The rate of change is the speed at which a variable changes over a specific period of time. It is expressed as a ratio between a change in one variable relative to a corresponding change in another. Graphically, the rate of change is represented by the slope of a line and mathematically as the percentage change in value over a specific period of time and represents the momentum of a variable.

To calculate the ROC, one takes the current value of a stock and divides it by the value from a previous period, then subtracts one and multiplies by 100 for the percentage figure.

Rate of Change = [(Current Value of Stock/Previous Value of Stock) - 1]*100

A security with a high momentum has a positive ROC and outperforms the market in the short term whereas a low momentum security has a negative ROC and is likely to decline in value, which can be seen as an indicator to sell.

I have tried like below to get forex price.. 

![image](https://user-images.githubusercontent.com/32416314/74117210-ed0a8780-4bdc-11ea-893c-17c42fabc205.png)

**Comment by hotmatrixx** [comment]
this is best used over longer periods than the length of the candle you're using; it should be (period1) - / (Period 2) to give a more stable idea over time, as the last tick can be quite volitile. and depending on the mement you run the script, can give quite faried results.

I'd be more inclined to use candle 3/candle 2 or something similar., and I'd hardly use the 'current price' as a reliable trend indicator, personally. 

I can't comment too much, however, as I prefer stocks with a clear rise/fall pattern emerging.

**Comment by muroyal** [comment]
Yes I have tried with period but is lagging more time to get hence we can
use previous candle close and pervious 2nd candle close..
