### ISSUE TITLE
Binary.com PRICE MANIPULATION WITH PROOF

### ISSUE THREAD

**Issue by thommmaz** [binary-com/binary-bot#2444]
Look what I got this morning - vol50 index on bot and on MT5

And you think that you can beat the broker with some bot :D :D lol

![binary com manipulation](https://user-images.githubusercontent.com/40931373/74130855-c273fb00-4beb-11ea-89cb-5851225e0062.png)

Another one:

![binary com manipulation1](https://user-images.githubusercontent.com/40931373/74131098-46c67e00-4bec-11ea-8a40-d37f19dea68a.png)

**Comment by thommmaz** [comment]
Looks like it never ends... How many price differences in 10 minutes... jesus..

![binary com manipulation2](https://user-images.githubusercontent.com/40931373/74131462-074c6180-4bed-11ea-97f2-969f2aeaf382.png)

**Comment by saarsalu** [comment]
is it not against the law?
where you could show things like that

**Comment by saarsalu** [comment]
@anton-binary 

What do you have to say about it?

**Comment by saarsalu** [comment]
![Screenshot (353)](https://user-images.githubusercontent.com/30391002/74169699-6a151b80-4c34-11ea-9ed7-0f7883749a10.png)

**Comment by saarsalu** [comment]
![Screenshot (353)_LI](https://user-images.githubusercontent.com/30391002/74169764-8749ea00-4c34-11ea-894f-44cc8f5e6fd3.jpg)
so what do we have here?

**Comment by saarsalu** [comment]
This is called a different supplier of quotes!  Binary - FXCM

**Comment by hotmatrixx** [comment]
Volitile spreads on differing brokers, there will be a discrepency.
Try it with an "actual" forex instrument.

you'll get theis between brokers, no matter who they are. it's called spread, and they are allowed to do it; you might even notice that the BO quotes are 0.0100 higher than MT5 - they have to make a margin at some point.

**Comment by aaron-binary** [comment]
Hey @thommmaz,

It looks like you're comparing the WebSocket feed with the TradingView feed. They may sometimes differ due to their timing, however their historical data will match.

Regards,
Aaron

**Comment by nelson-trader** [comment]
> 
> 
> Look what I got this morning - vol50 index on bot and on MT5
> 
> And you think that you can beat the broker with some bot :D :D lol
> 
> ![binary com manipulation](https://user-images.githubusercontent.com/40931373/74130855-c273fb00-4beb-11ea-89cb-5851225e0062.png)
> 
> Another one:
> 
> ![binary com manipulation1](https://user-images.githubusercontent.com/40931373/74131098-46c67e00-4bec-11ea-8a40-d37f19dea68a.png)

YOU POSTED FAKE EDITED PHOTOS. YOUR MARKED CANDLE DOESNT MATCTH CLOCK TIME FOR BOTH SIDE EAC OF THEM EDITED AND FAKE. YOU MUST BE PUNISHED TO MISSGUIDE PPL

**Comment by nelson-trader** [comment]
> 
> 
> Look what I got this morning - vol50 index on bot and on MT5
> 
> And you think that you can beat the broker with some bot :D :D lol
> 
> ![binary com manipulation](https://user-images.githubusercontent.com/40931373/74130855-c273fb00-4beb-11ea-89cb-5851225e0062.png)
> 
> Another one:
> 
> ![binary com manipulation1](https://user-images.githubusercontent.com/40931373/74131098-46c67e00-4bec-11ea-8a40-d37f19dea68a.png)

**Comment by nelson-trader** [comment]
> 
> 
> Look what I got this morning - vol50 index on bot and on MT5
> 
> And you think that you can beat the broker with some bot :D :D lol
> 
> ![binary com manipulation](https://user-images.githubusercontent.com/40931373/74130855-c273fb00-4beb-11ea-89cb-5851225e0062.png)
> 
> Another one:
> 
> ![binary com manipulation1](https://user-images.githubusercontent.com/40931373/74131098-46c67e00-4bec-11ea-8a40-d37f19dea68a.png)

mt5 tick price and binary.com website tick price is always different a little, nothing new here

**Comment by nelson-trader** [comment]
> 
> 
> Look what I got this morning - vol50 index on bot and on MT5
> 
> And you think that you can beat the broker with some bot :D :D lol
> 
> ![binary com manipulation](https://user-images.githubusercontent.com/40931373/74130855-c273fb00-4beb-11ea-89cb-5851225e0062.png)
> 
> Another one:
> 
> ![binary com manipulation1](https://user-images.githubusercontent.com/40931373/74131098-46c67e00-4bec-11ea-8a40-d37f19dea68a.png)

bot analysys not based on mt5
