### ISSUE TITLE
Sorry an error!!!

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2451]
And how you trade if this shit apers in ewry 30 min
![20200213_113343](https://user-images.githubusercontent.com/30391002/74420835-bfc80e80-4e54-11ea-9ab5-79db7c20ee8b.jpg)

@aaron-binary

**Comment by aaron-binary** [comment]
Hey @saarsalu,

Please contact our support team at support@binary.com, they'll inform the right people to look into this. Sorry for the inconvenience!

Regards,
Aaron

**Comment by thommmaz** [comment]
I have seen it years, it's a very common error, support will tell you that clear browser cache, update browser, check network etc...pointless. Just log out and log in again, error should be gone. There is no solution for that, it happens all the time.
