### ISSUE TITLE
How can I add the ADX INDICATOR for my bot and How to use.

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2452]

**Comment by freedayz04** [comment]
[adx.v3.xml.zip](https://github.com/binary-com/binary-bot/files/4198652/adx.v3.xml.zip)

How to use this

**Comment by muroyal** [comment]
I have one more xml file for ADX but i am unable to upload this is given by @saidforex26 
[@indikator.adx (1).zip](https://github.com/binary-com/binary-bot/files/4205381/%40indikator.adx.1.zip)
