### ISSUE TITLE
Bot that executes trades automatically when price met

### ISSUE THREAD

**Issue by abhiuk** [binary-com/binary-bot#2456]
Hi, can someone create a bot or if it exists already.

I'm looking for a bot to trade forex binary that automatically executes a trade when price is met, like a pending order.

For example - Open USDJPY Call trade end time 10:00 GMT if price hits 108.00 

& in case price doesn't hit 108.000 by 10 GMT then trade gets canceled / invalidated.

**Comment by muroyal** [comment]
https://github.com/binary-com/binary-bot/issues/2318 you can use this thread add additional last tick condition for price validation...
