### ISSUE TITLE
Anybody have this xxxx-xZ based bot??

### ISSUE THREAD

**Issue by trident2005** [binary-com/binary-bot#2459]
It has become something popular, but very expensive for a strategy without much sense, I want to try it for a long time to see how good it is

https://www.youtube.com/watch?v=Gsx3-SwNwQg

**Comment by ZDEGLET** [comment]
НЕ ЗАНИМАЙСЯ ЕРУНДОЙ!!!
Я ЕГО ТЕСТИРОВАЛ. ПОЛНАЯ ЧУШЬ. ДЕНЕГ НА СЧЕТУ НЕ ХВАТИТ.

**Comment by trident2005** [comment]
You bought it??  I have a copy but I don't know how to make it work

**Comment by aaron-binary** [comment]
We love the open sharing of knowledge, but we don't encourage advertising and selling your applications here. This repository is used to help others, report issues, request new features, etc.

We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today.

You can also contact marketing@binary.com to learn more about partnership options.
