### ISSUE TITLE
Help: If lost, wait for X sec...

### ISSUE THREAD

**Issue by unzer** [binary-com/binary-bot#246]
Hi All!

What I need, maybe is simple, but i tried and failed...

If The Result is Loss > Wait 420 sec... 
   > So, when the time is over, It will be a new candle... 
         > After the 420 sec, I don't want purchase again, unless the signals of my contract are true again...

Is it possible?

**Comment by BotBrazil** [comment]
![Uploading ima
![pause](https://user-images.githubusercontent.com/29413757/27104981-419ac778-5064-11e7-9562-8ff824c3fe92.png)
ge.png…

**Comment by unzer** [comment]
Tks a lot!

Em 13 de jun de 2017 6:15 PM, "BotBrazil" <notifications@github.com>
escreveu:
