### ISSUE TITLE
BB % indicator Forex 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2462]
I am just updating this strategy if anyone interested we can work out on it.  

https://github.com/binary-com/binary-bot/issues/1749

**Comment by muroyal** [comment]
@hotmatrixx @saidforex26 Can you help me 
How to get BB% min value is less than <-2.5  from 5 candles low 
BB % max value is > 1.2 from 5 candles High.

**Comment by saidforex26** [comment]
> 
> 
> @hotmatrixx @saidforex26 Can you help me
> How to get BB% min value is less than <-0.2 from 5 candles low
> BB % max value is > 1.2 from 5 candles High.

[BB % @muroyal.zip](https://github.com/binary-com/binary-bot/files/4211100/BB.%40muroyal.zip)

**Comment by muroyal** [comment]
@saidforex26 thanks for your help . I have modified it little bit. I am planing to keep MACD or Stockitstics to confirm the trade But at present one is giving good results . I have many martingales But if you have any better one please add it. 

The trades should be like CALL PUT CALL PUT like that first trade should not repeat next. 

If the failures repeat 2 time the trades should stop for 15 minutes.

**Comment by saidforex26** [comment]
> 
> 
> @saidforex26 thanks for your help . I have modified it little bit. I am planing to keep MACD or Stockitstics to confirm the trade But at present one is giving good results . I have many martingales But if you have any better one please add it.
> 
> But my Main strategy not fulfilled.. Need to verify last candle or from two candles need to verify the bb% is met the condition or not :)
> 
> The trades should be like CALL PUT CALL PUT like that first trade should not repeat next.
> 
> If the failures repeat 2 time the trades should stop for 15 minutes.
> [BB % bot v1.0.zip](https://github.com/binary-com/binary-bot/files/4212360/BB.bot.v1.0.zip)

please send your modification results back you. I will do your backtes strategy with past data. we see the results what can last a long time

**Comment by muroyal** [comment]
Please find final configurations It seems this is valid for high probability results. 
[BB % bot MACD Murali Base @muroyal v2.1.zip](https://github.com/binary-com/binary-bot/files/4213344/BB.bot.MACD.Murali.Base.%40muroyal.v2.1.zip)

**Comment by muroyal** [comment]
@saidforex26  I have sent email to you
