### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#2463]
HELP
BLOCK NEEDED = 100 TRANSACTIONS.
THEN THE ROBOT STOPS.

**Comment by muroyal** [comment]
![image](https://user-images.githubusercontent.com/32416314/74662226-83cbdb00-51bf-11ea-9af2-89b83c4e12c5.png)

**Comment by ZDEGLET** [comment]
ok:)

**Comment by ahmadhus** [comment]
@ZDEGLET  

sad story , you nwwd help now .
