### ISSUE TITLE
Binary Corrija esse erro , na plataforma

### ISSUE THREAD

**Issue by Goncalves2020** [binary-com/binary-bot#2465]
Já fazem 3 dias que os clientes que utilizam os Bots na modalidade Par/Impar estão tendo esse erro na plataforma, com qualquer bot par ou impar que tenha estratégia de mudar de par para impar no decorrer da operação, todos estão apresentando esse erro, não me venham dizer que o erro é no meu bot, pois eu já testei mais de 5 bots de pessoas diferentes e todos estão com esta erro.

![erro par impar](https://user-images.githubusercontent.com/56326689/74685741-27ac8b00-51ae-11ea-880c-4402954df824.jpg)

**Comment by gustavolima2019** [comment]
@aaron-binary  Veja este erro por favor....

**Comment by aaron-binary** [comment]
Hey @Goncalves2020,

We're looking into this, thank you for opening an issue here. Will update you once we know more asap.

Regards,
Aaron

**Comment by Goncalves2020** [comment]
Ok I just sent it to your email. Now all bots in all trading modes are making the same mistake!
