### ISSUE TITLE
BITTE UM HILFE! Martingale BOT

### ISSUE THREAD

**Issue by Blacky84** [binary-com/binary-bot#247]
Guten Tag Leute!
Ich möchte gerne ein Martingale Bot erstellen mit den Nachsetzten von der Zahl 1,4,12 Dollar und nach Gewinn wieder auf 1!
Es funktioniert bis jetzt leider nicht!
Nach Verlust macht er einen Trade mit 4 und bleibt immer auf Amount 4 und nicht auf 12?

Was muss ich tun um die Reihenfolge zu setzten 1,4,12 nach Gewinn 1!

Sehen Sie mein Bild von meinem Binary Bot.
![binary bot](https://user-images.githubusercontent.com/29401415/27088116-204952cc-5057-11e7-83df-b09b322c624a.JPG)

Wäre sehr Dankbar um schnelle Hilfe..

Gruß
Blacky84

**Comment by TECHNUMB** [comment]
try this just rename .txt file to .xml
[binary-bot-stake1-4-12.txt](https://github.com/binary-com/binary-bot/files/1072037/binary-bot-stake1-4-12.txt)

**Comment by Blacky84** [comment]
Hallo TECHNUMB.
Ich kann leider mit der .txt Datei nichts anfangen! Können Sie mir genauere Infos geben?
Gruß

**Comment by Blacky84** [comment]
Ich möchte ein einfaches System erstellen!! 
Nach Verlust Trade Amount "X"
Nach Verlust Trade Amount "X"
Nach Verlust Trade Amount "X"
Nach Gewinn Trade Amount wieder auf Anfang 1

Wie erstelle ich so einen Bot??

DANKE

**Comment by Blacky84** [comment]
Hier ein Beispiel von meinen Problem...
Der Trade bleibt in der Amount 4 Schleife und geht nicht weiter auf Amount 12

![2](https://user-images.githubusercontent.com/29401415/27098445-dbc0522e-5077-11e7-9f90-237231ddc74c.JPG)

**Comment by Blacky84** [comment]
Hier die Nachsetz Trades....
![3](https://user-images.githubusercontent.com/29401415/27098622-851bf670-5078-11e7-9ffb-bc34c3866da0.JPG)

**Comment by TECHNUMB** [comment]
![static](https://user-images.githubusercontent.com/29121397/27140729-45c9539c-50f4-11e7-8a76-e8492117ac70.jpg)

**Comment by TECHNUMB** [comment]
[bi.zip](https://github.com/binary-com/binary-bot/files/1075110/bi.zip)

**Comment by TECHNUMB** [comment]
Wenn du mehr für martingale mehr haben möchtest
![static2](https://user-images.githubusercontent.com/29121397/27141654-c7dbb9d6-50f6-11e7-8751-26713f46d1af.jpg)

**Comment by Blacky84** [comment]
Vielen vielen Dank TECHNUMB
Der Auto Bot funktioniert SUPER..:!!

DANKE für deine Hilfe..... 👍 🥇 💯%
