### ISSUE TITLE
Need help with 2nd step martingale 

### ISSUE THREAD

**Issue by akilan007** [binary-com/binary-bot#2473]
Hi,
I need to run martingale after 2nd loss only. any idea how to do in binary bot ?

thanks

**Comment by Martinez222** [comment]
Try martingale block from bere :+1: 
https://github.com/Fruitfella/ROBOT-binary/issues/35.It has aption to start after x loses..

**Comment by akilan007** [comment]
> t a

i will check and let you know thank you
