### ISSUE TITLE
Binary bot strategy

### ISSUE THREAD

**Issue by shemhazais** [binary-com/binary-bot#2478]
Hi. 
I need help.
How can i make a simple strategy forex eur/usd. Only double the ammount if i lose and return back to the main ammounnt when i win. I try to many strategy but its not for my country. I am from Greece. Anyone can help me. Thanks all

**Comment by muroyal** [comment]
@shemhazais I think you are new to binary.com Please don't trade directly on real account. study and get some knowledge first 

Please read below URl article you will get some details about your money management 

https://github.com/Fruitfella/ROBOT-binary

**Comment by shemhazais** [comment]
> 
> 
> @shemhazais I think you are new to binary.com Please don't trade directly on real account. study and get some knowledge first
> 
> Please read below URl article you will get some details about your money management
> 
> https://github.com/Fruitfella/ROBOT-binary

Thanks muroyal. I will take a look on your link!!!

**Comment by Kosta92** [comment]
What you want to do with the money (double on loss, initial stake on win) is called the **Martingale strategy** or **Martingale system**. You can add it to your bot by integrating the script called _FRUITFELLA's Martingale Ver.3.0_ that the user Fruitfella made in the page muroyal gave you.

**Comment by shemhazais** [comment]
Hi.
Thanks on your response.
My problem is that i am from Greece and when i load an file,
always the system says that its not available in my country.
What  i must do for that?

Στις Πέμ, 20 Φεβ 2020 στις 1:31 μ.μ., ο/η Kosta92 <notifications@github.com>
έγραψε:

**Comment by shemhazais** [comment]
I got it. Now i try to Setup it !

Στις Πέμ, 20 Φεβ 2020 στις 2:03 μ.μ., ο/η shemhazais shemhazais <
shemhazais@gmail.com> έγραψε:

**Comment by muroyal** [comment]
You can purchase VPS and try to trade on it data center chnge to some other location where binary.com support

**Comment by LowKey22** [comment]
Hey how did you solve the problem with country denial?? greetings
