### ISSUE TITLE
Given candle list is not valid , Please help

### ISSUE THREAD

**Issue by Max-Profit** [binary-com/binary-bot#2482]
Hello
I have a bot , and i got this error sometimes : **Given candle list is not valid**
please help me
@binary-ex-machina  @muroyal
![Given Candle](https://user-images.githubusercontent.com/57646685/74916702-91f64300-53db-11ea-9c1b-b99db3665eae.jpg)
[Presh-CP Bot-Normal-Martingale-Fixed---1.zip](https://github.com/binary-com/binary-bot/files/4229712/Presh-CP.Bot-Normal-Martingale-Fixed---1.zip)

**Comment by ahmadhus** [comment]
..

**Comment by ahmadhus** [comment]
.

**Comment by Martinez222** [comment]
My friend what îs your strategie?Cross Macd...Cross Ema?:)

**Comment by muroyal** [comment]
@Max-Profit 

Please try like below removed direction up function check it how to us 

![image](https://user-images.githubusercontent.com/32416314/75070847-1bac2a80-551a-11ea-85c9-37a1e9a234f5.png)

**Comment by Martinez222** [comment]
if u need macd cross please use @muroyal  code #2475

**Comment by Max-Profit** [comment]
> @Max-Profit
> 
> Please try like below removed direction up function check it how to use
> 
> ![image](https://user-images.githubusercontent.com/32416314/75070847-1bac2a80-551a-11ea-85c9-37a1e9a234f5.png)

Thanks a Lot , it works now

**Comment by ahmadhus** [comment]
@Max-Profit 

brother what is your recommended balance ? 
and you are trading on volatility or forex or what ? 
thanks

**Comment by Max-Profit** [comment]
> @Max-Profit
> 
> brother what is your recommended balance ?
> and you are trading on volatility or forex or what ?
> thanks

it was good on first hours , but after that change to very bad and blew my account , do not use it

**Comment by ahmadhus** [comment]
@Max-Profit 

thanks for your replay , 

do you have another bot .?
