### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by emtecetr** [binary-com/binary-bot#2486]
Pls someone help me building bot with working strategy i  am using in manual trade but it is so hard like that . : we count 9 times odd in a row and then buy even from 0.35 if win next trade coilunt again if lose continue buying with martingale 2.1 every tik until we win . I count max 14 times odd or even in row. And oposit too with even. Thank you all . You gonna save my eyes and head if someone helps me.

**Comment by saidforex26** [comment]
what volatility index

**Comment by Max-Profit** [comment]
here you are , please share your results , my email is babakfbs@gmail.com
[9-Even-Odd.zip](https://github.com/binary-com/binary-bot/files/4242432/9-Even-Odd.zip)

**Comment by emtecetr** [comment]
Thank you . Second time works . But for 7 hours it reaches 17 times in row.

**Comment by Max-Profit** [comment]
> Thank you . Second time works . But for 7 hours it reaches 17 times in row.

It is normal , you have to use good money management
