### ISSUE TITLE
What is Binary.com MT5 Demo Server Address ?

### ISSUE THREAD

**Issue by Max-Profit** [binary-com/binary-bot#2487]
Hi
What is Binary.com MT5 Demo Server Address ?

**Comment by saarsalu** [comment]
> Hi
> What is Binary.com MT5 Demo Server Address ?

Binary.com-Demo

**Comment by Max-Profit** [comment]
> > Hi
> > What is Binary.com MT5 Demo Server Address ?
> 
> Binary.com-Demo

Thanks a lot
I can login on my iphone’s MT5 with your given server address , But I can not login on windows MT5

**Comment by saarsalu** [comment]
> > > Hi
> > > What is Binary.com MT5 Demo Server Address ?
> > 
> > 
> > Binary.com-Demo
> 
> Thanks a lot
> I can login on my iphone’s MT5 with your given server address , But I can not login on windows MT5
> The journal message is :
> “ No connection to Binary.com-Demo “

Intresting my pc is connected with this server
![Screenshot_20200224-020244_MetaTrader 5](https://user-images.githubusercontent.com/30391002/75122775-eafafb00-56a9-11ea-931c-9d95410b0d9b.jpg)

**Comment by Max-Profit** [comment]
> > > > Hi
> > > > What is Binary.com MT5 Demo Server Address ?
> > > 
> > > 
> > > Binary.com-Demo
> > 
> > 
> > Thanks a lot
> > I can login on my iphone’s MT5 with your given server address , But I can not login on windows MT5
> > The journal message is :
> > “ No connection to Binary.com-Demo “
> 
> Intresting my pc is connected with this server
> ![Screenshot_20200224-020244_MetaTrader 5](https://user-images.githubusercontent.com/30391002/75122775-eafafb00-56a9-11ea-931c-9d95410b0d9b.jpg)

But you have sent your mobile phone screenshot , i also can connect with my mobile phone , but can not connect with my windows pc MT5

**Comment by saarsalu** [comment]
> > > > > Hi
> > > > > What is Binary.com MT5 Demo Server Address ?
> > > > 
> > > > 
> > > > Binary.com-Demo
> > > 
> > > 
> > > Thanks a lot
> > > I can login on my iphone’s MT5 with your given server address , But I can not login on windows MT5
> > > The journal message is :
> > > “ No connection to Binary.com-Demo “
> > 
> > 
> > Intresting my pc is connected with this server
> > ![Screenshot_20200224-020244_MetaTrader 5](https://user-images.githubusercontent.com/30391002/75122775-eafafb00-56a9-11ea-931c-9d95410b0d9b.jpg)
> 
> But you have sent your mobile phone screenshot , i also can connect with my mobile phone , but can not connect with my windows pc MT5

![image](https://user-images.githubusercontent.com/30391002/75139930-903bc080-56f6-11ea-8f34-5f15969b2954.png)
here you goo pc screan

**Comment by Max-Profit** [comment]
> > > > > > Hi
> > > > > > What is Binary.com MT5 Demo Server Address ?
> > > > > 
> > > > > 
> > > > > Binary.com-Demo
> > > > 
> > > > 
> > > > Thanks a lot
> > > > I can login on my iphone’s MT5 with your given server address , But I can not login on windows MT5
> > > > The journal message is :
> > > > “ No connection to Binary.com-Demo “
> > > 
> > > 
> > > Intresting my pc is connected with this server
> > > ![Screenshot_20200224-020244_MetaTrader 5](https://user-images.githubusercontent.com/30391002/75122775-eafafb00-56a9-11ea-931c-9d95410b0d9b.jpg)
> > 
> > 
> > But you have sent your mobile phone screenshot , i also can connect with my mobile phone , but can not connect with my windows pc MT5
> 
> ![image](https://user-images.githubusercontent.com/30391002/75139930-903bc080-56f6-11ea-8f34-5f15969b2954.png)
> here you goo pc screan

Thanks a lot for reply 
İ could not login yet
Please help me
