### ISSUE TITLE
Telegram Signals configured -- Running with high winning rate ...

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2491]
Hello All I have created telegram sample bot with binary bot for  forex traders name 

" @Iq options free Signals forex💰💰"

https://web.telegram.org/#/im?p=@chanikyaforex

EUR\USD GBP\USD & USD\JPY..
the bot will generate alerts on forex with my strategy.. 

Thanks
evaroyal84@gmail.com
Telegram I'd : @royal089

**Comment by ZDEGLET** [comment]
Why not write:
1) What should be the minimum amount on the account?
2) How many losses in a row to expect?
3) Do we work with martingale or not?
4)% of the gain from transactions made?
5) How much do you want $ for your labors?
Too many questions arise.

**Comment by muroyal** [comment]
1. What should be the minimum amount on the account? 50$
   2. How many losses in a row to expect? Max 3 is expected.
   3. Do we work with martingale or not? Yes their own decision..
   4)% of the gain from transactions made?  No
   4. How much do you want $ for your labors? 0 I don't want any money..
   5. Too many questions arise.

It is a public group.. I am not interested to take any money...

**Comment by muroyal** [comment]
Heads Off Binary.com Today they have stopped telegram services  :) :)


![image](https://user-images.githubusercontent.com/32416314/75172788-d3784c80-5753-11ea-8e5d-12e481d0064b.png)

**Comment by ZDEGLET** [comment]
Они хотят чтоб ты без штанов и трусов остался!!!

**Comment by muroyal** [comment]
The only way to do battle with Forex

**Comment by eonuoha30** [comment]
> Hello All I have created telegram sample bot with binary bot for forex traders name
> 
> " @iq options free Signals forex"
> 
> EUR\USD GBP\USD & USD\JPY..
> the bot will generate alerts on forex with my strategy..
> 
> Thanks
> [evaroyal84@gmail.com](mailto:evaroyal84@gmail.com)
> Telegram I'd : @royal089

Pls, send me a copy of the bot  via eonuoha30@gmail.com let me take a look at it.

You can also recheck the teleegram API link with the binary website if it was properly done. Because that was the major problem I discovered last time I saw that 'telegram cannot be sent error ' messagw

**Comment by muroyal** [comment]
Initially it was working suddenly it has stopped working

**Comment by muroyal** [comment]
> > Hello All I have created telegram sample bot with binary bot for forex traders name
> > " @iq options free Signals forex"
> > EUR\USD GBP\USD & USD\JPY..
> > the bot will generate alerts on forex with my strategy..
> > Thanks
> > [evaroyal84@gmail.com](mailto:evaroyal84@gmail.com)
> > Telegram I'd : @royal089
> 
> Pls, send me a copy of the bot via [eonuoha30@gmail.com](mailto:eonuoha30@gmail.com) let me take a look at it.
> 
> You can also recheck the teleegram API link with the binary website if it was properly done. Because that was the major problem I discovered last time I saw that 'telegram cannot be sent error ' messagw

How to do it ... I have restarted telegram bot..

**Comment by saarsalu** [comment]
> > > Hello All I have created telegram sample bot with binary bot for forex traders name
> > > " @iq options free Signals forex"
> > > EUR\USD GBP\USD & USD\JPY..
> > > the bot will generate alerts on forex with my strategy..
> > > Thanks
> > > [evaroyal84@gmail.com](mailto:evaroyal84@gmail.com)
> > > Telegram I'd : @royal089
> > 
> > 
> > Pls, send me a copy of the bot via [eonuoha30@gmail.com](mailto:eonuoha30@gmail.com) let me take a look at it.
> > You can also recheck the teleegram API link with the binary website if it was properly done. Because that was the major problem I discovered last time I saw that 'telegram cannot be sent error ' messagw
> 
> How to do it ... I have restarted telegram bot..

wath is telegram Bot?
can you share with me the bot

**Comment by muroyal** [comment]
I have removed permissions to telegram bot hence the bot is not sending alerts ___---- I have fixed it now alerts are generating.

**Comment by muroyal** [comment]
Results 

![image](https://user-images.githubusercontent.com/32416314/75567753-0a15d600-5a78-11ea-9f96-68fc1f636caa.png)

**Comment by muroyal** [comment]
Results :+1: 
![IMG_20200228_221436_804](https://user-images.githubusercontent.com/32416314/75674903-12eeed80-5cac-11ea-844a-d2d1d93cfa09.jpg)

**Comment by Craziestar36** [comment]
I have joined but I can`t see the bot anywhere

**Comment by muroyal** [comment]
Please message me @royal089

**Comment by muroyal** [comment]
![image](https://user-images.githubusercontent.com/32416314/76417394-cfd6fd80-63c2-11ea-821d-ec1c50c16b06.png)

**Comment by muroyal** [comment]
https://t.me/joinchat/I3I5E0VxbTsP9Ot4FvbuDg
