### ISSUE TITLE
Break time after 5 win trade

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2492]
anybody code, 5 minute bot trading stop after 5 win trades.
with best regards

**Comment by Martinez222** [comment]
5 wins in a row?

**Comment by navneetsinh** [comment]
> anybody code, 5-minute bot trading stop after 5 winning trades.
> with best regards

![Break time after 5 win trade #2492](https://user-images.githubusercontent.com/42480287/75282617-5f16d980-5837-11ea-82bb-77dbbbd6cbbe.png)

**Comment by sohailsb** [comment]
> > anybody code, 5-minute bot trading stop after 5 winning trades.
> > with best regards
> 
> ![Break time after 5 win trade #2492](https://user-images.githubusercontent.com/42480287/75282617-5f16d980-5837-11ea-82bb-77dbbbd6cbbe.png)

THANK YOU SO MUCH
