### ISSUE TITLE
Please Help! binary bot Profitable strategy  *-*

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2493]
Dear friends ,

At the beginning and so far I have completed two years in trading and I regret to tell you that I lost all my money,

On the professional level I have two baccalaureate degrees and many international courses, and so far I have not found any work in my certificates,

I have a family and two children, I need as much money as anyone in the world, especially those who face every day a problem with money,

We all know that even if you have the most profitable strategies in the world, you will not be able to raise all the money in the world, and that in the end we are human and have a love for help and humanity,
So please my friends, help me to be able to spend on my family as a man. I would be grateful to you all the time.

binaty option strategy
 Best regards
ahmadhusam112@gmail.com

**Comment by ZDEGLET** [comment]
Печальная история:( 
Таких в мире миллионы. Такова жизнь.

**Comment by ahmadhus** [comment]
@ZDEGLET
All respect to your opinion ,

**Comment by ZDEGLET** [comment]
@ahmadhus 
I have been on this forum for over 3 years. I have not seen anyone lay out a profitable strategy.

**Comment by ahmadhus** [comment]
@ZDEGLET 

that looks strange little bit,  is it right that no one have a good strategy !!
i can't image this idea because by looking at the video on YouTube they have enormous balance !! from where they gain it , 
that's why until know am trying and looking forward to have a profitable strategy .

i do not know maybe iam looking on the wrong way ..
 thanks for your replay .

**Comment by thommmaz** [comment]
> @ZDEGLET
> 
> that looks strange little bit, is it right that no one have a good strategy !!
> i can't image this idea because by looking at the video on YouTube they have enormous balance !! from where they gain it ,
> that's why until know am trying and looking forward to have a profitable strategy .
> 
> i do not know maybe iam looking on the wrong way ..
> thanks for your replay .

If you are looking youtube videos then look these videos carefully. Most of them are demo accounts, videos are faked to show them as real accounts and so on. Youtube is full of scammers. I've been following one russian forum about binary bots. They have tried many years to create successful bot but all their bots have failed sooner or later. There are thousands of bot but none of them will give you money in real account. Forget binary bots and start learning binary option or forex trading. Why people think that they can beat computer?

**Comment by ahmadhus** [comment]
@thommmaz 

that is right 100% 
so should we stop trying or what should we do ?

and how to make 10$ a day , i do not want thousands number of money

**Comment by Martinez222** [comment]
Hey,try his (first on your demo acc) on major pairs.You will get a few trades per day..
Be awere of news (https://www.investing.com/economic-calendar/)
[Forex for MM.zip](https://github.com/binary-com/binary-bot/files/4250168/Forex.for.MM.zip)

**Comment by cleberscr** [comment]
wow, many people are like you brother, but getting $ 10 dollars a day is a good and fast goal, if you find a good bot, it will give you this result in just 5 minutes ...
