### ISSUE TITLE
50% win rate, >95% payout 

### ISSUE THREAD

**Issue by Eshhh** [binary-com/binary-bot#2497]
Does anyone have a bot with at least 50% win rate with above 95% payout?

Preferably working on rise/fall or touch trade type. Not Digits.

Doesn't necessarily have to be profitable. Thanks

**Comment by ahmadhus** [comment]
.

**Comment by virtusasys** [comment]
i also have.. but its digital under 5 over 4..

**Comment by binary-ex-machina** [comment]
@Eshhh all rise/fall bots are 50% win rate with 95% payout

**Comment by virtusasys** [comment]
https://www.youtube.com/watch?v=ewYQAXjK6M8
i have please check this

**Comment by binary-ex-machina** [comment]
@virtusasys what you have? you know that 250 trades on virtual are not even considered for statistics right?

**Comment by virtusasys** [comment]
Yes I know.. but you don't understand long time running problems @binary-ex-machina .  CPU over heat and getting shutdown.. high memory usage. Bot getting slow. Ram usage is too high.. how to record long videos.. ??

**Comment by virtusasys** [comment]
I don't you what u say.. bit my method is afrlter few hours lap restart.

**Comment by binary-ex-machina** [comment]
@virtusasys I understand all those external problems you wrote. It's not about record the entire trading, is to record with more than 1000 trades at least, in my opinion. Also virtual account shows that you don't trust your strategy to put with real money, why should I? I just asked about your video, because you said that had a bot rise/fall with payout 95% that has above win rate then 50%.

I can make a bot right now with 90% accuracy, but just on 20 trades. Is that good for me say that I have a bot with winrate above 50%? i don't think so

**Comment by virtusasys** [comment]
Please share your knowledge 90% accurate.. because most people finding like that bot.. and go to my channel and look at real account run.. 1 st trade auto matically sale at market and if lost run next step. Please check

**Comment by binary-ex-machina** [comment]
there is no 90% accuracy with rise fall and it will never have on binary options. Sell at market before the contract expires is not profitable on long run. Again your videos have very few trades, i can't take less than 1000 trades in consideration to say that your bot is different than any other bot on this planet. Also the only real account video you have, you already started with $42, so how we will know that you used that bot? Also you sell bots, if they are good as you try to show, why sell? if they are consistent and you make money with them, is still necessary to make money selling scripts?

My knowledge is this. All rise fall bots have 50% win rate on long run. All strategies that sell at the market are not profitable on long run. When i write long run i mean months using, thousands of trades, not 200

**Comment by virtusasys** [comment]
I already tested more times weeks months . This is 95% win rate bot. I'm satisfy that. Yes I'm selling bots .. but not fake ones .. because I need quick money .. because u doesn't know how people live .. if I live I'll post someday.

**Comment by binary-ex-machina** [comment]
sorry, but it's impossible to believe that you have a 95% win rate bot Rise/Fall. Selling contracts before expire don't make the win rate bigger bro. It's same as using a Higher/Lower bot with a barrier to return very low profit on the trades, it's just doesn't count. I wish you luck. I don't know how you live, but i know about binary options, and when I see someone spreading information that is not true, i like to comment
