### ISSUE TITLE
I want sale my earlier bot .. can you please help m e

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2498]
https://youtu.be/qCpEW2CoMIs
10 usd per hour.. capture by Mobile screen recorder with virtual account.
singithiml@gmail.com

**Comment by sohailsb** [comment]
i have better, low risk, never loss, trading smoothly  for long time

**Comment by ahmadhus** [comment]
@sohailsb 
how much will cost us ?

**Comment by sohailsb** [comment]
> @sohailsb
> how much will cost us ?

i can manage account on 50 percent share, first week free
account must be minimum 50$ balance

**Comment by ahmadhus** [comment]
@sohailsb

how much your bot is profitable ?

and how you will manage the account ?

**Comment by sohailsb** [comment]
> @sohailsb
> 
> how much your bot is profitable ?
> 
> and how you will manage the account ?

minimum double to 4 time in a month and second answer is my headache, how i can manage multiples account, you dont worry

**Comment by thommmaz** [comment]
> https://youtu.be/qCpEW2CoMIs
> 10 usd per hour.. capture by Mobile screen recorder with virtual account.
> [singithiml@gmail.com](mailto:singithiml@gmail.com)

You are trying to sell DEMO bot??? Firstly put that bot on real account!!

**Comment by virtusasys** [comment]
> > https://youtu.be/qCpEW2CoMIs
> > 10 usd per hour.. capture by Mobile screen recorder with virtual account.
> > [singithiml@gmail.com](mailto:singithiml@gmail.com)
> 
> You are trying to sell DEMO bot??? Firstly put that bot on real account!!

This is my earlier bot . I wanted quick money. That's it

This is my new one
https://github.com/binary-com/binary-bot/issues/2476 check this in real account
