### ISSUE TITLE
Money Management Required !!!

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2500]
![image](https://user-images.githubusercontent.com/58647652/75346533-7c988180-58d1-11ea-8234-ca134a6a3bde.png)

[Over4Bot By Freedayz04.zip](https://github.com/binary-com/binary-bot/files/4255780/Over4Bot.By.Freedayz04.zip)

**Comment by ZDEGLET** [comment]
с этим роботом банкрот при любых обстоятельствах.

**Comment by freedayz04** [comment]
> с этим роботом банкрот при любых обстоятельствах.

Sorry , I don't understand. English plz.

**Comment by ZDEGLET** [comment]
with this robot bankrupt under any circumstances.

**Comment by Kosta92** [comment]
Every bot that deals with digits is unprofitable in the long run.

Period.

**Comment by Kosta92** [comment]
There is no money management strategy that can save you from digits going against you. Digits are a losing game, always, without exception.
