### ISSUE TITLE
I AM SUCCESSFUL

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2509]
I am successful trader, if any body want my copy trades, send me your Token of your Demo or Real account, Balance must be as low as 12 Dollar.

**Comment by Max-Profit** [comment]
> I am successful trader, if any body want my copy trades, send me your Token of your Demo or Real account, Balance must be as low as 12 Dollar.

Hi Mate

here is my Token : zpfuru5vtlRCY0S

**Comment by saarsalu** [comment]
> I am successful trader, if any body want my copy trades, send me your Token of your Demo or Real account, Balance must be as low as 12 Dollar.

show me r trades saarsalu46@gmail.com

**Comment by sohailsb** [comment]
> > I am successful trader, if any body want my copy trades, send me your Token of your Demo or Real account, Balance must be as low as 12 Dollar.
> 
> show me r trades [saarsalu46@gmail.com](mailto:saarsalu46@gmail.com)

if you want check my trading, give me, your demo token and follow me, if you satisfied then contact me 
WhatsApp: +923007860567

**Comment by saarsalu** [comment]
> > > I am successful trader, if any body want my copy trades, send me your Token of your Demo or Real account, Balance must be as low as 12 Dollar.
> > 
> > 
> > show me r trades [saarsalu46@gmail.com](mailto:saarsalu46@gmail.com)
> 
> if you want check my trading, give me, your demo token and follow me, if you satisfied then contact me
> WhatsApp: +923007860567

here it is cWERerJ4DQmleQp

**Comment by sohailsb** [comment]
> > > > I am successful trader, if any body want my copy trades, send me your Token of your Demo or Real account, Balance must be as low as 12 Dollar.
> > > 
> > > 
> > > show me r trades [saarsalu46@gmail.com](mailto:saarsalu46@gmail.com)
> > 
> > 
> > if you want check my trading, give me, your demo token and follow me, if you satisfied then contact me
> > WhatsApp: +923007860567
> 
> here it is cWERerJ4DQmleQp

Added

**Comment by saarsalu** [comment]
> +923007860567

r you serios?

> account, Balance must be as low as 12 Dollar.

r you serios. ok its demo but first trade 11 USD and lost so if i cive to you real acount with 12 usd then you allready blow my acount 
![image](https://user-images.githubusercontent.com/30391002/75627497-6b08ef80-5bd9-11ea-8104-65fb0f224acc.png)

**Comment by Max-Profit** [comment]
you have blown my account, how you can call you successfull trader ?

**Comment by saarsalu** [comment]
You fucker 
![Screenshot_20200302-064513_Chrome](https://user-images.githubusercontent.com/30391002/75646186-70098580-5c51-11ea-8f70-7c089afd1ecb.jpg)
Da fuck is this? And this is sucsesfol. R you real moran?
