### ISSUE TITLE
BOT DE TENDENCIA!!!

### ISSUE THREAD

**Issue by alex-net007** [binary-com/binary-bot#2511]
Galera criei um bot de tendência e gostaria da ajuda de vocês pra aprimora-ló!!! 
Esse bot possui um martingale onde cada lance pode ser alterado com o seu valor desejado, dessa forma evita surpresas na hora da operação.

**Comment by alex-net007** [comment]
Como faço pra adicionar o bot aqui???

**Comment by alex-net007** [comment]
**Ai o bot!!!! estou aberto a opiniões!!** 
[Bot-MorFel.zip](https://github.com/binary-com/binary-bot/files/4270723/Bot-MorFel.zip)

**Comment by JenggotSantuy** [comment]
what help do you want

**Comment by alex-net007** [comment]
> que ajuda você quer

gostaria de encontrar o melhor tik(1-tik..2-tik...3-tik) para o bot e se possível adicionar mais algum indicador para ficar assertivo

**Comment by JenggotSantuy** [comment]
primeiro a procurar o melhor carrapato deve ser definitivamente por julgamento

os dois bots não podem ser extraídos

com o que você está jogando contrato

**Comment by JenggotSantuy** [comment]
primeiro a procurar o melhor carrapato deve ser definitivamente por julgamento

os dois bots não podem ser extraídos

com o que você está jogando contrato

**Comment by saarsalu** [comment]
> **Oh the bot !!!! I am open to opinions !! **
> [Bot-MorFel.zip](https://github.com/binary-com/binary-bot/files/4270723/Bot-MorFel.zip)

![image](https://user-images.githubusercontent.com/30391002/75625201-6c7bed00-5bc4-11ea-8136-8e395bc2705b.png)

**Comment by alex-net007** [comment]
[Bot-MorFel1.zip](https://github.com/binary-com/binary-bot/files/4277063/Bot-MorFel1.zip)
