### ISSUE TITLE
Any tips how to avoid this un-successful trades 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2515]
The underlying market has moved too much since you priced the contract. The contract payout has changed from USD1.96 to USD1.85.

Getting above warnings is there any thing can include loops to retry the un successful trades.

1) Is there how to find current trade status.
2) If we have any function to validate the trade then successes if it has failed to place  then we can retry it. 
3) is it possible to customize trade failure retry interval?

@aaron-binary

**Comment by aaron-binary** [comment]
Hey @muyoral,

- We don't consider price movements as critical errors, so the bot will continue executing its logic as long as the **Restart on last trade error** checkbox is checked. When this error is shown to you, the bot will revert to the start of the **Before purchase** scope and run your logic again.
- There is currently no way to customise the retry interval.

Regards,
Aaron

**Comment by muroyal** [comment]
Thanks
