### ISSUE TITLE
@saidforex26 Need one sample ADX indicator bot 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2516]
@saidforex26 . You are helping people here, I saw you have given ADX indicator in your repository. 

Can you please create a ADX sample bot. We are not aware how to use the ADX in our bots. 

Many peoples are waiting for your reply.. 

Thanks 
Muroyal

**Comment by saidforex26** [comment]
please give the strategy that you use using the adx indicator, I will make the bot

**Comment by muroyal** [comment]
Strategy: 

Bollinger Band 20 reached upper (CALL) or lower (PUT) band below. 

ADX indicator value increasing from past three candles and above 30.

![image](https://user-images.githubusercontent.com/32416314/75680908-88f95180-5cb8-11ea-9bbd-216409df9b41.png)

**Comment by saidforex26** [comment]
your strategy uses the list of adx values ​​... please wait I will update the adx indicator again because the previous indicator does not have a list of adx values

**Comment by Max-Profit** [comment]
good strategy

**Comment by muroyal** [comment]
@saidforex26 for array setup if it takes time atlest provide normal one

**Comment by saidforex26** [comment]
Is it like this
[BB MUROYAL.zip](https://github.com/binary-com/binary-bot/files/4293108/BB.MUROYAL.zip)

**Comment by muroyal** [comment]
@saidforex26  Thanks a lot for providing this. Getting error while running it. 

![image](https://user-images.githubusercontent.com/32416314/75987090-50a27f00-5f15-11ea-8984-c57980dd51db.png)
