### ISSUE TITLE
Erro na leitura do Bloco de saída do valor!

### ISSUE THREAD

**Issue by opstrade** [binary-com/binary-bot#2517]
![image](https://user-images.githubusercontent.com/56803963/75789545-9eb65780-5d48-11ea-8d0e-e6f08c34b532.png)

Bloco de resumo não é executado... ! existe alguma forma de eu definir o valor de saida, um numero par ou impar?

**Comment by opstrade** [comment]
quero que se o valor de saida for par, ela faça ou não martingale!  está montado correto, mas o bloco não é executado,! nem mesmo quando monta para notificar...

**Comment by cleberscr** [comment]
Esse martingale está muito estranho mano...

**Comment by azludium** [comment]
Perdi seu contato William , parou de atualizar os bots binary ?
