### ISSUE TITLE
Leave bot and dont wasting ur time!!!! Can explain this?? My proof binary.com is cheating

### ISSUE THREAD

**Issue by cunk888** [binary-com/binary-bot#2518]
This is the reason the bot will never work...
With barrier 0.32 higher lower ... +0.32 but still lose.. hahahha so funny..... This the reason ur bot will never work
![IMG_20200304_010223](https://user-images.githubusercontent.com/59736310/75799965-d73f4b00-5db3-11ea-8c57-14a78e70d579.jpg)

**Comment by cunk888** [comment]
I have proof log summry. And log... Dont wasting ur money man

**Comment by cunk888** [comment]
![Screenshot_2020-03-04-01-13-12-193_com chrome dev](https://user-images.githubusercontent.com/59736310/75800974-5c772f80-5db5-11ea-8c30-bf38d3eb2ba1.png)

**Comment by cunk888** [comment]
![IMG_20200304_011406](https://user-images.githubusercontent.com/59736310/75801044-787ad100-5db5-11ea-80b5-243a9cb96614.jpg)

**Comment by clau167** [comment]
Thx man... Nice work !!!!

**Comment by cunk888** [comment]
@clau167 binary chaange my setting +lower to -lower wkwkwk i have proof log that i never stop the bot

**Comment by cunk888** [comment]
See my setting ![Screenshot_2020-03-04-01-50-26-245_com android chrome](https://user-images.githubusercontent.com/59736310/75804190-93037900-5dba-11ea-8471-208a809babed.png)

**Comment by trident2005** [comment]
I don't know, friend, there are other people who are doing very well in REAL and VIRTUAL

Check this: https://www.youtube.com/watch?v=lkx4eA3F21Y

Maybe it is an error in the server, if it were REAL you can send that operation to audit with customer service

**Comment by cunk888** [comment]
@trident2005  its up to u men... Im just trying to help the others to leave the binary.bot.

**Comment by aaron-binary** [comment]
Hey @cunk888,

Thank you for opening an issue here.

Are you able to provide a detailed explanation of which behaviour isn't working as intended? This will help me identify whether something wrong is going on here. Could you also share your strategy so I can test if it's correctly following your logic?

Regards,
Aaron

**Comment by cunk888** [comment]
@aaron-binary can u explain why binary change my barrier + to -??? I have my proof log. Detail my transactions

**Comment by cunk888** [comment]
I never stop my bot! And the setting i never change

**Comment by cunk888** [comment]
Why change my barrier + to minus my setting lower is + but binary change to - ??? 😅 Good job

**Comment by thommmaz** [comment]
> 
> 
> I don't know, friend, there are other people who are doing very well in REAL and VIRTUAL
> 
> Check this: https://www.youtube.com/watch?v=lkx4eA3F21Y
> 
> Maybe it is an error in the server, if it were REAL you can send that operation to audit with customer service

As you see in this video not all the trades are same, some of them are different because of "who knows".. and this is another reason why bot can work successfully  at some time but not all the time. It is martingale strategy, imagine now if you have 10 step martingale and demo account wins and real account lose. BOTS NEVER BE CONSISTENTLY SUCCESSFUL!

**Comment by trident2005** [comment]
> > I don't know, friend, there are other people who are doing very well in REAL and VIRTUAL
> > Check this: https://www.youtube.com/watch?v=lkx4eA3F21Y
> > Maybe it is an error in the server, if it were REAL you can send that operation to audit with customer service
> 
> As you see in this video not all the trades are same, some of them are different because of "who knows".. and this is another reason why bot can work successfully at some time but not all the time. It is martingale strategy, imagine now if you have 10 step martingale and demo account wins and real account lose. BOTS NEVER BE CONSISTENTLY SUCCESSFUL!

I saw the viedeo again, to detail what you say, I could see that 391 operations 3 were different, considering that they are executed from the same IP I think that could generate some problem, but I saw each entry price and each exit price, and they were the same with the exception of 3, and makes a martingale, but it is a very special martingale, I have not seen any other martingale do that, it is like a hybrid between martingale and oscar grind.

**Comment by trident2005** [comment]
> Why change my barrier + to minus my setting lower is + but binary change to - ??? 😅 Good job

I saw that the administrator asked you a question, I didn't see you answer, you just continued with your argument.

**Comment by saarsalu** [comment]
![Screenshot (481)](https://user-images.githubusercontent.com/30391002/76090832-f3fe9d00-5fc4-11ea-89bb-893ed7d97a29.png)

opend at same time and the price mowing is diferent!!!!!
how da fuck?

**Comment by XiaoYuzu** [comment]
kalo - jadi + itu bisa jadi logic bot lo ada yang salah hadeh

**Comment by binary-ex-machina** [comment]
@cunk888 can you post the bot logic here so we all can check what was the problem?
