### ISSUE TITLE
You can earn on numbers, but martingale can make you bankrupt !!!

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#2525]
![2020-03-04_23-10-51](https://user-images.githubusercontent.com/36106343/75919936-7e34ed00-5e6f-11ea-8cd7-23d6c8f92f43.png)

**Comment by Max-Profit** [comment]
Hi @ZDEGLET 

Please share your bot with me  : babakfbs@gmail.com

i need it , Thanks

**Comment by ZDEGLET** [comment]
Do not look at the beautiful picture, this robot will always be unprofitable. I put it out so that you can draw conclusions on how the situation with the numbers may turn out.

**Comment by Shuckoswaldo** [comment]
Puedes compartir bot. Xml shuckoswaldo@gmail.com
