### ISSUE TITLE
@saidforex26 Virtual loss Strategy

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2527]
Dear Sir, I want to save one martingale with virtual loss,
have your virtual loss strategy.
with best regards.
@saidforex26

**Comment by Max-Profit** [comment]
Hello , please explain more .

**Comment by saidforex26** [comment]
@sohailsb  please share your bot. I add money management

**Comment by sohailsb** [comment]
> @sohailsb please share your bot. I add money management

3 Digit same, Differ strategy
Any four digit same, then wait for trade on first rule every time

**Comment by saidforex26** [comment]
> > @sohailsb please share your bot. I add money management
> 
> 3 Digit same, Differ strategy
> Any four digit same, then wait for trade on first rule every time

[3digit same. los wait 4digit same.zip](https://github.com/binary-com/binary-bot/files/4304748/3digit.same.los.wait.4digit.same.zip)
Please try

**Comment by sohailsb** [comment]
thanks

**Comment by sohailsb** [comment]
> > > @sohailsb please share your bot. I add money management
> > 
> > 
> > 3 Digit same, Differ strategy
> > Any four digit same, then wait for trade on first rule every time
> 
> [3digit same. los wait 4digit same.zip](https://github.com/binary-com/binary-bot/files/4304762/3digit.same.los.wait.4digit.same.zip)
> 
> Please try

Not working according to rules, plz check

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/76185439-349b2800-620a-11ea-80ef-03492db34ba0.png)

**Comment by saidforex26** [comment]
It should be the same as your strategy

**Comment by saidforex26** [comment]
oh it turns out there is a bug with bot.binary.com. the last digit list is different from the tick list. now we cannot use the last digit list because an error occurred

**Comment by sohailsb** [comment]
ok, please make better, this is very nice bot.
and plz add martingale

**Comment by saidforex26** [comment]
I will solve the problem by making a list of the last digits with the block that I have

**Comment by saidforex26** [comment]
the bot should be back to normal. because they have updated it earlier

**Comment by saidforex26** [comment]
please try the bot again and for martinggale you can add it yourself because you have long been in this forum you should be able to create your own martinggale

**Comment by sohailsb** [comment]
> please try the bot again and for martinggale you can add it yourself because you have long been in this forum you should be able to create your own martinggale

thank you very much, I can do my self.
