### ISSUE TITLE
last digits, hellp

### ISSUE THREAD

**Issue by cleberscr** [binary-com/binary-bot#2529]
hello friends, I'm here to ask for a little help, I can only do the strategy of the last digit like that (second photo), but now I want to learn how to get the last 2 digits or more...
Example:

(this I already know) 7,139,145 = last digit ends with 5 = call
(this I want to learn) 8,139,134 = last digits ends with 34 = do put

![Screenshot_2](https://user-images.githubusercontent.com/61013585/76145660-46de6000-606a-11ea-89c7-d32cbd92135a.png)
![Screenshot_1](https://user-images.githubusercontent.com/61013585/76145662-4776f680-606a-11ea-9892-fd9b58656aa8.png)

**Comment by lxxneonxxl** [comment]
https://github.com/lxxneonxxl/THE-LAST-2-DIGITS/blob/master/binary-bot%20(6).xml

**Comment by lxxneonxxl** [comment]
> Привет друзья, я здесь, чтобы попросить небольшую помощь, я могу только сделать стратегию последней цифры (второе фото), но теперь я хочу узнать, как получить последние 2 цифры или больше ...
> Пример :
> 
> (это я уже знаю) 7,139,145 = последняя цифра оканчивается на 5 = вызов
> (это я хочу узнать) 8,139,134 = последние цифры оканчивается на 34 = сделать ставку
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/61013585/76145660-46de6000-606a-11ea-89c7-d32cbd92135a.png)
> ![Screenshot_1](https://user-images.githubusercontent.com/61013585/76145662-4776f680-606a-11ea-9892-fd9b58656aa8.png)

https://github.com/lxxneonxxl/THE-LAST-2-DIGITS/blob/master/binary-bot%20(6).xml

**Comment by cleberscr** [comment]
> > Привет друзья, я здесь, чтобы попросить небольшую помощь, я могу только сделать стратегию последней цифры (второе фото), но теперь я хочу узнать, как получить последние 2 цифры или больше ...
> > Пример :
> > (это я уже знаю) 7,139,145 = последняя цифра оканчивается на 5 = вызов
> > (это я хочу узнать) 8,139,134 = последние цифры оканчивается на 34 = сделать ставку
> > ![Screenshot_2](https://user-images.githubusercontent.com/61013585/76145660-46de6000-606a-11ea-89c7-d32cbd92135a.png)
> > ![Screenshot_1](https://user-images.githubusercontent.com/61013585/76145662-4776f680-606a-11ea-9892-fd9b58656aa8.png)
> 
> https://github.com/lxxneonxxl/THE-LAST-2-DIGITS/blob/master/binary-bot%20(6).xml
> 
> ![image](https://user-images.githubusercontent.com/57267933/76150979-dc0c4380-60c0-11ea-8e5a-4a0776bcf9ee.png)
> 
> This is an example. Change what you want

thank you very much friend, was coming to ask you how to change <3

**Comment by cleberscr** [comment]
> > Привет друзья, я здесь, чтобы попросить небольшую помощь, я могу только сделать стратегию последней цифры (второе фото), но теперь я хочу узнать, как получить последние 2 цифры или больше ...
> > Пример :
> > (это я уже знаю) 7,139,145 = последняя цифра оканчивается на 5 = вызов
> > (это я хочу узнать) 8,139,134 = последние цифры оканчивается на 34 = сделать ставку
> > ![Screenshot_2](https://user-images.githubusercontent.com/61013585/76145660-46de6000-606a-11ea-89c7-d32cbd92135a.png)
> > ![Screenshot_1](https://user-images.githubusercontent.com/61013585/76145662-4776f680-606a-11ea-9892-fd9b58656aa8.png)
> 
> https://github.com/lxxneonxxl/THE-LAST-2-DIGITS/blob/master/binary-bot%20(6).xml
> 
> ![image](https://user-images.githubusercontent.com/57267933/76150979-dc0c4380-60c0-11ea-8e5a-4a0776bcf9ee.png)
> 
> This is an example. Change what you want

hey buddy if my strategy is to have more digits
Example:
22 = call
23 = put
24 = put
35 = call

how do I configure to have more last digits?

**Comment by lxxneonxxl** [comment]
> эй, приятель, если моя стратегия состоит в том, чтобы иметь больше цифр
> Пример:
> 22 = колл
> 23 = ставить
> 24 = ставить
> 35 = звонить
> 
> как я могу настроить, чтобы иметь больше последних цифр?

https://github.com/lxxneonxxl/THE-LAST-2-DIGITS/blob/master/binary-bot%20(7).xml

**Comment by cleberscr** [comment]
> > эй, приятель, если моя стратегия состоит в том, чтобы иметь больше цифр
> > Пример:
> > 22 = колл
> > 23 = ставить
> > 24 = ставить
> > 35 = звонить
> > как я могу настроить, чтобы иметь больше последних цифр?
> 
> https://github.com/lxxneonxxl/THE-LAST-2-DIGITS/blob/master/binary-bot%20(7).xml

thank you very much friend, you're amazing <3
