### ISSUE TITLE
stay in sideways strat

### ISSUE THREAD

**Issue by XiaoYuzu** [binary-com/binary-bot#2531]
halo bro, saya punya strategy stay in saat market sideways, nah di strategy ini saya mau nambahin jika candle sebelumnya merah maka : 
stay in : - 0.3 & + 1.5
dan jika hijau
stay in : +0.3 & -1.5

mohon bantuannya

----------------------------------------------------------------------------------

hello bro, I have a strategy stay in when the market is sideways, well in this strategy I want to add if the previous candle is red then:
stay in: - 0.3 & + 1.5
and if it's green
stay in: +0.3 & -1.5

Please help

**Comment by saarsalu** [comment]
> 1.5

for wath volatylity
or curensy

**Comment by XiaoYuzu** [comment]
> > 1.5
> 
> for wath volatylity
> or curensy

index 25
