### ISSUE TITLE
BINARY BOT Prediction Different  

### ISSUE THREAD

**Issue by neooxide** [binary-com/binary-bot#2537]
Como puedo cambiar mi prediccion en funcion del ultimo digito, Por ejemplo.
Si el ultimo digito fue 3, deseo tener una prediccion de valor 3 en el siguiente tick

**Comment by Martinez222** [comment]
hey!
Try this way :

![prediction 3](https://user-images.githubusercontent.com/39260368/76412771-e4080400-639c-11ea-9e97-978fc5cc8143.jpg)

**Comment by neooxide** [comment]
Thank you so much
