### ISSUE TITLE
Help to create digit match bot

### ISSUE THREAD

**Issue by radooooi** [binary-com/binary-bot#2538]
Hello dear 

I need a bot for example if the # 1579.xx

The roles is that the last two number should be same and the ldp will be 9 (the number after the point 

Thats all

**Comment by Martinez222** [comment]
Hey!Some times is missing the prediction due the internet connection ,lag etc.I put also some martingale block.Feel free to develop!

PS this kind of bot will blow your acc very fast !!  :))
![match](https://user-images.githubusercontent.com/39260368/76417048-d2c2f580-63a4-11ea-9e8c-ad9d55767a11.jpg)
[bibi_MATCH.zip](https://github.com/binary-com/binary-bot/files/4318236/bibi_MATCH.zip)

**Comment by ananA2** [comment]
> Hello dear
> 
> I need a bot for example if the # 1579.xx
> 
> The roles is that the last two number should be same and the ldp will be 9 (the number after the point
> 
> Thats all

Excellent Digit over bot. 
![Uploading Screenshot_20230401-155448.png…]()
 https://github.com/binary-com/binary-bot/issues/3864#issue-1650424206
