### ISSUE TITLE
saidforex26   How to trade open on specific time

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2540]
how to trade open on a specific time?
Digit Differ Strategy
i want to open every trade on last second on a minute

with best regards

**Comment by Martinez222** [comment]
if u want to trade on sec 59 u can do it like that but you will have 2-4 sec delay : 
![59](https://user-images.githubusercontent.com/39260368/76549788-adfc7a00-6499-11ea-9785-b49e850cde44.jpg)

**Comment by sohailsb** [comment]
thanks
