### ISSUE TITLE
Strategy for forex ---can anyone interested  t o create BOT on this Strategy 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2542]
Strategy for forex can anyone interested  t o create BOT on this Strategy  

https://www.forexfactory.com/showthread.php?t=533791

**Comment by Martinez222** [comment]
what is a SMA cross over then confirmation of 2 same candles?

**Comment by muroyal** [comment]
Sorry I don't have idea to extract mt4 files need to open indicators in mt4
for more info ..I have found it in forum an it is more interesting hence I
have posted here
