### ISSUE TITLE
change buying strategy

### ISSUE THREAD

**Issue by valeriefaith** [binary-com/binary-bot#2543]
Is there any way to make block 4 - when the result is a loss-  change the buying strategy in block 2

**Comment by Martinez222** [comment]
Try like this : 
![strategy A - B](https://user-images.githubusercontent.com/39260368/76638935-f6796d80-6555-11ea-96b8-037d28a00cbb.jpg)

**Comment by valeriefaith** [comment]
Thanks @Martinez222 for the help.
