### ISSUE TITLE
How can i can i have my bot take a trade only when criteria is met in a certain order?

### ISSUE THREAD

**Issue by josward1** [binary-com/binary-bot#2544]

**Comment by Martinez222** [comment]
U need to loop your criteria so it will wait the other ones to fullfil:
Ex: criteria 1 fulfill-loop (wait)
Criteria 2  fulfilll -loop
Criteria 3 fulfilll (last one)-then purchase order

**Comment by josward1** [comment]
thank you

**Comment by Martinez222** [comment]
U are welcome

**Comment by Kosta92** [comment]
@Martinez222 And how to do that? Where is "loop wait" function located or how to build it?

**Comment by Martinez222** [comment]
@Kosta92 
![loop](https://user-images.githubusercontent.com/39260368/76682351-24b58680-6604-11ea-807f-49a2e2234f58.jpg)
