### ISSUE TITLE
Want to sale my low budget bot quickly

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2547]
https://www.youtube.com/watch?v=9C1BXDwiRZk
dushanuyt@gmail.com

this is call put bot i want sale it
and ill upload 15 hour result with higher lower trade with only 2 step lost
i just wanted quick money 
if you interested please contact me... i ll upload 15 hour result with my real account
thanks...  

![screen](https://user-images.githubusercontent.com/59830499/76570504-6e568200-64db-11ea-9be8-f800bbfd6d43.jpg)
martingale 5x multiply ...{4 X enough}
i want sale my all 3 bots
digital 
call put
and higher lower
every bot can earn 10 - 25 usd per hour

**Comment by sl777** [comment]
How Much?

**Comment by virtusasys** [comment]
Digital Bot is 59$ Usd higher lower and call put is little-bit expensive.. but 100% guranteed .. please contact by email

**Comment by aaron-binary** [comment]
Hi @virtusasys,

We love the open sharing of knowledge, but we don't encourage advertising and selling your applications here. This repository is used to help others, report issues, request new features, etc.

We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today.

You can also contact marketing@binary.com to learn more about partnership options.

Regards,
Aaron
