### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#2549]
@aaron-binary @anton-binary @aminmarashi-binary hay, there has been a bug in the binary bot. Please correct the list of last and last digits. because they don't take the last digit of the last tick

**Comment by aaron-binary** [comment]
Hey @saidforex26,

We're looking into this right now.

Regards,
Aaron

**Comment by saidforex26** [comment]
I see lately this block **digit list** and the **last digit list** bock often have problems

**Comment by aaron-binary** [comment]
Hey @saidforex26,

What exactly is the issue with these blocks?

Regards,
Aaron
