### ISSUE TITLE
how can i make sell if available !!

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2558]
Dear All ,

how can i make sell if available if the open trade was win 60% so the bot will close the trade ? 
![a](https://user-images.githubusercontent.com/55850508/76650131-a22cb880-656a-11ea-845a-01ad23a87005.png)

**Comment by ahmadhus** [comment]
Please help

**Comment by ahmadhus** [comment]
Please help

**Comment by ahmadhus** [comment]
Please help

**Comment by ahmadhus** [comment]
Please help

**Comment by ahmadhus** [comment]
Please help

**Comment by Martinez222** [comment]
See here : 
https://github.com/binary-com/binary-bot/issues/2342#issuecomment-576025629

**Comment by Martinez222** [comment]
Just put 60 insted 70...

**Comment by ahmadhus** [comment]
@Martinez222 
thanks for your replay 

can you send me the txt or xml of the needed block ?

**Comment by Martinez222** [comment]
@ahmadhus you have all in the picture : 
![image](https://user-images.githubusercontent.com/39260368/76658957-ea090b00-657d-11ea-91da-fa65ae83b45f.png)

**Comment by ahmadhus** [comment]
@Martinez222 

the problem that i do not know how to build this blocks .

thanks

**Comment by Max-Profit** [comment]
Enjoy it .... 
[Sell at market.xml.zip](https://github.com/binary-com/binary-bot/files/4331715/Sell.at.market.xml.zip)
