### ISSUE TITLE
bot just stop...need help Pls

### ISSUE THREAD

**Issue by poroinika** [binary-com/binary-bot#2559]
The bot is good but just stop it,when he close the trade position,somtimes not start new analyse and need to run it agine.
If he start analyse not stop.

Not start affter close some trade ONLY!!!!

Try and will see,can someone change it 

THANKS!!!!
[MOI-NEW.txt](https://github.com/binary-com/binary-bot/files/4331152/MOI-NEW.txt)

**Comment by ahmadhus** [comment]
intrested

**Comment by poroinika** [comment]
> intrested

yes sir,my internet conection is realy good,and I try with mobile internet from my phone and it's same.

today stop aftther furst position,affther that stop aftther 43 close position,I dont undurstand where is the problem......Can you chek?

**Comment by Martinez222** [comment]
i think the probem is with the notification put it in block 4 in front of trade again.
U can do it like in picture.

P.S this is Fruitfella martingale block ...... :))))
![error bot](https://user-images.githubusercontent.com/39260368/76659485-3bfe6080-657f-11ea-9277-163d2609fbe7.jpg)

**Comment by Martinez222** [comment]
if is not that you will have to loop the condition in block 1  (define trade option)

**Comment by poroinika** [comment]
> if is not that you will have to loop the condition in block 1 (define trade option)

I try with block 4=same problem
Delete all block 4 and all martigles and creat it with simle martingle,change all block 1 and nothing.....same problem

**Comment by Martinez222** [comment]
Confirm and loop the candle condition in block 1

**Comment by poroinika** [comment]
> Confirm and loop the candle condition in block 1

Can you show me what you mean?

**Comment by Martinez222** [comment]
This is modyfied bot : 
![poronika](https://user-images.githubusercontent.com/39260368/76682016-0d28ce80-6601-11ea-95b3-4a117a75d5b4.jpg)
![poronika2](https://user-images.githubusercontent.com/39260368/76682019-0ef29200-6601-11ea-8487-2ee05355917e.jpg)
[poroinika Hi_Lo.zip](https://github.com/binary-com/binary-bot/files/4332724/poroinika.Hi_Lo.zip)

**Comment by Martinez222** [comment]
ps it goes 6 marti steps in 30 runs ...

**Comment by poroinika** [comment]
> ps it goes 6 marti steps in 30 runs ...

Hmmm.....i run your and mine bot togetther and I see they not open same time trades.....and your bot miss some trades and with mine they are Win.
Your bot make 5 losess mine 3 on the row

**Comment by Martinez222** [comment]
Of corse the bots don't open the same trades !Bot has some tick analyse ..u will have to presume that both bots are starting in the same time and u don't have any internet interuption ,lag etc...

P.S îs not my bot is your bot..:)

**Comment by poroinika** [comment]
> Of corse the bots don't open the same trades !Bot has some tick analyse ..u will have to presume that both bots are starting in the same time and u don't have any internet interuption ,lag etc...
> 
> P.S îs not my bot is your bot..:)

I runn it at same time and gives different signals,have same signals but have and different
