### ISSUE TITLE
Hull Moving Average ARRAY indicator

### ISSUE THREAD

**Issue by Rover1953** [binary-com/binary-bot#2560]
Hi guys! Please help to find out the Hull Moving Average ARRAY indicator, I highlighted "ARRAY". Many thanks in advance for assistance.

**Comment by Martinez222** [comment]
may be like that: 

![hull](https://user-images.githubusercontent.com/39260368/76689397-2865ff00-663e-11ea-8217-d527b5b019b6.jpg)

**Comment by Martinez222** [comment]
u can find indicator block here : https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators

**Comment by Rover1953** [comment]
Lot of thanks for Your kind assistance! Have a nice day!

сб, 14 мар. 2020 г. в 21:53, Martinez222 <notifications@github.com>:

**Comment by Rover1953** [comment]
One question still remains, I'm sending a screenshot.

вс, 15 мар. 2020 г. в 11:18, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by Rover1953** [comment]
unfortunately with these parameters, the bot is very slow and freezes

вс, 15 мар. 2020 г. в 16:33, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by Rover1953** [comment]
вс, 15 мар. 2020 г. в 16:39, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by Martinez222** [comment]
maybe u build it wrong..I let it run for more than 30 minute is working normally..

**Comment by Rover1953** [comment]
Could You please check what is wrong in my building a bot?
It's freezing after start. With other my bots no such problem.
I'm sending also xml file.

вс, 15 мар. 2020 г. в 19:02, Martinez222 <notifications@github.com>:

**Comment by Rover1953** [comment]
пн, 16 мар. 2020 г. в 07:58, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by Martinez222** [comment]
I'm not seeing any printscreen or xml file..

**Comment by Rover1953** [comment]
I'm kindly sending 2 files again, please check.
пн, 16 мар. 2020 г. в 11:03, Martinez222 <notifications@github.com>:

**Comment by Martinez222** [comment]
I realy don't know were u send your files.. :)

**Comment by Rover1953** [comment]
I think the problem with freezing the bot is too many blocks, loading to
the bot body while bot building.
Which blocks should be removed? I try to build the bot with two crossing
Hull MA, but I see on Your picture that one of crossing MA is Weighted MA.
Was it mistake or should be like that? I was trying all variants, but my
bot is freezing computer.

пн, 16 мар. 2020 г. в 18:08, Martinez222 <notifications@github.com>:

**Comment by Martinez222** [comment]
The pictura i uploaded is just a example.Change it with what ever  your strategy need.

I don't think the bot freez because of to many blocks ...

**Comment by Rover1953** [comment]
Many thanks for Your help. Finally I've found the solution.

**Comment by Rover1953** [comment]
I have found the reason of freezing the bot. I used too high lengths of
crossing Hull MA: 26 and 52 as per strategy.
Everything works well with lengths 3 and 11.
Many thanks for Your help & assistance.
Have a Nice Day!



вт, 17 мар. 2020 г. в 11:26, Martinez222 <notifications@github.com>:

**Comment by Martinez222** [comment]
Ok!Good luck!

**Comment by Rover1953** [comment]
Hi Martinez222,
My computer works, but too hard with 3 blocks, highlighted on my attached
picture. Actually i need only Hull MA Array indicator for trading.
Is it possible to remove that 3 blocks and use only Hull MA Array block?
Thank You


вт, 17 мар. 2020 г. в 13:33, Martinez222 <notifications@github.com>:

**Comment by Martinez222** [comment]
I'm not sure that i understand what u want.If we  discurs about cross lines it is the only way..

**Comment by Rover1953** [comment]
Yes, we discuss about cross lines.
Thank You,
Sorry, I have one more question.
Could You help me to find the Least Squares Moving Average Array indicator.
I will try to create the bot with above indicator.



чт, 28 мая 2020 г. в 20:25, Martinez222 <notifications@github.com>:

**Comment by Rover1953** [comment]
Even if "Least Squares Moving Average" indicator, without "Array". Please,
help to find it.
Many thanks in advance.

чт, 28 мая 2020 г. в 23:59, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by Martinez222** [comment]
I'm sorry but i realy don't understand what u want..

**Comment by Rover1953** [comment]
I will try to explain in more detail what I want. There is such an
indicator "Least Squares Moving Average" on Trading View platform, but a
block with this indicator is not offered on the Binary Bot site.
I want to use it when creating a bot. I would also like to find an
indicator " Least Squares Moving Average ARRAY".
I really hope that I was able to explain exactly what I'm looking for.
Many thanks in advance.

пт, 29 мая 2020 г. в 23:13, Martinez222 <notifications@github.com>:

**Comment by Martinez222** [comment]
If "Least Squares Moving Average ARRAY" is a indicator u will need the formulla in order to make a bot..

**Comment by Rover1953** [comment]
I'd like to create two different bots.

My formula to use the  Least Squares Moving Average ARRAY indicator in
order to make a first bot is as follows:
The price is crossing LSMA upwards    -  purchase RISE
The price is crossing LSMA downwards - purchase FALL

My formula to use the  Least Squares Moving Average indicator in order to
make a second bot is as follows:
The price is higher than LSMA     -  purchase FALL
The price is lower than  LSMA      - purchase RISE

Did I understand the meaning of the word "formula" correctly?



сб, 30 мая 2020 г. в 16:59, Martinez222 <notifications@github.com>:

**Comment by Rover1953** [comment]
Sorry, but you did not reply to my last letter

сб, 30 мая 2020 г. в 17:45, Yuriy Klyuchnikov <rover1953@gmail.com>:

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: Rover1953 <notifications@github.com>
Enviado: quinta-feira, 4 de junho de 2020 12:07
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Hull Moving Average ARRAY indicator (#2560)


Sorry, but you did not reply to my last letter

сб, 30 мая 2020 г. в 17:45, Yuriy Klyuchnikov <rover1953@gmail.com>:
