### ISSUE TITLE
Run bot on local machine

### ISSUE THREAD

**Issue by alekshnl** [binary-com/binary-bot#2565]
Hello, is it possible to run the binary bot also on a local machine? Can somebody help me with this or explain in a few steps what needs to happen? Thanks a lot!

**Comment by aaron-binary** [comment]
Hey @alekshnl,

Bots always run on a local machine as everything happens in your browser, although there is a connection made to our servers to purchase contracts etc.

An alternative way to run the bot is to use the command line interface, please read more about that here: https://github.com/binary-com/binary-bot#running-the-cli-command

Regards,
Aaron

**Comment by alekshnl** [comment]
Hey @aaron-binary,

Thanks for your reply.

Okay, understood. Is the webhook functionality also hosted locally or does it post information through your servers? 

Additional question (I don't want to create a separate topic for this): in what way can I download bulk tick information of a certain asset?

Kind regards,
Aleks

**Comment by aaron-binary** [comment]
Hi @alekshnl,

> Okay, understood. Is the webhook functionality also hosted locally or does it post information through your servers? 

Webhooks will originate from your local machine, we're using JS's fetch API to send these requests. https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

> Additional question (I don't want to create a separate topic for this): in what way can I download bulk tick information of a certain asset?

You may download up to 5k ticks at a time using our `ticks_history` API call, please see https://developers.binary.com/api/#ticks_history for more information.

Hope that helps!

Regards,
Aaron
