### ISSUE TITLE
Make connection

### ISSUE THREAD

**Issue by newfbi** [binary-com/binary-bot#2566]
Hello guys! I would like to know how I can integrate Auth, to connect to bot.html? I did all the update and link. but he always asks to connect! do I have to add any more JS?
![image](https://user-images.githubusercontent.com/18191137/76721779-e1e8d100-671f-11ea-9296-0d8c676b4cbc.png)

**Comment by Martinez222** [comment]
Try with another browser...

**Comment by newfbi** [comment]
Hello! So I've tried everything! Create several App_id keys and not be able to configure 1 connection. Do you have a guide?

**Comment by aaron-binary** [comment]
Hey @newfbi,

I'm not too sure what you're asking here, could you tell me what you're trying to achieve?

Regards,
Aaron
