### ISSUE TITLE
this is the script if it is possible to get values for every line Greatings to every one

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#2567]
this is the script if it is possible to get values for every line
Greatings to every one

**Comment by tymu** [comment]
//@version=2
study("Stealthy 7 Max Draw Down")
len= input(defval=30, type=integer)
maxlow = 0
maxhigh = 0
MaxDD = 0
for x = len to 0
    if maxlow == 0
        maxlow := low[x]
    if maxhigh == 0
        maxhigh := high[x]
    if high[x] > maxhigh
        maxhigh := high[x] 
    if (1 - (low[x] / maxhigh)) * 100 > MaxDD
        maxlow := low[x]
        MaxDD := (1 - (maxlow / maxhigh)) * 100

returns = (close[0] / close[len]) * 100 - 100
AvgReturn = sma(returns,len)
plot(0,color=black)
plot(returns,color=green)
plot(AvgReturn,color=green,linewidth=2)
plot(nz(MaxDD),color=red,linewidth=2)

**Comment by Kosta92** [comment]
He is talking about [this](https://vn.tradingview.com/script/SDW2SfkX-Stealthy-7-Max-Draw-Down/)
