### ISSUE TITLE
Difference between Volatility Indices

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2568]
What's the actual difference between Volatility Index 10 up to V100?
What do these numbers even mean?
Is V10 less volatile than V100, for example, or are they about the same?
If there is difference in volatility, how is it measured? Like, is V10 a 10% volatile compared to V100's 100% (volatile in terms of market going sideways more often or stronger)?

**Comment by trident2005** [comment]
I think those are all the same, obviously each one has its own direction, but I mean you couldn't say that one is more stable than the other, for example.

**Comment by Kosta92** [comment]
That's exactly what I though.
