### ISSUE TITLE
Notify maximum amount of consecutive losses

### ISSUE THREAD

**Issue by trident2005** [binary-com/binary-bot#2571]
@binary-ex-machina, @saidforex26, 

Please, I need the bot to print the largest number of losses (OTM) at the bottom left of the screen, the bot to work for several hours and print how many consecutive losses (OTM) have been.

Could you help me create that ??

**Comment by saidforex26** [comment]
yes I already have a block that can tell each level los details, win details, los level details, the largest stake amount, the amount of balance needed to run the bot. and many other functions, you can use the money management block that I made. please send your bot, I add the block

**Comment by trident2005** [comment]
Ok @saidforex26 

Here is the scrypt
[Candle Bot.zip](https://github.com/binary-com/binary-bot/files/4341942/Candle.Bot.zip)
 
And thanks for your time and your attention

**Comment by saidforex26** [comment]
please adjust your money management settings what notifications you want to get in block 1.
[candle bot add mts.zip](https://github.com/binary-com/binary-bot/files/4343383/candle.bot.add.mts.zip)

**Comment by ZDEGLET** [comment]
[001.zip](https://github.com/binary-com/binary-bot/files/4343574/001.zip)

**Comment by trident2005** [comment]
@saidforex26 

it is very complex, it will take me a while to fully understand, very grateful to you for your collaboration

**Comment by trident2005** [comment]
@ZDEGLET thank you, it is more easy to implement in others scrypts.
