### ISSUE TITLE
3 ticks to the same direction

### ISSUE THREAD

**Issue by BotBrazil** [binary-com/binary-bot#258]
How do I get a call order after 3 ticks high. For putt order I found this example below, but it does not work to call if it reverses, does anyone help me? please help me @aminmarashi tks
![sem titulo](https://user-images.githubusercontent.com/29413757/27310343-ee82abde-552f-11e7-8449-7d1ae245cab1.jpg)

**Comment by Fruitfella** [comment]
![3ticks](https://user-images.githubusercontent.com/26277327/28099496-1e0eaf06-66e7-11e7-9189-c873262d21b8.PNG)

**Comment by Fruitfella** [comment]
![3ticks](https://user-images.githubusercontent.com/26277327/28099510-36a4a638-66e7-11e7-8538-0cfe67312dae.PNG)
@BotBrazil

**Comment by BotBrazil** [comment]
tanks a lot @Fruitfella
