### ISSUE TITLE
Timed Entry

### ISSUE THREAD

**Issue by MattKimbel** [binary-com/binary-bot#2584]
Please I want to set a bot that enters before  the current  candle closes.
Reasons being  enteries might be bad for next candle, usually  because  of the  jump.
Thanks🙏

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/77162015-f0e7ce80-6ae5-11ea-96cc-11487646c03c.png)

**Comment by MattKimbel** [comment]
Thanks
