### ISSUE TITLE
Restarting bot after 4 consecutive losses

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2593]
Hi, 
I created a bot with the Martingale strategy (increasing the stake after a loss). Just wondering if it is possible to make the bot to restart with the initial stake after 5 minutes after seeing 4 consecutive losses? i.e., for eg., Let's assume my initial stake is $1 and the the stake doubles after every loss. So, if there are 4 consecutive losses, I would be losing $1, $2, $4 and $8. Is it possible to stop the bot after 4 consecutive losses and freshly restart automatically after 5 minutes with a $1 stake rather than continuing with $16, $32 etc.,?
Just wanted to do this to minimize losses when the market is fluctuating heavily.
Thanks

**Comment by JenggotSantuy** [comment]
@binarybotbegginer 
very likely
and it can be done

**Comment by lxxneonxxl** [comment]
Possible. I advise you to look at existing topics.. this way you will get more knowledge of how to do it. This will significantly help you in further development of bots

**Comment by binarybotbegginer** [comment]
> Possible. I advise you to look at existing topics.. this way you will get more knowledge of how to do it. This will significantly help you in further development of bots

Sorry. I couldn't find a related topic or example. Can you please share a link? Thanks

**Comment by Martinez222** [comment]
Try this :
![5](https://user-images.githubusercontent.com/39260368/77566175-f66e5b80-6ecd-11ea-8d8b-1455364d68d8.jpg)

**Comment by Martinez222** [comment]
PS put stake block to curency..:)

**Comment by binarybotbegginer** [comment]
@Martinez222 Thanks a lot. It is working the way I wanted it to. Just a small tweak. Added another "Trade Again" function.
![TA](https://user-images.githubusercontent.com/62483125/77837916-43527a80-71cb-11ea-8888-291ce8d0317f.jpg)

**Comment by Martinez222** [comment]
i was in a hurry and i put trade again block wrong.U don't need 2 trade again blocks.Were u put it is ok.
U are welcome!
