### ISSUE TITLE
Can someone make a XML binary bot with my requirements

### ISSUE THREAD

**Issue by udhaykumar1993** [binary-com/binary-bot#2595]
My requirements are : 

Take a Buy trade with 1M expiry ( any Volatility index pairs)
When we get a Sequence of three same Bull candles and 4th candle is a Inside bar. 
Inside bar is that High and low of 4th candle should be within the 3rd candle. 

Same vice versa for Sell Trade : 
 When get a sequence for 3 Bear Candles and 4th candle is an inside bar

When need to Take martingales as per the below sequence After a lose : 
If Buy trade Lost : UP , Down,UP,UP,Down
If Sell trade Lost : Down , Up,Down , Down , Up

Once we will get a Winning trade with martingale types . We need to wait for a Fresh new Inside bar signal
Inputs Required : 
Initial Stake : 
Winning Stake : 
Take Profit : 
Stop loss : 
Martingale level  : 5 
Martingale Factor :2 

Please let me know if you have any questions. If you are available to help. I would appreciate your help. Thanks 

Here is an image of inside bar for a buy trade.
![image](https://user-images.githubusercontent.com/61644874/77254485-3e4f7180-6c87-11ea-9334-e88edf40903f.png)

**Comment by udhaykumar1993** [comment]
Anyone Help on this?

**Comment by Martinez222** [comment]
My friend this is a place were peoples are helping other peoples  , not a place where u can get free bots! :)

In attach u will find a bot that is not entirely what u want...but fell free to develop & test it!
God bless us all with helth!!
[Color Candle X Candle Analyses x.zip](https://github.com/binary-com/binary-bot/files/4399025/Color.Candle.X.Candle.Analyses.x.zip)

**Comment by udhaykumar1993** [comment]
Thank you bro. I understand. i also try to help the people as much as possible.  I will to develop Bot as for my requirements. Thank you for the effort.

**Comment by udhaykumar1993** [comment]
> 
> 
> My friend this is a place were peoples are helping other peoples , not a place where u can get free bots! :)
> 
> In attach u will find a bot that is not entirely what u want...but fell free to develop & test it!
> God bless us all with helth!!
> [Color Candle X Candle Analyses x.zip](https://github.com/binary-com/binary-bot/files/4399025/Color.Candle.X.Candle.Analyses.x.zip)
S
Stay safe and keep supporting :) God bless you
