### ISSUE TITLE
cannot withdraw

### ISSUE THREAD

**Issue by lupus-00** [binary-com/binary-bot#2598]
i have problem to withdraw
i already sent email to binary.com support but they haven't reply yet
i one can help me to contact them..

**Comment by lupus-00** [comment]
@aaron-binary

**Comment by aaron-binary** [comment]
Hey @lupus-00,

Please contact us at support@binary.com, they will be able to help you. 👍 

Hope that helps,
Aaron

**Comment by lupus-00** [comment]
i already sent email to support@binary.com two days ago but until now
there's no response from them..

**Comment by martinrf79** [comment]
Can you withdraw already?

**Comment by harshalkharose** [comment]
binary don't give withdrawal instant???
