### ISSUE TITLE
MACD EXAMPLE

### ISSUE THREAD

**Issue by Jay1892** [binary-com/binary-bot#260]
Amin,

How can i create a Macd Strategy Which will  Purchase when the Signal line crosses 0.0001 and -0.0001..  Thanks

**Comment by aminmarashi** [comment]
Is [this](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/macd_signal_range.xml) what you want?

**Comment by Jay1892** [comment]
When I click I can't view ..  if you can paste a example how the block look like .  I can set it ..  I mean a pic of the block MACD signal line cross 0.0001 (put) and signal line cross -0.0001 call

**Comment by aminmarashi** [comment]
Here:
<img width="578" alt="screen shot 2017-06-23 at 4 51 21 pm" src="https://user-images.githubusercontent.com/6560964/27474226-499eaaf2-5834-11e7-8b7f-258b557e31cc.png">

**Comment by Jay1892** [comment]
Legend. Thank you ..  you are so much very happy. Thanks again

**Comment by Rover1953** [comment]
Amin, please specify in which case purchase Rise and in which case purchase Fall. Many thanks.
