### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by jose895** [binary-com/binary-bot#2603]
Please help Someone would be so kind to be able to program my strategy for binary in XML, it consists of the following parameters: To buy one touch when the penultimate digit is "5" blue and the worm's head is green. example (1,166.50 x, xxx, 5x)              to buy in digit 5 ​​blue color and also that the worm's head is green

**Comment by saidforex26** [comment]
[digit5blueworm.zip](https://github.com/binary-com/binary-bot/files/4373206/digit5blueworm.zip)

**Comment by jose895** [comment]
Thanks
