### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by jose895** [binary-com/binary-bot#2604]
can someone help me to program this strategy for one touch: That 50% return per contract, and that after each contract won, make compound interest at 3 levels, but in the event of loss, the return percentage changes to 120% and martingale until the loss is recovered, and likewise that return percentage change back to 50% and redo compound interest in case of profit

**Comment by aaron-binary** [comment]
Duplicate of https://github.com/binary-com/binary-bot/issues/2603
