### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by Zeemi20** [binary-com/binary-bot#2606]
Hello, can I use binary.bot to my binary.com metatrader account?

**Comment by Zahraam2** [comment]
or even deriv bot?

**Comment by ZDEGLET** [comment]
да

**Comment by Zahraam2** [comment]
@ZDEGLET how can I use it for my metatrader account?? Can you olease tell me

**Comment by Zahraam2** [comment]
@anton-binary @arun-binary @aaron-binary ?? any idea?

**Comment by aaron-binary** [comment]
Hey @Zahraam2,

This isn't currently possible.

Regards,
Aaron
