### ISSUE TITLE
Range preak 200 index 

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2608]
who pays my margin call.
you waste. why do you make such a couple if you can't accept that people are doing it well :(

a week ago I raised my account from USD 200 to 1500 Usd and now I have an open transaction that I would like to close as the market is blocked with this pair and I am currently trading at a profit. in the morning the current deal was 300 usd. but suddenly the market moved downwards and stayed on 3 usd.
![Screenshot (608)](https://user-images.githubusercontent.com/30391002/77583388-a9987e00-6ee9-11ea-9ce6-f4677538ee7c.png)

**Comment by thommmaz** [comment]
> who pays my margin call.
> you waste. why do you make such a couple if you can't accept that people are doing it well :(
> 
> a week ago I raised my account from USD 200 to 1500 Usd and now I have an open transaction that I would like to close as the market is blocked with this pair and I am currently trading at a profit. in the morning the current deal was 300 usd. but suddenly the market moved downwards and stayed on 3 usd.
> ![Screenshot (608)](https://user-images.githubusercontent.com/30391002/77583388-a9987e00-6ee9-11ea-9ce6-f4677538ee7c.png)

Range Break pairs are only available for demo accounts not for real accounts.

**Comment by saarsalu** [comment]
> > who pays my margin call.
> > you waste. why do you make such a couple if you can't accept that people are doing it well :(
> > a week ago I raised my account from USD 200 to 1500 Usd and now I have an open transaction that I would like to close as the market is blocked with this pair and I am currently trading at a profit. in the morning the current deal was 300 usd. but suddenly the market moved downwards and stayed on 3 usd.
> 
> Range Break pairs are only available for demo accounts not for real accounts.

and if there is a demo account you are allowed to play dick.
do you think it's normal

why do you need this pair at all.

**Comment by aaron-binary** [comment]
Hey @saarsalu,

Please discuss MT5 related topics on our forums over at https://binary.vanillacommunity.com/, these GitHub issues pages are meant to discuss Binary Bot related topics.

Regards,
Aaron
