### ISSUE TITLE
TICK COUNTING BOT

### ISSUE THREAD

**Issue by akolojodaniel** [binary-com/binary-bot#2609]
@BINARY-EX MACHINA, please help me out with a bot that counts ticks. thanks

**Comment by Martinez222** [comment]
@akolojodaniel  i dont know what are u looking for but see below an example : 
[counttick_ex.zip](https://github.com/binary-com/binary-bot/files/4393393/counttick_ex.zip)

**Comment by akolojodaniel** [comment]
Thanks. 
I want bot that have
Tick 1,tick2,tick3,etc.
Eg we can have: 
If tick1 is less than tick2, purchase...

**Comment by Martinez222** [comment]
[tiky.zip](https://github.com/binary-com/binary-bot/files/4395204/tiky.zip)

**Comment by akolojodaniel** [comment]
THANKS
