### ISSUE TITLE
Indicator Set Up

### ISSUE THREAD

**Issue by Jay1892** [binary-com/binary-bot#261]

**Comment by Jay1892** [comment]
Hey Mate,

Instead of the Chart showing the Incorrect Indicators Setting Value,  Why can't you link Trading View on the Bottom..this might a better option then the  indicators value can be change to match the bot ..

**Comment by aminmarashi** [comment]
Hi. This actually could be a good idea, but we use the chart for showing ongoing trade and we can't do the same thing with Trading View or any other external chart.
Of course, we'll look into adding indicator options to Binary Bot chart soon.

**Comment by aminmarashi** [comment]
We will add this in a new chart view!

**Comment by aminmarashi** [comment]
It's now added.

**Comment by Jay1892** [comment]
You are a Legend!  Thanks Mate...
