### ISSUE TITLE
Bot Not Starting

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#2611]
After Adding a second trade option, The Bot Won't Start:

![image](https://user-images.githubusercontent.com/54149729/77678035-dfdd0880-6f90-11ea-8096-7816af319a75.png)

It keeps telling me : Bot is starting.
But it never start running

![image](https://user-images.githubusercontent.com/54149729/77678191-131f9780-6f91-11ea-9310-6aa81263a731.png)

Please Help !

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by Martinez222** [comment]
Move your condition in 'define trade option" or put your xml file here...

**Comment by Adammodex** [comment]
Can you please give me your email, I'll send it to you there. I don't wanna share my bot with the public.

**Comment by Adammodex** [comment]
> 
> 
> Move your condition in 'define trade option" or put your xml file here...

Can you please give me your email, I'll send it to you there. I don't wanna share my bot with the public.

**Comment by Martinez222** [comment]
claudiu23@gmail.com

**Comment by Adammodex** [comment]
I sent you the file sir, please check your e-mail. 
Thanks !

**Comment by Martinez222** [comment]
U have it in your e-mail.
U are welcome!

**Comment by Adammodex** [comment]
Thank You sir very much !!!

**Comment by Adammodex** [comment]
I still have this issue.
Pls Can Someone help me?
Everytime i edit the bot, it just goes back to normal and it's not starting.

@binary-ex-machina
@saidforex26
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by Martinez222** [comment]
@Adammodex  u give me a broken bot with some condition missing and i show u how to do it so the bot work..
I'm not a magician to guess what u want If u delete blocks from the bot !

**Comment by Adammodex** [comment]
I really do want to learn how to do different conditions. But thats the problem. Idk how to do it, if you could sir provide me with a list of what i should add there. That'll be awesome.

And thats because i camt always bother you, or this community if im creating a new bot. I just want to do it myself.

Thank You very much.

**Comment by Adammodex** [comment]
Thank You Very Much Sir, I figured it out.

**Comment by niyixx** [comment]
Hi @Adammodex please how did you fix this issue?
