### ISSUE TITLE
If variable not in numbers

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2613]
Hello All,

Can anyone help with below requirement.

IF VARIABLE not in list of numbers
Then 
---- strategy

Is there any function to compare variable number in list of numbers ?

Kindly help me..

**Comment by muroyal** [comment]
@saidforex26

**Comment by saidforex26** [comment]
I beg you to forget the details ,, everything can be made

**Comment by muroyal** [comment]
Sorry ..  

here is the details. 

If (Current Hour is not 12,18,19,3,4,5)
Trade mode True

![image](https://user-images.githubusercontent.com/32416314/77814829-be883380-70da-11ea-84ca-a484d0ed547f.png)

**Comment by saidforex26** [comment]
make sure your clock format with 24. example block that you want
![image](https://user-images.githubusercontent.com/54820719/77822460-e94fa780-712d-11ea-964e-62eee7d88cd7.png)

**Comment by muroyal** [comment]
Thanks a lot My friend.. .

**Comment by saidforex26** [comment]
okey
