### ISSUE TITLE
entrance opening or closing candle

### ISSUE THREAD

**Issue by claytonliotti** [binary-com/binary-bot#2614]
It is possible to make the bot pass the entry only when closing or opening a candle

**Comment by josward1** [comment]
![IMG_0357](https://user-images.githubusercontent.com/37579005/78026951-68262980-7354-11ea-95e7-b0b40a094b66.JPG)

**Comment by josward1** [comment]
[ATT00001 (1).txt](https://github.com/binary-com/binary-bot/files/4409058/ATT00001.1.txt)

**Comment by josward1** [comment]
![IMG_0360](https://user-images.githubusercontent.com/37579005/78027718-bbe54280-7355-11ea-889f-256d2b70ce76.JPG)

**Comment by claytonliotti** [comment]
ok thanks
