### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by jose895** [binary-com/binary-bot#2616]
Can someone help me to program the following strategy that consists of the following indications: volatility: 100 one touch barrier: +0.12 macd: fast MA period 12, slow MA period 26, signal period 9 9 
That I buy one touch when the MA of the macd crosses from bottom to top, but that the tick that proves the crossing is easy and the next one also, then that I bought one touch, thank you very much

**Comment by Martinez222** [comment]
here u go @jose895 !
Feel free to develop it (change barrier,,time etc acording to your strategy)

[touch macd zxz.zip](https://github.com/binary-com/binary-bot/files/4399606/touch.macd.zxz.zip)

**Comment by jose895** [comment]
Thank you very much friend, God bless you

**Comment by jose895** [comment]
I was testing the bot but it does not work properly it takes false signals and evades the good ones, what I want is for the tick that causes the MA to cross and the next one to be bullish ticks, and that only if those conditions are met buy
