### ISSUE TITLE
Strategy Bot help!!

### ISSUE THREAD

**Issue by Zeemi20** [binary-com/binary-bot#2617]
I want to create a strategy that opens a rise trade if 1 minute candle was high for 2 times in a row, and open fall trade if 1 minute candle is lower for 2 times in a row. how ca I do it?

**Comment by Martinez222** [comment]
Salut!
I don't know if this is what u want but feel free to test & develop it!
[Hi Low Bot.zip](https://github.com/binary-com/binary-bot/files/4398856/Hi.Low.Bot.zip)
