### ISSUE TITLE
The provider_connection_token does not exist or has not been specified.

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2619]
The provider_connection_token does not exist or has not been specified. How To FIX
![image](https://user-images.githubusercontent.com/58647652/77850118-8aa42f80-71fa-11ea-83dd-eba00de4efd4.png)

**Comment by aaron-binary** [comment]
Hey @freedayz04,

Could you provide us with steps to reproduce this?

Regards,
Aaron

**Comment by harshalkharose** [comment]
> The provider_connection_token does not exist or has not been specified. How To FIX
> ![image](https://user-images.githubusercontent.com/58647652/77850118-8aa42f80-71fa-11ea-83dd-eba00de4efd4.png)

Same here

**Comment by harshalkharose** [comment]
Hello Harshal kharose here,
Please solve this
In MACD Indicator How to set fast moving average line cross slow moving average line then buy and wait for the same for next same move.
Please help thank you & regards
