### ISSUE TITLE
Testing a binary.com bot

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2621]
Hi,

Just wondering if there is any way to test a bot with historic data? i.e., Can we create a bot and test how it would have performed if it was run from 01/01/2020 to 28/02/2020? I thought that if there was a way to do so, we would be able to quickly and easily test a bot rather allowing it to run and waiting for a few days to know whether it would work or not.

**Comment by aaron-binary** [comment]
I believe @hotmatrixx made something like this previously, perhaps he can help out?

Regards,
Aaron

**Comment by binarybotbegginer** [comment]
@hotmatrixx and @binary-ex-machina Have you done something similar before?
