### ISSUE TITLE
Please Build This Stratergy for ODD/EVEN 

### ISSUE THREAD

**Issue by karkec** [binary-com/binary-bot#2622]
I have a strategy like Purchase Levels in numbers.
1 EVEN
2 ODD
3 EVEN
4 EVEN
5 ODD
6 ODD
7 EVEN
8 EVEN
9 EVEN
10 ODD
11 ODD
12 ODD. Follow this cycle until the trade in positive i.e. IF loss comes the BOT should follow the above mentioned trend. If the bot makes profit means, it should start the trend from beginning. For example if the bot makes profit green signal at level 8 means, then it should start from level one.

**Comment by qadeershah3266** [comment]
Trade for how many ticks?

**Comment by karkec** [comment]
10 ticks
