### ISSUE TITLE
Please give the bot an even odd one with a strategy that is at a loss.

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#2624]
I need an unprofitable even / odd robot with a strategy.

**Comment by udhaykumar1993** [comment]
> I need an unprofitable even / odd robot with a strategy.

i can provide you.  i will share you in short time.

**Comment by ZDEGLET** [comment]
@udhaykumar1993 
Okey

**Comment by udhaykumar1993** [comment]
> 
> 
> @udhaykumar1993
> Okey

Here is the ODD EVEN Bot

[EVEN_ODD_alternate.zip](https://github.com/binary-com/binary-bot/files/4415190/EVEN_ODD_alternate.zip)
