### ISSUE TITLE
Made a profitable bot. The problems started.

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#2625]
Made a profitable bot. The problems started.
At normal Internet speed, the bot loads 15 minutes, before a second.
Your profitable bot is being watched. You are under the hood. Further, a simple-to-execute bot issues incorrect transactions, as I still do not understand how to prove it later:(

**Comment by ZDEGLET** [comment]
Now it is loading normally again. I don’t understand what the problem is.

**Comment by Martinez222** [comment]
U can not beat them at their own game....

**Comment by harshalkharose** [comment]
Hello Harshal kharose here,
Please solve this
In MACD Indicator How to set fast moving average line cross slow moving average line then buy and wait for the same for next same move.
Please help thank you & regards

**Comment by Rithea268** [comment]
ONE
