### ISSUE TITLE
 last digit analysis bot (Rise/Fall)

### ISSUE THREAD

**Issue by Dilzez** [binary-com/binary-bot#2627]
Hello Friend !!!
I want to create a rise/fall bot to analyze the **last digit 4 times in a row.**
**If Blue Number,**
This is the blue number order 1<2<3<4<5<6<7<8<9 
1st time last digit < 2nd time last digit < 3rd-time last digit < 4th-time last digit --   --- Call trade 
Ex- 3,5,6,9 = call
      1,3,8,9  = call
      4,5,6,7 = call 
**_**if 1st time last digit was number  "7" we can't start to analysis because we cant take last digit 4 times.**_    (7,8,9,???)**
1st time last digit >2nd time last digit >3rd time last digit >4th time last digit --   --- Put trade 
Ex - 9,7,2,1 = put
       6,5,2,1 = put 
       8,6,5,3 = put 
**_**if 1st-time last digit was number  "3" we can't start to analysis because we can't take the last digit 4 times.**_    (3,2,1,???)**
**Don't consider the number "0" to analyze. Please ignore "0"** 

**If Red Number,**
This is the Red number order 9<8<7<6<5<4<3<2<1 
1st-time last digit < 2nd-time last digit < 3rd-time last digit < 4th-time last digit ----- Call trade 
Ex - 8,4,2,1 = call 
       9,5,3,4 = call
       7,6,5,4 = call 
**_**if 1st-time last digit was number  "3" we can't start to analysis because we can't take the last digit 4 times.**_    (3,2,1,???)**
1st time last digit >2nd time last digit >3rd time last digit >4th time last digit --   --- Put trade 
Ex - 1,4,6,8 = put
       4,7,8,9 = put 
       1,2,3,4 = put 
**_**if 1st-time last digit was number  "7" we can't start to analysis because we can't take the last digit 4 times.**_    (3,2,1,???)**
**Don't consider the number "0" to analyze. Please ignore "0"**

**Comment by Kosta92** [comment]
Digits are random numbers. Don't think too much about their "patterns" or try to think about a winning strategy because it won't work.

**Comment by Dilzez** [comment]
> Digits are random numbers. Don't think too much about their "patterns" or try to think about a winning strategy because it won't work.

I tried this strategy manually. but it takes a few  times to get a trade. that is why I am looking for a bot for this strategy

**Comment by Max-Profit** [comment]
> > Digits are random numbers. Don't think too much about their "patterns" or try to think about a winning strategy because it won't work.
> 
> I tried this strategy manually.it works but it takes a few times to get a trade. that is why I am looking for a bot for this strategy

How long you have tested manually and How about trade duration ( how many ticks ) ?

**Comment by Dilzez** [comment]
> > > Digits are random numbers. Don't think too much about their "patterns" or try to think about a winning strategy because it won't work.
> > 
> > 
> > I tried this strategy manually.it works but it takes a few times to get a trade. that is why I am looking for a bot for this strategy
> 
> How long you have tested manually and How about trade duration ( how many ticks ) ?

yes 5 ticks trades

**Comment by thommmaz** [comment]
Making digit bots is absolutely waste of time. You never win broker in its own game! Put your time and effort to call-put bots, during at least 2 minutes and then maybe you can earn some pennies.

**Comment by Dilzez** [comment]
> Making digit bots is absolutely waste of time. You never win broker in its own game! Put your time and effort to call-put bots, during at least 2 minutes and then maybe you can earn some pennies.
