### ISSUE TITLE
COG Indicator for Bots

### ISSUE THREAD

**Issue by traderjnunes** [binary-com/binary-bot#2629]
Dear All,

Is it possible to creat this indicator using binnary blocks?

https://www.markettraders.com/blog/center-gravity-indicator/

The COG consists of two lines and is based on the sum of prices over a specified period. A simple moving average of the COG is plotted along the indicator to act as a signal line which generates buy and sell signals.

The formula used to calculate the COG indicator is shown below:

COG = SUM of closing prices Pn x (n+1) / Sum of closing prices Pn

The standard settings of the indicator are the last 10 periods’ closing prices and a 3-period simple moving average of the COG, however you can adjust these settings to fine-tune the trading signals that the indicator returns.

**Comment by muroyal** [comment]
Formula ?

**Comment by harshalkharose** [comment]
Hello Harshal kharose here,
Please solve this
In MACD Indicator How to set fast moving average line cross slow moving average line then buy and wait for the same for next same move.
Please help thank you & regards

**Comment by traderjnunes** [comment]
> Formula ?

Yes. Link is available
