### ISSUE TITLE
macd histogram

### ISSUE THREAD

**Issue by cleberscr** [binary-com/binary-bot#2630]
hello friends i'm trying to do and looking for a while how to use macd in that way
if the macd histogram is green, rise
if the macd histogram is red, fall

could someone help me?

**Comment by Martinez222** [comment]
@cleberscr here u go :  
![macd h](https://user-images.githubusercontent.com/39260368/78450207-a6d61f80-7685-11ea-9cb1-bd741e671f9a.jpg)

**Comment by cleberscr** [comment]
> @cleberscr aqui você vai:
> ![macd h](https://user-images.githubusercontent.com/39260368/78450207-a6d61f80-7685-11ea-9cb1-bd741e671f9a.jpg)

oh boy, thank you so much <3
