### ISSUE TITLE
How to get the highest tick point of candle

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2641]
![image](https://user-images.githubusercontent.com/58647652/78546693-0c621180-7828-11ea-82bd-47fe1063dda7.png)

**Comment by Kosta92** [comment]
Inside **Tick Analysis** drag **In candles list read Open # from end 1 with interval Default**, and then change the variable **Open** to **High**.

![Candle](https://user-images.githubusercontent.com/11698414/78553794-31e02280-780a-11ea-90d2-08c27967529a.png)

**Comment by freedayz04** [comment]
Thank you ^^

> Inside **Tick Analysis** drag **In candles list read Open # from end 1 with interval Default**, and then change the variable **Open** to **High**.
> 
> ![Candle](https://user-images.githubusercontent.com/11698414/78553794-31e02280-780a-11ea-90d2-08c27967529a.png)

Thank you.
