### ISSUE TITLE
how to create 10 second Japanese candlestick and use a bot on it ??

### ISSUE THREAD

**Issue by petersob** [binary-com/binary-bot#2642]
I would like to create a bot that works on a 10 second timeframe

**Comment by Rigoff** [comment]
I'm interested too! I can create only 1 candle, for example 5 ticks candle, just take tick #5 this is the open candle, and the tick #1 or last tick this is the close candle, and high and low are the max and min for 5 ticks. After, create var this cnadle. After, cycle create variable candles. Or? I dont know... Maybe there is a simpler solution?

**Comment by petersob** [comment]
Send me a screenshot thank you I am a beginner

**Comment by petersob** [comment]
Send me a screenshot thank you I am a beginner

**Comment by petersob** [comment]
send me block screenshot

**Comment by Rigoff** [comment]
I'm sorry, I haven’t found a solution yet

**Comment by petersob** [comment]
Aidez moi

**Comment by petersob** [comment]
help me
