### ISSUE TITLE
management money

### ISSUE THREAD

**Issue by traderjnunes** [binary-com/binary-bot#2644]
Please is there a solution to use a bot to do a certain number of martingale when loos and Soros (multiply the result x 2) until a certain number of wins?

**Comment by ZDEGLET** [comment]
Yes

**Comment by traderjnunes** [comment]
I sent to you by e-mail

Example with profit 94%

Trade | Stake | Profit | Result | Notes
-- | -- | -- | -- | --
1 | $1.00 | $1.94 | Win |  
2 | $1.94 | $3.76 | Win |  
3 | $1.00 | $1.94 | Win | Back to initial Stake
4 | $1.94 | $1.94 | Loss |  
5 | $1.00 | $1.94 | Win |  
6 | $1.94 | $3.76 | Win |  
7 | $3.76 | $7.30 | Win |  
8 | $1.00 | $1.94 | Win |  
9 | $1.94 | $3.76 | Win |  
10 | $3.76 | $3.76 | Loss |  
11 | $1.00 | $1.00 | Loss |  
12 | $1.06 | $1.06 | Loss |  
13 | $2.20 | $2.20 | Loss |  
14 | $4.53 | $4.53 | Loss |  
15 | $9.35 | $9.35 | Loss |  
16 | $1.00 | $1.94 | Win | Back to initial Stake
17 | $1.00 | $1.94 | Win |

**Comment by Emptrader43** [comment]
Creo que estás aplicando Interés Compuesto ,,lo mejor sería , hacerlo corto para evitar quedar estancado.
