### ISSUE TITLE
Please help me with me some probabilities?

### ISSUE THREAD

**Issue by Migotto-R** [binary-com/binary-bot#2647]
Hello guys, i'm new here and i'm from Brazil! Up ahead, i'm sorry for any mistakes in my english, still learning..

So, i've been setting up a strategy for my bot in Binary with digits, match and differ.

We all know that this M/D strategy has 90% chance on winning on the first stake, am I correct?
The question is, if you lose on the first, then the second stake comes with martingale x 11 to keep earning, then if we loss again, we come to the third and fourth entrance with martingale. Has anyone seen more than 4 losses in a row? for weeks I've been making my robot, and having it backtested, and it never loses more than 3, and always win in the fourth entrance.
Could someone please give me your opinion about this? what is the probability to lose 4 in a row? 0,01%? 1 in 10000?

**Comment by Migotto-R** [comment]
![image](https://user-images.githubusercontent.com/63299284/78678445-56e29d00-78bf-11ea-97f9-2d359447f1e0.png)

**Comment by rubenspina** [comment]
I don't know how to make a bot but here is what I think the bot does not calculate the time I will give an example pause when the market goes against it and do not change the direction of buying all the bot buys in luck and there is no strategy in any bot this is the reason that you lose 4 times.

**Comment by rubenspina** [comment]
need this stupidity to make $ 1
![image](https://user-images.githubusercontent.com/30381449/80843489-d4f24500-8bda-11ea-9c1c-93ddbee04107.png)
