### ISSUE TITLE
Binary bot error

### ISSUE THREAD

**Issue by harshalkharose** [binary-com/binary-bot#2648]
![IMG-20200407-WA0015](https://user-images.githubusercontent.com/63083867/78705353-f8eb9f00-792a-11ea-8cb8-239c5db68b16.jpg)
Why this message showing please help

**Comment by aaron-binary** [comment]
Hey @harshalkharose,

This should be resolved now, please let us know if you're still experiencing this error by emailing us at support@binary.com.

Regards,
Aaron

**Comment by harshalkharose** [comment]
Hello yes still same error showing 
what to write in mail,
is you binary support team?
