### ISSUE TITLE
Binary bot result without martingale.

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2651]
https://youtu.be/42MM4PnrRi0

**Comment by thommmaz** [comment]
> https://youtu.be/42MM4PnrRi0

Pointless.First of all its demo and that guy is a scammer. He is only selling bots nothing else. Probably have never tried any of his "grail projects" in real account.

**Comment by virtusasys** [comment]
i think your the beggar from email guy..  dont insult man...i dont give it to you and dont beg.. please

**Comment by virtusasys** [comment]
all reference numbers date time all details have binary. ask them.. i dont give it to you.. dont beg ...

**Comment by virtusasys** [comment]
![tghom](https://user-images.githubusercontent.com/59830499/78754622-6f24eb80-7995-11ea-8ae1-db08fe37d75b.JPG)
Begger...

**Comment by vixtrade** [comment]
> > https://youtu.be/42MM4PnrRi0
> 
> Pointless.First of all its demo and that guy is a scammer. He is only selling bots nothing else. Probably have never tried any of his "grail projects" in real account.

Yeah, well-known scammer is behind these youtube videos. Have had little chat with that guy, he asked $5K for bot.

**Comment by vixtrade** [comment]
> ![tghom](https://user-images.githubusercontent.com/59830499/78754622-6f24eb80-7995-11ea-8ae1-db08fe37d75b.JPG)
> Begger...

You are wrong, this is not @thommmaz email. Check your facts before making yourself fool :D :D

**Comment by virtusasys** [comment]
![ddddddddddddddd](https://user-images.githubusercontent.com/59830499/78784089-55e66400-79c2-11ea-8573-c4281b90182b.JPG)
Same Guy.. GUMROAD SCAMMERS.. IDIOTS...

**Comment by virtusasys** [comment]
I am Close this.. cant reply these Like Beggers.. when these idiots beg and beg when not given blame it.. IDIOTS...Poor Beggers
