### ISSUE TITLE
Offsetting position BOT

### ISSUE THREAD

**Issue by BinaryMollefar** [binary-com/binary-bot#2654]
Hello guys, 

Does anybody knows how to create a BOT that places 2 positions at the exact same time? Basically I want to create a BOT that opens 2 positions for BUY/SELL, HIGHER/LOWER, OVER/UNDER and so fort at the exact same time - **offsetting each other**. The trade will be trickerede by some of the indicators available. 

When I try to create the my BOT in the drag'n drop builder I'm not able to create more than one buy/sell-window and I don't see any ways of creating a "do this **AND** this if..." module. 

Looking forward to hearing from you guys. 

Regards, 
BinaryMollefar

**Comment by thommmaz** [comment]
> Hello guys,
> 
> Does anybody knows how to create a BOT that places 2 positions at the exact same time? Basically I want to create a BOT that opens 2 positions for BUY/SELL, HIGHER/LOWER, OVER/UNDER and so fort at the exact same time - **offsetting each other**. The trade will be trickerede by some of the indicators available.
> 
> When I try to create the my BOT in the drag'n drop builder I'm not able to create more than one buy/sell-window and I don't see any ways of creating a "do this **AND** this if..." module.
> 
> Looking forward to hearing from you guys.
> 
> Regards,
> BinaryMollefar

As far as I know it is not possible for one bot opening two opposite trades at the same time. You can open two windows and two bots but there comes time delay. Other option is do that manually -  bot is doing buy and you manually click sell.
