### ISSUE TITLE
Set up SMMA index on binary.com

### ISSUE THREAD

**Issue by bangvanthuat** [binary-com/binary-bot#2661]
Hello
Please understand if my writing is not good.
Can you show me or set me an SMMA indicator with an input of 7 in the binary.com bot?
Thanks!

**Comment by aaron-binary** [comment]
Hey @bangvanthuat,

You may use the SMA indicator block as per below example:

<img width="684" alt="Screenshot 2020-04-10 at 09 49 51" src="https://user-images.githubusercontent.com/44427668/78955076-bd122e80-7b10-11ea-82e2-c8ac237ed56d.png">

I've attached the blocks as a .txt file to this post, you may download it and remove the .txt extension, then you can upload it into Binary Bot.

Hope that helps,
Aaron

[bangvanthuat.xml.txt](https://github.com/binary-com/binary-bot/files/4459462/bangvanthuat.xml.txt)

**Comment by bangvanthuat** [comment]
Hello aaron-binary
Thank you for your interest in my problem.
It looks like your share is not what I expected.  The SMMA indicator that I'm interested in is calculated by the formula below, and on the bot binary that indicator I already know about. Can you help me set the index according to the formula below?  thanks!
The formula to calculate the SMMA is –

SMMA = (SMMA# – SMMA* + CLOSE)/N

Where

SMMA# – Previous bar’s smoothed sum

SMMA* – Previous bar’s smoothed moving average

CLOSE – Present closing price

N – Period of smoothing

**Comment by Martinez222** [comment]
@bangvanthuat see here:
https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/smoothed_moving_average/exmachina-smma.xml

**Comment by bangvanthuat** [comment]
Thank you, I did the same thing.
