### ISSUE TITLE
Help Me Search Zipcode Angular 

### ISSUE THREAD

**Issue by Eulerhp** [binary-com/binary-bot#2662]
I want to automatically fill in or address fields with the data returned from the query on get http.
Helpe me
Example:
input text zipcode ng-blur = 12564865
input text address = Street Amazon 

`This my controller.
self.validateCep = function() {
            var str = trim(self.profile.cep);

            self.pegaCep = function () {
                $http.get("http://localhost/markeet-web/cep.php?cep="+str).success(function (retorno){
                    console.log(retorno);
                    self.cep = retorno.data;
                    if(retorno.data == 1){
                        $('#profile_address').val(data.profile_address);
 
                        root.requestFocus('profile_num');
                    }
                });
             }

            if (str == ''){
                self.valid.cep = false;
                root.requestFocus('profile_cep');
                return false;
            } else {
                self.valid.cep = true;
            }
            return true;
        };

===========================================
This my form html
 <div layout="row">
                            <md-input-container flex>
                                <label>CEP</label>
                                <input ng-model="profile.cep" type="text" id="profile_cep" ng-blur="pegaCep()" ng-change="validateCep()">
                                <error-message ng-if="!valid.cep">invalid cep</error-message>
                            </md-input-container>
                        </div>
                      
                        
                        <div layout="row">
                            <md-input-container flex>
                                <label>Address</label>
                                <textarea ng-model="profile.address" name="profile.address" rows="3" id="profile_address" ng-change="validateAddress()">
                                    </textarea>
                                <error-message ng-if="!valid.address">invalid address</error-message>
                            </md-input-container>
                        </div>`

**Comment by aaron-binary** [comment]
Hey @Eulerhp,

This is probably not the right place to ask. I recommend asking your question over at Stackoverflow where they'll be able to assist you better.

- https://stackoverflow.com/questions/ask

Regards,
Aaron
