### ISSUE TITLE
need help in a bot 

### ISSUE THREAD

**Issue by damdam97** [binary-com/binary-bot#2663]
can anyone help implement martingale into this differ digits bot
[binary-bot-digit-differ.zip](https://github.com/binary-com/binary-bot/files/4459027/binary-bot-digit-differ.zip)

 thank you guys

**Comment by Martinez222** [comment]
[diggit differ martg.zip](https://github.com/binary-com/binary-bot/files/4463001/diggit.differ.martg.zip)

**Comment by damdam97** [comment]
> [diggit differ martg.zip](https://github.com/binary-com/binary-bot/files/4463001/diggit.differ.martg.zip)

thank you so much brother
