### ISSUE TITLE
Binary bot match digit

### ISSUE THREAD

**Issue by harshalkharose** [binary-com/binary-bot#2665]
Hello can help me with match digit strategy to build bot thank you

**Comment by Martinez222** [comment]
See here : 
https://github.com/binary-com/binary-bot/issues/2538

**Comment by harshalkharose** [comment]
Thank you Martine you right you said MACD strategy will give more false signals

**Comment by harshalkharose** [comment]
How we notify current position of cursor not last tick I'm talking about I'm talking last tick
