### ISSUE TITLE
Create timer block for BOT binary.com

### ISSUE THREAD

**Issue by bangvanthuat** [binary-com/binary-bot#2668]
Hello friends.
Let me ask you a question that I think many of you have the same problem with me. That is how to set the bot a timer function block in time is seconds, minutes, hours and days in real time? (my purpose when asking this problem is to solve the problem so that I can set a buy or sell order according to my intended time when the signal is good, not to wait for the end of a candle, when that has lost a nice price to place order).
I hope someone can solve this problem of mine.
Thanks!

**Comment by Martinez222** [comment]
there is a ex machina full version with date ..u just search for it in this github.This is what i've got :
[time stmp.zip](https://github.com/binary-com/binary-bot/files/4463111/time.stmp.zip)
![time is](https://user-images.githubusercontent.com/39260368/79018252-06e42e80-7b7c-11ea-9ffc-ae7ed2dd07b8.jpg)

**Comment by bangvanthuat** [comment]
Oh, great, this is what I need now.
Thank you very much !

Vào Th 7, 11 thg 4, 2020 vào lúc 02:39 Martinez222 <
notifications@github.com> đã viết:
