### ISSUE TITLE
Binary bot issue

### ISSUE THREAD

**Issue by harshalkharose** [binary-com/binary-bot#2671]
How we notify current position of cursor not last tick
 I'm talking about current position of point how can we notify please help

**Comment by Kosta92** [comment]
**Last Tick** is the current position of a point.

See my example:

![Last Tick](https://user-images.githubusercontent.com/11698414/79038642-3413f980-7bdb-11ea-982e-31e58026e845.png)

**Comment by harshalkharose** [comment]
That was last tick as I said I don't want last tick live tick or location

**Comment by Kosta92** [comment]
Upload a screenshot of what exactly do you want to make. You can't notify a position of a mouse cursor because the bot can't see your cursor at all.
