### ISSUE TITLE
ANY ONE CAN HELP ME

### ISSUE THREAD

**Issue by islamrefaey2019** [binary-com/binary-bot#2673]
I WANT TO CONVERT THIS TXT TO XML
[Rise.Fall.Predictor..txt](https://github.com/binary-com/binary-bot/files/4465297/Rise.Fall.Predictor.txt)
 BOT

**Comment by JenggotSantuy** [comment]
> I WANT TO CONVERT THIS TXT TO XML
> [Rise.Fall.Predictor..txt](https://github.com/binary-com/binary-bot/files/4465297/Rise.Fall.Predictor.txt)
> BOT

Enjoy it
[RiseFallPredictor.zip](https://github.com/binary-com/binary-bot/files/4465349/RiseFallPredictor.zip)

**Comment by islamrefaey2019** [comment]
THANKS ALOT

**Comment by Kosta92** [comment]
Just rename the file extension from **.TXT** to **.XML** and that's it.
