### ISSUE TITLE
MACD Histogram it's different values from Binary Chart

### ISSUE THREAD

**Issue by caduafonso** [binary-com/binary-bot#268]
Hi guys, coding my MACD Histogram, I noted the values are different from Binary.com. I'm trying get last exact Macd in tick list but the numbers are always differents. How can I fix it?

**## Binary Chart**
![image](https://user-images.githubusercontent.com/29738946/27607502-74f72eee-5b5a-11e7-9552-76004593f4ea.png)

**## Bot Binary**
![image](https://user-images.githubusercontent.com/29738946/27607601-c3171d64-5b5a-11e7-918e-28fd43b517cd.png)

**Comment by BotBrazil** [comment]
![image](https://user-images.githubusercontent.com/29413757/27774167-3804eae2-5f62-11e7-92ca-17ad79cfd76f.png)

**Comment by caduafonso** [comment]
Oi BotBrazil! Creio que é brasileiro, correto? Então amigo, eu quero trabalhar com Ticks, acompanhando os valores que meu Robô mostra, são diferentes da tabela da traingview/Binary.com. 

O valor MACD eu consigo achar exato trabalhando em Ticks, mas o MACD Signal e MACD Histogram são sempre diferentes ao trabalhar em Ticks. Não consigo de jeito nenhum fazer com que os valores sejam iguais a da tabela e assim, a abertura de operação que o robô faz acaba sempre tendo Loss.

**Comment by aminmarashi** [comment]
We added trading view chart inside the Binary Bot. You can now compare the indicator values between the two charts and the output of the indicator blocks. Please make sure you're using the same configurations in the charts and the indicator blocks:
<img width="1280" alt="screen shot 2017-07-03 at 4 25 58 pm" src="https://user-images.githubusercontent.com/6560964/27784484-d212c442-600c-11e7-8df2-c25a54f6cd0e.png">
**Note:** The default values provided for indicators matches the Binary Bot chart indicators.
