### ISSUE TITLE
How can I make the text "Time" into next line of telegram

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2683]
![93186125_3020533618011578_3748386498030862336_o](https://user-images.githubusercontent.com/58647652/79216081-cdab0780-7e76-11ea-95e5-b7cfe485d96d.jpg)
![92446017_3020535964678010_1171669539365060608_n](https://user-images.githubusercontent.com/58647652/79216085-cedc3480-7e76-11ea-8dbf-01c2fdd370f6.jpg)

**Comment by bangvanthuat** [comment]
@freedayz04 
Please explain in more detail what you want so we can help you.

**Comment by freedayz04** [comment]
> @freedayz04
> Please explain in more detail what you want so we can help you.

need that "Time Line" move to the bottom line

**Comment by aaron-binary** [comment]
Hey @freedayz04,

We don't currently support multiline strings. 

We'll discuss internally whether we should add a multiline text block that allows you to specify multiple lines of text. 

As a quick workaround, you could send multiple messages to Telegram for now.

Regards,
Aaron
