### ISSUE TITLE
RSI, bollinger bands and martingale all in one bot

### ISSUE THREAD

**Issue by BinaryMollefar** [binary-com/binary-bot#2684]
Hello, 

Does anybody know how to combine RSI, bollinger bands and martingale all in one bot? I want a bot that takes a trade every time RSI and bollinger bands are both satisfied. 

Furthermore does anybody know how to make a bot that opens the position on the next candle? So when the signal is activated the bot waits until the next candle opens and then executes the trade? (see pictures below)

Regards, 
BinaryMollefar

![download](https://user-images.githubusercontent.com/63345427/79234423-87e84200-7e6a-11ea-8ee7-bebb113bb5ca.png)
![download (1)](https://user-images.githubusercontent.com/63345427/79234431-8ae33280-7e6a-11ea-995a-809b8f8ae9e9.png)

**Comment by bangvanthuat** [comment]
Hello @BinaryMollefar 
See if this is what you are looking for?
![image](https://user-images.githubusercontent.com/63410420/79241910-da8f2180-7e9d-11ea-910b-7bd9fde30563.png)
![image](https://user-images.githubusercontent.com/63410420/79242017-f85c8680-7e9d-11ea-8030-001147e7370e.png)

**Comment by BinaryMollefar** [comment]
Thanks for sharing @bangvanthuat 

It might well be what I was looking for. Is it possible that you could share the XML-file with me?

Furthermore, do you know to build martingale into the bot? I would like the bot take advantage of the martingale strategy when a loss occur, but only after the bot has returned to the yellow area of RSI as shown below. 

![download](https://user-images.githubusercontent.com/63345427/79390018-3d042280-7f6f-11ea-8ab1-c6c881200bda.png)

**Comment by bangvanthuat** [comment]
Dear @BinaryMollefar.
The conditions given for the bot to work are unknown, so I can only set up
the bot as below (There was martingale and max loss). You can develop
further depending on your desired conditions based on the blocks you give.
Good luck!
[image: image.png]
[image: image.png]


Vào Th 5, 16 thg 4, 2020 vào lúc 04:19 BinaryMollefar <
notifications@github.com> đã viết:

**Comment by BinaryMollefar** [comment]
Again thanks for sharing @bangvanthuat. However, it's not possible to see the pictures (don't know if something went wrong?). 

The conditions doesn't matter for now - I would just like to test the XML-file for the above screenshots and see how the martingale works with the strategy and then I can build on myself.

**Comment by bangvanthuat** [comment]
Sorry. I don't know how to add attachments now, I tried the zip file but it
didn't work.  If you know please show me or give me the email address I
will send you.

Vào 14:42 T.5, 16 Th4 2020 BinaryMollefar <notifications@github.com> đã
viết:

**Comment by bangvanthuat** [comment]
@BinaryMollefar 
I have sent you the BOT you are looking for, it is in text form. You paste it into a new bot file, delete all the data in that bot and copy all my data into it.
[BOT= one minutes bollinger bands + RSI.txt](https://github.com/binary-com/binary-bot/files/4487971/BOT.one.minutes.bollinger.bands.%2B.RSI.txt)

**Comment by BinaryMollefar** [comment]
Thank you very much @bangvanthuat 
Furthermore, my email address is mortenlaursen1234@hotmail.com if you still want to send the XML-file. I would be great if you could also send the pictures you tried to attach above.
