### ISSUE TITLE
need help in a bot

### ISSUE THREAD

**Issue by damdam97** [binary-com/binary-bot#2685]
can anyone help me fix that bot please 

![Screenshot_1](https://user-images.githubusercontent.com/62912459/79267254-c690f300-7e90-11ea-8791-c7b7c5e11596.png)

[BULL MARKET For $25 Profit.zip](https://github.com/binary-com/binary-bot/files/4477390/BULL.MARKET.For.25.Profit.zip)

**Comment by Kosta92** [comment]
What's wrong with it?
