### ISSUE TITLE
File attached

### ISSUE THREAD

**Issue by bangvanthuat** [binary-com/binary-bot#2687]
Hi.
I am a new member, people only help me how to add attachments to the reply. I do not know how yet.
Thanks!

**Comment by JenggotSantuy** [comment]
> Hi.
> I am a new member, people only help me how to add attachments to the reply. I do not know how yet.
> Thanks!

please click on the circled icon
just follow the instructions
hopefully can help
![IMG_20200416_200529](https://user-images.githubusercontent.com/61324577/79459760-f91c2680-801d-11ea-83e8-f21c1bf8fccf.JPG)

**Comment by bangvanthuat** [comment]
@JenggotSantuy This is all my appearance.
![1](https://user-images.githubusercontent.com/63410420/79470358-7bf7ae00-802b-11ea-8441-b181f3bb3b7e.PNG)

**Comment by JenggotSantuy** [comment]
possible to attach not displayed
try clicking the arrow down the rightmost who knows

![IMG_20200417_034700](https://user-images.githubusercontent.com/61324577/79505149-2983b500-805e-11ea-99d0-69f6e5218f11.JPG)
