### ISSUE TITLE
EMA wrong values

### ISSUE THREAD

**Issue by rgoncalves** [binary-com/binary-bot#269]
Hello all,

I am trying to use EMA without success:
![image](https://user-images.githubusercontent.com/666184/27692644-22ad955c-5cdf-11e7-8269-fd5a795788b3.png)

Values:
![image](https://user-images.githubusercontent.com/666184/27692728-59ae5226-5cdf-11e7-820c-3cf7c779f7dc.png)

Why does EMA value is a lot of values? And also why value is different than binary.com graph?
I am trying to compare SMA with EMA...and like this is impossible.

![image](https://user-images.githubusercontent.com/666184/27692919-d0849432-5cdf-11e7-90b8-9015714a56b9.png)

Thanks

**Comment by Fruitfella** [comment]
Hello Ricardo! long time no see.
you are wondering why EMA has a lot of values? _lol_ thats because you
were using **EMA Array** , you can use the normal one to get 1 value.
There are 2 types of Indicators, the normal one under **Indicators**
menu and the array type under **Advanced** menu.

**Comment by sinung21** [comment]
try this   https://depositfiles.com/files/eb70mnxl3

**Comment by rgoncalves** [comment]
Hello @Fruitfella and  @sinung21 , 

thanks a lot! I was able to see where I did wrong. :)

BR
