### ISSUE TITLE
[Bugs] Why don't binary.com can't let me set 1 minute candle ? & Can't change period of indicator 

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2692]
![image](https://user-images.githubusercontent.com/58647652/79558021-bd409a00-80cd-11ea-909f-0ad636606b23.png)

and when i click this. It hidden and I cant change period and anything
![image](https://user-images.githubusercontent.com/58647652/79558333-29230280-80ce-11ea-9efc-cec5bc113483.png)

**Comment by Martinez222** [comment]
I have the same problem..

**Comment by bangvanthuat** [comment]
I also recognize that problem. It just arises in the recent update.

**Comment by Kosta92** [comment]
This recent update also broke the indicator settings - can't access them.

**Comment by aaron-binary** [comment]
Hey all,

This is a bug and we're working on fixing this.

Regards,
Aaron
