### ISSUE TITLE
How to setup bot to order when last digit show >8 or 9 twice?

### ISSUE THREAD

**Issue by birdykung** [binary-com/binary-bot#2694]
Hello,
I would to create my stretegy. I test about 2 weeks.
I play DIGITUNDER by Prediction = 8 and i observe when last digit show 8 or 9 twice
 (tick1=8, tick22=8 / tick1=8, tick22=9 / tick1=9, tick22=8 / tick1=9, tick22=9)
then click purchase under, it will win almost all time (winrate about 90%).

So, I would to create bot but i do not know how to set block. Could anyone help me to design?

**Comment by bangvanthuat** [comment]
Numbers appear completely random, without any rules at all and it is possible that the floor's algorithm will make your choices wrong and lead to losses. Please consider with your choice.

**Comment by Martinez222** [comment]
@birdykung  here u go : 

[under 8.zip](https://github.com/binary-com/binary-bot/files/4493585/under.8.zip)

**Comment by birdykung** [comment]
> @birdykung here u go :
> 
> [under 8.zip](https://github.com/binary-com/binary-bot/files/4493585/under.8.zip)

Thank you so much

**Comment by birdykung** [comment]
> @birdykung here u go :
> 
> [under 8.zip](https://github.com/binary-com/binary-bot/files/4493585/under.8.zip)

Excuse me,
![Screenshot_31](https://user-images.githubusercontent.com/38474267/79583568-79628a80-80f7-11ea-9246-a73e86b5beb7.png)
 where i get this function on left menu?

**Comment by Martinez222** [comment]
![11](https://user-images.githubusercontent.com/39260368/79584065-8c189780-80d6-11ea-91be-f0c382055c6c.jpg)
![12](https://user-images.githubusercontent.com/39260368/79584071-8de25b00-80d6-11ea-863f-1d2f79a7ba2a.jpg)

**Comment by birdykung** [comment]
OK i saw it when right click. Thanks

**Comment by deeptechno90** [comment]
Hello Guys!I want to make a digit under bot take under purchases if the last digit is 8 followed by 9 or 9 followed by 8.  Prediction is 8 Volatility 10 index. 1 tick.   

Much Love!
