### ISSUE TITLE
Bot is not running please help

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#2695]
https://drive.google.com/open?id=1y9y6JxF61Y4L3Ru1cX10ZUVXTFKWviSi

**Comment by Martinez222** [comment]
GG my men!I've got good results!
![results](https://user-images.githubusercontent.com/39260368/79692772-a46fea00-826f-11ea-8e38-0c8ca5d79d08.jpg)

**Comment by tymu** [comment]
@Martinez222 hello, can you share your version?

**Comment by rubenspina** [comment]
veja isto todos
https://ongdetraders.blogspot.com/
[cid:b4d848ab-f521-4a54-a097-235b6d2706f6]
[https://1.bp.blogspot.com/-OZPbOBXonbc/XvPcVuBmH_I/AAAAAAAAAhQ/sxZyRFg72Q8V3NDyKwbDFKNIPYYQY5eJACNcBGAsYHQ/w1200-h630-p-k-no-nu/dollar.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com
[cid:0f5bec70-0b69-4647-836c-6ee2f87dd4a6]

________________________________
De: Aaron <notifications@github.com>
Enviado: segunda-feira, 11 de maio de 2020 04:13
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Bot is not running please help (#2695)


Closed #2695<https://github.com/binary-com/binary-bot/issues/2695>.

**Comment by Gajandanraj** [comment]
Please share the working version
