### ISSUE TITLE
Custom martingale steps

### ISSUE THREAD

**Issue by SanJess** [binary-com/binary-bot#2696]
Can someone please help me to add custom size martingale steps(5 [steps)
 to this Binary.com bot
[binary-bot $10.zip](https://github.com/binary-com/binary-bot/files/4494124/binary-bot.10.zip)

**Comment by Martinez222** [comment]
What custom steps?

**Comment by SanJess** [comment]
Custom amounts like step1 $0.35, step2 $0.39, step3 $0.80 step4 $1.64 ........ Not the usual multiplication

**Comment by Martinez222** [comment]
@SanJess here u go my friend :  


[binary-bot modified $10.zip](https://github.com/binary-com/binary-bot/files/4496324/binary-bot.modified.10.zip)
Stay safe!

**Comment by SanJess** [comment]
Thank you so so much for the help. I use to be able to choose the sequence (call, call, put, put) can you please do that too.

**Comment by Martinez222** [comment]
Did u search for what u want in this github?I'm sure that  this is already  discussed..

**Comment by SanJess** [comment]
Yes I did, thanks anyway.
