### ISSUE TITLE
Can anyone please help me on how to set up a binary bot. I have tried setting it up myself but very hard as I don’t have any technical experience . Any support will be appreciated please. Thanks 

### ISSUE THREAD

**Issue by onwuzurike** [binary-com/binary-bot#2698]

**Comment by ZDEGLET** [comment]
Was?

**Comment by rubenspina** [comment]
ok vejo você sempre nas postagem de bot e nao estou bricando tenho varios bot que pego aqui mas o melhor que achei é o pinbar tenho um bot aqui que faz o que eu quero so que tive de colocar um pause nele e ficar olhando o grafico para clicar nele para executar eu sou o gatilho do but e eu que mudo a direçao dele manual se vai subir ou descer. vc tem o que preciso veja esta nao da para saber a hora certa que o mercado vai ficar a favor do bot
![image](https://user-images.githubusercontent.com/30381449/79614031-10b6e600-80d6-11ea-93d6-44a893bf9a37.png)
![image](https://user-images.githubusercontent.com/30381449/79614095-3348ff00-80d6-11ea-910a-66a53b4fb0f3.png)
![image](https://user-images.githubusercontent.com/30381449/79614144-4d82dd00-80d6-11ea-9249-083b707eee7c.png)

**Comment by onwuzurike** [comment]
Hi Rubespina,

Can you please speak in English language so that I understand you?

Thanks.

Coleman


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rubenspina** [comment]
eu uso 
https://translate.google.com.br/

**Comment by thommmaz** [comment]
> ok vejo você sempre nas postagem de bot e nao estou bricando tenho varios bot que pego aqui mas o melhor que achei é o pinbar tenho um bot aqui que faz o que eu quero so que tive de colocar um pause nele e ficar olhando o grafico para clicar nele para executar eu sou o gatilho do but e eu que mudo a direçao dele manual se vai subir ou descer. vc tem o que preciso veja esta nao da para saber a hora certa que o mercado vai ficar a favor do bot
> ![image](https://user-images.githubusercontent.com/30381449/79614031-10b6e600-80d6-11ea-93d6-44a893bf9a37.png)
> ![image](https://user-images.githubusercontent.com/30381449/79614095-3348ff00-80d6-11ea-910a-66a53b4fb0f3.png)
> ![image](https://user-images.githubusercontent.com/30381449/79614144-4d82dd00-80d6-11ea-9249-083b707eee7c.png)

I see you have been running same bot like 2 years know? Have you ever tried it on real account?

Vejo que você está executando o mesmo bot há 2 anos, sabe? Você já tentou isso por conta real?

**Comment by Martinez222** [comment]
@onwuzurike what is your strategy?
