### ISSUE TITLE
Sell available and take profit

### ISSUE THREAD

**Issue by rgoncalves** [binary-com/binary-bot#270]
Hello all,

does any one have an example how to use sell available after purchase?

Thanks
BR

**Comment by Fruitfella** [comment]
@rgoncalves, cant give u sample now but ill give u a hint.
[Sell is available] block in "during purchase" (S3 if my memory didnt fail me).
Note that not every contract can be close before it expired, so this
"sell is available" is to check if its possible to close the contract
before it expire and u close the contract with the other block [sell
at market].
if u want to experiment with this block, try any purchase with
duration 1 Minute or more

**Comment by BotBrazil** [comment]
@Fruitfella 
Please as soon as possible give us an example of doing so as soon as we are in profit. tks

**Comment by rgoncalves** [comment]
Hi @Fruitfella, thanks a lot for your feedback. I was able to use "during purchase" (S3).
