### ISSUE TITLE
How to provide copy trading to others

### ISSUE THREAD

**Issue by Muroyal1** [binary-com/binary-bot#2706]
I have created Forex telegram channel 

https://t.me/chanikyaforex1 

@chanikyaforex1

Many subscribers and followers are asking copy trading is there any tool for providing my strategies trades to others ?

**Comment by aaron-binary** [comment]
Hey @Muroyal1,

We don't have an interface for this in Binary Bot, however your followers may be able to get it working using Webtrader. Please see this video for more information:

- https://www.youtube.com/watch?v=dJ6i90Hf0Fg

It would require you to generate a **Read-only** token and share that with your followers, once they take your token and submit it in the form depicted in the screenshot below, the copying should work.

<img width="625" alt="Screenshot 2020-04-21 at 09 41 40" src="https://user-images.githubusercontent.com/44427668/79815843-50225280-83b4-11ea-9112-59366bdbca7d.png">

Let me know if this worked. 👍 

Regards,
Aaron

**Comment by Muroyal1** [comment]
Thanks I will try it..
