### ISSUE TITLE
Can we keep history tick? 

### ISSUE THREAD

**Issue by birdykung** [binary-com/binary-bot#2707]
Hello,
I have idea to set bot but i do not know to setup.
I would like to keep last digit back 100 ticks and check no. 0-7 have more than 8-9 then purchase "Under".

Can anyone have idea to setup bot?

**Comment by bangvanthuat** [comment]
@birdykung 
If you want to type the ratio of the number of words 0-7 is greater than the number from 8-9, then what you want is offline.
BOT only works when all the numbers 0-9 appear and I only do historical data of 25 numbers, if you want the data history of 100 numbers you will develop more based on the pattern.




=>>> [BOT.txt](https://github.com/binary-com/binary-bot/files/4530263/BOT.txt)
