### ISSUE TITLE
Digit Differ Strategy

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2708]
Hi All,

Good Day. I have a query about creating a bot with the "Digit Differ" strategy. Apologies in advance if the question is amateurish or something that is impossible. 

Just wondering whether we can create a bot which would take the last digit of the ENTRY SPOT as the "prediction" and bet on that differing in the EXIT SPOT after 20 seconds?

**Comment by Kosta92** [comment]
Of course that is possible, but there is no strategy behind this because the last digits are just random numbers and there is no point of delaying the trade for 20 seconds because the exit spot digit could as well be the same as an entry spot one, not different. Digits are a waste of time and money.

**Comment by binarybotbegginer** [comment]
> Of course that is possible, but there is no strategy behind this because the last digits are just random numbers and there is no point of delaying the trade for 20 seconds because the exit spot digit could as well be the same as an entry spot one, not different. Digits are a waste of time and money.

Thanks for your response. Yes, I do get that last digits are random numbers. But I just wanted to try this strategy, maybe with different time periods. Is there a way to pick the LAST DIGIT of the ENTRY SPOT as a prediction?

**Comment by binarybotbegginer** [comment]
For eg., if the ENTRY SPOT is 7187.207, I was looking to create a bot that would predict the last digit to differ from "7" after 20 seconds. Is it possible to create something like that?

**Comment by binarybotbegginer** [comment]
@hotmatrixx
@aaron-binary
@binary-ex-mechina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

**Comment by binarybotbegginer** [comment]
@hotmatrixx
@aaron-binary
@binary-ex-machina
@gokula-krishna-dev
@Eshhh
@Batekmax
@lasaidhari

**Comment by sinung21** [comment]
[LD AFTER 20.zip](https://github.com/binary-com/binary-bot/files/4524961/LD.AFTER.20.zip)
here for you

**Comment by binarybotbegginer** [comment]
> [LD AFTER 20.zip](https://github.com/binary-com/binary-bot/files/4524961/LD.AFTER.20.zip)
> here for you

Hi there, Thanks a lot for that. The bot appears to work, but sorry, it works a bit differently to how I wanted it to.
Sorry if I was not clear earlier. I wanted the LAST DIGIT of the "Entry Spot" to be taken as the PREDICTION.
![image](https://user-images.githubusercontent.com/62483125/80184225-4cb1f400-865e-11ea-9af6-49a0e66ad671.png)
For example: This image is a screenshot taken when the bot was running. The LAST DIGIT of the "Entry Spot" is 8 but the prediction is 9. I would like the prediction to be 8. Thus I would like to set the prediction that the LAST DIGIT of the "Exit Spot" won't be 8 after 10 ticks.

Thanks

**Comment by binarybotbegginer** [comment]
> [LD AFTER 20.zip](https://github.com/binary-com/binary-bot/files/4524961/LD.AFTER.20.zip)
> here for you

Hi there, Thanks a lot for that. The bot appears to work, but sorry, it works a bit differently to how I wanted it to.
Sorry if I was not clear earlier. I wanted the LAST DIGIT of the "Entry Spot" to be taken as the PREDICTION.
![image](https://user-images.githubusercontent.com/62483125/80184706-33f60e00-865f-11ea-9994-5df53f9fcf28.png)

For example: This image is a screenshot taken when the bot was running. The LAST DIGIT of the "Entry Spot" is 8 but the prediction is 9. I would like the prediction to be 8. Thus I would like to set the prediction that the LAST DIGIT of the "Exit Spot" won't be 8 after 10 ticks.

Is it possible to do something like that?

Thanks

**Comment by binarybotbegginer** [comment]
> [LD AFTER 20.zip](https://github.com/binary-com/binary-bot/files/4524961/LD.AFTER.20.zip)
> here for you

Hi there, Thanks a lot for that. The bot appears to work, but sorry, it works a bit differently to how I wanted it to.
Sorry if I was not clear earlier. I wanted the LAST DIGIT of the "Entry Spot" to be taken as the PREDICTION.
![Uploading image.png…]()

For example: This image is a screenshot taken when the bot was running. The LAST DIGIT of the "Entry Spot" is 8 but the prediction is 9. I would like the prediction to be 8. Thus I would like to set the prediction that the LAST DIGIT of the "Exit Spot" won't be 8 after 10 ticks.

Is it possible to do something like that at all?

Thanks

**Comment by binarybotbegginer** [comment]
> [LD AFTER 20.zip](https://github.com/binary-com/binary-bot/files/4524961/LD.AFTER.20.zip)
> here for you

Hi there, Thanks a lot for that. The bot appears to work, but sorry, it works a bit differently to how I wanted it to.
Sorry if I was not clear earlier. I wanted the LAST DIGIT of the "Entry Spot" to be taken as the PREDICTION.
![image](https://user-images.githubusercontent.com/62483125/80196260-40836200-8671-11ea-850f-5ba33acd1333.png)


For example: This image is a screenshot taken when the bot was running. The LAST DIGIT of the "Entry Spot" is 8 but the prediction is 9. I would like the prediction to be 8. Thus I would like to set the prediction that the LAST DIGIT of the "Exit Spot" won't be 8 after 10 ticks.

Is it possible to do something like that at all?

Thanks

**Comment by sinung21** [comment]
[LD 8 PREDICT 8 10TICK V100.zip](https://github.com/binary-com/binary-bot/files/4530696/LD.8.PREDICT.8.10TICK.V100.zip)
MAY BE LIKE THAT

**Comment by binarybotbegginer** [comment]
> [LD 8 PREDICT 8 10TICK V100.zip](https://github.com/binary-com/binary-bot/files/4530696/LD.8.PREDICT.8.10TICK.V100.zip)
> MAY BE LIKE THAT

Hi there,

Thanks for that. But sorry, it still doesn't match. Please see image below:
![image](https://user-images.githubusercontent.com/62483125/80245200-62570600-86be-11ea-88df-613e123aa82e.png)

The last digit setting and prediction in the bot is 8 but the LAST DIGIT of the "Entry Spot" is 4. Is it possible to get an "Entry Spot" with 8 as the LAST DIGIT?

**Comment by binarybotbegginer** [comment]
> [LD 8 PREDICT 8 10TICK V100.zip](https://github.com/binary-com/binary-bot/files/4530696/LD.8.PREDICT.8.10TICK.V100.zip)
> MAY BE LIKE THAT

Hi there,

Thanks for that. But sorry, it still doesn't match. Please see image below:
![image](https://user-images.githubusercontent.com/62483125/80245836-86ffad80-86bf-11ea-97d8-2d0060bd7b5e.png)

The last digit setting and prediction in the bot is 8 but the LAST DIGIT of the "Entry Spot" is 4. Is it possible to get an "Entry Spot" with 8 as the LAST DIGIT?

I made a few tweaks as well. But still got the same results.

Thanks
