### ISSUE TITLE
help with one bot it doest work could you help please

### ISSUE THREAD

**Issue by enrique2121** [binary-com/binary-bot#2710]

**Comment by Kosta92** [comment]
We can't help you if you don't provide that bot to us. Simple as that.

**Comment by enrique2121** [comment]
[s.zip](https://github.com/binary-com/binary-bot/files/4509388/s.zip)
sorry is the bot paid bot

**Comment by Kosta92** [comment]
Those are digits bots and they are completely useless because there is no way to predict last digits since they are random numbers.
