### ISSUE TITLE
Need help with 1 min candle interval bot

### ISSUE THREAD

**Issue by saravananperumal93** [binary-com/binary-bot#2712]
Need help with a bot to check if the previous candle is red or green and based on it to decide whether to put or call for Volatility 100 Index. 

I'm using Seconds since Epoch / 60 to be greater than 57, in that case assuming that it enters trade at 58th second and opens trade at next minute '00' seconds. But there is a lag mostly for every 10-15 trades which makes the candle color to take the color of the next minute. How to handle this lag. Please help.

Example - candle color from 10:00:00 to 10:01:00 is red. My expectation is to trade "put' for next candle. But when trade happens, it takes green and trade "call" instead of red, because it was green at 10:01:01.

**Comment by saravananperumal93** [comment]
@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

**Comment by bangvanthuat** [comment]
@saravananperumal93  Perhaps this is what you are looking for.

![Capture](https://user-images.githubusercontent.com/63410420/80226312-66f7cc00-8676-11ea-8c6c-201a848c3e27.PNG)

**Comment by saravananperumal93** [comment]
@bangvanthuat  - Thanks much. But this is not the one I'm looking for. I need it for a 1min candle strategy instead of a tick. Can you help me out plzz.

**Comment by saravananperumal93** [comment]
Also the trading time duration is 1minute. so i really need help with the candle strategy.

**Comment by trident2005** [comment]
![module](https://user-images.githubusercontent.com/56892552/80976638-ad28fa00-8df1-11ea-8843-6ae353fac31f.png)
You need to put all your strategu insidide this module

**Comment by saravananperumal93** [comment]
fine. this is where i'm facing the issue. There is a lag every 10-15 trades when i use this condition (sometimes trade timestamp starts at :58 secs and sometimes at :00 and sometimes even at :02)  and the bot takes the next candle color (start of the next minute) and decides to trade.

**Comment by trident2005** [comment]
there no way to enter exactly in the 0 second, you need to learn how to work with this issue, since a perfect executions between candle and candle is not possible

**Comment by saravananperumal93** [comment]
@trident2005 thank you for the information.
