### ISSUE TITLE
 Create a bot with specific characteristics

### ISSUE THREAD

**Issue by Geanfranco39** [binary-com/binary-bot#2713]
Good.

I hope someone can help me.

I don't know how to create an advanced bot and I would like someone to help me build one with the following characteristics:

1: Be an odd / even bot

2: That starts when the last digit is an odd or even number repeated 5 times

3: In case of losing, have a martingale to make up for the lost amount

4: Stop the bot when it reaches maximum losses

5: Let the bot stop when it reaches the expected profit

**Comment by ZDEGLET** [comment]
I saw on the robot 17 in a row odd.
I worked on this scheme, it is unprofitable :(

**Comment by Geanfranco39** [comment]
I would like to try it.
Do you have the XML file?

**Comment by ZDEGLET** [comment]
https://github.com/binary-com/binary-bot/issues/2699
Выгодные боты конечно есть. Это мой пример чтоб развеять мифы (на реальном счету робот не работает). ВСЕ РАБОТАЕТ. 
РОБОТ ПО ТВОЕЙ СТРАТЕГИИ!!!
[EEEEE OOOOO.zip](https://github.com/binary-com/binary-bot/files/4513160/EEEEE.OOOOO.zip)

**Comment by Geanfranco39** [comment]
Thanks my friend

**Comment by Geanfranco39** [comment]
Do you have a list of profitable bots?

**Comment by ZDEGLET** [comment]
Есть.
Я их тестирую.
Как я писал мhttps://github.com/binary-com/binary-bot/issues/2699 тестировать нужно 24\7 в течении 3-6 месяцев. Потом делать выводы.

**Comment by rubenspina** [comment]
I agree with you the bot does not even work what I do I just put $ 5 or $ 10 if it goes well if I don’t lose more than this these bot are crap everything rubbish that touches up to your last cents $
