### ISSUE TITLE
WINNING BOT NEED HELP

### ISSUE THREAD

**Issue by nobleb2007** [binary-com/binary-bot#2716]
OKAY than
Can you kindly implement this differ strategy if possible.

If the last digit appears 2times in a row predict the number but if lost predict 0

After win Then return back to previous 

I hope it is clear. Thanks

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

Please, kindly help me implement it

**Comment by ZDEGLET** [comment]
Write down the sequence.

**Comment by nobleb2007** [comment]
This is it if 
LDP 45.872    this is first 2
LDP 45.772  this is second 2  predict 2 if this lost
It should automatically predict 0 as next trade and if it wins, it should go back to stage one. 
I hope you get it.

Volatility 10 with tick 2
@bangvanthuat

**Comment by ZDEGLET** [comment]
Clearly I’ll try to do it.

**Comment by Kosta92** [comment]
This is not a winning strategy, and since it's dealing with digits, it's actaully a losing strategy because digits are unpredictable random numbers and trading those can easily wipe your account balance.

**Comment by ZDEGLET** [comment]
@Kosta92 

С виртуальным минусом цифровую стратегию можно сделать прибыльной

**Comment by ZDEGLET** [comment]
@nobleb2007 
We work only with 22?

**Comment by nobleb2007** [comment]
@ZDEGLET  
Yes you can make it like that. Grateful

**Comment by ZDEGLET** [comment]
@nobleb2007 
Write mail I will send :)

**Comment by bangvanthuat** [comment]
> Đây là nếu
> LDP 45.872, đây là 2
> LDP 45.772 đầu tiên, đây là 2 dự đoán 2 nếu thua,
> nó sẽ tự động dự đoán 0 là giao dịch tiếp theo và nếu thắng, nó sẽ quay lại giai đoạn một.
> Tôi hi vọng bạn có được nó.
> 
> Biến động 10 với đánh dấu 2
> @bangaugehuat

@nobleb2007 
I think that is not a good strategy for you to profit. Try another strategy.

**Comment by nobleb2007** [comment]
Have you tested it, how did you know that is not a good strategy. 

I will be grateful if you can help as you promised @ZDEGLET  this is my email nobleb2007@gmail.com

**Comment by bangvanthuat** [comment]
@nobleb2007 
The number that appears is random just like the price of a candle so you can not know what the future price of it is.
The number it can repeat consecutively most is the last number 0-9

**Comment by nobleb2007** [comment]
@ZDEGLET  am patiently await your response. God bless you

**Comment by ZDEGLET** [comment]
@nobleb2007 
see mail

**Comment by nobleb2007** [comment]
@ZDEGLET  am grateful thanks. I received it

**Comment by poroinika** [comment]
> @nobleb2007
> see mail

Why not share here?
