### ISSUE TITLE
Entry Spot - Digit Differ Bot

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2719]
Hi everyone, 

Good Day. Just wondering if there is a way to control the "Entry Spot"? i.e., Can we make the bot to purchase if the last digit is a specific number? 

For eg., Can we create a bot to purchase if the value is 1191.71?

Thanks

**Comment by ZDEGLET** [comment]
@binarybotbegginer 
Yes.
How long will you wait for this value? If it will be 1 time per month?
Or is there still a strategy?

**Comment by bangvanthuat** [comment]
@binarybotbegginer  
Perhaps it is better to choose a price range instead of such a fixed value. The possibility of it achieving true value you set is very long, even never true.

**Comment by binarybotbegginer** [comment]
> @binarybotbegginer
> Yes.
> How long will you wait for this value? If it will be 1 time per month?
> Or is there still a strategy?

Hi, Apologies. I think I did not mention the example clearly. As mentioned before the example, just wondering if we can make the bot to purchase if the "last digit" is a specific number. 

Can we set the required last digit as "1" and make the bot purchase when the value is 1191.71, 1181.81, 1198.31 etc.,?

**Comment by bangvanthuat** [comment]
@binarybotbegginer 
As far as I understand, your request is so. You can set your BOT to operate as CALL / PUT when there are fluctuations in prices, and the final number of the prices may be from 0 to 9 depending on the conditions you provide.

![Capture](https://user-images.githubusercontent.com/63410420/80269720-5c701d80-86dc-11ea-8e1f-5e412f70d723.PNG)

**Comment by binarybotbegginer** [comment]
> @binarybotbegginer
> As far as I understand, your request is so. You can set your BOT to operate as CALL / PUT when there are fluctuations in prices, and the final number of the prices may be from 0 to 9 depending on the conditions you provide.
> 
> ![Capture](https://user-images.githubusercontent.com/63410420/80269720-5c701d80-86dc-11ea-8e1f-5e412f70d723.PNG)

Hi, Thanks for that. I tried this method earlier, but it didn't seem to work. For eg: In one instance, I wanted the last digit to be 5, but the last digit of the Entry Spot was 4.

**Comment by binarybotbegginer** [comment]
> @binarybotbegginer
> As far as I understand, your request is so. You can set your BOT to operate as CALL / PUT when there are fluctuations in prices, and the final number of the prices may be from 0 to 9 depending on the conditions you provide.
> 
> ![Capture](https://user-images.githubusercontent.com/63410420/80269720-5c701d80-86dc-11ea-8e1f-5e412f70d723.PNG)

Hi, Thanks for that. I tried this method earlier, but it didn't seem to work. For eg: In one instance, I wanted the last digit of the Entry Spot to be 5, but it ended up being 4.

**Comment by Tebu1429** [comment]
Good day , can someone please help me to add martingale on a bot?

**Comment by bangvanthuat** [comment]
> > @binarybotbegginer 
> > Theo tôi hiểu, yêu cầu của bạn là như vậy. Bạn có thể đặt BOT hoạt động dưới dạng GỌI / PUT khi có biến động về giá và số cuối cùng của giá có thể từ 0 đến 9 tùy thuộc vào các điều kiện bạn cung cấp.
> > ![Chiếm lấy](https://user-images.githubusercontent.com/63410420/80269720-5c701d80-86dc-11ea-8e1f-5e412f70d723.PNG)
> 
> Xin chào, Cảm ơn vì điều đó. Tôi đã thử phương pháp này sớm hơn nhưng dường như không hiệu quả. Ví dụ: Trong một trường hợp, tôi muốn chữ số cuối cùng của Entry Spot là 5, nhưng cuối cùng lại là 4.

When the price reaches the last digit you wish for the BOT to activate Buy or Sell, when the last digit meets it will trigger the BOT but it will not Buy or Sell at that price because there will be time. to execute the order and it will deviate from your desired price.

**Comment by bangvanthuat** [comment]
> Chúc một ngày tốt lành, ai đó có thể vui lòng giúp tôi thêm martingale trên bot không?

@Tebu1429 
If you want to martingale for BOT you can set up more like that!

![Capture](https://user-images.githubusercontent.com/63410420/80307929-6ede7a00-87f6-11ea-84d3-297aeaa6b176.PNG)

**Comment by binarybotbegginer** [comment]
> > > @binarybotbegginer
> > > Theo tôi hiểu, yêu cầu của bạn là như vậy. Bạn có thể đặt BOT hoạt động dưới dạng GỌI / PUT khi có biến động về giá và số cuối cùng của giá có thể từ 0 đến 9 tùy thuộc vào các điều kiện bạn cung cấp.
> > > ![Chiếm lấy](https://user-images.githubusercontent.com/63410420/80269720-5c701d80-86dc-11ea-8e1f-5e412f70d723.PNG)
> > 
> > 
> > Xin chào, Cảm ơn vì điều đó. Tôi đã thử phương pháp này sớm hơn nhưng dường như không hiệu quả. Ví dụ: Trong một trường hợp, tôi muốn chữ số cuối cùng của Entry Spot là 5, nhưng cuối cùng lại là 4.
> 
> When the price reaches the last digit you wish for the BOT to activate Buy or Sell, when the last digit meets it will trigger the BOT but it will not Buy or Sell at that price because there will be time. to execute the order and it will deviate from your desired price.

Thanks a lot for the info. But if anyone thinks there is a way to control the "Entry Spot" please do let me know.

**Comment by binarybotbegginer** [comment]
> > > @binarybotbegginer
> > > Theo tôi hiểu, yêu cầu của bạn là như vậy. Bạn có thể đặt BOT hoạt động dưới dạng GỌI / PUT khi có biến động về giá và số cuối cùng của giá có thể từ 0 đến 9 tùy thuộc vào các điều kiện bạn cung cấp.
> > > ![Chiếm lấy](https://user-images.githubusercontent.com/63410420/80269720-5c701d80-86dc-11ea-8e1f-5e412f70d723.PNG)
> > 
> > 
> > Xin chào, Cảm ơn vì điều đó. Tôi đã thử phương pháp này sớm hơn nhưng dường như không hiệu quả. Ví dụ: Trong một trường hợp, tôi muốn chữ số cuối cùng của Entry Spot là 5, nhưng cuối cùng lại là 4.
> 
> When the price reaches the last digit you wish for the BOT to activate Buy or Sell, when the last digit meets it will trigger the BOT but it will not Buy or Sell at that price because there will be time. to execute the order and it will deviate from your desired price.

Thanks a lot for the info. But if anyone thinks there is a way to control the "Entry Spot", can you please let me know?

**Comment by ZDEGLET** [comment]
@Tebu1429 
throw the robot to the mail (with the mark martingale) hook martingale
zdeglet@gmail.com
