### ISSUE TITLE
PRICECLOSE is the current price ?

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2720]
![image](https://user-images.githubusercontent.com/58647652/80201306-21270d80-864e-11ea-8cdd-6cc1d9c5b30d.png)

in www.binarybot.online I build my strategy. So I want to know PRICECLOSE is the current price ?
If isn't not how I can set current price above sma 5

**Comment by Kosta92** [comment]
Just to be clear, that software has nothing to do with the official Binary Bot so this community may not help you or know how to help you.

**Comment by freedayz04** [comment]
> Just to be clear, that software has nothing to do with the official Binary Bot so this community may not help you or know how to help you.
thx Okay.
So where is www.binarybot.online  community.

**Comment by Kosta92** [comment]
That software was developed by a user from this community called [Binary Ex Machina](https://github.com/binary-ex-machina).

You can contact him at: binaryexmachina@gmail.com
