### ISSUE TITLE
How to set Bot stop when loss 2 times continue?

### ISSUE THREAD

**Issue by birdykung** [binary-com/binary-bot#2721]
How to set Bot stop when loss 2 times continue?

**Comment by bangvanthuat** [comment]
@birdykung 
What you need here. Let's create it that way.

![Capture](https://user-images.githubusercontent.com/63410420/80237718-6582cf80-8687-11ea-828a-264b4a23ceb2.PNG)

**Comment by birdykung** [comment]
> @birdykung
> What you need here. Let's create it that way.
> 
> ![Capture](https://user-images.githubusercontent.com/63410420/80237718-6582cf80-8687-11ea-828a-264b4a23ceb2.PNG)

Oh. Thank you so much
