### ISSUE TITLE
HOW TO CREATE THIS REALLY SIMPLE BOT? 

### ISSUE THREAD

**Issue by Fabcast21** [binary-com/binary-bot#2722]
I need to create a really simple binary options bot it works like this... 

For this exactly formation I need to make a sell with 5 minutes of deadline
![1](https://user-images.githubusercontent.com/64336083/80293346-3cfce300-8724-11ea-9a4e-5489700b92e6.png)

And for this other exact formation I need to make a buy with 5 minutes of deadline
![2](https://user-images.githubusercontent.com/64336083/80293467-39b62700-8725-11ea-8422-a688df2f0c44.png)

I'll test it in volatility index and also forex but only in the NY session.

I hope someone can help me! I seriously need this, thank you strange :D

**Comment by bangvanthuat** [comment]
@Fabcast21 
This is what you are looking for, hopefully it will help you.
Thanks!
![Capture1](https://user-images.githubusercontent.com/63410420/80307689-d4ca0200-87f4-11ea-9d38-4f7ec69a62b7.PNG)

![Capture](https://user-images.githubusercontent.com/63410420/80307691-da274c80-87f4-11ea-8d24-c2ae445e221f.PNG)

=>=>  [BOT.txt](https://github.com/binary-com/binary-bot/files/4535305/BOT.txt)

**Comment by Fabcast21** [comment]
I will test it !  Thanks @bangvanthuat you are amazing :D

**Comment by Fabcast21** [comment]
> @Fabcast21
> This is what you are looking for, hopefully it will help you.
> Thanks!
> ![Capture1](https://user-images.githubusercontent.com/63410420/80307689-d4ca0200-87f4-11ea-9d38-4f7ec69a62b7.PNG)
> 
> ![Capture](https://user-images.githubusercontent.com/63410420/80307691-da274c80-87f4-11ea-8d24-c2ae445e221f.PNG)
> 
> =>=> [BOT.txt](https://github.com/binary-com/binary-bot/files/4535305/BOT.txt)

I test it but I realize that doesn't makes two operations at the same time for example, if it just opened a buy option and the market shows a sell option it doesn't open the trade till the deadline of the buy option, how can I make it to do that, thanks :D  and is working amazing

**Comment by bangvanthuat** [comment]
@Fabcast21 
You just need to adjust the candle conditions. I show you a sample so you know how it works and what you have to do.
