### ISSUE TITLE
TICK PER TICK STRATEGY

### ISSUE THREAD

**Issue by Fabcast21** [binary-com/binary-bot#2729]
Hi guys! Is it possible to make bot in binary to do entries with the bull index ?? 
the strategy is like this:
1. if the market does 3 falling ticks and the 4th tick is blue we buy with a 5 ticks deadline.

Is really simple! but seriously I don't know anything about bots and how to build them, thanks stranger!!

**Comment by bangvanthuat** [comment]
@Fabcast21 
This is what you are looking for.


![Capture](https://user-images.githubusercontent.com/63410420/80607574-e105c780-8a5f-11ea-9ec7-e26f569f4705.PNG)

**Comment by Fabcast21** [comment]
Thanks! you're great, but when I'm trying to run the bot it appears this error "Cannot read property 'slice' of undefined" why is that? 



> @Fabcast21
> This is what you are looking for.
> 
> ![Capture](https://user-images.githubusercontent.com/63410420/80607574-e105c780-8a5f-11ea-9ec7-e26f569f4705.PNG)

**Comment by bangvanthuat** [comment]
> Cảm ơn! bạn thật tuyệt, nhưng khi tôi đang cố gắng chạy bot thì xuất hiện lỗi này "Không thể đọc thuộc tính 'lát' không xác định" tại sao lại như vậy?
> 
> > @ Fabcast21 
> > Đây là những gì bạn đang tìm kiếm.
> > ![Chiếm lấy](https://user-images.githubusercontent.com/63410420/80607574-e105c780-8a5f-11ea-9ec7-e26f569f4705.PNG)

You do not need to worry about that, it will not affect your performance.

**Comment by Fabcast21** [comment]
> > Cảm ơn! bạn thật tuyệt, nhưng khi tôi đang cố gắng chạy bot thì xuất hiện lỗi này "Không thể đọc thuộc tính 'lát' không xác định" tại sao lại như vậy?
> > > @ Fabcast21
> > > Đây là những gì bạn đang tìm kiếm.
> > > ![Chiếm lấy](https://user-images.githubusercontent.com/63410420/80607574-e105c780-8a5f-11ea-9ec7-e26f569f4705.PNG)
> 
> You do not need to worry about that, it will not affect your performance.

But you know there is a problem because when a buy trade is made doesn't follow the rules of the strategy, it is suppossed to do a buy if the market does, RED, RED, RED, BLUE, that's  3 down ticks and later one up tick, doesn't buy,  it buys when it makes some random movements, how can I fix that?  thanks again :D !!

**Comment by BEKKALI16** [comment]
Helow friend
i have pefect strategy in bull market digit match.please contact me on my email : bekkali2013@gmail.com
