### ISSUE TITLE
Is this a bug ? The balance bloc

### ISSUE THREAD

**Issue by GreenB0t** [binary-com/binary-bot#2736]
When I set the variable **original b** to balance & print there values, they're the first time the same but the secon time diffrent
![Screenshot_20200430-150814](https://user-images.githubusercontent.com/58006778/80727369-2922f980-8af5-11ea-9822-bdf9bbf76287.jpg)
![Screenshot_20200430-150823](https://user-images.githubusercontent.com/58006778/80727462-45bf3180-8af5-11ea-8909-0cc22b966ad9.jpg)
![Screenshot_20200430-150841](https://user-images.githubusercontent.com/58006778/80727488-4e176c80-8af5-11ea-89a2-5f4775702142.jpg)

& when I put the notification bloc here even the first time the values are wrong

![Screenshot_20200430-150736](https://user-images.githubusercontent.com/58006778/80727629-78692a00-8af5-11ea-95b2-70b83861a051.jpg)
![Screenshot_20200430-150745](https://user-images.githubusercontent.com/58006778/80727658-81f29200-8af5-11ea-94b8-d53647682a6b.jpg)

**Comment by aaron-binary** [comment]
Hey @GreenB0t,

This is a bug and we will fix it up from our side. The values returned should've been the same in both the balance block and the variable you've set up previously. 

Let me look into this and issue a fix.

Regards,
Aaron

**Comment by GreenB0t** [comment]
Ok, thank you for taking the time to check out this issue hope it'll be fixed soon
