### ISSUE TITLE
problema na compra em forex(resolvido)

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#2737]
olá a todos! tenho um robô que opera em forex, só que todas as vezes que ele vai entrar em uma operação diz que o valor do contrato foi modificado e não consegue dar o lance. tem como resolver isso???

**Comment by contatodeanet** [comment]
existe alguma regra para o bot ficar atualizando o valor do contrato??

**Comment by Kosta92** [comment]
Enable this option and try again:

![Restart Buy-Sell on error](https://user-images.githubusercontent.com/11698414/80765023-4c27ca80-8b42-11ea-80f3-f70747bf1f24.png)

**Comment by contatodeanet** [comment]
já descobri!! precisar usar essa opção! serve tanto para forex como também para o binary!!
![VVV](https://user-images.githubusercontent.com/43180630/80812782-03522f00-8b9f-11ea-900a-7bc95a9242ed.png)
