### ISSUE TITLE
How to setup bot to check last 3 digit?

### ISSUE THREAD

**Issue by birdykung** [binary-com/binary-bot#2739]
![Screenshot_28](https://user-images.githubusercontent.com/38474267/80784835-8461f400-8ba8-11ea-98ea-6093d9eef2de.png)

Hello Guy,
I would like to purchase EVEN when the last 3 digit have 0.
Please advise how to setup bot.

Thanks.

**Comment by nextnaro** [comment]
Here, may help.

[binary-bot-block.txt](https://github.com/binary-com/binary-bot/files/4565621/binary-bot-block.txt)

**Comment by birdykung** [comment]
> Here, may help.
> 
> [binary-bot-block (3).xml.txt](https://github.com/binary-com/binary-bot/files/4565681/binary-bot-block.3.xml.txt)

Thank you so much

**Comment by nextnaro** [comment]
คนๆทย?

**Comment by NEWBIE3232** [comment]
please repost strategy 
the block is not loading its saying file format not supported
please make it a zip file
