### ISSUE TITLE
synthetic free telegram signals channel 

### ISSUE THREAD

**Issue by Muroyal1** [binary-com/binary-bot#2741]
Binary.com synthetic scripts signals.

V10,V25,V50 & v100

24/7 signals 2 minutes duration trades..

Contact: binarytraderschanikya@gmail.com
Admin: @royal089
https://t.me/binary_synthatic_signals
![Screenshot_2020-05-02-19-12-01-73](https://user-images.githubusercontent.com/63347273/80865737-f7eb2a80-8ca8-11ea-8afb-a624505d60ce.jpg)

**Comment by Muroyal1** [comment]
![Uploading IMG_20200503_014605.jpg…]()

**Comment by ainvoot** [comment]
I tested for a few hours and losses more than you can win!

I suggest finding a better strategy!
