### ISSUE TITLE
Prediction Digit Counting

### ISSUE THREAD

**Issue by iakhan88** [binary-com/binary-bot#2744]
Hi ,
Would like to know the method to count last predicted digit, 
Let say predicted digit is 5, than when bot found the last digit 5 it should count it 2nd time before execution of trade.

**Comment by iakhan88** [comment]
![Dead Shot 1](https://user-images.githubusercontent.com/63729337/80912693-3e4b9280-8d58-11ea-95dc-dd26bdbe82ef.png)

Here is the block, I need to count predicted digit 2 times, than trade start

**Comment by lxxneonxxl** [comment]
Do you mean to make it fall out 3 times in a row? or does it not matter?

**Comment by iakhan88** [comment]
> Do you mean to make it fall out 3 times in a row? or does it not matter?

no matter how many times, i will re modify it later when get the block, can u help me out

**Comment by lxxneonxxl** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/57267933/80923026-9ea6f800-8d89-11ea-96e4-49b7c89ace75.png)

**Comment by iakhan88** [comment]
sorry but language making difficult to understand

**Comment by lxxneonxxl** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/57267933/80923103-170db900-8d8a-11ea-815a-0ffb1978bb3e.png)
