### ISSUE TITLE
Renko

### ISSUE THREAD

**Issue by lxxneonxxl** [binary-com/binary-bot#2746]
Hi, everybody. Any thoughts on how to achieve Renko chart values.. ????

----------------------------------------------------------------------------------
Help.. I made a percentage notification of the tick difference... I want these % values to be added together after each tick.. how can I do this

![Screenshot_5](https://user-images.githubusercontent.com/57267933/80920590-77482f00-8d79-11ea-9217-403998d5683c.png)

![Screenshot_6](https://user-images.githubusercontent.com/57267933/80920703-37357c00-8d7a-11ea-8504-8b8f073edff2.png)
![Screenshot_8](https://user-images.githubusercontent.com/57267933/80921211-a8c2f980-8d7d-11ea-87e7-67a4e557f4f6.png)

--------------------------------------------------------------------------------------------------------
I need the previous % value to be added to the present value up to a certain value with each new tick. 
For example. when the total is 0.1% or 1% then either -0.1 ... --1% this will count as a bar as a block on RENKO charts
![Screenshot_11](https://user-images.githubusercontent.com/57267933/80955917-d30dc900-8e08-11ea-82f2-ae2895043438.png)

**Comment by lxxneonxxl** [comment]
Help.. I made a percentage notification of the tick difference... I want these % values to be added together after each tick.. how can I do this

![Screenshot_5](https://user-images.githubusercontent.com/57267933/80920590-77482f00-8d79-11ea-9217-403998d5683c.png)

**Comment by lxxneonxxl** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/57267933/80920597-829b5a80-8d79-11ea-800d-f8a0fd24fb6c.png)

**Comment by lxxneonxxl** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/57267933/80920703-37357c00-8d7a-11ea-8504-8b8f073edff2.png)

**Comment by ZDEGLET** [comment]
@lxxneonxxl 

quit the job we will think.

**Comment by trident2005** [comment]
Hi, can you share de algorithm??

**Comment by lxxneonxxl** [comment]
The robot itself doesn't seem to exist yet.. there is only a block %
[Percentage.zip](https://github.com/binary-com/binary-bot/files/4571465/Percentage.zip)
