### ISSUE TITLE
what does this "redworm greenworm blueworm" mean ? 

### ISSUE THREAD

**Issue by freedayz04** [binary-com/binary-bot#2749]
what does this "redworm greenworm blueworm" mean ?  
and someone have bot about worm please share it.

Thank you.

**Comment by trident2005** [comment]
Blueworm means "new highest price" and Green Worm means "acctual price stays between the highest and lowest price"

**Comment by freedayz04** [comment]
> Blueworm means "new highest price" and Green Worm means "acctual price stays between the highest and lowest price"

Thankyou . and Red means new lowest price right ?

**Comment by trident2005** [comment]
> > Blueworm means "new highest price" and Green Worm means "acctual price stays between the highest and lowest price"
> 
> Thankyou . and Red means new lowest price right ?

Exactly

**Comment by trident2005** [comment]
there no way to enter exactly in the 0 second, you need to learn how to work with this issue, since a perfect executions between candle and candle is not possible

**Comment by Kosta92** [comment]
You can see it working here, for example: [https://www.binary.com/en/trading.html](https://www.binary.com/en/trading.html)

![download (3)](https://user-images.githubusercontent.com/11698414/80994043-66acbd00-8e3c-11ea-8deb-7fe7c17d6402.png)

(yellow dot is just a position of my cursor when I saved the image)
