### ISSUE TITLE
Changes made to Binary Bot today 3rd July 2017.

### ISSUE THREAD

**Issue by JDPNZ** [binary-com/binary-bot#275]
I notice with more than a little frustration that today, Binary decided to limit the list object to a maximum of 10 entries.
As such, you have a maximum of 10 ticks, 10 candles and 10 entries in a locally created list.
I don't know - does this mean that all of us using moving averages, MACD, RSI and/or other indicators should perhaps go find another broker or what exactly is it that Binary.com is trying to achieve here?

**Comment by aminmarashi** [comment]
Hi @JDPNZ, there are no such limits in Binary Bot.
However, we did a major release yesterday which might have some bugs we are not aware of. Could you please provide more information regarding the issue?
[limits.xml.zip](https://github.com/binary-com/binary-bot/files/1120860/limits.xml.zip)
<img width="822" alt="screen shot 2017-07-04 at 10 26 07 am" src="https://user-images.githubusercontent.com/6560964/27812728-9d96d0c2-60a3-11e7-8b49-3e6d18e197e5.png">
