### ISSUE TITLE
What's the difference between synthetic market indices ? 

### ISSUE THREAD

**Issue by GreenB0t** [binary-com/binary-bot#2753]
Can you please simply explain the difference between synthetic market: bearish, bullish, 10,25..100 ? & how would they effect my trading
Thank you in advance ✔️

**Comment by Kosta92** [comment]
This question is the same as mine from 50 days ago, although I didn't get a precise answer: #2568

**Comment by trident2005** [comment]
Bear and BULL just work from monday to friday and the rest of it 24/7, in operative terms they not have any difference

**Comment by aaron-binary** [comment]
You may find more information on Synthetic Indices below:

- https://www.binary.com/en/get-started/binary-options.html#range-of-markets

**Comment by bangvanthuat** [comment]
@GreenB0t 
It is simply a form of index based on real market indices and the indexes are put into algorithms to make the player never win.
Never play something bogus and hope to win.

**Comment by josward1** [comment]
@bangvanthuat could you explain more about this? surely if you work out scenarios that repeat themselves you can win? the chart still follows basic chart patterns therefore can't be completely random? This is a concern i have always had with spending time working on this, i have worked out a number of good strategies that work and have been tested for 500-1000 trades however my concern is that when these run on live Binary.com work out what your doing and adjust the chart to catch you out.

**Comment by bangvanthuat** [comment]
I just make sure these indicators are not real. It just simulates something similar. And the way it works, I don't know, it's a secret. @aaron-binary  will probably give you a better answer.

**Comment by aaron-binary** [comment]
We don't manipulate the charts and this could be verified:

- Logged in and logged out clients see the same chart.
- Historical data is available for download from [Webtrader](https://webtrader.binary.com/) (no need to be logged in to access this).
- Contracts purchased on demo and real accounts settle in the same way.
- Our Synthetic Indices are audited by licensed third party entities.

**Comment by bangvanthuat** [comment]
@aaron-binary  So why does binary.com not offer binary options "Digits" on currency pairs ?, is it possible that the history and results of the players can be compared and tested so binary.com does not apply to pairs? currency?

**Comment by josward1** [comment]
i understand that the price will match for everybody across the demo and live account. But what i'm asking is if somebody has a successful strategy.. are binary.com realistically going to allow this strategy to continue working considering a working strategy can potentially earn millions in a year. Or after a while change the rhythm of the chart so that strategy does not continue working. This would still show matching results between a demo and live account across all accounts as you have explained, pass an audit and still not allow a successful strategy to continue.

**Comment by bangvanthuat** [comment]
@josward1  I don't know that, only the owners of this game will decide that problem. I have not seen a chart of binary.com on traders' profit so I can trust that someone has made a profit here.

**Comment by josward1** [comment]
@aaron-binary have you got a response to my previous comment? i've had a hand full of successful strategies tested for 1000 trades or more on demo and back tested historically. After 2 weeks of successful trading on live they all of a sudden completely stop working. Realistically binary.com aren't going to allow a successful strategy to continue are they as you are in control of the charts?

**Comment by bangvanthuat** [comment]
> @ aaron-binary bạn có nhận được phản hồi cho nhận xét trước đây của tôi không? Tôi đã có đầy đủ các chiến lược thành công được thử nghiệm cho 1000 giao dịch trở lên trên bản demo và được kiểm tra lại trong lịch sử. Sau 2 tuần giao dịch thành công trực tiếp, tất cả đột nhiên ngừng hoạt động. Thực tế binary.com sẽ không cho phép một chiến lược thành công để tiếp tục như họ đang kiểm soát các biểu đồ?

@josward1  You know someone is taking money from your wallet, can you be quiet even for people to take it all away???

**Comment by josward1** [comment]
Then they should not be offering it as a Tradable asset if they don't want to pay out successful traders. Happy to take peoples money but wont pay any out? I understand this is classed as gaming so wont come under FCA regulations however it does fall into the category of fixed odds betting which are regulated by the gambling commission. Binary.com are clearly breaking one law or another with this and i'm going to go all out on bringing this to light and put a stop to it a long with seeking legal advise regarding time wasted and money lost. This should not be allowed.
