### ISSUE TITLE
What is the best time to run a bot during the day ? 

### ISSUE THREAD

**Issue by GreenB0t** [binary-com/binary-bot#2754]
What is the best time to run a bot effectively during the day, & are synthetic indices effected by wich time of the day it is ?

**Comment by trident2005** [comment]
If you are using synthetic indexes, you have no better time to work with it

**Comment by bangvanthuat** [comment]
@GreenB0t  You can run 24h/7days, it does not depend on the time, it depends on the most important thing is the BOT strategy and the market you trade.
I have BOTs running with virtual accounts with synthetic indicators, the profit is very stable and stable, but when running with real accounts, I always lose all my accounts.

**Comment by renatolsxc** [comment]
> @GreenB0t You can run 24h/7days, it does not depend on the time, it depends on the most important thing is the BOT strategy and the market you trade. I have BOTs running with virtual accounts with synthetic indicators, the profit is very stable and stable, but when running with real accounts, I always lose all my accounts.

Do you have a bot profitable?
