### ISSUE TITLE
Tengo un robot y algunas perosna les gustaria probarlo

### ISSUE THREAD

**Issue by abreu2049** [binary-com/binary-bot#2756]
tengo un robot y las personas me están pidiendo un periodo de prueba, pero actualmente no puedo hacer eso por que perdería el control , necesito poder codificarlo de forma que el archivo se envie como periodo de prueba y a determinado tiempo se desactive y no funcione mas, si el cliente desea suscribirse este debería poder activarse de nuevo previa autorización

**Comment by trident2005** [comment]
Ya en muchas oportunidades se ha dicho que NO ES POSIBLE codificar scrypts XML, debes programar tu estrategia en algún leguaje de programación como Visual Studio, JAVA, PHYTON etc.

**Comment by abreu2049** [comment]
Ustedes me podrían ayudar ?

**Comment by trident2005** [comment]
Eso es para usuarios avanzados en programación, es mucho mas complejo que hacer un scrypt en XML, , lo mas probable, es que debas pagar a un tercero para sacar tu proyecto adelante.

**Comment by adhamjon91** [comment]
Hi. I have a friend who can code it in any programming language. That is, it implements the bot on a third-party application and it will work using the api.
You can control it if the person doesn't pay you can disable it.
If your bot is profitable, we code it for free for you. 
@Aka388 telegram for communication

**Comment by DrMystery** [comment]
Telegram : @JackpotTrading can help in this case
