### ISSUE TITLE
Rate limit reached for: buy, retrying in Ns

### ISSUE THREAD

**Issue by ccalafiore** [binary-com/binary-bot#2759]
I run my own bot on https://www.binary.bot/bot.html with my virtual account. it works fine for some time, but at some point, I got this error "Rate limit reached for: buy, retrying in Ns". Please, any help?

[binary-bot_not_lists.zip](https://github.com/binary-com/binary-bot/files/4585152/binary-bot_not_lists.zip)

**Comment by aaron-binary** [comment]
Hey @ccalafiore,

This usually happens when you're running multiple bots at the same time. Is this the case? We enforce some limits on API requests made per minute or day, you're quick to hit those limits when trading on 1-tick Synthetic Indices contracts.

```
"api_call_limits": {
      "max_proposal_subscription": {
        "applies_to": "subscribing to proposal concurrently",
        "max": 5
      },
      "max_requestes_general": {
        "applies_to": "rest of calls",
        "hourly": 14400,
        "minutely": 180
      },
      "max_requests_outcome": {
        "applies_to": "portfolio, statement and proposal",
        "hourly": 1500,
        "minutely": 25
      },
      "max_requests_pricing": {
        "applies_to": "proposal and proposal_open_contract",
        "hourly": 3600,
        "minutely": 80
      }
    },
```

Regards,
Aaron

**Comment by ccalafiore** [comment]
I only use one bot. 

So, which of those limits does it hit? The hourly limit 14400? are those limits valid also for real accounts? So, I put "trade again" inside a block that waits for 10 seconds (see the image).

![wait](https://user-images.githubusercontent.com/44749641/81198456-67b72900-8fb9-11ea-834f-819cca1098df.PNG)

**Comment by ccalafiore** [comment]
the bot never hit any of those limits without the 10 seconds wait block. It makes 1 trade per 4 sec. this means 15 trades per min (60/4) and 900 trades per hour (15*60).

**Comment by thommmaz** [comment]
I recently facing same issue. Only one bot is running, 5 ticks, max 50 trades per day but all the time I see that rate limit error.
