### ISSUE TITLE
Binary Bot Education and Training. 

### ISSUE THREAD

**Issue by Davtonics77** [binary-com/binary-bot#2761]
Good afternoon,.  Please I don't know how to use the bot in building my own strategy. 
Please how  can I get the proper training and education on the Bot, so that I can build my own strategy. As soon as possible. 
Thank you.

**Comment by ZDEGLET** [comment]
It depends on what strategy. They are complex and simple.
Describe the strategy in a letter if you do not want to make it public (with meta a new strategy).

zdeglet@gmail.com

**Comment by Davtonics77** [comment]
thank you sir

**Comment by ZDEGLET** [comment]
@Davtonics77 
Why don't you write a letter? I can tell you which direction to go.

**Comment by Davtonics77** [comment]
Good day sir,
But how do I write the letter,?  And who do I address the letter to?
Thanks sir
David o

**Comment by ZDEGLET** [comment]
@Davtonics77 
To my mail.
zdeglet@gmail.com

**Comment by Davtonics77** [comment]
I Have sent the letter to your mail.
Thanks & Regards
