### ISSUE TITLE
Adding split martinagle to a bot.

### ISSUE THREAD

**Issue by Ozlos123** [binary-com/binary-bot#2762]
If a deal is lost, for example:
-0.35
The original martingale would be 3.5
But let's say I want to split it in to 2  separate martingale 1.75 and 1.75 after the loss or even into 3  so it would be 1.16 than 1.16 and than again 1.16 

Need help

**Comment by Martinez222** [comment]
try like this :  
![split 1](https://user-images.githubusercontent.com/39260368/81499659-c9d39f00-92d5-11ea-98d9-4c06407fb102.jpg)
![split 2](https://user-images.githubusercontent.com/39260368/81499663-cb9d6280-92d5-11ea-8dd1-b03503de35f5.jpg)

**Comment by Ozlos123** [comment]
Thank you, I'll try
