### ISSUE TITLE
Digit differ bot

### ISSUE THREAD

**Issue by Ozlos123** [binary-com/binary-bot#2765]
Can someone please help me make a bot, I know what I want but don't have the skills to make it!

The bot I want to make is a digit differ bot.
The prediction can be any number you'd like.
I'l go with 2 as an example.
So If the last digit appears "2" a contract is made. if the contract is won the bot waits for anorther "2" to appear and makes the next deal.

But here is what I can't do- if a contract is made and lost I want to make a split martingale.
So if I lose - 1.0 € the usual martingale would be 11€, but I want to split those 11€ in 2 or 3 separate contracts so it would be like this:
-1. 0 ;  3.6 ; 3.6 ; 3.6   or  - 1 ; 5.5 ; 5.5 and so on and on if it loses the next one as well.

I just want to reduce the risk and make the bot for smaller balances.
Could someone help?

**Comment by saidforex26** [comment]
[Ozlos123 differs2 martinggale step.zip](https://github.com/binary-com/binary-bot/files/4609288/Ozlos123.differs2.martinggale.step.zip)
hopefully can help 
![Ozlos123 differs2 martinggale step](https://user-images.githubusercontent.com/54820719/81558069-9d944d00-93bf-11ea-9e13-5f756b3ab374.gif)

**Comment by Ozlos123** [comment]
Thanks a lot.
And a very helpful video, i'l try to improve my bot building skills and let you know how the bot works.

**Comment by saidforex26** [comment]
You're welcome. hopefully can help you develop your bot

**Comment by Ozlos123** [comment]
Oke, can we switch up the bot strategy?
Making the bot make a deal when any last 3 digits have been equal and putting the same split for martingale if a loss acurres

**Comment by saidforex26** [comment]
this strategy When time can produce los up to 3-4 times

**Comment by Ozlos123** [comment]
I was checking the strategy and it has 1 out of 10 chance to lose ratio.
And if we split the martingale the bets are far smaller.

Its not only for one digit to appear 3 times. It for any digit that appears 3 times in a row

**Comment by saidforex26** [comment]
please develop it. hopefully can help
[Ozlos123  martinggale step add 3digit same.zip](https://github.com/binary-com/binary-bot/files/4614739/Ozlos123.martinggale.step.add.3digit.same.zip)
![Ozlos123  martinggale step add 3digit same](https://user-images.githubusercontent.com/54820719/81669582-025fae00-9479-11ea-8122-d94e69f2dbf0.gif)
