### ISSUE TITLE
Delay in bot from 0 to 2 seconds between DEFINE TRADE OPTIONS and PURCHASE CONTRACT blocks

### ISSUE THREAD

**Issue by pardeli** [binary-com/binary-bot#2766]
Hi,
Can someone help me with this topic:

I have a bot where I can search for a patern and then define the Prediction according with the patern found. That is working fine.

The problem is the transition betzeen there 2 blocks: 
DEFINE TRADE OPTIONS and PURCHASE CONTRACT

As you can see in my bot, I inserted a notification for the "seconds since Epoch" to measure the delay between those 2 blocks
The result is very different from trade to trade.
Somerimes the two notifications are genetated in the same second, other times with 1 second delay and other times with 2 seconds delay.

Does anyone knows the reason of this behavior?
Is there any way to prevent this?

Thank in advance.
PP

![delay](https://user-images.githubusercontent.com/65088995/81482895-85df8c00-923a-11ea-8836-0aaa0a58d10e.png)

**Comment by aaron-binary** [comment]
Hey @pardeli,

This is usually related to network speed. The bot moves to the 2nd block when the client has sent a proposal to our server and that request has been answered by the server. If it takes the 0-2 seconds to send the request, it will take that much time to move to the 2nd block.

You can inspect the requests that are being made to our server by inspecting the websocket messages. This Stackoverflow page may help: https://stackoverflow.com/q/43081107

Regards,
Aaron

**Comment by pardeli** [comment]
Thank you Aaron for the feedback.

Is there any way to improve this delay?

Best regards, 
Pedro

**Comment by Kosta92** [comment]
Yes. Move your computer to Binary Bot's server location.

**Comment by trident2005** [comment]
If your stragedy is created 100% on the 2 block, your contract does not experience delay,  I think the problem is another, 

I only experience these delays when contracts are defined by barriers such as OVER / UNDER, and the definition must be placed in block 1, but if we decide to work with a single barrier directly in block 2, the delay no longer exists if your internet is optimal.
