### ISSUE TITLE
martingale dont work

### ISSUE THREAD

**Issue by islamrefaey2019** [binary-com/binary-bot#2767]
I dont know why martingale not working 
please can any one help me
[RF_BINARY.txt](https://github.com/binary-com/binary-bot/files/4604887/RF_BINARY.txt)

**Comment by Martinez222** [comment]
here u go :  

[RF_Binary_Jeg.zip](https://github.com/binary-com/binary-bot/files/4605673/RF_Binary_Jeg.zip)

**Comment by ZDEGLET** [comment]
THIS GRAL !!!
![2020-05-10_17-48-25](https://user-images.githubusercontent.com/36106343/81502434-a402c600-92e6-11ea-9bef-d7f1f4181ff5.png)

**Comment by ZDEGLET** [comment]
![2020-05-10_18-53-46](https://user-images.githubusercontent.com/36106343/81504013-acabca00-92ef-11ea-97ad-573d3b6d2360.png)

**Comment by islamrefaey2019** [comment]
I use martingale after 3 losses 
![11](https://user-images.githubusercontent.com/51350288/81504840-d662f200-92eb-11ea-8025-994753fdd4a2.png)

**Comment by islamrefaey2019** [comment]
> here u go :
> 
> [RF_Binary_Jeg.zip](https://github.com/binary-com/binary-bot/files/4605673/RF_Binary_Jeg.zip)

thanks my friend
