### ISSUE TITLE
Summary at the end of Bot

### ISSUE THREAD

**Issue by iakhan88** [binary-com/binary-bot#2770]
Hi, is there any way to make a summary after ending the bot, which shows the results like no of martingles, max loss amount, max win amount, total time from start of bot to end of bot??? etc etc???

**Comment by aaron-binary** [comment]
Hey @iakhan88,

There is currently no way of analysing these numbers as these are all user generated. 

We have however talked about a variable watcher (very similar to a browser's developer tools), which allows the user to see the values of their variables in real time. This may provide you with the numbers you're looking for. 

I'd love to hear more about your idea.

Regards,
Aaron

**Comment by saidforex26** [comment]
@iakhan88  maybe you can find what you are looking for in this money management. please develop ...
[zip@lasaidhari  Money Management V1.01 licenci version EDIT FALSE.zip](https://github.com/binary-com/binary-bot/files/4608899/zip%40lasaidhari.Money.Management.V1.01.licenci.version.EDIT.FALSE.zip)

**Comment by iakhan88** [comment]
> @iakhan88 maybe you can find what you are looking for in this money management. please develop ...
> [zip@lasaidhari Money Management V1.01 licenci version EDIT FALSE.zip](https://github.com/binary-com/binary-bot/files/4608899/zip%40lasaidhari.Money.Management.V1.01.licenci.version.EDIT.FALSE.zip)

Nice work, but its my bad luck that due to unfamiliar from Indo language it is hard to understand the blocks, I try to use google translate but its time taking, ur work can ease my strategy if its in english, Thanks and once again really nice work

**Comment by saidforex26** [comment]
to make it to the English version it could be. but at the moment I don't have the time to edit it
