### ISSUE TITLE
Help with prediction value

### ISSUE THREAD

**Issue by helciobtc** [binary-com/binary-bot#2771]
Please, I'm having trouble getting what I want to do.
Notice that I am printing in red the value of the PREDICT variable that is being used to define the trade option PREDICTION but note that the value that is being used for the operation is not the same as that being printed, random value is being used and not I can adjust
Can someone help me please?
The green prints are from the last digits, I'm trying to work with the repetition break.
however, I cannot place my trade to be executed in DIFFERS with prediction in the digit that repeated.

Thanks in advance
![Captura de Tela 2020-05-11 às 05 41 19](https://user-images.githubusercontent.com/55867013/81541958-4b651480-934a-11ea-945e-660bb16ad469.png)

**Comment by helciobtc** [comment]
the repetition was from digit 0 that appears in the print of the PREDICT variable but the same value is not used for the PREDICTION of the negotiation, note that the value 4 was used at random

**Comment by saidforex26** [comment]
[2same digits.zip](https://github.com/binary-com/binary-bot/files/4609079/2same.digits.zip)
hopefully can help
![2digit same](https://user-images.githubusercontent.com/54820719/81554186-ee547780-93b8-11ea-9d83-bb72de1319e2.gif)

**Comment by helciobtc** [comment]
Hello friend, allow you to accept some of your time and attention to help me !!

perceived that or encoded that sent when the last digit entered is repeated 2 times, the operation process starts, however, a digit is skipped before being entered

are there possibilities to enter the digit directly as repetitions without this delay?
Thank you

**Comment by saidforex26** [comment]
The block that I have analyzes the same digit ... you can develop it
