### ISSUE TITLE
Binary Bot Run Under 35$ in real Account

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2772]
https://youtu.be/XkpdLiOEGjo

**Comment by Kosta92** [comment]
Another useless bot that is asking for trouble which seems like it can easily empty your $35 account. Deffinitely not worth a **THOUSAND** dollars.

**Comment by trident2005** [comment]
100$ dollar bot??, How you can recommend 30 USD if you have a martingale step up to 19.53 USD ??, it is very irresponsible of you to use GitHub to sell your scrypts, if you trust in your scrypts so much use them with your own money, for me this is an ordinary RISE/FALL scrypt, 

 You just try to hunt fools

**Comment by ZDEGLET** [comment]
@virtusasys 
Look !!! Your bot is just resting !!!
https://github.com/binary-com/binary-bot/issues/2699
