### ISSUE TITLE
Rate limit reached for: buy, retrying in just few order how about rate limit for frx?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2774]
![image](https://user-images.githubusercontent.com/31925501/81684629-b6693500-9489-11ea-8b50-dafbfa03631e.png)

Rate limit reached for: buy, retrying in just few order how about rate limit for frx?
Please look @ time stamp and order as caputured.

**Comment by aaron-binary** [comment]
Hey @nextnaro,

We've seen multiple reports about this and I've escalated this to the right people.

- Are you using multiple bots or just a single instance?

Regards,
Aaron

**Comment by nextnaro** [comment]
> Hey @nextnaro,
> 
> We've seen multiple reports about this and I've escalated this to the right people.
> 
> * Are you using multiple bots or just a single instance?
> 
> Regards,
> Aaron

only 1.

**Comment by ZDEGLET** [comment]
Sometimes this is rare but it happens. Why it is not clear.
