### ISSUE TITLE
Last "Two" digits - Digit Differ Strategy

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2775]
Hi Everyone,

Good Day. Is there a way to create a bot which starts when the last two digits are equal? I wanted to create a bot which would do the following:
Starts if the last two digits of the tick value are the same. For eg: 192.3499.
Set the last digit of the tick value as the prediction; In this case - 9.
Predict to "differ" after 5 ticks.

Thanks in Advance.

**Comment by Kosta92** [comment]
This has been asked and done many times before and it's one of the worst "strategies" in existence. Trading digits is only based on luck and can easily empty your balance.

**Comment by binarybotbegginer** [comment]
> This has been asked and done many times before and it's one of the worst "strategies" in existence, even if you wait for 3 or even 4 same digits. Trading digits is only based on luck and can easily empty your balance.

Hi, 
Thanks for your response. I understand what you say. Just wanted to give it a try. 
Can you please share the link to the discussion where it was discussed earlier? Or, is it possible to show how to run a bot if the last 2 digits are equal?
Thanks

**Comment by bangvanthuat** [comment]
@binarybotbegginer  & @all 
I recommend you focus and spend your time on the Up / Down section, and the other sections if you don't want to lose money.

**Comment by thommmaz** [comment]
Digits are casino. There is no strategy for digits, these are random numbers, generated randomly. Waste of time. Try some call/put strategy.

**Comment by nextnaro** [comment]
#2739

**Comment by SANJAYA922** [comment]
Please let me know, how to set chrome browser always online even though phone display off for running bot?
