### ISSUE TITLE
Dbot will replace binary bot or parallel?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2776]
Dbot will replace binary bot or Both running in parallel/
I try to upload my existing xml build form binary bot to Dbot failed to load.

**Comment by aaron-binary** [comment]
Hey @nextnaro,

Both Binary Bot and DBot will run in parallel for a while, however we won't add any new features such as blocks and UI elements to the old Binary Bot. 

We try to stay backward compatible and have built in a conversion that _should_ convert your old strategy to the new format, but it looks like we missed some things. Could you share your strategy with us? You may either upload it to https://gist.github.com/ and paste the link here, or email us on binarybot@binary.com if you'd like to keep it private.

Regards,
Aaron
