### ISSUE TITLE
Deriv has no candle option for a period of one minute

### ISSUE THREAD

**Issue by bangvanthuat** [binary-com/binary-bot#2778]
@aaron-binary  I have seen this problem been informed by a person before, but there was a long time ago that binary.com didn't fix that problem.
![1](https://user-images.githubusercontent.com/63410420/81831013-0833bd00-9567-11ea-9c67-3a1cce671b86.PNG)

**Comment by thommmaz** [comment]
Old bot system also does not have 1M candle anymore.

**Comment by aaron-binary** [comment]
Hey @bangvanthuat and @thommmaz,

We're re-adding 1-minute candle interval soon, sorry for the inconvenience. 

Regards,
Aaron
