### ISSUE TITLE
even_odd_strategy

### ISSUE THREAD

**Issue by Rover1953** [binary-com/binary-bot#2781]
Please, guys, help to create the bot with following strategy:
The first bet is even. If it wins, then trade again even, if it loses, then trade odd,
If odd wins then trade again odd. If odd loses, then trade even and so on.
The idea is to make the same bet in case of profit, and opposite bet in case of loss.
Thank You in advance.
I tried to create something like attached.
![even_odd](https://user-images.githubusercontent.com/39854027/81930139-cd766700-95f0-11ea-9415-edef5ec48525.png)

**Comment by saidforex26** [comment]
hopefully can help
[Rover1953 even_odd_strategy.zip](https://github.com/binary-com/binary-bot/files/4628529/Rover1953.even_odd_strategy.zip)
![Rover1953 even_odd_strategy](https://user-images.githubusercontent.com/54820719/81938806-07af2b00-9628-11ea-8b42-75e0fd347a92.gif)

**Comment by Rover1953** [comment]
My Friend! You are really Great expert! Thanks a lot! I could not realise
it by myself!


чт, 14 мая 2020 г. в 16:16, saidforex26 <notifications@github.com>:

**Comment by saidforex26** [comment]
ok .. hopefully the bot can develop

**Comment by Rover1953** [comment]
Dear Saidforex, I can not connect martingale to even_odd bot. Please see my
attached file...

пт, 15 мая 2020 г. в 01:06, saidforex26 <notifications@github.com>:

**Comment by saidforex26** [comment]
Martingale what do you mean

>

**Comment by Rover1953** [comment]
I mean martingale with expected profit, maximum loss amount, trade amount
and martingale multiplier.

пн, 18 мая 2020 г. в 23:03, saidforex26 <notifications@github.com>:
