### ISSUE TITLE
Need changes in the Martingale strategy

### ISSUE THREAD

**Issue by sanal2020** [binary-com/binary-bot#2783]
Good Day

I would like to your kind consideration and help to add the Martingale strategy as mentioned in the screenshot for the below bot. I’ve manually put the Martingale amount on each loss trade for better understanding. Thank you for your time!

![Presentation](https://user-images.githubusercontent.com/62329098/82112331-8364c100-9769-11ea-9804-fa1005628d03.png)

[Rise_Fall Bot (26 Sec.).xml.zip](https://github.com/binary-com/binary-bot/files/4636887/Rise_Fall.Bot.26.Sec.xml.zip)

**Comment by thommmaz** [comment]
With 3x martingale stakes can go very high in short time.

![3xmrty](https://user-images.githubusercontent.com/40931373/82290445-9ec10d80-99af-11ea-8b69-9f956d1674e8.jpg)

**Comment by thommmaz** [comment]
![3xmrty](https://user-images.githubusercontent.com/40931373/82369491-c64fbe80-9a1f-11ea-8c20-e8ddd1261c84.jpg)
