### ISSUE TITLE
Please upgrade and change BOT / Deriv

### ISSUE THREAD

**Issue by bangvanthuat** [binary-com/binary-bot#2784]
Hello friends
I have run the test on the BOT / Deriv version and according to my comments and thoughts, binary.com should upgrade and improve:
1.The BOT programming interface is not intuitive:
- It's too complicated and confusing for me to find the block I need.
- In the interface there is no item to open the chart for me to observe and implement my ideas. I have to open another window to observe.
-During the test run, it was separated into different tabs, making it impossible for me to know and observe what was going on.
2.Binary.com has integrated too many items into the website, so it makes the program very difficult and stingy.
==> These are my own feelings, I hope binary.com will make changes to improve and bring the best experience for traders. what do you think?

![1](https://user-images.githubusercontent.com/63410420/82121973-f8141b80-97ba-11ea-9de8-0b9bf005ce88.PNG)
![2](https://user-images.githubusercontent.com/63410420/82121977-fc403900-97ba-11ea-8510-d48ffade7e9f.PNG)

**Comment by nextnaro** [comment]
agreed, on work space should show graph and on summary tab show few record from transaction and journal too.
some block missing but when upload collection backward support will generate it like  tick from string  not in list.

please carry  all functions to Deriv.


i feel it better but still confused and learning.

**Comment by nextnaro** [comment]
on function with parameter when add can not remove or edit, collapse, expland also some time missing.
![image](https://user-images.githubusercontent.com/31925501/82123005-927b5b80-97c9-11ea-93e7-afc010c9fc36.png)

**Comment by bangvanthuat** [comment]
I don't understand why the binary.com technical team removes the good stuff from the old version. It is hard to understand.
