### ISSUE TITLE
Bot strategy question on barrier.

### ISSUE THREAD

**Issue by morrehgist** [binary-com/binary-bot#2788]
Hello everyone,

Let's say currently the direction is rise and I have the set barrier as +0.15 in a higher/lower trade set up so that I enter a trade that executes higher than the barrier I've set. Is it possible to change the price barrier of the same bot to negative (-0.15) if the direction is fall? How can this be implemented?

**Comment by Kosta92** [comment]
Make it like this:

![Barrier 2](https://user-images.githubusercontent.com/11698414/82155841-f4929a00-9877-11ea-8f45-5b5579e4aac0.png)

**Comment by morrehgist** [comment]
Awesome! Let me try this and see if it's going to work. Thanks

> Make it like this:
> 
> ![Barrier](https://user-images.githubusercontent.com/11698414/82156492-8bad2100-987b-11ea-9186-3ec26fa43841.png)

**Comment by Pngugi2005** [comment]
hi Kosta92 ,

kindly send me here zip file with below settings
@Kosta92 
1. V50  ( offset barrier -0.2)trade for call 25 seconds....if for the last 30 seconds it was going up trend.  And vice versa ( offset barrier +0.2) put 25 seconds if the last 30 it was downtrend.

Please send me the XML file once done. 

Thanks.
