### ISSUE TITLE
RSI not showing same values as MT4

### ISSUE THREAD

**Issue by DrMystery** [binary-com/binary-bot#2789]
I wanted to convert a simple MT4 strategy into a binary.com bot
[M1 Timeframe] when RSI is oversold the purchase touch [with respect to MT4]
I had no idea how to make it so i found one bot similar for free but it shows different values of RSI.

![Screenshot_27](https://user-images.githubusercontent.com/26347723/82136883-24b64a80-9830-11ea-997c-7457c2c0627d.png)
![Screenshot_25](https://user-images.githubusercontent.com/26347723/82136881-23851d80-9830-11ea-8bef-045fb4652264.png)
![Screenshot_28](https://user-images.githubusercontent.com/26347723/82136882-24b64a80-9830-11ea-8335-1c87d967e2c4.png)

I wanted the RSI to fucntion as it is functioning in MT4 M1 chart.
Please help me with this.

**Comment by Martinez222** [comment]
Hey!Your bot analysis in on tick list.In MT4 is on candles.Change in RSI indicator block tick list with candles list
...

**Comment by DrMystery** [comment]
Thank you it worked. :)

**Comment by Martinez222** [comment]
U are welcome!
Close this issue :)

**Comment by Charlescpe** [comment]
@Martinez222 @DrMystery  can you help me for my strategy , Im getting zero value for my RSI 

![BOt1](https://user-images.githubusercontent.com/54802854/82862843-3fd13a80-9f53-11ea-8eab-b87b3442e2d6.png)
![BOt2](https://user-images.githubusercontent.com/54802854/82862847-419afe00-9f53-11ea-831b-6abad633e027.png)

**Comment by Martinez222** [comment]
![rsi](https://user-images.githubusercontent.com/39260368/82872853-47391980-9f3c-11ea-9335-0280f3fa892d.jpg)

**Comment by josward1** [comment]
binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company
