### ISSUE TITLE
purchase on ending candle

### ISSUE THREAD

**Issue by apaajadehbos** [binary-com/binary-bot#279]
Hi guys,

can someone help me please, how i make block with purchase after ending candle. For example,
candle green ending, then start purchase on new candle....

**Comment by aminmarashi** [comment]
Please take a look at [this](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/alternate%2520call%2520put%2520on%2520new%2520candle.xml)

**Comment by aminmarashi** [comment]
Please feel free to reopen if you have any other inquiry.
