### ISSUE TITLE
Need guidance for bot to buy over after a trigger last digit

### ISSUE THREAD

**Issue by sat150** [binary-com/binary-bot#2793]
Hello guys. I need some help
Here is the strategy. If last digit is 7 it read the next 2 last digit. If it under 7 it buy over. If the next 2 last, one is 7 over it wait till got 7 under then buy

**Comment by murali139** [comment]
for 1 tick or?

**Comment by sat150** [comment]
> for 1 tick or?


Yup it is for 1 tick

**Comment by NEWBIE3232** [comment]
please on what market?? 
10,25,50,75, or 100

**Comment by NEWBIE3232** [comment]
[sat150 over7 bot.zip](https://github.com/binary-com/binary-bot/files/4678536/sat150.over7.bot.zip)

here you go!

**Comment by sat150** [comment]
> please on what market??
> 10,25,50,75, or 100

Sorry to late reply. Mostly at 100

**Comment by sat150** [comment]
Thanks will try it and let you know the result

**Comment by NEWBIE3232** [comment]
owk
but when i tried it, the performance was poor

**Comment by NEWBIE3232** [comment]
although i made a new strategy from that one though
dont know if you would be intrested

**Comment by sat150** [comment]
How good your strategy is?

**Comment by NEWBIE3232** [comment]
its actually from your i just tweaked it.
by changing the over7 to UNDER3
the win rate is more encouraging here

**Comment by sat150** [comment]
I could try it. What time did you use it? And what gmt are you?

**Comment by sat150** [comment]
Just try your suggestion. Under3. Actually the basic are buy over 3 or 5.
Then again after trying under 3. I just thought. Why not under3 and over 7
simultaneously. Am i being greedy here? Sorry if i do

**Comment by josward1** [comment]
binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company

**Comment by NEWBIE3232** [comment]
can you share these bots????

**Comment by josward1** [comment]
I’m not at my computer at the minute but I’ll be happy to share it with you

Sent from my iPhone

On 30 May 2020, at 22:19, Dave <notifications@github.com> wrote:

﻿

can you share these bots????

**Comment by NEWBIE3232** [comment]
ok 
please when you are in reach of your computer please share
thanks

**Comment by sat150** [comment]
Here is the bot
