### ISSUE TITLE
is it possiable to fix password in binary bot

### ISSUE THREAD

**Issue by opbs2** [binary-com/binary-bot#2796]
how can I set a password in the binary bot? then no one can modify or copy my block

**Comment by ZDEGLET** [comment]
@opbs2 
No 100%

**Comment by adhamjon91** [comment]
Сделай бота на китайском

**Comment by opbs2** [comment]
are you want bot

शुक्र, 22 मई 2020 को 9:24 pm बजे को adhamjon91 <notifications@github.com>
ने लिखा:
