### ISSUE TITLE
Binary Bots for Sale

### ISSUE THREAD

**Issue by Gunter-Pearson** [binary-com/binary-bot#2798]
I'm working on a new projetct [TheProfitHunter ](bit.ly/TheProfitHunter) but meanwhile I'll let here the bots i developed and that they are with special prices for a short time.  All of them come along with a user manual, hints and strategy suggestion.

Profit Hunter - Bollinger Bands
Bot that uses call/put strategy by reading Bollinger bands. Price: $15
Video: https://youtu.be/AgOltc-y10Q 
Buy it here: https://gum.co/dEST 

Profit Hunter - Over/Under - Modal
Bot that uses Over/Under strategy with a explendid accuracy. Price: $15
Vídeo: https://youtu.be/QM2rQmp6f0o
Buy it here: https://gum.co/dHNBIr 

Profit Hunter – Barrier Bot
A secure bot that uses a low barrier strategy. Price: $15
Video: https://youtu.be/S8CXlplXoOM 
Buy it here:  https://gum.co/mSdTE 

Profit Hunter - Avenger Match Digits
A match digits bot with awesome accuracy and well adjusted martingale. Price: $20
Video: https://youtu.be/__H_P414rTI 
Buy it here: https://gum.co/veEEi 

Profit Hunter - Golden Bot 2.0  - RunLow
Our last Bot, that uses “run/low”strategy. Very accurate and profitable. Price: $20 
Video: https://youtu.be/94fAyyMoeA4 
Buy it here: https://gum.co/dGSw

**Comment by ZDEGLET** [comment]
I don’t understand why there are many small members. You just need one big one and that's it.
Why sell chicken that lays golden eggs.
CONCLUSIONS: None of these bots will make a profit. HAT!!!

**Comment by ZDEGLET** [comment]
@Gunter-Pearson 

See my example. The bot works without martingale and I do not sell it !!!
https://github.com/binary-com/binary-bot/issues/2699

**Comment by Gunter-Pearson** [comment]
Ok, thanks for the heads up.

**Comment by aaron-binary** [comment]
Hi @Gunter-Pearson,

We love the open sharing of knowledge, but we don't encourage advertising and selling your applications here. This repository is used to help others, report issues, request new features, etc.

We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today.

You can also contact marketing@binary.com to learn more about partnership options.
