### ISSUE TITLE
Вы хотите выиграть у брокера!!! :)

### ISSUE THREAD

**Issue by ZDEGLET** [binary-com/binary-bot#2799]
At the time when I have to win, I lost. It's good that this is a demo account.
They gave about 30%. Calculate what martingale should be.

Draw conclusions, gentlemen, before you start !!! :)

![2020-05-22_11-09-17](https://user-images.githubusercontent.com/36106343/82646367-2eb7bf00-9c1d-11ea-8acf-eb69cceea043.png)

Or monitor what percentage of payment.
![2020-05-22_11-23-47](https://user-images.githubusercontent.com/36106343/82647473-ed281380-9c1e-11ea-83e8-4e5ae95dfdf1.png)

**Comment by ZDEGLET** [comment]
The candle was 300 points.
![2020-05-22_11-28-27](https://user-images.githubusercontent.com/36106343/82648181-fcf42780-9c1f-11ea-95f0-5c7e9cdbc81a.png)

Even in this situation, I am losing !!! :(

![2020-05-22_11-32-28](https://user-images.githubusercontent.com/36106343/82648248-15fcd880-9c20-11ea-8101-35779846e787.png)

**Comment by thommmaz** [comment]
Metatrader price and bot system price are not the same! There are lot of differences. Bot system price is the same as webtrader price.
