### ISSUE TITLE
trend box

### ISSUE THREAD

**Issue by Muroyal1** [binary-com/binary-bot#2801]
![image](https://user-images.githubusercontent.com/63347273/82670523-ec14d780-9c5a-11ea-8679-36a27f69a083.png)

Trend Up 

Last tick is above last 5 candles high. 

Trend Down.
 
Last tick is below 5 candles low. 

It has to continue on every candles calculating last 5 candles.

**Comment by Muroyal1** [comment]
@saidforex26

**Comment by saidforex26** [comment]
can you explain again

**Comment by Muroyal1** [comment]
Thanks for your reply. 

On Every tick has to calculate its last 5 previous candles high if last tick is above previous 5 candles high then the trend will be UP. 

On every tick has to verify previous 5 candles low's if last tick is below previous 5 candles low then trend is DOWN.

This formula it close relation with Darvas box indicator  https://www.stockmaniacs.net/darvas-box-indicator/.

![image](https://user-images.githubusercontent.com/63347273/82675218-2170f380-9c62-11ea-8e7b-021968301fe1.png)

**Comment by saidforex26** [comment]
have you develop it. This will detect the shape of hing and low in 5 candles. you can develop it again. 
[muroyal1 color hinglow 5candle.zip](https://github.com/binary-com/binary-bot/files/4670659/muroyal1.color.hinglow.5candle.zip)

![muroyal1 color hinglow 5candle](https://user-images.githubusercontent.com/54820719/82713684-632f8780-9cbe-11ea-8c4b-4a33d9590360.gif)

**Comment by alansilva1** [comment]
> have you develop it. This will detect the shape of hing and low in 5 candles. you can develop it again.
> [muroyal1 color hinglow 5candle.zip](https://github.com/binary-com/binary-bot/files/4670659/muroyal1.color.hinglow.5candle.zip)
> 
> ![muroyal1 color hinglow 5candle](https://user-images.githubusercontent.com/54820719/82713684-632f8780-9cbe-11ea-8c4b-4a33d9590360.gif)

Friend, I sent an email about a strategy. Add a robot, please.

**Comment by komenggg** [comment]
> have you develop it. This will detect the shape of hing and low in 5 candles. you can develop it again.
> [muroyal1 color hinglow 5candle.zip](https://github.com/binary-com/binary-bot/files/4670659/muroyal1.color.hinglow.5candle.zip)
> 
> ![muroyal1 color hinglow 5candle](https://user-images.githubusercontent.com/54820719/82713684-632f8780-9cbe-11ea-8c4b-4a33d9590360.gif)



> have you develop it. This will detect the shape of hing and low in 5 candles. you can develop it again.
> [muroyal1 color hinglow 5candle.zip](https://github.com/binary-com/binary-bot/files/4670659/muroyal1.color.hinglow.5candle.zip)
> 
> ![muroyal1 color hinglow 5candle](https://user-images.githubusercontent.com/54820719/82713684-632f8780-9cbe-11ea-8c4b-4a33d9590360.gif)

Heellow,  can you help me
