### ISSUE TITLE
count RSI

### ISSUE THREAD

**Issue by felixhuy** [binary-com/binary-bot#2803]
Hi, please help me with RSI14
I made RSI14
And i want to check if RSI>70 then RSI<70, do purchase Rise and else RSI<30 then RSI>30, do Fall
But it is not work
<img src="https://i.imgur.com/6XXsjE9.jpg" />

**Comment by Kosta92** [comment]
I think this should do the trick:

![RSI](https://user-images.githubusercontent.com/11698414/82730839-f4c0e880-9d02-11ea-89e2-af6414520e6f.png)

**Comment by felixhuy** [comment]
> I think this should do the trick:
> 
> ![RSI](https://user-images.githubusercontent.com/11698414/82730839-f4c0e880-9d02-11ea-89e2-af6414520e6f.png)

thank you so much, it run so good
