### ISSUE TITLE
Very Important Indicator? 

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#2804]
Dear all.

Does any one have indictor that can give me information that the chart will change in the next seconds (no matter what direction will be)
What is important that the chart will change in the next seconds?

And will be perfect if there is a bot? 

Thanks alot

**Comment by ahmadhus** [comment]
.

**Comment by ahmadhus** [comment]
.

**Comment by Kosta92** [comment]
There is no such thing as an indicator that can predict the future.

**Comment by ahmadhus** [comment]
@Kosta92  i did not mean predicting the future. I mean just a high movment..
