### ISSUE TITLE
When all volatility indices started?

### ISSUE THREAD

**Issue by tymu** [binary-com/binary-bot#2805]
When all volatility indices started?

**Comment by josward1** [comment]
binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company
