### ISSUE TITLE
RSI Value is Zero NEED HELP 

### ISSUE THREAD

**Issue by Charlescpe** [binary-com/binary-bot#2807]
Can anyone help me why my rsi values is 0 ? 
My Strategy is  If RSI 100 is less than or equal to 33 if RSI100 + RSI9 is less than or equal to 38 and RSI 3 less than or equal to 0.5 Purchase Rise 

![BOt1](https://user-images.githubusercontent.com/54802854/82794392-fd512480-9ea4-11ea-90e5-7b8edf04ce37.png)
![BOt2](https://user-images.githubusercontent.com/54802854/82794401-ffb37e80-9ea4-11ea-9216-2e72734c634d.png)

**Comment by Kosta92** [comment]
Here is your bot, fixed:

[Charlescpe's RSI Bot.zip](https://github.com/binary-com/binary-bot/files/4682266/Charlescpe.s.RSI.Bot.zip)

**Comment by Charlescpe** [comment]
@Kosta92  Thanks for the help man! Can you Help me to understand what is the difference between normal rsi and rsi index array  output,  and the picture below with red circle I m confused how to use that block
![sample](https://user-images.githubusercontent.com/54802854/83107756-6036fb80-a0f1-11ea-8a7b-5bfe6a7cda98.png)

**Comment by Kosta92** [comment]
RSI gives you only the latest tick/candle result, while the RSI Array builds a list (an array) of previous results from which you can take the latest result (in list get # from end 1) or the second to last (in list get # from end 2), or some other result.

**Comment by Charlescpe** [comment]
@Kosta92 Now i understand how it works, but i dont understand the Open time candle value what is the ouput of it
