### ISSUE TITLE
DIGIT MIDDLE SECRET STRATEGY

### ISSUE THREAD

**Issue by NEWBIE3232** [binary-com/binary-bot#2811]
PLEASE I NEED A BOT WHICH ANALYSIS ON THE MIDDLE DIGITS OF DEX75

![digit middle](https://user-images.githubusercontent.com/65873634/82836455-6a24e880-9ebe-11ea-8a8b-6a8711970390.jpg)

@saidforex26 @aaron-binary

**Comment by NEWBIE3232** [comment]
I.E 
IF THE TWO MIDDLE DIGIT IS 28 PURCHASE FALL

**Comment by saidforex26** [comment]
please step up again

**Comment by NEWBIE3232** [comment]
i dont understand

**Comment by saidforex26** [comment]
explain how the strategy works

**Comment by NEWBIE3232** [comment]
i have reopened the issue

**Comment by saidforex26** [comment]
What I mean is. explain how this strategy works. so I can help make the bot

**Comment by NEWBIE3232** [comment]
owk

**Comment by NEWBIE3232** [comment]
if the ending two digits is=15 purchase rise

**Comment by NEWBIE3232** [comment]
that is the bot opens a buy option when the last two digit of volatility 75
is=15
NOTE: it can be any two numbers but my observation is 15 its 85% accurate

**Comment by ZDEGLET** [comment]
@NEWBIE3232 

How much does 1 hour fall?

**Comment by NEWBIE3232** [comment]
I.E
458,912.*15*33
the 15 has appeared then,
the bot should select rise option in this kind of situation

**Comment by NEWBIE3232** [comment]
No 5 TICK

**Comment by NEWBIE3232** [comment]
@saidforex26  
1 TICK RISE

**Comment by NEWBIE3232** [comment]
@saidforex26 
5 TICK RISE

**Comment by NEWBIE3232** [comment]
@ZDEGLET 
5 TICK FALL
sorry for the previous error

**Comment by NEWBIE3232** [comment]
DIGIT MIDDLE SECRET STRATEGY
1. IF THE MIDDLE DIGITS OF VOLATILITY 75 IS=28 for example: 435,893.5(28)7 
2. PURCHASE FALL 5 TICK
.
.
while for
.
LAST ENDING TWO DIGIT STRATEGY
1. IF THE ENDING LAST DIGIT IS=51  for example: 436,573.(51)82
2. PURCHASE RISE 5 TICK

please not there are two srategy here @saidforex26 @ZDEGLET

**Comment by NEWBIE3232** [comment]
is it clear now??

**Comment by NEWBIE3232** [comment]
DIGIT MIDDLE STRATEGY
IF THE MIDDLE DIGIT IS=28 PURCHASE FALL 5 TICK
the example is been circled in the image

![digit middle](https://user-images.githubusercontent.com/65873634/82845832-f692d380-9edd-11ea-8ba3-3971835a9e87.jpg)

**Comment by NEWBIE3232** [comment]
ENDING TO DIGIT STRATEGY
IF THE ENDING TWO DIGITS IS=61(as shown in the image) PURCHASE RISE 5TIK

![Last two digit](https://user-images.githubusercontent.com/65873634/82845899-44a7d700-9ede-11ea-8d3b-9c60d03d40c3.jpg)

**Comment by saidforex26** [comment]
[dave F28R51.zip](https://github.com/binary-com/binary-bot/files/4679057/dave.F28R51.zip)

**Comment by NEWBIE3232** [comment]
i have a bot to share with you 
should i go ahead

**Comment by saidforex26** [comment]
Please, go ahead. I just helped

**Comment by NEWBIE3232** [comment]
this is the performance rate
minimum balance $200
initial stake $0.55

![now now](https://user-images.githubusercontent.com/65873634/82846759-57240f80-9ee2-11ea-8a50-c3050dc922d6.png)

**Comment by NEWBIE3232** [comment]
[saidforex26 .zip](https://github.com/binary-com/binary-bot/files/4679104/saidforex26.zip)

**Comment by saidforex26** [comment]
if you already have a good strategy and bot. then just use it.

**Comment by NEWBIE3232** [comment]
hahaha
not like that my friend, in my 3years in binary.com i have seen that no strategy works for ever 
they always update there site so i too have to think of new strategies

**Comment by saidforex26** [comment]
yes because you use digits. good rise fall and use the right indicators when the trend is strong.

**Comment by NEWBIE3232** [comment]
am really working on that but i have not really gotten a strategy for rise and fall yet.
and also i dont know how to code so anytime i observe a new strategy i have to do i manually which i dont like it sucks.

**Comment by NEWBIE3232** [comment]
you can share a few if you have, i would be very glad

**Comment by saidforex26** [comment]
yes because you use digits. good rise fall and use the right indicators when the trend is strong.

> hahaha
> not like that my friend, in my 3years in binary.com i have seen that no strategy works for ever
> they always update there site so i too have to think of new strategies

you can share a few if you have, i would be very glad

**Comment by NEWBIE3232** [comment]
you can help share some of your bots so i can test them out i see which one suits me.
please

**Comment by saidforex26** [comment]
I use manual and bot strategies. bot doesn't run long. so there is a time

**Comment by NEWBIE3232** [comment]
ok i understand
.
if you use manual that means you are really good at binary.com
.
am just trying to learn the manual trading strategy and its giving me a tough time.

**Comment by NEWBIE3232** [comment]
always loss loss loss

**Comment by NEWBIE3232** [comment]
but am not still giving up though,  i will surely be a guru one day.
its just about time and patince

**Comment by NEWBIE3232** [comment]
please drop your email address
lets chat via email
mine roadsmedialmt@gmail.com

**Comment by saidforex26** [comment]
> please drop your email address
> lets chat via email
> mine [roadsmedialmt@gmail.com](mailto:roadsmedialmt@gmail.com)

saidforex26@gmail.com

**Comment by arehmanyounis** [comment]
arehmanyounis@gmail.com
