### ISSUE TITLE
the problem of withdrawing real account funds

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#2814]
Hi. I have a problem withdrawing my funds that have a withdrawal limit has exceeded $ 10000 with ticket number 161,494 .. please help to connect the ticket ... @sam-binary @tom-binary @aminmarashi-binary  @Mahboobeh-binary @jy-binary  @aaron-binary  @anton-binary

**Comment by NEWBIE3232** [comment]
hello my friend  
have you verified your account
because most times they require account verification for withdrawals above $1,000

**Comment by anton-binary** [comment]
Hi @NEWBIE3232, @saidforex26,

Please kindly contact Customer Support https://www.binary.com/en/contact.html to clarify your questions.

Please also note that GitHub issues forum moderated by **technical** team. We're happy to look at bugs and issues as well as to hear feedback from you about binary bot platform, however, deposits, withdrawals, and account verification related questions are beyond our scope. So, please contact customer support for those.

Thanks,
Anton
