### ISSUE TITLE
BULL INDEX SECRET NUMBER

### ISSUE THREAD

**Issue by NEWBIE3232** [binary-com/binary-bot#2815]
HELLO PLEASE I NEED A BOT THAT ANALYSIS THE CURRENT SPOT PRICE AND OPENS A TRRADE WHN THE  FOUR DIGITS ARE EQUAL TO A PARTICULAR NUMBER.
EX: 123,9.0058
if its 0058 it should purchase FALL 5 ticks
.
![bull all digits](https://user-images.githubusercontent.com/65873634/82937967-f7347400-9f88-11ea-83be-6e24405a85ff.jpg)

@creativi77 @saidforex26

**Comment by Kosta92** [comment]
How often do you expect to see those four digits and what makes you think that the price will go down after seeing them? I don't see a logic behind your strategy.

**Comment by NEWBIE3232** [comment]
Please I need a bot for ot of you can share please do I would be  very greatful.

**Comment by NEWBIE3232** [comment]
Please if you can help create one for me please I would be very grateful..

**Comment by saidforex26** [comment]
[dave bull 0058fall.zip](https://github.com/binary-com/binary-bot/files/4687032/dave.bull.0058fall.zip)

**Comment by NEWBIE3232** [comment]
Thanks @saidforex26 you are just a life saver..

**Comment by NEWBIE3232** [comment]
@saidforex26 have you been able to withdraw your funds or you did the account verification??
