### ISSUE TITLE
message---CANDLEINDEX cannot be empty 

### ISSUE THREAD

**Issue by disemp** [binary-com/binary-bot#282]
hi,

can someone help me please, why i cannot run my bot now. it has a message CANDLEINDEX cannot be empty, 30 minutes ago i could use that.....

**Comment by aminmarashi** [comment]
Hi, Sorry for the inconvenience. This is a known bug. We will do our best to fix this soon.

**Comment by disemp** [comment]
oh..ok. hope fix soon...

**Comment by aminmarashi** [comment]
This should be fixed now. Could you please check again?

**Comment by disemp** [comment]
sure..thanks @aminmarashi ..fast response
