### ISSUE TITLE
Trade same direction as current candle.

### ISSUE THREAD

**Issue by SanJess** [binary-com/binary-bot#2821]
Good day is there someone here that is able help with this blocks.
I want to check current candle's direction and trade in same direction after 20 seconds.

**Comment by navneetsinh** [comment]
> Good day is there someone here that is able help with this blocks.
> I want to check current candle's direction and trade in same direction after 20 seconds.

@SanJess 
![Trade same direction as current candle  #2821](https://user-images.githubusercontent.com/42480287/83321856-7f0fcc00-a270-11ea-946c-1feee45e3ec3.png)
