### ISSUE TITLE
Least Squares Moving Average Array

### ISSUE THREAD

**Issue by Rover1953** [binary-com/binary-bot#2822]
Hi guys! Please help to find the indicator "Least Squares Moving Average Array" to install it to the bot. Thank You! Have a nice Day!

**Comment by Rover1953** [comment]
Even if "Least Squares Moving Average" indicator, without "Array". Please, help to find it.
Many thanks in advance.

**Comment by Rover1953** [comment]
I will try to explain in more detail what I want. 
There is such an indicator "Least Squares Moving Average" on Trading View platform, but a block with this indicator is not offered on the Binary Bot site.
I want to use it when creating a bot. 
I would also like to find an indicator "Least Squares Moving Average ARRAY".
I really hope that I was able to explain exactly what I'm looking for.
Many thanks in advance.

Я постараюсь объяснить более подробно, чего я хочу. 
На платформе Trading View есть такой индикатор "Least Squares Moving Average», но на сайте "Binary Bot" блок с этим индикатором не предлагается.
Я хочу использовать его при создании бота. 
Также хотелось бы найти индикатор "Least Squares Moving Average ARRAY". 
Я действительно надеюсь, что мне удалось объяснить именно то, что я ищу.
Спасибо заранее.

**Comment by Rover1953** [comment]
Dear Fruitfella, You have suggested many useful indicators. Can you help me find a block with a Least Squares Moving Average indicator? Many thanks in advance.

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: Rover1953 <notifications@github.com>
Enviado: sexta-feira, 12 de junho de 2020 19:21
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Least Squares Moving Average Array (#2822)


Dear Fruitfella, You have suggested many useful indicators. Can you help me find a block with a Least Squares Moving Average indicator? Many thanks in advance.

**Comment by Rover1953** [comment]
Binary Ex-Machina, Can you help me find a block with a Least Squares Moving Average indicator?

**Comment by Rover1953** [comment]
May you help me to build a Least Squares Moving Average bot-block ?

**Comment by IQBinary** [comment]
![View by IQBinary 2020 08 01 14_22_43](https://user-images.githubusercontent.com/54183297/89098358-681e5f00-d404-11ea-92c5-b0ff7d4491a5.jpg)
iqbinarybot@gmail.com

**Comment by Rover1953** [comment]
I can't understand, I'm sorry, please, explain...

**Comment by Rover1953** [comment]
Hi, guys!
Nice picture, but I cannot understand the very essence.
Could You explain the point of view on my question how to create the LSMA
block for Binary Bot?


сб, 1 авг. 2020 г. в 12:07, IQ Binary <notifications@github.com>:
