### ISSUE TITLE
Can a bot like this blow up your account in the long run...just asking for opinions...NB: am not selling it

### ISSUE THREAD

**Issue by overwatch873** [binary-com/binary-bot#2825]
![best bot](https://user-images.githubusercontent.com/53020991/83270157-5d5b0a00-a1c8-11ea-8cc5-c3b61a093b30.png)

**Comment by Kosta92** [comment]
Yeah. Pretty much digit bots are invented to blow up your account with their randomness and low payout rates.

**Comment by josward1** [comment]
binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company

**Comment by thommmaz** [comment]
Digit bot needs at least 10 000 run to make any conclusion. And even after that you can't be sure it works the same way on real account because real trades and demo trades are different, demo trades don't have delay, real trades have delay in. And what's most important - digits are casino.

**Comment by josward1** [comment]
My bots aren’t digit bots they were rare occurrences based on momentum using the RSI as a measuring device. The chart couldn’t have possibly changed by chance to stop out my bot

Sent from my iPhone

On 30 May 2020, at 19:08, thommmaz <notifications@github.com> wrote:

﻿

Digit bot needs at least 10 000 run to make any conclusion. And even after that you can't be sure it works the same way on real account because real trades and demo trades are different, demo trades don't have delay, real trades have delay in. And what's most important - digits are casino.

**Comment by Jackpeter96** [comment]
> binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company

Please how did you back test your bot.. I have a bit I really need to back test

**Comment by josward1** [comment]
The way I do it is manually scroll back through the historical chart data and look for scenarios the criteria has been met and check if the trade has won or lost

Sent from my iPhone

On 31 May 2020, at 13:03, Jackpeter96 <notifications@github.com> wrote:

﻿

binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company

Please how did you back test your bot.. I have a bit I really need to back test

**Comment by Jackpeter96** [comment]
I thought the backtesting was automated of some sort 
Backtesting my bot manually will be very hectic. 
It's an even and odd digit bot

**Comment by josward1** [comment]
I wish I had a bot that could automatically back test it would have saved me weeks. I can build basic bots for what I need but I’m not an expert programmer I wouldn’t know how to do that. I’ve heard of that sort of thing been done before on here though. Sorry I can’t help you any more with that one

Sent from my iPhone

On 31 May 2020, at 13:34, Jackpeter96 <notifications@github.com> wrote:

﻿

I thought the backtesting was automated of some sort
Backtesting my bot manually will be very hectic.
It's an even and odd digit bot

**Comment by Brajuh** [comment]
Drop the bot file let's test it out and paste the result on three different sessions or 24 trade
