### ISSUE TITLE
Different results for the same bot

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2826]
Hi everyone,

Good Day. I was running two "Last Digit Prediction" bots in different tabs. All the parameters were the same except for the time interval set between 2 trades after a loss.

I found that a trade placed exactly at the same time yielded a profit in one bot and a loss in the other.
![image](https://user-images.githubusercontent.com/62483125/83306407-9b9f0a80-a256-11ea-8f52-ca11246590be.png)
![image](https://user-images.githubusercontent.com/62483125/83306493-c2f5d780-a256-11ea-887d-d6bec25b5c74.png)

As I had said earlier all the parameters were the same. Duration was 1 tick for both the bots. Only the "Run after" time was different.

Can anyone tell me why this could have happened? Is it possible for something like this to happen at all?

Thanks in advance.

**Comment by Kosta92** [comment]
My biggest concern is that you're trying to build a digits bot. You won't see a profit there because it's easy to drain your account balance.

**Comment by josward1** [comment]
binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters

**Comment by thommmaz** [comment]
First of all digits are totally casino and secondly very easy to manipulate. 

Look log file, are the prediction same for both trades?
