### ISSUE TITLE
How  is this possible>?Different markets same charts??!?!

### ISSUE THREAD

**Issue by Martinez222** [binary-com/binary-bot#2827]
![trust](https://user-images.githubusercontent.com/39260368/83325638-702c1800-a276-11ea-8bee-dd163fed0d7b.jpg)

**Comment by Kosta92** [comment]
Volatility 75 chart got stuck as Volatility 10. Try chaning the Market to some other and then change it back to Volatility 75. That should fix it.

**Comment by josward1** [comment]
binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company

**Comment by Martinez222** [comment]
@Kosta92  are u working for them?I was looking on the charts 2 diffetent bots(touch /notouch) and the trades were according to the charts...I'm here from more then 3 years i belive they cheat!

**Comment by josward1** [comment]
I don’t work for them I’m a qualified trader and created 4-5 systems to trade the volatility indices. I put them all in to bots that were successful and properly tried and tested for over 1000 trades and back tested historically, no more than 3 loosers on the bounce. traded successfully for no longer than two weeks each before completely stop working. This isn’t just a failure of the strategy the index obviously triggering my strict criteria and noticeable changes in behaviour of the price in those certain scenarios. I have moved back to forex now but I’m determined to put a stop to this they must be breaking the law somehow. Do not waste anymore time on money on binary.com bot trading

Sent from my iPhone

On 30 May 2020, at 16:32, Martinez222 <notifications@github.com> wrote:

﻿

@Kosta92<https://github.com/Kosta92> are u working for them?I was looking on the charts 2 diffetent bots(touch /notouch) and the trades were according to the charts...I'm here from more then 3 years i belive they cheat!

**Comment by josward1** [comment]
The charts match the bot results but they are in control of the behaviour of the chart and if there is a threat to them they work out the strategy and adjust the chart to make you loose. The volatility indices are produced by a random number generator that they have control over. Hence why the charts are only available by downloading via binary.com

Sent from my iPhone

On 30 May 2020, at 16:32, Martinez222 <notifications@github.com> wrote:

﻿

@Kosta92<https://github.com/Kosta92> are u working for them?I was looking on the charts 2 diffetent bots(touch /notouch) and the trades were according to the charts...I'm here from more then 3 years i belive they cheat!

**Comment by Martinez222** [comment]
I know all about volatility indices If someone lose someone else win...The broker lose,i don't belive so.We all need to belive that all bots are working for them!you can't beat them at
their own game!!!

**Comment by josward1** [comment]
The answer is forex trade manually if you ever need any help with that feel free to email me I’ll point you in the right direction but don’t waste anymore time with binary.com bots.

Sent from my iPhone

On 30 May 2020, at 20:56, Martinez222 <notifications@github.com> wrote:

﻿

I know all about volatility indices If someone lose someone else win...The broker lose,i don't belive so.We all need to belive that all bots are working for them!you can't beat them at
their own game!!!

**Comment by NEWBIE3232** [comment]
@josward1 please how can i email you.
i would love to be guided.
Thanks

**Comment by josward1** [comment]
Josward1@hotmail.com feel free to email me any time I’ll help you out wherever I can

Sent from my iPhone

On 31 May 2020, at 05:38, Dave <notifications@github.com> wrote:

﻿

@josward1<https://github.com/josward1> please how can i email you.
i would love to be guided.
Thanks

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: josward1 <notifications@github.com>
Enviado: sábado, 30 de maio de 2020 12:09
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] How is this possible>?Different markets same charts??!?! (#2827)


binary.com fix the charts to counter any successful bot. you cant possibly win. they are fraudsters. i have had successful bots tested for over 1000 trades and backtested through historical data. after 2 weeks of successful trading the bots completely stop working. Along with that my account kept getting froze every week or two demanding more proof of ID. They only want money moving one way. Into their pockets. Take it from somebody with 3-4 years experience dealing with this company
