### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by shafikgh** [binary-com/binary-bot#2833]
Hello 
I would like to ask you guys , how could I creat a condition says 
Check if the biggest digit's percent is Odd do call 
If Even do put .
Please have a look on the pic.

Thank you guys. 
![Screenshot_20200601-154705_Samsung Internet](https://user-images.githubusercontent.com/60851555/83416253-b1f8c200-a420-11ea-9c0a-cfd071249f5f.jpg)

**Comment by Jackpeter96** [comment]
You said biggest digit percent but yet you indicate 0% in the photo and what would be the duration of the purchase you would want

**Comment by shafikgh** [comment]
U r right :) 
 that pic with mention to 7 digit  i got it from website just to make it clear and understand what i am taking about.

According to my words in that pic the biggest will be 0 digit 16% 

Thank you :)
