### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by lcmouras** [binary-com/binary-bot#2835]
**Good evening**

I am developing a platform to offer my bots for FREE to help people, not for profit for me.
I am having trouble implementing my bots on the platform, as a just "clickable" option '<button>'.
I would like some help on this, where I can start, maybe do an individual '.js' on the outside with 'xmlhttprequest' options.
I need a north.

um exemplo disto:
<img src="https://i.imgur.com/q3jdvvo.jpg">
Thank you in advance for your help

**Comment by ZDEGLET** [comment]
Want to help people put your bots here and don’t worry.

**Comment by aaron-binary** [comment]
Hey @lcmouras,

You could have a look at the `binary-bot/src/botPage/view/blockly/index.js` file. There is a `loadWorkspace` function that may be useful to you. For example, you could call this function with a custom XML when clicking on one of your custom strategies.

Regards,
Aaron

**Comment by lcmouras** [comment]
@aaron-binary 


Sorry for the insistence, but, could you tell me how can I do this?

**Comment by lcmouras** [comment]
@aaron-binary 

Hello,

I managed to insert a list of my bots in my application.

But I have a small problem, how can I choose the default language in which my binary bot application will open?
It is automatically programmed to load in "English". Where or how can I change to another language for automatic loading?

I'm using the live-api.

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: lcmouras <notifications@github.com>
Enviado: quinta-feira, 4 de junho de 2020 02:42
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Code problems (#2835)


@aaron-binary<https://github.com/aaron-binary>

Sorry for the insistence, but, could you tell me how can I do this?
