### ISSUE TITLE
Last Digit - Digit Differ Bot

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2839]
Hi everyone, Good Day.

Can anyone please confirm what does this function do?
![image](https://user-images.githubusercontent.com/62483125/83665752-f43c2200-a61f-11ea-9af5-2276c90b158d.png)
Please correct me if I am wrong. According to my understanding it fetches the last digit of the tick value before the bet is placed i.e., the last digit of the tick value before the Entry Spot. Am I right?

If that is the case what does this function do? 
![image](https://user-images.githubusercontent.com/62483125/83665973-53019b80-a620-11ea-94ad-7d2d1de82eab.png)
It has 0 instead of 1. I thought that it would return an error if included in a bot, but it appeared to run and did make some predictions. 
Can anyone tell me what value does it fetch?

Thanks in advance.

**Comment by aaron-binary** [comment]
Hey @binarybotbegginer,

You're correct, fetching `1` from end will fetch the last value in the given list, whereas `0` from end will return the first value of the given list (I agree that that's a bit confusing). 

The best way to visualise this is by using the notify block, please see the screenshot below:

<img width="1134" alt="Screenshot 2020-06-04 at 09 58 02" src="https://user-images.githubusercontent.com/44427668/83706419-fca95280-a649-11ea-84b3-bbdc5db6b854.png">

If you'd like to play around with this, here's the XML:

- https://gist.github.com/aaron-binary/48936e9e9c0c29d82a47650a744120ec

Hope that helps,
Aaron

**Comment by binarybotbegginer** [comment]
> Hey @binarybotbegginer,
> 
> You're correct, fetching `1` from end will fetch the last value in the given list, whereas `0` from end will return the first value of the given list (I agree that that's a bit confusing).
> 
> The best way to visualise this is by using the notify block, please see the screenshot below:
> 
> <img alt="Screenshot 2020-06-04 at 09 58 02" width="1134" src="https://user-images.githubusercontent.com/44427668/83706419-fca95280-a649-11ea-84b3-bbdc5db6b854.png">
> 
> If you'd like to play around with this, here's the XML:
> 
> * https://gist.github.com/aaron-binary/48936e9e9c0c29d82a47650a744120ec
> 
> Hope that helps,
> Aaron

Thanks a lot for that. Is it possible to explain with a "Digit Differ" example please?

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://2.bp.blogspot.com/-3AoDOzW1gV8/XvQK1dJa7uI/AAAAAAAAAh8/WbMqNuNadCM5MguQ-eLUyGbF0EwAvkD9ACK4BGAYYCw/w1200-h630-p-k-no-nu/image.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: sam-binary <notifications@github.com>
Enviado: quinta-feira, 18 de junho de 2020 03:25
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Last Digit - Digit Differ Bot (#2839)


Closed #2839<https://github.com/binary-com/binary-bot/issues/2839>.

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: binarybotbegginer <notifications@github.com>
Enviado: quinta-feira, 4 de junho de 2020 09:07
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Last Digit - Digit Differ Bot (#2839)


Hey @binarybotbegginer<https://github.com/binarybotbegginer>,

You're correct, fetching 1 from end will fetch the last value in the given list, whereas 0 from end will return the first value of the given list (I agree that that's a bit confusing).

The best way to visualise this is by using the notify block, please see the screenshot below:

[Screenshot 2020-06-04 at 09 58 02]<https://user-images.githubusercontent.com/44427668/83706419-fca95280-a649-11ea-84b3-bbdc5db6b854.png>

If you'd like to play around with this, here's the XML:

  *   https://gist.github.com/aaron-binary/48936e9e9c0c29d82a47650a744120ec

Hope that helps,
Aaron

Thanks a lot for that. Is it possible to explain with a "Digit Differ" example please?
