### ISSUE TITLE
counter of green candles and red candles

### ISSUE THREAD

**Issue by claytonliotti** [binary-com/binary-bot#2840]
hello 
how to set a counter for green and red candles in closing the candles

**Comment by grzmartins** [comment]
<img width="662" alt="Sem Título" src="https://user-images.githubusercontent.com/4849671/83699918-bb7a5980-a5db-11ea-8a56-607c7041857b.png">

**Comment by claytonliotti** [comment]
![image](https://user-images.githubusercontent.com/44580787/83702359-ddc3a580-a5e2-11ea-8b95-e356e233c1ea.png)

that's how I did it

**Comment by claytonliotti** [comment]
53/5000
Hello
you can count the candle after closing it

**Comment by grzmartins** [comment]
A sua função só vai definir e existe um novo candle, para saber se ele é verde ou vermelho  precisa da função "Is candle black?", que na verdade diz se ele é vermelho ou não rsrs

**Comment by claytonliotti** [comment]
that's right
I want to count the candles at the close
create a candle counter

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: claytonliotti <notifications@github.com>
Enviado: sexta-feira, 5 de junho de 2020 00:50
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] counter of green candles and red candles (#2840)


that's right
I want to count the candles at the close
create a candle counter

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: Graziani Martins <notifications@github.com>
Enviado: quinta-feira, 4 de junho de 2020 11:18
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] counter of green candles and red candles (#2840)


A sua função só vai definir e existe um novo candle, para saber se ele é verde ou vermelho precisa da função "Is candle black?", que na verdade diz se ele é vermelho ou não rsrs

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: claytonliotti <notifications@github.com>
Enviado: quinta-feira, 4 de junho de 2020 11:09
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] counter of green candles and red candles (#2840)


53/5000
Hello
you can count the candle after closing it

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: claytonliotti <notifications@github.com>
Enviado: quinta-feira, 4 de junho de 2020 00:41
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] counter of green candles and red candles (#2840)


[image]<https://user-images.githubusercontent.com/44580787/83702359-ddc3a580-a5e2-11ea-8b95-e356e233c1ea.png>

that's how I did it
