### ISSUE TITLE
How to get predition value from previous trade. 

### ISSUE THREAD

**Issue by silambu8194** [binary-com/binary-bot#2843]
Hi all, 
I want to know,  how to get last trade predition value and use the same value for my next trade kn binary bot.  
For Ex.  I am using predition value randomly 0-9.  If win my predicted value will be change randomly for next trade but if i loss that trade my next trade prediction value is same from my last trade (which is loss) prediction value.  Kindly help me.

**Comment by silambu8194** [comment]
I found it myself

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://2.bp.blogspot.com/-3AoDOzW1gV8/XvQK1dJa7uI/AAAAAAAAAh8/WbMqNuNadCM5MguQ-eLUyGbF0EwAvkD9ACK4BGAYYCw/w1200-h630-p-k-no-nu/image.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com

________________________________
De: silambu8194 <notifications@github.com>
Enviado: quarta-feira, 17 de junho de 2020 16:36
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] How to get predition value from previous trade. (#2843)


I found it myself
