### ISSUE TITLE
Help to put compound interest in my robot

### ISSUE THREAD

**Issue by sitespagando** [binary-com/binary-bot#2847]
Hello guys, I found a very good robot on the internet, but I would like to make some changes, but I don't understand. I ask for help from someone who understands about editing and creating

I already tested it for a week on the virtual account and it has 90% accuracy, so I will use it on the real account

I would like to add the practice of generating compound interest.

Example: he won the first time, in the next entry he needs to enter the amount he won + initial value, repeat this 5 times in a row while winning, after 5 times in a row with compound interest, he returns to enter the initial value again, so that the gains are faster and when you lose, it is not a high value to make martingale.

FOLLOW THE ROBOT TO DOWNLOAD THE FILE ATTACHED

[BOT DIGIT DIFFER.zip](https://github.com/binary-com/binary-bot/files/4751064/BOT.DIGIT.DIFFER.zip)

**Comment by Kosta92** [comment]
> when you lose, it is not a high value to make martingale

You do realise that you are talking about digits differ. Digits are completely random and trading them is only based on luck. Trading digits differ actually has the highest martingale (20x), which, if you lose more than 3 or 4 times in a row, can completely wipe your account balance. Losing multiple times in a row is rare but it does happen. Never trade digits with a real account.
