### ISSUE TITLE
New binary-bot does not run simple logic

### ISSUE THREAD

**Issue by APWx** [binary-com/binary-bot#285]
As in the title .... the logic: if direction rise purchase rise does not work. The bot freeze at the start. Is that because of the candle index bug that was just reported ?

**Comment by aminmarashi** [comment]
No, not related. Thanks for reporting, we'll fix it asap.

**Comment by aminmarashi** [comment]
Should be fixed now.

**Comment by APWx** [comment]
It works now. Thank you.

2017-07-04 21:34 GMT-05:00 Amin Marashi <notifications@github.com>:
