### ISSUE TITLE
Binary tick reader analyzer 

### ISSUE THREAD

**Issue by Jackpeter96** [binary-com/binary-bot#2850]
Please can someone explain how to trade rise and fall using the binary tick ready analyzer 

What numbers to look and how to analyze  the trend

**Comment by Ana29tol** [comment]
[STRATEGY_xZ_Nicolai_(Eng)(1).pdf](https://github.com/binary-com/binary-bot/files/4775214/STRATEGY_xZ_Nicolai_.Eng.1.pdf)

**Comment by buckman1974** [comment]
I have this also, Ana29tol .. does it make sense to you? and are you using it ok to make profits? (the owner of this PDF won't respond) even though I paid a small amount for it.. and I see many on Youtube using these Analyzers but not sure of the instructions?

**Comment by overwatch873** [comment]
Usually based on tick movements....for example out 5 ticks...if you get 3 ticks up 2 ticks down...then you buy/call and vice versa...depends with the logic

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: Ana29tol <notifications@github.com>
Enviado: sábado, 13 de junho de 2020 18:35
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Binary tick reader analyzer (#2850)


STRATEGY_xZ_Nicolai_(Eng)(1).pdf<https://github.com/binary-com/binary-bot/files/4775214/STRATEGY_xZ_Nicolai_.Eng.1.pdf>

**Comment by rkel0015612** [comment]
can you help me with the trend tick analyzer
