### ISSUE TITLE
MEGA STRATEGY REQUEST

### ISSUE THREAD

**Issue by NEWBIE3232** [binary-com/binary-bot#2856]
HELLO
PLEASE I NEED HELP BUILDING A BOT
PLEASE AN INTRESTED PROGRAMMER SHOULD RESPOND
THIS STRATEGY IS 99% WORKING, BUT IT REQUIRES SERIOUS BUILDING/CODING 
I CANT EPLAIN ALL THE SECRET BEHIND THE STRATEGY HERE SO PLEASE IF YOU ARE INTRESTED PLEASE RESPOND.
@saidforex26 and all other programmers

**Comment by NEWBIE3232** [comment]
it would take a great logical work in other for the bot to be able to be built so i need assisstance

**Comment by saidforex26** [comment]
What strategy do you have

**Comment by sajeeshbinary** [comment]
i want digit killer startegy ,any one pls support me
![ss-opit-100](https://user-images.githubusercontent.com/66852445/84617303-1e2cf880-aeec-11ea-945d-19c691a2ea9e.jpg)

**Comment by sajeeshbinary** [comment]
any one pls create this type of binary bot

**Comment by NEWBIE3232** [comment]
@sajeeshbinary  if its digit differ stratery you want i have  better one for you.
better than digit killer.
its called the OMEGA DIFFER 
it gives 1loss in 20 runs

**Comment by NEWBIE3232** [comment]
@saidforex26 let me drop the strategy
sorry i took long to reply
am just trying to find the best way to present  and explian the strategy for your understanding

**Comment by NEWBIE3232** [comment]
@sajeeshbinary PLEASE DO WELL TO TWEAK OR EDIT THE STRATEGY TO BEST SUIT YOUR NEEDS.
NOTE: NO BOT IS PERFECT

**Comment by NEWBIE3232** [comment]
@saidforex26 
PLEASE CHECK YOUR EMAIL

**Comment by saidforex26** [comment]
is your email roadsmedialmt@gmail.com

**Comment by NEWBIE3232** [comment]
@saidforex26 yes..
i justsent you a message again with more explanation

**Comment by NEWBIE3232** [comment]
Yes

**Comment by NEWBIE3232** [comment]
@saidforex26  please check your email

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: Dave <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 08:32
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] MEGA STRATEGY REQUEST (#2856)


@saidforex26<https://github.com/saidforex26>
PLEASE CHECK YOUR EMAIL

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: saidforex26 <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 08:34
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] MEGA STRATEGY REQUEST (#2856)


is your email roadsmedialmt@gmail.com<mailto:roadsmedialmt@gmail.com>

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: saidforex26 <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 02:32
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] MEGA STRATEGY REQUEST (#2856)


What strategy do you have
