### ISSUE TITLE
digit killer strategy 

### ISSUE THREAD

**Issue by sajeeshbinary** [binary-com/binary-bot#2857]
pls any one to create this type of bot
![ss-opit-100](https://user-images.githubusercontent.com/66852445/84617749-8b8d5900-aeed-11ea-9995-566bf5f1d388.jpg)

**Comment by overwatch873** [comment]
Dont be naive to think that its a holy grail system....you cam still incur 3 consecutive looses and that would most likely mess up your account....

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
________________________________
De: sajeeshbinary <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 04:20
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] digit killer strategy (#2857)


pls any one to create this type of bot
[ss-opit-100]<https://user-images.githubusercontent.com/66852445/84617749-8b8d5900-aeed-11ea-9995-566bf5f1d388.jpg>

**Comment by trident2005** [comment]
@rubenspina please stop the spam
