### ISSUE TITLE
cannot load previously save xml blocks

### ISSUE THREAD

**Issue by gabrielnkrumahza** [binary-com/binary-bot#2858]
[Botpif.zip](https://github.com/binary-com/binary-bot/files/4778030/Botpif.zip)

Hi
I edited the strategy above and saved it into xml but when I try to load it, it fails to load to binary, with the response unrecognized file. Kindly assist, thank you

**Comment by gabrielnkrumahza** [comment]
Hi 
I edited the strategy above and saved it into xml but when I try to load it, it fails to load to binary, with the response unrecognized file. Kindly assist, thank you

**Comment by sam-binary** [comment]
Hi @gabrielnkrumahza ,

Please make sure that the xml file content or extension(.xml) was not modified.

Regards,
Sam

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: Gabriel Nkrumah <notifications@github.com>
Enviado: segunda-feira, 15 de junho de 2020 04:32
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] cannot load previously save xml blocks (#2858)


Hi
I edited the strategy above and saved it into xml but when I try to load it, it fails to load to binary, with the response unrecognized file. Kindly assist, thank you
