### ISSUE TITLE
Best BOT 98% Profit

### ISSUE THREAD

**Issue by isave** [binary-com/binary-bot#2859]
I want to buy best bot 2020
pm me isepparhan@gmail.com

**Comment by overwatch873** [comment]
Just dont get scammed bro

**Comment by sam-binary** [comment]
Hi @isave ,

We love the open sharing of knowledge, but we don't encourage advertising or selling your applications here. This repository is used to help others, report issues, request new features, etc.
We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today.

You can also contact marketing@binary.com to learn more about partnership options.
