### ISSUE TITLE
15 min candle setted but bot works on 1 min candle

### ISSUE THREAD

**Issue by zomuzco** [binary-com/binary-bot#286]
Hello, I'm building a bot using RSI and BB (RSI>70+BB> upper SELL) and I have 2 problems:  
1) I setted the default candle on 15 minutes candle but bot works on 1 min candle.
2) I'd like the buy/sell starts at the end of the candle, for example if the 15 mins candle close over 70RSI and over the upper BB then sell. 
![snap](https://user-images.githubusercontent.com/29904469/27844812-2a55d890-6127-11e7-8b33-be17c69d17cd.JPG)
 

Here is the screenshot of what I planned till now.
Can you help me? I am quite noob.

**Comment by aminmarashi** [comment]
Didn't you forget to change the default candle interval to 15 minutes in the first block?

**Comment by zomuzco** [comment]
In the screenshot candle is settled on 1min, but I run the bot with 15 min and it works anyway on 1 min candle

**Comment by aminmarashi** [comment]
Ah, I see. Thanks for reporting. Will fix soon.

**Comment by zomuzco** [comment]
Thank you very much! 
What about the second question? Is the bot correct to sell or buy just when the 15 min candle close on upper rsi and bb or should I change something?

**Comment by aminmarashi** [comment]
Your strategy looks fine to me, I'll check it and let you know.

**Comment by aminmarashi** [comment]
Your strategy looks fine by me. And the issue should be fixed. So why not give it a try using virtual account first? :)

**Comment by zomuzco** [comment]
I tryed it but the bot is still working on 1 min candle instead of 15 min

**Comment by aminmarashi** [comment]
Did you refresh? I checked with:
[binary-bot rsi.xml.zip](https://github.com/binary-com/binary-bot/files/1127063/binary-bot.rsi.xml.zip) and it seems to be working fine.

**Comment by aminmarashi** [comment]
to make sure you can compare the values from the chart

**Comment by aminmarashi** [comment]
You can also try with 
[matching candles.xml.zip](https://github.com/binary-com/binary-bot/files/1127071/matching.candles.xml.zip)
This is what I get:
<img width="892" alt="screen shot 2017-07-06 at 3 40 23 pm" src="https://user-images.githubusercontent.com/6560964/27900576-873f31ba-6261-11e7-83d2-cfcf51d1760b.png">

**Comment by zomuzco** [comment]
ok. I'll try to refresh and run the bot this afternoon and see if it works, thank you

**Comment by zomuzco** [comment]
Ok, now it seems to work properly, thank you very much, I noticed just a delay between the candle closing and the operation start. Could it be because I run more bots at the same time?

**Comment by aminmarashi** [comment]
Could you please describe the delay in more details (which candle closing (the chart or the blocks) and which operation start (purchase?)). Or better if you can give me a screen recording that demonstrates the delay.

**Comment by zomuzco** [comment]
I think it's delay for this reason: if the bot works on 15 min candles starting operation at the close of the candle, sell or buy should start alwais in fixed times isn't it? For example 9.00, 16.15, 20.30 and similar. It happens to start at (for example) 16.20, 16.22. Maybe I am wrong and the bot works on independent candle different from the cart?

**Comment by aminmarashi** [comment]
Yes, the above strategy works on the candles close values (which can be anytime during the 15 minutes of the candle existence). I suggest you try the `open` value (which will be determined on starting time of each candle) if you need to trade on new candles.

**Comment by zomuzco** [comment]
Oh ok, I thought close values meant that the bot consider only the final value of the 15 min candle and not it could be in anytime candle existence. I'll try with open value, thanks.
