### ISSUE TITLE
Minta Tolong Buatin Bot Digit Over Binary~

### ISSUE THREAD

**Issue by adityo-subekti** [binary-com/binary-bot#2860]
Permisi agan, agan.. bisa Minta tolong buat Bot Digit Over Binary~ sesuai dengan logika ini di video youtube nggak~?

thanks before :)
link: 

https://www.youtube.com/watch?v=tWNLP5BDSvo&feature=youtu.be

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: adityo-subekti <notifications@github.com>
Enviado: terça-feira, 16 de junho de 2020 04:57
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Minta Tolong Buatin Bot Digit Over Binary~ (#2860)


Permisi agan, agan.. bisa Minta tolong buat Bot Digit Over Binary~ sesuai dengan logika ini di video youtube nggak~?

thanks before :)
link:

https://www.youtube.com/watch?v=tWNLP5BDSvo&feature=youtu.be
