### ISSUE TITLE
Binary bot - candle values

### ISSUE THREAD

**Issue by hpdk9** [binary-com/binary-bot#2861]
How to read the open value of the current candle? Please help.

**Comment by sam-binary** [comment]
Hi @hpdk9 

you can use this block to read it.
<img width="506" alt="Screenshot 2020-06-17 at 11 36 41 AM" src="https://user-images.githubusercontent.com/51310435/84852226-e14d3700-b08e-11ea-88ed-30fd94d468c1.png">
It's under `Tick Analysis` Menu.

Regards,
Sam

**Comment by hpdk9** [comment]
Thanks sam-binary! Does the block you have given read the current candle or the candle immediately before the current one?

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: hpdk9 <notifications@github.com>
Enviado: terça-feira, 16 de junho de 2020 09:10
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Binary bot - candle values (#2861)


How to read the open value of the current candle? Please help.
