### ISSUE TITLE
Index 25 never lose Rise/Fall strategy

### ISSUE THREAD

**Issue by Simo-912** [binary-com/binary-bot#2864]
Hello Guys,I hope you safe right there!
I have bought a Rise/Fall strategy for Binary.com and It worked work very well...and I need your help to build a bot based on it.

For Index 25, how to open an open position is as follows:
RISE: see the movement of "worm garfik", if chart move up 3 times in situation of highest point[Blue Head], and 
move straight, then do open position RISE 5 ticks.

FALL:: see the movement of "worm garfik", if the chart moves down 3 times in the lowest point [Red Head]
situation, and move up a bit, then do the open position Fall.

see the “worm garbage” movement, if the graph moves up 3 times in the highest point situation,
 and move down a bit, then do the Fall position open.

**Comment by overwatch873** [comment]
Therez nothing like a "never lose robot"....its alwys gonnna lose at some point....what really matters is your money management strategy

**Comment by thommmaz** [comment]
Tick strategy never work the same way in demo and in real account.  If it works manually then use it manually, you never win with bot, there is always some problem with bots - network, system updates, upgrades, many other issues from broker side....

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: Simo-912 <notifications@github.com>
Enviado: terça-feira, 16 de junho de 2020 21:02
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Index 25 never lose Rise/Fall strategy (#2864)


Hello Guys,I hope you safe right there!
I have bought a Rise/Fall strategy for Binary.com and It worked work very well...and I need your help to build a bot based on it.

For Index 25, how to open an open position is as follows:
RISE: see the movement of "worm garfik", if chart move up 3 times in situation of highest point[Blue Head], and
move straight, then do open position RISE 5 ticks.

FALL:: see the movement of "worm garfik", if the chart moves down 3 times in the lowest point [Red Head]
situation, and move up a bit, then do the open position Fall.

see the “worm garbage” movement, if the graph moves up 3 times in the highest point situation,
and move down a bit, then do the Fall position open.
