### ISSUE TITLE
Bot trading

### ISSUE THREAD

**Issue by overwatch873** [binary-com/binary-bot#2865]
Sup guys.....which robots are better digits bots(over/under;even/odd) OR rise/ fall bots....in the long run.....AND WHY??

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://2.bp.blogspot.com/-3AoDOzW1gV8/XvQK1dJa7uI/AAAAAAAAAh8/WbMqNuNadCM5MguQ-eLUyGbF0EwAvkD9ACK4BGAYYCw/w1200-h630-p-k-no-nu/image.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: overwatch873 <notifications@github.com>
Enviado: quarta-feira, 17 de junho de 2020 01:00
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Bot trading (#2865)


Sup guys.....which robots are better digits bots(over/under;even/odd) OR rise/ fall bots....in the long run.....AND WHY??
