### ISSUE TITLE
binary buster indicator is big scam

### ISSUE THREAD

**Issue by islamrefaey2019** [binary-com/binary-bot#2867]
this scammer sell his bad indicator for me by 100$ 
his indicator is free in all telegram channel 
please no one contact him 
he was a big Indian thief
his indicator here 
[BINARY BUSTER PROFIT 2(2).zip](https://github.com/binary-com/binary-bot/files/4790517/BINARY.BUSTER.PROFIT.2.2.zip)

this is the link of his bad and scam telegram channel 
https://t.me/binarybuster09

**Comment by sam-binary** [comment]
Hi @islamrefaey2019 ,

We love the open sharing of knowledge, but we don't encourage advertising and selling your applications here. This repository is used to help others, report issues, request new features, etc.
We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today.

You can also contact marketing@binary.com to learn more about partnership options.
