### ISSUE TITLE
Rise Fall Strategy - Consecutive rise for 4 ticks

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2885]
Hi All,

Good Day. I am planning to create a bot based on Rise / Fall. One of the parameters / conditions for that bot is "Consecutive rise for 4 ticks".

For eg:
1723.56
1725.22
1729.01
1732.11

Can anyone please tell me whether the following it the right way to do it?

![image](https://user-images.githubusercontent.com/62483125/85843773-cba9e100-b7f5-11ea-98eb-c815b4799431.png)

Thanks

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: binarybotbegginer <notifications@github.com>
Enviado: sexta-feira, 26 de junho de 2020 09:42
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Rise Fall Strategy - Consecutive rise for 4 ticks (#2885)


Hi All,

Good Day. I am planning to create a bot based on Rise / Fall. One of the parameters / conditions for that bot is "Consecutive rise for 4 ticks".

For eg:
1723.56
1725.22
1729.01
1732.11

Can anyone please tell me whether the following it the right way to do it?

[image]<https://user-images.githubusercontent.com/62483125/85843773-cba9e100-b7f5-11ea-98eb-c815b4799431.png>

Thanks

**Comment by Kosta92** [comment]
Yes, that's correct.

**Comment by binarybotbegginer** [comment]
> Yes, that's correct.

Thanks a lot.
