### ISSUE TITLE
Typed Digits follow bot?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#2886]
Is there a simple way to determine two numbers on Vol 100, say :

XXXX.X8
XXXX.X1
Always FALL Trade on next digit regardless of what it is? so the signal is **ONLY  8 then followed by 1 to FALL**?

XXXX.X5
XXXX.X0
Always RISE Trade on next digit regardless of what it is? so the signal is **ONLY  5 then followed by 0 to RISE**?

Whats the simplest way to determine the END last digit on Vol 100 over different sets of digits that appear over time in the sequence above?

Ontop of the above is there a simple way to add the color too? so XXXX.X8 (RED ONLY) and XXXX.X1 (Blue only)  ??

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
________________________________
De: buckman1974 <notifications@github.com>
Enviado: sexta-feira, 26 de junho de 2020 13:29
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Typed Digits follow bot? (#2886)


Is there a simple way to determine two numbers on Vol 100, say :

XXXX.X8
XXXX.X1
Always FALL Trade on next digit regardless of what it is? so the signal is ONLY 8 then followed by 1 to FALL?

XXXX.X5
XXXX.X0
Always RISE Trade on next digit regardless of what it is? so the signal is ONLY 5 then followed by 0 to RISE?

Whats the simplest way to determine the END last digit on Vol 100 over different sets of digits that appear over time in the sequence above?
