### ISSUE TITLE
How to add split martingale to my recovery bot 

### ISSUE THREAD

**Issue by Raghuramreddyj** [binary-com/binary-bot#2888]
Hi

@Binary-ex-machine
@arun-binary 

can you please help me how to add split martingale to my existing recovery bot 
i want the "loss recovery stake" to be split in to 3 steps
[https://drive.google.com/file/d/1SxnRCfVT5x6KgS2HWJI9h8N44Ydgt-Tj/view?usp=sharing](url) 

please help.....

**Comment by rubenspina** [comment]
da uma olhada com calma aqui que vai encontrar o que vc quer tem varios pdf de estrategias. https://ongdetraders.blogspot.com/

[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
cheap hypermarket digital bot<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: Raghuramreddyj <notifications@github.com>
Enviado: sábado, 27 de junho de 2020 17:07
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] How to add split martingale to my recovery bot (#2888)


Oi

@ Binário-ex-máquina
@ arun-binário<https://github.com/arun-binary>

você pode me ajudar como adicionar split martingale ao meu bot de recuperação existente?
Quero que a "perda de recuperação" seja dividida em três etapas
https://drive.google.com/file/d/1SxnRCfVT5x6KgS2HWJI9h8N44Ydgt-Tj/view? usp = compartilhamento<url>

por favor ajude.....

-
Você está recebendo isso porque está inscrito neste tópico.

**Comment by thommmaz** [comment]
Digits are casino. You can never beat broker in their own game. Generate rise/fall bot minimum at least 2min trade duration and maybe you can earn some pennies. Forget digits!
