### ISSUE TITLE
Best strategy for bot? what time i should use?

### ISSUE THREAD

**Issue by chidotaku** [binary-com/binary-bot#2889]
Hello, i have and strategy,  i must win only two times per day.  

![image](https://user-images.githubusercontent.com/67313783/85984416-c6dc5d00-b9ae-11ea-8bc8-1e97bce8955d.png)

My question here is what time is the best hour for using a bot?  It works with synthetic indices but i need he won only two times per day 

What do you think about this?

**Comment by nanajr** [comment]
Any answer to this question would be subjective at best.
What bot are you using? What strategy? Which asset even there are several among synthetic indices...
You being using the bot for a while...maybe you can help us answer that question.

**Comment by thommmaz** [comment]
Synthetic indexes are randomly generated prices, there is no such a thing as "best hour" or "best time" for trading them.

**Comment by Brajuh** [comment]
Sorry I don't think there is a best trading time for indexes

**Comment by chidotaku** [comment]
Hello thanks for the answer i will sharing you my bot! but sadly here my results

![image](https://user-images.githubusercontent.com/67313783/86223510-3ee08980-bb4d-11ea-807b-0569ed602759.png)

 I thought i found a good time UTC-5 . And starting my plan, i just need only 4 wins per day. But at the 15th day i lose my money T_T.... So i started again... with a new strategy because in the last time the 4th martingale was the lost so...i was trying only 3 wins per day... and...
![image](https://user-images.githubusercontent.com/67313783/86224130-1c9b3b80-bb4e-11ea-92fa-a02377bef4e5.png)

At the 11th day again i lose my money again T_T. So i understand if i put only two wins one day i will lose my money again, or maybe im wrong or missing something...

Here the link of my bot, 

https://www.mediafire.com/file/dcao8lieef83c7d/50usd_capital.xml/file
