### ISSUE TITLE
Candle Color

### ISSUE THREAD

**Issue by overwatch873** [binary-com/binary-bot#2890]
Hello guys...is there a block  of code which determines the current candle colour lets say in one minute time frame...(ie)" not the previous candle colour".... For example the logic would be like....if last tick < MA 10 and current candle colur is red .....Purchase Fall

**Comment by Brajuh** [comment]
Do you want a candle colour block?

**Comment by overwatch873** [comment]
> Do you want a candle colour block?

Yes bro

**Comment by Brajuh** [comment]
[@lasaidhari.Block.Candles.Color.Indicator.BCCI.zip](https://github.com/binary-com/binary-bot/files/4858507/%40lasaidhari.Block.Candles.Color.Indicator.BCCI.zip)
Please share the bot if created, would you?

**Comment by Brajuh** [comment]
Ask how to use it if you can't figure it out

**Comment by overwatch873** [comment]
Okay thanks bro...will do so
