### ISSUE TITLE
Need Help for small changes

### ISSUE THREAD

**Issue by luckykings** [binary-com/binary-bot#2893]
**Need Help for Small Changes Binary bot Please Help Me**

i have a over under bot ( Need bolck trade this number 0 1 2 3 4 ) ( no trade ) i want to trade only this number 5 6 7 8 9 ( trade) see this picture
![56414895-ac3a2e80-62a9-11e9-9fe5-42fb9b250682](https://user-images.githubusercontent.com/44045741/86344669-f8d21580-bc73-11ea-8c7d-e13c579a2f75.jpg)
[binary-bot.zip](https://github.com/binary-com/binary-bot/files/4863375/binary-bot.zip)

**Comment by overwatch873** [comment]
umm if am getting your question correctly ...your want your bot to predict the next last digit...and you want it to be above 5 everytime....which is 100% percent impossible......digits are highly unpredictable....and you likely never gonna be profitable when using digit bots in the long run...its just gambling

**Comment by thommmaz** [comment]
Digits are randomly generated numbers by computer. You think you can beat computer?? 

Digits are gambling, forget it and concentrate to some rise/fall strategy with expiration minimum 2min.
