### ISSUE TITLE
Synthentic indices

### ISSUE THREAD

**Issue by overwatch873** [binary-com/binary-bot#2895]
Hey guys....which is the best indice to trade ...when using a rise/fall bot.....preferebly stable and less volatility

**Comment by thommmaz** [comment]
Volatility indexes has nothing to do with volatility. These are randomly generated prices and every pair can be stable and less stable at some time. No one can predict it and I'm 100% sure that algorithm they use for generating prices changing in time.

**Comment by overwatch873** [comment]
> Volatility indexes has nothing to do with volatility. These are randomly generated prices and every pair can be stable and less stable at some time. No one can predict it and I'm 100% sure that algorithm they use for generating prices changing in time.

Thanks mate
