### ISSUE TITLE
BOT REQUEST

### ISSUE THREAD

**Issue by NEWBIE3232** [binary-com/binary-bot#2899]
HELLO
PLEASE I NEED A BOT THAT ANALYSIS THE LAST 20 TICKS OF THE MARKET
E.G THE BOT SHOULD CHECK IF THE NUMBER OF RISE(UP) TICKS ARE MORE THAN THAT OF THE FALL TICKS THEN IT SHOULD PURCHASE FALL
THAT IS THE BOT SHOULD COUNT THE LAST 20 TICKS AND SEE IF ITS THE RISE OR THE FALL THAT HAS THE HIGHEST RATIO AND THEN IT SHOULD TAKE THE OPPOSITE DIRECTION.
.
@saidforex26

**Comment by saidforex26** [comment]
I have the indicator. maybe you can explain it better

**Comment by NEWBIE3232** [comment]
that is the bot should make a list of the last 20 ticks,( rise and fall directions)
then the bot should purchase a trade with.
i.e
if in the last 20ticks, the number or occurance of rise ticks is more than that of the fall thicks then purcahse fall 5ticks
.
@saidforex26

**Comment by overwatch873** [comment]
have you  it tried manually perhaps using a tick reader.....whats the win ratio of that strategy

**Comment by NEWBIE3232** [comment]
@overwatch873 
.
80% success rate

**Comment by trident2005** [comment]
This is a tick-picker or tick average calculator, it does not have a 80% success rate, when you get this automated you will see
