### ISSUE TITLE
I want to know if it is possible to add a strategy to the bot

### ISSUE THREAD

**Issue by elielson00x** [binary-com/binary-bot#2902]
Hello, I hope you're okay
I want to know if you can develop a configuration in a bot 

Running 1 tick
If 4 consecutive losses, Then wait 45 seconds for next operation 

Thank you
Wedge

**Comment by overwatch873** [comment]
Yeah its very possible ...though you didnt specify the type of bot or strategy you wanna develop

**Comment by elielson00x** [comment]
Ok I will bring the configuration

**Comment by elielson00x** [comment]
Bot for Binary
Even or odd opção de trade

Martingale Level and factor set

Bot trade  synthetic index, Preferably the 50 index 


With entries from 1 tick
When there is 3 consecutive loss the bot gives a delay of 46 seconds for the next purchase
Other settings can be defaults for a conventional bot 


Thankful.

Wedge

**Comment by elielson00x** [comment]
> Sim, é muito possível ... embora você não tenha especificado o tipo de bot ou estratégia que deseja desenvolver

Do you develop?
