### ISSUE TITLE
Using absolute barrier values in higher/lower bots

### ISSUE THREAD

**Issue by luizmlo** [binary-com/binary-bot#2904]
So, when dealing with the barrier for higher/lower contracts, is there a way to update the value when using the absolute type?

I've been using a strategy manually that works really well for some weeks now, but I can't make it work because I can't update the barrier value later on, what I need is to update it before each trade, in a way that I can always have the barrier 700pts (RS_75) above or under the price, to enter in the safest way. Is there a way to do it? To call the trade options during execution?

**Comment by trident2005** [comment]
You need to put all strategy in the 1 block using loops

**Comment by GreenB0t** [comment]
> You need to put all strategy in the 1 block using loops

Can you please explain more I'm having similar issues
