### ISSUE TITLE
Help creating bot following strategy, last digit appears between 0 and 4 for 4 times, it enters above 4

### ISSUE THREAD

**Issue by Leo520741** [binary-com/binary-bot#2908]
/

**Comment by daredude26** [comment]
How many ticks bro

**Comment by Leo520741** [comment]
> Quantos carrapatos bro

Only 1. Example: after 4 tick all between 0 and 4 he enters buying above 4

**Comment by whoisofumba** [comment]
Example;;

2
1
0
1
---------
Over 4

**Comment by Leo520741** [comment]
> É isso que você quer dizer??
Yes

**Comment by Leo520741** [comment]
> É isso que você quer dizer??

Yes

**Comment by argent1** [comment]
Hi
It is possible to create

argent1@centrum.sk


Ok

**Comment by IQBinary** [comment]
@Leo520741 
![View by IQBinary 2020 08 04 16_58_33](https://user-images.githubusercontent.com/54183297/89288745-c56c1780-d673-11ea-900c-6dfdf50cee27.jpg)
iqbinarybot@gmail.com

**Comment by argent1** [comment]
it can be a web application?
price: 299e
______________________________________________________________ 
> Od: "IQ Binary" <oznámenia@github.com>> 
Komu: "binary-com / binary-bot" <binary-bot@noreply.github.com 
>> Dátum: 04.08.2020 13:29 
> príkaz: Re: [binary-com / binary-bot] Pomôžte vytvoriť robota nasledujúcu stratégiu, posledná číslica sa objaví medzi 0 a 4 štyrikrát, zadá sa nad 4 (# 2908) 
>
 
@ Leo520741  <https://github.com/Leo520741>iqbinarybot@gmail.com <iqbinarybot@gmail.com>
  <https://user-images.githubusercontent.com/54183297/89288745-c56c1780-d673-11ea-900c-6dfdf50cee27.jpg>
  <iqbinarybot@gmail.com>
- 
Dostávate túto správu, pretože ste sa vyjadrili.

**Comment by argent1** [comment]
Are you interested?
 
Karl
______________________________________________________________ 
> Od: "IQ Binary" <oznámenia@github.com>> 
Komu: "binary-com / binary-bot" <binary-bot@noreply.github.com 
>> Dátum: 04.08.2020 13:29 
> príkaz: Re: [binary-com / binary-bot] Pomôžte vytvoriť robota nasledujúcu stratégiu, posledná číslica sa objaví medzi 0 a 4 štyrikrát, zadá sa nad 4 (# 2908) 
>
 
@ Leo520741  <https://github.com/Leo520741>iqbinarybot@gmail.com <iqbinarybot@gmail.com>
  <https://user-images.githubusercontent.com/54183297/89288745-c56c1780-d673-11ea-900c-6dfdf50cee27.jpg>
  <iqbinarybot@gmail.com>
- 
Dostávate túto správu, pretože ste sa vyjadrili.

**Comment by argent1** [comment]
Ok
299EUR
 
KArl
______________________________________________________________ 
> Od: "Aaron Imming" <oznámenia@github.com>> 
Komu: "binary-com / binary-bot" <binary-bot@noreply.github.com 
>> Dátum: 18.08.2020 03:45 
> príkaz: Re: [binary-com / binary-bot] Pomôžte vytvoriť robota nasledujúcu stratégiu, posledná číslica sa objaví medzi 0 a 4 štyrikrát, zadá sa nad 4 (# 2908) 
>
 
Zatvorené # 2908 <https://github.com/binary-com/binary-bot/issues/2908> .
- 
Dostávate túto správu, pretože ste sa vyjadrili.
