### ISSUE TITLE
Put-Call Strategy - Martingale

### ISSUE THREAD

**Issue by midnighttrade** [binary-com/binary-bot#2910]
Hi All

I need some help!! I have been playing with the attached strategy, the issue I have is when it gets to a big size trade it does not execute because it gives an error stating maximum payout is only 200. How can I change that so that the payout maximum is more??

Please and thank you

 
[Put - Call Strategy.txt](https://github.com/binary-com/binary-bot/files/4917383/Put.-.Call.Strategy.txt)

**Comment by nextnaro** [comment]
your bot dont have payout limit, 
only here also set to 918
![image](https://user-images.githubusercontent.com/31925501/87494863-a258d400-c682-11ea-8f2b-28f9b325c481.png)
may be checking 
![image](https://user-images.githubusercontent.com/31925501/87494933-c74d4700-c682-11ea-8df8-70ee23cffcb1.png)
