### ISSUE TITLE
i need binary bot read last 2 digits,color and  number add - Exmple - last digits 5,9 5-red 9-blue add purchase over  

### ISSUE THREAD

**Issue by channa2020** [binary-com/binary-bot#2911]

**Comment by argent1** [comment]
Hi
It is possible to create

argent1@centrum.sk


Ok

**Comment by argent1** [comment]
ok 299eur
______________________________________________________________ 
> Od: "channa2020" <oznámenia@github.com>> 
Komu: "binary-com / binary-bot" <binary-bot@noreply.github.com 
>> Dátum: 05.08.2020 10:34 
> Dátum: Re : [binárny-com / binárny-bot] Potrebujem binárny robot prečítať posledné 2 číslice, pridať farbu a číslo - Príklad - posledné číslice 5,9 5-červené 9-modré pridať nákup po (# 2911) 
>
 
Zatvorené # 2911 <https://github.com/binary-com/binary-bot/issues/2911> .
- 
Dostávate túto správu, pretože ste sa vyjadrili.
