### ISSUE TITLE
good strategy, plz help

### ISSUE THREAD

**Issue by mat3usmcd** [binary-com/binary-bot#2912]
Digits> Different

Every 5 tick ending 0
bet that the next number will not be 0

example:
tick 1 - xxxxx9
tick 2 - xxxxx0
tick 3 - xxxxx0
tick 4 - xxxxx0
tick 5 - xxxxx0
tick 6 - xxxxx0

here the robot would give an entry because five stick 0 appeared

in case of this loss, do martingale x11 after 100 seconds

could someone make an xml of this? I've been visualizing for 6 months, and a good strategy

**Comment by politecruise** [comment]
here check this out

[mat3usmcd bot.txt](https://github.com/binary-com/binary-bot/files/4928845/mat3usmcd.bot.txt)

**Comment by politecruise** [comment]
rename from txt to xml

**Comment by mat3usmcd** [comment]
> here check this out
> 
> [mat3usmcd bot.txt](https://github.com/binary-com/binary-bot/files/4928845/mat3usmcd.bot.txt)

wonderful, thank you

if not asking too much, you could add stops win / loss and martigale
