### ISSUE TITLE
For rebranding issue we can't use trading view volatility chart.Please solve this problem.

### ISSUE THREAD

**Issue by shfx0096** [binary-com/binary-bot#2913]

**Comment by sam-binary** [comment]
Hi @shfx0096 ,

We don't have a plan to add in the TradingView chart to DBot at the moment. As an alternative, you can visit  https://tradingview.binary.com/ while trading in Dbot. Happy Trading!

Regards,
Sam

**Comment by shfx0096** [comment]
Sorry to say , this link doesn't work.

> Hi @shfx0096 ,
> 
> We don't have a plan to add in the TradingView chart to DBot at the moment. As an alternative, you can visit https://tradingview.binary.com/ while trading in Dbot. Happy Trading!
> 
> Regards,
> Sam

Sorry to say , this link doesn't work. https://tradingview.binary.com/
