### ISSUE TITLE
 does anyone have the free DM Analyzer Digit Match?

### ISSUE THREAD

**Issue by Leo520741** [binary-com/binary-bot#2915]

**Comment by politecruise** [comment]
how does it work??

do you have a youtube link to it??

**Comment by Leo520741** [comment]
> como funciona??
> 
> você tem um link do youtube para ele?


I don't know how it works, I would like to learn, if someone can make it available.

**Comment by politecruise** [comment]
you must have seen it somewhere, if i see it in a video or something then i would proceed from there.

**Comment by Leo520741** [comment]
> você deve ter visto em algum lugar, se eu o vejo em um vídeo ou algo assim, eu continuaria a partir daí.

Sorry, it's your next link https://www.youtube.com/watch?v=h_X-u4_n7Xc
Seems like a good strategy
