### ISSUE TITLE
Change the duration of a trade at runtime

### ISSUE THREAD

**Issue by iospetrosky** [binary-com/binary-bot#2916]
I would like to set the duration of the trade based on this logic on a 5 minute candle.

In the "watch and purchase" cycle I monitor the price and when certain conditions are met I want to enter a trade for the remaining duration of the candle.
Even if I use a variable to set the duration like in this picture

![image](https://user-images.githubusercontent.com/10598137/87687992-4ffcdd80-c77e-11ea-8357-64c2bfbcfc15.png)

if I change the value of "dyn_duration" before the Trade command, I get a trade of the duration of the value that was set when the bot started (which is the only place where you can define the parameters of the trade).

Is there a way to somehow refresh those values set at startup and get what I need?

Thanks

LP.

**Comment by nextnaro** [comment]
![image](https://user-images.githubusercontent.com/31925501/87775681-11882100-c859-11ea-9113-0e6ec9f52c83.png)
follow this! if i understand currently.

**Comment by iospetrosky** [comment]
Yes
Let's say that I'm monitoring a chart with 5 minutes candles.
When there are still 156 seconds to the end of the candle (I already have the algorithm get this value) I want to enter a trade with a specific amount of money (this works because you can apply a martingale) AND a duration of 156 seconds.

What happens now is this
I change the value in the variable dyn_duration
The trade is opened with the duration set when the bot started
Then the bot finds another good entry point (in a different candle)
I change the dyn_duration
The trade is opened with the PREVIOUS value (NOT the one set at the beginning)

So I guess there is some sort of re-initialize of the trade values when a trade is closed rather than BEFORE a trade is opened.

Any hint very appreciated

L.
