### ISSUE TITLE
binary odd even bot binary.com

### ISSUE THREAD

**Issue by kevinfer9696** [binary-com/binary-bot#2920]
I want to create a Last digit bot that goes for odd or even  everytime the Last Two Digits are equal.

For example:

tick 1 - xxxxx0
tick 2 - xxxxx5
tick 3 - xxxxx6
tick 4 - xxxxx6

We got two Last digit 6 in a row, so we should Set OP to EVEN

How to get this tick list, and everytime we get 2 Last digits in a row, we set the prediction to this Last Digit and go ODD OR EVEN??

**Comment by kevinfer9696** [comment]
no body wants to be in profit ???

**Comment by murali139** [comment]
means 5th tick even? or please tell correct info

**Comment by IQBinary** [comment]
@kevinfer9696 
![View by IQBinary 2020 08 02 18_32_58](https://user-images.githubusercontent.com/54183297/89123707-04bd2b80-d4ef-11ea-8c28-75963c8086dd.jpg)
iqbinarybot@gmail.com

**Comment by IQBinary** [comment]
@kevinfer9696 
![View by IQBinary 2020 08 02 19_00_17](https://user-images.githubusercontent.com/54183297/89124181-a5611a80-d4f2-11ea-97e1-d39e5aed2833.jpg)
iqbinarybot@gmail.com

**Comment by kevinfer9696** [comment]
Can send ir to me?
