### ISSUE TITLE
Dbot can disable auto reload when new version available? 

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2926]
![image](https://user-images.githubusercontent.com/31925501/88134674-cf276100-cc17-11ea-8b5e-b6d0d758447f.png)
Dbot forced to reload page when new version update, 
possible just only notify, and update on next login or after stop bot?

**Comment by aaron-binary** [comment]
Hey @nextnaro,

We're working on disabling this when the bot is running.

Sorry for that!

Regards,
Aaron
