### ISSUE TITLE
Last 2 digits 

### ISSUE THREAD

**Issue by shafikgh** [binary-com/binary-bot#2928]
Hello
I need help to have control on the last 2 digits in the same last tick.

Ex: last tick is 1654,35
I need to define if last digit =5 and the digit before last digit =3  do sell or buy
All that in the same last tick. 

Thanks a lot.

**Comment by IQBinary** [comment]
@shafikgh 
![View by IQBinary 2020 08 02 19_26_20](https://user-images.githubusercontent.com/54183297/89124665-5c12ca00-d4f6-11ea-9428-eb75bd4814e1.jpg)
iqbinarybot@gmail.com

**Comment by shafikgh** [comment]
Thank you so much 
I will try it

**Comment by shafikgh** [comment]
> @shafikgh
> ![View by IQBinary 2020 08 02 19_26_20](https://user-images.githubusercontent.com/54183297/89124665-5c12ca00-d4f6-11ea-9428-eb75bd4814e1.jpg)
> [iqbinarybot@gmail.com](mailto:iqbinarybot@gmail.com)

Thanks man
 but i couldn't make it in IF condition :( 

Could you please merg it with IF condition 
So it will be : 
IF last two digits are 99 ( for example )
DO call 

Thanks a lot :)
