### ISSUE TITLE
Restart Bot after 4 consecutive losses

### ISSUE THREAD

**Issue by Adatzzu** [binary-com/binary-bot#2929]
Hello Team, I'm working on a bot with Martingale strategy (increasing the stake after a loss). And I'm wondering if it is possible to make the bot to restart with the initial stake after 4 consecutive losses and having to wait 15 minutes in order to submit a new operation in the market, for eg.,My initial stake is $1 and the the stake doubles after every loss. So, if there are 4 consecutive losses, I would be losing $1, $2, $4 and $8. Is it possible to stop the bot after 4 consecutive losses and freshly restart automatically after 15 minutes with a $1 stake rather than continuing with $16, $32 etc.,? Just wanted to do this to minimize losses when the market is fluctuating heavily. Cheers.

PD: I know there is a old ticket #2593  with this request, but since it's already close I cannot comment or share my bot in order to get a hand with my case because the way me and my partner configurate the bot is different from the solution proposed, thanks.

_Here is the screenshots of the bot:_
![Bot 1 -Define your trade](https://user-images.githubusercontent.com/68701507/88308884-348c5800-ccd3-11ea-86aa-0c3b4151457a.png)
![Bot 4 -Get your trade result](https://user-images.githubusercontent.com/68701507/88308889-36eeb200-ccd3-11ea-9206-9d87ff2ea325.png)

**Comment by deja12** [comment]
![help](https://user-images.githubusercontent.com/17170020/88636866-e7452780-d0d2-11ea-80f8-fa6a4fd70d3b.png)


use maxLossSequence
and then use 900 seconds for 15 minute
set initial amount  to win amount

Hope it helps

**Comment by IQBinary** [comment]
![View by IQBinary 2020 08 01 12_48_59](https://user-images.githubusercontent.com/54183297/89096599-70bb6900-d3f5-11ea-9d36-acce936bdd80.jpg)
iqbinarybot@gmail.com
