### ISSUE TITLE
Dbot feature request List, Text elements reOrder, and custom function parameter? 

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2930]
![image](https://user-images.githubusercontent.com/31925501/88459107-45042480-cec5-11ea-895b-fa07e663b3d1.png)
Under Text or List unable to reorder only just add and delete Possible to reorder?
and under custom function 
![image](https://user-images.githubusercontent.com/31925501/88459139-a5936180-cec5-11ea-8088-69bc200c9a82.png)
after parameter added unable to rename or remove possible to update on this also?

**Comment by trident2005** [comment]
The issue about editing custom functions was raised by me in the official dbot thread and so far they have not solved that problem.

Dbot is not a replacement for now and it is far from being a replacement for binary.bot

https://github.com/binary-com/binary-bot/issues/2146

**Comment by nextnaro** [comment]
good to hear that issue was raised , all my bot migrated to dbot.

**Comment by aaron-binary** [comment]
Hey @trident2005 and @nextnaro,

Those are good ideas. We'll discuss this internally and work on adding this.

Regards,
Aaron
