### ISSUE TITLE
Binary bot 2

### ISSUE THREAD

**Issue by onahpaulinho360** [binary-com/binary-bot#2932]
How do i set my bot to make two two repitition like: CALL, CALL, PUT, PUT and vice versa? Thanks in advance.

**Comment by IQBinary** [comment]
iqbinarybot@gmail.com

**Comment by onahpaulinho360** [comment]
Please i authored the thread on github today about CALL,CALL and PUT, PUT
option and u drop ur email.

**Comment by onahpaulinho360** [comment]
> ![screenshot-bot binary com-2020 07 31-17_23_07](https://user-images.githubusercontent.com/54183297/89032711-e4586a00-d352-11ea-8a0e-0e2ea9932600.png)
> 
> [iqbinarybot@gmail.com](mailto:iqbinarybot@gmail.com)

I have tried it using  this set up  you  gave me but the bot did not work at all.

**Comment by IQBinary** [comment]
@onahpaulinho360 
it's working ok
![View by IQBinary 2020 08 05 00_35_15](https://user-images.githubusercontent.com/54183297/89334137-b1480a80-d6b3-11ea-8889-12bc6632bb46.jpg)
iqbinarybot@gmail.com

**Comment by onahpaulinho360** [comment]
> @onahpaulinho360
> it's working ok
> ![View by IQBinary 2020 08 05 00_35_15](https://user-images.githubusercontent.com/54183297/89334137-b1480a80-d6b3-11ea-8889-12bc6632bb46.jpg)
> [iqbinarybot@gmail.com](mailto:iqbinarybot@gmail.com)

![Screenshot_20200805-073908](https://user-images.githubusercontent.com/67044970/89380226-140ac780-d6ef-11ea-8d99-6351f3c32cd4.png)
Thank you so much it's working but stops after making for RUNS.

**Comment by onahpaulinho360** [comment]
Yeah it's working but it stops after making 4 trades.

**Comment by onahpaulinho360** [comment]
> if you still want

Please i still need your help i want it to make more trades.

**Comment by HOANGDUYTR** [comment]
If you need to edit bot or write a new one I can help

Vào Th 2, 24 thg 8, 2020 vào lúc 23:55 onahpaulinho360 <
notifications@github.com> đã viết:

**Comment by onahpaulinho360** [comment]
Ok I want you to help me to build a bot that work like this: the trade type
should be rise and fall, if the trade lose a position it should start
working like this CAll, CAll, PUT, PUT, CALL, CALL, PUT, PUT until it reach
a winning position if the last winning position is CALL it should start
trading in that direction or else PUT it should start trading in direction
PUT, Thank you in advance.
