### ISSUE TITLE
Butuh Investor sekitar $50-$100 untuk jalankan formula BOT Binary Ane. Yang mau Monggo coment... 

### ISSUE THREAD

**Issue by GATB16** [binary-com/binary-bot#2934]
![Screenshot_39](https://user-images.githubusercontent.com/68894516/88665600-1080aa80-d109-11ea-846b-6497ff11e44a.jpg)
![Screenshot_40](https://user-images.githubusercontent.com/68894516/88665708-3f971c00-d109-11ea-9534-3cf63a622292.jpg)

**Comment by saidforex26** [comment]
RF atau digit

**Comment by GATB16** [comment]
digit bos....

**Comment by GATB16** [comment]
minat tele 
https://t.me/Deblo

**Comment by saidforex26** [comment]
vtrc .  jika mengunkan rf munkin orang akan bermint. tpi itu hanya strategi differs..

**Comment by GATB16** [comment]
klo RF banyak yang minat ya...? iya saya baru bikin buat Digit....
