### ISSUE TITLE
Trying to open a position with my whole balance when I get two consecutive loses

### ISSUE THREAD

**Issue by Blakbard** [binary-com/binary-bot#2936]
I'm trying a bot where it opens a position with my whole balance if it records two consecutive loses. I have not been able to achieve this.![image](https://user-images.githubusercontent.com/53714361/88933893-e13c7b80-d277-11ea-96c7-b36fd63406e6.jpeg)

**Comment by IQBinary** [comment]
![screenshot-bot binary com-2020 07 31-17_23_07](https://user-images.githubusercontent.com/54183297/89035922-63e93780-d359-11ea-8117-78290179d4d2.png)
iqbinarybot@gmail.com

**Comment by IQBinary** [comment]
![screenshot-bot binary com-2020 07 31-18_14_48](https://user-images.githubusercontent.com/54183297/89036161-cf330980-d359-11ea-9947-585570cc46e6.png)
iqbinarybot@gmail.com

**Comment by Blakbard** [comment]
Man you're a legend.
