### ISSUE TITLE
RESTART BOT

### ISSUE THREAD

**Issue by allensilvaa** [binary-com/binary-bot#2937]
PERSONAL SPEAK ALL WELL? , I HAVE A BOT HERE WHICH I WOULD LIKE IT TO RESET AFTER ARRIVING AT THE 3 SERIES COUNT, SOMEONE KNOWS THE Q I SHOULD DO TO PERFORM THIS RESET AS SOON AS REACHING THE VARIABLE SERUM COUNT 3.
![1](https://user-images.githubusercontent.com/53317636/88971490-5d3fbf00-d28a-11ea-8799-83878b37612b.jpg)
![2](https://user-images.githubusercontent.com/53317636/88971505-64ff6380-d28a-11ea-903d-fee028b4393c.jpg)

**Comment by IQBinary** [comment]
iqbinarybot@gmail.com

**Comment by loigaak** [comment]
send gmail: hoangvanloi1166@gmail.com im fix now
