### ISSUE TITLE
1 tick odd strategy 

### ISSUE THREAD

**Issue by Simo-912** [binary-com/binary-bot#2938]
Hi guys,
Please help me to create a simple bot....if the last digit=0 purchase odd 1 tick
And please dont forget martingale...please guys help 🐸🙏

**Comment by IQBinary** [comment]
![View by IQBinary 2020 08 01 11_42_50 1 tick odd strategy #2938](https://user-images.githubusercontent.com/54183297/89095502-44e7b580-d3ec-11ea-90b5-8683bd914c20.jpg)
iqbinarybot@gmail.com

**Comment by Simo-912** [comment]
Thank you so much 💓💓

**Comment by Simo-912** [comment]
Please iqbinary can you send me the file
This is my email darrarm6@gmail.com

**Comment by Simo-912** [comment]
I mean xml 😅💓

**Comment by Simo-912** [comment]
Please Iq binary send me xml file
