### ISSUE TITLE
How to read Volatility 75 First Digits

### ISSUE THREAD

**Issue by channa2020** [binary-com/binary-bot#2939]
How to read Volatility 75 First Digits. E.x. - 513,879.4696 - i need to read 4 number Digits.
Please help me. look Screen Shot

**Comment by IQBinary** [comment]
![View by IQBinary 2020 08 01 14_54_58](https://user-images.githubusercontent.com/54183297/89098652-14614500-d407-11ea-8dc6-ce6e519461bf.jpg)
iqbinarybot@gmail.com

**Comment by channa2020** [comment]
> ![View by IQBinary 2020 08 01 14_54_58](https://user-images.githubusercontent.com/54183297/89098652-14614500-d407-11ea-8dc6-ce6e519461bf.jpg)
> [iqbinarybot@gmail.com](mailto:iqbinarybot@gmail.com)

Thank You So Much Support i Create it
