### ISSUE TITLE
 the bot stops at losses

### ISSUE THREAD

**Issue by makebos** [binary-com/binary-bot#2942]
Hello
the bot I have stops when it has losses, I want it to continue trading
It works with martingale, I would like it to restart

thank you
[[Binary Bot Pro] Fast Odd x Even Strategy (26-Jul-2020).zip](https://github.com/binary-com/binary-bot/files/5019410/Binary.Bot.Pro.Fast.Odd.x.Even.Strategy.26-Jul-2020.zip)

**Comment by IQBinary** [comment]
@makebos 
Yes, it can possible but with which condition or continue as usual whatever you lost.
iqbinarybot@gmail.com
