### ISSUE TITLE
Dbot:: run after block always disable after load block must enable by manually every time.

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2943]
"Run after" block always disable after load and  block must enable by manually every time.
![image](https://user-images.githubusercontent.com/31925501/89243698-2d503d00-d637-11ea-8894-6ed348c3f0e9.png)

**Comment by aaron-binary** [comment]
Hey @nextnaro,

Let us look into this, that doesn't look right.

Regards,
Aaron
