### ISSUE TITLE
LDP - consecutive 3 same last digits - Differ

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2946]
Hi All,

Good Day. I tried to create a digit differ bot where the bot would predict that the last digit would differ if 3 consecutive ticks had the same last digit. 

It seemed to work ok. But, I tried to compare the results with the raw data obtained from the Binary MT5 app / software. It looked like there were many instances where three consecutive ticks had the same last digit but the bot had not placed bets in all those instances. 

I have attached the bot here. Is it possible for someone to tell me why bets were not placed in all the instances and are there any specific criteria under which the bot placed bets?
[LDP 3.zip](https://github.com/binary-com/binary-bot/files/5036962/LDP.3.zip)

Thanks

**Comment by rhissan** [comment]
Here it goes 
[diff3.zip](https://github.com/binary-com/binary-bot/files/5037489/diff3.zip)

**Comment by rhissan** [comment]
That loop that you did is unecessary and probably this was the cause, this is a very simple bot but ir rarely worth it...

**Comment by binarybotbegginer** [comment]
> That loop that you did is unecessary and probably this was the cause, this is a very simple bot but ir rarely worth it...

Hi,

Thanks for your response. Is it possible to tell what impact does the loop exactly have on the bot i.e., how is it missing more than hundred betting opportunities? Does the "run after 1 second" cause  a delay in placing bets?

Thanks

**Comment by Kosta92** [comment]
Just so you know, Binary Bot and their MT5 software are using different trading charts. That's why you saw consecutive digits in MT5, but they probably weren't there in Binary Bot.
