### ISSUE TITLE
Best Binary Touch Bot

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2952]
https://youtu.be/VvzPCGJIKk4

**Comment by aaron-binary** [comment]
Hi @virtusasys,

We love the open sharing of knowledge, but we don't encourage advertising and selling your applications here. This repository is used to help others, report issues, request new features, etc.

We hope to provide another channel for these kind of discussions soon. In the meantime, If you'd like to sell your application in our shop, you can find out more here: https://shop.binary.com/pages/sell-your-products-on-binary-com-shop-today.

You can also contact marketing@binary.com to learn more about partnership options.
