### ISSUE TITLE
i need last digit 3 come purchase Differs and last 2 digits Come Purchase Differ 

### ISSUE THREAD

**Issue by channa2020** [binary-com/binary-bot#2957]
i need last digit 3 come purchase Differs and last 2 digits Come Purchase Differ 
E.X -
1456.23 - last Digit 3 - Purchase Differ
1456.23 / 1457.23  - last Digits 3,3 - purchase Differs
1456.23 / 1457.23 / 1456..23 - last Digits 3,3,3 - purchase Differs
Thank you

**Comment by binief** [comment]
[3 consecutive ticks same last digit (copy).txt](https://github.com/binary-com/binary-bot/files/5075492/3.consecutive.ticks.same.last.digit.copy.txt)

**Comment by murali139** [comment]
thank you bro, god bless you

**Comment by channa2020** [comment]
> [3 consecutive ticks same last digit (copy).txt](https://github.com/binary-com/binary-bot/files/5075492/3.consecutive.ticks.same.last.digit.copy.txt)

please give me xml file sir

**Comment by binief** [comment]
Rename it to .xml

**Comment by channa2020** [comment]
> Rename it to .xml

Thank you so much
