### ISSUE TITLE
Historical Data - Daily Reset Indices

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#2962]
Hi All,

Good Day. Can anyone please tell me whether it is possible to get historical data for the Daily Reset Indices (Bull Market Index and Bear Market Index)?

I am aware that we can get historical data for Continuous Indices (Volatility 10, Volatility 100 etc.,) from the Binary MT5 app. I am not able to find the data for Daily Reset Indices.

Thanks

**Comment by aaron-binary** [comment]
Hey @binarybotbegginer,

You can get historical data for all our symbols. Please check https://webtrader.binary.com/

Regards,
Aaron

**Comment by binarybotbegginer** [comment]
> Hey @binarybotbegginer,
> 
> You can get historical data for all our symbols. Please check https://webtrader.binary.com/
> 
> Regards, Aaron

Hi @aaimio,

Thanks for your reply. Do we have a step by step guide to extract the historical data? Just asking as the link that you provided leads to a standard binary.com page.

Thanks

**Comment by IQBinary** [comment]
@binarybotbegginer 
![screenshot-webtrader binary com-2021 11 01-04_03_13](https://user-images.githubusercontent.com/54183297/139603391-5be0fd85-7119-4b50-b200-8de90ccec13b.png)

**Comment by binarybotbegginer** [comment]
> @binarybotbegginer ![screenshot-webtrader binary com-2021 11 01-04_03_13](https://user-images.githubusercontent.com/54183297/139603391-5be0fd85-7119-4b50-b200-8de90ccec13b.png)

Thanks a lot for this. I see that we can get only an hour's worth of data exported to excel (I might be wrong). Can we get for a longer period (like an entire day)?

Thanks in advance.
