### ISSUE TITLE
Binary bot odd even

### ISSUE THREAD

**Issue by inspiredsam** [binary-com/binary-bot#2965]
Hello  @aaron-binary @sysadmin-frontend-binary @afshinpaydar-binary @aminmarashi-binary @jy-binary @anton-binary @sam-binary @torsten-binary @negar-binary @msamprz @mahdipourziaei-binary @arun-binary @kelly-binary @Fruitfella
Please I need someone to help me create this binary bot trading strategy

Trade 1: Even Even 

Trade 2: Odd 

Trade 3: Even 

Trade 4: Odd Odd 

Trade 5: Even

Trade 6: Odd 

Trade 7: Even Even 

Trade 8: Odd Odd 

Trade 9: Even 

Trade 10: Odd 

Restart from Trade 1 again

With martingale and take profit

**Comment by Kosta92** [comment]
I have tried the same strategy (and with PUT/CALL options), but as all other "strategies" based on pure luck, this one also fails after some time.
