### ISSUE TITLE
Binary bot trading using API

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#2976]
Hi guys,

Please feel free to check out my trading applications using the binarydotcom API. It builds on the CLI bot on here and offers a load GUI features etc

It's FREE to use and always will be!

Https://binarybottrading.eu 

New video tutorial under the knowledge menu to help new users.

Cheers,

Will

**Comment by nobleb2007** [comment]
Nice concept but it is only trading rise and fall only. What of other market. 

The graphics aspect as consume a lot of space making it difficult to view you winning and trading history. My observation

**Comment by Jacques0106** [comment]
there isnt any attached files on the above link
