### ISSUE TITLE
Periods longer than data length

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2977]
I'm trying to set up a MACD+EMA bot on Forex markets and I'm getting the error: **Periods longer than data length**.

My setup is MACD 12, 26, 9 and EMA 200.

Why is this happening?
Why isn't the data length as long as in Synthetic Indices?
What are the limits?

**Comment by aaron-binary** [comment]
Hey @Kosta92,

Could you share your strategy? Then we could investigate what's happening here.

Thanks!
Aaron

**Comment by hotmatrixx** [comment]
are you using or reading from an array or list anywhere else in your strategy? including a candles list?
