### ISSUE TITLE
question

### ISSUE THREAD

**Issue by HOANGDUYTR** [binary-com/binary-bot#2978]
Who can explain for me what rsi array is?

**Comment by Kosta92** [comment]
It's simple.

RSI gives you only the latest value of a tick or a candle:

![RSI](https://user-images.githubusercontent.com/11698414/91060518-5ad34980-e62b-11ea-8b97-90b02b66f287.png)

RSI Array gives you the list of all previous values:

![RSI Array](https://user-images.githubusercontent.com/11698414/91060582-6de61980-e62b-11ea-9f8f-84c9b579bafd.png)

You can take any value from the list for your function, for example:

![RSI Array (3 last values)](https://user-images.githubusercontent.com/11698414/91060723-94a45000-e62b-11ea-96e3-83eefdec5902.png)

Here is the example of all of those combined with the lastest value marked with a circle:

![RSI all](https://user-images.githubusercontent.com/11698414/91061340-5a877e00-e62c-11ea-85d6-e5e537972131.png)

**Comment by HOANGDUYTR** [comment]
thank so much guy


Vào Th 2, 24 thg 8, 2020 vào lúc 22:09 Kosta92 <notifications@github.com>
đã viết:
