### ISSUE TITLE
Differ Digit bot

### ISSUE THREAD

**Issue by MattKimbel** [binary-com/binary-bot#2979]
Why does it happen that after several means to set prediction to last digits it's always just going random.

**Comment by MattKimbel** [comment]
@sam-binary @aaron-binary 
Please help me with an accurate last digits block sirs thanks.

**Comment by aaron-binary** [comment]
Hey @MattKimbel,

Could you describe the issue that's happening in more detail?

Regards,
Aaron

**Comment by MattKimbel** [comment]
I select prediction to last digit but it's always just going random

**Comment by MattKimbel** [comment]
![20200827-064302](https://user-images.githubusercontent.com/60224839/91389285-e79b2480-e830-11ea-8250-bb0c9ebaf64a.png)
Am I making a mistake?

**Comment by MattKimbel** [comment]
@aaron-binary

**Comment by aaron-binary** [comment]
@MattKimbel,

The `set predict to Last Digit` is only executed once at the start, after that it'll constantly reflect the same value (I assume based on the screenshot you've provided). To fix this, you can move the `set predict to Last Digit` to the `Define Trade Options` statement/scope.

Hope that helps!
Aaron
