### ISSUE TITLE
Important Question 

### ISSUE THREAD

**Issue by MattKimbel** [binary-com/binary-bot#2981]
Can someone actually make profits consistently with digit differ using $100

Honest Opinions pls

**Comment by Joshbinary** [comment]
@MattKimbel if you are looking to make money via binary bot using digits with 100 bucks
Then there is only 1 way

**Comment by MattKimbel** [comment]
@Joshbinary Pls I'd like to know

**Comment by Joshbinary** [comment]
@MattKimbel Unfortunately I can't send you the bot I'll only tell u
It's using Matches 
Apparently you'll need a hundred steps martingale 
But it's within your 100$ capital 

Hope that helps Good luck.

**Comment by MattKimbel** [comment]
Thanks very much I'll look into it with my team 
And I'll get back to you sir.  Thank you.

**Comment by Joshbinary** [comment]
You are most welcome.

**Comment by trident2005** [comment]
No, is almost imposible be consistent with DIFFERS contracts.

**Comment by Glexmoney** [comment]
Binary trading is like playing roullete, its pure casino !! and no one can beat the casino

**Comment by hotmatrixx** [comment]
> 
> 
> Can someone actually make profits consistently with digit differ using $100
> 
> Honest Opinions pls

Digit Differ are fake. They are computer controlled, and supposedly 'random', the computer knows your 'bid' long before closing, so could potentially manipulate the outcome - change a number to take all your money.

They ARE fake. They are only available on "Synthetic" indices - Synthetic Indices are 'simulated stocks' that are computer AI controlled to simulate the appearance of real Forex or Stock movements.
