### ISSUE TITLE
add losses

### ISSUE THREAD

**Issue by claytonliotti** [binary-com/binary-bot#2982]
hello how do i add the losses when followed to recover in martingale
adding the two losses 1.75 but only recovered 1.28

![image](https://user-images.githubusercontent.com/44580787/91507019-0e497180-e8aa-11ea-9ae0-4548ee75419c.png)

**Comment by hotmatrixx** [comment]
you need to divide your losses by the current payout to get the 'correct' number to recover.

**Comment by claytonliotti** [comment]
makes sense, so I didn't understand how I'm going to put this on the bot
