### ISSUE TITLE
bot LDP worm color

### ISSUE THREAD

**Issue by pao11901** [binary-com/binary-bot#2984]
hi.
I have a strategy for binary, if somebody could help me program it I would appreciate it very much ..
it is like this:
I analyze the volatility index 100 (1s) the last digit.
I analyze a sequence of 5 digits, the first digit must be even and the color of the worm's head must have been blue, the second and third must be red odd numbers and the worm's head must have been green, also the second digit it must be greater than the first digit, the fourth and fifth must be even blue and the fifth must be greater than the fourth.
example:
4blue 5red 3red 2blue 6blue bet down
bet down.
thank you very much
![image](https://user-images.githubusercontent.com/46610874/92009732-8e3e6400-ed0e-11ea-8f12-11acbd8e7e92.png)

**Comment by Uchandjr** [comment]
![20200904_010607](https://user-images.githubusercontent.com/59737653/92145494-e1b5cc80-ee4a-11ea-980a-fafbb41f9ae2.jpg)

Like this, right?

**Comment by pao11901** [comment]
hi. yes, something like that.
analyzing: 4 Blue | 5 Red | 3 Red | 2 Blue | 6 Blue || even | odd | odd | even | even || worm head | blue | green | green | green | green ||
bet Down!!

**Comment by cleberscr** [comment]
does this work to call too?

**Comment by cleberscr** [comment]
and that's profitable?

**Comment by IQBinary** [comment]
@pao11901 
![IQ Binary - (bot binary com)(2020 10 02_12_31_22)](https://user-images.githubusercontent.com/54183297/94896504-40eb1900-04ab-11eb-892a-7b9ce255df8f.jpg)
iqbinarybot@gmail.com
