### ISSUE TITLE
Most stable profit strategy

### ISSUE THREAD

**Issue by rgoncalves** [binary-com/binary-bot#299]
Hi all,

does anybody can share a strategy that give a long term stable profit?

Thanks
BR

**Comment by okovalov** [comment]
![image](https://user-images.githubusercontent.com/1706749/27915446-63c1c702-6234-11e7-9c12-8d543d361c6b.png)
:)

**Comment by Fruitfella** [comment]
:rofl:  dunno why but i really laugh seeing @okovalov 's comment :rofl:

**Comment by sarderiftekhar** [comment]
Stop dreaming about it, no matter whatever strategy you put on. Binary will never let you win.

**Comment by Timmyb11** [comment]
thats a lie...i have been with them for a year now... you have to learn first and learn how to make little profit daily not much 10% of your capital profit is okay in a day

**Comment by rgoncalves** [comment]
Hi @Timmyb11, can you share how you do a little profit every day?

Thanks a lot

**Comment by Timmyb11** [comment]
@rgoncalves , yes i can but not for free... i don't charge money but you have to be my affiliate and deposit before i share you the strategy.... because am very sure of my strategy and if am to sell i will sell it for at least $3000 so i always use affiliate as a medium to share my strategy and i collect commission from binary.com when you make profits.... if you can do that then be ready to hit big soon with patients

**Comment by sarderiftekhar** [comment]
Timmyb11,

For your information, you cannot make money if your affiliate make profits.
Only if he makes a loss you get commission.

I have proof for that.

**Comment by Timmyb11** [comment]
really? that;s a big a lie stop spoiling the company name if you loss your money... remember you get commission on the total monthly profit.... and if your affiliate did't make profit at the end of the month you will wont get commission.... binary.com is not a place where you trade while in a hurry to make money... you make money little... i have friends trading with them for two years now also... don;t know why you taking like this...

**Comment by aminmarashi** [comment]
If anyone is interested in earning money from their strategies or bots, please feel free to talk to marketing@binary.com for further assistance.

**Comment by sarderiftekhar** [comment]
Dear Timmy,

Look at your affiliate account carefully. If any of your affiliate makes
profit your commission goes minus. That means negative balance. Look again.

**Comment by Timmyb11** [comment]
thats not real bro, i have clients that makes profit and i make profit in my affiliate

**Comment by aminmarashi** [comment]
Sorry, I had to delete the above conversation. Please keep github issues for coding purposes only.

**Comment by bigmantrader** [comment]
> If anyone is interested in earning money from their strategies or bots, please feel free to talk to [marketing@binary.com](mailto:marketing@binary.com) for further assistance.

I have a bot for sale to make money from but it needs a little modification. I think my bot is worth $250 . can you help me out if I write the marketing @ binary

**Comment by murali139** [comment]
bro if you send bot history(bot log) of 7 days then i trust it.
if you do it without martingale i appreciate you.

**Comment by bigmantrader** [comment]
> bro if you send bot history(bot log) of 7 days then i trust it. if you do it without martingale i appreciate you.
> […](#)
> On 20/02/2019, bigmantrader ***@***.***> wrote: > If anyone is interested in earning money from their strategies or bots, > please feel free to talk to > ***@***.******@***.***) for further > assistance. I have a bot for sale to make money from but it needs a little modification. I think my bot is worth $250 . can you help me out if I write the marketing @ binary -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#299 (comment)](https://github.com/binary-com/binary-bot/issues/299#issuecomment-465570101)

write to my email address tjcomputerinstitute@gmail.com and we can chat on whatsapp.
