### ISSUE TITLE
Digit Bot

### ISSUE THREAD

**Issue by Braxton-Lee** [binary-com/binary-bot#2992]
Greetings 

Please help

When the last digit is zero that's the only time the digit diff bot lose.

Please help with the settings.
[New Compressed (zipped) Folder.zip](https://github.com/binary-com/binary-bot/files/5178916/New.Compressed.zipped.Folder.zip)

**Comment by cleberscr** [comment]
just to encourage you
[digit 0.zip](https://github.com/binary-com/binary-bot/files/5279277/digit.0.zip)

**Comment by Braxton-Lee** [comment]
Good day, Thank you for your help.

Thank you for your help. The bot is still losing on digit 0 consecutively. Im so caught up, i just need a bot that can help get me out of debt corona has put me in.

**Comment by cleberscr** [comment]
> Good day, Thank you for your help.
> 
> Thank you for your help. The bot is still losing on digit 0 consecutively. Im so caught up, i just need a bot that can help get me out of debt corona has put me in.

if you want to make money with binary bot. a digit bot above 0 is not the option, try a Call and Put, Pair or Odd, or one of digits that is above 5 or below 6, that the trade profit is a good value
