### ISSUE TITLE
Daily Reset Indices missing?

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2993]
What happened to Daily Reset Indices? They are missing from both Binary bot and Deriv bot.

**Comment by aaron-binary** [comment]
Hey @Kosta92,

They're still there on my side. Could you confirm?

<img width="778" alt="Screenshot 2020-09-11 at 10 05 08" src="https://user-images.githubusercontent.com/44427668/92842552-47d7bc00-f416-11ea-8bd8-5dcd94b0010c.png">

Regards,
Aaron

**Comment by Kosta92** [comment]
They are back now.

You may close this ticket.
