### ISSUE TITLE
Digit Differ No Loss

### ISSUE THREAD

**Issue by Foxi-it** [binary-com/binary-bot#2996]
Is it actually possible get 100% win in Digit differ Binary Bot ?

If not he is a Scammer : https://www.youtube.com/watch?v=1MUMTKQutQM
Note: Don't buy bot from him. He cheated 20$ and sent only a Basic differ bot.

**Comment by trident2005** [comment]
Just by watching the video I know he is a scammer, he set up a real account number over a virtual account number

**Comment by Kosta92** [comment]
It's completely fake.
