### ISSUE TITLE
"Direction is"...

### ISSUE THREAD

**Issue by rgoncalves** [binary-com/binary-bot#300]
Hi all,

does anyone knows how can I use "Direction is" on tick analisys?

![image](https://user-images.githubusercontent.com/666184/27930963-6b86dca0-6290-11e7-9a81-13b26344ea66.png)

Thanks

**Comment by aminmarashi** [comment]
<img width="245" alt="screen shot 2017-07-07 at 8 34 56 am" src="https://user-images.githubusercontent.com/6560964/27938236-332fda0a-62ef-11e7-99ce-989e2bfa6beb.png">

Download here: [direction in tick analysis.xml.zip](https://github.com/binary-com/binary-bot/files/1129613/direction.in.tick.analysis.xml.zip)

**Comment by rgoncalves** [comment]
Thank you @aminmarashi
