### ISSUE TITLE
edit

### ISSUE THREAD

**Issue by dbot123** [binary-com/binary-bot#3001]

**Comment by rsrahoo123** [comment]
like this

![like this](https://user-images.githubusercontent.com/59532183/93031936-daeb3e80-f62e-11ea-92cc-db53f57082b1.png)

**Comment by rsrahoo123** [comment]
any one  have please put it in comment or  can created this please put the xml file in comment

**Comment by aakanksha2000** [comment]
send your email

**Comment by nobleb2007** [comment]
This is a very nice martingale strategy. Gurus in the house can help build this
@aminmarashi-binary @gokula-krishna-dev 
@alienfly

**Comment by rsrahoo123** [comment]
> aakanksha2000  
my email is:   idrissmili1@gmail.com
