### ISSUE TITLE
ATUALIZANDO O BOT

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3002]
_Olá a todos! tenho um bot muito bom mas queria saber se já tem como colocar a nova opção do **DERIV.COM**
adicionar a opção de x100 x200 x500 e x1000 se tiver alguém poderia explicar como adicionar no bot!!_
![image](https://user-images.githubusercontent.com/43180630/93352363-20fff800-f811-11ea-892d-e67f006928b6.png)

**Comment by carol-binary** [comment]
Olá contatodeanet! 

Nós não vamos implementar essa característica no Binary Bot. Isso sera sendo adicionada para a plataforma DBot em breve. Muito obrigada!

Atenciosamente,
Carol
