### ISSUE TITLE
Sell profit/loss block returning error 

### ISSUE THREAD

**Issue by garshom** [binary-com/binary-bot#3004]
Hello Team,

Same raised issue  this.data.get is not a function  #2997 is still coming, 

please take a look at this.

<img width="1102" alt="Screenshot 2020-09-18 at 14 40 09" src="https://user-images.githubusercontent.com/6675709/93595509-8e9e5680-f9c0-11ea-8624-72e1319de43c.png">

**Comment by carol-binary** [comment]
Hi @garshom,

We're working on a fix for this, we'll update you soon! 

Regards,
Carol

**Comment by garshom** [comment]
Any update on this issue guys..

**Comment by carol-binary** [comment]
This should be fixed now, @garshom!
