### ISSUE TITLE
Count the color of last n ticks?

### ISSUE THREAD

**Issue by linhvb** [binary-com/binary-bot#3011]
Dear Man

Could anyone help to change this code to count the color of last n tick?

[green.red.red.green.red.zip](https://github.com/binary-com/binary-bot/files/5267759/green.red.red.green.red.zip)

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/94166032-3dc7ab80-fe61-11ea-92c8-38c9367a99f5.png)
