### ISSUE TITLE
‌Bollinger Bands‌ and Moving Average

### ISSUE THREAD

**Issue by cleberscr** [binary-com/binary-bot#3012]
how do I know that the previous candle 3 of the bollinger bands (top, bottom or middle) and moving average is above or lower from the closing of the previous candle 2?

![image](https://user-images.githubusercontent.com/61013585/94169705-81241900-fe65-11ea-8c72-6cc91e40a27c.png)

**Comment by contatodeanet** [comment]
![image](https://user-images.githubusercontent.com/43180630/94172054-643d1500-fe68-11ea-89b8-21f820730e2d.png)

**Comment by cleberscr** [comment]
thanks buddy <3
