### ISSUE TITLE
Bot Only Ups / Only Downs gets stucked...

### ISSUE THREAD

**Issue by elpeter2020** [binary-com/binary-bot#3013]
@aaron-binary @aminmarashi-binary @Mahboobeh-binary

I have a problem with a simple bot (see in attached) it gets stucked forever since last days, could you help me guys?

Thank you

[BOT Only Ups - Only Downs (ambas plataformas) (1).zip](https://github.com/binary-com/binary-bot/files/5286679/BOT.Only.Ups.-.Only.Downs.ambas.plataformas.1.zip)

**Comment by aaron-binary** [comment]
Hey @elpeter2020,

Thank you for reporting this and sending through your strategy.

I've tested it and found an issue on our side which we'll address asap.

Regards,
Aaron

**Comment by aaron-binary** [comment]
Hey @elpeter2020,

We've released a fix for this, could you confirm whether or not you're still experiencing any difficulties with trading on our servers?

Regards,
Aaron
