### ISSUE TITLE
Indicador de volume

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3015]
Olá a todos! alguém teria algum indicador de volume para me adicionar ao meu bot???

**Comment by cleberscr** [comment]
ei mano, sou do brasil, mas quando for mandar algo aqui, ja manda traduzido, pq quem comanda aqui é so gringo kk
tem esse repositorio, n sei se vai te ajudar mano
https://github.com/binary-ex-machina/binary.com-bot/tree/master/indicators

**Comment by contatodeanet** [comment]
> ei mano, sou do brasil, mas quando for mandar algo aqui, ja manda traduzido, pq quem comanda aqui é so gringo kk
> tem esse repositorio, n sei se vai te ajudar mano
> https://github.com/binary-ex-machina/binary.com-bot/tree/master/indicators

Vlw @cleberscr , tenho um bot que trabalha bem 24hs usando fractal mas preciso de mais algum indicador pra aumentar a assertividade dele!!

**Comment by cleberscr** [comment]
> > ei mano, sou do brasil, mas quando for mandar algo aqui, ja manda traduzido, pq quem comanda aqui é so gringo kk
> > tem esse repositorio, n sei se vai te ajudar mano
> > https://github.com/binary-ex-machina/binary.com-bot/tree/master/indicators
> 
> Vlw @cleberscr , tenho um bot que trabalha bem 24hs usando fractal mas preciso de mais algum indicador pra aumentar a assertividade dele!!

Usa medias moveis e bandas de bollinger = filtro de tendencia
o fractal tem que ser o periodo 2 ou 3 (5 eu acho que n é tão bom não)
