### ISSUE TITLE
Please help, I'm just studying

### ISSUE THREAD

**Issue by Livandos** [binary-com/binary-bot#3017]
Please help, I'm just studying and i can't do it (
I need in a cycle (for example every 5 ticks) find amount change up and amount change down 
I will be very grateful )
<img width="132" alt="2020-09-23" src="https://user-images.githubusercontent.com/61840855/94527642-f6b22f80-023f-11eb-8d7d-fee790134b71.png">

**Comment by IQBinary** [comment]
@Livandos 
![IQ Binary - (bot binary com)(2020 10 02_11_57_02)](https://user-images.githubusercontent.com/54183297/94894230-91ac4300-04a6-11eb-8421-cf11bff570a2.jpg)
iqbinarybot@gmail.com

**Comment by Livandos** [comment]
> @Livandos
> ![IQ Binary - (bot binary com)(2020 10 02_11_57_02)](https://user-images.githubusercontent.com/54183297/94894230-91ac4300-04a6-11eb-8421-cf11bff570a2.jpg)
> [iqbinarybot@gmail.com](mailto:iqbinarybot@gmail.com)

Thank you!
