### ISSUE TITLE
High and Low (H & L) in trade chart

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#3018]
Hi. How are those High and Low points calculated?

![H   L](https://user-images.githubusercontent.com/11698414/94683518-f6d92a80-0326-11eb-8b68-f6216195fd37.png)

Are those Support and Resistance points?
If so, how can I replicate them in a bot?

**Comment by IQBinary** [comment]
@Kosta92 
It's not for support and resistance 
It's High and low tick from selected ticks
![IQ Binary - (bot binary com)(2020 10 02_11_37_46)](https://user-images.githubusercontent.com/54183297/94893184-337e6080-04a4-11eb-8f91-ed198eaa6ddb.jpg)
iqbinarybot@gmail.com

**Comment by Kosta92** [comment]
@IQBinary Thank you for answering my question. Cheers!
