### ISSUE TITLE
Alterar tempo de execução

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3019]
Olá a todos! tenho um Bot que vem trabalhando muito bem, mas eu gostaria de saber se tem como alterar o tempo de execução sem ter que parar o bot. exemplo: ele tá configurado para 1 minuto mas o bot reconheceu uma entrada de apenas 30 segundos como eu poderia fazer essa alteração sem ter q parar ou dar o lance para ele aceitar esse tempo???
espero que eu tenha explicado com clareza.
![image](https://user-images.githubusercontent.com/43180630/94715883-6ef22100-0324-11eb-93f1-0d4c8121b5f3.png)

Eu queria que antes da execução pudesse ser alterado o tempo
 
![image](https://user-images.githubusercontent.com/43180630/94716314-0788a100-0325-11eb-9f4a-ecea8d17eb98.png)

**Comment by cleberscr** [comment]
você vai ter que trabalhar com o bloco segundos desde o epoch, e no lugar de minutos altera para segundos

**Comment by contatodeanet** [comment]
> você vai ter que trabalhar com o bloco segundos desde o epoch, e no lugar de minutos altera para segundos

O problema é que em 'definir opções de negociação' não altera nada depois q vc executa o bot, essa alteração só acontece quando inicia ou o bot faz alguma operação, durante o processo ele n pode ser alterado. Isso é frustrante!!!! 

outra coisa que faz muita raiva e quando a negociação da erro(Proposta de contrato desconhecido)!!!! Puta Merda mano!!!!!
![Captura de tela de 2020-09-30 19-58-28](https://user-images.githubusercontent.com/43180630/94748986-0bceb180-0359-11eb-84b3-0909f7515cbb.png)

**Comment by cleberscr** [comment]
> > você vai ter que trabalhar com o bloco segundos desde o epoch, e no lugar de minutos altera para segundos
> 
> O problema é que em 'definir opções de negociação' não altera nada depois q vc executa o bot, essa alteração só acontece quando inicia ou o bot faz alguma operação, durante o processo ele n pode ser alterado. Isso é frustrante!!!!
> 
> outra coisa que faz muita raiva e quando a negociação da erro(Proposta de contrato desconhecido)!!!! Puta Merda mano!!!!!
> ![Captura de tela de 2020-09-30 19-58-28](https://user-images.githubusercontent.com/43180630/94748986-0bceb180-0359-11eb-84b3-0909f7515cbb.png)

tente isso mano
me passa seu whats ou telegram, vai ser melhor pra gente tirar duvidas, ja q aqui é so gringo que responde e tals

![image](https://user-images.githubusercontent.com/61013585/97046323-97e58a80-154d-11eb-80aa-323b9a51e223.png)
