### ISSUE TITLE
O binary.com já tem data para finalizar suas operações?????

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3020]
O site binary.com vai ser substituído definitivamente pelo deriv.com ou vão trabalhar em paralelo????

Particularmente não gosto da interface da Deriv.com acho muito complicado a montagem do bot, alguém mais tem essa dificuldade???

**Comment by cleberscr** [comment]
todos tem

**Comment by aaron-binary** [comment]
Hey @contatodeanet,

No futuro, concentraremos nossos esforços no Deriv.com. Adoraríamos saber como podemos facilitar o uso da plataforma DBot, sinta-se à vontade para comentar aqui ou enviar um e-mail para binarybot@binary.com.

Saudações,
Aaron
