### ISSUE TITLE
Hey, is this Bug? Small font issue.

### ISSUE THREAD

**Issue by deny-titan** [binary-com/binary-bot#3021]
This is screenshot of DBot in my laptop. Is this Bug? I can't change chart to any market.

<img width="221" alt="Small_Font_1" src="https://user-images.githubusercontent.com/71332443/94845912-94794a80-044a-11eb-8748-6e3811d6266e.png">

<img width="329" alt="Small_Font_2" src="https://user-images.githubusercontent.com/71332443/94845929-9ba05880-044a-11eb-92df-673373299a2c.png">

**Comment by aaron-binary** [comment]
Hey @deny-titan,

Looks like some of the assets aren't loaded correctly. Could you try to do a [hard refresh](https://www.namecheap.com/support/knowledgebase/article.aspx/10078/2194/how-to-do-a-hard-refresh-in-chrome-firefox-and-ie)?

Regards,
Aaron

**Comment by deny-titan** [comment]
> Hey @deny-titan,
> 
> Looks like some of the assets aren't loaded correctly. Could you try to do a [hard refresh](https://www.namecheap.com/support/knowledgebase/article.aspx/10078/2194/how-to-do-a-hard-refresh-in-chrome-firefox-and-ie)?
> 
> Regards,
> Aaron

Ok @aaron-binary Problem Solved with resetting Microsoft Edge.
Thankyou!

**Comment by VIPER12th** [comment]
Please leave your email
