### ISSUE TITLE
MARTINGALE START WORKING AFTER 2 LOSSES OF TRADE

### ISSUE THREAD

**Issue by Neacrist** [binary-com/binary-bot#3022]
Hello
How do I make martingale bot to start working after 2 losses of trade?
Please help me.

**Comment by IQBinary** [comment]
> 
> 
> Hello
> How do I make martingale bot to start working after 2 losses of trade?
> Please help me.

@Neacrist 
![IQ Binary - (bot binary com)(2020 10 03_10_55_03)](https://user-images.githubusercontent.com/54183297/94984178-fe871200-0566-11eb-803f-69ba7ebbb9fa.jpg)
iqbinarybot@gmail.com
