### ISSUE TITLE
Bot barrier v10

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#3024]
Hello, I would like to know if anyone can configure a bot with the following features:
volatility index10 
stays in goes out
2 minutes
Default barrier e.g. +1.071 -1.071
The most important thing is that the bot executes the trades every 2 minutes, it doesn't matter if the trade is won or lost, the important thing is that it is executed every 2 minutes. 
Ex: 10:00 lose 10:02 win 10:04 win 10:06 win 10:08 win or lose 10:10 win or lose  10:12  10:14 etc.

Kind regards

**Comment by IQBinary** [comment]
Your given condition will not take trade on exact every 2 minutes.
