### ISSUE TITLE
Ladder profit

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#3026]
Hi.

How to make a ladder profit part of the bot, in a way that it ups the stake until it hits a profit limit (say $10), then restarts the stake from $1 until it hits the next $10 limit (now being $20 total profit, then $30, $40,...)? I have tried using the _Contract Detail: profit_ block, but it looks only at a single trade profit, and a _Total Profit_ block which looks at a total proft/loss, but whenever the total profit is above $10 it always trades using $1 stakes until it brings down the profit to $9 or lower, in order to hit $10.

I just don't know how to combine those blocks.

Can you help me?

**Comment by overwatch873** [comment]
> Hi.
> 
> How to make a ladder profit part of the bot, in a way that it ups the stake until it hits a profit limit (say $10), then restarts the stake from $1 until it hits the next $10 limit (now being $20 total profit, then $30, $40,...)? I have tried using the _Contract Detail: profit_ block, but it looks only at a single trade profit, and a _Total Profit_ block which looks at a total proft/loss, but whenever the total profit is above $10 it always trades using $1 stakes until it brings down the profit to $9 or lower, in order to hit $10.
> 
> I just don't know how to combine those blocks.
> 
> Can you help me?
 
Hi can you send you the xml block..
Wlll check it out
