### ISSUE TITLE
Periods longer than data length

### ISSUE THREAD

**Issue by trident2005** [binary-com/binary-bot#3033]
@aaron-binary 

All day yesterday I was testing an algorithm that contains the same structure as the one we can see in the image, but today it stopped working throwing the message "Periods longer than data length", and none based on this structure works, it throws the same message.

![image](https://user-images.githubusercontent.com/56892552/95510855-954b3880-0984-11eb-9574-a1659028822b.png)

**Comment by ChinthakaJP** [comment]
Yes...i'm also testing my bot above 2 months...but today it says "Given Candle is not Valid "  
![Untitled](https://user-images.githubusercontent.com/35625635/95523197-a5e2c980-09eb-11eb-8e86-d5e203df47b8.jpg)

I think this is a technical issue...

**Comment by trident2005** [comment]
@ChinthakaJP but if I test on DERIV it works

**Comment by ChinthakaJP** [comment]
@trident2005 my bot is not working on DERIV.

**Comment by aaron-binary** [comment]
Hey guys,

The `Periods longer than data length` error is thrown when the candle list you're feeding into the `Exponential Moving Average Array`-block contains lesser values than the period you specified, usually it means the candle list is empty. 

Could you verify this by using a `Notify (green) with sound: (Silent) <candle_list>`-block? If the notify returns enough values but the error is still thrown, something might be up on our side.

Regards,
Aaron
