### ISSUE TITLE
Given Candle not Valid

### ISSUE THREAD

**Issue by overwatch873** [binary-com/binary-bot#3036]
@aminmarashi-binary @aaron-binary @carol-binary .....Hi there seem to be an issue with binary bot candlestick block....all my bots with candlestick analysis....keep saying given candle not valid...but they worked perfectly fine yesterday.... please fix

**Comment by aaron-binary** [comment]
Hey @overwatch873,

We're aware of this issue and will release a fix soon.

Regards,
Aaron

**Comment by carol-binary** [comment]
Hey @overwatch873,

This should be fixed now!

Regards,
Carol
