### ISSUE TITLE
Download transaction history on deriv bot

### ISSUE THREAD

**Issue by stranger-dev** [binary-com/binary-bot#3040]
Hi,

I can't download transaction history on deriv bot, 
Is that feature out or will we have to wait.

**Comment by stranger-dev** [comment]
I used this a lot on binary bot. It'd be nice to have.

**Comment by aaron-binary** [comment]
Hey @stranger-dev,

You can click the Download button in the Transactions and Journal tab, please see the screenshot below:

![Screenshot 2020-10-12 at 10 01 38](https://user-images.githubusercontent.com/44427668/95697673-113dcd00-0c72-11eb-9793-236bddaa47a9.png)

Clicking the button will download your Transaction log in a .csv format.

Regards,
Aaron

**Comment by stranger-dev** [comment]
Hi @aaron-binary 

I had tried that before and I just noticed you have to stop the bot for the download button to be active,
could you make it possible to download even of the bot is still running? Like it is on binary bot?

**Comment by aaron-binary** [comment]
Hey @stranger-dev,

We could do that, however some transactions would be incomplete. Are you using some automation or something?

Would love to hear how you're using the transaction log.

Regards,
Aaron

**Comment by stranger-dev** [comment]
I use that when I'm trying to check or analyze something real quick in the previous transactions , 
I shouldn't need to stop the bot for that.

for the incomplete transaction, it doesn't matter coz it's always at the bottom of the document.

You could exclude the incomplete transaction from the download. and If this isn't possible, then make this feature optional through platform settings.
