### ISSUE TITLE
multiple open orders in sametime

### ISSUE THREAD

**Issue by susantha1995** [binary-com/binary-bot#3042]
hi, please help me to fix this.

can we make a binary bot for open multiple orders at the same time?

for ex: bot open 12.00 am first order(expire in 30 minutes) so again bot should be can open another orders 12.05, and more orders before expiring the first order(before 12.30)

so I need to open multiple orders at the same time with the martingale option.

**Comment by larajeanz1999** [comment]
I think your talking about timer bot...I think I know bot like that it's bot of two browser windows ,First browser purchase call and second browser purchase put at the same time ,If that's what you want I have the bot !

**Comment by woletm** [comment]
> I think your talking about timer bot...I think I know bot like that it's bot of two browser windows ,First browser purchase call and second browser purchase put at the same time ,If that's what you want I have the bot !

please drop the bot. let me see
