### ISSUE TITLE
Simple wining bot!!

### ISSUE THREAD

**Issue by larajeanz1999** [binary-com/binary-bot#3043]
**Hello everyone!!

In fact I get confused every time I try to write that bot... I want to code bot works on that sequence ''call ,put ,call ,put'' and goes on and on, it doesn't matter the result ,just the sequence like that ''call ,put ,call ,put, call ,put''... lot of people get confused on that even it's easy to code it ! Right ?... 

I will be glad if you help us on that !!**

**Comment by dushn** [comment]
> **Hello everyone!!
> 
> In fact I get confused every time I try to write that bot... I want to code bot works on that sequence ''call ,put ,call ,put'' and goes on and on, it doesn't matter the result ,just the sequence like that ''call ,put ,call ,put, call ,put''... lot of people get confused on that even it's easy to code it ! Right ?...
> 
> I will be glad if you help us on that !!**

https://github.com/binary-com/binary-bot/issues/1885
these strategy not work long time. don't run in real account

**Comment by Kosta92** [comment]
I've tried this so called "strategy" a few times in a various ways and it always loses money after some time. That's the nature of volatility markets, they are made to be random.
