### ISSUE TITLE
How to create bot Fibonacci Retracement

### ISSUE THREAD

**Issue by AIY-007** [binary-com/binary-bot#3049]
@binary-ex-machina @lasaidhari @saidforex26 @Fruitfella @aminmarashi-binary @Mahboobeh-binary @jy-binary @ashkanx @Aaron Imming @IQ Binary

**Comment by binary-ex-machina** [comment]
This may help you get the fibo levels. I put the analysis of Max/Min values for the starting points of the retracement, so it depends on the strategy you use to be used with the levels.

![image](https://user-images.githubusercontent.com/34610787/124409923-b710fa80-dd1f-11eb-9bf9-2290d79f0463.png)
