### ISSUE TITLE
The bot is stucking

### ISSUE THREAD

**Issue by Antiteemon** [binary-com/binary-bot#305]
I have such a problem.

The bot works fine, but it happens that at some point it freezes. After that, the bot stops making transactions, because it believes that the deal is still open. Who can advise something?

Thanks for helping
![image](https://user-images.githubusercontent.com/29971559/27946013-6fffa10a-62f8-11e7-8046-a71d99148fa5.png)

**Comment by aminmarashi** [comment]
This is a known issue, we're doing our best to fix this.

**Comment by Antiteemon** [comment]
Thanks for answer. Interesting, why "1 minute's" durations working good, but 5 minutes got this :(

**Comment by aminmarashi** [comment]
I hope that this issue is fixed, could you please check @Antiteemon ?

**Comment by aminmarashi** [comment]
Please feel free to reopen if the issue still exists.
