### ISSUE TITLE
great idea 

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#3050]
Dear All

Please can any one help me with creat bot in this idea :

If the last digit is a odd number and happend 5 times Respectively

example : the alst digit : 1 . 5 .1 .3 ,9 (5 odd digit )
the next trade will be for even numbers
the bot will take a even trade .

thank you

**Comment by VIPER12th** [comment]
> Dear All
> 
> Please can any one help me with creat bot in this idea :
> 
> If the last digit is a odd number and happend 5 times Respectively
> 
> example : the alst digit : 1 . 5 .1 .3 ,9 (5 odd digit )
> the next trade will be for even numbers
> the bot will take a even trade .
> 
> thank you

@ahmadhus 
[5ODD IS EVEN 1THICK V75.txt](https://github.com/binary-com/binary-bot/files/5396443/5ODD.IS.EVEN.1THICK.V75.txt)

**Comment by Joniekesh** [comment]
> > Dear All
> > Please can any one help me with creat bot in this idea :
> > If the last digit is a odd number and happend 5 times Respectively
> > example : the alst digit : 1 . 5 .1 .3 ,9 (5 odd digit )
> > the next trade will be for even numbers
> > the bot will take a even trade .
> > thank you
> 
> @ahmadhus
> [5ODD IS EVEN 1THICK V75.txt](https://github.com/binary-com/binary-bot/files/5396443/5ODD.IS.EVEN.1THICK.V75.txt)

I just tested the bot and it's doing a great job.Could you please add resettable or 110 steps compounding to the bot?

Thanks.
