### ISSUE TITLE
PROBLEMA NA CONTAGEM DOS SEGUNDOS NA VELA

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3057]
Olá a todos! tenho duas gestões a tratar, a primeira é: porque que no sintético a contagem dos segundos na vela fica mudando de par para impar ex: se eu colocar um contador de segundos ele aparece 2...4..6..8... e do nada muda para 3...5..7..9..11... isso faz com que minha entrada no inicio da vela não seja exata, se eu colocar pra inicial em 57 segundos e ele tiver na contagem de numero par simplesmente o bot não reconhece, como resolver isso???? 

Outra coisa que eu gostaria de saber é se existe uma quantidade exata de tiks dentro de uma vela, assim em vez de contar os segundos eu contaria os tiks!!!

preciso de uma regra que inicie exatamente no inicio da vela!!! alguém pode me ajudar!!????

**Comment by cleberscr** [comment]
isso é pq o sistema da binary n consegue carregar tudo em apenas 1 segundo, e da esse delay de 1 segundo que pega apenas os numeros pares ou impares, dependendo da hora que vc aperta

tem esse sistema que pode te ajudar, se der 58 ou 59 vai abrir a negociação, ou seja, bem no inicio da vela, só que o tempo da negociação tem que ser 53 ou 55 segundos por causa dos delays e etc

![Uploading image.png…]()

**Comment by contatodeanet** [comment]
> isso é pq o sistema da binário n consegue carregar tudo em apenas 1 segundo, e da esse atraso de 1 segundo que pega apenas os numeros pares ou impares, dependendo da hora que vc aperta
> 
> tem esse sistema que pode te ajudar, se der 58 ou 59 vai abrir uma negociação, ou seja, bem no início da vela, só que o tempo da negociação tem que ser 53 ou 55 segundos por causa dos atrasos e etc.
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/61013585/97044591-ac745380-154a-11eb-9140-345380ad6a2d.png)

Eu já uso dessa forma @cleberscr  mas como a binary tem muito gap fica complicado acertar o inicio da vela... vlw pela ajuda!!! vou continuar procurando alguma forma de resolver isso!!!

**Comment by contatodeanet** [comment]
Eu descobri!!!! cada vela na volatilidade 10 tem exatamente 30 tik's e como ele sempre entra no segundo tik pra conseguir marcar a entrada exata o lance tem que ser feito no tik 30 da vela anterior. ele vai contar: tik-29(gatilho de entrada)..tik-30(gatilho de execução), vou testar e depois coloco a regra aqui pra quem quiser usar!!!!!

**Comment by contatodeanet** [comment]
![image](https://user-images.githubusercontent.com/43180630/97082891-4091f980-15e3-11eb-8773-9ed8bb2834c5.png)
![image](https://user-images.githubusercontent.com/43180630/97082907-5b646e00-15e3-11eb-9edc-e28bba61ad1f.png)
Independe do tamanho do GAP agora o bot sempre vai abrir no inicio da vela!!!


[abertura de vela.txt](https://github.com/binary-com/binary-bot/files/5432948/abertura.de.vela.txt)

**Comment by contatodeanet** [comment]
**_agora é só adicionar essa regra a qualquer bot de vela!!! espero ter ajudado!!!!_**

**Comment by cleberscr** [comment]
hmmm, vou testar jaja, interessante, obrigado

**Comment by cleberscr** [comment]
> **_agora é só adicionar essa regra a qualquer bot de vela!!! espero ter ajudado!!!!_**

eu testei e é realmente bom, porém se tem algum bot que precisa do fechamento da mm (vela anterior) essa maneira n ajuda

**Comment by clebertido87** [comment]
olá, os robos que crio na Binary.com só consigo rodar por Tick, não consigo habilitar a função na (1) Intervalo padrão de velas: 1 minuto, alguem já conseguiu rodar um robô para Candlestick e não só os Tick ?????
