### ISSUE TITLE
I have strategy and it's working fine but I need some modifications in that bot.

### ISSUE THREAD

**Issue by saibinaryiq** [binary-com/binary-bot#3061]
<img width="1360" alt="Screenshot 2020-10-24 at 2 56 04 AM" src="https://user-images.githubusercontent.com/73366677/97055469-7f548f00-15a4-11eb-8926-b8bc949eb9a6.png">
I am using digit differ bot. in that bot once I got the loss it's taking Martingale with multiplier 11. instead of it should take multiplier as 3 and it should loop for 4 times and then it come back to initial investment.

**Comment by usherreuben** [comment]
Take a look at this 3 stage Martingale in the xml and develop yours around this idea.  i think this can really help you
[3 stages MARTINgale.txt](https://github.com/binary-com/binary-bot/files/5447043/3.stages.MARTINgale.txt)

**Comment by saibinaryiq** [comment]
@usherreuben Thank you let me try to do that.
