### ISSUE TITLE
Help me create money management like this 

### ISSUE THREAD

**Issue by Simo-912** [binary-com/binary-bot#3062]
![D_NQ_NP_978061-MLB31935487028_082019-O](https://user-images.githubusercontent.com/66981410/97093391-63ec9100-1643-11eb-9a4d-eb23fbfa11cf.jpg)
![IMG_20201024_215453](https://user-images.githubusercontent.com/66981410/97093417-a31ae200-1643-11eb-9544-ac4dac4a5700.jpg)

**Comment by Simo-912** [comment]
Please guys help

**Comment by larajeanz1999** [comment]
if you mean 2 martingale after 1 loss drop the bot here ,maybe i can do something

**Comment by Simo-912** [comment]
Hi Bro thank you so much,here is the bot ✌😊
https://drive.google.com/file/d/16WfzAsTnOcyUoIngWBv6AEUKh_7voq1v/view?usp=drivesdk

**Comment by Simo-912** [comment]
> if you mean 2 martingale after 1 loss drop the bot here ,maybe i can do something

Please I sent you the bot

**Comment by larajeanz1999** [comment]
I will do what I can

**Comment by Simo-912** [comment]
Thank u so much

**Comment by larajeanz1999** [comment]
Sorry ,I didn't made it ,I hope you find someone who could made it for you...
But I will keep trying

**Comment by Simo-912** [comment]
Thank you so much
Tell me do you know how to covert pdf file to xml file

**Comment by larajeanz1999** [comment]
Yes ,you can use some online converters
