### ISSUE TITLE
the last digit stats! is it possible?

### ISSUE THREAD

**Issue by larajeanz1999** [binary-com/binary-bot#3063]
**Hi 
I was wondering if you can help me to code differ bot predicts digit if that digit has last stats is 0.00% ???**

Thanks and I will be very thankful
@deny-titan
@aaron-binary
@saidforex26
@contact
@GreenBot
@hotmatrixx
@AlienFly
@sam-binary
@ChinthakaJP
@IQBinary

**Comment by larajeanz1999** [comment]
[http://images.vfl.ru/ii/1603579582/8c774427/32046967.png
](url)

**Comment by larajeanz1999** [comment]
![digit](https://user-images.githubusercontent.com/72756400/97095166-f45dae00-1610-11eb-8ca5-584fb52be95b.png)

**Comment by deny-titan** [comment]
@larajeanz1999 

Consider that maybe more than 1 digit are on 0.00% stats. Try my bot to Purchase Differs digit with 0.00% stats using random select if more than 1 digit that have 0.00% stats survey :

[Survey 0 pct Last Digit with Purchase (1).zip](https://github.com/binary-com/binary-bot/files/5460694/Survey.0.pct.Last.Digit.with.Purchase.1.zip)
