### ISSUE TITLE
Help. I don't understad to use "load block from" . 

### ISSUE THREAD

**Issue by sunitpro** [binary-com/binary-bot#3066]
Hi every one, i can' t to use "Load block from" in Binary Bot. You can help me to use it in my bot. Tks all very much.

1. what do i can use?
2. where must I upload it to? 
and how do i use in my code?

If you can take a picture ur screen for me, is very good.

Thanks all to see my topic

**Comment by wyu001** [comment]
sunit .. you mean to load bot xml file into the bot.binary.com ?

**Comment by sunitpro** [comment]
> sunit .. you mean to load bot xml file into the bot.binary.com ?

i know load bot xml, but i don't know to use function "load block from" because it must upload and add a link into it, right?
