### ISSUE TITLE
Please, help to get correct value

### ISSUE THREAD

**Issue by Livandos** [binary-com/binary-bot#3069]
Please, help to get correct value! Rounding does not help
Thanks!
![2020-10-27_LI](https://user-images.githubusercontent.com/61840855/97327179-65a19900-187d-11eb-828f-a5e20e7c55a2.jpg)

**Comment by XYRubiYx** [comment]
You can multiply the value by 100 example and use the mathematical properties: 
var value = 0.5199999999999818
value = value * 100;
now you round the number.
after:
value = value / 100;
![image](https://user-images.githubusercontent.com/63131349/102843653-5dcb2480-43e8-11eb-9d07-3fe82ee9da6c.png)

**Comment by XYRubiYx** [comment]
For the negative value you can use either the mathematical property "absolute value", or multiply the value by (-1)
Example:
var number = -0.8999999999999;
number = number * (-1);
or
number = |number|;
this is up to you!
