### ISSUE TITLE
Help / Minta tolong nich .. 

### ISSUE THREAD

**Issue by wyu001** [binary-com/binary-bot#3073]
temen2 .. minta tolong dengan sangat .. ada yg bisa ajarin saya utk menggunakan puzzle bot binary  sort numeric ascending ? 
maksudnya utk membalik - mengurut angka tick 3 atau 4 digit terakhir ..berikut yg saya maksud : 

Tick V.100  1235.46 ----> nah saya ingin ngambil angka 546 nya ... sampe tahap ini saya bisa ..
546 ----> 654         -----> nah utk merubah sususan dari 546 ke 654 ini yg saya masih bingung , tolong bantuannya spt apa 
susunan bot nya ...? ada puzzle yg saya sebut diatas : sort numeric ascending ( di daftar menu LIST paling bawah ) , saya yakin 
bisa menggunakan puzzle ini utk membalik urutan angka - cuma saya mentok masih bego .. gimana makenya .. tolong ya sob .. 
makasih banyak sebelumnya. 

wyu001

**Comment by deny-titan** [comment]
Kalau sudah bisa mengambil angka 546 nya, berarti tinggal mengurutkan saja menjadi 654 kan? Saya pakai DBot, caranya seperti ini. Catatan: contoh yang saya berikan ini menganggap 546 nya sudah dalam bentuk "text" ya. Kalau dia masih berupa angka numerik caranya beda lagi.

![SharedScreenshot_sort](https://user-images.githubusercontent.com/71332443/97600516-b828b400-1a3b-11eb-95aa-f7202bab369a.jpg)

**Comment by deny-titan** [comment]
Nah yang ini contoh kalau 546 awalnya berupa data numerik, perlu dikonversi jadi text dulu.

![SharedScreenshot_sort_from_numeric](https://user-images.githubusercontent.com/71332443/97604442-13f53c00-1a40-11eb-8260-071e913cac98.jpg)

**Comment by wyu001** [comment]
Hallo Mas Deny ... wuahh.. keren nich .. thanks alot yaa mas bantuannya .. much appreciate it mas bro ... tak coba dulu ... skali lagi 
matur nuwun sanget...

**Comment by deny-titan** [comment]
> Hallo Mas Deny ... wuahh.. keren nich .. thanks alot yaa mas bantuannya .. much appreciate it mas bro ... tak coba dulu ... skali lagi
> matur nuwun sanget...

Sami-sami Mas Bro :)

**Comment by wyu001** [comment]
Mas..Deny .. nyuwun tulung lagi nich ... iki macet mas bro... kepentok di undefined terus....apanya yg salah yaaa.. udah sama kan mas .. susunan puzzlenya ? kena undifined in not a function ... nyuwun tulung mas di koreksi .. matur sembah nuwun ... 

![image](https://user-images.githubusercontent.com/37494697/97624046-1e6fff80-1a59-11eb-9b9c-d203366a84c9.png)

**Comment by wyu001** [comment]
uwis mas udah bisa .. he he he .. salah yg di paling bawah kuwalik .. he he he .. suwun yakkk mas bro...

**Comment by wyu001** [comment]
Mas Deny , waduh maaf bolak balik nanya - itu angka hasil descending dan ascending , emang gak bisa di anggep angka ya mas .. saya coba lakukan pengurangan/penjumlahan hasilnya NaN..piye mas agar angka nya terbaca sbg angka agar bisa di hitung ...ada saran kah ? makasih yaa...

**Comment by deny-titan** [comment]
> Mas Deny , waduh maaf bolak balik nanya - itu angka hasil descending dan ascending , emang gak bisa di anggep angka ya mas .. saya coba lakukan pengurangan/penjumlahan hasilnya NaN..piye mas agar angka nya terbaca sbg angka agar bisa di hitung ...ada saran kah ? makasih yaa...

@wyu001  Waduh iya Mas. Kalau dia sudah jadi text, susah dibalikin lagi jadi angka. Apa njenengan perlu tetap sebagai angka Mas datanya?

**Comment by deny-titan** [comment]
Oh, ini solusinya Mas. Pakai tools absolute (bisa cari di Math). Sorry saya pakai DBot. Belum pernah coba2 bikin di binary. Kayaknya ada juga kok.

![SharedScreenshot_text_to_num](https://user-images.githubusercontent.com/71332443/97652029-14b5be80-1a90-11eb-897b-e0ed78a1354d.jpg)

**Comment by deny-titan** [comment]
@wyu001 Gantian nanya boleh kan Mas ? Hehe. Ini screen shot yang di thread #3076 dari njenengan kan Mas? Boleh ngerti strategi signalnya nggak? Hehehe...

**Comment by deny-titan** [comment]
@wyu001 Gantian mau tanya boleh nggak Mas Bro tentang strategy yang ada di pict thread sebelah? Klo krg berkenan di sini, via email juga oke. Hehehe....

**Comment by wyu001** [comment]
woleh bgt dunk .. surat2an ae yo mas .. njenengan info disini layangnya ben aku sing kirim layang ke ngejengan sorry ngomong jowo broo..njenengan ngerti kan knp ?

**Comment by wyu001** [comment]
> Oh, ini solusinya Mas. Pakai tools absolute (bisa cari di Math). Sorry saya pakai DBot. Belum pernah coba2 bikin di binary. Kayaknya ada juga kok.
> 
> ![SharedScreenshot_text_to_num](https://user-images.githubusercontent.com/71332443/97652029-14b5be80-1a90-11eb-897b-e0ed78a1354d.jpg)

Ha ha ha .. iyo suwun mass... sebenernya udah ada itu .. mas bro sulisnya .. eh solusine .. itu dideretan petunjukmu .. sudah ada yg paling bawah - itu tinggal dibuatin set baru .. trus make test from list B ..dst nya .. udah balik jadi angka lagi .. lebih pendek sob langkahnya .. sengaja nyusun bot yg paling pendek logikanya biar gak ke udak2 .. kalo binary nya ngaco ...kadang kan suka macet...atemp buy.>>>>>>buy success>>>>>>delay >>>>contract closed ....sering kan kayak gini .. he he .. tapi suer suwun mas .. jadi punya ilmu baru iki ... he he he

**Comment by deny-titan** [comment]
> woleh bgt dunk .. surat2an ae yo mas .. njenengan info disini layangnya ben aku sing kirim layang ke ngejengan sorry ngomong jowo broo..njenengan ngerti kan knp ?

Hehehe.. Yoii...jalurhijau.dbot@gmail.com

**Comment by wyu001** [comment]
siappp kolor ijo meluncurrr...

**Comment by deny-titan** [comment]
> siappp kolor ijo meluncurrr...

Wkwkwk.... Oke sip!
