### ISSUE TITLE
Pls help me Insert split Martingale

### ISSUE THREAD

**Issue by VIPER12th** [binary-com/binary-bot#3077]
@deny-titan 
[Jhhh.txt](https://github.com/binary-com/binary-bot/files/5454570/Jhhh.txt)
Hello pls can you help insert split Martingale into this my bot I will appreciate

**Comment by wyu001** [comment]
![image](https://user-images.githubusercontent.com/37494697/97526601-1160fb00-19dc-11eb-9143-61d50b9cd1f5.png)

There you go ... you could use the martingale  for other bots.. easy for you to develops the bot's
without confusing to manage your money management. 

Enjoy.... 
[jhhh wyu revised01.txt](https://github.com/binary-com/binary-bot/files/5456211/jhhh.wyu.revised01.txt)

**Comment by VIPER12th** [comment]
> ![image](https://user-images.githubusercontent.com/37494697/97526601-1160fb00-19dc-11eb-9143-61d50b9cd1f5.png)
> 
> There you go ... you could use the martingale for other bots.. easy for you to develops the bot's
> without confusing to manage your money management.
> 
> Enjoy....
> [jhhh wyu revised01.txt](https://github.com/binary-com/binary-bot/files/5456211/jhhh.wyu.revised01.txt)

Thanks brother Allah bless you @wyu001

**Comment by VIPER12th** [comment]
Leave me your WhatsApp number or telegram pls

**Comment by VIPER12th** [comment]
> ![image](https://user-images.githubusercontent.com/37494697/97526601-1160fb00-19dc-11eb-9143-61d50b9cd1f5.png)
> 
> There you go ... you could use the martingale for other bots.. easy for you to develops the bot's
> without confusing to manage your money management.
> 
> Enjoy....
> [jhhh wyu revised01.txt](https://github.com/binary-com/binary-bot/files/5456211/jhhh.wyu.revised01.txt)

Pls kindly reupload it in zip format, it's given me error msg here pls

**Comment by wyu001** [comment]
haiyaa.. come on bro... that's txt file .. you can easily downloaded... after you got the files - open it with notepad.. then on the notepad click file - then save as .. you name it whatever you prefer ... and put .xml (after the file name ) .. choose the file saving
as all files (as ANSI kind ) .. then click save or ok.  that's all .... ( i did the same when you sent your files asking to modify ).

I am sorry bro .. I can't leave my number here - i have only 1 number for my present jobs ..no facebook , no IG , no social media .. ha ha ha I am old fashion guy. you may search my nick name .. then you could get my email address on my old timer post ( way back 2018 ) .. send me an email then we could discuss

cheers, 
wyu001

Tips : for digits .. pls play one side only 👍 

![image](https://user-images.githubusercontent.com/37494697/97537439-60655b00-19f1-11eb-9cb4-47386a3b25a8.png)

**Comment by VIPER12th** [comment]
> haiyaa.. come on bro... that's txt file .. you can easily downloaded... after you got the files - open it with notepad.. then on the notepad click file - then save as .. you name it whatever you prefer ... and put .xml (after the file name ) .. choose the file saving
> as all files (as ANSI kind ) .. then click save or ok. that's all .... ( i did the same when you sent your files asking to modify ).
> 
> I am sorry bro .. I can't leave my number here - i have only 1 number for my present jobs ..no facebook , no IG , no social media .. ha ha ha I am old fashion guy. you may search my nick name .. then you could get my email address on my old timer post ( way back 2018 ) .. send me an email then we could discuss
> 
> cheers,
> wyu001
> 
> Tips : for digits .. pls play one side only 👍
> 
> ![image](https://user-images.githubusercontent.com/37494697/97537439-60655b00-19f1-11eb-9cb4-47386a3b25a8.png)

Ok I have searched tired I couldn't find your email but message me on my email sagaciousprince76@gmail.com thanks

**Comment by wyu001** [comment]
check your spam email viper ..
