### ISSUE TITLE
Vamos criar um bot com Fibonacci/LTA/LTB/Suporte e Resistência?

### ISSUE THREAD

**Issue by eduardoxgt** [binary-com/binary-bot#3078]
Gostaria de ter ajuda para criar um bot que analisasse o gráfico usando o Price action, sei que não e impossível porque eu já criei a retração De Fibonacci.

**Comment by contatodeanet** [comment]
é muito complicado pois tanto a LTA como LTB oscila muito nas MA, teria q ter uma forma de mapear em qual MA o suporte e a resistência se encontra e definir qual seria o ponto de entrada assim q tocar na MA, deu pra entender!!?

**Comment by contatodeanet** [comment]
tenho um bot que faz isso com tiks, funciona assim: ele teoricamente reconhece um suporte/resistência e assim q é rompido ele aguarda o pullback para efetuar a operação

**Comment by contatodeanet** [comment]
se quiser posso disponibilizar aqui pra gente tentar melhorar!!!

**Comment by eduardoxgt** [comment]
Usar média móvel como suporte e resistência e LTA e LTB e uma boa mas não acho muito confiante
