### ISSUE TITLE
SPLIT MARTINGALE

### ISSUE THREAD

**Issue by VIPER12th** [binary-com/binary-bot#3083]
please I need someone to help me insert this type of martingale into my under bot, the martingale is like this , anytime the first trade lose it should work like this
$1 x 11 but if it lose again next trade will be 11 x 5.5 if this win it will repeat the 11x5.5 again so as to recover all the previous loss if this win it will now return back to initial $1
It is only only the first trade it will multiply by 11 any loss after , it should continue to multiply by 
5.5  until wins and recover all the previous loss amount and return back to initial stake
 Thanks so much
[VIPERS FAVORITE.txt](https://github.com/binary-com/binary-bot/files/5470298/VIPERS.FAVORITE.txt)

@deny-titan
@saidforex26
@contact
@GreenBot
@hotmatrixx
@AlienFly
@sam-binary

**Comment by MiithRanDir** [comment]
Try this
[Download](https://newsonthegotoday.com/8t9sr3)
![2020-11-27_142646](https://user-images.githubusercontent.com/5079543/100422434-e8a45200-30bc-11eb-88e8-1a36885308f0.jpg)
