### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by VIPER12th** [binary-com/binary-bot#3089]
Who can help me to build this strategy into a bot
 The strategy is like this 1st trade will be under 7 if it loss, immediately second trade will be over 0, immediately if it loss 3 trade will under 9 with martingale. Thanks
@deny-titan

**Comment by deny-titan** [comment]
@VIPER12th  How about your strategy to pick up the tick to trade?

**Comment by VIPER12th** [comment]
> @VIPER12th How about your strategy to pick up the tick to trade?

@deny-titan Anytime the bot discovered 5 straight over 7 example 8,7,9,9,8 then it should start trade with under 7. 

Or anytime the percentage of 0 is highest among the LDP
THANKS BOSS

**Comment by woletm** [comment]
@deny-titan  please help me attend to my issue too please. its a new one tagged "money management system needed please"

**Comment by ChinthakaJP** [comment]
@VIPER12th I created a bot and i did some improvement with adding LDP analyzer...Try this in Virtual Account before using Real Account
[Over Under.zip](https://github.com/binary-com/binary-bot/files/5508052/Over.Under.zip)

**Comment by VIPER12th** [comment]
> @VIPER12th I created a bot and i did some improvement with adding LDP analyzer...Try this in Virtual Account before using Real Account
> [Over Under.zip](https://github.com/binary-com/binary-bot/files/5508052/Over.Under.zip)

Aiit thanks
