### ISSUE TITLE
CRIEI UM BOT FANTÁSTICO!!!!!

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3092]
_**Melhor bot que já fiz até hoje de combine/difere. testem e postem os resultados para gente tentar melhorar se possível!!!**_

[ALEX_MAMUTE.txt](https://github.com/binary-com/binary-bot/files/5497530/ALEX_MAMUTE.txt)

**Comment by danielmaoli** [comment]
Boa! Mas como roda ele? É .txt

Desculpa a ignorancia

**Comment by alanvito1** [comment]
Só alterar a extensão do arquivo renomeando-o e com a opção de extensões visíveis.

**Comment by DwebDigital** [comment]
@alanvito1 bacana a iniciativa!

Testei ele aqui, e problema que vejo é o gale alto... x11 é bastante, pode quebrar uma banca facilmente. 
Estou buscando alternativas pra usar no lugar do gale. O @binary-ex-machina fez uma vez uma estratégia muito boa, mas não a tenho mais aqui. 

Estou elaborando uma nova estratégia. Assim que eu conseguir te passo aqui pra você testar ok.

**Comment by DwebDigital** [comment]
![download](https://user-images.githubusercontent.com/66212687/98417475-b83e3a80-205f-11eb-9613-c1baf9bf6f56.png)
