### ISSUE TITLE
Consecutive Last Digits - Digit Differ Bot

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#3094]
Hi  everyone,

Good Day. I was trying to create a bot with the following condition:
If 4 consecutive ticks have the four consecutive numbers as their last digits, the 5th tick will not have a last digit which falls in that series.
For eg: if 4 ticks have the following values:
8360.91
8361.12
8360.93
8360.84

The last digits are consecutive numbers: 1,2,3 and 4. I wanted to create a bot that would predict that the last digit of the 5th tick is not 5.

I tried this:
![image](https://user-images.githubusercontent.com/62483125/98450241-0e19fc00-21a0-11eb-9615-d75a53a3085a.png)

The bot appears to trigger when there are 4 consecutive last digits (need to recheck) but it does not seem to fix the 5th digit in the series as the prediction i.e., it appears to run if the LD's are (for eg.) 1,2,3,4 but the prediction is not set to 5. It sets some other random number. Can anyone tell me what am I doing wrong?

Thanks

**Comment by JenggotSantuy** [comment]
I always set Predictions and look for the Last Digits
so the logic has to be reversed
🙏

**Comment by MiithRanDir** [comment]
try this
[DIFF-Consecutive.zip](https://github.com/binary-com/binary-bot/files/5551120/DIFF-Consecutive.zip)

**Comment by woletm** [comment]
@MiithRanDir , please i have an idea of a differ bot that counts loses, before doing martingale, for example, after every 4 loses, it does multiplies. the initial capital doesnt change until 4 loses are recorded. if possible, make the number of loses to be recorded a variable so it can be changed regularly

**Comment by AnonymousBlackPride** [comment]
> 

Hey did you manage to create the bot?

**Comment by AnonymousBlackPride** [comment]
I had the same idea but im stuck just like you. i can't seem to have it choose the next digit in the sequence.
