### ISSUE TITLE
Loss Bot.

### ISSUE THREAD

**Issue by NEWBIE3232** [binary-com/binary-bot#3097]
Hello friends please I need a bot that would first analyse the number of losses before placing a real trade. 
 .
Example
If last digit is even purchase even after 1 tick.
.
Now the bot should analyse the and place invisible trades to see, if the invisible trade has 3 or 4 or 5 or 6 loses then, the bot should now purchase a real trade of even, thereby reducing the number of losses in the real money or the active session 
@saidforex26 @chinthakaJP

**Comment by jp322** [comment]
Aqui no brasil tem um software que faz isso. vc coloca 2 token real e virtual voce progama quantos loss a conta escravo vai dar ai so depois  o bot entra na conta real. o seja 2 bots dentro de um software.

**Comment by NEWBIE3232** [comment]
> Aqui no brasil tem um software que faz isso. vc coloca 2 token real e virtual voce progama quantos loss a conta escravo vai dar ai so depois o bot entra na conta real. o seja 2 bots dentro de um software.

owk so please how do i get the software??

**Comment by NEWBIE3232** [comment]
please freinds help
@deny-titan @saidforex26  @ChinthakaJP

**Comment by IQBinary** [comment]
@NEWBIE3232 

iqbinarybot@gmail.com

**Comment by saidforex26** [comment]
ini adalah fungsi untuk menganalisa virtual open. silahkan dkombinasi dengan strtegy anda.
[analisa virtual 3xloss.zip](https://github.com/binary-com/binary-bot/files/5541931/analisa.virtual.3xloss.zip)

**Comment by NEWBIE3232** [comment]
@saidforex26  thanks

**Comment by NEWBIE3232** [comment]
> ini adalah fungsi untuk menganalisa virtual open. silahkan dkombinasi dengan strtegy anda.
> [analisa virtual 3xloss.zip](https://github.com/binary-com/binary-bot/files/5541931/analisa.virtual.3xloss.zip)

Let me test it out

**Comment by jp322** [comment]
pessoal entrei em contato com dono do software to aguardando. sao 2 software um pago e outro com licença liberada, porem o que e gratuito vc paga uma porcenagem encima dos lucros, se ele me autorizar vou colocar o arquivo. o software foi desemvolvido por um americano com parceria de um brasileiro. vc progama quanto loss   e depois  o bot entra na  conta real faz as etradas no msmo bot porem um bot vai ta na virtual como escravo e outro na real  e tem que usar na vps porque demora dar entrada., vc poe fazer o espelhamento e na binary e no software fazem entradas juntas e tem configuacao de delay quase  0 , dentro do softwre, tem varias configuraçoes.

**Comment by NEWBIE3232** [comment]
hello thanks for the bot  @saidforex26 the bot is very complex i cant understand it, and also its not working very fine

**Comment by NEWBIE3232** [comment]
after placing a trade, the bot should start anayling for another 3 losses again before placing another trade rather than waiting for 2 secs

**Comment by saidforex26** [comment]
> after placing a trade, the bot should start anayling for another 3 losses again before placing another trade rather than waiting for 2 secs

![Untitled](https://user-images.githubusercontent.com/54820719/99201558-7a22e280-27e6-11eb-8a9b-c56ab7fc8017.jpg)

**Comment by NEWBIE3232** [comment]
ok

**Comment by NEWBIE3232** [comment]
@saidforex26  please where do i set martingale to mutiply by 2 after a loss so that i can recover the lost money

**Comment by saidforex26** [comment]
I see you've been in this discussion place for a long time. . you should be able to make your own money management.

**Comment by woletm** [comment]
@saidforex26, please i have an idea of a bot that only does martingale after x number of loses, eg after 4 loses. please can you help me create it. i want it to run for differ. and the number of loses and martingale can be adjustable?

**Comment by Reitrader** [comment]
> > depois de colocar uma negociação, o bot deve começar a anayling por mais 3 perdas novamente antes de colocar outra negociação em vez de esperar por 2 segundos
> 
> ![Sem título](https://user-images.githubusercontent.com/54820719/99201558-7a22e280-27e6-11eb-8a9b-c56ab7fc8017.jpg)


Thanks @ saidforex26 , How to set it up for when you win, make your loss zero?

**Comment by cunk888** [comment]
@saidforex26 untuk mengaktifkan loss berrut bgmn caranya? Pas saya tes, loss brrut saya atur 2. Lalu OP, tpi saat dijalankan apabila loss win loss OP. Seharusnya loss loss OP

**Comment by cunk888** [comment]
@saidforex26 bagaimana cara mengaktifkan loss berurut?

**Comment by Reitrader** [comment]
> @ saidforex26 bagaimana cara mengaktifkan perda berurut?

Thank you .. I already managed to solve it.

**Comment by cunk888** [comment]
@Reitrader  how?

**Comment by Reitrader** [comment]
concluded....

**Comment by botfx45** [comment]
pass the bot xml pls
