### ISSUE TITLE
 I want macd api Bot.macd()

### ISSUE THREAD

**Issue by MiithRanDir** [binary-com/binary-bot#3099]
I used js to run bot files and stuck where I couldn't get MACD data Try trying to find, and there is no manual.
If it's something else, for example ma,
 this can be retrieved Use 
`var ma = Bot.sma (candlelist, period);`

Anyone have a manual?

**Comment by nextnaro** [comment]
ผมเขียนไม่เป็น แบ่งด่วย ตัวใหม่ derive-api เห็นมีคู่มือ
