### ISSUE TITLE
Add Option Trade After Candle M1 Close

### ISSUE THREAD

**Issue by bangrianzz** [binary-com/binary-bot#3103]
hi guys, this is my first post.

i try to learn adn build binary bot. but i confuse to add another block to open trade after losing candle in M1.

can you help me and solve me..?
i wass adding my xml to understanding mine..

https://drive.google.com/file/d/1UFtOKjYBKSyrLCpBvCs14TNPvxr8lnaA/view?usp=sharing

**Comment by bangrianzz** [comment]
here my .xml

**Comment by XxRubialixX** [comment]
Let me see if I got it do you want to enter the operation when the last candle ends?
