### ISSUE TITLE
rsi the right opportunity to sell / buy

### ISSUE THREAD

**Issue by rasmusvakander** [binary-com/binary-bot#3106]
if rsi goes above 80 and then turns and goes below, then I want to sell and if rsi goes below 20 and then turns and goes above 20 I want to buy. can anyone help

**Comment by MiithRanDir** [comment]
Try this [Bot RSI Reversal](https://newsonthegotoday.com/cb8iy7)

**Comment by rasmusvakander** [comment]
thank you very mutch:)
