### ISSUE TITLE
Binary.com bot assistance

### ISSUE THREAD

**Issue by rafkenya** [binary-com/binary-bot#3109]
Hello guys ,I need assistance in making a bot with the following specifications:
1.Trade is based on color of the previous candle.
2.Martingale as follows
       Trade 1-$1
        Trade 2-$2
        Trade 3-$4
         Trade 4-$9
         Trade 5-$20
          Trade 6-$40
           Trade 7-$90
3.It trades at the beginning of a candle formation,not at it has started to form.
4.Time frame of 1 minute.

**Comment by MiithRanDir** [comment]
Try this
[Follow Candle Color](https://newsonthegotoday.com/qfrogl)

**Comment by rafkenya** [comment]
Thanks alot

**Comment by rafkenya** [comment]
Ahm how can I remove the waiting from a lost trade in your bot sir?

**Comment by rafkenya** [comment]
@MiithRanDir kindly assist me with removing the lag in moving to New candle
