### ISSUE TITLE
Boolinger Band Strategy concept need support 

### ISSUE THREAD

**Issue by doehlma** [binary-com/binary-bot#3113]
Hello all,

how and if it is possible to define Bot for following sequences:

a) when the the last candle was red and the following candle is green and  start outside and end inside the Bollinger Band
    -> Bot should start afterwards with 1 min CALL

![CALL _Condition](https://user-images.githubusercontent.com/49290510/100672624-7eacd680-3362-11eb-8047-da8088b0c561.JPG)
 
b) vice versa

![PUT _Condition](https://user-images.githubusercontent.com/49290510/100672713-a00dc280-3362-11eb-87d4-bb4545ef5350.JPG)

I would appreciate it very much if somebody in the community would be able and friendly to create for me as beginner 
the BOT ??

Thanks to all in advance for your support...

**Comment by IQBinary** [comment]
> 
> 
> Hello all,
> 
> how and if it is possible to define Bot for following sequences:
> 
> a) when the the last candle was red and the following candle is green and start outside and end inside the Bollinger Band
> -> Bot should start afterwards with 1 min CALL
> 
> ![CALL _Condition](https://user-images.githubusercontent.com/49290510/100672624-7eacd680-3362-11eb-8047-da8088b0c561.JPG)
> 
> b) vice versa
> 
> ![PUT _Condition](https://user-images.githubusercontent.com/49290510/100672713-a00dc280-3362-11eb-87d4-bb4545ef5350.JPG)
> 
> I would appreciate it very much if somebody in the community would be able and friendly to create for me as beginner
> the BOT ??
> 
> Thanks to all in advance for your support...

iqbinarybot@gmail.com
