### ISSUE TITLE
prices be saved in a sheet in excel?

### ISSUE THREAD

**Issue by pao11901** [binary-com/binary-bot#3114]
Hi everyone.
Can someone help me, how can the tick prices be saved in a sheet in excel?
I explain:
prices
6,689,196
6,689,016
6,688,796
6,689,022
any volatility index.
and so successively all those that appear are kept in an excel sheet.
I know that what I need is very rare, but if someone can help me, thank you very much ...

**Comment by IQBinary** [comment]
@pao11901 
![IQ Binary - (bot binary com)(2020 12 02_23_08_24)](https://user-images.githubusercontent.com/54183297/100910204-ad0deb80-34f3-11eb-8ede-e4b291d97879.jpg)
iqbinarybot@gmail.com
