### ISSUE TITLE
Deriv.bot  Bug | please fix problem on "Delayed run" block.

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#3116]
when load bot.xml to deriv bot "Delayed run" is disabled onload.
after enable then duplicate or drag another block to workspace  "Delayed run" turned into disable it self. please see my capture screen
![2020-12-05-02-38-44](https://user-images.githubusercontent.com/31925501/101231678-d28e2700-36a4-11eb-83a5-863e23bbb180.gif)
@aaron-binary 
@carol-binary 
@jy-binary 
@aminmarashi-binary 
@Mahboobeh-binary

**Comment by aaron-binary** [comment]
Hey @nextnaro,

We'll look into this and issue a fix soon.

Regards,
Aaron
