### ISSUE TITLE
Deriv graph purchase beacons bug

### ISSUE THREAD

**Issue by stranger-dev** [binary-com/binary-bot#3119]
I noticed that the beacons show differently in different  screen resolutions.

From the image below, I switched from the maccbook PRO display to the 1080p hp display and the beacons showed differently. its really trippy.
![Screen Shot 2020-12-07 at 09 20 37](https://user-images.githubusercontent.com/45882174/101317863-62cc9780-3870-11eb-94aa-503f351bfcb8.png)

Here are the screen resolutions:

<img width="581" alt="Screen Shot 2020-12-07 at 09 39 08" src="https://user-images.githubusercontent.com/45882174/101317884-6d872c80-3870-11eb-9063-bada109ae23b.png">

Is this a bug?

### Also, issue reports are not active on the deriv repo, so I posted this here.

**Comment by Kosta92** [comment]
What are those beacons? How do you activate them?
