### ISSUE TITLE
Running a BOT 24/7

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#3120]
Is it possible to run a binary Bot for 24hours a day?

Someone mentioned use of a virtual private server (VPS)

Please, how possible is it?

Even if it means linking the to a third party app.

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh
@MiithRanDir

**Comment by MiithRanDir** [comment]
I run the bot through VPS 24 hrs.

**Comment by alanvito1** [comment]
Yes, you can

**Comment by alanvito1** [comment]
Web base not, api ou mt5

**Comment by alanvito1** [comment]
https://github.com/alanvito1/superfree-binary-bot
Here you have some strategies to learn and build yourself strategy or buy any bot from anyone.

**Comment by eonuoha30** [comment]
> I run the bot through VPS 24 hrs.

Hello, 

How can I set up or use a vps for my bot?
