### ISSUE TITLE
[question] Help to Deploy test 

### ISSUE THREAD

**Issue by egarciahz** [binary-com/binary-bot#3123]
I have followed this question #2209 but I am not clear in which part of the code I add my appId

I will be using github for development and testing but I would like to know if I can deploy in a vps as an EC2 or something like that.

**Comment by aaron-binary** [comment]
Hey @egarciahz,

You can have a look at `src/common/appId.js` and add your App ID there. You can register one at https://developers.binary.com/applications/.

Regards,
Aaron
