### ISSUE TITLE
Notificador de resultados Perda e Ganho

### ISSUE THREAD

**Issue by Reitrader** [binary-com/binary-bot#3125]
Preciso fazer um bot que no bloco 4 ele cria uma lista de ganho e perda a partir dos resultados. Se ganhou = g, se perdeu = p. E de uma forma que quando eu escolho por exemplo: SE p,p,g,g,g ele me notifica. E que eu possa editar várias listas contendo outras sequência para ele me notificar com outros resultados: ex... SE p,g,p,p = notifica, SE g,p,g,g = notifica. E que independente da quantidade de resultados sequenciais que eu definir ele me notifica.

É possível fazer isso? Obrigado

**Comment by XYRubiYx** [comment]
Bom não é tão difícil posso te ajudar.... esses "a partir dos resultados" você se refere ao tipo de trade digítos?

**Comment by XYRubiYx** [comment]
Cara entendi +-, qual seria o tipo de contrato??
![image](https://user-images.githubusercontent.com/63131349/102927480-d75d2400-4475-11eb-8111-23fed48ab5cf.png)
Fiz um exemplo com par e impar, (no caso entrar no par quando der a sequencia p, q, p, p)

**Comment by XYRubiYx** [comment]
![image](https://user-images.githubusercontent.com/63131349/102927717-3f136f00-4476-11eb-82e6-fc065f31dbe6.png)
Eu deixei a notificação em azul para mostrar a sequencia em tempo real...
Quando fez a sequencia que eu pré-determinei ele ficou verde como você pode ver!

**Comment by Reitrader** [comment]
> ![image](https://user-images.githubusercontent.com/63131349/102927717-3f136f00-4476-11eb-82e6-fc065f31dbe6.png)
> Eu deixei a notificação em azul para mostrar a sequencia em tempo real...
> Quando fez a sequencia que eu pré-determinei ele ficou verde como você pode ver!

Nossa parece que ficou top... na verdade é para fazer sim uma catalogação e estudo dos resultados... tipo um simulador que vai avisar a hora de dar entradas... ainda estou desenvolvendo mas preciso desta parte...
Pode enviar? reinaldo.guaira@gmail.com, ou compartilhar aqui.... Gratidão mesmo, eu estava quebrando a cabeça. Valeu irmão...

**Comment by XYRubiYx** [comment]
Por aqui não da... eles não aceitam o formato .xml
eu fiz upload no mediafire: https://www.mediafire.com/file/a29lqjwi1rdasx8/botanalisesequencias.xml

**Comment by XYRubiYx** [comment]
Okay vou te enviar pelo gmail

**Comment by Reitrader** [comment]
> Okay vou te enviar pelo gmail

Valeu irmão... muito agradecido....

**Comment by XYRubiYx** [comment]
Dnd ;)
