### ISSUE TITLE
Result win/lost - notification

### ISSUE THREAD

**Issue by Reitrader** [binary-com/binary-bot#3126]
@ binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@ murali139
@baruga
@ghost
@Eshhh
I need to make a bot that in block 4 it creates a list of gains and losses from the results. If you won = w, if you lost = l. And in a way that when I choose for example w,w,l,l,l he notifies me. And that I can edit several lists containing other sequences for him to notify me with other results: examples: w, w, l, l = notify, another example: w, l,l,w,w,w,l = notify. And that regardless of the amount of sequential results that I define, it notifies me.

Is it possible to do that? I swear I'm trying for almost 2 days ... but I'm still at the beginning of my schedule ... can you help me?

I greatly appreciate your attention, and I await your response.

Hugs.

**Comment by cleberscr** [comment]
bom, creio que sim, não testei, mas não entendi por qual motivo você quer isso, não faz sentido

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/102814127-d14d4180-43a8-11eb-81e0-b86a5b1ed349.png)

**Comment by Reitrader** [comment]
Legal, mas a partir do resultado por exemplo: l,w,l,l no bloco 4, saindo essa sequência, colocar uma notificação que ele fez a sequência, e se ele não seguir a sequência ele volta no último resultado definido pela letra. Explicando melhor, é um notificador de perdas e ganhos, onde eu vou montar uma sequência de acordo com algumas estratégias, l,w,l,l é só o exemplo. A ideia é colocar o bot para comprar só par e quando surgir algumas das sequências ele me notifica... serão várias ex... l,l,l,w, ou w,w,w,w,l. No bloco 4 eu colocarei várias sequências, exemplo, extratégia w,w,l,l e os resultados sairem na sequência w,w,w, o terceiro w está errado, então ele volta para segundo w esperando um l, saindo o na sequência l ele formou w,w,l, e se depois  a quarta sequência sair w ele volta no começo da sequência, se sair o l, ele me notifica porque formou w,w,l,l   .... Espero ter explicado melhor. Ogrigado

**Comment by Reitrader** [comment]
obrigado @cleberscr , percebi que você tem um bom conhecimento de xml, Abraços.

**Comment by Reitrader** [comment]
@cleberscr ... pode ajudar de acordo com as últimas explicações?

**Comment by cleberscr** [comment]
> @cleberscr ... pode ajudar de acordo com as últimas explicações?

me chama no telegram @cleberscr
