### ISSUE TITLE
Running a bot for 24hours per day

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#3127]
Is it possible to run a binary Bot for 24hours a day?

Someone mentioned use of a virtual private server (VPS)

Please, how possible is it?

Even if it means linking the to a third party app.

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh
@MiithRanDir

**Comment by nextnaro** [comment]
just buy VPS service , Linux with GUI or windows. install browser login your binary or derive account > upload your bot to run on your VPS. and monitoring by remote desktop vnc or any remote software.

get cheap vps https://lowendbox.com/tag/vps/
software for remote desktop https://alternativeto.net/software/remote-desktop-connection/

**Comment by cunk888** [comment]
This my withdraw hahahha
![IMG_20201225_214753](https://user-images.githubusercontent.com/59736310/103136393-f4eeef80-46fa-11eb-8846-532487b2abb9.jpg)

**Comment by cunk888** [comment]
![IMG_20201225_214320](https://user-images.githubusercontent.com/59736310/103136396-089a5600-46fb-11eb-83da-f77e77e62721.jpg)
