### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by botfx45** [binary-com/binary-bot#3131]
I need to create a bot that just buy and sell regardless of whether you lose or win. its only function is to buy and sell with a martingale

I would thank you a lot

**Comment by XYRubiYx** [comment]
![image](https://user-images.githubusercontent.com/63131349/102899357-8c2d1c00-4449-11eb-91b0-c02bdb442ea8.png)
Like this?

**Comment by botfx45** [comment]
I knew it was something simple but I couldn't, thank you very much

**Comment by XYRubiYx** [comment]
No problem! If you have any questions, I'll be glad to answer them.

**Comment by botfx45** [comment]
just one more thing, I want to make it operate only when the rsi is 50 ... or half. could you help me with that idea

**Comment by XYRubiYx** [comment]
For sure I just need to know which rsi period you want and exactly which area of ​​rsi is call and put.

**Comment by botfx45** [comment]
Rsi 49 to 51 ... he can only enter those three intervals 49 50 and 51

**Comment by botfx45** [comment]
the period I modify it

**Comment by XYRubiYx** [comment]
Like this? https://www.mediafire.com/file/8m3k4lsz8vv7ikb/RSI-14-BuyandSell.xml

**Comment by botfx45** [comment]
haha you're a real crack brother that's how I wanted it ... thank you very much

**Comment by XYRubiYx** [comment]
It was nothing ;)

**Comment by MiithRanDir** [comment]
1. set variable is_buy as boolean
2. purchase IF is_buy THEN purchase RISE ELSE purchase FALL END IF
3. after purchase set is_buy = not is_buy

**Comment by botfx45** [comment]
hello the truth was not so good the bot, can you help me with a small modification please ... candle 1 CALL, candle 2 (no trade), candle 3 PUT, candle 4 (no trade) candle 5 CALL, candle 6 (no trade), candle 7 PUT .... and so on up to 9 candles

**Comment by botfx45** [comment]
hello the truth was not so good the bot, can you help me with a small modification please ... candle 1 CALL, candle 2 (no trade), candle 3 PUT, candle 4 (no trade) candle 5 CALL, candle 6 (no trade), candle 7 PUT .... and so on up to 9 candles

**Comment by botfx45** [comment]
up to level 9 martingale, they understand one candle if another does not one if another does not

**Comment by botfx45** [comment]
XxRubixX Please help me with the last man I swear it is the last. is that the other bot has failed me many times, so I want to modify it a little can you please and thank you very much really
