### ISSUE TITLE
HILO need help

### ISSUE THREAD

**Issue by nobleb2007** [binary-com/binary-bot#3132]
Kindly help change to Higher lower 

I will like the bot to follow this set up
The Stake sould be first 2 same .. 0.35 USD/0.35 USD 

and after 2loses in a row then Factor  3.5-> 3th Stake 1.5 USD / 4th  etc 
[HELP NEEDED.txt](https://github.com/binary-com/binary-bot/files/5733985/HELP.NEEDED.txt)
until it wins.

I wolud be very grateful

Many thanks in advance for your all support.

Best regards,
@XYRubiYx

**Comment by XYRubiYx** [comment]
Hi, change to Higher lower, how would it be?

**Comment by XYRubiYx** [comment]
![image](https://user-images.githubusercontent.com/63131349/103037605-04c7d180-454b-11eb-9ba6-f3d81b24b690.png)

I've already added 2 consecutive losses, only the explanation of the higter lower.... did you want to alternate each operation?

**Comment by nobleb2007** [comment]
Yes, if it is possible. If it wins, it should alternate but if it loses, if should analyze the market again before making any trade.

I hope you can help with that.
Thanks

**Comment by nobleb2007** [comment]
Please kindly help to implement the strategy. God bless you.
