### ISSUE TITLE
business deal

### ISSUE THREAD

**Issue by smarttrook** [binary-com/binary-bot#3133]
I found a bot works in binary.com <<< on YouTube and I like it, but when loses a trade, it is increases the amount of the trade and I want to change that
 and i will pay for that

**Comment by nextnaro** [comment]
?woh em llet

**Comment by eonuoha30** [comment]
Tell me about it.

eonuoha30@gmail.com

**Comment by IQBinary** [comment]
> 
> 
> I found a bot works in binary.com <<< on YouTube and I like it, but when loses a trade, it is increases the amount of the trade and I want to change that
> and i will pay for that
iqbinarybot@gmail.com
