### ISSUE TITLE
Upload de robô pelo celular 

### ISSUE THREAD

**Issue by zaifel7** [binary-com/binary-bot#3138]
Olá, preciso mandar um bot para a deriv pelo celular mas não estou conseguindo, é possível?

Depois de fazer o upload do robô preciso fazer algumas mudanças na configuração também.

**Comment by aaron-binary** [comment]
Hey @zaifel7,

We only allow loading strategies on the responsive version of DBot, you cannot make modifications (other than changing the fields on input blocks).

Regards,
Aaron
