### ISSUE TITLE
SMA 50 strategy needs BOT definition -  Newbie

### ISSUE THREAD

**Issue by doehlma** [binary-com/binary-bot#3139]
is somebody here in community who can answer or work on it  please ??

=========================================================================
Hello all together,

I want to ask the community and especially experts, whether someone would be so kind to help me and define
Bot for following concept:

a) If Market (e.g. Index75)  is in **Up trend** and

**Candle start below SMA 50 -> and closing above SMA 50** 

**-> Bot should start ~ 5 seconds before candle ends a trade for 1 min.**

b) If Market (e.g. Index75)  is in Down trend the same scenery but vice versa.

For case a) and better understanding I attached the explanation picture. 

Many thanks in advance for your support and time.

![Concept](https://user-images.githubusercontent.com/49290510/103363813-5d9fe880-4abc-11eb-8dd8-60f5a782b75d.jpg)

**Comment by doehlma** [comment]
Hello,

is somebody here in community who can help me with this request ??

Thanks in advance for support

**Comment by chatwoodaddison** [comment]
Email me at chatwoodaddison3@gmail.com
