### ISSUE TITLE
Anyone who has a way to manage money  for 50% win rate.

### ISSUE THREAD

**Issue by MiithRanDir** [binary-com/binary-bot#3141]
Because sometimes the win rate is 50% or more.
But in some cases, it will be a winning streak, losing streak in several bets.
Therefore, when using **martingale**, sometimes it will cost a lot of money.
Anyone who has a money management the way to secure capital please advise.

**Example for martingale**

1 - **W**
2 - **W**
3 - **W**
4 - **W**
5 - **W**
6 - **W**
7 - _L_
8 - _L_
9 - _L_
10 - _L_

The win rate is 60%, but having four consecutive losses can also cost a lot of money 😅.

The system I tested But it doesn't work

- Martingale
- Anti martingale
- Fibonacci
- Oscar's Grin
- d'Alembert
- Flat bet
- Labouchere
- Double profit

**Comment by alanvito1** [comment]
Hello, look here bot 0005, shared mg, it recuperates with few plays, no double, about 15% each play to recuperate.
 [Here](https://github.com/alanvito1/superfree-binary-bot)

**Comment by MiithRanDir** [comment]
@alanvito1 Thank you for suggesting
I tried the 0005 bot already, but the DIGIT DIFFER bot is very risky if it gets wrong.
I did not test yet 10 orders, 1 wrong order already.
![2021-01-02_201607](https://user-images.githubusercontent.com/5079543/103458133-be872500-4d37-11eb-85d0-d4f6dabc1d2b.jpg)

**Comment by alanvito1** [comment]
See bot 0005

**Comment by alanvito1** [comment]
You can optimize this system, at me see it's maybe the better way for risk control

**Comment by alanvito1** [comment]
> @alanvito1 Thank you for suggesting
> I tried the 0005 bot already, but the DIGIT DIFFER bot is very risky if it gets wrong.
> I did not test yet 10 orders, 1 wrong order already.
> ![2021-01-02_201607](https://user-images.githubusercontent.com/5079543/103458133-be872500-4d37-11eb-85d0-d4f6dabc1d2b.jpg)

Aah, import this money management for your strategy

**Comment by Zeemi20** [comment]
@alanvito1  can you help me in this issue, how to make this section of bot : if 4 (1 minute) candles are rising in a row sell and if 4 (1 minute) candles are falling then buy.

**Comment by overwatch873** [comment]
> Hello, look here bot 0005, shared mg, it recuperates with few plays, no double, about 15% each play to recuperate.
> [Here](https://github.com/alanvito1/superfree-binary-bot)

How do i download those....i am failing to

**Comment by alanvito1** [comment]
> > Hello, look here bot 0005, shared mg, it recuperates with few plays, no double, about 15% each play to recuperate.
> > [Here](https://github.com/alanvito1/superfree-binary-bot)
> 
> Hi....How do i download those bots....i am failing to

try copy the script and paste in your file xml (blank)

**Comment by overwatch873** [comment]
> > > Hello, look here bot 0005, shared mg, it recuperates with few plays, no double, about 15% each play to recuperate.
> > > [Here](https://github.com/alanvito1/superfree-binary-bot)
> > 
> > 
> > Hi....How do i download those bots....i am failing to
> 
> try copy the script and paste in your file xml (blank)
> 
> or download and change .txt to .xml
> 
> [BOT - 0005 - Digits - Shared Loss.txt](https://github.com/binary-com/binary-bot/files/5907690/BOT.-.0005.-.Digits.-.Shared.Loss.txt)

Thanks a lot mate

**Comment by overwatch873** [comment]
> > > Hello, look here bot 0005, shared mg, it recuperates with few plays, no double, about 15% each play to recuperate.
> > > [Here](https://github.com/alanvito1/superfree-binary-bot)
> > 
> > 
> > Hi....How do i download those bots....i am failing to
> 
> try copy the script and paste in your file xml (blank)
> 
> or download and change .txt to .xml
> 
> [BOT - 0005 - Digits - Shared Loss.txt](https://github.com/binary-com/binary-bot/files/5907690/BOT.-.0005.-.Digits.-.Shared.Loss.txt)

Hi bro i have one last request can you send me the bb + gap bot ...i tried what you told me to copy and paste the txt file to a blank xml page ...
But when i try to upload the bot on the binarybot platform it says unrecognized format...i dont know what am doing wrong
