### ISSUE TITLE
haha you're a real crack brother that's how I wanted it ... thank you very much

### ISSUE THREAD

**Issue by allensilvaa** [binary-com/binary-bot#3144]
haha you're a real crack brother that's how I wanted it ... thank you very much

_Originally posted by @botfx45 in https://github.com/binary-com/binary-bot/issues/3131#issuecomment-749635549_

compartilha o xml por favor? ;)

**Comment by botfx45** [comment]
Send me an email and I'll pass it on to you tomorrow. Fabiobg121@gmail.com

**Comment by botfx45** [comment]
listo ya lo envié ;)
