### ISSUE TITLE
Digit Differ Bot - Prediction

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#3145]
Hello everyone,

Good Day. I tried to create a very simple Digit Differ Bot as shown below: 

![image](https://user-images.githubusercontent.com/62483125/103799328-d223ea00-50af-11eb-8cb3-a7dcb1bae736.png)

The aim was to create a bot which would consider the last digit of the current tick as the prediction and predict that the last digit of the next tick would differ.

The trade was  successful:

![image](https://user-images.githubusercontent.com/62483125/103800492-5d51af80-50b1-11eb-9a3a-db5a0d53d3cd.png)

Upon analyzing I found out this:

![image](https://user-images.githubusercontent.com/62483125/103800941-e5d05000-50b1-11eb-9f0b-2178194f11ab.png)

As seen in the picture above, the prediction should have been "1" but it was "2". 

I created  another bot where I set the prediction as the last digit of the 4th tick from the end. The prediction  was not right there as well. 

Can anyone please tell me what am I doing wrong?

Thanks in advance.

**Comment by MiithRanDir** [comment]
Bot delay

**Comment by binarybotbegginer** [comment]
> Bot delay Is there a way to overcome this?

**Comment by binarybotbegginer** [comment]
> Bot delay

Is there a way to overcome this problem?

**Comment by binarybotbegginer** [comment]
I even tried using the last digit of the 2nd, 3rd or 4th tick . It doesn't seem to work. Can anyone help?
@binary-ex-machina 
@aaron-binary
