### ISSUE TITLE
Can anyone help me to execute for the lowest number?

### ISSUE THREAD

**Issue by indraIMSA** [binary-com/binary-bot#3146]
i want bot to take over when the lowest number is selected

**Comment by chatwoodaddison** [comment]
Inbox me in my email, I can help 
.
Chatwoodaddison3@gmail.com

**Comment by indraIMSA** [comment]
Thx for the offer, i already figure it out

Cheers

Dikirim dari iPhone saya

Pada 20 Jan 2021, pukul 20.48, Chatwoodaddison <notifications@github.com> menulis:

**Comment by chatwoodaddison** [comment]
You're Welcome
