### ISSUE TITLE
Contribuição para o grupo

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3147]
tenho um bot que faz uma media de $5 a $10 dólares por dia, trabalha 24hs e só precisa de $202,00 dólares inicial para operar!!!
Trabalha hospedado na nuvem da amazon, não pago nada porque criei um TS de teste por 1 ano!!!
Faço minhas coisas durante o dia e de 2 em 2 dias eu faço saque!!

Até agora não me fez vergonha!!!kkk
[BICHO_PREGUIÇA.txt](https://github.com/binary-com/binary-bot/files/5781585/BICHO_PREGUICA.txt)

**Comment by contatodeanet** [comment]
![image](https://user-images.githubusercontent.com/43180630/104014564-02dc5000-5192-11eb-9ec4-601768a44e3d.png)

**Comment by allensilvaa** [comment]
Ah quantos dias você vem operando com o bot?
quantos loss seguidos já chegou ?

**Comment by contatodeanet** [comment]
> Ah quantos dias você vem operando com o bot?
> quantos loss seguidos já chegou ?

Já tem uns 15 dias rodando, não tem nenhum loss seguido, ele apenas erra uma vz faz a correção do valor e segue novamente....bem simples o bot!!! pra quem tem paciência ele é maravilhoso!!! eu nem fico mais olhando!!!kkk sei que se ele errar 2 vz seguidas o valor que eu vou perder vai ser 202 dólares, nada de ter susto ou quebrar a banca. estou estudando uma forma dele ficar mais assertivo, assim que conseguir posto a atualização aqui!!

**Comment by cleberscr** [comment]
> > Ah quantos dias você vem operando com o bot?
> > quantos loss seguidos já chegou ?
> 
> Já tem uns 15 dias rodando, não tem nenhum loss seguido, ele apenas erra uma vz faz a correção do valor e segue novamente....bem simples o bot!!! pra quem tem paciência ele é maravilhoso!!! eu nem fico mais olhando!!!kkk sei que se ele errar 2 vz seguidas o valor que eu vou perder vai ser 202 dólares, nada de ter susto ou quebrar a banca. estou estudando uma forma dele ficar mais assertivo, assim que conseguir posto a atualização aqui!!

já tive essa ideia, mas se ta rodando até agora sem loss, parabéns, mas faltou um pouco de criatividade no martingale, procure entender mais sobre calculos e você vai ficar mais despreocupado com isso e de 202 dolares, pode precisar até menos de 100 dolares. basta pensar

**Comment by JULIANO2532** [comment]
Apareceu arquivo não suportado, poderia enviar novamente?

**Comment by viniciusctt** [comment]
> tenho um bot que faz uma media de $5 a $10 dólares por dia, trabalha 24hs e só precisa de $202,00 dólares inicial para operar!!!
> Trabalha hospedado na nuvem da amazon, não pago nada porque criei um TS de teste por 1 ano!!!
> Faço minhas coisas durante o dia e de 2 em 2 dias eu faço saque!!
> 
> Até agora não me fez vergonha!!!kkk
> [BICHO_PREGUIÇA.txt](https://github.com/binary-com/binary-bot/files/5781585/BICHO_PREGUICA.txt)

fala querido eu estou testando... gostaria de entender um pouco melhor o martingale que você fez ali.... teria como dar uma implementada talvez... aguardo retorno
