### ISSUE TITLE
Binary Bot For Selected Last Digit

### ISSUE THREAD

**Issue by nickshag** [binary-com/binary-bot#3150]
Hi Guys,

I need to create bot for following strategy, I'm new to here & still no idea how to build a bot for trading. If anyone could help me, appreciate a lot!

If LDP appears 2 times continuously, place 2 Over contract. (5,3,7,7,9,5,1,2,3,6,8,5,3,3,8,6,3,1,**2,2** - Place the order)
Its better we can change two time LDP as desire.

Hope you'll help me with this guys, Thanks!

**Comment by eonuoha30** [comment]
If the last digit appears twice, do you want us to predict a 'differ trade' or 'over/under trade' ?

**Comment by gbeke72** [comment]
I need to create bot for following strategy, I'm new to here & still no idea how to build a bot for trading. If anyone could help me, appreciate a lot!
@gbekeloluwa72
