### ISSUE TITLE
Last digit stats 

### ISSUE THREAD

**Issue by Manoj551998** [binary-com/binary-bot#3151]
How to get the lowest digit percentage in last digit stats for volatility 10  then number of ticks 100. If anybody know help me
![Screenshot_20210110-201438](https://user-images.githubusercontent.com/30549738/104126089-b9058c80-5380-11eb-9990-6a53eb01f4b7.png)

**Comment by cleberscr** [comment]
https://github.com/Fruitfella/ROBOT-binary/issues/35
