### ISSUE TITLE
Please help me to create this money management

### ISSUE THREAD

**Issue by aakanksha2000** [binary-com/binary-bot#3153]
Hello friends..please help me to create this money management

0.35 win 
0.35 loss
0.35 loss
0.35 loss
0.35 win
1.54 win
0.35 win

Thanks !

**Comment by overwatch873** [comment]
Created it a long time ago....let me save you the trouble....ts just as bad as martingale...because you go 15 trades without double wins and have huge looses inbetween

**Comment by aakanksha2000** [comment]
@overwatch873 can you share that bot with me
