### ISSUE TITLE
build a binary bot  for binary.com

### ISSUE THREAD

**Issue by TonnyBucky2** [binary-com/binary-bot#3154]
i need someone to create me a bot with just one strategy
that is digit under  1 tick  digit 4

**Comment by eonuoha30** [comment]
1 tick 

And 

UNDER 4 ?

**Comment by TonnyBucky2** [comment]
yes sir

**Comment by TonnyBucky2** [comment]
but using last ticks

eg  190.5893
 190.4672



           190.6841
 190.8563
  190.5678
  190.3876
 now i mean
 3,2,1,3 then above 4
 8,6



                 now you purchase under
    prediction should be 4

**Comment by eonuoha30** [comment]
The bot should trade based on the LAST DIGIT of the LAST TICK?

If the last digit is below 5, it trades over 4

If the last digit is above 4, it trades under 4 ?

**Comment by eonuoha30** [comment]
Here's your bot (rename it from .txt  TO .xml)

[Your bot.txt](https://github.com/binary-com/binary-bot/files/5824465/Your.bot.txt)

**Comment by eonuoha30** [comment]
For a little fee, I can help you fix STOP LOSS, TAKE PROFIT or any MONEY MANAGEMENT PLAN to your bot.

Or help you create a new one according to your strategy/ideas.

I deliver within 24 hours

Send me email on eonuoha30@gmail.com

Or WhatsApp/telegram/calls +2348134998827

**Comment by NEWBIE3232** [comment]
No need to collect fee na bro. 
Na help everyone dey na..
If you fit help am just run am for am.

**Comment by NEWBIE3232** [comment]
@TonnyBucky2 please drop your email, so I can send the prototype of the bot to you..

**Comment by VERTO13** [comment]
> @TonnyBucky2 please drop your email, so I can send the prototype of the bot to you..

Can you send me to try it out too please, vitor.emma99@hotmail.com

**Comment by TonnyBucky2** [comment]
tonnybucky2@gmail.com

**Comment by eonuoha30** [comment]
> No need to collect fee na bro.
> Na help everyone dey na..
> If you fit help am just run am for am.


I guess, you didnt see the bot I attached to the text

**Comment by taikhoan1209** [comment]
> i need someone to create me a bot with just one strategy
> that is digit under 1 tick digit 4

can you contact me if you want

**Comment by Zeemi20** [comment]
@eonuoha30 can you help me in this issue, how to make this section of bot : if 4 (1 minute) candles are rising in a row sell and if 4 (1 minute) candles are falling then buy.

**Comment by samyelsayed** [comment]
> The bot should trade based on the LAST DIGIT of the LAST TICK?
> 
> If the last digit is below 5, it trades over 4
> 
> If the last digit is above 4, it trades under 4 ?

I eant ask you anything

**Comment by samyelsayed** [comment]
> For a little fee, I can help you fix STOP LOSS, TAKE PROFIT or any MONEY MANAGEMENT PLAN to your bot.
> 
> Or help you create a new one according to your strategy/ideas.
> 
> I deliver within 24 hours
> 
> Send me email on eonuoha30@gmail.com
> 
> Or WhatsApp/telegram/calls +2348134998827

If you specify that the bot does not enter a trade unless it is the last number 1 or 2, then this will be the entry spot?

**Comment by eonuoha30** [comment]
> > For a little fee, I can help you fix STOP LOSS, TAKE PROFIT or any MONEY MANAGEMENT PLAN to your bot.
> > Or help you create a new one according to your strategy/ideas.
> > I deliver within 24 hours
> > Send me email on [eonuoha30@gmail.com](mailto:eonuoha30@gmail.com)
> > Or WhatsApp/telegram/calls +2348134998827
> 
> If you specify that the bot does not enter a trade unless it is the last number 1 or 2, then this will be the entry spot?

Send me mail let's talk.

eonuoha30@gmail.com
