### ISSUE TITLE
Digit and Spot Bot

### ISSUE THREAD

**Issue by NEWBIE3232** [binary-com/binary-bot#3155]
Please someone should create a bot with this condition.
.
If the first last digit is 6 and spot colour is B  and the second last digit is 6 and spot colour is R  then purchase FALL after 5 tick
i.e if tick 1 is (6B) and Tick 2 is (6R) then purchase Fall .
108.456 (B) 
108.296 (R)
That is the spot price moved from the blue zone to the Red zone but the last digit is still 6.
Then purchase Fall
@saidforex26

**Comment by eonuoha30** [comment]
....doesn't make ant difference.

It still won't last long before Crushing your bankroll.

**Comment by saidforex26** [comment]
> Please someone should create a bot with this condition.
> .
> If the first last digit is 6 and spot colour is B and the second last digit is 6 and spot colour is R then purchase FALL after 5 tick
> i.e if tick 1 is (6B) and Tick 2 is (6R) then purchase Fall .
> 108.456 (B)
> 108.296 (R)
> That is the spot price moved from the blue zone to the Red zone but the last digit is still 6.
> Then purchase Fall
> @saidforex26

[66 BR BINARY.BOT.zip](https://github.com/binary-com/binary-bot/files/5825934/66.BR.BINARY.BOT.zip)
