### ISSUE TITLE
Help in strategy

### ISSUE THREAD

**Issue by Zeemi20** [binary-com/binary-bot#3157]
Hello! 
Any one knows how to make this : if 4 (1 minute) candles are rising in a row sell and if 4 (1 minute) candles are falling then buy. 
I tried a lot but couldn’t find a way to do it 

Thanks in advance

**Comment by cleberscr** [comment]
![Uploading image.png…]()

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/105100171-a4657a80-5a8b-11eb-8a84-1dd3d6cd022e.png)

**Comment by Zeemi20** [comment]
@cleberscr Thank you!!
