### ISSUE TITLE
هل هنالك اي حد عربي هنا ?

### ISSUE THREAD

**Issue by ahmadhus** [binary-com/binary-bot#3158]
مرحبا جميعا 
ممكن تخبرونا كيف بتسحبو فلوسكم لبلادكم العربية ؟
انا من الاردن وعم بواجه صعوبه في  سحب الاموال .

**Comment by Zeemi20** [comment]
بتقدر تسحبهم مباشرة على بطاقتك او على احد برامج الوسطاء  الي بيتعاملو معهم

**Comment by ahmadhus** [comment]
مساء الخير
حاولت مسبقا سحب المبلغ على البطاقه ولم يصل المبلغ ولم استطيع ارجاعه للمنصه 
من اي دولة انت ؟
وايش في برامج وساطه بتوصل للاردن ؟
مشكور

**Comment by Zeemi20** [comment]
مساءالنور 
اذا صار اكثر من ١٠ ايام على التحويل و ما وصل ولا رجع للمنصة لازم تتصل على البنك يلي مصدِّر الكارد، لان هيك بكون في غلط اما انو البنك حجز عليها لغايات معرفة المصدر او رفض استلامها، و بالحالتين لازم تتواصل معهم وتاخد اثبات منهم او رقم التحويل عشان تبعت للمنصة و يرجعو المبلغ بحسابك

انا من العراق بس عشت و تربيت بالاردن..

**Comment by Zeemi20** [comment]
حالياً لازم تتأكد من WebMoney (حسب علمي كانو يتعاملو معهم Binary.com) اذا بتقدر تسحب عليهم، اعمل حساب و اسحب من عندهم على حسابك البنكي لان ما عندهم تأخير (عن تجربة شخصية)

**Comment by ahmadhus** [comment]
> مساءالنور
> اذا صار اكثر من ١٠ ايام على التحويل و ما وصل ولا رجع للمنصة لازم تتصل على البنك يلي مصدِّر الكارد، لان هيك بكون في غلط اما انو البنك حجز عليها لغايات معرفة المصدر او رفض استلامها، و بالحالتين لازم تتواصل معهم وتاخد اثبات منهم او رقم التحويل عشان تبعت للمنصة و يرجعو المبلغ بحسابك
> 
> انا من العراق بس عشت و تربيت بالاردن..

يا اهلا باهل العراق الغاليين 

ممكن اتواصل معك بالايميل او اي اكاونت بتفضله 

لانه في كثير تفاصيل لعملية التحويل وللان البنك بيرفض يستلم ومنصة باينري بترفض ارجاع المبلغ 

مشكور

**Comment by Zeemi20** [comment]
اكيد مافي اي مشكلة.. الايميل : zeemids@yahoo.com

**Comment by ahmadhus** [comment]
@Zeemi20
تم الارسال صديقي
