### ISSUE TITLE
Do you have a GOOD STRATEGY or IDEA? read this now...

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#3161]
Hello....

This forum aims at helping you with your strategies and clarifying tough issues regarding binary trading.

It might take hours, days or weeks to get a response.

If responded to, you might still have lots of ideas/strategies you'd love to try out (but not willing to wait again).

Anyway....

You can have all your strategies and ideas worked on 'immediately' for just a little token.

Send me an email now through:

eonuoha30@gmail.com

Or +2348134998827 (Calls, Whatsapp, telegram)

Best regards.

**Comment by Phi-thagoras** [comment]
Hi need a binary bot/ a tutorial for a bot that can get numbers from an external website (i.e external to Binary.com/Deriv.com) or a manually created list of numbers stored in excel file or xml file stored external to the main website. that external list of number is to be fed into the bot as a prediction

**Comment by eonuoha30** [comment]
> Hi need a binary bot/ a tutorial for a bot that can get numbers from an external website (i.e external to Binary.com/Deriv.com) or a manually created list of numbers stored in excel file or xml file stored external to the main website. that external list of number is to be fed into the bot as a prediction

Hello, 

Check out #3161
