### ISSUE TITLE
Last Two digits - Digit Differ Strategy

### ISSUE THREAD

**Issue by AIY-007** [binary-com/binary-bot#3163]
Good Day. Is there a way to create a bot which starts when the last two digits are equal? I wanted to create a bot which would do the following:
Starts if the last two digits of the tick value are the same. For eg: 1628.44
@hotmatrixx 
![Last Digit 442](https://user-images.githubusercontent.com/71758957/105569322-61e5bb80-5d73-11eb-94d5-2759f98cd385.jpg)

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/105621373-8e3a2000-5de5-11eb-9b4f-655fb8b0834d.png)

**Comment by eonuoha30** [comment]
It would be easier for him/her if you drop the XML file

**Comment by AIY-007** [comment]
@cleberscr 
Thank you very much.

**Comment by AIY-007** [comment]
@cleberscr It didn't work As i want. For example Starts if the last two digits of the tick value are the same. For eg: 1628.00, 1629.11, 1628.22, 1628.33, 1628.44, 1628.55, 1628.66, 1628.77, 1628.88, 1628.99

**Comment by chatwoodaddison** [comment]
@AIY-007 
Its possible to built the bot 
Email me: chatwoodaddison3@gmail.com 
I can help.

**Comment by cleberscr** [comment]
> @cleberscr Não funcionou como eu queria. Por exemplo, começa se os dois últimos dígitos do valor do tick forem iguais. Por exemplo:
> XXXX.00
> XXXX.11
> XXXX.22
> XXXX.33
> XXXX.44
> XXXX.55
> XXXX.66
> XXXX.77
> XXXX.88
> XXXX.99 Espero que você entenda


[last digit.zip](https://github.com/binary-com/binary-bot/files/5874662/last.digit.zip)

**Comment by AIY-007** [comment]
@cleberscr Thanks again.You are a good teacher For me. May only good things come into life

**Comment by AIY-007** [comment]
@cleberscr Would it be possible if adjust Prediction Equal to last two digits of the tick value are the same. For eg: 
XXXX.00 = Prediction 0
XXXX.11 = Prediction 1
XXXX.22 = Prediction 2
XXXX.33 = Prediction 3
XXXX.44 = Prediction 4
XXXX.55 = Prediction 5
XXXX.66 = Prediction 6
XXXX.77 = Prediction 7
XXXX.88 = Prediction 8
XXXX.99 = Prediction 9

**Comment by cleberscr** [comment]
unfortunately not, because when the last digit is 0 and set the forecast to 0, there will be a delay and it will not work, some programmers said they have to do it straight from the api, you know?

**Comment by AIY-007** [comment]
Unfortunately you can't build it. I invested in bot binary And the center has lost enough money. You have strategy Advice  or bot overcome market or not?

**Comment by cleberscr** [comment]
> @cleberscr Infelizmente você não pode construí-lo. Eu investi no binário do bot E o centro perdeu dinheiro suficiente. Você tem conselhos de estratégia ou bot para superar o mercado ou não?

the advice is to divide your stop gain into partial goals
Example:
 stop gain: $20
when you wake up: 5
lunch: 5
afternoon coffee: 5
dinner or before sleeping: 5

4x5 = 20

**Comment by AIY-007** [comment]
@cleberscr Thanks for the advice.
