### ISSUE TITLE
Bot não finalizou contrato

### ISSUE THREAD

**Issue by ThiagoThiel** [binary-com/binary-bot#3165]
Tenho usado com frequência um bot, mas hoje por algum motivo ele não finalizou o contrato em uma de suas operações, e justo em um contrato que ganhei, gostaria de que creditassem para  mim o valor ganho, mas antes me pediram para entrar em contato com esse suporte de bot, gostaria de saber qual o próximo passo a seguir, obrigado

número de referência do contrato não finalizado é 54516886821

**Comment by chatwoodaddison** [comment]
@ThiagoThiel 
Email me: @chatwoodaddison3@gmail.com 
I can help
