### ISSUE TITLE
binary bot  digit differs

### ISSUE THREAD

**Issue by mdtazmir1** [binary-com/binary-bot#3166]
ro help me pls i need one digit differs bot
like only last digit 0 and 0 end after trad not before fast time 0 coming not trad two times 0 coming after tradneed- help me
![dg](https://user-images.githubusercontent.com/67690709/105808510-e70de200-5fb8-11eb-9a5c-cdf8819392e1.png)

**Comment by chatwoodaddison** [comment]
Email me: chatwoodaddison3@gmail.com 
I can help

**Comment by mdtazmir1** [comment]
yes bro

**Comment by chatwoodaddison** [comment]
Email me directly so I can share the file with you..
Not from here 
Send a direct mail to my email address
