### ISSUE TITLE
can anyone help to change ldp or prediction after we win?

### ISSUE THREAD

**Issue by indraIMSA** [binary-com/binary-bot#3167]

**Comment by JenggotSantuy** [comment]
which bot to change?

**Comment by indraIMSA** [comment]
Match, after win change to next number 

Start prediction 3 after winning i want the prediction 7

Dikirim dari iPhone saya

Pada 26 Jan 2021, pukul 20.01, JenggotSantuy <notifications@github.com> menulis:

**Comment by JenggotSantuy** [comment]
if it's this simple maybe just setting directly in block 4 is it what you mean?

![IMG_20210127_004250](https://user-images.githubusercontent.com/61324577/105883423-6a6f1800-6039-11eb-95cb-0f9330ad6a43.JPG)

**Comment by indraIMSA** [comment]
I done that, i mean after first win the prediction change to another prediction after the second win

Because i want the prediction from 3 to 7 to 0

Dikirim dari iPhone saya

Pada 27 Jan 2021, pukul 00.49, JenggotSantuy <notifications@github.com> menulis:

**Comment by indraIMSA** [comment]
And after that i want to loop back to the prediction 3 to 7 to 0 again

Thx before

Dikirim dari iPhone saya

Pada 27 Jan 2021, pukul 00.49, JenggotSantuy <notifications@github.com> menulis:

**Comment by eonuoha30** [comment]
#3161
