### ISSUE TITLE
Need to help to create this binary bot.

### ISSUE THREAD

**Issue by HansikA1201** [binary-com/binary-bot#3170]
I need help to create this digit differ bot, plz help!
@binary-ex-machina
@saidforex26
@Fruitfella
![D938FF37-D275-4EBF-8BA1-0A75A166E8E6](https://user-images.githubusercontent.com/77802536/105888860-88397e80-6033-11eb-821a-73872d551b86.jpeg)

**Comment by eonuoha30** [comment]
https://github.com/binary-com/binary-bot/issues/3161
