### ISSUE TITLE
Bug na binary bot

### ISSUE THREAD

**Issue by moura98** [binary-com/binary-bot#3175]
so I have a strategy that consists of several robots open in different windows of the computer running 24 hours a day, this robot does analysis and enters the market accordingly, but when the opportunity comes, the bot suddenly stops and does not enter the operation, so I have to play the bot again for it to start operating again and wait for a new opportunity. Can anyone help me with this issue?

**Comment by Jonni81** [comment]
Какая ошибка у вас выходит?

**Comment by moura98** [comment]
у меня есть стратегия, которая состоит из нескольких доступных в разных окнах компьютеров, работающих 24 часа в сутки, этот робот анализирует и входит в рынок соответственно, но когда появляется возможность, бот внезапно останавливается, и тогда мне не нужно играть бот снова, чтобы снова начать торговать и ждать новой возможности. Может ли кто-нибудь помочь мне с этим вопросом?
u menya yest' strategiya, kotoraya sostoit iz neskol'kikh dostupnykh v raznykh oknakh komp'yuterov, rabotayushchikh 24 chasa v sutki, etot robot analiziruyet i vkhodit v rynok sootvetstvenno, no kogda poyavlyayetsya vozmozhnost', bot vnezapno ostanavlivayetsya, i togda mne ne nuzhno igrat' bot snova, chtoby snova nachat' torgovat' i zhdat' novoy vozmozhnosti. Mozhet li kto-nibud' pomoch' mne s etim voprosom?

**Comment by Jonni81** [comment]
Русский?)))
Я помогу тебе. Только мне нужно понять принцип работы бота и ошибки

**Comment by Jonni81** [comment]
пиши сюда.            kazarinov.treiding@yandex.ru

**Comment by moura98** [comment]
бот выполняет подсчет свечей из 12 последовательных свечей в том же направлении, что и бот делает входную ставку на разворот рынка, я открываю 12 окон в браузере 1 окно для бычьего рынка, чтобы оценить волатильность 100, и оставляю ботов работать весь день, но когда соблюдаются условия для входа бота в операцию, которую он приостанавливает, не входит в операцию там, я должен нажать на игру и снова ждать 12 свечей подряд, чтобы бот вошел в операцию, и каждый раз, когда я меняю конфигурация бота та же проблема
bot vypolnyayet podschet svechey iz 12 posledovatel'nykh svechey v tom zhe napravlenii, chto i bot delayet vkhodnuyu stavku na razvorot rynka, ya otkryvayu 12 okon v brauzere 1 okno dlya bych'yego rynka, chtoby otsenit' volatil'nost' 100, i ostavlyayu botov rabotat' ves' den', no kogda soblyudayutsya usloviya dlya vkhoda bota v operatsiyu, kotoruyu on priostanavlivayet, ne vkhodit v operatsiyu tam, ya dolzhen nazhat' na igru i snova zhdat' 12 svechey podryad, chtoby bot voshel v operatsiyu, i kazhdyy raz, kogda ya menyayu konfiguratsiya bota ta zhe problema

**Comment by cleberscr** [comment]
> então tenho uma estratégia que consiste em vários robôs abertos em diferentes janelas do computador rodando 24 horas por dia, esse robô faz análises e entra no mercado de acordo, mas quando surge a oportunidade, o bot para de repente e não entra na operação, então tenho que jogar o bot novamente para começar a operar novamente e esperar por uma nova oportunidade. Alguém pode me ajudar com essa questão?

me chama no telegram @cleberscr

**Comment by moura98** [comment]
Vou te chamar 👍
