### ISSUE TITLE
D'Alembert Strategy enhancement

### ISSUE THREAD

**Issue by huguh** [binary-com/binary-bot#318]
Hello everybody, I'm trying to attach a funcionality to dalembert strategy but I'm missing something. Cant get it right. I guess I know nothing about putting those blocks together. 

Heres the deal, in the first attached picture we have the original ready made D'Alembert Strategy as downloaded in binary.com shop. Yesterday I asked the coder Amin Marashi for a way to set predifined parameters for "expected profit", maximum loss" and "trade amount" so I dont have to fill the dialog boxes that appears every time in the beginning  when a new set of trades is open. Thats because of the high frequency trading strategy Im testing. With predifined parameters the process would get more eficient. 
![1](https://user-images.githubusercontent.com/30154394/28177023-cfeb03f8-67cf-11e7-8194-c659e7022213.png)

Well he was very kind and helped me as he already had made a block of parameters for this exact issue. He gave me the two adresses below
https://gist.githubusercontent.com/aminmarashi/9f7d6ae54ed0448c013c4e77d829710f/raw/6768888b4b0fef32c2dabaf51434b3a507b20c4f/Screen%2520Shot%25202017-07-13%2520at%252011.02.15%2520AM.png

https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/dalembert_predefined_params.xml

Well, Ive tried many ways to put 1 plus 1 together but my coding skills is absolutely zero if I have any. When I put the bloks together as it shows in the first adress Amin gave me, it occurs that when I title the new block to "D'Alembert Trade Amount" it automatically changes to "D'Alembert Trade Amount2" as you can see in the second picture Ive attached here. So I dont understand how to make this reference. And also I dont know what to do with the adress of the raw code he had gave me. 
![3](https://user-images.githubusercontent.com/30154394/28177216-79f0f308-67d0-11e7-9a42-8a936a489911.png)

So any enlightenment I get here would be very much appreciated. Thank you everybody

**Comment by Fruitfella** [comment]
@huguh 
That happened because u use 2 D'Alemberts, 1 from the shop and 1 from amin.
The easiest way to fix that is : 
1. refresh ur browser
2. load only 1 xml. the one that amin gave u.
3. run the bot.
4. tada! good luck!

**Comment by huguh** [comment]
Hum nope, then i get "D'Alembert Trade Amount" in the block for the parameters, but in 'stake' it changes to "D'Alembert Trade Amount (deleted)" if i change the original xml for the one amin gave me as its shown on the print. By the way, if it adds any information, the adress for the original xml is https://gist.githubusercontent.com/aminmarashi/0feb52b5802519cd4157b612d9bd3471/raw/dalembert.xml

![5](https://user-images.githubusercontent.com/30154394/28183265-334f1cd0-67e5-11e7-9e68-6a22207a3c11.png)

**Comment by Fruitfella** [comment]
of course u did it wrong, otherwise there wont be problem. 😛 
did u download/save the xml from the link amin gave u?
1. Right click the <a href="https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/dalembert_predefined_params.xml">D'Alembert link</a>, then __*save link content as..*__, `Save`
2. Open binary bot in ur browser, dont forget to log in.
3. Click **_Load new blocks (xml file)_**, the one with folder icon, right below (under?) ur account balance, then open the **xml** file that uve just saved.
4. Run the bot.

**Comment by huguh** [comment]
Oh man is that easy? XD hahaha im feeling ashamed now, i was thinking i had to push some blocks around lol. I think its awesome this easy way to mount strategies using this intuitive blocks and tools but even that is not easy for people like me who dont know nothing about coding. Hey thank you so much  Fruitfella, now its all working fine of course duh XD

**Comment by Fruitfella** [comment]
I'll tell u a secret @huguh , I'm also not a coder and know nothing about coding. Well this is no secret _lol_
Good luck with ur bot and dont forget to ***CLOSE*** this issue since its already solved!

**Comment by huguh** [comment]
Well you must be better in lego than me anyway hahaha. I'll keep learning this, its very nice, thanks dude
