### ISSUE TITLE
Need help for an incredible idea for a bot

### ISSUE THREAD

**Issue by Rabieabd** [binary-com/binary-bot#3180]
Hello guys, I would like your help to build a very simple yet very effective bot, I tried its strategy manually and it is effective but I need to automate it, thanks in advance

**Comment by Jonni81** [comment]
пиши kazarinov.treiding@yandex.ru

**Comment by VERTO13** [comment]
Can you explain your idea, I can try to build the bot if its a simple strategy

**Comment by eonuoha30** [comment]
Click and Check here " #3161 "
