### ISSUE TITLE
hii.. i need an last digit collector

### ISSUE THREAD

**Issue by moshika18471** [binary-com/binary-bot#3181]
as i mentioned above i really need a volatility index **last digit collector** which collects all the last digits automatically with the time period.  i want to test a strategy of **1,3,5,7,9 DOWN  9,7,5,3,1 UP**  so i want to test is that is really working SO if anybody has a certain program for that please let me know

**Comment by moshika18471** [comment]
feel free to contact me on d.gamageofficial@gmail.com or moshika18471@gmail.com

**Comment by eonuoha30** [comment]
This strategy would take a lot I time before entering a trade.

However, Click and Check here " #3161 "
