### ISSUE TITLE
could you help me change this Rise/Fall bot to Higher/lower

### ISSUE THREAD

**Issue by basquetemfhx** [binary-com/binary-bot#3186]
I have tried to change this, but I can't. Could you help me, please?
I would like the bot to run with a +2 and -2 barrier
[bot-mascd-rsi.zip](https://github.com/binary-com/binary-bot/files/5974967/bot-mascd-rsi.zip)

**Comment by eonuoha30** [comment]
Check out " #3161 "

**Comment by basquetemfhx** [comment]
What happened as the community Binary-bot? before it wasn't like that.
@binary-ex-machina
