### ISSUE TITLE
Run a different bot or run with different conditions after a loss

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#3187]
Hi All, 

Good Day. Just wondering whether it is possible to run a different bot or run the bot with different conditions for one trade after a loss?

For eg., Let's say I have a bot for "Stays inside / Goes Outside" with certain conditions. There have been 5 consecutive wins since the  bot started and one loss after that. Can I make the bot run with different conditions after the loss till I get a profit?

Thanks in advance.

**Comment by eonuoha30** [comment]
It'll have to be on same "Stays inside / Goes Outside"  if their are barriers, they can be changed.

Also, it'll have to be on same market (e.g volatility 25 market)


Click or Check " #3161 "

**Comment by binarybotbegginer** [comment]
> It'll have to be on same "Stays inside / Goes Outside" if their are barriers, they can be changed.
> 
> Also, it'll have to be on same market (e.g volatility 25 market)
> 
> Click or Check " #3161 "

Thanks. Is it possible to show a bot example?

**Comment by eonuoha30** [comment]
Send me a mail

And your bot.

I'd work on it and the desired conditions.


eonuoha30@gmail.com
