### ISSUE TITLE
Deriv default bot

### ISSUE THREAD

**Issue by Thandiwe01** [binary-com/binary-bot#3188]
Hi can anyone assist me please how do I set back my deriv default bot

**Comment by carol-binary** [comment]
Hi @Thandiwe01, 

Are you looking to reset the workspace to it's default strategy? If so, then you can click the `Reset` button as shown below. 

![image](https://user-images.githubusercontent.com/58209918/108673749-a8a70c80-74fd-11eb-9435-8fb3150cfba2.png)

Regards,
Carol
