### ISSUE TITLE
Request for money management blocks 

### ISSUE THREAD

**Issue by Rithea268** [binary-com/binary-bot#3190]
Hi everyone, can you share money management blocks as shown below because I found it difficult to create. 

![2](https://user-images.githubusercontent.com/63917537/108536318-eabe2b80-730e-11eb-9421-a4e9001307e6.PNG)

**Comment by IQBinary** [comment]
![screenshot-bot-binary-com-bot-html-1613757693654](https://user-images.githubusercontent.com/54183297/108543400-0aebeb80-730b-11eb-8f0c-c44e0b6fef16.png)
iqbinarybot@gmail.com

**Comment by eonuoha30** [comment]
For this money management to work, some logic needs to be applied in block 4.

Adding those lines to block 1 won't solve the problem.

Send me an email or message on WhatsApp and I'll work on your bot 'immediately ' or at least, give you the desired blocks (FREE OF CHARGE).

I need to understand your money management do that I can fix up the required logic on block 4.

My email:

eonuoha30@gmail.com

Or +2348134998827 (Calls, Whatsapp, telegram)

Best regards.

You can click this link to directly message me on WhatsApp :

https://api.whatsapp.com/send?phone=2348134998827&text=Hello



P.S

If you need more bots in any STRATEGY/IDEA to be worked on IMMEDIATELY, I will do that for a little fee.

It will be be delivered on same day.

With a STOP LOSS, TAKE PROFIT and Trade notifications
