### ISSUE TITLE
Ajuda no projeto de um bot, por favor. 

### ISSUE THREAD

**Issue by Americano500** [binary-com/binary-bot#3198]
Boa tarde galera, seguinte. Estou com um problemão com edição de um bot. 
No caso gostaria de adicionar uma análise nele, que é a seguinte,

Analisar os ticks e depois de uma repetição de 9 ele compra menor que 9, caso dê loss, o martingale seria numa nova previsão
pro bot errar  7 ,8 ,9 com uma análise que se  7-8-9 for igual ou menor que 8% ele compra menor. Assim o martingale ficaria baixissimo e eu apenas iria recuperar o loss anterior com uma entrada baixa e se acertasse o martingale, voltar pra errar apenas o 9... 

Abaixo o bot, obrigado a todos. 

[Em construção.zip](https://github.com/binary-com/binary-bot/files/6092390/Em.construcao.zip)

**Comment by eonuoha30** [comment]
Check #3161

**Comment by Peacefull-Mind** [comment]
Americano, Conseguiste fazer teu bot ?
