### ISSUE TITLE
Saving the summary and log

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#320]
The summary and the log are in danger! Lets save them before its too late! _lol_ kidding.

@aminmarashi Could u make buttons to save the summary and log? I see there is `Share` button in Chart pop-up that actually save the chart in png and pdf format.
If possible, I want the summary and log can be saved in form of table, so txt format is a no-no. picture seems not good. Maybe its better in pdf or html or... any other format that u think its better.

**Comment by aminmarashi** [comment]
That's actually a very good idea. I added this to the development queue.

**Comment by Fruitfella** [comment]
Thank you 😄

**Comment by Fruitfella** [comment]
@aminmarashi Oh finally! the magic button! thanks
