### ISSUE TITLE
Rise Fall AI bot based on BB,RSI,EMA,SMA Fibonacci,MACD,worm ticks,with 15 indicator

### ISSUE THREAD

**Issue by benn10-blip** [binary-com/binary-bot#3201]
@ex-machina
@saidforex

I'm trying to create a bot that looks at percentages and calculates outcome, it need to use BB,rsi,ema,sma,fibonnaci,macd, worm ticks,

a.i system . the most perfect bot to profit, that never loses in two streak. I've tried countless bots,none of them work.  Hope we can teamwork to create the best bot. and then upload it here as .xml or .zip file for users to try and users can profit.

**Comment by Jonni81** [comment]
Какие критерии нужно прописать в боте?

**Comment by benn10-blip** [comment]
У бота не должно быть стоп-лоссов, мартингейл не нужен. всегда побеждает Взлет и падение.

**Comment by benn10-blip** [comment]
The bot should have no stop loss,needs no martingale. always wins Rise and fall.

**Comment by Jonni81** [comment]
давай напишем. я начну потом скину сюда. я думаю что то и получится собрать хотяб с 65-70 % винрейтом

**Comment by Jonni81** [comment]
на индексах я думаю стоит попробовать?

**Comment by benn10-blip** [comment]
да по индексам. Потом мы принесем больше помощи. 70/80% винрейт.

**Comment by benn10-blip** [comment]
80 win rate bot it willl take a month after many test of all users to finish.

**Comment by binary-ex-machina** [comment]
@benn10-blip what you want to create is impossible. No matter how many indicators you use, "that never loses in two streaks" is not achievable. All rise fall strategies are a 50% win rate in the long term. No matter what you use, it is impossible to prevent more than 2 losses in a row
