### ISSUE TITLE
new web bot

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#3204]
https://www.binarybotstudio.com.

1. create a multi bot index
2. multi token access.
3. Can make purchases in various asset indexes.
4. Combination of virtual, real and manual
5. there is an HTML block. CSS and Javascript to create charts for market analysis. and others.

https://www.youtube.com/watch?v=qYotABigg_o

**Comment by cleberscr** [comment]
nice bro

**Comment by saidforex26** [comment]
please develop the bot

**Comment by Moh201x** [comment]
Hello friend, I saw your bot that is based on the xxxx.xz stratgey , can you teach me this strategy ? or send me the full packege so i can learn it ? 
my email : mohammedk.daoud360@gmail.com
Thanks.
