### ISSUE TITLE
ASKING - How to see "Volatility 100 (1s) Index" on real tradingview.com platform?

### ISSUE THREAD

**Issue by anggado** [binary-com/binary-bot#3205]
Hi guys, anyone know How to see "Volatility 100 (1s) Index" on real tradingview.com platform? i found good indicator on tradingview.com but I cant found "Volatility 100 (1s) Index" in there. 

![image](https://user-images.githubusercontent.com/77214683/110809532-8e1fb200-82b7-11eb-9686-a6d6d8c3600c.png)

**Comment by saidforex26** [comment]
how to add tradingview. binary.com at www.binarybotstudio.com

https://youtu.be/BFkg-42u4u4

**Comment by anggado** [comment]
hi @saidforex26 thank you, but this is not what I'm looking for. I'm looking how to see "Volatility 100 (1s) Index" on real tradingview.com website.

I can see the graph supported by tradingview using your method but some indicator is not available there, especially "public indicators created by tradingview community". your method only provide standart/original indicators

Thank you :)

**Comment by saidforex26** [comment]
you can find what indicators you are looking for

**Comment by anggado** [comment]
hi @saidforex26,

No, they are different,

theres indicators that available in binary.com provided by tradingview.com
![image](https://user-images.githubusercontent.com/77214683/111018507-c0cac700-83eb-11eb-858a-a3e1834f5f9e.png)


and here is the indicators that available in tradingview.com. it has public library
![image](https://user-images.githubusercontent.com/77214683/111018533-eb1c8480-83eb-11eb-86a8-482caf9bcb63.png)


do you know how to use public library indicators in binary.com chart?

thanks!

**Comment by palangappa** [comment]
@anggado You can Go to kissbillions.com there you can go to the signals page to find signals related to binary platform
