### ISSUE TITLE
Tela Incompleta

### ISSUE THREAD

**Issue by samarabarroso** [binary-com/binary-bot#3207]
Boa noite.
Gostaria de relatar problema que a tela está incompleta, impossibilitando de fazer as configurações correta para usar o site.
Solicito a verificação e aguardo retorno o quanto antes, pois está atrapalhando o meu trabalho.
Segue o print da tela para melhor compreensão do problema.

![Binary (tela incompleta)](https://user-images.githubusercontent.com/80655860/111091267-25cc0d00-8511-11eb-9abe-7e2af5847257.png)

**Comment by cleberscr** [comment]
abaixa o zoom, ou vai nas propriedades do seu computador e deixa na resolução padrão

**Comment by carol-binary** [comment]
Olá @samarabarroso,
Você também pode rolar pela área de trabalho.

Estou encerrando este problema, reabra-o se o problema persistir.

Cumprimentos,
Carol
