### ISSUE TITLE
Bot em teste!!!

### ISSUE THREAD

**Issue by contatodeanet** [binary-com/binary-bot#3208]
Fala galera fiz um bot bem interessante que ainda está em fase de teste!! ele funciona assim: faz uma soma de cada digito q sai em blocos de nota separados, o primeiro que atingir a quantidade de 10 ele entra na operação com o mesmo digito!! parece promissor mas ainda estou testando e gostaria da opinião de vc6 para fazer alguns ajustes se possível!!!!

**Comment by contatodeanet** [comment]
![image](https://user-images.githubusercontent.com/43180630/111660957-5bad1200-87ed-11eb-8245-2022055f2e5b.png)

**Comment by contatodeanet** [comment]
[BBbot.txt](https://github.com/binary-com/binary-bot/files/6165660/BBbot.txt)
 Tá aí pra quem quiser testar!!! lembra de me passar o feedback depois pra saber o desempenho dele blz galera!!!
Um abraço a todos!!!!

**Comment by cleberscr** [comment]
> [BBbot.txt](https://github.com/binary-com/binary-bot/files/6165660/BBbot.txt)
> Tá aí pra quem quiser testar!!! lembra de me passar o feedback depois pra saber o desempenho dele blz galera!!!
> Um abraço a todos!!!!

loss em seguida?

**Comment by anggado** [comment]
hi @contatodeanet thank you! I'm testing it now also! I will share the status here, please you do as well :)

**Comment by viniciusctt** [comment]
> [BBbot.txt](https://github.com/binary-com/binary-bot/files/6165660/BBbot.txt)
> Tá aí pra quem quiser testar!!! lembra de me passar o feedback depois pra saber o desempenho dele blz galera!!!
> Um abraço a todos!!!!

Amanhã vou testar amigo

**Comment by oramaster** [comment]
About testing it now. Feedback coming soon

**Comment by deny-titan** [comment]
Looks good. I'm testing your Bot with Deriv : Lost:10 Won:99 Profit:$9.00 with only 1 step Martingale.

**Comment by oramaster** [comment]
Looks good, see picture below:
74 Runs, 67wins, 7 losses, 2hr 30min run time:

![Untitled](https://user-images.githubusercontent.com/63653432/112321873-b690ae80-8cb0-11eb-9ab7-2346e826dbd1.png)
