### ISSUE TITLE
bot binary.com api

### ISSUE THREAD

**Issue by juniorcls** [binary-com/binary-bot#3213]
hello everyone, i'm clovis junior, brazil - acre.

I am developing a website for a binary.com bot - the file and an xml - more as I am going to sell through hotmart, I would like the file to open directly on my website, of course after logging into the hotmart. Is it possible to do that?

**Comment by cleberscr** [comment]
você pode criar seu site separadamente, você pega o email da pessoa da hotmart e gera uma senha automatica, ela entra no site e quando entrar, ele pode alterar a senha, assim ele ja entra no seu site sem precisar da hotmart, ele só vai voltar na hotmart para fazer o pagamento da proxima mensalidade, se ele não pagar, deve ter algum jeito de ver o email e tirar ele pra não usar o seu site....
