### ISSUE TITLE
need help, I hit the jackpot of  forex and binary options

### ISSUE THREAD

**Issue by ceakuk** [binary-com/binary-bot#3214]
after many years i finally developed an simple system that wins exponentially without increasing bet size. i have tested it with data from yahoo finance in python and now i want to do it binary. winning with all data i tested  hundreds of  different data.

the problem is i analise a combination of data like EURUSD, EURGBP, EURJPY, GBPUSD, GBPJPY, USDJPY and the more pairs the better. once i analyse them i trade all of them. but how can i trade all the data at once. the analysis is very very simple but how can i trade all at once?
![Unbenannt](https://user-images.githubusercontent.com/43122491/113080805-c855e280-91d7-11eb-902f-3e128a93daac.PNG)

**Comment by sanal2020** [comment]
Email me: sanal.rms@aol.in

I can help

**Comment by ceakuk** [comment]
ok

**Comment by Bull-013** [comment]
Caso não tenha encontrado a solução, tenho sugestões.
e-mail: traidejm@gmail.com

**Comment by Xbrmachine** [comment]
@ceakuk VOCÊ POSSUI O ARQUIVO MQL?

PODERIA POSTAR AQUI? ASSIM PODERIAMOS ANALIZAR E CONVERTE-LO PARA BINARIO.

OU ENVIE VIA E-MAIL correiasawyer@gmail.com
