### ISSUE TITLE
How to change trade type and martingale together 

### ISSUE THREAD

**Issue by Hordunlarmy** [binary-com/binary-bot#3218]
![Capture1](https://user-images.githubusercontent.com/32147852/113522872-ea66b080-959b-11eb-9705-7ebe4e72985f.PNG)

That's my bot..i have martingale but it's not kicking in.. 
I don't know how to combine it

I want the bot to switch trade types after a loss and double the entry price, only after a loss though

![Capture2](https://user-images.githubusercontent.com/32147852/113522904-31ed3c80-959c-11eb-9991-51e2fc1062b4.PNG)

Now it only switch trade type after loss but entry price remains the same... 

Please help!!! 

@binary-ex-machina

**Comment by deny-titan** [comment]
@Hordunlarmy Just give a little modification in block Define Trade Option. Change block Payout with Stake. You can find it on Left Menu : Binary --> trade Definition. Then, use your variable named "actual stake" as 'Stake' not 'Initial Stake'. Because if you still use Inital Stake then your Stake will not doubled while Martingale step.

**Comment by Hordunlarmy** [comment]
@Hordunlarmy Just give a little modification in block Define Trade Option. Change block Payout with Stake. You can find it on Left Menu : Binary --> trade Definition. Then, use your variable named "actual stake" as 'Stake' not 'Initial Stake'. Because if you still use Inital Stake then your Stake will not doubled while Martingale step.

_Originally posted by @deny-titan in https://github.com/binary-com/binary-bot/issues/3218#issuecomment-813454375_

Thanks for commenting... I'm not entirely sure I get what you explained, I tried to tweak the bot with your explanation based on my understanding .. 
Still does same thing.. 

Could you maybe help with the tweaking it, I'll attach the bot
[teebot1.txt](https://github.com/binary-com/binary-bot/files/6260466/teebot1.txt)

And cant it be done with payout trade definition?? I want it to be payout instead of stake...
Thanks

**Comment by Hordunlarmy** [comment]
> @Hordunlarmy Just give a little modification in block Define Trade Option. Change block Payout with Stake. You can find it on Left Menu : Binary --> trade Definition. Then, use your variable named "actual stake" as 'Stake' not 'Initial Stake'. Because if you still use Inital Stake then your Stake will not doubled while Martingale step.

Thanks for commenting... I'm not entirely sure I get what you explained, I tried to tweak the bot with your explanation based on my understanding ..
Still does same thing..

Could you maybe help with the tweaking it, I'll attach the bot
[teebot1.txt](https://github.com/binary-com/binary-bot/files/6260466/teebot1.txt)

And cant it be done with payout trade definition?? I want it to be payout instead of stake...
Thanks

**Comment by Hordunlarmy** [comment]
> @Hordunlarmy Just give a little modification in block Define Trade Option. Change block Payout with Stake. You can find it on Left Menu : Binary --> trade Definition. Then, use your variable named "actual stake" as 'Stake' not 'Initial Stake'. Because if you still use Inital Stake then your Stake will not doubled while Martingale step.

Never mind mate, I got it...thanks a lot
![Capture3](https://user-images.githubusercontent.com/32147852/113635413-7b0ac280-9668-11eb-9348-5d2869a05ad2.PNG)


One more question though..
What if I want martingale to be fixed instead of multiplying the value.. 

Like I want it to go from 1 to 3 to 8 to 18 ,like that

**Comment by deny-titan** [comment]
> > @Hordunlarmy Just give a little modification in block Define Trade Option. Change block Payout with Stake. You can find it on Left Menu : Binary --> trade Definition. Then, use your variable named "actual stake" as 'Stake' not 'Initial Stake'. Because if you still use Inital Stake then your Stake will not doubled while Martingale step.
> 
> Never mind mate, I got it...thanks a lot
> ![Capture3](https://user-images.githubusercontent.com/32147852/113635413-7b0ac280-9668-11eb-9348-5d2869a05ad2.PNG)
> 
> One more question though..
> What if I want martingale to be fixed instead of multiplying the value..
> 
> Like I want it to go from 1 to 3 to 8 to 18 ,like that

You should have a List that use to save fix multiplier (or Stake) as Martingale. Example, In row 1 set as 3, row 2 set as 8, row 3 set as 18. Then you can give a logic before trade again to read from number of row in List, according to Martingale Step (step 1, step 2, step 3, ...).

**Comment by Hordunlarmy** [comment]
> > > @Hordunlarmy Just give a little modification in block Define Trade Option. Change block Payout with Stake. You can find it on Left Menu : Binary --> trade Definition. Then, use your variable named "actual stake" as 'Stake' not 'Initial Stake'. Because if you still use Inital Stake then your Stake will not doubled while Martingale step.
> > 
> > 
> > Never mind mate, I got it...thanks a lot
> > ![Capture3](https://user-images.githubusercontent.com/32147852/113635413-7b0ac280-9668-11eb-9348-5d2869a05ad2.PNG)
> > One more question though..
> > What if I want martingale to be fixed instead of multiplying the value..
> > Like I want it to go from 1 to 3 to 8 to 18 ,like that
> 
> You should have a List that use to save fix multiplier (or Stake) as Martingale. Example, In row 1 set as 3, row 2 set as 8, row 3 set as 18. Then you can give a logic before trade again to read from number of row in List, according to Martingale Step (step 1, step 2, step 3, ...).

Nah, I've got no idea how to go about this one.. 
Can you help 
[teebot2.txt](https://github.com/binary-com/binary-bot/files/6264370/teebot2.txt)

**Comment by deny-titan** [comment]
@Hordunlarmy Cek my revision on your bot :

Please extract XML file inside : 
[teebot2.rev1.xml.zip](https://github.com/binary-com/binary-bot/files/6265181/teebot2.rev1.xml.zip)

**Comment by Hordunlarmy** [comment]
> @Hordunlarmy Cek my revision on your bot :
> 
> Please extract XML file inside :
> [teebot2.rev1.xml.zip](https://github.com/binary-com/binary-bot/files/6265181/teebot2.rev1.xml.zip)

You are awesome man 👍 
Got exactly what I needed... Thanks a lot

**Comment by deny-titan** [comment]
> > @Hordunlarmy Cek my revision on your bot :
> > Please extract XML file inside :
> > [teebot2.rev1.xml.zip](https://github.com/binary-com/binary-bot/files/6265181/teebot2.rev1.xml.zip)
> 
> You are awesome man 👍
> Got exactly what I needed... Thanks a lot

You're welcome.

**Comment by alanvito1** [comment]
good

**Comment by qiri88** [comment]
> ![Capture1](https://user-images.githubusercontent.com/32147852/113522872-ea66b080-959b-11eb-9705-7ebe4e72985f.PNG)
> 
> That's my bot..i have martingale but it's not kicking in.. I don't know how to combine it
> 
> I want the bot to switch trade types after a loss and double the entry price, only after a loss though
> 
> ![Capture2](https://user-images.githubusercontent.com/32147852/113522904-31ed3c80-959c-11eb-9991-51e2fc1062b4.PNG)
> 
> Now it only switch trade type after loss but entry price remains the same...
> 
> Please help!!!
> 
> @binary-ex-machina

Got same problem with my bot .. 
martingale too high can wipe you account if it runs for the second time .. mind twitching it for me .. ie reduce the martingale to a double the stake than going over board.

[teebot2.rev1.xml.zip](https://github.com/binary-com/binary-bot/files/8471485/teebot2.rev1.xml.zip)

>
