### ISSUE TITLE
Help For Learn Loop Repeat 

### ISSUE THREAD

**Issue by anura1975** [binary-com/binary-bot#3219]
<img width="158" alt="screencapture-binary-bot-bot-html-2021-04-06-08_40_25" src="https://user-images.githubusercontent.com/32257287/113653878-46bcf380-96b4-11eb-955e-d2014d7ac14b.png">

If someone know about these repeat loops, please show me an example.

**Comment by deny-titan** [comment]
Hi @anura1975 
Here is an example of using repeat while :
![using_repeat_while](https://user-images.githubusercontent.com/71332443/113724395-7f90b300-971c-11eb-9ce6-02cb57e749ec.jpg)

And sample of binary bot :
Please extract .XML flie inside : 
[using_repeat_while.zip](https://github.com/binary-com/binary-bot/files/6265244/using_repeat_while.zip)
