### ISSUE TITLE
Help with profit loss calculation

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#322]
HI I need help with Profit loss calculation.

My bot increases every time .50p in the stake. Even on Loss or Profit. But I need to setup a condition that when it recovers from the loss the stake will go for the starting stake of 0.35p.

Problem I am facing that if I put a check if the total profit is more than 0 then set stake to 0.35, then it will always put 0.35p , will not increase the stake.

Don't know how to check this...

**Comment by Fruitfella** [comment]
@sarderiftekhar What if u dont lose, instead, u won 10x in a row? will it keep increasing?

**Comment by sarderiftekhar** [comment]
Yes... it will keep on increasing until target profit is reached...

**Comment by Fruitfella** [comment]
@sarderiftekhar a win after losses then reset?

**Comment by Fruitfella** [comment]
Try this 
![capture](https://user-images.githubusercontent.com/26277327/28320577-22605032-6bfb-11e7-8f0a-3aa87c59c857.PNG)

**Comment by sarderiftekhar** [comment]
Done coding...checking it now...thanks

**Comment by sarderiftekhar** [comment]
![image](https://user-images.githubusercontent.com/20506657/28321656-b5248760-6bcb-11e7-857b-8299b75c763e.png)

Didnt work...didnt started from 0.35 after regaining profit...

**Comment by sarderiftekhar** [comment]
![image](https://user-images.githubusercontent.com/20506657/28322002-bfda5742-6bcc-11e7-9e94-b94921621b9b.png)

**Comment by sarderiftekhar** [comment]
After recovery its not starting from 0.35 again...

**Comment by sarderiftekhar** [comment]
Brilliant it worked.........thanks...Fruitfella 

![image](https://user-images.githubusercontent.com/20506657/28323963-2c4c0de4-6bd2-11e7-8c9d-71a7a7301c4e.png)

**Comment by Fruitfella** [comment]
ur welcome @sarderiftekhar , good luck with ur bot and dont forget to **close** this issue.
