### ISSUE TITLE
counting losses

### ISSUE THREAD

**Issue by Darren-1992** [binary-com/binary-bot#3220]
good afternoon
 I would like to ask you a question, you can put two loss counters in a binary bot, I ask why I am trying to make a bot that has two strategies, but each one that has its own loss counter, thank you I await your answers.

**Comment by MBarros91** [comment]
obviously, just name variables as "strategy 1 loss count" and "strategy 2 loss count"

**Comment by Darren-1992** [comment]
This is how I have done it, but when running the bot, when there is a loss, both variables recognize the loss, and the objective is that these counters are independent for each strategy.

**Comment by MBarros91** [comment]
you have to use 'true/false' condition

if < result is loss
and < strategy 1 < true
change 'strategy 1 loss count' by '1'

if < result is loss
and < strategy 2 < true
change 'strategy 2 loss count' by '1'

**Comment by MBarros91** [comment]
and before contract purchase
set 'strategy 1' to 'true'
set 'strategy 2' to 'false'
and viceversa everytime you trigger each of those strategies

**Comment by Darren-1992** [comment]
> obviously, just name variables as "strategy 1 loss count" and "strategy 2 loss count"

ddsvvsvs

> and before contract purchase
> set 'strategy 1' to 'true'
> set 'strategy 2' to 'false'
> and viceversa everytime you trigger each of those strategies

thank you for taking the time to answer my question

**Comment by MBarros91** [comment]
you're welcome, brother! we are here to help each other

regards

**Comment by saidforex26** [comment]
if you want to create a bot and have multiple strategies and get each strategy's details. maybe you can visit www.binarybotstudio.com

**Comment by Darren-1992** [comment]
> if you want to create a bot and have multiple strategies and get each strategy's details. maybe you can visit [www.binarybotstudio.com](http://www.binarybotstudio.com)

thanks interesting I see that the website has more options

**Comment by saidforex26** [comment]
yes .. in a few hours I will do an update. you can create bots and share your bots for free or they can be sold and also you can take bots made by other people

**Comment by saidforex26** [comment]
click ctrl f5 to update the website. now you can share bots or sell bots in the market.
