### ISSUE TITLE
Differ after repeat, 24/7 strategy

### ISSUE THREAD

**Issue by MBarros91** [binary-com/binary-bot#3221]
Hello fellows!

Today i'm trying slow strategy bot to run 24h, even with slow profit, but extremely low on risk, for low balances.

The idea is:
after 2 'last digit' repeat (00, 11, 22...), set 'last digit' as 'prediction' and 'purchase' 'differ'; 
after loss, differ prediction will be set after 3 consecutive repeats (000, 111, 222....);

The problem is:
tick count is fast, when you use a 'last digit' 'notify', the pop up use to double the last digit notify, also, the bot is a bit `loaded`, sometimes the page stops and need to restart.

Need help to fix and make it lighter, free and open to test (Virtual Account), and obviously use at final version if want to;

.XML OneDrive link: https://1drv.ms/u/s!AmpNRPSsjKtXkHLQoSH3okSd4178?e=yGvUxo

P.s.: open for any other 24/7 strategies suggestions;

Regards!

**Comment by MBarros91** [comment]
Solved the crash issue, just add a 'run after' '1' before 'last digit' count

**Comment by MBarros91** [comment]
@deny-titan are you there? want to try?

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/114585522-206df980-9c5a-11eb-8811-2a8164ad9367.png)

**Comment by MBarros91** [comment]
@cleberscr Eu fiz isso, mas parece que toda vez que você encontra um bot de baixo risco e profit à longo prazo o site da Binary "crasha"..... Já fiz uns 3 ou 4 bots diferentes que o site acaba travando depois de iniciar o robô... A própria Deriv, extensão da Binary, não oferece bot trade para "Digits" (over;under, match;differ...) por serem, teoricamente, de baixo risco...

Você conhece alguma outra plataforma "operável" com robôs e/ou estratégia de longo prazo para compartilhar?

**Comment by deny-titan** [comment]
> @deny-titan are you there? want to try?

Hi Bro @MBarros91 . Ok. I'll try your bot...

**Comment by MBarros91** [comment]
> > @cleberscr Eu fiz isso, mas parece que toda vez que você encontra um bot de baixo risco e profit à longo prazo o site da Binary "crasha"..... Já fiz uns 3 ou 4 bots diferentes que o site acaba travando depois de iniciar o robô... A própria Deriv, extensão da Binary, não oferece bot trade para "Digits" (over;under, match;differ...) por serem, teoricamente, de baixo risco...
> > Você conhece alguma outra plataforma "operável" com robôs e/ou estratégia de longo prazo para compartilhar?
> 
> Ja tentaste operar atravex de um servidor or usar outro programa para fazer o bot e usar a API da binary ?

Only through VM, but after a few hours running bot start to delay notifications and allowed conditions to buy, delaying entry, rising risk (theorically)
