### ISSUE TITLE
free bot 

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#3222]
new version market www.binarybotstudio.com .

free bot https://youtu.be/zO2YBuKFJPw

**Comment by deny-titan** [comment]
Yang paling menarik dari binarybotstudio, sepertinya kita bisa menjalankan beberapa bot secara simultan. Ini berpotensi sangat baik untuk mengembangkan strategi bot Higher/Lower ataupun Touch/NoTouch di market synthetic. Salah satu keuntungan lainnya untuk markt real forex adalah, pada 1 body bot yang sama, kita bisa mengambil referensi data dari beberapa market yang berbeda. Misalnya pada pair EUR/USD, kita masih dapat baca data candle dari market GBP/USD dan USD/CHF. Hal ini mungkin bermanfaat bagi yang ingin mencoba strategi correlations trading system seperti pada case #3214 . Semoga dugaan saya benar, karena memang belum sempat mencoba untuk bot-bot seperti itu di binarybotstudio.com. Saya baru coba untuk beberapa strategi klasik seperti Digit Over/Under dan Differs. Good Job Bro @saidforex26

**Comment by saidforex26** [comment]
ya seperti itu cara kerjanya. anda bisa mendapatkan data aset dari semua index juga bisa melakukan pembelian semua index dalam satu file bot. .  juga dapat membuat indikator atau apapun untuk mendukung analisa dengan mengunakan bantuan block HTML, CSS dan javasript.

**Comment by deny-titan** [comment]
> ya seperti itu cara kerjanya. anda bisa mendapatkan data aset dari semua index juga bisa melakukan pembelian semua index dalam satu file bot. . juga dapat membuat indikator atau apapun untuk mendukung analisa dengan mengunakan bantuan block HTML, CSS dan javasript.

Keren banget. Saya cek lagi ternyata mulai ada seperi Market untuk menawarkan bot disana. Sukses terus Bro. Saya akan coba fitur-fitur di binarybotstudio.

**Comment by saidforex26** [comment]
ya kita bisa berbagi bot atau menjual bot. silakan klik ctrl f5 untuk bisa memperbarui website.
