### ISSUE TITLE
EVEN/ODD BOT

### ISSUE THREAD

**Issue by joshua2131** [binary-com/binary-bot#3226]
Can someone help me create Even/Odd bot with this strategy 

![untitled](https://user-images.githubusercontent.com/82709298/115137752-6b4f8e80-a017-11eb-9bbf-29834d2dc34a.jpg)

Thanks in advance

**Comment by MBarros91** [comment]
[Even;Odd Bot.zip](https://github.com/binary-com/binary-bot/files/6330806/Even.Odd.Bot.zip)

Done, buddy!

**Comment by MBarros91** [comment]
Image, if you want to do by yourself...

![even;odd bot](https://user-images.githubusercontent.com/81837048/115139894-e52d4b00-a00a-11eb-8e1d-4ee414c9aca6.jpg)

**Comment by MBarros91** [comment]
Remember: use a Virtual Account before play with real money and add a recovery system for losses (strongly recommended)!

**Comment by joshua2131** [comment]
Thanks Buddy!

**Comment by joshua2131** [comment]
From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
Can you adjust to trade ODD when the last number of the entry spot is odd?

![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)

**Comment by MBarros91** [comment]
Unfortunately it is not possible, as you can see, every 'entry spot' is exactly the same 'exit spot', would be a 100% win rate if possible...
Logically, the contract is set to purchase, with :prediction: 'even/odd', at 2nd step
Just at 4th step you have access to :contract detail: 'entry/exit spot value'
Basically, you can't "choose" what you'll 'buy', and when you do it, the 'sell' will be the same
Otherwise you would 'buy' even/odd contracts and set to 'sell' when you 'win'
But, rembember, you can't 'predict' 'next tick' or 'next last digit'... when you create a strategy based on last digit/digits (or tick/ticks), you will always buy/sell a contract "randomly"... for this reason there is no bots with 100% win rate/accuracy...
Strategies are made to reduce risks, but you can't avoid them 100%. Being the 'next tick/last digit' unpredictable, you will always have a chance to lose, even with the best strategy of the best trader/bot creator of the world, the maximum win rate you can reach is 99,999.....%

**Comment by MBarros91** [comment]
By the way, I've updated the bot (fixed some notify messages, for better accuracy)... Feel free to use it ^^

[Even;Odd Bot - Notify Fixes.zip](https://github.com/binary-com/binary-bot/files/6331904/Even.Odd.Bot.-.Notify.Fixes.zip)

**Comment by MBarros91** [comment]
> From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> Can you adjust to trade ODD when the last number of the entry spot is odd?
> 
> ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)

Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)... 

![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)

Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.

Best of wishes, have a good day brother!

Regards,

MBros

**Comment by joshua2131** [comment]
Thanks brother, will try the updated bot.

**Comment by olestyleno1** [comment]
> > From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> > Can you adjust to trade ODD when the last number of the entry spot is odd?
> > ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> > ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)
> 
> Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)...
> 
> ![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)
> 
> Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.
> 
> Best of wishes, have a good day brother!
> 
> Regards,
> 
> MBros

I want to contact you
can you leave your email, if you use telegram even better :D

**Comment by joshua2131** [comment]
drop your telegram let me contact you

**Comment by joshua2131** [comment]
> 
> 
> > > From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> > > Can you adjust to trade ODD when the last number of the entry spot is odd?
> > > ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> > > ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)
> > 
> > 
> > Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)...
> > ![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)
> > Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.
> > Best of wishes, have a good day brother!
> > Regards,
> > MBros
> 
> I want to contact you
> can you leave your email, if you use telegram even better :D

drop your telegram let me contact you.

**Comment by MBarros91** [comment]
> > > From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> > > Can you adjust to trade ODD when the last number of the entry spot is odd?
> > > ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> > > ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)
> > 
> > 
> > Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)...
> > ![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)
> > Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.
> > Best of wishes, have a good day brother!
> > Regards,
> > MBros
> 
> I want to contact you
> can you leave your email, if you use telegram even better :D



> > > > From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> > > > Can you adjust to trade ODD when the last number of the entry spot is odd?
> > > > ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> > > > ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)
> > > 
> > > 
> > > Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)...
> > > ![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)
> > > Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.
> > > Best of wishes, have a good day brother!
> > > Regards,
> > > MBros
> > 
> > 
> > I want to contact you
> > can you leave your email, if you use telegram even better :D
> 
> drop your telegram let me contact you.

What's up, brothers? Say it...

**Comment by joshua2131** [comment]
> 
> 
> > > > From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> > > > Can you adjust to trade ODD when the last number of the entry spot is odd?
> > > > ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> > > > ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)
> > > 
> > > 
> > > Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)...
> > > ![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)
> > > Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.
> > > Best of wishes, have a good day brother!
> > > Regards,
> > > MBros
> > 
> > 
> > I want to contact you
> > can you leave your email, if you use telegram even better :D
> 
> > > > > From this Even/Odd bot: trade wins if bot trades EVEN and the last number of the entry spot is also even.
> > > > > Can you adjust to trade ODD when the last number of the entry spot is odd?
> > > > > ![Screenshot_2021-04-18 Binary Bot](https://user-images.githubusercontent.com/82709298/115142020-f12b0400-a02e-11eb-9215-a46ba2d75e1b.png)
> > > > > ![Screenshot_2021-04-18 Binary Bot(1)](https://user-images.githubusercontent.com/82709298/115142023-f2f4c780-a02e-11eb-9348-50ac4f140e16.png)
> > > > 
> > > > 
> > > > Check it again, the bot is already doing both operations/purchases, but the 'buy' is based on the 'last digit', not the 'entry spot', as I said, you just have access to 'entry/exit spot value' **after** purchase(with even/odd set)...
> > > > ![evenoddworking](https://user-images.githubusercontent.com/81837048/115155929-665eff00-a058-11eb-868f-8e8413a34978.jpg)
> > > > Try to download this latest version that I've uploaded above and load it again. Choose your Virtual Account before load the .XML file or the bot configuration will be lost and you will need to load it again.
> > > > Best of wishes, have a good day brother!
> > > > Regards,
> > > > MBros
> > > 
> > > 
> > > I want to contact you
> > > can you leave your email, if you use telegram even better :D
> > 
> > 
> > drop your telegram let me contact you.
> 
> What's up, brothers? Say it...

yh i think work on something on telegram,.....fast response
