### ISSUE TITLE
How correctly count up  down 2x 4x in a row in higher lower bot

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3229]
@nijil-binary  
@Mahboobeh-binary 
@jy-binary 
@binary-ex-machina

I watched two tutorial videos about 2x 4x up and down in a row 
one bot Logic :
DOWN 4X in a row -- Purchase Higher
UP 4x in a row -- Purchase Higher
it coded as show in photo 

![Screenshot_1](https://user-images.githubusercontent.com/76085185/115682372-6a9e5b80-a37b-11eb-8c81-c189737b8c3f.png)

another bot logic 
UP 4x in a row - purchase higer

it coded as shown in photo 
![Screenshot_2](https://user-images.githubusercontent.com/76085185/115682469-7e49c200-a37b-11eb-9304-94d446995c27.png)

Second code is more clear and understand 
I want to know is this correct and effective codes?

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/116030790-c0e8f400-a632-11eb-803e-5dcc17f2dcc1.png)

**Comment by vnxz** [comment]
@cleberscr
thanks you bro.How an modify this higher condition for more specific.
example Green worm head ,blue worm head confirmation etc..
I still not clear how can read blue head green head by codes.
Most coders make this green blue head by tick list higher and lower count.
![61139950-de21f200-a4a0-11e9-970e-fd25f78a5a5d](https://user-images.githubusercontent.com/76085185/116091738-25579200-a6cb-11eb-89dc-da40a558c34a.png)

How can read color of worm head exctly.?

**Comment by cleberscr** [comment]
[worm.zip](https://github.com/binary-com/binary-bot/files/6380140/worm.zip)
