### ISSUE TITLE
How to change Barrier (+/-) value

### ISSUE THREAD

**Issue by mnaseem01** [binary-com/binary-bot#323]
Hi,
Can you please help how to change + and - sign after finish trade. I want to change this sign based on my condition
![image](https://user-images.githubusercontent.com/13481811/28317773-5d830dfc-6bd9-11e7-95ba-bc73c378b7e2.png)

**Comment by Fruitfella** [comment]
for now, u cant 😛

**Comment by aminmarashi** [comment]
Actually, you can. Here's an example: [switch_barrier_sign.xml](https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/switch_barrier_sign.xml)

**Comment by Fruitfella** [comment]
_Oh_ I never thought we could put other blocks in **Difine Trade Options** , why didnt thought that 😛

**Comment by aminmarashi** [comment]
Because you couldn't until recently. Better to avoid this feature unless you know what you're doing :).

**Comment by mnaseem01** [comment]
@aminmarashi Thanks alot i solve my problem
