### ISSUE TITLE
bot marginale strategy

### ISSUE THREAD

**Issue by precious2818** [binary-com/binary-bot#3230]
please what is the block code to create a binarybot strategy that adds profit and trade agai for instance eg.stake 0.35 win 0.31 then stake 2 0.66 wins 0,50 then stake 3 1.16 and so on

**Comment by Darren-1992** [comment]
> please what is the block code to create a binarybot strategy that adds profit and trade agai for instance eg.stake 0.35 win 0.31 then stake 2 0.66 wins 0,50 then stake 3 1.16 and so on

it is not advisable to do what you say knowing that an unpredictable market.

**Comment by Xbrmachine** [comment]
![image](https://user-images.githubusercontent.com/84425979/118883842-1af47680-b8cc-11eb-83a0-d998945dc1ad.png)


SEGUINTE:

Gostaria que após 1 perca o martingale invertesse a direção do trade por exemplo:

UMA OPERAÇÃO CALL = LOSS
PROXIMO CANDLE ABRE UMA VENDA = PUT


Há dois preoble as encontrados neste codigo:
1- ele não abre o martingalle no proximo candle (está executando apenas no proximo sinal)
2- não está abrindo o martingale na direção oposta do loss


Por gentileza nobres, podem auxiliar?
