### ISSUE TITLE
How can solve rate limit reach for proposal open contract

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3232]
I get this rate limit problem error when running my bot
How can solve it.
![Screenshot_4](https://user-images.githubusercontent.com/76085185/115988096-1fd04e00-a5de-11eb-802c-45f1f6d8e396.png)

**Comment by deny-titan** [comment]
Usually I got this error if I used 2 bots or more that do rapidly purchase contract from one account. You should try to use 2 accounts or more to test a high speed bot.

**Comment by vnxz** [comment]
thanks .it is solved.
