### ISSUE TITLE
Volatility Indices Patterrn

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#3234]
Hi All,

Just wanted to know whether it is possible to study or predict the pattern of volatility indices at all. Like for eg.: Is there a time they would keep rising or keep falling continuously. I have seen many instances where they go up or go down continuously or ~12+ ticks.

We can (to an extent) try to predict the "forex" direction by following the global economic news and developments. Is there a way to predict something like that for volatility indices?

**Comment by zivasjr** [comment]
UP

**Comment by deny-titan** [comment]
@binarybotbegginer, Volatility Index is one of synthetic market. It means  the movement of price is depends on Binary machine/server. I think this is as a game. Enjoy this market to examine your strategy based on technical analysis only, cause there is no real market fundamental neither real underlying assets, that affecting Volatility Index.

**Comment by MBarros91** [comment]
> @binarybotbegginer, Volatility Index is one of synthetic market. It means the movement of price is depends on Binary machine/server. I think this is as a game. Enjoy this market to examine your strategy based on technical analysis only, cause there is no real market fundamental neither real underlying assets, that affecting Volatility Index.

synthetic index are the 'micro' economy, like cryptocurrency flux

**Comment by binarybotbegginer** [comment]
I have seen certain instances where they keep going up (or down) continuously for approximately 15 ticks. Is there a way to predict when such a big / continuous rise or fall would happen?

**Comment by MBarros91** [comment]
> I have seen certain instances where they keep going up (or down) continuously for approximately 15 ticks. Is there a way to predict when such a big / continuous rise or fall would happen?

Yes! When you use MACD/Signal analysis you can see signs of reversal, when both indicators switch positions. When it hit bband too. when price hit a top line (a peak), almost 100% chance to price go down a few ticks (reverse/retraction) then keep falling or go up again. same when hit bottom line (bolinger band)

![Untitled](https://user-images.githubusercontent.com/81837048/117579592-0513d400-b0ca-11eb-949c-d121899acb24.png)

*red circles showing when both lines switch positions between each other
**black circle showing when price line cross lower band then cross inside again. attention at the end, as I said sometimes price hit a band but keep rise/fall trend, reason why is important to watch MACD. at first example both signals switch positions, at the end they don't
remember, graphic is showing a side trend using 1m candles, higher periods analysis can show those signals slowly but more precisely

**Comment by MBarros91** [comment]
A friendly tip: sometimes people think that it's a lot of things to learn/understand. personally, I've learned all those things that I'm saying in about 30 days. Strongly suggest to keep your head up, is a good way to exercise your brain/mind!

Regards!

**Comment by Xbrmachine** [comment]
EIS COMO FUNCIONAM OS INDICES SINTETICOS

Existem sempre dois lados para os traders SOBE ou DESCE

A corretora jamais irá te dar dinheiro, então não espere que ela tenha criado um indice sintetico para te ajudar a ganhar dinheiro e ficar rico.

Sempre que o maior volume de dinheiro estiver em apostas compradoras, o grafico irá desder.
Assim a corretora paga para a menor parte os ganhos e sobra a diferença para a corretora.

Então uma estrategia que funcione é você descobrir sempre onde está o menor volume de dinheiro apostado, a vitoria é sempre do menor volume.

Somente lembrando que a corretora usa o dinheiro dos perdedores para pagar aos vencedores, nunca sai do bolso dela, caso contrario seria inviavel para a mesma manter seu negócio funcionando.


Olhando aqgora por este prisma, devemos desenvolver uma estratégia vencedora não baseado em analise grafica, nem em price action ou suporte e resistência, como ja compreenderam, isso não lhe trará ganhos consistêntes.

Existem sim formas de arrancar dinheiro deles e é com este intuito que abrí um novo problema #3262 

Onde iramos discutir as melhores maneiras de fazer issod ar certo, com a ajuda da maravilhosa imaginação de todos iremos conseguir.

**Comment by Xbrmachine** [comment]
![Screenshot_20210527-172257](https://user-images.githubusercontent.com/84425979/119894112-94b2e280-bf12-11eb-819c-2a2ed1a6ef35.png)
 

Ha solução viavel sim

**Comment by zivasjr** [comment]
> ![Screenshot_20210527-172257](https://user-images.githubusercontent.com/84425979/119894112-94b2e280-bf12-11eb-819c-2a2ed1a6ef35.png)
> 
> Ha solução viavel sim

Como?

**Comment by Xbrmachine** [comment]
Possuo o BOT mais perfeito já criado para a corretora binary e estou criando um grupo de investimento coletivo onde a partir de 10 dólares será possivel obter bons lucros.

Para saber mais acesse nosso telegram:
https://t.me/botbr

**Comment by binary-ex-machina** [comment]
> Possuo o BOT mais perfeito já criado para a corretora binary e estou criando um grupo de investimento coletivo onde a partir de 10 dólares será possivel obter bons lucros.
> 
> Para saber mais acesse nosso telegram:
> https://t.me/botbr

https://github.com/binary-com/binary-bot/issues/3260#issuecomment-854792310

Muita besteira escrita aqui que fica até dificil de comentar algo racional para os marketeiros de bots milagrosos e perfeitos. Não existe volume nos indices sinteticos, então esse negócio de que quando tem mais compradores do que vendedores o preço sobe é mentira. O mercado sintetico é gerado aleatoriamente, 100% randomico. A corretora ganha  em cada trade, payout menor de 100% já é o lucro da corretora no longo prazo. 

@binarybotbegginer it's not possible to predict a randomly generated market that never closes or is impacted by any external factor, like news about that market. It's a 100% random generated market, all attempts to predict the next moves have the same chance of trading it blindly, 50%.
