### ISSUE TITLE
How can code worn head color as blue heaad red head green head 

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3235]
I want to know logic of code in worm pattern.
red head is fall
blue head is rise 
and what is green head and how can code this head color in binary bot.

![65290362-8d6bec80-db14-11e9-92f5-fa2da62d95fb](https://user-images.githubusercontent.com/76085185/116102380-acf5ce80-a6d4-11eb-8c14-cee5bf66abaf.png)

**Comment by cleberscr** [comment]
[worm.zip](https://github.com/binary-com/binary-bot/files/6380143/worm.zip)

**Comment by vnxz** [comment]
thanks your help. Can I know how use this in trade condition. I understand what is blue red and green in code. Just call Text "Blue", "Red" "Green" in condition?

**Comment by saidforex26** [comment]
[worm view.zip](https://github.com/binary-com/binary-bot/files/6404363/worm.view.zip)

**Comment by cleberscr** [comment]
> obrigado sua ajuda. Posso saber como usar isso na condição de comércio. Eu entendo o que é azul, vermelho e verde no código. Basta chamar o texto de "Blue", "Red" "Green" no estado?

yes
