### ISSUE TITLE
Need help for the bot for idea about MATCHES TRADE type

### ISSUE THREAD

**Issue by tunckt** [binary-com/binary-bot#3236]
Hi fellows,
I have an idea about matches trade type and hope somebody can help to make the bot as follows:
1. Market Volatility 75 Index. Initial Stake 0.35$. Duration 1 tick.
2. Logic:
- Analysis the number not appears 15 ticks in row. Purchase that number. Trade again & again with that number till it matches. (If there is more than one number eligible, choose randomly to purchase).
- Not martingale in 8 first trade, from trade 9, martingale factor is 1.3.
- When the result is matches, do other analysis to find number, make other purchase.
In additional, it’s so good if we can add these conditions to prevent burning all our budget:
1. Target profit 10$.
2. Stoploss 20$.
3. Stop after martingale level 25 or trade loss level 35.

**Comment by KingMoni** [comment]
Can we create a bot out of this?

**Comment by MBarros91** [comment]
last digit list, period 15. in list every number change count 1. if 0 set prediction to this number, buy differ.
a bit complex to explain, I'll do it soon.

**Comment by MBarros91** [comment]
nice strategy btw

**Comment by MBarros91** [comment]
but I like the inverse of it. Purchase differ most repeated number, instead of less repeated....

**Comment by MBarros91** [comment]
there should be a easier way to do it... It's extensive, but should work... 

create a sublist with analysis+1
repeat 'analysis period' times changing every first number by 1. as the 'analysis period list' is done, break out of the loop
keep the 'analysis' out of the loop with the 'last' from 'list' 'count -1' (the 16th digit, out of the analysis)

![Untitled](https://user-images.githubusercontent.com/81837048/117520652-975b9100-af7f-11eb-84db-8b8b3a69b427.png)

now you have 0123456789 variables with how many times it's showed in your analysis list
set a new list to sort it, ascending. the first one is the least frequent. set a condition to if the least frequent = 0, set prediction to 'least frequent variable', purchase 'differ'
done!

**Comment by tunckt** [comment]
> there should be a easier way to do it... It's extensive, but should work...
> 
> create a sublist with analysis+1
> repeat 'analysis period' times changing every first number by 1. as the 'analysis period list' is done, break out of the loop
> keep the 'analysis' out of the loop with the 'last' from 'list' 'count -1' (the 16th digit, out of the analysis)
> 
> ![Untitled](https://user-images.githubusercontent.com/81837048/117520652-975b9100-af7f-11eb-84db-8b8b3a69b427.png)
> 
> now you have 0123456789 variables with how many times it's showed in your analysis list
> set a new list to sort it, ascending. the first one is the least frequent. set a condition to if the least frequent = 0, set prediction to 'least frequent variable', purchase 'differ'
> done!

Thank you so much for your support @MBarros91 , could you share .xml file. Hope you & other people can earn money from this idea and the bot.

**Comment by Peacefull-Mind** [comment]
@MBarros91   " now you have 0123456789 variables with how many times it's showed in your analysis list
set a new list to sort it, ascending. the first one is the least frequent. set a condition to if the least frequent = 0, set prediction to 'least frequent variable', purchase 'differ' done! "  
It sounds easy when you say it like that :) but to actually do it don't even know where to start. :) and i thought i knew a bit about binary bots by the looks of i don't know nothing at all hahaha :)
