### ISSUE TITLE
help with martingale

### ISSUE THREAD

**Issue by ttors** [binary-com/binary-bot#3240]
Hello. Please add matingale up to 3 steps. And then it is reset to the initial bet.
![git](https://user-images.githubusercontent.com/73289812/117061857-5e2ae300-ad2b-11eb-81f5-04326a63d3f6.jpg)

[git.zip](https://github.com/binary-com/binary-bot/files/6423715/git.zip)

**Comment by Darren-1992** [comment]
> Hello. Please add matingale up to 3 steps. And then it is reset to the initial bet.
> ![git](https://user-images.githubusercontent.com/73289812/117061857-5e2ae300-ad2b-11eb-81f5-04326a63d3f6.jpg)
> 
> [git.zip](https://github.com/binary-com/binary-bot/files/6423715/git.zip)

hello good afternoon asahonenko I hope this is helpful
[binary-bot Martingale Reset .zip](https://github.com/binary-com/binary-bot/files/6430253/binary-bot.Martingale.Reset.zip)

**Comment by asahonenko** [comment]
more It's good. But can I fix my code?

**Comment by Darren-1992** [comment]
> Thank you. Exactly what is needed

you're welcome asahonenko a pleasure for that we are to help each other.

**Comment by Darren-1992** [comment]
> Thank you. Exactly what is needed

you're welcome, that's why we're here to help each other.
