### ISSUE TITLE
how to count fake loss and trade 

### ISSUE THREAD

**Issue by bintex32** [binary-com/binary-bot#3242]
hi, I'm a beginner to programming , please help me to complete the bot ..i need your help to complete some requirements.
@cleberscr
@binary-ex-machina
@saidforex26
@ceakuk

**Requirement is Count 2 fake losses and get  the trade**  

![Screenshot (40)](https://user-images.githubusercontent.com/83890614/117568707-74e08980-b0df-11eb-97d9-1225319c5e4d.png)

**Comment by saidforex26** [comment]
[under 5 add virtual los 2x @lasaidhari.zip](https://github.com/binary-com/binary-bot/files/6447641/under.5.add.virtual.los.2x.%40lasaidhari.zip)

**Comment by bintex32** [comment]
thank you so much...
