### ISSUE TITLE
Even/Odd Counter Bot

### ISSUE THREAD

**Issue by fperiin** [binary-com/binary-bot#3249]
I'm finding it difficult to make an account of how many times in a row an odd number came out

Can anyone guide me how I could do this?

The idea is to make the purchase after leaving "n" times the even number and buying by betting on the odd odd. I even have a sketch of the bot I made, but it is not in English so I preferred not to post the print to possibly not confuse it with the name of variables

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/118142238-90e67280-b3e0-11eb-8a10-3d2ebe12a555.png)
