### ISSUE TITLE
CANDLE ERROR?

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#325]
![picture01](https://user-images.githubusercontent.com/26277327/28345073-d33d96de-6c51-11e7-969e-aed244aeb9b4.png)

@aminmarashi Im pretty sure that both notifications should have same value.
The blue notification is correct but the red seems to get the value from the last candle since it changes in every tick.

**Comment by aminmarashi** [comment]
Should be resolved @Fruitfella, could you please check again?

**Comment by Fruitfella** [comment]
Yep, resolved!
