### ISSUE TITLE
Why cannot load tick data on tick chart

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3250]
My binary bot tick chart not show anything
what wrong
![Screenshot_1](https://user-images.githubusercontent.com/76085185/118077762-c12b1280-b3da-11eb-8ae4-3be758581015.png)

**Comment by fperiin** [comment]
> My binary bot tick chart not show anything
> what wrong
> ![Screenshot_1](https://user-images.githubusercontent.com/76085185/118077762-c12b1280-b3da-11eb-8ae4-3be758581015.png)

The same thing happens on my computer, try using the incognito mode that will work !!

**Comment by vnxz** [comment]
> 
> 
> > My binary bot tick chart not show anything
> > what wrong
> > ![Screenshot_1](https://user-images.githubusercontent.com/76085185/118077762-c12b1280-b3da-11eb-8ae4-3be758581015.png)
> 
> The same thing happens on my computer, try using the incognito mode that will work !!

inognito mode also not work .

**Comment by saidforex26** [comment]
it stopped working a few months ago. maybe the developer bot.binary.com is no longer being developed. broke into deriv.com ...

**Comment by saidforex26** [comment]
maybe you can also use www.binarybotstudio.com
