### ISSUE TITLE
Last Digit Stat and digit differ bot 

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3251]
I need help last digit stat script block that show by % or highest and lowest of Last digit .
Period may be with tick list or digit list
Strategy is to open differ whenever last digit % is lowest ,prediction is this lowest LD.

I tested one model, win rate is 60 and loss 1 .
But I need custom function block that can show LDP .
Thanks

**Comment by cleberscr** [comment]
https://github.com/Fruitfella/ROBOT-binary/issues/35
