### ISSUE TITLE
Odd Even

### ISSUE THREAD

**Issue by samratmohite** [binary-com/binary-bot#3253]
Hey Guys.. just checked all the issues so far on the forum however couldn't find solution hence writing.. please spare few minutes of your to help

I want to bot that checks if last digits of last 5 ticks were EVEN if yes Then will purchase odd and vice versa.

eg. -  
12348
65342
96584
32576
12500

so list should be - 8,2,4,6,0 - Bot should read them logically as EVEN and the place purchase for Odd

if this numbers are odd in nature then should do the same just change purchase to EVEN

Please let me know if anyone can think on this and help.

**Comment by cleberscr** [comment]
![image](https://user-images.githubusercontent.com/61013585/118404993-c216ab00-b64b-11eb-9625-9f9e8382209f.png)

**Comment by samratmohite** [comment]
Thanks Cleberscr .. just one more request .. I tried creating  a martingle but its not wokring the way i want something is wrong with codes.. 

Request is - 
my initial stake is $1 or $0.35 however if there is loss then stake should increase by another $0.35 only .. 

so if 4 consecutive losses then my 5th stake should be 0.35*5 but its actually making it far more.. 

can your please suggest code here..

**Comment by cleberscr** [comment]
> Obrigado Cleberscr .. só mais um pedido .. Eu tentei criar um martingle, mas não está funcionando da maneira que eu quero algo está errado com os códigos ..
> 
> O pedido é -
> minha aposta inicial é de $ 1 ou $ 0,35, no entanto, se houver perda, a aposta deve aumentar em mais $ 0,35 apenas.
> 
> então, se houver 4 derrotas consecutivas, minha 5ª aposta deve ser de 0,35 * 5, mas na verdade está aumentando muito mais.
> 
> pode sugerir o código aqui ..

![image](https://user-images.githubusercontent.com/61013585/118513708-5a736500-b70a-11eb-85be-88b9df18762f.png)
