### ISSUE TITLE
How create virtual loss and win as shown in photo

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3256]
I need help for this virtual win and loss function block.
I find clues on issues but not see
please help me

![Screenshot_1](https://user-images.githubusercontent.com/76085185/118368559-7cfd6500-b5c8-11eb-9e91-46b251fcc21a.png)

**Comment by VERTO13** [comment]
https://apps.neuronaltrader.com/binary-bot/bot.html its in that website, it gives you the tools you need, if you need help send me a mail vitor.emma99@hotmail.com Im not an expert on the website but I can help you with simple stuff
