### ISSUE TITLE
Does anyone has this Money Mangament block

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3257]
I found one sample photo
its MM is
0.35 stake loss
0.66 stake
if still loss,reduce stake to 0.35
and gradually 
0.35 to  0.39 -> 0.53 -> 0.71->0.96
if win ,next stake is still multiply 1.87
after that to original stake.

![102705347-c66bb180-42c1-11eb-839f-78ce87c8f066](https://user-images.githubusercontent.com/76085185/118389140-6e599100-b64e-11eb-8338-7f94b4a20e8d.png)

I also has a similar MM block but need to modify this block to get as above MM.
Block I have is still multiply one stake after win and reduce to original stake but not has stake function while still loose reduce stake
Please someone help me

[template.zip](https://github.com/binary-com/binary-bot/files/6488820/template.zip)

**Comment by binary-ex-machina** [comment]
It's very hard to make money management with just some results, but it seems that it uses various factors and it applies them until the profit of that run is positive. One way of making it is like the image below

![image](https://user-images.githubusercontent.com/34610787/120104705-33fef200-c12c-11eb-81bd-d46020b2149b.png)

**Comment by vnxz** [comment]
> 
> 
> It's very hard to make money management with just some results, but it seems that it uses various factors and it applies them until the profit of that run is positive. One way of making it is like the image below. After all, factors are used, it will start using from the first again until the profit since the last loss is above 0, then return to the initial stake
> 
> ![image](https://user-images.githubusercontent.com/34610787/120104705-33fef200-c12c-11eb-81bd-d46020b2149b.png)


Thanks bro .
I finally understand this Money management style .I will explain here , plz code this

It based on win step and loss step
original stake is 0.35
Rule is 

from start , it win , no change stake 
example = 0.35 / 0.35 / 0.35 / 0.35 ( All win / no change )
if loss , start manage here
if loss , reduce ( original stake divided by 1.9 ) of  loss stake to trade next 

example 0.35 loss , it is minimal stake no need to reduce stake , so 

if 0.35 stake loss , next trade stake is 0.35 

if still loss this 0.35 

multiply by 1.4 
0.35 loss
0.39 loss
0.53 loss
0.71 loss
0.96  WIN , If win here wining management ,if win next stake is , win stake * 1.4 ,
example 0.96 stake win , next stake is 1.34

if loss this 1.4 stake , it will reduce to 1.4 divided by 1.9 , so reduce to 0.73 stake
if 0.73 stake loss , multiply by 1.4 , so next stake is 1.03
if win 1.03 stake , next stake is 1.03 * 1.94 = 1.99 stake
if loss 1.99 , change stake to 1.99 divide by1.9 = 1.05
if 1.05 loss , multiply by 1.4 = 1.47 stake

Conclusion 

loss stake divided by 1.9
win stake multiply by 1.4 ( only for two win / after two win count , back to original stake 0.35 )
if loss stake is 0.35 , no change stake.

I try to create this , but fail ,
please help me.
