### ISSUE TITLE
How can mention digit 1  from a text digit list

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3258]
I make a list of last 5 ticks last digits.

![Screenshot_1](https://user-images.githubusercontent.com/76085185/118498814-68e27080-b74c-11eb-93f0-c4c66e5b0adf.png)

![Screenshot_2](https://user-images.githubusercontent.com/76085185/118498838-6d0e8e00-b74c-11eb-89de-17ed545ca64e.png)

store in A variable
I want to mention 1 whenever this A value contain digit 1 ( example 94111 / 47121 / 31126 )
Because I want to make differ bet when last digit is 1 and last 5 digits also contain 1.
What tool need to use to mention this 1 .
thanks for help.

**Comment by cleberscr** [comment]
[REPETEWIN.zip](https://github.com/binary-com/binary-bot/files/6494840/REPETEWIN.zip)
