### ISSUE TITLE
BOT BR PERFEITO / CORETORA BINARY

### ISSUE THREAD

**Issue by Xbrmachine** [binary-com/binary-bot#3262]

**Comment by Xbrmachine** [comment]
![Screenshot_20210527-172257](https://user-images.githubusercontent.com/84425979/119893799-3685ff80-bf12-11eb-85c3-9023dca76677.png)


Me parece que ha soluções reais pessoal, continuo trabalhando para o desenvolvimento da melhor experiência possivel.

![Uploading Screenshot_20210527-171717~2.png…]()

**Comment by brunomoreiras** [comment]
Ola @Xbrmachine eu tenho interesse em participar do projeto, como faço para integrar esse processo. aguardo retorno, valeu

**Comment by htnlabs** [comment]
Olá, tenho interesse em contribuir ao projeto. Algum grupo no Telegram?

**Comment by Xbrmachine** [comment]
@brunomoreiras, 

Para integrar ao projeto basta trazer ideias para que elas sejam avaliadas e assim possamos unir ao que ja temos e criarmos um bot incomparável.

**Comment by Xbrmachine** [comment]
@htnlabs 

Não havia oensado ainda em um grupo no telegram para discutir sobre, mas é uma otima ideia.  

Criei o grupo abaixo para discutirmos 

Bot Br / discursão
https://t.me/botbr

**Comment by brunomoreiras** [comment]
Ok vou entrar no telegram e conversamos por la blz

**Comment by Xbrmachine** [comment]
![image](https://user-images.githubusercontent.com/84425979/120072288-83301e80-c069-11eb-8367-df9ea9c8d9c1.png)


seguimos

**Comment by Xbrmachine** [comment]
![image](https://user-images.githubusercontent.com/84425979/120072322-b07ccc80-c069-11eb-998f-4111dffa9b54.png)


:)

**Comment by Xbrmachine** [comment]
Esta questão agora passará a ser discutida no repositório adequado https://github.com/Xbrmachine/Binary-bot-br/issues/1#issue-906475855

**Comment by Xbrmachine** [comment]
Como dialogado no grupo do telegram https://t.me/botbr

Levantei a hipotese de realizar a gestão da estratégia e dar a ela a importancia necessária para que ao aplicar a estrategia adequada possamos obter retorno ao longo do tempo ainda que tenhamos multiplas percas.

Aplicando uma versão personalizada do metodo soros e sem martigalle, aprimorando as entradas com o lucro obtido o dividindo pela gestão que acharmos mais adequada:

![image](https://user-images.githubusercontent.com/84425979/120250405-61df5600-c254-11eb-8b88-30fbb2cde7e2.png)
