### ISSUE TITLE
Can mention Entry Spot price in binary bot?

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3264]
Normally , entry spot is next digit to last digit
Example
Tick 3223.50 /  Last digit is 0
Next Tick is 3223.78 / Last digit is 8
Entry spot is 8

I want to mention this entry spot.
How can I do it
I invite to senior developers ho had experience in this.
Please help me.

Condition is 
if entry spot not equal to last digit

**Comment by binary-ex-machina** [comment]
the only I see to get the entry value and the entry digit is on block 4, where is possible to get the contract parameters

![image](https://user-images.githubusercontent.com/34610787/120084800-919e2a80-c0a9-11eb-8a05-912c1839ac60.png)

**Comment by vnxz** [comment]
> 
> 
> the only I see to get the entry value and the entry digit is on block 4, where is possible to get the contract parameters
> 
> ![image](https://user-images.githubusercontent.com/34610787/120084800-919e2a80-c0a9-11eb-8a05-912c1839ac60.png)

thanks friend ,I got it
