### ISSUE TITLE
MARTINGALLE PARA UM RESULTADO EFICAZ!!!

### ISSUE THREAD

**Issue by Xbrmachine** [binary-com/binary-bot#3265]
![image](https://user-images.githubusercontent.com/84425979/118883842-1af47680-b8cc-11eb-83a0-d998945dc1ad.png)

SEGUINTE:

Gostaria que após 1 perca o martingale invertesse a direção do trade por exemplo:

UMA OPERAÇÃO CALL = LOSS
PROXIMO CANDLE ABRE UMA VENDA = PUT

Há dois preoble as encontrados neste codigo:
1- ele não abre o martingalle no proximo candle (está executando apenas no proximo sinal)
2- não está abrindo o martingale na direção oposta do loss

Por gentileza nobres, podem auxiliar?

**Comment by cleberscr** [comment]
tente o martingale tradicional
