### ISSUE TITLE
How can filter last predit number not to trade 2nd time with same signal

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3267]
I made a differ bot based on digit analyzer.
Tick 100 
least digit % is under 5
Trade on 1 Tick duration
if least digit % under 5 and predit this least number to open order
But I dont want to trade this previous predit number because signal is not finish after exit spot happen
still count and this same signal happen .Bot again enter with same predit number
This frequent order around 4 times will be one loss happen.
So I want to prevent not to open next trade with previous predit number
How can set previous predit number value with timestamp .

![Screenshot_1](https://user-images.githubusercontent.com/76085185/118990558-01752c80-b9a9-11eb-8eb9-28a1ed7bae33.png)

@saidforex26
@ex-machina

**Comment by saidforex26** [comment]
please send the bot. I can edit it for you

**Comment by vnxz** [comment]
> 
> 
> please send the bot. I can edit it for you

[raw.zip](https://github.com/binary-com/binary-bot/files/6527904/raw.zip)

thanks bro here is bot.

**Comment by saidforex26** [comment]
[new raw 2seconsds.zip](https://github.com/binary-com/binary-bot/files/6528663/new.raw.2seconsds.zip)

**Comment by vnxz** [comment]
> 
> 
> [new raw 2seconsds.zip](https://github.com/binary-com/binary-bot/files/6528663/new.raw.2seconsds.zip)

thanks bro I will test now.

**Comment by vnxz** [comment]
I get the solution by myself . But it is still not profitable LOL .
I give up in digit differ bot.
