### ISSUE TITLE
Velas em Sequência acima/abaixo de SMA (Sequence candles above/below SMA)

### ISSUE THREAD

**Issue by Nandossp** [binary-com/binary-bot#3268]
Gostaria de saber se saber se é possível o bot dar entrada, por exemplo, 1 ou mais velas, (no rompimento) seguindo a sequência, sendo que a regra seria que a vela fechasse acima ou abaixo da média móvel. Obrigado. Na foto, exemplo de venda.

I would like to know if it's possible made a bot, operating, for example, 1 or more candles, (candle breaking), following the sequence (green or red), above or bellow of the SMA. Thanks. On the picture, a selling example.

![Candles abaixo SMA](https://user-images.githubusercontent.com/84539562/119034508-c8c35c00-b984-11eb-8876-f990ea231df9.PNG)

**Comment by binary-ex-machina** [comment]
Ficou um pouco confuso a sua explicação sobre a estratégia, se é para comprar no rompimento ou se é para comprar em todas as velas.

Se for para comprar na direção da abertura e fechamento das velas com o MA, essa ideia abaixo vai funcionar
![image](https://user-images.githubusercontent.com/34610787/120084658-551dff00-c0a8-11eb-9388-c14c4294549c.png)

Se for apenas no cruzamento, dai precisa mudar os sinais nos blocos de comparação
![image](https://user-images.githubusercontent.com/34610787/120084669-71ba3700-c0a8-11eb-94e3-8e389a7d05e9.png)

a parte que compara os segundos é para a analise ser feita apenas uma vez no final da vela atual

**Comment by Nandossp** [comment]
Olá amigo, na verdade, o exemplo seria: Formaram 3 velas verdes acima da média, quando a quarta vela romper a terceira vela sequencial, se dá a entrada para o fechamento e Expiração nesta mesma quarta vela....pode ver no gráfico, principalmente das volatilidades que isso muito certo...candles de M1

**Comment by binary-ex-machina** [comment]
Testei aqui e esta funcionando assim: Após o cruzamento do candle com a média, aparecendo 3 candles na mesma direção do cruzamento, quando o preço no 4º candle cruzar a máxima/mínima do candle, o bot compra a favor.

![image](https://user-images.githubusercontent.com/34610787/120219572-cdec9a80-c211-11eb-8db1-36921d3993aa.png)
![image](https://user-images.githubusercontent.com/34610787/120219585-d3e27b80-c211-11eb-9bf9-dc29b9d36efb.png)

**Comment by Nandossp** [comment]
Obrigado amigo, legal, vou testar e com certeza te dou um feedback nos próximos dias....essa estratégia eu peguei de um curso que comprei para mini índice e mini dolar. E nos mercados de volatilidade da Binary, vi que com algumas adaptações, (ao menos visualmente) é muito assertivo.

**Comment by Nandossp** [comment]
![image](https://user-images.githubusercontent.com/84539562/121078292-2215f280-c7af-11eb-8657-1a0ecfa153bd.png)

Fala amigo blz? Consegui testar somente agora, e achoque estou fazendo alguma coisa errada. O padrão parece que está certinho, agora, quando ele dá a entrada, o tempo de finalização está em 45 minutos....desculpe, mas não entendo de programação, procurei nas configurações do robô, mas parece estar tudo normal....sabe o que poderia ser?
