### ISSUE TITLE
trading bot

### ISSUE THREAD

**Issue by teeekaypython** [binary-com/binary-bot#3271]
hello everyone i have been trying to develop my own trading robot using python. Can someone explain to me the procedure to get  live prices from the deriv server to my tradin robot using socketstrem API or any other tool. The trading robot will only identify what it is trained to from its server, i wasnt looking forward to embeed it on MT5 or Trading View, Your help is greatly appreciated

**Comment by vnxz** [comment]
> 
> 
> hello everyone i have been trying to develop my own trading robot using python. Can someone explain to me the procedure to get live prices from the deriv server to my tradin robot using socketstrem API or any other tool. The trading robot will only identify what it is trained to from its server, i wasnt looking forward to embeed it on MT5 or Trading View, Your help is greatly appreciated

how can trade binary with python?
I interest
