### ISSUE TITLE
Over/Under bot creation help..

### ISSUE THREAD

**Issue by Chaosallon** [binary-com/binary-bot#3276]
Please help me to create the below strategy using the below figures.

Synthetic Indices - Volatility 100 index
Digits - Under/over
Duration - 1 tick
Last digit prediction - 5
Stake - 1 USD
Martingale level - up to 3 (multiply by 2.0 in each level) after the final level reached, stop the bot.
Wining method - Match the last digit as between 6 to 9, exact four times continuously (such as the last digit - 6,8,9,7, 9978, 8867 or combinations which relates to the above method) then purchase digit under. 

This is what I'm using in smart trader,
![image](https://user-images.githubusercontent.com/44803831/119317971-6032f280-bc96-11eb-9d14-5de7c453147f.png)

Experts, please help...

Thanks

**Comment by cleberscr** [comment]
[under5.zip](https://github.com/binary-com/binary-bot/files/6533163/under5.zip)

**Comment by Chaosallon** [comment]
@cleberscr   This is great and it's complex. I will check this and let you know. at the moment it works with balance result. 
Thank you very much for the support.

**Comment by Chaosallon** [comment]
@cleberscr Please add martingale settings up to 5 failures then start with an initial stake. 
 your earlier support is highly recommended
[under5.zip](https://github.com/binary-com/binary-bot/files/6571409/under5.zip)
.

Thanks
