### ISSUE TITLE
Where are the Binary Bot server, I am ready to buy VPS, hoping to choose the best country? United States OR United Kingdom??

### ISSUE THREAD

**Issue by gaorufeng** [binary-com/binary-bot#328]
Where are the Binary Bot server, I am ready to buy VPS, hoping to choose the best country? United States OR United Kingdom??

The Vultr VPS can choose different regions.

Tokyo
Japan

Singapore
Singapore

London
United Kingdom
Frankfurt
Germany

Paris
France

Amsterdam
Netherlands
Miami
United States

Atlanta
United States

Chicago
United States
Seattle
United States

Los Angeles
United States

Dallas
United States
New York (NJ)
United States

Silicon Valley
United States

Sydney

**Comment by aminmarashi** [comment]
"USA based server should be better than Europe latency-wise. Although anywhere in the USA will work well, the AWS North Virginia region is suggested and considered stable."
