### ISSUE TITLE
t.Native Global string is not a function

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3282]
what wrong with binary.com 
It show this error
![Screenshot_2](https://user-images.githubusercontent.com/76085185/119524038-46330600-bda3-11eb-9051-5c6241c27248.png)

**Comment by Goodluckwal** [comment]
Yes the same issue .....
why....?

**Comment by Cristianotx** [comment]
Same issue here..

**Comment by Goodluckwal** [comment]
> Same issue here @aaimio, it start today
> [dalembert.zip](https://github.com/binary-com/binary-bot/files/6540814/dalembert.zip)

Hai Trident2005...
What is dalembert.zip....?

**Comment by thwalimer** [comment]
hey como están, pensé que solo era error mío pero veo que no, el problema pasa por el uso del martingala.

**Comment by saharaku91** [comment]
I have the same issue, but i was used Deriv.com and it's still normal running.

What happened of Binary.com?

**Comment by trident2005** [comment]
> > Same issue here @aaimio, it start today
> > [dalembert.zip](https://github.com/binary-com/binary-bot/files/6540814/dalembert.zip)
> 
> Hai Trident2005...
> What is dalembert.zip....?

It is money management based on Dalembert theory

**Comment by saharaku91** [comment]
So, if you have an issue about binary.com.
You can try your bot at Deriv.com.

Same platform and can running very well,

**Comment by vnxz** [comment]
> 
> 
> So, if you have an issue about binary.com.
> You can try your bot at Deriv.com.
> 
> Same platform and can running very well,

I cannot load some my binary bot to deriv.

**Comment by Goodluckwal** [comment]
> > So, if you have an issue about binary.com.
> > You can try your bot at Deriv.com.
> > Same platform and can running very well,
> 
> I cannot load some my binary bot to deriv.

Yes, I have same issue, the bot can load to deriv, but not running.....

**Comment by Goodluckwal** [comment]
I have contacted the binary customer service via chatlive and the answer is as below:

Dear Goodluckwal,

Greetings from Binary and Deriv.

We have run and tested all six of your XML files and found that all files are working fine. There is no problem running using the bot. If the issue persists, we strongly recommend you contact the developer itself and let him/her know about your issue.

As a gentle reminder, you may also check and ensure you enter the correct stake before running the bot. The stake is varies depending on your XML files uploaded.

Should you have any further issues, please feel free to reach out to us via LiveChat or reply back to this email.

Thank you.

Regards,
Binary and Deriv



What does it mean ?

**Comment by Cristianotx** [comment]
The bot returned to work here as a magic pass!! haha

**Comment by Goodluckwal** [comment]
Hmmm ... looks like it's normal again, I've run some bots

**Comment by carol-binary** [comment]
Hello,

We had this issue for a couple hours but it's been fixed now, if the issue persists for you, please refresh the bot page and it should be okay. 

Regards,
Carol

**Comment by thwalimer** [comment]
Si actualmente sirve, tan raro debe ser un error de la plataforma si persiste informaré.
