### ISSUE TITLE
Issue about binary bot

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3283]
@aaimio 
Why binary bot platform has error ,Bot cannot run today and tick chart cannot load data .
It is warning sign to shut down binary bot?
Why cannot load binary bots to Deriv ?
How can convert B bot to D bot ?

**Comment by Goodluckwal** [comment]
How to contact binary bot?

**Comment by carol-binary** [comment]
Hello @vnxz and @Goodluckwal, 

We're prioritizing a fix for this and it should be released soon, I will update you here when it's done.

Regards,
Carol

**Comment by vnxz** [comment]
> 
> 
> Hello @vnxz and @Goodluckwal,
> 
> We're prioritizing a fix for this and it should be released soon, I will update you here when it's done.
> 
> Regards,
> Carol

please update tick chart, it still not load any tick data.

![Screenshot_1](https://user-images.githubusercontent.com/76085185/120063331-a15b4600-c08c-11eb-8faf-37a9b80e7ecd.png)

**Comment by carol-binary** [comment]
Hi @vnxz, 

We've released the fix for this bug, please let me know if you still face it. 

Regards,
Carol

**Comment by vnxz** [comment]
> 
> 
> Hi @vnxz,
> 
> We've released the fix for this bug, please let me know if you still face it.
> 
> Regards,
> Carol

thanks bug gone.
