### ISSUE TITLE
How to read this 2 digit and as Number

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#329]
Hi everyone,

I need to read this 2 digit as whole number like 54,67,87 and compare them with each other.
So I need to find at the next digit the number is bigger than the previous one ? Need to read 3 or 4 levels..
![vol 50](https://user-images.githubusercontent.com/20506657/28389021-72658d14-6ccc-11e7-9916-e2679daea29f.png)

**Comment by Fruitfella** [comment]
This is how you get that 2 digits
![capture](https://user-images.githubusercontent.com/26277327/28389710-828bc41c-6d01-11e7-9ac1-16b875ef2ecc.PNG)

**Comment by sarderiftekhar** [comment]
Thanks Fruitfella. But how to do it if I need to read 5 of them continuously one after another?

**Comment by Fruitfella** [comment]
you can either put each of them into a variable or you can put them into a list.
if you read #223 , you can find how to do that. the only different is that #223 analyze the last digit.

**Comment by okovalov** [comment]
@Fruitfella I am glad you guys found work I have done useful and continue to use it and extend it.

**Comment by Fruitfella** [comment]
hi @okovalov
I'm more glad than u _lol_ , I learned a lot from u, and from amin too😄

**Comment by sarderiftekhar** [comment]
Hi, Its working, but I am stuck with negative value. How do I make a negative value positive>

Like difference coming -10, want to make it 10 to trigger an action?

**Comment by sarderiftekhar** [comment]
Not to worry Solved it...........many thanks guys
