### ISSUE TITLE
update new

### ISSUE THREAD

**Issue by saidforex26** [binary-com/binary-bot#3292]
new update www.binarybotstudio.com

a. update issue
b. add 6seconds,10seconds, 15seconds ,20seconds,and 30seconds candle interval
c. add indicator:
1. Arnaud Legoux MA
2. Average True Range
3. Awesome oscillator,
4. Choppiness Indicator
5. Commodity Channel Index
6. Double MA
7. Hull MA
8.Ichimoku Cloud
9. Price Oscillator
10. Smoothed Moving Average
11. Stochastic
12. Triple MA
13. True Range
14. Weighted Moving Average (WMA)
15. Williams Alligator
16. Williams% R

**Comment by binary-ex-machina** [comment]
The interface is a little messy and some windows are overlapping each other, which may be confusing for the bot setup. The addition of the indicators is very good. Nice work so far

**Comment by saidforex26** [comment]
> The interface is a little messy and some windows are overlapping each other, which may be confusing for the bot setup. The addition of the indicators is very good. Nice work so far

thanks master. the source of the indicator is from your github. my website built it myself so the display is still not good. please advise the master how to adjust the interface so that it can be better at building bots.

**Comment by binary-ex-machina** [comment]
The main problem of the bot builder you did in the latest version of Google blockly is hard to customize. To make it really better and mix well with your interface will require a lot of work and testing (I tried to build something in that idea too, didn't work well and I couldn't fix the issues). For the overall website, check Google Material Design, they have a lot of libraries to make the interface more seamless, maybe this helps you. The idea is nice, you build any strategy you want and have some kind of dashboard to check the charts and the statistics. Keep it going!

**Comment by saidforex26** [comment]
I really listed my master's advice. I will update it and test it again. Whatever advice is given, it really helps me in the first ...

**Comment by sundaybaezofficial** [comment]
BRO @saidforex26 THE XML FILES DONT WORK

**Comment by saidforex26** [comment]
> BRO @saidforex26 THE XML FILES DONT WORK

who are you using xml from. the binary.bot XML file cannot be run on www.binarybotstudio. big and vice versa,

**Comment by sundaybaezofficial** [comment]
> > BRO @saidforex26 THE XML FILES DONT WORK
> 
> who are you using xml from. the binary.bot XML file cannot be run on [www.binarybotstudio](http://www.binarybotstudio). big and vice versa,

ok perfect bro  thanks , i can have 10 index with virtual loss at the same time ?

**Comment by saidforex26** [comment]
okay .. maybe tomorrow I will update the website. because the website was online when there was some BUG in the profit details. and the addition of virtual blocks that can be created up to 100 Virtual BOTs. so can create 200 BOT in 1 XML file
