### ISSUE TITLE
Need Help in Last Digit series bigger or smaller custom function

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3294]
I want to mention last 5 digits as their increasing of decreasing
example 
last tick digit is 9
4th tick digit is 8
3rd tick digit is 7
2nd tick digit is 5
1st tick digit is 3

35789  3 < 5 < 7 < 8 < 9 

86531 8 > 6 > 5 > 3 > 1 

I set as follow but it is not correct ,

![Screenshot_6](https://user-images.githubusercontent.com/76085185/120371549-fcff2b00-c33b-11eb-8be2-b6c5bc3f2260.png)

when i = 1 , 
1+1 < 1 

1+2 < 2
1+3 < 3
1+4 < 4
1+5 < 5

2nd place digit need to compare with 3rd place digit 
3rd place digit need to compare with 4th place digit
4th place digit need to compare with 5th place digit

Please help me 

![Screenshot_7](https://user-images.githubusercontent.com/76085185/120371920-89a9e900-c33c-11eb-8c87-2695a7f24641.png)

![Screenshot_4](https://user-images.githubusercontent.com/76085185/120371591-0b4d4700-c33c-11eb-8c90-0104aa1c5f2d.png)
check picture
last digit  are not correct when show result.
7 3 3 1 2 
1< 2 / so it should be larger sign
3 > 1 / it should be smaller sign
3 = 3 / is should be equal sign
7 > 3 / it should be smaller sign 

what wrong?

here is block 

[sample .zip](https://github.com/binary-com/binary-bot/files/6579783/sample.zip)

**Comment by binary-ex-machina** [comment]
try like this

![image](https://user-images.githubusercontent.com/34610787/120385366-b2f75480-c2fd-11eb-8884-273cc480f662.png)

![image](https://user-images.githubusercontent.com/34610787/120385403-c0144380-c2fd-11eb-8c8e-e98a3b0936fe.png)

**Comment by vnxz** [comment]
> 
> 
> try like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/120385366-b2f75480-c2fd-11eb-8884-273cc480f662.png)
> 
> ![image](https://user-images.githubusercontent.com/34610787/120385403-c0144380-c2fd-11eb-8c8e-e98a3b0936fe.png)

thanks friend , I found  I wrong is listing block, So I see wrong digit list , thanks

**Comment by vnxz** [comment]
> 
> 
> try like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/120385366-b2f75480-c2fd-11eb-8884-273cc480f662.png)
> 
> ![image](https://user-images.githubusercontent.com/34610787/120385403-c0144380-c2fd-11eb-8c8e-e98a3b0936fe.png)

if want to compare over 1 digit place in digit series  ,
example  4782  
     4 < 8 
     7 > 2
     8 > 2
   
How can compare

**Comment by Pabzev** [comment]
Could you please share you xml. I'd like to test it. @vnxz
