### ISSUE TITLE
Binary Bot stops in the "Attempting to buy" stage

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#3295]
Hello everyone,

Does anyone know why a binary bot sometimes abruptly stops in the "Attempting to buy" stage? This happens even if there is sufficient balance remaining in the account.

Thanks in advance.

**Comment by binary-ex-machina** [comment]
try activating this option

![image](https://user-images.githubusercontent.com/34610787/120385547-f05be200-c2fd-11eb-970a-ecf01c429bd0.png)

![image](https://user-images.githubusercontent.com/34610787/120385586-fb167700-c2fd-11eb-9044-bd33672a2e00.png)

**Comment by binarybotbegginer** [comment]
> try activating this option
> 
> ![image](https://user-images.githubusercontent.com/34610787/120385547-f05be200-c2fd-11eb-970a-ecf01c429bd0.png)
> 
> ![image](https://user-images.githubusercontent.com/34610787/120385586-fb167700-c2fd-11eb-9044-bd33672a2e00.png)

Thanks a lot. But sorry, I was not able to find it. Can you please tell me where can it be found?

Also, is it just available in DBot? Is it not available in Binary Bot?

Thanks in advance.

**Comment by binary-ex-machina** [comment]
both are available on the Block 1

**Comment by binarybotbegginer** [comment]
> both are available on the Block 1

Oh yes, I found it. Thanks

**Comment by binarybotbegginer** [comment]
> both are available on the Block 1

Just found that it stops even when this option is activated.
