### ISSUE TITLE
Need Help in money management block

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3296]
I believe only good money management can maintain account in binary bot.
So I interest in MM
 this Money management style .I will explain here , plz code this

It based on win step and loss step
original stake is 0.35
Rule is 

from start , it win , no change stake 
example = 0.35 / 0.35 / 0.35 / 0.35 ( All win / no change )
if loss , start manage here
if loss , reduce ( original stake divided by 1.9 ) of  loss stake to trade next 

example 0.35 loss , it is minimal stake no need to reduce stake , so 

if 0.35 stake loss , next trade stake is 0.35 

if still loss this 0.35 

multiply by 1.4 
0.35 loss
0.39 loss
0.53 loss
0.71 loss
0.96  WIN , If win here wining management ,if win next stake is , win stake * 1.4 ,
example 0.96 stake win , next stake is 1.34
only 2 step win and reset to original stake 0.35
0.95 win
1.34 win
reset stake 0.35

if loss this 1.4 stake , it will reduce to 1.4 divided by 1.9 , so reduce to 0.73 stake
if 0.73 stake loss , multiply by 1.4 , so next stake is 1.03
if win 1.03 stake , next stake is 1.03 * 1.94 = 1.99 stake
if loss 1.99 , change stake to 1.99 divide by1.9 = 1.05
if 1.05 loss , multiply by 1.4 = 1.47 stake

Conclusion 

loss stake divided by 1.9
win stake multiply by 1.4
if loss stake is 0.35 , no change stake
only 2 step win stake split

Can someone help me.
I try this block . I still not get correct result.

**Comment by binary-ex-machina** [comment]
maybe this is what you are looking for

![image](https://user-images.githubusercontent.com/34610787/120860708-7c6b4500-c55c-11eb-96ab-94b3faae0fca.png)

**Comment by vnxz** [comment]
> 
> 
> maybe this is what you are looking for
> 
> ![image](https://user-images.githubusercontent.com/34610787/120860708-7c6b4500-c55c-11eb-96ab-94b3faae0fca.png)

IF also need to multiply to reduce stake , how can do
example
0.99 stake loss
reduce to 0.55 stake
0.55 stake loss and next stake multiply by 1.4
where  need to edit

**Comment by binary-ex-machina** [comment]
Change the **initial** variable to 0.55. The bot will check if the stake is equal to the initial and then apply the rules for starting applying the factor for the losses. My opinion is this: too much complexity for the same result as a normal martingale

**Comment by Pabzev** [comment]
Hi. I have tested  a strategy which consists in 4 consecutive LDP and then open Digit Differs. This strategy provided me good profits but up to a point.  The traditional martingale risks too much and it is not so viable for small accounts. I tested your MM system you applied separately with other strategies  I'd like to use  the MM above  in combination of 4 consecutive LDP strategy.
Could either of you add this strategy on the bot I got here? Thank you.
[DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip](https://github.com/binary-com/binary-bot/files/6660080/DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip)

**Comment by Pabzev** [comment]
@binary-ex-machina  Could you please assist above...I'd really appreaciate.

**Comment by binary-ex-machina** [comment]
@Pabzev the bot you pot its not the one with digit differ. Just put the logic of your strategy on the money management that i did on this image https://github.com/binary-com/binary-bot/issues/3296#issuecomment-854989025 and try to make it work

My advice: dont waste time trying to split the losses on the next trades, it may work on small number of trades, but on long run you will never recover

**Comment by Pabzev** [comment]
Got it. Thank you, meu amigo. It was a pleasure.

**Comment by Pabzev** [comment]
@binary-ex-machina would you have the xml file of that strategy so I can save some time?

**Comment by Pabzev** [comment]
@binary-ex-machina Sir, I really liked the settings from your MM system. Trying to adjust a stratategy, which one you'd think it is more consistent? More relevant to spend some time on? Thanks in advance.
