### ISSUE TITLE
Help for create a bot

### ISSUE THREAD

**Issue by john3893** [binary-com/binary-bot#3299]
Hello
I have a good startegy but i need someone to help for create a bot for this
The rules for strategy (over/under)  ( vol 10 or 100)
1 - we need a blue tick under 7 just should not be 7,8,9
2 - after a blue tick should see the red tick with 7 number ( We do not need blue 7 just after a blue tick we see a red tick with number 7)
after this we have to open under position at number 7 .
Martingale rate should be 2.5 
If possible please make a bot with this rule and send that xml file here
Thank you

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/121063735-14f00800-c79d-11eb-8cc1-181a4d322dbb.png)

**Comment by john3893** [comment]
@binary-ex-machina 
Thank you alot
Would you please add a block for blue tick it should be under 7 i forgot to add it in thread

**Comment by binary-ex-machina** [comment]
@john3893 blue tick is just a tick going up. The logic is already on the image I sent

**Comment by john3893** [comment]
@binary-ex-machina 
Yeah you right
But bot is not working i got this error
Cannot read property slice for undefined
So what is problem here? Is that working for you?

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/121128164-88594e80-c85d-11eb-9596-841ac0ce7a23.png)

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/121129707-edae3f00-c85f-11eb-8744-bdb2771193de.png)

**Comment by saidforex26** [comment]
[under 7BR Bbsd.zip](https://github.com/binary-com/binary-bot/files/6613734/under.7BR.Bbsd.zip)

**Comment by john3893** [comment]
@saidforex26 Thank you buddy
But would you please add this to the bot:
Martingale does not work
and if possible blue tick should be under 7 if see this numbers 7,8,9 and then see a 7 red dont put trade just open trade for under 7 blue ticks

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/121176209-88be0d80-c88e-11eb-8e4a-98ecfcb400ac.png)
[under 7BR Bbsd.zip](https://github.com/binary-com/binary-bot/files/6616000/under.7BR.Bbsd.zip)

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/121176688-17cb2580-c88f-11eb-85ac-f244110f5b58.png)
I look at the history of the strategy, it seems that it will lose too. but first try the one I just sent

**Comment by john3893** [comment]
@saidforex26 Yes there will be some loose but i have test this strategy for more than one week in different times usually after a lost position you can recover this losses with 2 or 3 times with martingale
Anyway i will test the bot and will share result here thanks for your help

**Comment by john3893** [comment]
![20210608_162208](https://user-images.githubusercontent.com/85484604/121180197-d24e2e80-c875-11eb-9c74-360d7e84798f.jpg)
@saidforex26 martingale still not fixed
After a lost trade should trade with 3.5$ to recover this loss

**Comment by saidforex26** [comment]
[under 7BR Bbsd v2.zip](https://github.com/binary-com/binary-bot/files/6616247/under.7BR.Bbsd.v2.zip)

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/121182861-12bda480-c896-11eb-865c-8b168d46b21d.png)
[under 7BR Bbsd virtual 2x.zip](https://github.com/binary-com/binary-bot/files/6616322/under.7BR.Bbsd.virtual.2x.zip)

this one I use virtual loss 2x or win 2x then the bot continues again. you have to connect the token also on the virtual page

**Comment by john3893** [comment]
![20210608_173352](https://user-images.githubusercontent.com/85484604/121190000-ded78480-c87f-11eb-9ae4-ad8b20963fba.jpg)
![20210608_173357](https://user-images.githubusercontent.com/85484604/121190025-e39c3880-c87f-11eb-90ba-2b344669b810.jpg)
@saidforex26 I did it but its still without martingale
What's wrong with my settings?

**Comment by saidforex26** [comment]
please take a photo of your screen code. and is there a green page refresh button on the screen in the upper left corner?

**Comment by saidforex26** [comment]
maybe you are still using the old version of the website. please clear your browser cache. after that reopen the website and click CTR-F5 on the keyboard

**Comment by john3893** [comment]
![20210608_211845](https://user-images.githubusercontent.com/85484604/121225973-4b15b080-c89f-11eb-9027-786d1a126149.jpg)

@saidforex26 I did all you said and nothing changed and still can't trade with martingale

**Comment by john3893** [comment]
Anothet shot : 
![20210608_212614](https://user-images.githubusercontent.com/85484604/121226841-3980d880-c8a0-11eb-8701-aa26170acb19.jpg)
also sometimes i face with this bug : 
![20210608_212633](https://user-images.githubusercontent.com/85484604/121226978-57e6d400-c8a0-11eb-8600-5860de0c085f.jpg)

look at trades several trades with 16$

**Comment by saidforex26** [comment]
in mine went well. maybe you can try this one
[under 7BR Bbsd virtual 2x v2.zip](https://github.com/binary-com/binary-bot/files/6620169/under.7BR.Bbsd.virtual.2x.v2.zip)

**Comment by alansilva1** [comment]
> no meu correu bem. talvez você possa tentar este
> [em 7BR Bbsd virtual 2x v2.zip](https://github.com/binary-com/binary-bot/files/6620187/under.7BR.Bbsd.virtual.2x.v2.zip)
I cannot add robot to the platform. Do you have a video explaining how it works??

**Comment by saidforex26** [comment]
![under br7](https://user-images.githubusercontent.com/54820719/121294974-da16dd00-c920-11eb-97b6-30720bcc352e.gif)

**Comment by john3893** [comment]
@saidforex26 Tried also in several PCs and martingale does not work i think this is platform bug

**Comment by saidforex26** [comment]
> @saidforex26 Tried also in several PCs and martingale does not work i think this is platform bug

please clear your browser. because here it works fine,

**Comment by saidforex26** [comment]
> @saidforex26 Tried also in several PCs and martingale does not work i think this is platform bug

fix it right away.

**Comment by john3893** [comment]
@saidforex26 Problem exist
Used multi browser also doesn't work
Is there a way to create it as dbot or binary.com bot platform?

**Comment by saidforex26** [comment]
to move bots to binarybot can't. because some blocks are not owned by binarybot. you have to create in binarybot like @binary-ex-machina created.


here the martinggale works fine. there is only an error in the appearance of the details of the win and loss and the profit. maybe you see negative profit . I'm fixing it

**Comment by john3893** [comment]
I used the bot that @binary-ex-machina shared but i faced with some errors and bot cannot be start.
If you can solve this issue on your platform so please let me know here when its solved

**Comment by saidforex26** [comment]
> I used the bot that @binary-ex-machina shared but i faced with some errors and bot cannot be start.
> If you can solve this issue on your platform so please let me know here when its solved

ok. please wait

**Comment by john3893** [comment]
@saidforex26 Hello dude
Did you solve this issue?
