### ISSUE TITLE
Notificação  Proposta de venda de contrato desconhecida

### ISSUE THREAD

**Issue by danielRaibolt123** [binary-com/binary-bot#3303]
Por favor, quem puder me ajudar.
Desenvolvi um Bot de Call e Put e ele está funcionando perfeitamente, até que de vez em quando aparece esse mensagem de Proposta de venda de contrato desconhecida e stopa o Bot.
Alguém sabe como resolver isso?
![Captura de Tela (64)](https://user-images.githubusercontent.com/42899863/121089326-5c868c00-c7bd-11eb-82e7-3dad4694e87f.png)

**Comment by saidforex26** [comment]
use www.binarybotstudio.com . automatically gives error notifications and also when there is an error then the error block will be red. so it's easy to find fault.

**Comment by saidforex26** [comment]
![image](https://user-images.githubusercontent.com/54820719/121126895-8098aa80-c85b-11eb-9a52-d561e9411aa2.png)

**Comment by binary-ex-machina** [comment]
@danielRaibolt123 posta uma imagem do bloco 3 aberto, talvez o problema de venda de contrato esteja ali

**Comment by danielRaibolt123** [comment]
> @ danielRaibolt123 posta uma imagem do bloco 3 aberto, talvez o problema de venda de contrato esteja ali

![Captura de Tela (80)](https://user-images.githubusercontent.com/42899863/121430470-83c09300-c94e-11eb-8e34-807c818d8225.png)
