### ISSUE TITLE
help me, I want to change the entry time

### ISSUE THREAD

**Issue by LichtNovancrhono** [binary-com/binary-bot#3304]
I am making a candlestick robot but the time for entry is not what I expected I want the entry time to be 2 seconds before the opening of the candlestick but I got a random time in my bot.
I could have used the "Run After(s)" command in the time line but it will get the data late because I want the robot to fetch the data a few seconds before the close of the candlestick
Thank you

![result](https://user-images.githubusercontent.com/85581912/121239922-03555000-c8c4-11eb-9ad7-ebfbbc50e472.png)
![problem result 1](https://user-images.githubusercontent.com/85581912/121239940-06e8d700-c8c4-11eb-953f-1db52b4c373c.png)
![problem result 2](https://user-images.githubusercontent.com/85581912/121239948-09e3c780-c8c4-11eb-8224-4a8d62ec31fb.png)

**Comment by binary-ex-machina** [comment]
Some computers have this "delay" in the entries, even if you use the right seconds like you are using (based on the image you sent). Try to change how your computer clock gets time (from the internet, not manually) and test for some NTP servers (for windows).

**Comment by LichtNovancrhono** [comment]
> Some computers have this "delay" in the entries, even if you use the right seconds like you are using (based on the image you sent). Try to change how your computer clock gets time (from the internet, not manually) and test for some NTP servers (for windows).

Thank you sir, I have solved this problem, it turns out that my Windows NTP is not configured properly
