### ISSUE TITLE
How can get this tick previous high

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3306]
I want to know how can get value of previous tick highest value as show in picture
I mean not Blue head .
I just want as similar concept of candle highest value in candle chart
So in tick chart, highest value of previous tick 
![Screenshot_5](https://user-images.githubusercontent.com/76085185/121386036-aadb8c80-c96f-11eb-97f1-eb7f5ab5213d.png)

**Comment by binary-ex-machina** [comment]
You can do like the image below. The logic is this:

1. Sort the ticks list with descending order (the highest numbers will come first), based on the sub-list with the range you want. then put on a variable
2. Now you can access the second-highest value with the get block with #2
3. In case you need the index of that value (so you can compare if it's on the range you are looking for), just use the find occurrence block and use the GET block with the index you want to compare

In the image below, the bot will purchase Rise in case the second-highest tick index is in the last 50 ticks (the Tick List block returns 1000 ticks, so the index will return with that length, so I used 950)

![image](https://user-images.githubusercontent.com/34610787/121441794-d440ec00-c960-11eb-9ea6-9fbde0e4fe88.png)

**Comment by vnxz** [comment]
> 
> 
> You can do like the image below. The logic is this:
> 
>     1. Sort the ticks list with descending order (the highest numbers will come first), based on the sub-list with the range you want. then put on a variable
> 
>     2. Now you can access the second-highest value with the get block with #2
> 
>     3. In case you need the index of that value (so you can compare if it's on the range you are looking for), just use the find occurrence block and use the GET block with the index you want to compare
> 
> 
> In the image below, the bot will purchase Rise in case the second-highest tick index is in the last 50 ticks (the Tick List block returns 1000 ticks, so the index will return with that length, so I used 950)
> 
> ![image](https://user-images.githubusercontent.com/34610787/121441794-d440ec00-c960-11eb-9ea6-9fbde0e4fe88.png)

actually I still not understand how to use this

 sub-list from #
 substring from #letter   
 find occurence of item
 find occurence of text

Thanks you master

**Comment by binary-ex-machina** [comment]
@vnxz send what you want to do, full logic. This way, I can help you make the strategy. 

If it's just to get the second-highest value in a period of ticks, this will do the job.

![image](https://user-images.githubusercontent.com/34610787/121547801-d9df1600-c9e2-11eb-940a-c3a7b457f1a4.png)

**Comment by vnxz** [comment]
> 
> 
> @vnxz send what you want to do, full logic. This way, I can help you make the strategy.
> 
> If it's just to get the second-highest value in a period of ticks, this will do the job.
> 
> ![image](https://user-images.githubusercontent.com/34610787/121547801-d9df1600-c9e2-11eb-940a-c3a7b457f1a4.png)

It work when no side trend. No loss
But in tick consolidation , it make false signal because of range movement,
If we can also filter range height ( if 1st previous tick highest = 2nd previous highest etc )

![Screenshot_2](https://user-images.githubusercontent.com/76085185/121549299-c019ef00-ca33-11eb-8f15-e4e5bb1bb624.png)


![Screenshot_1](https://user-images.githubusercontent.com/76085185/121549329-c6a86680-ca33-11eb-85fd-341cc68d48c0.png)

**Comment by binary-ex-machina** [comment]
But when the bot buys the contract? What's the logic to make it purchase?

**Comment by vnxz** [comment]
> 
> 
> But when the bot buys the contract? What's the logic to make it purchase?

if last tick higher than previous highest tick , bet CALL
Duration is second 15

**Comment by binary-ex-machina** [comment]
Try like this. If the latest tick is the highest, and the second-highest tick of the list is at least 25 ticks away from the latest highest tick, it purchases Rise. This way, you can get those peaks.

![image](https://user-images.githubusercontent.com/34610787/121557604-41995f00-c9eb-11eb-8037-5012cd491158.png)

Another way to do this, but without the distance between ticks idea, is to compare the last tick with the highest tick of the period. In case the last tick is the highest of the period, it means that its the new peak of that period

![image](https://user-images.githubusercontent.com/34610787/121558015-a81e7d00-c9eb-11eb-8e42-0a0573d2632b.png)

**Comment by vnxz** [comment]
> 
> 
> Try like this. If the latest tick is the highest, and the second-highest tick of the list is at least 25 ticks away from the latest highest tick, it purchases Rise. This way, you can get those peaks.
> 
> ![image](https://user-images.githubusercontent.com/34610787/121557604-41995f00-c9eb-11eb-8037-5012cd491158.png)
> 
> Another way to do this, but without the distance between ticks idea, is to compare the last tick with the highest tick of the period. In case the last tick is the highest of the period, it means that its the new peak of that period
> 
> ![image](https://user-images.githubusercontent.com/34610787/121558015-a81e7d00-c9eb-11eb-8e42-0a0573d2632b.png)

Thanks for help blocks master.
I testing now.
and also
how can filter side ranging of highest tick .


![Screenshot_2](https://user-images.githubusercontent.com/76085185/121562389-67e8ea00-ca3f-11eb-8329-a369eabe5779.png)

**Comment by binary-ex-machina** [comment]
Filter sideways is tough to do with precision. Normally you always get a 50% chance, but using a distance between ticks may help. Increase the amount that the last highest tick needs to be from the latest highest tick, and you will have less sideways (instead of 175 of the image I sent before, use 150 or 125). Numbers from 100. or less will be happening so often, and it will not improve the analysis very well

**Comment by vnxz** [comment]
> 
> 
> Try like this. If the latest tick is the highest, and the second-highest tick of the list is at least 25 ticks away from the latest highest tick, it purchases Rise. This way, you can get those peaks.
> 
> ![image](https://user-images.githubusercontent.com/34610787/121557604-41995f00-c9eb-11eb-8037-5012cd491158.png)
> 
> Another way to do this, but without the distance between ticks idea, is to compare the last tick with the highest tick of the period. In case the last tick is the highest of the period, it means that its the new peak of that period
> 
> ![image](https://user-images.githubusercontent.com/34610787/121558015-a81e7d00-c9eb-11eb-8e42-0a0573d2632b.png)

I need a little more clear in concept

in sublist first occurence of 2nd index tick mean ( sublist is 100 tick . right ?)
if want 2nd index in previous 50 ticks , should be
in sublist first occurence  > 50 ?

if want to purchase contract when last tick above this 2nd index
block is like that
if last tick > in sublist first occurence  > 50 
Right?

**Comment by binary-ex-machina** [comment]
> in sublist, first occurrence of 2nd index tick mean ( sublist is 100 tick . right ?)

sublist with from end 100 tp last means that the list will have the latest 100 ticks

> if want 2nd index in the previous 50 ticks, should it be in the sublist the first occurrence > 50?

No, that idea is to have ticks between the highest peaks. in case you use 50, the second-highest tick need to be at least 50 ticks before the actual highest tick

> if want to purchase contract when last tick above this 2nd index
> block is like that
> if last tick >2nd index value in sublist first occurrence > 50
> but in sublist, first occurrence block only return occurrence number but not show 2nd index value
> if directly call 2nd index value, it will show adjacent previous tick of last tick
> Right?

There is no need to check if the last tick is above the second highest. Just check if the last tick is the highest in that period and make sure the second-highest tick is at least 50 ticks behind the last tick.

> So how can notify this 2# index tick value as xxxz,zy

this has nothing to do with the highest tick; this is just the digits of that tick, which doesn't have any impact on the tick movement

It looks like you are asking two things that don't have anything in common with each other. Or you want to access the highest ticks in the charts, or you want to get digits after the comma.

**Comment by vnxz** [comment]
> 
> 
> > in sublist, first occurrence of 2nd index tick mean ( sublist is 100 tick . right ?)
> 
> sublist with from end 100 tp last means that the list will have the latest 100 ticks
> 
> > if want 2nd index in the previous 50 ticks, should it be in the sublist the first occurrence > 50?
> 
> No, that idea is to have ticks between the highest peaks. in case you use 50, the second-highest tick need to be at least 50 ticks before the actual highest tick
> 
> > if want to purchase contract when last tick above this 2nd index
> > block is like that
> > if last tick >2nd index value in sublist first occurrence > 50
> > but in sublist, first occurrence block only return occurrence number but not show 2nd index value
> > if directly call 2nd index value, it will show adjacent previous tick of last tick
> > Right?
> 
> There is no need to check if the last tick is above the second highest. Just check if the last tick is the highest in that period and make sure the second-highest tick is at least 50 ticks behind the last tick.
> 
> > So how can notify this 2# index tick value as xxxz,zy
> 
> this has nothing to do with the highest tick; this is just the digits of that tick, which doesn't have any impact on the tick movement
> 
> It looks like you are asking two things that don't have anything in common with each other. Or you want to access the highest ticks in the charts, or you want to get digits after the comma.

thanks master, I just need to know is it correct entry point when order enter in tick chart
and to adjust as require distance between two highest peaks.
thanks for support
