### ISSUE TITLE
É possivel mudar o trade type durante a execução do robo?

### ISSUE THREAD

**Issue by gdaneluti** [binary-com/binary-bot#3307]
Estou desenvolvendo uma estratégia na qual o meu trade type padrao é match/differ, eu gostaria de saber se é possivel eu mudar o trade type para over/under baseando-se em uma regra. Por exemplo quando acontecer duas perdas seguidas.

**Comment by binary-ex-machina** [comment]
não é possível usando os blocos

**Comment by gdaneluti** [comment]
Como seria possivel @binary-ex-machina ?

**Comment by binary-ex-machina** [comment]
Por api você consegue fazer qualquer combinação de trades e lógica

https://github.com/binary-com/binary-live-api

**Comment by precious2818** [comment]
@binary-ex-machina please how can I make a 5 tick prediction to start on the next candle eg the signal to trade appeared at 8:12:24(hrs/mins/seconds) how can I make it purchase trade on 8:13:00 if the next candle appear Instead of it appearing immediately the signal appears
