### ISSUE TITLE
Counting a senario 

### ISSUE THREAD

**Issue by sahanpremasiri** [binary-com/binary-bot#3311]
Can any one write a code to

Count no of occasions "odd digit after digit "6"  (for lat 30 digits)
if no of occasions mentioned above = 3, then purchase "EVEN" after digit "6"

**Comment by vnxz** [comment]
> 
> 
> Can any one write a code to
> 
> Count no of occasions "odd digit after digit "6" (for lat 30 digits)
> if no of occasions mentioned above = 3, then purchase "EVEN" after digit "6"

if you need help , you should post clearly what you want with example
example 
xxxy.x6
xxxy.xOdd number 
Right?
this will happen in last 30 digits 

that mean logic is

if
previous last digit is 6
current last digit is ODD ( may be 1 )

Change ( counter ) by 1

if counter = 3
if last digit 6

set counter to 0

EVEN BET 

This is logic
made it

**Comment by precious2818** [comment]
Please how can I make a 5 tick prediction to start on the next candle eg the signal to trade appeared at 8:12:24(hrs/mins/seconds) how can I make it purchase trade on 8:13:00 if the next candle appear Instead of it appearing immediately the signal appears
