### ISSUE TITLE
What Money management should be best for bot with Loss in a row maximum 6

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3312]
I made a RF bot , current situation is profit without martingale
Maximum loss in a row is 6
What Money management style suitable for this 
![Screenshot_1](https://user-images.githubusercontent.com/76085185/121811307-010b4100-cc8a-11eb-8222-13fb5845a707.png)

**Comment by Pabzev** [comment]
Hi. This is regarding money management block #3296 under your name. I have tested  a strategy which consists in 4 consecutive LDP and then open Digit Differs. This strategy provided me good profits but up to a point.  The traditional martingale risks too much and it is not so viable for small accounts. I tested your MM system you shared in block #3296 and applied separately with other strategies.  I'd like to use  that MM in combination of 4 consecutive LDP strategy.
Could  you add this strategy on the bot I got here? Thank you.
[DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip](https://github.com/binary-com/binary-bot/files/6660084/DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip)
