### ISSUE TITLE
Can Anyone Help me Create a bot for this strategy 

### ISSUE THREAD

**Issue by Eranga1978** [binary-com/binary-bot#3313]
Hi
Can anyone help me create a bot for this strategy?
Synthetic Index 10
High/Low
5 Ticks
Barrier off set +0.400
Purchase Lower
Entry point: Last digit turn to Red digit 1 when the market is going down.

**Comment by Eranga1978** [comment]
![4ABDFFBC-93C0-4EA5-ACAA-4329065721B8](https://user-images.githubusercontent.com/85838110/121814192-5bf26780-cc8d-11eb-9bae-4ea017970aaa.jpeg)

**Comment by vnxz** [comment]
> 
> 
> Hi
> Can anyone help me create a bot for this strategy?
> Synthetic Index 10
> High/Low
> 5 Ticks
> Barrier off set +0.400
> Purchase Lower
> Entry point: Last digit turn to Red digit 1 when the market is going down.

you did it manually ?
profit or not.
If profit , bot is easy.
if not , dont waste time
I made alot of bot with digit rise fall
loss in a row more than 6
useless

**Comment by Eranga1978** [comment]
> > Hi
> > Can anyone help me create a bot for this strategy?
> > Synthetic Index 10
> > High/Low
> > 5 Ticks
> > Barrier off set +0.400
> > Purchase Lower
> > Entry point: Last digit turn to Red digit 1 when the market is going down.
> 
> you did it manually ?
> profit or not.
> If profit , bot is easy.
> if not , dont waste time
> I made alot of bot with digit rise fall
> loss in a row more than 6
> useless

Yes I’ve done it manually. It is profitable. I need to create a bot.  Are you able to create a bot for above strategy.

**Comment by timnashcouk** [comment]
![Screenshot 2021-06-16 at 16 09 56](https://user-images.githubusercontent.com/5869812/122250008-377ed100-cec1-11eb-8094-7ff5a225410a.png)
Is your strategy as a bot, if the market is going down, and the last digit is 1 then trade. 
This is no more profitable then simply trading when the market goes down just slower.

Indeed by the joys of variance the just follow the downward trend out performed your strategy.

![Screenshot 2021-06-16 at 16 37 07](https://user-images.githubusercontent.com/5869812/122249999-351c7700-cec1-11eb-84b7-4658a5275fa3.png)

The problem with both, is you have margins similar to digits, where it's really difficult to handle money management, so unless you can consistently get over 90% win rate you are going to have to do something creative, which will inevitably lead to you going bust.

**Comment by Eranga1978** [comment]
> ![Screenshot 2021-06-16 at 16 09 56](https://user-images.githubusercontent.com/5869812/122250008-377ed100-cec1-11eb-8094-7ff5a225410a.png)
> Is your strategy as a bot, if the market is going down, and the last digit is 1 then trade.
> This is no more profitable then simply trading when the market goes down just slower.
> 
> Indeed by the joys of variance the just follow the downward trend out performed your strategy.
> 
> ![Screenshot 2021-06-16 at 16 37 07](https://user-images.githubusercontent.com/5869812/122249999-351c7700-cec1-11eb-84b7-4658a5275fa3.png)
> 
> The problem with both, is you have margins similar to digits, where it's really difficult to handle money management, so unless you can consistently get over 90% win rate you are going to have to do something creative, which will inevitably lead to you going bust.

The entry point in this needs to be when the digits turn RED and the LAST DIGIT is Number 3. Could you do that please.

**Comment by precious2818** [comment]
Please how can I make a 5 tick prediction to start on the next candle eg the signal to trade appeared at 8:12:24(hrs/mins/seconds) how can I make it purchase trade on 8:13:00 if the next candle appear Instead of it appearing immediately the signal appears
