### ISSUE TITLE
Please Help Me to pop up notification like this picture

### ISSUE THREAD

**Issue by LichtNovancrhono** [binary-com/binary-bot#3314]
Please let me know.
i want to pop up this notification what script should i add on my bot
thank you.
![timestamp](https://user-images.githubusercontent.com/85581912/121825535-37be7700-ccdd-11eb-99c9-4e2b46f8495b.png)

**Comment by vnxz** [comment]
> 
> 
> Please let me know.
> i want to pop up this notification what script should i add on my bot
> thank you.
> ![timestamp](https://user-images.githubusercontent.com/85581912/121825535-37be7700-ccdd-11eb-99c9-4e2b46f8495b.png)

go to Tools
Misc
choose notify block
