### ISSUE TITLE
I have a strategy that has 99% winning but I don’t know how to complete the code please help

### ISSUE THREAD

**Issue by precious2818** [binary-com/binary-bot#3317]
Please how can I create a strategy that if first candle is blue and rsi is less than 50 and second candle is red with no rsi purchase rise meaning I want the rsi to obey only the first candle and wait for the second candle to confirm with no rsi assign to the second candle`

**Comment by vnxz** [comment]
> 
> 
> Please how can I create a strategy that if first candle is blue and rsi is less than 50 and second candle is red with no rsi purchase rise meaning I want the rsi to obey only the first candle and wait for the second candle to confirm with no rsi assign to the second candle`

what mean no RSI
Code cannot set no RSI

**Comment by saidforex26** [comment]
> Please how can I create a strategy that if first candle is blue and rsi is less than 50 and second candle is red with no rsi purchase rise meaning I want the rsi to obey only the first candle and wait for the second candle to confirm with no rsi assign to the second candle`

use RSI With a list of close candles
![image](https://user-images.githubusercontent.com/54820719/122235280-25685700-cef0-11eb-865e-d7e0195340a5.png)
