### ISSUE TITLE
ERROR?!

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#332]
@aminmarashi 
![capture](https://user-images.githubusercontent.com/26277327/28411457-fcf365d4-6d6a-11e7-97eb-4be20c808eb8.PNG)
To day my bot didnt work poperly as it did before, so i made a few check like the pict above.
1. Notification seems doesnt work anymore in `function` and `every tick` blocks, though what i really want to check is whether it can get variable's value from other blocks like it used to be.
2. Main block (2) seems cant get variable's value from `function` and `every tick` blocks.
3. or perhaps the problem is on `function` and `every tick` blocks?

**Comment by aminmarashi** [comment]
Works fine for me: [var_set_test.xml](https://gist.github.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/var_set_test.xml)
1. Seems like you're using `ignore` block instead of `every tick`
2. You're not actually calling the `do something` function

**Comment by Fruitfella** [comment]
@aminmarashi ah, my bad _lol_ too tired and sleepy yesterday, didnt notice that. now I know that i should just get some sleep when tired, instead of doing serious thing.
also, i just tested my bot and its worked, I wonder if yesterday im really awake _lol_ 
i'll close this false alarm.
sorry for wasting ur time.. :P
