### ISSUE TITLE
O Projeto binary bot em qual linguagem foi escrita ?

### ISSUE THREAD

**Issue by luizchequini** [binary-com/binary-bot#3321]
Desculpe a falta de conhecimento mas Trabalho com desenvolvimento Web com Asp.Net com a linguagem C# e gostaria de estudar o binary bot.

Consegui realiza executar a aplicação no Visual Code, através dos comandos:

1. Mudei a porta de localhost:80 para localhost:4000 dentro do arquivo **gulpfile.babel.js**
2. Atualizei o npm
3. Executei o comando via prompt de comando - npm install
4. e após o comando - npm start

Mas tudo isto segundo o passo a passo descritos aqui no Github.

**A pergunta é qual linguagem esta aplicação foi desenvolvida.**

Fico no aguardo.

**Comment by binary-ex-machina** [comment]
na descrição do repositório, mostra quais linguagens foram utilizadas

![image](https://user-images.githubusercontent.com/34610787/123183572-2e18da00-d468-11eb-8972-b65f0df20be2.png)
