### ISSUE TITLE
Help with strategy

### ISSUE THREAD

**Issue by fperiin** [binary-com/binary-bot#3322]
I would like to know how I do indicate incoming inputs when the chart hits highs and lows. Example, when the graph hits the red ball it makes an CALL entry and when it reaches the green marble it makes an entry PUT

![image](https://user-images.githubusercontent.com/84112929/122313441-9c9bec00-ceec-11eb-90ef-7fac076e7e82.png)

**Comment by binary-ex-machina** [comment]
The "red ball" or "green ball" appears on the lowest/highest points on the chart. In case you zoom out a little more, those points will change place. They are calculated based on the visible data on the chart. Let's say in your chart you count 20 ticks, and you can get the highest/lowest ticks using the max/min block on the bot

![image](https://user-images.githubusercontent.com/34610787/123208301-36d3d500-d495-11eb-82af-5391ac6d5651.png)
