### ISSUE TITLE
last digit of the exit spot value 

### ISSUE THREAD

**Issue by rampageT** [binary-com/binary-bot#3325]
hello could someone help me , i need a bot with a martingale based on the exit spot value ,  specifically the last digit of the exit spot value e.g if the last trade exit spot value last digit was 5 then the bot must do a martingale if not 5 then the bot shouldnt  do martingale

**Comment by timnashcouk** [comment]
<img width="481" alt="Screenshot 2021-06-21 at 09 25 18" src="https://user-images.githubusercontent.com/5869812/122730939-b2097100-d272-11eb-9e2a-b005ac5135ba.png">
You can use the last digit under Tick Analysis.

**Comment by vnxz** [comment]
> 
> 
> hello could someone help me , i need a bot with a martingale based on the exit spot value , specifically the last digit of the exit spot value e.g if the last trade exit spot value last digit was 5 then the bot must do a martingale if not 5 then the bot shouldnt do martingale

here is how get last digit of exit spot

![Screenshot_2](https://user-images.githubusercontent.com/76085185/122738753-493ceb80-d2a8-11eb-928f-8b773fe32534.png)

**Comment by rampageT** [comment]
thanks i will test both methods out and send you my results
