### ISSUE TITLE
Help me, How to determine whether a candle is rising or falling as it ends

### ISSUE THREAD

**Issue by theboyof8x** [binary-com/binary-bot#333]
I can not setup my bot, so it can be determined when a candle ends as the candle is up or down...Plsss

**Comment by delonbh** [comment]
![image](https://user-images.githubusercontent.com/25711367/28417443-85e0b9b0-6d2e-11e7-8641-917c4faa51da.png)

**Comment by aminmarashi** [comment]
Take a look at [detect-a-new-candle-started](https://gist.github.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb#detect-a-new-candle-started) for detecting a new candle.
[Here](https://gist.github.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/green_or_red_on_new_candle.xml) is an example.
<img width="418" alt="screen shot 2017-07-21 at 9 32 27 am" src="https://user-images.githubusercontent.com/6560964/28445555-89c536f4-6df7-11e7-81e0-49cb3091e291.png">

**Comment by theboyof8x** [comment]
Thanks @aminmarashi Aminmarashi

My calculations are:
1 - If the current candles finish as the candles are dropped then the bot will enter the put order at the opening price of the next candles
2 - If the current candles are over candles, then the bot will enter the Call at the opening price of the next candles

My Bot Setup By Your Guide But It's On Invalid Order

![image](https://user-images.githubusercontent.com/30315833/28448775-f28125d8-6e04-11e7-845f-dc2b10cbe148.png)

**Comment by aminmarashi** [comment]
Just change to:
<img width="417" alt="screen shot 2017-07-21 at 12 44 29 pm" src="https://user-images.githubusercontent.com/6560964/28449407-5db24226-6e12-11e7-85c6-5149e8bd1343.png">
to read the second most recent candle.

**Comment by theboyof8x** [comment]
Dear @aminmarashi !

Sorry you for my limited knowledge ...

I added the bot as instructed but it still can not enter the Call / Put command at the start of the next Candle.

Can I Speak Back to Me When Setup Bot is Following, And Help Yourself:
   - Bot Will Read Current Candidate Data (M1 Time Frame - 1 minute form a Candle)
   -> When Candle Ends Candle is Up / Down
   -> Bot Will Go To Call / Put Order At The Right Time To Start The Next Candle

Thank you very much

**Comment by Fruitfella** [comment]
Try this @theboyof8x 
![capture](https://user-images.githubusercontent.com/26277327/28468055-093efdac-6e5c-11e7-9584-5cfded73565d.PNG)

**Comment by theboyof8x** [comment]
Dear @Fruitfella 

I have setup the Bot as instructed by you, but the Bot is still in command when the current Candle is not finished.

Emotions You study more about my desires.

Thank you very much
![candle](https://user-images.githubusercontent.com/30315833/28475685-78ab2b50-6e77-11e7-9968-5ac58e683f9a.jpg)

**Comment by Fruitfella** [comment]
@theboyof8x 
That actually happen after a few trades, cuz the trade's contract start 1 tick after u proposed it, it ended in 1 minute (entry to close) + 1 tick (start time to entry) while a candle is only 1 minute. So the next trade would late 1 tick and the next after it late 2 ticks and so on. Its hard to explain it with my limited english, hope u get it.
To solve this u need to give up 1 candle after every trade. So after a trade closed u dont make a purchase on that candle and wait for the next.

Try this 
![capture](https://user-images.githubusercontent.com/26277327/28476838-b1521708-6e7b-11e7-8132-957b505dff0a.PNG)

**Comment by Fruitfella** [comment]
@theboyof8x Actually, u dont need that `skip` variable, i accidentally mixed it with my strategy _lol_ , that `skip` will skip a tick after the first new candle open.
like this is better for u. no skip
![capture](https://user-images.githubusercontent.com/26277327/28477673-5be3c0c4-6e7f-11e7-8d08-2f4f7ef1baf5.PNG)

**Comment by theboyof8x** [comment]
Thanks @Fruitfella 
Bot Fruitfella set it up!
Bot In Command 2s slow when Candle 3 forms - so good :)
Logic In Command Of The Bot:
  1..Bot Enter the Order in Candle 1 (as shown in the attached picture)
  2..Bot Wait for Candle 2 to form and finish
  3..Bot Enter Commands at Candle 3
Now I Just Compute a Strategy for Bot Activity ...
I lost a lot of $ to Bot first.

Thank you very much!
![sdsdsd](https://user-images.githubusercontent.com/30315833/28478892-671d4b5e-6e84-11e7-9417-e40795dee76d.jpg)

**Comment by Fruitfella** [comment]
@theboyof8x 
this is my email : rudika.fx@gmail.com
i'll try to fix it but please dont forget to explain the strategy in detail.

**Comment by folubebe** [comment]
Can you creat bot using stoch

**Comment by montanarop** [comment]
where is the bot
