### ISSUE TITLE
Even odd Bot request

### ISSUE THREAD

**Issue by cromeaxe** [binary-com/binary-bot#3332]
- market 100 index
- Based last tick pattern i.e. 
(EE,OO,EOO,OEE,EEEE,OOOO) modifiable
- trade on maximum two pattern
- wait function after win/loss in sec
- marti multiplier, max marti stop, 1 tick trade, target tp and sl

Thanks 😃 

Ps attached pic for info
![Screenshot_2021-06-22-13-03-30-87](https://user-images.githubusercontent.com/60475279/122884258-95953380-d35b-11eb-81b4-4bffed850610.png)

**Comment by binary-ex-machina** [comment]
Use on the auto trader web, its easier and faster to use

**Comment by cromeaxe** [comment]
> Use on the auto trader web, its easier and faster to use

Its easier to use..but payout is less than original
