### ISSUE TITLE
Can made trailing stop in binary bot?

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3333]
![Screenshot_2](https://user-images.githubusercontent.com/76085185/122893005-ed3b9b00-d36b-11eb-865b-6f7b14acc056.png)
I want to know if there trailing stop block in binary bot.
How can make it?

because this moment make disappointed me
Tick cheating in profit one

![Screenshot_3](https://user-images.githubusercontent.com/76085185/122894288-13156f80-d36d-11eb-83e5-87ad0b3d09a8.png)

**Comment by trident2005** [comment]
The trailing stop figure does not exist on binary options, you need try with reset put/reset call contracts.

**Comment by vnxz** [comment]
> 
> 
> The trailing stop figure does not exist on binary options, you need try with reset put/reset call contracts.

thanks ,I forget about this .I will test .

**Comment by binary-ex-machina** [comment]
Even with trailing stop on that cases, you would lose. When one tick change the result of a trade, your entry was not good
