### ISSUE TITLE
Tick to open trade immediatly next candle appear

### ISSUE THREAD

**Issue by precious2818** [binary-com/binary-bot#3335]
Please how can I make a 5 tick prediction to start on the next candle eg the signal to trade appeared at 8:12:24(hrs/mins/seconds) how can I make it purchase trade on 8:13:00 if the next candle appear Instead of it appearing immediately  the signal appears

**Comment by binary-ex-machina** [comment]
you can do like in the image below. When the signal appears, it will wait x seconds until the next candle to start the trate

Where you see Direction is Rise, you switch for your strategy filter for the Call option. For the Put option, switch the Direction is Fall

![image](https://user-images.githubusercontent.com/34610787/123183985-19891180-d469-11eb-802d-5f2ac0171a1f.png)

**Comment by precious2818** [comment]
> you can do like in the image below. When the signal appears, it will wait x seconds until the next candle to start the trate
> 
> Where you see Direction is Rise, you switch for your strategy filter for the Call option. For the Put option, switch the Direction is Fall
> 
> ![image](https://user-images.githubusercontent.com/34610787/123183985-19891180-d469-11eb-802d-5f2ac0171a1f.png)

Please where would I put in my strategy

**Comment by binary-ex-machina** [comment]
@precious2818 i have explained in my post what you should do it, read it again
