### ISSUE TITLE
Last Digits Stats

### ISSUE THREAD

**Issue by anushkak2000** [binary-com/binary-bot#3338]
Hi Everybody,

Can anyone create a bot according to the following conditions. If so please post a bot here.

Market : Volatility 50 Index
Trade Type : Over/Under
Contract Type : Over
Duration : 1Tick
Stake : 1USD
Prediction : 1

**Trade open condition**
If last digit value shows "1"
And
If Last Digit Stat Value of "0" <= 8%
And
If Last Digit Stat Value of "1" <= 8%

**Comment by binary-ex-machina** [comment]
You didn't specify the number of digits used to calculate the percentages of each digit, so I put 100

![image](https://user-images.githubusercontent.com/34610787/123677254-43e91f00-d81b-11eb-8a06-739eefea6cbf.png)

**Comment by anushkak2000** [comment]
can you send me xml file
