### ISSUE TITLE
Required Binary Bot Even ODD

### ISSUE THREAD

**Issue by lokesh6481** [binary-com/binary-bot#3339]
I required a Bot for Binary Option using

02468 EVEN can run Twice
13579 ODD can run Twice

I mean First and Second Trade EVEN, EVEN
Third and Fourth Trade ODD, ODD
Then after EVEN, EVEN
Then ODD, ODD
EVEN
EVEN
ODD
ODD
EVEN
EVEN
ODD
ODD

With Martingal

Please HELP

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/123675762-785bdb80-d819-11eb-8ac7-a2474eab6f65.png)
