### ISSUE TITLE
Bot get stuck after update

### ISSUE THREAD

**Issue by delonbh** [binary-com/binary-bot#334]
Dears, cant run my bot test after update.

Could you tellme whats its wrong?

https://image.prntscr.com/image/U0utfPUGQV2jZ3wOn6yPng.png

**Comment by aminmarashi** [comment]
In order to get the `min` and `max` of RSI, you can use:
<img width="724" alt="screen shot 2017-07-21 at 9 20 05 am" src="https://user-images.githubusercontent.com/6560964/28445249-d7f297f6-6df5-11e7-8355-b1cfbf77eb8a.png">
Sorting the whole `RSI` list is too heavy.

**Comment by delonbh** [comment]
Thank you.
I'll try  it

Em 20 de jul de 2017 22:21, "Amin Marashi" <notifications@github.com>
escreveu:
