### ISSUE TITLE
Longest losing streak in a row?

### ISSUE THREAD

**Issue by miguelj082** [binary-com/binary-bot#3348]
Greetings to the entire community and I would like to ask this:

I have made backups where I have reached 10 losses in a row but I would like to hear from you: in rise / fall, even/odd contracts, what is the biggest streak of consecutive losses you have had?

**Comment by binary-ex-machina** [comment]
These are my highest losing streak so far

Rise/Fall - 26 losses in a row (1min, EURUSD)
Rise/Fall - 22 losses in a row( ticks, Index 100)
Rise/Fall - 18 losses in a row (1min, Index 75)

Even odd - 34 losses in a row (1 tick duration, Index 100)

**Comment by miguelj082** [comment]
Thanks!
