### ISSUE TITLE
Preciso de ajuda para montar um bloco 

### ISSUE THREAD

**Issue by fcroch** [binary-com/binary-bot#3349]
I want to build a block to take between 20 samples, which digit is the highest frequency and which digit is the lowest frequency.

**Comment by binary-ex-machina** [comment]
you can try like this image below. It will make a list of all digits, taking the highest value and the lowest value to point the highest/lowest frequency of the digits

![image](https://user-images.githubusercontent.com/34610787/124413325-c5aee000-dd26-11eb-8e10-7755f6b41cd4.png)

**Comment by fcroch** [comment]
> você pode tentar como esta imagem abaixo. Ele fará uma lista de todos os dígitos, tomando o valor mais alto e o valor mais baixo para apontar a frequência mais alta / mais baixa dos dígitos
> 
> ![imagem](https://user-images.githubusercontent.com/34610787/124413325-c5aee000-dd26-11eb-8e10-7755f6b41cd4.png)

Thanks my friend.
