### ISSUE TITLE
Higher/Lower

### ISSUE THREAD

**Issue by anushkak2000** [binary-com/binary-bot#3354]
Please anybody can create a bot for following condition.

Pair : Volatility 100 index
Duration : 6 ticks
Barrier Offset : +2.17
Stake : 1$

**_Condition:_**

Bot trade "Lower" if last digit values after decimal point are "01,02,03,04,05,06,07,08,09"

example: 4701.01   4708.02  4783.03 etc...

**Comment by binary-ex-machina** [comment]
you can do like this below
![image](https://user-images.githubusercontent.com/34610787/124826883-bceb2380-df4b-11eb-983c-c2b1258b070b.png)

**Comment by mIKLAUS4** [comment]
> вы можете сделать это следующим образом
> ![изображение](https://user-images.githubusercontent.com/34610787/124826883-bceb2380-df4b-11eb-983c-c2b1258b070b.png)

Hello. I tried your code and it seems to me that it is not correct. I mean that the resulting bot does not trade according to the idea of the author who asked to make the robot. It does not open a trade when 01.02.03 after the decimal point are equal and so on.
![Screenshot_10](https://user-images.githubusercontent.com/87127557/124912655-e44afa80-dff6-11eb-90f4-09ac21be7f6b.png)
![Screenshot_11](https://user-images.githubusercontent.com/87127557/124912657-e6ad5480-dff6-11eb-8754-52c668342186.png)

**Comment by binary-ex-machina** [comment]
@mIKLAUS4 yes, it does what you asked. However, if you are looking on the entry spot for that numbers, you must understand that there is a delay of 1 tick after the bot purchase the contract, so you will never see 01,02,03 that the bot is filtering. Try to put a notification on block 2, and you will see that it is working as you asked.

**Comment by mIKLAUS4** [comment]
@binary-ex-machina Exactly, I completely forgot about the 1 tick delay. Thanks for the clarification!
