### ISSUE TITLE
Deriv Bot Integration (dbot)

### ISSUE THREAD

**Issue by binarybotbrazil** [binary-com/binary-bot#3355]
I need to integrate the Deriv Bot system with another platform, does anyone know any repository in Deploy state where I can simply get the compiled code and replicate it on another system?
I refer to this screen: https://app.deriv.com/bot?lang=EN

I know you already have repositories with this application, but I don't know about the frameworks used for development.

Can you help me? @binary-ex-machina @anton-binary

**Comment by binary-ex-machina** [comment]
check here https://github.com/binary-com/deriv-app

**Comment by vipclubsi** [comment]
Hello Friend!

I've already tried using this repository, but I can't deploy :(
I tried several times, but it gives an error when compiling on the server.
Do you have this repository already deployed?

@binary-ex-machina

**Comment by binary-ex-machina** [comment]
What errors do you get when you try to run a server? Did you followed the instructions and checked the FAq from the repository?

**Comment by vipclubsi** [comment]
Most errors are due to my lack of knowledge in the language used. I really don't know what to do, as I've tried everything, so I needed an environment already deployed.
If you don't have the environment already deployed, do you think you can help me with the process?

@binary-ex-machina

**Comment by binary-ex-machina** [comment]
I can't assist you in the deployment. Try to run it on your local server and load the bot package. Check the logs on your server and front end to see what errors you get on the console. It's the best way to check if you are running the right server framework version and installed everything right. You having a good knowledge of the language is essential to solve the possible issues you find in the installation, so I advise you to study the language so you can find at least what errors it is showing
