### ISSUE TITLE
Working binary strategy

### ISSUE THREAD

**Issue by codebluded** [binary-com/binary-bot#3357]
So i have this strategy which i think could net a little profit and i need help making it.
Please add to it or improve it and post here for testing.

[binary even.odd.strategy.txt](https://github.com/binary-com/binary-bot/files/6791256/binary.even.odd.strategy.txt)
.

 Thanks!

**Comment by binary-ex-machina** [comment]
you can try like this

![image](https://user-images.githubusercontent.com/34610787/125211177-f9d05680-e27a-11eb-8e02-e3ed0e5e9cb0.png)

**Comment by codebluded** [comment]
That is amazing. Can you send it to me for testing???

deniskrotich@gmail.com

**Comment by vnxz** [comment]
> 
> 
> you can try like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/125211177-f9d05680-e27a-11eb-8e02-e3ed0e5e9cb0.png)

what mean -3 counter 
this value not come when run
should be if counter = 3 else iseven true
