### ISSUE TITLE
how to read next candle details

### ISSUE THREAD

**Issue by freedonone** [binary-com/binary-bot#3360]
please I need a bot that will read the close of future candles,

like if I start it now.... it will read the close value of the current candle, also the that of the future ones 

thanks

**Comment by binary-ex-machina** [comment]
To get the close value of the actual candle, you need to analyze the last tick of the candle. In case you use 1 min time candle duration, you can do like the image below. Multiply the 60 for any time frame above 1 (ex: 5min will be 300)

This way, you will get the latest close value. To get the actual close value (not closed candle), use the last tick block

![image](https://user-images.githubusercontent.com/34610787/125480561-aba42370-726f-4a94-980e-a1683aa4cb42.png)

**Comment by freedonone** [comment]
https://www.youtube.com/watch?v=ohtnf4H_HMA


i am trying setup a bot this exact way..... excluding the ATR  aspect
help me look into it. thanks

**Comment by freedonone** [comment]
> To get the close value of the actual candle, you need to analyze the last tick of the candle. In case you use 1 min time candle duration, you can do like the image below. Multiply the 60 for any time frame above 1 (ex: 5min will be 300)
> 
> This way, you will get the latest close value. To get the actual close value (not closed candle), use the last tick block
> 
> ![image](https://user-images.githubusercontent.com/34610787/125480561-aba42370-726f-4a94-980e-a1683aa4cb42.png)

ohk, I will check it out.... help me look into this https://www.youtube.com/watch?v=ohtnf4H_HMA

**Comment by freedonone** [comment]
tried the above..... I am getting open values instead of close values

**Comment by binary-ex-machina** [comment]
@freedonone, to make what you want to form the video, you must change how the logic is done on the blocks. It must work like a timeline, changing variables over the ticks and storing them to compare later to trigger all the filters. To analyze in the correct time (at the end of the candle, where there are no more ticks on that candle, so it's closed), you must check the data on the last tick of the candle. To do that, you must check in what second you are and when you are at the 58 seconds (last tick in 2 seconds per tick markets). 

I have put a notify block to see what second is printing when the analysis is done. However, if you don't get numbers above 57, there is something wrong with your computer time, so this idea will not be done on your computer.

The logic in the image below follows the strategy from the link you sent (https://www.youtube.com/watch?v=ohtnf4H_HMA) without the 3 candles above the EMA 200 rules. I didn't test in full, but it should help you build the idea and improve.

![image](https://user-images.githubusercontent.com/34610787/125537961-a8e05f12-7145-4ce4-9cb2-cf786f5f6c45.png)

**Comment by freedonone** [comment]
thanks buddy lemme check it out

**Comment by freedonone** [comment]
![image](https://user-images.githubusercontent.com/54136867/125543653-4a42e9c3-b10a-454d-95e9-befa1173bb47.png)

the blocks with purple seems to be the same..

the one with pink could you verify it...

**Comment by binary-ex-machina** [comment]
The logic is correct. Please try to read the logic and how it works. It's like a timeline. Every ELSE IF block will occur on a different candle, not at a single candle. Following the video you sent, it must WAIT for crosses, so the ELSE IF blocks do that on every candle.

**Comment by freedonone** [comment]
check the purple marks, the cross under block came out twice and there is no block for 200

**Comment by freedonone** [comment]
> The logic is correct. Please try to read the logic and how it works. It's like a timeline. Every ELSE IF block will occur on a different candle, not at a single candle. Following the video you sent, it must WAIT for crosses, so the ELSE IF blocks do that on every candle.

i am not disputing your work, you are always on point

**Comment by binary-ex-machina** [comment]
>  there is no block for 200

check again the image
![image](https://user-images.githubusercontent.com/34610787/125546185-2599af62-40d7-45ba-8e5a-3f7c78055b22.png)

> I am not disputing your work. You are always on point

Check every block on the image, including the cross custom functions, the block order, and check my other messages here on this post. I may be wrong on some parts of the strategy from the video, but the logic is right. I hope this helps you with your idea

best,

**Comment by freedonone** [comment]
![image](https://user-images.githubusercontent.com/54136867/125546545-4fbe82db-5b5a-4b52-8898-d993046f85d2.png)



i mean this
