### ISSUE TITLE
Boy not bying on specified digit

### ISSUE THREAD

**Issue by Darkside380** [binary-com/binary-bot#3361]
In purchase conditions i placed " buy if last digit in not 6" but somtimes the bot enters a trade with the last digit = 6
I tried it vise versa, buy if last digit is 6 and non of the entery points start with 6. Please help.

**Comment by binary-ex-machina** [comment]
The bot buys the contract at the right time based on your filter "if the last digit is not 6", but it doesn't mean it starts the contract at the same tick you analyzed. Normally, it takes 1 tick to enter the trade. It will be rare to analyze and enter the same tick.
