### ISSUE TITLE
i want to build a deriv.com jump strategy 

### ISSUE THREAD

**Issue by Stnepel6672** [binary-com/binary-bot#3364]
please i am looking for a way to build a bot  on this strategy. 1 minute candle, trades on 10ticks.  Rise/fall.
The strategy works with 3pips jump. If its possible, let the bot bet on 10% of the account per time. Once there's a jump (eg. 5012 to 5015) you trade higher or lower based on the direction of the jump. Please can anyone help me to build this? If this isn't  clear I can explain further. Thank you.

**Comment by Stnepel6672** [comment]
please i am looking for a way to build a bot on this strategy. 1 minute candle, trades on 10ticks. Rise/fall.
The strategy works with 3pips jump. If its possible, let the bot bet on 10% of the account per time. Once there's a jump (eg. 5012 to 5015) you trade higher or lower based on the direction of the jump. Please can anyone help me to build this? If this isn't clear I can explain further. Thank you.

**Comment by binary-ex-machina** [comment]
Try this idea below. It will open a trade when the amount of movement up is 3 or more (on index 100). You wrote 3 pips, but on the Index 100, 3 pips are 0.03. To be a $3 movement, you must use 300 pips. Based on your analysis, I let the pips as divided by 100 ( in this case you can put 3, and it will work like 300). For other indexes, you must check what is the average pip movement for them and change the variable **_minimumAmountOfPips_**

![image](https://user-images.githubusercontent.com/34610787/126183487-7fe69a37-7792-426c-882c-152a790ba10c.png)

**Comment by Stnepel6672** [comment]
Awesome.  Thanks will try this out now

**Comment by Stnepel6672** [comment]
Please  do you have this in XML?

**Comment by Stnepel6672** [comment]
![20210719_200034](https://user-images.githubusercontent.com/87564251/126213215-7e4d53e3-df86-46de-9210-24c3e4ec7502.jpg)

**Comment by binary-ex-machina** [comment]
@Stnepel6672 why are you using balance 1? send a full image of your page

**Comment by Stnepel6672** [comment]
![Screenshot_20210719-202446_Chrome](https://user-images.githubusercontent.com/87564251/126215803-282314e1-3a55-4964-a42b-55456b5a855a.jpg)

**Comment by Stnepel6672** [comment]
I'll  readjust  that. Is their a way I can get an xml file? I think i may have missed a thing or 2

**Comment by Stnepel6672** [comment]
thanks so so much

**Comment by binary-ex-machina** [comment]
the tick list is not a variable, but a Tick Analysis block

![image](https://user-images.githubusercontent.com/34610787/126216615-a88e3b0d-ca3e-4444-9b73-3a6a9dc0a721.png)

**Comment by Stnepel6672** [comment]
Ok. Will input that now.

**Comment by Stnepel6672** [comment]
![20210719_212946](https://user-images.githubusercontent.com/87564251/126223716-8a030548-72a3-4a9b-a0e5-c76310256afd.png)

Please how can I get the "else if" I think not getting that is making the trades go only in one direction. Thanks so much for your help. Trades are executing now

**Comment by Stnepel6672** [comment]
![Screenshot_20210719-220813_Chrome](https://user-images.githubusercontent.com/87564251/126227830-ef5ec0e7-efbe-4e25-b940-21861918fc23.jpg)
 
This is what it looks like. I think if what I got wrong that is keeping the trades one sided is the "else if". This is my first time on the bot building and you have helped me immensely

**Comment by Stnepel6672** [comment]
I've made the adjustment but it only takes trades in one direction. Is their any suggestion  that can help me adjust that?

**Comment by binary-ex-machina** [comment]
@Stnepel6672 click on the icon on the IF block and use Else if

![image](https://user-images.githubusercontent.com/34610787/126245466-620b0467-6f9d-46ea-a143-1a0dc31d3f2e.png)

**Comment by Stnepel6672** [comment]
Thanks so much. Have been able to make the adjustment,  however trades are still taken in one direction alone.
