### ISSUE TITLE
Platform Hacked

### ISSUE THREAD

**Issue by binarybotbrazil** [binary-com/binary-bot#3366]
How can I find out who owns an app_id?
My platform was hacked, and the owner of this app_id has entered his ID into the system and replaced my old one.
I would like to know the owner of the Application ID so that I can take legal action.
It's possible?
The App_ID is this: 28052
Can someone help me?

@binary-ex-machina

**Comment by binary-ex-machina** [comment]
@binarybotbrazil contact Deriv/Binary and explain the problem. They will assist you

support@deriv.com 
support@binary.com

**Comment by saidforex26** [comment]
@binary-ex-machina how to deal with this message. What to do (Sorry, an error occurred while processing your request.)
