### ISSUE TITLE
I want to build a strategy based on Jumps on volatility 100(i)s

### ISSUE THREAD

**Issue by Stnepel6672** [binary-com/binary-bot#3367]
please i am looking for a way to build a bot on this strategy. 1 minute candle, trades on 10ticks. Rise/fall.
The strategy works with 3pips jump. If its possible, let the bot bet on 10% of the account per time. Once there's a jump (eg. 5012 to 5015) you trade higher or lower based on the direction of the jump. Please can anyone help me to build this? If this isn't clear I can explain further. Thank you.

**Comment by binary-ex-machina** [comment]
duplicated #3364
