### ISSUE TITLE
Low/Upper Shadow and Body Percetage

### ISSUE THREAD

**Issue by mnaseem01** [binary-com/binary-bot#337]
Hi,
Can you please help on the Low Shadow and Upper Shadow value. I try this it is not working.
![image](https://user-images.githubusercontent.com/13481811/28498818-f70617bc-6fb7-11e7-9e7f-53763a35fe35.png)

**Comment by aminmarashi** [comment]
You should use a candle block without `Open`, `High`, ... values
Try this:
<img width="479" alt="screen shot 2017-07-24 at 9 16 17 am" src="https://user-images.githubusercontent.com/6560964/28504912-d3c3532a-7050-11e7-8764-1b3d644dcaeb.png">
