### ISSUE TITLE
Digit match bot with two alternating digits

### ISSUE THREAD

**Issue by Truwalter** [binary-com/binary-bot#3371]
Please can anyone help me and develope a digits match bot with two alternating digits and martingale factor, number of loses before martingale and number of consecutive loses before bot stops, stop loss and take profit.

**Comment by binary-ex-machina** [comment]
You can do it like this. It's working as you asked

![image](https://user-images.githubusercontent.com/34610787/129935345-5259df0f-beed-4fda-b096-93feb057ce41.png)

![image](https://user-images.githubusercontent.com/34610787/129935406-4da8f99b-b357-4d24-9c39-f477399163b8.png)

**Comment by Truwalter** [comment]
Please can you upload the bot?
Or email it to trustwalter5@gmail.com, please.
