### ISSUE TITLE
Need help with modifying this excellent binary bot

### ISSUE THREAD

**Issue by eniolax** [binary-com/binary-bot#3372]
Hello, Please I came across this wonderful bot. (see attached). The bot has a Martingale till 20 levels. The only problem with the bot is that initials stake MUST be $0.35 dollars. Now that is good (for anyone will huge amount to start) but after about a dozens misses (losses) that small amount can grow to be over $2000.

I have back-tested it severally. Its very good even with lots of misses, it still makes profit. The only problem is the initial (start) stake.  I want anyone to assist to modify the boot to accept any lower initial stake (like $0.01 or $0.001)
You can view the code via the link below.

https://drive.google.com/file/d/1jcNwJJ5CKhRST7pcSAgXVei31h7R1Ht2/view?usp=sharing

Error message: ![Error Message for binary bot](https://user-images.githubusercontent.com/41271650/126873060-691779c1-2a19-4d8a-a0b1-0a76516fb8fb.jpg)

Thanks.

**Comment by vnxz** [comment]
oh no.minimal stake start from 0.35
you cannot change to 0.01

**Comment by eniolax** [comment]
O.k thanks for the info. 

Do you have any bot with high accuracy?

**Comment by vnxz** [comment]
there is no bot with high accuracy.Binary is gambling
