### ISSUE TITLE
Rise /Fall Bot

### ISSUE THREAD

**Issue by anushkak2000** [binary-com/binary-bot#3376]
Can anyone create a bot with following condition. Pls check attached image. All values are last digit values. Please note that
colors of last digit values must be consider.
![Scan](https://user-images.githubusercontent.com/86454824/127874571-6b584ab6-2c5b-4fff-9c60-584d5e18c3a4.jpg)

**Comment by vnxz** [comment]
proven strategy?

**Comment by anushkak2000** [comment]
> proven strategy?

think so....

**Comment by LongNguyen1691** [comment]
> chiến lược đã được chứng minh?

kết quả của nó có hiệu quả không  ? Có thể cho tôi xin bot được không ? Cảm ơn !

**Comment by binary-ex-machina** [comment]
@anushkak2000, you can do like this. This is strategy, and analysis is garbage. It will lose the same way you play any rise/fall strategy. Don't waste time on this

![image](https://user-images.githubusercontent.com/34610787/129946910-1a9cbe97-4294-4578-9be9-358fd4701ddf.png)
