### ISSUE TITLE
Cần giúp thêm mất ảo 2 lần rồi vào tài khoản thực

### ISSUE THREAD

**Issue by LongNguyen1691** [binary-com/binary-bot#3379]
Cần giúp thêm mất ảo 2 lần rồi vào tài khoản thực ! Cảm ơn
[1.zip](https://github.com/binary-com/binary-bot/files/6948476/1.zip)

**Comment by Orrddy** [comment]
> Cần giúp thêm mất ảo 2 lần rồi vào tài khoản thực ! Cảm ơn

Ok nhưng bạn đã thử bot này bao lâu rồi ...

và mất mát tối đa là bao nhiêu
