### ISSUE TITLE
Open a trade when the new candle crosses the old candle

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#338]
HI All,

![image](https://user-images.githubusercontent.com/20506657/28503621-57ba4476-7002-11e7-925b-455c67c12746.png)

I need to read the previous candle high and low. And when the new candle croses that high or low of the previous candle it trades rise or fall. Its based on  1 minute candle.

How can I do that, please help...

**Comment by sarderiftekhar** [comment]
How can I read previous candles high and low? I want to compare the current price is higher than the previous candles high or opposite if the current price is lower than the last candles low?

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/28550357-602d7ec6-710a-11e7-8e46-8c918c099fa6.PNG)

**Comment by sarderiftekhar** [comment]
Already found and done thanks anyway Fruitfella.....

**Comment by Fruitfella** [comment]
@sarderiftekhar ??

**Comment by sarderiftekhar** [comment]
Hi Fruitfella, thanks again. Need a favor on coding. I setup for trade when it crosses higher or lowers of the previous candle. But how do keep it for only one trade per candle?

Suppose, the new candle crossed the high of the old candle, then the rising trade will trigger. But will not do anymore trade until new candle.

So each time only one trade, until new candle.


Thanks in advance.

**Comment by Fruitfella** [comment]
u can try this...
![capture](https://user-images.githubusercontent.com/26277327/28595581-a26d01da-71be-11e7-9607-e5a4cb166e61.PNG)

u can change the num in yellow circle if u want to trade more than once per candle.

**Comment by KickandRun** [comment]
Hi @Fruitfella 
Can you help me?
How can i set my bot, i wan to open purchase rise or fall if the spot increasing 30point in  interval tick every 2 minutes, 
thanks in advance

**Comment by Fruitfella** [comment]
sorry, i dont get what you mean, can you elaborate more?

**Comment by KickandRun** [comment]
I try following bot but don't work.
I try buy rise once candle increasing 30point from lower in interval 2 minutes, thank you
![gambar](https://user-images.githubusercontent.com/31030811/29344405-c9642062-8261-11e7-82ee-c51a362f6058.png)

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/29344628-68469c40-8263-11e7-9e0a-f72f6578c183.png)

**Comment by KickandRun** [comment]
thank you, i will try
Have a nice day!

**Comment by KickandRun** [comment]
I try but dosn't work

**Comment by Fruitfella** [comment]
give me a screenshot, i got a feeling that you didnt really understand how binary bot works

**Comment by KickandRun** [comment]
thank you for your feedback
![gambar](https://user-images.githubusercontent.com/31030811/29356629-05735112-829f-11e7-814e-5bf43c79c586.png)

**Comment by Fruitfella** [comment]
its disabled.
![untitled](https://user-images.githubusercontent.com/26277327/29357107-99eaef5c-82a0-11e7-986b-26b37437835c.png)
right click on it the click **`Enable block`**

**Comment by KickandRun** [comment]
i get it, why it's work? what is the function of Enable block?
Thank you for your support

**Comment by Fruitfella** [comment]
the function of Enable block? to enable a disabled block, i guess :rofl: 
some blocks will auto-disabled if you put it outside of a mainblock.

**Comment by KickandRun** [comment]
ohhh, i see, enable it make bot will runn,,,
thanks 

Good luck

**Comment by KickandRun** [comment]
Hi Fruitfella,

Ho can i made bot if i wan buy rise if the candle closed higher than open?
thanks in advance

**Comment by hmebert1980** [comment]
Fruitfella going crazy with these types of questions...
