### ISSUE TITLE
Binary bot that will change prediction on 3 same last digit

### ISSUE THREAD

**Issue by jahidbappy** [binary-com/binary-bot#3380]
Plz, can anyone make a bot that will change the prediction if the last digit is the same in 3 tricks and purchase differ for example if the last 3 ticks are like this XXXX.73- XXXX.53 -XXXX.93 it's going to change prediction to 3 and purchase differ. it will do this to any digit if the last digit is the same in 3 ticks. it could be 0 to 9 any digit.
I already made a bot that can purchase differ if the last 3 digit is same but I can't make to change the prediction if you understand what I am saying plz help me

[binary-bot.zip](https://github.com/binary-com/binary-bot/files/6949555/binary-bot.zip)

**Comment by binary-ex-machina** [comment]
you can try like this

![image](https://user-images.githubusercontent.com/34610787/129953010-0c272c67-9565-4e57-a4e7-95a66fd2b52f.png)

**Comment by jahidbappy** [comment]
> you can try like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/129953010-0c272c67-9565-4e57-a4e7-95a66fd2b52f.png)

I did but sometimes it reads the same digit 2 times and loses is there another way???

**Comment by binary-ex-machina** [comment]
@jahidbappy is not possible because between block 1 and block 2 will have a delay, and in that time, it won't follow the rule you want. The best is to work with a fixed prediction and put the logic on the second block. It will not prevent the delay 100%, but it will reduce a lot

**Comment by jahidbappy** [comment]
> @jahidbappy is not possible because between block 1 and block 2 will have a delay, and in that time, it won't follow the rule you want. The best is to work with a fixed prediction and put the logic on the second block. It will not prevent the delay 100%, but it will reduce a lot

ok, then how do I put the logic?? I want it to be as safe as possible
