### ISSUE TITLE
who can help me find this code

### ISSUE THREAD

**Issue by cunk888** [binary-com/binary-bot#3382]
this is a free stake if the loss bot will automatically follow according to the list. 

the problem is how to change the compound level as well as a free stake list.
if lose, the compound level list and also the free stake list will move to the next according to the list that has been made
I've tried to try but it doesn't work. The following is the file, please give instructions if you know 😊
[Please edit.txt](https://github.com/binary-com/binary-bot/files/6956987/Please.edit.txt)

**Comment by cunk888** [comment]
![Screenshot_20210810-034240~2](https://user-images.githubusercontent.com/59736310/128764763-e0863449-12d5-468e-94b1-1e9ba95b4ffa.jpg)

**Comment by anton-binary** [comment]
Hey, I ran your you XML and it seems working as designed. Can you clarify how you expect it to works? I.e. how do you expect stake to changed?

**Comment by cunk888** [comment]
Freestake ✔️ running well
But the list compound leve not working.
Ex:.
0.35 compound_level 1 loss
And then 0.55 compound level go to 2 buf if win the compound will reset to first again.
If 0.55 loss compoun lvl go to next list to 1 and when purchasing 1$

**Comment by anton-binary** [comment]
How do you expect compound to work? I see you only set the value to Compound, but never actually use this variable anywhere.
![image](https://user-images.githubusercontent.com/43776314/129169613-1adfc73f-194d-49c6-aee8-b3d71571eba0.png)

**Comment by anton-binary** [comment]
You assign compound to variable C, but never use it too.
![image](https://user-images.githubusercontent.com/43776314/129171573-82d7bfa5-7806-4aa9-84e1-74981574ef73.png)

**Comment by vnxz** [comment]
> 
> 
> Freestake ✔️ running well
> But the list compound leve not working.
> Ex:.
> 0.35 compound_level 1 loss
> And then 0.55 compound level go to 2 buf if win the compound will reset to first again.
> If 0.55 loss compoun lvl go to next list to 1 and when purchasing 1$

you want is if loss cycle win ,stake reset to 0.35.
right?

**Comment by svet1996** [comment]
@cunk888  can you help me, i have a almost ready bot but i want when he made loss trade , next trade to be with the same amount and after second loss trade to make x2 every single trade till i made win trade 

1trade - stake 0.35 - loss 
2trade - stake 0.35 - loss
3.trade stake 0.7 - loss
4trade - stake 1.4 - won
5trade - stake 0.35 - won
![123](https://user-images.githubusercontent.com/55443781/129856131-d7220b06-e61b-4df9-b8c3-50cc783e06a2.png)

**Comment by binary-ex-machina** [comment]
@cunk888 you can do like this, using modulus with the length of the list and comparing with a counter

![image](https://user-images.githubusercontent.com/34610787/129954406-67736cbe-6152-4c9b-8b58-d1e78c773d9f.png)
