### ISSUE TITLE
Can someone help me make a binary bot

### ISSUE THREAD

**Issue by ranmarucode** [binary-com/binary-bot#3383]
I have my own strategy for trading in binary.com Its pretty simple I would say. But its tiring if I trade it manually every day. So can anyone help me making the bot so its run automatically?

I'm trading on Volality Index 10 purchasing both digit over and under.

In the bot how do you generate random number between 1-9 for the Prediction.
If the Prediction is 9 and also the last digit from the last tick is greater/equal to 7 its purchase under
If the Prediction is 1 and also the last digit from the last tick is lower/equal to 3 its purchase over

I've made it that way, but for some reason it always pick the last digit as its prediction not a random number.
![bot](https://user-images.githubusercontent.com/77820163/128856727-f4141f06-5a02-4d5b-b8fc-e9671eeee025.PNG)

**Comment by binary-ex-machina** [comment]
set the prediction on the defined trade options part

![image](https://user-images.githubusercontent.com/34610787/129954602-ad01cfa0-9587-4f79-8b45-33b96d49fbc2.png)

**Comment by kavydon** [comment]
hey is this a profitable binary bot?

**Comment by binary-ex-machina** [comment]
@kavydon  In long term, no
