### ISSUE TITLE
Binary.com / Digit Match Bot 

### ISSUE THREAD

**Issue by BinaryGT** [binary-com/binary-bot#3385]
Hello I have a couple of digit match strategy's for Binary.com and I need help creating a bot for them I've tried them all manually and they work can someone help me.

**Comment by binary-ex-machina** [comment]
Post the strategy in full details here and you might get some help

**Comment by BinaryGT** [comment]
[DIGITS MATCHES Trsdingsignalbinary.com.pdf](https://github.com/binary-com/binary-bot/files/7013855/DIGITS.MATCHES.Trsdingsignalbinary.com.pdf)

The strategy is listed in full in the link above

**Comment by binary-ex-machina** [comment]
I readed the pdf, a lot of non sense and myth about digits trading, dont waste you time with these absurd patterns that appear on internet. It's just garbage. Any of those methods will have the same win rate as playing with any other strategy, so it's not worth spending time building that

**Comment by BinaryGT** [comment]
Okay thank you a lot, I really appreciate your advice

**Comment by khan1313** [comment]
> Post the strategy in full details here and you might get some help

Hello sir.
    Sir can you explain how i learn digits pattern to trade in digit over and digit under.?
And guide me how to use stats?

Thanks and Regards

**Comment by binary-ex-machina** [comment]
@khan1313, there is no digits pattern. The digits are randomly generated, and every number has the same chance of appearing. So in case you want to bet on sequences of numbers, like waiting for the number zero to appear five times, then trade, the odds are almost the same since you can't enter right after the digit came, all the time.

**Comment by khan1313** [comment]
> @khan1313, there is no digits pattern. The digits are randomly generated, and every number has the same chance of appearing. So in case you want to bet on sequences of numbers, like waiting for the number zero to appear five times, then trade, the odds are almost the same since you can't enter right after the digit came, all the time.

What do you suggest for me to trade in digit over and under. ??

**Comment by khan1313** [comment]
> @khan1313 have good capital to recover from losses, use the proper martingale, aim for small profit per day, let's say 1% of your money. Have money to recover from 8-10 losses in a row and have luck

Ok thanks sir.
And guide me about Vitual and what is web www.binarytools.io  .... it is right way to use this binary bot in this website??

**Comment by binary-ex-machina** [comment]
@khan1313 they are just a copy of the original bot by binary.com with some extra blocks built with the blocks. Their virtual trading is just sticking with a minor stake until the conditions are met, then entering the original stake. Not virtual trading as it needs to be. I don't know about their support, but to unlock the full version, you need to pay, so for me is not worth it

**Comment by khan1313** [comment]
> @khan1313 they are just a copy of the original bot by binary.com with some extra blocks built with the blocks. Their virtual trading is just sticking with a minor stake until the conditions are met, then entering the original stake. Not virtual trading as it needs to be. I don't know about their support, but to unlock the full version, you need to pay, so for me is not worth it

Its means its good to use. There is no problem to use ! ?

**Comment by binary-ex-machina** [comment]
Do you mean a problem as they can steal your account? I don't think they can do it, but since you authorize the app to use your account to trade, who knows if the website will trade without you knowing? it's always a risk

**Comment by khan1313** [comment]
> Do you mean a problem as they can steal your account? I don't think they can do it, but since you authorize the app to use your account to trade, who knows if the website will trade without you knowing? it's always a risk

Then what do you recommend for pure trading?
Or do you have rise and fall stragety?

**Comment by besteranga** [comment]
Plz give me low pajet bot

**Comment by bond1111** [comment]
This discussion is interesting. What's the highest number of times a digit can appear in a row. 4 or 5?

**Comment by binary-ex-machina** [comment]
@bond1111 I already saw more than 7

**Comment by bond1111** [comment]
I hear python can be used to predict a random sequence. Can deriv's seed not be gotten to determine these pseudorandom numbers?

**Comment by binary-ex-machina** [comment]
it's a random sequence, it's impossible to predict with anything more than 10% chance, no matter the programming language
