### ISSUE TITLE
Fourier extrapolation

### ISSUE THREAD

**Issue by benn10-blip** [binary-com/binary-bot#3387]
Can we create a bot that has Fourier extrapolation but for ticks?

**Comment by benn10-blip** [comment]
@binary-ex-machina

**Comment by binary-ex-machina** [comment]
@benn10-blip, the calculation for the Fourier Extrapolation is very complex. I will try to replicate on code and then try with the blocks. since it requires only one data source, the indicator accepts ticks

**Comment by benn10-blip** [comment]
awesome,im looking forward

**Comment by benn10-blip** [comment]
Ill donate to you end of the month

**Comment by benn10-blip** [comment]
How long will it take you to write it? @binary-ex-machina

**Comment by svet1996** [comment]
@binary-ex-machina  can you help me, i have a almost ready bot but i want when he made loss trade , next trade to be with the same amount and after second loss trade to make x2 every single trade till i made win trade 

1trade - stake 0.35 - loss 
2trade - stake 0.35 - loss
3.trade stake 0.7 - loss
4trade - stake 1.4 - won
5trade - stake 0.35 - won
![123](https://user-images.githubusercontent.com/55443781/129856131-d7220b06-e61b-4df9-b8c3-50cc783e06a2.png)

**Comment by vnxz** [comment]
> 
> 
> @binary-ex-machina can you help me, i have a almost ready bot but i want when he made loss trade , next trade to be with the same amount and after second loss trade to make x2 every single trade till i made win trade
> 
> 1trade - stake 0.35 - loss
> 2trade - stake 0.35 - loss
> 3.trade stake 0.7 - loss
> 4trade - stake 1.4 - won
> 5trade - stake 0.35 - won
> ![123](https://user-images.githubusercontent.com/55443781/129856131-d7220b06-e61b-4df9-b8c3-50cc783e06a2.png)

THIS IS EASY BUT NEED TO HAVE MORE WIN COUNT IF NOT , IT CANNOT PROFIT MUCH
WILL TAKE VERY LONG TIME
I ALREADY MADE THIS MONEY MANAGEMENT
IF YOUR EVEN BOT MADE MORE WIN COUNT, IT CAN BE

**Comment by binary-ex-machina** [comment]
@benn10-blip, unfortunately, the calculations are complex to be used inside an XML bot. It will overload the page with the formula requests. Also Fourier extrapolation accuracy is close to 50%, so is not worth it with the sample data we can get from Deriv (max 1000 candles or ticks)

**Comment by svet1996** [comment]
@binary-ex-machina  can you help me for this issue ? thank you

**Comment by vnxz** [comment]
> 
> 
> @binary-ex-machina can you help me for this issue ? thank you

send me your xml , i will add Money management
errtoo5@gmail.com
