### ISSUE TITLE
how get bollinger band value with exponential MA period 20

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3388]
How can set  bollinger value as show in photo
![Screenshot_3](https://user-images.githubusercontent.com/76085185/129468876-aad713c8-82f5-49e2-8e28-0ef8752ef788.png)

**Comment by binary-ex-machina** [comment]
You can create a new Bollinger Bands indicator with the blocks. In the image below, you get upper and lower bands with the settings you sent and using the EMA for the calculations
![image](https://user-images.githubusercontent.com/34610787/129957365-a59d172a-0ce6-40c0-b9bc-f00322c87519.png)
