### ISSUE TITLE
How can identify current candle is candle black or not definitely

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3393]
although define
when call signal get,
 if current candle is candle black,not to open order .

But in actually , this CALL is open .

How can define accurate this signal

I think need to wait time a little after open candle time
after that if open greater than close or less than close define
How can do this

![Screenshot_1](https://user-images.githubusercontent.com/76085185/130317584-02e447b7-d3b7-4c6d-9346-ffe38bf17534.png)

**Comment by binary-ex-machina** [comment]
post the logic to buy the contract. The condition to not buy unless the candle is green is this below

![image](https://user-images.githubusercontent.com/34610787/130370886-a322f85a-f6bc-4cf5-abef-2f04c9eebcaf.png)
