### ISSUE TITLE
Add virtual loss to Digit Diff Script

### ISSUE THREAD

**Issue by ansarirj** [binary-com/binary-bot#3398]
Can someone plz help me to add a virtual loss script to an existing binary bot script? 

I need to let the bot run till it reaches 2 consecutive losses before actually entering a real trade. The digit diff script is already pretty awesome but I want to wait till it hits 2 consecutive losses and then I want to run real trades till a profit is hit. Can someone help me with this? Also, do let me know the possible cons of this strategy. the script is attached herewith. thanks in advance
[Differs_Percentage.txt](https://github.com/binary-com/binary-bot/files/7038494/Differs_Percentage.txt)

**Comment by ansarirj** [comment]
Also, can we add an additional step where we wait again for 2 consecutive losses once the profit target is hit and then start with real trade again?

**Comment by binary-ex-machina** [comment]
you can check here how to implement a fake loss 

https://github.com/binary-com/binary-bot/issues/3375#issuecomment-901303850
