### ISSUE TITLE
OVER UNDER BOT.. PLEASE make me a bot like this

### ISSUE THREAD

**Issue by MassSLtrader** [binary-com/binary-bot#3403]
Tick-1
Digit-2 OVER
Martingale 2.5

Strategy-
Last digit Should appear two times numbers below 3 continuously and the next when the last digit is below 3 Open a trade.
Ex- 2,1,4,5,6,**2**=Trade
3,3,6,0 = Trade
1,3,0,2,1,2, = No trade becuse still small numbers!
1,3,1,2,3,8,6,1=Trade

**Comment by binary-ex-machina** [comment]
you can try to understand the same logic of your other request, just changing the prediction

https://github.com/binary-com/binary-bot/issues/3400

**Comment by khan1313** [comment]
> you can try to understand the same logic of your other request, just changing the prediction
> 
> https://github.com/binary-com/binary-bot/issues/3400


Hello Sir . 
 
I need to understand digit predictions of binary digit trading? Please help

**Comment by khan1313** [comment]
> you can try to understand the same logic of your other request, just changing the prediction
> 
> https://github.com/binary-com/binary-bot/issues/3400

Hello Sir.
               Sir i need to want to learn Digit trading like digit over and digit under. And digit differ. Many times i do trading but taking losses to much. 
Please Show me the right way to where i learn these things.
Mostly peoples use LAST DIGIT PREDICTION STATISTICS but thats I don't know how i read it perfectly. Please help me


Thanks and Regards
