### ISSUE TITLE
Bot not starting

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#3406]
Hello, can anyone tell me why the attached bot sometimes starts and sometimes does not work.
The idea is that the bot starts every two minutes, in candles of 2 minutes. I changed the values 120 and 118seconds by 60 and 58seconds but it has the same failure, sometimes it does not start.  Greetings
![bot dont start](https://user-images.githubusercontent.com/52263754/131235735-319d305a-085d-4d81-a061-1c8a20ff432f.PNG)

**Comment by sundaybaezofficial** [comment]
hey bro 

binary sometimes skips a few seconds or ticks , try to put in this way 


![image](https://user-images.githubusercontent.com/85972837/131265858-626dfc74-497f-487a-9165-f140302431e4.png)

**Comment by victor1106** [comment]
I need someone who have a binary bot with good strategy

**Comment by victor1106** [comment]
I need someone who have a binary bot with good strategy

**Comment by Tommilye** [comment]
I have, email me at marioncelaz@gmail.com
