### ISSUE TITLE
create a bot based on this strategy

### ISSUE THREAD

**Issue by benn10-blip** [binary-com/binary-bot#3408]
can u guys create a bot based on this strategy?

![88863553-551b4d00-d1c0-11ea-9062-7b1a0d982679](https://user-images.githubusercontent.com/80210932/131373452-f3c1af74-fc22-41b5-b49f-9ed0046eabc5.png)

**Comment by benn10-blip** [comment]
@saidforex26

**Comment by benn10-blip** [comment]
@binary-ex-machina

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/131589255-45f4fc82-1c86-453b-8504-1a4e6efeee55.png)

**Comment by BEKKALI16** [comment]
> you can do like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/131589255-45f4fc82-1c86-453b-8504-1a4e6efeee55.png)

I NEED TO MAKE BOT BOT.GIVE YOUR CONTACT
