### ISSUE TITLE
Wrong barrier - Higher / Lower Market

### ISSUE THREAD

**Issue by miguelj082** [binary-com/binary-bot#3414]
Hi everyone.

Does anyone have a template to take higher / lower operations and the barrier is correct according to the situation? I have a template attempt but sometimes it doesn't pick the barrier I want even though I set the condition. I attach photos of the way in which I have made the bot (it is not the strategy I am looking for).

I appreciate your help.

![Captura](https://user-images.githubusercontent.com/86895417/131944863-f72b1016-a593-4ac5-b9e7-a9601b7646d2.PNG)
![Captura2](https://user-images.githubusercontent.com/86895417/131945003-2525def2-a875-4c23-b90a-29865ead27dc.PNG)

**Comment by miguelj082** [comment]
@binary-ex-machina can you help me? please

**Comment by binary-ex-machina** [comment]
you can try like this

![image](https://user-images.githubusercontent.com/34610787/132285797-6a8567d3-35dc-4391-b79a-591e52dbf77e.png)

**Comment by miguelj082** [comment]
@binary-ex-machina Thank you very much for your help, it works with the correct barrier. I have been testing how it works and I have some observations:

1. The condition is fulfilled but it does not do the operation on the same tick that is fulfilled because it needs to break the cycle.

2. Once the cycle is broken, enter 1 tick late.

Do you think this influences? Is there a way to take it at tick 1 based on my chart? I plan to make my entries at 5 ticks when I have my strategy.
![Captura2](https://user-images.githubusercontent.com/86895417/132426622-48a955e5-223a-4a59-a0d7-b5482b8e94b1.PNG)

**Comment by khan1313** [comment]
> you can try like this
> 
> ![image](https://user-images.githubusercontent.com/34610787/132285797-6a8567d3-35dc-4391-b79a-591e52dbf77e.png)
> 

Hello Sir.
               Sir i need to want to learn Digit trading like digit over and digit under. And digit differ. Many times i do trading but taking losses to much. 
Please Show me the right way to where i learn these things.
Mostly peoples use LAST DIGIT PREDICTION STATISTICS but thats I don't know how i read it perfectly. Please help me


Thanks and Regards
