### ISSUE TITLE
Gridbot

### ISSUE THREAD

**Issue by benn10-blip** [binary-com/binary-bot#3416]
@binary-ex-machina

I want to create the faumos gridbot in which is used in big companies such as binance. i want this grid but to sell when profit and sell when losing profit to cut losses.

**Comment by benn10-blip** [comment]
![image](https://user-images.githubusercontent.com/80210932/132107654-ef93f39f-86b9-4e63-8ecc-7c8c106b82a9.png)

**Comment by benn10-blip** [comment]
make the grid the grid to five to 10 levels

**Comment by benn10-blip** [comment]
![image](https://user-images.githubusercontent.com/80210932/132107769-5704e62d-b89e-4f95-a7b3-a21ade4b32b3.png)

**Comment by binary-ex-machina** [comment]
The grid strategy doesn't work for binary options. The trades have expiry dates, and most of the time, you will close the operation in loss when it reaches the opposite grid of the trade or even on the same side. Even using higher durations will lead to losses. You may try trading with this idea using Multipliers, but it will need to be manually
