### ISSUE TITLE
Passing in an env variable

### ISSUE THREAD

**Issue by okovalov** [binary-com/binary-bot#342]
@aminmarashi I really need to be able to pass at least those three things as parameters for the bot starting command. That would be really a helpful and making life easier thing, because without it I need to copy paste bot source and change only one thing (asset name for instance) and I gotta be really careful to make sure I do not commit an api key into the repo, but having it would allow to reuse SAME file for testing a strategy on different assets and using different duration.

Thank you a lot for understanding.

so after starting the bot with the command

`$ APIKEY=1234 ASSET=R_100 DURATION=5 bot ldp_v1.js`

I would be able to read those values in the code

```
var ApiKey      = process.env.APIKEY; 
var TradeSymbol = process.env.ASSET; 
var Duration    = process.env.DURATION; 

```

**Comment by phlawio** [comment]
Como faço o programa entrar com uma compra (call) e depois entrar com uma venda (put), e depois call, logo após put, e assim sucessivamente, fazendo um loop?
