### ISSUE TITLE
Candle test 2 minutes

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#3423]
Hello, I would like to know if there is a way to configure a bot block to analyze the values of a 2min candle in vol 10. The function would be from the entry point of the candle add or subtract (if it is green or red candle) the maximum or minimum value reached in that candle, the result greater than 1.10 or less than 1.10. It is to continue analyzing statistics in barriers inside out or in touch not touch. The ideal would be to do a back testing but I don't know if it is possible in the in out touch no touch option.
 With the traditional bot it cannot be done because there is a loss of time of approximately 2 or 3 seconds so it is not possible to analyze every 2 minutes exactly. 

Regards

**Comment by sundaybaezofficial** [comment]
yes is no possible binary have delay ,,, the only way for bots is to enter in 1 min candle .. 55 seconds operations or operate manually
