### ISSUE TITLE
please help to pause when bot lose

### ISSUE THREAD

**Issue by lasebopjm** [binary-com/binary-bot#3427]
ini bot yang saya gunakan

[binary-bot-Profitable.BOT0017 - Professor Inv.FMMv2.6x.xml.zip](https://github.com/binary-com/binary-bot/files/7178213/binary-bot-Profitable.BOT0017.-.Professor.Inv.FMMv2.6x.xml.zip)

[@Fruitfella](https://github.com/Fruitfellal)

**Comment by Truwalter** [comment]
> ini bot yang saya gunakan
> 
> [binary-bot-Profitable.BOT0017 - Professor Inv.FMMv2.6x.xml.zip](https://github.com/binary-com/binary-bot/files/7178213/binary-bot-Profitable.BOT0017.-.Professor.Inv.FMMv2.6x.xml.zip)
> 
> [@Fruitfella](https://github.com/Fruitfellal)

Specify how long it will pause and send to was.me/2348134933126
