### ISSUE TITLE
A rise and fall bot or stratagy with 70% to 80% win rate in binary

### ISSUE THREAD

**Issue by jahidbappy** [binary-com/binary-bot#3428]
Plz, can anyone tell or give me a strategy that has a 70% or 80% win rate in binary.com. So I can use it without a martingale

I have low balance in my account and I don't want to lose them so plz help me if you can

**Comment by Truwalter** [comment]
> Plz, can anyone tell or give me a strategy that has a 70% or 80% win rate in binary.com. So I can use it without a martingale
> 
> I have low balance in my account and I don't want to lose them so plz help me if you can

Chat wa.me/2348134933126
