### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aleks7772012** [binary-com/binary-bot#343]
а как я могу получить инструкцию по написанию бота, или по крайней мере блок описание
and how can I get a manual for writing of the bot, or at least block description

**Comment by blinksmith** [comment]
### You can learn blockly from here https://developers.google.com/blockly/
![blockly](https://user-images.githubusercontent.com/409976/28618586-1b7c8ac6-722f-11e7-8da5-0f17fdb74b30.PNG)
