### ISSUE TITLE
Please identify what trade type  he is using ( menna badr )

### ISSUE THREAD

**Issue by pugak825** [binary-com/binary-bot#3433]
We all know this menna badr is trading in demo look at his video in youtube.
[](https://youtu.be/WpH8UMxMbXE) 
The only thing that is expose is the Entry and Exit which is 3406.30 something like that it starts with number 3 sometimes 4. 
Can you guess the trading type so we can make a bot from that kind .thank you 🙂
![Screenshot_20210926_072539](https://user-images.githubusercontent.com/91371750/134788919-5563a1c9-81f1-47ee-9ee7-3d5107a473c1.jpg)

**Comment by pugak825** [comment]
Ok i will not trust him

**Comment by harshalkharose** [comment]
Hello brother I know this type of trade in working on the same bot

**Comment by Goldenboy9** [comment]
> Hello brother I know this type of trade in working on the same bot

Can you share the bot to us here please !

**Comment by Arohman94** [comment]
> Dia penipu

feel very helped by this information, almost cheated by menna badr

**Comment by Arohman94** [comment]
> Halo saudara saya tahu jenis perdagangan ini dalam mengerjakan bot yang sama

Very great, may I try, and take the bot. I hope you will be rewarded better by God
