### ISSUE TITLE
24 hours profitable bot

### ISSUE THREAD

**Issue by LGloucester** [binary-com/binary-bot#3436]
I know, it's insane. But I've created it.

**Comment by anggado** [comment]
would be so much nice if you would share it to us @LGloucester

**Comment by LGloucester** [comment]
> would be so much nice if you would share it to us @LGloucester 

I haven't decided yet whether I should just boast about it or start selling haha

**Comment by VERTO13** [comment]
You can send me a message of your decision please @LGloucester

**Comment by Otavianofreitas** [comment]
share it here so we can help you testing... @LGloucester

**Comment by pugak825** [comment]
show some screenshots

**Comment by CnK888** [comment]
I created bot can stay for 3 days

**Comment by anggado** [comment]
@CnK888 please share the xml with us here, dont be like @LGloucester 😜

**Comment by bobmeg** [comment]
Is this even possible...??
