### ISSUE TITLE
Becarefull!!! Anybody can explain this binary chart

### ISSUE THREAD

**Issue by CnK888** [binary-com/binary-bot#3440]
![Screenshot_2021-10-08-11-00-48-465_com android chrome](https://user-images.githubusercontent.com/92135259/136492976-d2186341-b147-4bf1-a0f2-f8cd8e94c795.jpg)
And this
![IMG_20211008_110414](https://user-images.githubusercontent.com/92135259/136493001-891a1989-cf1c-4a8c-bc40-0af9672fbe76.jpg)
Same time 🤣

**Comment by pugak825** [comment]
that is why trading view chart is a real index, binary bot is synthetic market
