### ISSUE TITLE
Please can anyone make this EVEN ODD BOT

### ISSUE THREAD

**Issue by MassSLtrader** [binary-com/binary-bot#3452]
Stratergy -

3 odds = Trade EVEN
3 Evens = Trade ODD

Ex-
14,375.03
14,375.07
14,375.05
(3 odds = Trade EVEN)

14,375.06
14,375.02
14,375.00
(3 evens = trade ODD)

**Comment by MassSLtrader** [comment]
bot is almost good!. but,it always jumping a number.
like this  
444 (3evens) it should be 4. but,it appears 8
468 (3evens) trade odd. it should be number 6. but,apears 7
Ex-on the picture!! 
like i said,its always jumping one digit

Can you fix that please

**Comment by VERTO13** [comment]
I'll try but maybe I wont be able to fix it, because its maybe because of binary delay

**Comment by Peacefull-Mind** [comment]
can anyone help to create a no touch bot ?

**Comment by Truwalter** [comment]
> Stratergy -
> 
> 3 odds = Trade EVEN 3 Evens = Trade ODD
> 
> Ex- 14,375.03 14,375.07 14,375.05 (3 odds = Trade EVEN)
> 
> 14,375.06 14,375.02 14,375.00 (3 evens = trade ODD)

I have it well developed, but in Portuguese. chat was.me/2348134933126

**Comment by Xerm-wear** [comment]
mind sharing the bot #Truwalter
