### ISSUE TITLE
Binary bot strategy touch no touch 

### ISSUE THREAD

**Issue by Peacefull-Mind** [binary-com/binary-bot#3460]
can someone please help creating a bot with this strategy.
ive been doing this manually for over half a year and is very profitable however is very time consuming aswell.

many thanks 

[NO touch strategy description(1).pdf](https://github.com/binary-com/binary-bot/files/7442061/NO.touch.strategy.description.1.pdf)

**Comment by bobmeg** [comment]
What is the percentage profit on thw barrier...??

**Comment by Peacefull-Mind** [comment]
The percentage will be over 600.Do you think you can create this ?Sent from my Galaxy
-------- Original message --------From: bobmeg ***@***.***> Date: 03/11/2021  11:50  (GMT+02:00) To: binary-com/binary-bot ***@***.***> Cc: Peacefull-Mind ***@***.***>, Author ***@***.***> Subject: Re: [binary-com/binary-bot] Binary bot strategy touch no touch  (Issue #3460) 
What is the percentage profit on thw barrier...??

**Comment by Peacefull-Mind** [comment]
basically the idea is,,, 
identify a strong trend, purchase a no touch position against the trend with a high pay-out for example 600% and then close trade when profit is between 150 to 200% what happen sometimes in the first tick.

this will give you a 2/1 profit what means you don't need to use martingale as you will win enough times to cover you losses. even if you only win half of the times what is very unlikely you will still be on 0.
I've been doing this manually and works extremely well however after a wile you start seeing things when they don't exist and start doing trades all the time without paying attention to the trend. :p

**Comment by bobmeg** [comment]
Its a good idea but actually still equally risky with a bot

**Comment by Peacefull-Mind** [comment]
ive build a bot with this strategy already and works ok but im using emas to identify the trend what is not great ideally i would have ADX, stochastic, and RSI .

is this something you can build ?
