### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by binarybotbegginer** [binary-com/binary-bot#3461]
Hello All,

Hope everyone are doing well. Just wondering where could we get historical data for all the "Volatality Indices"? I understand that charts.binary.com provides the last 100 tick values for each 5 minute interval. Just wondering whether we can get individual tick data for a selected number of days (full days)? I earlier used the Binary MT5 app to get the data, but I am not sure why, I am not able to retrieve the data these days. I get an error message saying something like "session timeout".

Thanks in advance.

**Comment by sundaybaezofficial** [comment]
the only way to get the historical data is with mt5 deriv in pc 

![image](https://user-images.githubusercontent.com/85972837/140244791-dbdccd54-7a74-4902-8912-40038f240975.png)
