### ISSUE TITLE
Is it possible to create a link that loads my bot xml file?

### ISSUE THREAD

**Issue by rotneto** [binary-com/binary-bot#3462]
Hello good afternoon.

I would like a suggestion or idea for a simple feature.

The idea is to create a link that in the onclick event loads my bot xml file, is this possible?

I've already taken a look at the code, but I didn't identify the xml loading function because then it makes a mistake to add an event loading the file from the remote server link.

I appreciate any suggestions.

**Comment by sundaybaezofficial** [comment]
is posible with the link of the block  xml like this

![image](https://user-images.githubusercontent.com/85972837/140244263-2d51fb6e-8c08-4b5a-904c-ef9aa5fd612f.png)



[Load Block from.zip](https://github.com/binary-com/binary-bot/files/7471744/Load.Block.from.zip)

**Comment by rotneto** [comment]
> is posible with the link of the block xml like this
> 
> ![image](https://user-images.githubusercontent.com/85972837/140244263-2d51fb6e-8c08-4b5a-904c-ef9aa5fd612f.png)
> 
> [Load Block from.zip](https://github.com/binary-com/binary-bot/files/7471744/Load.Block.from.zip)

thanks
