### ISSUE TITLE
 How can we make this pattern  Doji (Doji, Dragonfly , Gravestone Doji ) and  Long Lower Shadow  and  Long Upper Shadow  

### ISSUE THREAD

**Issue by dulajkulathunga** [binary-com/binary-bot#3470]
Can someone help me create below pattern or  if you have these kind of pattern kindly share it here please 

  Doji (Doji, Dragonfly , Gravestone Doji ) ,
  Long Lower Shadow 
  Long Upper Shadow

**Comment by Truwalter** [comment]
I have the robot, well developed

**Comment by Truwalter** [comment]
> Can someone help me create below pattern or if you have these kind of pattern kindly share it here please
> 
> Doji (Doji, Dragonfly , Gravestone Doji ) , Long Lower Shadow Long Upper Shadow

I have the paid bot.
