### ISSUE TITLE
you try.. try..& try ,you waste time & money and when you finally succeed to do something this shit appears:"this strategy is not availble in your country"

### ISSUE THREAD

**Issue by Martinez222** [binary-com/binary-bot#3473]

**Comment by Martinez222** [comment]
Did anyone know what the f... happened?Is this temporary?Is a solution to keep using bots?
![realvs](https://user-images.githubusercontent.com/39260368/142380102-380aa25f-2c0d-47bd-8990-ada52ccd8c8b.jpg)
![restriction](https://user-images.githubusercontent.com/39260368/142380108-c0eb32f3-2310-467d-88ed-c2e3c3decbfb.jpg)

**Comment by LowKey22** [comment]
hey did you solve this??

**Comment by Martinez222** [comment]
@LowKey22 
5 years of trying ... 5 years of time lost ..a lot of money lost until I managed to build a profitable robot..And when I finally managed to do that and start to recover this crap appeared !! No explanations ..no advance notifications !! Bastards !!
My advice for everyone:DON'T INVEST ANY MONEY ON BINARY.COM!SCAMERS!!!!

**Comment by Bebindas** [comment]
@Martinez222 SORRY FOR WHAT YOUR FACING  CAN YOU SHARE STRATEGY WITH US  PLEASE IF YOU DONT MIND .. 
WAITING FOR REPLAY THANKS IN ADVANCE .
