### ISSUE TITLE
different digits bot @binaryexmachina @Fruitfella HELP

### ISSUE THREAD

**Issue by enexxen** [binary-com/binary-bot#3474]
hello, I need help for my Digit Bot when I lose to make a new entry in 156 seconds, but if the contract is won continue normally @binary-ex-machina @Fruitfella

![image](https://user-images.githubusercontent.com/93987193/142418810-7276bee4-eda1-4736-867d-6bd9977edc05.png)

for some reason that I do not know the least frequent number in the circle is never put at 0 although the statistics say that the least frequent is 0, why is it?

![image](https://user-images.githubusercontent.com/93987193/142419854-74a084da-0435-4f1e-bd4e-2ea2ae92665c.png)

my Bot runs when the last 2 numbers are equal to the most frequent number in a list of 99.9 ticks, he makes an entry with the least frequent number that is different from the number 1

![image](https://user-images.githubusercontent.com/93987193/142420671-c923adf6-789b-4d1a-847c-d51cbfec9c49.png)

the 156 seconds are to avoid this

![image](https://user-images.githubusercontent.com/93987193/142446507-e37910a0-39c3-45c7-b976-47d253cbee42.png)

![image](https://user-images.githubusercontent.com/93987193/142503601-22a0d4a1-2583-4e31-91d3-649908ffeff8.png)

**Comment by binary-ex-machina** [comment]
inside the fruitfella block, you must check if the contract is won. In case of a win, trade again directly. Otherwise, wait for 156 seconds

![image](https://user-images.githubusercontent.com/34610787/149584654-9554cd64-acc4-432b-bb70-fcac5941c86d.png)

**Comment by enexxen** [comment]
> dentro del bloque fruitfella, debe verificar si se gana el contrato. En caso de ganar, opere de nuevo directamente. De lo contrario, espere 156 segundos.
> 
> ![imagen](https://user-images.githubusercontent.com/34610787/149584654-9554cd64-acc4-432b-bb70-fcac5941c86d.png)

muchas gracias amigo
