### ISSUE TITLE
Este é um recurso novo da binary.com ? 

### ISSUE THREAD

**Issue by ForexJapao** [binary-com/binary-bot#3475]
Como Fazer o bot trocar da conta real para conta virtual como este bot da foto ? Este é um recurso novo da binary.com ? 

![TROCA REAL VIRTUAL](https://user-images.githubusercontent.com/56320282/142454481-00b3f818-7b79-4552-84c8-2fe7cedec6e8.jpg)

**Comment by cleberscr** [comment]
https://bot.binarytools.io/platform
