### ISSUE TITLE
Indicator reading (value) of the last 2 ticks/candles

### ISSUE THREAD

**Issue by Jaskown** [binary-com/binary-bot#3477]
Ahoe!

How can I get an indicator reading/value of the previous 2 ticks? 
I know of the previous tick (using Last Tick) but if I want to go further back into tick 2,3,4 etc how can I do it for let's say SMA or EMA?

**Comment by binary-ex-machina** [comment]
You can use the arrays for the indicators and the lists for ticks and candles

![image](https://user-images.githubusercontent.com/34610787/149581600-196bf150-695c-4a12-8056-3a280fd24b86.png)

**Comment by Jaskown** [comment]
@binary-ex-machina  Thanks


> You can use the arrays for the indicators and the lists for ticks and candles
> 
> ![image](https://user-images.githubusercontent.com/34610787/149581600-196bf150-695c-4a12-8056-3a280fd24b86.png)
