### ISSUE TITLE
Earn money fast -Please make bot like this

### ISSUE THREAD

**Issue by pugak825** [binary-com/binary-bot#3479]
Rise Fall BOT
👉Here's the sequence 
☀️Call
🔸Put
☀️Call
☀️Call
🔸Put
🔸Put
Repeated infinite
And put Martingale also.
Thank you.🙂
[Earn money Fast](https://youtu.be/rniK8giSeRk)

**Comment by VERTO13** [comment]
But, in which pair, how many ticks or minutes?

**Comment by bitcoin-generator** [comment]
Have you tried adding this pattern to deegeebot?

**Comment by pugak825** [comment]
> But, in which index, how many ticks or minutes?

Any index that will do

**Comment by pugak825** [comment]
> Have you tried adding this pattern to deegeebot?

I don't know how to use that

**Comment by VERTO13** [comment]
> > But, in which index, how many ticks or minutes?
> 
> 
> 
> Any index that will do

And do you want it with ticks or minutes and how many of them?

**Comment by pugak825** [comment]
Ticks or minutea , can you do that please, thank you

**Comment by MiithRanDir** [comment]
I made a bot for you to try.
[binary-bot-seq.zip](https://github.com/binary-com/binary-bot/files/7667506/binary-bot-seq.zip)


[มังกรฟ้า](https://www.มังกรฟ้าเชิญมารวย.com)

**Comment by pugak825** [comment]
THANK YOU BROTHER, you RE GENIUS , this is exactly what i need , happy new year

**Comment by ChinthakaJP** [comment]
Join My Channel and Subscribe  : 
https://www.youtube.com/channel/UCYFCodv64R4w5087LM4Jq4A
