### ISSUE TITLE
How to create a bot with these conditions, please?

### ISSUE THREAD

**Issue by joshnguyen92** [binary-com/binary-bot#3483]
Last digit "0", Purchase "Differs", prediction "0"....If result "loss", it will set one more order immediately...not to wait until the next last digit "0"...if loss again, continue setting one more order immediately until win with martingale...and then if win, back to trade again....How to create a bot with those conditions, please!!?

**Comment by binary-ex-machina** [comment]
you can do like this

![image](https://user-images.githubusercontent.com/34610787/149579656-f75da7e0-ef02-4208-b20b-2ce7f6f2e55f.png)
