### ISSUE TITLE
time if loss less than 1 minute stop trading - binary bot

### ISSUE THREAD

**Issue by Sherifelbarbary** [binary-com/binary-bot#3490]
iam using binary bot no touch for 2 min

i want to add ..  if the trade loss in less than 1 min from opening position stop trading

i hope some one help me in that

thanks

**Comment by binary-ex-machina** [comment]
There is no block to make the bot stop altogether. So you can avoid the script going through the Trade Again block. But I didn't understand what you wanted to do.

I guess you want the trade to end trade if it's in loss and with less than 1min of the contract duration. Am I right?
