### ISSUE TITLE
Need forex expert advisor using below mention indicators.

### ISSUE THREAD

**Issue by dula96** [binary-com/binary-bot#3507]
Need forex expert advisor using below mention indicators.

1.Moving Averages (Parameters: As you wish)
2.Bollinger Bands (Parameters: As you wish)
3.Relative Strength Index (RSI) (Parameters: As you wish)
4.Commodity Channel Index (Parameters: As you wish)
5.Stochastic Oscillator (Parameters: As you wish)

Thanks.

**Comment by binary-ex-machina** [comment]
@dula96 you can build your expert advisor here https://www.eabuilder.com/

This repository is for the binary bot and Deriv bot issues, not forex expert advisors. Try to find the right repository for this, or forum
