### ISSUE TITLE
LAST 2 DIGITS ARE EQUAL I NEED BOT OF DIFFER

### ISSUE THREAD

**Issue by arehmanyounis** [binary-com/binary-bot#3512]
Hi everyone,
Is it possible to start a bot if the "Last 2 digits" are equal?
For eg.: If the tick value is 5735.99 -> Last 2 digits are equal. i.e, "9". Random trigger set 0-9 .
mean any 2 digits will come same Example
5735.00 bot start 
5735.11
5735.22....... 5735.99
I would like to set the prediction as "0 to 9" and bet that it differs in the next tick.

Is it possible?

**Comment by binary-ex-machina** [comment]
@arehmanyounis, it's possible. You do this by putting the last tick in a variable, transforming it into a string, then you get the letters as it is an array of elements

![image](https://user-images.githubusercontent.com/34610787/149530022-20f687b1-03b2-4222-87f6-c72aaa4f5284.png)

**Comment by arehmanyounis** [comment]
GOD BLESS YOU THANKS FOR REPLY IF ITS POSSIBLE TO MAKE BOT  FOR ME PLEASE REPLY

**Comment by arehmanyounis** [comment]
ONCE AGAIN THANKS IT IS POSSIBLE TO MAKE WITH MARTINGLE ALSO

**Comment by binary-ex-machina** [comment]
@arehmanyounis yes, it's possible to insert martingale

![image](https://user-images.githubusercontent.com/34610787/149622756-05d42b8f-4866-46f1-ab44-85a19a03c4e4.png)

**Comment by arehmanyounis** [comment]
once again thanks alot to reply me I AM NOT ABLE TO SET THIS ABOVE MENTIONED CONDITIONS PLEASE HELP ME AND PLEASE I REQUESTED TO MAKE A BOT AND EMAIL TO arehmanyounis@gmail.com 
i shall be very thanks full to you

please reply

**Comment by cleberscr** [comment]
> @arehmanyounis sim, é possível inserir martingale
> 
> ![imagem](https://user-images.githubusercontent.com/34610787/149622756-05d42b8f-4866-46f1-ab44-85a19a03c4e4.png)

meu amigo, vi você ajudando algumas pessoas e muitas vezes ficou parecendo tempo perdido e muitas vezes elas implorando para você fazer para elas, você decide usar o que quer e fazer se quiser, claro, mas parece que as pessoas estão preferindo a binary classica, mais facil de aprender e fazer, o dbot parece que deixa eles muitos confusos para aprendizado....

**Comment by binary-ex-machina** [comment]
@cleberscr concordo com  você na parte que eles preferem fazer com o bot clássico. Eu prefiro no DBot por que ali é onde a Deriv vai investir para o futuro e vai chegar um ponto onde o bot de blocos clássico cai ser removido. 

Da parte de elas parecerem perder tempo perguntando ou eu respondendo de algumas formas que não são tão mastigadas, a minha ideia aqui sempre foi de instigar o pessoal a se virar por conta própria, especialmente para não depender deste repositório 100% do tempo. Se Eu conseguir que 1 em cada 100 consiga usar o Dbot e ainda fazer o básico das estratégias, já valeu o esforço aqui. 

Obrigado pelas colocações

**Comment by arehmanyounis** [comment]
please make bot and email xml file

**Comment by khan1313** [comment]
> @cleberscr concordo com  você na parte que eles preferem fazer com o bot clássico. Eu prefiro no DBot por que ali é onde a Deriv vai investir para o futuro e vai chegar um ponto onde o bot de blocos clássico cai ser removido. 
> 
> Da parte de elas parecerem perder tempo perguntando ou eu respondendo de algumas formas que não são tão mastigadas, a minha ideia aqui sempre foi de instigar o pessoal a se virar por conta própria, especialmente para não depender deste repositório 100% do tempo. Se Eu conseguir que 1 em cada 100 consiga usar o Dbot e ainda fazer o básico das estratégias, já valeu o esforço aqui. 
> 
> Obrigado pelas colocações

Hello Sir.
I want to know binary digits algorithm. How its works and hows we trade in digit trading in smart trader platform which is provided by binary.com. 
Also i want your WhatsApp contact number please...
