### ISSUE TITLE
Bot creator/developer

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#3514]
STOP waiting for days before getting a response to your questions (you might even not get a response)

For a little fee, I will create BOT for all your strategies.

I can also help you edit your bots, add martingale, stop loss, take profit or anything you need.

Send a message to my email on eonuoha30@gmail.com

Or WhatsApp me by clicking this link: 
https://api.whatsapp.com/send?phone=2348134998827&text=I%20need%20a%20bot

**Comment by binary-ex-machina** [comment]
I don't think there is a marketplace to offer your services. This repository exists to help people, teach others, post issues, and get help on questions about the binary bot. There are other forums and websites where you can promote your services

**Comment by KingSo7** [comment]
Why will you create a bot for someone and take money, won't you benefit from it when it's profitable? My brother let's help each other. @binary-ex-machina please can you help me create my bot pleases, I will provide the details when you are ready please

**Comment by binary-ex-machina** [comment]
@KingSo7, maybe I can help you, but instead of asking for help in someone's issue, create an Issue and post your problem in there. Then wait for someone to help

**Comment by KingSo7** [comment]
@binary-ex-machina I have created one just now kindly help if you can
