### ISSUE TITLE
How to enter trade when the new candle opens/bot attached ?

### ISSUE THREAD

**Issue by dritonbytyqi** [binary-com/binary-bot#3515]
Hello Guys
I hope you can help me with something, I have a bot that I tried to make the logic work with higher/lower vith modified virtual loss but I have a problem :
How to enter the trade in the start of candle (if it can start in the first tick would be great) or to start when the last candle (1 min TF) closes then enter trade for 10 ticks :
If anyone has any idea for this problem how to add this block please help 
I attached the bot here : 
[Almost done Counter Fix.zip](https://github.com/binary-com/binary-bot/files/7866261/Almost.done.Counter.Fix.zip)

**Comment by binary-ex-machina** [comment]
You can make all the analysis of your strategy at the last tick of the actual candle. This way, if one of your conditions where true, it will start at the first tick of the next candle


![image](https://user-images.githubusercontent.com/34610787/149579007-7f220336-6546-479e-9242-c2b2a968c478.png)

**Comment by dritonbytyqi** [comment]
@binary-ex-machina  thank you very much , It is working now i tested but I have a problem with martingale , how can I make instead of martingale for covering loss, next trade  with for ex 
0.35 x 2.1 , 0.72 x 2.1 
Instead of that to go with 
0.35, 0.40, 0.80 , 1.70 , 3.70 etc 
Any idea how to make that ?

**Comment by binary-ex-machina** [comment]
the example you gave is like martingale, but twice the factor, just use bigger factor to multiple the stake

**Comment by dritonbytyqi** [comment]
@binary-ex-machina I think you missunderstood, I don't want to use factor multiplier at all, I just want to use a list of next trade covering the lost trade for example making a list,and for each trade to make a sum/number of next investment 
0.35 then 0.40 then 0.80 then 1.70 then 3.70 or a higher number or steps of the list for recovering the first lost trade 
Costummode list with amounts (fixed amounts) not using multiplier or incremental methode

**Comment by binary-ex-machina** [comment]
You can make a stake list like this below. If the amount of sequential losses is higher than the number of items in the stake list, it will restart from the first item

![image](https://user-images.githubusercontent.com/34610787/149849704-35397bce-da42-46dc-8e6f-a7f5599c3a82.png)
