### ISSUE TITLE
BINARY BOT HELP VIRTUAL LOSS FREE BOT TOO!

### ISSUE THREAD

**Issue by BudidiKun** [binary-com/binary-bot#3516]
Hello Friend! 
Can someone help me put a virtual loss in my bot its so annoying because when i try to put virtual loss it trades to 9$ at first real trade after the virtual loss it has to be 1
Pls help
Here is the bot your can use it
but pls can you help me to put a virtual loss where if it loss it enter at 1$ not 9 because it count the loss trade in martingle

[SMA BOT.txt](https://github.com/binary-com/binary-bot/files/7875127/SMA.BOT.txt)

change the .txt to .xml

**Comment by binary-ex-machina** [comment]
here is a detailed way to implement virtual loss to your strategy

https://github.com/binary-com/binary-bot/issues/3526
