### ISSUE TITLE
How to use XML code??

### ISSUE THREAD

**Issue by sai84** [binary-com/binary-bot#352]
Hello! Recently I've started to develop robots using web-interface on bots,binary.com. I see that many useful examples of code are located here in XML-code. Could you please explane my how to use it?

**Comment by Fruitfella** [comment]
Hi @sai84 , wellcome. here is how to use xml file : 
1. open bot.binary.com/bot.html, dont forget to log in with with either ur real or virtual account
2. click **Load new blocks (xml file)** the one with folder icon on the top-right corner, under your account balance
3. locate ur xml file, open it.
4. run ur bot to test it by clicking **Run the bot** button, the one with triangle icon on the right screen.

note: hover ur mouse arrow on the buttons or blocks to see description.

**Comment by sai84** [comment]
Thanks!

**Comment by aminmarashi** [comment]
@sai84 You can also add the block xml files by dragging and dropping them into the bot page.
