### ISSUE TITLE
please add martingale 

### ISSUE THREAD

**Issue by zakziko12** [binary-com/binary-bot#3521]
[Bot Double Agent Even Odd Pattern.zip](https://github.com/binary-com/binary-bot/files/7929420/Bot.Double.Agent.Even.Odd.Pattern.zip)

**Comment by KingSo7** [comment]
So i added tge martingale but the is a little problem with it. As soon as it gives the martingale and wins, stop the bot and run again to start at  initial stake. I have added stop lóss and take profit too
[Work 1.txt](https://github.com/binary-com/binary-bot/files/7978249/Work.1.txt)

**Comment by zakziko12** [comment]
> So i added tge martingale but the is a little problem with it. As soon as it gives the martingale and wins, stop the bot and run again to start at initial stake. I have added stop lóss and take profit too [Work 1.txt](https://github.com/binary-com/binary-bot/files/7978249/Work.1.txt)

Thank you for your time, I encountered a problem when opening the first trade and you lose, the bot stops

**Comment by KingSo7** [comment]
> 

Try changing the stop loss

**Comment by zakziko12** [comment]
> So i added tge martingale but the is a little problem with it. As soon as it gives the martingale and wins, stop the bot and run again to start at initial stake. I have added stop lóss and take profit too

tahnk you Sir
