### ISSUE TITLE
How to enter at the OPEN of a candle always without delay?

### ISSUE THREAD

**Issue by Rigoff** [binary-com/binary-bot#3529]
Hello! What to do to avoid this "Rate limit reached for: buy, retrying in 1.5s" when trading with a bot on forex currency? Help fix this please! Because of this, the trading results do not match the candles.
![Screenshot_164](https://user-images.githubusercontent.com/43293449/152125667-51ff8520-be37-4421-a483-b283fce0bdfd.png)

**Comment by binary-ex-machina** [comment]
Try to stay under 20 trades per minute and 720 trades per hour. The forex pairs have different rate limits.

**Comment by Rigoff** [comment]
Thank you very much for your reply, but I have a timeframe of 15 minutes and an expiration of 15 minutes, that is, 1 trade 1 time in 15 minutes, and then not every candle, about 30-60 trades per week.  Please, look, maybe it's because the yellow block makes a request every tick in the range from 0 to 20?
![Screenshot_166](https://user-images.githubusercontent.com/43293449/152177356-7b664e42-4ade-4b89-a34e-e8d923f94781.png)

**Comment by Rigoff** [comment]
But only 1 bot works on my account, and it makes 1 trade 1 time in 15 minutes, okay, so the problem is not in the bot, but in the broker, strange and sad. Thanks for the help.

**Comment by hotmatrixx** [comment]
Hi, guys.

It's been a really long time!

So, Binary x that's a pretty tidy solution.
What I used to do, which might be a bit heavier, actually, was 


 I'd save the open time as a variable
 then on every tick, I'd test if that variable changed, and if it had I'd return that as a function, then update the original variable to the newer value :)

**Comment by Rigoff** [comment]
> Hi, guys.
> 
> It's been a really long time!
> 
> So, Binary x that's a pretty tidy solution. What I used to do, which might be a bit heavier, actually, was
> 
> I'd save the open time as a variable then on every tick, I'd test if that variable changed, and if it had I'd return that as a function, then update the original variable to the newer value :)

Hello, this is a bot, please do it?
![Screenshot_172](https://user-images.githubusercontent.com/43293449/152493468-a56c98db-ae8f-410c-b387-051a8df3faf8.png)

**Comment by binary-ex-machina** [comment]
@hotmatrixx, your idea is another way to enter the trade on a new candle. The main issue is that you will always enter one tick inside the candle and not at 0 seconds of the new candle. Using Seconds to Epoch, the bot can analyze the last tick of the candle and start the trade right at the beginning of the next candle.
