### ISSUE TITLE
HELP ME FIX THIS input cannot be empty ERROR

### ISSUE THREAD

**Issue by Bkind254** [binary-com/binary-bot#3530]
Hi good people I've been trying to fix this issue from the bot i created  please assist me fixing it..any help would be great and appreciated. I keep getting saying INPUT CANNOT BE EMPTY. Here is the bot. @binary-ex-machina you are awesome at this. Also @James-Ngigi.
[one touch.zip](https://github.com/binary-com/binary-bot/files/7995931/one.touch.zip)

**Comment by binary-ex-machina** [comment]
put the ticks list in the input list on these blocks. The EMA block needs to receive a list of values to calculate. When you don't pass a value, it will not work

![image](https://user-images.githubusercontent.com/34610787/152376676-c4c626ee-594b-4ac4-b750-994b1665b409.png)

**Comment by Bkind254** [comment]
Okqy let me do that Thank you bro
