### ISSUE TITLE
(BUG / Major QOL)List Blocks VS Indicators

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#3531]
Most Indicators require a Candles List to work off, this is fine.
The candles lists list the last 1000 candles, this is fine.

The issue, is that the indicator seems to use the Oldest available Data in the list, whereas most of the time, a user is likely wanting to use the most fresh data first, meaning that result that we get is the indicator is 1000 candles old.

There is no simple way to tell an incidator to use the end of the string, I have "worked around this" 
in 2 ways;

1 is to create my own list using a loop that counts backwards, then using that data
or 
2 snipping the last few candles for the period I want using "Get Sub List"

**Comment by binary-ex-machina** [comment]
On my tests, the indicators are using the right value, as you can see in the image below
![image](https://user-images.githubusercontent.com/34610787/152646408-2fe29d42-b344-4b13-bb0b-d3ac30bc3b78.png)

On DBot, the same happens, all correct. The red line is moving average with 20
![image](https://user-images.githubusercontent.com/34610787/152646520-aec522f3-b6ac-4a80-97f8-d6b74298d7dc.png)

![image](https://user-images.githubusercontent.com/34610787/152646493-572fa076-ef22-4dca-ba67-de6d97fa5b4d.png)

Can you show an example so we can reproduce the issue?
