### ISSUE TITLE
pagina bot defeito

### ISSUE THREAD

**Issue by andlilinmacedo** [binary-com/binary-bot#3534]
pagina bot não rola para cima não tendo como fazer as configurações do robo iniciantes perdendo dinheiro pois não sabe que tem de fazer todas as configurações para ele operar robo operando sem não aparece saldo da conta para visualizalo tem de entrar em saldo roda pe da pagina sem informações

**Comment by binary-ex-machina** [comment]
Consegue mandar uma imagem da página do bot com defeito? Outra questão é qual página do bot você está usando

testei todos aqui e estão funcionando normalmente, com todos os botões aparecendo

https://bot.binary.com/bot.html
![image](https://user-images.githubusercontent.com/34610787/153230689-ce8be2ae-451c-4d60-98cf-d21edf3a458e.png)

https://bot.deriv.com/
![image](https://user-images.githubusercontent.com/34610787/153230759-4cf32407-d6e5-4d25-a5af-409b79573fca.png)

https://app.deriv.com/bot
![image](https://user-images.githubusercontent.com/34610787/153230825-ac57cf5f-edfe-4b92-8093-97a37dbd849a.png)
