### ISSUE TITLE
PUT PREDICTION AS THE LAST DIGIT

### ISSUE THREAD

**Issue by rainmaker21111** [binary-com/binary-bot#3535]
Hi, I need help. Is it possible to set up the bot in a way such that if a number appears 3 times in a row as the last digit , the bot can place the trade with the prediction being the number that appeared three times in a row?

**Comment by brianmcaudill** [comment]
Today I was building the same bot that you are describing and running onto issues with dynamically changing the "prediction". I am not sure if this system can be programmed with a bot or if you need to use the API. I will have to do some more testing. If anyone else knows let me know.
