### ISSUE TITLE
Execute XML in Background via API

### ISSUE THREAD

**Issue by binarybotbrazil** [binary-com/binary-bot#3540]
Is it possible to execute XML strategies in the background via API, without having to leave the browser active?
I don't mean using VPS, but specifically executing the XML strategies via the backend (PHP, NodeJS, etc), through the API.

It is very tiring to have to leave the cell phone or computer/VPS on 100% of the time, so I would like to know if there is already a code ready to do this, or even if there is not, what would be the most correct way to build this?

**Comment by hotmatrixx** [comment]
No, they do not provide this as a service.
your code, your hardware.

I think you may have noticed that the bot is hardly optimized, it runs a PC hard with quite a lot of RAM and CPU usage.

I can't imagine they'd be happy with footing that cost for us unless we were actually using a live account....

in saying that, they do have a native / non browser client floating around somewhere that 'may' be more efficient.

**Comment by binarybotbrazil** [comment]
@hotmatrixx I imagined that too! I'm thinking of a way to implement this myself.
Would there be any direction?

**Comment by binary-ex-machina** [comment]
@binarybotbrazil, you need to read the XML and transcript to the language your page will read. Google Blockly has a library to transcript XML to other languages (I know about the JS library, but they have others). The same way the bot page can get the XML content and use as filter for all the 4 trading stages, you can use with any language
