### ISSUE TITLE
[BUG Report] Deriv bot - Payout (Rise) / (Fall) block

### ISSUE THREAD

**Issue by hotmatrixx** [binary-com/binary-bot#3543]
I am using the Payout block to determine the amount of a payout during the 'prepare to purchase' phase - in block 2. I only want it to trade if the returns are high or low enough.

![image](https://user-images.githubusercontent.com/49715381/154282932-108dc520-55ef-4e66-8b46-3c349cdf0682.png)

I was not getting the results I expected.

During testing I discovered that it works well on the FIRST trade, and upon any winning or losing trade (ie the bot cycles through to block 4). HOWEVER. I have a loop in block 2 in the form of a simple IF/Then if the payout isn't high enough .

So, if this condition becomes 'true' the bot will loop in block 2. It will however no longer update the Payout block, and it's value will remain the same indefinitely.

This means that If the condition (payout is too low) becomes TRUE - my bot will not buy a trade, and will loop until the payout raises high enough, BUT the payout never updates so i keeps looping on the value that caused it to stop looping in the first place.

![image](https://user-images.githubusercontent.com/49715381/154283220-0ce9cd08-d9e8-4c0b-b209-0ca678f4a8e8.png)

**Comment by binary-ex-machina** [comment]
I have tested here and the payout is changing normally. What market did you used on your tests?

![image](https://user-images.githubusercontent.com/34610787/161870593-6e46d6a5-9f1e-4d53-93ca-ea234cecb07e.png)
