### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Sergiu20** [binary-com/binary-bot#3547]
Como construir um bot a partir do menu inicial do Deriv Bot e em seguida executar o bot?

**Comment by binary-ex-machina** [comment]
Siga estes passos

1. Abre a página https://app.deriv.com/bot?lang=PT
2. Login com a sua conta
3. No menu blocos, selecione o bloco que você quer usar 
![image](https://user-images.githubusercontent.com/34610787/161866602-5fdd50d1-b2c5-4e53-936f-72c321dcb22b.png)

4. Ao selecionar o bloco, clique e arraste para o centro da tela
![image](https://user-images.githubusercontent.com/34610787/161866635-3ec07bdc-1115-48d4-b841-6f2c669c3c9e.png)

5. Construa o seu bot como você quer e clica em executar no canto superior direito da tela  
![image](https://user-images.githubusercontent.com/34610787/161866689-a6fe6ace-7153-4f4c-9a12-27db643b83aa.png)

Caso exista algum erro, clique na parte de avisos
