### ISSUE TITLE
Creación de lista automatica

### ISSUE THREAD

**Issue by Diego13Vinsco** [binary-com/binary-bot#3548]
Saludos, estoy tratando de crear un bot que me cree una lista automática ejemplo: Cuado se da la opción de comprar el bot me guarda el valor del tick en una Variable, este seria el dato 1 de la lista  cuando vuelva a comprar este sería el dato 2 y así sucesivamente hasta 60 y luego el número 61 seria nuevamente el dato 1, no se como hacerlo ya que por lo que veo me tocaría crear 60 variables para poderlos ingresar a la lista de forma manual, muchas Gracias por su tiempo.

**Comment by binary-ex-machina** [comment]
You can do it like this image below. When the number of items in the list entryTicks reaches 60, it will empty the list and add it again.

![image](https://user-images.githubusercontent.com/34610787/161865941-b79af5c0-8e0a-4de9-8ffc-bb2138246fb7.png)


If you want to keep the numbers and start renewing each position on the list, you can do it like the image below. This way, you start the bot with a list of 60 numbers. Each time the bot purchases a contract, it increases a variable counter and uses that variable to select the position on the list to substitute with the new tick

![image](https://user-images.githubusercontent.com/34610787/161866376-32fd3df5-e1e0-4797-8b52-0a3eafd9b8d4.png)
