### ISSUE TITLE
even odd bot

### ISSUE THREAD

**Issue by shadoWalker254** [binary-com/binary-bot#3554]
hello i wanted to ask if it is posible to create a bot that can enter a spot and you set a terget last number to appear say even so that it will run and if the last number is even it exit the spot if it does not get the even it continue to wait until it appers,
thanks in advance

**Comment by binary-ex-machina** [comment]
@shadoWalker254 the XML bot can trade only binary options, so you can't set when the bot exits. It will exit when the duration is over. You can sell the contract earlier, but then you must use longer durations to be able to sell the contract earlier. 

The image below will show how to buy/sell the contract based on the last digit being Even. Of course, this logic is non-sense, and it will buy/sell the contract almost at random, but you will get the idea of how to implement the logic to buy and sell the contract. To implement a logic to trade with Multipliers (where you can end the trade when you want), then you need to use API

![image](https://user-images.githubusercontent.com/34610787/161865495-46159285-7391-4507-a009-03800b7709e3.png)
