### ISSUE TITLE
[BOT REQUIRED] Martingale Bot - Auto Start from beginning when 3 times loss

### ISSUE THREAD

**Issue by vaibhav1405** [binary-com/binary-bot#3555]
Hi devs,
I need a martingale strategy in which it will again start trading when 3 martingale loss is hit
0.35$(Loss)   ->     0.70$(Loss)   ->        2$(Loss) In Case of loss/profit it will go to 0.35
	Martingale              Martingale 

Market - You can create in any market
Trade Type - Higher Lower

Thank You

**Comment by Jean-Eudes215** [comment]
if you want I create the robot for you but what do I gain in return?

**Comment by mwtheus** [comment]
Please send me a message so we can discuss further:

Telegram: @mwttt7
WhatsApp: +55 96 98142-6018

**Comment by binary-ex-machina** [comment]
@vaibhav1405, you can do like this image below. The bot will restart the stake when there are three sequential losses or when there is a win

![image](https://user-images.githubusercontent.com/34610787/161865020-718c9294-6c66-418b-b71b-be3616c89b80.png)

**Comment by vaibhav1405** [comment]
@binary-ex-machina  Thank you so much dude.

**Comment by kadenoo** [comment]
> @binary-ex-machina Hey buddy can you assist me in creating a bot that I can set the starting time.The bot should also activate martingale when it hits digits 4 or 5 on digit over or under.
Please Contact me on mugambideniskimathi@gmail.com
