### ISSUE TITLE
binary bot ends in

### ISSUE THREAD

**Issue by Bkind254** [binary-com/binary-bot#3558]
Hi @binary-ex-machina how can i identify a ranging market using technical analysis so that i can effectively trade ends in option in the binary bot

**Comment by hotmatrixx** [comment]
@[Bkind254](https://github.com/Bkind254)

You're asking the wrong person, really. We are here to help with 'how to code' the thing you want, once you know what you want.
You're not sure what technical analysis you even want to use, so it's far too early for any of us to begin to help you at this stage.

The bot has MACD, Bollinger Bands, RSI, SMA / EMA all built in, so if you can find your own strategy using one of those methods, maybe we can help you to turn the strategy into code>?

**Comment by Bkind254** [comment]
Wow Thank you very much for your response i dont know many people here thats why i targeted him,..am grateful you replied.

**Comment by Bkind254** [comment]
@hotmatrixx My strategy is,... applying the indicators required i need a bot that runs 'Ends in' when the market is slow or ranging. i'm sorry i dont know which is the best indicator to apply but from your experience you can advice me on that. For real, am not sure what technical analysis to apply coz i dont know how to identify a slow or a ranging market. This idea is great bro help me create it.

**Comment by binary-ex-machina** [comment]
@hotmatrixx maybe not that wrong, but you reply faster than me.

@Bkind254, when you use Ends In, are you referring to the Ends between 2 barriers. If that is the case, you must use the strategy close to the end of the trend. Using it in the middle of a ranging market will be riskier. Also, as hotmatrixx wrote, it will be better to know the filters (indicators, patterns) you will use in the strategy for the answer to be more concise. 

A straightforward way to determine the end of a trend is when the price crosses a simple moving average with 20 periods and keeps crossing the same moving average multiple times in a row. 

The image below shows that the price had a strong downward movement, and after the first cross on the SMA, it started to move inside a price range. Starting the trade at this moment will increase your rate of success. Of course, it's not a bulletproof strategy, but it's an easy way to identify. There are other indicators like RSI, Chopp indicator, ADX, and many others that can help you check the volatility and the market momentum

![image](https://user-images.githubusercontent.com/34610787/159175737-a3dc0df4-d349-4d76-a059-7edbf2c2e7d1.png)

**Comment by Bkind254** [comment]
@binary-ex-machina thanks alot for the information ,one question tho, When the ends in btw barrier strategy expires every 2 minutes, is it advisable i use the 2 minute chart only?

**Comment by binary-ex-machina** [comment]
@Bkind254 will be easier for you to analyze the market moment using the same time frame and duration. For example, you can analyze the 1min chart and use 5min expiration. 

You combine both numbers and use a higher duration that the time frame chart gives you extra time for possible earlier trades. Those trades you enter the market that is still trending and go sidelines sometime after., not affecting the trade result that much. 

You can sell the contract earlier if you enter the trade too late, so there are some options to use that trade type.

**Comment by Bkind254** [comment]
Thank you very much @binary-ex-machina .
