### ISSUE TITLE
Por favor, alguém me ajuda com o ERRO do desenvolvimento do meu bot

### ISSUE THREAD

**Issue by JoaoVitorpc2** [binary-com/binary-bot#3559]
Bom, o bot tem como estratégia Dígitos Superiores e Inferiores, contém previsões de 1 a 8, eu queria que ele definisse a previsão quando a porcentagem de ganho fosse maior que a de perda, 60 - 40 %. Eu coloquei pra definir no bloco 2, só que atrasa muito e acaba comprando com outro dígito ou quando é pra comprar superior, acaba comprando inferior, no bloco 4 a estratégia dá certo só que ele define a previsão somente 1 vez a cada entrada, eu queria que ele definisse a previsão de acordo com as porcentagens de previsão win e loss em tempo real. Ele até que define em tempo real só que define 1 vez por entrada, e o bot acaba ficando lento com a estratégia dessa forma. Queria que ele definisse mais rápido as previsões para o bot trabalhar melhor sem dar entradas falsas como citado no bloco 2

**Comment by JoaoLucas2020** [comment]
Olá , sou um jovem de 14 anos que estuda programação e trabalha com a binary

em primeiro lugar esse é o github da bot.binary.com , aqui é onde você pode fazer denúncias sobre problemas com a PLATAFORMA não sobre o seu bot , mas irei lhe ajudar com o seu bot

já considerou colocar a sua estratégia antes do bloco de compra? no bloco 1 mesmo

no bloco 1 ele faz a criação do contrato e no bloco 2 ele está fazendo a analise , o erro está no fato de que a analise é feita DEPOIS de criar o contrato e não antes

pra corrigir isso você pode colocar um bloco de repetição antes da criação do contrato (repetir se verdadeiro e na hora de comprar sair do loop) , assim o bot irá primeiro fazer a analise e depois criar um contrato de compra que faça sentido com o momento atual

Espero ter ajudado :p


[exemplo : ]
![image](https://user-images.githubusercontent.com/87786723/159132774-48026a73-e92c-42d2-bc4c-c811c6886943.png)

**Comment by JoaoVitorpc2** [comment]
Boa noite Lucas, ah sim achei que seria uma comunidade de ajuda sobre os bots aqui. Tentei aqui como você citou o código acima e não chegou a rodar, aí coloquei um loop um encaixado no outro com as funções { enquanto e até} e chegou a travar a binary, mas faz sentido do jeito que você falou, não teria como você fazer um vídeo codando e rodando o bot por gentileza ? Me ajudaria demais amigo, você não tem noção !

**Comment by JoaoVitorpc2** [comment]
Só que ao invés de você fazer no modo Difere, faria under e over pra entender melhor a lógica, por favor se não for pedir muito

**Comment by JoaoVitorpc2** [comment]
fui "fuçando" e deu certo aqui João Lucas, o Loop ele tem que ser até falso e executa após 1 segundo, obrigadão. Você citou que tem 14 anos né, tenho 18 cara sou novo também kkk, se quiser passar contato depois pra gente tá discutindo estratégias sobre a binary aí, será muito bom trocar uma idéia com quem entende bem das estratégias

**Comment by JoaoLucas2020** [comment]
eu não tenho muitos métodos pra contato , perdi meu celular recentemente porém tenho um discord , caso você queira me adicionar por lá PhoenixGD20#4776

e outra o bloco pra esperar depois de 1 segundo depende da volatilidade

basicamente casa esteja jogando em mercado normal deixa em 2 segundos
caso esteja jogando em mercado de segundo (exemplo : Volatility 10 (1s)) deixa em 1 segundo

é por que em mercado normal cada tick tem a duração de 1 segundo enquanto no mercado de (1s) cada tick tem a duração de 1 segundo

**Comment by JoaoVitorpc2** [comment]
Sim sim, te adicionei lá. É Juaum#7677, aí a gente vai conversando sobre nossas estratégias. Quanto mais amplo for o nosso conhecimento mais eu tenho certeza que a gente domina esse mercado.

**Comment by binary-ex-machina** [comment]
@JoaoVitorpc2 pode postar os problemas e as duvidas sobre os bots aqui que tem gente que ajuda. Aqui já foi um repositório apenas sobre os problemas dos bots, nos últimos anos é para qualquer coisa relacionada aos bots, estratégias, novas ideias, sugestões, etc.
