### ISSUE TITLE
BOT DIFERE

### ISSUE THREAD

**Issue by raphaelaugustoguimaraes** [binary-com/binary-bot#3560]
Olá meus amigos.

Estou com um bot que altera a previsão sempre que algum número chega a 0%, porém gostaria de ajustar para que ele faça apenas uma compra quando a previsão chegar a 0%, e depois só compre quando alterar a previsão. 

Conto com a colaboração de vocês.

Obg.

**Comment by binary-ex-machina** [comment]
posta o bot que talvez alguém ajude

**Comment by raphaelaugustoguimaraes** [comment]
> post o bot que talvez alguém ajude

Claro meu amigo, Estou fazendo isso agora. Se alguém puder ajudar, agradeço. 
[Digito Difere.zip](https://github.com/binary-com/binary-bot/files/8447452/Digito.Difere.zip)

**Comment by binary-ex-machina** [comment]
Na imagem abaixo você pode conferir como mudar o xml para atender ao que você precisa. Além dos blocos estão anotações importantes para entender a lógica da ideia e em caso de precisar alterar, já ter apontado quais blocos precisam ser trocados ou adicionados

![image](https://user-images.githubusercontent.com/34610787/162500169-84a8b9c8-d72e-43d4-b012-de6ed78c737a.png)

**Comment by raphaelaugustoguimaraes** [comment]
Boa noite meu amigo. Agradeço a ajuda. Mas acho que fiz algo errado. Pois após esses ajustes a previsão está está indo errada. Exemplo: Digito 7 fica em 0% ele compra diferente de 4 Exemplo. E mesmo após a vitoria, continua comprando, difere, depois de umas 3 compras ele muda.
