### ISSUE TITLE
Mostrarle al Bot La TENDENCIA

### ISSUE THREAD

**Issue by Masapostol** [binary-com/binary-bot#3561]
por favor alguien podría ayudarme, necesito indicarle al bot que tendencia es la predominante, y si es por medio de un indicador como decirle cual es la primera vela que da esa tendencia.

@ex-machina

**Comment by binary-ex-machina** [comment]
You can use the moving average to see the trend at the moment of checking. You can check if the candle crossed the moving average to get the first candle of that trend. Remember that the trend can change in 2-3 candles or 100-150 candles. Check the image below to know how to make the check with the candle and the moving average

![image](https://user-images.githubusercontent.com/34610787/161863779-7df10aab-6ead-4707-a001-e6c58ce6c660.png)
