### ISSUE TITLE
Bot modification

### ISSUE THREAD

**Issue by osmosis221** [binary-com/binary-bot#3564]
Thank you so much for your invaluable contribute on dalembert predifined codes on here. Appreciate

But pls, the purchase condition only buy. Please can help edit the bot XML dalembert predifined to be buying and selling?

![Screenshot_2022-04-01-15-08-17-590_com android chrome](https://user-images.githubusercontent.com/102663556/161280427-aa2fef61-2a1e-4e41-8581-51b0f307b648.jpg)

**Comment by binary-ex-machina** [comment]
The Quick strategies have only money management and risk management. You need to create all the logic in purchasing the contract (if it's rise or fall, when it must be done, etc.)
