### ISSUE TITLE
Digit trading

### ISSUE THREAD

**Issue by khan1313** [binary-com/binary-bot#3568]
@lipika-deriv @khalid-deriv what is digit trading. And how we read digits statistics. Why its going up suddenly and why its going down suddenly?? Can you explain it

**Comment by binary-ex-machina** [comment]
Digits are randomly generated. Any number has the same % to come next

**Comment by khan1313** [comment]
> Digits are randomly generated. Any number has the same % to come next

Sir can you give me your telegram contact id. I want to talk with you
