### ISSUE TITLE
Bot Delay...

### ISSUE THREAD

**Issue by oespiao** [binary-com/binary-bot#3571]
Gostaria de saber se é normal o delay no bot, ou se foi a forma como programei...
Ex: bot q analisa 3 ultimos digitos se forem iguais, negocie este digitio no difere..
Pela auditoria tenho visto q sempre pula 1 ticktac...
![image](https://user-images.githubusercontent.com/31420501/162263241-99ae511c-4054-42f5-b2e3-976091795968.png)

Conforme a imagem eu encontrei 3 digitos "6", porem ele comprou no ticktack posterior...

**Comment by alex-net007** [comment]
É normal! ele entra na operação com o tik e você escolheu e finaliza no tik seguinte!

**Comment by oespiao** [comment]
> É normal! ele entra na operação com o tik que você escolheu e finaliza no tik seguinte! No caso o primeiro tik é o de entrada, você tem que ter sua estratégia baseada 2 tik's a frente! Deu pra entender!?

Ola Alex, obrigado pelo retorno, mas consegui alterando a logica operar no digito seguinte à minha análise.
