### ISSUE TITLE
Script for mt5 deriv

### ISSUE THREAD

**Issue by martinrf79** [binary-com/binary-bot#3574]
Hello how are you. I would like to know if someone can help me, what I need is an mt5 script that measures the distance from the opening to the maximum and the opening to the minimum of a candle. If someone can help me, you can send me info here or to martinrf79@gmail.com Greetings to all

**Comment by binary-ex-machina** [comment]
You can take the difference from the open price to the minimum price of the candle and the difference from the open price to the maximum value of the candle, like this image below

![image](https://user-images.githubusercontent.com/34610787/162784067-a345d391-d36b-435f-a948-f7d1756bbb42.png)

**Comment by lucky4911** [comment]
> You can take the difference from the open price to the minimum price of the candle and the difference from the open price to the maximum value of the candle, like this image below
> 
> ![image](https://user-images.githubusercontent.com/34610787/162784067-a345d391-d36b-435f-a948-f7d1756bbb42.png)

Sir please my issue response please sir i m waiting sir
