### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ramazan5551** [binary-com/binary-bot#359]
You want to create a robot

**Comment by okovalov** [comment]
well, I guess 
![image](https://user-images.githubusercontent.com/1706749/28971582-7691af00-78fa-11e7-9470-7b8c63b81091.png)

**Comment by Fruitfella** [comment]
![lol](https://user-images.githubusercontent.com/26277327/28971732-3a896d4c-7957-11e7-99f8-34af8ca9b990.gif)
Okay, thats funny :rofl:
