### ISSUE TITLE
Get specified position of a list

### ISSUE THREAD

**Issue by excepticons** [binary-com/binary-bot#360]
Hi.
I have a list with 10 items. Each item in the list is the number of times a digit was the last digit.
For example: MyList = 21, 34, 44, 11, 3, 86, 34, 25, 99, 345
Each position represents the digits 0, 1, 2, 3, 4, 5, 6, 7, 8. 9.
Then:
Digit 0 was 21 times the last digit.
Digit 1 was 34 times the last digit.
Digit 2 was 44 times the last digit.
Digit 3 was 11 times the last digit.
and so on.

I want to get the position of the min or the max in list. I mean, in the above example list, I want to know that position 5 is the min value and for such, the digit 4 is the digit that has come out the least.

How can I get positions using the counters on list?

Thanks.

Gustavo

**Comment by Fruitfella** [comment]
#223 :)

**Comment by excepticons** [comment]
Thank you.

**Comment by okovalov** [comment]
:)
