### ISSUE TITLE
Variable with value NaN

### ISSUE THREAD

**Issue by excepticons** [binary-com/binary-bot#361]
Hi.
For some reason, after several minutes, a variable for counting purposes, reach a value NaN.
What means?

Thank you.

Gustavo B.

**Comment by Fruitfella** [comment]
maybe thats bc the value of that var isnt recognized or null (empty)

**Comment by excepticons** [comment]
Thanks, @Fruitfella 
My variable is a counter, and after some ticks, has a normal integer value (1, 5, etc.) but later (after other some ticks) has NaN value. I don't know why. Other counter variables has a proper integer value.
Please, anyone have an idea?
Thanks.

**Comment by Fruitfella** [comment]
Its too hard for me to find the problem without seeing the bot, 😛

**Comment by excepticons** [comment]
Ok. I'll try to show some images for supporting my issue.

Image 1 and 2 shows my trade definition and variables that will be used. You can view ConteoDeDigito0 to ConteoDeDigito9 vars. Ten vars for counting Last Digit of each tick. Also, a list ListaOcurrencias to have stored the occurrences of the last digit.
For every tick, I'm counting the occurrence on each variable and set the value on the position list.

Image 3 shows that the counter on position 1 of list is normal. 
Image 4 shows that the counter on position 1 has a value of Nan.
Image 5 shows that the bot runs continuously, counting for others digits, without errors.


![part1](https://user-images.githubusercontent.com/15220791/28999483-130b3cd4-7a0e-11e7-9458-a970a2bfa972.PNG)

![part2](https://user-images.githubusercontent.com/15220791/28999485-17d4b3b2-7a0e-11e7-94a0-4fd9a3ac5fc9.PNG)


![runcounter1](https://user-images.githubusercontent.com/15220791/28999487-1ce09ae2-7a0e-11e7-81f1-600e73847ff7.PNG)

![runcounter2](https://user-images.githubusercontent.com/15220791/28999489-21bc9c6e-7a0e-11e7-9314-b04e7225c73d.PNG)

![runcounter3](https://user-images.githubusercontent.com/15220791/28999492-255d1eac-7a0e-11e7-92c3-eb2e2dc4036a.PNG)

**Comment by Fruitfella** [comment]
I dont know the problem of your bot, amigo. but i think i know what you are trying to get from it.
why dont you try this?
![capture](https://user-images.githubusercontent.com/26277327/28999691-642a1f78-7a7b-11e7-87de-30453003675e.png)

**Comment by Fruitfella** [comment]
sorry, i forgot the **`CandidadMuestra`**
![capture](https://user-images.githubusercontent.com/26277327/28999714-8cc04a7e-7a7c-11e7-937b-14f49001e6ef.png)

**Comment by excepticons** [comment]
Hi @Fruitfella 
Thanks. I'll try it right now.

**Comment by excepticons** [comment]
Works fine!
Thanks @Fruitfella

**Comment by Fruitfella** [comment]
:)

**Comment by Fruitfella** [comment]
:) dont forget to close this issue since its already solved
