### ISSUE TITLE
Need to add all the values

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#363]
HI Everyone,

Need help with adding values. 
Like in Volatility index 50 current price is  400.6789 
So I need to read how many digits are there first, here its total 7.
Then I want to add all the values.
4+0+0+6+7+8+9 = ?
Like this...

![image](https://user-images.githubusercontent.com/20506657/28995088-fcdae946-79d6-11e7-8d8e-87b69b30892e.png)

I tried But its not working and I dont know how to find how many digits are there in first place....

**Comment by Fruitfella** [comment]
@sarderiftekhar 
![capture](https://user-images.githubusercontent.com/26277327/28995378-fc5d42da-7a11-11e7-9350-6f0389e49b35.png)

**Comment by sarderiftekhar** [comment]
HI Fruitfella Thank you. But I am getting this error

![image](https://user-images.githubusercontent.com/20506657/28995726-bf3b9a92-79e8-11e7-90c1-50757ec14d57.png)

Can you upload your code as .txt file i will convert it ...to see what mistake I made...

**Comment by Fruitfella** [comment]
your mistake is that `create text with` block, you put it wrong.
look at my picture again and see the different

**Comment by sarderiftekhar** [comment]
HI Fruitfella Thank you. Its working...but looks like my strategy is not good......not going well..
