### ISSUE TITLE
Binary Higher/Lower bot

### ISSUE THREAD

**Issue by wizcharming** [binary-com/binary-bot#3646]
Hi please help me create a bot with a barrier of +0.9999 on Bear Market with 5ticks
and make it trade lower when the last four digits below 3000 ( eg: 958."1780" , 957."2368")
Please i'd really appreciate it 

@lasaidhari
@binary-ex-machina
@Hooponopono
@hotmatrixx
@AlienFly
@baruga
@Eshhh
@aaimio

**Comment by saidforex26** [comment]
https://youtu.be/n2V_ZK3Ol00

**Comment by wizcharming** [comment]
thanks allot

**Comment by wizcharming** [comment]
please can i get the xml file instead im not so good with creating bots

**Comment by saidforex26** [comment]
[the last four digits below 3000 xml.zip](https://github.com/binary-com/binary-bot/files/8916568/the.last.four.digits.below.3000.xml.zip)

**Comment by wizcharming** [comment]
i tried uploading it to binary and deriv but it kept giving an error ive unzipped it and added the xml extension

**Comment by saidforex26** [comment]
bot hanya bisa dibuka di http://botstudio.online/

**Comment by wizcharming** [comment]
i cant login or link my api to the site it redirects me to deriv instead

**Comment by saidforex26** [comment]
login botstudio.online and run bot https://youtu.be/PpgQtgRFqZM

**Comment by wizcharming** [comment]
thank you
