### ISSUE TITLE
Set Stake with a real account with BTC

### ISSUE THREAD

**Issue by excepticons** [binary-com/binary-bot#365]
Hi.
I have BTC on my real account.
Please, how can I set Stake with BTC and not USD in my Bot, when I run it with my real account in BTC?
Thanks.

Gustavo

**Comment by excepticons** [comment]
Please, I get an error message that USD is not default currency, but my currency account is BTC.

**Comment by aminmarashi** [comment]
We will add BTC support when #346 is merged. Possibly today or tomorrow.

**Comment by aminmarashi** [comment]
You can now select BTC. Let me know if you faced any problem

**Comment by excepticons** [comment]
Thank you @aminmarashi !
