### ISSUE TITLE
My BOT stops

### ISSUE THREAD

**Issue by excepticons** [binary-com/binary-bot#366]
Hi.
My Bot runs continuously on virtual account but stops at the end of first trade when I use the same Bot on my real account.
I have a "if..do..else" on block "Get your trade result and trade again" and both in "if" and in "else" there is a "Trade again".
Please, where can I check why?
Thanks.

![image](https://user-images.githubusercontent.com/15220791/29010933-be5578a2-7af4-11e7-93ee-6f01896b3dc3.png)

**Comment by excepticons** [comment]
I think there was an error message similar to "substractFixed not defined".
I cant take it exactly.
Thanks.

**Comment by Fruitfella** [comment]
that **`MaxStatsIdx`** is kovalov's ?
that **`MiUltimoDigito`** is your Last Digit Prediction right?

are you sure what you want is not this..?
![capture](https://user-images.githubusercontent.com/26277327/29011166-2d49bf32-7b5b-11e7-98d8-aea51a51f0fe.png)
Im pretty sure that you dont need _if Result is Win_ since you put same blocks on both _do_ and _else_

**Comment by excepticons** [comment]
Hi Fruitfella.
I want to set the value of MaxStatsIdx to MiUltimoDigito.
The block Set on my image does not mean "Set the value of MaxStatsIdx to variable MiUltimoDigito" ?

**Comment by excepticons** [comment]
Ok, Ok. My mistake.
Thank you again, Fruitfella.
I will close this issue.

**Comment by Fruitfella** [comment]
:)

**Comment by excepticons** [comment]
I already corrected my BOT, but I still getting the error message on first trade and BOT stop:

![image](https://user-images.githubusercontent.com/15220791/29011643-54a2a276-7afa-11e7-9c3d-377442b273f1.png)

**Comment by Fruitfella** [comment]
I assume you use kovalov's functions..
have you load all the functions needed?
have you put the needed function blocks to its place?
![capture](https://user-images.githubusercontent.com/26277327/29012003-1aef2046-7b62-11e7-816d-b62508b2f485.png)

**Comment by mnaseem01** [comment]
Hi all.
I have also the same error. 
![image](https://user-images.githubusercontent.com/13481811/29012040-62a59d5c-7b49-11e7-98a1-74eaf32fad48.png)

**Comment by okovalov** [comment]
looks like people got really confused how to load all those dependencies... thinking on how to put it all together in one block pr smth like that..

**Comment by Fruitfella** [comment]
I think "not defined" error is caused by some variables that you havent define its type yet, and you put into that variable, value that isnt number or string. usually its list value.
Its hard for me to find the exact problem that cause that to your bot without seeing the whole bot.

**Comment by aminmarashi** [comment]
@excepticons  and @mnaseem01 This is a bug we're trying to fix. Sorry for the inconvenience.

**Comment by aminmarashi** [comment]
@excepticons Thanks to your fast report, we were able to fix it.

**Comment by Penjahat1** [comment]
I got the same notification. "SubtractFixed is not defined".
The martigale in my bot would not run. It was fine last week.
Was there an update in binary system today?

**Comment by aminmarashi** [comment]
@Penjahat1 Yes, it was a bug that we solved, could you please try again?

**Comment by mikesettecasse** [comment]
hi guys? do you have a guide to program a bot? please
