### ISSUE TITLE
Sma crossover  simultaneous  with new candle

### ISSUE THREAD

**Issue by anjorinyinka** [binary-com/binary-bot#3682]
Hello..
Really need help writing this binary bot.its a touch/no touch bot that is based on the crossover of the 5 and 20 sma. A cross downwards triggers a downwards touch trade and vice-versa.I can  work on the sma crossovers very well. However, i would like that a trade is initiated ONLY  when a crossover happens simultaneously with the opening of a new candle. That is crossovers on an already existing candle is ignored except it happen at the same time a new candle is formed/opened.

Been having problems on this for the past two weeks.
Would really appreciate a bit of help here guys..

**Comment by anjorinyinka** [comment]
@derivmaster ...thank you so much..i cant appreciate u enough....u av made my day...

**Comment by basa07** [comment]
Can you help me create a Digits bot over under the last number?
You open trades in a demo account, and after one or two or three consecutive losses, you open a real deal in a real account
The matingal can be split
Split the martingale into 2, 3 or 4
