### ISSUE TITLE
Blank Log

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#369]
something happen to the log @aminmarashi 
its blank now. doesnt record anything.
it was fine this morning (its noon now in my place)
![capture](https://user-images.githubusercontent.com/26277327/29013596-273d51ae-7b6e-11e7-9b98-cb0bcce29dda.png)

**Comment by aminmarashi** [comment]
Thanks @Fruitfella, result of reckless releasing, could you please check again? should be fixed.

**Comment by Fruitfella** [comment]
Its good now 👍 
![capture](https://user-images.githubusercontent.com/26277327/29013661-a58dacca-7b6e-11e7-83ab-0f006a1d4a3f.png)
