### ISSUE TITLE
Something wrong...

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#370]
another error occurred @aminmarashi 
i've been using my martingale for weeks, it was fine this mornin.
now, it doenst reset anymore after win, some variable lost it value and become "NaN" and it trigger stoploss even though its not even loss.
![capture](https://user-images.githubusercontent.com/26277327/29014314-9a4575ec-7b72-11e7-8496-add8d5b5b298.png)

**Comment by aminmarashi** [comment]
@Fruitfella Really sorry for the inconvenience and many thanks for your patience and help. This issue is with the contract details block. I'll fix it asap.

**Comment by aminmarashi** [comment]
@Fruitfella should be fixed, thanks again.

**Comment by Fruitfella** [comment]
Yup, fixed 👍 
Btw @aminmarashi 
i think its better if you do these updates like you did in the past, update on the beta first before update the official. this is to avoid the user lost money because of errors like this (if they use real account after some untested updates which they might not know)
official update should be done at least 24h after the beta update, or maybe 3days for some major updates.

this way, we can use the beta to test both our strategies (bots) and the beta itself while those who want to run their bots with real account can do that on official without worry an error like this would happen and cause some loss.

also, make a notice (list?) in the beta for some new updates that arent applied on the official yet so that we can always know the different. this notice will disappear when the updates are done on the official.

well, just a suggestion. :)

thanks
