### ISSUE TITLE
Como criar um bot que só opera na conta real após ter 'x' quantidade de loss na virtual...

### ISSUE THREAD

**Issue by Vcarneiro2** [binary-com/binary-bot#3703]
![image](https://user-images.githubusercontent.com/107152523/182153851-f096c092-4dd8-42de-9af6-205a1278b21c.png)

Como consigo criar um bot ( como imagem anexa ) com a opção de alternar entre conta real e virtual em um mesmo bot ?

**Comment by derivmaster** [comment]
Hello my friend @Vcarneiro2 this is a advanced virtual loss/win changer only available in BINARYTOOLS.IO

![image](https://user-images.githubusercontent.com/107600731/182666019-d392c173-fcf7-45d1-b311-f166659ba142.png)

You need to put the conditions to Main Account & Virtual Account
- In the example bot the condition is the pattern WL for MAIN ACCOUNT
- and to return to VIRTUAL ACCOUNT after 3 Win operation

Example operations : 

![image](https://user-images.githubusercontent.com/107600731/182666787-8a3db3ed-89b0-4750-aa04-ff05fb247f7c.png)

[Virtual Loss_Win Changer v1.0 by binarytools.io.zip](https://github.com/binary-com/binary-bot/files/9253593/Virtual.Loss_Win.Changer.v1.0.by.binarytools.io.zip)


Remember RUN the bot here 👉🏻 BOT.BINARYTOOLS.IO 

For more questions & tutorial about Virtual Hook visit the community
Official Community portuguese telegram : neuronaltrader_portugues

![image](https://user-images.githubusercontent.com/107600731/181341186-5beadf41-2e08-4a92-b224-68d821e0669e.png)

**Comment by Vcarneiro2** [comment]
Olá @derivmaster , valeu pelo retorno. 
Gratidao.
Seguirei suas sugestões, inclusive já entrei no telegran.
