### ISSUE TITLE
virtual hook binary bot 

### ISSUE THREAD

**Issue by precious2818** [binary-com/binary-bot#3737]
How i can define a virtual Hook counting .
In virtual Hook
If
WIN ,WIN ON VITUAL HOOK THEN CHANGE TO REAL ACCOUNT ON THIRD TRADE UNTIL THERE IS A LOSS THEN CHANGE TO VITUAL HOOK TILL WIN,WIN AGAIN
AND I'M MAKING USE OF AN OSCAR GRIND STRATEGY FOR MONEY MANAGEMENT
Do you have any knowledge about it
@binary-ex-machina
Give me image of text file i need guidance to create it please

**Comment by derivmaster** [comment]
good day friend @precious2818 , i can help you send the bot to configure the virtual hook 


For more questions & tutorial 
Official english Community telegram : neuronaltrader_community

![image](https://user-images.githubusercontent.com/107600731/181341186-5beadf41-2e08-4a92-b224-68d821e0669e.png)

**Comment by precious2818** [comment]
Please how can I send the file here.

**Comment by binary-ex-machina** [comment]
@precious2818 feels free to use the virtual hook with 0 configurations at https://binaryblocks.pro/

**Comment by precious2818** [comment]
How can I be able to make use of it please and create the following coding

**Comment by precious2818** [comment]
Can you send me a screenshot or link to a video

**Comment by precious2818** [comment]
How i can define a virtual Hook counting .
In virtual Hook
If
LOSS,LOSS LOSS is greater then 3  until there is a win on the virtual then
open real trade  till profit of 2$ is reached
Is it possible to create it
Do you have any knowledge about it
@binary-ex-machina
Give me image of text file i need guidance to create it please
