### ISSUE TITLE
two bots in one

### ISSUE THREAD

**Issue by cisbinary** [binary-com/binary-bot#3752]
is it possible to build two bots that run at the same time?

**Comment by binary-ex-machina** [comment]
You can run one script on the page but open multiple pages in your browser. But, of course, all that depends on your computer power to run both scripts. Since the page requires some good ram memory, you will have difficulty running with slow computers (at least with low ram memory).

**Comment by cisbinary** [comment]
Right, noted. What is the setup for a split martingale function?

**Comment by saidforex26** [comment]
this can only be done at botstudio.online. without having to open multiple tabs. you can make bot as you want. can do multi index and multi type contract in one xml file . example https://www.youtube.com/watch?v=WGyDw6wgIp0
