### ISSUE TITLE
Help in making new bot

### ISSUE THREAD

**Issue by cisbinary** [binary-com/binary-bot#3759]
Someone help me make a match digit bot
-The bot will only start to trade "matches" if digit 3 has failed to appear in the last 11 times in a row.
-Martingale factor 1.2
-Duration 1tick
-Prediction 3

**Comment by cisbinary** [comment]
@derivmaster

**Comment by cisbinary** [comment]
@binary-ex-machina

**Comment by binary-ex-machina** [comment]
@cisbinary, you can do like this image below. It will check the number of digits you select in the Trade Definitions block. Change the martingale parameters as you need

download [this](https://github.com/binary-com/binary-bot/files/9992760/matches.json.zip) file, unzip and run it [here](https://binaryblocks.pro/) 

![image](https://user-images.githubusercontent.com/34610787/201412004-0b084656-491f-4cd6-a0df-52987e5d9f37.png)

**Comment by cisbinary** [comment]
done
