### ISSUE TITLE
Bot strategy 

### ISSUE THREAD

**Issue by Alkalineboom** [binary-com/binary-bot#3760]
Help me create a bot with this strategy,,, when the stochastic indicator level is greater than 95 we buy a rise trade and if its less than 5 a fall trade ( period K(14) D (1) applied to close
![Screenshot_20221111-211233_Telegram](https://user-images.githubusercontent.com/110045302/201402927-3337129e-273d-48ec-bd6f-123797c865d9.jpg)

**Comment by binary-ex-machina** [comment]
You can do it like the image below. On each tick, it will check if the stochastic K is above 95 or below 5. I have added martingale and risk management, changing as you need

Download [this](https://github.com/binary-com/binary-bot/files/9993783/stoch.json.zip) file, unzip and use it [here](https://binaryblocks.pro/) at **binaryblocks.pro**

![image](https://user-images.githubusercontent.com/34610787/201448709-5d73ee01-a587-47fd-ba86-a0eddc739ee9.png)

**Comment by Alkalineboom** [comment]
Thanks alot
