### ISSUE TITLE
How to code

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#377]
![image](https://user-images.githubusercontent.com/20506657/29174361-f9168990-7ddd-11e7-9897-4cc127e09d90.png)

How do I calculate the difference between the total win and loss.  This is for an Odd Even bot.
So My plan is to change the setting to opposite direction if its loosing too many times...like the difference is more than 5, then switch odd to even and even to odd.

![image](https://user-images.githubusercontent.com/20506657/29174578-9c3528c0-7dde-11e7-99ff-003df156efcf.png)

**Comment by sarderiftekhar** [comment]
![image](https://user-images.githubusercontent.com/20506657/29174684-ee568324-7dde-11e7-8d65-6e27f98117a3.png)

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/29175427-3d1ba60e-7e13-11e7-90f6-20777d684e65.png)

**Comment by Fruitfella** [comment]
btw, its a bad idea to reverse your strategy.
if your strategy give you too many losses, its better to check what is wrong with the strategy and revise it, or you can just change your strategy with the new one.

**Comment by sarderiftekhar** [comment]
I am increasing the stake each time by 0.50 on every win or loss. So if starts loosing too many times, then I manually switch to opposite, and works good...lets see. thanks @Fruitfella
