### ISSUE TITLE
Reset Martingale

### ISSUE THREAD

**Issue by juliosilva10** [binary-com/binary-bot#3771]
Hello guys. I need to use martingale on odd inputs and reset martingale on even inputs. Can you help me?
The loss is working normally.

![image](https://user-images.githubusercontent.com/43079210/205513126-2814ac8a-6ff8-49ed-9ba4-400900f0ac79.png)

![image](https://user-images.githubusercontent.com/43079210/205513466-389f0fa6-c212-44a9-bd92-7f56000823f2.png)

![image](https://user-images.githubusercontent.com/43079210/205513300-4982a715-ae65-4537-af61-576b1a732fb6.png)

**Comment by derivmaster** [comment]
Hello friend @juliosilva10  , please send the bot , i can help you with that


For more questions & tutorial 
Official english Community telegram : [neuronaltrader_community](https://t.me/neuronaltrader_community)


![image](https://user-images.githubusercontent.com/107600731/181342346-a9c57038-9399-4481-aa5f-bde8240424b3.png)

**Comment by juliosilva10** [comment]
Hello, friend derivmaster.

[Teste Differs.zip](https://github.com/binary-com/binary-bot/files/10179878/Teste.Differs.zip)

**Comment by derivmaster** [comment]
friend @juliosilva10 the bot is done  , with money management and compound reset

![image](https://user-images.githubusercontent.com/107600731/206868391-f83ac35a-e776-4969-b445-ddc2ad4a704b.png)

[Difigt Diff Compound by binarytools.io.zip](https://github.com/binary-com/binary-bot/files/10200631/Difigt.Diff.Compound.by.binarytools.io.zip)


Remember RUN the bot here 👉🏻 [BOT.BINARYTOOLS.IO](https://bot.binarytools.io/platform)

For more questions & tutorial 
Official english Community telegram : [neuronaltrader_community](https://t.me/neuronaltrader_community)


![image](https://user-images.githubusercontent.com/107600731/181342346-a9c57038-9399-4481-aa5f-bde8240424b3.png)
