### ISSUE TITLE
Take profit 

### ISSUE THREAD

**Issue by Felixowe** [binary-com/binary-bot#3774]
I need help adding take profit to a bot i been using to trade which is highly efficient, any help I'd get I'd be grateful

**Comment by bobmeg** [comment]
How can we help..you have not posted the bot..??

**Comment by Felixowe** [comment]
Did you get it?

**Comment by Felixowe** [comment]
I don't know why i can't post it here though

**Comment by Felixowe** [comment]
How can i send it here, through mail is it okay?

**Comment by Felixowe** [comment]
[Uploading Triple Av75.xml…]()

**Comment by Felixowe** [comment]
Duplicate of #

**Comment by Azinth** [comment]
I would like to know either. The bot I'm talking is in that link:

[](https://github.com/binary-com/binary-bot/files/6728027/masaniello.money.management.xml.zip)
