### ISSUE TITLE
How does MACD block work? /doesn't give the right values?

### ISSUE THREAD

**Issue by wannesc** [binary-com/binary-bot#381]
Hello,

How does the MACD block work? I put it in my code like this:
![image](https://user-images.githubusercontent.com/31114276/29436649-dfe6a91c-83ac-11e7-997e-ae9a1f269dae.png)

Maybe I do something wrong but it doesn't give the same values as the MACD indicator on the chart. Not for the histogram, MACD line or the signal line.
I've tried the following:
Change the market
Change the default candle time
Stop using default candle time and put in the time manually
Changed from # from end to # (with # from end negative numbers also give a solution???)
I made the list beforehand and put it in input list in a second phase.
,,,

I'm out of ideas. Is there anyone who knows why I don't get the right values?

Kind regards
Wannes

**Comment by Kmitka** [comment]
I have been testing MACD algorithms today, and have similar, but different problem. The MACD Signal is corelating with bot's chart, but not relevant to any type of MCDA Signal on trading chart (on binary.com main trading page). TEMA type of MA Signal gives the closest (but not identical) values, and none of the rest (SMA, EMA, WMA, TRIMA) gives actual value from the bot's chart.
The MACD parameter shows exact values, though.

Does bot work on different implementation than the trading page?

PS. @wannesc  - your block looks like mine - should work, at least for the bot's chart. Which chart do you use?

**Comment by Kmitka** [comment]
![mcda signal fail](https://user-images.githubusercontent.com/31114851/29438549-bd136b7c-83b7-11e7-87f4-d9562dfdf2ce.jpg)
Pictured are bot's chart (left) and trading chart (right). Red line shows SMA type of MACD Signal for trading chart and default type on bot's chart (there is "SMA" type claimed in the array block too), You can see the difference, while MACD (green line) values are corelating.

**Comment by wannesc** [comment]
Indeed, the MACD values (histogram, MACD line and signal line) are equal to the values in bot chart but not in the trading chart. They also don't correlate. They are miles apart.

So I think the code behind the MACD block isn't correct. The values on the bot chart probably use the same code. (as you can only add the indicators which are possible to calculate in the bot)

**Comment by Kmitka** [comment]
For me MACD (green line) matches exactly. (Next popup notification shows exact value as in trade chart).

**Comment by wannesc** [comment]
made another check on the trade chart:
![image](https://user-images.githubusercontent.com/31114276/29478731-ae19f23c-846e-11e7-900b-eca0a9a26540.png)
The MACD line should be EMA12 - EMA26. As shown on the picture this should be 18297, 7962 - 18226,1174 = 71,6788. Instead the MACD indicator gives a MACD line of 53,6452

What am i missing?

**Comment by wannesc** [comment]
OK, found it. The standard settings for MACD in the trade chart are with the SMA lines, while MACD normally is with the EMA. If I Change them correctly (MACD with EMA with EMA lines and MACD with SMA with SMA lines) the values match.

I will have to take a look if this fixes my problem in the first post.

**Comment by Kmitka** [comment]
But it doesn't fix mine, where SMA itself is calculated differently from one chart to the other..

**Comment by aminmarashi** [comment]
The charts in `binary bot` and `webtrader`/`binary.com` are not compatible. If you want an advanced chart, feel free to use the built-in `trading view` chart.
<img width="983" alt="screen shot 2017-08-22 at 10 13 45 am" src="https://user-images.githubusercontent.com/6560964/29545755-ab56eb02-8722-11e7-8978-ae7717a64f3d.png">

**Comment by Kmitka** [comment]
Thank you @aminmarashi for the advice, I also have noticed that tradingview is a good option. 
But I still can't understand what does it mean "not compatible", since the indicators are simple mathematic calculations depending on historical saved values. 
Isn't always 2+2=4?

**Comment by aminmarashi** [comment]
There can be a variety of the implementations for each indicator, which can be slightly different. So depending on which MACD implementation you're using your results may vary. In Binary Bot we make sure the indicators we have in the charts and in the blocks are completely compatible with each other. So It's safe to use them interchangeably.
