### ISSUE TITLE
@derivmaster

### ISSUE THREAD

**Issue by cisbinary** [binary-com/binary-bot#3822]
Are the last four consecutive digits either odd or even? If true, let the bot initiate a trade (either odd or even based on last digit analysis)  till it wins. After winning it goes back to analysis.

**Comment by derivmaster** [comment]
Hey friend @cisbinary  this is the bot EVEN/ODD COUNTER with risk management

![image](https://user-images.githubusercontent.com/107600731/218619653-c7b6f6c5-a0fe-47f8-bd35-4af5fbc27a74.png)


[EVEN_ODD COUNTER by binarytools.io.zip](https://github.com/binary-com/binary-bot/files/10727943/EVEN_ODD.COUNTER.by.binarytools.io.zip)


Remember RUN the bot here 👉🏻 [BOT.BINARYTOOLS.IO ](https://bot.binarytools.io/platform)

For more questions & tutorial 
Official english Community telegram : [neuronaltrader_community](https://t.me/neuronaltrader_community)

**Comment by cisbinary** [comment]
hello friend @derivmaster ,any reason why the bot isn't opening any trades?

**Comment by derivmaster** [comment]
friend @cisbinary , please send photo to see or video
