### ISSUE TITLE
Bull Market Reading Digits

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#384]
HI I am having difficulty reading Bull market digits. Its not reading correctly.

I need to read this

![bul--option1](https://user-images.githubusercontent.com/20506657/29564680-bfac59b2-873a-11e7-9762-2588afb02a94.png)

Code I Used:

![bull market](https://user-images.githubusercontent.com/20506657/29564692-c6ce6a14-873a-11e7-9a00-f1cc395b31f1.png)

But not reading properly 

![not reading properly](https://user-images.githubusercontent.com/20506657/29564729-ef4c6586-873a-11e7-8c39-feabacf0a0e6.png)

**Comment by Fruitfella** [comment]
change your **`round`** block into **`round down`**

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/29565770-7c7a7ebc-8771-11e7-9b62-f8d1c019ecce.png)

**Comment by sarderiftekhar** [comment]
Thanks Fruitfella .........great

**Comment by tadeu66** [comment]
alguem tem a formula do Digits Corresponde Estratégia no Market Bull Index Binary.com
