### ISSUE TITLE
Over digit bot

### ISSUE THREAD

**Issue by jkm-github** [binary-com/binary-bot#3873]
Hi I am creating a bot for digit over and I want it to find the probability of the last 25 Ticks and then buy over if there is a probability of that particular number is over 75%

**Comment by Andres-Guarin** [comment]
open the bots xml here: https://bot.binarytools.io/platform
-the bot includes the Virtual Hook to do virtual operations if you want (virtual loss, virtual win) is disabled ✅
includes smart risk library martingale split mode ✅
includes the digitats library to perform the analysis of percentage digits ✅

![image](https://user-images.githubusercontent.com/131272671/234706245-c6203a3d-8600-4b91-bf7f-618a0f5ec64e.png)
![image](https://user-images.githubusercontent.com/131272671/234706489-7b1611a6-572a-48ed-ba68-cec814f766c1.png)
![image](https://user-images.githubusercontent.com/131272671/234707397-f55a38a9-99f4-469e-ab16-a83ddc678ce6.png)
![image](https://user-images.githubusercontent.com/131272671/234708137-a9a8f4ad-568f-4d2a-8a25-22189d0fee20.png)

We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_community
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣

👇👇DOWNLOAD THE BOT FREE HERE 👇👇
[digitstats.zip](https://github.com/binary-com/binary-bot/files/11337494/digitstats.zip)

**Comment by jkm-github** [comment]
I can't seem to be able to join the group

**Comment by jkm-github** [comment]
I can't seem to be able to join the group 

> open the bots xml here: https://bot.binarytools.io/platform -the bot includes the Virtual Hook to do virtual operations if you want (virtual loss, virtual win) is disabled ✅ includes smart risk library martingale split mode ✅ includes the digitats library to perform the analysis of percentage digits ✅
> 
> ![image](https://user-images.githubusercontent.com/131272671/234706245-c6203a3d-8600-4b91-bf7f-618a0f5ec64e.png) ![image](https://user-images.githubusercontent.com/131272671/234706489-7b1611a6-572a-48ed-ba68-cec814f766c1.png) ![image](https://user-images.githubusercontent.com/131272671/234707397-f55a38a9-99f4-469e-ab16-a83ddc678ce6.png) ![image](https://user-images.githubusercontent.com/131272671/234708137-a9a8f4ad-568f-4d2a-8a25-22189d0fee20.png)
> 
> We remind you that Neuronal Trader only has 3 groups:
> 
> ✅ (SPANISH GROUP) https://t.me/neuronaltrader_community ✅ (ENGLISH GROUP) https://t.me/neuronaltrader_community ✅ (PORTUGUESE GROUP) https://t.me/neuronaltrader_portugues
> 
> and there is only one channel for informational purposes:
> 
> 👉(THE ONLY NEURONAL TRADER CHANNEL)👈 https://t.me/neuronaltrader
> 
> 🔉🔊❕These are the official Neuronal Trader communities❕📢📣
> 
> 👇👇DOWNLOAD THE BOT FREE HERE 👇👇 [digitstats.zip](https://github.com/binary-com/binary-bot/files/11337494/digitstats.zip)

I can't join the telegram group

**Comment by jkm-github** [comment]
And are there like any English video tutorials or something?

**Comment by Andres-Guarin** [comment]
> And are there like any English video tutorials or something?

Tutorials but in Spanish, you can use subtitles

DIGITSTATS/DIGITS Library 👇

 Part 1: https://youtu.be/QpLMM_8l9t4
 Part 2: https://youtu.be/wFksxfXrfRw

 DIGITSTATS complement:

 1) https://youtu.be/k1BIaAHPLGw
 2) https://youtu.be/jaZXgj-vZpM
 3) https://youtu.be/2t5h1oX3tO0

Write to me on Telegram to join you
@AndresGuarinStaff

**Comment by jkm-github** [comment]
Ok
