### ISSUE TITLE
Help in resetting compound interest after severa runs

### ISSUE THREAD

**Issue by dudeprodigy** [binary-com/binary-bot#3887]
Hi guys, I need help to reset stake to initial stake after 4 runs compounding. Return stake from :contract detail payout to initial stake

**Comment by Andres-Guarin** [comment]
open the bot here👇
https://bot.binarytools.io/platform

I will send you two examples
the first bot only does compound interest up to a certain level and then resets to the initial stake, and the second bot includes compound interest and the martingale split

![image](https://github.com/binary-com/binary-bot/assets/131272671/20116f09-44c7-442d-bda7-ccffc1bb849d)
![image](https://github.com/binary-com/binary-bot/assets/131272671/7fa410b1-c5b0-4a21-88fe-1239bf33b1d3)
We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_community
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣

👇👇DOWNLOAD THE BOT FREE HERE 👇👇
1. only compound
[only compound.zip](https://github.com/binary-com/binary-bot/files/11482513/only.compound.zip)
2. split + compound FULL
[SPLIT + COMPOUND FULL.zip](https://github.com/binary-com/binary-bot/files/11482517/SPLIT.%2B.COMPOUND.FULL.zip)

**Comment by dudeprodigy** [comment]
Thanks the strategy for split compounding works best for me
