### ISSUE TITLE
100% never loss bot touch + / -

### ISSUE THREAD

**Issue by dudeprodigy** [binary-com/binary-bot#3888]
Can someone help to recreate this infinite bot. https://m.youtube.com/watch?v=9RsoYF0kd1E&t=12s
It takes TOUCH trades for vol 10 (1s) with the lowest barrier possible of 0.08. it is always in profits whether barrier offset is positive or negative, i.e its in a win from entry 9102.5---> exit 9102.9 and also wins from entry 9102.5----->exit 9102.1. it also has compounding levels.

**Comment by dudeprodigy** [comment]
They almost had me fooled. Does that mean even the strategies are fakes?

**Comment by Andres-Guarin** [comment]
> They almost had me fooled. Does that mean even the strategies are fakes?

Yes, all fake
"Binary Blocks Experts" = SCAM
