### ISSUE TITLE
stake list

### ISSUE THREAD

**Issue by cisbinary** [binary-com/binary-bot#3890]
anyone who can help me create a bot with stake list instead of the traditional martingale bot?

**Comment by Andres-Guarin** [comment]
> 

open the bot here👇
https://bot.binarytools.io/platform

the bot includes the virtual DISABLED ✅
Stake List ✅

![image](https://github.com/binary-com/binary-bot/assets/131272671/40536390-5b99-4ba1-bff5-c98068c5a0b2)
![image](https://github.com/binary-com/binary-bot/assets/131272671/2d338753-0541-4dcb-9000-66cb359b9114)
![image](https://github.com/binary-com/binary-bot/assets/131272671/ff754fa2-2688-4add-adc7-f0b0abd9054a)
![image](https://github.com/binary-com/binary-bot/assets/131272671/f1c98e55-03a0-4a11-8ca0-547482520d3a)
![image](https://github.com/binary-com/binary-bot/assets/131272671/594280b0-ca5d-48a8-aa0e-d946c24e74ec)

We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_community
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣

👇👇DOWNLOAD THE BOT FREE HERE 👇👇
[STAKE LIST.zip](https://github.com/binary-com/binary-bot/files/11538056/STAKE.LIST.zip)
