### ISSUE TITLE
Over 4 under 5

### ISSUE THREAD

**Issue by AntonyNjuguna848** [binary-com/binary-bot#3894]
https://github.com/binary-ex-machina/binary.com-bot/issues/97#issue-1738772015

**Comment by Singertech5** [comment]
Hola, ¿el bot está cambiando entre cuentas principales y virtuales?

**Comment by AntonyNjuguna848** [comment]
Okay, but i want to put number of losses my self,eg,

=>zigzag to [prompt]>[number]>[Text]

@Andres-Guarin 
@Andres-Guarin 
@Andres-Guarin 
@Andres-Guarin
