### ISSUE TITLE
Over 2 Over 4 binary bot 

### ISSUE THREAD

**Issue by Ncubed254** [binary-com/binary-bot#3897]
Can you help me with a bot trading over 2 but when it losses it will trade on over 4 until it wins ,then it shifts back to over 2 . Volatility 100 .
Thank You

**Comment by Andres-Guarin** [comment]
open the bot here👇
https://bot.binarytools.io/platform

the bot includes the virtual Hook DISABLED✅
The bot includes the Smart Risk library for money management✅

![image](https://github.com/binary-com/binary-bot/assets/131272671/680411b4-c0d2-4e4c-ad9c-f6ce8abfd8b6)
![image](https://github.com/binary-com/binary-bot/assets/131272671/258bf93c-0515-41db-b80c-c216cb4555b1)

We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_community
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣

👇👇DOWNLOAD THE BOT FREE HERE 👇👇
[OVER 2-4.zip](https://github.com/binary-com/binary-bot/files/11825952/OVER.2-4.zip)

**Comment by cisbinary** [comment]
@Andres-Guarin is there any way to make the above bot to start trading on real account first, then when it loses it switches to virtual trading and when it finds a win on virtual settings , it gets back to continue trading on real account factoring in martingale. And the cycle continues. Thanks

**Comment by Ncubed254** [comment]
Much appreciation  Andres
