### ISSUE TITLE
Help install error 

### ISSUE THREAD

**Issue by dhenafuers** [binary-com/binary-bot#39]
how to install to localhost?

![screenshot_22](https://cloud.githubusercontent.com/assets/11412512/18231228/57ad5234-72dd-11e6-87e6-175a4ce190f7.png)

**Comment by Shashank-In** [comment]
are you using windows?

**Comment by dhenafuers** [comment]
@Shashank-In  yup.

**Comment by aminmarashi** [comment]
Make sure your node and npm are up-to-date.

run:
```
npm install
npm run dev
```

It's best if you can run on a Linux or Mac OS X machine.
