### ISSUE TITLE
Last Candle Black CLOSED

### ISSUE THREAD

**Issue by willsilvabc** [binary-com/binary-bot#392]
Hello guys. I need a block that the bot considers the color of the last candle CLOSED, to make a call or put. I created a block with function below but the bot considers the current candle as closed. Can someone help me? Thank you all.
![blockblackcandle](https://user-images.githubusercontent.com/31419269/29848927-f895e706-8cf9-11e7-8c1d-29e145c9fe9f.png)

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/29867341-78c5f6ae-8da5-11e7-91d3-12de664a5a70.png)

**Comment by willsilvabc** [comment]
![bloconewcandle](https://user-images.githubusercontent.com/31419269/29903368-eaf0e93a-8dd9-11e7-9197-cbb64a984058.png)

Hello Fruitfella, thank you for your time and dedication. I put the function I have here but it did not work. As soon as I play on the bot he considers the current candle as closed. I would like the bot to analyze the previous candle and open the order to the same direction as the candle previously closed. Sorry if I was not very clear. My English is not very good. Thank you.

**Comment by Fruitfella** [comment]
you put that **`Purchase Rise`** in the wrong place!

**Comment by Fruitfella** [comment]
![untitled](https://user-images.githubusercontent.com/26277327/29906852-1bc11c7a-8e42-11e7-93c9-d0c21ff21443.png)

**Comment by willsilvabc** [comment]
My bot's name is GodFruit.  Its working now. 

Tks fella.
