### ISSUE TITLE
Digit match bot, with 5 ticks

### ISSUE THREAD

**Issue by Saleh023** [binary-com/binary-bot#3943]
Hi can anyone help me to create a bot that follow this strategy,  without martingale:
Trigger  ldp
11.          9
22.          8
33.           7
44.           6
66.           4
77.            3
88.             2
99.              1
Trigger is the last 2 digits @pavel-latyshou-binary

**Comment by binary-ex-machina** [comment]
@Saleh023, here is your bot. It will change the prediction based on the latest two digits

Download: [Digit Match 5 Ticks.json.zip](https://github.com/binary-com/binary-bot/files/12702699/Digit.Match.5.Ticks.json.zip)

Run it here https://binaryblocks.pro/
![Screenshot 2023-09-22 at 13 23 04](https://github.com/binary-com/binary-bot/assets/34610787/89abdfb5-309c-4419-88e3-35ab2417c2ef)


![image](https://github.com/binary-com/binary-bot/assets/34610787/f73eaa02-56bf-47eb-9a70-f9b91e9e3590)

**Comment by Saleh023** [comment]
thank you so much
