### ISSUE TITLE
Over 2 under 7 bot

### ISSUE THREAD

**Issue by Ncubed254** [binary-com/binary-bot#3945]
Hello. Kindly help by building a bot of over 2 under 7 . Volatility 100 index
Martingale of 3 .,also add split martingale which I can switch off if I want to Use the Normal martingale of 3.
It should have a split martingale Incase of a loss  0.35 , 0.5, 0.7, 0.9, 1.2...
Have a feature of when to apply the martingale Incase of a losses.. maybe do martingale after maybe 2 losses ( when I decide).
if it's trading over 2 & a loss occurs,it should switch to under 7.. it should maintain the winning side but when a loss occurs switch to other side eg 
over 2-loss switch 
Under 7 - loss switch 
Over win . maintain over until loss .
Thank you

**Comment by Ncubed254** [comment]
Incase of 3 losses.it should have a 1 minute delay

**Comment by binary-ex-machina** [comment]
Here is the bot. It has two money management: a stake list, which will use the item in the list as a stake after each loss, and a martingale. There is a variable that you can set to true or false and change the martingale type. All the other features you requested 

Download it here [Over 2 under 7 bot.json.zip](https://github.com/binary-com/binary-bot/files/12702454/Over.2.under.7.bot.json.zip)

Run it here https://binaryblocks.pro

![image](https://github.com/binary-com/binary-bot/assets/34610787/2d94690d-d383-4361-9ccb-152a307e6da8)

**Comment by Ncubed254** [comment]
Thank You .
