### ISSUE TITLE
SMA Direction

### ISSUE THREAD

**Issue by Nox71** [binary-com/binary-bot#397]
Hi guys, is anybody have an idea how to check SMA direction (go up or down), i need to check if both of my SMA's goes in the same direction or not. @aminmarashi, can you help please?

**Comment by Nox71** [comment]
And how i can count 40 sec from the candle open time? Right now i'm trying to do something like that 
![time](https://user-images.githubusercontent.com/31651285/30160807-c0d1e12e-93d6-11e7-896b-db58de2da7d1.PNG)

**Comment by Nox71** [comment]
Also tried like this and nothing (
![another](https://user-images.githubusercontent.com/31651285/30162637-2e783e88-93de-11e7-9088-43138d935bb2.PNG)

**Comment by binary-ex-machina** [comment]
Analysing the last SMa values you can get what direction it is. Just take the last candle or tick and check if it is higher then the first tick within the period. In sideways this will be a problem. 

Also for the seconds, just use reminder of the epoch by 60 to check in what second of the minute you are.

![sma direction epoch](https://user-images.githubusercontent.com/34610787/34892846-e6037346-f7c1-11e7-8b76-5031eedbe2ae.png)

[smadirection.xml.zip](https://github.com/binary-com/binary-bot/files/1627307/smadirection.xml.zip)

**Comment by Nox71** [comment]
Thanks friend! Is there any way to determine sideways market?

**Comment by binary-ex-machina** [comment]
i've created the CHOP indicator that tells you when the sideways are strong.

https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/chop/chop.xml
here is the sample config: https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators

also more info how the indicator works: https://www.tradingview.com/wiki/Choppiness_Index_(CHOP)

in short is: High value = strong sideways | Low value = strong trend

**Comment by Nox71** [comment]
thanks a lot friend!
