### ISSUE TITLE
Problem/error on "stop the bot for balance"

### ISSUE THREAD

**Issue by zomuzco** [binary-com/binary-bot#398]
Hello, I set a bot for working only if the balance is under certain limit. Maybe I made some mistake or maybe there's a bug. This afternoon I setted the bot to work if the real balance was <1075. I reached balance 1076 but the bot didn't stop and worked again. In the screenshot i posted how I set it, is there something wrong. 
The balance update was correctly updated. Thank you.

![shot1](https://user-images.githubusercontent.com/29904469/30181336-2f7d67f6-9413-11e7-963c-4f97bbf50ab0.JPG)

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/30240516-05a8929a-959c-11e7-8b40-378a597f79b5.png)

**Comment by zomuzco** [comment]
Thank you very much!
