### ISSUE TITLE
OVER UNDER BOT

### ISSUE THREAD

**Issue by Ncubed254** [binary-com/binary-bot#3983]
Hello there .
kindly help me built a bot trading over 5 under 8 .VOLATILITY 100 INDEX .trading on https://bot.binarytools.io/platform
It should trade on one side of a trade until losing, then switch to the other side.
For instance when its trading on over 5 & winning it should maintain that side  until it hits a loss for it to switch to under .
Incase of loses it should trade zigzag way until hits a win.
When trading under 8 it should automatically  stake by 1.75 ALWAYS INCASE THERE IS A LOSS AFTER TRADING OVER 5.
when **### trading over 5 the STAKE SHOULD ALWAYS REMAIN CONSTANT AT 0.35** , NO MARTINGALE ,EVEN AFTER THERE IS A LOSS ON UNDER 8.
AFTER WINNING UNDER 8 WITH A STAKE OF 1.75 IT SHOULD GO BACK TO TRADE WITH A STAKE OF 0.35.
THANK YOU

**Comment by binary-deriv-master** [comment]
Friend @Ncubed254  , here is the bot OVER 5 and UNDER 8 , 0,35$ and 1.75$ , no martingale

![image](https://github.com/binary-com/binary-bot/assets/142959192/c2a52664-16e3-4ec2-8271-a1871a7613c3)
![image](https://github.com/binary-com/binary-bot/assets/142959192/bdfb32ef-9f1d-44f3-9222-2914720b01f5)


We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_comunidad
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣

👇👇DOWNLOAD THE BOT FREE HERE 👇👇

[OVER_UNDER SWITCH by binarytools.io.zip](https://github.com/binary-com/binary-bot/files/13494750/OVER_UNDER.SWITCH.by.binarytools.io.zip)


Open the bot on BinaryTools 👇
https://bot.binarytools.io/platform

**Comment by Ncubed254** [comment]
Thank You so much  Binary Deriv Master
