### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Timmyb11** [binary-com/binary-bot#406]
@aminmarashi  please i want you to build my bot with my strategy please how do i go about it?

**Comment by aminmarashi** [comment]
Do you mind if you share your strategy with us here?

**Comment by Timmyb11** [comment]
No, i want it private please... its simple i just want you to create the bot for me please

**Comment by Timmyb11** [comment]
@aminmarashi  No, i want it private please... its simple i just want you to create the bot for me please

**Comment by Timmyb11** [comment]
@aminmarashi sent you the mail please do check it
