### ISSUE TITLE
Digit match with stats

### ISSUE THREAD

**Issue by HarshAchar** [binary-com/binary-bot#408]
hello developers, 
i was exploring previously opened issues for any help with DIGIT MATCH / DIFFER bot. I was looking for a way to use the last digit stats provided on the binary.com site.
I found one contribution from issue #223  by @okovalov and @Fruitfella which seemed very much what I was looking for. 
@Fruitfellas bot works but is very lengthy and bulky.
So I checked on @okovalov's BUT his bot is not running. 

Could anybody tell me what I need to correct in the blocks to make it work? Ive attached the zip xml.
 
[sample_digit_stat_bot.zip](https://github.com/binary-com/binary-bot/files/1346308/sample_digit_stat_bot.zip)

**Comment by Fruitfella** [comment]
hmm?
kovalov's should works fine if you load all the functions to your bot.

mine is lengthy and bulky because i was a beginner, i didn't know how
to use some blocks. :P
btw, i made some functions for digit betting. get Last Digit Analyzer
<a href="https://github.com/Fruitfella/ROBOT-binary/issues/35">here</a>.
i'm sure it'll help you.

**Comment by HarshAchar** [comment]
Thanks for the swift response @Fruitfella , ill check & get back to you.

**Comment by sunny199112** [comment]
hi all i am new in binary bot..pls i am using digit differ but when i get 1 loss..my all profit gone..and also i get 3 row martingle loss also...give me the appropriate way...that i can help to earn money...@fruitfella

**Comment by Fruitfella** [comment]
@sunny199112 that is the risk of low return contracts, a loss would wipe all your collected profits. 
the solution would be : 
1. find a better strategy with lower martingale level (max consecutive losses).
2. trade in different contract, the one with higher payout.
