### ISSUE TITLE
The trade entries in the summary pop up

### ISSUE THREAD

**Issue by HarshAchar** [binary-com/binary-bot#410]
hi developers, the bot platform works great. 
there is one thing that we, _the users_, need to do and is quite monotonous.

Could you please make an enhancement such that the most recent trade is displayed at the top of the summary trades list? 

This will make it convenient for viewing and eliminates the need for one to keep scrolling down in order to see the most recent executed trade.

**Comment by aminmarashi** [comment]
Thanks, please let me know if you found any issues.
