### ISSUE TITLE
consecutive losses problem (HELP)

### ISSUE THREAD

**Issue by liamtwine** [binary-com/binary-bot#411]
okay so i am creating a bot that begins martingale after a certain amount of consecutive losses. i found a script that claims to do this however it counts EVERY loss regardless if its consecutive or not. can anyone help with this

**Comment by Jo-Hannes** [comment]
<a href="https://github.com/Fruitfella/ROBOT-binary/issues/35">Fruifella's Martingale Ver.3.0</a>

**Comment by Fruitfella** [comment]
@liamtwine

**Comment by liamtwine** [comment]
thanks for reply however this is is only to reset MG after a certain losses but i want to BEGIN MG when say 5 consecutive losses are hit

**Comment by Jo-Hans** [comment]
@liamtwine are you sure you've looked at Fruifella's Martingale Ver.3.0?? there is **Martingale Start After** which is definitely to start martingale after consecutive losses.

**Comment by Jo-Hans** [comment]
input Martingale Start After = 5 to start martingale after 5 consecutive losses

**Comment by liamtwine** [comment]
this starts martingale after 5 losses all together regardless of consecutive or not I think

**Comment by Jo-Hans** [comment]
you think??!!!
dude, don't ask for help if you don't even want to try what ppl told you! such a waste of time.
oh whatever.... i'm out!

**Comment by liamtwine** [comment]
sorry. Yes I have tried it and it doesn't offer what I want. I meant not offend you. I appreciate your help

**Comment by liamtwine** [comment]
also, when i try to load the xml blocks it says blocks loaded but then nothing shows other than the "load from url" block and thats it

**Comment by Jo-Hans** [comment]
as i thought, you haven't tried it yet and just draw a conclusion.
if you are that good in thinking, why bother ask for help?
in that link, there is a "READ THIS FIRST" in very BIG WORDS on the TOP MOST of the page so that anyone who go to that page would see it unless they are blind.
what is "READ THIS FIRST" means?

*sorry i'm a bit rude, but you really irked me and i hate liar*

**Comment by liamtwine** [comment]
but the issue is now when I load the blocks it just loads the xml but no blocks.

**Comment by Jo-Hans** [comment]
that is because you didn't read the "READ THIS FIRST" on that page :P

**Comment by okovalov** [comment]
@Jo-Hans reading that kind of comments and seeing such attitude really discouraging from helping people.. How the neck I suppose to help if you are not f..cking capable to read that paragraph and blindly copy paste that sh..t without even understanding it.. simply copy paste.. no.. they dont do that and keep complaining it did not work.. so frustrating...

**Comment by Jo-Hans** [comment]
@okovalov yeah, now i know why fruitfella wrote **"OR YOU'LL DIE"** after **"READ THIS FIRST"** in his page LOL

**Comment by liamtwine** [comment]
I'm really sorry guys. I skipped that because I "assumed" it was showing how to add xml. I've now read it and realised I was an idiot. I've been trading for years with IQ option and make a healthy living but wanted to automate my trading so came to binary.com. thanks for the help. Maybe you can help answer my other issue labeled: RSI using candles need ticks. really would appreciate it
