### ISSUE TITLE
RSI bot only using candles (NEED TICKS)

### ISSUE THREAD

**Issue by liamtwine** [binary-com/binary-bot#412]
So I've created a bot that uses RSI and I wanted it to purchase up when below 25 and fall when above 75 but the issue is how can I set the default candle type to tick. Because when I add RSI to a chart and watch it at the same time it does fall below the levels on the tick chart but of course not the candles. How can I sort this so it's using tick for my RSI

**Comment by gyilaoliver** [comment]
As I know, and if I'm wrong please anyone correct me, the bot uses ticks for calculating the indicators, even if you have set the default candle size to 1 min.
However, I also noticed that the indicator value calculated by the bot does not always match the value from the chart.

**Comment by liamtwine** [comment]
That's exactly correct

**Comment by Jacques0106** [comment]
Set Rsi input list to tick list
