### ISSUE TITLE
Text Print Block Problem (BUG?)

### ISSUE THREAD

**Issue by Fruitfella** [binary-com/binary-bot#420]
Hi @aminmarashi, its been a while.
I want to report this problem regarding Text Print Block.
For some reason, I put the **`Print`** block on Purchase Block (P2). then this is what happened.
![print text bug](https://user-images.githubusercontent.com/26277327/31859817-d0403f48-b73a-11e7-95e9-acf1ecbd52dc.PNG)

after that, I can neither close the pop-up notification nor stop the bot. :P 
no matter how many times i click the **`OK`** button, it will always pop-up again and again before i got a chance to stop the bot.
I managed to stop the bot by using alt+tab then clicking the stop button before it pop-up again. Well, closing the browser would also work, i guess. but for the good sake, please do something about it.

my suggestion is if it possible, add another button on that notification pop-up (cancel or stop) and when we click it, the bot will stop. or that **`OK`** button is fine as long as it stop the bot when we click it.

best regards.

**Comment by gokula-krishna-dev** [comment]
@Fruitfella This cannot be implemented because it kills the purpose of print.
