### ISSUE TITLE
Issue with martingale trade amount subroutine

### ISSUE THREAD

**Issue by Eshhh** [binary-com/binary-bot#430]
I wanna input my Take Profit, Stop Loss and Trade Amount in the "run once at start" block while using "martingale trade amount" subroutine with the normal martingale robots. I'm not a coder so please help on How to modify the script? Thanks

**Comment by opbinbr66** [comment]
Hi @Eshhh!
Could you please provide the bot you're trying to working on? Maybe I can help you.
This repository has a lot of information about it, and you can check the @aminmarashi gist to find the best examples: https://gist.github.com/aminmarashi

Best regards,
opbinbr66
