### ISSUE TITLE
How create Hull Moving Average on Bot Binary?

### ISSUE THREAD

**Issue by Sun29** [binary-com/binary-bot#436]
Hi Aminmarashi 
Can You help me write bot-block Hull Moving Average?
Thank you.

**Comment by baruga** [comment]
@Sun29 Like this???
![image](https://user-images.githubusercontent.com/24489532/34473335-68c40d5e-efac-11e7-9f39-687a98c24d4e.png)

**Comment by binary-ex-machina** [comment]
i have the indicator: https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#hull-ma

**Comment by Sun29** [comment]
Special thank to @binary-ex-machina 
and special thank to @Fruitfella.

+ @binary-ex-machina have created HMA at  https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#hull-ma

+ and @Fruitfella have created HMA at  https://gist.githubusercontent.com/Fruitfella/f40a7255dd059ebbc08fd8e8d76f6826/raw/07419df119aeb58085364c6f72223f5ca804081b/FRUITFELLA_HullMA.xml

I've closing this issue.

**Comment by MauricioSortudo** [comment]
https://gist.githubusercontent.com/Fruitfella/49ce9660f490d414df9c4dc14bbda437/raw/cf199f558853ca064f0611b90c4b6866c3596dd1/FHullMA.xml
