### ISSUE TITLE
Bot Automation working on Virtual Account but not Live Account

### ISSUE THREAD

**Issue by diamondgeezer1974** [binary-com/binary-bot#45]
I’ve had a go at utilising the binary bot to compile a simple strategy.
It works fine on the Virtual Account…, but not on the Live account. The live account is stopping the next trade from executing, so therefore isn’t providing automation which is what a bot is supposed to do.

I’m a bit of a whizz at Camtasia Studio, so I’ve compiled a mp4 video (which you can get to from the dropbox link below) which shows you what's happening, both on the Virtual Account as well as on my Live account.

The only thing that is different is the Currency… on the Virtual Account its set to USD, but my live account is set to GBP as I’m in the UK. Could this be causing the issue?

Link to Video file
https://www.dropbox.com/s/x7w28atu9142mf2/Binary%20Bot%20Not%20Working%20on%20Live%20Account.mp4?dl=0

PS...I've tried this on multiple machines using multiple browsers and they all have the same issue (Edge, Internet Explorer, Firefox, Google Chrome, and Safari on Apple Devices).

**Comment by aminmarashi** [comment]
@diamondgeezer1974 Thanks for reporting, we're working on it.
