### ISSUE TITLE
Close Button Missing on Summary Screen

### ISSUE THREAD

**Issue by QuickBooksDoctor** [binary-com/binary-bot#461]
Using FireFox v57.02 browser.

the "X" to close the Summary window is hidden behind the Download Log button.

![tradinglogheadder](https://user-images.githubusercontent.com/34055584/34395490-5442ac9c-eb69-11e7-88b2-03c61eb660ef.PNG)

**Comment by nextnaro** [comment]
chrome also no download trade history  button.

**Comment by gokula-krishna-dev** [comment]
@QuickBooksDoctor currently this issue is fixed in current release. Feel free to reopen if you still face this issue.
