### ISSUE TITLE
Save as Collection Tick Box is hidden

### ISSUE THREAD

**Issue by QuickBooksDoctor** [binary-com/binary-bot#462]
Using FireFox v57.02 browser.

When clicking "Save blocks as xml" button, the "Save As Collection" tick-box is hidden behind the "Save" button.

![botsaveaspng](https://user-images.githubusercontent.com/34055584/34395554-d9814116-eb69-11e7-9ce3-555672022447.PNG)

**Comment by gokula-krishna-dev** [comment]
@QuickBooksDoctor This issue is fixed. Please reopen if still face this issue.
