### ISSUE TITLE
D alembert fix

### ISSUE THREAD

**Issue by armmar4711** [binary-com/binary-bot#478]
Can you help me fix D'alembert if win -1 and if loss +1.5
The Normal is +1 -1

**Comment by binary-ex-machina** [comment]
change the size when loss in Core function
![screen shot 2018-01-08 at 15 58 02](https://user-images.githubusercontent.com/34610787/34684608-d97a753a-f48c-11e7-8244-c64d7170fdbd.png)

**Comment by armmar4711** [comment]
it's work thankyou.

**Comment by davidanold** [comment]
Can I get the xml file for this
