### ISSUE TITLE
Trade Definition Changed  &  Now Not Working

### ISSUE THREAD

**Issue by diamondgeezer1974** [binary-com/binary-bot#48]
Hi,

Me again (Sorry).
It looks like the Trade Definition segment of the bot has changed.
Before, you used to select the Market, and then Trade Type, and now it looks like its all been rolled into one segment.

However, this new version isn't working for me and I think the system needs rolling back to the previous setup as further testing is required.

I have been doing some lengthy testing on my strategy over the last couple of days to determine its success, and now I can't do this anymore due to the latest change.

My strategy uses the Digits->Difference (DIGITDIFF) against the Volatility 10 Index, and there is no way to execute a DIGITDIFF now with this new version that has been rolled out so I can now no longer progress with my testing.

I can set the Market, and Trade Type settings as you'd expect but I think the Contract Type dropdown box needs further attention. I would have expected it to give me the option "Matches" and "Differs"... but instead its giving me the options "Both", "Ends In" and "Ends Out". If I select "Both"... then bot runs but does a "DIGITMATCH" process...and if I select "Ends In" or "Ends Out" then it asks for a upper and lower barrier values (which obviously aren't required for the type of trade I'm trying to execute). But there is no way that I can see in that I can get it to do a DIGITDIFF process. Please let me know if I'm missing something.

Any chance you can roll back the system please and correct these issues above before rolling it out again - That way i can carry on with my testing of my strategy.

Oh, and also in addition.... I've noticed that when you log into bot.binary.com using Mozilla FireFox, you can't use the dropdown in the top right corner to change to your different accounts (Live and Virtual etc) - However this does seem to be working in other browsers.

Hope this helps.

Please let me know when this has been fixed.

![contract type example](https://cloud.githubusercontent.com/assets/22943769/20186042/53a94004-a766-11e6-92bb-5608f9a54d86.png)

**Comment by aminmarashi** [comment]
@diamondgeezer1974 Sorry for the big delay. This issue is long gone now. Could you please specify the version of your Firefox browser if the problem still exists.

Thanks for your help

**Comment by aminmarashi** [comment]
I want to close this issue as it's out of date.
