### ISSUE TITLE
How do i Convert .XML to javascript to run in Cli mode. or possible to run .xml in bot cli?

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#484]
How do i Convert .XML to javascript like blelow.
https://blockly-demo.appspot.com/static/demos/code/index.html#
i created 1 bot and need to convert to java script and run under cli mode.
i created account on https://binary.vanillacommunity.com i never get confirmation email i cant create new topic .

Need help.

**Comment by gokula-krishna-dev** [comment]
@nextnaro as of now we don't have that feature in binary bot as of now. We will add it soon.

**Comment by valentino242** [comment]
When You Add this feature dude?
