### ISSUE TITLE
How to generate random integer as prediction which is not equal to last digit

### ISSUE THREAD

**Issue by Eshhh** [binary-com/binary-bot#488]
Hi guys,

Someone please help me in how to code, to generate a random integer as a prediction which will not be equal to last digit for a digit differ robot.
@aminmarashi 
Thanks

**Comment by binary-ex-machina** [comment]
![differ](https://user-images.githubusercontent.com/34610787/34890891-c0de51c8-f7ba-11e7-81a5-14910fd7c886.png)
[differ_from_last.xml.zip](https://github.com/binary-com/binary-bot/files/1627172/differ_from_last.xml.zip)

**Comment by Eshhh** [comment]
@binary-ex-machina Thanks man.. will try and let you know..

**Comment by binary-ex-machina** [comment]
@Eshhh if it worked, please close this issue and the other duplicated : #487

**Comment by Eshhh** [comment]
@binary-ex-machina Thanks for the idea man, it works just fine, though it doesnt work for the condition where the last digit and the random integer is 0 at the same time. But this is good enough and im closing this issue. Thanks again..

**Comment by binary-ex-machina** [comment]
@Eshhh the random integer should be between 1 and 9, so 0 - 0 never happen. Hope that helps.

**Comment by Eshhh** [comment]
@binary-ex-machina yes absolutely.. i set the random integer to 0-9.. my bad.. Thanks again..
