### ISSUE TITLE
Balance before and after the bet

### ISSUE THREAD

**Issue by cheeseheadmoron** [binary-com/binary-bot#491]
How could you put in the block in the "After Purchase" function; the difference of Balance, before purchase and after purchase (whether the result is win or loss).

**Comment by lasaidhari** [comment]
please clarify

**Comment by cheeseheadmoron** [comment]
Hi Lasaidhari. I need the bot to check the Balance before purchase (B-0) and compare it to the Balance after the result (B-1). If B-1>B-0, then continue with the initial Stake. But if B-1<B-0, then apply Martingale factor for recovery on the next Stake.

**Comment by binary-ex-machina** [comment]
I think this is what you looking for
![balance](https://user-images.githubusercontent.com/34610787/35282214-11e4057a-003c-11e8-8629-e6f2b2fede64.png)

[balance.xml.zip](https://github.com/binary-com/binary-bot/files/1656404/balance.xml.zip)

**Comment by cheeseheadmoron** [comment]
Thanks @binary-ex-machina
