### ISSUE TITLE
Changing the Barrier Sign referring to Trend

### ISSUE THREAD

**Issue by cheeseheadmoron** [binary-com/binary-bot#493]
How could the Bot set for adjusting the Sign of the Barrier referring to current Trend.
On the Touch/No Touch.
If the Trend is Up, then the Barrier is returned to (+). But if the Trend is Down, then the Barrier is changed to (-).

**Comment by binary-ex-machina** [comment]
answer here [#323](https://github.com/binary-com/binary-bot/issues/323)

**Comment by cheeseheadmoron** [comment]
Thanks @binary-ex-machina
