### ISSUE TITLE
Custom Progression

### ISSUE THREAD

**Issue by CJAsmar** [binary-com/binary-bot#496]
Hello. Please I need help regarding the increase in stakes. I need whenever I lose a trade, the stake to increase to a certain amount I choose and when I win, it goes back to the initial stake I have chosen before.
For example I start with a stake of $1.
If loss it goes up to a value of $3.
If loss it goes up to a value of $7.
If loss it goes up again and again and again.
If won it goes back to $1.
But I need to insert my progression before the start of the trading session.

**Comment by binary-ex-machina** [comment]
When you hit play, it will pronpt the user to inser the progression. Use comma as delimiter, like: 1,2,3,4,5,6 and don't use spaces.

![progression](https://user-images.githubusercontent.com/34610787/35332159-1e5a4458-00f1-11e8-9906-3cb833fae2b1.png)

[progression.xml.zip](https://github.com/binary-com/binary-bot/files/1659792/progression.xml.zip)

**Comment by CJAsmar** [comment]
Thank you I will test as soon as possible and close the thread if it worked

**Comment by CJAsmar** [comment]
Thank you works 100% as needed
