### ISSUE TITLE
Change contract type from higher to lower and then vice versa after a number of contracts

### ISSUE THREAD

**Issue by James-Ngigi** [binary-com/binary-bot#502]
I would really like some assistance with setting up the contract to change from higher(call) to lower(put) and then vice versa after any trade, successful or unsuccessful, i would like this to be done repeatedly until i stop the bot> To clarify, i want the bot to be like as shown in the pic below, 
![capture](https://user-images.githubusercontent.com/28121458/35476805-5fbd867a-03c7-11e8-8c8c-17ed361f6052.PNG)
This would really much help me, if there is anyone with a solution, i would really benefit from it. Thanks though

**Comment by xremmy** [comment]
[James Ngigi bot.txt](https://github.com/binary-com/binary-bot/files/1670624/James.Ngigi.bot.txt)

Try this

**Comment by James-Ngigi** [comment]
Thank you so much
