### ISSUE TITLE
quick fix, can anyone figure out this?

### ISSUE THREAD

**Issue by James-Ngigi** [binary-com/binary-bot#503]
Hello, 
Someone please help me with this problem:
I am trying to have my bot change its contract from higher(call) to lower(put) and then vice versa after after 2 trades, be it a loss or a win
Still, i want to multiply the previous investment by 2.5 if the previous investment lost.
If the previous investment won, i would like it to stake the investment back to 1 US dollar,

So this is the summary,

First contract should be 1, if it wins, next contract should remain as 1, if it lost, (previous contract staked * 2.5) and the sequence until there is a win
The contract type should change after 2 trades doesn't matter if it won or lost.

Below is a screenshot of how far i have reached, someone please show me my error and show me the right way to do it, i'm stuck here

![capture](https://user-images.githubusercontent.com/28121458/35481162-5f6341c0-042f-11e8-92c7-abe64f3777f5.PNG)

Thanks in advance

**Comment by binary-ex-machina** [comment]
I don't know how you manage to have PUT and Rise at the same time on your Before Purchase, but here is the bot.

![2go](https://user-images.githubusercontent.com/34610787/35516617-583abb2a-04f3-11e8-82d4-2be211d11339.png)

[sequence2.xml.zip](https://github.com/binary-com/binary-bot/files/1673981/sequence2.xml.zip)

**Comment by James-Ngigi** [comment]
Wow! Thanks alot, well, i got help on having put and rise at the same time, look at it, 
[Put and Call.txt](https://github.com/binary-com/binary-bot/files/1674024/Put.and.Call.txt)
Thanks again

**Comment by binary-ex-machina** [comment]
it shows Rise & Fall for me, but anyway, if it worked, please close the issue!

**Comment by James-Ngigi** [comment]
It works 100%, your the best
