### ISSUE TITLE
Golden Eye

### ISSUE THREAD

**Issue by CJAsmar** [binary-com/binary-bot#510]
Hello @binary-ex-machina,

Can you please help me with this strategy?

Buying a CALL option:
Immediately after a green arrow appears
ADX indicator has to be at least on level 25

Buying a PUT option:
Immediately after red arrow appears
ADX indicator has to be at least on level 25

ADX indicator is the blue line that is shown when in the DMI indicator

Please check this link for further details.
http://webcache.googleusercontent.com/search?q=cache:http://best-binary-options-strategy.com/golden-eye-trading-strategy/

Thank you so much,
So sorry for disturbing you

**Comment by binary-ex-machina** [comment]
ADX indicator is complex to create on binary.com.

What i have so far doesn't work very well and I'll need some help to create this indicator to use on the strategy.


• len = 14
• TrueRange = max(max(high-low, abs(high-close[1])), abs(low-close[1]))
• DirectionalMovementPlus = high-high[1] > low[1]-low ? max(high-high[1], 0): 0
• DirectionalMovementMinus = low[1]-low > high-high[1] ? max(low[1]-low, 0): 0
• SmoothedTrueRange = SmoothedTrueRange[1] - (SmoothedTrueRange[1]/len) + TrueRange
• SmoothedDirectionalMovementPlus = SmoothedDirectionalMovementPlus[1] - (SmoothedDirectionalMovementPlus[1]/len) + DirectionalMovementPlus
• SmoothedDirectionalMovementMinus = SmoothedDirectionalMovementMinus[1]) - (SmoothedDirectionalMovementMinus[1]/len) + DirectionalMovementMinus
• DIPlus = SmoothedDirectionalMovementPlus / SmoothedTrueRange * 100
• DIMinus = SmoothedDirectionalMovementMinus / SmoothedTrueRange * 100
• DX = abs(DIPlus-DIMinus) / (DIPlus+DIMinus)*100
• ADX = sma(DX, len)

![adx](https://user-images.githubusercontent.com/34610787/35866019-2f3836d0-0b3d-11e8-8faf-f9b10e89dd37.png)


[adx v3.xml.zip](https://github.com/binary-com/binary-bot/files/1699511/adx.v3.xml.zip)

**Comment by CJAsmar** [comment]
Okay so what is missing?

**Comment by CJAsmar** [comment]
Hello @binary-ex-machina 

I am contacting you through this issue because I have something important to discuss with you and only you.

Please check this link.
https://www.youtube.com/watch?v=cM1CI-_IABo

I have contacted the email address and he gave me a list of, according to him, fully functional bots that he created and is selling at a reasonable price.

If you could send me an email, my email address: chawki.junior@gmail.com , and I can forward you the emails he sent me and maybe you can help me decide whether is it a good investment or not.

Please reply ASAP.
I need to to invest in something.

Thank you so much

**Comment by thepiamboys** [comment]
U have create adx indikator utama working. But for 1 period time. Van u make itu to 14 period??

**Comment by supun616** [comment]
ADX INDICATOR HOW TO ADD TICK LIST
