### ISSUE TITLE
stopLoss after a number of consecutive losses

### ISSUE THREAD

**Issue by James-Ngigi** [binary-com/binary-bot#513]
Hi, so, i have a bot that has a stop loss after a number of losses, the problem is the bot does not do this continuously, it counts the overall number of losses and then stops
What i need it to do is, i would like it to stop trading after a number of consecutive losses e.g. 8 **consecutive** losses, not overall number of losses, take a look at how it looks like. 
If anyone can change, modify or create a new one, i'd appreciate.
Here is the screenshot of the bot
![capture](https://user-images.githubusercontent.com/28121458/35922942-f88dc214-0c2f-11e8-885e-7e5cbb4b2870.PNG)
and here is the screenshot of when it stops trading
![capture](https://user-images.githubusercontent.com/28121458/35923089-593fddea-0c30-11e8-8879-a00602225c99.PNG)
Thanks

**Comment by binary-ex-machina** [comment]
![consecutive](https://user-images.githubusercontent.com/34610787/35925233-5af11b8c-0c0c-11e8-9cde-30c33297afd8.png)
