### ISSUE TITLE
a BUG on "WATCH & PURCHASE CONTRACT" BLOCK (FOREX) --- BUG

### ISSUE THREAD

**Issue by Jo-Hans** [binary-com/binary-bot#518]
@aminmarashi @gokula-krishna-dev we need some bug repellents or insecticides here!! lol.

to day i tried some forex strategy to binary bot.
i felt something wrong as the bot didn't worked as it should, so checked it out and found this BUG.
**the bot execute the script on "WATCH & PURCHASE CONTRACT" block twice (or even trice) on very tick.**
but when i changed the asset to volatility idx, everything works fine. this BUG only happen on forex (i only checked forex and volatility, so idk about the other assets).

here is the test i made to check the bug.
[TES-BLOCK(2)-EXECUTED.zip](https://github.com/binary-com/binary-bot/files/1709700/TES-BLOCK.2.-EXECUTED.zip)
![error_on_purchase_block](https://user-images.githubusercontent.com/32584948/36011000-01bf06e2-0d87-11e8-8977-53a2a159d608.PNG)**

**Comment by gokula-krishna-dev** [comment]
We have currently fixed this issue in current release. Feel free to reopen this issue if you still face it.
