### ISSUE TITLE
Message Error: High barrier must be higher than low barrier.

### ISSUE THREAD

**Issue by carlosalan2** [binary-com/binary-bot#522]
Guys, 

I have this error message and i have no idea what iam doing wrong. 

By website its OK this contract at the same conditions. Anyone could help me with this?

NOT OK:
![error](https://user-images.githubusercontent.com/20076600/36071849-cdb00688-0f04-11e8-924d-5765e1732810.PNG)

OK:
![success](https://user-images.githubusercontent.com/20076600/36071881-46b0eae8-0f05-11e8-8319-5bfe13c6240c.PNG)

**Comment by AlienFly** [comment]
You need change "Barrier Offset 1" to "+10" and "Barrier Offset 2" to "-1".

**Comment by carlosalan2** [comment]
Thank you, it worked here.!
