### ISSUE TITLE
Hello..i'm new to binary.com...i Need a minimum LOSS Bot..Thankz

### ISSUE THREAD

**Issue by ChinthakaJP** [binary-com/binary-bot#526]
I Need a minimum LOSS Bot# 
Hello..i'm new to binary.com...i Need a minimum LOSS Bot..Thankz

**Comment by ZDEGLET** [comment]
ЭТО ОЧЕНЬ СЛОЖНО ДОБИТЬСЯ ОТ БОТА. А ХОРОШИЙ БОТ НУЖНО ПОКУПАТЬ. И ТО НЕ ФАКТ ЧТО ОН ТЕБЯ УСТРОИТ.

**Comment by binary-ex-machina** [comment]
@ChinthakaJP i think you mean Stop loss or Max Loss.

![image](https://user-images.githubusercontent.com/34610787/36231191-4cb84884-11c4-11e8-9244-4507e6da61c7.png)

[stoploss.xml.zip](https://github.com/binary-com/binary-bot/files/1725842/stoploss.xml.zip)

**Comment by ChinthakaJP** [comment]
@binary-ex-machine No...i need fully completed bot....my capital $50....thankz

**Comment by binary-ex-machina** [comment]
you are new to binary options right? before put your money on any bot, learn how it works, build some bot and learn the basics. You can find a lot of bots here on the issues with many strategies incorporating stoploss. Do some search and learn more before investing
