### ISSUE TITLE
Is it a bug or is this just the way it works?

### ISSUE THREAD

**Issue by James-Ngigi** [binary-com/binary-bot#538]
So, i was checking out the Oscars grind strategy bot and it has a way its supposed to work
Like this,
![logs](https://user-images.githubusercontent.com/28121458/36349258-478f64f6-1493-11e8-9757-88ba7e2c849b.JPG)
but today i was testing it out and i don't think its supposed to work this way
![capture](https://user-images.githubusercontent.com/28121458/36349262-692fef54-1493-11e8-8705-86385a0dc4ee.JPG)
![2](https://user-images.githubusercontent.com/28121458/36349264-6cce7482-1493-11e8-88b0-5bab4db79dbd.JPG)

Is this a safety feature or is it a bug?

**Comment by binary-ex-machina** [comment]
please put your xml here for testing
