### ISSUE TITLE
Help how to change the value of the barrier

### ISSUE THREAD

**Issue by Jonni81** [binary-com/binary-bot#555]
Help how to change the value of the barrier is + or -. Depending on the MACD signal
![screenshot](https://user-images.githubusercontent.com/30568441/36610527-cc44e6d8-18fa-11e8-8c17-94285a95de3a.png)

**Comment by binary-ex-machina** [comment]
you can change the sign only before entering the trade, so do you calculations on the block 1

![image](https://user-images.githubusercontent.com/34610787/36610704-f2b51dd8-18af-11e8-87d4-189717b44853.png)

**Comment by Jonni81** [comment]
Thanks for your help.)))
