### ISSUE TITLE
EMA Indicators need help

### ISSUE THREAD

**Issue by davidx85** [binary-com/binary-bot#562]
hey,

at first sorry my english is not so good sorry. I have a question. My idea is that the bot call or put if the indicators EMA 2 - 20 under or over so thats a up or downtrend.If EMA 2 higher than EMA 3, if EMA 3 higher than EMA 4 an so on.. But it don't work well because my bot says the most time "wait" so he don't buy a option. The bot runs all day long but he make only 2 buys.  I always change the input list from last tick to candle list but that don't helped.
What is wrong can you help me? 

I will run the bot on 3 min candle on forex market.
The bot should buy a option when the next candle starts but this also don't work when he buy the candle isn't close..

![image](https://user-images.githubusercontent.com/36933726/36809567-8ce5ebbe-1cc8-11e8-9b73-02473a64c721.png)

![image](https://user-images.githubusercontent.com/36933726/36809636-c08dd814-1cc8-11e8-997d-4cbe1e6bdcb5.png)

![image](https://user-images.githubusercontent.com/36933726/36809652-d1c5e554-1cc8-11e8-9db9-18115787f404.png)

![image](https://user-images.githubusercontent.com/36933726/36809718-09213f6c-1cc9-11e8-9b6c-015794f16706.png)

![image](https://user-images.githubusercontent.com/36933726/36809802-4b5837c8-1cc9-11e8-8e0c-d0f63f027349.png)

Could you help me?

Thanks
David

**Comment by binary-ex-machina** [comment]
the verification on block 2 with remainder of seconds since epoch is for 3min candles (3x60). If you change the candle time, multiply by 60 (ex.: 5min = 300)

![image](https://user-images.githubusercontent.com/34610787/36848300-9d9becd4-1d3f-11e8-9690-9b52e8fe4a26.png)

[forex rainbow.xml.zip](https://github.com/binary-com/binary-bot/files/1771402/forex.rainbow.xml.zip)

**Comment by davidx85** [comment]
Thanks! I think that is what i search for. But only one question. Could you explain how it works.
I don't understand zthe right side , count with 1 from 1 to 18 and so on. Is that Ema 1 -18 ?

**Comment by binary-ex-machina** [comment]
count from 1 to 20, increasing each loop by 1. The first EMA is i + 1, where i is the number on the loop. So it will compare in this way: 2>3;3>4;4>5... and so on. You can change the start (from) and how much it will go (to). If you want to compare EMAs with difference of 2, you change the (by)  input.

Also on the bot, where it says 20 needs to be 18, so the check will go from 2 - 20. I forgot to change.

**Comment by davidx85** [comment]
great  job! thanks that is what i search for.

:)
