### ISSUE TITLE
Invalid Token error does not logout users

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-bot#57]
If users are logged in, logging their token out causes invalid token error. This error is a logout signal and should remove all the shown accounts and replace them with the `Log in` button.
Refreshing won't help.

**Comment by aminmarashi** [comment]
This issue is partially solved as it still gives the invalid token error instead of please login.

**Comment by aminmarashi** [comment]
Fixed

**Comment by verticalinchrist** [comment]
I need assistance because it gives invalid real account token. Please help me.

Thanks
