### ISSUE TITLE
stochastic

### ISSUE THREAD

**Issue by Jonni81** [binary-com/binary-bot#570]
how to collect stochastic?

**Comment by binary-ex-machina** [comment]
i have this indicator: https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#stochastic

**Comment by Jonni81** [comment]
двоично-экс-махина Thanks. But I couldn't figure it out. I'm saving an xml file. But then I have nothing loaded

**Comment by binary-ex-machina** [comment]
look on functions

**Comment by Jonni81** [comment]
двоично-экс-махина 
![screenshot 3](https://user-images.githubusercontent.com/30568441/37172043-e702b34e-2339-11e8-9f6d-4ad892b4a8fe.png)
![screenshot 4](https://user-images.githubusercontent.com/30568441/37172050-f0b1146c-2339-11e8-8b81-8f59e1e2f15a.png)
that's what happens.

**Comment by binary-ex-machina** [comment]
tested right now
![image](https://user-images.githubusercontent.com/34610787/37174466-54ad4a52-22f5-11e8-86bc-6cffa9d22c91.png)

**Comment by Jonni81** [comment]
I won't upload anything. You can send me a screenshot of the deployed indicator I gather. 08.03.2018, 23:23, "Binary Ex Machina" <notifications@github.com>:tested right now—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by binary-ex-machina** [comment]
don't understand what you are writing

**Comment by Jonni81** [comment]
I don't have blocks loaded anyway. Could you at least let me send a screenshot of the indicator. And I'd take it

**Comment by bidzah** [comment]
@binary-ex-machina, kindly send me indicator on email so that I can test. my email is tapiwabrianmushavi@gmail.com

**Comment by binary-ex-machina** [comment]
[exmachina-stochastic.xml.zip](https://github.com/binary-com/binary-bot/files/1804457/exmachina-stochastic.xml.zip)

**Comment by Jonni81** [comment]
![screenshot 8](https://user-images.githubusercontent.com/30568441/37322187-f05184d6-269d-11e8-8c54-24fd427f9b54.png)
@двоично-экс-махина thanks a lot. Now it is well loaded. May not have loaded due to the fact that no zip was
