### ISSUE TITLE
Stochastic Indicator

### ISSUE THREAD

**Issue by Relicetti** [binary-com/binary-bot#578]
Someone knows how to make the Stochastic Indicator on Binary?

Thanks

**Comment by binary-ex-machina** [comment]
I've created one: https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#stochastic

**Comment by Relicetti** [comment]
@binary-ex-machina,

I think it didn`t work, just appeared that:
![image](https://user-images.githubusercontent.com/36014476/37099179-7ee2ad6e-21fe-11e8-92f4-41db502ff867.png)

**Comment by binary-ex-machina** [comment]
Take a look at the functions, it's there. After that follow the image like the wiki on the link that i sent.

**Comment by Relicetti** [comment]
@binary-ex-machina,

I am sorry, I`ve found. 

Thank you so much.
