### ISSUE TITLE
List updated after each contract?

### ISSUE THREAD

**Issue by AlienFly** [binary-com/binary-bot#580]
@aminmarashi , @binary-ex-machina

How create a list that is updated after each transaction?
For example, after each transaction we get a certain value of variable and this value should be added to the list.

**Comment by binary-ex-machina** [comment]
are you asking about a list of every deposit/withdraw from your account?

**Comment by AlienFly** [comment]
no. for example, bot makes certain calculations on result of contract, in block # 4. this result should be added to list after each contract.

**Comment by binary-ex-machina** [comment]
ah you are asking about each trade. Contract Detail > Profit will give you the profit of the trade. After that just do your calcs and put on a list.

**Comment by AlienFly** [comment]
no. it's not a profit. =)
I calculate the length of the contract. I need that after each contract its length be recorded in the list, for subsequent calculations based on these values.
ie for use with this 
![01](https://user-images.githubusercontent.com/36364199/37099685-b4e15816-226c-11e8-8052-86a9b009ccb3.png)

**Comment by binary-ex-machina** [comment]
Length of the contract? I don't get it. What you want to store in a list on block 4 after each trade?

**Comment by AlienFly** [comment]
![01](https://user-images.githubusercontent.com/36364199/37100516-e4de26c8-226e-11e8-9a72-89b55aad24ef.png)

I need length of  "Time Counter" to be added to list after each contract

**Comment by binary-ex-machina** [comment]
you can insert on the list

![image](https://user-images.githubusercontent.com/34610787/37103602-5e85b66e-2209-11e8-868d-3a433ef2750e.png)

Remember to define the list before and set as empty

![image](https://user-images.githubusercontent.com/34610787/37103645-7887ce08-2209-11e8-808c-9b3ff2b5dba1.png)

**Comment by AlienFly** [comment]
oh, so easy. thanks man =)
