### ISSUE TITLE
Proof of Binary's Cheating

### ISSUE THREAD

**Issue by duynguyen2709** [binary-com/binary-bot#594]
Deleted !

**Comment by janps1712** [comment]
Where is the cheating? As far as I can see you are trading "not 0" on virtual and "not 5" on real?

**Comment by Jo-Hans** [comment]
@duynguyen2709 dude, don't embarrass yourself. Lol
even if they want to cheat, they definitely won't do such cheap trick. if they really make virtual and real account have different result, people would notice it already and they'd be done decades ago.
the best way to cheat is to make the price rise when trader purchase down and to set last digit 1 if trader set match 1. and no trader could find any proof.
but i doubt they'd do that. bc their business is good. they got profit by simply playing math.

"trust the broker you trade with, don't trade with broker you don't trust"
