### ISSUE TITLE
CLI: Selecting restart options

### ISSUE THREAD

**Issue by Baselope** [binary-com/binary-bot#609]
How do I enable/select the restart options in CLI?
![image](https://user-images.githubusercontent.com/36667093/37751987-3a479218-2d9e-11e8-82c3-9cb7529ab725.png)
Is this correct:
![image](https://user-images.githubusercontent.com/36667093/37758019-76f3a9fe-2db7-11e8-9fff-2f70ca38f861.png)

For clarity:
1. which flag is correct: `restartOnError` according to #344 or `shouldRestartOnError` according to `[tools.js](https://github.com/binary-com/binary-bot/blob/master/src/botPage/bot/__tests__/tools.js)`
2. where should it be placed: in `Bot.init` or `Bot.start`?

**Comment by gokula-krishna-dev** [comment]
@Baselope 

Q1:
Restart buy/sell on error = timeMachineEnabled
Restart last trade on error = shouldRestartOnError

Q2:
It should be placed in Bot.init

Feel free to reopen if your issue is not resolved. Also note that bot CLI is not supported officially so try it with your own risk.
