### ISSUE TITLE
LastDigit

### ISSUE THREAD

**Issue by sersh999** [binary-com/binary-bot#61]
Hi.
LastDigit have type string, therefore i can't use this for prediction in Digit Difference, such as need have type intereger.
Please fixed this moment.

**Comment by aminmarashi** [comment]
@sersh999 Thanks for reporting, will be fixed soon

**Comment by aminmarashi** [comment]
Fixed by 88c8c6f, could you please check and close the issue?

**Comment by sersh999** [comment]
Hi.
Thanks, now all is ok.

6 Дек 2016 г. 10:58 пользователь "Amin Marashi" <notifications@github.com>
написал:
