### ISSUE TITLE
Bug on closing trade

### ISSUE THREAD

**Issue by binary-ex-machina** [binary-com/binary-bot#616]
Hello, help understand what is happening here

![image](https://user-images.githubusercontent.com/34610787/37869294-c6fd62cc-2f93-11e8-9474-88df756bdd07.png)

The duration was 14min and 40 seconds. 
It enters the trade on 18:29:58
and finish the trade on 18:45:01

If you do the math that is 00:15:03. My internet connection is good and the browser are updated (Chrome)

23 seconds of difference, i was lucky that i won that bet, but why this happens?

**Comment by gokula-krishna-dev** [comment]
@binary-ex-machina Can you please share your timezone?

**Comment by gokula-krishna-dev** [comment]
That might be one possible explanation and there is also a possibility in delay while executing the trade.

**Comment by binary-ex-machina** [comment]
Got it. I was running some bots at the same time. I think it's all to do with the internet connection.
