### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jonni81** [binary-com/binary-bot#624]
![screenshot 4](https://user-images.githubusercontent.com/30568441/38136113-c77c38c6-3435-11e8-9be3-62af41ed4795.png)
Help please. How can I Express these numbers in bot? X1 X2 X3 X4

**Comment by AlienFly** [comment]
![01](https://user-images.githubusercontent.com/36364199/38140766-8f340faa-3478-11e8-838c-356f03a5cec8.png)

**Comment by tymu** [comment]
@AlienFly share xml of the block

**Comment by Jonni81** [comment]
AlienFly thanks
