### ISSUE TITLE
[Bug] HighLow wrong purchasing (no error in logic)

### ISSUE THREAD

**Issue by duynguyen2709** [binary-com/binary-bot#630]
![screenshot_20180403192626](https://user-images.githubusercontent.com/31149300/38249440-dd054582-3775-11e8-97cd-27bbe14aeb42.png)
![q12131](https://user-images.githubusercontent.com/31149300/38249438-dcca5c24-3775-11e8-9917-54bbc458f22a.png)
![123412](https://user-images.githubusercontent.com/31149300/38249437-dc8f18a8-3775-11e8-80cf-86786590659d.png)

Having hard time to find out what I'm doing wrong here. My idea is when I purchase Higher than it would be : Higher than (Entry + 1) ; and for Lower is : Lower than (Entry - 1).
However the bot is running like "random" (or if I have made mistake somewhere without realising ?) .
Also tried to put negative number in the barrier and had no success.
Any help would be appreciated :D

**Comment by binary-ex-machina** [comment]
First try to understand how the bot works.

First block runs as you click on the play button. After the block 4 it goes back to the block 1, so the logic that you are using on the block 2, needs to be on the block 4.

1 - define your trade - all the logic that choose signals, values of the stake, duration...
2 - watch and purchase - just define when to purchase the contract
3 - watch you trade
4 - collect result of the trade - collect the results and possibly define the next trade
