### ISSUE TITLE
Best times to trade on Volatility indicies

### ISSUE THREAD

**Issue by James-Ngigi** [binary-com/binary-bot#637]
Hi, 
Who has the knowledge on what times the _volatility indices_ are not on a sideways trend _**hourly**_ rather on a continuous down or up trend at **GMT**?
If you have knowledge of these _**hours**_, please share, it will mean a lot. Thanks.

**Comment by xremmy** [comment]
Someone posted this in a forum i was in like 5 years ago, i don't know if it is till valid as there is no reference to it on binary.com site.
![binary com trading times](https://user-images.githubusercontent.com/25975068/38473448-29c3b988-3b88-11e8-8ac4-1993deb412c6.jpeg)

**Comment by James-Ngigi** [comment]
Thank you @xremmy !!
