### ISSUE TITLE
1426.69% in 15 trading days

### ISSUE THREAD

**Issue by elyyyes** [binary-com/binary-bot#658]
Hi everybody,

i offer my services for anyone who want to earn money from trading
we accept from all interested because we work with pro rata basis 50/50 for every trading day

EXAMPLE :
1st day : 
you invest $100 and we do "example" 13% as benefits , you will have $100+($13/2)=$106.5
2nd day : 
we invest for you $106.5 and if we do 15% as benefits , you will have $106.5+($15.97/2)=$114.48 
3rd day : ...
4th day : ...
and you can demand your money when you want

you can see my screenshots for all 15 days ...

![screenshot_20180418-013051](https://user-images.githubusercontent.com/29686874/38906464-2f286d48-42b7-11e8-8ba3-c400d3876e03.jpg)
![screenshot_20180418-013244](https://user-images.githubusercontent.com/29686874/38906465-2f6d9e22-42b7-11e8-8e78-f768b81ae83f.jpg)
![screenshot_20180418-013334](https://user-images.githubusercontent.com/29686874/38906466-2fb6edde-42b7-11e8-86ad-dc996a14af83.jpg)
![screenshot_20180418-013429](https://user-images.githubusercontent.com/29686874/38906468-30155d9c-42b7-11e8-9829-f1911625cb5e.jpg)
![screenshot_20180418-013513](https://user-images.githubusercontent.com/29686874/38906469-30f88c98-42b7-11e8-9629-5584e16e10e9.jpg)
![screenshot_20180418-013553](https://user-images.githubusercontent.com/29686874/38906470-3205995a-42b7-11e8-908f-c422cff43314.jpg)
![screenshot_20180418-013642](https://user-images.githubusercontent.com/29686874/38906472-33bcd434-42b7-11e8-8e84-ca727002958e.jpg)
![screenshot_20180418-013725](https://user-images.githubusercontent.com/29686874/38906476-37319258-42b7-11e8-9908-cfe673e3dacc.jpg)
![screenshot_20180418-013805](https://user-images.githubusercontent.com/29686874/38906479-3b228cc8-42b7-11e8-9bc1-2347c874e1a5.jpg)
![screenshot_20180418-013847](https://user-images.githubusercontent.com/29686874/38906483-3f3a4436-42b7-11e8-84e8-98bef04c17ac.jpg)
![screenshot_20180418-013957](https://user-images.githubusercontent.com/29686874/38906487-4261a622-42b7-11e8-8d90-189bd0bfef83.jpg)
![screenshot_20180418-014032](https://user-images.githubusercontent.com/29686874/38906495-4f50a702-42b7-11e8-9b53-5d3089305601.jpg)
![screenshot_20180418-014112](https://user-images.githubusercontent.com/29686874/38906497-54ab6890-42b7-11e8-8753-ed4f8476610d.jpg)
![screenshot_20180418-014154](https://user-images.githubusercontent.com/29686874/38906503-59df692e-42b7-11e8-8239-6c630552d34b.jpg)
![screenshot_20180418-014322](https://user-images.githubusercontent.com/29686874/38906512-66ddd0ac-42b7-11e8-8414-02b7ed3095c1.jpg)
![screenshot_20180418-014444](https://user-images.githubusercontent.com/29686874/38906513-698add0e-42b7-11e8-8874-bfae0c18ac64.jpg)

We accept contribution via Neteller
You can invest the amount that you want ( write the sum that you want to invest it in comment, and when we reach the demand, we close offer, give you the neteller account and we begin working )

Hope you appreciate my work
Good luck everybody

**Comment by elyyyes** [comment]
@gokula-krishna-dev 
can i know what is reasons ?!!

**Comment by gokula-krishna-dev** [comment]
@elyyyes we only accept the question which are related to bot issue or bot development.
