### ISSUE TITLE
How to get value of Entry spot on block (3)

### ISSUE THREAD

**Issue by Eshhh** [binary-com/binary-bot#663]
Im trying to sell at market when last 2 ticks are below or above entry spot by defining a trend. Something like this.

![image](https://user-images.githubusercontent.com/33750313/39037423-173f8034-449e-11e8-8432-a0aff57cd306.png)

doesn't work. Does Someone have any idea how to do this?

**Comment by Jonni81** [comment]
@Eshhh Maybe just 1 tick more than the second?

**Comment by Eshhh** [comment]
@Jonni81 I wanna trade on 1m candle and trade enters on the beginning of the candle, and the trade expires after 55s.. At any point during the trade, if the last two ticks falls below or above the entry spot, the trade should be sold.

**Comment by Eshhh** [comment]
@Jonni81 i wanna sell when at loss so that i can define the next trade amount. Thanks

**Comment by AlienFly** [comment]
> Im trying to sell at market when last 2 ticks are below or above entry spot by defining a trend. Something like this.

![001](https://user-images.githubusercontent.com/36364199/39066975-632b8908-451a-11e8-8d69-04efda5b3f07.png)

**Comment by Eshhh** [comment]
@AlienFly  i know, is there a way to get the entry spot value in block 3? thanks..

**Comment by AlienFly** [comment]
Immediately before buying a contract, assign value of last tick to variable. And use this variable in Block # 3.

**Comment by binary-ex-machina** [comment]
You can get like this

![image](https://user-images.githubusercontent.com/34610787/39401737-f28d2940-4b22-11e8-9f3b-0ca26a97f775.png)

**Comment by Eshhh** [comment]
@binary-ex-machina will try it thanks..
