### ISSUE TITLE
stochastic question

### ISSUE THREAD

**Issue by csajkas** [binary-com/binary-bot#667]
Hello friends,
I have a little problem with a indicator. How to set Ticks List to timeframe?? Can someone to help me? 
Thank you  :)

![easycapture1](https://user-images.githubusercontent.com/35691604/39096027-3e17448c-464a-11e8-9f5a-1437e51f50a3.jpg)

![easycapture3](https://user-images.githubusercontent.com/35691604/39094550-87559e78-4631-11e8-9c6b-061eef0209e0.jpg)

**Comment by wijanarkokns** [comment]
[St.K.zip](https://github.com/binary-com/binary-bot/files/1935891/St.K.zip)

**Comment by wijanarkokns** [comment]
![screenshot_2018-04-23-00-29-44_1](https://user-images.githubusercontent.com/32452523/39098007-6f2bcdce-468e-11e8-9fe1-090ed87bc28a.jpg)

**Comment by csajkas** [comment]
Thank you @wijanarkokns

**Comment by csajkas** [comment]
Hi
I have again a question... How can I set levels for rise and fall? What is wrong here? Thanks..
@wijanarkokns 
![easycapture2](https://user-images.githubusercontent.com/35691604/39208177-7d82a800-4802-11e8-830f-5c6010e64b58.jpg)

**Comment by wijanarkokns** [comment]
[Try this.zip](https://github.com/binary-com/binary-bot/files/1945062/Try.this.zip)

**Comment by csajkas** [comment]
You are a King @wijanarkokns :smiley:  Thank you again...

![easycapture1](https://user-images.githubusercontent.com/35691604/39226898-a86226c4-4855-11e8-9235-a2ecc45f302b.jpg)

**Comment by trident2005** [comment]
Regards

Would it be possible to make the modification with respect to other indicators so that they also work on ticks?
