### ISSUE TITLE
Creating of a variable

### ISSUE THREAD

**Issue by James-Ngigi** [binary-com/binary-bot#671]
Hi, 
I am trying to create a variable that automatically detects the account balance and stores it, as a value that can be used within the bot.
Does anyone know how to create this variable?
I personally don't even know how to start create it.
Many thanks to anyone who participates in creating it.

**Comment by AlienFly** [comment]
`Tools` -> `Misc.` -> `Balance: number`

**Comment by James-Ngigi** [comment]
Thanks! didn't look there
