### ISSUE TITLE
script a word 'else'

### ISSUE THREAD

**Issue by lecadou** [binary-com/binary-bot#689]
i can not script the word' else' help me

**Comment by gokula-krishna-dev** [comment]
In if block you can see a gear icon. There will be a pop up, drag the else block from left to right. 

<img width="285" alt="screen shot 2018-05-10 at 4 00 34 pm" src="https://user-images.githubusercontent.com/33853819/39859186-8c3ae61c-546b-11e8-9af5-07a332a4e359.png">

Feel free to reopen if you need more clarification.
