### ISSUE TITLE
please add the RSI indicator at the binary.bot

### ISSUE THREAD

**Issue by ekozhin** [binary-com/binary-bot#69]

**Comment by aminmarashi** [comment]
This is planned to be done, thanks for the concern.

**Comment by dritonbytyqi** [comment]
Hello people
Is RSI indicator added yet?

**Comment by aminmarashi** [comment]
It's currently under development https://github.com/binary-com/binary-bot/projects/1

**Comment by aminmarashi** [comment]
@dritonbytyqi @ekozhin The RSI block is added and is ready to use, enjoy. PR for ref: https://github.com/binary-com/binary-bot/pull/73

**Comment by ekozhin** [comment]
good news Amin, i wiil testing :)

**Comment by dritonbytyqi** [comment]
thanks for the project done #Amin
Eko is time to make it work :P
