### ISSUE TITLE
HELP....Binary.com working fine,but Bot not loading

### ISSUE THREAD

**Issue by Seapson** [binary-com/binary-bot#696]
The site is working alright,but the bot ( https://bot.binary.com/bot.html ) keeps loading.. 
https://screenshots.firefox.com/FeTR000fXxnuiEVM/bot.binary.com
pls i'm i the only person experiencing this?
Even the webtrader says connection error, but i have connection

**Comment by duynguyen2709** [comment]
maybe try to clear ur browser's cache & cookie would help, or even consider changing ur browser ?

**Comment by gokula-krishna-dev** [comment]
@Seapson Firefox clients have issues when connecting to binary server and we are investigating it. I would recommend you to use Chrome until it is resolved.

**Comment by Seapson** [comment]
Thanks a lot....ive changed the browser and its working fine now
