### ISSUE TITLE
Help on how to stop martingale level after 3 losses. 

### ISSUE THREAD

**Issue by Seapson** [binary-com/binary-bot#699]
![ucscreenshot20180511055933](https://user-images.githubusercontent.com/38880008/39907430-a91e2e72-54e0-11e8-9d4b-eaf176cd9106.jpg)
I have fruitfella v.3 martingale,but the martingale factor cant be changed,and the martingale level is just dormant.can anybody help with how to change the martingale factor and level

**Comment by csajkas** [comment]
Please,upload your  bot.

**Comment by Seapson** [comment]
Thanks @csajkas i was able to do that myself after hours of trying....but i've got another problem...i'm trying to create a bot that will make a list of last digit chart,then purchase the minimum last digit,i.e the digit that appears the least(red bar) in the chart
