### ISSUE TITLE
strategy crossing SMA

### ISSUE THREAD

**Issue by ekozhin** [binary-com/binary-bot#70]
Amin, I want to make the strategy at the crossing of SMA 14 and SMA 21, only when they crossing, the robot would open transaction
Written by algorithm, but the transaction is not open
The robot does not work the condition of equality
![cross sma](https://cloud.githubusercontent.com/assets/24454432/21048564/f2d42d3a-be20-11e6-8228-cd69c4d1e36d.jpg)

**Comment by aminmarashi** [comment]
Hi, Usually when comparing two values it helps to monitor them using the notify block. If you do, you'll see that the values of sma_21 and sma_14 will almost never meet, though they might be very close at times. Therefore you can define a threshold for their difference and decide to buy based on this threshold.
<img width="506" alt="screen shot 2016-12-10 at 1 40 08 am" src="https://cloud.githubusercontent.com/assets/6560964/21058612/c2dc527a-be79-11e6-913f-64f2026d5a39.png">
You can find a working example [here](https://gist.github.com/aminmarashi/ccd7f1378b23142ea854f12dae7a1098)

**Comment by ekozhin** [comment]
Yes, that's it, thanks Amin! Now I only adjust value Threshold 👍

**Comment by aminmarashi** [comment]
No problem, I'll close this issue. 👍

**Comment by aminmarashi** [comment]
Example moved to [here](https://gist.github.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb)

**Comment by santostm** [comment]
Amin, how can I improve this strategy doing this:
when SMA 14 > SMA 21 the robot opens a transaction (purchase rise) for just 5 minutes. Afterwards, the robot waits to open a new order (purchase fall) only when SMA 14 < SMA 21 for just 5 minutes too. So, the robot should do this over and over again. Thanks!
