### ISSUE TITLE
Binary.bot update problems

### ISSUE THREAD

**Issue by wyu001** [binary-com/binary-bot#709]
@aminmarashi , 
Dear Amin , pls be informed that we found after binary.bot.com updated , its performance are 
not much better ( I may say - worse , sorry ) compare to prior update , and funny things that in new bot website ( after update ) , once we create bot and load some blocks into - the bot could run , but then 
after we save into xml for next use , we can't open it , it's necessary we re-build again from scratch.. so please kindly check to have it back run as previous performance at least.. Thanks a lot ..

cheers, 
wyu

**Comment by gokula-krishna-dev** [comment]
@wyu001 May I know which browser you use?

**Comment by wyu001** [comment]
@gokula-krishna-dev , Hi Krishna, thanks for quick response, sorry for my bad English but will tried to explained : 
1.  I am testing using - browsers : chrome ( this is most browser I've use ) , opera , mozilla 
we notice that some update has been done on binary.bot.com - generally the menu for each items for creating block are the same. just the fonts are more smaller , and whenever i clicked hold to move over the block on the webpage , the fonts are blur ..and when release click ..font back as normal ( never happen on previous webpage prior update ) 
2. Updating balance value - is very very slow
3. Loading xml files into the bot webpage , two different things happen : 
a. xml file that saved from previous ( before updated bot web ) it could be loaded and run normally , this is for xml file without any additional loaded block ( like added tools from www.github etc etc such fruitfella tools).. it could loaded normally , otherwise failed to load
b. the xml that we loaded into bot webpage , then we did some changes by added or removed some items then we save it , it's saved , but when we trying to re-loaded again that saved xml file , can not open, it means that we can not making any bot with this new update bot webpage to save it for next use , we have to make it again and again every time we want run bot with our strategy. 
4. Download menu - its in connection with point no. 3 above , the download menu are gone / missing in this new update bot webpage.  ( you may try it by click right on webpage on any block , duplicate , expand, delete , help .. all is there ..but donwload is gone ) .. 

some friends has been put questioning in Bahasa regarding this matter too - they facing same problems , and I may assume there is nothing wrong with the browser , it is the update that went wrong creating this problems , therefore , i may suggested on my previous message to put it back on same conditions prior update :) , if possible. 

anyway , appreciate to your kind support , hopefully would be back to normal soon. 

best regards, 
wyu

**Comment by gokula-krishna-dev** [comment]
Thanks for taking your time to explain the problems in detail. We are currently looking into it and will get back to you soonest.
