### ISSUE TITLE
Bug::function create it self after save and load bot.

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#717]
Please see VDO i save my bot and load it.
after load UporDow 2,3 created it  self.
https://youtu.be/Wrj14CbOsJ0
![image](https://user-images.githubusercontent.com/31925501/40403047-c6f2d3a8-5e81-11e8-81dc-f1e848a95fa4.png)

![image](https://user-images.githubusercontent.com/31925501/40403052-d1ec66a2-5e81-11e8-8f0c-f21e95a6c15d.png)

**Comment by apaajadehbos** [comment]
numerous complains on this issue, this is still unsolved problem. i don't know why @gokula-krishna-dev  keep asking we sent the xml ...
