### ISSUE TITLE
Opening contracts at round minutes

### ISSUE THREAD

**Issue by zdradozhi** [binary-com/binary-bot#753]
Hello guys, I searched everywhere but didn't find. I need my bot to open every next contract exactly at next round minute: 
01:00 - 02:00 - first trade
02:02 - 02:58 - pause
03:00 - 04:00 - next trade
04:02 - 05:02 pause
06:00 - 07:00 ...........

Can anyone help? Didn't understand how "SECONDS SINCE EPOCH" work at all!

OK, done, finally found it at Fruitfellas, thanks to him!

**Comment by baruga** [comment]
@zdradozhi UP UP UP

**Comment by saltanov82** [comment]
@zdradozhi Share the xml template. Thanks!

**Comment by zdradozhi** [comment]
Here is the block by Fruitfella

[FRUITFELLA_New_Candle_v2.zip](https://github.com/binary-com/binary-bot/files/2137370/FRUITFELLA_New_Candle_v2.zip)
