### ISSUE TITLE
1 minute candle

### ISSUE THREAD

**Issue by csajkas** [binary-com/binary-bot#765]
Hi friends,

I have a problem with my new idea.
How to code this function?

- if 1 minute candle is closed and close price is bigger than EMA line- ->create put 

I will check this option only when candle closed, not non stop. If closed price not bigger then wait to next candle closing... again check option and open position or wait again a minute,,,

Thank you

**Comment by baruga** [comment]
@csajkas how many EMA friends???

**Comment by csajkas** [comment]
@baruga  EMA 20 and EMA 150

**Comment by csajkas** [comment]
Any answer @baruga ?
