### ISSUE TITLE
help with this xml binary bot project!

### ISSUE THREAD

**Issue by ericcovich** [binary-com/binary-bot#782]
Hi i have tried to find way to put martingale in the project but I can't!

<xml xmlns="http://www.w3.org/1999/xhtml" collection="false">
  <variables>
    <variable type="" id="p$UV*qsWmSQ;AhIK/gw/">Expected Profit</variable>
    <variable type="" id="JwD:@g{9wy~Yb8U$g#D)">Win Amount</variable>
    <variable type="" id="S!#hMb2,90%Hx:6;^BjM">Initial Amount</variable>
    <variable type="" id=";^GNC#iVnS}8dmc}4M=0">Contract Type</variable>
  </variables>
  <block type="trade" id="73vWdDagX-YhN)CtN.3D" x="976" y="-89">
    <field name="MARKET_LIST">volidx</field>
    <field name="SUBMARKET_LIST">random_index</field>
    <field name="SYMBOL_LIST">R_75</field>
    <field name="TRADETYPECAT_LIST">callput</field>
    <field name="TRADETYPE_LIST">risefall</field>
    <field name="TYPE_LIST">both</field>
    <field name="CANDLEINTERVAL_LIST">60</field>
    <field name="TIME_MACHINE_ENABLED">FALSE</field>
    <field name="RESTARTONERROR">TRUE</field>
    <statement name="INITIALIZATION">
      <block type="variables_set" id="`m*jmnd~?(%PYRjyP:Ey">
        <field name="VAR" id="p$UV*qsWmSQ;AhIK/gw/" variabletype="">Expected Profit</field>
        <value name="VALUE">
          <block type="math_number" id="O!^gPI|s(#{)40]P!Ylr">
            <field name="NUM">100</field>
          </block>
        </value>
        <next>
          <block type="variables_set" id="HbI}]gP((Rooso*IH%@9">
            <field name="VAR" id="JwD:@g{9wy~Yb8U$g#D)" variabletype="">Win Amount</field>
            <value name="VALUE">
              <block type="math_number" id="d!*oox4NJx@*obQ)l6Q1">
                <field name="NUM">0.35</field>
              </block>
            </value>
            <next>
              <block type="variables_set" id="1`SW/Wbc=TR%r:/F`[{T">
                <field name="VAR" id="S!#hMb2,90%Hx:6;^BjM" variabletype="">Initial Amount</field>
                <value name="VALUE">
                  <block type="math_number" id="Zw$e.S13BwD1EB^FJMEv">
                    <field name="NUM">0.35</field>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="6v!@?*xZA~*U{SuB=T[N">
                    <field name="VAR" id=";^GNC#iVnS}8dmc}4M=0" variabletype="">Contract Type</field>
                    <value name="VALUE">
                      <block type="text" id="4^!Tx5_|Of5,0r})/9^d">
                        <field name="TEXT">Call</field>
                      </block>
                    </value>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
    <statement name="SUBMARKET">
      <block type="tradeOptions" id="P/$$`axlza/b`ekqm!^f">
        <field name="DURATIONTYPE_LIST">t</field>
        <field name="CURRENCY_LIST">USD</field>
        <value name="DURATION">
          <block type="math_number" id="0p-bjjEuB1k(LNWLaiS]">
            <field name="NUM">5</field>
          </block>
        </value>
        <value name="AMOUNT">
          <block type="variables_get" id="HMfSgJ`Iq-Z:Fz-}i+-{">
            <field name="VAR" id="S!#hMb2,90%Hx:6;^BjM" variabletype="">Initial Amount</field>
          </block>
        </value>
      </block>
    </statement>
  </block>
  <block type="before_purchase" id="tOc)]Xd=cAm0aiy+-8(8" x="-10" y="4">
    <statement name="BEFOREPURCHASE_STACK">
      <block type="controls_if" id="i^y1-),y7~|#4?F~nZ_|">
        <mutation else="1"></mutation>
        <value name="IF0">
          <block type="logic_compare" id="!WkMU~7t-BaX/6mu`-0^">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="variables_get" id="nFY.TxN+a_J`Np?^d:2c">
                <field name="VAR" id=";^GNC#iVnS}8dmc}4M=0" variabletype="">Contract Type</field>
              </block>
            </value>
            <value name="B">
              <block type="text" id="2,4_9}MD6ZJ9Io([N~c;">
                <field name="TEXT">Call</field>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO0">
          <block type="purchase" id="Q;`vp48|v7pG%t@W6`uQ">
            <field name="PURCHASE_LIST">CALL</field>
          </block>
        </statement>
        <statement name="ELSE">
          <block type="purchase" id="@5$RB6|F?Ws{|s)a6(3k">
            <field name="PURCHASE_LIST">PUT</field>
          </block>
        </statement>
      </block>
    </statement>
  </block>
  <block type="after_purchase" id="Vt,CkLeK8E?%BmnB`~M)" x="734" y="465">
    <statement name="AFTERPURCHASE_STACK">
      <block type="controls_if" id="fhx(fO!cb|asgk(ay{hB">
        <value name="IF0">
          <block type="contract_check_result" id="AnEQFO/5OWIoC#=IddTD">
            <field name="CHECK_RESULT">win</field>
          </block>
        </value>
        <statement name="DO0">
          <block type="variables_set" id="Tog#MhWdMy#vYmH~^x[m">
            <field name="VAR" id="S!#hMb2,90%Hx:6;^BjM" variabletype="">Initial Amount</field>
            <value name="VALUE">
              <block type="variables_get" id="=EewnE+LLDCBiY[OTw}*">
                <field name="VAR" id="JwD:@g{9wy~Yb8U$g#D)" variabletype="">Win Amount</field>
              </block>
            </value>

thanksssss

**Comment by ericcovich** [comment]
[needmartingale.txt](https://github.com/binary-com/binary-bot/files/2216649/needmartingale.txt)

**Comment by murali139** [comment]
i need set martingle level to 5 for digit match

**Comment by valentino242** [comment]
just add >set initial amount to win amount under result is win < 



hope it help

**Comment by murali139** [comment]
i want best digit match binary bot for lifetime. If its paid bot, i am ready to pay. please tell me where can i buy best digit match binary bot or if you can supply the best digit match binary bot i have to paid for that.
