### ISSUE TITLE
RSI value in BOT and in the Webtrader Chart not matching

### ISSUE THREAD

**Issue by gopibc** [binary-com/binary-bot#792]
Hello Team,

I was trying to implement RSI in one of my BOTs, however when I crosschecked - for the same settings the RSI values obtained for 1 minute candle in the BOT never matched with the RSI values I was seeing on the WebTrader Chart. However the close price of the candle and Bollinger Band values were accurate. Below is the attached screenshot of the same.
![rsi issue](https://user-images.githubusercontent.com/41890506/43381843-8cec5d08-93f3-11e8-9fd6-3837772a7b7b.jpg)
Later I tried creating a BOT that obtains Bollinger Band (12,2) upper and lower values, the Close values and RSI(3) values of the PREVIOUS Candle(since it is already closed and finalized unlike the running candle). The issue is seen there are well, Bollinger Band values and Candle Close values are accurate but RSI is not.
I guess the RSI calculation in the BOT is different from the RSI  calculation on the Webtrader Chart.
I would like to know how could I match them both and obtain the values as seen on the Webtrader Chart.
I have attached the BOT here for reference.
Thank you and awaiting response.

Regards,
Gopi B C

[Previous Candle Close-BB-RSI.zip](https://github.com/binary-com/binary-bot/files/2240005/Previous.Candle.Close-BB-RSI.zip)

**Comment by wijanarkokns** [comment]
The indicator value on the bot is more suitable on the tradingview chart. Could be how to calibrate it differently, to produce a value that is also different

**Comment by gopibc** [comment]
I agree, but my point of view is, if the Close Value of the candles are matching, on the BOT as well as the WebTrader, and Bollinger Band values derived out of Close Values are also matching both on BOT and WebTrader - why should not only RSI values match, as we know even that is calculated out of Close Values of the candles. If Close Values, which is a dataset for both BOT and Webtrader are common and matching, then RSI would not match only because the underlying calculations are different or coded differently. I just want to know how to either match them or correlate them to avoid errors in my analysis and implementation of the same when I am switching between manually trading and BOT.

**Comment by wijanarkokns** [comment]
https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsiif you can make rsi manually. there may be an answer there. and calibration more precisely or closer to the value of webtrader rsi can be found.

**Comment by gopibc** [comment]
In fact I have tried several RSI calculations by coding it manually in the BOT and also in excel file as well. But I am not getting to match WebTrader and BOT. I mainly need to understand how to fix RSI calculation within the BOT as it appears in Webtrader - if not by in-built RSI function at least by manually calculating then within the BOT.

**Comment by wijanarkokns** [comment]
![image](https://user-images.githubusercontent.com/32452523/43437564-ebbeef7e-94b3-11e8-8acc-17e6ce5968b9.png)

**Comment by wijanarkokns** [comment]
The value of RSI on webtrader can already be applied to the bot. You only need to use a close-down list of candles that have been cropped. If RSI period 3 = >> input list close from the end of the ( period + 1 ) to thelast end.

**Comment by wijanarkokns** [comment]
![whatsapp image 2018-07-31 at 11 19 31](https://user-images.githubusercontent.com/32452523/43437794-11a0a038-94b5-11e8-93bd-b50e7fea875f.jpeg)

**Comment by wijanarkokns** [comment]
![image](https://user-images.githubusercontent.com/32452523/43437933-b66a17ac-94b5-11e8-8932-00e03418ac69.png)
Use the RSI array, the value generated does not need to be re-calibrated. And crop the close list as pict.

**Comment by gopibc** [comment]
Awesome, thank you so much @wijanarkokns

**Comment by wijanarkokns** [comment]
![image](https://user-images.githubusercontent.com/32452523/43446758-e37d0948-94d3-11e8-9fd9-85f3a770e030.png)     
[rsi array webtrader.zip](https://github.com/binary-com/binary-bot/files/2244311/rsi.array.webtrader.zip) 

u'r wlcme .., @gopibc
