### ISSUE TITLE
How to disable notifies

### ISSUE THREAD

**Issue by muumitrollu** [binary-com/binary-bot#802]
Hello, 

does anyone know how to disable profit and loss notifies on the right corner? You know these green and yellow notifies.

![5a68b6234effc887eefbd63c7c066d6b](https://user-images.githubusercontent.com/42265100/43945545-0ed72ed4-9c8b-11e8-915c-5cc087219a0e.png)

**Comment by gokula-krishna-dev** [comment]
@muumitrollu as of now you cannot disable the notification.
