### ISSUE TITLE
Get Moving Average Value with Period

### ISSUE THREAD

**Issue by daviduck123** [binary-com/binary-bot#813]
I would like to try my logic with some Moving Average Indicator, but i have a trouble getting the value of current Moving Average Value.

![image](https://user-images.githubusercontent.com/6469921/44303137-2ef99b00-a363-11e8-8bcc-04477fa5aa64.png)
How to get value of Moving Average from this candle?

![image](https://user-images.githubusercontent.com/6469921/44303156-94e62280-a363-11e8-9065-f4183056c8dd.png)
Here is how I set it

**Comment by AlienFly** [comment]
![list](https://user-images.githubusercontent.com/36364199/44306635-ef9b7080-a39b-11e8-8078-960a70411449.png)

**Comment by daviduck123** [comment]
@AlienFly  Thank so much..
Going to continue my work now..
And do testing for 1 week first. Because it is slow bot but with such a long-time analysis
