### ISSUE TITLE
Want to check with you. how many of ram consumed by chrome or any browser when bot running.

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#816]
Want to check with you. how many of ram consumed by chrome or any browser when bot running.
![39762468_401901690214504_4459648651504910336_n](https://user-images.githubusercontent.com/31925501/44408687-74041400-a593-11e8-9e7b-97740e05e996.jpg)

My almost 800M only for chrome is open only bot and tradingview chart. 
My bot about 8100 lines in xml file.
some time hang.

**Comment by binary-ex-machina** [comment]
It depends of the strategy applied. If it runs calculation on every tick, it will consume a lot more. Also using alerts will consume more.

**Comment by nextnaro** [comment]
thanks , close ticket.
