### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by csajkas** [binary-com/binary-bot#830]
Hi friends,

I have a question: 

Bot have a condition when must open a trade. (Example indicator crossing) BUT if result is LOSS don't wait to next signal. Must next trade instantly open and this must repeat as long as he win. If result is WIN then start from first condition

How to create this option?

Thanks

**Comment by AlienFly** [comment]
![qw](https://user-images.githubusercontent.com/36364199/44959587-a4d03b80-aef9-11e8-9613-5a477b104592.png)

**Comment by csajkas** [comment]
Thank you @AlienFly  :1st_place_medal:
