### ISSUE TITLE
How to start trade on close candle

### ISSUE THREAD

**Issue by Rigoff** [binary-com/binary-bot#856]
I have a robot that works on timeframe 1 min. and сontracts are bought at the opening of a new candle. How to make so that contracts were bought at closing of a current candle or on 59 second? What are the blocks for this? What algorithm can you offer?

**Comment by AlienFly** [comment]
Закрытие текущей свечи и открытие новой - это один и тот же момент...
А вообще, стыдно должно быть, торгуя ботами на youtube не знать как открыть сделку в нужный момент времени. Представляю что там в коде ваших ботов твориться...

**Comment by Rigoff** [comment]
> я бы поспорил что это один и тот же момент, потому что когда я вхожу на открытии свечи, по правилам брокера первый тик в период начиная от 00 секунд считается входной котировкай, и иногда ее нет в этот период и тогда начало отсчета экспирации начинается с 02 или даже с 04 секунды, что не есть хорошо, потому что даже за 1 тик порой цена может пройти всю длину своего тела, а вот если бы я входил на 59 секунде, то тогда как раз первый тик в промежуток 59-00 сек был бы входной котировкой, и это бы как раз был бы истинный вход на начале свечи или на конце тут уже без разницы

**Comment by AlienFly** [comment]
Все эти проблемы решаются банально хорошей связью с сервером бинари. Найди нормальный ВПС с минимальным пингом и проблема исчезнет...

**Comment by Rigoff** [comment]
на индексах волатильности в минуте 30 тиков, то есть 1 тик в 2 секунды, пинг тут не при чем, мне нужно войти на 59 секунде, входная котировка была первым тиком открытия свечи, а не вторм, у индексов волатильности огромные гэпы, и мне нужно что бы входящая котировка совпадала с "Open" свечи, а все что выше было предложено, подразумевает время начала контракта и в таком случае входная котировка будет первым тиком уже на сформированной свече, и как я писал может улететь далеко от "Open" свечи. Если непонятно о чем я говорю открой аудит в меню анализа или истории счета, кнопка просмотр на любом индексе, и посмотри что такое время начала и что такое входящая котировка, между ними есть разница.

**Comment by binary-ex-machina** [comment]
to enter on the open tick of the candle you have to start the trade on the 58 seconds of the minute or the last minute of the candle.

If the candle time is 1min, you have to enter on 58 seconds. If the candle time is 5min you have to enter the trade at 4:58.

Here is an example using candle time 1min

![image](https://user-images.githubusercontent.com/34610787/45627167-b07a4100-ba67-11e8-8caf-c88c33d00302.png)

**Comment by Rigoff** [comment]
> to enter on the open tick of the candle you have to start the trade on the 58 seconds of the minute or the last minute of the candle.
> 
> If the candle time is 1min, you have to enter on 58 seconds. If the candle time is 5min you have to enter the trade at 4:58.
> 
> Here is an example using candle time 1min
> 
> ![image](https://user-images.githubusercontent.com/34610787/45627167-b07a4100-ba67-11e8-8caf-c88c33d00302.png)

thanks for the advice, I will check it...

**Comment by Rigoff** [comment]
Thank you all, everything turned out! Special thanks to "binary-ex-machina"!

**Comment by Rigoff** [comment]
The issue was solved

**Comment by mare69** [comment]
i need help width this......
how can i add this to my bot...before purchase?
![test55](https://user-images.githubusercontent.com/52427410/60765476-3751e600-a09b-11e9-8e6b-3b66b512f6f5.PNG)

**Comment by Rigoff** [comment]
> i need help width this......
> how can i add this to my bot...before purchase?
> ![test55](https://user-images.githubusercontent.com/52427410/60765476-3751e600-a09b-11e9-8e6b-3b66b512f6f5.PNG)

![Screenshot_26](https://user-images.githubusercontent.com/43293449/60766619-e18a3780-a0b4-11e9-9395-7c27999017ed.png)
![Screenshot_27](https://user-images.githubusercontent.com/43293449/60766620-e18a3780-a0b4-11e9-86d4-9b330c402a74.png)

**Comment by mare69** [comment]
pls help....is not working.....
i start bot 11:52:58 but firt trade made 11:53:05
Every second he jumped a second or two forward, and finished after 5 min with 6 sec of the difference between trades
![test56](https://user-images.githubusercontent.com/52427410/60766832-80139a00-a0af-11e9-86f8-d67dd1820eee.PNG)

**Comment by mare69** [comment]
not working....

**Comment by Rigoff** [comment]
> not working....

no problem, send me your bot and i edit bot and send you my email markrigoff@yahoo.com

**Comment by mare69** [comment]
**How to open trade at next candle?**
I solved part of the problem, but now it opens the trade every other minute, not the next minute....
eny idea?
![test58](https://user-images.githubusercontent.com/52427410/60773349-7700e800-a104-11e9-919a-8c7ad91521b1.PNG)

**Comment by mare69** [comment]
is still not solvet....eny idea whay not trade next candle?

**Comment by binary-ex-machina** [comment]
@mare69 use 54 seconds as duration

**Comment by Rigoff** [comment]
Yes 54-56 sec and soft for synchro tine server atomic see my screen here with and without Soft
![Screenshot_28](https://user-images.githubusercontent.com/43293449/60823898-42973580-a1b1-11e9-8043-b2c8a6c0606b.png)
![Screenshot_29](https://user-images.githubusercontent.com/43293449/60823899-432fcc00-a1b1-11e9-8ae8-61b595ec6389.png)

**Comment by Rigoff** [comment]
If your expiration (duration) need omly 5-10 ticks, see how my screen
![Screenshot_30](https://user-images.githubusercontent.com/43293449/60824231-e7b20e00-a1b1-11e9-9229-6f5d9e2c0a17.png)

**Comment by binary-ex-machina** [comment]
@Rigoff no need software to use 54 seconds, just set it on the block 1

**Comment by Rigoff** [comment]
> @Rigoff no need software to use 54 seconds, just set it on the block 1

yes, soft is not for use 54 sec open, but for synchro time PC with atomic time server

**Comment by binary-ex-machina** [comment]
and what is the atomic time server?
