### ISSUE TITLE
Make profit while you lose

### ISSUE THREAD

**Issue by folubebe** [binary-com/binary-bot#857]
As we all know, there is no method that guarantees 100% win but by research and tweaking bots from the renowned @binary-ex-machina, I give you a bot that makes profit even if you lose. Contact me if interested, serious buyers only tokskins@gmail.com.

![image](https://user-images.githubusercontent.com/40350449/45593999-a2a2be00-b98a-11e8-8359-33b5e7b0a069.png)

**Comment by binary-ex-machina** [comment]
@gokula-krishna-dev another one trying to sell things here
