### ISSUE TITLE
How can l make variables w x y z etc for this

### ISSUE THREAD

**Issue by Thabs5** [binary-com/binary-bot#858]
![image](https://user-images.githubusercontent.com/35899861/45596944-77d55b80-b9c4-11e8-842f-0bccc71f9c99.png)

**Comment by AlienFly** [comment]
![gg](https://user-images.githubusercontent.com/36364199/45599897-3a8cc000-b9fc-11e8-97ba-050349aad301.png)

**Comment by Thabs5** [comment]
[New Even and Odd.zip](https://github.com/binary-com/binary-bot/files/2388391/New.Even.and.Odd.zip)
Help me here l am stuck
