### ISSUE TITLE
Three candle strategy

### ISSUE THREAD

**Issue by janith119** [binary-com/binary-bot#88]
Amin I read alot about this blog on binary.com bot, and i faced a problem when i do this

I want to program a bot that checks for :two candle values in the same direction then the** third candle** should be of the same direction.
(ex:if there are two red candles then the third candle is also** red**)

This may seems simple but its difficult for me.I admire your help and hope to get an answer soon

**Comment by aminmarashi** [comment]
Thank you @janith119, you can find the blocks [here](https://gist.githubusercontent.com/aminmarashi/09d5aa04eef3bd372264da6044355805/raw/276cdf2a6afbeee42649773230e76610018744ef/3%2520same%2520candle%2520colors.xml).
<img width="844" alt="screen shot 2016-12-22 at 8 46 52 am" src="https://cloud.githubusercontent.com/assets/6560964/21411474/bd56bf9e-c823-11e6-8188-928805001061.png">

**Comment by wilsonsiena** [comment]
What is the best market?
