### ISSUE TITLE
can you please change this txt file to xml file 

### ISSUE THREAD

**Issue by thiliza** [binary-com/binary-bot#907]
[Over1.Under8.binary-bot.TXT](https://github.com/binary-com/binary-bot/files/2491800/Over1.Under8.binary-bot.TXT)

**Comment by buckman1974** [comment]
Just rename the .txt part to .xml and this should open as an XML file  :)

**Comment by sinung21** [comment]
[Over1.Under8.binary-bot.zip](https://github.com/binary-com/binary-bot/files/2492039/Over1.Under8.binary-bot.zip)

**Comment by thiliza** [comment]
thanks
