### ISSUE TITLE
Bagaimana cara Order Buy/Sell (Call/Put) Bersamaan menggunakan BOT (xml)??

### ISSUE THREAD

**Issue by bersemi888** [binary-com/binary-bot#943]
Bagaimana cara Order Buy/Sell (Call/Put) Bersamaan menggunakan BOT (xml)??

**Comment by sinung21** [comment]
buka 2 tab bro..jalankan bot bersamaan

**Comment by baruga** [comment]
@bersemi888 Nambahin mastere @sinung21 Buat acuan botnya agar bisa belinya secara bersamaan misal detik xx atau apalah gitu yang terpenting waktunya bersamaan untuk OPnya

**Comment by bersemi888** [comment]
Maksud saya bikin 1 bot xml bisa OP bersamaan bos ku... tapi kayaknya ga bisa ya? klo buka 2 tab lebih sdh bisa saya lakukan..

**Comment by baruga** [comment]
@sinung21 ada solusinya????

**Comment by baruga** [comment]
Apa ada yang bisa memecahkan masalhnya???

**Comment by bersemi888** [comment]
belom ada solusi
