### ISSUE TITLE
Martingale Level Limit and Reinitiating after First Level

### ISSUE THREAD

**Issue by Chaosallon** [binary-com/binary-bot#950]
Please help to modify this XML to limit martingale level ten and after that restart the stake price as the first level($0.35). Or if anyone has an advance martingale XML than I attached please share with me. I'm a new one for the forum.

Thanks 

[Martingale_Basic.txt](https://github.com/binary-com/binary-bot/files/2552934/Martingale_Basic.txt)

**Comment by baruga** [comment]
@Chaosallon U can use MM MPSU Ver 3

**Comment by Chaosallon** [comment]
@baruga Thanks for your support. I do a test run and will update you definitely.

**Comment by binary-ex-machina** [comment]
Very simple to do it. Change Max Steps to limit the times martingale will be applied.

![image](https://user-images.githubusercontent.com/34610787/48201175-91ea4500-e348-11e8-947c-17f7c6609e17.png)

**Comment by Chaosallon** [comment]
I had changed the bot you mentioned above. it's simple but I did not know how to setup it. thank you very much for your guidance. it gives good and bad result, but generally, it's quite good for the trade. 
I will update further and prefer to get help from professionals like you.

Thank You
