### ISSUE TITLE
Update the barrier values after each tick

### ISSUE THREAD

**Issue by bouhali00** [binary-com/binary-bot#987]
@binary-ex-machina
Hello,
I made a bot with two offset barriers.
the brobleme is that the block '' Define trade options '' does not refresh after each tick, and meanwhile it is possible that the direction is changed and does not correspond to the direction of trade !! Attached picture and BOT file
Is there way to update the barrier values after each tick.
greetings.

![barrier 1](https://user-images.githubusercontent.com/44878529/48971186-54570e80-f00e-11e8-93a1-ca7c201f775d.png)
![barrier 2](https://user-images.githubusercontent.com/44878529/48971189-5c16b300-f00e-11e8-8b4f-8f68463ad0d9.png)
[MACD TREND D B.xml.txt](https://github.com/binary-com/binary-bot/files/2612449/MACD.TREND.D.B.xml.txt)

**Comment by binary-ex-machina** [comment]
duplicate #944
