### ISSUE TITLE
can anyone crack this trial version binary indicator? 

### ISSUE THREAD

**Issue by ashrafulcg** [binary-com/binary-bot#991]
[AVSDA NEW.zip](https://github.com/binary-com/binary-bot/files/2613547/AVSDA.NEW.zip)

**Comment by murali139** [comment]
this indicator not work perfectly bro, i used paid norepaint
indicators also but no one gives better results

**Comment by binary-ex-machina** [comment]
this is not related with binary.com and the blocks site. Also github is not a cracking place.
