### ISSUE TITLE
Load Block From not working

### ISSUE THREAD

**Issue by Pelpa87** [binary-com/binary-bot#999]
@binary-ex-machina
Hi, I'm having some issue loading "blocks from" I have a function on an URL, but it doens't load anything. I've tried saving it as a collection, whenever I load it locally it works fine. But whe I use de "Load Block From" block, it doens't do anything.
I followed this post step by step, but nothing comes out
https://github.com/binary-com/binary-bot/issues/626

can you give me some advice? 
Thanks

**Comment by binary-ex-machina** [comment]
post the files here

**Comment by Pelpa87** [comment]
this is the file I want to be remoted. it just a variable setting
[remotepassword3.txt](https://github.com/binary-com/binary-bot/files/2620493/remotepassword3.txt)

**Comment by Pelpa87** [comment]
> post the files here
Here, it's an xml file that I want it to be remote. It's just a variable setting
[remotepassword3.txt](https://github.com/binary-com/binary-bot/files/2620539/remotepassword3.txt)

**Comment by Pelpa87** [comment]
@binary-ex-machina basically what I want is to set a password and I want it to be remote. that way you insert the password via a prompt message, and it checks if its the same as the one in the remote block..
or maybe is there any way to do that?

**Comment by binary-ex-machina** [comment]
In the past that was possible but now, when you load external blocks, they are added to the block canvas and can be explored and modified. 

You can't lock the code in any way today, since it will be very easy to just delete the blocks that make the password verification.

**Comment by Pelpa87** [comment]
@binary-ex-machina oh, ok. so is there any way I can protect my code against any editing or even running?

**Comment by binary-ex-machina** [comment]
you can just hide the blocks below one another in the canvas and this will prevent amateurs from checking the blocks. If it's a person with a minimal force of will that try to click on the things in the screen, they will remove the password very easily. You can't protect the code.

**Comment by Pelpa87** [comment]
> you can just hide the blocks below one another in the canvas and this will prevent amateurs from checking the blocks. If it's a person with a minimal force of will that try to click on the things in the screen, they will remove the password very easily. You can't protect the code.

Well, I was begining to think something like that...
Thank you very much man! you're very helpfull and always around!
thanks again for all your help!
